### ISSUE TITLE
API Store 의 도메인 변경

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#1001]
금일 API Store 측에서 문자발송 장애가 있었습니다.
관련한 메일을 받았습니다.

> Subject: [API스토어]대용량 SMS서비스 장애 관련
> 
> 보낸 사람: "API스토어" apistore.help@kt.com
> 제목: [API스토어]대용량 SMS서비스 장애 관련
> 날짜: 2016년 10월 28일 오후 3시 21분 32초 GMT+9
> 받는 사람: "이름없음" 10001if@theopencloset.net
> 
> 안녕하세요 API스토어 입니다.
> 
> 금일 서비스 장애 관련 하여 수정 확인 하였는데 개발적인 이슈가 있어 전달 드립니다.
> 
> 기존 호출 하시는 URL이 문제가 있어, 해당 도메인을 바꿔야 하는 이슈가 발생 하였습니다.
> 
> 기존: http://api.openapi.io/ppurio/1/message/SMS
> 
> 수정: http://api.apistore.co.kr/ppurio/1/message/SMS
> 
> 위 내용으로 수정하여 API 호출 하시면 문제 없이 발송이 가능하니 확인 부탁드립니다.
> 
> 감사 합니다.

변경해서 적용시켜야 합니다.

https://github.com/keedi/SMS-Send-KR-APIStore/pull/1

에 PR 을 했습니다. 새로 배포한뒤에 서버에 적용시켜야 합니다.

현재 서비스 상태와 언제까지 반영해야 하는건지 문의했습니다만 아직 답이 없습니다.

**Comment by keedi** [comment]
늦었지만 [0.002 버전](https://metacpan.org/release/KEEDI/SMS-Send-KR-APIStore-0.002) 릴리스 완료했습니다.

**Comment by keedi** [comment]
해당 모듈 저장소에 등록 되었으므로 본 이슈는 닫습니다.
