### ISSUE TITLE
대여 후 안내 문자가 전송되지 않음

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#1002]
시스템상에서 확인한 것은 아닙니다.
오늘오전부터 대여후 3건의 안내문자메세지가 전달되지 않는다고 합니다.

다른 문자메세지는 보내진다고 합니다.

확인해봐야 알 수 있습니다.

**Comment by aanoaa** [comment]
#1001 과 관련이 있을 수 있습니다.
`sending` 상태인 sms 가 1000 건이 넘습니다.

**Comment by aanoaa** [comment]
API Store 에서 성공할때도 있고 실패할때도 있고 그런게 아닌가 싶습니다.

**Comment by aanoaa** [comment]
https://github.com/aanoaa/SMS-Send-KR-APIStore/blob/develop/lib/SMS/Send/KR/APIStore.pm

임시로 패치된 파일을 사용해서 `opencloset.sms` 를 기동했습니다.

몇건 모니터링 하고 있는데 sms 가 전송되고 있습니다.

**Comment by aanoaa** [comment]
`sending` 상태의 메세지를 확인해보니, 다양합니다.
대여후 문자 뿐만 아니라 인증번호, 미납메세지 등등 전송 안된 것이 많습니다.

패치전까지도 계속 발생하였습니다.

**Comment by aanoaa** [comment]
`2016-10-28 08:35:17` 메세지가 `sending` 상태인 마지막 메세지 입니다.
`+09:00` 해주어야 현지시각입니다.

**Comment by yongbin** [comment]
어제 오후에 @10001if 님께 이야기를 듣고 1차 확인했을때도 간헐적으로 전송이 되다 안되다 하던 상황이었습니다. 기존 .io 도메인에서 .co.kr 도메인으로 변경을 유도하고 있는데 아마도 도메인 연장이나 DNS 관리에 문제가 있었던것 같습니다. 아래는 현시점 두 도메인의 DNS 질의 결과 입니다.

# api.openapi.io (변경전)

> ; <<>> DiG 9.8.3-P1 <<>> api.openapi.io
> ;; global options: +cmd
> ;; Got answer:
> ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 46976
> ;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 2, ADDITIONAL: 2
> 
> ;; QUESTION SECTION:
> ;api.openapi.io.			IN	A
> 
> ;; ANSWER SECTION:
> api.openapi.io.		60	IN	A	210.114.20.92
> 
> ;; AUTHORITY SECTION:
> openapi.io.		60	IN	NS	ns2.paran.com.
> openapi.io.		60	IN	NS	ns1.paran.com.
> 
> ;; ADDITIONAL SECTION:
> ns1.paran.com.		36115	IN	A	211.45.150.64
> ns2.paran.com.		137975	IN	A	211.45.151.64
> 
> ;; Query time: 171 msec
> ;; SERVER: 192.168.10.254#53(192.168.10.254)
> ;; WHEN: Sat Oct 29 18:45:35 2016
> ;; MSG SIZE  rcvd: 125

# api.apistore.co.kr (변경후)

> ; <<>> DiG 9.8.3-P1 <<>> api.apistore.co.kr
> ;; global options: +cmd
> ;; Got answer:
> ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 49811
> ;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 2, ADDITIONAL: 2
> 
> ;; QUESTION SECTION:
> ;api.apistore.co.kr.		IN	A
> 
> ;; ANSWER SECTION:
> api.apistore.co.kr.	60	IN	A	210.114.20.92
> 
> ;; AUTHORITY SECTION:
> apistore.co.kr.		60	IN	NS	ns2.paran.com.
> apistore.co.kr.		60	IN	NS	ns1.paran.com.
> 
> ;; ADDITIONAL SECTION:
> ns1.paran.com.		51553	IN	A	211.45.150.64
> ns2.paran.com.		51553	IN	A	211.45.151.64
> 
> ;; Query time: 73 msec
> ;; SERVER: 192.168.10.254#53(192.168.10.254)
> ;; WHEN: Sat Oct 29 18:46:00 2016
> ;; MSG SIZE  rcvd: 129

**Comment by aanoaa** [comment]
패치 전에 1300여건이었고, 3일이 지난 오늘도 1300여건입니다.
패치 이후에 발송 실패건수가 늘어나지 않았습니다.

**Comment by keedi** [comment]
늦었지만 [SMS::Send::KR::APIStore 0.002 버전](https://metacpan.org/release/KEEDI/SMS-Send-KR-APIStore-0.002) 릴리스 완료했습니다.

**Comment by keedi** [comment]
keedi/SMS-Send-KR-APIStore#1

**Comment by keedi** [comment]
해당 모듈 수정 적용 이후 이슈가 발생하지 않고 있습니다. 저장소의 필요 모듈 버전을 명시한 커밋을 추가했습니다. 완료된 작업이므로 이슈 닫습니다.

서버에는 이미 배포된 상태입니다.
