### ISSUE TITLE
로그인한 관리자가 주문서의 기본 담당자가 되도록 함

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#1003]
주문서를 대여할때 담당자를 지정할 수 있는데, 로그인한 사용자가 자동으로 선택되도록 해야합니다.

**Comment by keedi** [comment]
제가 진행합니다.

**Comment by keedi** [comment]
이 이슈의 경우 문제가 발생할 소지가 있습니다.

일단 로그인한 사용자가 주문서의 기본 담당자가 되도록 한다고 하는데 어느 시점에 선택할지가 모호합니다. 서버 입장에서는 여러 사람이 로그인해있는데 과연 어떤 사용자를 기준으로 기본 담당자를 설정할 것인가를 판단하기 어렵습니다.

다만, 문맥을 고려했을 때, 포장완료에서 결제대기로 넘어가는 시점 특정 주문서를 결제대기로 넘긴 관리자의 계정으로 담당자를 설정 했으면 좋겠다는 것으로 보입니다. 역시 문제의 소지는 있지만, 원하는 기능으로 보이니 일단 구현하도록 합니다.

현재는 서버측에서 결제 대기로 넘어간 주문서를 최초 열람할 시점에 필요한 정보 몇가지를 설정해주는데 이 부분에서 처리해도 되나 이 경우 꼭 결제를 진행할 담당자가 아니라도 동시에 열람할 경우 담당자가 변경되거나 엉뚱한 관리자가 담당자가 될 가능성이 있으므로 적절하지 않습니다.

현재 결제 대기로 넘기는 절차 화면은 다음과 같습니다.

![screenshot-monster silex kr 10301 2016-11-11 16-38-00](https://cloud.githubusercontent.com/assets/138451/20207810/483648b2-a82d-11e6-8c7e-a111f758443f.png)

상기 화면에서 결제 대기 버튼을 눌러 포장 완료 상태 주문서를 결제 대기로 만들며, 이때 이 버튼을 누른 사람이 최종 결제 절차를 진행하고 있습니다. 즉 해당 버튼을 누른 시점에 처리해야 할 것 같습니다. 해당 부분은 클라이언트에서 ajax를 통해 처리하고 있으므로 주문서의 상태를 바꿀때 담당자도 같이 변경하도록 하겠습니다.

**Comment by keedi** [comment]
작업 완료했으므로 이슈 닫습니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
