### ISSUE TITLE
의류의 기증행위 변경이 아니됨

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#1004]
기증목록 내에서 2588 의 의류를 2818 로 옮길 수 없음
2818은 donation.theopencloset.net 을 통해서 등록된 의류라고 합니다.

**Comment by aanoaa** [comment]
단순히 javascript 오류였습니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
