### ISSUE TITLE
40458 주문서가 미납목록에 나타나지 않음

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#1005]
완납처리할 방법이 없음

**Comment by 10001if** [comment]
주문서 번호 41545도 같은 상황입니다. 왜 - 표시가 되는지 이유가 궁금합니다.

**Comment by aanoaa** [comment]
해당 주문서는 완납/불납이 아닌 연체/연장료에 대한 에누리가 되어 있습니다.
연체조건을 만족하는 주문서가 아닙니다.

하지만 완납/불납 버튼을 누르지 않아서 `미납` 이라는 타이틀이 따라 다니고 있습니다.

처리방식이 잘못되었다기 보다는 고려치 못한 상황인 것 같습니다.

**Comment by aanoaa** [comment]
추측해보건데,

- 반납예정일 이후에 반납
- 이때에 최종 연체/연장비 에 대해서 `전체에누리` 버튼을 누름(전체에누리는 뭔지 기억이 안남)

이 아닌가 합니다.

전체에누리 버튼을 눌렀다면 `미납` 이라는 타이틀이 붙어서는 아니됩니다.

우선 위 시나리오를 재현해보도록 하겠습니다.

**Comment by aanoaa** [comment]
재현을 위해 테스트를 해보았습니다.

- 연체된 주문서에 대해 반납절차를 진행
- 의류를 선택하고 `전체반납` 버튼을 누름
- `미납금`을 받지 않으면 더이상 진행할 수 없음
- `최종 연체/연장료`를 `미납`으로 선택하고, `전체에누리` 버튼을 누름
- `전체반납` 버튼을 클릭

`미납`주문서로 되지만 연체 주문서에는 해당되지 않음(재현됨)

**Comment by aanoaa** [comment]
연체료에 대해 전체에누리를 했다면 `미납`이 아님에도 최종 연체/연장료 를 `미납`으로 선택했습니다.
(에누리 해주었기 때문에 미납금이 없습니다)

의미상으로 잘못되지 않았나 싶습니다.

현재 15개의 주문서가 이런 상태 입니다.

``` sql
SELECT `me`.`id`, SUM( `order_details`.`final_price` ) AS `sum_final_price` FROM `order` `me` LEFT JOIN `order_detail` `order_details` ON `order_details`.`order_id` = `me`.`id` WHERE ( ( `me`.`status_id` = 9 AND `order_details`.`stage` > 0 AND ( `me`.`late_fee_pay_with` = '미납' OR `me`.`compensation_pay_with` = '미납' ) ) ) GROUP BY `me`.`id` HAVING `sum_final_price` = 0 ORDER BY `return_date`;
```

```
+-------+-----------------+
| id    | sum_final_price |
+-------+-----------------+
| 11469 |               0 |
| 11816 |               0 |
| 13505 |               0 |
| 14355 |               0 |
| 13887 |               0 |
| 14715 |               0 |
| 15256 |               0 |
| 16431 |               0 |
| 29939 |               0 |
| 35329 |               0 |
| 34934 |               0 |
| 37409 |               0 |
| 37273 |               0 |
| 38230 |               0 |
| 40458 |               0 |
+-------+-----------------+
```

위 15개의 주문서에 대해서 `미납` 타이틀을 제거하고(데이터를 수정해서),
전체에누리를 눌렀을때에 `미납` 으로 선택할 수 없도록 하겠습니다.

**Comment by aanoaa** [comment]
```sql
UPDATE `order` SET late_fee_pay_with = '', compensation_pay_with = '' WHERE id in (11469,11816,13505,14355,13887,14715,15256,16431,29939,35329,34934,37409,37273,38230,40458,39849);
```

미납 타이틀을 떼기 위해서 위 쿼리를 실행시켰습니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
