### ISSUE TITLE
자켓 사진의 일괄등록

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#1006]
https://github.com/opencloset/OpenCloset-Avatar-Web/issues/4

에 관련된 이력이 있습니다.

사진을 등록할 수 있는 기능이 있지만, 의류가 많다보니 하나하나씩 등록하기가 어려워서 일괄
등록을 요청하셨습니다.

https://docs.google.com/spreadsheets/d/1Z-pImKVCQfPJUliuGKF03PgXW-6B-82JG2zUQaDnjA4/edit?ts=578dca8c#gid=0

이 파일을 참고해서 일괄등록해야 하는데, usb 로 전달받은 사진과 갯수에서 차이가 있습니다.
사진파일은 868 개인데, 파일의 의류태그는 842 개 입니다.

**Comment by aanoaa** [comment]
@10001if help

**Comment by aanoaa** [comment]
사진이 등록된 의류에는 `사진촬영` 태그가 붙어야 합니다.

**Comment by aanoaa** [comment]
> 이 파일을 참고해서 일괄등록해야 하는데, usb 로 전달받은 사진과 갯수에서 차이가 있습니다.
사진파일은 868 개인데, 파일의 의류태그는 842 개 입니다.

사진에 비해 의류태그가 부족한게 문제입니다.
갯수도 맞지 않으니까 이 사진이 맞는가 하는 것 역시 문제입니다.

cc @10001if

**Comment by 10001if** [comment]
@aanoaa 최종적으로 의류 숫자와 사진 숫자가 맞는 데이터를 전달해 드렸습니다. 이후에는 직접 의류 사진을 찍어 업로드 하도록 하겠습니다. 그 외 의류에 대해서는 이미지가 아직 올라가지 않았다는 일러스트 이미지를 올리려고 합니다. 여쭤보고 진행하도록 하겠습니다. 이 이슈가 필요하지 않다면 닫아주셔도 될 것 같습니다.

**Comment by aanoaa** [comment]
의류코드파일과 사진 갯수에 차이가 있습니다.

    $ ll *.JPG | wc -l
    1133

https://docs.google.com/spreadsheets/d/1Z-pImKVCQfPJUliuGKF03PgXW-6B-82JG2zUQaDnjA4/edit?ts=578dca8c#gid=0

에서는 의류코드가 842개 밖에 없습니다.

**Comment by aanoaa** [comment]
@10001if 사진을 몇번 받았는데 계속 작업하지 못하고 있는 이유가 매번 같습니다.
의류코드가 담긴 파일을 같이 전달해주세요.

**Comment by aanoaa** [comment]
새로운 문서를 사용중입니다.
https://docs.google.com/spreadsheets/d/1bKa3XFxSk8tZubfx6dzyigM9_fPlzMhZwKXk8kJQxfI/edit?ts=586201f6#gid=0

**Comment by aanoaa** [comment]
- [ ] 이미 등록되어 있는 의류사진을 삭제
  - default 이미지는 제외
- [ ] 썸네일삭제
- [ ] 의류사진 업로드
- [ ] 의류태그 등록

**Comment by aanoaa** [comment]
```
> use opencloset-avatar;
> DELETE FROM avatar;

<OPENCLOSET-AVATAR-HOME>$ rm -rf public/thumbnails/
```

**Comment by aanoaa** [comment]
지난 작업이력을 살펴보니 의류태그는 이번에 등록되는 사진이 아니라 사진이 등록된지 않은 자켓에 대해서 `사진촬영` 태그를 붙입니다.

cc @10001if

**Comment by aanoaa** [comment]
의류태그는 필요없다고 합니다.

**Comment by aanoaa** [comment]
이번에 등록된 의류사진 용량의 합이 3.3G 정도 됩니다.
서버의 디스크사용률이 높아서 업로드 하는게 부담스럽습니다.

cc @yongbin

**Comment by aanoaa** [comment]
사진을 준비하고 아래 스크립트를 실행시키면 사진이 업로드 됩니다.

``` perl
use strict;
use warnings;
use HTTP::Tiny;
use HTTP::Tiny::Multipart;
use Path::Tiny;

our $TOKEN = 's3cr3t';
our $URL   = 'https://avatar.theopencloset.net/avatar/';

my $http = HTTP::Tiny->new;
my @top;
while ( my $row = <DATA> ) {
    chomp $row;
    my ( $top, $bottom ) = split /,/, $row;
    if ( $top =~ m/^j/i ) {
        $top = uc $top;
        push @top, $top;
    }
    else {
        warn "Wrong clothes code: $top\n";
    }
}

print "clothes code: ", scalar @top, "\n";
print "Start uploading ...\n";

my $dir = path('imgs/');
my $cnt = 0;
for my $img ( $dir->children(qr/\.JPG$/) ) {
    my $top = shift @top;
    die "Empty clothes code\n" unless $top;

    my $res = $http->post_multipart(
        $URL,
        {
            key   => $top,
            token => $TOKEN,
            img   => {
                filename => "$img",
                content  => $img->slurp,
            }
        }
    );

    die "$img: $res->{reason}\n" unless $res->{success};
    $cnt++;
}

print "Uploaded $cnt images successfully\n";

__DATA__
J038,P04F,
....,....,
```

**Comment by aanoaa** [comment]
@10001if 의류코드 문서에서 32번째줄의 `J1E5` 가 이상합니다.
보기에는 한줄 개행이지만 프로그램을 사용해서 업로드할때에 순서가 어긋나 버리면 그 답안지 밀려쓴 것 처럼 되어버리거든요.

수정해주세요.

**Comment by 10001if** [comment]
@aanoaa 감사합니다. 수정 완료하였습니다!

**Comment by keedi** [comment]
소스 코드 상의 url 주소 제거했습니다.

@10001if 구글 닥스 링크는 공개되도 상관없는 것인지 확인하시구요. 상관없으면 상관없습니다.

**Comment by aanoaa** [comment]
```
$ perl a.pl 
clothes code: 1133
Start uploading ...
Uploaded 1133 images successfully
```

**Comment by aanoaa** [comment]
https://avatar.theopencloset.net/avatar/bb1c86cec01f61b871d2f84f88ddf17e?s=200

예로 하나만 링크합니다.
J1L5 의 사진입니다.

**Comment by aanoaa** [comment]
앞으로 추가되는 의류는 재고관리 프로그램을 이용하거나 의류등록시에 사진을 첨부해서 등록할 수 있습니다.

**Comment by 10001if** [comment]
@aanoaa 네~ 링크가 오픈된 것이 아니라 괜찮습니다.

**Comment by aanoaa** [comment]
사진이 잘못 등록되었습니다.
등록된 모든 사진을 삭제하고 다시 등록해야 합니다.

자켓사진은 직접 전달받았습니다.

**Comment by aanoaa** [comment]
https://github.com/opencloset/opencloset/issues/1006#issuecomment-269279426

참고해서 DB 와 썸네일파일을 삭제하였습니다.

**Comment by aanoaa** [comment]
```
$ perl a.pl 
clothes code: 1133
Start uploading ...
img/_MG_0271.JPG: Bad Gateway
```

업로드 중에 오류가 발생하였습니다.
첨부터 다시 하거나 스크립트를 수정해야 합니다.

**Comment by aanoaa** [comment]
`J038` 가 1번인데 의류사진이 다릅니다.

스크립트의 의류사진 순서를 파일명으로 정렬하지 않아서 생기는 문제입니다.

다시 등록해야 합니다.

**Comment by aanoaa** [comment]
위 업로드 스크립트도 파일명 정렬하도록 수정하였습니다.

**Comment by aanoaa** [comment]
1133 여장의 사진이 업로드 되었습니다.

    $ perl a.pl 
    clothes code: 1133
    Start uploading ...
    Uploaded 1133 images successfully

**Comment by aanoaa** [comment]
이거 또 다 지워달라고..

**Comment by aanoaa** [comment]
일괄등록은 이제 안할것이기 때문에 삭제만 하면 될 것 같습니다.

**Comment by aanoaa** [comment]
mysql> DELETE FROM avatar WHERE id != 1;
    Query OK, 1222 rows affected (0.40 sec)

1133 개를 업로드 했었는데 1222 개가 삭제되었습니다.
따로 업로드한 파일도 지워졌습니다.

**Comment by 10001if** [comment]
@aanoaa 감사합니다. ^^
