### ISSUE TITLE
대여자의 성별을 바꾸면 해당 대여자의 현재 예약 정보 중 성별도 같이 변경하도록 함

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#1011]
10:30 대여자를 남자 -> 여자로 변경하고 새로고침하면 대여자 이름이 나타나지 않습니다.
예약인원이 꽉차지 않은 시간대로 선택해도 나타나지 않습니다.

**Comment by keedi** [comment]
대여자 성별만 변경해서는 안될텐데요. 해당 주문서의 `booking` 항목 역시 바뀐 성별에 맞게 바꾸어야 합니다. 정확히 말하면 해당 주문서의 `booking`의 `gender` 값을 바꾸는게 아니라 주문서 안의 `booking_id`를 해당 성별에 맞는 적절한 `booking`의 `id`를 찾아 변경해주어야 합니다.

**Comment by keedi** [comment]
@10001if 하나 궁금한 것이 성별을 바꾸어야 할 경우가 있나요? 있다면 어떤 상황이었는지요?

**Comment by keedi** [comment]
예약 페이지나 시간표 페이지나 비슷할 것으로 보입니다.

**Comment by keedi** [comment]
@10001if 피드백 받은 뒤 처리하겠습니다. 확인 부탁드려요~

**Comment by 10001if** [comment]
@keedi 성별을 바꾸어야 하는 경우는 실수로 입력을 잘못하거나 예약자와 이용자가 다른 경우입니다. 예약자(아내)가 이용자(남편) 대신 예약 했을 경우 성별은 여성으로 뜨게 되는데, 여성으로 뜨게 되면 모니터 화면에서 여성에게만 보이는 치수가 뜨기 대문에 옷을 골라드릴 수가 없는 상황이 발생합니다.

**Comment by keedi** [comment]
흐음. 실수로 입력을 잘못한 경우든 대리이든 그렇다면 예약 정보를 바꾸어야 하는데, 현재 남성 슬롯과 여성 슬롯이 다릅니다. 예를 들어 현재 10:00시 슬롯이 각각 4명이고 이미 4명, 4명 꽉 찬 상태라 하더라도 남성 10:00 예약을 여성 10:00 예약으로 바꾸어서 3명/5명이 되는 기능이 필요한 것인가요?

**Comment by keedi** [comment]
확인하니 예약 페이지와 시간표 페이지는 구현 방식이 미세하게 다릅니다. 시간표에서는 열린옷장이 원하는 방식으로 표현되고 예약 페이지에서는 그렇지 않습니다. 하지만 역설적으로 시간표에서 보이는 연유는 상호 체크를 덜해서 마치 그런 것처럼 보이는 것일 뿐 오히려 잘못 보이는(버그에 가까운) 것에 가깝습니다.

**Comment by keedi** [comment]
어쨌든 예를 들어 화요일 15:00시각에 남자 슬롯이 5명 여자 슬롯이 5명이고 예약이 꽉 찬 상태라고 가정합니다. 이때 홍길동이라는 남성 예약자의 성별을 홍길동의 사용자 정보에서 변경할 경우 열린옷장이 원하는 시나리오는 다음과 같습니다.

- 홍길동의 사용자 정보의 성별이 여성으로 변경
- 홍길동의 주문서는 주문서 자체는 현재로선 전혀 성별이 없기 때문에 변경할 부분은 없음
- 홍길동의 현재 시점 예약 정보는 성별 값이 존재하므로 15:00 남성 성별을 바라보고 있는 것을 15:00 여성 성별을 바라보도록 수정
- 이때 예약 상태는 남 4/5가 되고 여 6/5가 됨
- 남성 슬롯이 하나가 비어 추가 예약 가능하게 되는 것은 감안한다고 함
- 여성 슬롯이 하나가 추가되어 예약 인원 숫자 오버가 되는 것은 감안한다고 함
- 현 시점 예약 말고 이전 예약의 경우 성별 정보를 변경하지 않는다고 함

**Comment by 10001if** [comment]
@keedi 이 이슈는 실수보다는 대리 대여 이슈가 대부분이었습니다. #1066 로 대리 대여 이슈를 해결하려고 하므로 본 이슈는 닫도록 하겠습니다. 예약페이지에 보이지 않는 문제는 열린옷장 운영상에서는 큰 문제가 없기 때문입니다. 이슈가 필요한 경우 다시 열도록 하겠습니다.
