### ISSUE TITLE
봉사활동 목록의 검색 기능 강화

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#1012]
현재는 

- 상태별
- 이름 or 전화번호 or 이메일 `(1)`

검색이 가능합니다.

- 봉사활동일로 검색가능
- `(1)` 의 검색결과 + 상태별 검색
- `(1)` 의 검색결과 + 활동일 검색

이 필요합니다.

활동일과 사용자 그리고 상태의 and 검색이 필요합니다.

**Comment by 10001if** [comment]
본 기능이 꼭 필요하지 않다고 판단합니다. 이슈 닫고 검색에 관련해서 꼭 필요한 내용이 발생하면 다시 열도록 하겠습니다.
