### ISSUE TITLE
정장 반납 안내지의 반납 문구 및 형식 수정

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1013]
현재 반납 00월 00일(0) 형식입니다.

이를 
1. 반납 00월 00일(0)의 글 아래에 언더바 ___________ 가 붙어야 합니다.
2. 본 멘트 아래 폰트크기 "9"로 *택배반납은 반납일 1일전 발송 이라는 멘트가 삽입되어야 합니다.

**Comment by keedi** [comment]
#958 릴리스 이후 피드백입니다.

**Comment by keedi** [comment]
pdfmake 문서에는 없지만 소스를 확인해보니 글자를 꾸밀 수 있는 옵션이 있었습니다. 해당 옵션은 다음과 같습니다.

- decoration: underline, overline, lineThrough
- decorationStyle: solid, dashed, dotted, double, wavy
- decorationColor
- background

**Comment by keedi** [comment]
상기 옵션을 이용해서 반납 일자 문자열의 형식을 조정했습니다.

```javascript
        orderTargetDate: {
          margin: [ 55, 8, 0, 0 ],
          font: "D2Coding",
          fontSize: 14,
          decoration: "underline",
          decorationStyle: "wavy",
          decorationColor: "red",
          background: "#eeffaa"
        },
```

실제로 pdf로 보이는 모습은 다음과 같습니다.

![screenshot- domain date time](https://cloud.githubusercontent.com/assets/138451/20206834/891e6758-a826-11e6-8377-3bc9675ca4ad.png)

**Comment by keedi** [comment]
배경색을 넣어달라는 요청은 없었으나 목적 자체가 강조를 원하는 것이니 토너를 좀 사용한다손 치더라도 형광 노란색(또는 녹색)으로 배경을 넣고 밑줄은 빨간색으로 더불어 밑줄 형식은 직선이 아닌 물결선을 넣었습니다.

**Comment by keedi** [comment]
작업 완료했으므로 이슈 닫습니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
