### ISSUE TITLE
주문서가 포장 완료 상태일 때 정장 반납 안내지를 출력

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1014]
결제대기 상태에서 출력을 할 수 있으나, 이런 경우에는 이미 대여자가 결제를 인지한 상태입니다.
출력 시간이 대여자가 결제대로 방문하는 시간보다 긴 것으로 확인되므로 포장완료 상태에서 출력을 하고자 합니다.
이때, 반납일은 결정되지 않았으므로, 3박 4일 기준으로 반납일을 확정하도록 합니다.

**Comment by keedi** [comment]
#958 릴리스 이후 피드백입니다.

**Comment by keedi** [comment]
진행합니다.

**Comment by keedi** [comment]
열린옷장 측의 요구 사항은 우선 포장 완료 주문서 목록을 보는 화면에서 비고란에 정장 반납 안내지를 출력할 수 있는 버튼을 추가해주길 바라고 있습니다.

![screenshot-monster silex kr 10301 2016-11-11 19-16-11](https://cloud.githubusercontent.com/assets/138451/20211769/617378ac-a843-11e6-970d-f07c2b7aaf1c.png)

**Comment by keedi** [comment]
정장 반납 안내지를 제대로 출력하려면 주문서 정보중 `order.rental_date`와 `order.target_date` 값이 제대로 저장되어 있어야 합니다. 해당 값은 결제대기 주문서에 들어가서 화면을 띄우면 그때 동적으로 값을 설정합니다. 따라서 포장 완료 주문서 목록을 보는 시점에는 정확한 날짜 값이 설정되지 않은 상태입니다.

**Comment by keedi** [comment]
문제를 해결하는 방법 중 하나로 대여일과 반납일을 어딘가에서 저장하는 지점을 만들고 해당 지점에서 적절한 값을 설정하는 방법이 있습니다. 관련해서 신체 치수 측정이라던가 또는 예약 시점이라던가를 제안해보았지만 내부적으로 어렵다고 합니다. 더불어 대부분의 경우 3박 4일이기 때문에 틀리면 수정하는 손 치더라도 강제로 대여일은 오늘 날짜가, 반납일은 3박 4일에 해당하는 날짜가 출력되면 좋겠다고 합니다.

**Comment by keedi** [comment]
또 다른 방법으로 포장 완료에서 결제 대기로 변경하는 버튼을 누르는 시점에 자동 계산 후(물론 이 계산은 정확하지 않습니다. 왜냐하면 최종 결제가 된 것이 아니기 때문입니다) 주문서에 대여일과 반납일을 저장하는 방법입니다. 하지만 이렇게 되면 기존 주문서 열람 페이지에서 자동 계산 하는 코드가 이미 충분히 복잡해 완벽하게 적용하기도 어렵고 적용한다 하더라도 사실 진짜 대여일과 반납일이 아니기 때문에 무의미합니다. 심지어 이 경우 현재 결제 취소가 일어날 경우 대여일이 존재하게 되는데 현재 실제로 이 주문서가 대여가 되었는지 여부를 대여일로 확인하는 경우가 많기 때문에 이렇게 수정할 경우 부작용이 클 것으로 사료됩니다.

**Comment by keedi** [comment]
따라서 이렇게 문제를 해결하는 대신 pdf를 출력하는 컨트롤러에서 대여일과 반납일이 존재하지 않는 경우 강제로 대여일은 오늘, 반납일은 3박 4일 후 날짜로 간주하고 pdf 를 생성하는 방법을 사용하려고 합니다. 이 경우 실제 데이터베이스를 건드리지 않기 때문에 부작용이 가장 적을 것으로 사료됩니다.

**Comment by keedi** [comment]
구현 완료한 화면은 다음과 같습니다.

![screenshot-monster silex kr 10301 2016-11-11 20-39-25](https://cloud.githubusercontent.com/assets/138451/20214068/315f4e64-a84f-11e6-85e8-c792c0b92944.png)

**Comment by keedi** [comment]
작업 완료했으므로 이슈 닫습니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
