### ISSUE TITLE
정장 반납 안내지의 반납일이 3박 4일이 아닌 4박 5일로 보임

### ISSUE THREAD

**Issue by keedi** [opencloset/opencloset#1020]
실제 예정 반납일이 3박 4일 기준으로 표시되어야 하는데 출력용 PDF에서는 4박 5일 기준으로 표시가 된다고 합니다. 예를 들어 11월 12일 토요일 대여일 경우 반납일은 11월 15일 화요일 이어야 하는데 11월 16일 수요일로 보이고 있는 것입니다.

**Comment by keedi** [comment]
문제가 일어나고 있는 주문서는 결제 대기 상태의 주문서가 아닌 그 이전 상태의 주문서로 즉, 대여일과 반납일이 없어서 자동 계산해주는 주문서입니다.

**Comment by keedi** [comment]
현재 해당 부분 구현 코드는 다음과 같습니다.

```perl
    my $rental_date = $order->rental_date ? $order->rental_date->clone : DateTime->today;
    my $target_date =
          $order->target_date
        ? $order->target_date->clone
        : DateTime->today->add( days => 4, seconds => -1 );

    my $rental_date_str =
        $rental_date->set_time_zone( $self->config->{timezone} )->set_locale("ko_KR")
        ->strftime("대여 %m월 %d일(%a)");
    my $target_date_str =
        $target_date->set_time_zone( $self->config->{timezone} )->set_locale("ko_KR")
        ->strftime("반납 %m월 %d일(%a)");
```

**Comment by keedi** [comment]
코드상으로는 문제가 없어 보이지만 단계별로 확인을 해보니 시간대 설정하는 부분이 `today` 이후에 나오게 될 경우 시간대가 적용되면서 반납일이 3박 4일과 4박 5일의 경계선상에 위치하며 4박 5일로 보이게 되는 현상을 발견했습니다.

이를 방지하기 위해서는 `today`를 하는 시점에 확실하게 시간대 영역을 설정해야 합니다.

**Comment by keedi** [comment]
수정 및 릴리스, 서버에 배포 완료했습니다. 이슈 닫습니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
