### ISSUE TITLE
결제 대기 상태일 경우 정장 반납 안내지의 반납 예정일이 틀림

### ISSUE THREAD

**Issue by keedi** [opencloset/opencloset#1023]
포장 완료 상태일 때 출력용 정장 반납 안내지의 반납 예정일이 3박 4일보다 3~4일 더 이후로 설정되는 문제가 있다고 합니다.

확인해보니 다음과 같은 식으로 보입니다.

![screenshot- domain date time](https://cloud.githubusercontent.com/assets/138451/20258966/9ca00d42-aa95-11e6-8f8e-af790395239f.png)

**Comment by keedi** [comment]
이는 이전에 포장 완료 시점에 출력하겠다는 의견을 고려해서 반납일이 설정되지 않았을때를 기준으로 자동 계산하다보니 생긴 문제로 보입니다. 어떤 경우든 출력해야 할 경우가 있으므로 제대로 수정하도록 합니다.

**Comment by keedi** [comment]
관련해서 수정했습니다. 반납일이 없는 경우는 기존처럼 3일을 더하도록 했으며, 이미 반납일이 있는 경우는 다시 더하지 않도록 했습니다.

**Comment by keedi** [comment]
작업 완료했으므로 이슈 닫습니다. :)

**Comment by keedi** [comment]
릴리스 및 배포 완료했습니다.

**Comment by 10001if** [comment]
확인완료하였습니다. 감사합니다. ^^
