### ISSUE TITLE
취업날개 방문자 중 목적/지역에 따른 통계

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1030]
취업날개 이용자 중 목적/지역에 따른 통계를 확인하고자 합니다.

1. 목적이라 함은, 취업목적외에 대여를 하는 경우 어떤 목적으로 얼마나 대여하는지 확인해야 합니다. 더불어 이 경우 메세지를 함께 확인하고 싶습니다. 메세지를 통해 다른 목적으로 대여하는 경우에 대한 상황파악 등 정보가 필요하기 때문입니다.

2. 지역이라 함은, 서울 이외에 거주하는 사람들의 이용 현황에 대해 확인해야 하기 때문입니다. 현재 원칙적으로는 서울에 거주하는 사람만 대상으로 진행하고 있습니다. 서울 거주 외 사람들의 대여 기록을 통해 상황을 확인하고자 합니다.

**Comment by keedi** [comment]
2주나 3주에 한번 있는 전체 회의 때 사용할 자료라고 합니다. 일단 UI에 추가하지는 않고 당장 통계 결과만 알고 싶다고 합니다.

**Comment by keedi** [comment]
가능하면 이런 이슈도 2개로 나누는 것이 더 적절할 것 같습니다. 한 이슈에 두가지 이야기를 하게 되면 댓글로 의견을 주고 받는데 있어 애로사항이 있기 때문입니다. 참고해주시구요. 일단 이번은 하나의 이슈에서 처리하겠습니다.

**Comment by keedi** [comment]
우선 목적에 따른 대여 통계를 내는 질의는 다음과 같습니다.

```sql
SELECT
    o.purpose  AS purpose
    , COUNT(*) AS count
FROM `order` AS o
LEFT JOIN `booking` AS b ON b.id = o.booking_id
LEFT JOIN `coupon`  AS c ON c.id = o.coupon_id
WHERE (
    b.id IS NOT NULL
    AND c.id IS NOT NULL
    AND o.rental_date IS NOT NULL
    AND c.desc LIKE "seoul|%"
    AND c.status = "used"
)
GROUP BY o.purpose
ORDER BY count DESC
;
```

상기 질의는 목적 별 대여해간 주문서 숫자를 뽑아내는 질의입니다. 이 질의를 실행한 결과에서는 메시지 정보는 담겨있지 않습니다.

목적에 면접이라는 용어가 없는 경우의 주문서에서 대여 메시지가 있는 경우를 추려내는 질의는 다음과 같습니다.

```sql
SELECT
    o.id
    , o.purpose AS purpose
    , o.message AS message
FROM `order` AS o
LEFT JOIN `booking` AS b ON b.id = o.booking_id
LEFT JOIN `coupon`  AS c ON c.id = o.coupon_id
WHERE (
    b.id IS NOT NULL
    AND c.id IS NOT NULL
    AND o.rental_date IS NOT NULL
    AND c.desc LIKE "seoul|%"
    AND c.status = "used"
    AND o.purpose NOT LIKE "%면접%"
    AND o.message IS NOT NULL
)
ORDER BY o.id ASC
;
```

**Comment by keedi** [comment]
지역별 대여 통계를 내는 질의는 다음과 같습니다.

```sql
SELECT
    SUBSTRING_INDEX(ui.address2, " ", 1) AS o_addr
    , COUNT(*)                             AS o_count
FROM `order` AS o
LEFT JOIN `booking`   AS b  ON b.id       = o.booking_id
LEFT JOIN `coupon`    AS c  ON c.id       = o.coupon_id
LEFT JOIN `user`      AS u  ON u.id       = o.user_id
LEFT JOIN `user_info` AS ui ON ui.user_id = u.id
WHERE (
    b.id IS NOT NULL
    AND c.id IS NOT NULL
    AND o.rental_date IS NOT NULL
    AND c.desc LIKE "seoul|%"
    AND c.status = "used"
)
GROUP BY o_addr
ORDER BY o_count DESC
;
```

주문서 테이블에서 `address2` 컬럼을 사용했으며, SQL의 `SUBSTRING_INDEX()` 함수를 사용해 첫 번째 공백 이전의 지역 정보를 기준으로 묶어서 결과를 도출합니다.

**Comment by keedi** [comment]
실제 데이터베이스에서 수행한 최종 결과물은 메일로 전달드렸습니다.
작업 완료했으므로 이슈 닫습니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
