### ISSUE TITLE
방문 예약시 예약일 우측에 요일을 표시

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1031]
![2016-11-17 2 12 16](https://cloud.githubusercontent.com/assets/4696328/20377112/104ac0de-acd0-11e6-90a4-c754a552c694.png)
위 화면처럼 예약시간 우측에 요일이 표시되도록 요청드립니다.

**Comment by keedi** [comment]
구현 완료한 화면은 다음과 같습니다.

![screenshot-monster silex kr 10301 2016-11-22 08-50-17](https://cloud.githubusercontent.com/assets/138451/20505508/ec2e0728-b090-11e6-8d01-63612eabe31a.png)

**Comment by keedi** [comment]
기존 `moment.js`가 2013년 기준 2.0.0 버전이어서 가장 최신 버전인 2.16.0으로 갱신했으며, 더불어 bower로 관리하도록 변경했습니다.

**Comment by keedi** [comment]
작업 완료했으므로 이슈 닫습니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
