### ISSUE TITLE
방문 예약시 예약 시간 우측에 예약 가능한 인원 표시

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1032]
![2016-11-17 2 12 16](https://cloud.githubusercontent.com/assets/4696328/20377167/89666f40-acd0-11e6-94a4-d36751acbaec.png)
친구들이 함께 대여하려고 방문하는 경우가 종종 있는데, 시간 당 몇 명이 방문 가능한지 문의주는 경우가 많습니다. 예약가능 인원을 화면에서 바로 보여줄 수 있다면 좋겠습니다.

**Comment by keedi** [comment]
구현 완료한 화면입니다.

![screenshot-monster silex kr 10301 2016-11-22 09-28-04](https://cloud.githubusercontent.com/assets/138451/20506259/2e310a76-b096-11e6-9166-0ca929da362b.png)

**Comment by keedi** [comment]
작업 완료했으므로 이슈 닫습니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
