### ISSUE TITLE
SMS 매크로관리 기능

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#1034]
수시로 발생하는 이슈가 SMS 관련된 이슈입니다.
처리하는데 시간이 걸리고, js 코드로 관리하기 때문에 적용되려면 배포과정을 거쳐야 합니다.

이를 staff 가 관리할 수 있도록 하고자 합니다.

- 매크로를 추가/삭제
- 매크로별로 발신번호를 지정할 수 있도록
- 매크로내 특수문자 치환기능 (`000` -> `홍길동`)

**Comment by 10001if** [comment]
@aanoaa 와.. 너무 좋은 생각이세요! 저희가 직접 처리할 수 있다면 훨씬 좋을 것 같습니다.

**Comment by aanoaa** [comment]
발신번호에 조건이 있는 듯 싶습니다.
등록되지 아니한 발신번호로 매크로를 만들어서 테스트 해봤는데 받지 못했습니다.

**Comment by aanoaa** [comment]
다른 거는 됩니다.(사진관 한개만 해봤지만.. 될거라 믿습니다)

**Comment by keedi** [comment]
법이 바뀌어서 등록하지 않은 발신 번호로는 전송이 불가합니다. `[Web 발신]`이 강제로 붙기 시작한 시절 부터 그랬습니다.

**Comment by aanoaa** [comment]
![screenshot-staff theopencloset net 2016-11-17 19-13-37](https://cloud.githubusercontent.com/assets/170528/20385222/002bd0ec-acfa-11e6-9018-b7c918e50ff3.png)

이거 누르세요

**Comment by 10001if** [comment]
확인 하였습니다. 정말 좋은 기능입니다! 감사합니다. ^^
