### ISSUE TITLE
43074 주문서의 상태를 반납에서 환불로 변경

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1035]
온라인 대여의류 환불인데 반납으로 잘못체크하였습니다. `반납`에서 `환불`로 수정 부탁드립니다.

주문서번호 43074 입니다.

**Comment by keedi** [comment]
실수로 환불을 못하고 잘못 반납한 경우 처리 절차는 다음과 같습니다.

- 해당 주문서의 상태를 **반납**에서 **환불**로 변경
- 해당 주문서의 `order_detail` 항목의 의류 상태를 **반납**에서 **환불**로 변경
- 해당 주문서의 `order_detail` 항목에 환불 항목을 추가
  - **대여 가격**을 총금액 음수 금액으로
  - **소계**를 **대여 가격**과 동일하게
  - **환불 수수료: 0원** 내용을 추가

**Comment by keedi** [comment]
@10001if 환불 수수료가 있는지 확인한 다음 처리하겠습니다. 확인 부탁드려요~

**Comment by keedi** [comment]
상기 내역을 처리하는 질의는 다음과 같습니다.

```sql
UPDATE `order` SET `status_id`=42 where `id`=43074;
UPDATE `order_detail` SET `status_id`=42 where `order_id`=43074 AND `clothes_code` IS NOT NULL;
INSERT INTO `order_detail` (`order_id`, `name`, `stage`, `price`, `final_price`, `desc`, `create_date`)
  VALUES (43074, "환불", 3, -28000, -28000, "환불 수수료: 0원", "2016-11-08 16:44:15")
  ;
```

**Comment by keedi** [comment]
환불 수수료는 0원이라고 합니다. 처리합니다.

**Comment by keedi** [comment]
적용 완료했습니다. 이슈 닫습니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
