### ISSUE TITLE
일찍 오거나 늦게 오는 방문자의 통계

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1037]
일찍오거나 늦게오는 방문자의 수를 확인하고자 합니다.

예약시간보다 방문시간이 빠르거나 느린경우 30분 단위로 앞뒤로 5시간까지 성별을 구분하여 월별로 통계를 확인하고 싶습니다. 급하게 요청드려 죄송합니다..

**Comment by keedi** [comment]
2주나 3주에 한번 있는 전체 회의 때 사용할 자료라고 합니다. 일단 UI에 추가하지는 않고 당장 통계 결과만 알고 싶다고 합니다.

**Comment by yongbin** [comment]
불침번 서다가 처리해봤습니다.

### query

예약시간(`booking`.`date`)와 실제 방문시간(`order_status_log`.`status` 가 13(방문) 인 최초 `timestamp`)의 차이가 하루 미만인 33480 주문서를 대상으로 예약시간과 방문시간의 차이 `time_diff`(분)과 30분 단위수 `time_diff_group`을 구하는 쿼리입니다.

```sql
SELECT
    a.id
    ,e.gender                                                   AS 'gender'
    ,SUBSTR(b.date,1,7)                                         AS 'month'
    ,b.date                                                     AS 'booking_time'
    ,c.arrival_time                                             AS 'arrival_time'
    ,DATE(b.date)                                               AS 'booking_date'
    ,DATE(c.arrival_time)                                       AS 'arrival_date'
    ,DATEDIFF(DATE(b.date), DATE(c.arrival_time))               AS 'date_diff'
    ,TIMESTAMPDIFF(MINUTE,b.date, c.arrival_time)               AS 'time_diff'
    ,CEIL(TIMESTAMPDIFF(MINUTE,b.date, c.arrival_time) / 30)    AS 'time_diff_group'
FROM `order` AS a
        INNER JOIN `booking` AS b ON a.`booking_id` = b.`id`
        INNER JOIN (
                SELECT `order_id`
                        , MIN(`timestamp`) AS arrival_time
                FROM `order_status_log`
                WHERE `status_id` = 13
                GROUP BY `order_id`
                ) AS c ON a.id = c.order_id
        INNER JOIN `user` AS d ON a.user_id = d.id
        INNER JOIN `user_info` AS e ON d.id = e.user_id
WHERE
    DATEDIFF(DATE(b.date), DATE(c.arrival_time)) = 0
```

### pivot table

2016년 10월 예시(female, male)

![screenshot 2016-11-22 03 24 58](https://cloud.githubusercontent.com/assets/52704/20495747/bb35cbd6-b065-11e6-938b-a44bf0568766.png)

결과 ods 파일은 staff 와 한만일 대표님께 메일로 전달하겠습니다.

**Comment by keedi** [comment]
담당자 변경합니다.

**Comment by keedi** [comment]
@yongbin 더불어 추가로 월별 뿐만 아니라 총계 값도 원한다고 합니다. 참고하시구요. 더불어 메일로 보낸 자료를 보면 백분율 관련이 있는데 이것이 잘못된 값 같으니 확인해달라고 남겨두었는데 역시 확인 요망합니다.

**Comment by keedi** [comment]
@yongbin 더불어 상기 질의를 날려보면 그 결과가 cvs든 ods든 타입으로 나오지 않는 중간 자료인데 최종 메일로 보내는 자료용 결과를 후 처리하는 방법을 남겨두시기 바랍니다.

**Comment by yongbin** [comment]
총계 피봇 테이블 시트를 추가한 ODS 파일을 다시 메일 발송했습니다.(%관련 컬럼은 리베라 오피스에서 subgroup 비율을 제공하지 않아서 삭제했습니다) 

상기 쿼리로부터 자료를 생성하는 방법은 아래와 같습니다.

## 1. 쿼리결과를 CSV로 export
## 2. CSV를 리베라 오피스로 열기
## 3. Data -> PivotTable -> Create

![screenshot 2016-11-23 16 32 38](https://cloud.githubusercontent.com/assets/52704/20553889/4efbab7a-b19b-11e6-93b7-39520ec98982.png)

## 4 자료의 전체영역이 선택되고 아래와 같이 피벗테이블 구성
DataFiled 에 **id 를 Count 로 지정하는것에 유의** (기본함수는 sum)

### 1)월별 / 지연시간 x 성별 피봇
![screenshot 2016-11-23 16 32 25](https://cloud.githubusercontent.com/assets/52704/20553892/5519a282-b19b-11e6-8d71-c9e108c1580b.png)
### 2) 지연시간 x 성별 피봇
![screenshot 2016-11-23 16 31 46](https://cloud.githubusercontent.com/assets/52704/20553894/59557a10-b19b-11e6-91eb-6dee65b105c6.png)

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^

**Comment by 10001if** [comment]
본 자료를 통해 30분 늦게 오는 인원의 비율이 다소 높은 것으로 확인했기 때문에 늦지 않도록 구체적으로 늦으면 안되는 이유에 대해 잘 알려주고 본 내용 강화하는 방법을 도입하는 것으로 확인하였습니다. 매우 유익한 자료였습니다. 감사합니다.
