### ISSUE TITLE
미리 입어보기 위해 방문하는 대여자 통계

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1038]
미리 입어보기 위해 방문하는 사용자의 수를 확인하고 싶습니다.

미리 입어보는 분을 체크하기 위해서는 예약일시보다 5일이상 빨리 방문한 인원 중, 대여를 하지 않고 돌아간 사람으로 체크하여 추정하면 될 것으로 생각합니다.

이 경우도 월별로 성별을 구분하여 확인하고 싶습니다.

**Comment by keedi** [comment]
2주나 3주에 한번 있는 전체 회의 때 사용할 자료라고 합니다. 일단 UI에 추가하지는 않고 당장 통계 결과만 알고 싶다고 합니다.

**Comment by keedi** [comment]
진행합니다.

**Comment by keedi** [comment]
오늘 논의 결과 처리하지 않기로 했습니다.

**Comment by keedi** [comment]
이슈 닫습니다.
