### ISSUE TITLE
2회 이상 미방문자의 확인

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1041]
2회 이상 미방문자에게는 룰에 따른 페널티를 부과하려고 합니다.
2회 이상 미방문자의 수를 확인 한 뒤, 페널티의 내용을 결정하려고 합니다.
2회, 3회, 4회.. 횟수별로 미방문자의 총 인원(남/여)을 알고 싶습니다.

횟수|총인원|남|여
----|-----|--|--
2회|00|00|00
3회|00|00|00
4회|00|00|00
5회|00|00|00
6회|00|00|00
합계|00|00|00

**Comment by yongbin** [comment]
![screen shot 2016-11-21 at 12 24 32 pm](https://cloud.githubusercontent.com/assets/52704/20469741/7f666c80-afe5-11e6-8324-643c53f07bdd.png)

**Comment by yongbin** [comment]
#1029 에 작성되어있던 쿼리를 조금 수정한 뒤에 Libreoffice 피벗 테이블로 간단하게 구했습니다.

```sql
SELECT
    u.id						   AS user_id
    , ui.gender                    AS gender
    , COUNT(*)                     AS cnt
FROM `order` AS o
LEFT JOIN `booking`   AS b  ON b.id = o.booking_id
LEFT JOIN `status`    AS s  ON s.id = o.status_id
LEFT JOIN `user`      AS u  ON u.id = o.user_id
LEFT JOIN `user_info` AS ui ON ui.user_id = u.id
WHERE (
    (
        ( o.status_id = 14  AND b.date < CURDATE() ) -- 방문 예약이지만 1일 이상 지난 경우
        OR
        ( o.status_id = 12 ) -- 방문 안함 경우
    )
    AND o.parent_id IS NULL -- 부모 주문서
)
GROUP BY user_id
ORDER BY b.date DESC
;
```

**Comment by yongbin** [comment]
@10001if 님께 전달했습니다. 이슈닫습니다.

**Comment by keedi** [comment]
@yongbin 메일 보내실때, staff, info 참조 좀 부탁드립니다. :(

**Comment by yongbin** [comment]
아 이 이슈는 위에 pivot table 결과를 눈으로 보시고 그냥 OK 하셨기 때문에 따로 메일 보내지 않았습니다. 메일 보낼때는 주의해서 참조하겠습니다.
