### ISSUE TITLE
주말(토/일) 미방문하는 봉사자의 통계 확인

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1042]

**Comment by yongbin** [comment]
@10001if  님께 중간결과를 보내드렸습니다. 세부사항이 결정되면 진행하겠습니다.

**Comment by yongbin** [comment]
@10001if  님께서 세부사항을 결정해주시면 다시 assign 해주시기 바랍니다.

**Comment by 10001if** [comment]
보내주신 자료로 체크하였습니다. 184명 중 134명 약 74% 정도가 136*를 통해 유입되는 것으로 확인하였습니다. 136*를 닫고 운영하면서 추이를 지켜보도록 하겠습니다.
