### ISSUE TITLE
봉사자 소속센터 기록

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1045]

**Comment by aanoaa** [comment]
완료 목록에 1365 아이디와 함께 표시되어야 합니다.

**Comment by 10001if** [comment]
@aanoaa 완료목록에 1365아이디와 소속센터가 표시되지 않는 것 같습니다. 확인 부탁드릴게요. ^^

**Comment by aanoaa** [comment]
네 그건 아직 적용 전 입니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
