### ISSUE TITLE
preparation 검색 추천 세트의류의 의류의 마우스 hover 시 나타나는 기증자정보가 상의정보로만 표시됨

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1046]

**Comment by yongbin** [comment]
https://github.com/opencloset/monitor/issues/138

**Comment by yongbin** [comment]
https://github.com/opencloset/monitor/issues/141 이슈에서 처리되었습니다.

**Comment by yongbin** [comment]
@10001if 님과 확인해보니 이 이슈와 opencloset/monitor#141 이슈는 다른 이슈였습니다. 처리해야합니다.

**Comment by keedi** [comment]
@10001if 가능하면 이슈의 내용을 정리해주시고 버그일 경우 재현이 가능하다면 화면도 갈무리 해주시면 좋을 것 같습니다.

**Comment by 10001if** [comment]
@keedi https://github.com/opencloset/monitor/issues/138 이슈에 상세 내용을 정리하였습니다. 확인 부탁드립니다.

**Comment by 10001if** [comment]
중요한 이슈입니다. 진행이 되어야 합니다~
