### ISSUE TITLE
방문예약에 지난 주문서의 의류착용일이 입력되어 있음

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#1047]
의류착용일이 비어있어야 함에도 지난 대여의 의류착용일이 남아있다고 합니다.

**Comment by aanoaa** [comment]
최근의류착용일로 라벨이 바뀐다면 괜찮을까요?

**Comment by aanoaa** [comment]
버그는 아닙니다.
사용자의 최근 의류착용일을 저장하고 있고 그 날짜를 보여주고 있습니다.

**Comment by aanoaa** [comment]
@10001if 어떻게 바뀌길 원하시는 건가요?

**Comment by 10001if** [comment]
@aanoaa 예약시 이용자가 착용일을 입력할 수 있도록 착용일이 리셋되어야 합니다.

**Comment by aanoaa** [comment]
예약했을때의 의류착용일이 보여져야 합니다.

지난번에 이용했다고 하더라도 이번에 새로 방문예약을 했다면 이번 방문예약할때 입력했던 의류착용일

**Comment by keedi** [comment]
@10001if 음 제가 보기에 이 이슈는 사용자 정보 페이지에서의 이슈가 아니라 방문 예약 화면에서의 이슈 같아보이는데요. 사용자 정보 페이지 쪽은 아무 이슈가 없는 것 아닌지요? 확인 부탁드립니다.

**Comment by aanoaa** [comment]
그러고 보니 헛갈리네요.
아래 둘중에 어느 것 인가요?

- 방문예약이후에 사용자 화면의 착용일이 최근 것으로 업데이트 되어야 한다.
- 재방문자의 방문예약화면에서 착용일이 비어있어야 한다.

**Comment by keedi** [comment]
제 느낌의 경우 사용자 화면은 현재 아무 문제가 없고, 예약 화면에서 기존에 빌렸던 적이 있는 사람일 경우 마지막에 기입했던 자료를 편의상 다시 보여주는데 그것 때문에 헷갈린다는 것 같습니다. 정확한 것은 @10001if 님의 피드백을 보아야할 것 같습니다.

**Comment by 10001if** [comment]
@keedi 이야기 주신 것처럼 사용자가 예약을 진행할 때 예약화면에서 착용일이 (주소가 그대로 남아있는 것처럼) 기존 착용일 그대로 남아 있는 것이 문제입니다.

**Comment by 10001if** [comment]
@aanoaa 착용일자가 그대로 남아 있는 것 같습니다. 확인 부탁드릴게요~
![2016-11-25 12 37 01](https://cloud.githubusercontent.com/assets/4696328/20613897/eb7ab600-b30b-11e6-8271-4337980ab0b8.png)

**Comment by 10001if** [comment]
![2016-11-25 12 38 18](https://cloud.githubusercontent.com/assets/4696328/20613918/14340e98-b30c-11e6-8a28-cb66373929c6.png)
이게 맞겠네요~

**Comment by 10001if** [comment]
직원예약이었습니다. 잘 적용되어 있는 듯 합니다. 이슈 닫도록 하겠습니다.
