### ISSUE TITLE
정장 반납 안내지의 음영과 밑줄을 제거함

### ISSUE THREAD

**Issue by keedi** [opencloset/opencloset#1058]
정장 반납 안내지에 반납일의 경우 강조하기 위해 현재 형광 노란색의 음영과 빨간 밑줄을 추가하고 있습니다.

![screenshot- domain date time](https://cloud.githubusercontent.com/assets/138451/20556855/488c3582-b1ac-11e6-9054-837dd025f0b9.png)

그런데 열린옷장 측에서 재생 토너를 쓰면서부터 번짐이 심해 알아보기가 힘들다고 합니다. 관련해서 음영과 밑줄을 제거해달라고 합니다.

**Comment by keedi** [comment]
처리 완료한 화면입니다.

![screenshot- domain date time](https://cloud.githubusercontent.com/assets/138451/20614404/6a04b8b8-b311-11e6-98a6-dcf6c9f018d1.png)

**Comment by keedi** [comment]
작업 완료했으므로 이슈 닫습니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
