### ISSUE TITLE
셔츠의 그룹핑 자료를 통해 검색결과로 그룹의 숫자를 알려주도록 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1064]
요즘 그룹핑 자료를 통해 재고관리를 실시하고 있습니다. https://github.com/opencloset/opencloset/issues/607

그런데 그 과정에서 셔츠도 그룹핑을 통해 의류를 손쉽게 정리하고 찾을 수 있게 하면 어떨까라는 생각을 하게 되었습니다.

현재는 이렇습니다.

1. 셔츠에 필요한 사이즈 측정 : 가슴, 목둘레, 팔길이
2. 가슴 사이즈를 보고 구간에서 의류를 선택 함 (90, 100, 105 ...)
3. 구간 내에서 목둘레와 팔길이를 살펴본 후 적합한 의류를 선택

정확히 맞는 의류를 전달하기 위해서는 3가지 사이즈를 모두 확인해야 합니다.
그러나 이 3가지 사이즈를 모두 확인해서 셔츠를 찾는 것이 어렵고 시간도 많이 필요합니다.
때문에 스트레스를 받기도 하지만, 제대로 셔츠를 찾아주지 못해 한번 입고 다시 찾아드려야 하는 경우가 많습니다.
이로 인해 다시 찾는 시간이 추가적으로 소요되고, 한번 입은 셔츠는 다시 다려야 하기에 비용도 상승합니다.

때문에 다음과 같은 방법을 요청드리고 싶습니다.

1. 사이즈 구간을 설정 

(1) 가슴 : 
  1) 90 이하
  2) 91~96
  3) 97~102
  4) 103~109
  5) 110~116
  6) 117~123
  7) 124~130
  8) 131 이상

(2) 목둘레 
  1) 34 이하
  2) 35~40
  3) 41~46
  4) 47 이상

(3) 팔길이 
  1) 57 이하
  2) 58~60
  4) 61~63
  5) 64이상 

2. 본 사이즈를 대상으로 https://github.com/opencloset/opencloset/issues/607 과 같은 방법으로
그룹핑을 실시
3. 대여자의 신체치수를 기반으로 그룹핑 결과를 알려줌
4. 옷장지기는 그 그룹 숫자로 가서 셔츠를 찾아 셔츠를 제공
5. 잘 맞지 않을 경우를 대비하여 알려준 그룹보다 더 큰 그룹 2개, 더 작은 그룹 2개를 동시에 알려줌

이렇게 생각 중입니다.

이렇게 되면 다음과 같은 장점이 있습니다.

1. 옷장지기는 셔츠를 찾아 헤멜 필요가 없다.
2. 봉사자와 옷장지기는 세탁된 셔츠를 5층에서 숫자만 보고 바로 정렬할 수 있다.

그런데 이를 바로 실행하기에는 약간의 두려움(?)이 있습니다.

따라서 다음과 같은 방법이 가능한지 문의 드리고 싶습니다.

1. 실제 대여자의 신체치수를 가지고 그룹핑 한 결과값(셔츠의 사이즈)를 확인
2. 대여자가 대여한 셔츠의 기록과 비교하여 그 범위 내에 들어 갔는지 비교
3. 대여의 정확도가 얼마인지 체크

이런 방식을 통해 실제 적용이 가능한지 타진해보고 가능하다면, 수트를 대여하기 전에 테스트(?)를 위해 실전에서 활용해 보고 싶습니다. 가능할지 @yongbin 의견 부탁드립니다. 테스트가 어렵다면 그룹핑 결과를 가지고 샘플 대여자를 지정하여 하루에 10명 정도 일주일 동안 실험을 해볼 계획이 있습니다.

**Comment by yongbin** [comment]
넵 이 이슈는 #607 이 마무리되면 고민해 보겠습니다.

**Comment by yongbin** [comment]
@10001if 님과 논의결과 상대적으로 우선순위가 높습니다. 이 이슈를 우선 진행합니다.

**Comment by 10001if** [comment]
@yongbin 예측치 기준을 말씀드립니다.

1. 가슴 : 신체사이즈 + 7
2. 목둘레 : 신체사이즈 + 2
3. 팔길이 : 신체 사이즈 + 1

**Comment by 10001if** [comment]
현재는 다음 이슈가 필요하지 않습니다. 이슈가 필요한 경우 다시 열도록 하겠습니다.
