### ISSUE TITLE
의류 착용일과 예약 방문일 간 차이가 클 경우 대여자에게 경고함

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1065]
옷을 예약할 수 없다는 것을 모르는 경우가 많습니다.
따라서 예약시 옷을 미리 예약할 수 없다는 점에 대해 안내가 필요합니다.
착용일이 방문일 5일 이후인 경우 미리 입어보는 사람으로 간주하고 미리 입을 때 발생하는 상황에 대해 안내합니다.

안내해야 할 내용과 방법에 대해서는 다시 작성하도록 하겠습니다.

**Comment by keedi** [comment]
관련해서 조금 더 자세하게 고민해보시고 적어주시면 바로 진행하겠습니다.

확인 부탁드립니다.

**Comment by 10001if** [comment]
@Bentleypark 고민이 정리되면 바로 적어주셔도 좋습니다.

**Comment by Bentleypark** [comment]
@keedi @10001if 
대여자가 예약 진행시, 착용날짜 - 방문날짜 = 4일 이상 될 경우에 미리 입어보는경우에 해당됩니다. 예약페이지에서 대여자가 날짜를 선택할때 팝업창 형태로 다시 한번 해당 경우에 대한 세부안내가 필요합니다. 

팝업창은  대여자가 방문날짜/착용날짜를 선택한 후
아래 조건이 될때 대여자에게 팝업창을 띄우도록 합니다. 
팝업창 띄우는 조건: 착용날짜 - 방문날짜 = 4일 이상  

(팝업창 내용) 

열린옷장 정장대여 서비스는 기본적으로 방문하는 날짜에 의류를 수령하여 3박4일동안 이용 가능합니다.  

ex) 
-방문날짜: 2016년 3월 10일 
-착용날짜: 2016년 3월 16일
-총 대여기간: 6박7일 

3박4일을 초과하여 추가비용이 발생하게 됩니다. 방문날짜를 다시 한번 확인하시고 선택해주시길 부탁드립니다. 정장스타일 및 사이즈 때문에 미리 입어보시는 경우에는 별도의 비용이 발생하지 않으며, 방문하여 착용한 의류에 대한 예약은 제공하지 않습니다. 열린옷장 서비스를 이용하시는데 참고해주시길 부탁드립니다.

**Comment by 10001if** [comment]
팝업창 내용을 아래와 같이 수정하였습니다.

ex) 
- 방문 날짜: 2016년 3월 10일 
- 착용 날짜: 2016년 3월 16일
- 총 대여기간: 6박 7일 인 경우

기본 대여기간인 3박 4일에서 0일 초과. 연장비용 00,000원 발생. 

"예약일에 대여하지 않고 사전 방문 하는 경우, 아래 유의사항을 꼭 확인해주세요."

1. 의류 예약(찜)은 불가능합니다. 당일 대여를 원칙으로 합니다. 
2. 그럼에도 스타일/사이즈 확인을 위해 미리 방문해야 한다면 예약을 마치고 방문하세요. 
3. 하지만 대여일에 같은 옷을 입을 수 없으므로 권장하지 않습니다. 대여일에 가장 잘 맞는 옷으로 대여하세요!

**Comment by aanoaa** [comment]
이슈를 요약하면,
보통의 경우 `의류착용일 - 방문일 >= 4` 라면, 미리 입어보는 경우입니다.(맞나요?)
그래서 문자메세지로 이와 관련된 안내를 보내주도록 하자는 것입니다.

**Comment by 10001if** [comment]
@aanoaa 네! 맞습니다!

**Comment by 10001if** [comment]
@aanoaa 내용을 다시 확인해보니, 문자 메세지가 아니라 웹 상에서 바로 확인할 수 있도록 '팝업'과 같은 형태의 알림을 요청한 건입니다. 문자메세지가 확인하기는 용이하지만, 위의 내용을 살펴보면 예약 전에 다음 사항을 확인하고 미리 오는 것을 예방하고자 하는 측면이 큽니다. 문자메세지를 받았다는 것은 이미 예약이 완료된 뜻이라는 의미이므로 미리 오는 사람을 줄일 수 있는 방법은 되지 못할 가능성이 크지 못할 것입니다. 예약시 먼저 안내를 실시 하도록 해야 합니다.

**Comment by keedi** [comment]
@10001if 여전히 필요한 기능인지 확인 부탁드립니다.

**Comment by 10001if** [comment]
@keedi 네. 여전히 필요합니다. 일찍 방문하는 경우, 연장비용은 @aanoaa 께서 개발해 주신 덕분에 잘 안내가 되고 있지만 위에서 언급한 내용에 대한 고지가 필요합니다.

>"예약일에 대여하지 않고 사전 방문 하는 경우, 아래 유의사항을 꼭 확인해주세요."

    의류 예약(찜)은 불가능합니다. 당일 대여를 원칙으로 합니다.
    그럼에도 스타일/사이즈 확인을 위해 미리 방문해야 한다면 예약을 마치고 방문하세요.
    하지만 대여일에 같은 옷을 입을 수 없으므로 권장하지 않습니다. 대여일에 가장 잘 맞는 옷으로 대여하세요!

의류를 찜할 수 있다고 이해하거나 현장에서 요청하면 될것이라는 기대(?)로 미리 방문하는 경우들이 지소적으로 발생하고 있기 때문입니다.

**Comment by keedi** [comment]
진행합니다.

**Comment by keedi** [comment]
구현 중인 화면은 다음과 같습니다.

![2017-11-15 16-34-33](https://user-images.githubusercontent.com/138451/32824114-0b3cbc3e-ca23-11e7-9541-beb1eeae1eac.png)

![2017-11-15 16-32-49](https://user-images.githubusercontent.com/138451/32824062-c5dd9b4a-ca22-11e7-844a-e8e3578de3d1.png)

@10001if 문구나 색상 등 수정하실 내용이 있다면 피드백 부탁드립니다.

**Comment by 10001if** [comment]
의류 예약(찜)은 불가능하며 당일 대여를 원칙으로 합니다.
그럼에도 불구하고 스타일/사이즈 확인을 위해 미리 방문해야 한다면 예약을 완료해주세요. 
하지만 실제 대여하고자 하는 날에 해당 의류가 대여 된 상태라면, 같은 옷은 대여할 수 없으므로 미리 방문하는 것은 권장하지 않습니다. 대여일에 가장 잘 맞는 옷으로 대여하세요!

**Comment by 10001if** [comment]
이렇게 수정 부탁드립니다! :)

**Comment by keedi** [comment]
작업 완료했습니다. 이슈 닫습니다.

**Comment by 10001if** [comment]
제가 직접 예약을 해보았는데. 팝업창이 뜨지 않습니다. 한번 더 확인 부탁드립니다.

**Comment by keedi** [comment]
한 번 더 확인 부탁드립니다. 착오가 있어 staff 만 배포하고 visit 쪽은 배포가 안됐었네요;; 방금 visit 새로 배포했습니다. 적용이 안된 것 같으면 강제 새로 고침 2~3번 부탁드립니다.

**Comment by 10001if** [comment]
확인했습니다. 잘 표시됩니다. 감사합니다. :)
