### ISSUE TITLE
대리인을 통한 대여

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1066]
대리방문 전에 예약 전에 어떠한 사이즈를 알아야 하는지 안내를 해야 합니다.
대리로 방문하는지 여부를 체크하는 항목이 필요합니다.
그 이후에는 대리로 방문할 경우에 대해 안내해야 하며
최종적으로 예약이 완료되면 대리방문자에게 착용자에게 필요한 사이즈 정보를 문자로 안내해야 합니다.

대리 방문에 대한 방법과 안내내용은 다시 정리하도록 하겠습니다.

**Comment by 10001if** [comment]
@Bentleypark 이슈 해결을 위해 투입 요청합니다~

**Comment by aanoaa** [comment]
대여를 위해 대여시스템에서는 사용자정보를 참고하는데,
사용자정보는 사용자의 신체치수정보를 포함하고 있습니다.

대리인이 방문했을경우 사용자정보의 필수 정보인

- 이름
- 이메일
- 전화번호

등을 모를 수 도 있습니다.

신체치수도 직접 측정하는 정보만큼 만족스럽지 않을 수 있습니다.
대리인에 대한 정보를 사용자정보로 우겨넣기는 힘든 방법인 것 같고
대리인정보를 위한 값을 유동적으로 넣을 수 있는 방법과
이를 활용한 새로운 대여방법을 만들어야 합니다.

지금 시스템은 사용자정보를 참고해서 대여절차가 이루어지고 있습니다.

--------------------------

대리인대여에 영향을 받을 수 있는 부분을 추측해보면

- 방문예약
- 대여과정전반
  - staff
  - monitor
- 반납

이 아닐까 합니다.

추가로 쿠폰 및 대여할인에 대한 변수도 고려해야 합니다.

**Comment by aanoaa** [comment]
기존 시스템의 변경대신에 `대여.theopencloset.net` 시스템을 새로 만드는 것이 나을 수 있습니다.

**Comment by aanoaa** [comment]
대리인을 통한 대여

- 본인이 방문해서 다른 사람의 의류를 대여
- 본인이 예약했지만 타인이 방문해서 의류를 대여

**Comment by aanoaa** [comment]
> 현재 대리로 대여하는 대여자에 대한 문제들이 지속적으로 발생하고 있습니다.
> 따라서 다음과 같은 방법이 필요하다고 @keedi 이야기 주셨습니다.
> 
> 실제 착용자가 아닌 경우 대리로 대여하는 자의 정보를 따로 기록하는 것이 필요한데
> 이는 온라인 주문을 신청할 때 주문자의 정보와 동일합니까? [o] 
> 본 항목에 체크하면 자동으로 배송지가 결정되는 것 과 같은 항목을 말합니다. 
> 구체적인 내용은 @keedi 추가적인 논의가 필요합니다.

**Comment by 10001if** [comment]
@aanoaa 본 이슈는 온라인에도 동일하게 적용이 필요한 이슈입니다. 사용자 정보는 온오프라인이 동일하게 공유하여 사용하고 있기 때문입니다.

**Comment by aanoaa** [comment]
궁극적으로는 하나의 주문서에서 다양한 품목의 다양한 사이즈를 여러개씩 대여할 수 있는 방법이 필요하다고 합니다.
(모든게 다 되는)

대리인대여는 위 문제를 해결하는 과정중 하나일 뿐 입니다.

**Comment by aanoaa** [comment]
가상 시나리오 입니다.

- 방문예약시에 대리/단체 대여여부를 묻는다.
- 방문예약후에 신체치수를 입력할 수 있도록 한다.(단체일 경우에는 n명)
  - 대여품목도 선택가능해야 한다.
- 시간표에 대리/단체 대여를 표시한다.
- 주문서는 성별정보를 가질 수 있어야 한다.
- 주문서는 n명의 신체치수정보를 포함할 수 있어야 한다.
  - 주문서에서 n명의 신체치수정보를 excel 파일로 다운로드/업로드 할 수 있어야 한다.
- 단체나 대리대여의 경우에는 검색결과에 포함시키지 않는다.
- 단체/대리 대여일 경우에는 사용자 정보가 아닌 주문서 정보에서 신체치수를 수정할 수 있도록 한다.
- 대여후에 대리/단체 대여일 경우에는 사용자의 신체치수를 주문서에 복사하지 않는다.

**Comment by aanoaa** [comment]
본인이 예약해서 대리인이 오든, 대리인의 정보로 예약을 했던 상관없이
이러한 경우에는 사용자정보의 신체치수를 건드리지 않아야 합니다.

주문서정보의 신체치수를 수정할 수 있도록 하는 것이 해결방법인 것 같습니다.

**Comment by aanoaa** [comment]
@pingpongworks

> 방문예약시에 대리/단체 대여여부를 묻는다.

내용과 함께 어디에 위치해야할지 알려주세요.

**Comment by pingpongworks** [comment]
네~ 휴일 끝난후 출근해서 정리해보겠습니다. 


2017. 7. 26. 오후 2:17 Hyungsuk Hong <notifications@github.com> 작성:

**Comment by aanoaa** [comment]
schema 변경이 필요할 것 같습니다.
주문서 table 에는 몇가지 flag 가 있는데,

    online, pass, ignore, ignore_sms, bestfit

is_xxx 가 아니라 그냥 쓰고 있습니다.

대리대여 여부를 저장하고자 하는데

`agent`? 컬럼을 추가할까 합니다.

**Comment by pingpongworks** [comment]
내용 정리를 하려고 하던 차에 @10001if 님이 휴가를 끝내고 돌아왔습니다. 대리대여 구현 방향이나 구체적인 방법에 의견차가 있을 수도 있을 거 같아, @aanoaa님과 만일대표가 한번 더 논의한 후에 정리하는 게 좋을 거 같습니다.

**Comment by 10001if** [comment]
대리 대여자의 심리가 조금 궁금합니다. 대리로 방문하는 경우 착용자가 직접 방문할 수 없는 경우가 이에 해당될 텐데, 실제 착용자가 의류를 착용하지 못하기 때문에 원칙적으로는 온라인과 다를 바가 없습니다. 그래서 대리대여는 적극적으로 온라인 대여를 통해 안내할 계획을 가지고 있습니다. (하지만 적용이 가능하려면 원더스퀵이 적용된 상태여야 합니다. 현재는 신청할 수 있는 시점이 3-5일 전이기 때문에 급하게 필요한 사람들에게는 실효성이 크지 않습니다.)

하지만 이 경우에도 방문을 원하는 경우가 존재할 것입니다. 추측컨대, "우리 아들(딸)의 면접이니 내가 한번 봐야겠다"거나 "그래도 직접 보고 가져와야 마음이 편하다"와 같은 심리일 것으로 추측됩니다. 이 경우에도 정확한 사이즈가 존재해야 잘 맞는 의류를 제공해 드릴 수 있기 때문에 대리로 방문을 하려는 경우 착용자의 사이즈를 입력한 뒤 예약이 진행되도록 하려고 합니다. 이 때문에 예약이 늦어져 예약만료 상황이 발생할 수 있으나 실제 하루에 대리 대여로 방문하는 인원이 많지 않으므로, 대리방문 대여자의 경우에는 예약인원과 관계없이 예약이 가능하도록 하려 합니다.

그리고 이 경우 시간표에 `대리대여` 표시를 하여 방문 전에 미리 의류를 준비해 놓을 수 있도록 합니다. 그래서 방문시에 바로 의류를 전달하고 전달된 의류에 문제가 없다면 바로 대여를 진행할 수 있도록 하려 합니다. 온라인과 같은 방식이지만 대리대여자의 최종 결정이 존재하며 택배를 통해 발송하는게 아니라 대리대여자가 직접 의류를 가져간다는 점에서 다릅니다.

**Comment by 10001if** [comment]
다만, 대리대여자가 착용자의 사이즈를 입력하는데 불가능할 경우가 있으므로 이 경우 사이즈 입력 하는 곳 하단에 사이즈를 입력할 수 없는 경우에 대비한 내용을 적어야 합니다. (예> 사이즈 확인이 불가능한 경우 전화주세요. 이 경우 정확한 사이즈의 의류를 제공해 드릴 수 없으니 이 점 양해 부탁드립니다.)

**Comment by 10001if** [comment]
이름 전화번호 하단에 대리/단체 여부를 묻습니다. 내용은 다음과 같습니다.

**Comment by 10001if** [comment]
![2017-08-03 11 23 32](https://user-images.githubusercontent.com/4696328/28906033-92daee2a-784f-11e7-9d68-9ad5209e9c4c.png)

**Comment by 10001if** [comment]
예약자 본인과 실제 의류를 착용하는 사람이 다른 경우(대리로 대여하는 경우), 오른쪽 빈칸에 체크해 주세요. [ ]

**Comment by 10001if** [comment]
<의류 사이즈 입력 창 상단에 안내되어야 할 문구입니다>
실제 착용자의 사이즈를 줄자로 측정하여 정확히 입력해 주세요. 일반적인 사이즈 호칭 (예> 95, 100 이나 55, 66)으로 의류를 대여하는 경우 착용시 의류의 사이즈가 맞지 않을 가능성이 상당히 높습니다. 특히 면접, 결혼식과 같이 중요한 일정을 앞두고 계신 분이거나 체형이 특별한 경우에는 반드시 실제 착용자의 현재 사이즈를 새로 측정하여 입력해주세요.

**Comment by 10001if** [comment]
필요한 사이즈 정보는 다음과 같습니다. 

1. 남성
키, 몸무게, 가슴둘레, 허리둘레, 허벅지둘레
2. 여성
키, 몸무게, 가슴둘레, 배꼽둘레, 엉덩이둘레

이상의 사이즈만 기입받고자 합니다.

**Comment by 10001if** [comment]
이용을 해보니 몇가지 수정의견이 있었습니다.

1. 예약자 본인과 대리인의 의류를 동시에 대여해야 할 경우에 선택할 수 있는 항목이 없습니다. 
사실 이 경우는 대리인으로 선택하고 본인은 현장에서 사이즈를 측정하여 사용자 정보에 입력하면 되므로 대리인의 경우만 미리 사이즈를 입력해 놓으면 되기 때문에 큰 문제는 없어 보입니다. 다만, 입력자가 이 사실에 대해 명확히 이해하고 있지 못하므로 이에 대한 적극적인 안내가 필요해 보입니다. (너무 많은 안내가 들어가는 것 같긴 합니다.)

2. 대리인의 사이즈를 바로 알지 못하기 때문에 나중에라도 사이즈를 입력할 수 있는 url을 제공해야 합니다. 대부분의 대리대여자가 착용자의 사이즈를 바로 알지 못하기 때문에 예약시에는 예약을 우선 진행하고 차 후에라도 사이즈를 입력할 수 있는 url을 전달해야 합니다.

**Comment by aanoaa** [comment]
> 예약자 본인과 대리인의 의류를 동시에 대여해야 할 경우에 선택할 수 있는 항목이 없습니다.

어떻게 안내할 것인지 알려주세요.
담당자 변경하겠습니다.

> 대리인의 사이즈를 바로 알지 못하기 때문에 나중에라도 사이즈를 입력할 수 있는 url을 제공해야 합니다.

이메일을 활용하면 다양한 정보를 대여자가 원할때 열어서 볼 수 있습니다.
의견일 뿐 입니다.

더 좋은 방안이나 어떻게 진행할지 결정해서 알려주세요.

**Comment by 10001if** [comment]
@aanoaa 네~ 결정해서 다시 남겨놓겠습니다.

**Comment by 10001if** [comment]
> 예약자 본인과 대리인의 의류를 동시에 대여해야 할 경우에 선택할 수 있는 항목이 없습니다.

-> 실제로 이용해보니 이 문제에 대해 문의를 한 경우 없었다고 합니다. 차후에 문제가 발생하면 다시 요청드리겠습니다.

> 대리인의 사이즈를 바로 알지 못하기 때문에 나중에라도 사이즈를 입력할 수 있는 url을 제공해야 합니다.

-> 이메일을 통해 정보를 추후에 입력할 수 있도록 요청드립니다. 하지만, 이메일을 통해 본 내용을 입력해야 한다는 사실을 인지하지 못하고 있을 것입니다. 따라서 다음과 같이 요청드립니다.

1. 대리인 예약 완료
2. 대리인 사이즈 입력 창 뜸 -> 대리인 사이즈의 입력 창 내용 수정

열린옷장 대리인 정보를 입력해주세요
1명의 신체치수 정보를 각각 입력해주세요.

***지금 사이즈 입력이 불가능한 경우, 작성해주신 메일 주소로 사이즈 입력이 가능한 주소를 보내드립니다. 지금 사이즈를 입력할 수 없다면, 반드시 방문 전까지 대리인의 사이즈를 입력해 주세요.*** -> 추가 

실제 착용자의 사이즈를 줄자로 측정하여 정확히 입력해 주세요. 일반적인 사이즈 호칭 (예> 95, 100 이나 55, 66)으로 의류를 대여하는 경우 착용시 의류의 사이즈가 맞지 않을 가능성이 상당히 높습니다. 특히 면접, 결혼식과 같이 중요한 일정을 앞두고 계신 분이거나 체형이 특별한 경우에는 반드시 실제 착용자의 현재 사이즈를 새로 측정하여 입력해주세요.

**Comment by aanoaa** [comment]
대리인 대여일 경우에만 이메일을 보내는 건가요?
이메일의 제목과 내용을 알려주세요.

**Comment by keedi** [comment]
@10001if 가능하면 릴리스 및 배포 이후 개선 사항은 별도 이슈로 열어주세요. 지금 처럼 이용해본 뒤 피드백을 얻는 경우가 그 경우라고 생각됩니다. 동일 이슈에서 개선 사항을 처리하는 부분이 이어져 길게 진행되게 되면 원래 제목과 다르게 진행되어 이후 검색이 쉽지 않은 부분이 있습니다.

이미 완료된 이슈라면 간단히 정리하고 이슈 닫아주시고, 아직 완료되지 않았다면 별도의 이슈를 열어 내용을 정리해주신 다음 본 이슈를 닫아주세요.

**Comment by 10001if** [comment]
@keedi 네. 무슨 말씀인지 이해했습니다. 아직 완료되지 않은 이슈이므로 별도의 이슈를 열어 내용을 정리한 뒤 본 이슈를 닫도록 하겠습니다. 그ㅓㄴ데 별도의 이슈를 열을 때 본 이슈와 연결을 시키는 것이 필요한가요?
