### ISSUE TITLE
대여자가 선호의류를 대여이력에서 선택할 수 있도록 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1067]
3개월 이내 재방문의 경우 지난 기록을 보여줘서 원하는 의류사이즈를 체크하도록 합니다. (대여 일로 선택할 수 있도록 함)
그리고 지난 기록의 사이즈는 잘 맞으나 다른 색상을 입고 싶던지 조금 다른 이유가 존재하는 경우에도 기록을 받도록 합니다. 이를 통해 대여자가 신체 사이즈 재 측정을 기다리는 시간을 줄일 수 있습니다. 신체 사이즈 재측정을 하는 것은 아니나 의류준비 상태로 넘기는 권한을 신체측정자가 가지고 있으므로 본 단계를 통해야만 대여가 진행되기 때문입니다.

지난 기록에 대해 질문을 하는 내용에 대해서는 다시 정리하여 올리도록 하겠습니다.

이때,  선택한 의류가 없을 수도 있다는 것에 동의를 하도록 하는 항목이 필요하며, 이 같은 과정이 진행된 상태에서 방문을 하면 안내시 그 인원은 `방문` 상태가 아닌 `의류준비`로 바로 넘어갈 수 있도록 해야 합니다.

**Comment by keedi** [comment]
회의 중입니다.

변경 내용을 기록합니다.

> 3개월 이내 재방문의 경우

3개월 이내가 아니고 모든 기록 기준이었으면 좋겠다고 합니다.

> 원하는 의류사이즈를 체크

의류 사이즈를 체크한다기 보다는 빌렸던 기록을 열람하게 해주고, 그 옷이 마음에 들어서 다시 빌리고 싶은지, 아닌지, 또는 없으면 유사 사이즈를 원하는지, 아니면 더 큰 옷을 원하는지, 작은 옷을 원하는지, 또는 다 마음에 드는데 색상만 바꾸고 싶은지 등의 의향을 확인하고 싶다는 의미라고 합니다.

> 대여 일로 선택할 수 있도록 함

여러 벌을 빌렸다면 언제 빌렸던 옷을 기준으로 말하고 싶어하는지 모를 수 있기 때문에 빌렸던 주문서 목록의 날짜와 대여 항목을 보여주면서 의사를 묻고 싶다고 합니다.

**Comment by keedi** [comment]
회의 완료했습니다.

> 지난 기록에 대해 질문을 하는 내용에 대해서는 다시 정리하여 올리도록 하겠습니다.

상기 내용 피드백 확인 후 작업 진행합니다.

**Comment by 10001if** [comment]
어떤 순서에 넣을지는 아직 결정하지 못했습니다.
내용만 우선 올려놓습니다.

000님, 
0000년 00월 00일에 마지막으로 열린옷장에 방문하였습니다.

1. 마지막 방문 이후로 체중 변화가 있다면 '사이즈 다시 측정' 버튼을 클릭해주세요. 
열린옷장 방문 시, 신체 사이즈를 다시 측정하여 변화된 신체 사이즈에 맞는 의류를 추천해 드립니다.

2. 지난 대여의류를 다시 대여하고 싶다면 '대여 했던 의류 착용' 버튼을 클릭해주세요.
* 선택한 의류가 대여중일 경우 비슷한 사이즈의 의류로 대체될 수 있습니다.
** 베스트핏은 의류가 000님께 잘 맞았던 경우, 열린옷장에서 기록한 정보입니다. 의류 선택시 참고해주세요.

- [ ] 사이즈 다시 측정
- [ ] 대여 했던 의류 착용
- [x] <2016.12.23> | 자켓, 바지, 셔츠, 타이, 구두, 벨트 | 베스트핏 
- [ ] <2016.09.25> | 자켓, 바지

**Comment by 10001if** [comment]
@keedi 내용은 정했는데 들어가야 할 순서 때문에 고민되는 부분이 있어서, 오시면 이슈에 대해 논의하고 결정하였으면 합니다.

**Comment by 10001if** [comment]
@Bentleypark 구원 요청입니다~

**Comment by Bentleypark** [comment]
<img width="447" alt="2017-07-02 6 05 47" src="https://user-images.githubusercontent.com/8054417/27768591-36604da4-5f52-11e7-8153-81bc1efb5361.png">
 방문대여 예약 페이지에서 대여품목을 선택하는 옵션 바로 위쪽에  "지난 대여의류 신청" 버튼을 생성하여, 대여자가 직접 지난 대여 의류 및 신체치수 재 측정 여부를 선택할 수 있도록 합니다. 

<img width="544" alt="2017-07-02 6 12 34" src="https://user-images.githubusercontent.com/8054417/27768622-a8e878b0-5f52-11e7-91b7-890c898fc961.png">
세부 내용을 보충하면. 여성분들은 블라우스 선택할 수 있도록 기능이 필요하며, 지난 대여 의류 중에 불편한 점을 직접 텍스트로 입력할 수 있도록 기능이 필요합니다.

**Comment by aanoaa** [comment]
![default](https://user-images.githubusercontent.com/170528/27859346-700f8b92-61b3-11e7-96f1-be598005d21c.png)

착용날짜와 대여품목 사이에 아래와 같은 라디오 버튼을 넣어서 대여했던이력중에 선택할 수 있도록 합니다.

    [ ] <2016.12.23> | 자켓, 바지, 셔츠, 타이, 구두, 벨트
    [ ] <2016.09.25> | 자켓, 바지

선택된 텍스트는 의류준비화면에 보여질 수 있도록 합니다.(`사용자정보.설명` 입니다.)

**Comment by aanoaa** [comment]
블라우스 종류를 선택할 수 있도록 하는 문제도 같이 해결이 되었으면 합니다.

**Comment by 10001if** [comment]
이렇게 기존 기록으로 대여를 희망하는 경우에는 방문 전 미리 준비가 가능할 것으로 보입니다. 다만, 다른 표시가 있어야 합니다. 

예를 들어 시간표 상에 `재대여희망` 과 같은 표시를 나타내고 preparation 화면에서도 동일한 표시를 보여주면 미리 준비할 수도 있고 신체치수를 통해 넘어온 정보를 보고도 바로 준비할 수 있을 것입니다.

**Comment by aanoaa** [comment]
지난 대여중에 맘에드는 의류가 있었다면 방문예약할때에 대여자가 선택할 수 있게 해서 staff 가 의류를 선택할때 더 쉽게 도움이 되고자 하는 기능입니다.
온라인 서비스에서는 이미 되고 있는 기능입니다.

![default](https://user-images.githubusercontent.com/170528/29200756-dc5de4c8-7e92-11e7-9f63-537089c09d36.png)

**Comment by 10001if** [comment]
@aanoaa 대여자가 지난 의류기록을 선택하면 사용자 정보에서 그 내역을 확인할 수 있나요? prepration 화면에 해당 정보를 알리기 위해서는 종전과 같이 지난 대여의류 기록 버튼을 눌러 설명란에 입력하는 방식으로 진행되는 건가요? 테스트로 예약을 해보았는데, 다른 정보를 확인할 수 없어서 문의드립니다~

**Comment by 10001if** [comment]
@aanoaa 다시보니, 사용자 정보에는 따로 표시가 없고 prepration 화면에 `00-00 의류 대여 희망합니다` 가 표시되는 걸로 확인 됩니다. 지난 대여 기록으로 의류를 대여하길 희망하는 경우에 해당 정보를 입력받는 것은 다음과 같은 장점을 가지고 있습니다.

1. 방문 전에 미리 의류를 준비해 놓을 수 있다. 
대리 대여와 유사한 경우입니다. 그 의류가 있다면 동일한 의류를, 해당 의류가 없어도 
신체 사이즈의 변화가 없고 동일하다면 해당 사이즈에 맞는 의류를 미리 준비해 놓을 수 있습니다. 하지만 이를 위해서는 시간표에 지난 대여의류를 희망하는 사람이라는 안내가 되어야 합니다. (대리대여처럼 표시가 필요)

2. 구두, 타이처럼 방문시 신체치수 측정 과정 없이 바로 의류준비로 넘어가도록 한다.
본 경우도 신체치수 단계가 필요없으므로 현장에서 방문 예약 확인을 하면 https://github.com/opencloset/opencloset/issues/1068 이슈에서처럼 바로 의류준비로 넘어갈 수 있도록 하고자 합니다.

**Comment by aanoaa** [comment]
대여했던 의류를 다시 대여하고자 할때 **단축된 절차**를 사용하실 생각인가요?

단축된 절차는 아직은 그렇게 하고 있지 않으므로 원하시는 바를 설명해주세요.
당일 아침에 목록을 확인해서 모든 의류를 포장해놓고 대여자가 방문하면 바로 결제하고 대여하는 방식인가요?

**Comment by 10001if** [comment]
>당일 아침에 목록을 확인해서 모든 의류를 포장해놓고 대여자가 방문하면 바로 결제하고 대여하는 방식인가요?

@aanoaa 네, 단축된 절차를 사용할 계획입니다. 구체적으로 어떻게 진행하고 싶은지 작성해놓겠습니다. 당일 아침에 목록을 확인하여 준비해 놓으면 미리 준비하는 과정을 통해 시간을 더 단축시킬 수 있고 사이즈가 기입된 대리대여나, 다시 대여하고자 하는 대여자가 속한 예약타임에는 업무가 과중되지 않으므로 더 많은 인원의 예약을 진행할 수 있습니다. 

다만, 차후에는 이런 경우 가능하다면 온라인 택배를 통해 배송받는 절차를 안내하여 온라인으로 의류를 제공할 수 있도록 변경하고자 합니다. 원하는 바를 작성해 놓겠습니다.

**Comment by 10001if** [comment]
@aanoaa 원하는 기능은 다음과 같습니다.

1. 원하는 의류가 있는 경우, 입구에서 예약확인을 진행하면 그 다음 상태가 `방문`이 아니라 `의류준비`로 바로 진행될 수 있도록 요청드립니다. 구두, 타이만 하는 경우와 동일한 절차입니다.

2. 시간표에 대리인과 유사하게 표시를 두어 시간표만 보고도 미리 의류를 준비할 수 있도록 하려고 합니다. 이를 위해 다른 표시를 할 수 있도록 아래와 같이 적용 요청드립니다. 이렇게 바로 찾아야 하는 경우가 1) 방문 전 예약시에 대여희망을 선택한 경우와 2) 미리 입어본 경우도 해당하므로 두 가지를 구분하는 것이 필요합니다.

우선 이번 경우에는 화살표 대신 마우스를 넣어주시면 될 것 같습니다. 방문 전 대여희망을 마우스로 체크했다고 이해하면 될 것 같네요. 

이렇게  두 가지 이슈 적용을 요청드립니다.

**Comment by 10001if** [comment]
@aanoaa 2번을 요청드린 이유는 옷을 찾아드리기 위해 방문을 기다리지 않아도 되는 분들인 경우 아침 시간이나 중간에 있는 여유 시간을 활용하여 의류를 미리 준비해 놓기 위함입니다. 이를 위해 위에서 요청드린 시간표 표시 외에 다음을 요청드립니다.

1. 시간표 상에 미리 입어보거나, 대여를 희망하는 사람들의 인원을 표시하고자 합니다. 둘의 합계 수를 표시하고자 합니다.
![2017-09-13 4 02 23](https://user-images.githubusercontent.com/4696328/30364880-f5f2b01c-98a0-11e7-84f7-6ac3015f6d4e.png)
2. 주문서에서 미리준비를 누르면 미리 준비해야 하는 당일의 목록을 보여줍니다. 다음 표를 보고 미리 한번에 의류를 준비하고자 합니다. 따라서 아래와 그림과 같이 대여시간, 대여희망품목, 의류코드와 사이즈, 의류 상태가 필요합니다. 의류 사이즈는 다음과 같습니다. 

![2017-09-13 4 02 11](https://user-images.githubusercontent.com/4696328/30365006-5f27c1c6-98a1-11e7-841b-bfdc3bac2318.png)

1) 남자 자켓 : 윗배 - 팔길이 - 가슴, 남자바지 : 허리 - 허벅지 - 바지길이
2) 여자 자켓 : 윗배 - 팔길이 - 가슴, 여자바지 : 허리 - 허벅지 - 바지길이, 여자 스커트 : 엉덩이 - 허리 - 기장

**Comment by 10001if** [comment]
미리준비의 주문서에는 반납예정일과 담당자가 나타나지 않을 것입니다.

**Comment by 10001if** [comment]
@aanoaa 잘 이해되지 않거나 필요한 부분이 있으시면 알려주세요. 더 상세하게 작성하도록 하겠습니다.

**Comment by 10001if** [comment]
@keedi 필요한 작업입니다. 하지만 최초에 요청했던 이슈가 완료되었으므로 이슈 닫겠습니다. 피드백으로 요청드리는 내용은 별도의 이슈에 정리하였습니다.
