### ISSUE TITLE
구두 및 타이만 대여하는 경우 대여 화면에서 주문서 상태를 바로 의류준비로 변경할 수 있게 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1068]
구두, 타이만 대여하는 경우에는 신체사이즈 측정을 기다릴 필요가 없습니다.

때문에 구두 or 타이만 대여하는 경우에는 예약탭에서 구두/타이만 대여한다는 표시를 해주고 구두는 사이즈가 필요하므로, 사이즈 입력창이 추가로 나타나도록 해야합니다. 그래서 구두의 사이즈 입력이 끝나면 `방문예약`에서 `방문`이 아니라 `방문예약`에서 `의류준비`로 바로 상태가 전환될 수 있도록 요청드립니다.. ^^

**Comment by keedi** [comment]
담당자 변경합니다.

**Comment by keedi** [comment]
시간표 페이지에서 주문서의 상태를 변경할 수 있습니다. 하지만 열린옷장에서 업무 프로세스가 바뀌면서 입구에서 방문을 받고, 포장 및 결제까지 3 가지 업무를 진행하도록 되었습니다. 이로 인해 기존 시간표 페이지에서 상태를 변경하는 것은 너무 불편하므로 대여 페이지에서 주문서의 상태를 변경할 수 있도록 해달라는 요청이 있어 #ᅟ929 이슈에서 해결되었습니다.

본 이슈는 시간표 페이지가 아닌 대여 페이지에서 구현 되어야 하는 이슈 입니다.

**Comment by keedi** [comment]
현재 대여 페이지에서는 다음과 같은 화면에서 **방문예약 -> 방문** 상태로 변경하고 있습니다.

![screenshot-monster silex kr 10301-2017-01-20-15-37-25](https://cloud.githubusercontent.com/assets/138451/22138961/b0b8b674-df26-11e6-9112-f7cd6539de47.png)

새롭게 원하는 기능은 대여자가 빌리는 의류가 구두 또는(그리고) 타이일 경우 상기 버튼 우측에 또 다른 버튼을 배치하는 것입니다. 더불어 이 때 구두가 있을 경우 구두의 사이즈를 입력할 수 있어야 한다고 합니다.

**Comment by keedi** [comment]
방금 회의를 통해 무슨 기능을 요구하는 것인지 정확히 전달 받았습니다.

**Comment by keedi** [comment]
진행합니다.

**Comment by keedi** [comment]
다시 진행합니다.

**Comment by keedi** [comment]
작업 중 핸들바를 이용한 jst 처리에서 다음과 같은 표기법이 동작하지 않음을 확인했습니다.

```coffeescript
  $('#query.typeahead').on 'typeahead:select', (e, data) ->
    data.status = OpenCloset.status
    template    = JST['rental/typeahead-select']
    html        = template(data)
    $('#selected').html(html)
```

```html
  <a href="/api/order/{{order_id}}" class="btn btn-xs btn-success btn-update-status" data-status-id="{{status_id['방문'].id}}">
    방문예약
    <i class="icon-arrow-right"></i>
    방문
  </a>
```

상기와 같이 사용할 경우 `grunt`시 다음과 같은 오류가 발생합니다.

```plain
Running "handlebars:compile" (handlebars) task
>> Error: Parse error on line 12:
>> ..." data-status-id="{{status['방문'].id}}">
>> -----------------------^
>> Expecting 'ID', 'STRING', 'NUMBER', 'BOOLEAN', 'UNDEFINED', 'NULL', 'DATA', got 'INVALID'
Warning: Handlebars failed to compile public/jst/rental/typeahead-select.html. Use --force to continue.

Aborted due to warnings.
```

관련해서 `[...]` 표기법이 완벽하게 지원되지 않는 것으로 보이며 `.`를 대체해서 사용할 경우 잘 동작함을 확인했습니다. 하지만 사용하고 있는 속성이 한글인 관계로 `.` 표기로 사용하기에는 찜찜한 부분이 있어 속성을 대체하거나 또는 표기법을 대체하는 것이 나을 것 같습니다.

관련해 일단은 필요한 부분만 핸들바쪽으로 넘겨주는 식으로 해결합니다.

```coffeescript
  $('#query.typeahead').on 'typeahead:select', (e, data) ->
    data.status =
      visited:         OpenCloset.status['방문'].id
      prepare_clothes: OpenCloset.status['의류준비'].id

    template = JST['rental/typeahead-select']
    html     = template(data)
    $('#selected').html(html)
```

```html
  <a href="/api/order/{{order_id}}" class="btn btn-xs btn-success btn-update-status" data-status-id="{{status.visited}}">
    방문예약
    <i class="icon-arrow-right"></i>
    방문
  </a>
```

**Comment by keedi** [comment]
구현된 화면은 다음과 같습니다.

![screenshot-monster silex kr 10301-2017-02-15-21-23-09](https://cloud.githubusercontent.com/assets/138451/22975006/575106de-f3c8-11e6-9e16-55bfcb9759a4.png)

**Comment by keedi** [comment]
릴리스 이후에 피드백을 받는 경우가 많기 때문에 머지 전에 피드백을 받은 후 확인 한 다음 머지하겠습니다.

**Comment by 10001if** [comment]
@keedi 요청드린 내용이 정확히 전달되었습니다. 구현된 화면으로 진행되면 문제 없습니다. 감사합니다.

**Comment by keedi** [comment]
방금 머지했습니다.

**Comment by keedi** [comment]
@10001if  테스트 서버에 배포 완료했습니다. 테스트 부탁드립니다. :-)

**Comment by 10001if** [comment]
@keedi 확인 완료했습니다. 정상적으로 잘 작동됩니다.

**Comment by keedi** [comment]
이슈 닫습니다. :-)

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
