### ISSUE TITLE
대리 대여자에 대한 정보를 추가적으로 받도록 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1070]
현재 대리로 대여하는 대여자에 대한 문제들이 지속적으로 발생하고 있습니다.
따라서 다음과 같은 방법이 필요하다고 @keedi 이야기 주셨습니다.

실제 착용자가 아닌 경우 대리로 대여하는 자의 정보를 따로 기록하는 것이 필요한데
이는 온라인 주문을 신청할 때 주문자의 정보와 동일합니까? [o] 
본 항목에 체크하면 자동으로 배송지가 결정되는 것 과 같은 항목을 말합니다. 
구체적인 내용은 @keedi 추가적인 논의가 필요합니다.

**Comment by 10001if** [comment]
@keedi 본 문제도 적극적으로 해결해야 하는 이슈입니다. 궁금한 부분을 물어봐주시거나 의견을 주시면 답변 드리도록 하겠습니다.

**Comment by aanoaa** [comment]
#1066 에서 진행하겠습니다.
