### ISSUE TITLE
4층 반납메모 글씨 색상을 변경하고 글씨의 크기를 키움

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1074]
![2016-11-28 4 26 25](https://cloud.githubusercontent.com/assets/4696328/20659697/96729ef0-b588-11e6-9cca-ad04f3b31fb8.png)

상단에 띄웠음에도 불구하고 글씨가 작아 잘 확인하지 못하는 경우가 많다고 합니다.

글씨의 색상을 변경하고 크기를 키워 더 잘 보이도록 요청드립니다. ^^;

취업날개 신분증 확인 이슈를 맞물려 있어서 빠른 작업 요청드리겠습니다. ^^

**Comment by aanoaa** [comment]
![- 2016-11-28 16-37-20](https://cloud.githubusercontent.com/assets/170528/20659764/f7e8bb74-b588-11e6-83c9-f61bf109943a.png)

이미 적용되어 있습니다.
더 키우나요?

**Comment by 10001if** [comment]
지금 적용되어 있는 크기와 색깔이면 됩니다! 감사합니다. ^^
