### ISSUE TITLE
쉬운 방문 예약시간 변경과 취소

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1075]
기존의 예약 시간 확인 문자에 본 내용이 추가되었으면 합니다. 

'예약' 꼭 지켜주세요! 
열린옷장은 많은 분들은 '멋질 권리'를 위해 최선을 다하고 있습니다. 원활한 대여를 위해 함께 해주세요! 

1. 지각은 NO!
열린옷장에는 하루에 최대 100명의 대여자가 다녀갑니다. 단 5분의 지각도 하루의 대여 환경을 혼란스럽게 만듭니다. 꼭 예약 시간에 방문해주세요. ※ 예약한 시간에 방문하지 않는 경우, 정시에 방문한 대여자를 먼저 안내하기 때문에 늦거나 일찍 온 시간만큼 대기시간이 길어집니다. 

예약시간을 변경 하려면, 아래의 '예약시간 변경하기'를 클릭하여 예약 시간을 수정해주세요. 예약을 변경하고자 하는 경우, 예약인원이 초과되어 예약이 되지 않을 수 있습니다. 정시에 방문이 어려운 경우에는 예약이 초과되기 전에 미리 예약시간을 변경해주시기 바랍니다. <예약시간 변경하기>

2. 노쇼(no show)금지
예약한 일시에 방문하지 못하는 경우 반드시 예약을 '취소' 해주세요. 
열린옷장은 100% 예약제로 운영되기 때문에 하루에 방문 가능한 예약 인원이 정해져 있습니다. 예약을 '취소'하지 않는 경우, 방문이 필요한 다른 분이 열린옷장을 이용 할 수 없습니다. 방문이 필요한 다른 분을 위해 반드시 '예약취소' 해주세요. ※ 방문이 어려운 경우 적어도 예약시간 세 시간 전까지는 예약을 취소 해주세요. <방문예약 취소하기>

**Comment by aanoaa** [comment]
지금의 봉사활동 취소처럼 문자메세지에 링크를 제공해주고 버튼 한번 누르는 걸로 취소하게 할 수도 있습니다.
사용자 입장에서는 더욱 편리합니다.

인증은 `주문서 id + 사용자 휴대폰번호 뒷자리`로 사용합니다.
문자메세지에 `주문서 id + 사용자 휴대폰번호 뒷자리` 가 포함된 링크를 만들어서 붙여주고 버튼 하나로 취소할 수 있게 합니다.

```
xxx님 x월 x일 x시 x분으로 방문 예약이 완료되었습니다.
<열린옷장 위치안내>
서울특별시 광진구 아차산로 213 국민은행, 건대입구역 1번 출구로 나오신 뒤 오른쪽으로 꺾어 150M 가량 직진하시면 1층에 국민은행이 있는 건물 5층으로 올라오시면 됩니다. (도보로 약 3분 소요)
지도 안내: https://goo.gl/UuJyrx
```

쉬운 취소를 사용하고자 한다면 문자 메세지 내용이 바뀌어야 합니다.

**Comment by aanoaa** [comment]
원하는 기능은 이렇습니다.

예약시간만 변경이 가능한 화면이 필요
인증은 `주문서 ID + 폰뒷자리` 로 문자메세지에 포함되어 있고 다시 인증을 시도 하지 않습니다.
취소는 버튼 클릭 한번으로 가능하고 예약시간 변경도 가능한 시간대 버튼을 나열해주고 선택할 수 있도록 합니다.

**Comment by 10001if** [comment]
@aanoaa 제가 문자 내용을 수정하였습니다. 상단의 내용을 추가해주시면 됩니다. 요청드립니다. ^^

**Comment by aanoaa** [comment]
![400 bad request - 2016-11-29 17-29-26](https://cloud.githubusercontent.com/assets/170528/20702049/687feeea-b659-11e6-8e04-48f8c3223a46.png)

잘못된 접근이라거나, 링크가 잘못되었을때 사용자에게 에러화면을 보여주려합니다.
지금의 bad request, not found 같은 경우에 staff 을 위한 화면입니다.

일반 사용자에게 보여주기에는 적절하지 않습니다.

- 에러 처리를 할때에 템플릿을 지정할 수 있도록 하거나(에러처리확장)
- 지금의 에러 화면을 바꾸는 방안이 있습니다.

cc @keedi @yongbin

**Comment by aanoaa** [comment]
이번에 추가되는 기능은 로그인 없이 예약을 취소하거나 예약시간을 변경하는 기능입니다.
로그인되지 않은 사용자는 api 호출을 할 수 없습니다.
해서, booking-list 를 얻어올 수 없습니다.

mojolicious 에서 action -> action 을 호출할 방법이 있을려나 모르겠습니다.

**Comment by aanoaa** [comment]
`api#gui_booking_list` 의 결과가 필요한데 호출할 방법이 없다면,
중복된 코드를 작성하거나, helper 로 만들어야 할 것 같습니다.

**Comment by aanoaa** [comment]
방문예약시간이 지났다면 예약시간을 변경할 수 없도록 해야 할까요?
이런 경우는 예약했지만 방문하지 않고 시간만 변경해서 방문이 가능합니다.

어찌보면 더 편리한 기능이긴 합니다.
기존에 입력했던 내용들을 다시 입력하지 않아도 되거든요.

미방문하고 한달뒤에 문자 찾아서 예약시간을 변경하고 이용할 수도 있습니다.
(악용인가..?)

**Comment by aanoaa** [comment]
![2016-11-30 14-40-03](https://cloud.githubusercontent.com/assets/170528/20741146/a392a74a-b70b-11e6-8e93-19646c8532ac.png)
![2016-11-30 14-40-33](https://cloud.githubusercontent.com/assets/170528/20741147/a3968cde-b70b-11e6-8d2a-985f77d6fe3e.png)

**Comment by aanoaa** [comment]
- staff 이 아닌 사용자에게 보여질 에러 화면을 어떻게 처리할 것인지
- 방문예약시간이 지난 주문서에 대해서도 방문예약시간을 변경할 수 있도록 할 것인지

를 결정해야 합니다.

**Comment by aanoaa** [comment]
방문예약시간 변경에 관련한 문의전화가 너무 많이 와서 4층 업무에 지장이 있다고 합니다.

**Comment by MoDoLEE** [comment]
예약할 때와 마찬가지로 헷갈림을 방지하기 위해서 시간 변경과 취소 시 요일도 함께 표시해 주는게 좋을 것 같습니다.

**Comment by 10001if** [comment]
'예약' 꼭 지켜주세요! 
열린옷장은 많은 분들은 '멋질 권리'를 위해 최선을 다하고 있습니다. 원활한 대여를 위해 함께 해주세요! 

1. 지각은 NO!
열린옷장에는 하루에 최대 100명의 대여자가 다녀갑니다. 단 5분의 지각도 하루의 대여 환경을 혼란스럽게 만듭니다. 꼭 예약 시간에 방문해주세요. ※ 주의 : 예약한 시간에 방문하지 못한 경우, 정시에 방문한 대여자를 먼저 안내하기 때문에 늦거나 일찍 온 시간만큼 대기시간이 길어집니다. 

2. 예약시간은 어떻게 변경하나요?
예약시간을 변경 하려면, 아래의 '예약시간 변경하기'를 클릭하여 예약 시간을 수정해주세요. 변경하는 시간의 예약인원이 초과되어 있으면 처음 예약과 동일하게 예약변경이 허용되지 않습니다. 예약한 시간에 방문이 어려운 경우 예약인원이 초과되기 전에 미리 예약시간을 변경해주시기 바랍니다. <예약시간 변경하기>

3. 노쇼(no show)금지 
예약한 일시에 방문하지 못하는 경우 반드시 예약을 '취소' 해주세요. 
열린옷장은 100% 예약제로 운영되기 때문에 하루에 방문 가능한 예약 인원이 정해져 있습니다. 방문이 필요한 다른 분을 위해 반드시 '예약취소' 해주세요. ※ 방문이 어려운 경우 적어도 예약시간 세 시간 전까지는 예약을 취소 해주세요. <방문예약 취소하기>

**Comment by aanoaa** [comment]
예약시간변경의 경우, 예약시간이 지났다고 하더라도 지금과 같은 날짜라면 예약시간을 변경할 수 있도록 하고,
지난 경우에는 변경할 수 없도록 해야 합니다.

예로 지금 `2016-12-01T14:00` 인데, `2016-11-30T17:00` 예약인 경우에는 변경할 수 없고,
`2016-12-01T10:00` 예약은 변경할 수 있습니다.

**Comment by aanoaa** [comment]
2016-12-01 13:00:00
    2016-12-01 (목요일) 	13:00 4명 예약 가능 

이런식으로 요일과 함께 예약가능 인원을 표시해줘야 합니다.

**Comment by aanoaa** [comment]
![2016-12-01 13-09-07](https://cloud.githubusercontent.com/assets/170528/20781588/618f7cd0-b7c7-11e6-8153-ae478925814b.png)

예약이 꽉 찬 시간은 표시하지 않았습니다.

**Comment by aanoaa** [comment]
![2016-12-01 13-28-49](https://cloud.githubusercontent.com/assets/170528/20781881/202cbaf2-b7ca-11e6-8356-5638a11dff5e.png)

제가 이해가 좀 부족했습니다.
예약가능한 시간대는 열어두고 예약이 꽉찬 시간대는 선택할 수 없도록 수정하였습니다.

**Comment by aanoaa** [comment]
`0명 예약 가능`

대신에

~~`예약인원초과`~~

로 보여져야 합니다.

**Comment by aanoaa** [comment]
``` perl
return $self->error( 400, { str => 'booking_id is required' } ) if $v->has_error;
```

이와 같은 방식으로 간단한 에러처리를 해왔습니다.
허나 사용자가 보기에 적절하지 않은 에러 화면이라서,

``` perl
return 
    $self->error( 400, { str => 'booking_id is required' }, 'path/to/template' )
    if $v->has_error;
```

처럼 템플릿을 지정할 수 있도록 수정하였습니다.

**Comment by aanoaa** [comment]
![2016-12-01 13 58 25](https://cloud.githubusercontent.com/assets/170528/20782342/4173b77a-b7ce-11e6-8d48-25c86e552dd3.png)

**Comment by aanoaa** [comment]
@10001if SMS 내용만 추가되면 배포 가능합니다.

**Comment by 10001if** [comment]
예약시간 변경/취소는 ~~에서 가능합니다.

1. 지각은 NO!
꼭 예약 시간에 방문해주세요. 예약한 시간에 방문하지 못한 경우, 정시에 방문한 대여자를 먼저 안내하기 때문에 늦거나 일찍 온 시간만큼 대기시간이 길어집니다.

2. 예약시간 변경안내
변경하는 시간의 예약인원이 초과되어 있으면 예약시간을 변경 할 수 없습니다. 예약한 시간에 방문이 어려운 경우 예약인원이 초과되기 전에 미리 예약시간을 변경해주시기 바랍니다. 

3. 노쇼(no show)금지
열린옷장은 하루에 방문 가능한 예약 인원이 정해져 있습니다. 방문이 어려운 경우 다른 분을 위해 반드시 '예약취소' 해주세요. 적어도 예약시간 세 시간 전까지는 예약을 취소 해주세요.

**Comment by 10001if** [comment]
예약시간 변경/취소는 ~~에서 가능합니다.

1. 지각은 NO!
꼭 예약 시간에 방문해주세요. 예약한 시간에 방문하지 못한 경우, 정시에 방문한 대여자를 먼저 안내하기 때문에 늦거나 일찍 온 시간만큼 대기시간이 길어집니다.

2. 노쇼(no show)금지
열린옷장은 하루에 방문 가능한 예약 인원이 정해져 있습니다. 방문이 어려운 경우 다른 분을 위해 반드시 '예약취소' 해주세요. 예약취소는 세 시간 전까지 가능합니다.

**Comment by 10001if** [comment]
@aanoaa 

> 예약시간 변경/취소는 ~에서 가능합니다.

주소가 조금 이상한 것 같습니다. 확인해보니 기존에 변경/취소 주소로 이동하네요.

확인 부탁드릴게요 ^^

**Comment by aanoaa** [comment]
SMS 상의 주소는 맞는데, 방문예약 화면으로 redirect 됩니다.

**Comment by aanoaa** [comment]
제가 착각했습니다.
오타가 있어서 url 이 잘못되어 있습니다.

**Comment by aanoaa** [comment]
7a392f86c3181488ca91e39dec4015112ec60671

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
