### ISSUE TITLE
미납문자전송 내용 수정

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#1078]
[열린옷장] xxx님, 0일 연장, 2일 연체로 추가 금액 19,200원이 발생하였습니다. 금일 중으로 국민은행 205737-04-003013 (예금주 : 사단법인열린옷장)으로 입금해주세요.

0일 연장 이라고 한다면 메세지 내용에서 빠지도록 해야 합니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
