### ISSUE TITLE
이용약관 내용의 수정

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1079]
제8조 손상 및 분실
① 대여자는 대여한 의류의 손상 및 분실 시 열린옷장 담당자에게 즉시 알려야 합니다.
② 대여 이후의 의류손상은 대여자의 부주의로 간주 되므로 본 경우의 배상책임은 대여자에게 있습니다. 열린옷장은 대여된 의류의 손상 및 분실에 대하여 책임이 없습니다. 
③ 대여한 의류가 손상된 경우 대여자에게 손상비가 산정되어 청구되고, 손상으로 인하여 사용이 불가능한 경우 대여 금액의 5배에 해당하는 금액이, 분실의 경우에는 금액의 10배에 해당하는 금액이 청구됩니다.
④ 의류 대여 이전에 손상이 발견된 경우, 열린옷장은 그 손상비를 청구할 수 없습니다.

이용약관의 본 항목 수정 요청드립니다. ^^

**Comment by aanoaa** [comment]
방문예약에서의 이용약관 말씀하시는거죠?
홈페이지의 이용약관은 제가 관리하고 있지 않습니다.

**Comment by 10001if** [comment]
@aanoaa 네. 맞습니다. 방문예약 이용약관 수정 부탁드립니다. :)

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
