### ISSUE TITLE
택배 반납 수와 비율 정보를 요청

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1080]
택배 반납과 방문 반납의 실제 수를 확인하고자 합니다.

월별 | 택배반납 |비율| 방문반납 |비율|월대여자
----|-----|---|---|-----|-----
2015-01|00|00%|00|00%|0000
2015-02|00|00%|00|00%|0000
..|..|..|..|..|..
2016-11|00|00%|00|00%|0000

* 비율은 월대여자를 기준으로 합니다.

요일별 | 택배반납 |비율| 방문반납 |비율|월대여자
----|-----|---|---|-----|------
월|00|00%|00|00%|0000
화|00|00%|00|00%|0000
..|..|..|..|..|..
일|00|00%|00|00%|0000

본 통계는 다음 주 월요일까지 요청드립니다.

**Comment by yongbin** [comment]
order.`return_method` 컬럼을 참고해야합니다.

**Comment by yongbin** [comment]
```sql
SELECT SUBSTR(return_date,1,7) AS 'month',DAYNAME(rental_date) AS 'weekday' , return_method FROM `order`
WHERE `status_id` = 9
```

위 쿼리로 구한 결과를 다음과 같이 후처리 합니다.

```perl
use strict;
use warnings;

use v5.20;
use Text::CSV_XS qw/csv/;
use Data::Dumper;
use List::Util qw/any/;
use utf8;

binmode STDOUT,':utf8';


my $visit = qr(^방문반납,?$);
my @parcel= qw/ CJ대한통운 CSVnet편의점 KGB 기타 동부 로젠 옐로우캡 우체국 한진 현대 /;

my $aoh = csv( in => "query_result.csv", headers => "auto" );

my @result;
for my $row ( @$aoh ) {
    #next if $row->{return_method} =~ /^NULL$/i;

    my @data = split(/,/, $row->{return_method});
    my $method;

    if( any { $_ eq $data[0] } @parcel ) {
        $method = '택배';
    } else {
        $method = '방문반납';
    }
    push @result, { %{ $row } , 'method' => $method, pacel => $data[0] };
}

csv (in => \@result, out => "file.csv", encoding => 'utf-8');

```

그리고 결과를 LIbreoffice 의 피봇 테이블로 정리합니다.

## 요일별

![screenshot 2016-12-12 18 00 01](https://cloud.githubusercontent.com/assets/52704/21093425/1ad453b6-c095-11e6-9a96-6a9c0c836918.png)

## 월별

![screenshot 2016-12-12 17 59 54](https://cloud.githubusercontent.com/assets/52704/21093426/1c8c72f6-c095-11e6-959b-ed2f4a69e18d.png)

**Comment by yongbin** [comment]
한가지 의문점은 주문서중에 `반납(9)` 상태인 주문서중에 상당수가 `return_method`가 NULL 입니다. 분석에서는 NULL인 경우 방문반납인것으로 처리했습니다.

**Comment by 10001if** [comment]
@yongbin 

> 한가지 의문점은 주문서중에 반납(9) 상태인 주문서중에 상당수가 return_method가 NULL 입니다. 분석에서는 NULL인 경우 방문반납인것으로 처리했습니다.

내용을 잘 이해하지 못했습니다. 한번 더 설명 부탁드릴게요. 자료는 잘 받았습니다.

**Comment by keedi** [comment]
콕 찝어 주문서 번호를 몇개 알려줬으면 답변하기 쉬웠을텐데 그런 것이 없으니 대충 답하면 택배 반납이 처음부터 있던 기능도 아닐거고 어쨌든 명시적으로 택배라고 적지 않았다면 방문 반납이라고 보는게 맞을테지만 아닌 경우가 있다면 알려주세요. 여튼 그렇습니다.

**Comment by yongbin** [comment]
확인결과 `return_method` 컬럼은 택배가 있는경우만 입력을 합니다. 선택지중 '방문반납'이 있기때문에 조금 혼란이 있었지만, 이 이슈에서 처리한 방법은 큰 문제가 없어보입니다. @10001if  자료에 문제 없다면 이슈 닫아주세요

**Comment by 10001if** [comment]
네, 그럼 이슈 닫도록 하겠습니다.
