### ISSUE TITLE
택배발송알리미, 연장 URL 오류

### ISSUE THREAD

**Issue by MoDoLEE** [opencloset/opencloset#1084]
대여 시 발송되는 SMS에 포함된 택배발송알리미와 연장 URL이 잘못된 형태로 전송되고 있습니다.

~/46221/return 를 받아야되는 대여자가
~/51961/return 를 받았다고 문의가 왔습니다.

확인해본 결과 문의 주신 사용자의 주문서 번호는 46221이었고, 사용자 번호가 51961이었습니다.
택배, 연장을 위한 URL이 현재 주문서번호가 아니라 사용자번호로 전송되고 있는 것 같습니다.

이런 문제로 여러번 전화가 왔다고 합니다.
확인 부탁드리겠습니다~^^

**Comment by keedi** [comment]
먼저 확인한 내용부터 정리해보겠습니다.

실 서버에서 문자 전송 내역을 확인해보았습니다.

```
07043257521 -> 010*****888 (장ㅎㄹ) | https://.../order/51961/return | 2016-12-01 16:12:24
07043257521 -> 010*****895 (최ㅎㅇ) | https://.../order/51961/return | 2016-12-01 16:15:09
```

상기와 같은 문자 메시지 전송 내역이 있습니다. 일단 첫 번째 것은 엉뚱한 사람(장ㅎㄹ)에게 엉뚱한 내용이 잘못 전송된 것입니다. 두번째 것은 보내려는 사람에게 엉뚱한 내용이 전송된 것입니다. 정황상 최ㅎㅇ님께 보내려고 했던 것은 맞아보이니 두번째 것은 받는 사람 번호는 제대로 넣었으나 url이 잘못된 것이죠.

시각은 12월 1일 오후 4시 12분과 15분 짧은 3분 사이에 있었구요.

내용은 앞뒤 아무런 설명없이 URL만 SMS로 전달 된 것 같습니다.

상기 내용으로 추측컨대 확인해야 할 부분은 다음과 같습니다.

- 시스템에서 아무런 문구없이 URL만 보내는 경우가 있는가? 방금 확인 결과 없어보이긴 했지만, @aanoaa 님의 확인이 필요합니다.
- 만약 상기 확인상 URL만 보내는 경우가 없다면 열린옷장에서 직접 받을 사람을 지정하고, 내용을 만들어서 전송했을 가능성이 있습니다. 그랬던 적이 있는가? 확인이 필요합니다.

현재까지 제가 확인한 바로는 코드상으로는 주문서 식별 번호와 사용자 식별 번호를 혼용해서 URL을 생성하는 없었습니다만 조금 더 확인해보겠습니다. 코드상의 확인과 별개로 12월 1일 당시 잘못된 형태로 전송한 문자를 시스템이 아닌 직접 생성해서 문자를 보낸적이 있는가 확인 부탁드립니다.

**Comment by 10001if** [comment]
@MoDoLEE @keedi 이 건은 문제가 없는 건입니다.

~/46221/return 를 받아야되는 대여자가
~/51961/return 를 받았다고 문의가 온게 아니라 

46221은 order 번호이고
51961은 user 번호인데

이 대여자가 택배 알리미 문자가 삭제되어, 옷장지기에게 재발송 요청한 것입니다.
그런데 옷장지기가 실수로 유저번호를 넣어 문자를 발송한 것입니다. 
당일 문자 발송한 옷장지기에게 확인 완료하였습니다.
옷장지기가 유저번호와 오더번호의 차이를 알지 못해 발생한 해프닝이었습니다.

그리고 택배발송 알리미가 잘 되지 않는다는 연락이 오고 있다고 전달받고는 있으나..
전화 연락과 동시에 실제 URL을 클릭하였을 때 오류가 발생한 경우를 아직은 확인하지 못하였습니다.
다시 확인해 보고 말씀드리겠습니다. 본 이슈는 우선 닫도록 하겠습니다.

**Comment by 10001if** [comment]
@keedi 엉뚱한 사람(장ㅎㄹ)님은 본 문자를 발송한 옷장지기 입니다. ^^
