### ISSUE TITLE
온라인 주문 신청 구현

### ISSUE THREAD

**Issue by keedi** [opencloset/opencloset#109]
방문 예약과는 별개로 온라인 주문 신청 페이지가 필요합니다. 현재는 홈페이지를 통해 구글 독스와 연계해서 사용하고 있으며 스태프가 수시로 구글 독스를 확인해서 온라인 주문 처리 및 발송을 한다고 합니다. 이를 개선하고 재고 관리 시스템과 통합하기 위해 온라인 주문 신청을 구현합니다.

**Comment by aanoaa** [comment]
이 이슈가 `기증`처럼 구체화되어서 만들어지면 온라인 대여의 발판이 될 것 같습니다.

**Comment by yongbin** [comment]
넵 그렇게 생각하고 있습니다.

**Comment by 10001if** [comment]
@yongbin 대표님 이슈가 구체화 될 수 있도록 저도 더 분발하겠습니다. 그리고 별도로 진행되던 온라인몰은 다음 주 초에 오픈할 예정이라고 합니다. 오픈되면 다시 공유드리겠습니다.

**Comment by 10001if** [comment]
@yongbin 과 이야기 나눈 내용을 옮겨놓습니다. 온라인 사이트 성공의 핵심은 검색이므로 검색의 완성도가 높아질 수 있는 것이 중요합니다. 따라서 현재 활용하는 검색의 구체적인 피드백을 전달하고 이 과정을 통해 정확도를 높여나가는 작업이 필요해 보입니다. 

그리고 이와는 별개로 온라인 사이트 설계/제작은 조금 더 속도를 내어서 진행하도록 하였면 합니다. 상반기 내로 오픈하여 하반기에는 온라인으로 의류를 공유할 수 있기를 희망합니다. ^^

**Comment by aanoaa** [comment]
가상의 대여자 홍길동씨가 온라인 주문을 통해 의류를 수령하고 반납하는 절차에 대한 시나리오가 필요합니다.

그 시나리오를 토대로 어떤 작업이 필요할지 해야할 일을 짐작할 수 있을 것 같습니다.

**Comment by yongbin** [comment]
넵 말씀하신 시나리오 준비하겠습니다.

**Comment by aanoaa** [comment]
뭔가 결과물을 만들어내려고 하지 말고 여기에 코멘트로 남겨주세요.

- 홍길동씨는...
- 어쩌고 저쩌고..

이런식으로요.

**Comment by aanoaa** [comment]
다른 이슈보다도 우선적으로 해주세요.

**Comment by yongbin** [comment]
넵 이 이슈를 가장 먼저 진행하겠습니다.

**Comment by yongbin** [comment]
-   율도국에 거주하고 잇는 홍길동씨는 (주)활빈당에 면접을 위해 정장이
    필요합니다. 인터넷 검색으로 '열린옷장'을 알게되었지만 율도국과 열린옷장의
    오프라인 매장은 너무 멀기때문에 온라인을 통해서 주문을 결정한다.

# 신청

-   홍길동씨는 브라우저에서 online.theopencloshet.net 에 접속한다.
-   홍길동씨는 과거 한번도 온라인 대여를 사용한 적이 없으며, 오프라인 매장을
    통해서도 대여한 이력이 없기때문에 별도의 회원가입 프로세스를 통해서
    열린옷장에 가입한다.
-   홍길동씨는 가입한 아이디와 비밀번호를 통해 로그인한다.
-   홍길동씨는 온라인페이지에서 '신청' 버튼을 눌러 온라인 대여 프로세스
    시작한다.
-   먼저 시스템은 홍길동씨의 과거 신체사이즈가 있는지 확인한다. 만약에 있다면
    직전 신체사이즈를 사용할지 여부를 물어본다.
-   과거 신체사이즈가 없거나 최근 살이쩌서 신체사이즈를 새로 측정하기로 선택한
    경우에는 별도의 '신체치수 측정'화면으로 이동한다.
-   '신체치수 측정' 화면은 신체치수 측정이 필요한 각 부위별로 어떻게
    측정하는지를 설명해주는 각각의 동영상을 백그라운드 영상으로 보여주면서
    홍길동씨가 동영상을 참고해서 자신의 신체치수를 기입할수 있는 형태의 UI를
    가진다. 즉 목둘레를 재는화면의 경우 화면에 목둘레를 입력하는 text input
    widget이 존재하고 배경 비디오로 목둘레를 잘 재는 방법을 설명하는 비디오가
    자동재생되며 목둘레를 입력하면 다음 가슴둘레로 넘어가는 그런 식이다.
-   '신체치수 측정'에 구체적인 참고는 인두치노사이트의 측정화면을 참고하면된다. (가입필요)
    -   <https://www.indochino.com/account/measurements>#
    -   <https://www.indochino.com/measurements>
-   혹은 인두치노를 참고한것으로 보이는 스트라이프의 구현을 참고해도 된다.
    -   <https://stripes.co.kr>
-   '신체치수 측정' 에서 백그라운드로 사용될 영상은 이미
    촬영되어있다.(한만일대표님 링크 보충해주세요)
-   신체 치수 측정이 완료되면 별도의 '사용 용도', '선호 색상'을 기입하낟.
-   홍길동씨가 입력한 신체치수를 바탕으로 열린옷장의 의류검색을 이용해서
    대여할 수 있는 옷의 목록을 구하고 추가 조건으로 필터링한 뒤 최종적으로
    3개의 의류 선택지를 사용자에게 제공한다.
-   홍길동씨는 3개의 의류선택지를 레이어팝업된 의류의 이미지 형태로 확인하고
    (이미지 형태는 아직 미정) 간단하게 의류의 치수등의 정보를 텍스트로
    제공받는다.
-   홍길동씨에게 제공하는 의류 선택지는 기본적으로 남성일 경우 자켓과 바지,
    여성일 경우 블라우스와 치마를 기본으로 하며 그 이외의 기본 조합에
    대해서는 온라인 대여를 제공하지 않는다. (코트라던지, 조끼등)
-   홍길동씨는 3개의 이미지중 가운데 멋진 은갈색 상하의 정작 슈트를 선택한다.
-   홍길동씨는 추가로 '의류 옵션' 선택화면으로 이동한다. 의류 옵션에서는
    추가적으로 정장 슈트에 필요한 부속의류를 선택할 수 있다. 남자의 경우 셔츠,
    벨트, 구두, 넥타이등이다.
-   의류 옵션의 경우 수량만 선택할 뿐 특별한 옵션이 없으며 특정 의류로 특정하지
    않는다. 이후 사용자 신체치수를 참고해서 옷장지기가 온라인대여가 결정되는 시점에
    특정 의류로 연결하게 된다.
-   셔츠1, 벨트1, 구두1, 넥타이1을 선택하고 '다음'을 누른 홍길동씨는 '결제요청'
    화면으로 이동하게 된다.
-   이 시점은 지금까지 나온 신청서의 내용을 바탕으로 결제 금액과 열린옷장이
    계약한 PG사가 제공하는 결제방법등을 선택해서 최종적으로 결제승인을
    발생시키는 단계의 전단계이다.
-   이 단계에서 최종 '결제' 버튼을 누르기 전까지 홍길동씨가 선택한 은갈치
    슈트는 오프라인 매장에서 어떠한 표시가 없이 자유롭게 대여가 가능한 상태이며
    심지어 홍길동씨와 비슷한 시간에 활빈당 면접을 준비하는 임꺽정씨에게도 해당
    의류는 동이랗게 노출된다. 하지만 '결제' 버튼을 누른시점 이후로 이 의류는
    결제가 완료되거나 혹은 결제신청후 특정시간까지 배타적으로 홍길동씨에게
    할당되며 다른 온라인 대여 노출이나, 오프라인 대여가 불가능해진다.
-   운좋게도 홍길동씨가 선택한 은갈치 슈트는 온전하게 대여가 가능하기때문에
    최종적인 결제화면으로 진행되면 최종적인 결제는 '아임포트' 인터페이스를
    이용해서 PG쪽에 전달한다.
    -   <http://www.iamport.kr/>
-   끝

# 수령

# 반납

**Comment by yongbin** [comment]
@aanoaa 보시고 내용적인 부분이나 형식적인 부분에서 부족한 부분 알려주시면 보완해 나가겠습니다. 수력,반납 부분은 @10001if 님과 좀더 의논해서 보강하겠습니다.

**Comment by 10001if** [comment]
> '신체치수 측정' 에서 백그라운드로 사용될 영상은 이미 촬영되어있다.(한만일대표님 링크 보충해주세요)
http://opencloset1.godo.co.kr/shop/main/html.php?htmid=proc/body_size.htm 확인해주시면 됩니다. 그러나 윗배둘레는 촬영되어 있지 않습니다. 추가적으로 촬영해야 합니다.
나머지 부분의 경우 지난 번에 이야기 주셨던 내용과 동일하며, 크게 문제되는 부분은 없는 것으로 보여집니다.

**Comment by aanoaa** [comment]
편하신방법으로 시나리오를 가지고 미리보기를 간단하게 만들어주세요.
디자인을 하라는 얘기는 아니고요, 몇개의 화면이 필요할지, 각 화면에 어떤 기능이 들어갈지 알아보기 위함입니다.

**Comment by yongbin** [comment]
![img_0683](https://cloud.githubusercontent.com/assets/52704/14343332/3a26227c-fcdb-11e5-8300-79b6f9ebf9c8.jpg)
 
간단하게 미리보기를 한번 작성해봤습니다. 시나리오로 쓸때는 몰랐는데 막상 백지에다 뭘 그리려니까 비어있는게 엄청 많습니다. @10001if 님고 상의해서 좀 더 빈공간을 체워나간뒤에 발사믹 같은 도구로 깔끔하게 정리하겠습니다.

**Comment by aanoaa** [comment]
깔끔하지 않아도 좋습니다.
정리하는데 들이는 시간이 아깝습니다.
링크의 연결같은건 무시하셔도 괜찮습니다.

**Comment by yongbin** [comment]
넵 그러면 깔끔하게 정리하는건 스킵하고 의견을 전달할수 있는 수준으로만 정리하겠습니다 아무튼 생각보다 진행해보니까 비어있는 부분이 많아서 그부분을 @10001if 님과 먼저 상의해보고 말씀드리겠습니다.

**Comment by aanoaa** [comment]
네 지금 아주 좋아보입니다.

**Comment by aanoaa** [comment]
군더더기 없고 후지고(나쁜뜻이 아니에요)

**Comment by yongbin** [comment]
> 후지고(나쁜뜻이 아니에요)

ㅋㅋㅋㅋㅋㅋ

**Comment by yongbin** [comment]
오늘은 회원가입과 로그인절차에 대해서 좀 더 구체적으로 생각해봤습니다. 그림을 그려보니까 결정해야할 사항들이 많습니다.

![img_0712](https://cloud.githubusercontent.com/assets/52704/14419904/de20a1a6-0003-11e6-80a8-ebd98b306d24.jpg)


# 회원가입 장면 1

-   [ ] 정책적으로 본인인증을 필수로 진행할지 결정해야합니다.
-   [ ] 휴대폰 본인인증 서비스 연동에 대한 사항을 확인해야합니다(업체,가격,연동방법)

# 회원가입장면 2

-   [ ] 회원의 로그인시 id를 사용할지 email을 사용할지 결정해야합니다.
-   [ ] email을 사용할 경우 email의 인증절차를 따로 설계해야합니다.
-   [ ] 회원가입에 필요한 정보를 나열하고, 필수입력 항목과 선택입력항목을 분류해야합니다.
-   [ ] 기존 열린옷장의 오프라인 대여했던 사람들의 연동을 어떻게 할지 결정해야합니다.

# Email 인증화면 1

-   [ ] email 인증을 할 경우 고객에게 어떤 페이지를 어떤식으로 보이게 할지 결정해야합니다
-   [ ] email 인증을 할 경우 인증의 만료(expire) 시간과 사용자가 어떻게 재인증을 요청할수 있는지를 설계해야합니다.

# 회원가입장면 3

-   [ ] \`신체정보측정\`을 \`대여\`안에 포함해서 진행할지 독립적으로 진행할지 결정해야합니다.
-   [ ] 회원가입이 완료되었을때 보여줄 화면과 디자인이 필요합니다.
-   [ ] 회원가입이 완료된이후 자동으로 로그인 세션을 만들지 사용자로 하여금 다시한번 로그인하도록 할지 결정해야합니다.

# 로그인 장면 1

-   [ ] 위에 언급한 것 처럼 id에 id를 사용할지 email을 사용할지 결정해야합니다.

# 로그인 장면 2

-   [ ] email인증을 진행할 경우 만약 가입은 되었지만 email 인증이 되지 않은 회원은 어떤 제약을 둘지 결정해야합니다.

# 로그인 장면 3

-   [ ] 로그인 이후 보여줄 화면과 메세지를 결정해야합니다.

# 추가

-   [ ] 작성하다보니 다음사항들을 더 보강해야할것으로 보입니다.
    1.  회원 탈퇴 절차 및 화면
    2.  회원정보 수정 절차 및 화면
    3.  비밀번호 찾기 절차 및 화면
    4.  id찾기 절차 및 화면

**Comment by yongbin** [comment]
#736

**Comment by aanoaa** [comment]
프로젝트를 분리해서 이슈 및 코드를 운영할 필요가 있어 보입니다.
지금 이슈가 너무 커져버릴 것도 같고요.
새로운 프로젝트에서 이슈를 세분화해서 해결해나가면 좋을 것 같습니다.

적절한 이름으로 프로젝트를 만들어주세요.

**Comment by aanoaa** [comment]
개인적으로 `online` 은 좀 이상하지 않나요?
웹서비스가 당연히 온라인이데..

**Comment by 10001if** [comment]
@yongbin 확인은 했는데, 찾아뵙고 이야기를 좀 나누면 훨씬 부드럽게 진행이 될 것 같네요. 온라인 서비스에 대해 제가 조금 더 깊이 고민해야 할 것 같습니다. 우선 큰 틀에서는 대표님이 적어주신 내용에 문제가 있는 것 같지는 않네요. 고민해주셔서 감사드립니다. ^^

**Comment by yongbin** [comment]
새로만드는 서비스의 저장소는 `OpenCloset-서비스URL-Web` 형태로 하려고 합니다. URL이 아직 결정되지 않았으므로 당분간만 이 이슈에 업데이트하고 새로운 저장소가 만들어지면 추후 그쪾에서 진행하겠습니다.

**Comment by yongbin** [comment]
오늘은 회원가입에서 기존 오프란인 회원은 전환 관련 처리와 MyPage 관련한 부분을 조금 생각해봤습니다.

![img_0729](https://cloud.githubusercontent.com/assets/52704/14596185/a6a6a7c6-057f-11e6-8ba1-bf6bd5afe22e.jpg)

# 기존회원 전환 장면 1

-   [ ] 기존 오프란인 대여회원의 경우 온란인으로 전환할수 있는 별도의 절차가 준비되어야 합니다.

# 기존회원 전환 장면 2

-   [ ] 기존 가입에서 가장 신뢰성이 있는 식별정보는 회원의 이름과 휴대폰 번호이기 때문에 두 인자를 통해 회원을 검색하는 화면을 제공합니다.

# 기존회원 전환 장면 3

-   [ ] 검색결과는 기존 오프라인 대여기록과 함께 보여주고 본인이 맞는지 확인후에 전환을 진행하도록 안내합니다.
-   [ ] 이 시점에 별도로 필요한 약관동의나 개인정보 처리에 대한 동의절차를 진행합니다.

# 기존회원 전환 장면 4

-   [ ] 회원 검색을 성공한경우 기존에 가지고 있던 정보중 신규 회원 스키마에 적용시킬 수 있는 정보를 가지고 오고 나머지 추가되어야 할 정보들을 추가로 받는 화면을 제공합니다.
-   [ ] 이 시점에서 기존 회원가입절차와 동일하게 email 인증등의 절차를 동일하게 진행합니다.

# MyPage 장면 1

-   [ ] 좌측 사이드바에는 회원정보 수정 및 탈퇴링크를 제공하는 목록을 제공합니다.
-   [ ] 중앙 블록을 통해서 '내 대여', '내 치수', '내 질문'을 각각 제공합니다.

# MyPage 장면 2 - 내 대여

-   [ ] 나의 대여기록을 열람할수 있는 목록입니다. 온라인 대여와 오프라인대여가 연동되어야 합니다.
-   [ ] 대여에 연결된 대여자의 대여메세지와 기증자의 기증메세지가 연결되어야 합니다.
-   [ ] 온라인 대여의 경우 '배송중' 등의 상태를 통해 대여자가 대여한 옷의 현재 위치를 알 수 있도록 처리해야합니다.

# MyPage 장면 3 - 내 치수

-   [ ] 내 치수를 별도로 관리할지 '내 대여'에 일부 정보로 넣을지 좀 더 고민해 봐야합니다.

# MyPage 장면 4 - 내 질문

-   [ ] 고객 Q&A를 처리하기 위해서 만든 목록입니다.
-   [ ] 하지만 구체적인 아이디어가 없습니다. 구체화가 필요합니다.

**Comment by 10001if** [comment]
@yongbin http://comento.kr/

**Comment by yongbin** [comment]
오늘 오전에 @10001if 님과 의논한 내용입니다. 

-   온라인 사이트 이름은 share.theopencloset.net으로 한다.
-   기존 오프라인 예약을 신규 쉐어 회원가입으로 대체한다.
-   신규 쉐어 회원가입시 휴대폰 본인인증 과정이후 과거 오프라인 대여 기록이 있으면 기존 회원정보를 가지고 온다.
-   없으면 일반적인 회원가입 절차를 진행한다.
-   로그인 방법등은 Silex에서 임의로 결정한다.
-   주소는 대여 시점(오프라인인 경우 예약)에 쓰도록 한다.
-   신체치수 측정과 대여는 통합한다.
-   체험하기 : 신체치수 측정등이 없어도 전체적인 흐름을 알수 있는 화면
-   Email 인증을 안하고 회원가입은 최대한 간소하게 만든다.
-   세트에 대한 사진은 우선 촬영분으로 처리하고 추후 착샷을 보강할 계획을 세운다.
-   세트에 대한 사진을 업로드 할수 있는 수단 강구

**Comment by yongbin** [comment]
OpenCloset::Share::Web ( https://github.com/opencloset/OpenCloset-Share-Web ) 저장소 개장했습니다.

**Comment by yongbin** [comment]
![screen shot 2016-05-02 at 4 03 48 pm](https://cloud.githubusercontent.com/assets/52704/14948860/bc5ca2d6-107f-11e6-855f-ba488c94df7a.png)

지난주 부터 이민정님과 함께 온라인 대여서비스 구현을 구체화 해 나가고 있습니다. 위는 현재까지 정리한 장면 리스트입니다. 구체적인 결과물은 HTML 형태로 공유될 예정이고 추후 업데이트 되는데로 새로운 저장소에 이슈로 등록하겠습니다. 지금까지 정리했던 내용돠 달라진 주요 변경사항에 대해서 먼저 공유드립니다.

 - PC 브라우져 환경을 기준으로 작업하는것이 아니라, 모바일웹 환경에 대응한 페이지를 기획할 예정입니다.
 - 휴대폰 인증과 이메일 인증절차중 휴대폰 인증만 진행하고 이메일 인증의 경우 필수에서 제거하기로 했습니다.
 - 서비스의 메인 페이지를 별도로 구성하지 않고 '대여하기' 기능이 서비스의 메인페이지가 되도록 구성했습니다. 이는 component 형식으로 구현하는 열린옷장 서비스 특성을 반영한 결정입니다.
 - 대여추천에 있어서 기존 3개만 노출하는것에서 전체다 노출하는 방식으로 방향을 변경했습니다. 또한 과거 대여의류역시 같이 보여주기로 했습니다.

**Comment by aanoaa** [comment]
예전의 새옷등록 이슈 처리했을때, 새옷등록을 위해서 할게 많았는데, 이슈 하나가 너무 길어지다보니
알아보기 좀 어렵더라고요.

저장소를 나누고(나눌필요가 있었습니다) 이슈를 쪼개서 등록하니까 해야할 일이 보이고 보다 쉽게 처리할 수 있었습니다.

이 이슈도 마찬가지로 새로운 저장소도 생겼겠다, 이슈를 의미있게 나누고 적절하게 처리해 나가는 것이 좋을 것 같습니다.

**Comment by aanoaa** [comment]
아래 내용이 맞는지는 모르겠지만,

- [ ] app skeleton 생성
- [ ] My Page
- [ ] 회원가입
- [ ] 기존회원전환?
- [ ] 내 질문

등으로 이슈를 세분화하고 진행했으면 합니다.
`app skeleton 생성` 은 제가 생각한겁니다.

**Comment by yongbin** [comment]
넵 좋습니다. 앞으로 열린옷장 온라인 대여 서비스(쉐어)와 관련된 이슈는 https://github.com/opencloset/OpenCloset-Share-Web/issues 에서 진행하도록 하겠습니다.
