### ISSUE TITLE
기증자의 전체 연락처 목록

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1091]
뉴스레터 발송을 위해 전체 기증자의 이메일을 요청드리려고 합니다. CSV 파일로 요청드립니다. 그리고 파일의 마지막 기증자가 누구인지도 함께 요청드립니다. 뉴스레터 발송을 위한 것이기 때문에 19일 이전에 받을 수 있도록 요청드립니다.

**Comment by keedi** [comment]
다음 형식으로 필요합니다.

- 이름
- 이메일
- 전화번호

**Comment by keedi** [comment]
기증자의 전체 연락처 목록을 뽑는 질의는 다음과 같습니다.

```sql
SELECT
    u.name
    , u.email
    , ui.phone
FROM donation AS d
LEFT JOIN user      AS u  ON u.id = d.user_id
LEFT JOIN user_info AS ui ON u.id = ui.user_id
GROUP BY u.id
ORDER BY u.id
;
```

**Comment by keedi** [comment]
상기 질의의 결과를 확인하면서 이름과 이메일 주소에 공백과 같은 들어가지 말아야 하는 글자가 다수 들어가 있음을 확인했습니다. 관련해서 이 자료를 그대로 활용할 경우 문자 전송이나 이메일 전송시 제대로 전송되지 않는 이슈가 발생할 수 있습니다. 또한 이메일과 전화번호가 들어가 있지 않는 경우도 있습니다. 아마도 이는 기증받는 페이지가 기존 재고 관리 시스템에서 별도 저장소로 빠지면서 기증 받는 절차가 바뀌어서 생긴 것으로 보입니다. 이는 열린옷장 측에서 고려해야 할 것 같네요.

**Comment by keedi** [comment]
이름, 이메일, 전화 번호에 허용할 수 없는 자료가 들어가는 경우를 따로 추출해서 올바르게 고치는 작업이 필요해 보입니다. 이는 별도의 이슈로 열어서 처리해야 할 것 같습니다.

**Comment by keedi** [comment]
실제 추출 자료는 이메일로 전달드렸습니다.

@10001if 피드백 부탁드립니다.
특별히 피드백이 없으면 이슈 닫을 예정입니다.

불필요한 문자가 들어간 부분은 #1096 이슈에서 처리하겠습니다. 아마도 해당 이슈가 처리되면 다시 뽑아서 전달해야 할 것으로 보입니다.

**Comment by keedi** [comment]
전체 목록은 전달 드렸으며 따로 이후 피드백은 없으므로 문제가 없어보입니다. 이슈 닫습니다.
