### ISSUE TITLE
봉사자 전체 연락처 목록

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1093]
자원봉사자의 전체 이메일 파일을 요청드립니다. 뉴스레터 발송용입니다. 파일은 CSV 파일로 요청드리구요. 파일에 마지막 봉사자 명단을 따로 기입 요청드립니다. 19일까지 뽑아주시면 됩니다.

**Comment by keedi** [comment]
다음 형식으로 필요합니다.

- 이름
- 이메일
- 전화번호

**Comment by keedi** [comment]
실제 자원 봉사를 완수한 봉사자 관련 정보를 추출하는 질의는 다음과 같습니다.

```sql
SELECT
    v.id
    , vw.id
    , v.name
    , v.email
    , v.phone
    , vw.status
    , vw.activity_from_date
FROM volunteer AS v
LEFT JOIN volunteer_work AS vw
    ON v.id = vw.volunteer_id
WHERE
    (
        vw.`status` = "done"
    )
ORDER BY
    v.id
    , vw.activity_from_date ASC
;
```

동일한 사람이 여러번 자원 봉사를 수행할 수 있기 때문에 중복을 제거한 봉사자를 추출하는 방법은 다음과 같습니다.

```
SELECT
    v.name
    , v.email
    , v.phone
FROM volunteer AS v
LEFT JOIN volunteer_work AS vw
    ON v.id = vw.volunteer_id
WHERE
    (
        vw.`status` = "done"
    )
GROUP BY v.id
ORDER BY
    v.id
;
```

**Comment by keedi** [comment]
추출한 실제 자료 결과는 메일로 전송했습니다. 피드백 확인 후 이슈 닫습니다.

**Comment by keedi** [comment]
봉사자의 경우 실제 신청하고 자원 봉사를 수행하지 않은 사람도 있을 수 있습니다. 확인 결과 실제로 방문해서 자원 봉사를 수행한 사람에 한해 목록을 뽑고 싶다고 합니다. 이 경우 `volunteer_work.status` 값이 `done`인지 확인해야 합니다.

**Comment by 10001if** [comment]
@keedi 언제부터 등록된 봉사자인지 등록시점을 알고 싶습니다.

**Comment by keedi** [comment]
처음 등록은 2015년 8월 21일이지만 해당 자료는 테스트 자료일 가능성이 있고 실제 시점은 2015년 9월 5일로 사료됩니다.

**Comment by keedi** [comment]
특별히 수정할 부분은 없는 것 같습니다. 이슈 닫습니다.
