### ISSUE TITLE
특정 신체 부위의 평균 크기가 올바르지 않음

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#1097]
여성 165cm / 54kg
평균 사이즈 중에 허벅지 둘레가 맞지 않습니다.

평균 허벅지 둘레: 136.8

잘못입력된 정보가 있는게 아닌가 생각됩니다.
잘못 입력된 사이즈를 올바르게 고쳐야 영향을 받지 않을 것 같습니다.

**Comment by yongbin** [comment]
정기적인 모델 업데이트  (#776,  #720) 때마다 이상치 검사를 하는데 이때 걸러내야하는 이상치 문제인거 같습니다. 제가 처리하겠습니다.

**Comment by aanoaa** [comment]
확인할 수 있는 경로입니다.

    /user/52658

**Comment by 10001if** [comment]
/user/57782의 다리길이의 차이가 큽니다. 이상치 작업을 한동안 하지 못했습니다~ 작업이 필요해 보입니다~

**Comment by aanoaa** [comment]
이상치가 발견되는 키/몸무게/성별에 대해서 오차범위를 벗어나는 데이터를 삭제해주어야 하는 작업인 것 같습니다.
리포트가 있을때마다 수정을 해주거나, 범위를 정해서 주기적으로 삭제해줄 필요가 있습니다.

**Comment by pingpongworks** [comment]
https://staff.theopencloset.net/user/62018
사용자정보 (62018) (신체정보 : 171/60 )  
다리길이/무릎길이 평균치와 차이 많이 납니다
