### ISSUE TITLE
현대택배 -> 롯데택배로 변경

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1098]
12/16부로 현대택배 -> 롯데택배로 변경 되었다고 합니다.  대여자가 반납 시 운송장 번호와 택배사를 입력하는 목록에서 현대택배 대신 롯데택배로 입력할 수 있도록 수정 요청드립니다.

**Comment by 10001if** [comment]
https://github.com/opencloset/opencloset/issues/1092 이슈를 보니 현대택배가 애초에 등록이 되어 있지 않았네요. 롯데택배 등록을 요청드립니다. ^^

**Comment by aanoaa** [comment]
지난번에 현태택배가 목록에 없다고 하신게 무슨의미인지 이해했습니다.
주문서의 반납방법에 없다는 말씀이신것 같습니다.

사용자가 입력하는 `열린옷장 반납택배 발송알리미` 에는 현대택배가 목록에 있엇고 이것을 롯데택배로 변경하였습니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
