### ISSUE TITLE
문자 발송용 웹발신 전화번호 변경

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1100]
현재는 070-4325-7521 과 070-7583-7521 번호를 사용 중입니다.
070-4325-7521는 4층에서 열린옷장 전체 안내를 070-7583-7521는 지하에서 온라인 전용으로 사용 중입니다.

그런데, 열린옷장에서 보내는 웹발신 문자가 자꾸 스팸 처리 된다는 제보가 제법 많았습니다.
가장 의심이 되는 부분은 070 번호의 사용이었습니다. 그래서 번호를 변경하였습니다.
02-6929-1020 번호를 사용하기로 하였습니다.

종전에 070-4325-7521로 발송되던 발신번호를 02-6929-1020으로 수정 요청드립니다.

**Comment by 10001if** [comment]
02 번호를 사용하며 변경된 내용은 다음과 같습니다.

1. 스팸이 걸리지 않을 것(?)이라는 기대..
2. ARS 자동응답을 통한 기본내용의 안내, 상담원 연결 전까지 대략적인 내용을 제공. 직접 통화량이 줄어 통화 중인 대기 상태가 줄어들 것으로 기대합니다.
3. 지하, 4층, 5층 간 내선 연결을 통한 커뮤니케이션의 확대.

**Comment by keedi** [comment]
오늘 중으로 처리하겠습니다.

**Comment by keedi** [comment]
APISTORE API 문서의 **3.5 발신번호 등록** 항목을 참고해 `/sendnumber/save/{client_id}` 주소를 사용해 02-6929-1020 번호를 등록했습니다. 문서상으로만 볼 때 등록 기능은 몹시 모호합니다. 해당 업체에 문의 및 테스트한 결과 발신번호 등록 기능의 상태는 다음과 같습니다.

- 삭제 기능 지원하지 않음
- 수정 기능 지원하지 않음
- 문서와는 다르게 등록 번호의 설명(`comment`)가 없어도 등록 가능
- `comment`를 입력하지 않은 경우 빈 문자열이 아닌 undef로 등록되는 것으로 보임
- 등록시 기존 목록은 그대로 두고 계속 추가되는 방식

**Comment by keedi** [comment]
릴리스 및 실서버에 배포 완료했습니다.

발신번호 변경과 관련해 서버에서 다음과 같은 작업을 수행했습니다.

```bash
$ ubic stop opencloset.cron.sms
$ ubic stop opencloset.staff
$ ubic stop opencloset.visit
$ ubic stop opencloset.volunteer
$ ubic stop opencloset.sms
#
# staff, visit, volunteer 설정 수정
#
$ ubic start opencloset.sms
$ ubic start opencloset.volunteer
$ ubic start opencloset.visit
$ ubic start opencloset.staff
$ ubic start opencloset.cron.sms
```

**Comment by keedi** [comment]
@10001if 테스트해보시고 확인 결과 알려주세요.

**Comment by keedi** [comment]
문자 매크로 기능이 추가되면서 해당 기능이 설정의 발신자 번호를 쓰지 않는 관계로 매크로쪽 전화번호는 수동으로 수정합니다.

**Comment by keedi** [comment]
음... 문자 전송 페이지의 기본 발신 번호가 하드코딩되어 있습니다. 이로 인해 설정값 변경으로만은 제대로 저장이 안되는군요. 일단 서버쪽 템플릿을 임시 수정했습니다. 하드코딩된 부분은 제대로 수정해야 합니다. 이는 별도 이슈에서 처리하겠습니다. :(

![screenshot-staff theopencloset net 2016-12-22 09-28-59](https://cloud.githubusercontent.com/assets/138451/21411112/3285ce04-c829-11e6-8a44-d187b471185b.png)

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
