### ISSUE TITLE
예약 제한 인원 변경

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1106]
시간 |	       남자|	       여자|
---|---|----
10:00|	5|		4	|
10:30|	4|		5	|
11:00|	5	|	4	|
11:30|	4	|	5	|
12:00|	0	|	0	|
12:30|	0      |	0	|
13:00|	0	|	0	|
13:30|	0	|	0	|
14:00|	5	|	4	|
14:30|	4	|	5	|
15:00|	5	|	4	|
15:30|	4	|	5	|
16:00|	5	|	4	|
16:30|	4	|	5	|
17:00|	5	|	4	|
17:30|	2	|	2      |

기존에 남녀 4명(마지막 타임만 2명)이었던 것을 위 표와 같이 4명 5명으로 변경하고자 함.

**Comment by keedi** [comment]
진행합니다.

**Comment by keedi** [comment]
월~일까지 동일하다고 합니다.

**Comment by keedi** [comment]
처리했습니다. 이슈 닫습니다. 배포할 때 실제 설정 파일을 조정해야 합니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
