### ISSUE TITLE
반납 희망일 하루 전 알림 SMS 전송

### ISSUE THREAD

**Issue by keedi** [opencloset/opencloset#111]
#92 의 의존 항목입니다.

~~#92 에서 언급한 것과는 다르게 반납 하루 전이 아니라 반납 당일 문자를 보내는 것으로 최종 결정했습니다. 대여중인 주문서에 대해 반납 당일 오전 9시에 일괄로 문자 메시지를 보내기로 했습니다.~~

여기서 중요한 것이 반납일은 반납 예정일이 아니라 *반납 희망일*이라는 점입니다. 정확히는 반납 예정일이 대여자가 반납해야 하는 날이지만 대여자가 열린옷장 측으로 연락을 취해 부득이하게 반납할 날을 변경했다면 이 경우에 한해 *반납 희망일*을 조정합니다. 연체료는 반납 예정일을 기준으로 계산하지만 알림 SMS는 *반납 희망일*을 기준으로 전송합니다.

**Comment by keedi** [comment]
이 기능은 구현 완료되면 바로 동작하게 되므로 보낼 문자 내역이나 보낼 사용자에 대한 조건이라던가 등등 최종 확인을 거친 다음 진행하겠습니다.

**Comment by keedi** [comment]
2014년 3월 3일 미팅 결과 반납 당일이 아닌 반납 1일 전에 전송하기로 최종 결론을 내렸습니다.

반납 당일 보내려고 했던 이유는 반납해야 한다는 사실을 대여자가 잊어버리고 있을 수 있다고 판단했기 때문입니다. 하지만 다시 내부적으로 토의한 결과 잊어버릴 사람은 하루 전이나 당일이나 잊어버릴 것이며, 당일 스케줄이 있을 경우 당일 알림을 받아도 어찌할 수가 없으리라고 판단해서 당일이 아닌 1일 전에 전송하기로 최종 결정을 내렸습니다.

**Comment by keedi** [comment]
따라서 이슈 제목을 변경합니다. :)

**Comment by keedi** [comment]
반납일 1일전 오전 11시에 일괄 전송하기로 합니다.

**Comment by keedi** [comment]
반납일이 아닌 반납 희망일 기준 하루 전에 문자를 보내야 합니다. 원칙적으로 반납일과 반납 희망일은 동일한 날짜입니다. 대여자에게 연락이 와서 부득이하게 반납일을 뒤로 미루는 경우 사용하는 것이 반납 희망일입니다. 비록 연체가 되긴 하나 열린옷장 측에 고지를 한 상황이기 때문에 이 경우는 반납일 기준으로 문자를 보내면 대여자가 당황할 여지가 있습니다. 즉, 최종 정리하면 반납일이 아닌 **반납 희망일** 기준으로 하루 전에 SMS를 전송해야 합니다.

제목도 변경했습니다.

**Comment by 10001if** [comment]
000님, 열린옷장입니다. 내일은 대여하신 의류의 반납일입니다. 기한내에 반납 부탁드립니다. 반납가능시간 : 오전 10시~오후 6시 (점심시간 1시~2시 제외)

**Comment by keedi** [comment]
논의 및 확인 완료했습다. 작업 진행하면 됩니다. :)

**Comment by keedi** [comment]
@10001if 여전히 문구나 내용이 동일한지요? SMS를 사용하실지 아니면 LMS를 사용하실지도 결정 부탁드립니다. 더불어 APIStore로 변경하면서 SMS 글자 수 제한이 80글자로 바뀌었기 때문에 그대로 사용하신다 할지라도 글자 수 변경이 필요합니다. LMS로 변경하신다면 마찬가지로 문구를 수정해야 합니다.

**Comment by keedi** [comment]
#116 항목과 마찬가지로 APIStore 서비스 체결 이후 #264 항목 처리를 통해 SMS 후불 결제가 가능해졌으므로 예약 전송 기능도 진행하려고 합니다.

**Comment by 10001if** [comment]
- 반납일 : 열린옷장입니다. xx일에 대여하신 의류의 반납일입니다. 오늘 중으로 꼭 반납해주세요.

**Comment by 10001if** [comment]
이렇게 부탁드립니다.

**Comment by keedi** [comment]
메시지 확인완료했습니다. 발송 시각은 어찌하면 될런지요?

**Comment by 10001if** [comment]
확인 완료하였습니다. 오전 11시에 발송해주시면 됩니다.

**Comment by keedi** [comment]
진행합니다.

**Comment by keedi** [comment]
@10001if 으음!? 적어주신 내용이 지금까지 논의랑 다른 것 같습니다.

최초 이슈는 반납일에 문자 보내기였다가, 이후에 반납일이 반납 희망일로 바뀌고, 다시 반납 희망일 1일 전에 문자를 보냈으면 좋겠다고 이야기가 나왔은데 마지막에 기록해주신대로라면 반납 희망일 당일 11시에 문자를 보내는 것인데요...

논의 과정없이 갑자기 바뀌어 착각하신 것인지 아니면 의도하신 것인지요?

**Comment by 10001if** [comment]
네~ 제가 좀 헷갈렸네요. 다시 정리해서 보내드리겠습니다. :(

**Comment by 10001if** [comment]
- 반납일 -1일 : [열린옷장] 내일은 xx일에 대여하신 의류 반납일입니다. 내일까지 반납부탁드립니다.

- 반납일 1일 전 오전 11시에 발송 부탁드립니다.

**Comment by keedi** [comment]
opencloset/OpenCloset-Cron#1 이슈가 완료되면 본 이슈를 닫겠습니다.

**Comment by keedi** [comment]
opencloset/OpenCloset-Cron-SMS#2 에서 처리하겠습니다.

**Comment by keedi** [comment]
OpenCloset::Cron::SMS 0.001 버전을 릴리스했습니다.

릴리스 모듈은 다음 위치에서 확인할 수 있습니다.

https://cpan.theopencloset.net/

**Comment by keedi** [comment]
구현은 완료되었으므로 실서버에서 동작하도록 배포를 진행합니다.

**Comment by keedi** [comment]
실서버에 배포 완료했습니다. ubic 항목 이름은 `opencloset.cron.sms` 입니다.

```bash
$ ubic status
opencloset
    opencloset.cron
        opencloset.cron.sms     running (pid 17037)
    opencloset.fakepause        running (pid 20702)
    opencloset.monitor          running (pid 32009)
    opencloset.sms              running (pid 12597)
    opencloset.staff            running (pid 12585)
    opencloset.visit            running (pid 11406)
```

**Comment by keedi** [comment]
배포 완료했으므로 이슈 닫습니다. :)

동작과 관련해 버그가 있을 경우 별도의 이슈를 등록해 처리하겠습니다.
