### ISSUE TITLE
취업날개 통계 확인

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#1111]
`Tue, 27 Dec 2016 12:45:54 +0900` 기준으로 아래 쿼리 결과는 `3861`명 입니다.

    SELECT status, COUNT(*) FROM coupon WHERE `desc` LIKE 'seoul|%' GROUP BY status;
    +----------+----------+
    | status   | COUNT(*) |
    +----------+----------+
    | provided |     1737 |
    | used     |     3861 |
    +----------+----------+

하지만, https://staff.theopencloset.net/stat/events/seoul 에서는 방문인원이 `3966`명 입니다.

**Comment by aanoaa** [comment]
`4,000`명에 도달하거나 2016년 말까지 진행하기로 한 이벤트인데, 수치의 오류로 인해 이벤트 주최자와 오해가 발생할 수 있습니다.
빠른해결이 필요합니다.

**Comment by aanoaa** [comment]
@10001if 님은 `4,000` 명을 채우고 싶어합니다.

**Comment by aanoaa** [comment]
@yongbin 취업날개 이벤트 종료기간이 가깝습니다.
이벤트 주최측과 정확인 수치를 공유해야 하기 때문에 잘못되어 있다면 확인이 필요합니다.

제가 하고픈 말은 통계 페이지보다

```sql
SELECT status, COUNT(*) FROM coupon WHERE `desc` LIKE 'seoul|%' GROUP BY status;
```

이 수치가 더 정확할 것 같습니다.
통계상에서 중복된 카운트가 있는게 아닌가 싶습니다.

**Comment by 10001if** [comment]
@aanoaa @yongbin 가장 중요한 건 현재 이용자가 몇 명인지입니다. 4000명이 다 되면 이용을 중지해야 하기 때문입니다.

**Comment by yongbin** [comment]
#916 에서 `provided` 상태의 주문서중 order에 `coupon_id` 값이 있는 쿠폰들을 사용된 쿠폰으로 인식했습니다. 관련해서 한만일대표님과 확인한결과 사용되지 않은 쿠폰으로 봐야한다고 하셨기때문에 해당 내용을 쿼리에 반영했습니다.

```sql
                SELECT
                    *
                FROM
                    (
                        SELECT
                            a.`date`                                        AS 'booking_date'
                            ,b.`id`                                         AS 'order_id'
                            ,YEAR(a.`date`)                                 AS 'booking_year'
                            ,MONTH(a.`date`)                                AS 'booking_month'
                            ,DAY(a.`date`)                                  AS 'booking_day'
                            ,IF(b.status_id = 12 OR b.status_id = 14, 0, 1) AS 'is_visit'
                            ,d.gender                                       AS 'gender'
                            ,d.birth                                        AS 'birth'
                            ,YEAR(NOW()) - d.birth                          AS 'age'
                            ,TRUNCATE(YEAR(NOW()) - d.birth, -1)            AS 'age_group'
                            ,IF(b.`coupon_id` IS NOT NULL AND e.status = 'used' AND b.status_id NOT IN ( 14, 12, 40 ), 1, 0)            AS 'is_coupon_use'
                            ,e.`id`                                         AS 'coupon_id'
                            ,e.`update_date`                                AS 'coupon_date'
                            ,e.`status`                                     AS 'coupon_status'
                            ,SUBSTRING_INDEX(e.desc, '|', 1)                AS 'coupon_type'
                            ,IFNULL(a.`date` - e.`update_date`,0)           AS 'booking_coupon_issue_diff'
                            ,s.name
                        FROM
                            `booking` AS a
                            INNER JOIN `order`      AS b ON ( a.id = b.booking_id )
                            INNER JOIN `user`       AS c ON ( b.user_id = c.id )
                            INNER JOIN `user_info`  AS d ON ( c.id = d.user_id )
                            INNER JOIN `status`     AS s ON ( b.status_id = s.id )
                            LEFT  JOIN `coupon`     AS e ON ( b.coupon_id = e.id )
                    ) AS x
                WHERE
                    `booking_coupon_issue_diff` >= 0
                    AND `booking_date` > '2016-04-25'
                    AND `is_coupon_use` = 1
```
현 시점 기준으로 결과는 3895명입니다. 이 수치가 타당한지 좀 더 검토를 해봐야합니다.

**Comment by yongbin** [comment]
다음 주문서는 쿠폰상태가 `used` 상태이지만 사용되지 않은것으로 보입니다. 

 - 29891
 - 35967
 - 38909
 - 41466
 - 42031
 - 44351

**Comment by aanoaa** [comment]
쿠폰이 두번이상 지급되는 버그가 있는 것은 알고 있었습니다.
그 수량에 대해서는 알아보았습니다.

``` sql
SELECT coupon_id, COUNT(coupon_id) AS a FROM `order` GROUP BY coupon_id HAVING a > 1;
```

100건이 넘습니다.
5417 쿠폰은 8개의 주문서에 포함되어 있습니다.

이게 전부 버그에 의한 것은 아닙니다.
미방문자가 다시 쿠폰으로 예약했다면 주문서에 쿠폰이 발급됩니다.

**Comment by aanoaa** [comment]
한번 사용된 쿠폰은 계산할때에 `사용된 쿠폰` 이라고 표시됩니다.
어떻게 처리되었는지 궁금합니다.

이렇게 중복해서 지급된 쿠폰이 통계상에 더해졌기 때문에 @yongbin 님의 쿼리 결과와 실제 사용된 쿠폰의 수가 다른게 아닐까 합니다.

**Comment by aanoaa** [comment]
- 노출된 링크를 통해서 중복지급된 쿠폰
- 세션버그로 인해 중복지급된 쿠폰

에 의해 하나의 쿠폰이지만 여러번 사용된 횟수가 더해져서 통계상의 수치와 실제 사용된 쿠폰의 숫자가 다릅니다.

'사용된 쿠폰' 일 경우에 현금이나 카드 결제를 받아야 했지만, 사용가능한 쿠폰으로 인식해서 무료로 대여해주었습니다.
정확하게 사용된 쿠폰수는

    SELECT status, COUNT(*) FROM coupon WHERE `desc` LIKE 'seoul|%' GROUP BY status;

`used` 의 수치가 맞지만 무료로 대여해준 횟수는 아래의 패치된 통계상의 수치가 가깝습니다.

https://github.com/opencloset/opencloset/issues/1111#issuecomment-269424866
