### ISSUE TITLE
대여, 주문서 탭에 online/offline 구분을 하도록 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1115]
현재 온라인 오프라인 공통으로 사용 중인 대여, 주문서 탭에 온라인/오프라인을 구분 할 수 있도록 요청드립니다.
구분 정보는 가장 왼쪽에 있는 주문서 번호 혹은 순서 오른쪽에 표시되도록 요청드립니다. 매일 온라인 발송 시간에는 헷갈린다고 하니 빠른 작업 요청드립니다. ^^
![2016-12-29 3 40 05](https://cloud.githubusercontent.com/assets/4696328/21538146/4ae8f476-cddd-11e6-97a8-a88e129347c9.png)

**Comment by 10001if** [comment]
![2016-12-29 3 40 16](https://cloud.githubusercontent.com/assets/4696328/21538167/7de572a0-cddd-11e6-8e21-6e83e02c6ddf.png)

**Comment by aanoaa** [comment]
![- 2017-01-11 12-06-56](https://cloud.githubusercontent.com/assets/170528/21833830/c01c34ce-d7f6-11e6-990c-4bc8f1c6bfd3.png)
![- 2017-01-11 12-06-07](https://cloud.githubusercontent.com/assets/170528/21833831/c057e6cc-d7f6-11e6-9796-1c19806ec4f4.png)

온/오프라인을 구분하는 테이블의 행을 추가해보니까 너무 넓어져서,
주문서 번호와 이름 옆에 녹색 동그라미로 온라인 주문서를 표시하였습니다.

**Comment by 10001if** [comment]
@aanoaa 녹색 동그라미가 있는게 온라인 주문서인거죠~?

**Comment by 10001if** [comment]
@aanoaa 없는게 오프라인 주문서이구요~?

**Comment by aanoaa** [comment]
네 맞습니다.
녹색 동그라미 위에 마우스 올리면 `online` 이라고 나타납니다.

**Comment by 10001if** [comment]
@aanoaa 그런 기능까지.. 세심하시네요! 감사합니다. ^^

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
