### ISSUE TITLE
온라인 문자 발송용 웹발신 전화번호 변경

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1117]
현재는 070-4325-7521 과 070-7583-7521 번호를 사용 중입니다.
070-4325-7521는 4층에서 열린옷장 전체 안내를 070-7583-7521는 지하에서 온라인 전용으로 사용 중입니다.

그런데, 열린옷장에서 보내는 웹발신 문자가 자꾸 스팸 처리 된다는 제보가 제법 많았습니다.
가장 의심이 되는 부분은 070 번호의 사용이었습니다. 그래서 번호를 변경하였고 02-6929-1020 번호를 사용 중입니다.

본 이슈는 https://github.com/opencloset/opencloset/issues/1100 에서 해결되었습니다.

이번 이슈에서는 온라인 용도로 사용 중인 070-7583-7521 번호의 변경입니다.

070-7583-7521 번호를 02-6929-1029로 변경 요청드립니다.

**Comment by keedi** [comment]
본 이슈는 모니터 웹응용 쪽의 이슈이므로 그 쪽에서 처리하기로 하고 이슈 닫습니다.
