### ISSUE TITLE
분실 또는 폐기될때 셋트의류를 해제

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1118]
의류의 상태가 분실, 폐기로 변경될 때.

그 의류가 세트라면
세트로 맺어졌던 상태가 자동으로 풀리도록 수정 요청드립니다.

**Comment by aanoaa** [comment]
#1127 이슈와 비슷한 주제 입니다.

- [ ] opencloset home
- [ ] donation 의류태그 관리

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
