### ISSUE TITLE
태그에 대한 설명추가

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#1120]
`4층보관` 이란 태그 이름에 대한 설명을 덧붙여야 합니다.

**Comment by aanoaa** [comment]
태그를 만든사람의 의도를 사용하는 사람에게 전달해주려는 의도입니다.

**Comment by aanoaa** [comment]
현재 태그관리는 opencloset 에서 하고 있습니다.

opencloset(staff)은 계속해서 기능을 분리해나가고 있습니다.
이런상황에서 기능을 추가하기가 적절하지 않아 보입니다.

대체할 만한 서비스 도메인이 있을까요?
개인적으로 태그관리는 opencloset 이 가장 적절해보이긴 합니다.

다른 의견이 없다면 opencloset 에서 진행하도록 하겠습니다.

cc @keedi @yongbin

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
