### ISSUE TITLE
공휴일에는 연체문자(반납일 이후 문자)가 발송되지 않도록 함

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#1121]
D 가 반납일이라고 한다면

- D+1
- D+2
- D+3

문자가 공휴일에는 전송되지 않아야 합니다.

**Comment by aanoaa** [comment]
OpenCloset-Cron-SMS 의 이슈입니다.
volunteer 등에서 공휴일과 관련된 작업이력이 있습니다.
참고해서 작업하면 되겠습니다.

**Comment by 10001if** [comment]
아직 확인은 하지 못했지만, 문제가 생기면 다시 이슈를 열도록 하겠습니다.
