### ISSUE TITLE
문자메세지 발신번호의 변경

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1122]
현재 070-7583-7521 번호로 안내되는 문자 or 이메일 or 안내가 있다면 모두 02-6929-1029 로 변경 요청드립니다. 02-6929-1029의 웹발신 전화번호 등록이 완료되어 온라인 대시보드에서는 02-6929-1029 번호로 발송이 되고 있습니다.

**Comment by aanoaa** [comment]
모든 서비스에서 기존에 사용되던 번호인 `070-7583-7521` 를 `02-6929-1029` 로 바꾸어야 합니다.

**Comment by aanoaa** [comment]
바뀔번호는 웹발신번호로 이미 등록해놓았습니다.

**Comment by aanoaa** [comment]
각 서비스의 설정파일, `lib`, `template`, `*.js` 등을 뒤져봤습니다.

- [ ] opencloset 설정파일
- [ ] opencloset visit.coffee
- [ ] donation https://donation.theopencloset.net/guide1
- [ ] donation 기증박스 반송신청 화면
- [ ] volunteer 설정파일
- [ ] OpenCloset-Plugin-Helpers
- [ ] monitor 설정파일
- [ ] monitor online.coffee

**Comment by aanoaa** [comment]
#1100 이슈를 보면 `02-6929-1020` 번호는 등록되었지만 `02-6929-1029` 웹발신 번호로 등록되지 않았습니다.

**Comment by aanoaa** [comment]
https://github.com/opencloset/monitor/issues/142 에서 `02-6929-1029` 번호가 등록되었습니다.

**Comment by aanoaa** [comment]
- [ ] OpenCloset-Plugin-Helpers 를 새로 배포해야 합니다.

**Comment by aanoaa** [comment]
모두 배포하고 적용했습니다.

**Comment by aanoaa** [comment]
extra holiday 파일을 따로 두고 `2017-01-30` 일을 대체휴일로 지정했는데 봉사활동프로그램에서 제대로 동작하지 않습니다.

원인을 찾아야 합니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^

**Comment by 10001if** [comment]
>현재 070-7583-7521 번호로 안내되는 문자 or 이메일 or 안내가 있다면 모두 02-6929-1029 로 변경 요청드립니다. 02-6929-1029의 웹발신 전화번호 등록이 완료되어 온라인 대시보드에서는 02-6929-1029 번호로 발송이 되고 있습니다.

@aanoaa 제가 올려놓고 모르고 있었습니다.. 02-6929-1029가 아니라 02-6929-1020 번호로 발송이 되어야 합니다. 

02-6929-1029는 온라인 번호이고, 이를 제외한 모든 문자는 02-6929-1020로 발송되어야 합니다.
예> 대여확정 후 안내문자, 예약완료 문자 등

**Comment by aanoaa** [comment]
`0269291029` 으로 발송된 메세지를 확인해봤습니다.

```
[열린옷장] xxx님, 1일 연장으로 추가 금액 6,000...
[열린옷장] xxx님의 의류가 정상적으로 반납되었습니다.
열린옷장 인증번호: xxxxxx
안녕하세요. xxx님이 9월 23일에 신청하신 자원봉사
xxx 기증자님, 안녕하세요. 열린옷장입니다.
xxx님, 신청하신 주문이 정상적으로 결제완료 되었습니
xxx 기증자님, 반송 신청 완료되었습니다. 신청하신대
[열린옷장] xxx님 안녕하세요. 택배반납을 하시거나
```

이 정도인 것 같습니다.
각각의 메세지가 어디에서 발송되는지 확인해서 발신번호를 변경하겠습니다.

변경된 후에도 잘못된 부분이 있으면 알려주시기 바랍니다.

**Comment by aanoaa** [comment]
```
[열린옷장] xxx님, 1일 연장으로 추가 금액 6,000... - staff | 가상계좌 전송하기 버튼 (OpenCloset::Plugin::Helpers)
[열린옷장] xxx님의 의류가 정상적으로 반납되었습니다.   - staff | 의류반납처리 직후 (OpenCloset::API::SMS)
열린옷장 인증번호: xxxxxx                     - visit | OpenCloset::Web::Controller::API + config `$self->config->{sms}{ $self->config->{sms}{driver} }{_from}`
안녕하세요. xxx님이 9월 23일에 신청하신 자원봉사    - volunteer | OpenCloset::Plugin::Helpers
xxx 기증자님, 안녕하세요. 열린옷장입니다.          - donation | OpenCloset::Plugin::Helpers
xxx님, 신청하신 주문이 정상적으로 결제완료 되었습니   - share | 온라인이라서 바뀌면 안됨
xxx 기증자님, 반송 신청 완료되었습니다. 신청하신대   - donation | OpenCloset::Plugin::Helpers
[열린옷장] xxx님 안녕하세요. 택배반납을 하시거나    - staff | OpenCloset::Web::Controller::Order $self->config->{sms}{ $self->config->{sms}{driver} }{_from}
```

**Comment by aanoaa** [comment]
인증번호를 보낼때의 발신번호는 이미 `1020` 으로 되어있는데 왜 `1029` 로 된건지 알 수 없네요.

**Comment by aanoaa** [comment]
배포 & 설치하고 각 서비스를 재시작 했습니다.

**Comment by 10001if** [comment]
빠른 수정 감사드립니다.
