### ISSUE TITLE
의류상태가 분실, 폐기로 변경될 경우 의류에 입력되어 있는 태그를 자동 삭제하도록 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1127]
의류의 상태를 추가하기 보다는 태그 기능을 통해 의류를 관리하는 방향을 추천해 주셨던 것으로 기억합니다.

때문에 태그를 조금 더 적극적으로 사용하려고 합니다.
이를 위해 불필요하게 기록되어 있는 태그의 상태를 최소화 하고자, 의류가 분실, 폐기 되는 경우 태그가 동시에 삭제 되도록 요청드립니다.

태그 자체가 삭제 되는 것이 아니라
의류에 입력되어 있는 태그가 삭제 되도록 하는 것입니다.
현재는 폐기, 분실 상태에 있는 의류에도 태그가 붙어 있어 태그로 의류를 관리하기에 문제점들이 발생하고 있기 때문입니다.

요청드립니다.

**Comment by aanoaa** [comment]
> 의류의 상태를 추가하기 보다는 태그 기능을 통해 의류를 관리하는 방향을 추천해 주셨던 것으로 기억합니다.

저는 그런적 없는 것 같습니다. 의류의 area 에 대해 얘기한 적은 있습니다.

**Comment by aanoaa** [comment]
의류의 상태를 변경할 수 있는 곳을 파악해야 합니다.

`분실`, `폐기` 로 상태를 변경할 수 있는 곳은

- opencloset 의 home
- donation 의 의류 태그 관리

입니다.

이 두 곳 이외에 상태를 변경할 수 있는 채널이 있으면 알려주세요.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^

그리고

> 의류의 상태를 추가하기 보다는 태그 기능을 통해 의류를 관리하는 방향을 추천해 주셨던 것으로 기억합니다.

이 발언은 대표님께서 해주셨었습니다~ 사일렉스의 전체 의견이라고 생각했나봅니다~ ^^

**Comment by 10001if** [comment]
> opencloset 의 home
>  donation 의 의류 태그 관리
> 입니다.
> 
> 이 두 곳 이외에 상태를 변경할 수 있는 채널이 있으면 알려주세요.

이 두 곳 이외에 상태를 변경할 수 있는 채널은 존재하지 않습니다.
