### ISSUE TITLE
"의류보관 박스 영구보관(09-01)" 태그가 붙어있는 의류의 상태를 대여불가로 변경

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1131]
의류보관 박스 영구보관(09-01) 태그가 붙어 있는 의류의 상태를 전부 대여불가로 바꾸고자 합니다.

일일이 상태를 변경하는게 어려워 일괄로 상태 변경을 요청드리고자 합니다.

**Comment by 10001if** [comment]
태그 정리를 한번에 하고 있는데, 본 작업이 마무리 되어야 다음 작업을 진행할 수 있어서 신속하게 요청드리고자 합니다. ^^

**Comment by aanoaa** [comment]
https://staff.theopencloset.net/clothes?tag=80

60여개의 의류가 등록되어 있고 현재 상태가 `폐기` 입니다.
폐기된 의류인데 대여불가로 변경하나요?

**Comment by 10001if** [comment]
@aanoaa 네 맞습니다. 저희가 태그를 잘못 사용하고 있었습니다. 그 60개의 의류는 현재 지하에 보관 중입니다. 상태를 폐기로 처리하는게 편하다고 생각해서 그렇게 하고 있었습니다. 그런데 폐기는 저희가 보유하고 있지 않은 의류를 뜻하는 것이기에 앞으로는 대여불가 상태로 하고 태그를 통해 의류의 현재 위치와 내용에 대해 파악하려고 합니다. 60개의 의류는 `폐기`가 아니라 `대여불가` 상태로 변경되어야 합니다.

**Comment by aanoaa** [comment]
의류의 상태를 변경하는 작업은 항상 조심해야 합니다.
대여중인 상태의 의류가 있는지 꼭 확인해봐야 합니다.

**Comment by aanoaa** [comment]
아래 스크립트를 실행햐면 되겠습니다.

``` perl
use strict;
use warnings;
use OpenCloset::Config;
use OpenCloset::Schema;
my $occ = OpenCloset::Config->new( file => "app.conf" );
my $schema = OpenCloset::Schema->connect( $occ->dbic );

my $tag = $schema->resultset('Tag')->find( { id => 80 } );
my $clothes = $tag->clothes;

my $cnt = $clothes->search( { status_id => 2 } )->count;
die "rent: $cnt\n" if $cnt;

$clothes->update( { status_id => 3 } );
```

**Comment by aanoaa** [comment]
적용하였습니다.

**Comment by 10001if** [comment]
@aanoaa 지난 주에 모두 눈으로 직접 확인한 건입니다. 신경 써주셔서 감사드립니다~ ^^
