### ISSUE TITLE
여성 자켓의류 세트 해제시 오류발생

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1135]
여성의류 전체가 모두 그런 것으로 보이는데, 우선 제가 해본 의류코드는 J25N/K0Y6 입니다.
세트 처리된 의류를 해체하고자 할 때 스커트에서 자켓을 해체하면 오류없이 진행되나, 자켓에서 스커트를 해체하면 error 라는 표시가 상단에 드면서 해체가 되지 않습니다. 확인 부탁드리겠습니다~
![2017-01-12 11 40 53](https://cloud.githubusercontent.com/assets/4696328/21875035/4711fe62-d8bc-11e6-91de-1dec132bc3a5.png)

**Comment by aanoaa** [comment]
`DELETE /api/suit/:code` 를 요청했을때에 응답코드 400과 함께 아래 내용을 받습니다.

    {"error":{"data":{"code":"REGEXP_CONSTRAINT_FAILED"},"str":"code:REGEXP_CONSTRAINT_FAILED"}}

**Comment by aanoaa** [comment]
스커트의 의류코드는 `K` 인데 코드상에서는 셔츠의 `S` 를 사용하고 있습니다.
실수로 인한 버그 같습니다.
