### ISSUE TITLE
푸터 하단에 있는 전화번호의 변경

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1138]

**Comment by aanoaa** [comment]
`OpenCloset::Plugin::Helpers::footer` 와 `opencloset.css` 를 함께 사용하시면

https://donation.theopencloset.net/ 의 footer 와 같은 결과를 얻을 수 있습니다.

참고

- https://github.com/opencloset/OpenCloset-Plugin-Helpers/blob/develop/lib/OpenCloset/Plugin/Helpers.pm#L195
- https://github.com/opencloset/opencloset.css/blob/master/dist/css/opencloset.css#L66

**Comment by 10001if** [comment]
@keedi 소요시간이 오래 걸리는 작업이 아니라면, 선작업 부탁드립니다. 많이 보는 페이지는 아니지만 그래도 잘못된 전화번호가 떠 있는 부분은 빠른 수정이 이뤄지면 좋을 듯 합니다. ^^

**Comment by keedi** [comment]
오늘 처리해두겠습니다. :)

**Comment by keedi** [comment]
지금까지는 관리의 편의 때문에 재고관리 쪽에도 남겼지만 앞으로는 가능하면 관련 있는 별개의 이슈가 아니면 양쪽에 남기지 않았으면합니다. 이슈가 많다보니 헷갈리네요. ㅎ
