### ISSUE TITLE
방문자 통계에서 2016-12월의 통계가 나타나지 않음

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1139]
![2017-01-12 4 06 25](https://cloud.githubusercontent.com/assets/4696328/21880297/8e428174-d8e1-11e6-8424-0571ede74d6d.png)
@yongbin 아예 방문자 통계 인원의 집계가 나타나지 않습니다. 확인 부탁드립니다.

**Comment by keedi** [comment]
담당자 변경합니다.

**Comment by keedi** [comment]
#637 이슈와 연관 있었던 것 같습니다. 1년만의 이슈라 확인해야 하는데 동일한 사유라면 비교적 간단히 해결할 수 있을 것 같습니다.

**Comment by keedi** [comment]
진행합니다.

**Comment by keedi** [comment]
#659 에서 2016년 5월에 발견했던 동일한 이슈입니다. 2015년 12월의 통계자료가 보이지 않음이 보고되었었으며, 관련해서 연도가 바뀜으로 인해 자동 캐싱이 되지 않아 발생한 문제입니다. 당시에도 연말 자료는 실서버에서 수동으로 캐싱을 생성했습니다.

> @10001if 당시 해가 바뀔때 내부 캐싱 문제 때문에 12월 분량이 연산되지 않았던 이슈입니다. 실서버에 강제로 연산시켜 결과를 캐싱시켜놓았으니 이제 잘 보일 겁니다. :)
> 
> 해당 페이지 관련해서 이슈가 있을 경우 별도 이슈를 열어서 기록해주세요~

**Comment by keedi** [comment]
실서버에서 다음 명령을 수행해 2016년 12월 캐시를 강제 생성했습니다.

```bash
$ bin/opencloset-stat-visitor-cache.pl app.conf 2016-12-31
caching: day-20161231000000-20161231235959
caching: month-20161201000000-20161231235959
You have new mail in /var/mail/opencloset
$
```

**Comment by keedi** [comment]
작업 완료했습니다. 이슈 닫습니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
