### ISSUE TITLE
대여 화면에서 예약자의 이전 방문 기록 확인

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1142]
대여탭 `/rental/` 에서 예약자의 이전 방문 기록을 확인 할 수 있도록 함

최초 방문 시 예약자가 이전에 몇 번 대여했었는지 기록을 확인하고자 합니다. 
현재는 주문서 상단에 표시가 되고 있습니다.

![2017-01-13 5 13 04](https://cloud.githubusercontent.com/assets/4696328/21922811/d1f72924-d9b3-11e6-8032-37c1ee4f0097.png)

하지만 최초 방문시에도 쉽게 확인 할 수 있도록 요청드립니다.

![2017-01-11 2 07 27](https://cloud.githubusercontent.com/assets/4696328/21922784/aca0fbfa-d9b3-11e6-9ad5-71b21198cf8d.png)

![2017-01-11 2 07 19](https://cloud.githubusercontent.com/assets/4696328/21922786/aea5c8ae-d9b3-11e6-91c3-1bdc3a6756ef.png)

**Comment by keedi** [comment]
담당자 변경합니다.

**Comment by keedi** [comment]
마지막 갈무리 화면의 경우 실수가 있다고 합니다. 마지막 팝업의 각 항목별로 이전 방문 기록이 보여야 된다고 합니다.

**Comment by keedi** [comment]
진행합니다.

**Comment by keedi** [comment]
구현한 화면은 다음과 같습니다.

팝업에서 보이는 모습입니다.
![2017-01-23 18-43-34](https://cloud.githubusercontent.com/assets/138451/22201054/593b3490-e1a5-11e6-99b6-bef2d52edf8b.png)

팝업에서 선택 이후 보이는 모습입니다.
![screenshot-monster silex kr 10301-2017-01-23-19-49-48](https://cloud.githubusercontent.com/assets/138451/22201070/6c3e5478-e1a5-11e6-8724-e1c6dd4e92e6.png)

**Comment by keedi** [comment]
작업 완료했습니다. 이슈 닫습니다.

**Comment by 10001if** [comment]
@keedi 배포가 아직 안된 것 같습니다. 혹시 언제쯤 배포 될지 확인 부탁드리겠습니다. ^^

**Comment by 10001if** [comment]
@keedi 아직 적용이 되지 않은 것 같습니다. 확인 부탁드리겠습니다.

**Comment by aanoaa** [comment]
![- 2017-02-08 18-04-27](https://cloud.githubusercontent.com/assets/170528/22730142/0e8f4ec8-ee29-11e6-81bb-4f06d87076f8.png)

제가 배포과정에서 실수한 것 같습니다.
다시 한번 확인해주세요.

**Comment by 10001if** [comment]
@aanoaa 아직 안되는 것 같습니다. 내일 출근하시면 다시 여쭤볼게요.

**Comment by keedi** [comment]
음 실섭에서 확인했는데 잘 동작하는 것 같은데요?

![rental-01](https://cloud.githubusercontent.com/assets/138451/22754677/bd8b06a6-ee83-11e6-9a7f-171fdcee4aa7.png)
![rental-02](https://cloud.githubusercontent.com/assets/138451/22754683/c16e0516-ee83-11e6-938a-c97790db4ab6.png)

확인 부탁드립니다. 혹시 여전히 동작하지 않는다면 새로고침 해보신 이후 다시 확인 부탁드립니다.

**Comment by 10001if** [comment]
네. 다시 확인해보니 정상적으로 작동합니다. 감사합니다.
