### ISSUE TITLE
Text::Haml 버전에 따른 오류

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#1143]
**테스트 서버**에서 최신 버전으로 반영하고 재시작하였더니 warning 이 발생하였습니다.

    $ ubic restart opencloset.staff
    Restarting opencloset.staff... Constants from lexical variables potentially modified elsewhere are deprecated at /.../lib/perl5/Text/Haml.pm line 27, <DATA> line 1.
    Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\\\\#\\{ <-- HERE / at /.../lib/perl5/Text/Haml.pm line 968, <DATA> line 1.
    Constants from lexical variables potentially modified elsewhere are deprecated at /.../lib/perl5/Text/Haml.pm line 27, <DATA> line 1.
    Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\\\\#\\{ <-- HERE / at /.../lib/perl5/Text/Haml.pm line 968, <DATA> line 1.

해서 생각없이 모듈을 업그레이드

    $ cpanm Text::Haml
    --> Working on Text::Haml
    Fetching http://www.cpan.org/authors/id/V/VT/VTI/Text-Haml-0.990117.tar.gz ... OK
    Configuring Text-Haml-0.990117 ... OK
    Building and testing Text-Haml-0.990117 ... OK
    Successfully installed Text-Haml-0.990117 (upgraded from 0.990116)

하고 재시작

    $ ubic reload opencloset.staff
    Reloading opencloset.staff... reloaded

이후에는 

    [Tue Jan 17 15:56:49 2017] [error] Template error in "layouts/notlogin.html.haml": Template error in "layouts/default/css-page.html.haml": syntax error at (eval 707) line 18, near ";else"
    syntax error at (eval 707) line 25, near ";}"
    Global symbol "$_H" requires explicit package name (did you forget to declare "my $_H"?) at (eval 707) line 27.

오류가 발생합니다.

https://metacpan.org/changes/distribution/Text-Haml

**Comment by aanoaa** [comment]
<hshong> 혹시 이거 관련된 이슈 아시나요?  [16:03]
    <hshong> 0.990117 2016-04-25T09:25:07Z
    <hshong> 이게 작년 4월에 패치된거라서
    <keedi> 네 전에 남겼는데. 이슈 찾아드릴게요.
    <keedi> 그냥 간단하게 바로 이전 버전 설치하면 됩니다.
    <keedi> 패치 커밋은 되었는데 릴리스를 안해서  [16:04]
    <keedi> 걍 바로 이전버전인 0.990116인가 설치하면 문제 해결될겁니다.

    $ cpanm http://www.cpan.org/authors/id/V/VT/VTI/Text-Haml-0.990116.tar.gz
    --> Working on http://www.cpan.org/authors/id/V/VT/VTI/Text-Haml-0.990116.tar.gz
    Fetching http://www.cpan.org/authors/id/V/VT/VTI/Text-Haml-0.990116.tar.gz ... OK
    Configuring Text-Haml-0.990116 ... OK
    Building and testing Text-Haml-0.990116 ... OK
    Successfully installed Text-Haml-0.990116
    1 distribution installed

이전버전으로 되돌렸습니다.

**Comment by keedi** [comment]
작년에 머지는 되었지만 릴리스가 되지 않아 다음 릴리스까지는계속 이슈가 있을 것입니다. 이전 버전 설치로 해결하도록 합니다.

https://github.com/vti/text-haml/issues/40
