### ISSUE TITLE
공유폴더의 의류사진을 시스템에 자동 업로드

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1144]
유료로 지불하여 공유폴더를 사용하게 되는 경우에, 공유 폴더에 의류의 코드명으로 파일명을 만들어 입력하면 자동으로 동기화되어 의류 정보 중에 사진을 입력하는 곳에 사진이 업로드 되도록 함.

본 기능 전에는 사진을 촬영하여 eyefi를 통해 컴퓨터로 옮기는 것은 가능하지만, 의류 정보가 있는 창에서 의류를 업로드 시켜야 하는 번거로움이 있습니다. 작업의 우선 순위는 높지 않으나, 이슈에 적혀져 있지 않아 작성하였습니다.

**Comment by aanoaa** [comment]
설명들어갑니다.

- 특정 디렉토리에 카메라로 찍은 사진들이 동기화됩니다(eyefi)
- staff 이 그 파일명을 `J001.jpg` 처럼 변경합니다.
- 디렉토리에 변경이 있으면 스캔해서 의류사진을 자동으로 업로드

하는 기능입니다.
작업 볼륨이 매우 있어 보입니다.(위..윈도우즈 application?)

cc @keedi @yongbin

**Comment by MoDoLEE** [comment]
자동 업로드 기능이 있는 FTP 프로그램이 있네요. 폴더 내의 변경 사항이 있으면 지정된 곳에 업로드가 가능한 것 같습니다. 스케줄링해서 일정 시간마다 업로드도 가능하고요.

http://www.nchsoftware.com/fling/index.html

**Comment by aanoaa** [comment]
생각해보니 윈도우즈 application 일 필요가 없는게, rsync 도 있고 ftp 도 있고 동기화 하는 방법은 여러가지가 있습니다.

동기화 직후에 추가된 파일에 대해서 사진을 등록하면 될 것 같습니다.

**Comment by keedi** [comment]
관련 이슈는 제가 전담하겠습니다. 담당자 변경합니다.

**Comment by 10001if** [comment]
정말 필요한 이슈인지 조금 더 고민이 필요합니다. 이슈 닫도록 하겠습니다.
