### ISSUE TITLE
예약 확인 안내창의 전화번호 변경

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1147]
현재 02-6929-1029의 번호로 안내되고 있습니다. 
02-6929-1020 번호로 수정 요청드립니다. 

1029는 지하에서 온라인/자원봉사자 안내 전용으로 사용 중입니다.
1020이 열린옷장 대표 번호 입니다. 빠른 수정 요청드립니다.

![2017-01-20 12 09 57](https://cloud.githubusercontent.com/assets/4696328/22134559/42e81c2c-df0b-11e6-8a9f-40e6495c5e73.png)

**Comment by 10001if** [comment]
@keedi  빠른 수정 요청드립니다. ^^

**Comment by keedi** [comment]
진행합니다.

**Comment by keedi** [comment]
수정 및 배포 완료했습니다.

![screenshot-visit theopencloset net-2017-01-20-13-25-23](https://cloud.githubusercontent.com/assets/138451/22135835/168dc5ec-df14-11e6-9346-99ad47537067.png)

**Comment by keedi** [comment]
다만 클라이언트(사용자) 브라우저에서 캐싱하고 있을 수 있으므로 이전과 동일하게 보인다면 새로 고침을 해야지만 적용 된 화면을 볼 수 있습니다. (사용자에게 그것을 요청하기 쉬운 일은 아니겠지만...)

**Comment by keedi** [comment]
이슈 닫습니다.
