### ISSUE TITLE
일일 정산 메뉴 및 페이지 추가

### ISSUE THREAD

**Issue by keedi** [opencloset/opencloset#115]
현재는 일일 정산, 즉 시제를 맞추는 것이 굉장한 일이라고 합니다. 받은 금액과 서류상 금액을 계산해서 맞추어야 하는데 서류상 금액을 정산하는 일이 매우 번거롭다고 합니다. 따라서 주문서를 기반으로 시스템적으로 해당 날짜의 시제를 정산할 수 있는 페이지를 구현하고 좌측에 메뉴를 추가합니다.

요구사항은 다음과 같습니다.
- 당일 현금 총 금액 표시
- 당일 카드 총 금액 표시
- 당일 입금 총 금액 표시
- 당일 현금영수증 총 금액 표시
- 당일 세금계산서 총 금액 표시
- 일일 정산 페이지는 지정한 사용자만 열람할 수 있어야 함

**Comment by keedi** [comment]
연체료나 배상료 때문에 일일 정산 이라는 개념이 조금 모호한 부분이 있습니다. 관련해서 논의 후 처리해야 합니다.

**Comment by keedi** [comment]
현재 모든 주문의 비용 항목은 주문서 단위로 저장하고 있습니다. 따라서 주문서 단위 정산은 가능하지만 현재는 일일 정산은 불가능한 시스템입니다. 논의해본 결과 주문서 단위 정산이 아닌 일일 정산이 필요하다고 합니다. 마치 은행처럼 매일매일 현금과 카드 등의 내역을 관리하고 궁극적으로는 홈페이지에 실시간 공개를 통해 투명하게 거래 내역을 공개하는 것이 목표라고 합니다.

궁극적으로는 주문서 단위 시제도 금액적인 측면에서는 문제 될 것이 없으나 주문서의 생명 주기가 보통 4일이고 연체가 생길 경우 더 늘어나기도 하기 때문에 사람이 주문서 단위로 정산을 하며 매일매일 돈을 관리한다는 것은 어려운 것이 사실입니다. 따라서 일일 정산이 가능하도록 수정해서 구현하도록 합니다.

**Comment by keedi** [comment]
요구 사항 확인 완료했으므로 *논의필요* 라벨은 제거합니다. :)

**Comment by keedi** [comment]
일정을 고려해 마일스톤에서 제거합니다. 더불어 #481 항목과 같은 주문서 관련 변경 사항이 있기 때문에 순위를 뒤로 미루겠습니다.

**Comment by aanoaa** [comment]
볼륨이 좀 있는 이슈라고 생각됩니다.
마일스톤을 변경하겠습니다.

**Comment by aanoaa** [comment]
- [ ] 당일 현금 총 금액 표시
- [ ] 당일 카드 총 금액 표시
- [ ] 당일 입금 총 금액 표시
- [ ] 당일 현금영수증 총 금액 표시
- [ ] 당일 세금계산서 총 금액 표시

위에서 언급한 금액의 계산식을 만들어야 합니다.
특정일을 가지고 실제 매출과 비교해 볼 수 있도록 특정일의 일일정산에 대한 수치를 알려주세요.

**Comment by aanoaa** [comment]
2016-04-11 을 기준으로 해보겠습니다.

**Comment by aanoaa** [comment]
매출 = 대여비 + 연체/연장비 ?

**Comment by aanoaa** [comment]
대여와 연체비를 제외하고 더 수입이 발생할 수 있는 곳이 있나요?

**Comment by aanoaa** [comment]
저의 궁금증

- 주문서의 상태가 변경되는데 지난날의 이력을 쫓을 수 있을까?
  - 1년전 오늘의 매출을 알 수 있을까?

**Comment by aanoaa** [comment]
주문서의 대여비: stage 가 0 인 final_price 의 합

대여비는 `rental_date` 를 기준으로 범위를 찾고,

    주문서의 연체비: stage 가 1 인 final_price 의 합

연체비는 `return_date` 를 기준으로 찾아야..

**Comment by yongbin** [comment]
주문서의 상태변경이력은 트리거로 DB에 쌓이고 있습니다. 일일정산을 염두한건 아니지만 도움이 될수도 있을것 같아서 말씀드립니다.

**Comment by aanoaa** [comment]
주문서의 상태와 관계없이 일일정산내역을 계산할 수 있습니다.

**Comment by aanoaa** [comment]
```
연체 10,000
미납인데 2,000 은 받음 나중에 8,000 받기로 함 <- 이 기능이 없다
```

미납금을 분할해서 받을 수 없습니다.

정산은 정확해야 해서 이런 문제가 발생합니다.

**Comment by aanoaa** [comment]
위의 경우는 연체인 상황에서 옷은 받았는데, 연체비를 전부 받지는
못했을때 입니다.

- 불납
- 완납

기능인데, 두 기능 모두

    미납 -> 완납
    미납 -> 불납

은 가능합니다. 하지만 문제가 되는것은 미납금을 분할해서 받을때입니다.

    미납(10,000) -> 미납(5,000) -> 완납

가운데 몇번의 분할 납부가 더 있을 지 모릅니다.

**Comment by aanoaa** [comment]
분할반납에 대한 이슈는 다루지 않도록 하고 진행하겠습니다.

**Comment by aanoaa** [comment]
> 매출 = 대여비 + 연체/연장비 ?

미납금이 있습니다.

매출 = 대여비 + 연체/연장비 + 미납금

**Comment by aanoaa** [comment]
2단계 인증을 위한 계정/비밀번호를 이메일을 통해 전달 받았습니다.
배포만 하면 됩니다.

**Comment by aanoaa** [comment]
basic auth 와 비슷한 방법을 통해 2단계 인증을 구현하였습니다.

요청 URL 에 userinfo 가 없을때

    https://staff.theopencloset.net/income
    https://username:password@staff.theopencloset.net/income <- username:password 가 userinfo

status code 401 과 함께

    WWW Authenticate: Basic realm=income

헤더를 응답해서 브라우저에서 userinfo 를 입력할 수 있는 prompt 를 띄웁니다.

그리고 알아서 적절한 세션관리를 해주었습니다.
하지만 basic auth 에서는 logout 기능이 없기 때문에 꼼수를 써서 logout 되도록 하였습니다.

(브라우저는 종료전까지 인증에 성공하면 userinfo 를 달고 다닙니다.)

꼼수란

    https://wrong-username:wrong-password@staff.theopencloset.net/income

로 redirect 해서 browser 의 userinfo 를 덮어쓰게 하는 것 입니다.

여기서 reverse proxy 를 같이 사용할 경우에 문제가 발생합니다.

    my $url = $self->url_for('/')->to_abs
    # http://staff.theopencloset.net/

    $url->userinfo('wrong-username:wrong-password');
    # http://wrong-username:wrong-password@staff.theopencloset.net/

    my $url = $self->url_for('/')
    # /
    $url->userinfo('wrong-username:wrong-password');
    # http:/

상대경로를 사용하면 userinfo 를 붙일 수 없고
절대경로를 사용하면 scheme 이 http 가 되어버립니다.

이 문제를 해결해야 합니다.

**Comment by aanoaa** [comment]
현재 저희 서버의 reverse proxy 설정에 사용되는 
`X-Forwarded-Proto` 헤더를 검사하도록 하면 해결됩니다.

**Comment by aanoaa** [comment]
그리고 계정설정할때에 hashref 에

    10001if => 'password'

가 안되서 왜 안되는고 봤더니 컴파일러가 `if` 문으로 인식합니다 ㅋㅋ

    '10001if' => 'password'

처럼 해결

**Comment by aanoaa** [comment]
707eb9e658117ee628bd941dfd06ba6058fc0d5e

**Comment by aanoaa** [comment]
연체비 의 미납 항목은 실제로 받은 금액이 아니기 때문에 쿠폰처럼 따로 나타나야 합니다.

**Comment by aanoaa** [comment]
쿠폰과 미납을 제외한 결제수단별 합산금액을 나타내야합니다.

**Comment by aanoaa** [comment]
입력한 값을 합계 또한 필요합니다.

**Comment by aanoaa** [comment]
온/오프라인을 구별해야 합니다.

**Comment by keedi** [comment]
정산 페이지 접근은 basic auth가 아니라 사용자 계정에 레벨을 두어 url별로 접근 권한을 처리해야 한다고 생각합니다만... 일단 기록차 남겨둡니다.

**Comment by aanoaa** [comment]
첨엔 사용자별 권한 부여로 생각했는데, 
현실은 자신이 자신의 계정을 사용할 수 없는 실정이라서 이런식으로 처리하였습니다.
1인 1PC 가 아니라 계산/치수측정/반납/포장 등에서 PC 가 사용되고 있고 이를 본인의 계정으로
사용하기가 어려운 실정입니다.

**Comment by aanoaa** [comment]
opencloset 계정을 만들어서 공유하도록하고, 사용자별로 권한을 부여한다면 대안이 될 수 있지 않을까 합니다.

**Comment by aanoaa** [comment]
- [ ] 연체비 의 미납 항목은 실제로 받은 금액이 아니기 때문에 쿠폰처럼 따로 나타나야 합니다.
- [ ] 쿠폰과 미납을 제외한 결제수단별 합산금액을 나타내야합니다.
- [ ] 입력한 값의 합계 또한 필요합니다.
- [ ] 온/오프라인을 구별해야 합니다.

**Comment by aanoaa** [comment]
온/오프라인 매출을 어떻게 구별하는지 탐구생활을..

**Comment by aanoaa** [comment]
`쿠폰+현금` 일때 어떻게하지..

**Comment by aanoaa** [comment]
온라인 매출은 예약시간이 22:00 인 것을 기준으로 삼았습니다.
반납에 대한 건은 고려치 않았고 온라인 대여비만을 고려했습니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^

**Comment by 10001if** [comment]
@aanoaa 10001if의 비밀번호를 변경하고자 합니다~ 전달해 드려야 할 내용 있으면 알려주세요.

**Comment by aanoaa** [comment]
@10001if http://ratfactor.com/sha1 에서 비밀번호로 사용하실 문자열을 넣으신 후에 변환된 값을 저한테만 전달해주세요.

**Comment by aanoaa** [comment]
전달받아서 변경하였습니다.
