### ISSUE TITLE
남자 가슴둘레와 셔츠 가슴둘레의 차이를 최소/최대/평균값으로 나누어 알고자 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1150]
남자 가슴둘레 | 셔츠 가슴둘레 (최소) | 셔츠 가슴둘레(최대) | 셔츠 가슴둘레(평균) | 수
--- | --- | --- | --- | ---
00 | 00 | 00 | 00 | 00

요청드립니다.

**Comment by 10001if** [comment]
추가적으로 윗배둘레에 대한 정보도 동일하게 요청드립니다.

**Comment by yongbin** [comment]
다음 쿼리를 통해서 기초자료를 구할 수 있습니다.

```sql
SELECT
    c.bust
    ,MEAN(d.bust)
FROM `order` AS a
        INNER JOIN `user` AS b ON a.user_id = b.id
        INNER JOIN `user_info` AS c ON b.id = c.user_id
        LEFT JOIN `order_detail` AS d ON a.id = d.order_id
        INNER JOIN `clothes` AS e ON d.`clothes_code` = e.code
WHERE
    c.gender = 'male'
    AND e.gender='male' 
    AND e.category = 'shirt'
GROUP BY a.id
```



@10001if 설명드린것 처럼 보내드린 기초자료를 기반으로 Libreoffice에 피벗 테이블 기능을 이용하면 원하는 결과를 얻을수 있습니다. 참고로 결과 자료에서 한 줄은 주문을 의미하며 cnt 는 주문당 셔츠 주문수를 의미하기 때문에 피벗 구성에서 데이터 영역은 다음과 같이 구성하면 됩니다.
 - min(mean_bust)
 - max(mean_bust)
 - average(mean_bust)
 - sum(cnt)

**Comment by yongbin** [comment]
관련 자료 메일로 송부했습니다.
