### ISSUE TITLE
여성의 키에 따른 총장의 평균 길이를 알고자 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1154]
여성의 키 | 착용했던 스커트 총장의 평균 길이
--- | ----
150 | 46
...|...
180 | 56
합계 | 11200

여성의 키에 따른 스커트 총장의 길이를 체크하여 스커트 수선 길이를 가늠하고자 합니다.
자료 요청드립니다.

**Comment by yongbin** [comment]
```sql
SELECT
    c.height
    ,b.length
FROM `order_detail` AS a
    INNER JOIN `clothes` AS b ON a.clothes_code = b.code
    INNER JOIN `order` AS c ON a.order_id = c.id
WHERE b.gender = 'female'
    AND b.category = 'skirt'
```

**Comment by yongbin** [comment]
[query_result.csv.zip](https://github.com/opencloset/opencloset/files/745243/query_result.csv.zip)

결과를 첨부합니다. 피벗테이블에서 좌측컬럼을 `heigh`t로  data 컬럼을 `length`의 평균으로 지정하면 원하는 통계를 얻을 수 있습니다.
