### ISSUE TITLE
셔츠 팔길이의 수를 알고자 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1155]
남자셔츠 팔길이 | 수
--- | ----
53 | 23
...|...
70 | 5
합계 | 14500

셔츠 팔길이를 3단계로 구분하여 정렬하려고 합니다.
이를 위해  남자셔츠 팔길이 정보를 요청드립니다.

**Comment by yongbin** [comment]
[query_result.csv.zip](https://github.com/opencloset/opencloset/files/731970/query_result.csv.zip)
