### ISSUE TITLE
pdfmake js 라이브러리를 설치할 수 없음

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#1156]
bower pdfmake-dist#~0.1.31     ECMDERR Failed to execute "git ls-remote --tags --heads https://github.com/pdfmake/pdfmake.git", exit code of #128 remote: Invalid username or password. fatal: Authentication failed for 'https://github.com/pdfmake/pdfmake.git/'

bower package 의 버전문제 같은데, https://github.com/pdfmake/pdfmake 가 사라지고 https://github.com/bpampuch/pdfmake 에서 관리되는 듯 합니다.

**Comment by keedi** [comment]
내일 중으로 처리하겠습니다. 우선적으로 `bower install`시 해당 `pdfmake` 부분 제거 후 설치한 후 다시 되돌리는 방식으로 임시 조치 가능합니다.

**Comment by keedi** [comment]
내일은 무신...(혼잣말...) 여튼 기억해두고 있습니다.;;;

**Comment by keedi** [comment]
#947 과 관련이 있는 이슈입니다.

정리하면 원래 저장소는 bpampuch/pdfmake지만 당시 버그패치 등 추가 요구사항이 관리되지 않아 pdfmake/pdfmake 저장소를 사용했었습니다.

**Comment by keedi** [comment]
무슨 영문인지 기록을 찾지 못하겠으나 2016년 11월 당시 bpampuch/pdfmake 저장소는 2015년 11월 0.1.20 릴리스가 마지막이었습니다만, 이후 각지(?)의 패치 및 수정 사항이 쭉 반영된 것으로 보입니다. 당시 브라우저의 js 오류를 잡는 패치가 반영된 pdfmake/pdfmake는 0.1.20 이후 자체적으로 버전업을 진행해서 0.1.31까지 버전업을 했던 것으로 기억합니다. 어쨌든 pdfmake/pdfmake 저장소는 없어졌으며 bpampuch/pdfmake 저장소는 새롭게 릴리스를 시작해서 0.1.25 까지 릴리스가 된 것으로 보입니다.

**Comment by keedi** [comment]
0.1.25 버전으로 테스트 결과 브라우저 오류 없이 정상 동작함을 확인했습니다.

**Comment by keedi** [comment]
이슈 닫습니다.

**Comment by aanoaa** [comment]
배포후에 pdfmake 가 출력되지 않았습니다.
해서, pdfmake 의 bower package 가 변경됨을 보고

    $ bower install
    bower pdfmake#~0.1.25           cached https://github.com/bpampuch/pdfmake.git#0.1.25
    bower pdfmake#~0.1.25         validate 0.1.25 against https://github.com/bpampuch/pdfmake.git#~0.1.25
    bower pdfmake#~0.1.25          install pdfmake#0.1.25
    bower                          skipped pdfmake was not installed because there is already a non-bower directory with that name in the components directory (public/components/pdfmake). You can force installation with --force.

했지만, 오류가 발생 해서 `pdfmake` 디렉토리를 다른 곳에 백업해놓고

    $ rm -rf public/components/pdfmake
    $ bower install
    $ grunt

해주었습니다.
지금은 다시 동작합니다.
