### ISSUE TITLE
사용자정보에서 만료된 인증번호가 보이지 않음

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#1158]
![a](https://cloud.githubusercontent.com/assets/170528/22535418/6acb63a6-e93e-11e6-8c33-9102b902a34b.png)

원래는 여기에 인증번호가 보여야 합니다.

왜 보여야 하는지는 기억나지 않습니다.
보이는 걸 불러주는건지 아니면 다시 문자메세지가 보내지는 건지...

**Comment by keedi** [comment]
인증번호 추가랑 갱신 버튼은 직접 추가하셨던 것 같은데요.

#837

**Comment by aanoaa** [comment]
제가 작업한 것은 맞는데, `만료됨` 버튼을 눌렀을때 sms 가 전송되는 건지, 만료기간이 늘어나는 건지
기억이 나질 않습니다.

인증번호가 표시되고 `만료됨` 버튼을 눌렀을때 만료기간이 5분간 늘어나는 것 같습니다.

옷장지기는 표시된 인증번호를 대여자에게 직접안내하는 용도인 것 같습니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
