### ISSUE TITLE
대여 의류 연체시 SMS 전송

### ISSUE THREAD

**Issue by keedi** [opencloset/opencloset#116]
반납 기일을 지키지 못한 경우 대여자에게 SMS를 전송해야 합니다.

요구 사항은 다음과 같습니다.

- 반납 예정일이 아닌 *반납 희망일*을 기준으로 계산
- 아직 구현되진 않았지만 온라인 대여를 제외한 오프라인 대여에 한해 SMS 전송
- 반납 희망일 기준 1일, 3일, 5일 지났을 경우 오전 9시에 문자 메시지를 일괄 발송
- 1일차 메시지: 열린옷장입니다. XX일에 대여하셨던 대여 의류가 연체중입니다. 오늘 중으로 반납해주세요.
- 3일차 메시지: 열린옷장입니다. XXX님 대여 의류가 연체중입니다. 확인 후 반납바랍니다.
- 5일차 메시지: 열린옷장입니다. XXX님 XX일 째 연체입니다. 연락바랍니다.
- 5일차 이후 연체자는 따로 SMS를 전송하지 않음(전화를 하든 직원이 직접 관리한다고 함)

**Comment by keedi** [comment]
문구나 조건 등 확실하게 짚고 넘어가야 합니다.

**Comment by 10001if** [comment]
반납 예정일이 아닌 반납 희망일을 기준으로 계산
반납 희망일 기준 1일, 3일, 5일 지났을 경우 오전 11시에 문자 메시지를 일괄 발송

- 반납일 +1일 : 000님, 열린옷장입니다.  XX일에 대여하셨던 대여 의류가 연체중입니다. 오늘 중으로 반납 부탁드립니다. 

- 반납일 +2일 : 000님, 열린옷장입니다.  대여하신 의류가 반납되지 않고 있습니다. 연체료는 하루에 대여료의 20%씩 부과됩니다. 현재 000님의  연체료는 00000원입니다. 

- 반납일 +3일 : 000님, 열린옷장입니다.  대여하신 의류의 반납이 지체되고 있습니다.  약정 대여기간으로부터 3일이 연체되었습니다.  연체료는 1일 지날 때마다 전체 대여료의 20%씩 부과됩니다. 더이상 지체하지 마시고 빠른 반납 부탁드립니다. 

- 반납일 +4일 이후 연체자는 따로 SMS를 전송하지 않음(전화를 하든 직원이 직접 관리할 예정)

**Comment by keedi** [comment]
@10001if 상기 메시지 그대로 사용하면 되는지요? 희망일을 연장일로 고려하는 등 변화가 꽤 있는 터라 그대로 사용하실 것인지 아니면 수정하실 것인지요? 확인 부탁드립니다.

**Comment by keedi** [comment]
APIStore 서비스 체결 이후 #264 항목 처리를 통해 SMS 후불 결제가 가능해졌으므로 예약 전송 기능도 진행하려고 합니다.

**Comment by 10001if** [comment]
반납일 +1일 : 000님, 열린옷장입니다. XX일에 대여하셨던 대여 의류가 반납 되지않았습니다. 오늘 중으로 반납 부탁드립니다.

반납일 +2일 : 000님, 열린옷장입니다. 대여하신 의류가 반납되지 않고 있습니다. 추가금액은 하루에 대여료의 20%씩 부과됩니다. 현재 000님의 추가금액은 00000원입니다.

반납일 +3일 : 000님, 열린옷장입니다. 대여하신 의류의 반납이 지체되고 있습니다. 약정 대여기간으로부터 3일이 지났습니다. 추가금액은 1일 지날 때마다 전체 대여료의 20%씩 부과됩니다. 더이상 지체하지 마시고 빠른 반납 부탁드립니다.

반납일 +4일 이후 연체자는 따로 SMS를 전송하지 않음(전화를 하든 직원이 직접 관리할 예정)

**Comment by 10001if** [comment]
상기 메세지로 부탁드리려고 하는데, 옷장지지들의 의견을 한번만 수렴해 본 뒤 확답 남기겠습니다.

**Comment by 10001if** [comment]
- 반납일 +2일 : ooo님, 열린옷장입니다. xx일에 대여하셨던 의류가 반납되지 않았습니다. 오늘 중으로 반납 부탁드립니다.

- 반납일 +3일 : ooo님, 열린옷장입니다. 의류 반납이 지연되고 있습니다. 추가금액은 하루에 대여료의 20%씩 부과됩니다. 현재 ooo님의 추가금액은 ooooo원입니다.

확인 완료하였습니다. 이렇게 부탁드립니다. (+1일은 문자를 보내지 않기로 하였습니다.)

**Comment by keedi** [comment]
메시지 확인했습니다. SMS 전송 시각은 언제로 하면 되는지요?

예를 들면 6월 22일이 반납 예정일 입니다. 이때 반납일+2일은 6월 24일입니다. 6월 24일 몇시에 전송하면 되는지요?

**Comment by 10001if** [comment]
오전 11시에 발송해주시면 됩니다. :)

**Comment by keedi** [comment]
진행합니다.

**Comment by 10001if** [comment]
< 위에 부탁드렸던 문자메세지 내용은 무시하시고 아래 내용으로 추가 부탁드립니다. >
< 시간은 오전 11시 발송으로 요청드립니다>

- 반납일 +2일 : [열린옷장] xx일에 대여하셨던 의류가 반납되지 않았습니다. 빠른 반납 부탁드립니다.

- 반납일 +3일 : [열린옷장] ooo님, 의류 반납이 지체되고 있습니다. 추가금액은 하루에 대여료의 20%씩 부과됩니다. 현재 ooo님의 추가금액은 ooooo원입니다.

**Comment by keedi** [comment]
opencloset/OpenCloset-Cron#2 이슈가 완료되면 본 이슈를 닫겠습니다.

**Comment by keedi** [comment]
opencloset/OpenCloset-Cron-SMS#1 에서 처리하겠습니다.

**Comment by keedi** [comment]
OpenCloset::Cron::SMS 0.003 버전을 릴리스했습니다.

릴리스 모듈은 다음 위치에서 확인할 수 있습니다.

https://cpan.theopencloset.net/

**Comment by keedi** [comment]
실서버에 배포 완료했으며 서비스도 재기동했습니다.

내일 오전 부터는 2일 및 3일 지연자에게도 문자 메시지가 자동으로 전송됩니다. :-)

**Comment by keedi** [comment]
이슈 닫습니다.

**Comment by 10001if** [comment]
저희 자체로 주문서를 생성하여 확인해보았습니다. 정상적으로 전달되고 있습니다. 확인완료하였습니다.
