### ISSUE TITLE
사용자정보에서 입력되었던 내용들이 보이지 않음

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#1165]
![b](https://cloud.githubusercontent.com/assets/170528/22615414/c04e431c-ead7-11e6-9f74-1363b0afbcd7.png)

@10001if 님의 사용자정보 화면입니다.
기존에 입력되어 있던 정보도 안보입니다.

**Comment by 10001if** [comment]
@aanoaa 로그인이 되지 않고 있어 불편하다는 요청이 있네요. 온라인으로 바쁘시겠지만 확인 부탁드립니다. ^^

**Comment by aanoaa** [comment]
js 에러입니다.
온라인서비스를 위해 새로 추가된 상태들이 js(OpenCloset.Status) 에 정의되어있지 않았습니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
