### ISSUE TITLE
운송장으로 택배 위치를 확인할 수 있는 링크의 연결이 잘못되어 있음

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1166]
![12 2017-02-08 12 02 57](https://cloud.githubusercontent.com/assets/4696328/22722654/0fafd980-edfc-11e6-92cd-d7dec6008caa.png)
빨간색 박스 안의 버튼을 누르면 운송장 확인할 수 있는 창이 열리지 않고 동일한 주문서 창이 새로 만들어 집니다. 확인 부탁드립니다.

**Comment by aanoaa** [comment]
모든 택배가 조회되는 것이 아니고 몇개의 택배업체만 지원되고 있습니다.
일단 CSVnet 편의점은 대상이 아닙니다.

조회가 되지 않는 택배추적 링크는 `a` 태그의 href 속성을 '#' 으로 해서 별다른 동작이 없도록 막았습니다.
하지만 무슨 이유에서인지 href 속성이 '' 으로 표시되어서 클릭이 가능하며 브라우저 기본동작인 현재 주소로 여겨집니다.

**Comment by aanoaa** [comment]
%a#order-tracking-url{:href => "#{url_for(tracking_url($order)) || '#'}", :target => '_blank'}

`traking_url($order)` 가 없다면

    <a target="_blank" href="#" id="order-tracking-url"></a>

처럼 나와야 하는데,

    <a target="_blank" href="" id="order-tracking-url"></a>

처럼 나옵니다.
Text::Haml 문제인 것 같습니다.

**Comment by aanoaa** [comment]
조회가 되지 않는 택배는 누를 수 없도록 링크를 제거하였습니다.

**Comment by 10001if** [comment]
@aanoaa 제가 조회가 되지 않는 택배가 있는지 몰랐습니다..

**Comment by 10001if** [comment]
@aanoaa 기존에는 연체 중인 사람의 경우 택배 링크를 보고 택배를 보냈구나 인지하는 수단으로 활용하였는데, 큰 이슈는 없네요. 삭제 해주신게 좋은 것 같습니다. 확인 요망 라벨 제거하겠습니다. ^^
