### ISSUE TITLE
주문서 내 대여자 반납일 항목 추가

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1167]
의류 반납에서 명쾌하게 해결되지 않은 이슈가 있습니다.

대여자가 실제 반납한 날짜를 명확히 알지 못한다는 것입니다.  (물론, 최초 반납자의 경우에는 실제 반납일을 대부분 알고 있음) 현재 주문서 상에 있는 반납 일은 열린옷장이 대여자의 의류를 반납받은 날을 뜻합니다. 하지만 1) 택배의 경우에는 택배를 접수한 날로 반납일을 확인하고 2) 무인반납의 경우에는 그 전 날을 반납일로 확인하고 3) 열린옷장 사유의 휴일의 경우 휴일 전 날을 반납일로 합니다.

이처럼 실제 반납 일로 처리해야 하는 날과 열린옷장에서 반납 받는 일이 다르기 때문에 발생하는 문제들이 있습니다.
가장 대표적인 것이 연장/연체료 입니다. 연장/연체료는 반납예정일/반납희망일/반납일 과의 관계로 계산됩니다. 그런데 이 반납일이 실제 연장/연체로 계산되어야 하는 반납일과 차이가 있습니다.

https://github.com/opencloset/opencloset/issues/815 이슈를 통해 연장/연체비를 계산하는 번거로움을 해결해 주셨습니다. 그런데 여전히 남아있는 문제는 문자발송시 연장/연체일의 계산이 정확하지 않다는 점입니다. 연장/연체일은 반납일에 따라 진행되지만 연장/연체비의 경우에는 캘린더에 체크한 대여자가 반납한 반납일을 토대로 진행되기 때문입니다.

예) 주문서번호 41392의 경우 `반납일`은 25일이지만, 대여자가 실제 반납한 일은 24일입니다. 
때문에 다음과 같이 연장료는 1일 이지만,
![2017-02-08 12 10 54](https://cloud.githubusercontent.com/assets/4696328/22724247/7e6b2800-ee08-11e6-9986-f350500d1ecf.png)

문자 발송시에는 금액은 1일 금액이지만, 연체 1일이 더해져 있습니다.
![2017-02-08 12 11 03](https://cloud.githubusercontent.com/assets/4696328/22724222/43836392-ee08-11e6-9aae-89ba2fefb6ba.png)

현재 해결하고 싶은 이슈는 크게 2가지입니다.

1) 최초 반납자 이후 다른 4층 옷장지기가 주문서를 보았을 때 `반납일`외에 `대여자 반납일`을 알아야 함.
2) `대여자 반납일`이 문자에 그대로 적용되었으면 함.   

지난 번에 @aanoaa 께서 2)번은 적용이 어렵다고 하셨던 걸로 기억합니다. 따라서 1)번만 해결이 되어도 좋을 것 같습니다.

이를 위해 다음과 같이 요청드리고자 합니다.

1. `대여자 반납일` 이 추가되어야 합니다. 이에 해당하는 경우는 택배발송, 무인반납, 휴일 등입니다.
2. 815 이슈를 통해 입력한 (실제 대여자 반납일)이 `대여자 반납일` 항목에 표시되도록 합니다. 
-> 본 작업을 통해 실제 반납처리해야 할 날짜를 확인 할 수 있게 됩니다. 
3. 가능하다면, 아래 그림처럼 문자에 입력되는 내용에 연체/연장일이 바로 수정될 수 있도록 요청드립니다.
![2017-02-08 12 10 54](https://cloud.githubusercontent.com/assets/4696328/22724863/825d287e-ee0c-11e6-9a0a-ea790963af6a.png)

@aanoaa 당장 진행해야 하는 이슈는 아니니, 온라인 하시면서 같이 봐주시면 될 것 같습니다.

**Comment by aanoaa** [comment]
택배반납할때에 대여자가 반납한날과 택배사가 접수한 날이 다를 수 있습니다.
택배를 접수하고 운송장번호를 발급받아서 운송장번호를 `열린옷장 반납택배 발송알리미` 에 입력한 날짜를 기록해둬야 언제 입력했는지 알 수 있습니다.

**Comment by aanoaa** [comment]
`택배발송/반납일` 을 선택했다면, `반납일`이 지금시간이 아니라 `택배발송/반납일`이 되어야 합니다.

**Comment by aanoaa** [comment]
`열린옷장 반납택배 발송알리미` 에 운송장번호를 입력한 날을 `반납일`로 지정한다면 추가적인 날짜를 기록해 둘 필요는 없습니다.

+ 반납일이 `택배발송/반납일:` 에 표시되고 staff 이 이것을 수정할 수 있도록 한다면 되지 않을까 합니다.

**Comment by aanoaa** [comment]
41392 주문서의 연장료는 6,400원 입니다.
이는 계산해서 나온 결과가 아니라, staff 이 반납당시에 계산결과를 수정한 값 입니다.

반납일과 반납예정일, 반납희망일로 계산하면 연체료(1일 9600원), 연장료(1일 6,400) 해서 16,000원 입니다.
문자메세지 전송기능은 계산해서 보내는 것이 아니라 저장해둔 미납금액을 발송합니다.

문제가 되는 부분은 문자메세지에 `1일 연장, 1일 연체로 추가금액 6,400원` 입니다.
staff 이 반납처리할때에 연체 아닌 것으로 판단하고 연장료만 미납한 것으로 계산했음에도 미납금 안내 문자에
연체와 관련된 부분이 포함되는 것 입니다.

이 경우 택배반납을 했고, 택배반납은 반납일 하루전에 하므로 정상입니다.
하지만 시스템에서의 반납일은 `전체반납` 버튼을 누른 시점이므로 적절한 처리가 필요합니다.

**Comment by aanoaa** [comment]
> 택배발송/반납일 을 선택했다면, 반납일이 지금시간이 아니라 택배발송/반납일이 되어야 합니다.

이미 적어두었네요. 이렇게 해야 위 문제를 해결할 수 있겠습니다.

**Comment by aanoaa** [comment]
반납일을 지정하게 되었을때 걱정이, 주문서가 `대여중` 에서 `반납` 으로 변경되는 시간을 기록할 수 없다는 것 입니다.
`전체반납` 버튼을 누른 시점을 `반납처리일` 로 본다면 컬럼이 추가되어야 합니다.
반납처리일이 꼭 필요할지는 모르겠습니다.

**Comment by aanoaa** [comment]
미납일때에 미납금내역을 연장료/연체료 구분해서 저장해두고 있습니다.
이를 참고하면 미납금 안내문자 내용을 적절하게 변경할 수 있겠습니다.

![- 2017-03-15 15-17-23](https://cloud.githubusercontent.com/assets/170528/23935984/b2783e30-0992-11e7-82ea-114ace952b84.png)

**Comment by aanoaa** [comment]
> 그런데 여전히 남아있는 문제는 문자발송시 연장/연체일의 계산이 정확하지 않다는 점입니다.

내용을 다시 읽어봤을때에 해결하고 싶은 문제는 이것 같습니다.

하지만

> 최초 반납자 이후 다른 4층 옷장지기가 주문서를 보았을 때 반납일외에 대여자 반납일을 알아야 함.
> 대여자 반납일이 문자에 그대로 적용되었으면 함.

에서 `대여자 반납일`이 필요함을 얘기해주셨습니다.

질문입니다.

`대여자 반납일` 을 `택배반납일` 로 봐도 될까요?
미납문자메세지가 아래처럼 적절하게 바뀌어도 `택배반납일`이 여전히 필요한가요?

```
[열린옷장] xxx님, 1일 연장, 1일 연체로 추가 금액 6,400원이 발생하였습니다. 금일 중으로 국민은행 205737-04-003013 (예금주 : 사단법인열린옷장)으로 입금해주세요. 입금자명과 xxx님의 이름이 동일해야 확인이 가능합니다. 반드시 xxx님 이름으로 입금해 주세요.

[열린옷장] xxx님, 1일 연장으로 추가 금액 6,400원이 발생하였습니다. 금일 중으로 국민은행 205737-04-003013 (예금주 : 사단법인열린옷장)으로 입금해주세요. 입금자명과 xxx님의 이름이 동일해야 확인이 가능합니다. 반드시 xxx님 이름으로 입금해 주세요.
```

@10001if

**Comment by aanoaa** [comment]
문자메세지 문제가 해결된다고 하더라도,
반납처리일과 반납일이 구분될 필요는 있습니다.

택배/무인반납함 등에서의 반납일은 반납처리일과 다를 수 있습니다.
방문반납의 경우 반납일과 반납처리일이 같겠습니다.

**Comment by aanoaa** [comment]
- 문자메세지를 우선 처리한다.
- 현재 반납일을 반납처리일로 사용할 수 있도록 스키마 변경
- 반납될때 반납일과 반납처리일을 구분해서 저장
- 반납일의 용도가 바뀌므로 데몬 프로그램에서 바라보는 반납일과 반납처리일을 적절하게 수정

해야 합니다.
볼륨이 있는 작업입니다.

**Comment by aanoaa** [comment]
여기에서는 문자메세지의 내용만 수정하도록 하겠습니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^

**Comment by 10001if** [comment]
확인했을 때는 맞았는데.. 좀 이상한게 있어서 남깁니다. 
~/order/54742의 경우 17일까지 반납해야 하는데 반납일은 18일입니다. 원반납일은 16일이었구요.
그래서 원래는 연장 1일 연체 1일이라 총 금액이 12,500원이어야 합니다.
그런데 무인택배함에 전 날 넣어놓고 가셔서 실제 반납일이 17일입니다. 그래서 연장 1일 5,000원만 문자에 입력되어야 하는데. 문자에는 연장 1일 연체 1일 5,000원으로 찍힙니다. 확인 부탁드릴게요.

**Comment by aanoaa** [comment]
@10001if 연체/연장료 에누리 -7500원 입니다.
https://staff.theopencloset.net/order/54742 직접한번 확인해보세요.

**Comment by 10001if** [comment]
@aanoaa 네~ 금액은 -7,500원 되는게 맞습니다. 그래서 5,000원이 미납금인데요.
이 주문서의 경우에는 미납문자 전송을 눌렀을 때 `연장 1일 5,000원`이 입력되어야 하는데.
`연장 1일, 연체 1일 5,000원`이 입력됩니다. 
문자메세지 내용이 수정되지 않은 것 같아서 확인 요청 드렸었습니다~

**Comment by aanoaa** [comment]
그렇게 기록에 남겼기 때문에 수정할 수 없습니다.
이런 경우라면

1. 연제/연장료를 에누리할게 아니라,
2. 반납일을 (-2d)로 지정하면 연체료가 발생안하게 되지 않나요?

`(1)` 의 경우는 연체가 발생했지만 받지 않겠다
`(2)` 의 경우는 연체가 발생하지 않았다

의 의미 같습니다.

**Comment by aanoaa** [comment]
> 반납일을 (-2d)로 지정하면 연체료가 발생안하게 되지 않나요?

반납일을 (-2d) 로 지정한다는 의미는, `택배발송/반납일` 을 지정한다는 뜻 입니다.

**Comment by 10001if** [comment]
@aanoaa 네~ 반납일을 지정하는 방법으로 해야 가능하다는 것은 이해 했습니다~

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
