### ISSUE TITLE
온라인 대여 지원을 위해 3회 이상 대여시 할인 기능을 별도 모듈로 분리함

### ISSUE THREAD

**Issue by keedi** [opencloset/opencloset#1172]
온라인 대여 기능 구현 중 오프라인과 마찬가지로 3회 이상 대여시 할인 기능이 동일한 조건으로 필요하다고 합니다. 따라서 기존 구현 코드를 별도의 모듈로 분리해서 코드 중복을 막습니다.

다음 이슈와 관련있습니다.

- 3회 이상 대여시 할인 opencloset/OpenCloset-Share-Web#79
- 3회째 대여자 부터 대여자의 부담을 줄이기 위해 비용을 할인함 opencloset/opencloset#790
- 3회 이상 대여자의 할인시 할인 내역을 주문서에 표시 opencloset/opencloset#946

**Comment by keedi** [comment]
별도 모듈인 `OpenCloset::DB::Plugin::Order::Sale`로 분리하고 0.001 버전을 릴리스했습니다.

저장소 주소는 다음과 같습니다.

https://github.com/opencloset/OpenCloset-DB-Plugin-Order-Sale

**Comment by keedi** [comment]
특별한 오류가 없다면 사용자는 변경 내역을 체감하지 못하는 이슈입니다. 추후 배포 후 정상 동작하는지 확인이 필요합니다.

작업 완료했으므로 이슈 닫습니다.

**Comment by keedi** [comment]
테스트 서버에는 배포 완료 했습니다.

**Comment by aanoaa** [comment]
실섭에 배포하였습니다.
`v1.8.47`
