### ISSUE TITLE
서울시 이벤트 알림

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#1173]
300명째 에서 알림이 필요합니다.
@10001if 님의 개인 메일로 300명째 이용했다는 알림을 보내야 합니다.

**Comment by aanoaa** [comment]
알람을 받을 수신이메일을 설정파일에 두었습니다.
배포후에 하면 잊을 수 있으므로 미리 추가해두었습니다.

배포한 후에 서비스 재시작 하면 적용됩니다.

**Comment by aanoaa** [comment]
이메일 오면 라벨 제거해주세요.
제 계정도 알람을 받을 수 있도록 해놓았습니다.

**Comment by 10001if** [comment]
@aanoaa 300명이 이번 주 초에 넘어서요~ 제가 눈으로 확인해서 서울시에 전달했습니다. ^^
