### ISSUE TITLE
신규 주소가 검색되지 않음

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1175]
최근에 생긴 주소들의 경우 주소 검색이 안되는 이슈들이 종종 발생하고 있습니다.
주소 DB 업데이트를 요청드립니다.

**Comment by 10001if** [comment]
https://www.poesis.org/postcodify/ 에서는 정상적으로 검색이 되고 있습니다.

**Comment by aanoaa** [comment]
검색이 아니되는 주소예가 필요합니다.

**Comment by aanoaa** [comment]
https://www.poesis.org/postcodify/guide/owndb 를 보고 하려는데,
php 설치하기가 넘 어렵습니다.

**Comment by aanoaa** [comment]
http://storage.poesis.kr/downloads/post/ 에 2016-12-30 일 버전이 있습니다.
이걸 사용하도록 하겠습니다.

**Comment by aanoaa** [comment]
$ wget http://storage.poesis.kr/downloads/post/postcodify.20161230.v3.mysqldump.xz
    $ xz -d postcodify.20161230.v3.mysqldump.xz
    $ mysql -u postcodify -p postcodify < postcodify.20161230.v3.mysqldump

**Comment by aanoaa** [comment]
하면 될 줄 알았는데,

    ERROR 1050 (42S01) at line 19: Table 'postcodify_addresses' already exists

에러가 발생합니다.

**Comment by aanoaa** [comment]
mysql> DROP DATABASE postcodify;
    $ mysql -u postcodify -p -e 'CREATE DATABASE `postcodify` DEFAULT CHARACTER SET utf8;'
    $ mysql -u postcodify -p postcodify < postcodify.20161230.v3.mysqldump

DB 를 날리고 새로 맨들었습니다.
이게 제대로 동작하는지는 제 PC 에서 우선 확인해보겠습니다.

**Comment by aanoaa** [comment]
스키마가 변경되었습니다.
DB 만 갱신하고 사용할 수는 없고, Postcodify 모듈도 수정해주어야 합니다.

**Comment by aanoaa** [comment]
변경된 스키마를 Postcodify 에 반영하고 주소검색을 해봤더니 예전처럼 동작은 하는 것 같습니다.
어떤 버전을 포팅했는지 기억이 나질 않는데, 현재는 v3 입니다.
v3 에 맞춰서 Postcodify 모듈도 수정해주는 것이 좋을 것 같습니다.

**Comment by aanoaa** [comment]
이력을 확인해봤는데 2.2 버전기준입니다.(p5-postcodify)
현재버전은 3.4.1 입니다.(postcodify)

**Comment by aanoaa** [comment]
v2.2 -> v3.4.1

의 변경사항을 확인하고 반영해야 합니다.
하루꼬박 해도 모자랄 것 같습니다.

**Comment by 10001if** [comment]
급한 이슈는 아닙니다. 시간 여유가 있거나 다른 작업이 여의치 않을 때 진행해주셔도 됩니다.

**Comment by aanoaa** [comment]
https://github.com/aanoaa/p5-postcodify/tree/v3 에 반영했습니다.

> 검색이 아니되는 주소예가 필요합니다.

이걸 가지고 검색이 되는지 확인해봐야하고, 기타 다른 검색도 되는지 확인이 필요합니다.

**Comment by MoDoLEE** [comment]
경상남도 창원시 마산합포구 완월남6길 5-1
경기도 부천시 옥길동 747-1 (양지로 234-26)

이 두 주소가 검색이 안됩니다.

**Comment by aanoaa** [comment]
```
$ perl scripts/search.pl 경상남도 창원시 마산합포구 완월남6길 5-1 | _ print
{
  "nums": "5-1",
  "msg": "",
  "sort": "JUSO",
  "version": "development",
  "cache": "HIT",
  "type": "JUSO+NUMS",
  "results": [
    {
      "dbid": "4812512800104820007000001",
      "other": {
        "short": "완월동",
        "long": "완월동 482-7",
        "roadid": "48125478751201",
        "addrid": "611120",
        "others": null,
        "bldnum": ""
      },
      "address": { "building": null, "base": "경상남도 창원시 마산합포구", "old": "완월동 482-7", "new": "완월남6길 5-1" },
      "english": {
        "new": "5-1 Wanwollam 6-gil",
        "building": "",
        "base": "Masanhappo-gu Changwon-si Gyeongsangnam-do",
        "old": "482-7 Wanwol-dong"
      },
      "code6": "631-862",
      "code5": "51268"
    }
  ],
  "error": "",
  "count": 1,
  "lang": "KO",
  "time": "0.0156"
}
```

```
$ perl scripts/search.pl  경기도 부천시 옥길동 747-1 | _ print
{
  "lang": "KO",
  "cache": "HIT",
  "nums": "747-1",
  "time": "0.0153",
  "version": "development",
  "msg": "",
  "type": "JIBEON+NUMS",
  "results": [
    {
      "code6": "421-602",
      "other": {
        "long": "옥길동 747-1",
        "bldnum": "401~410동",
        "roadid": "41190318602103",
        "addrid": "1303469",
        "others": "범박동; 보육시설; 부천옥길헤일라움",
        "short": "옥길동"
      },
      "dbid": "4119011500107470001000014",
      "english": {
        "building": "",
        "new": "234-26 Yangji-ro",
        "old": "747-1 Okgil-dong",
        "base": "Bucheon-si Gyeonggi-do"
      },
      "code5": "14786",
      "address": { "new": "양지로 234-26", "building": null, "old": "옥길동 747-1", "base": "경기도 부천시" }
    }
  ],
  "count": 1,
  "sort": "JIBEON",
  "error": ""
}
```

새로운 버전에서는 검색이 됩니다.

**Comment by keedi** [comment]
aanoaa/p5-postcodify 쪽이 버전업 되었던데 웹(컨트롤러)쪽에서도 적용해야 할 부분이 있나요?

**Comment by aanoaa** [comment]
오리지날의 `서울시 광진구 화양동 48-3` 을 검색했을때의 결과입니다.
이 결과와 똑같은 포맷으로 출력되어야 하겠습니다.

``` json
{
  "version": "3.4.1",
  "error": "",
  "msg": "",
  "count": 3,
  "time": "0.001",
  "lang": "KO",
  "sort": "JIBEON",
  "type": "JIBEON+NUMS",
  "nums": "48-3",
  "cache": "MISS",
  "results": [
    {
      "postcode5": "05015",
      "postcode6": "143917",
      "ko_common": "서울특별시 광진구",
      "ko_doro": "아차산로23길 48-3",
      "ko_jibeon": "화양동 36-23",
      "en_common": "Gwangjin-gu, Seoul",
      "en_doro": "48-3, Achasan-ro 23-gil",
      "en_jibeon": "36-23, Hwayang-dong",
      "building_id": "1121510700100360023017269",
      "building_name": "",
      "building_nums": "",
      "other_addresses": "",
      "road_id": "112154112310",
      "internal_id": "616479"
    },
    {
      "postcode5": "05019",
      "postcode6": "143917",
      "ko_common": "서울특별시 광진구",
      "ko_doro": "동일로24길 48-3",
      "ko_jibeon": "화양동 46-32",
      "en_common": "Gwangjin-gu, Seoul",
      "en_doro": "48-3, Dongil-ro 24-gil",
      "en_jibeon": "46-32, Hwayang-dong",
      "building_id": "1121510700100460032021406",
      "building_name": "",
      "building_nums": "",
      "other_addresses": "",
      "road_id": "112154112198",
      "internal_id": "614183"
    },
    {
      "postcode5": "05019",
      "postcode6": "143917",
      "ko_common": "서울특별시 광진구",
      "ko_doro": "아차산로 213",
      "ko_jibeon": "화양동 48-3",
      "en_common": "Gwangjin-gu, Seoul",
      "en_doro": "213, Achasan-ro",
      "en_jibeon": "48-3, Hwayang-dong",
      "building_id": "1121510700100480003017608",
      "building_name": "",
      "building_nums": "",
      "other_addresses": "웅진빌딩",
      "road_id": "112153000002",
      "internal_id": "607948"
    }
  ]
}
```

**Comment by keedi** [comment]
> aanoaa/p5-postcodify 쪽이 버전업 되었던데 데이터베이스 적용 및 모듈 업데이트를 제외하고 웹(컨트롤러)쪽에서도 적용해야 할 부분이 있나요?

없을 것 같다고 합니다.

**Comment by aanoaa** [comment]
- DB 업그레이드
- Postcodify 모듈 업그레이드

해서 주소검색이 오류없이 동작함을 확인했습니다.

---------------------------

1. Postcodify 모듈 배포
2. 서버(staff.theopencloset.net, postcodify.theopencloset.net) 의 database 업그레이드
3. 모듈설치
4. 재시작

2. 번이 시간이 오래걸리는 작업입니다.
영업시간 이후에 진행해야 합니다.
잘못되었을 경우에 롤백해야 합니다.
현재의 DB 를 백업해둘 필요가 있습니다.

**Comment by aanoaa** [comment]
생각해보니 이게 영업시간 이후에 진행한다고 될게 아니군요.
방문예약은 아무때나 할 수 있으니..

**Comment by aanoaa** [comment]
git repo 를 통해 설치했었는데, 불편해서 cpan.theopencloset.net 에 업로드했습니다.
[Postcodify-v0.3.0.tar.gz](https://cpan.theopencloset.net/STAFF@THEOPENCLOSET.NET/Postcodify-v0.3.0.tar.gz)

**Comment by aanoaa** [comment]
주소검색 DB 는 현재 2개가 사용되고 있습니다.

1. visit
2. postcodify

1번은 방문예약할때 주소검색과 사용자 정보에서의 주소 변경할때에,
2번은 share 에서 회원가입과 배송주소를 입력할때에 각각 사용하고 있습니다.

--------------------------------

우선 2번의 DB 를 업그레이드 해서 테스트해보고, 동작에 무리가 없다면 방문예약서비스가 2번을 사용하도록 하겠습니다.
그렇게되면 방문예약 서비스와 주소검색 서비스는 분리됩니다.

**Comment by aanoaa** [comment]
잘못알았습니다.
같은 DB 를 사용하는 웹서비스가 따로 존재하는 것 이었습니다.

**Comment by aanoaa** [comment]
우선 주소DB 를 백업해두고, 사용자가 많지 않을 시간인 새벽에 진행하겠습니다.

**Comment by aanoaa** [comment]
작업진행중에는 주소검색이 되지 않기 때문에 신규사용자의 방문예약이 되지 않습니다.
주소가 변경되지 않은 기존 사용자는 해당되지 않습니다.

온라인 주문도 마찬가지 입니다.

**Comment by aanoaa** [comment]
갱신이후에는 캐쉬 파일도 지워줘야 합니다.

**Comment by aanoaa** [comment]
30분 정도 걸렸습니다.
완료하였습니다.

**Comment by 10001if** [comment]
고생하셨네요. 감사합니다. ^^
