### ISSUE TITLE
가방 바코드 100개 요청

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1182]
가방을 대여해보려고 합니다. 가방 바코드 100개를 요청드립니다.

**Comment by aanoaa** [comment]
가방은 아직 열린옷장의 의류로 등록한 적이 없죠?

의류코드의 prefix 와 의류등록이 가능하도록 변경이 필요합니다.

**Comment by 10001if** [comment]
네. 아직은 열린옷장 의류로 등록한 적이 없었습니다.

**Comment by keedi** [comment]
대여 품목으로 가방 추가 #1192 항목을 별도로 만들었습니다. 없던 품목 추가는 단순 추가와는 달리 확인해야 할 부분이 많습니다. 어쨌든 가방 바코드 100개 추가와는 별개로 시스템에서 사용할 수 있도록 항목부터 우선 추가해야 합니다. (대여, 반납, 검색, 문자 등등등)

**Comment by aanoaa** [comment]
> 대여, 반납, 검색, 문자 등등등

대여, 반납, 검색은 확인했습니다.
문자는 무엇을 의미하는지 모르겠습니다.

**Comment by aanoaa** [comment]
$ ./script/generate_code.pl bag 10
    의류코드를 찾을 수 없습니다: bag at ./script/generate_code.pl line 38, <DATA> line 1.

일단 bag 에 대한 last code 를 등록해주어야 하겠습니다.

    INSERT INTO clothes_code (`category`, `code`) VALUES ('bag', '0G000');

last code 를 넣어주고 

    $ ./script/generate_code.pl bag 10
    G001,1600-0001
    G002,1600-0002
    G003,1600-0003
    G004,1600-0004
    G005,1600-0005
    G006,1600-0006
    G007,1600-0007
    G008,1600-0008
    G009,1600-0009
    G00A,1600-0010

제대로 출력됨을 확인했습니다.

**Comment by aanoaa** [comment]
- install OpenCloset::Common v0.0.14
- donation 의 재배포 및 재시작
- staff 의 재시작(혹시모르니)
- clothes_code 에 bag 카테고리 추가(last code 관리)

    INSERT INTO clothes_code (`category`, `code`) VALUES ('bag', '0G000');

- 가방코드 100개 뽑아서 전달

**Comment by aanoaa** [comment]
[bag.zip](https://github.com/opencloset/opencloset/files/823624/bag.zip)

가방 의류코드 100개 첨부합니다.

**Comment by aanoaa** [comment]
csv 가 첨부가 안되서 zip 파일로 첨부합니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
