### ISSUE TITLE
이벤트참여자의 쿠폰이 사라지는 주문서

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#1183]
서울시 이벤트로 방문예약을 했는데, 결제할때 보니 쿠폰이 사라지는 현상이 종종 발견되고 있습니다.

추적하기 쉽게 로그를 좀 더 상세하게 남겨야 합니다.

    # 이벤트 페이지에 다시 방문했을때 기존 주문서에서 쿠폰을 제거
    [Mon Feb 13 13:03:00 2017] [info] Delete coupon_id from existing order(52257): XXXX-XXXX-XXXX

    # 기존주문서에서 제거된 쿠폰으로 방문예약을 했을때
    [Sun Feb 19 19:16:48 2017] [info] Now, use coupon(8095) in order(52923)

이렇게 두줄 남기고 있는데, 좀 더 추적하기 편리해야 합니다.

**Comment by aanoaa** [comment]
![- 2017-02-23 15-13-29](https://cloud.githubusercontent.com/assets/170528/23246971/a8fc2ae6-f9da-11e6-8159-0a2c5ea8315e.png)

쿠폰이 재발급되었다면 staff 가 알 수 있도록 반납메모에 위와 같은 메세지를 입력해주도록 해야 합니다.

**Comment by aanoaa** [comment]
이벤트 페이지에서 KEB 하나은행 문구 삭제 해야 합니다.

**Comment by aanoaa** [comment]
대여탭에 반납확인메모가 나타나면 좋겠습니다.

방문예약 주문서인데 반납확인메모가 있다면 그것은 100%(지금은) 쿠폰이 지워진 주문서이기 때문입니다.

**Comment by aanoaa** [comment]
시간표에서도 쿠폰이 지워진 주문서를 표시해주어야 합니다.

**Comment by aanoaa** [comment]
@10001if https://visit.theopencloset.net/events/seoul 여기에 다른사람 이용에 대한 안내문구가 추가되어야 한다고 하셨습니다.

적어주세요.

**Comment by aanoaa** [comment]
![- 2017-02-23 17-15-17](https://cloud.githubusercontent.com/assets/170528/23250276/ae95f82c-f9eb-11e6-9b7d-46119a1d4028.png)

**Comment by aanoaa** [comment]
![- 2017-02-23 17-28-21](https://cloud.githubusercontent.com/assets/170528/23250675/7f6733a2-f9ed-11e6-8e58-0651835952d4.png)

이름옆에 경고마크를 붙였고 경고마크위에 마우스를 올리면 자세한 내용이 보입니다.

**Comment by 10001if** [comment]
본 페이지의 웹주소(URL)은 공유하거나 양도될 수 없습니다. 페이지의 웹주소(URL)가 공유되거나 양도되는 경우 발생하는 모든 불이익은 예약자 본인에게 있음을 유념하시기 바랍니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
