### ISSUE TITLE
여성의 윗배둘레에 따른 팔길이 정보 요청

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1186]
여성 윗배 | 팔길이 1 | 횟수|  팔길이 2.. | 횟수
-- | -- | -- | -- | --
44(65~69) | -- | -- | -- | --
55(70~74)   | -- | -- | -- | --
66(75~79)   | -- | -- | -- | --
77(80~84)  | -- | -- | -- | --
88(85~89)  | -- | -- | -- | --
99(90~94)  | -- | -- | -- | --
100(95~99)  | -- | -- | -- | --
110(100~106)  | -- | -- | -- | --
120(107~112)  | -- | -- | -- | --
합계  | -- | -- | -- | --

**Comment by aanoaa** [comment]
급한게 아니면 @yongbin 님이 처리하도록 하고 급한거면 제가 할게요

**Comment by 10001if** [comment]
@yongbin 처리해주실 수 있나요? 내일(금요일)까지 요청드리는 자료인데요. 혹시 어려우시면 이야기 해주세요. 그럼 @aanoaa 요청드리겠습니다~

**Comment by yongbin** [comment]
제가 내일까지 처리하겠습니다.

**Comment by yongbin** [comment]
어제 처리한 이슈입니다.
