### ISSUE TITLE
사이즈 검색순위 기준입니다. (남자)

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#119]
* 남자
1. 가슴 +2 +3 +4  +1 0
2. 중동 +4 +5 +6 +7 +8 +9 +10   
3. 허리 +0 +1 +2 +3 +4 -1 -2  
4. 허벅지 58 이하는 +4 +5 +6 +7 +8 +9 / 59 이상은 +6 이상 (Max 없음) 
5. 팔 -1 -2  0 +1 +2 +3
6. 다리길이는 원래 바지길이보다는 짧지 않으면 됨. (합/불 여부만 따지면 됨)

**Comment by keedi** [comment]
그 당시 기록하긴 했지만 지금 기준에서 무엇을 어떻게 해야할지 명확하지 않은 이슈입니다. 더 명확한 내용이 나오면 그때 별개의 이슈를 생성한 후 처리하도록 합니다.

이슈 닫습니다. :)
