### ISSUE TITLE
대여 품목으로 가방 추가

### ISSUE THREAD

**Issue by keedi** [opencloset/opencloset#1192]
> 가방 바코드 100개 요청 #1182
> 
> @10001if:
> 가방을 대여해보려고 합니다. 가방 바코드 100개를 요청드립니다.
> 
> @aanoaa:
> 가방은 아직 열린옷장의 의류로 등록한 적이 없죠?
> 의류코드의 prefix 와 의류등록이 가능하도록 변경이 필요합니다.
> 
> @10001if:
> 네. 아직은 열린옷장 의류로 등록한 적이 없었습니다.

대여 품목으로 가방을 추가해달라는 요청이 들어왔습니다. 100개 발급하는 이슈와 별개로 처리되어야 합니다.

**Comment by aanoaa** [comment]
현재 등록되어 있는 의류품목입니다.

```
+-----------+-----------------------+
| category  | prefix                |
+-----------+-----------------------+
| belt      | E                     |
| blouse    | B                     |
| coat      | C                     |
| jacket    | J                     |
| misc      | M                     |
| onepiece  | O                     |
| pants     | P                     |
| shirt     | S                     |
| shoes     | A                     |
| skirt     | K                     |
| tie       | T                     |
| waistcoat | W                     |
+-----------+-----------------------+
```

prefix 는 alphabet 대문자 이기 때문에 26개 밖에 쓸 수 없습니다.
`bag` 에 포함되면서 아직 사용되지 않은 것은 `G` 입니다.
`G` 라는 prefix 를 사용하도록 하겠습니다.

**Comment by aanoaa** [comment]
- OpenCloset-Common 의 `OpenCloset::Constants::Category` 에 `$BAG` 을 추가
- 가방을 의류등록 할 수 있도록 donation 을 변경
- staff 의 첫화면에 바코드를 찍었을때에 제대로 표시되도록 변경

이후에 대여와 반납이 가능한지 여부를 테스트 해보면 되지 않을까 합니다.

**Comment by aanoaa** [comment]
- 온라인에서 대여 가능한지 여부

역시 확인해봐야 하겠습니다.

**Comment by aanoaa** [comment]
온라인에서는 대여가능 품목에 없기 때문에 대여할 수 없습니다.

**Comment by aanoaa** [comment]
staff 에서도 특별한 변경 없이 등록한 것만으로 대여/반납이 가능했습니다.

**Comment by aanoaa** [comment]
특이한 점으로는 이미 bundle.coffee 에 `bag` 카테고리가 등록되어 있었습니다.

**Comment by aanoaa** [comment]
100개의 가방에 대해 바코드번호를 생성하고 마지막 코드를 갱신해주면 될 것 같습니다.
