### ISSUE TITLE
쿠폰으로 결제한 건에 대해서, 환불하면 쿠폰을 사용가능하도록 변경

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#1193]
서울시 이벤트 통계에 영향을 줄 수 있고, 환불시에는 2회대여가 불가능해지기 때문입니다.

**Comment by aanoaa** [comment]
환불하면 `사용된 쿠폰` 에서 `사용가능 쿠폰` 으로 변경됩니다.

**Comment by 10001if** [comment]
확인 후 말씀드리겠습니다.

**Comment by 10001if** [comment]
문제가 생기면 추후에 다시 열도록 하겠습니다.
