### ISSUE TITLE
취업날개와 같은 형식의 이벤트 추가

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1194]
취업날개과 유사한 형식의 이벤트가 추가되어야 합니다.

3월 초에 진행하기를 희망하고 있습니다.

이름 : 뉴딜일자리
사용횟수 : 1인당 2회
유효기간 : 2017년 3월 31일

쿠폰 발행 수는 확인해서 다시 알려드릴게요.
쿠폰은 발행하여 이메일로 제공하면 출력하여 오프라인으로 나눠 준다고 하네요.
관악고*, 십시일*과 같은 프로세스이나 통계페이지가 존재해야 한다는 점이 다릅니다.
취업날개와 동일하지만 쿠폰 예약방식이 다른 사이트를 통해 들어오는 것이 아니라는 점이 다릅니다.

**Comment by aanoaa** [comment]
통계와도 관련이 있습니다.
(이벤트 명칭을 정확하게 숨기고자 서울시 이벤트라고 했었는데 번거로우니 그냥 취업날개라고 하겠습니다.)

취업날개 통계의 경우 매 요청마다 복잡한 계산이 이루어집니다.
이게 통계자료를 쌓고 있지 않기 때문인데, 이벤트가 늘어날때마다 이런 통계용 계산이 필요합니다.

이벤트 범용적인 통계용 자료를 쌓고 이벤트 이름을 가지고 비슷한 포맷을 출력할 수 있다면 좋을 것 같습니다.

--------------------------

- 쿠폰 발급할때 한줄
- 쿠폰으로 예약할때 한줄
- 쿠폰을 사용할때 한줄
- 환불해서 쿠폰이 취소될때 한줄

해두면 통계자료를 뽑기도 쉽고 이벤트마다 따로 통계화면을 구성하지 않아도 됩니다.

**Comment by aanoaa** [comment]
@10001if 이번주내에 어떻게 진행할지 얘기해주신다고 했습니다.

**Comment by 10001if** [comment]
본 사업이 잠정중단 되었다고 오늘 아침에 전달 받았습니다. 이슈 닫도록 하겠습니다.

**Comment by 10001if** [comment]
이 건은 서울시에서 요청한 건 때문에 연 이슈입니다. 그런데 본 이슈를 연 뒤에 다른 자치단체에서 연락이 왔고, 다른 기업체에서도 연락이 왔습니다. 모든 곳의 바람은 가능하면 손 쉽게 조건에 맞는 대여자가 대여하고 그 결과를 공유받는 것이었습니다. 앞으로 이런 건이 충분히 늘어날 가능성이 있고, 역으로 제안을 할 수도 있을 것입니다. 이런 제안을 위해 통계 계산이 미리 준비되어 있는 것이 필요해 보입니다. 취업날개의 복사본이 늘어날 가능성이 충분히 있어 보입니다.

**Comment by aanoaa** [comment]
이벤트가 추가된다면 `OpenCloset::Cron::Visitor` 에 worker 를 추가해서 일일 방문자 수를 넣어줘야 합니다.
그 이후에는 `/stat/events/:event` 를 통해서 방문자수/미방문자수 를 볼 수 있습니다.

**Comment by aanoaa** [comment]
통계에 대한 준비작업은 끝났습니다.
새로운 이벤트가 진행되기로 하면 그때 새로운 이슈를 열어서 진행하겠습니다.
