### ISSUE TITLE
봉사활동 신청 페이지 수정

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1195]

**Comment by aanoaa** [comment]
Github 의 Projects 기능을 사용해보고 있습니다.
잘 활용된다면 이 이슈처럼 레퍼런스 이슈는 필요가 없을 것도 같습니다.

**Comment by aanoaa** [comment]
https://github.com/opencloset/opencloset/projects/2

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^

**Comment by aanoaa** [comment]
내용이 수정되어야 합니다.

**Comment by aanoaa** [comment]
Project 에서 이슈를 관리하고 있습니다.
더이상 레퍼런스 이슈는 필요가 없을 것 같습니다.
`확인요망` 라벨 또한 필요가 없습니다.

**Comment by aanoaa** [comment]
https://github.com/orgs/opencloset/projects/1
