### ISSUE TITLE
연장, 택배 URL 404 에러 발생

### ISSUE THREAD

**Issue by MoDoLEE** [opencloset/opencloset#1196]
연장안내 문자에서 연장 시 404 에러가 난다는 전화가 몇 건 있었습니다.
확인해 본 결과, 휴대폰 기종마다 또는 OS에 따라서 링크를 인식하는 방식이 달라서 생기는 문제 같습니다.

아래와 같은 문자를 받는데,

[열린옷장] 오늘은 26일에 대여하신 의류 반납일입니다. 운영시간(10시~18시) 중에는 웅진빌딩 403호로 반납해 주시고, 운영 외 시간에는 21시까지 4층 엘리베이터 앞에 무인반납함에 반납해 주세요. 대여 기간 연장이 필요하신 경우, (https://staff.theopencloset.net/order/xxxxx/extension)에서 대여기간을 연장해 주세요. (연장없이 무단으로 반납이 늦어지면 연체 처리 되어 하루 당 대여료의 30%의 추가 비용이 발생합니다.) 택배로 발송하신 경우 (https://staff.theopencloset.net/order/xxxxx/return)에서 택배사, 운송장번호를 등록해 주세요. (발송알리미 미입력시 택배발송 지연으로 인해 연체처리가 될 수 있습니다.) 

여기에서 **_https://staff.theopencloset.net/order/xxxxx/extension)에서_** 를 링크로 인식하여 브라우저창에 입력됩니다.
정상적으로 인식되게 하려면 괄호를 빼고 **대여 기간 연장이 필요하신 경우, _https://staff.theopencloset.net/order/xxxxx/extension_ 에서 대여기간을 연장해 주세요. ** 와 같이 수정되어야 합니다.

return URL도 마찬가지 입니다.

정리 하자면 발송 문자가 아래와 같이 변경되어야 합니다.

[열린옷장] 오늘은 26일에 대여하신 의류 반납일입니다. 운영시간(10시~18시) 중에는 웅진빌딩 403호로 반납해 주시고, 운영 외 시간에는 21시까지 4층 엘리베이터 앞에 무인반납함에 반납해 주세요. 대여 기간 연장이 필요하신 경우, https://staff.theopencloset.net/order/xxxxx/extension 에서 대여기간을 연장해 주세요. (연장없이 무단으로 반납이 늦어지면 연체 처리 되어 하루 당 대여료의 30%의 추가 비용이 발생합니다.) 택배로 발송하신 경우 https://staff.theopencloset.net/order/xxxxx/return 에서 택배사, 운송장번호를 등록해 주세요. (발송알리미 미입력시 택배발송 지연으로 인해 연체처리가 될 수 있습니다.)

**Comment by aanoaa** [comment]
결제가 확정되고 나면 SMS 를 발송하는데 현재 거기에 포함된 내용은 이렇습니다.

> 1. 택배로 발송을 하신 경우: https://staff.theopencloset.net/order/:order_id/return 를 클릭하여 반납택배 발송알리미를 작성해주세요.

> 2. 대여기간을 연장 하려는 경우: https://staff.theopencloset.net/order/:order_id/extension 를 클릭하여 대여기간 연장신청서를 작성해주세요.

**Comment by aanoaa** [comment]
위 내용은 반납당일 문자메세지인 것 같습니다.

**Comment by aanoaa** [comment]
[OpenCloset-Cron-SMS-0.012.tar.gz](https://cpan.theopencloset.net/STAFF@THEOPENCLOSET.NET/OpenCloset-Cron-SMS-0.012.tar.gz) 배포하였습니다.

**Comment by 10001if** [comment]
확인하였습니다. 추가 이슈가 생기면 다시 열도록 하겠습니다.
