### ISSUE TITLE
방문 예약시 예약자의 미납 내역이 있으면 납부할 수 있도록 팝업 및 문자 메시지로 안내

### ISSUE THREAD

**Issue by Bentleypark** [opencloset/opencloset#1197]
미납금이 있는 대여자가 방문예약을 할 경우에 예약단계에서 미납내역을 알려주시고 방문하기 전에 미납금을 모두 납부해야 의류대여가 가능하다고 안내하도록 해야 합니다. 

현재 예약 단계 중에 전화번호 인증 후 미납금 납부안내를 넣어주시면 됩니다.

 1) 전화 번호 인증- 2) **미납금 납부 안내**  - 3) 세부 예약 사항 입력 - 4) 최종 예약 완료 

미납금 납부 안내는 팝업창으로 안내를 하고 안내멘트는 다음과 같습니다. 

OOO님, 0000년 00월 00일 대여하신 의류의 반납이 늦어져, 추가 금액 19,200원이 발생하였습니다. 방문예약 전에 국민은행 205737-04-003013 (예금주 : 사단법인열린옷장)으로 미납금을 완납하지 않으시면, 직원의 요청에 따라 현장에서 미납금을 결제 해주셔야 합니다. 미납금이 완납되지 않는 경우, 열린옷장 서비스 이용이 제한될 수 있으니 이점에 유의하시고 미리 확인 부탁드립니다. 

대여자가 예약 완료 후, 예약확인 문자와 더불어 동일하게 안내 메세지를 문자로 보내주도록 합니다. 
문자의 안내 메세지는 팝업창과 동일하게 합니다.

**Comment by 10001if** [comment]
@keedi 미납금이 완납되지 않은 채로 재대여를 하는 경우가 늘어나고 있습니다. 

이런 경우에 1. 미납금이 완납되지 않았다는 정보를 전달하고 2. 미납금을 완납받기 위한 절차를 안내하려고 합니다.

**Comment by 10001if** [comment]
@keedi 몸이 좋지 않으시다는 이야기를 듣고 괜히 죄송한 맘이 들어.. @aanoaa 님을 추가로 소환하였습니다.

**Comment by 10001if** [comment]
@aanoaa 일반 계좌가 아닌 가상계좌로 안내되도록 수정 요청드립니다.

**Comment by aanoaa** [comment]
휴대폰번호 인증 후에

- 미납금이 있는지 체크해서
- 가상계좌를 만들고
- 미납금 내역 안내 후
- 예약페이지로 이동

하는 작업입니다.

**Comment by 10001if** [comment]
@aanoaa 네. 정확히 이해해주셨습니다.

**Comment by aanoaa** [comment]
입금된후 callback 주소가 visit.theopencloset.net 입니다.
정상적으로 처리될 수 있는지 확인이 필요합니다.

**Comment by aanoaa** [comment]
배포전에 생각났던 것인데,

- 가상계좌의 입금후 콜백주소를 visit 가 아닌 staff 로 바꾸거나
- visit 에서 가상계좌의 콜백처리를 가능하도록 해야 합니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
