### ISSUE TITLE
취업날개 통계 페이지에서 정보 추가

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1198]
[월간 방문 인원.pdf](https://github.com/opencloset/opencloset/files/815983/default.pdf)
다음과 같이 파란색으로 적혀 있는 부분의 정보 업데이트를 요청드립니다. 서울시에서 요청한 자료라 다음 주 화요일까지는 작업 부탁드립니다. 

1. (일평균 –명)
2. 합계 부분에서 (-%) 
추가되면 됩니다.

**Comment by yongbin** [comment]
#1210 에서 처리되었습니다. 결과 화면은 아래와 같습니다.

![screenshot 2017-03-09 18 51 34](https://cloud.githubusercontent.com/assets/52704/23744898/72265256-04f9-11e7-9ac2-f03b7cc8e2b4.png)


@10001if 님 컨펌해주시면 반영하겠습니다.

**Comment by 10001if** [comment]
네. 롹인 완료했습니다. 감사합니다.

**Comment by 10001if** [comment]
방문인원에 오류가 있는 것 같습니다. 확인 부탁드리겠습니다.

**Comment by 10001if** [comment]
인원이 너무 적습니다. 작업 중 오류가 발생한게 아닌가 싶습니다.

**Comment by aanoaa** [comment]
`취업날개 방문인원` 이 너무 적습니다.
작년에 4천명이 넘어야 하는데 합해봐야 몇백명 안됩니다.

**Comment by yongbin** [comment]
확인했습니다. 결과화면을 확인헀을때는 인원이 맞았는데 지금현재는 총인원수가 300명대로 너무 적게 나오고 있습니다.

**Comment by 10001if** [comment]
@yongbin 서울시에서 연락이 왔네요. 매일매일 보고자료용으로 쓰고 있었는데, 인원이 안맞는다구요~ 작업이 어렵다면 원래 상태로 돌렸다가 다시 작업해 주실 수 있을까요?

**Comment by 10001if** [comment]
@yongbin 수정 완료 가능한 시점이 언제쯤 일까요~?

**Comment by yongbin** [comment]
오늘중으로 확인해서 수정하곘습니다.

**Comment by 10001if** [comment]
@yongbin 감사합니다~

**Comment by yongbin** [comment]
https://github.com/opencloset/OpenCloset-Schema/pull/118#issuecomment-286035322 에서 `coupon` 테이블의 `update_date`를 KST로 변경했기때문에 취업날계 통계를 계산하던 아래 쿼리에 영향이 생겨 수치가 틀리게 되었습니다.

```sql
                SELECT
                    *
                FROM
                    (
                        SELECT
                            a.`date`                                        AS 'booking_date'
                            ,b.`id`                                         AS 'order_id'
                            ,YEAR(a.`date`)                                 AS 'booking_year'
                            ,MONTH(a.`date`)                                AS 'booking_month'
                            ,DAY(a.`date`)                                  AS 'booking_day'
                            ,IF(b.status_id = 12 OR b.status_id = 14, 0, 1) AS 'is_visit'
                            ,d.gender                                       AS 'gender'
                            ,d.birth                                        AS 'birth'
                            ,YEAR(NOW()) - d.birth                          AS 'age'
                            ,TRUNCATE(YEAR(NOW()) - d.birth, -1)            AS 'age_group'
                            ,IF(b.`coupon_id` IS NOT NULL, 1, 0)            AS 'is_coupon_use'
                            ,e.`id`                                         AS 'coupon_id'
                            ,e.`update_date`                                AS 'coupon_date'
                            ,e.`status`                                     AS 'coupon_status'
                            ,SUBSTRING_INDEX(e.desc, '|', 1)                AS 'coupon_type'
                            ,IFNULL(a.`date` - e.`update_date`,0)           AS 'booking_coupon_issue_diff'
                        FROM
                            `booking` AS a
                            INNER JOIN `order`      AS b ON ( a.id = b.booking_id )
                            INNER JOIN `user`       AS c ON ( b.user_id = c.id )
                            INNER JOIN `user_info`  AS d ON ( c.id = d.user_id )
                            LEFT  JOIN `coupon`     AS e ON ( b.coupon_id = e.id )
                    ) AS x
                WHERE
                    `booking_coupon_issue_diff` >= 0
                    AND `booking_date` > '2016-04-25'
```
구체적으로 `예약시점`과 `쿠폰의 사용시점` 의 차이를 보이는 `booking_coupon_issue_diff` 컬럼이 양수가 되도록 한 ``booking_coupon_issue_diff` >= 0` 조건이 원인이었는데, 지금 확인해보니 이 부분은 명백하게 제 실수입니다. 예약시간에 방문한 뒤, 일정 대기시간 이후에 쿠폰을 사용하기떄문에 의도한 식은 반대로 `쿠폰사용시점`에서 `예약시점`을 빼서 이 수가 양수인지를 확인했어야 맞는 쿼리입니다.

기존에는 #1201 과 연결되어 `update_date`는 UTC(KST - 9) 로 저장되고 있었기 때문에 사실상 기존 쿼리는 `예약시점`보다 `쿠폰사용시점`이 9시간이내로 빠른 주문서를 모두 정상으로 처리했습니다.

현재는 https://github.com/opencloset/OpenCloset-Schema/pull/118#issuecomment-286035322 에서 더블인코딩되어있던 UTC 값을 일괄로 +9 해줬기 때문에 쿼리는 다음과 같이 다시 작성되어야 합니다.

```sql
                SELECT
                    *
                FROM
                    (
                        SELECT
                            a.`date`                                        AS 'booking_date'
                            ,b.`id`                                         AS 'order_id'
                            ,YEAR(a.`date`)                                 AS 'booking_year'
                            ,MONTH(a.`date`)                                AS 'booking_month'
                            ,DAY(a.`date`)                                  AS 'booking_day'
                            ,IF(b.status_id = 12 OR b.status_id = 14, 0, 1) AS 'is_visit'
                            ,d.gender                                       AS 'gender'
                            ,d.birth                                        AS 'birth'
                            ,YEAR(NOW()) - d.birth                          AS 'age'
                            ,TRUNCATE(YEAR(NOW()) - d.birth, -1)            AS 'age_group'
                            ,IF(b.`coupon_id` IS NOT NULL, 1, 0)            AS 'is_coupon_use'
                            ,e.`id`                                         AS 'coupon_id'
                            ,e.`update_date`                                AS 'coupon_date'
                            ,e.`status`                                     AS 'coupon_status'
                            ,SUBSTRING_INDEX(e.desc, '|', 1)                AS 'coupon_type'
                            ,IFNULL(e.`update_date` - a.`date`,0)           AS 'booking_coupon_issue_diff'
                        FROM
                            `booking` AS a
                            INNER JOIN `order`      AS b ON ( a.id = b.booking_id )
                            INNER JOIN `user`       AS c ON ( b.user_id = c.id )
                            INNER JOIN `user_info`  AS d ON ( c.id = d.user_id )
                            LEFT  JOIN `coupon`     AS e ON ( b.coupon_id = e.id )
                    ) AS x
                WHERE
                    `booking_coupon_issue_diff` > 0
                    AND `booking_date` > '2016-04-25'
```
 
![screenshot 2017-03-21 19 05 48](https://cloud.githubusercontent.com/assets/52704/24142996/9fc037b0-0e6b-11e7-892e-137712b2f1e5.png)

이 경우 월별 방문자수나 최종 방문자수에서 기존자료와 차이가 발생하게 됩니다. 서울시와 통계값들이 공유되던 프로젝트이기때문에 현시점에 통계를 참값으로 변경할지 혹은 ** 기존한 동일한 기준의 오류값 ** 으로 사용할지 여부를 판단해야 합니다 ( 이 경우 기존 쿼리에서 0을 +9에 해당하는 -21600 으로 변경해주면 됩니다) 

관련내용 @10001if 님과 상의한후 결정되면 반영하겠습니다.

**Comment by yongbin** [comment]
관련해서 @10001if 님과 유선으로 통화한 내용을 간략하게 정리합니다.

현재 제공되는 `stat/events/seoul` 페이지는 쿠폰발행의 설계변경등 기술적인 이슈와 제 실수등이 겹쳐서 현재 정확한 수치가 제공되고 있지 않습니다. 하지만 연속적으로 업무를 진행하기위한 목적으로 기존과 동일한 방식으로 수치를 제공하도록 결정했습니다. 

대신 이 페이지는 `seoul`, `seoul-2017` 이벤트가 진행되는 2017년 4월 말까지만 활용하고 그 이후에는 각각의 이벤트별 별도 통계페이지를 이용해서 관련정보를 확인하는것이 옳습니다

**Comment by yongbin** [comment]
83471e3 처리되었습니다.

**Comment by 10001if** [comment]
@yongbin 네. 그럼 5월 1일부터 진행되는 프로젝트 때에는 별도의 이벤트명으로 진행하도록 하겠습니다. @aanoaa 진행 사항에 변도이 생기면 공유드리도록 하겠습니다.

**Comment by 10001if** [comment]
@yongbin 대표님 이 이슈 언제 배포될까요? 서울시에서 연락을 자주 주시네요. 바로 진행 가능하다면 배포 요청드립니다.

**Comment by yongbin** [comment]
v1.8.53  에서 배포되었습니다.

**Comment by 10001if** [comment]
@yongbin @aanoaa 정리를 하자면 다음과 같습니다.

2017년 2월 이전의 이용자수는 시에 최종 제출했던 인원과 동일해야 합니다.
사용수+예약수 의 이슈가 있어 인원이 변경된다는 말씀해주셨지만, 쿠폰을 사용한 인원의 수가 달라진다는 건 시에서 납득하기 어려울 것으로 보입니다. 페이지를 분리하는 것은 문제가 없다고 하였으니

1. 2016년 전체 : 이용자 수 4032명
2. 2017년 1월 2월 : 이용자 수 322명
3월은 23일까지 303명이 사용한 것으로 책정하였고, 24일부터 4월 어느 시점까지 303명이 사용되는 것으로 이벤트는 종료되는 것으로 결정되었습니다.

따라서 1과 2는 이미 제출된 숫자이기 때문에 과거의 숫자와 동일해야 하고 3월~4월은 미래의 숫자이므로 동일한 기준으로 책정되면 문제 없습니다.

**Comment by aanoaa** [comment]
#1198 에서 요구하는 대로 취업날개 이벤트의 통계수치를 맞춰야 합니다.
지금까지 `사용수+예약수` 로 카운팅 했기 때문에 이걸 `사용수` 로 카운팅하면 수치가 달라질 수 있습니다.

이후에 일별 통계를 `visitor` 에 넣고 통계를 보여주는 페이지에서 `visitor` 의 수치합산을 보여주도록 하면 되겠습니다.

**Comment by yongbin** [comment]
이 이슈는 당초 취업날개 통계 페이지에서 일평균등의 추가 정보를 추가하는 이슈였고 해당기능은 잘 반영되었습니다. 다만, 시기적으로 이 이슈가 적용되고 약 2동안 `timezone` 이슈와 쿠폰처리방식 개선등의 이슈가 진행되면서 표면적으로 통계의 숫자가 맞지 않는것 처럼 보인겁니다.

따라서 이 이슈는 닫고 별도 이슈를 열어서 통계숫자 이슈를 처리하겠습니다.

**Comment by 10001if** [comment]
@aanoaa 멘트 수정 요청이 있습니다. "일일평균"란을 "운영일(일일평균)"으로 수정해 달라는 요청입니다.

**Comment by aanoaa** [comment]
일간 방문인원을 날짜의 역순으로 정렬해서 보여주도록 해야 합니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
