### ISSUE TITLE
footer의 SNS 링크가 잘못되어 있음

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#1199]
https://www.instagram.com/opencloset_story/

가 아니라

https://www.instagram.com/opencloset_people/

**Comment by aanoaa** [comment]
5b1f5e79a02f969391359f29369dac819923c9f1

정확하게는 이것은 opencloset/opencloset 의 이슈보다는 donation, volunteer, share 에 반영되어야 할 이슈입니다.

OpenCloset::Plugin::Helper v0.0.14 를 배포 & 설치하고 위 3개의 서비스를 재시작 해주어야 합니다.

**Comment by aanoaa** [comment]
각각의 서비스에 cpanfile 을 업데이트 해주었습니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
