### ISSUE TITLE
필요한 사이즈 목록입니다.

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#120]
골반둘레
밑위
종아리둘레
밑단
목둘레
어깨너비
윗팔둘레
등길이
발길이
볼넓이

이상입니다.

**Comment by keedi** [comment]
최종 확인이 필요합니다. 현재 시스템에 없으나 추가했으면 하는 목록을 다시 정확하게 기록해주세요.

**Comment by keedi** [comment]
더불어 상기 기록한 내역이 신체 치수에 해당하는 것인지 의류 치수에 해당하는 것인지 역시 정확하게 확인 바랍니다. 동일하다면 상관없지만 그것이 아니라면 항목별로 나누어서 기록해주세요.

**Comment by 10001if** [comment]
의류사이즈와 신체사이즈 모두 필요합니다. 하지만 이 이슈는 #373 이슈와 동일한 듯 합니다. 이슈가 다른 것이 아니라면 @keedi 께서 이슈를 닫아주셔도 됩니다.

**Comment by keedi** [comment]
중복 이슈이므로 닫습니다.
