### ISSUE TITLE
대기실의 안내글을 TTS를 통해 안내음성으로 지원하고자 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1202]
1000번까지 무료로 이용할 수 있는 TTS 프로그램이 있는데, 테스트로 이용해 보면 어떨까요?
https://www.vocalware.com/index/demo

-> 이런 요청이 들어왔습니다. 실제 적용 가능한지 확인을 부탁드릴게요.

**Comment by aanoaa** [comment]
http 요청으로 audio 파일 링크를 준다고 합니다.
반응속도가 어떻게 될지는 모르겠지만 이용할 수 있겠지요

**Comment by aanoaa** [comment]
https://developers.daum.net/services/apis/newtone 이런것도 있습니다.
iOS, android 등 모바일 OS 에서만 사용가능한 것 같습니다.

**Comment by aanoaa** [comment]
https://translate.google.com/?hl=ko&tab=TT 에서도 스피커를 클릭하면 TTS 기능이 됩니다.

**Comment by aanoaa** [comment]
https://developers.naver.com/docs/labs/tts/ 이거 2016년까지 어쩌고 나오는데 끝난건지 어떤건지..

**Comment by aanoaa** [comment]
http://www.neospeech.com/

**Comment by aanoaa** [comment]
잉여력이 있으면 재밌을 것 같은데, 마음의 여유가 없습니다.

**Comment by aanoaa** [comment]
naver 의 TTS 의 경우 일일 10,000 건 사용할 수 있는 것 같습니다.

**Comment by aanoaa** [comment]
'반갑습니다 네이버' 로 한번 요청해서 성공했는데 사용량이 `9` 가 되었습니다.
글자수에 따라서 채워지는게 아닐까 싶습니다.

**Comment by aanoaa** [comment]
'야호' 를 한번 더 했는데 사용량이 그대로 '9' 입니다.

**Comment by aanoaa** [comment]
``` perl
use utf8;
use strict;
use warnings;
use HTTP::Tiny;
use Path::Tiny;

my $client_id     = 'xxxxxxxxxxxxxxxxxxxx';
my $client_secret = 'xxxxxxxxxx';

my $text = '야호';

our $URL = "https://openapi.naver.com/v1/voice/tts.bin";

my $http = HTTP::Tiny->new(
    default_headers => {
        agent                   => 'WebService::Naver::TTS - development',
        'X-Naver-Client-Id'     => $client_id,
        'X-Naver-Client-Secret' => $client_secret,
    }
);

my $res = $http->post_form(
    $URL,
    {
        speaker => 'mijin',
        speed   => 0,
        text    => $text,
    }
);

die "Failed!\n" unless $res->{success};
path('tmp2.mp3')->spew_raw( $res->{content} );

print "done\n";
```

**Comment by aanoaa** [comment]
시간이 좀 흐른뒤에 다시 통계를 보니 `11`이 되어 있습니다.
` (공백)`을 포함한 글자수가 맞는 것 같습니다.

**Comment by aanoaa** [comment]
`xxx님 7번 탈의실로 와주세요` 는 17 을 소비하게 됩니다.

**Comment by aanoaa** [comment]
xxx님 대기중입니다(18)
    xxx님 의류 준비를 기다려주세요(30)
    xxx님 의류를 수선 중 입니다(27)
    xxx님 의류를 포장 중 입니다(27)
    xxx님 신체 치수 측정 장소로 와주세요(36)
    xxx님 번 탈의실로 입장해 주세요(31)
    xxx님 결제 장소로 와주세요(26)

모두 더하면 195자 입니다.
탈의실을 한번 입장한다고 가정했을때에, 200자를 소비한다고 가정하면

일일허용량(10,000자)로는 50명이 사용할 수 있습니다.

**Comment by aanoaa** [comment]
https://developers.naver.com/apps/#/cooperation 여기에 정확한 내용이 있습니다.
음성합성 API의 경우 일 허용량이 10,000 글자 입니다.

그 이상을 사용하려면 제휴신청을 해야 하는데 거기에 대한 가격안내는 못찾았습니다.

**Comment by aanoaa** [comment]
승인만 되면 사용가능한 것인지, 승인후에 가격을 지불해야 하는 것인지는 적혀있지 않아서 모르겠습니다.

**Comment by MoDoLEE** [comment]
다른 안내와 중첩 될 경우 오히려 역효과가 있을 것 같습니다. 그래서 가장 중요한 탈의실 안내만 음성으로 나왔으면 합니다.

**Comment by MoDoLEE** [comment]
대여자 이름과 탈의실 번호가 명확히 들릴 수 있도록
중간 중간 쉼표(,)를 추가해서
"x,x,x,님, xx번, 탈의실로 입장해 주세요"
와 같은 형태로 입력되어야 합니다.

**Comment by 10001if** [comment]
@aanoaa 제휴 신청 하기 전에 먼저 테스트로 써보는게 좋을 것 같습니다. 탈의실 안내 31자 기분으로 10000자면 하루 양으로는 충분할 것 같습니다.

**Comment by aanoaa** [comment]
```
xxx님 대기중입니다(11)
xxx님 의류 준비를 기다려주세요(18)
xxx님 의류를 수선 중 입니다(17)
xxx님 의류를 포장 중 입니다(17)
xxx님 신체 치수 측정 장소로 와주세요(22)
xxx님 번 탈의실로 입장해 주세요(19)
xxx님 결제 장소로 와주세요(16)
```

한글을 2글자씩 셌습니다.
글자 수를 수정합니다.
