### ISSUE TITLE
주문서 번호 54106의 상태 체크

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1204]
주문서 번호 54106의 상태가 좀 이상합니다. 온라인 예약인데. 상태가 `주소선택`입니다. 오늘 10:30에 예약이 되어있어서, 온라인 주문 오류인가 했는데 실제로 오프라인 방문을 하셨습니다. 그래서 예약을 취소하고 다시 예약을 시도하였는데 취소도 되지 않고 다시 예약도 되지 않았습니다. 확인 부탁드립니다.

**Comment by aanoaa** [comment]
급한데로 시간표에서 상태를 변경해보세요

가 아니될것 같습니다 온라인 주문서는 시간표에서 표시되질않으니..

온라인 주문서의 상태를 바꿀 수 있는 기능이 필요하네요

**Comment by aanoaa** [comment]
급한데로 사용할 방법은 주소선택 주문서를 삭제하고 다시 방문예약을 하면 가능 할 것 같습니다

**Comment by aanoaa** [comment]
온라인주문서를 삭제하고 방뮨예약함

오프라인 대여의 경우 같은날 동일인이 두개의 주문서를 작성할 수 없도록 되어 있는데 온라인 주문서와 뒤섞이니 이런 문제가 발생한 것 같습니다

**Comment by 10001if** [comment]
@aanoaa 온라인 주문서를 삭제하려면 어떻게 해야하죠~? 예약 취소는 되지 않았습니다.

**Comment by aanoaa** [comment]
본인이 직접 대여기록에서 삭제할 수 있습니다

**Comment by 10001if** [comment]
@aanoaa 본인에게 주문서를 삭제하도록 요청하기가 번거로울 것 같은데요~ 여튼 현재는 저희가 직접 삭제할 수는 없다는 말씀이시죠? 오전에 저희가 삭제한 후 다시 예약을 시도했는데 되지 않아 의류는 대여해 드리고 대여 품목을 종이에 적어 놓았습니다. 오늘날짜로 주문서를 생성해야 해서 예약을 해야 합니다. 수동으로 예약을 할 수 있도록 요청드리고자 합니다. 황**님(7716) / 주문서번호 54106 / 대여품목 J1S9, K04I 이고, 취업날개 이용하십니다.

**Comment by aanoaa** [comment]
사용자정보에 나타난 온라인 주문서를 선택했습니다.
온라인 주문서의 경우 방문예약 시간이 없기 때문에 시간표에 나타나질 않습니다.

54108 주문서가 방문예약 주문서이고, 54106 는 온라인 주문서 번호입니다.

**Comment by aanoaa** [comment]
적절히 처리해주신다고 합니다.

**Comment by aanoaa** [comment]
54108 주문서의 예약을 취소해서 방문예약 시간이 사라졌는데, 그때 당시에 `포장` 상태여서 상태변경을 할 수 없습니다.

직접 데이터를 수정해주어야 하겠습니다.

**Comment by aanoaa** [comment]
``` sql
UPDATE `order` SET status_id = 14 WHERE id = 54108;
```

방문예약 상태로 다시 돌려 놓도록 하겠습니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
