### ISSUE TITLE
방문예약시간이 현재시간보다 이전일때 예약이 갱신되지 않는 문제

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#1207]
쿠폰과 관련이 있는데, 쿠폰없이 예약했다가 쿠폰을 사용해서 결제하고 싶어 하는 경우가 있습니다.
이럴때에는 대여자에게 취업날개 이벤트를 통해서 다시 예약을 해달라고 부탁을 합니다.

지금이 11:00 인데 10:30 방문예약을 했다면 다시 방문예약을 하게 되었을때 문제가 있을 수 있습니다.
방문예약 시간이 현재시간보다 이전이라고 할지라도 허용해야 할 수 있습니다.

**Comment by 10001if** [comment]
@aanoaa 느끼기에는 이게 문제되는 것 같지 않은데.. 문제가 되지 않는다면 이슈 닫아주셔도 될 것 같습니다.

**Comment by aanoaa** [comment]
뭔지 기억나지도 않습니다.

**Comment by 10001if** [comment]
그럼 이슈 닫겠습니다~
