### ISSUE TITLE
주문서에 쿠폰번호만 넣으면 쿠폰 처리가 될 수 있도록 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1208]
현재는 취업날개의 경우에는 일자리 포털을 통해서만 쿠폰 적용이 가능하고 다른 경우에는 쿠폰 페이지에서 쿠폰을 입력하고 예약해야만 쿠폰 적용이 가능합니다. 하지만 쿠폰이용을 하려면 반드시 예약을 다시 해야만 하는 불편함이 있는데요. 쿠폰번호를 입력한다면 바로 쿠폰 적용이 될 수 있도록 하는 기능이 추가되었으면 합니다. 이슈의 크기를 잘 모르겠네요. @aanoaa 판단하셔서 중간에 작업을 진행해 주시면 좋겠습니다. 좀 큰 이슈라면 과감히 넘겨버려도 괜찮습니다.

**Comment by aanoaa** [comment]
어제는 4건이나 발생했습니다.

**Comment by aanoaa** [comment]
쿠폰번호를 입력할 수 있도록 하고,

- 사용가능한 쿠폰이라면 주문서에 쿠폰이 적용되도록 한다
- 사용가능한 쿠폰이 아니라면 적절한 에러메세지를 보여준다

**Comment by aanoaa** [comment]
POST /order/:id/coupon

에서 처리할까 합니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^

**Comment by 10001if** [comment]
사용할 수 없는 쿠폰입니다: used 이라고 나오는 경우 사용된 주문서를 알려주어, 클릭 시 바로 사용된 주문서로 이동할 수 있도록 하는 기능이 필요합니다. 그래야 쿠폰의 사용여부에 대해 더 정확하게 안내할 수 있기 때문입니다.

**Comment by aanoaa** [comment]
![- 2017-04-13 14-09-26](https://cloud.githubusercontent.com/assets/170528/24991005/d753745a-2052-11e7-8830-9113e6456a43.png)

주문서 바로가기 링크가 추가되었습니다.

**Comment by 10001if** [comment]
@aanoaa 이 기능이면 문제가 있었던 지점을 찾아 이용자와 정확하게 커뮤니테이션 할 수 있을 것으로 보입니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
