### ISSUE TITLE
order/539671 상태를 대여중 상태로 해야 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1211]
order/53967의 주문서의 현재 상태는 `포장`입니다.
그러나 본 주문서는 대여확정이 완료된 주문서 이기 때문에 `대여중`상태로 변경되어야 합니다.
상태가 변경되지 않아 preparation 화면에서도 포장으로 그대로 남아 있습니다. 수정 요청드립니다.

preparation 에서 실시간 갱신이 되지 않아 실수로 상태를 바꿨기 때문에 상태가 포장 상태로 되어 있는 것으로 추정됩니다.

**Comment by 10001if** [comment]
@aanoaa 휴일에 죄송하지만 화면에 계속 남아 있네요. 가능하시면 빠른 작업 요청드리겠습니다.

**Comment by aanoaa** [comment]
어떻게 결제완료 된 주문서의 상태를 다시 포장으로 변경하신건가요?
방법이 있나요?

**Comment by aanoaa** [comment]
```
mysql> UPDATE `order` SET status_id = 2 WHERE id = 53967;
Query OK, 1 row affected (0.00 sec)
Rows matched: 1  Changed: 1  Warnings: 0
```

변경하였습니다.

**Comment by 10001if** [comment]
@aanoaa preparation 화면에서 갱신되지 않고 포장에 그대로 남아 있었다네요. 오랫동안 포장에 남아 있어서 확인해보려고 의류준비로 넘겼는데, 그 때는 이미 대여중인 상태였다고 합니다.

**Comment by aanoaa** [comment]
추정컨대, 이벤트 알림 기능에 문제가 있어서 의류준비탭에서 대여된 주문서가 갱신되지 않았고 화면에 남아 있는 주문서의 상태를 의류준비로 변경한게 아닐까 싶습니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
