### ISSUE TITLE
실시간 남성 세트 재고 파악을 위한 기능

### ISSUE THREAD

**Issue by MoDoLEE** [opencloset/opencloset#1214]
#1181 를 통해서 5층 대여공간에 있는 남성 세트를 정리했습니다.
그 이후에 지속적인 관리를 위해 필요한 기능을 요청드립니다.
매번 csv 파일을 받아서 처리할 수 없으므로, 해당 기능을 staff에 추가해 주셨으면 합니다.

해당 기능을 통해서 기증 받은 의류의 수선 여부, 사용 여부를 파악할 수 있습니다.
예를 들어 특정 그룹( **[188)[178)[159)[159)** )의 의류가 기증 들어왔을 때 5층에 이미 재고가 포화상태라면, 수선하지 않고 보관을 합니다. 그렇지 않고 필요 재고 보다 부족한 상황이라면, 5층에서 사용할 수 있도록 수선합니다.

원하는 기능은 아래와 같습니다.
검색 조건을 선택하고 검색 버튼을 누르면 예시와 같은 검색 결과가 나오는 기능입니다.

**데이터는 남성 정장 세트만 사용합니다.**

**## [검색 조건]**

![default](https://cloud.githubusercontent.com/assets/14110661/24090760/7abd5a6e-0d86-11e7-873e-6f834ce9434f.png)

1. 윗배
- 87 이하
- 88 ~ 91
- 92 ~ 95
- 96 ~ 99
- 100 ~ 103
- 104 ~ 107
- 108 ~ 112
- 113 이상

2. 허리
- 77 이하
- 78 ~ 82
- 83 ~ 87
- 88 ~ 92
- 93 ~ 97
- 98 ~ 104
- 105 ~ 111
- 112 이상

3. 허벅지
- 58 이하
- 59 ~ 63
- 64 ~ 68
- 69 ~ 73
- 74 이상

4. 팔길이
- 58 이하
- 59 ~ 61
- 62 ~ 64
- 65 이상

5. 위치
- 5층 (의류 태그에 "5층"이 있는 경우)
- 4층 (의류 태그에 "4층_ ~~~"이 있는 경우)
- 지하 (의류 태그에 "지하_~~~"이 있는 경우)

6. 상태
- 대여가능 (자켓, 팬츠의 상태가 **모두** 대여가능인 경우)
- 대여중 (자켓, 팬츠 중 **하나라도** 대여 중인 경우)
- 반납 (자켓, 팬츠 중 **하나라도** 반납인 경우)
- 수선 (자켓, 팬츠 중 **하나라도** 반납인 경우)
- 세탁 (자켓, 팬츠 중 **하나라도** 세탁인 경우)
- 대여불가 (자켓, 팬츠 중 **하나라도** 대여불가인 경우)

7. 색상 : 자켓 색상을 기준으로 표시해 주세요.
- 블랙
- 네이비
- 차콜그레이
- 그레이
- 브라운
- 기타

8. 계절
- 춘추 (자켓, 팬츠의 의류 태그에 "하복", "동복" 아무것도 없는 경우)
- 여름 (자켓, 팬츠 중 **하나라도** 의류 태그에 "하복"이 있는 경우)
- 겨울 (자켓, 팬츠 중 **하나라도** 의류 태그에 "동복"이 있는 경우)

**## [검색 결과]**

![default](https://cloud.githubusercontent.com/assets/14110661/24090761/7c1db0de-0d86-11e7-8452-03aee1307ef4.png)

1. 순번

2. 대여주기
: (대여가능일 / 대여횟수)의 계산 결과 값

3. 숫자코드
: 자켓의 영문 바코드를 숫자로 변환한 값

4. 자켓 바코드

5. 팬츠 바코드

6. 상태
- 대여가능 (자켓, 팬츠의 상태가 **모두** 대여가능인 경우)
- 대여중 (자켓, 팬츠 중 **하나라도** 대여 중인 경우)
- 반납 (자켓, 팬츠 중 **하나라도** 반납인 경우)
- 수선 (자켓, 팬츠 중 **하나라도** 반납인 경우)
- 세탁 (자켓, 팬츠 중 **하나라도** 세탁인 경우)
- 대여불가 (자켓, 팬츠 중 **하나라도** 대여불가인 경우)

7. 위치
- 5층 (의류 태그에 "5층"이 있는 경우)
- 4층 (의류 태그에 "4층_ ~~~"이 있는 경우)
- 지하 (의류 태그에 "지하_~~~"이 있는 경우)

8. 색상
9. 가슴
10. 윗배
11. 팔길이
12. 상의길이
13. 허리
14. 허벅지
15. 하의길이
16. 밑단

**Comment by 10001if** [comment]
@yongbin 재고관리를 위해 건네주신 그룹핑 자료를 검토/확인 한 후 각 그룹별로 비율을 체크하여 480벌의 적정 비율 수량을 결정했습니다. 현재는 5층에 정해진 의류만 보유되어 있는 상황인데요. 기증이 들어오는 새 옷을 그룹내에 추가할지, 혹은 그룹내 의류가 포화상태 일 때 기증된 새 의류와 교환할지 여부를 확인하기 위해 다음과 같은 자료를 요청드립니다. 적정한 의류 수량확보는 온라인 대여와도 동일하게 필요한 이슈입니다. 내용 검토 후 작업 요청드립니다. 의문 나시는 부분은 언제든 작성 부탁 드리겠습니다~

**Comment by 10001if** [comment]
@yongbin 대표님 @MoDoLEE 과 이야기 나눠본 결과 현재 이 기능을 필요로 하는 것인지 확실하지가 않네요. 조금 더 고민 한 뒤에 다시 문의드리도록 하겠습니다. 우선 이슈는 닫도록 하겠습니다.
