### ISSUE TITLE
메뉴에 위키 링크를 추가

### ISSUE THREAD

**Issue by MoDoLEE** [opencloset/opencloset#1217]
첫화면
새 옷
의류
사용자
기증
...

이 메뉴에 위키 링크를 추가하려 합니다.

신체치수예측 아래
통계 위에

**위키** 라고 메뉴를 추가하고
http://ko.opencloset.wikidok.net 로 연결해 주세요.

**Comment by keedi** [comment]
@10001if 이미 알고 계시겠지만 wikidok 사이트를 통해 작성하는 문서는 전체 열람 가능합니다. 이 점 인지하고 계신지 확인 부탁드리며, 여전시 신체치수예측과 통계 사이 위치에 위키 메뉴를 주가하면 되는 것인지 확인 부탁드립니다.

**Comment by 10001if** [comment]
오픈되는 것은 인지하고 있었는데. 내부적으로 한번 의논을 하고 결정해야 할 것 같습니다. 확인 후 다시 남기도록 하겠습니다.

**Comment by keedi** [comment]
확인 후 피드백 남겨주세요~ 우선 순위가 밀리는 것 같아 마일스톤에서 제거합니다. 필요 없는 이슈면 닫아주셔도 됩니다. 필요한 이슈라면 적절한 우선 순위에 해당하는 마일스톤에 넣어주세요.

**Comment by 10001if** [comment]
위키에 필요 내용을 정리하는 직업은 매우 필요하지만, 모든 내용이 공유되어 더 적극적으로 활용하기엔 부담이 되는 부분이 있네요. 우선 이슈 닫겠습니다. 이 내용에 대해 더 고민해 본 뒤 필요한 부분에 대해 요청드리겠습니다.

**Comment by keedi** [comment]
@10001if 
아, 그런데 현재 이슈 자체는 재고 관리 시스템에서 클릭할 수 있는 메뉴 링크를 추가하는 것입니다. 위키 자체는 공개되어 있으니 관련해 확인해보시는 것이 필요하다는 의미였고, 재고 관리 시스템의 메뉴에 링크를 추가하는 것이 편리하다면 본 이슈는 해결되는 것이 적절하겠죠~. 공개 여부는 내부 팀원들과 고민해보시고 재고 관리 자체는 공개 시스템이 아니니 메뉴 추가는 상관없습니다.

다시 확인해보시고, 메뉴 추가가 필요하다면 다시 열어서 적절한 마일스톤에 넣어주세요. :)

**Comment by 10001if** [comment]
네. 내부관리 정보가 전부 오픈되는 부분에 대한 고민이 더 필요하다고 판단했습니다. 링크를 삽인한다는 것은 이 기능을 더 활발하게 사용한다는 의미이니 더 고민해보고 결정한 뒤에 요청드리는게 좋을 것 같네요. 지불하면 프라이빗한 비공개 계정이 생기는지 확인해보겠습니다.

**Comment by 10001if** [comment]
위키문서 자체에 비공개 계정이 존재하는 것이 앞뒤가 안맞는 표현이네요. 공개자료로 사용하되 중요한 정보만 따로 모아 내부자료에 올릴지 고민을 더 해보겠습니다.
