### ISSUE TITLE
취업날개 이벤트의 인원 수 제한

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1218]
이용자가 217명이 되면 더 이상 예약을 할 수 없도록 요청드립니다.

매월 303명 정도가 대여해야 하는데. 이번달에 389명이 대여해서 다음 달 인원 중에 86명을 제하고 진행하려 합니다. 작업 요청드립니다.

**Comment by aanoaa** [comment]
> 이용자가 217명이 되면 더 이상 예약을 할 수 없도록 요청드립니다.

2017년 4월달의 가 빠졌습니다.

**Comment by 10001if** [comment]
@aanoaa 네. 2017년 4월달의 이용자가 217명이 되면 더 이상 예약을 할 수 없도록 요청드립니다. 정식 계약 전에 몇번의 계약방식의 변화가 있었는데요. 어제(29일) 인원 수 조정 연락이 왔습니다. 월 인원 303명 제한으로 전달받았는데요. 정확히 말하면 303번의 이용 후에는 종료되도록 하는 것입니다. 과거의 666번의 이용 정책은 303번의 이용으로 변경되었습니다.

**Comment by aanoaa** [comment]
> 올해 667명으로 알고 있었는데, 매달 303명 제한이 있는 건가요?

올해가 아니라 2017-03-31일까지 667명 제한이 있었습니다.

**Comment by aanoaa** [comment]
@10001if 3월 이후에는 정식으로 이벤트가 시작된다고 들었는데, 최대 몇명이 이용가능한지에 대한 업데이트가 없습니다.

**Comment by aanoaa** [comment]
정식으로는 5월부터 이벤트가 시작됩니다.
최대 10,000명이고 이때는 매달 제한이 없습니다.

2017년 4월달에만 217명 제한을 두는 것이 필요합니다.

**Comment by aanoaa** [comment]
@10001if
아직 3월달이 이틀 남아서 쿠폰예약과 사용건수가 더 발생할 수 있는데,
217로 확정해도 괜찮은건가요?

**Comment by 10001if** [comment]
@aanoaa 네! 303명이 발생한 시점이 이미 넘어버려서요. 30일은 이미 4월로 포함되어 있는 상태입니다.

**Comment by 10001if** [comment]
@aanoaa 아니네요..

**Comment by 10001if** [comment]
예) 3월달 최종 이용자 수 403명인 경우
403명 - 303명 = 100명 따라서 100명 초과

4월달 최초 이용자 수 303명이었으나
지난 달에 100명이 초과 이용했기 때문에
303명 - 100명 = 203명이 4월달의 최종 이용횟수

4월달은 203명입니다.

**Comment by aanoaa** [comment]
쿠폰에 예약일과 사용일이 있으면 통계를 계산하기에 더 편리할 것 같습니다.
지금은 생성일, 갱신일, 만료일 3개의 datetime 컬럼이 있습니다.
하지만 지금도 알 수 있습니다.
예약일은 `order.create_date` 이고, 사용일은 `order.rental_date` 입니다.

**Comment by aanoaa** [comment]
`303명 - 3월달 취업날개 방문인원` 을 4월가능 예약자로 받으면 되겠네요.

**Comment by aanoaa** [comment]
2017년 3월과 4월에 사용된 쿠폰수를 찾고 싶습니다.
방문예약날짜(`booking.date`)가 3월이고 쿠폰이 사용된(`c.status = used`) 주문서의 갯수를 세면 되지 않을까 싶은데
통계상의 수치와 다릅니다.

``` sql
SELECT 
  COUNT(*)
FROM 
  coupon c JOIN `order` o ON c.id = o.coupon_id
JOIN
  booking b ON b.id = o.booking_id
WHERE
  c.status = 'used'
AND
  YEAR(b.date) = 2017
AND
  MONTH(b.date) = 3
;
```

위 쿼리의 결과는 `382`건 이지만, 통계에서 `2017-03`의 `취업날개 방문인원`은 `394`건 입니다.
물론 통계에는 성별, 연령대별 연산이 필요해서 더 복잡하겠지만 두개의 결과가 같아지기 위한 쿼리가 필요합니다.

**Comment by aanoaa** [comment]
아래쿼리를 사용해야 합니다.

```
SELECT COUNT(*) FROM
(
  SELECT
    o.id AS 'order_id',
    IF(o.status_id = 12 OR o.status_id = 14, 0, 1) AS 'is_visit',
    IF(o.coupon_id IS NOT NULL, 1, 0) AS 'is_coupon_use',
    b.date AS 'booking_date',
    b.date - c.update_date AS 'diff'
  FROM booking b
  INNER JOIN `order`  o ON b.id = o.booking_id
  LEFT  JOIN `coupon` c ON c.id = o.coupon_id
) AS x
WHERE `diff` > -21600 AND YEAR(`booking_date`) = 2017 AND MONTH(`booking_date`) = 3 AND `is_visit` = 1 AND `is_coupon_use` = 1;
```

**Comment by aanoaa** [comment]
아래 두개의 쿼리 결과는 같습니다.
둘다 예약수 + 사용수를 합한 수치입니다.

``` sql
SELECT COUNT(*) FROM
(
  SELECT
    o.id AS 'order_id',
    IF(o.status_id = 12 OR o.status_id = 14, 0, 1) AS 'is_visit',
    c.status                                       AS 'coupon_status',
    b.date                                         AS 'booking_date'
  FROM booking b
  INNER JOIN `order`  o ON b.id = o.booking_id
  LEFT  JOIN `coupon` c ON c.id = o.coupon_id
) AS x
WHERE YEAR(`booking_date`) = 2017 AND MONTH(`booking_date`) = 3 AND `is_visit` = 1 AND `coupon_status` REGEXP 'used|reserved|provided';
```

``` sql
SELECT 
  COUNT(*)
FROM 
  coupon c
JOIN
   `order` o ON c.id = o.coupon_id
JOIN
  booking b ON b.id = o.booking_id
WHERE
  o.status_id NOT IN (12, 14)
AND
  c.status REGEXP 'used|reserved|provided'
AND
  YEAR(b.date) = 2017
AND
  MONTH(b.date) = 3
;
```

**Comment by aanoaa** [comment]
통계쿼리에서 잘못된 점이 있습니다.
주문서에 coupon_id 가 있는지 여부로 쿠폰이 사용되었는가를 체크하고 있습니다.

잘못된건 아니지만 정확하게는 쿠폰의 상태를 체크해봐야 합니다.

`취업날개 방문인원` 은 `예약수 + 사용수` 를 모두 합한 수치입니다.

**Comment by aanoaa** [comment]
진행하면서 통계에서 coupon_id 존재 여부가 아닌 쿠폰의 상태를 가지고 체크하도록 변경하겠습니다.
cc @yongbin

**Comment by aanoaa** [comment]
`취업날개 방문인원`이 `사용수` 일까요? `사용수+예약수` 일까요?
기존 통계에서는 `사용수+예약수` 입니다.

cc @10001if @yongbin

**Comment by aanoaa** [comment]
기존처럼 똑같이 가겠습니다.

**Comment by aanoaa** [comment]
`사용수+예약수` 로 하게되면 예약수가 변경될 수 있습니다.
어제의 4월달과 오늘의 4월달 수치가 달라질 수 있습니다.(한두건 정도?)

쿠폰이 사라지는 이유와 같습니다.
중복된 사용을 방지하기 위해서 쿠폰이 다시 발급될때에 이미 예약된 쿠폰을 주문서에서 삭제하기 때문입니다.

**Comment by 10001if** [comment]
기존에 667명으로 제한을 두었지만, 현재 시점에서는 제한 사유가 아닙니다. 667명으로 진행하기로 한 건은 최초 논의 때 나왔지만 시작 후에는 월별로 사용된 인원 수만큼 금액을 요청하기로 하였습니다. 다만 2월에는 333명 이내, 3월 4월은 303명 이내로 진행되어야 합니다.

**Comment by 10001if** [comment]
@aanoaa 취업날개 방문인원은 `사용수`이어야 합니다. 하지만 인원이 달라질 수 있다고 하시기 때문에 현재는 종전대로 유지하되, 5월부터 진행되는 이벤트에는 독립된 페이지에서 수정 된 카운팅 방법으로 통계에 적용되도록 해야 할 것으로 보입니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^

**Comment by 10001if** [comment]
@aanoaa 다시 요청드립니다. 오늘 서울시에서 수정된 정보를 다시 전달 받았습니다. 쿠폰의 제한 기준은 1가지 입니다. 4/31일입니다. 5/1일부터는 새로 바뀐 정식 프로그램이 적용될 것입니다. 그 전까지는 인원제한 없이 4/31일까지 이용할 수 있도록 수정 요청드립니다. 

> 이용자가 217명이 되면 더 이상 예약을 할 수 없도록 요청드립니다.
> 
> 매월 303명 정도가 대여해야 하는데. 이번달에 389명이 대여해서 다음 달 인원 중에 86명을 제하고 진행하려 합니다. 작업 요청드립니다.

따라서 위에서 요청드린 본 내용은 취소 되어야 합니다.

**Comment by 10001if** [comment]
@aanoaa 그리고 정책의 변경이 있었습니다. 1인당 2회에서 1인당 10회로 변경이 되었는데. 5월 1일이 아니라 바로 적용을 요청하시네요. 이 부분도 수정이 필요합니다. 10회가 적절한지는 의문이 드나, 서울시에서 내린 결정이라 이 부분에 대해서는 요청사항대로 진행을 해야 할 것으로 보입니다.

**Comment by 10001if** [comment]
10회는 전체가 아니라 매년 기준입니다. 따라서 2017년에는 1인당 10회까지 사용할 수 있으며 12/31일을 넘어가면 새로 갱신됩니다.

**Comment by aanoaa** [comment]
> @aanoaa 취업날개 방문인원은 사용수이어야 합니다. 하지만 인원이 달라질 수 있다고 하시기 때문에 현재는 종전대로 유지하되, 5월부터 진행되는 이벤트에는 독립된 페이지에서 수정 된 카운팅 방법으로 통계에 적용되도록 해야 할 것으로 보입니다.

이번에 이것을 확실하게 해두고 가지 않으면 또다시 문제가 발생할 수 있습니다.

**Comment by aanoaa** [comment]
의자에서 제일 중요한건 안넘어지는 겁니다.
기본으로 돌아가서 여기서 해야할 것은

- 하루에 쿠폰을 사용해서 대여한 사람 수와
- 예약만하고 사용하지 않은 사람 수

를 구해야 합니다.

--------------------------------

2017-04-10일에 방문

``` sql
SELECT 
  o.id, b.date, ui.gender, ui.birth, c.status
FROM 
  coupon c
JOIN
   `order` o ON c.id = o.coupon_id
JOIN
  booking b ON b.id = o.booking_id
JOIN
  user_info ui ON o.user_id = ui.user_id
WHERE
  o.status_id NOT IN (12, 14)
AND
  c.status = 'used'
AND
  DATE_FORMAT(b.date, '%Y-%m-%d') = '2017-04-10';
```
------------------------------

2017-04-10일에 방문안함

``` sql
SELECT 
  o.id, b.date, ui.gender, ui.birth, c.status
FROM 
  coupon c
JOIN
   `order` o ON c.id = o.coupon_id
JOIN
  booking b ON b.id = o.booking_id
JOIN
  user_info ui ON o.user_id = ui.user_id
WHERE
  o.status_id IN (12, 14)
AND
  c.status IN ('provided', 'reserved')
AND
  DATE_FORMAT(b.date, '%Y-%m-%d') = '2017-04-10';
```

**Comment by aanoaa** [comment]
지금의 쿼리는 지금까지의 사용횟수를 일별/성별/연령별로 한번에 뽑아내기 위해서 복잡합니다.
좀 더 이해하기 쉽게 바꾸면 좋지 않을까 합니다.
cc @yongbin

**Comment by aanoaa** [comment]
더 정확한 방문안함 조건은 `coupon.status = reserved` 입니다.

**Comment by aanoaa** [comment]
[OpenCloset-Cron-Visitor-v0.0.4.tar.gz](https://cpan.theopencloset.net/STAFF@THEOPENCLOSET.NET/OpenCloset-Cron-Visitor-v0.0.4.tar.gz) 배포하였습니다.

**Comment by aanoaa** [comment]
@10001if 최대 인원수는 제한이 있나요?

**Comment by aanoaa** [comment]
이벤트는 언제 종료하나요?

**Comment by aanoaa** [comment]
2017년도 이벤트는 한명이 10번까지 이용할 수 있습니다.
~ 2017-04월 까지는 인원 수 제한이 없습니다.
2017-05월 ~ 2017-12월은 10,000회 제한이 있습니다(확실치는 않습니다)

**Comment by aanoaa** [comment]
내년에도 이벤트가 진행될 가능성은 있지만 확실하지 않습니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
