### ISSUE TITLE
취업날개 이벤트 종료 메세지

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#1220]
이벤트가 종료되었다고 나타난다고 합니다.

**Comment by aanoaa** [comment]
지난 패치때에 이벤트와 관련된 작업이 있었지만 이벤트 종료일과 관련된 변경은 없었습니다.
기록을 찾기는 어렵지만 2017년도에 다시 이벤트를 시작하면서,
667건으로 협의를 했고 4월달에 정식으로 시작할것이므로 3월말까지 이벤트를 진행하기로 했던 것으로 기억합니다.

코드상에도 2017-03-31일이 이벤트 마지막 날입니다.

이벤트 종료기간을 늘이도록 하겠습니다.

4월이 지나기 전에 이벤트에 대한 정확한 내용이 업데이트 되어야 하겠습니다.

**Comment by aanoaa** [comment]
@10001if 2017년 3월까지 였던 이벤트기간을 변경해서 적용했습니다.

**Comment by 10001if** [comment]
@aanoaa 이벤트 기간은 4월 31일까지로 해주시면 됩니다.
