### ISSUE TITLE
취업날개 통계페이지의 숫자오류를 수정

### ISSUE THREAD

**Issue by yongbin** [opencloset/opencloset#1222]
서울시와 2016년 진행한 취업날개(쿠폰 이벤트명 : `seoul`)과 2017년 1월부터 진행중인 취업날개(`seoul-2017`) 의 통계가 서울시와 이미 공유한 내용과 일치하도록 통계수치를 조정합니다.

이 이슈는 #1198 과 #1221 과 관련이 있습니다.

**Comment by yongbin** [comment]
https://github.com/opencloset/opencloset/issues/1198#issuecomment-290654259

> @yongbin @aanoaa 정리를 하자면 다음과 같습니다.
> 
> 2017년 2월 이전의 이용자수는 시에 최종 제출했던 인원과 동일해야 합니다.
> 사용수+예약수 의 이슈가 있어 인원이 변경된다는 말씀해주셨지만, 쿠폰을 사용한 인원의 수가 달라진다는 건 시에서 납득하기 어려울 것으로 보입니다. 페이지를 분리하는 것은 문제가 없다고 하였으니
> 
> 1. 2016년 전체 : 이용자 수 4032명
> 2. 2017년 1월 2월 : 이용자 수 322명
> 3월은 23일까지 303명이 사용한 것으로 책정하였고, 24일부터 4월 어느 시점까지 303명이 사용되는 것으로 이벤트는 종료되는 것으로 결정되었습니다.
> 
> 따라서 1과 2는 이미 제출된 숫자이기 때문에 과거의 숫자와 동일해야 하고 3월~4월은 미래의 숫자이므로 동일한 기준으로 책정되면 문제 없습니다.

**Comment by yongbin** [comment]
우선 `seoul`과 `seoul-2017` 각각에 서울시에 보고된 정확한 숫자를 파악해야 합니다.

**Comment by yongbin** [comment]
다행이 https://github.com/opencloset/opencloset/issues/1198#issuecomment-285305674 에 캡처 되어있는 이미지의 2016년 숫자 합니다 4032로 서울시가 파악하고 있는 숫자와 동일합니다. `seoul`은 이 이미지의 숫자를 기준으로 복원하면 됩니다.

**Comment by yongbin** [comment]
[seoul-stat-csv.txt](https://github.com/opencloset/opencloset/files/888919/seoul-stat-csv.txt)


이미지를 옮긴 결과입니다.

```
|---------+-------+------+--------+----+-----+----+-----------+------+--------+----+----+----|
|   month | visit | male | female | 10 |  20 | 30 | non-visit | male | female | 10 | 20 | 30 |
|---------+-------+------+--------+----+-----+----+-----------+------+--------+----+----+----|
| 2016-12 |   629 |  218 |    411 |  6 | 553 | 69 |        36 |   12 |     24 |  2 | 33 |  1 |
| 2016-11 |   812 |  297 |    515 |  4 | 755 | 53 |        60 |   27 |     33 |  1 | 50 |  9 |
| 2016-10 |   533 |  172 |    361 |  2 | 472 | 59 |        34 |   10 |     24 |    | 29 |  5 |
|  2016-9 |   275 |  122 |    153 |    | 247 | 27 |        24 |    9 |     15 |  1 | 20 |  3 |
|  2016-8 |   349 |  137 |    212 |  1 | 307 | 41 |        21 |   12 |      9 |    | 18 |  3 |
|  2016-7 |   368 |  110 |    258 |  1 | 322 | 45 |        20 |    9 |     11 |    | 17 |  3 |
|  2016-6 |   458 |  174 |    284 |  4 | 381 | 73 |        16 |    8 |      8 |    | 15 |  1 |
|  2016-5 |   536 |  204 |    332 |    | 472 | 64 |        50 |   17 |     33 |    | 43 |  7 |
|  2016-4 |    72 |   22 |     50 |    |  64 |  8 |         9 |    2 |      7 |    |  6 |  3 |
|---------+-------+------+--------+----+-----+----+-----------+------+--------+----+----+----|
```

합계숫자를 검증해본 결과 총합의 합산과, 성별합산은 4032로 알고있는것과 동일하지만, 연령합산은 이미지와 동일함에도 불구하고 4030으로 2가 부족합니다. 아마도 10~30대 이외의 연령에서 취업날개를 이용한 대여가 있었는지 확인이 필요하며 저 수치가 문제가 없는지 확인해야합니다.

cc @10001if

**Comment by yongbin** [comment]
숫자에 대한 확인이 끝나면  https://github.com/opencloset/OpenCloset-Schema/issues/120 완료된 후 테이블에 넣으면 됩니다.

**Comment by aanoaa** [comment]
작업후에 확인해보니 4033건 입니다.(오차 +1)
이 수치를 변경할지, 그대로 둘지 상의해서 처리하도록 하겠습니다.

**Comment by aanoaa** [comment]
https://staff.theopencloset.net/stat/events/seoul

**Comment by yongbin** [comment]
조금 착오가 있는것 같습니다. `seoul`은 2016-12 까지 이벤트이고 2017-01은 `seoul-2017` 이벤트입니다 따라서 1월분을 뺴면 4006 으로 기존에 알고있던 오차와 동일한 오차가 납니다.(동일한 쿼리로 동일한 자료에서 뽑았으니 어찌보면 당연한 결과입니다) 

그리고 4032가 맞다고 하더라도 전체 월별총합까지 맞춰야하기때문에 결국은 데이터이 손을 대야할것으로 보입니다. 일단 2016-12까지의 자료를 기준으로 어떻게 조정하면 아름다운 4032가 나올지 비교해보고 업데이트하겠습니다.

**Comment by yongbin** [comment]
우선 현시점 DB와 열린옷장 최신을 제 로컬에 띄운후 `visitor` 테이블을 보정하는 쿼리를 정리해서 아름다운 결과가 나오도록 한 뒤 컨펌받고 이상없으면 실서버에 반영하도록 하겠습니다.

**Comment by aanoaa** [comment]
취업날개 이벤트는 12월말에 끝났지만, 12월에 예약해서 1월에 사용한 사용자도 있습니다.

**Comment by yongbin** [comment]
그런데 그게 제가 듣기로는 통계기준으로는 12월까지로 완료했고 1월에 등록된 사람은 `seoul-2017` 명목으로 받았다고 들었습니다. 형석님말씀하신방법으로 계산하는게 맞을수도 있습니다. 그부분 한만일대표님 근처예시면 확인해서 알려주세요

**Comment by 10001if** [comment]
@yongbin 1월까지 예약한 인원은 `seoul-2016`으로 예약을 진행했습니다. 하지만 1월 예약으로 이용한 인원에 대해서는 2017년 2월에 1월과 2월분을 합쳐서 지급받았습니다.

**Comment by aanoaa** [comment]
올해 취업날개는 2월중반에 시작했습니다.
임시로 667건을 3월말까지 하는걸로요.

**Comment by 10001if** [comment]
@yongbin `seoul-2017`은 2월 달에 예약한 인원들부터 시작되었습니다.

**Comment by 10001if** [comment]
제가 통계를 확인해 보니 4033명이 1월 인원이 포함된 숫자네요. 4032명은 2016년 4월~12월의 합산 숫자여야 합니다. 왜냐하면 12월말 종료 후 4032명에 대한 보고가 이뤄졌기 때문입니다.

**Comment by aanoaa** [comment]
예약자수도 방문인원에 포함되기 때문에 보고했을 당시 1월 예약자 수도 방문인원에 포함되어 있었을 것이라고 봅니다

**Comment by yongbin** [comment]
상황을 정리해보겠습니다.

@10001if 

1. 2017-01 월의 대여자는 2016년도에 시행한 취업날개 통계에 들어가야하나요? 맞다면 몇명으로 보고되었나요?
2. 2016년 시행한 취업날개 통계에 최종합(2017년 1월포함) 은 얼마로 나와야하나요?

위에 적어주신 comment 를 보면 2016 이벤트가 12월에 종료되었다는 말씀과  2017-01월 이벤트가 2016년 에 포함되었다는 말씀이 섞여있어서 정확하게 파악이 어렵습니다.

**Comment by aanoaa** [comment]
2016 이벤트 총합계산 할때에는 2017 이벤트는 시작되지도 않았습니다.
언제까지인지를 염두해두고 방문인원을 카운팅 하지 않았습니다.

지금도 `방문인원`은 `예약수+사용수` 입니다.
이벤트가 끝난 후에 총합을 계산할테니 2017년 1월초에(총합계산 할때) 했을 것입니다.
그렇다면 지금까지의 방문자 수를 계산해서 보여줄테니 2017-01 월의 수치도 포함되어서 `4032`건이 나왔을 것입니다.
`2017-01-05`일에 총합을 계산했다면 `4032`건 입니다.
`2017-01-06`일 부터는 `4033`건 입니다.(`2017-01-06`에 1건 있습니다.)

**Comment by aanoaa** [comment]
일간방문인원을 펼쳐보세요.

**Comment by aanoaa** [comment]
2016년도 취업날개 이벤트 방문자 수는 4033명이다.
다만 총합을 내는 시점에서 4032명이었을 수 있다.

가 저의 생각입니다.

**Comment by yongbin** [comment]
> 이벤트가 끝난 후에 총합을 계산할테니 2017년 1월초에(총합계산 할때) 했을 것입니다.
> 그렇다면 지금까지의 방문자 수를 계산해서 보여줄테니 2017-01 월의 수치도 포함되어서 4032건이 나왔을 것입니다.

그게 약간 다른게 https://github.com/opencloset/opencloset/issues/1198#issuecomment-285305674 스크린샷을 보면 2017-01 을 포함하지 않고도 4032명이 나오고 있습니다. 아마도 서울시에서 주장하는 수치는 저 수치인거 같습니다.

**Comment by aanoaa** [comment]
지금과 월별 방문인원이 조금씩 차이가 나네요.

계산의 오류를 발견하고 한번 수정해서 지금의 계산이 맞다고 한다면,
저 계산이 틀린게 아니었을까 싶습니다.

**Comment by aanoaa** [comment]
(일별 visitor 에 넣은 수치가 맞다면)
지금의 통계가 맞습니다.
그리고 2017-01까지가 2016년 이벤트에 계산되어야 하는게 맞습니다.

하지만

[월간방문인원.pdf](https://github.com/opencloset/opencloset/files/815983/default.pdf)
위 파일처럼 합이 맞아야 합니다.
우리의 실수를 인정하고 이야기는 했지만 이미 보고가 되어서 결과를 수정할 수는 없습니다.

2016년 12월까지의 합이 `4032`가 되어야 합니다.
2017년도 1-2월의 합은 296(2월) + 26(1월) 인 `326` 이어야 합니다.

- `2017-01` 의 26건을 `event-2017` 로 옮긴다
- `2016-04-25` 에 `+25` (그러면 2016 12월 까지가 `4032`)
- `2017-02-01` 에 `+1` (그러면 2017 1,2월의 합이 `326`)

--------------------------

@10001if 님과 이야기 되었습니다.
이렇게 마무리 하겠습니다.

**Comment by aanoaa** [comment]
``` SQL
UPDATE visitor SET event = 'seoul-2017' WHERE `date` BETWEEN '2017-01-01' AND '2017-01-31' AND event = 'seoul';
INSERT INTO visitor (`date`, event, visited, visited_male, visited_age_10) VALUES ('2016-04-25', 'seoul', 25, 25, 25);
INSERT INTO visitor (`date`, event, visited, visited_male, visited_age_10) VALUES ('2017-02-01', 'seoul-2017', 1, 1, 1);
```

**Comment by aanoaa** [comment]
적용하였습니다.
@10001if 수치를 확인해보시기 바랍니다.

**Comment by yongbin** [comment]
제가 가지고 있던 표랑 비교했을때는 맞는것 같습니다. 제 입장에서는 더 이상 확인할 방법이 없습니다. @10001if 님과 이야기해서 확인후에 이슈 닫으면 됩니다. 수고하셨습니다!

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
