### ISSUE TITLE
온라인 통계 페이지의 신설

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1224]
매월 온라인 인원을 집계해야 하는 이슈가 발생하였습니다.
필요한 정보는 오프라인 방문자 정보와 동일하게, 일/주/월 별 인원입니다.

작업 요청드립니다.

**Comment by 10001if** [comment]
@aanoaa 어느 분께 작업을 요청드려야 할지 몰라 우선 이슈로 남겨놓도록 하겠습니다.

**Comment by aanoaa** [comment]
`visitor.online` 컬럼이 필요하지 않나 싶습니다.

**Comment by aanoaa** [comment]
`visitor.online` 컬럼을 추가하고, `OpenCloset::Cron::Visitor` 에서 일일 방문자의 통계를 넣어주는 작업이 필요합니다.
지금 방문자 통계화면에서 online 컬럼만 구분해서 볼 수 있도록 제공하면 되겠습니다.

**Comment by aanoaa** [comment]
결제가 되지 않았음에도 `rental_date`가 입력되어 있는 주문서들에 대해 일괄 NULL 로 변경해주는 작업이 필요합니다.

**Comment by aanoaa** [comment]
온라인의 경우 예약/방문/미방문/Bestfit 은 의미가 없습니다.
대여자 수만 수집하고 보여주면 되지 않을까 합니다.

**Comment by keedi** [comment]
통계 관련은 staff에 있는 것을 포함, 새로운 아예 사이트를 별도로 구성하는 것이 좋지 않을까 생각하고 있습니다만, 아직 구체화 된 것은 없습니다.

**Comment by keedi** [comment]
일단 본 기능까지는 staff쪽에 구현되고 나면 통째로 덜어내서 사이트를 분리하는 방법을 고민해보겠습니다.

**Comment by aanoaa** [comment]
조건을 `rental_date` 로 해서 온라인 대여자의 일별 통계를 넣어봤습니다.
04-06(16), 04-07(15) 의 수치가 이상합니다.

아무래도 지난번에 결제가 확정되기 전에 `rental_date` 를 넣어두었던 문제 같습니다.
데이터를 수정해주고 다시 수집하면 올바른 결과가 나오지 않을까 합니다.

![- 2017-04-11 16-44-40](https://cloud.githubusercontent.com/assets/170528/24898214/129f072c-1ed7-11e7-84fb-3340d09c6ed9.png)

**Comment by aanoaa** [comment]
https://staff.theopencloset.net/stat/visitor/online/

**Comment by aanoaa** [comment]
`2017-04-10 (월)` 이 0건으로 나오는데 발송은 3건 했다고 합니다.
`rental_date` 로 수집을 하고 있어서 발송(예정)일과는 차이가 있을 수 있습니다.

**Comment by 10001if** [comment]
@aanoaa @keedi 확인했습니다. 본 페이지로 정산을 실시하는 것은 아니므로 추세를 확인하기 위한 페이지로 활용하겠습니다.
