### ISSUE TITLE
방문자 예약시간 변경 오류

### ISSUE THREAD

**Issue by MoDoLEE** [opencloset/opencloset#1225]
#1075  이슈와 관련있습니다.

해당 기능이 현재 오작동 중입니다.
"예약 시간이 지났습니다" 라는 메세지가 나온다는 피드백이 많습니다.
제 예상으로는 타임존 변경 시 문제가 생긴 것 같습니다. 확인 부탁드립니다.

**Comment by aanoaa** [comment]
확인했습니다.

지난번의 timezone 작업의 영향은 아니고
오늘날짜를 기준으로 예약시간을 확인하는데, 오늘날짜에 timezone 설정이 빠져있었습니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
