### ISSUE TITLE
의류정보 페이지에서 의류태그 추가 시 검색기능

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1226]
의류정보에서 태그를  추가할 때
태그 검색이 가능하도록 기능추가해주세요.
(새옷 등록 페이지에서 태그 검색이 되는 것처럼)
태그 종류가 너무 많아져서 검색없이 추가하는데 시간이 너무 걸립니다.

**Comment by aanoaa** [comment]
이미 검색이 되고 있습니다.

**Comment by pingpongworks** [comment]
네~숨은 기능이 있었네요. 감사합니다^^
