### ISSUE TITLE
실수로 반납 처리했는데, 환불로 수정 요청

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1229]
/order/58027

**Comment by aanoaa** [comment]
비슷한 이슈가 있었나요?
지금 반납으로 되어 있는데, 상태가 환불로 바뀌어야 필요가 있나요?

-------------------------

지금은 주문서의 상태를 A 에서 B 로 바꿀때에 조심해야 할게뭐지? 를 먼저 생각하게 됩니다.

상태변경을 조심해서 해야할 경우와 그렇지 않은 경우가 있기 때문입니다.

- 대여중 -> 반납
- xxx -> 대여중

일때에는 
옷을 잃어 버릴 수도 있기 때문에 바코드를 꼭 찍어주어야 합니다.
해서 상태변경이 번거롭습니다.

모듈로써 이런한 기능을 지원한다면 요청이 있을때마다 스크립트를 간단하게 돌려서 해결할 수 있지 않을까 합니다.
괜히 이슈의 볼륨을 키우는 것일 수도 있습니다.

**Comment by aanoaa** [comment]
- 미납 -> 완납
- 미납 -> 불납
- 불납 -> 완납

기능은 모듈로 만들어서 잘 사용하고 있습니다.
이처럼 비슷한 기능을 하는 모듈이 있으면 반복된 번거로운 작업을 줄일 수 있지 않을까 합니다.

**Comment by aanoaa** [comment]
my $status = OpenCloset::Common::Status->new;
    $status->update({ $order, $to, $extra });

주문서의 상태가 변경될때에 고려해야 할 상황이 있습니다.

- 주문서의 상태가 변경될때에 문자메세지가 전송되어야 한다던지
- 주문서와 관련된 모든 의류들의 상태가 변경되어야 한다던지
- 미납금액을 받은건지?
- 환불금액은 얼마를 받은건지?
- 결제금액이 얼마인지?

등등 좀 어렵습니다.

**Comment by aanoaa** [comment]
상황이 많아서 모든 경우를 고려하는 건 좀 어려울 것 같고,
이와 같은 요청이 있을때마다 하나씩 추가해가면 할 수 있을 것도 같습니다.
이번경우에는 `반납 -> 환불` 에 대한 문제만 처리하는 거죠.

**Comment by pingpongworks** [comment]
네~ 비용을 환불해준 경우에 실수로 반납처리해버리면 정산이 안 맞을 수 있어서, 반납을 굳이 환불로 바꾸려는 것입니다. 또한 나중에 대여기록을 확인해야할 경우가 있을 때 환불을 했었는지 제대로 대여를 했었는지를 알야아 할 수도 있고요, 

하지만, 잦은 경우가 아니니까 좀더 경우가 많이 생기면 '모듈'생각해보기로 하지요~아직까지는 옷장지기들이 환불과 반납의 개념을 혼동하는 경우가 있어서 처리할 때 조금만 더 신경쓰면 될 거 같습니다.

**Comment by aanoaa** [comment]
> 하지만, 잦은 경우가 아니니까 좀더 경우가 많이 생기면 '모듈'생각해보기로 하지요~아직까지는 옷장지기들이 환불과 반납의 개념을 혼동하는 경우가 있어서 처리할 때 조금만 더 신경쓰면 될 거 같습니다.

제가 어떻게 처리할 것인지에 대한 방식에 대한 고민이었습니다.

**Comment by keedi** [comment]
유사한 이슈는 #1035 입니다. 그 때 이후로 관련 절차에 시스템상 바뀐 부분이 없다면 동일할 것입니다. 당시 기능으로 만들지 않은 것은 실수로 클릭해 반납을 환불로 만드는 경우가 생길까봐였습니다.

**Comment by aanoaa** [comment]
> 지금 반납으로 되어 있는데, 상태가 환불로 바뀌어야 필요가 있나요?

의미상으로 다르기 때문입니다.
의류를 다시 대여가능한 상태로 되돌리는 것과는 별개로 환불했으니 반납보다는 환불로 기록하는
것이 더 정확합니다.

**Comment by aanoaa** [comment]
`returned2payback` 기능을 모듈화해서 처리하려 합니다.

- `OpenCloset::Common::Status`
- `OpenCloset::Common::Order`

패키지명 둘 중 하나로 하려고 하는데, 추천 받습니다.
더 좋은 제안을 해주셔도 좋습니다.

    use OpenCloset::Common::Xxxx qw/returned2payback/
    returned2payback( $order, $extra );

앞으로 많은 기능이 추가 될 것이라고 생각합니다.

- waiting_deposit2payment_done
- rental2returned
- ...

등등

필요할때마다 추가해서 중복된 작업을 줄이는 것이 목표입니다.
가능하면 테스트코드도 꼼꼼히 작성하고요.

**Comment by pingpongworks** [comment]
@keedi 환불수수료 기능이 있었군요! 특히 온라인대여 후 환불하는 경우가 상당수 있어서, 환불 수수료 규정이 필요할수도 있겠다고 생각하고 있었는데, 활용할 수 있을 것 같습니다^^

**Comment by aanoaa** [comment]
테스트로 반납을 환불로 변경한 후 비교화면입니다.

![- 2017-05-01 16-23-16](https://cloud.githubusercontent.com/assets/170528/25574622/172163a8-2e8b-11e7-8e53-b0ac0dcbd32e.png)

----------------------------

![after](https://cloud.githubusercontent.com/assets/170528/25574630/1ef27f86-2e8b-11e7-8dcd-4fb1e4139c16.png)

**Comment by aanoaa** [comment]
$ MOJO_CONFIG=app.conf script/web returned2payback 58027

배포뒤에 위 명령어를 실행시켜야 합니다.

**Comment by aanoaa** [comment]
https://staff.theopencloset.net/order/58027

    $ MOJO_CONFIG=app.conf script/web returned2payback 58027
    Successfully updated order(58027) from RETURNED to PAYBACK

환불로 변경하였습니다.

**Comment by pingpongworks** [comment]
확인했습니다~ 감사합니다~

김소령
OpenCloset / story tailor
010. 5278. 2844
pingpong@theopencloset.net

2017. 5. 1. 오후 6:02 Hyungsuk Hong <notifications@github.com> 작성:
