### ISSUE TITLE
비율 할인 쿠폰시스템과 링크스타트 이벤트 페이지 개설

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1231]
#1230 에서 발행한 쿠폰번호는 종이쿠폰으로 배포될 예정이기 때문에 기존의 취업날개나 해피빈과는 다르게 추가로 필요한 부분이 있을 듯 합니다.  

## **1. 예약시 추가로 필요한 부분**
1) 오프라인 예약 : https://visit.theopencloset.net/coupon 에서 쿠폰번호 입력 기존과 동일
2) 온라인예약 : 결제시 '쿠폰을 사용하겠습니다' 선택하고 쿠폰번호 입력, 기존과 동일
**3) 어느 대학 소속인지 입력이 필요하다고 합니다. 어느 시점에서 어떤 방식으로 입력하는게 좋을지 논의가 필요합니다.** 

## **2. 결제시 추가로 필요한 부분**
**1) 30% 할인된 금액으로 표기되어야 합니다**
2) 현재 3회이상 대여시 결제처럼 원래금액과 할인된 금액 같이 보이면 될 듯 합니다

**## 3. 월 정산시 링크스타트에 전달이 필요한 데이터**
1) 쿠폰 이용내역 : 이용자수 / 전체 대여금액 / 할인된 금액 (열린옷장에 정산해야할 금액)
2) 쿠폰이용자들이 쓴 대여메시지 모아서 따로 전달 : 이 부분은 어쩌면 @keedi 님과 논의하는게 필요할지도 모르겠네요. @aanoaa 님이 판단해주시면 좋겠습니다.

기업에서 빨리 학생들에게 혜택을 주고 싶다고 하셔서 조금 급하게 진행되어야 하게 됐네요. asap으로 부탁드려요~

**Comment by aanoaa** [comment]
검토해야할 부분이 뭔지도 모르는 상태입니다.
논의는 오래전부터 됐던건데, 갑가지 28일까지 해야하는 거라면 촉박하지 않나 싶습니다.

**Comment by aanoaa** [comment]
쿠폰시스템이 복잡해지는 것도 감안하시는 건가요?

이제까지 쿠폰 타입은 2종류였습니다.

1. 단벌셋트(금액과 상관없이 1벌의 수트셋트를 대여할 수 있음)
2. 금액(1만원쿠폰등)

보통의 경우라면, 쿠폰번호만 입력하고 바로 사용할 수 있도록 되어 있습니다.

1번의 경우라면 쿠폰번호 입력하면 끝
2번의 경우라면 쿠폰번호를 입력하고 `전체대여비 - 쿠폰금액`을 제외하고 입금해야 합니다.

이번에 말씀하신 것은,

- 30% 할인 쿠폰
  - 서비스제휴?(30% 쿠폰 할인을 적용받는 대신에 자신이 어느대학 소속인지 입력해야 합니다.)

어느대학 소속인지 입력하지 않으면? 30% 적용이 아니되는 것인가요?

저같은 사람은 조건이 붙는 쿠폰은 사용하지 않습니다.
의심하게 되거든요.

**Comment by aanoaa** [comment]
대학명을 입력하는데 확인은 안해도 되나요?
사용자가 100명인데, 모두 서울대라고 적어도 괜찮은건가요?

**Comment by aanoaa** [comment]
> 쿠폰 이용내역 : 이용자수 / 전체 대여금액 / 할인된 금액 (열린옷장에 정산해야할 금액)

지금의 취업날개처럼 방문자수/미방문자수 통계는 낼 수 있지만, 주문서의 금액을 계산하고 있지는 않습니다.
통계 시스템의 수정이 필요합니다.

**Comment by aanoaa** [comment]
이슈 우선순위를 따로 관리하면서, ASAP 라벨은 더이상 사용하지 않습니다.
지난 경험에서 ASAP 가 남용되었기 때문입니다.

**Comment by aanoaa** [comment]
마음에 걸리는 부분입니다.

1. 쿠폰 사용조건으로 대학이름을 입력
  - 심플한 사용성을 해침
  - 열린옷장과 열린옷장 쿠폰은 대학과 연관이 없지만 어딘가에 사용자의 대학교명을 저장해야함
2. % 타입의 쿠폰추가
  - 쿠폰타입별로 일일 통계 계산 방식이 달라짐

시스템이 복잡해지는 것은 필요하다면 어쩔 수 없는 것이겠지만, 하나의 제휴?업체 때문에 서비스의 심플함을 포기하는 것은
안좋은 선택인 것 같습니다.

취업날개 이벤트도 서울시 거주자임을 확인하는 절차 하나때문에 얼마나 번거롭던가요.

**Comment by aanoaa** [comment]
> 대학명을 입력하는데 확인은 안해도 되나요?

확인하지 않아도 됩니다.

**Comment by aanoaa** [comment]
3회 이상 대여자가 링크스타터 쿠폰을 사용해서 예약했다면 할인은 어떻게 되나요?

**Comment by pingpongworks** [comment]
28일 금요일까지 완료되야하는 부분은 "쿠폰 발행" 만입니다. 

예약시스템과 30% 할인시스템 작업이 언제까지 완료되어
쿠폰사용이 가능한지는 이번 주에 작업하시면서 알려주세요.  
일단은 5월 첫째주 이후에 쿠폰 배포하는 것으로 링크스타트에 요청하겠습니다.

**Comment by aanoaa** [comment]
@pingpongworks 님과 이야기를 했습니다.
원안대로 진행합니다.

다만 마감시간이 5월 1일이 아니라 제가 준비되고나면 쿠폰을 발행해서 사용할 수 있도록 합니다.

### 오프라인 대여 ###

https://visit.theopencloset.net/events/seoul

처럼 링크스타터 이벤트 화면을 구성합니다.
쿠폰번호와 더불어 대학명을 입력받습니다.
결제시에 쿠폰타입을 확인하여 30% 할인된 금액으로 결제할 수 있도록 합니다.

**3회 이상 대여자는 중복할인이 가능한건지 확인해야 합니다.**

### 온라인 대여 ###

결제할때에 `쿠폰을 사용하겠습니다` 버튼을 누르고 쿠폰번호를 입력합니다.
쿠폰타입이 링크스타터라면 대학이름을 입력받고 할인율을 적용해서 결제금액을 갱신합니다.

**3회 이상 대여자는 중복할인이 가능한건지 확인해야 합니다.**

### 사용금액 결산 ###

취업날개는 오프라인 대여자의 방문자수/미방문자수 만을 계산하고 있습니다.
이것으로는 부족하고 할인타입 쿠폰에 대해서는 주문서의 할인된 금액을 모아서 저장해야 합니다.

통계화면에서는 이 금액까지 표시되어야 합니다.

**Comment by aanoaa** [comment]
링크스타트에서 다른 서비스와도 이벤트를 기획중인데,
할인 쿠폰이 아닌 금액쿠폰을 사용하는 곳도 있습니다.

**Comment by pingpongworks** [comment]
https://visit.theopencloset.net/events/linkstart
페이지에 들어갈 타이틀과 문구는 정리해서 형석님께 전달하겠습니다.

**Comment by aanoaa** [comment]
대학명을 저장해두어야 합니다.
주문서에 들어가기에는 적절하지 않은 것 같고,

    coupon.extra TEXT DEFAULT NULL

정도면 적당하지 않을까 싶습니다.

**Comment by aanoaa** [comment]
![- 2017-04-25 18-25-17](https://cloud.githubusercontent.com/assets/170528/25378280/e9f61a40-29e4-11e7-8235-41a32303197d.png)

3회 이상 대여 할인이 적용되면 `order_detail.desc` 에 `3회 이상 방문(30% 할인)` 이라고 적고 있습니다.
쿠폰에 의한 할인가가 적용될때에도 `order_detail.desc` 에 관련된 내용을 적어주도록 하는게 좋을 것 같습니다.

**Comment by aanoaa** [comment]
`rate` 타입의 쿠폰을 사용한 주문서에 대해서는 `od.desc` 에 `30% 할인쿠폰` 이라고 적도록 하겠습니다.

**Comment by pingpongworks** [comment]
![default](https://cloud.githubusercontent.com/assets/17288038/25381033/424ec45a-29ed-11e7-8b74-f4f17e4580a6.png)
링크스타트 예약페이지에 로고, 이 데이터로 사용해주세요~

**Comment by aanoaa** [comment]
주문서마다 할인율을 적용해서 금액을 계산하려면
`10,000`원짜리 품목에 할인율이 적용된 금액 `7,000`원 으로 저장하지 말고, `10,000`원으로 기록하고
할인금액 품목인 `-3,000`원을 추가하는 것이 유리할 것 같습니다.

모든품목에 대해서이지만 예를 들어
자켓, 팬츠에 대해서

    자켓: 7,000(30% 쿠폰할인)
    팬츠: 7,000(30% 쿠폰할인)

가 아니라

    자켓: 10,000
    팬츠: 10,000
    자켓: -3,000(30% 쿠폰할인)
    팬츠: -3,000(30% 쿠폰할인)

이렇게 하지 않으면 `7,000` 과 `30%` 를 가지고 `3,000`원을 계산해 내야 합니다.

    7000 = X - X * 0.3

1번은 desc text 를 파싱해서 금액을 계산해내는 방법이고
2번은 청구할 금액을 추가로 저장하는 방법입니다.

**Comment by aanoaa** [comment]
@pingpongworks 님의 말씀해주신 방법대로,
품목별로 추가할 것이 아니라 총액에 대해 할인 금액을 지정해주는 방법도 있습니다.

    자켓: 10,000
    팬츠: 10,000
    할인쿠폰: -6,000(20,000 * 30%)

가장 적절한 방법이 아닌가 싶습니다.

**Comment by aanoaa** [comment]
#1208 이 해결되어서 결제대기 시점에 쿠폰을 넣을 수 있습니다.
포장 -> 포장완료 시점에 쿠폰할인금액을 계산하는데 ,
결제대기인 주문서에 쿠폰을 넣을때에도 쿠폰할인금액을 계산해야 하겠습니다.

**Comment by aanoaa** [comment]
3회 이상 할인 대상자가 30% 이하의 할인 쿠폰을 사용했을때는 오히려 더 불리한 조건으로 결제를 하게 됩니다.
이런 문제는 알고만 있겠습니다.

**Comment by aanoaa** [comment]
Controller 에서 스슥 하는걸로는 코드의 중복을 피할 수가 없습니다.
주문서의 할인쿠폰과 관려된 모듈로 작성해서 재사용할 수 있도록 해야 할 것 같습니다.

**Comment by aanoaa** [comment]
오프라인에서 주문서 상세내역이 작성되는 시점은 `포장 -> 포장완료`(선택한 항목을 대여합니다) 입니다.
이때에 할인쿠폰을 사용했다면 할인금액을 계산해서 넣어주게 됩니다.

결제대기 상태는 포장완료 이후입니다.
결제대기 상태인 주문서에 할인 쿠폰을 적용하면 할인금액이 추가되어야 하겠습니다.

쿠폰의 중복사용방지를 위해서 다른주문서에서 같은 쿠폰을 사용하면 쿠폰이 이동되고 있습니다.
이런 경우에는 두번 할인된 금액이 추가될 수 있기 때문에 이러한 경우에도 고려해야 합니다.

**Comment by aanoaa** [comment]
조따 복잡함 :confused:

**Comment by aanoaa** [comment]
테스트 중인데, js 에서 od.final_price 를 `0` 으로 업데이트 시킵니다.
어디서 그러는지 찾고 있습니다.

    [Wed Apr 26 18:44:47 2017] [info] order update: detail-final_price.0
    [Wed Apr 26 18:44:47 2017] [info]   order_detail.final_price 318481 [-6000] -> [0]

**Comment by aanoaa** [comment]
`대여기간`을 변경하면 금액이 바뀌는 기능이 있습니다.
이때에 할인쿠폰의 경우는 어찌 해야 할까요?
30% 할인 쿠폰이라면 3박4일 기준의 할인쿠폰인지 5박6일 대여해도 30%가 적용되는 것인가요?

이 기능에 의해 쿠폰금액이 `0`으로 바뀌는 것이었습니다.

    POST /order/58032/update
    name=detail-final_price&pk=318481&value=0

적절한 수정이 필요합니다.

**Comment by aanoaa** [comment]
의류가 아닌 품목에 대해서도 추가일에 대해 일괄 적용됩니다.
배송비와 에누리 금액을 각각 3,000원 1,000원 으로 하고 대여기간을 6박7일로(+3d) 변경하면
9,000원 3,000원이 되었습니다.

의도치 않은 기능인 것 같습니다.
의류에 대해서만 `대여비 x 추가일 x 20%` 를 적용해야 하겠습니다.

**Comment by pingpongworks** [comment]
3박4일까지만 지원되는걸로 링크스타트와 합의가 있었습니다. 품목도 기본세트만요~

남 : 자켓, 팬츠, 셔츠, 타이, 구두, 벨트
여 : 자켓, 스커트 or 팬츠, 블라우스, 구두

기간 연장이나 해당 외 품목 대여할 경우는 무조건 본인부담입니다~

김소령
OpenCloset / story tailor
010. 5278. 2844
pingpong@theopencloset.net

2017. 4. 27. 오후 12:57 Hyungsuk Hong <notifications@github.com> 작성:

**Comment by aanoaa** [comment]
오프라인과 온라인으로 테스트 용도의 쿠폰을 만들어서 사용해보고 통계가 제대로 집계되는지
확인해봐야 합니다.

또 각 기능이 원하는 요구사항이 맞는지 확인 받아야 합니다.

**Comment by pingpongworks** [comment]
https://visit.theopencloset.net/events/linkstart 에서 테스트해보면 되겠지요? 
테스트용 쿠폰번호 발행해주시면 테스트해보겠습니다~

**Comment by aanoaa** [comment]
통계가 수집되지 않았습니다.
로그를 살펴보니,

    2017-04-30 00:08:00.003051 +0900 info  main: insert_event_linkstart_daily[08 00 * * *] launched
    unhandled callback exception on event (start, OpenCloset::Cron=HASH(0x2afddd0), ): Undefined subroutine &main::event_linkstart called at /home/opencloset/.perlbrew/libs/perl-5.18.2@service/bin/opencloset-cron-visitor.pl line 154.

에러가 발생했습니다.

import 해주지 않고 사용한게 문제입니다.
수정해서 다시 배포하도록 하겠습니다.

**Comment by aanoaa** [comment]
> https://visit.theopencloset.net/events/linkstart 에서 테스트해보면 되겠지요?
> 테스트용 쿠폰번호 발행해주시면 테스트해보겠습니다~

"링크스타트 테스트용 쿠폰" 이란 제목의 이메일로 테스트용 쿠폰을 전달해드렸습니다.

오프라인/온라인 대여 모두 적용되는데, 온라인 쿠폰의 경우 대여일을 기준으로 통계를 산정합니다.
지금이 5/1일인데 배송문제로 공휴일을 제외하고 여차저차하면 대여일이 5/11일이 되고, 오늘 사용한 쿠폰에 대한 사용 통계는 5/12일날 볼 수 있습니다.(그날 통계는 다음날 새벽에 수집)

**Comment by aanoaa** [comment]
https://staff.theopencloset.net/stat/events/linkstart

cc @pingpongworks

**Comment by pingpongworks** [comment]
온라인, 오프라인 모두 쿠폰으로 대여 테스트 해보았습니다. 일단, 쿠폰 사용에는 문제가 없습니다. 

다만, 온라인 쿠폰을 사용할 때 쿠폰 입력 후 결제를 하지 않을 경우가 생길 것 같아서 쿠폰 입력 창에 문구 추가를 요청합니다. 
<img width="960" alt="2017-05-01 10 07 05" src="https://cloud.githubusercontent.com/assets/17288038/25570098/9d73a058-2e5c-11e7-893b-259c849420aa.png">

현재 입력되어있는 "30% 할인쿠폰입니다. LINKSTART X 열린옷장 이벤트쿠폰입니다" 그 자리에 아래와 같이 넣어주세요. 

## 쿠폰번호를 입력하시면 30% 할인됩니다.
## 결제창으로 이동 후 나머지 금액을 결제해주세요.
(타 할인혜택과 중복할인은 되지 않습니다.)

**Comment by aanoaa** [comment]
> 쿠폰번호를 입력하시면 30% 할인됩니다.

쿠폰번호는 이미 입력된 이후입니다.

"쿠폰을 사용하시면 30% 할인됩니다." 가 더 정확한 표현입니다.

> 결제창으로 이동 후 나머지 금액을 결제해주세요.

결제창으로 이동하지 않습니다.
"결제버튼을 눌러서 나머지금액을 결제해주세요" 가 더 정확한 표현입니다.

**Comment by pingpongworks** [comment]
> 쿠폰을 사용하시면 30% 할인됩니다.
> 결제버튼을 눌러서 나머지금액을 결제해주세요.
> (타 할인혜택과 중복할인은 되지 않습니다.)

이렇게 되네요. 좋습니다~

**Comment by pingpongworks** [comment]
온라인 쿠폰 내용 확인했습니다~ 훨씬 이용 프로세스가 쉬워진 거 같네요. 감사합니다~
