### ISSUE TITLE
이벤트관리

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#1232]
링크스타트와 같은 이벤트를 관리(추가/수정/삭제) 할 수 있으면 좋을 것 같습니다.

- 이벤트 추가
- 이벤트 삭제
- 쿠폰발행
  - 타입설정
  - 타입에 따른 부가정보 입력
- 시작/만료일 설정

그러나 대학이름과 같이 추가로 입력받아야 할 정보들이 있다면 관리 UI 로는 해결할 수 없을 것 입니다.

**Comment by 10001if** [comment]
쿠폰을 발행하는 이슈가 아직은 많지 않습니다. 추가적으로 필요한 상황이 생기면 다시 요청드리겠습니다~!
