### ISSUE TITLE
인천시 쿠폰 발행 요청

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1238]
https://github.com/opencloset/opencloset/issues/858 에서 진행해 주셨던 내용입니다.

`인천시` 단체의 쿠폰 발행을 요청드립니다. 방법은 지난 번에 보내주셨던 `십시일*`의 방식과 동일합니다.
- `suit` 타입으로
- 사용기간은 2018/9/31 까지
- 설명은 `청사진`
- 500개

인천시에서 선정한 청년 4000명을 대상으로 진행하는 프로젝트라고 합니다.
열린옷장에서는 500개의 쿠폰 번호만 전달하면 개인이 예약페이지를 통해 쿠폰 입력 후 예약을 진행한다고 합니다. 십시일*과 관악고*, 해피*캠페인과 내용은 동일합니다.

다만, 대상자가 이용 후 인천시에서 제공하는 홈페이지에 접속해 이용자를 별도로 입력해 주어야 하는 번거로움이 있습니다. 이 부분은 업체와 더 협의 중입니다. 우리 쪽에서 따로 프로그램을 개선할 필요성은 없어 보입니다. 

통계페이지는 취업날개와 동일하게 진행되면 됩니다. 

쿠폰번호 발급은 5/12일까지 요청드립니다.

**Comment by aanoaa** [comment]
쿠폰을 발행하는 것은 간단하지만,
새로운 쿠폰에대한 통계를 수집하는 프로그램을 추가해야 합니다.

**Comment by aanoaa** [comment]
- 해피빈캠페인
- gwanak
- 10bob

의 통계도 수집하고 있지 않습니다.
이번에 같이 진행하도록 하겠습니다.

**Comment by aanoaa** [comment]
이미 `해피빈캠페인` 이 한글로 사용하고 있어서 굳이 영문으로 이벤트 이름을 고집하지 않아도 될 것 같습니다.
통계페이지가 `/stat/events/:name` 으로 되어 있는데 한글이 들어가면 어찌될지는 모르겠습니다.

내부적으로 변환해서 제공해야 할 필요도 있습니다.

**Comment by aanoaa** [comment]
인천광역시 일자리정책과에서 진행하는 것이라고 합니다.

`incheonjob` 을 내부적인 이벤트명으로 사용하겠습니다.
어디에 발행한 쿠폰인지 구분하기 위한 이름입니다.

**Comment by aanoaa** [comment]
``` perl
#!/usr/bin/env perl
use utf8;
use strict;
use warnings;

use Algorithm::CouponCode qw(cc_generate cc_validate);

use OpenCloset::Schema;

my $CONF   = require 'app.conf';
my $schema = OpenCloset::Schema->connect({ ... });

my $type    = 'suit';
my $desc    = 'incheonjob';
my $expires = '2018-09-30T23:59:59';

for ( 1 .. 500 ) {
    my $code = cc_generate( parts => 3 );
    my $coupon = $schema->resultset('Coupon')->create(
        {
            code         => $code,
            type         => $type,
            desc         => $desc,
            expires_date => $expires
        }
    );

    unless ($coupon) {
        print STDERR "Couldn't create a new Coupon\n";
        next;
    }

    print "$code\n";
}
```

    $ perl a.pl > incheonjob.txt

로 해서 쿠폰 500장을 발급할 수 있습니다.
9월은 30일 까지 있습니다. 31일 expires_date 를 설정하면 에러가 발생합니다.

**Comment by aanoaa** [comment]
새로운 500장을 발급해서 email 로 전달해드렸습니다.

**Comment by 10001if** [comment]
@aanoaa 500개 발행요청이 추가로 들어왔네요. 지난번 발행해주셨던 것 말고 추가로 500개 발행 요청드립니다

**Comment by aanoaa** [comment]
이메일로 전달해드렸습니다.

**Comment by 10001if** [comment]
@aanoaa 인천시에서 유효기간 재설정을 요청하여서 프로그램을 관리하는 업체에서 쿠폰 1,000장을 다시 요청하였습니다. 메일로 주시면 다시 바로 전달하도록 하겠습니다.

**Comment by 10001if** [comment]
이슈 닫도록 하겠습니다.

**Comment by aanoaa** [comment]
마지막 쿠폰 1000장은 전달해드린 기록이 없는데 닫아도 되나요?

**Comment by 10001if** [comment]
@aanoaa 그러네요. 전달 받은걸로 착각하고 있었나봐요~ 그래도 따로 요청이 없으니.. 연락이 오면 다시 말씀드릴게요~!

**Comment by aanoaa** [comment]
``` perl
#!/usr/bin/env perl
use utf8;
use strict;
use warnings;

use Algorithm::CouponCode qw(cc_generate cc_validate);

use OpenCloset::Schema;

my $CONF   = require 'app.conf';
my $schema = OpenCloset::Schema->connect({ ... });

my $type    = 'suit';
my $desc    = 'incheonjob';
my $expires = '2018-09-30T23:59:59';

for ( 1 .. 1000 ) {
    my $code = cc_generate( parts => 3 );
    my $coupon = $schema->resultset('Coupon')->create(
        {
            code         => $code,
            type         => $type,
            desc         => $desc,
            expires_date => $expires
        }
    );

    unless ($coupon) {
        print STDERR "Couldn't create a new Coupon\n";
        next;
    }

    print "$code\n";
}
```

    $ perl a.pl > a.txt

이메일로 전달해 드렸습니다.
