### ISSUE TITLE
취업날개 예약 안내

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1239]
취업날개로 무료대여할 수 있다는 것을 좀더 적극적으로 안내하기 위해서 
방문예약 페이지 내용을 수정하여 다음과 같이 안내하고자 합니다.
좀더 많은 사람들이 무료대여의 혜택을 누릴 수 있도록 하기 위함입니다. 

취업날개 온라인대여의 경우에도 다음과 같은 안내가 필요할 듯 한데, 추후에 다시 말씀드릴게요~

![-](https://cloud.githubusercontent.com/assets/17288038/25935985/a00c5fce-3660-11e7-8f6e-3f8e5a525ae5.png)

**취업날개 예약하러가기** 누르면 다음 페이지로 연결되면 됩니다
http://job.seoul.go.kr/www/add_service/openChothesChest.do?method=selectOpenChothesChest

**Comment by aanoaa** [comment]
왜 직접 예약하면 혜택을 받지 못하고 취업날개서비스를 통해서만 가능한지 설명을 해주는게 있으면 더 좋을 것 같습니다.

    더 알아보기(클릭)

    (숨김/보임)
    어쩌고 저쩌고
    어쩌고 저쩌고

**Comment by aanoaa** [comment]
@pingpongworks 일부러 열린옷장 홈페이지 링크버튼과 예약가이드 링크버튼을 빼신건가요?

**Comment by pingpongworks** [comment]
네~ 만일대표와 논의한 결과 페이지에서 꼭 필요없다고 판단되어서 뺐어요~

김소령
OpenCloset / story tailor
010. 5278. 2844
pingpong@theopencloset.net

2017. 5. 15. 오후 3:38 Hyungsuk Hong <notifications@github.com> 작성:

**Comment by 10001if** [comment]
@pingpongworks 메일 푸터에 개인정보가 그대로 노출됩니다~ 우선 제가 삭제할게요~

**Comment by aanoaa** [comment]
![2017-06-05 10-28-36](https://cloud.githubusercontent.com/assets/170528/26767319/c42cc736-49d9-11e7-8338-2583074ec1bf.png)

**Comment by pingpongworks** [comment]
확인했습니다. 감사합니다~
