### ISSUE TITLE
방문예약 사진촬영 항목 수정

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1241]
방문예약할 때 대여목적 선택 항목 중

**## 사진촬영 (웨딩촬영) ==> 사진촬영** 

으로 수정해주세요. 

대여자가 웨딩사진 촬영으로 오는 경우는 거의 없는데

증명사진, 졸업사진 등 사진촬영 때문에 오시는 분들이 

가끔 문의를 하십니다~

**Comment by 10001if** [comment]
@aanoaa 단순한 이슈로 보입니다. 시간 되실 때 바로 수정 요청드립니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
