### ISSUE TITLE
새로운 방문예약 레이아웃 및 마크업

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#1243]
#1239 를 진행하는데 있어서,
footer 를 집어 넣으면 레이아웃이 이상하게 나옵니다.

방문예약 화면은 오랜된 ace-theme 를 사용하고 있는데 몇가지 불만이 있습니다.

- bootstrap2 를 사용중
- font-awesome 도 오래되었음
- ace-theme 의존성이 있는데 layout 이라던지 css 사용하려면 ace-theme 의 문서를 봐야함

이번 기회에 방문예약 페이지를 새롭게 구성하고자 합니다.
유지보수가 편리해지게 됩니다.

- renderer 를 haml -> ep 로 변경
- bootstrap2 -> bootstrap3
- ace-theme 의존성을 제거

---------------------

지금과 디자인이나 레이아웃은 되도록 똑같이 보이도록 하겠습니다.

**Comment by aanoaa** [comment]
`notlogin` layout 을 사용하는 화면은 3개 입니다.

- login
- booking/visit
- booking/visit2

레이아웃이 바뀐 것에 영향이 없어야 하겠습니다.

**Comment by aanoaa** [comment]
`templates/layouts/default/body-js.html.ep` 에서 bootstrap2 를 사용합니다.

    <script src="/lib/bootstrap/js/bootstrap.min.js"></script>

이것은 모든 페이지에 적용되어 있습니다.
visit 만 따로 사용하도록 나누면 되지만, ace-theme 와 bootstrap3 를 함께 업그레이드 할 수도 있습니다.

충분히 테스트해서 마이그레이션 후에 서비스에 지장 없도록 하면 될 것 같습니다.
물론 실시간으로 모니터링 하면서 rollback 준비도 하고요.

**Comment by aanoaa** [comment]
https://github.com/opencloset/opencloset/issues/176 에서 진행했던 흔적이 보입니다.

**Comment by aanoaa** [comment]
> bootstrap2 를 사용중

아닙니다 bootstrap3 를 사용중입니다.
하지만 bootstrap 3.3 이상을 사용하고자 합니다.

**Comment by aanoaa** [comment]
https://wrapbootstrap.com/theme/ace-responsive-admin-template-WB0B30DGR

> This item is no longer available

**Comment by aanoaa** [comment]
방문예약 화면에 footer 를 넣으려고 한건데,
테마를 업그레이드 하려고 하면 작업 볼륨이 너무 커집니다.

더이상 지원하지도 않는 듯 하여, 현재 테마를 bower pkg 로 사용할 수 있을지 여부도 불투명 합니다.

**Comment by aanoaa** [comment]
테마의 업그레이드는 하지 않고

- public/lib 의 정적파일을 대체할 수 있는 bower pkg 를 사용
- bootstrap3 -> bootstrap 3.x(최신버전) 의 적용

해보겠습니다.

**Comment by keedi** [comment]
지금 서울시와 연동 관련해서 이슈가 있는데 관련해 해결될 때까지 조금 딜레이시켜야 할 것 같습니다.

**Comment by aanoaa** [comment]
- select2

는 하위버전과의 호환성문제로 대체할 수 없었습니다.

- bootstrap-tag
- bootbox
- prettify

는 사용되지 않는 것 같지만 혹시 몰라서 그냥 두었습니다.

**Comment by aanoaa** [comment]
- jquery
- bootstrap
- underscore
- bootstrap-datepicker
- chosen
- facebox
- bootbox

`public/lib` 에서 사용되던 정적파일들을 bower pkg 로 대체 하였습니다.

- fontawesome

은 대체할 수 없어서 기존버전과 더불어 추가했습니다.
