### ISSUE TITLE
서울시청 일자리정책에 신규 예약 시스템과 연동

### ISSUE THREAD

**Issue by keedi** [opencloset/opencloset#1244]
어제 열린옷장을 통해 전달 받은 내용입니다.

> 보낸사람:   10001if
> 받는사람:   staff@silex
> 참조:   김소령
> 날짜:   2017년 5월 15일 오후 8:05
> 제목:   아이넷피아에서 제작한 통합 예약 사이트
> 
> 안녕하세요. 아이넷피아입니다.
> 통합예약 사이트 제작일정은 잘 진행중에 있으며 목요일까지 내부 디자인~개발 마무리,
> 금요일에 sms문자서비스 연동, 데이터 이전하여 5/19-22일 사이 오픈 예정입니다.
> 
> http://.../sub3/3_1.php
> 
> 통합예약 페이지 구성형식입니다.
> 김광훈 주무관님과 논의하여 맞춰둔 내용이니 경로확인하시어 이렇게 예약을 받을시
> 업체별로 문제의 소지가 있을경우 말씀 전달 바랍니다.
> 
> 업체별 소개 내용은 아래와 같이 들어가면 좋겠는데 업체별로 보내주신 내용이 저마다 틀립니다.
> 보내주신대로만 올려드리면 될지, 소개페이지가 업체로써는 가장 중요한 부분인데 보강할 내용이
> 있다면 내일까지 보내주시는 내용을 최종으로 반영처리해드리겠습니다.
> 
> 1 업체 소개 및 특장점 내용
> 2 서비스 내용(대여규정/예약안내 등)
> 3 업체 사진
> 4 오시는길(약도)
> 
> 주무관님께서는 서비스 소개, 대여절차, 대여규정에 대한 내용을 수요일까지 보내주셔야 합니다.
> 
> 모든 분들의 협조에 감사를 드립니다.

**Comment by keedi** [comment]
연동 관련해 전혀 협의가 되어있지 않은 터라 재문의를 요청드렸습니다.

> 보낸사람:   Keedi Kim
> 받는사람:   10001if
> 참조:
>     staff@silex
>     김소령
> 날짜:   2017년 5월 16일 오전 11:15
> 제목:   Re: 아이넷피아에서 제작한 통합 예약 사이트
> 
> 복붙하기 좋게 어미를 수정했습니다.;;;
> 
> - 이용약관 및 개인정보 이용안내 동의 역시 대여 예약하기 화면에서 마무리해야 합니다.
> - 이용약관 및 개인정보 이용안내 동의 내용은 수정될 수 있으므로 REST API로 제공할테니 확인해서 열람해야 합니다.
> - 대여일, 대여시간은 실시간으로 변화되는 상황이며, 단순히 1시간 단위가 아니므로 실시간으로 반영해서 보여주어야 합니다. 관련해 REST API를 제공할테니 확인해서 반영해야 합니다.
> - 개인정보를 미리 입력하는데, 입력한 내용을 어떻게 열린옷장 서버 측으로 전달할 것인지 관련 프로토콜을 명확하게 설명해주세요.
> - 대여방법 택배의 경우는 해당 업체에서 1회 대여 이후 대여인 경우만 선택이 가능해야 하는데, 관련해 어떻게 프로토콜을 어떻게 할 것인지 설명해주세요.
> 
> > 다음 항목 요청 및 문의드리면 될 것 같습니다.
> > 
> > - 이용약관 및 개인정보 이용안내 동의 역시 대여 예약하기 화면에서 마무리되어야 한다.
> > - 이용약관 및 개인정보 이용안내 동의 내용은 수정될 수 있으므로 REST API로 제공할테니 확인해서 열람되도록 해달라.
> > - 대여일, 대여시간은 실시간으로 변화되는 상황이며, 단순히 1시간 단위가 아니므로 실시간으로 반영해서 보여주어야 함. REST API를 제공할테니 확인해서 반영해달라.
> > - 개인정보를 미리 입력하는데, 입력한 내용을 어떻게 열린옷장 서버 측으로 전달할 것인지 관련 프로토콜을 명확하게 설명해달라.
> > - 대여방법 택배의 경우는 해당 업체에서 1회 대여 이후 대여인 경우만 선택이 가능해야 하는데, 관련해 어떻게 프로토콜을 어떻게 할 것인지 설명해달라.
> > 
> > 이상입니다.

**Comment by keedi** [comment]
이후 관련해서 열린옷장에서 연동 관련 문의를 했는데 22일이 마감인지라
일정 관계상 힘들 것 같다고 연락이 왔다고 합니다.
더불어 다음과 메시지를 아이넷피아의 기획부장으로부터 받고 다시 전달 받았습니다.

> 안녕하십니까. 아이넷피아 박기련 부장입니다.
>
> 연동 관련해서는 저희 사무실 02-2692-9072 로 연락주셔서 개발담당 이선용 팀장을
> 찾아주시면 됩니다.  현재 저희 개발 일정이 빠듯하여 한시간, 한시간이 저희로써는
> 소중한 상황이오니 되도록 담당자 연락주실때 핵심적인 사항만 빠르게 전달해주실수
> 있다면 감사하겠습니다.
>
> (1.효율적 연동방식협의, 2.가능여부 판단 및 일정협의)

**Comment by keedi** [comment]
전화 통화 전 보낸 답신은 다음과 같습니다.

> 보낸사람:   Keedi Kim <keedi.k@gmail.com>
> 받는사람:   박기련 <design1@inetpia.net>
> 참조:
>     이선용
>     김광훈
>     인포 열린옷장
>     staff@silex.kr
> 날짜:   2017년 5월 17일 오후 12:19
> 
> 안녕하세요. SILEX 김도형입니다.
> 
> 우선 일련의 상황에 대해서 유감인 점은 다음과 같습니다.
> 
> ----
> 
> 1.
> 지난 회의에서 분명히 열린옷장은 30분 단위로 예약을 받고 있으며,
> 인원수 제한은 실시간으로 변경되고 있음을 알려드렸고,
> 관련해서 규약을 정해 서로 통신해야 함을 설명드렸으며,
> 새로 만들게 시스템에 맞게 각 업체의 시스템도 변화가 필요하다고 말씀드렸으며,
> 문제없다고 하셨는데, 시간이 빠듯해 곤란함을 말씀하시니 당황스럽습니다.
> 
> 2.
> 더불어 참여하는 세 업체와 충분한 협의를 거치셨는지요?
> 일정 동안 화면 피드백을 받은 것은 이번이 처음이며,
> 그전에는 어떠한 관련해 열린옷장과 연동하기 위해 필요한 부분에
> 대한 문의도 없었으며, 협의 과정도 없었습니다.
> 나머지 두 업체와도 협의를 하시지 않으신 것인지, 아니면 열린옷장만
> 협의를 하지 않으신 것인지는 모르겠으나 어느 쪽이든 유감입니다.
> 
> 3.
> 1차 개발과 2차 개발로 나눈다고 하셨고, 1차 개발에서는 가장 기본적인
> 것을 우선으로 진행하시려 하셨다고 어제 전해들었습니다. 그 1차 개발의
> 기본 기능에는 당연히 예약이니, 참여 업체의 예약 과정이 반영되는 것은
> 새삼스러운 일이 아닙니다. 이미 파악도 끝났다고 하셨었고, 그 과정과
> 관련해 협의를 진행한적도 없이 당연한듯이 참여업체 중 한 업체의 시스템과
> 연동할 기술적인 고려를 하지 않은 상태입니다.  심지어 쿠폰 번호등 관련해
> 어떤 자료를 참여 업체 측에 전달해주는지도 전달 받은 내용도 전혀 없습니다.
> 오히려 어제에서야 화면을 보고 저희가 역으로 제안을 해야 하는 상황은 몹시
> 유감입니다.
> 
> ----
> 
> 핵심적인 사항만 빠르게 전달하면서, 협의를 진행하는 것은 불가능해보여,
> 귀사 개발팀의 시간을 낭비하지 않기 위해 명확히 메일로 전달드립니다.
> 
> 요구사항은 다음과 같습니다.
> 
> ----
> 
> 1.
> 예약 가능 시각은 실시간으로 계속 변경되므로, 이를 반영해야 합니다.  실시간으로
> 변경을 해줄 수 없다면 최소 해당 페이지를 렌더링하는 시점에라도 가장 최신 정보를
> 보여주어야 합니다.
> 
> 2.
> 예약 요청을 보낼 때 해당 요청은 그 짧은 시간 사이에 다른 예약자가 먼저 예약할
> 수 있기 때문에 예약에 실패할 수 있습니다.  따라서 최종 완료 버튼을 클릭하는
> 시점에 예약 요청을 보내고, 예약 실패여부를 확인한 다음 새로 예약 가능한 시각을
> 보여주고 예약을 진행할지 여부를 판단해야 합니다.
> 
> 3.
> 열린옷장은 현재 30분 단위로 예약을 받고 있습니다. 하지만 이것은 현재 그렇다는
> 것이지 20분 단위등 시간은 언제든지 바뀔 수 있습니다. 1.에서 언급한 것처럼 이
> 값은 요청해서 취득해야 합니다.
> 
> 4.
> 예약 과정 이후 참여 업체 측에 전달하는 정보 및 규약을 명확하게 명시바랍니다.
> 관련해서 예약 시스템에 변화가 있는 것은 당연합니다. 하지만 이를 공시하지
> 않으면, 시스템을 연동하는 것은 불가능하겠지요.
> 
> 5.
> 4. 항목과 연관이 있지만, 어떤 방식(쿠폰일지 기타 다른 방법일지...)을 사용하는지
> 명시해주시고, 관련해 전달하는 값을 기반으로 역으로 해당 값이 유효한지를 검증하고,
> 연관 정보를 취득할 수 있는 REST API를 제공바랍니다.
> 
> 6.
> 정보의 암호화 여부와 암호화를 한다면 암호화 방식을 명시바랍니다.
> 
> 7.
> 원격 요청의 규격과 요청시 인증 및 접근제한 방식을 명시바랍니다.
> 
> ----
> 
> 이상입니다.
> 
> 더불어 열린옷장이 제공해야 할 API는 결정되면 24시간 내로 제공토록 하겠습니다.
> 
> 고맙습니다.

**Comment by keedi** [comment]
이후 점심시간이 끼어 있어서 13시 30분에 아이넷피아의 이선용 팀장과 통화를 진행했습니다. 확인한 내용은 다음과 같습니다.

- 관련해서 1차 개발 범위는 이야기가 끝난 줄 알았다.
- 2차 개발에 추가 개발이 들어가나 일정 등은 아는바가 없다.
- 22일 1차 개발까지 요청한 사항은 진행하기 힘들다.
- 예약 관련해서는 예약 번호라는 개념을 사용한다. 이 값은 시스템 상에서 유일(unique)하다.

현재 열린옷장은 예약 인원이 많고, 그동안 자동화 작업을 진행해서 시스템으로 운영되고 있기 때문에 연동하지 않고 수작업으로 일일이 좌우 시스템을 왔다갔다하면서 처리하는 것은 현실적으로 불가능하며, 직원들과, 예약자들의 불만이 터져나올 것으로 예측됩니다. 해당업체에서 난색을 표하니 어쩔 수 없이 대안을 역제시했습니다.

- 열린옷장 선택시 예약일과 시간은 고르지 않도록 해달라.
- 예약 확인 버튼을 클릭하면 열린옷장에서 제공할 링크로 이동하게 해달라. 이후는 열린옷장이 처리하겠다.
- 이 때 예약 번호를 같이 넘겨달라.
- 업체에서는 예약번호로 우리가 요청할 경우 해당 예약 정보를 반환하는 API를 제공해달라.
- 업체에서는 예약번호로 예약일 및 시간을 갱신할 수 있는 API를 제공해달라.
- 업체에서는 API 이용시 사용할 인증 및 암호화 방식을 결정해달라.

여기까지는 동의를 얻어냈으며, 더불어 택배건이 있기 때문에 실제로 고려해야 할 부분은 더 있습니다. 관련해서는 우리측에서 확인할 부분은 확인한 다음 요구사항을 요청하기로 했습니다.

**Comment by keedi** [comment]
연동과 관련해서 몇가지 내용을 메일로 주고 받았었습니다. 다만 관련해서 공개적인 암호화 방식과 설정으로 처리할 수 있는 키 값의 조합이 아닌 업체측의 자체적인 방식을 사용하는 관계로 주고받은 메일의 내용이나 엔드포인트 주소와 관련한 부분을 본 이슈에 기록하는 것이 적절하지 않다고 판단되어 붙이지는 않습니다. 대신 관련 모든 메일은 전체 메일로 전달드렸습니다.

**Comment by keedi** [comment]
앞서 말한 이슈와 연관되어 서울시 요청을 받는 사이트는 깃헙 저장소를 사용하지 못하고 내부의 비공개 저장소를 이용했습니다. 기술적인 이슈와 보안과 관련된 이슈가 해결되어 공개하는데 문제가 없다고 판단되면 검토 후 깃헙 저장소로 이전하면 될 것 같습니다.

관련해 사용하는 이름 공간은 OpenCloset::Coupon::Web 입니다.

**Comment by keedi** [comment]
더불어 기존 서울시 요청을 처리하는 부분은 모두 막았습니다.

정확히 취업 날개 관련된 통계를 보여주는 페이지는 비공개로 열린옷장 내부에서만 접근 가능하도록 했습니다.

또한 서울시 취업날개 예약을 받는 페이지의 경우 사이트 개편으로 더이상 기존 방법으로 예약이 불가능함을 명시했습니다.

![screenshot-visit theopencloset net-2017-05-22-00-03-22](https://cloud.githubusercontent.com/assets/138451/26285080/19eef1ec-3e83-11e7-8384-32127d2124a8.png)

**Comment by keedi** [comment]
상기 처리는 정확하게 2017년 5월 22일 00시에 수행했습니다. @10001if 님과 토요일 이야기를 나누었던 결과 정확히는 서울시에서 가이드라인이 왔었어야 할 것 같은데 관련해서 아무런 언급이 없었다고 합니다. 공식적으로 22일에 오픈한다고 하고 지난번 그러면 언제까지 유지하는 것인지 물었을때 22일 전까지라고 대답을 들었었기 때문에 21일 23시 59분 59초가 지난 다음 관련 요청을 모두 막았습니다. 그 사이에 발급을 받은 사용자는 정상적으로 쿠폰을 사용할 수 있으나 이후는 서울시 정책에 따라 사용이 가능할 것 입니다.

**Comment by keedi** [comment]
이제 2017년 5월 22일 기점으로 더이상 열린옷장에서는 몇명이 쿠폰을 사용했는지, 몇번을 사용했는지, 부정발급은 없었는지는 고려하지 않아도 됩니다. 관련해 모든 처리는 서울시가 제작하는 예약 통합 포탈의 소관입니다.

**Comment by keedi** [comment]
오픈 첫날인 만큼 관련해 요청 이슈가 있을 수 있는 관계로 staff와 visit 모두 해당 가지에서 운영되도록 했습니다. 월요일이나 화요일까지 하루 이틀 정도 결과를 확인한 다음 수정할 부분이 있으면 수정하고, 이후 머지 후 릴리스 및 배포를 수행하겠습니다.

**Comment by keedi** [comment]
관련해서 서울시 연관 업체(아이넷피아)의 api 서버 이슈로 꽤 많은 오류가 발생하고 있습니다. 관련해서 시시비비를 쉽게 가리기 위해 오류 메시지를 더 자세하게 표현하고, 더불어 연락처도 같이 명시합니다. 정확히는 coupon 저장소에 기록해야 하지만, 해당 저장소는 연관업체의 기술적 사정으로 비공개로 작업중이라 여기 남깁니다.

![screenshot-coupon theopencloset net-2017-05-25-13-24-13](https://cloud.githubusercontent.com/assets/138451/26435962/e8273a02-414d-11e7-9129-191a748a0f01.png)

**Comment by keedi** [comment]
캡쳐를 해서 문의를 남길 수 있도록 유도합니다.

![screenshot-coupon theopencloset net-2017-05-25-13-34-14](https://cloud.githubusercontent.com/assets/138451/26436099/01d71d18-414f-11e7-899e-7cb302691ad2.png)

**Comment by keedi** [comment]
대부분 서울시 쪽 이슈긴 했지만 어쨌든 생각보다 오류 이슈가 많아 아직 머지를 진행하지 않았습니다. 여전히 고려하지 못한 경우 및 완벽하게 설계된 구조가 아니라 다양한 이슈가 있다고 예상되지만 목요일 오늘을 기점으로 치명적인 문제가 없다면 머지 진행 후 이슈 닫겠습니다.

**Comment by keedi** [comment]
가지 병합 및 릴리스, 실서버 배포 완료했습니다. 이슈 닫습니다.

이후 관련 이슈는 별도의 이슈를 열어서 처리합니다.

**Comment by 10001if** [comment]
급하게 오픈하느라 너무 고생하셨을 것 같네요. 추가로 이슈가 생기면 별도의 이슈를 만들어 남기도록 하겠습니다. 감사합니다.
