### ISSUE TITLE
신체치수 오류 - 확인요망

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1245]
~/user/63484
163/70
허벅지 둘레 93

~/user/63375 
165/54
허벅지둘레103

**Comment by keedi** [comment]
보안 측면의 연유로 url을 수정했습니다.

**Comment by pingpongworks** [comment]
아, 보안 문제 있을수 있겠네요. 
다음부턴 주문서번호만 기록하도록 하겠습니다. 

김소령
OpenCloset / story tailor
010. 5278. 2844
pingpong@theopencloset.net

2017. 5. 21. 오후 8:59 Keedi Kim <notifications@github.com> 작성:

**Comment by 10001if** [comment]
본 이슈는 @yongbin과 확인하여 차후에 수정하도록 하겠습니다.
