### ISSUE TITLE
대여 예약 가능인원 조정

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1247]
![image](https://cloud.githubusercontent.com/assets/17288038/26385749/c43c3cd6-407c-11e7-9fc3-7f425aaaf703.png)

10: 00~5:00  남자 5명 / 여자 5명
5:30              남자 2명 / 여자 2명

예약활성화 예약가능인원 수정부탁드립니다~

**Comment by aanoaa** [comment]
default 예약가능인원 수 를 조절해달라는 말씀이시죠?

before

| time | male | female |
| ---- | ---- |------- |
| 10:00 | 5 | 4 |
| 10:30 | 4 | 5 |
| 11:00 | 5 | 4 |
| 11:30 | 4 | 5 |
| 14:00 | 5 | 4 |
| 14:30 | 4 | 5 |
| 15:00 | 5 | 4 |
| 15:30 | 4 | 5 |
| 16:00 | 5 | 4 |
| 16:30 | 4 | 5 |
| 17:00 | 5 | 4 |
| 17:30 | 2 | 2 |

--------------------

after

| time | male | female |
| ---- | ---- |------- |
| 10:00 | 5 | 5 |
| 10:30 | 5 | 5 |
| 11:00 | 5 | 5 |
| 11:30 | 5 | 5 |
| 15:00 | 5 | 5 |
| 15:30 | 5 | 5 |
| 15:00 | 5 | 5 |
| 15:30 | 5 | 5 |
| 16:00 | 5 | 5 |
| 16:30 | 5 | 5 |
| 17:00 | 5 | 5 |
| 17:30 | 2 | 2 |

**Comment by aanoaa** [comment]
적용하였습니다.
테스트는 하지 않았습니다.
문제가 발견되면 말씀해주세요.

**Comment by pingpongworks** [comment]
네네~
감사합니다^^

2017. 6. 1. 오후 1:00 Hyungsuk Hong <notifications@github.com> 작성:

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
