### ISSUE TITLE
취업날개 2017-2 통계 페이지가 보이지 않음 

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1248]
5/22일 부터 시작된 취업날개의 통계 페이지가 보이지 않습니다. 통계를 확인 할 수 있도록 요청드립니다.

**Comment by keedi** [comment]
진행합니다.

**Comment by 10001if** [comment]
종전에는 취업날개에 온라인이 없어서 오프라인 인원만 보여주면 되었는데, 이제 온라인이 추가되어서 오프라인 온라인이 구분되어서 보여져야 할 필요가 있을 것 같습니다. 우선 당장 급한 이슈는 아니므로 기본적으로 해야할 작업 완료되시면 다시 말씀드리도록 하겠습니다.

**Comment by aanoaa** [comment]
의도한건 아니겠지만,
`seoul-2017` 로 수집하고 있는 통계가 `seoul-2017-2` 도 함께 수집하고 있습니다.
설명하면 통계 수집을 위한 검색조건이 `seoul-2017%` 입니다.

**Comment by aanoaa** [comment]
https://staff.theopencloset.net/stat/events/seoul-2017

위 페이지가 `seoul-2017` 과 `seoul-2017-2` 를 모두 합한 수치입니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
