### ISSUE TITLE
시간표 상에서 2017-2로 보이는 이름을 취업날개로 변경하고자 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1249]
현재 2017-2로 보여지는 이름을 취업날개로 변경하고자 합니다.

만약 이전 취업날개와 중복되면 안되는 이슈가 있다면 취업날개2와 같은 이름이어도 무관합니다.

**Comment by keedi** [comment]
진행합니다.

**Comment by 10001if** [comment]
감사합니다~!
