### ISSUE TITLE
취업날개 이용횟수를 늘이고 대여기간을 연장하는 방법

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1250]
종전에는 취업날개로 대여를 할 때 연장을 하는 경우에는 연장비가 발생하기 때문에 이용자 본인이 연장료를 부담하고 대여를 진행했습니다. 하지만 시에서 종전의 방식에서 변경된 방법을 이용하도록 하였습니다.

1회 대여시 4일까지 대여가 가능하므로 4일 이내의 기간으로 연장을 원하는 경우 1회 더 예약을 하여 연장비 없이 이용하도록 한 것입니다. 8일을 이용하고자 한다면 2회 더 대여를 하도록 한 것인데, 여기서 대여기간의 제한은 없고 이용기간의 제한만 존재합니다. 따라서 최초로 대여를 하는 대여자가 10회를 모두 이용하여 장기로 대여를 하고자 할 경우 최대 40일까지 대여가 가능합니다. 다만 이 경우에는 최초 예약분인 1회를 제외하고 나머지 9회분을 추가로 예약해야 합니다.

이 경우 최초 대여분은 대여확정을 누른 뒤 반납을 합니다. 그리고 마지막으로 예약한 주문서에서 최초 대여했던 품목과 동일한 의류코드를 다시 입력하고 대여일을 변경하여 대여를 진행하는 형식으로 연장 정책을 흡수하려고 합니다.

그런데 기존 주문서에 있던 의류들의 경우에는 모두 포장이 되어 있는 상태이기 때문에 다시 열어 바코드 스캐닝 과정을 거치기 힘들어 그냥 주문서의 의류 코드들을 복사하여 마지막 주문서 코드란에 입력하고 있습니다. 성수기에 이런 작업을 진행하기 때문에 결제과정이 크게 지체되고 있습니다.

따라서 마지막 주문서에서 이전 주문서의 의류 품목들을 한번에 가져 올 수 있는 기능이 필요합니다.

**Comment by 10001if** [comment]
@keedi 형석님이 출근하셔서 담당자를 변경했습니다. ^^

**Comment by 10001if** [comment]
@aanoaa 이런 기능은 정상적인 방법이 아닌 것 같은데요.. 이슈 보시고 의견 주시면 다시 설명해드리도록 하겠습니다.

**Comment by aanoaa** [comment]
취업날개 10회분을 한번에 사용한다고 가정해보겠습니다.

대여자는 하나의 취업날개 이용권으로 예약을 했습니다.(왜냐면 지금 1회분씩으로만 이용권이 발급되기때문)
10회분을 한번에 사용할 수 있다고 해도 취업날개 서비스에 이 사용자는 10회분을 사용했다고 알려줄 수 있는 방법이 없습니다.

우리쪽은 간단합니다.
39박 40일 대여할 수 있도록 하고 대여일을 4일로 나눠서 n회분을 사용했다고 알려주면 됩니다.

다른 방법으로는 취업날개 서비스에서 10회분 이용권을 발급하는 방법도 있습니다.
이런방식이라면 우리는 10회분 이용권이니까 대여기간을 늘려주면 됩니다.

우리가 고민해야할 건 아닙니다.
저쪽에서 고민해서 이렇게 이용해달라고 얘기하면 맞추면 됩니다.

방법이 있지도 않은데 취업날개 이용권을 10회분 사용해서 40일 대여하고 싶다는 사람이 있으면,
"아직은 그렇게 사용할 수 없다" 라고 얘기하면 되지 않나요?

--------------------

그리고 주문서를 9개 복사하는 것보다 대여기간을 39박 40일로 설정하는 방법이 훨씬 간단합니다.

**Comment by 10001if** [comment]
@aanoaa 예약과 관련해서는 10번 예약 후 주문서를 여러번 만드는 행위가 바림직하지 않다는 점에 대해서는 저도 동의합니다. 가능하면 39박 40일을 대여할 수 있도록 하고 대여일을 4일로 나눠서 n회분을 사용했다고 알려주는 방법으로 진행하면 문제가 없어 보입니다. 

그런데 이 경우 우리 쪽에서 진행한 작업이 취업나개 통계페이지에 등록될 수 있는가가 궁금합니다. 저쪽에서 고민해서 이용해 달라고 얘기해서 맞추는 결과를 이끌어 내려면 구체적으로 어떻게 해야할지 모르겠습니다. 의견 주시면 필요한 내용을 전달하도록 하겠습니다.

**Comment by aanoaa** [comment]
지금 취업날개 이용자는 1회 이용권으로 밖에 쓸 수 없습니다.
이용횟수를 늘이는 만큼 대여기간을 늘릴 수 있는 방법이 없습니다.

취업날개 서비스가 이런 점을 고민하지 않고 있는데,
왜 나서서 이런게 하는게 어떻겠냐 저렇게 하는게 어떻겠냐 하나요?

그렇게 하고 싶으신 건가요?

**Comment by 10001if** [comment]
@aanoaa 네. 제 생각은 이렇습니다. 
현재 대여일 연장으로 횟수를 계산하는 방식은 존재하지 않고 여러번 예약하는 방식으로만 연장 결제가 가능합니다.
그래서 우리가 할 수 있는 방법은 취업날개 다시 예약을 요청하여 주문서를 새로 생성하는 방법 밖에는 없습니다.
현재 이 상황에서 할 수 있는 방법이 주문서를 복사하는 방법이었습니다.

그런데 대여일 연장을 통해 할 수 있는 방법이 있다면 가장 이상적일 것 같습니다. 그런 방법을 요청하려면 아이넷**와 소통이 되어야 할텐데 어떻게 요청해야할지 모르겠습니다. 이런 이슈가 있는 경우 이런 방법으로 해결하는 것보다 역으로 요청하여 해결하는 것이 타당하거나 수월하다고 판단되어진다면 의견을 주셔요~ 

문제를 해결하는 게 저의 가장 큰 이슈입니다~

**Comment by aanoaa** [comment]
email 을 받았는데, `신청횟수 추가` 버튼을 넣는다고 합니다.
저희는 대여기간을 가지고 몇회 이용권을 사용했는지 계산해서 이용권을 사용한 횟수만큼 버튼을 눌러주는 효과를 내면 되겠습니다.

**Comment by aanoaa** [comment]
[면접정장 무료대여 예약서비스 2차 추가개발_스토리보드_v1.pptx](https://github.com/opencloset/opencloset/files/1107113/2._._v1.pptx)

**Comment by 10001if** [comment]
@aanoaa 주문서를 복사하는 기능은 필요가 없겠네요. :)

**Comment by aanoaa** [comment]
#1294 #1295 에서 해결되었습니다.
