### ISSUE TITLE
발 크기 --> 대여한 구두사이즈로

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1251]
대여자가 방문하여 신체치수를 잴 때 
사용자정보 신체치수에 발크기를 입력합니다. 
그런데, 실제로 대여하는 구두사이즈가 다른 경우가 종종 있습니다. 

사용자정보 신체치수 발크기가 
실제 대여한 구두사이즈로 변경될 수 있을까요?

**Comment by aanoaa** [comment]
질문이 있습니다. @pingpongworks

- 치수측정을 할때에 발 크기가 아닌 구두사이즈를 입력하면 되지 않나요?
- `사용자의 발 크기` 와 `주문서의 발 크기` 를 다르게 사용하고 계신건가요?
- `주문서의 발 크기` 와 `사용자의 발 크기` 가 다르다면 `사용자의 발 크기` 를 `주문서의 발 크기` 로 변경해달라는 말씀이신가요?

**Comment by pingpongworks** [comment]
치수입력할 때 발크기는 실제로는 구두사이즈를 물어보아서 입력합니다. 

근데 실제로 대여자가 구두를 신어보면 본인이 알고 있는 사이즈와 다른 경우가 꽤 있습니다. 

그래서 대여확정이 된 후, 주문서에 기록된 실제 대여한 구두사이즈로 신체치수의 발크기가 대체되면 좋겠다고 생각한 것입니다. 

그러면 다음에 재대여할 때 오차가 더욱 없을거 같습니다. 

2017. 6. 1. 오후 12:51 Hyungsuk Hong <notifications@github.com> 작성:

**Comment by aanoaa** [comment]
(구두를 대여한다면) 구두 사이즈를 확인해서 사용자 정보의 발 크기를 변경해주는 기능을 원하는 것 같습니다.

주문서의 상태가 구두 정보를 알아낼 수 있는 `포장완료`, `결제대기`, `대여중` 으로 변경될때에 가능합니다.

다만, `포장완료` 로 변경하는 것은 구두 사이즈와는 상관이 없는 행동인데 사용자 정보의 구두사이즈가 변경되는 기능이므로,
'A 를 했더니 B 가 되었어요' 같은 상황인 것 같습니다.

모니터를 닦았더니 컴퓨터가 빨라졌어요.

**Comment by aanoaa** [comment]
사용자정보의 구두사이즈와 실제 구두사이즈가 다름을 staff 가 인지 했을때에,
사용자정보에서 구두사이즈를 변경해주는 방법도 있습니다.

제 생각에는 번거롭지만 이게 더 옳은 방법 같습니다.

**Comment by aanoaa** [comment]
> 다름을 staff 가 인지 했을때에,

현실적으로 이때에 변경하는데 어려움이 있다고 합니다.
자동으로 변경되는게 가장 좋은 방법입니다.

**Comment by aanoaa** [comment]
주문서가 포장완료로 변경될때, 사용자의 구두 사이즈를 주문서의 구두 사이즈로 변경합니다(다를경우)

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
