### ISSUE TITLE
예약 취소 오류

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1253]
**주문서 62422 / 53058**

대여자가 2017년 5월 31일 14:00로 예약했다가
직접 문자의 링크로 예약 취소 했는데, 
예약 취소가 안되는 오류가 있었던 경우입니다. 
원인이 무엇인지 확인부탁드립니다.

**Comment by 10001if** [comment]
주문서번호 2개중 1개는 정상적으로 반납이 이뤄진 건입니다. 하지만 62422는 예약이 실제로 취소되지 않은 것인지 확인이 필요합니다. 실제로 예약자가 취소를 실시했지만 취소가 되지 않은 경우에 옷장지기는 예약취소실패 문제를 파악하지 못하고 있을 수도 있습니다.

**Comment by 10001if** [comment]
다음에 같은 문제가 다시 발생하면 이슈를 열도록 하겠습니다. 우선 이슈 닫겠습니다.
