### ISSUE TITLE
서비스장애

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#1255]
2017-06-01 10:30 분 쯤에 서비스가 느리다는 연락이 있었습니다.
접속해서 확인해보니 load avg 가 계속오르고 있었고 140을 넘기기도 했습니다.

@yongbin 님에게 연락해서 재부팅을 시도하였습니다.

**Comment by aanoaa** [comment]
왜 이런일이 발생했는지에 대한 원인을 파악해서 조치해야 합니다.

**Comment by aanoaa** [comment]
재부팅 이후에 https://share.theopencloset.net/ 접속하면 `Page not found` 가 표시됩니다.

**Comment by aanoaa** [comment]
> 재부팅 이후에 https://share.theopencloset.net/ 접속하면 Page not found 가 표시됩니다.

서비스 재시작해서 해결하였습니다.

**Comment by aanoaa** [comment]
> orepan2-indexer 가 top 의 최우선으로 보이고 있으니까 일단 cron 에서 막아놓도록 하겠습니다

orepan2-indexer 를 주기적으로 돌릴 것이 아니라, 모듈이 upload 되고 나면 한번씩 실행하는 방법으로 대체할 수 있는지 알아봐야 합니다.

지금은 막혀있습니다.
모듈이 업로드 되고 하면 한번씩 직접 실행해야 하겠습니다.

**Comment by yongbin** [comment]
최근 하루 CPU 모니터링과 장애시점 CPU 모니터링 결과입니다. 

![cpu-pinpoint 1496187002 1496295002](https://cloud.githubusercontent.com/assets/52704/26666429/d8d6bc84-46da-11e7-950c-5a980755baa2.png)

![cpu-pinpoint 1496264492 1496288792](https://cloud.githubusercontent.com/assets/52704/26666452/f6c9149e-46da-11e7-85c1-2deca915db70.png)

그리고 최근 일주일 CPU 모니터링결과 입니다. 

![cpu-pinpoint 1496264492 1496288792](https://cloud.githubusercontent.com/assets/52704/26666477/1112ad9c-46db-11e7-9789-405404262e49.png)

제가 볼떄 특이점은 다음과 같습니다.

1. 오늘 오전 10시 CPU 사용이 소폭상승이후에 급격하게 iowait (CPU가 디스크를 대기하는 시간)이 늘어나고 점점 가중되다가 결국 장비를 컨트롤 할 수 없는 상태가되어 하드리셋했다고 볼수 있습니다. 
2. 장비 재기동 이후에도 일정양의 iowait 이 존재했지만 현재는 전혀 없는 정상적인 수준입니다.
3. 주간 그래프를 볼때 금주 화요일 낮시간부터 OS가 고정적으로 CPU를 사용하는 작업이 있는것으로 보입니다. 이 작업이 장애와 직접적인 연관이 있는지는 알 수 없지만 의도한것이 아니라면 이 작업에 대해서도 확인이 필요해보입니다.

종합하면 

오전 10시 cron을 통해서든, 사용자 요청에 의해서든 디스크 사용을 많이 유발하는 프로세스가 발생되고 그 프로세스때문에 CPU 응답시간이 늦어져서 발생한 장애입니다. 평시 서버 상태나 재기동이후 상태를 고려할때 프로세스가 원인이라고 보기어렵고 오히려 terra 에서 사용한는 LVM 디스크의 일정영역(디스크)의 상태에 문제떄문에 발생했다고 추정하는게 더 자연스러워 보입니다. 직접적인 원인은 디스크이지만 별개로 화요일부터 추가된 프로세스의 원인은 별도 확인이 필요합니다.

대책

테라에 LVM으로 구성되어있는 디스크들중 일부 디스크가 smarted를 통해 경고를 보내고 있는 디스크가 있는데 처음 배치했을때부터 있던 현상이기때문에 무시하고 있었습니다. 테라 서버의 안전성이 중요해진 만큼 장착되어있는 ssd, non ssd 디스크 전수의 컨디션을 확인하고 교체가 필요한 디스크는 교체하는 작업을 일정을 잡아서 진행하겠습니다.

**Comment by yongbin** [comment]
현재 LVM 구성은 아래와 같습니다.

```
  PV         VG      Fmt  Attr PSize   PFree
  /dev/sda1  vg-vol0 lvm2 a--    1.82t  50.04g
  /dev/sdb1  vg-vol0 lvm2 a--    1.82t 863.01g
  /dev/sdc1  vg-vol0 lvm2 a--    1.82t 623.27g
  /dev/sdf1  vg-ssd  lvm2 a--   74.53g  10.53g
  /dev/sdh1  vg-vol0 lvm2 a--  931.51g 931.51g
  /dev/sdi1  vg-ssd  lvm2 a--   74.53g   4.53g
```

주로 노티가 오고 있는 smart 경고는 아래와 같습니다.

```
Jun  1 11:09:47 terra smartd[2031]: Device: /dev/sda [SAT], SMART Prefailure Attribute: 1 Raw_Read_Error_Rate changed from 115 to 117
Jun  1 11:09:48 terra smartd[2031]: Device: /dev/sdc [SAT], SMART Prefailure Attribute: 1 Raw_Read_Error_Rate changed from 116 to 117
Jun  1 11:09:48 terra smartd[2031]: Device: /dev/sdd [SAT], SMART Prefailure Attribute: 3 Spin_Up_Time changed from 83 to 77
Jun  1 11:09:48 terra smartd[2031]: Device: /dev/sde [SAT], SMART Prefailure Attribute: 3 Spin_Up_Time changed from 75 to 68
Jun  1 11:09:48 terra smartd[2031]: Device: /dev/sdh [SAT], SMART Prefailure Attribute: 3 Spin_Up_Time changed from 82 to 76
Jun  1 11:09:48 terra smartd[2031]: Device: /dev/sdc [SAT], SMART Prefailure Attribute: 1 Raw_Read_Error_Rate changed from 116 to 117
Jun  1 11:09:48 terra smartd[2031]: Device: /dev/sdd [SAT], SMART Prefailure Attribute: 3 Spin_Up_Time changed from 83 to 77
Jun  1 11:09:48 terra smartd[2031]: Device: /dev/sde [SAT], SMART Prefailure Attribute: 3 Spin_Up_Time changed from 75 to 68
Jun  1 11:09:48 terra smartd[2031]: Device: /dev/sdh [SAT], SMART Prefailure Attribute: 3 Spin_Up_Time changed from 82 to 76

```

**Comment by yongbin** [comment]
테라의 디스크 구성과 관련한 사항은 내부 버그질라에 잘 정리되어있습니다 

 - 2.5인치(vg-ssd) : 722
 - 3.5인치(vg-vol0) : 723

**Comment by yongbin** [comment]
> orepan2-indexer 가 top 의 최우선으로 보이고 있으니까 일단 cron 에서 막아놓도록 하겠습니다

`orepan2-indexer`이 문제의 원인일수도 있지만 이미 다른원인으로 iowait 이 증가한 상태에서 재수없게 orepan2-indexer이 기동되서 top에 계속 눈에 띄었을 가능성이 있습니다. 우선은 안전성을 위해서 중지해두고 정말 범인인지 확인하기위해서 야간에 풀어서 기동을 해보거나 하는 테스트가 필요합니다.

**Comment by yongbin** [comment]
어제 장애난 시점과 동일한 시점에 terra 장비를 모니터링했습니다. 특이한 프로세스는 찾지 못했는데 그래프상으로는 9시 45분 전후로 살짝 CPU 와 disk 사용이 증가하는 패턴은 동일하게 확인됩니다. 오늘은 디스크 iowait 으로 연결되지 않았기떄문에 이 프로세스가 직접적인 원인이 아니고 디스크 컨디션 이슈라는 생각이 더 강해졌지만, 이 프로세스를 찾으면 영향받는 디스크를 확인할 수 있습니다.

![cpu-pinpoint 1496257202 1496365202](https://cloud.githubusercontent.com/assets/52704/26706963/6823fc98-477c-11e7-86cd-a139b7298b61.png)

![cpu-pinpoint 1496362502 1496366282](https://cloud.githubusercontent.com/assets/52704/26706966/69fe69b8-477c-11e7-8b6b-53a471969010.png)

**Comment by yongbin** [comment]
![cpu-pinpoint 1494387002 1497238202](https://user-images.githubusercontent.com/52704/27018647-f737b238-4f6c-11e7-89cb-fe556de979ea.png)

장애시점부터 약 10일간 모니터링한 장애가 발생한 시점이후 뚜렷하게 유사한 징후가 없습니다. 

조금 전 원인중 하나로 지목된 `orepan-indexer` 의 cron 실행을 재개했습니다. `orepan-indexer`는 5분마다 한번씩 실행되며, 실행시간은 대략 20초 정도 됩니다.

```
real    0m19.229s
user    0m6.632s
sys     0m5.548s
```

**Comment by yongbin** [comment]
현 시점에서 제가 판단할수 있는 가능성은 4가지 정도 됩니다. 

1. 지목했던 `orapan-indexer`

오늘부터 기동을 재개했으므로 모니터링후 관련성을 확인하면 됩니다. 

2. 의문의 시스템 프로세스

5월 30일부터 장애가 발생한 시점까지 존재하다가 재기동이후 사라진 시스템 관련 task가 원인이었을수 있습니다. 관련해서 의심가는 정황이 있으면 알려주시기 바랍니다. 

3.디스크 노후화등에 따라 발생한 문제

opencloset이 운영되고 있는 테라 장비에 LVM 디스크 array를 구성하고 있는 디스크 대부분이 기동시간이 많이 경과한 디스크이기떄문에 지속적으로 smartd를 통해 경고를 보내고 있습니다. 장애에 직접적인 원인이라고 단정할 증거는 없지만 장기적으로 테라 전체의 안전성을 확보한다는 측면에서 노후한 디스크를 보다 용량이 큰 신규 디스크로 대체하는작업은 필요하다고 생각합니다.

1은 금주 모니터링을 통해서 확인하고, 3은 버그질라 별도 이슈에서 진행하도록 하겠습니다.

**Comment by yongbin** [comment]
디스크 교체를 위해 HGST 4TB Ultrastar 7K4000 HUS724040ALA640 (SATA3/7200/64M)  디스크 2개를 구입 완료했습니다.

**Comment by yongbin** [comment]
오전 10시 18분경 형석님으로 부터 서버 반응시간이 느리다는 연락을 받고 확인중입니다. 1차 확인결과 지난번과 비슷한 원인으로 판다되어 여기에 기록합니다. 
![cpu-pinpoint 1497898858 1498006858](https://user-images.githubusercontent.com/52704/27362937-66c66968-566c-11e7-9bdf-c312346e4e19.png)

**Comment by yongbin** [comment]
장애시점 3분정도 모너티렁한 htop 화면입니다. 

![screenshot_2017-06-21_10 26 42](https://user-images.githubusercontent.com/52704/27362977-a8ff47e6-566c-11e7-86ec-93280279404a.png)

CPU 1 번을 100 소모(아마도 iowait) 하고 있는 프로세스를 찾아야 합니다.

**Comment by yongbin** [comment]
![screenshot 2017-06-21 10 34 10](https://user-images.githubusercontent.com/52704/27363074-2f608ae8-566d-11e7-8640-ad1ec8e296ba.png)

이 프로세스가 좀 수상합니다.

**Comment by yongbin** [comment]
https://askubuntu.com/questions/116844/how-to-diagnose-ubuntu-cpu-spikes-io-wait

이 내용을 참고해서 HTOP에서 iowait 관련 지표들을 모니터링하고 있습니다.

**Comment by yongbin** [comment]
모니터링중 부하가 50까지 상승했지만 특별한 이유없이 떨어져서 현재는 2.36입니다.

**Comment by yongbin** [comment]
![cpu-pinpoint 1498002403 1498008883](https://user-images.githubusercontent.com/52704/27363549-2963b0ae-5670-11e7-8353-17bbd7485781.png)

당연한 이야기이지만 모니터링상 부하상승시점와 iowait 증가시점이 일치합니다.

**Comment by yongbin** [comment]
이제 장애가 발생한 시점에 iowait 이 발생하는 프로세스를 지목할수 있는 수단이 생겼습니다. 당분간 htop 모니터링을 상시 진행하겠습니다. 혹시 이상징후 포착시 바로 알려주시기 바랍니다.

별개로 LVM 디스크 교체는 일정대로 진행하겠습니다.

**Comment by aanoaa** [comment]
원인은 모르겠지만 간헐적으로 서버의 로드가 급작스럽게 증가할때가 있습니다.

- 원인 파악을 위해 모니터링을 할 것이고,
- 디스크문제일 것으로 추정하고 있어서 교체작업을 진행 중 입니다.

cc @10001if @pingpongworks

**Comment by yongbin** [comment]
오늘(6월 23일) 자정~새벽 2시 사이 LVM 어레이에 디스크를 추가하는 작업을 진행할 예정입니다. 같이 OS 패키지 업데이트 및 장비 재시작도 진행되기떄문에 해당시간에 예약, 문자발송, 온라인대여등이 되지 않을 수 있습니다.  참고해주시기 바랍니다.

**Comment by 10001if** [comment]
네. 알겠습니다. 내부에 공유하도록 하겠습니다.

**Comment by yongbin** [comment]
6월 24일 자정부터 3시 12분까지 디스크 증설 및 패키지 업데이트 작업을 완료했습니다. 예정보다 작업은 길어졌지만 계획했던 작업은 모두 완료했습니다. 자세한 사항은 내부시스템에 기록하겠습니다. 열린옷장 서비스 구동과 관련해서는 간단하게 ubic status와 staff 로그인정도 확인했습니다. 토요일 운영에서 특이점이 나올경우 빠른 대응이 필요합니다.

**Comment by aanoaa** [comment]
서버에 문제가 있는 것 같습니다.

서비스 계정으로 로그인이 아니되고, 경고 메세지가 출력됩니다.

```
aanoaa@opencloset1:~$ sudo su - opencloset
sudo: unable to open /var/lib/sudo/aanoaa/0: Read-only file system
sudo: unable to open /var/log/sudo-io/seq: Read-only file system

aanoaa@opencloset1:/var$ pwd
/var
aanoaa@opencloset1:/var$ ls
ls: reading directory .: Input/output error
```

https://unix.stackexchange.com/questions/39905/input-output-error-when-accessing-a-directory

> Input/Output errors during filesystem access attempts generally mean hardware issues.

cc @yongbin

**Comment by aanoaa** [comment]
`/var` 디렉토리에 접근할 수 없어서 생기는 문제인 것 같습니다.
새로 교체한 디스크에 문제가 있는 것 같고 새로운 디스크를 넣기 전에는 해결되지 않을 것 같다고 합니다.

문제가 발생하지 않는 디스크에 새로운 컨테이너를 구성해서 현재 서비스와 데이터를 이전해서 사용하기로 하였습니다.

**Comment by aanoaa** [comment]
어떤 서비스가 영향이 있는지 우선 파악해야합니다.

@pingpongworks 님 말씀으로는 됐다가 안됐다가 한다는데..

- monitor.의류준비 (구체적으로 뭐가 안되는지는 모르겠음, redis 가 `/var` 에 log 를 기록 할 것 같은데..)
- 나머지는 어찌어찌 한다.(모르겠음)

-----------------------------

컨테이너를 새롭게 구성한 뒤에는,

- 필수 package 설치
  - nginx
  - mysql
  - redis
  - ...
- db dump (마지막에 한번 더)
- plenv
  - 각 서비스별 의존성 패키지 설치
- nvm
  - coffeescript, bower, grunt, less 등
- service 설정
  - staff
  - visit
  - donation
  - monitor
  - volunteer
  - story
  - coupon?
  - ...
  - 각종 cronjob
- ubic 설치
  - 서비스 설정
  - log rotation
- cronjob
  - `OpenCloset::Cron::*` 말고 `crontab` 에 등록되어 있는 것들
- pending 된 SMS 처리
- 테스트

-----------------------------

등등을 해주어야 합니다.

진행과정은 github 보다는 bugzilla 에 적는 것이 더 좋을 것 같습니다.

**Comment by pingpongworks** [comment]
의류준비 외에도 문제있는 곳들이 있는거 같습니다. 오늘 예약이 112명으로 많아서 시간이 될지 모르겠는데, 최대한 빨리 안되는 부분 자세히 체크해서 github에 올려놓겠습니다

2017. 8. 21. 오후 1:34 Hyungsuk Hong <notifications@github.com> 작성:

**Comment by aanoaa** [comment]
`/var` 디렉토리의 백업을 새로운 디스크에 풀어서 마운트 시켰더니 동작합니다.
이것도 임시방편입니다.

예정했던대로 새로운 디스크에 컨테이너를 만들어서 서비스를 이전해야 한다고 합니다.

**Comment by pingpongworks** [comment]
**오전에 문제 발생이 발견되었던 부분**

**1. preparation 화면**
대여자가 방문하여 신체치수 측정 후 의류준비로 넘겼을 때 대쉬보드에는 뜨는데, 의류준비 화면에는 업로드되지 않았습니다. 그래서, 대여진행은 대쉬보드를 보면서 새로 도착한 대여자가 있으면 사용자정보에서 사이즈 확인 후, 옷을 준비하고, 시간표에서 탈의실 번호를 선택하여 넣었습니다. 그러면 탈의실에는 반영되었습니다. 그러나, 옷을 교환해주기 위해 탈의실에서 의류준비로 빼면 아래의 화면이 뜨고 모든 것이 정지상태가 됩니다. 
![_20170821_101139_1](https://user-images.githubusercontent.com/17288038/29504380-4fe9b82e-867a-11e7-8735-d743ab67ccb0.jpg)

**2. 주문내역서 화면**
포장을 완료하여 결제로 넘긴 후, 안내지 출력까지 아무 이상 없다가, 결제대기로 넘기면 비정상적인 화면이 떴습니다. 캡처를 해놓지 못헀습니다만, 화면의 모든 단어가 세로로 나오는 듯한 화면,,, 그래서, 아예 프로그램에서 나갔다가 첫화면으로 로그인하여 주문서로 들어가 결제대기로 들어가면 주문내역서가 정상적으로 보였습니다. 계속 들락날락 하면서 결제를 하긴 헀습니다. 

3. 취업날개 예약
취업날개 예약을 열린옷장으로 하려고 하면 방문일자 선택이 아예 안된다고 서울시에서 연락이 왔다고 합니다. 그런데, 점심 이후 테스트 해보니 지금은 되는 것 같습니다.. 일단 예약 안되는 분 있으면 열린옷장으로 전화주도록 안내부탁했으니까 또 문제가 생기면 알려드리겠습니다.  

@yongbin @yongbin 우선은 점심시간에 조치해주신 덕분에 큰 문제 없이 대여하고 있습니다. 문제 생기면 @yongbin대표님께 행아웃으로 알려드리기로 헀습니다. 고맙습니다.

**Comment by pingpongworks** [comment]
방금 발견된 오류입니다. 
온라인대여사이트에 로그인하려고 하면 아래 화면이 뜹니다.

<img width="960" alt="2017-08-21 14 37 22" src="https://user-images.githubusercontent.com/17288038/29505060-be2cf450-867e-11e7-9a06-5eabe2b98440.png">

**Comment by pingpongworks** [comment]
취업날개 예약이 안된다는 연락이 있었습니다. 
그런데, 평소에도 다양한 이유로 잘 안된다는 연락들이 있었어서 정확히 서버때문인지 판단은 못하겠습니다. 

일단은 예약이 안된다고 전화 온 경우, 옷장지기가 대신 예약을 진행해주고, 방문시 서울시 일자리포털을 통해서 다시 예약하는 방식으로 대처할 수 밖에 없는 상황입니다.

**Comment by aanoaa** [comment]
share 는 재부팅의 영향이 있었던 것 같습니다.
프로그램을 재시작해서 지금은 동작합니다.
취업날개 예약이 안된다는건 글세요 방문예약이 모두 안된다면 모를까
취업날개를 통한 방문예약만 안되지는 않을 것 같습니다.

다른 특별한 상황이 있는게 아닌가요? 취업날개 온라인 예약이라던지..

**Comment by pingpongworks** [comment]
@aanoaa 취업날개 관련해서는 이후로 연락이 없고, 저희가 테스트해봐도 잘 되고 있습니다. 일단 신경 안써도 될 듯합니다. 

**기증신청과 봉사신청이 익스폴로어에서 되지 않습니다. .**
지금 제가 테스트해보니까, 크롬에서는 아무 문제가 없는데 
익스플로어에서 기증신청을 하면 마지막에 아래 화면이 뜹니다. 
<img width="960" alt="2017-08-21 15 37 02" src="https://user-images.githubusercontent.com/17288038/29506710-19101f4c-8688-11e7-93be-877897af8c37.png">
  
자원봉사도 크롬에서는 정상적으로 신청이 되는데
익스플로어에서 하면 마지막에 아래 화면이 뜨면서 에러가 납니다. 
<img width="960" alt="2017-08-21 15 40 57" src="https://user-images.githubusercontent.com/17288038/29506810-72a5d39e-8688-11e7-9989-55398b5b6073.png">

**Comment by aanoaa** [comment]
익스플로어에서는 테스트를 전혀 못해봤습니다.
이번에 발생한 문제는 아닙니다.
생년월일을 잘못 입력한 것 같은데, `YYYY-mm-dd` 형식입니다.

**Comment by yongbin** [comment]
간략하게 오전에 장애가 난 상황과 조치를 정리하겠습니다.

## 상황 

- terra 장비에 sdc(2TB), sdd(4TB) 디스크가 input error 로 장치접근이 불가능
- 위 디스크는  lvm의 vg-vol0 를 구성하고 있는 디스크였으며 아래 lxc 이미지들이 이 영역에 존재함
```
  ├─vg--vol0-sq--backup--20170227+0900-cow    254:9    0  59.8G  0 lvm
  │ └─vg--vol0-sq--backup--20170227+0900      254:10   0   293G  0 lvm
  ├─vg--vol0-lxc_evid.silex.kr_storage        254:14   0   500G  0 lvm
  ├─vg--vol0-lxc_keedi.silex.kr               254:19   0    40G  0 lvm
  ├─vg--vol0-lxc_translation.r--project.org   254:20   0    40G  0 lvm
  ├─vg--vol0-sq--backup                       254:21   0   500G  0 lvm
  └─vg--vol0-lxc_opencloset1.silex.kr_var     254:22   0   100G  0 lvm
```
- 즉 정리하면 opencloset1 장비에 var 디렉토리에 해당하는 디스크영역이 일시적으로 접근이 불가한 상황
- 처음에는 단순 오류라고 생각했지만 물리 몰륨, 볼륨 그룹쪽에서 모두 동일한 현상이 나타나는것을 볼때 물리적 오류도 배재할수 없다고 판단. 만약 물리적 오류가 있다면 원격재기동에서 lvm 이 vg 로드에 실패하고 결과적으로 terra에 올라가있는 모든 서비스가 기동되지 않는 상황도 발생할 수 있음 

## 조치

 - 다행이 opencloset1 장비에서 이번 디스크 장애에 영향을 받는 부분은 `var` 디렉토리 뿐이며 나머지는 다른 영역에 존재함 (특히 일반적으로 MySQL이 var 하부에 자료를 저장하는데 과거 용량문제로 MySQL 저장영역역시 분리되어있었음)
 - 따라서 brompton 에 존재하던 과거 opencloset1 백업중 `var`에 해당하는 영역을 vg-ssd에 새로운 lv 에 푼 뒤 opencloset1의 var 를 새로운 lv 를 바라보도록 LXC 설정을 변경함
 - 변경후 백업이후 생성한 몇몇 로그디렉토리가 존재하지 않는 문재로 nginx 가 기동하지 않았지만 (id, coupon 등) 생성후 대부분 정상가동함

## 근본적인 해결방법

 - 우선 현재 vg-vol0 에 올라가있는 모든 자료중 sdc, sdd 에 영향받지 않는 영역은 조속한 백업이 필요함 
 - 추가적으로 opencloset1 서비스는 이번에 증설한 vg-ssd1 영역으로 옮기는것을 고려중 (clean 재설치보다 기존 시스템을 복사하는 방식으로 진행예정)
 - 최종적으로 sdc, sdd 영역에 모든 lv를 백업한 뒤, 물리적으로 IDC를 방문해서 디스크 상태를 확인하고 offsite 재기동후 필요한 조치를 해야함

**Comment by yongbin** [comment]
임시로 조치했던 opencloset1.silex.kr 의 디스크 볼륨을 아래와 같이 정리하는 작업을 오늘 자정에 진행합니다.

- opencloset1.silex.kr 서비스 일시 정지
- `vg-ssd` 영역으로 lxc_opencloset1.silex.kr LV 생성(Size 40G)
- 기존 `vg-vol0` 에 존재하던 lxc_opencloset1.silex.kr(10G) , `vg-ssd`에 존재하던 opencloset1_var_temp(5G) 의 파일을 각각 신설된 LV로 복사
 - LXC 마운트 옵션에서 임시로 var mount를 지정했던 사항을 해제 
 - LXC 재기동
 - opencloset1.silex.kr LV의 snapshot 후 backup
 - 3일후 기존 lv 삭제

작업은 9월 14일 00:15분 부터 진행할 예정이며 서비스 중지시간은 약 45분정도 예상합니다. 이 시간동안 온라인서비스 대여, 오프라인 예약, 문자발송등이 되지 않습니다. 대비 부탁드리며 필요시 공지도 부탁드립니다. 

@10001if

**Comment by 10001if** [comment]
@yongbin 네. 알겠습니다. 내용 전달하도록 하겠습니다.

**Comment by yongbin** [comment]
예정보다 준비및 확인시간이 더 소요되서 실제로 서비스를 내리고 작업한 시간은 am 6:45 ~ am 7:15  약 30분입니다. 

예정했던 `vg-ssd`로 LXC의 루트를 옮기고 분리되어있던 두 LV를 합치는 작업은 성공했으며 서비스도 다시정상적으로 가동중입니다. 대부분의 서비스가 재기동시 자동으로 시작되었지만 `share`의 경우 프로세스는 떠있지만 모졸리셔서 에러화면이 나오는 상황이라 수동으로 다시한번 재기동했습니다. (지난번 terra 디스크 증설때도 동일한 현상이 있었습니다) 

부수적으로 열린옷장 서비스들의 디스크 응답시간이 짧아졌기때문에 서비스가 전체적으로 빨라지는 효과도 기대할 수 있습니다. 

제가 확인하지 못한 이상점이 있을수 있습니다. 오늘 하루동안 이전후 나오는 이상점에 대해 주의해주시고 문제가 있다면 이 이슈에 남기거나 저에게 직접 알려주시기 바랍니다. 

@10001if , @aanoaa

**Comment by yongbin** [comment]
LVM snapshot 을 이용한 백업이 간단하기는 하지만 이번처럼 다른 이유로 VG에 문제가 생길경우 백업이 전부 유실된다는 단점이 있습니다. 고전적인 local copy + network archive 방식으로 백업을 변경하기위해서 [rsnapshot](http://rsnapshot.org/) 을 terra에 적용했고 `vg-ssd/lxc_opencloset1.silex.kr`, `lxc_opencloset1.silex.kr_storage` 을 대상으로 hourly(4시간), daily (7일), weekly(4주) 보관을 설정했습니다.

**Comment by 10001if** [comment]
네. 확인 후에 이상 있는 부분이 있으면 바로 공유하도록 하겠습니다.

**Comment by yongbin** [comment]
오늘 저녁에 한가지 작업이 더 필요하니다. 마찬가지로 오늘 자정부터 30분정도 소요 예정입니다.

**Comment by yongbin** [comment]
추가작업시작합니다. 약 40분정도 소요예정입니다.

**Comment by yongbin** [comment]
완료되었습니다. share 는 마찬가지로 수동 재시작해줬습니다. 이제 일주일간 localbackup 이 보존되는것을 확인하면 이 이슈는 닫겠습니다.

**Comment by 10001if** [comment]
@yongbin 따로 장애가 있거나 특이한 점은 전달받지 못했습니다. 작업 감사드립니다.

**Comment by yongbin** [comment]
현재 내부 이슈관리시스템에서 이 이슈와 관련된 이슈들이 진행중이거나 완료되었습니다. 

 - 1차백업 rsnapshot 도입 (Bug 938)
 - 2차백업 archive(Bug 933)
 - 3차 백업 rsyncd + rsnapshot (Bug 940)

오늘까지 1차백업으로 6일치, 2차백업을 4일, 3차백업으로 3일치 보관되었고 이 상태로 계속 운영되면 열린옷장 서비스관련 자료는 최장 10일치까지 3곳에 분산해서 보관됩니다. 

계획했던 개선작업을 완료했기때문에 이슈 닫겠습니다. 추후 이 장애에 근본 원인이었던 디스크 오류관련 사항은 
오프라인 작업때 별도 내부 이슈에 기록하겠습니다.
