### ISSUE TITLE
취업날개 서비스의 방문/미방문자의 통계수치 동기화

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#1256]
취업날개 공식 통계 서비스에는 지난 22일 부터 지금까지의 열린옷장의 방문자 숫자가 기록되지 않았습니다.

방문자수를 집계하는 방식은 이렇습니다.

- 예약
- 방문후 대여
- 이때에 통계서비스에 접속해서 대여자의 정보를 확인하고 `대여` 버튼을 클릭

이렇게 하면 `미방문 -= 1`, `방문 += 1` 으로 변경됩니다.

- 대여가 확정되었을때에 미방문 -> 방문 으로 변경하는 기능을 자동화 할 수 있어야 합니다.
- 22일 부터 누락된 방문자를 일괄로 변경해주어야 합니다.

@keedi 혹시 생각해두신 방법이 있으면 알려주세요.

**Comment by aanoaa** [comment]
- http://dressfree.net/service 에 로그인
- `예약 내역` 목록에서 상태를 변경할 대여자를 클릭
- `대여완료` 버튼을 클릭

계정은 따로 전달받았습니다.
`대여완료` 처리를 하려면 어떤방식으로 요청해야 하는지 inetpia 측에 문의해 볼 필요가 있습니다.
js 코드를 봤을때는 아래와 같은 요청을 만들면 되지 않을까 합니다.

```
POST http://dressfree.net/dev/ajax_update.php

uptype=online_state&val1=:rent_num&val2=2
```

--------------

```
val2
  1: 예약중
  2: 대여완료
  3: 회수완료
  4: 대여취소
```

응답은 'true' or 'false' 로 오는 것 같습니다.

**Comment by aanoaa** [comment]
https://github.com/opencloset/OpenCloset-Events-EmploymentWing

에 모듈을 추가 하였습니다.
앞으로 취업날개 서비스와 통신이 필요한 부분은 위 모듈에 추가해서 이용하겠습니다.

**Comment by aanoaa** [comment]
[OpenCloset-Events-EmploymentWing-v0.0.1.tar.gz](https://cpan.theopencloset.net/STAFF@THEOPENCLOSET.NET/OpenCloset-Events-EmploymentWing-v0.0.1.tar.gz) 배포하였습니다.

**Comment by aanoaa** [comment]
취업날개는 서비스이지만 열린옷장입장에서 보면 이벤트중 하나라서 이벤트로 분류하였습니다.

**Comment by aanoaa** [comment]
지금까지의 `미방문 -> 방문` 의 대여번호를 뽑아야 합니다.

**Comment by aanoaa** [comment]
세션 타임아웃을 몰라서 임의로 +10m 으로 설정하였습니다.
로그인하고 +10분까지 다시 로그인하는 과정없이 HTTP request 를 보낼 수 있습니다.

**Comment by aanoaa** [comment]
- 하루치를 모아서 변경할 수도 있고 (1)
- 개별 대여완료 이후에 바로 변경해 줄 수도 있습니다. (2)

(1) 은 cron 작업을 추가하면 되겠고,
(2) 는 프로그램의 변경이 필요합니다.

cron 작업을 추가했다가 필요가 없을때에 제거하는 방법이 더 관리하기 편리할 것 같습니다.

**Comment by aanoaa** [comment]
- 날짜 별로 취업날개를 통해 `예약 -> 대여` 목록을 뽑아서
- 해당 대여번호를 가지고 취업날개 서비스에 상태변경

해주면 될 것 같습니다.

**Comment by aanoaa** [comment]
- `OpenCloset::Cron::Event` 에서 이벤트와 관련된 cronjob 을 처리할 수 있도록 추가하거나,
- 이미 활용되고 있는 `OpenCloset-Cron-Visitor` 의 `event_wings` 에서 처리할 수 있습니다.

**Comment by aanoaa** [comment]
방문자 수를 수집하는 visitor 에서 온라인 상태변경 까지 해준다는게 맘에 들지 않습니다.
(1) 번으로 진행하겠습니다.

**Comment by aanoaa** [comment]
https://github.com/opencloset/OpenCloset-Cron-Event 를 만들었습니다.

**Comment by aanoaa** [comment]
ee669dabe5ea4013afc9e2724ff3fb8ba406427a 와 같이 설정파일을 추가해주어야 합니다.

**Comment by aanoaa** [comment]
``` perl
use strict;
use warnings;
use DateTime;
use Data::Dump;

use OpenCloset::Schema;
use OpenCloset::Cron::Event qw/update_employment_wing_status/;
use OpenCloset::Events::EmploymentWing qw/$EW_STATUS_BOOKING $EW_STATUS_COMPLETE/;

my $schema = OpenCloset::Schema->connect({ ... });

my $TZ   = 'Asia/Seoul';
my $date = DateTime->new(
    year      => 2017,
    month     => 5,
    day       => 21,
    time_zone => $TZ,
);

my $end = DateTime->new(
    year      => 2017,
    month     => 6,
    day       => 4,
    time_zone => $TZ,
);

my $account = {
    username => 'xxxxx',
    password => 'xxxxx',
};

my %stat;
while ( $date->add( days => 1 ) <= $end ) {
    my $count = update_employment_wing_status( $schema, $account, $date, $EW_STATUS_COMPLETE );
    $stat{ $date->ymd } = $count;
}

dd %stat;
```

위 스크립트를 실행해서 5/22 ~ 6/4 까지의 예약상태를 변경할 수 있습니다.

**Comment by aanoaa** [comment]
서버의 설정파일에 `freedress` 와 `opencloset-cron-event.pl` 값을 추가하였습니다.

**Comment by aanoaa** [comment]
[OpenCloset-Cron-Event-v0.0.1.tar.gz](https://cpan.theopencloset.net/STAFF@THEOPENCLOSET.NET/OpenCloset-Cron-Event-v0.0.1.tar.gz) 배포하였습니다.

**Comment by aanoaa** [comment]
`opencloset.cron.event` 서비스 실행시켰습니다.
내일(2017-06-06)부터 매일 AM 01:05 에 전날 방문자의 예약상태를 대여완료로 변경하게 됩니다.

**Comment by aanoaa** [comment]
2017-05-22 ~ 2017-06-04 까지의 모든 누락된 취업날개 상태를 변경하였습니다.
실패한 요청없이 모두 성공하였습니다.

    $ time perl a.pl
    ### 2017-05-22
    { fail => 0, success => 1 }
    ### 2017-05-23
    { fail => 0, success => 8 }
    ### 2017-05-24
    { fail => 0, success => 11 }
    ### 2017-05-25
    { fail => 0, success => 23 }
    ### 2017-05-26
    { fail => 0, success => 25 }
    ### 2017-05-27
    { fail => 0, success => 25 }
    ### 2017-05-28
    { fail => 0, success => 40 }
    ### 2017-05-29
    { fail => 0, success => 27 }
    ### 2017-05-30
    { fail => 0, success => 46 }
    ### 2017-05-31
    { fail => 0, success => 39 }
    ### 2017-06-01
    { fail => 0, success => 18 }
    ### 2017-06-02
    { fail => 0, success => 28 }
    ### 2017-06-03
    { fail => 0, success => 24 }
    ### 2017-06-04
    { fail => 0, success => 21 }
    
    real	5m58.696s
    user	0m0.476s
    sys	0m0.036s

5/22 ~ 5/28 까지의 수치가 저희가 사용하는 통계와 다른데 그 이유는

    열린옷장 통계 = 통합예약 서비스로 예약(A) + 통합예약 서비스 전 예약인원(B)

| 날짜 | 열린옷장 | 통합예약 |
|-----|--------|--------|
| 2017-05-22 | 57 | 1 |
| 2017-05-23 | 40 | 8 |
| 2017-05-24 | 38 | 11 |
| 2017-05-25 | 34 | 23 |
| 2017-05-26 | 31 | 25 |
| 2017-05-27 | 32 | 25 |
| 2017-05-28 | 41 | 40 |
| 2017-05-29 | 32 | 27 |
| 2017-05-30 | 46 | 46 |
| 2017-05-31 | 39 | 39 |
| 2017-06-01 | 18 | 18 |
| 2017-06-02 | 28 | 28 |
| 2017-06-03 | 24 | 24 |
| 2017-06-04 | 21 | 21 |

때문입니다.
예로 5/20 일 통합예약서비스가 운영되기 전에 예약하고 5/25일 이용한 사람이 있기 때문에 숫자가 다릅니다.

**Comment by aanoaa** [comment]
5/30 일 방문자의 예약상태를 바꿨는지 어쨌는지 기억이 안난다면 5/30일 에 대해 `OpenCloset::Cron::Event::update_employment_wing_status` 를 실행하면 됩니다.
두번 세번 실행해도 결과는 같습니다.

우리쪽의 데이터는 항상 그대로이고 통합예약서비스의 데이터를 변경하는 요청입니다.

**Comment by aanoaa** [comment]
이메일로 문의한 내용은 짬된걸로~

**Comment by 10001if** [comment]
@aanoaa 5월 정산은 서울시와 상의하여 완료하였습니다. 감사합니다.

**Comment by aanoaa** [comment]
배포후에 지난 이틀간의 로그를 확인해봤습니다.
fail 이 있으면 통계수치가 맞지 않을 수 있기 때문에 확인해서 조치해주어야 합니다.

다행히 지난 이틀간 예약상태를 변경하는 것에는 문제가 없어 보입니다.

```
2017-06-06 01:05:32.270613 +0900 info  main: 2017-06-05 success: 30, fail: 0
2017-06-07 01:05:00.243338 +0900 info  main: 2017-06-06 success: 0, fail: 0
```

**Comment by aanoaa** [comment]
실패가 발생했을때에 sms 나 email 로 noti 를 주도록 하면 어떨까 생각만 하고 있습니다.

**Comment by 10001if** [comment]
@aanoaa 알림을 통해 실패여부를 인식할 수 있도록 하는 것이 필요할 것 같습니다. 실패하는 경우가 있음에도 모르고 넘어간다면 정산에 문제가 발생할 수 있으므로 실패 여부를 인지하는 것이 필수적으로 필요하다고 생각합니다.

**Comment by aanoaa** [comment]
코드번호가 공개되어도 괜찮은지 모르겠습니다만 이미 사용된 코드이니까 적습니다.

`170601094522-372` 는 취업날개 예약내역목록에 대여일과 대여시간이 없습니다.
이로 인해서 6/5 일 통계 수치가 잘못 나오고 있습니다.

**Comment by aanoaa** [comment]
`170603231435-925` 은 6/4일로 예약후에 6/5일로 예약을 변경하였습니다.
이는 6/4일 통계로 집계됩니다. 예약시간을 변경하였을때에 취업날개의 예약시간에 반영되고 있지 않습니다.

**Comment by aanoaa** [comment]
미방문자의 수치가 많이 다른 이유도 예약일이 변경되었기 때문입니다.
열린옷장에서 예약일/예약시간을 변경한 것이 취업날개에 반영되지 않았기 때문입니다.

**Comment by aanoaa** [comment]
- 예약시간이 변경되면 취업날개에 반영해주고,
- 예약시간이 변경된 주문서를 찾아서 취업날개에 반영해주어야 합니다.
  - 예약시간 변경이 잦아서 찾아낸다는 것이 어려울 수 있을 것 같습니다.

**Comment by aanoaa** [comment]
지금까지 사용/미사용된 취업날개 주문서의 예약시간을 취업날개 서비스에 변경하고,
예약시간이 변경될때마다 취업날개 주문서인지 확인해서 변경하도록 해야합니다.

**Comment by aanoaa** [comment]
문제가 있습니다.
예약시간을 변경하면 온라인 예약상태가 `예약중`으로 변경됩니다.

5/22 ~ 지금까지의 취업날개 이용자의 예약시간을 변경해줘야 하는데,
그렇게 되면 모든 상태가 `예약중` 으로 변경됩니다.

**Comment by aanoaa** [comment]
협력업체 및 서울시에 문의 하였습니다.

> 안녕하세요.
> 열린옷장의 서비스를 담당하고 있는 홍형석이라고 합니다.
> 지난번에 메일 드렸는데 답이 없어서 다시 소개합니다.
> 
> 예약일시를 변경하고자 하는데 궁금한 점이 있어서 메일드립니다.
> rent_num 으로 예약일시를 변경하기 위해서 아래 api 를 호출하면 되는 걸로 알고 있습니다.
> 
>     예약일시 보내주실 페이지
>     http://dressfree.net/theopencloset/api_rentRcv.php
>     POST로 넘겨주실 변수
>     rent_num > 보내드린 예약코드
>     rent_date > 예약일(yyyy-mm-dd)
>     rent_time > 예약시간(hh:ss)
>     예약일이나 예약시간의 형식이 다를 경우 어떤 형식으로 보내주실 지 알려주시기 바랍니다.
> 
> 열린옷장에서는 예약후에 대여자가 예약일을 변경할 수 있도록 하고 있습니다.
> 대여자가 예약일시를 변경했을때에 위 API를 사용해서 예약일시를 변경하려고 하는데 문제가 있습니다.
> 
> 예약일시는 변경이 되는데, 의도치 않게 온라인 예약 상태가 예약중 으로 변경됩니다.
> 예약일시만 변경하는 방법을 알려주세요.
> 
> 방문자수를 가지고 서울시에 정산요청을 하고 있는데, 일일 통계의 수치가 안맞아서 정산하는데 어려움이 있습니다.
> 꼭 답변 부탁드립니다.
> 
> 그럼 수고하세요.

**Comment by aanoaa** [comment]
답변입니다.

> 기존에 넘기는 변수에 추가로 신규등록인지 예약일시변경인지 타입을 확인하는 변수를 하나 더 지정을 해서 해당변수에 지정된 타입에 따라 신규건인지 예약일시만 변경해야 하는 건인지 확인해서 그에 맞게 처리하도록 하겠습니다.
> 
> 추가되는 변수
> rcv_type
> 
> 신규건일 경우 rcv_type = ''
> 예약일시만 변경할 경우 rcv_type = 'm_date'
> 
> 수신페이지에는 이미 반영해 놓았으니 넘겨주실때 변수만 추가해주시면 바로 반영될겁니다.
> 
> 그럼 수고하세요.

**Comment by aanoaa** [comment]
[OpenCloset-Events-EmploymentWing-v0.0.2.tar.gz](https://cpan.theopencloset.net/STAFF@THEOPENCLOSET.NET/OpenCloset-Events-EmploymentWing-v0.0.2.tar.gz)
[OpenCloset-Cron-Event-v0.0.3.tar.gz](https://cpan.theopencloset.net/STAFF@THEOPENCLOSET.NET/OpenCloset-Cron-Event-v0.0.3.tar.gz)

예약일시 변경 API 를 사용할 수 있도록 수정하고 두개의 모듈을 다시 배포하였습니다.

OpenCloset-Cron-Event 를 설치하고 서비스를 재시작 해주어야 합니다.

    $ closetpan OpenCloset::Events::EmploymentWing
    $ closetpan OpenCloset::Cron::Event
    $ ubic restart opencloset.cron.event

**Comment by aanoaa** [comment]
적용하였습니다.

**Comment by aanoaa** [comment]
통계를 맞출 준비가 되었습니다.

`OpenCloset::Events::EmploymentWing` 의 `update_booking_datetime` 을 사용해서,

1. 열린옷장의 대여자가 예약일시를 변경하면 취업날개서비스에도 반영해준다.
2. 5/22 ~ 지금까지의 취업날개 사용/예약자의 예약일시를 변경해준다.

두개의 작업을 해야 합니다.

1번 작업을 먼저 반영하고, 2번 작업은 스크립트를 만들어서 처리하도록 하겠습니다.

**Comment by aanoaa** [comment]
설정파일에서 `freedress` 와 관련된 값을 제거 하였습니다.
이제는 필요없기 때문입니다.

**Comment by aanoaa** [comment]
이제와서 생각해보니 `EmploymentWing` 보다는 `JobWing` 이 더 나은 것 같습니다.
뭐 어쩔 수 없습니다.
여력이 생기면 바꿀테지만 아마도 안 바꿀 것 같습니다.

**Comment by aanoaa** [comment]
> 1. 열린옷장의 대여자가 예약일시를 변경하면 취업날개서비스에도 반영해준다.

적용하였습니다.

**Comment by aanoaa** [comment]
방문/미방문의 통계를 맞추려면 사용된 쿠폰 뿐만 아니라 예약 방문 한 모든 쿠폰에 대해서 예약일시를 변경해주어야 합니다.
5/22 ~ 지금까지 1200 여건 정도 됩니다.
1200 여건에 대해서 어느 것이 변경되었고 어느 것이 변경되지 않은지 알 수 있는 방법이 없습니다.

전체 건수에 대해서 열린옷장 예약일시 기준으로 업데이트 시켜주도록 하겠습니다.
한꺼번에 많은 요청이 가지 않도록 1초에 한건씩 처리하도록 하면, 20분이면 완료 될 것 같습니다.

**Comment by aanoaa** [comment]
``` perl
use strict;
use warnings;
use OpenCloset::Schema;
use OpenCloset::Events::EmploymentWing;

my $schema = OpenCloset::Schema->connect({ ... });

my $client = OpenCloset::Events::EmploymentWing->new;
my $rs =
    $schema->resultset('Coupon')->search( { desc => { -like => 'seoul-2017-2%' } } );

while ( my $coupon = $rs->next ) {
    my ( $name, $rent_num, $mbersn ) = split /\|/, $coupon->desc;
    next if $name ne 'seoul-2017-2';
    next unless $rent_num;
    next unless $mbersn;

    my $datetime = $coupon->order->booking->date;
    my $success = $client->update_booking_datetime( $rent_num, $datetime );
    unless ($success) {
        print STDERR "Failed to update booking_datetime($rent_num)\n";
    }

    sleep(1);
}
```

이 것을 돌리도록 하겠습니다.

**Comment by aanoaa** [comment]
온라인 주문서는 예약일시가 없습니다.
온/오프라인 통계수집을 달리해야합니다.

``` perl
use strict;
use warnings;
use OpenCloset::Schema;
use OpenCloset::Events::EmploymentWing;

my $schema = OpenCloset::Schema->connect({ ... });

my $client = OpenCloset::Events::EmploymentWing->new;
my $rs =
    $schema->resultset('Coupon')->search( { desc => { -like => 'seoul-2017-2%' } } );

while ( my $coupon = $rs->next ) {
    my ( $name, $rent_num, $mbersn ) = split /\|/, $coupon->desc;
    next if $name ne 'seoul-2017-2';
    next unless $rent_num;
    next unless $mbersn;

    my $order = $schema->resultset('Order')
        ->search( { coupon_id => $coupon->id, online => 0 }, { rows => 1 } )->single;
    next unless $order;

    my $booking = $order->booking;
    next unless $booking;

    my $datetime = $booking->date;
    my $success = $client->update_booking_datetime( $rent_num, $datetime );
    unless ($success) {
        print STDERR "Failed to update booking_datetime($rent_num)\n";
    }

    sleep(1);
}
```

**Comment by aanoaa** [comment]
통계가 여전히 차이가 있을 수 있습니다.
온라인(택배) 예약을 고려해서 반영해 주어야 합니다.

**Comment by aanoaa** [comment]
실패한 요청없이 처리되었습니다.

    $ time perl a.pl 
    
    real	11m27.966s
    user	0m3.188s
    sys	0m0.064s

**Comment by aanoaa** [comment]
예약 내역 리스트에서 대여방법: `택배(온라인)` 으로 검색하면 0건 입니다.
실제로 없었는지 확인이 필요합니다.

**Comment by aanoaa** [comment]
누적 취업날개 서비스 예약 수가 1044건 이라서 17여분이 걸려야 하는데 11분 27초 걸렸습니다.
쿠폰을 발행만 하고 실제로 예약은 하지 않은 것인지 확인해볼 필요가 있습니다.

**Comment by aanoaa** [comment]
취업날개 온라인 주문서: 5건
취업날개 예약된 주문서: 642건

입니다.
1044 건중에 쿠폰을 발행만 하고 예약을 하지 않은 쿠폰이 많은 것 같습니다.

숫자를 딱 맞추고 싶은데, 경우의 수가 다양한 건지 딱 맞지 않네요.

- 쿠폰을 발행하고 예약
- 쿠폰을 발행하고 예약하고 사용
- 쿠폰을 발행하고 온라인으로 대여
- 쿠폰을 발행하고 예약하지 않음
- 쿠폰을 발행하고 예약 후 취소

가 있을 것 같은데, 취소는 주문서를 삭제하기 때문에 몇 건이나 발생했는지 알 수 없습니다.

**Comment by aanoaa** [comment]
온라인 주문의 경우 예약일시가 비어있기 때문에 통계에 집계되지 않습니다.
이는 양쪽 모두에 해당합니다.

**Comment by aanoaa** [comment]
예약시간을 변경하는 채널이 한가지 더 있습니다.
방문예약후에 다시 와서 인증번호를 입력하고 예약일시를 변경하는 경우입니다.
이 경우에도 거꾸로 반영해주도록 해야 합니다.
(얼마 없을 것 같지만 파악이 아니됨)

**Comment by aanoaa** [comment]
1. 온라인 주문서의 통계를 수집
2. 방문예약화면에서 예약일시를 변경했을때에 취업날개에 반영

해주는 작업이 되면 마무리 됩니다.
온라인 통계 수치확인을 위해서 통계화면이 바뀔 수도 있습니다.

**Comment by aanoaa** [comment]
온라인 주문서는 대여일 기준으로 집계할 수 있습니다.

`5/30` 주문하고 `6/8 ~ 6/11` 이 대여기간 이라면,
대여일이 `6/8` 이고 이 주문서는 `6/8` 일 통계로 수집되는 겁니다.

현재 온라인 방문자 수를 위와 같은 방식으로 하고 있습니다.

**Comment by aanoaa** [comment]
온라인으로 쿠폰을 사용하였을때에 예약 상태를 변경해 주어야 합니다.

**Comment by aanoaa** [comment]
온라인대여에서 쿠폰을 사용만 하고 배송비를 결제하지 않은 주문서에 대해서는 의류를 발송하지 않습니다.
이런 주문서는 미방문 주문서로 분류할 수 있습니다.

온라인이라서 방문/미방문이란 단어가 적절하지는 않지만,

- 방문 => 대여됨
- 미방문 => 대여되지 않음

으로 여길 수 있습니다.

하지만 결제가 확정되지 않으면 `대여일`이 없기 때문에, 이런 주문서를 몇일날 통계로 잡아야 할 지 애매해 집니다.
쿠폰은 사용되었으나 대여일이 비어 있는 주문서는 의류착용일을 기준으로 온라인 미방문 주문서로 넣겠습니다.

**Comment by aanoaa** [comment]
통계화면에서 online/offline 구분해서 볼 수 있도록 해야합니다.

    GET /stat/events/seoul-2017
    GET /stat/events/seoul-2017?online=1
    GET /stat/events/seoul-2017?online=0

기본으로는 online + onffline 을 합한 값을 보도록 하고,
`online` query param 으로 구분해서 online/offline 별로 통계를 볼 수 있도록 하겠습니다.

**Comment by aanoaa** [comment]
별 것 아닌 줄 알았는데, 해야 할게 많은 이슈 입니다.

**Comment by aanoaa** [comment]
[OpenCloset-Cron-Visitor-v0.2.0.tar.gz](https://cpan.theopencloset.net/STAFF@THEOPENCLOSET.NET/OpenCloset-Cron-Visitor-v0.2.0.tar.gz) 를 배포하였습니다.

    $ closetpan OpenCloset::Cron::Visitor

새로운 모듈을 설치한 후에는,
아래 스크립트를 돌려서 5/22 ~ 6/11(어제) 까지의 취업날개 온라인 방문/미방문 통계를 수집해야 합니다.

``` perl
use strict;
use warnings;
use DateTime;

use OpenCloset::Schema;
use OpenCloset::Cron::Visitor qw/event_wings/;

my $schema = OpenCloset::Schema->connect({ ... });

my $tz = 'Asia/Seoul';
my $dt = DateTime->new(
    year      => 2017,
    month     => 5,
    day       => 22,
    time_zone => $tz
);

my $end = DateTime->now( time_zone => $tz )->truncate( to => 'day' );

while ( $dt < $end ) {
    my $count = event_wings( $schema, $dt );
    my $stat = $count->{online};
    $schema->resultset('Visitor')->create(
        {
            date           => "$dt",
            online         => 1,
            visited        => $stat->{male}{visited} + $stat->{female}{visited},
            visited_male   => $stat->{male}{visited},
            visited_female => $stat->{female}{visited},
            visited_age_10 => $stat->{10}{visited},
            visited_age_20 => $stat->{20}{visited},
            visited_age_30 => $stat->{30}{visited},

            unvisited        => $stat->{male}{unvisited} + $stat->{female}{unvisited},
            unvisited_male   => $stat->{male}{unvisited},
            unvisited_female => $stat->{female}{unvisited},
            unvisited_age_10 => $stat->{10}{unvisited},
            unvisited_age_20 => $stat->{20}{unvisited},
            unvisited_age_30 => $stat->{30}{unvisited},

            event => 'seoul-2017',
        }
    );

    $dt->add( days => 1 );
}
```

    $ ubic restart opencloset.cron.visitor

서비스도 재시작 해주어야 온라인 이벤트 방문/미방문자 수를 수집합니다.

**Comment by aanoaa** [comment]
스크립트 돌려서 온라인 방문/미방문자 통계를 수집했고, 서비스를 재시작 하였습니다.
오늘부터는 온라인 이벤트 방문/미방문자의 숫자도 수집합니다.

**Comment by aanoaa** [comment]
통계가 오프라인/온라인으로 세분화되었습니다.
기본적으로는 오프라인+온라인 입니다.

- [전체](https://staff.theopencloset.net/stat/events/seoul-2017) 
- [온라인만](https://staff.theopencloset.net/stat/events/seoul-2017?online=1)
- [오프라인만](https://staff.theopencloset.net/stat/events/seoul-2017?online=0)

**Comment by aanoaa** [comment]
오늘 새벽에 모니터링 해보고 문제가 없다면,
취업날개 서비스를 사용한 온라인+오프라인 통계가 수집됩니다.

공식(A) 통계페이지와 열린옷장(B)의 수치가 다를 수 있는데 이는,

- A 에서 온라인(택배) 대여의 통계를 합산하지 않기 때문
- 그밖에 이슈가 있을 수 있습니다.

일일 수치가 맞지 않는 문제도 해결하였습니다.
B 의 오프라인 일일 수치가 A 와 다르다면 왜 다른지 원인파악을 해야 합니다.

----------------------------

오늘 모니터링 후에 문제가 없다면 이슈를 닫도록 하겠습니다.

**Comment by aanoaa** [comment]
> 온라인으로 쿠폰을 사용하였을때에 예약 상태를 변경해 주어야 합니다.

잊지말고 해야합니다.
지금까지 사용된 쿠폰에 대해서 반영해주어야 합니다.

하지만 배송비를 결제하지 않았을 경우는 열린옷장에서는 미방문으로 세는데 취업날개에는 대여완료(방문)로 되는 문제가 있습니다.

**Comment by aanoaa** [comment]
이벤트 통계 수집하는데 오류가 발생했습니다.
다른 이벤트와 방문자는 정상적으로 동작했고, linkstart 만 발생했습니다.

    2017-06-13 00:08:00.007642 +0900 info  main: insert_event_linkstart_daily[08 00 * * *] launched
    unhandled callback exception on event (start, OpenCloset::Cron=HASH(0x28af1f0), ): DBIx::Class::Row::store_column(): No such column 'visited_rate_30_disstat' on OpenCloset::Schema::Result::Visitor at /path/to/bin/opencloset-cron-visitor.pl line 168

**Comment by aanoaa** [comment]
오타입니다. 편집기로 count 를 stat 으로 일괄변경하면서

    visited_rate_30_discount -> visited_rate_30_disstat

으로 변경되었습니다.

**Comment by aanoaa** [comment]
linkstart 오류 수정해서 배포하였습니다.

[OpenCloset-Cron-Visitor-v0.2.1.tar.gz](https://cpan.theopencloset.net/STAFF@THEOPENCLOSET.NET/OpenCloset-Cron-Visitor-v0.2.1.tar.gz)

**Comment by aanoaa** [comment]
서버에 반영하고 서비스 재시작 해주었습니다.

**Comment by aanoaa** [comment]
> 온라인으로 쿠폰을 사용하였을때에 예약 상태를 변경해 주어야 합니다.

대여가 될때 상태를 변경하는 것이 아니라, 하루 한번 모아서 상태를 변경해 주고 있습니다.
온라인 대여에서도 마찬가지로 하루 한번 상태를 모아서 변경해주면 될 것 같습니다.

**Comment by aanoaa** [comment]
아래 스크립트를 돌려서 취업날개를 통한 온라인 대여자의 상태를 반영시켰습니다.

``` perl
use strict;
use warnings;
use DateTime;
use Data::Dump;

use OpenCloset::Schema;
use OpenCloset::Events::EmploymentWing;
use OpenCloset::Constants::Status qw/$RENTAL $RETURNED/;

my $schema = OpenCloset::Schema->connect({ ... });

my $tz   = 'Asia/Seoul';
my $date = DateTime->new(
    year      => 2017,
    month     => 5,
    day       => 22,
    time_zone => $tz
);

my $end = DateTime->now( time_zone => $tz )->subtract( days => 1 );
my $client = OpenCloset::Events::EmploymentWing->new;

while ( $date <= $end ) {
    my $rs = $schema->resultset('Order')->search(
        {
            'me.online'      => 1,
            'me.rental_date' => {
                -between => [
                    $date->datetime,
                    $date->clone->add( days => 1 )->subtract( seconds => 1 )->datetime
                ]
            },
            'me.status_id' => { -in => [ $RENTAL, $RETURNED ] }, # 대여중 혹은 반납
            'coupon.status' => 'used',
            'coupon.desc'   => { -like => 'seoul-2017%' },
        },
        {
            select => ['coupon.desc'],
            as     => ['desc'],
            join   => 'coupon'
        }
    );

    my %count;
    while ( my $row = $rs->next ) {
        my $desc = $row->get_column('desc');
        my ( $event, $rent_num, $mbersn ) = split /\|/, $desc;
        next if $event eq 'seoul-2017';

        my $success = $client->update_status( $rent_num, $EW_STATUS_COMPLETE );

        unless ($success) {
            printf STDERR "[%s] Failed to update status to %d: %s", $date->ymd, $EW_STATUS_COMPLETE, $desc;

            $count{fail}++;
            sleep(1);
            next;
        }

        $count{success}++;
        sleep(1);
    }

    $date->add( days => 1 );

    print $date->ymd, "\n";
    dd %count;
}
```

**Comment by aanoaa** [comment]
취업날개 온라인 상태를 변경시키는 [OpenCloset-Cron-Event-v0.0.4.tar.gz](https://cpan.theopencloset.net/STAFF@THEOPENCLOSET.NET/OpenCloset-Cron-Event-v0.0.4.tar.gz) 배포하였습니다.

**Comment by aanoaa** [comment]
$ ubic restart opencloset.cron.event

적용하였습니다.

**Comment by aanoaa** [comment]
와 드디어 이슈가 끝났습니다. :smile:

**Comment by 10001if** [comment]
@aanoaa 고생 많으셨습니다. ㅠ

**Comment by aanoaa** [comment]
와 이거 @pingpongworks 님이 물어봐서 다시 읽어봤는데 정리를 참 잘해놨습니다.
self 칭찬 @aanoaa++
