### ISSUE TITLE
링크스타트 이벤트 통계 페이지 로그인

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1258]
링크스타트 이벤트 통계 페이지에 로그인 없이 들어갈 수가 없네요. 
링크스타트에서 들어가 보려다 못 들어가셨다고 하네요. 확인부탁드려요~

**Comment by aanoaa** [comment]
더이상 서울시에서 취업날개 통계를 볼 필요가 없어져서 모든 이벤트의 통계를 staff 만 볼 수 있도록 수정되었습니다.
linkstart 는 아직 한명도 이용하지 않았습니다.

현재는 로그인 이후에 `staff` or `not staff` 으로 분류되고 있습니다.
계정마다의 권한을 세분화하려면 볼륨이 있는 작업이 필요합니다.

@pingpongworks 링크스타트의 경우 이전과 마찬가지로 로그인 없이 볼 수 있는 통계화면이 필요한가요?

**Comment by aanoaa** [comment]
권한 이런거 상관없이 외부인(링크스타트에서)이 볼 수 있는 채널이 필요하다고 합니다.

**Comment by aanoaa** [comment]
`/events/linkstart/stat` 에서 인증없이 통계를 볼 수 있습니다.

**Comment by aanoaa** [comment]
@pingpongworks https://visit.theopencloset.net/events/linkstart/stat 입니다.

**Comment by pingpongworks** [comment]
링크스타트에 전달했습니다. 감사합니다^^

**Comment by pingpongworks** [comment]
링크스타트 통계페이지에 
주문서 금액만 표기되고 
30% 할인 가격이 표기되지 않습니다.
30% 할인가격이 표기되어야 나중에 정산할 때 편리합니다. 
아직 이용이 매우 저조해서 급하지 않으니까
시간 나실 때 수정 부탁드립니다. @aanoaa
