### ISSUE TITLE
취업날개 쿠폰 결제 장애

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1259]
![52a36e3323ccbb895a22bc88eddb863e](https://user-images.githubusercontent.com/17288038/26859283-a49b5222-4b71-11e7-8368-f498cbc9aa6b.jpg)

취업날개로 예약하신 분들이 결제할 때 사용된 쿠폰의 금액이 0원으로 뜨고 있습니다. 일단 수동으로 금액을 변경하고 있습니다만, 빠른 장애 해결 부탁드립니다~

**Comment by keedi** [comment]
해당 이슈가언제부터 발생한 것인지요? 5월 22일 부터인지요?

**Comment by pingpongworks** [comment]
아닙니다. 월요일까지 문제없었는데, 오늘 아침부터 발생했습니다.
하단에 단벌 할인쿠폰 항목이 새로 생겼는데, 그 문제인 듯 합니다.
![image](https://user-images.githubusercontent.com/17288038/26859947-16ccbb3e-4b76-11e7-8630-80c8d43a9517.png)

**Comment by keedi** [comment]
@aanoaa  OpenCloset-Plugin-Helpers v0.0.21 이슈인 것 같은데 이야기 나눠보셔야 할 것 같습니다.

**Comment by aanoaa** [comment]
https://github.com/opencloset/OpenCloset-Share-Web/issues/157

의 영향입니다

구체적으로는 위 이슈를 해결하기위해서 discount_order 를 변경했습니다.

**Comment by aanoaa** [comment]
단벌쿠폰을 사용해서 32,000 원이 결제금액에서 빠집니다. 실제로 받는 금액이 없으니 0원이 맞지 않나요?

어디가 어떻게 되어야 하는데 지금은 이렇다

라고 설명을 붙여주세요

**Comment by keedi** [comment]
@pingpongworks 자세한 설명이 필요할 것 같습니다~ 확인 부탁드려요.

**Comment by pingpongworks** [comment]
@keedi @aanoaa '단벌할인쿠폰' 항목을 모두들 처음 봐서요,,, 온라인의 suit타입 쿠폰 문제가 해결된 것과 연관지어서 생각을 미처 못했습니다. 어쨋든 쿠폰이 정상적으로 사용된 것이라면 0원이든 금액이 뜨든 문제는 없을 듯 합니다.  금액 관련해서 수정이 필요하면 @10001if 과 논의한 후 다시 말씀드리겠습니다.

**Comment by aanoaa** [comment]
수트 타입의 쿠폰은 금액을 산정하지 않았엇는데, 지난 패치때에 3박 4일 기준으로 대여한 품목만큼 금액을 산정해서 할인해주는 방식으로 바뀌었습니다. 충분하게 논의 하지 않고 반영해서 혼란이 있는 것 같습니다. 오후에 방문해서 내용을 자세하게 듣도록 하겠습니다.

**Comment by pingpongworks** [comment]
기본적으로는 0원으로 처리되는게 전혀 문제가 없을 것 같습니다. 기간을 연장하는 경우, 연장비용만 표기되는다는 설명을 @aanoaa 님에게 들었습니다. 오히려 추가비용을 정산하기가 더 편리할 것 같습니다.  문제가 없으므로 이슈 닫겠습니다~

**Comment by aanoaa** [comment]
수트 타입의 쿠폰은 지금까지 대여비를 무시하고 결제를 했습니다.
대여비를 그대로 표시해주고 결제금액을 받지 않는 방식이었습니다.

- 연장비와 배송비가 고려되지 않았습니다.

-----------------

이 방식이 변경되었습니다.
쿠폰타입에 따라서 할인되는 금액이 표시되고, 결제해야할 금액이 대여비가 됩니다.

대여비 30,000원 주문서의 경우

- `10,000원` 쿠폰을 사용 했을때의 대여비: 20,000
- `10%` 쿠폰을 사용 했을때의 대여비: 27,000
- `단벌` 쿠폰을 사용 했을때의 대여비: 0

-----------------

대여기간에 대해서도 결제해야 할 금액이 표시되도록 변경되었습니다.

대여비 30,000원 주문서를 1일 연장했을 경우 대여비는 30,000(대여비) + 6,000(연장비) 입니다.

- `10,000원` 쿠폰을 사용 했을때의 대여비: 26,000
- `10%` 쿠폰을 사용 했을때의 대여비: 33,000 (아마도? 모르겠습니다 이건..)
- `단벌` 쿠폰을 사용 했을때의 대여비: 6,000

-----------------

결제에 장애가 있었던 것은 아니고,
대여비 표시 방법이 변경된 것 입니다.
위에 내용을 정리했습니다.
궁금한 점은 남겨주시기 바랍니다.

결론입니다.

결제방법과 상관없이 대여비에 표시된 금액은 쿠폰타입과 연장비, 배송비를 고려해서 지불해야 할 금액입니다.

**Comment by pingpongworks** [comment]
네~ 확인했습니다
