### ISSUE TITLE
관악고용 쿠폰발행

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1260]
기존에 진행하던 이벤트 중 '관악고용' 의 쿠폰기간이 만료되어 다시 한번 쿠폰 발행을 요청합니다. 

- 총 50장
- 남 32000 한 세트, 여 30000원 한 세트 무료대여
- 기간 : 2017년 6월 7일~2018년 6월 7일

종전과 같이 쿠폰 페이지에 쿠폰번호 입력하는 형식으로 진행할 예정입니다.
https://visit.theopencloset.net/coupon

**Comment by aanoaa** [comment]
- type: suit
- desc: gwanak
- expires: 2018-06-07T23:59:59

50장 발행해서 email 로 전달해드렸습니다.

**Comment by pingpongworks** [comment]
잘 받았습니다. 감사합니다^^
