### ISSUE TITLE
취업날개 5002 오류

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#1263]
> 5002번 오류가 발생하는 대표적인 경우는 사용자 개인 정보, 특히 전화번호나 전자우편 주소가
> 다를 때 발생하므로 관련해서 취업날개 쪽 정보를 수정할지, 아니면 열린옷장 정보를 수정할지
> 판단해서 이후 처리를 진행해야 하는 부분입니다.

취업날개와 열린옷장의 개인정보가 달라서 발생하는 문제입니다.

서울시 -> inetpia -> silex 로 연락이 왔습니다.

해결방안을 찾아야 하는데,

**email, 성별, 생년을 덮어써서 5002 오류를 해결하자.** 라는게 @10001if 님 의견입니다.

**Comment by keedi** [comment]
coupon 쪽에서 처리할 내용이므로 이쪽에서는 이슈 닫습니다.
