### ISSUE TITLE
3회 이상 대여시 연장/연체비 적용은 할인된 금액을 기준으로 적용되도록 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1264]
3회 이상 대여시 일정기준에 따라 대여금액의 할인을 해주고 있습니다.
기본적으로 연장/연체비는 대여비에 20%/30%로 적용되고 있지만, 3회 이상 대여시에는 할인된 금액을 기준으로 적용되도록 요청드립니다. 온라인/오프라인 대여 모두 적용되어야 합니다.

**Comment by aanoaa** [comment]
할인대상자에게는 연장/연체비를 할인된 금액으로 적용해야 하는 이슈입니다.
3회이상 대여자에게 열린옷장 정책에 맞게 대여비를 할인해주는 제도가 있습니다.

[suit 타입의 쿠폰을 사용한 후에 배송비를 결제해야 함](https://github.com/opencloset/OpenCloset-Share-Web/issues/157) 이슈의 연장입니다.

    할인대상자가 대여기간을 연장하고자 할때,
    32,000(대여비) + 12,800(+2일 연장 40%) - 12,000(3회 이상 대여 할인)    # 오프라인(32,800), 온라인(35,800 = 대여비 32,800 + 배송비 3,000)

현재는 이렇게 계산되고 있는데 틀렸습니다.
연장비 계산법이 `대여비의 20% * 연장일` 이 아니라, `(대여비 - 할인금액) * 연장일` 이어야 합니다.

올바른 금액 계산법은

    할인대상자가 대여기간을 연장하고자 할때,
    32,000(대여비) - 12,000(3회 이상 대여 할인) + 8,000(+2일 연장 40%)     # 오프라인(28,000), 온라인(31,000 = 대여비 28,000 + 배송비 3,000)

**Comment by aanoaa** [comment]
연장료는 주문할때에 결제하기 때문에 `discount_order` 에서 처리하면 됩니다.
연체료 계산법도 확인해서 적용해야 합니다.

**Comment by aanoaa** [comment]
오프라인에서는 각 의류의 대여비 항목에 `의류의 대여비 * 0.2 * 연장일` 을 적용합니다.

3외 이상 대여자가 자켓, 팬츠, 셔츠, 구두를 대여했을경우에
대여비는 기본 대여비는 `20,000` 입니다.(셋트 이외 무료를 적용) 

    자켓: 10,000
    팬츠: 10,000
    셔츠: 0
    구두: 0

2일 연장했을때,

    자켓: 14,000
    팬츠: 14,000
    셔츠: 0
    구두: 0

으로 적용됩니다.

온라인에서는 총 `대여비 * 0.2 * 연장일` 항목을 추가 합니다.

    자켓: 10,000
    팬츠: 10,000
    셔츠: 0
    구두: 0
    2일 연장비: 8,000

**Comment by aanoaa** [comment]
미납금 계산모듈에서 할인금액을 제외한 금액을 제외한 금액을 기준으로 연장비를 계산하면 될 줄 알았는데 생각보다 복잡합니다.

- 온라인과 오프라인에서 연장비를 기록하는 방식이 다릅니다.
- 기록하는 방식에 따라서 연장비 계산 방식이 달라져야 합니다.
- 미납금 안내문자를 보낼때 옛날 계산 방식을 사용합니다.

예측하지 못한 상황이 더 있을 수 있습니다.
각 상황별로 연장/연체비 계산을 했을때 같은 금액이 나와야 합니다.

**Comment by aanoaa** [comment]
복잡한 이유는 연장비로만 생각했는데, 할인이 먼저 고려되어야 하기 때문입니다.

오프라인은 할인금액과 연장금액이 각 의류카테고리마다 적용되지만,
온라인에서는 할인금액과 연장금액이 따로 기록됩니다.

    자켓: 10,000
    팬츠: 10,000
    셔츠:  5,000

3회 이상 대여 할인 오프라인

    자켓: 10,000
    팬츠: 10,000
    셔츠:      0

3회 이상 대여 할인 온라인

    자켓: 10,000
    팬츠: 10,000
    셔츠:  5,000
    할인: -5,000

여기에서 2일 연장 오프라인

    자켓: 14,000
    팬츠: 14,000
    셔츠:      0

2일 연장 온라인

    자켓: 10,000
    팬츠: 10,000
    셔츠:  5,000
    할인: -5,000
    연장:  8,000

------------------------

하지만 미납금문자를 보낼때는 온라인 오프라인 주문서를 구분하지 않습니다.
온라인/오프라인 주문서별로 계산방식이 달라야 합니다.

**Comment by aanoaa** [comment]
할인쿠폰의 경우에도 할인 후 금액을 대여비로 책정해야 한다고 합니다.

10,000 원일때에 30% 쿠폰을 쓰면 대여비는 7,000 원이고 이것을 기준으로 연장/연체비를 계산해야 합니다.

**Comment by 10001if** [comment]
@aanoaa 할인쿠폰은 생까도 못했네요.. 30% 쿠폰이 생각보다 많은 이슈랑 연관되어 있네요..

**Comment by aanoaa** [comment]
주문서 상세 화면에서 `택배발송/반납일` 이 변함에 따라 연장료/연체료를 계산합니다.
이를 직접 계산하지 않고 서버와 통신한 값을 받아서 처리하도록 바꿔야 하겠습니다.

바꿔야 하는 곳은 `coffee/order-id.coffee` 의 `updateLateFee` 입니다.

이게 우선 적용되어야 반납후에 미납금이 할인금액을 제외한 금액을 기준으로 책정됩니다.
이후에는 OpenCloset-Cron-Unpaid 에서 미납금에 대해 가상계좌를 만드는데, 이때에는 반납할때 계산된 미납금이 그대로 사용되기 때문에 문제가 없습니다.

**Comment by aanoaa** [comment]
연장비/연체비는 `API#api_get_order` 에서 하는데 여기에서 `flatten_order` helper 를 사용합니다.
`flatten_order` helper 에서는 `OpenCloset::Calculator::LateFee` 를 활용해서 연장비/연체비를 계산하도록 되어있기 때문에 변경없이 적용가능합니다.

**Comment by 10001if** [comment]
혹시 #1275 #1274 이슈가 이것과 관계 되어 있나 싶어 이슈는 우선순위에서 삭제하지 않았습니다.
