### ISSUE TITLE
영업시간의 변경

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#1266]
점심시간이 기존 13:00 ~ 14:00 였는데, 12:30 ~ 14:00 로 변경되었습니다.

관련된 곳을 찾아서 바꾸어 줘야 합니다.

- https://donation.theopencloset.net/guide1

**Comment by aanoaa** [comment]
https://github.com/opencloset/donation/commit/03f305179b5e188e8daf224b9bcec89ac9985093

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
