### ISSUE TITLE
구두, 벨트, 스커트, 타이 바코드 생성 요청드립니다.

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1267]
구두 1000개
벨트 1000개
스커트 2000개
타이 1000개

@aanoaa 바코드 생성 요청드립니다.

**Comment by aanoaa** [comment]
https://github.com/opencloset/donation/files/1090606/codes.zip

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
