### ISSUE TITLE
주문서의 상태는 대여중인데, 의류의 상태가 대여중이 아닌 오류

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1268]
~/order/64667 의 경우 대여자가 반납을 하였지만 반납처리가 되어 있지 않고, 주문서 상의 의류들은 대여가능이거나 포장 취소 상태입니다. 확인 부탁드립니다.

**Comment by 10001if** [comment]
@aanoaa 혹시 몰라 아직 반납처리를 하지 않은 상태라고 합니다. 우선 반납이 된 것은 맞는 것으로 보이는데, 반납처리를 해도 될까요? 아니라면 연체문자 전송만 끈 상태로 문제가 해결되면 반납처리 하도록 하겠습니다.

**Comment by aanoaa** [comment]
정상적인 프로세스로 반납처리를 하였는데 주문서의 상태가 변경되지 아니한 것 같습니다.

**Comment by aanoaa** [comment]
주문서의 상태가 대여중이었는데

- `J0TH - 재킷`
- `K04J - 치마`
- `B0Q8 - 블라우스`

의 상태는 대여가능 상태였습니다.

**Comment by 10001if** [comment]
대여중인 주문서에 포함되어 있는 의류가 대여중이 아니라 포장취소나 대여가능 상태인 것이 문제라고 생각되어집니다.

**Comment by aanoaa** [comment]
제가 직접 전체반납을 하였습니다.

**Comment by aanoaa** [comment]
해당 주문서의 로그를 찾아봤는데, 16일과 20일 로그가 있습니다.
16일은 대여했을때의 기록이고,
20일이 반납했을때의 기록입니다.

```
[Tue Jun 20 12:27:19 2017] [debug] PUT "/api/order/64667.json"
[Tue Jun 20 12:41:41 2017] [debug] PUT "/api/order/64667.json"
```

눈여겨 볼것은 이거 두개인데, `12:41:41` 는 제가 반납처리한 기록입니다.

```
[Tue Jun 20 12:27:19 2017] [debug] PUT "/api/order/64667.json"
[Tue Jun 20 12:27:19 2017] [debug] Routing to controller "OpenCloset::Web::Controller::User" and action "auth" 
[Tue Jun 20 12:27:19 2017] [debug] Routing to controller "OpenCloset::Web::Controller::API" and action "api_update_order"
[Tue Jun 20 12:27:19 2017] [debug] 200 OK (0.082355s, 12.143/s)
```
에러는 발생하지 않았습니다.

트랜잭션을 걸어두지 않았다면 주문서의 상태만 바뀌고 의류의 상태는 바뀌지 않았을 가능성도 있습니다.

**Comment by aanoaa** [comment]
모르겠습니다.
찾기 어려울 것 같습니다.

다시 발생한다면 반납처리하지 않고 살펴봐야 하겠습니다.

**Comment by 10001if** [comment]
@aanoaa 5층에서 박선*님의 의류를 포장하는 과정에서 그 시기에 동시에 4층에서 이름이 동일한 윤선*(64703)님이 취업날개 연장을 희망하셔서 기존 주문서를 반납처리하고 다시 예약하여 기존 주문서의 품목을 복사하여 포장을 하고 있었습니다. 그런데 5층에서 이름을 착학하여 박선*님의 이름을 클릭해야 하지만 윤선*님의 이름을 클릭하여 실수로 포장완료하였고 결제대기 상태로 바꾸었습니다.

그런데 이후 포장이 잘못되었다는 사실을 알게되었고, 5층에서 기존 주문서를 새로주문 하였습니다. 그 이후 5층에서 정상적으로 박선*님의 이름으로 포장과 결제를 완료하였고, 4층에서는 윤선*님의 포장과 결제를 완료하였습니다. 

이것과 관련해서 이슈가 발생한 것인지 싶어 남겨놓습니다.
