### ISSUE TITLE
대여회전율 검색이 되지 않음

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1269]
통계메뉴 내에 있는 `대여회전율`이 작동하지 않습니다.
확인 요청드립니다.

**Comment by aanoaa** [comment]
```
$ ack CACHE lib/
lib/OpenCloset/Web/Controller/Statistic.pm
12:has CACHE => sub { shift->app->CACHE };
521:    my $cached = $self->CACHE->get($name) || [];
667:            $data = $self->CACHE->get($name);
709:            $data = $self->CACHE->get($name);
742:            $data = $self->CACHE->get($name);
796:            $data = $self->CACHE->get($name);
```

캐시가 비어서 일까요?

캐시를 가져오는 코드만 있지, 캐시에 넣어주는 코드는 안보입니다.
일정시간마다 주기적으로 돌리는 코드가 있는지 살펴봐야 합니다.

**Comment by aanoaa** [comment]
https://github.com/opencloset/opencloset/issues/540#issuecomment-231574873

> 새벽 2시 10분에 대여 회전율 관련 연산을 매일 연산후 캐싱하도록 실서버에 설정했습니다.

**Comment by aanoaa** [comment]
`bin/opencloset-stat-clothes-rent-cache.pl` 파일이 cache 에 데이터를 넣는 스크립트입니다.
직접 실행해봤는데,

    Can't call method "create_date" on an undefined value at /path/to/OpenCloset/Schema/Result/Clothes.pm line 492.

오류가 발생하고 있었습니다.
이것 때문에 캐시가 비었고 대여회전율이 수집안된 것 같습니다.

**Comment by aanoaa** [comment]
의류 `S2BD` 는 `donation_id` 가 `NULL` 이라서

    $self->donation->create_date->clone;

에서 `$self->donation` 이 `undef` 입니다.

`clothes` 테이블에서 `donation_id` 가 NULL 인 것은 저거 한개입니다.

**Comment by aanoaa** [comment]
등록된 의류는 23,000 여개가 넘는데 9000번대의 id 입니다.
의류등록 프로그램에 오류가 있을때 등록된게 아닐까 싶습니다.

기증없는 의류는 있을 수 없는데..

저 의류가 실제로 사용된다면 어디에서든 `undef` 오류가 발생했을 것으로 생각됩니다.

---------------

그냥 삭제 하자니, 등록된 의류가 삭제된 이후에 사용되어도 문제가 발생할 것 같기 때문입니다.
그렇다고해서 코드만 가지고 추적할 수도 없습니다.

**Comment by aanoaa** [comment]
```
             id: 9070
    donation_id: NULL
      status_id: 1
       group_id: 4858
           code: 0S2BD
           neck: 41
           bust: 112
          waist: 0
            hip: 0
       topbelly: 0
          belly: 0
            arm: 64
          thigh: 0
         length: 0
           cuff: NULL
          color: white
         gender: male
       category: shirt
          price: 5000
        comment: NULL
compatible_code: NULL
```

삭제하도록 하겠습니다.

```
mysql> DELETE FROM clothes WHERE donation_id IS NULL;
Query OK, 1 row affected (0.53 sec)
```

**Comment by aanoaa** [comment]
잘못된 데이터를 삭제했으니 대여회전율 수집 프로그램이 제대로 동작할 것 같습니다.
익일 대여회전율이 검색되는지 확인해보겠습니다.

**Comment by 10001if** [comment]
정상적으로 잘 작동하고 있습니다. 감사합니다.

**Comment by 10001if** [comment]
이슈 닫겠습니다.
