### ISSUE TITLE
수량 페이지에 검색이 가능하도록 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1270]
최근에 의류 기증량이 많아지면서 필요한 의류와 그렇지 않은 의류를 분류해야 하는 이슈가 발생하고 있습니다. 이와는 별개로 특이한 사이즈에 대해서 주문을 하여 부족한 수량을 채우는 작업을 진행하려고 합니다. 그럴 때 의류 수량을 확인하는 것이 매우 중요한데, 현재는 의류 수량을 확인할 수는 있지만 가용 수량만을 확인 할 수 있습니다.

가용 수량은 대여가능, 대여중, 대여불가, 세탁, 수선, 반납 상태를 의미합니다. 그런데 전체 수량을 확인하는데에는 용이하지만 필요한 수량을 확인 할 수는 없습니다. 따라서 `대여회전율`메뉴처럼 필요한 정보를 개별적으로 확인하고 싶습니다. 

1.`성별` 2.`종류` 3.`상태` 이 3가지 조건으로 수량을 확인하고자 합니다.

1. 성별 (복수 선택가능)
남성, 여성

2. 종류 (복수 선택가능)
가방, 벨트, 블라우스, 코트, 재킷, misc, 원피스, 바지, 셔츠, 신발, 치마, 넥타이, 조끼

3. 상태 (복수 선택가능)
대여가능, 대여중, 대여불가, 예약, 세탁, 수선, 반납, 부분반납, 반납배송중, 치수측정, 의류준비, 포장, 결제대기

위와 같은 조건으로 원하는 성별/종류/상태별로 수량을 확인하고 싶습니다.

**Comment by aanoaa** [comment]
/stat/clothes/amount

수량페이지는 위 route 얘기하는 것 입니다.

**Comment by aanoaa** [comment]
성별/종류/상태가 한번에 나오고 있는 것 같은데 저걸 추려서 보고 싶단 말씀이신가요?

> 특이한 사이즈에 대해서 주문을 하여 부족한 수량을 채우는 작업을 진행하려고 합니다

사이즈별 검색이 필요하신게 아닌가요?

내용을 이해하지 못했습니다.

**Comment by 10001if** [comment]
@aanoaa 핵심은 현재 보여지는 전체 수량은 상태가 가용수량을 의미하고 그 가용수량 그대로를 보고 있다는 점입니다. 
가용수량은 열린옷장에서 사용한다고 판단되어지는 의류를 말하는데, 그 안에서 대여중인 의류나 대여가능 의류나 반납 의류들을 따로 볼 수는 없습니다. 상황에 따라 수량을 파악해야 하는 이슈가 달라지는데 통계에서는 고정적으로 가용수량만 확인할 수 있기 때문에 수정을 요청드렸습니다~

**Comment by aanoaa** [comment]
@10001if 

1. 남성(성별), 자켓(품목), 대여중(상태) 로 검색했을때에 어떠한 결과가 나타나야 하나요?
2. 여성(성별), 자켓(품목) 으로 검색했을때에 어떠한 결과가 나타나야 하나요?
3. 자켓(품목) 으로 검색했을때에 어떠한 결과가 나타나야 하나요?

**Comment by 10001if** [comment]
![2017-09-13 2 32 57](https://user-images.githubusercontent.com/4696328/30361241-dac40e86-9890-11e7-9b09-0f2e2fc9e16a.png)
이렇게 검색을 시도합니다.

그러면, 

성별 | 품목 | 총수량 | 대여중 | 반납 | 대여불가 | 
-- | -- | -- | -- | -- | -- | 
남성 | 자켓 | 20 | 10 | 5 | 5 | 
남성 | 셔츠 | 100 | 50 | 30 | 20 | 
여성 | 블라우스 | 100 | 70 | 10 | 20 | 
합계 | -- | 220 | 160 | 105 | 45 | 

이렇게 결과를 보고 싶습니다.

**Comment by 10001if** [comment]
대여회전율에서는 재킷, 성별이 복수 선택이 되지 않습니다.
그런데 복수 선택이 꼭 필요한지 의문이 듭니다. 전체 정보를 보는 일이 실제로 많지 않기 때문입니다.

**Comment by aanoaa** [comment]
`재킷/남성/대여가능,대여중,대여불가...` 를 검색했는데,

여성 블라우스의 총수량과 상태별 수량이 나타나야 하나요?

**Comment by 10001if** [comment]
@aanoaa 수정하겠습니다. 불필요한 작업을 요청드리는 것보다 필요한 작업을 요청드리는게 좋을 것 같습니다. 

위의 대여회전율과 같이 검색하도록 하는 것을 가정하면


성별 | 품목 | 총수량 | 대여중 | 반납 | 대여불가 | 
-- | -- | -- | -- | -- | -- | 
남성 | 자켓 | 20 | 10 | 5 | 5 | 

이렇게 한개의 데이터만 나올 수 있도록 요청드립니다. 

현재 데이터는 아래에 그대로 두고 꼭 필요한 정보만 위쪽에서 수시로 확인하겠습니다.

**Comment by 10001if** [comment]
@aanoaa 
>재킷/남성/대여가능,대여중,대여불가... 를 검색했는데,
여성 블라우스의 총수량과 상태별 수량이 나타나야 하나요?

이 경우에는 

성별 | 품목 | 총수량 | 대여중 | 반납 | 대여불가 | 
-- | -- | -- | -- | -- | -- | 
남성 | 자켓 | 20 | 10 | 5 | 5 | 

나오면 됩니다.

**Comment by aanoaa** [comment]
상태가 더 많이 선택되었는데, 저렇게 3개만 나오면 되나요?

**Comment by 10001if** [comment]
@aanoaa 선택된 상태가 모두 나오도록 요청드립니다~!

**Comment by aanoaa** [comment]
현재 나타나고 있는 수량은 그대로 두고 검색 했을때에 말씀하신 추가 정보가 나타나면 되나요?

**Comment by aanoaa** [comment]
남성, 여성, 자켓, 팬츠가 선택되었다면,

성별 | 품목 | 총수량 | 대여가능 | 대여중 | 대여불가 | 
-- | -- | -- | -- | -- | -- | 
남성 | 자켓 | 20 | 10 | 5 | 5 | 
여성 | 자켓 | 20 | 10 | 5 | 5 | 
남성 | 팬츠 | 20 | 10 | 5 | 5 | 
여성 | 팬츠 | 20 | 10 | 5 | 5 | 

1. 이렇게 나오는 게 맞나요?
2. 상태가 선택이 안되면 어떻게 하나요?

**Comment by 10001if** [comment]
@aanoaa 
>1. 이렇게 나오는 게 맞나요?

네. 맞습니다.

>2. 상태가 선택이 안되면 어떻게 하나요?

선택이 안된다는 게 무슨 뜻인지 모르겠습니다. 상태가 존재하지 않는 다는 건가요?

**Comment by 10001if** [comment]
> 현재 나타나고 있는 수량은 그대로 두고 검색 했을때에 말씀하신 추가 정보가 나타나면 되나요?

네. 맞습니다.

**Comment by aanoaa** [comment]
중복선택 가능하다고 하셨으니 선택이 안될 수도 있지 않느냐입니다.

단순히 대여중만 선택하고 검색한다면 어떻게 나와야 하나요?

**Comment by aanoaa** [comment]
1. 성별 (단수)
남성, 여성

2. 종류 (단수)
가방, 벨트, 블라우스, 코트, 재킷, misc, 원피스, 바지, 셔츠, 신발, 치마, 넥타이, 조끼

3. 상태 (복수 선택가능)
대여가능, 대여중, 대여불가, 예약, 세탁, 수선, 반납, 부분반납, 반납배송중, 치수측정, 의류준비, 포장, 결제대기
선택안되었을때는 모두

라고 합니다.

**Comment by aanoaa** [comment]
![default](https://user-images.githubusercontent.com/170528/30365265-2a845064-98a2-11e7-936a-11b876f2ec75.png)

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
