### ISSUE TITLE
폐기의류의 장소추가

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#1273]
![j41i](https://user-images.githubusercontent.com/170528/27464830-7de74dac-580a-11e7-98be-c0a3eee72efb.png)

의류가 다른곳으로 재활용될때에 목적지를 선택할 수 있는 기능이 있습니다.

- 옷캔
- 비백

이 있었는데, `비전` 이 추가되어야 합니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
