### ISSUE TITLE
반납을 하지 않았는데 이미 반납으로 되어 있는 문제

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1274]
~/order/65508 김진*님

<상황설명>
1. 무인반납함에서 수트케이스를 꺼내 첫화면에서 자켓의 코드를 입력
2. 주문서로 들어감
3. 반납을 하지 않았는데 반납으로 되어 있음

실제 주문서를 보면 오늘(24일) 오후 3시 경에 반납이 되어 있는 것으로 확인이 되는데
반납을 시도한 시점은 4시 20분 경입니다. 

그 전에는 반납을 한 적이 없다고 하는데 이게 왜 이런 문제가 생겼는지 확인을 부탁드립니다. 

이 한 건이 아니라 2일 전(?) 정도 부터 약 5건 정도가 발견되었다고 합니다.
추측으로는 취업날개와 영향이 있는 것이 아닌가 싶은데요. 그냥 추정입니다.

확인 부탁드립니다. @aanoaa

**Comment by aanoaa** [comment]
해당 주문서의 상태변경 이력입니다.

```
+--------------+---------------------+
| name         | timestamp           |
+--------------+---------------------+
| 방문예약     | 2017-06-23 10:14:44 |
| 방문         | 2017-06-23 16:02:26 |
| 치수측정     | 2017-06-23 16:04:30 |
| 의류준비     | 2017-06-23 16:07:05 |
| 탈의07       | 2017-06-23 16:09:55 |
| 의류준비     | 2017-06-23 16:22:09 |
| 탈의07       | 2017-06-23 16:22:19 |
| 포장         | 2017-06-23 16:24:14 |
| 포장완료     | 2017-06-23 16:26:41 |
| 결제대기     | 2017-06-23 16:28:23 |
| 대여중       | 2017-06-23 16:29:49 |
| 반납         | 2017-06-24 15:56:45 |
+--------------+---------------------+
```

**Comment by aanoaa** [comment]
@10001if 주문서만 반납인가요 아님 대여한 의류들도 반납 인가요?

**Comment by 10001if** [comment]
@aanoaa 대여한 의류도 반납입니다.

**Comment by aanoaa** [comment]
`대여중`인 주문서를 `전체반납`을 하지 않았음에도
주문서와 의류 모두 `반납` 으로 변경되어 있었다는 내용입니다.

여러건 발생한 것으로 보면 단순한 실수 같지는 않지만 추적하기 너무 어려운 작업인 것 같습니다.

인간의 실수 혹은 프로그램의 오류인데..

다시 같은 현상이 발견되면 알려주세요.
알려주신다고 해도 방법이 있는 것 같지는 않습니다.

**Comment by 10001if** [comment]
다시 이런 현상이 발견되면, 그 때 남기도록 하겠습니다!
