### ISSUE TITLE
취업날개쿠폰 이용자의 경우 연장비가 계산되지 않는 현상

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1275]
~/order/64680 최승*님

대여일:2017-06-16
반납 예정일:2017-06-19
반납희망일:2017-06-23
반납일: 2017-06-23
대여비 : 25,000원

이 경우 하루 연장비 5,000원 X 4일 이므로 20,000원의 연장료가 계산되어야 하지만 연장료 계산이 되지 않았습니다. 취업날개 연장 건에 한해 이런 이슈가 2일 전부터 발생하였다고 하는데요. 확인 부탁드립니다. @aanoaa 

![2017-06-24 4 47 48](https://user-images.githubusercontent.com/4696328/27506838-30cc6478-58fd-11e7-9f1d-ead5998a4e73.png)

**Comment by aanoaa** [comment]
64680 주문서의 대여일, 반납희망일, 반납일, 대여가격, 할인가격, 연체비, 연장비, 연체+연장비 입니다.

```
rental_date:      2017-06-16T00:00:00
user_target_date: 2017-06-23T00:00:00
return_date:      2017-06-23T16:27:11
price:            25000
discount_price:   -25000
overdue_fee:      0
ext_fee:          0
late_fee:         0
```

**Comment by aanoaa** [comment]
왜 할인가격이 25,000원 인지 알아보아야 합니다.

**Comment by aanoaa** [comment]
연장/연체료 계산기가 잘못되었습니다.

`단벌 할인쿠폰` 만큼 할인해주고 있습니다.
처음 의도는 목적은 `30% 할인쿠폰` 과 같은 경우에만 할인된 가격을 적용하려고 했던 것 입니다.

**Comment by aanoaa** [comment]
[취업날개쿠폰 이용자의 경우 연장비가 계산되지 않는 현상](https://github.com/opencloset/opencloset/issues/1275)

```
rental_date:      2017-06-16T00:00:00
user_target_date: 2017-06-23T00:00:00
return_date:      2017-06-23T16:27:11
price:            25000
discount_price:   -25000
overdue_fee:      0
ext_fee:          0
late_fee:         0
```

`discount_price: -25000` 이것이 문제입니다.
`단벌 할인쿠폰` 이 할인된 금액으로 계산되지 않아야 합니다.

**Comment by aanoaa** [comment]
[OpenCloset-Calculator-LateFee-v0.2.3.tar.gz](https://cpan.theopencloset.net/STAFF@THEOPENCLOSET.NET/OpenCloset-Calculator-LateFee-v0.2.3.tar.gz) 모듈을 사용해서 계산하면,

```
rental_date:      2017-06-16T00:00:00
user_target_date: 2017-06-23T00:00:00
return_date:      2017-06-23T16:27:11
price:            25000
discount_price:   0
overdue_fee:      0
ext_fee:          20000
late_fee:         20000
```

연장료 `20,000` 으로 계산됩니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^

**Comment by aanoaa** [comment]
`10,000원 할인쿠폰` 과 같은 경우를 고려하지 못했습니다.
