### ISSUE TITLE
새로운 결제 및 반납 화면의 구성

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#1277]
staff 의 결제화면은 구성이 많이 복잡해졌습니다.
더이상의 추가 기능은 유지보수를 더욱 더 어렵게 만들고 있습니다.

많은 문제가 해결되어 있는 화면이라서 레퍼런스로 삼고,
결제/반납에 대해 새로운 화면을 만드는게 더 나을 수 있습니다.
(이후에는 rental.theopencloset.net 으로 서비스를 분리)

결제(대여) 및 반납이 가능토록 하고,

주문서를 만들고 결제를 확정하고, 반납을 확정하는 등의 행위를 모듈로 구성해서
추후에 결제 및 반납등의 복잡한 절차를 재활용할 수 있게 한다면 유지보수가 용이해 질 것 같습니다.

**Comment by aanoaa** [comment]
[대리인을 통한 대여](#1066) 이슈를 해결하기 위한 과정이라고 생각합니다.

**Comment by aanoaa** [comment]
새로운 화면을 구성/테스트하기 위해서 `결제대기` 상태의 주문서가 필요합니다.
방문예약과정 및 포장까지의 절차는 기존 시스템을 활용하고,

- 포장 -> 포장완료
- 포장완료 -> 결제대기
- 결제대기 -> 대여

를 모듈로 구성해서 테스트를 더 간단히 하고자 합니다.

**Comment by aanoaa** [comment]
위 세개의 이슈가 해결되었습니다.
방문예약된 주문서를 가지고 아래와 같이 상태를 변경할 수 있습니다.

    $api->box2boxed($order, ['J001', 'P001']);    # 포장 -> 포장완료
    $api->boxed2payment($order);                  # 포장완료 -> 결제대기
    $api->payment2rental($order);                 # 결제대기 -> 대여중

각 상황에 맞춰서 몇가지 옵션이 있고, SMS 도 전송됩니다.
새로운 대여 및 반납 화면을 만들 준비가 되었습니다.

**Comment by aanoaa** [comment]
대여하기 위해서는 staff 서비스를 이용해야 하고 staff 서비스는 웹프로그램입니다.
(브라우저에서 로그인해서 값을 넣고 클릭하고 확정버튼등을 눌러야 합니다.)

이번작업은 staff 서비스의 몇가지 기능을 응용프로그램으로 포팅한 것 입니다.

테스트와 유지보수 재활용이 더 편리해 집니다.

**Comment by 10001if** [comment]
@aanoaa 고민할게 많으셨을텐데 혼자서 하시느라 고생이 많으시네요. 감사합니다.

**Comment by aanoaa** [comment]
![default](https://user-images.githubusercontent.com/170528/27776538-6f161b26-5fe6-11e7-9518-ece8274e4cd8.png)

결제대기 상태의 주문서에서는 여러가지 값을 바꾸는 일이 많습니다.

- 담당자(default: 로그인한 계정)
- 대여기간
- 결제방법
- 주문서 메모 5F
- 대여 메세지
- 반납 확인 메모 4F
- bestfit
- 각 대여품목의 가격 수정

등을 변경할 수 있어야 합니다.

추가로

- 정장 반납 안내 출력
- 상태 별 시각
- 상태 별 소요시간
- 쿠폰코드 입력
- 새로주문 기능
- 연체문자전송 toggle
- 검색결과에 포함됩니다 toggle
- 미납/불납자 표시

기능이 있습니다.

**Comment by aanoaa** [comment]
`결제대기` 일때와 `대여중` 일때 사용할 수 있는 기능이 다릅니다.
지금처럼 사용할 수 있도록 하되, js 처리를 줄이고 API 를 활용해서 더 간단하게 바꿔야 하겠습니다.

대여/반납 코드가 간단해지고 나면, 그 이후에 대리인 대여 기능을 고민해서 추가해야 하겠습니다.

**Comment by aanoaa** [comment]
브라우저로 결제대기 상태의 주문서를 들어가면,
주문서에 사용자정보를 복사하는 기능이 있습니다.
`결제대기 -> 대여중`으로 변경될때가 더 적절하지 않나 싶습니다.

**Comment by aanoaa** [comment]
대여비 계산에 대한 룰을 정확하게 해야하겠습니다.

연체료, 연장료가 대여비에 영향을 받고 결제전후 계산 방식이 다릅니다.
여기에 `3회 이상 대여 할인`, `쿠폰 타입에 따른 할인`의 변수도 있습니다.
배송비와 에누리 가격과 최종가격등 변수에 따른 공식을 세워둬야 하겠습니다.

- 대여금액
- 할인금액
- 최종금액(대여금액 - 할인금액)

을 알아야 합니다.

지금의 `OpenCloset-Calculator-LateFee` 에서 사용되고 있는 대여료 계산방식은

    대여가격: clothes.price 를 모두 더한 값
    할인가격: order_detail 에서 3회 이상 방문 아이템의 clothes.price 를 모두 더한 값(비율이라면 비율만큼 제외)

아..존나 복잡해..

-------------------------------

왜 문제가 되냐면, 대여가격은 order_detail 을 참고하지 않고 있는데 `결제대기` 상태에서 의류품목의 가격을 staff 이 수정할 수 있습니다.

대여가격에 이 수정된 값이 반영되어야 합니다.

**Comment by aanoaa** [comment]
### offline ###

- 포장완료 이후부터 대여금액을 계산할 수 있습니다.
- 대여품목마다 가격이 있습니다.(자켓, 팬츠등)
- 3회 이상 대여부터 대여품목에 따라 본래 가격에서 할인됩니다.
  - 대여품목의 가격이 변경됩니다.
- 쿠폰을 사용했다면 쿠폰타입에 따라 할인됩니다.
  - 쿠폰할인금액 항목이 추가됩니다.
  - 쿠폰 타입이 suit 라면 전체금액을 할인하지만 연체/연장비는 정상금액을 기준으로 합니다.
- staff 은 결제대기 상태에서 각 품목의 가격을 조정할 수 있습니다.

### online ###

- 주문서가 생성된 이후부터 대여금액을 계산할 수 있습니다.
  - 모든 상태에서 계산할 수 있습니다.
- 3회 이상 대여부터 대여품목에 따라 할인항목이 추가됩니다.
- 쿠폰을 사용했다면 쿠폰타입에 따라 할인됩니다.
  - 쿠폰할인금액 항목이 추가됩니다.
  - 쿠폰 타입이 suit 라면 전체금액을 할인하지만 연체/연장비는 정상금액을 기준으로 합니다.

------------------------------------

위 기준으로 아래 금액을 계산할 수 있는 공식을 만들어야 합니다.

- 정상금액
- 할인금액
- 대여금액(정상금액 - 할인금액)
- 연체금액
- 연장금액

------------------------------------

이게 반납전/후의 연체비/연장비가 다를 수 있습니다.
반납전에는 정상가를 기준으로 연체비/연장비를 산정하지만,
반납할때 에누리 되었다면 반납후에는 미납금을 에누리된 금액으로 산정해야 합니다.
(이부분은 해결되어 있는 것 같습니다.)

**Comment by aanoaa** [comment]
복잡하게 적어놨지만 간단하게 해결될 수도 있습니다.

- 대여금액은 `order_detail.price` 의 합
- 미납금은 반납할때에 남겨두는 기록으로 계산
  - 하지만 반납전이라면 기록이 없으니 오늘 날짜 기준으로 연체/연장료를 따져봐야..
- 할인금액은 좀 상황별로 생각해봐야..

인 것 같습니다.

좀 더 정리를 잘해야 실마리가 보일 것 같습니다.

**Comment by aanoaa** [comment]
`order_detail.stage` 별로 대여, 연장, 배상, 환불, 불납금액을 기록하고 있습니다.
여기에서 할인금액은 따로 기록하고 있지 않습니다.

- `0`: 대여
- `1`: 연장
- `2`: 배상
- `3`: 환불
- `4`: 불납

---------------------

자켓, 팬츠, 셔츠, 구두, 벨트를 대여 (32,000)

- 할인없이 대여: 32,000
  - 이때에 연장(1일)/연체(1일): 연장(6,400)/연체(9,600)
  - 자켓금액을 8,000 으로 변경했을때: 30,000
- 할인해서 셔츠, 구두, 벨트가 0원으로 대여: 20,000
  - 이때에 연장(1일)/연체(1일): 연장(4,000)/연체(6,000)
  - 자켓금액을 8,000 으로 변경했을때: 18,000
    - 이때에 연장(1일)/연체(1일): 연장(3,600)/연체(5,400)
- 쿠폰으로 10,000 할인했을때: 22,000
  - 이때에 연장(1일)/연체(1일): 연장(4,400)/연체(6,600)
- 쿠폰으로 30% 할인 했을때: 22,400
  - 이때에 연장(1일)/연체(1일): 연장(4,480)/연체(6,720)
- suit 타입 쿠폰일때: 32,000 이지만 0 무엇으로 계산되어야 할까?
  - 이때에 연장(1일)/연체(1일): 연장(6,400)/연체(9,600)

**Comment by aanoaa** [comment]
![default](https://user-images.githubusercontent.com/170528/27903066-ef7e0b50-6272-11e7-9817-dcc1616149c3.png)

**Comment by 10001if** [comment]
@aanoaa 바뀐 부분이 많아보이네요. 고민할 부분이 많으셨을텐데 의견도 제대로 못드렸네요. 고생해주셔서 감사합니다~!

**Comment by aanoaa** [comment]
새로운 대여화면 입니다.
반납도 같은 화면에서 이루어 질 것입니다.

- 새로주문
- 대여중 -> 부분반납
- 대여중 -> 전체반납

등의 작업이 더 필요합니다.

js 에서 이루어지던 많은 작업들을 모듈화해서 server 에서 처리하도록 변경하였습니다.
아직 반납에 관련된 js 코드가 포함되지는 않았지만 코드량이 기존대비 10% 정도 입니다.

**Comment by aanoaa** [comment]
궁금한게 있으면 제가 직접 물어보고 있습니다.
다른 기능이 완료되면 배포되기전에 많은 분들에게 도움을 받아서 테스트해보겠습니다.

**Comment by aanoaa** [comment]
제기준의 해야할 기능들의 우선순위 입니다.
이미 사용되고 있는 것들이라서 모두 있어야 하는 기능들입니다.

정상적인 대여 ~ 반납 절차가 이루어져야 테스트하는 입장에서 편리할 것 같아서 전체 반납을
우선 처리해야 하겠습니다.

- 전체반납(대여중 -> 반납)
- 부분반납(하위 주문서 만들어서 스슥해야 하는 좀 복잡)
- 주문확정(쿠폰을 넣는 작업이 덜 되어 있음)
- 새로주문(복사하기 같은데..)

**Comment by 10001if** [comment]
@aanoaa 알겠습니다! 감사합니다!

**Comment by aanoaa** [comment]
3회 대여자가 자켓, 팬츠, 셔츠, 구두를 대여한다면

    자켓: 10000
    팬츠: 10000
    셔츠:     0
    구두:     0

이고,

    기존총액: 30000
    할인금액: 10000
    대여비:  20000

입니다.
여기까지는 맞습니다.

-------------------------

이때에 다시 suit 쿠폰을 사용하면,

    자켓: 10000
    팬츠: 10000
    셔츠:     0
    구두:     0

이고,

    기존총액: 30000
    할인금액: 30000
    대여비:      0

처럼 됩니다.
3회 이상 대여자가 suit 타입의 쿠폰을 사용하면, 셔츠와 구두의 가격이 정상가로 변경되어야 합니다.

**Comment by aanoaa** [comment]
- 전체반납
- 주문확정

은 끝났고,

- 부분반납
- 새로주문
- 하위주문서 생성?

등이 남았습니다.
`주문확정 ~ 전체반납` 피드백을 받아봤는데 나쁘지 않았습니다.

**Comment by aanoaa** [comment]
쿠폰 사용시에 기존 할인가를 정상으로 되돌리도록 하였습니다.

**Comment by aanoaa** [comment]
`새로주문` 기능은 결제할때에 의류품목을 더하거나 빼거나 바꾸거나 하고자 할때 사용한다고 합니다.

    결제대기 -> 새로주문 -> 의류항목만 빠지고 포장상태로 변경

새로운 주문서를 만들필요가 없습니다.
상태를 변경하고 세부항목들을 삭제하면 될 것 같습니다.

**Comment by aanoaa** [comment]
하위 주문서 생성은 부분반납에서 이루어 지는 것이고,

부분반납 및 새로주문 기능을 완료했습니다.
테스트를 많이 해보고 적용하면 될 것 같습니다.

**Comment by aanoaa** [comment]
아직 환불이 남았습니다. Aㅏ..

**Comment by aanoaa** [comment]
민영씨에게 테스트를 요청하고 피드백을 받았습니다.

- `연장/연체료 에누리` 에 금액을 입력하고 엔터 누름
- 대여기간을 늘리면 반납예정일도 변경되어야 함
- 운송장 번호를 입력할 수 있는 기능이 없음
- 부분반납을 하게되면 하위주문서는 대여일/예정일/희망일이 상위 주문서와 같아야..
  - 이건 대안이 있는 것이 하위주문서의 예정일/희망일 을 오늘로 변경하는 방법이 있음 대여일은 주문확정을 누르는 시점일텐고
- 배상금 입력못함
- 부분반납할때 반납 문자 전송되는지?
- 하위 주문서 전체반납할때 반납 문자 전송되는지? (이때에만 전송되어야 함)
- 어울림 입력안됨
- 대여기간에 따라 희망일과 예정일이 변경되어야(이건 되던건데.. 확인이 필요함)

**Comment by aanoaa** [comment]
> 부분반납할때 반납 문자 전송되는지?

안됨

> 하위 주문서 전체반납할때 반납 문자 전송되는지? (이때에만 전송되어야 함)

됨

**Comment by aanoaa** [comment]
운송장번호, 어울림, 배상금 모두 거의 쓰지 않는 기능입니다.
생각해보니 합격/불합격 기능도 빠졌네요.

필요하다면 다시 붙여야..

**Comment by aanoaa** [comment]
`/order/:id` 로 연결된 링크를 찾아서 `/orders/:id` 로 바꾸어줘야 합니다.

**Comment by aanoaa** [comment]
[OpenCloset-API-v0.0.1.tar.gz](https://cpan.theopencloset.net/STAFF@THEOPENCLOSET.NET/OpenCloset-API-v0.0.1.tar.gz) 배포하였습니다.

**Comment by aanoaa** [comment]
레거시 `포장 -> 포장완료`를  `OpenCloset::API` 를 사용하도록 변경해야 합니다.

**Comment by aanoaa** [comment]
테스트 전략

- 하루전 백업해둔 DB 를 가지고 온다.
- 실제 대여 기록을 토대로 대여와 반납을 재현해본다.
- 하루치의 대여/반납에 대해 문제가 발생했는지 확인할 수 있지 않나..

**Comment by aanoaa** [comment]
- [ ] 주문 신체 치수가 어느 시점에 복사되어서 보여져야 한다.(지금은 어디선가 그렇게 되고 있다)
- [ ] 쿠폰 몇번 사용했는지 표시해야..
- [ ] 검색결과에 포함됩니다.
- [ ] 모니터에 이벤트 전송이 안된다?(결제완료 했는데 포장중임) 포장완료 -> 결제대기가 아니되는듯
- [ ] 주문서메모/대여메세지/반납확인메모의 아이콘 색정도를 다르게 해서 구분에 유리하게..
- [ ] 상태 라벨의 색상을 이전하는게 보기 좋다.(대여중 - 빨강 등등)
- [ ] 반납상태에서는 `반납방법` 을 제외하고 변경할 수 없어야 한다.

**Comment by aanoaa** [comment]
- [ ] 대여일을 수정가능 하도록..
- [ ] 결제대기 상태에서만 각종 컬럼을 변경할 수 있어야 한다.

**Comment by aanoaa** [comment]
> 주문 신체 치수가 어느 시점에 복사되어서 보여져야 한다.(지금은 어디선가 그렇게 되고 있다)

어딘지 못찾겠습니다.

하지만, `결제대기 -> 대여중` 에서 처리하면 될 것 같습니다.

**Comment by aanoaa** [comment]
> 주문 신체 치수가 어느 시점에 복사되어서 보여져야 한다.(지금은 어디선가 그렇게 되고 있다)

`create_order` helper 에서 사용자의 신체치수를 주문서에 복사합니다.
`create_order` 는 `api#create_order - POST /api/order` 에서 호출됩니다.

**Comment by aanoaa** [comment]
`update_order` helper 를 통해서도 주문서의 신체치수를 변경할 수 있는데,
이는 `api#update_order - PUT /api/order/:id` 에서 호출됩니다.

**Comment by aanoaa** [comment]
> 모니터에 이벤트 전송이 안된다?(결제완료 했는데 포장중임) 포장완료 -> 결제대기가 아니되는듯

monitor 서비스 설정없이 테스트해서 permission 이 없어서 안된 듯 합니다.
문제없습니다.

동일한 host 에서 DNS 를 거쳐서 요청하게 될텐데, (localhost 대신에 monitor.theopencloset.net 으로 요청)
이때에 권한문제가 발생하는지 확인해봐야 합니다.
발생한다면 host 의 ip 를 whitelist 에 등록해주어야 합니다.

**Comment by aanoaa** [comment]
>  대여일을 수정가능 하도록..

대여일을 수정가능하게 한다는 게 좀 걸리는 점이,
결제대기에서 멈추고 대여하지 않았음에도 대여일이 생기는 문제가 발생할 수 있습니다.

대여일이 결제대기 상태의 주문서에 저장되는게 문제는 아니지만,
대여가 확정된 주문서만이 `대여일`을 가질 수 있는 걸로 알고 있습니다.

(왜 그런지는 모르겠는데 그렇게 사용하고 있습니다.)

대여일은 `대여` 버튼을 누르는 순간에 오늘날짜를 입력하고 있습니다.

**Comment by aanoaa** [comment]
이정도로 마무리해서 적용하겠습니다.
문제가 있거나 추가 요구사항은 이슈를 열어서 진행하겠습니다.

**Comment by aanoaa** [comment]
> 동일한 host 에서 DNS 를 거쳐서 요청하게 될텐데, (localhost 대신에 monitor.theopencloset.net 으로 요청)
> 이때에 권한문제가 발생하는지 확인해봐야 합니다.
> 발생한다면 host 의 ip 를 whitelist 에 등록해주어야 합니다.

- 포장 -> 결제대기
- 결제대기 -> 대여중

으로 변경될때에 monitor 의 대기화면이 제대로 갱신되는지 확인할 필요가 있습니다.

**Comment by aanoaa** [comment]
취업날개를 사용했다면 대여할때와 반납할때에 취업날개 서비스에 상태변경을 해주어야 하는데,
이 작업은 하루에 일괄로 처리하고 있습니다. - OpenCloset-Cron-Event

**Comment by pingpongworks** [comment]
감사합니다~ 
현장에서 사용해보면서 소소한 요청사항이 있으면 정리해서 한꺼번에 말씀드리겠습니다.
