### ISSUE TITLE
상반기 뉴스레터용 통계요청

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1278]
1. 2017년 3월 29일 이후 기증자 이메일, 이름, 전화번호 요청 #1216 랑 같은 포맷으로 그 이후 정보가 필요합니다. 

2. 기증의류 수량/ 재기증 의류 수량(품목별로) - 집계시작일을 알려주세요.

3. 열린옷장 이용자들 이용목적 (기간 전체)

| 이용목적 | 횟수 | 
| --------- | ---- |
| 사진촬영 | 235 | 
| 면접 | 2345 | 
| ... | ... | 
| 합계 | 12453 |

**Comment by 10001if** [comment]
@aanoaa 6월 30일에 발송이라고 하네요. 내일까지 요청드릴게요~ 갑자기 요청드려 죄송합니다~~

**Comment by aanoaa** [comment]
> 기증의류 수량/ 재기증 의류 수량(전체 아이템 수만 확인하면 된다고 하네요)

의류의 품목별 수량이 필요하다고 합니다.

| 품목 | 수량 | 재기증 |
|-----|-----|------|
| 자켓 | 100 |  100 |
| 팬츠 | 100 |  100 |
| ... | ... | .... |
| 합계 | 500 |  500 |

**Comment by aanoaa** [comment]
@10001if 출력 포맷을 정해서 알려주세요.

**Comment by 10001if** [comment]
@aanoaa csv 파일입니다.

**Comment by aanoaa** [comment]
``` sql
SELECT purpose, COUNT(purpose) FROM `order` GROUP BY purpose;
```

대여목적별 수량을 뽑는 쿼리 입니다.

**Comment by aanoaa** [comment]
품목/재활용별 수량입니다.

    | 45 | 재활용(옷캔)      |
    | 46 | 재활용(비백)      |
    | 57 | 재활용(비전)      |

``` sql
SELECT category, COUNT(category) FROM clothes WHERE status_id IN (45, 46, 57) GROUP BY category;
SELECT category, COUNT(category) FROM clothes WHERE status_id NOT IN (45, 46, 57) GROUP BY category;
```

**Comment by aanoaa** [comment]
기증자 정보가 포함되어 있어서 `상반기 뉴스레터용 통계` 라는 제목으로 이메일을 보내드렸습니다.

**Comment by aanoaa** [comment]
> 의류의 품목별 수량이 필요하다고 합니다.

재기증 의류가 아닌경우에 `폐기` 상태의 의류도 포함됩니다.

처음부터 재활용이 결정되는 의류는 의류의 상태가 `재활용(옷캔)`, `재활용(비백)` 입니다.
하지만 사용되다가 재활용이되는 의류는 상태가 `폐기` 이고 폐기장소가 `옷캔`, `비백` 입니다.

위에서 수량은 폐기가 포함된 수량입니다.
자켓의 수량이 1000, 재기증이 100 이라고 할때,
1000 에는 상태가 `폐기` 이고 폐기장소가 옷캔, 비백인 의류가 포함되어 있습니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
