### ISSUE TITLE
기묘한 반납 오류 

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1280]
최근에 같은 오류가 여러번 일어나고 있어서 원인을 찾아보면 좋겠습니다. 
무인반납함에 받은 의류를 반납처리하려고 보면, 이미 반납상태로 되어있는 경우입니다. 
처음엔 대여할 때 옷장지기 실수인가 했는데, 몇 건 반복되고 있어서 실수의 문제는 아닌 듯 합니다.
보통 약 1~2시간 전에 무인반납함 안에서 저절로 반납 상태로 바뀌어 있습니다. 
기록해놓았던 셀프 반납 주문서들입니다. 

66082
65508

**Comment by aanoaa** [comment]
[반납을 하지 않았는데 이미 반납으로 되어 있는 문제](#1274) 에서 해결하지 못했는데 계속해서 발생하고 있는 것 같습니다.

**Comment by aanoaa** [comment]
대여/반납 화면이 새롭게 바뀌었습니다.
다시 발생하면 알려주시기 바랍니다.
