### ISSUE TITLE
띄어쓰기가 있다고 예약이 안되는 오류

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1281]
이름에 띄어쓰기는 절대 없어서 이유를 모르겠습니다. 
사용자 추가를 새로 해서 일단은 예약을 해드렸습니다만,
예전엔 이름 띄어쓰기 확인해서 수정하면 정상적으로 되던 게 
현재는 전혀 안됩니다. 체크부탁드려요~

사용자정보 번호
69456
69377

**Comment by aanoaa** [comment]
> 이름과 휴대전화 번호가 일치하지 않습니다.

이 오류가 발생하는데 이게 좀 의아합니다.

같은 이름을 가진 사용자는 당연히 전화번호가 다를텐데 왜 저런 에러가 발생하는지 의문입니다.

이번 케이스만 그런건지 어떤건지..

**Comment by 10001if** [comment]
유사한 이슈가 다시 발생하면 오픈하여 작업 요청드리겠습니다.
