### ISSUE TITLE
취업날개 통계수치 비교

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#1284]
날짜별 방문인원수가 1명 ~ 2명 차이가 날때가 있습니다.

예를 들어 7/20일 방문인원의 수치가 다릅니다.
취업날개 공식통계에서는 21명이지만, 저희통계에서는 22명 입니다.

택배대여가 없는 날이기 때문에 1명을 찾아서 왜 차이가 나는지 알아봐야 합니다.

[취업날개 서비스의 방문/미방문자의 통계수치 동기화](https://github.com/opencloset/opencloset/issues/1256) 에서는

> 공식(A) 통계페이지와 열린옷장(B)의 수치가 다를 수 있는데 이는,
> 
> - A 에서 온라인(택배) 대여의 통계를 합산하지 않기 때문
> - 그밖에 이슈가 있을 수 있습니다.

라고 설명하고 있습니다.

**Comment by aanoaa** [comment]
주문서번호: 68055 입니다.
관련된 취업날개 정보입니다.

http://dressfree.net/service/admin_3_v.php?rent_num=170718180246-798

여기에서 보면 대여일과 대여시간이 비어있습니다.

**Comment by aanoaa** [comment]
대여일과 대여시간이 비어있는 경우에 쿠폰이 사용되었음에도 통계에는 잡히지 않습니다.

**Comment by aanoaa** [comment]
cc @pingpongworks

**Comment by aanoaa** [comment]
왜 예약일시가 비어있는지 확인을 해보았습니다.
열린옷장에서 방문예약이 완료되면 취업날개 api 를 호출해서 예약일시를 동기화 하고 있습니다.
로그를 살펴보니 api 요청이 항상 성공하고 있지 않습니다.

    [Sat Jul 22 22:06:15 2017] [warn] api call to dressfree.net failed: rent_num(xxxxxxxxxxxx-xxx), rent_date(2017-07-29), rent_time(10:00:00)

이렇게 실패한 rent_num 을 가지고 확인해보면 예약일시가 비어있습니다.
실패한 rent_num 을 수집해서 예약일시를 갱신해주도록 하면 offline 의 통계는 맞출 수 있을 것 같습니다.

더불어 왜 요청이 실패하는지 원인 파악을 하는 것도 중요할 것 같습니다.
타임아웃이 1초로 설정되어 있는데 늘려주거나 retry 를 하는 것도 방법일 것 같습니다.

**Comment by aanoaa** [comment]
2017-05-23 ~ 오늘까지 70건에 대해서 취업날개 예약일시 변경요청 실패한 `rent_num` 에 대해서 예약일시를 변경하도록 하겠습니다.

함정이 있습니다.
방문예약 이후에 예약일시를 다시 변경했다면 정상적으로 들어있을 수 있습니다.

    A일로 예약 -> 실패
    B일로 변경 -> 성공
    ----------------
    예약일시가 없는 것으로 알고 다시 A일로 변경

일일 통계 수치가 달라질 수 있습니다.

예약일시가 있는지 여부를 확인할 수 있으면 좋겠는데 직접 html 코드를 파싱하는 것 말고는 답이 없을 것 같습니다.

**Comment by aanoaa** [comment]
`rent_num` 을 가지고 주문서를 찾아서 주문서의 예약일시를 알아낼 수 있습니다.

**Comment by aanoaa** [comment]
api 요청 실패 로그를 뽑아서 예약일시를 갱신해주는 api 를 호출하였습니다.


``` perl
use strict;
use warnings;
use DateTime;

use OpenCloset::Schema;
use OpenCloset::Events::EmploymentWing;

my $schema = OpenCloset::Schema->connect({ ... });

my $client = OpenCloset::Events::EmploymentWing->new;

while ( my $row = <DATA> ) {
    chomp $row;
    $row =~ s/.*failed: //;
    my ( $rent_num, $ymd, $hms ) = split /, /, $row;

    $rent_num =~ s/[a-z_\(\)]//g;
    my $coupon = $schema->resultset('Coupon')->search( { desc => { -like => "seoul-2017-2|$rent_num|%" } }, { rows => 1 } )->single;
    my $order = $coupon->orders->next;
    unless ($order) {
        print STDERR "Not found order: $rent_num\n";
        next;
    }

    my $booking = $order->booking;
    unless ($booking) {
        # 이건 online?
        print STDERR "Undefined booking: $rent_num\n";
        next;
    }

    my $date = $booking->date;
    my $success = $client->update_booking_datetime( $rent_num, $date );
    if ($success) {
        print "success $rent_num\n";
    }
    else {
        print "failed $rent_num\n";
    }

    sleep(1);
}

__DATA__
development.log.10.gz:[Sat Jul 15 10:36:56 2017] [warn] api call to dressfree.net failed: rent_num(xxxxxxxxxxxx-xxx), rent_date(2017-07-17), rent_time(11:30:00)
...
```

**Comment by aanoaa** [comment]
결과입니다.

```
$ perl a.pl 
Not found order: 170715103017-497
success 170715173327-137
success 170714102137-396
success 170714212452-959
success 170713185544-464
Not found order: 170711090014-680
success 170711111134-486
success 170711200751-118
success 170709225530-478
success 170708200700-268
success 170707180827-746
success 170707220827-116
success 170706135246-214
Undefined booking: 170707000452-250
success 170704113745-595
success 170704163406-290
success 170704215019-576
success 170703014702-256
Undefined booking: 170630132742-701
success 170630201646-318
success 170628172626-176
success 170627124220-140
success 170626134433-122
success 170623081347-816
Not found order: 170623164205-996
success 170623164620-243
success 170622170908-344
success 170620151742-188
success 170620180513-068
success 170619104736-090
success 170619013415-484
success 170617163346-156
success 170616105025-088
success 170722220016-724
success 170615163921-133
success 170613015939-416
success 170613151621-296
success 170613205052-643
success 170612170217-657
success 170611141724-669
success 170611201127-716
success 170610081426-777
success 170610100957-429
success 170609175502-497
success 170610015349-412
success 170608092245-371
success 170608110330-852
success 170607124236-228
success 170607133229-759
success 170607190857-100
Not found order: 170608022438-862
success 170604202507-561
success 170602092145-310
success 170601094522-372
success 170601095737-501
success 170531162204-426
success 170530132939-506
success 170525184601-959
success 170524121438-801
success 170524125553-391
success 170524134542-713
success 170524172721-555
success 170523151304-905
success 170719103802-366
Undefined booking: 170719154052-238
success 170718123637-525
success 170718145535-033
success 170718161127-680
success 170718180246-798
success 170718223844-888
```

rent_num 노출 아 몰랑
이걸 따로 기록해두자니 피곤해서..

**Comment by aanoaa** [comment]
공식통계의 7월달 수치가 `703 -> 716` 으로 변경되었습니다.

**Comment by aanoaa** [comment]
7월 온라인 사용수가 `11` 입니다.
716 에서 11을 더해도 727, 4개가 빕니다.

**Comment by aanoaa** [comment]
> 취업날개 통계문의
> 
> 안녕하세요.
> 열린옷장 홍형석입니다.
> 
> 저희가 수집하고 있는 통계와 취업날개 서비스상의 통계가 달라서 살펴보았습니다.
> 확인해보니 대여일시가 비어있거나 배송희망일이 비어있는 것들이 있었습니다.
> 
> 열린옷장 -> dressfree 로의 예약일시 변경 API 호출실패가 원인인 것 같습니다.
> 
> 대여일시가 비어있는 rent_num 목록을 알려주시면 예약시간을 찾아서 다시 반영토록 하겠습니다.
> 택배(온라인) 의 경우에도 배송희망일이 비어있는 것들이 있는데 통계에 잡히고 있지 않는 것 같습니다.
> 
> 배송희망일이 비어있는 rent_num 목록과 어떻게 배송희망일을 변경할 수 있는지 방법을 알려주시면 반영토록 하겠습니다.
> 
> 그럼 수고하세요.

**Comment by aanoaa** [comment]
07-18 일 통계는

공식: 35
옷장: 34

이건 한개가 더 많은데 왜 더 많은지 알아봐야 합니다.

주문서번호 `67510`, 방문예약일시: `2017-07-17T14:30:00`

열린옷장은 17일인데 취업날개에서는 18일 입니다.
변경요청이 실패로그는 없습니다.

    development.log.13.gz:[Wed Jul 12 16:27:42 2017] [info] api call to dressfree.net success: rent_num(170712162411-874), rent_date(2017-07-18), rent_time(14:30:00)

18일로 방문예약 했다가 17일로 변경한 것 같은데,
17일로 변경했다면 실패 로그는 없으니 취업날개에 반영되었어야 할 것 같은데 반영이 되지 않았습니다.

열린옷장에서 예약일시를 변경했을때에 취업날개쪽에 반영을 해주는지 여부를 우선 확인해봐야 하겠습니다.

**Comment by aanoaa** [comment]
이렇게 하나씩 찾을 수는 없는 노릇입니다.

**Comment by aanoaa** [comment]
$ zgrep '/order/67510/booking' development.log.?.gz
    development.log.8.gz:[Mon Jul 17 11:18:31 2017] [debug] GET "/order/67510/booking/edit"

방문예약일시 변경 요청 로그가 없는데 어떻게 바꾼거지??

**Comment by aanoaa** [comment]
`취업날개 서비스에서 버튼을 눌러서 이용횟수를 추가하는 기능`

을 사용하게 되면 열린옷장에서 수집하고 있는 취업날개 서비스 이용통계와
취업날개 공식통계의 수치가 같을 수가 없습니다.

지금도 수치가 조금씩 다른데 이 기능을 사용하기 시작하면 차이가 더욱 많이 나게 될 것 입니다.
(오히려 줄어들 수도)

줄어들든 늘어나든 오차는 계속 벌어지게 됩니다.

1. 현재 오차(날짜가 비어있음)
2. 이용횟수버튼(누를때마다 추적할 방법이 없이 벌어짐)

이용횟수 버튼을 취업날개 서비스에서 직접 누르지 않고 열린옷장 시스템에서 대신 시뮬레이션을 해주고,
통계를 추적할 수 있는 무언가를 만들어야 합니다.

이 작업이 볼륨이 커 보여 해야 되는지도 모르겠습니다.
쓸데없이 일만 많이 하는 것 같습니다.

현재 오차가 벌어지는 이유를 수정하기 위해서 이메일로 문의 해놓았는데,
내일 답변이 오면 일단 그부분부터 고칠 수 있다면 고치도록 하겠습니다.

고쳐지면 다행인데 오차가 적다면 포기하고 다른걸 하는게 더 좋을 것 같습니다.
이용횟수버튼을 어떻게 해야 할지는 아직 모르겠습니다.

**Comment by aanoaa** [comment]
연장하기 기능은 해결되었습니다.

**Comment by aanoaa** [comment]
대여일시가 비어있는 목록과
배송희망일이 비어있는 목록을 이메일로 전달받았습니다.

날짜를 설정해주고 다시 비교해보도록 하겠습니다.

**Comment by aanoaa** [comment]
비어있는 대여일시를 넣어주었습니다.
7건인데 모두 성공했습니다.

실수로 업데이트 전후 수치를 비교해보진 못했습니다.

**Comment by aanoaa** [comment]
온라인 대여의 배송희망일이 비어있는 rent_num 에도 배송희망일을 넣어주었습니다.
모두 성공했습니다. 20 건 입니다.

**Comment by aanoaa** [comment]
https://jsfiddle.net/fshsafcy/

열린옷장에서 수집한 통계와
열린옷장의 DB 에서 뽑은 수치와
취업날개 공식통계의 7월달 수치를 비교해서 그래프화 시켜봤습니다.

**Comment by aanoaa** [comment]
애지간히 맞출만큼 맞춰봤는데 결국에는 안맞습니다.
어디부터 잘못된건지도 모르겠습니다.

이것만 붙잡고 있을 순 없습니다.
포기하고 닫겠습니다.

**Comment by 10001if** [comment]
고생하셨습니다. 이슈 우선순위에서 제거하도록 하겠습니다.
