### ISSUE TITLE
의류의 상태 대신에 상세항목의 상태를 나타냄

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#1285]
주문서 하단의 대여 항목 상세 테이블을 보면,

기존에는 상세항목의 상태를 나타내었는데,
지금은 의류의 현재 상태를 나타내고 있습니다.

이것을 기존처럼 상세항목의 상태가 나타나도록 해야 합니다.

예로, 반납된 주문서의 경우 상세항목은 모두 반납이어야 합니다.

**Comment by pingpongworks** [comment]
상세항목 상태로 잘 되었습니다. 확인했습니다~
