### ISSUE TITLE
부분반납후에 연체료가 계산되지 않음

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#1287]
타이를 빼고 반납 받아서 부분반납처리하고 타이만 하루 연체했습니다.

주문서번호: 67841 - 68361

그런데 연체료가 계산되지 않았고, 반납처리하려고 했더니 오류가 발생했습니다.

오류의 원인은 연체료 결제 방법이 없어서 입니다.

    'late_fee_pay_with' is required at /path/to/OpenCloset/API/Order.pm line 628.

입니다.

연체료가 계산되지 않은 것도 문제이고, 연체료가 없는 주제에 연체료 결제 방법이 없다고 반납처리가 안된 것도 문제입니다.

**Comment by aanoaa** [comment]
이 경우에는 타이의 가격이 0원 이라서 그렇습니다.
연체료는 올바르게 계산되었습니다.
100일 연체되었어도 0원 입니다.

**Comment by aanoaa** [comment]
연체일/연장일이 아니라 연체료/연장료가 있으면 결제방법의 선택을 강제하도록 해야 하겠습니다.

**Comment by aanoaa** [comment]
3회 이상 대여자의 경우에 타이만 단독대여 했을경우 2,000 원으로 책정하고 있습니다.
30% 할인받으면 1,400 원 입니다.

**Comment by pingpongworks** [comment]
네~ 타이는 0,원이라 문제 없습니다. 이슈정리하겠슴다
