### ISSUE TITLE
비율할인쿠폰 통계에 할인금액이 표시가 안됨

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#1290]
https://github.com/opencloset/opencloset/issues/1258#issuecomment-317359544

> 링크스타트 통계페이지에
> 주문서 금액만 표기되고
> 30% 할인 가격이 표기되지 않습니다.
> 30% 할인가격이 표기되어야 나중에 정산할 때 편리합니다.
> 아직 이용이 매우 저조해서 급하지 않으니까
> 시간 나실 때 수정 부탁드립니다. @aanoaa

**Comment by aanoaa** [comment]
임의로 우선순위를 좀 낮게 설정하였습니다.

**Comment by 10001if** [comment]
@aanoaa 사용률도 낮고 계산을 하는 것이 불가능해 보이지 않으므로 이슈 닫도록 하겠습니다. 차후에 정산이슈가 생기면 다시 열도록 하겠습니다.
