### ISSUE TITLE
취업날개 이용자 상세정보 링크

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#1292]
연장하기 기능을 사용하기 위해서 취업날개 서비스로의 링크를 제공합니다.

**Comment by pingpongworks** [comment]
1) 취날 관리자 페이지에 로그인 
    2) 연장하고자 하는 주문내역서에서 연장기간을 수정하고 주문을 확정한다
    3) 주문내역서의 취업날개 쿠폰 탭을 누른다
    4) 취날 관리자페이지 연장내역에서 연장사유를 적고 "연장하기"버튼을 누른다 (2번 연장을 원하면 2번 반복한다)
    5) 잔디 구매결제 란에 주문서/날짜/연장횟수를 메모한다

이런 방법으로 일단은 취업날개 연장 업무가 이전보다는 훨씬 수월해졌습니다. 아쉬운 것은 열린옷장 프로그램 주문내역서에서 취업날개쿠폰이 몇개 발행되었는지 확인이 가능하지 않은 것입니다. 

**취날 관리자페이지에서 이름 옆에 숫자로 쿠폰이용개수를 확인할 수 있는 것처럼, 열린옷장 주문내역서에서도 확인이 가능하면 좋을 것 같습니다** 

아마도 연동작업이 필요할 것 같습니다.

**Comment by pingpongworks** [comment]
전화로 취업날개 연장을 요청받았을 경우에는 

    1) 취날 관리자 페이지에 로그인 
    2) 주문내역서의 취업날개 쿠폰 탭을 누른다
    3) 취날 관리자페이지 연장내역에서 연장사유를 적고 "연장하기"버튼을 누른다 
    4) 반납메모란에 취업날개 연장임을 메모하여, 연장료를 결제하지 않도록 한다
    5) 잔디 구매결제 란에 주문서/날짜/연장횟수를 메모한다

이렇게 하고 있습니다. 역시 이전보다는 훨씬 편리해졌지만, 예전처럼 반납예정일을 수정할 수 있으면 연장료가 발생하지 않고 연장해줄 수 있지 않을까 하는 생각이 듭니다. 반납예정일을 수정하지 못하도록 했던 이유가 있을 거 같긴 한데요, 반납예정일 수정을 검토해보면 좋겠습니다.

**Comment by aanoaa** [comment]
`연장하기`를 누르면 취업날개 이용횟수가 1회 늘어납니다.(이게 통계에 +1 되어야 합니다)
열린옷장은 쿠폰을 발행하고 이후에 사용된 쿠폰을 가지고 이용횟수를 계산합니다.

`연장하기` 를 취업날개서비스가 아닌 열린옷장에서 누르면
내부적으로 쿠폰을 발행->사용으로 처리하고 취업날개에 `연장하기` 버튼을 누른 효과를 주도록 합니다.

이게 완벽하지는 않은 것이 rent_num 을 알 수 없습니다.
rent_num 한개당 쿠폰 한장으로 사용하고 있는데, rent_num 에 쿠폰이 2장이 됩니다.

중복쿠폰은 사용하지 않기로 해서 주문서마다 하나의 쿠폰을 사용토록 해왔는데 이 경우에는 두장의 쿠폰이 사용되도록 해야 하는것도 문제입니다.

억지로 취업날개 서비스에 맞추려고 하니 피곤합니다.

**Comment by pingpongworks** [comment]
수, 목에 작업해주신 덕분에 취업날개 연장하는 업무가 훨씬 편해졌습니다.  감사합니다^^
