### ISSUE TITLE
취업날개의 연장하기 버튼의 사용방법

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#1294]
> 취업날개의 연장하기 버튼문의
> 
> 안녕하세요.
> 열린옷장 홍형석입니다.
> 
> 오늘 취업날개를 3회 이용해서 대여기간을 늘리고 싶어하는 사용자가 있었습니다.
> 이용횟수를 차감하기 위해서 연장하기 상세내역을 입력하고 `연장하기` 버튼을 눌렀는데 열린옷장의 방문예약 화면으로 이동되었습니다.
> 
> 이게 의도가 무엇인가요?
> 사용자는 방문예약을 다시 해야 하는건가요?
> 
> 
> 
> 그리고 예약내역목록 에서의 신청횟수와 대여자 정보에서의 신청횟수가 다릅니다.
> 첨부 이미지파일을 참고해주세요.

![default](https://user-images.githubusercontent.com/170528/28605222-49327670-720b-11e7-8d07-e1dc409b7af9.png)
![1](https://user-images.githubusercontent.com/170528/28605221-491d53b2-720b-11e7-9241-a61d0d4ece27.png)

**Comment by aanoaa** [comment]
단순히 취업날개 서비스에서 이용횟수가 차감될 것이라고 기대 했는데, `연장하기` 버튼을
누르면 열린옷장 방문예약 화면으로 이동되었습니다.

----------------------

- 68583

2017-07-25 일에 정xx 님은 결제대기 상태에서 연장하기를 눌렀더니 방문예약으로 넘어와서
그대로 닫으면 안될 것 같아서 예약변경을 하였고, 방문예약시간이 변경되었습니다.

이후에 대여확정을 하였습니다.

- 68583

2017-07-26 일에 허x 님은 어제 정xx 님이 결제대기 상태였기 때문에 연장하기를 눌렀을때
방문예약으로 이동된 것이 아닐까 의심해서 우선 대여확정을 하였습니다.

이후에 연장하기를 눌렀더니 방문예약 화면으로 다시 이동되었고 이것도 그대로 닫으면 안될 것
같아서 다시 방문예약을 해서 주문서가 한개 더 생겼습니다.
새로 생긴 주문서를 어떻게 처리해야 할지 알려달라고 합니다.

----------------------

정xx 님은 취업날개 2회 사용이지만 열린옷장에서는 주문서가 한개이고 쿠폰이 1회 사용됨 입니다.
허x 님은 취업날개 3회 사용이지만 열린옷장에서는 주문서가 두개이고 각각 쿠폰이 1회는 사용됨, 1회 예약중인 상태입니다.

연장하기 버튼을 누를때마다 차이가 발생하니까 열린옷장 통계와 취업날개 통계를 비교하기
위해서 뭔가 방안이 필요할 것 같긴 합니다.

**Comment by aanoaa** [comment]
이런 경우에는 방문예약 화면으로 이동되더라도 신경쓰지 말고 그냥 닫으라고 전달해드렸습니다.
답변을 보고 앞으로의 대처에 대해 다시 알려드려야 하겠습니다.

**Comment by aanoaa** [comment]
통계작업을 위해서라면 visitor 만 건드리면 되기 때문에 쿠폰을 발행/사용할 필요는 없습니다.
20대 남자가 3회 이용해서 8박9일을 대여하고자 한다면,

- 대여기간을 8박 9일로 늘려서 대여해주고
- 취업날개 서비스의 연장하기 버튼을 2회 누릅니다.
- 취업날개 이벤트 통계에 +2 씩 해줍니다.
  - visitor.visited_age_20
  - visitor.visited_male
  - visitor.visited

취업날개의 연장하기 버튼을 눌렀을때에 callback 으로 받아서 할 수도 있겠지만,
담당 staff 이 연장하기 버튼도 누르고 통계를 위해서 무언가를 더 해주면 그럴 필요도
없습니다.

**Comment by aanoaa** [comment]
날짜와 이벤트 이름으로 일일 통계 수치를 넣고 있습니다.

`2017-07-26`일 `취업날개`의 방문자 수,
`2017-07-26`일 `열린옷장`의 방문자 수 등등

-------------------------------------

`2017-07-26`일 `취업날개-extra`의 방문자 수 를 저장할 수 있도록 하고,
일일 통계를 구할때 이 값을 참고해서 추가 숫자를 더해주도록 하면 해결될 수 있지 않을까
합니다.

- date: `2017-07-26`
- event: `extra-jobwing`
- visited_age_20: `2`
- visited_age_30: `1`
- visited_male: `1`
- visited_female: `2`

이런식으로 따로 모아둔수치를 일일 통계를 넣을때 참고해서 더해줍니다.
의도하지는 않았지만 연장하기에 대한 통계도 따로 쌓이는 식입니다.

**Comment by aanoaa** [comment]
> 안녕하십니까. 아이넷피아 박기련 부장입니다.
> 
> 우선 저희 작업진행이 매끄럽지 못했던 점 죄송합니다.
> 
> 열린옷장에서 보내주신 두통의 메일중 어제 보내주신 통계 부분과 금일 보내주신 신청횟수가 맞지 않는 부분은 금일중 처리 예정입니다.
> 
> 열린옷장에서 대여신청하신 분이 연장을 원하실 경우 저희가 아래의 두가지 방법중 1안으로 작업진행해드리려 하는데
> 이대로 진행해드려도 무리가 없겠는지.. 혹시 다른 문제가 발생될 소지가 있겠는지 내부 검토하여 말씀해주시면 감사하겠습니다.
> (금일 작업처리를 마무리해드리려 하고 있으니 빠른 답변 부탁드립니다.)
> 
> [1안] 열린옷장에서 대여신청하신 분이 연장신청 할 경우 열린옷장의 방문예약 화면으로 이동하지 못하게 막아두고 횟수만 1회 차감시키는 방법
> (이 경우 연장신청 정상 완료시 연장신청자와 열린옷장 관리자에게 SMS로 연장신청 안내 문자 전송)
> (메일주신 것처럼 취업날개를 3회 이용해서 대여기간을 늘리고 싶어하는 사용자가 있을 경우 연장신청은 한번에 1회 연장이 기준이기 때문에 연장신청을 3번에 걸쳐 진행하셔야 합니다.)
> 
> [2안] 열린옷장에서 대여신청하신 분은 우선 연장신청이 되지 않도록 막아두고 안내멘트 추가하는 방법
> (이 경우 통계가 맞지 않을 수 있어 좋지 않겠습니다.)
> 
> 그럼 오늘도 즐거운 하루 되십시오.
> 
> 감사합니다.

**Comment by aanoaa** [comment]
> 통계가 최우선으로 고려되어야 할 것 같으니 1안이 좋을 것 같습니다.
> 궁금한 점을 다시 남겼습니다.
> 답변 부탁드리겠습니다.
> 
> 방문예약 화면으로 넘어가서 무엇을 더 해야 하는 건가해서 여쭤봤습니다.
> 연장하기 버튼은 이용횟수만 차감시키는 버튼이 맞는 건가요?
> 다시 방문예약을 하지 않아도 되는건가요?
> 
>     [1안] 열린옷장에서 대여신청하신 분이 연장신청 할 경우 열린옷장의 방문예약 화면으로 이동하지 못하게 막아두고 횟수만 1회 차감시키는 방법
>     (이 경우 연장신청 정상 완료시 연장신청자와 열린옷장 관리자에게 SMS로 연장신청 안내 문자 전송)
> 
> 연장신청은 관리자가 하는 걸로 알고있는데, 대여신청하신 분이 연장신청을 할 수 있나요?
> 대여자가 연장을 원할때에는 열린옷장의 관리자가 취업날개 서비스에 접속해서 해당 대여자의 연장버튼을 누르고 있습니다.
> 
>     (메일주신 것처럼 취업날개를 3회 이용해서 대여기간을 늘리고 싶어하는 사용자가 있을 경우 연장신청은 한번에 1회 연장이 기준이기 때문에 연장신청을 3번에 걸쳐 진행하셔야 합니다.)
> 
> 3회 이용하는 것이라면 1회는 예약/사용할때에 이미 발생한 것이고 연장하기 버튼을 2회 더 눌러야 총 3회가 되는 것이 아닌가요?
> 
> 그럼 수고하세요

**Comment by aanoaa** [comment]
> 전화 연락이 왔습니다.
> 
> 관리자와 대여자 모두 연장신청을 할 수 있습니다.
> 열린옷장을 제외한 서비스에서는 대여자가 연장신청을 할 경우에 대여기간이 4박5일 연장된다고 합니다.
> 
> 연장하기 버튼은 이용횟수만 차감하는 기능이 맞고 다시 방문예약을 하지 않아도 된다고 합니다.
> 
>     3회 이용하는 것이라면 1회는 예약/사용할때에 이미 발생한 것이고 연장하기 버튼을 2회 더 눌러야 총 3회가 되는 것이 아닌가요?
> 
> 이 내용도 맞습니다.

**Comment by aanoaa** [comment]
staff 는 초기 의도대로 취업날개 서비스로 가서 상세내역을 입력하고 연장하기 버튼을 누르면 됩니다.

**Comment by aanoaa** [comment]
사용방법

- 추가 이용횟수만큼 `연장하기 - n회 연장` 버튼을 누릅니다.
- 취업날개 서비스로 이동해서 n회 만큼 상세내역을 입력하고 연장하기 버튼을 누릅니다.

어느 한쪽만 해주는게 아니라 둘 다 해주어야 합니다.

cc @pingpongworks

**Comment by aanoaa** [comment]
취업날개 이용자가 대여중에 연락해서 이용횟수를 차감하고 대여기간을 연장하는 경우가 있습니다.

전화로 연락이 오는 경우는 staff 이 대신 `취업날개 연장하기` 버튼을 눌러주기 때문에 상관이 없는데,
연락 없이 본인이 직접 연장하기 버튼을 누르게 될 경우에는 문제가 발생할 수 있습니다.

해결방법은

1. 취업날개 연장하기 버튼을 본인이 눌렀을때 취업날개 서비스에서 열린옷장의 API 를 호출
2. 본인이 연장할 수 없도록 막고 연락달라고 함

1번이 당연히 graceful 하지만 2번이 훨씬 쉽습니다.

2번을 사용한다고 해도 반납예정일과 반납희망일이 늘어나는 건 아니라서 메모해서 공유되지 않으면 반납할때에 연체/연장료를 청구할 수도 있습니다.

**Comment by aanoaa** [comment]
취업날개의 연장하기 버튼은 취소할 수 없습니다.
이 점을 감안해서 불편하게 사용하느니, 주문서에서 연장하기를 누르면 취업날개 연장하기를 에뮬레이션하도록 하겠습니다.
어차피 취소가 안되니까 `1회 취소`도 없애고 `연장하기 횟수 * 3` 을 반납희망일과 예정일에 반영해주도록 하겠습니다.

- 주문을 확정하기 전에 대여기간을 수정하지 않고 연장하기를 누릅니다.
- 반납예정일과 반납희망일이 변경되는 것을 확인합니다.(반납[희망|예정])일 += 연장하기 횟수 * 3)
  - 또 바꿀 수 있습니다. 이건 don't care
- 대여기간중에 연장신청 연락이 온다면 주문서 들어가서 연장하기 버튼을 눌러줍니다.
  (반납예정일과 반납희망일을 늘려주도록 하겠습니다.)


방문예약 시간을 기준으로 연장하기 숫자를 집계했는데 대여도중에 연장을 할 수가 있으니
방문예약시간이 아닌 오늘날짜 기준으로 넣어주도록 하겠습니다.

24일날 대여 26일날 연장 -> 26일날 +1 됨
위와 같은 경우 취업날개 통계가 24일에 + 될지 26일에 + 될지 모릅니다.

**Comment by aanoaa** [comment]
진짜 취업날깨 때문에 얼마나 많은 작업을 하는 건지..

**Comment by aanoaa** [comment]
수정하였지만 테스트해보지 못했습니다.
일단 반영해서 실제 데이터로 테스트하겠습니다.

**Comment by pingpongworks** [comment]
아무 문제없이 잘 되고 있습니다. 감사합니다^^
