### ISSUE TITLE
취업날개 통계용 연장버튼

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#1295]
[취업날개의 연장하기 버튼의 사용방법](https://github.com/opencloset/opencloset/issues/1294)

3박 4일 대여 기준으로 연 10회 취업날개 서비스를 사용할 수 있는데,
한번 대여할때에 이용횟수를 추가해서 대여기간을 늘리고자 할때에 취업날개 서비스의 연장하기
버튼을 활용합니다. (8박9일로 대여하는 대신에 이용횟수를 3회 사용)

문제는 우리는 내부적으로 쿠폰 시스템을 활용해서 취업날개 사용통계를 수집하고 있는데
연장하기 버튼을 사용하게 될 경우 쿠폰의 사용횟수를 가지고는 취업날개 이용횟수를 정확하게
셀 수 없게 됩니다.

이를 보완하기 위해서 `열린옷장의 취업날개 연장버튼?` 을 주문서에 두고
누를때마다 사용통계에 적절하게 반영되도록 하는 기능입니다.

**Comment by aanoaa** [comment]
아이디어는,
날짜별로 취업날개 extra 데이터를 수집, 저장하고 일일 통계를 구할때 이 데이터를 참고하도록 합니다.

- date: `2017-07-26`
- event: `extra-jobwing`
- visited_age_20: `2`
- visited_age_30: `1`
- visited_male: `1`
- visited_female: `2`

말로 풀어서 설명하면,

2017-07-26 일 취업날개 extra 데이터에는 

20대 2건, 30대 1건
남성 1건, 여성 2건

총 3건의 연장이력이 발생하였다.

**Comment by aanoaa** [comment]
연장버튼을 누르면 대략 이런느낌이랄까..

```
POST /visitors/:event

date=2017-07-26 or today
visited_age_20=n


## 이런 요청이 발생할때마다 추가가 아니라 수치 +1
POST /visitors/extra-seoul-2017?visited_age_20=1&visited_female=1
```

**Comment by aanoaa** [comment]
# 2017-07-26 14:00 에 방문예약한 20대 여성 김개똥씨가 2회 연장 신청을 했을 경우에..
    POST /stat/events/:event?date=2017-07-26&visited_age_20=2&visited_female=2

**Comment by aanoaa** [comment]
online/offline 여부도 중요할 것 같은데 이건 그냥 주문서 따라가는 걸로..

**Comment by aanoaa** [comment]
![2](https://user-images.githubusercontent.com/170528/28613952-0e47983c-722f-11e7-99d8-90eb4df64211.png)

1회 취소는 3회연장 했다가 아차 2회인데 싶을때 사용하는 기능입니다.
통계보기는 일별 연장하기 이력입니다.

**Comment by aanoaa** [comment]
여기서 연장한다고 연장되는건 아니고 취업날개 서비스에 들어가서 연장하기 버튼을 눌러줘야 합니다.
궁극적으로는 그것까지 해주면 좋을 것 같습니다.

**Comment by aanoaa** [comment]
68583 - 허x 님
68583 - 정xx 님

의 통계작업을 위해 

25일에 +1 26일 +2 해주었습니다.
26일은 오늘 방문자 통계 수집이 끝나면 반영이 됩니다.

25일 통계는 제가 직접 넣어주도록 하겠습니다.

**Comment by aanoaa** [comment]
``` sql
UPDATE visitor SET visited = visited + 1, visited_female = visited_female + 1, visited_age_20 = visited_age_20 + 1 WHERE `date` = '2017-07-25' AND online = 0 AND event = 'seoul-2017';
```

**Comment by aanoaa** [comment]
반영하였습니다.

**Comment by pingpongworks** [comment]
<img width="960" alt="2017-07-31 16 45 21" src="https://user-images.githubusercontent.com/17288038/28767875-73efd1ce-7610-11e7-9a0f-7c45cb05482a.png">

연장하기가 "대여중"일 때는 아무 문제없이 4일씩 잘 연장되고 있습니다만, 
결제대기에서 연장하기를 누르면 반납예정일이 1일만 늘어납니다. 
지금은 수동으로 반납예정일을 변경해서 사용하고 있습니다. 
1회를 연장했을 때 반납예정일과 반납희망일이 4일씩 추가될 수 있도록 부탁드려요~ @aanoaa

**Comment by pingpongworks** [comment]
<img width="960" alt="2017-07-31 16 45 21" src="https://user-images.githubusercontent.com/17288038/28768091-58fd7104-7611-11e7-952b-c68ad3612b59.png">

연장하기가 "대여중"일 때는 아무 문제없이 4일씩 잘 연장되고 있습니다만,
결제대기에서 연장하기를 누르면 반납예정일이 1일만 늘어납니다.
지금은 수동으로 반납예정일을 변경해서 사용하고 있습니다.
1회를 연장했을 때 반납예정일과 반납희망일이 4일씩 추가될 수 있도록 부탁드려요~ @aanoaa

**Comment by aanoaa** [comment]
연장하기 버튼을 맘대로 누를 수 없어서 테스트하기가 어렵습니다.
자세하게 설명해주세요.

반납 희망일이 언제였고 대여기간이 몇일이었는데 연장하기 몇회를 했더니 반납 희망일과 반납예정일이 어떻게 되었다.
이럴때에 반납예정일과 반납희망일이 이렇게 되는게 좋겠다. @pingpongworks

**Comment by aanoaa** [comment]
결제대기 상태의 주문서에서 반납예정일과 반납희망일이 2017-08-03 이었고,
이때에 연장하기 1회를 했다고 합니다.

반납예정일과 반납희망일이 2017-08-07 이 되어야 하는데,
반납예정일과 반납희망일이 2017-08-04 로 되었습니다.

**Comment by 10001if** [comment]
@aanoaa 마지막 이슈가 해결되지 않아 이슈를 닫지 못하고 있습니다. 

> 결제대기 상태의 주문서에서 반납예정일과 반납희망일이 2017-08-03 이었고,
이때에 연장하기 1회를 했다고 합니다.

>반납예정일과 반납희망일이 2017-08-07 이 되어야 하는데,
반납예정일과 반납희망일이 2017-08-04 로 되었습니다.

이렇게 연장한 후에 반납예정일과 희망일이 올바로 입력되지 않고 있습니다.

**Comment by 10001if** [comment]
확인을 해보니 다음과 같이 체크 되었습니다.

예> 3박 4일 대여. 반납예정일(희망일) 8월 1일. 

1. 결제대기 상태에서 취업날개 연장하기 버튼을 누르면 
현재> 반납예정일(희망일) 8월 2일로 +1일 추가됨 
변경요청> 반납예정일(희망일) 8월 5일로 +4일 추가되어야 함
-> 현재는 대여확정 전 직접 날짜를 변경하는 방식으로 사용 중입니다.

2. 대여중의 경우 취업날개 연장하기 버튼을 누르면
현재> 반납예정일(희망일) 8월 1일로 변동없음
변경요청> 반납예정일(희망일) 8월 5일로 +4일 추가되어야 함
-> 대여확정 후 반납예정일을 수정할 수 없어 4일만큼의 연장비가 발생하고 있음. 빠른 수정이 요구됩니다.

**Comment by 10001if** [comment]
@aanoaa 수정이 완료된건가요? 오후에 확인해보니 수정이 되지 않은 것 같아서요~ 수정이 된 거라면 저희가 다시 한번 확인해보겠습니다~

**Comment by aanoaa** [comment]
수정은 되었지만 아직 배포되진 않았습니다.
오늘 중으로 배포할 예정입니다.

**Comment by 10001if** [comment]
@aanoaa 네~ 알겠습니다~ 배포 후 다시 확인해 보도록 하겠습니다~!
