### ISSUE TITLE
봉사신청 가능인원 수정 요청

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1297]
비수기와 성수기의 봉사자 업무량 차이가 많이 나는데 비해
미리 대처를 하지 못해 봉사자들이 업무가 없어 난처한 상황이 발생하고 있습니다. 

문제 해결을 위해, 비수기와 성수기를 미리 설정하고 
필요한 봉사자 인원도 미리 제한할 수 있도록 하고자 합니다. 

    비수기 : 1월, 7월, 8월
    성수기 : 나머지 기간

    비수기 봉사신청자 : 동시간대 2명
    성수기 봉사신청자 : 동시간대 4명

내년 1월까지 미리 설정해놓을 수 있다면 부탁드리고요, 
아니면 일단
**8월 비수기 인원, 9월부터 12월 성수기 인원 설정** 부탁드릴게요~

당분간은 봉사인원 관련해서는 수정 없을 예정입니다~

**Comment by pingpongworks** [comment]
폴더를 잘못 적어서 voluteer에 다시 적었어요. 이건 닫아버릴게요

**Comment by aanoaa** [comment]
업무량에 비해 효율이 극히 낮은 작업이라고 생각됩니다.
캘린더에 알람 띄워놓고 1년에 3회 인간이 하면 되는 작업입니다.

잉여력이 있다면 이런걸 자동화 하는 것도 나쁘지는 않겠습니다.

**Comment by pingpongworks** [comment]
네~ 캘린더에 체크해놓고 인원조정 필요할 때마다 한달 전에 요청드리겠습니다. 

> 현시점은 비수기니까 동시간대 2명씩, 
> 9월 7일부터는 동시간대 4명으로 조정부탁드립니다.
