### ISSUE TITLE
안양시 쿠폰 발급 요청

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1298]
https://github.com/opencloset/opencloset/issues/858 에서 진행해 주셨던 내용입니다.

`안양청년옷장`의 쿠폰 발행을 요청드립니다. 
- `suit` 타입으로
- 사용기간은 2017/12/31 까지
- 설명은 `안양청년옷장`
- 300개
- 총 이용 횟수는 151회로 제한 

안양시에서 진행하는 프로젝트를 위해 쿠폰 발급을 요청드립니다. 
열린옷장에서 300개의 쿠폰 번호만 전달하면 안양시에서 해당 청년에게 쿠폰번호를 전달하는 방식입니다. 이후 개인이 예약페이지를 통해 쿠폰 입력 후 예약을 진행한다고 합니다. 취업날개와 유사한 형식이지만 안양시 내부에서 연령, 나이, 이용횟수(1인당 최대 5회)를 체크하여 선정된 인원에게 쿠폰을 제공한다고 합니다. 따라서 열린옷장은 이상의 조건으로만 쿠폰을 발급하여 제공하면 됩니다. 

통계페이지는 취업날개와 동일하게 요청드립니다. 오프라인으로만 운영하므로 온-오프 구분은 필요하지 않습니다. 

쿠폰번호 발급은 8/1일까지 요청드립니다. 급박하게 요청드려 죄송합니다~

**Comment by aanoaa** [comment]
> 총 이용 횟수는 151회로 제한

쿠폰은 300개인데 151회 제한은 뭔지 모르겠네요.

**Comment by aanoaa** [comment]
``` perl
#!/usr/bin/env perl
use utf8;
use strict;
use warnings;

use Algorithm::CouponCode qw(cc_generate cc_validate);

use OpenCloset::Schema;

my $schema = OpenCloset::Schema->connect({ ... });

my $type    = 'suit';
my $desc    = 'anyangyouth';
my $expires = '2017-12-31T23:59:59';

for ( 1 .. 300 ) {
    my $code = cc_generate( parts => 3 );
    my $coupon = $schema->resultset('Coupon')->create(
        {
            code         => $code,
            type         => $type,
            desc         => $desc,
            expires_date => $expires
        }
    );

    unless ($coupon) {
        print STDERR "Couldn't create a new Coupon\n";
        next;
    }

    print "$code\n";
}
```

**Comment by aanoaa** [comment]
이메일을 통해 전달해 드렸습니다.

**Comment by aanoaa** [comment]
통계작업을 해야 합니다.

**Comment by aanoaa** [comment]
[OpenCloset-Cron-Visitor-v0.2.3.tar.gz](https://cpan.theopencloset.net/STAFF@THEOPENCLOSET.NET/OpenCloset-Cron-Visitor-v0.2.3.tar.gz) 배포하였습니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
