### ISSUE TITLE
전체 에누리 했는데 에누리가 아니됨

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#1300]
68583

전체 에누리했는데 연장료 에누리항목이 생성되지 않았습니다.

**Comment by aanoaa** [comment]
에누리 금액을 입력하면 동작하지만 `전체 에누리` 버튼을 눌렀을때는 동작하지 않았습니다.
동작하지 않았다는 것은 반납후에 `연체/연장료 에누리` 항목이 추가되지 않았다는 것 입니다.
이부분을 수정하였습니다.

**Comment by pingpongworks** [comment]
감사합니닷
