### ISSUE TITLE
반납일과 반납희망일이 없는 주문서가 발생함

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1301]
바코드가 전혀 읽히지 않는 주문서가 다시 나타났다고 합니다. 넣어둔 안내지를 통해 주문서는 찾았습니다. ~/orders/68787 
확인해보니 취업날개이고 반납일, 반납희망일이 없습니다. 전해 듣기론 지난 번과 같은 상황이라고 하여 이슈에 남겨놓습니다.

**Comment by 10001if** [comment]
@aanoaa 확인 해 주시면 그 이후에 반납을 처리하려고 합니다. 반납 해도 될지 답변 부탁드립니다.

**Comment by aanoaa** [comment]
#1299 와 같은 증상입니다.

    의류정보 -> 주문서 -> 전체반납

하였습니다.
가끔씩 반납희망일과 반납예정일이 없는 주문서가 발견되는데 왜 그런지 파악해서 고쳐야 합니다.

**Comment by aanoaa** [comment]
위 주문서는 제가 전체반납하였습니다.

**Comment by aanoaa** [comment]
주문서상세 화면이 변경된 이후로는,
반납희망일과 반납예정일은 `포장완료 -> 결제대기` 시점에 계산해서 저장합니다.

`OpenCloset::API::boxed2payment` 에서 처리하는데 이 메소드를 호출하는 route 는

    PUT /api/order/:id

밖에 없습니다.

주문서목록 > 포장완료 > `포장완료 -> 결제대기` 버튼이 위 route 를 사용합니다.

`boxed2payment` 메소드를 호출하지 않고 포장완료 상태의 주문서를 결제대기로 변경하는 다른 route 가 있는지 찾아봐야 합니다.

**Comment by aanoaa** [comment]
대여일 로그입니다.

```
[Mon Jul 31 14:07:10 2017] [debug] PUT "/api/order/68787.json"
[Mon Jul 31 14:17:51 2017] [debug] GET "/api/order/68787.json"
[Mon Jul 31 14:17:51 2017] [debug] PUT "/api/order/68787.json"
[Mon Jul 31 14:22:28 2017] [debug] GET "/api/order/68787.json"
[Mon Jul 31 14:22:28 2017] [debug] PUT "/api/order/68787.json"
[Mon Jul 31 14:23:58 2017] [debug] PUT "/api/order/68787.json"
[Mon Jul 31 14:39:08 2017] [debug] PUT "/api/order/68787"
[Mon Jul 31 14:39:08 2017] [debug] GET "/rental/order/68787"
[Mon Jul 31 14:47:49 2017] [debug] GET "/order/68787/rental/paper/pdf"
[Mon Jul 31 14:48:57 2017] [debug] GET "/orders/68787"
[Mon Jul 31 14:50:11 2017] [debug] POST "/orders/68787/rental"
[Mon Jul 31 14:50:11 2017] [debug] GET "/orders/68787"
[Mon Jul 31 14:50:32 2017] [debug] GET "/order/68787/return/"
[Mon Jul 31 14:50:32 2017] [debug] GET "/order/68787/extension/"
[Mon Jul 31 14:50:32 2017] [debug] GET "/order/68787/return/"
[Mon Jul 31 14:50:32 2017] [debug] GET "/order/68787/extension/"
[Mon Jul 31 14:50:39 2017] [debug] GET "/order/68787/extension/"
[Mon Jul 31 14:50:39 2017] [debug] GET "/order/68787/extension/"
```

`POST "/orders/68787/rental"` 요청은 `결제대기 -> 대여중` 입니다.
`PUT /api/order/68787` 말고 다른 요청은 없습니다.

**Comment by aanoaa** [comment]
`boxed2payment` 를 의심해봐야합니다.

**Comment by aanoaa** [comment]
혹은 그 이후에 들어있던 값을 NULL 로 변경하는 부분이 있는지 확인해봐야 합니다.

**Comment by aanoaa** [comment]
`새로주문` 버튼이 주문서의 반납희망일과 반납예정일을 `NULL` 로 변경합니다.
하지만 새로 주문하고 다시 `포장 -> 포장완료`, `포장완료 -> 결제대기` 절차를 거칠 것이기 때문에 문제 없습니다.

**Comment by aanoaa** [comment]
관련해서 디버그 로그 메세지를 추가하였습니다.
또다시 발생한다면 다시 한번 알려주세요. @10001if

**Comment by 10001if** [comment]
@aanoaa 알겠습니다. 또 발생하면 다시 말씀드릴게요~

**Comment by 10001if** [comment]
@aanoaa /orders/70240 주문서에서 또 발생했습니다. 현재는 반납처리하지 않은 상태입니다.

**Comment by 10001if** [comment]
반납희망일은 뒤로 미루고 문자가 발송하지 않도록 해놓았습니다.

**Comment by aanoaa** [comment]
![default](https://user-images.githubusercontent.com/170528/29504376-44de31bc-867a-11e7-8746-6014b4c22101.png)

포장완료 다음에 결제대기가 없습니다.
포장완료 상태에서 대여중으로 변경된 듯 싶습니다.

**Comment by aanoaa** [comment]
로그를 가지고 추적해봤습니다.

```
[Wed Aug 16 15:45:05 2017] [debug] PUT "/api/order/70240.json"    - 방문
[Wed Aug 16 15:50:17 2017] [debug] GET "/api/order/70240.json"
[Wed Aug 16 15:50:17 2017] [debug] PUT "/api/order/70240.json"    - 치수측정
[Wed Aug 16 15:52:16 2017] [debug] GET "/api/order/70240.json"
[Wed Aug 16 15:52:16 2017] [debug] PUT "/api/order/70240.json"    - 의류준비
[Wed Aug 16 15:55:11 2017] [debug] PUT "/api/order/70240.json"    - 탈의
[Wed Aug 16 16:09:56 2017] [debug] PUT "/api/order/70240"         - 포장
[Wed Aug 16 16:09:57 2017] [debug] GET "/rental/order/70240"
[Wed Aug 16 16:11:20 2017] [debug] POST "/order"                  - 포장완료
[Wed Aug 16 16:13:41 2017] [debug] GET "/order/70240/rental/paper/pdf"
[Wed Aug 16 16:14:14 2017] [debug] GET "/orders/70240"            - **여기서 잘못누름**
[Wed Aug 16 16:15:15 2017] [debug] POST "/orders/70240/rental"    - 대여중
[Wed Aug 16 16:15:15 2017] [debug] GET "/orders/70240"            - 대여완료후 redirect
```

주문서의 포장완료 목록에서 `포장완료 -> 결제대기` 버튼을 눌렀어야 하는데 실수로 주문서 번호를 누른 것 같습니다.
`포장완료` 상태인 주문서에서 `주문확정`을 한 것입니다.

포장완료에서 결제가 가능합니다.
이부분을 결제대기인 주문서만 가능하도록 고칠 필요가 있습니다.

![default](https://user-images.githubusercontent.com/170528/29544030-434e3a9e-8720-11e7-9c7e-fbd891cd23ea.png)

**Comment by aanoaa** [comment]
요약하면,
포장완료 목록에서 실수로 `포장완료 -> 결제대기` 버튼 대신에 주문서 id 를 클릭하고 주문확정을 했습니다.
이런 실수를 예방하기 위해서 결제대기 주문서에서만 `주문확정` 버튼이 보이도록 했습니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
