### ISSUE TITLE
크롬에서 의류태그가 출력되지 않음

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#1304]
Not allowed to navigate top frame to data URL: blahblahblah

오류가 나면서 아니됩니다.
어제까지는 됐다고 하는데..

**Comment by aanoaa** [comment]
https://stackoverflow.com/questions/45493234/jspdf-not-allowed-to-navigate-top-frame-to-data-url

> Apparently Google Chrome has removed support for top-frame navigation, you can see more informations here: https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/GbVcuwg_QjM

크롬에서 안되는 모양입니다.
제 firefox 에서는 잘 동작하고 있습니다.

client 에서 pdf 를 생성하고 있는데 이것을 server 에서 만들어내도록 하는 방법이 있을 수 있습니다.

    my $pdf = $c->render_to_string('invoice', format => 'pdf');
    $c->render(data => $pdf, format => 'pdf');

불편하겠지만 의류태그를 출력할때에는 chrome 대신에 firefox 를 사용하시길 바랍니다.
어떤 브라우저를 써도 안될때에는 수정하겠습니다.

**Comment by aanoaa** [comment]
cc @pingpongworks @10001if @MoDoLEE

**Comment by 10001if** [comment]
@aanoaa firefox를 쓴다고 특별히 불편하진 않을 것 같습니다. 원래 firefox를 기준으로 테스트 하신다고 해서 이걸 위주로 쓰고 있었는데 의류 태그 출력이 되지 않아 chrome을 사용하고 있었습니다. firefox에서 의류 태그 출력이 가능하다면 그냥 firefox를 사용하면 될 듯 합니다.
