### ISSUE TITLE
쿠폰입력창을 통해 들어온 대여자에게는 서울시 취업날개 안내를 보여주지 않도록 함

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#1306]
@aanoaa 안양시에서 요청이 왔는데, 안양시 요청과 별개로 앞으로 다른 쿠폰들이 발행되었을 때 취업날개 안내가 보여지는 것이 자연스럽지 않은 것 같아 https://visit.theopencloset.net/coupon 로 예약을 진행하는 대여자에게는 예약창 하단에 취업날개 안내를 제거하여 예약을 진행하도록 하고자 합니다. 

![2017-08-23 8 16 17](https://user-images.githubusercontent.com/4696328/29613238-1d0ca034-8840-11e7-83d2-b1417fb39e20.png)

빨간 박스 안에 내용이 제거된 상태로 예약 화면을 볼 수 있도록 요청드립니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
