### ISSUE TITLE
구두, 자켓, 팬츠, 셔츠, 블라우스 바코드 요청입니다.

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1307]
구두 시작코드 A1I7 ~ 마지막코드 A28J 이렇게 1개씩만 요청드립니다.
(구두는 왼쪽 오른쪽 구 둔데에 붙여야 해서 코드 하나당 2개가 필요한데, 지난 번에 실수로 한개만 요청드렸었네요. 그래서 하나를 따로 뽑아 쓰다가 아무래도 불편해서 남은 코드들 1개씩을 더 요청드리고자 합니다.)

자켓 1000개
팬츠 1000개
셔츠 1000개
블라우스 1000개

요청드립니다.

**Comment by aanoaa** [comment]
구두 한켤레에 코드가 두개 사용되나요?
어떻게 해드려야 하는지 모르겠습니다.

**Comment by 10001if** [comment]
@aanoaa 제가 파일이 있다는 사실을 깜빡했습니다. ^^; 

자켓 1000개
팬츠 1000개
셔츠 1000개
블라우스 1000개

바코드만 요청드립니다.

**Comment by aanoaa** [comment]
바코드는 donation 서비스의 `script/generate_code.pl` 스크립트를 사용해서 생성합니다.

사용방법은..

```
/path/to/donation.theopencloset.net $ perl script/generate_code.pl 
Usage:
        $ script/generate_code.pl jacket 10
        $ script/generate_code.pl jacket 10 --save
        $ script/generate_code.pl jacket 10 --save > jacket.csv

        $ script/generate_code.pl --list
        $ script/generate_code.pl --help
/path/to/donation.theopencloset.net $ perl script/generate_code.pl --list
belt, blouse, coat, jacket, onepiece, pants, shirt, shoes, skirt, tie, waistcoat, bag, misc
```

``` sh
#!/bin/sh
perl script/generate_code.pl jacket 1000 > jacket.csv
perl script/generate_code.pl pants  1000 > pants.csv
perl script/generate_code.pl shirt  1000 > shirt.csv
perl script/generate_code.pl blouse 1000 > blouse.csv
```

스크립트를 실행한 결과물을 zip 으로 압축하였습니다.

[codes.zip](https://github.com/opencloset/opencloset/files/1247915/codes.zip)

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
