### ISSUE TITLE
특정인에게 특정금액으로 가상계좌를 생성하여 문자를 보낼 수 있는 기능의 추가 

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1308]
이 이슈가 끊임없이 발생하고 있습니다. 요는 이렇습니다.

* 과거 : 입금요청을 보내는 가장 대표적인 경우는 미납과 불납입니다. 종전에는 실제 존재하는 계좌로 입금하는 방식을 택하여서 입금 내역을 확인하려면 문자나 인터넷 뱅킹을 사용해야 했습니다. 이는 바로 확인하기 어려운 문제와 확인을 하지 못하고 놓치는 문제를 발생시켰습니다. 또한 다른 예금주로 입금하는 경우 추적이 힘들었고 실제 입금과 주문서 내부의 완납으로 수저아는 프로세스는 별개로 진행이 되어 불편한 부분이 존재했습니다.

* 현재 : 가상계좌를 통해 금액이 정확히 들어오는 경우 입금여부를 신경쓰지 않고도 주문서가 변경되어 많은 업무가 정확도 있게 게선이 되었습니다.

* 문제점 : 하지만, 이 경우에도 금액에 미납이나 불납 금액의 변경이 발생한 경우에는 가상계좌를 생성할 방법이 없어 종전의 방식대로 계좌를 알려주고 금액을 입금 받고 있습니다. 그런데 현재 열린옷장 통장의 계좌 납입상황을 알 수 있는 사람은 2명입니다. 이 사람들이 공석이 되었을 때에는 입금 여부를 확인하기가 매우 까다롭습니다. 

미납/불납금액에 변동이 있는 이유는 아주 다양한데, 가령 연체 3일이라고 생각하여 미납 문자를 발송했는데, 자신은 연장을 신청했었다고 주장하거나 실제 현장에서 연장을 요청한 경우들이 있고 불납의 경우도 금액을 수정하여 요청해야 할 상황이 계속 발생하고 있습니다.

 i) 가상계좌가 주문서와 연동되는 경우와 ii) 주문서와 연동되지 않는 경우 (단체 대여 선납비 등) 이 있을 것 같은데, 가상계좌 문자 발송 기능 자체를 생성하는 것이 복잡한 문제라면 현재 주문서에서 금액을 수정하여 가상계좌 문자를 발송할 수 있게 하는 기능을 요청드립니다.

**Comment by aanoaa** [comment]
금액 - `10,000`
계좌유효기간 - 3일?
예금주 - `열린옷장-홍길동`
은행 - `국민은행`?
전화번호

    10,000원 열린옷장-홍길동 국민은행 xxx-xxx-xxxx 으로 09-11 까지 입금해주세요.

주문서와는 관계없이

1. 발송될 문자 메세지 템플릿을 정해두거나
2. 가상계좌를 만들고 이를 확인할 수 있도록 하거나

하면 되지 않을까요?

입금되었을때 확인은 어떠한 방식으로 하실건가요?

@10001if

**Comment by 10001if** [comment]
@aanoaa 이야기 주신 것처럼 주문서와 관계없이 

1. 발송될 문자 메세지의 메세지 템플릿이 정해져 있고
2. 가상계좌를 만들고 이를 확인할 수 있게 하면

현재 발생하고 있는 문제를 해결할 수 있습니다.

다만, 입금 되었을 때 확인하는 방법은 아임포트 페이지를 통해 확인하려고 하는데 입금이 되면 입금이 되었다는 알림을 받을 수 없어 실시간으로 확인하는 것이 어려울 것 같습니다. 다시 말해, 돈이 입금되었을 경우 입금된 자체는 아임포트 페이지에서 확인이 가능하나, 입금이 들어온 순간 입금 여부를 알려주는 기능이 추가되면 좋을 것 같습니다.

**Comment by aanoaa** [comment]
입금후에 알림을 받을 채널이 필요한데,
info@theopencloset.net 으로 이메일을 보낼까요?
잔디의 특정 채널에 알려주는 방법도 있을 것 같은데, 제가 사용해보지 않아서 모르겠네요.

**Comment by aanoaa** [comment]
[잔디 커넥트 '웹훅(Incoming Webhook)'으로 외부 데이터를 잔디 메시지로 수신하기](https://jandi.zendesk.com/hc/ko/articles/210952203-%EC%9E%94%EB%94%94-%EC%BB%A4%EB%84%A5%ED%8A%B8-%EC%9B%B9%ED%9B%85-Incoming-Webhook-%EC%9C%BC%EB%A1%9C-%EC%99%B8%EB%B6%80-%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%A5%BC-%EC%9E%94%EB%94%94-%EB%A9%94%EC%8B%9C%EC%A7%80%EB%A1%9C-%EC%88%98%EC%8B%A0%ED%95%98%EA%B8%B0)

**Comment by 10001if** [comment]
@aanoaa 이메일로 확인하는 것도 가능한데, 가능하다면 잔디로 받을 수 있다면 훨씬 더 좋을 것 같습니다. 잔디는 놓치지 않고 바로 확인할 확률이 훨씬 높습니다.

**Comment by aanoaa** [comment]
> 잔디 커넥트 '웹훅(Incoming Webhook)'으로 외부 데이터를 잔디 메시지로 수신하기

링크를 참고해서,
알림을 받고자 하는 잔디 채널의 WebHook URL 을 저한테만 알려주세요.

**Comment by 10001if** [comment]
WebHook URL은 행아웃으로 전달하였습니다.

**Comment by aanoaa** [comment]
- 주문서와 관련있는 가상계좌
  - 입금된 후에 무슨 처리를 해야 하는지?
  - 어디에서 어떤 방식으로 가상계좌를 만들어서 전송하면 좋을지?
- 주문서와 관련없는 가상계좌
  - 입금된 후에 무슨 처리를 해야 하는지?
  - 어디에서 어떤 방식으로 가상계좌를 만들어서 전송하면 좋을지?

두 경우 모두 잔디에 알림을 줄 수는 있습니다.

**Comment by aanoaa** [comment]
잔디에 메세지를 좀 더 쉽게 전송하기 위해서 아래 모듈을 cpan 에 배포하였습니다.
https://github.com/aanoaa/WebService-Jandi-WebHook

**Comment by 10001if** [comment]
@aanoaa 
- 주문서와 관련 있는 경우
 - 주문서의 상태가 직접 변경하도록 작동되는 기능이 필요합니다.
 - 어디에서 어떤 방식으로 가상계좌를 만들어서 전송하면 될 지는 구체적으로 한번 더 확인한 뒤 남기도록 하겠습니다. 

- 주문서와 관련없는 가상계좌의 경우
 - 입금된 후에 입금에 관련된 후속 처리가 필요합니다.
 - 어디에서 어떤 벙식으로 가상계좌를 전송할지 고민 후에 다시 남기겠습니다.

정확하게 확인 한 후 다시 답변드리도록 하겠습니다.

**Comment by 10001if** [comment]
@aanoaa 다음과 같이 요청드립니다.

1. 연체/연장비 외에 금액을 송금받아야 하는 경우나 금액이 잘못 기입되어 수정이 필요한 경우
SMS 보내기 버튼을 누른다. 
![2017-09-13 12 30 20](https://user-images.githubusercontent.com/4696328/30358563-3aa8dc48-9880-11e7-85b4-67e23b5c9608.png)

2. 그 이후에는 SMS 보내기 화면으로 이동한다.

3. 화면에서 가상계좌를 생성하여 매크로 뒤에 붙인다. - 가상계좌 생성 버튼을 누르면 금액을 누를 수 있도록 하고 금액을 입력하면 계좌, 금액, 유효기간이 입력된다.

![2017-09-13 12 37 59](https://user-images.githubusercontent.com/4696328/30358732-6ccea710-9881-11e7-908a-e59523160f67.png)


4. 입금이 완료되면 잔디 토픽을 통해 알림을 전달한다.

**Comment by 10001if** [comment]
잔디 토픽은 새로 생성하였습니다. 기존에 사용하던 토픽으로 전달이 오면 정신이 없을 것 같아서요. 이 쪽으로 알림 전달 요청드립니다.

**Comment by 10001if** [comment]
@aanoaa 주문서를 바로 변경하도록 하는 기능은 추가하지 않도록 했습니다. 입금 알림만 오면 저희가 직접 주문서를 수정하도록 하겠습니다.

**Comment by aanoaa** [comment]
남겨주신 내용으로 볼때에,
주문서에서는 가상계좌로 바로가기 할 수 있는 링크만 남기고 주문서와 관련없는 가상계좌만 만드신다는 건가요?

**Comment by 10001if** [comment]
@aanoaa 우선 주문서와 관계없는 경우부터 작성하겠습니다.

![2017-09-13 12 37 59](https://user-images.githubusercontent.com/4696328/30361605-e489ede4-9892-11e7-8263-887f2a050f73.png)

주문서와 관계가 없는 경우에는 `sms 문자전송` 기능을 통해 발송하는 것으로 하겠습니다.
이런 경우의 발송은 다음과 같습니다.
ex> 9명이 단체 대여를 실시하였는데, 결제는 다른 1인이 진행하는 경우. 이 경우는 주문서와 관계없이 돈을 입금받아야 하는 경우입니다. 

이 경우에 발송할 때에는 주문서의 변경이 동반되지 않습니다.

이 경우에는 문자를 전송할 때 기존의 문자 매크로에 가상계좌만 추가하여 보낼 수 있으면 됩니다.
돈이 입금되면 잔디 알림으로 입금 여부를 확인합니다.

다만, 이 과정에서 가상계좌를 만들 때 필요한 정보가 무엇인지 잘 모르겠습니다. 지난번에 설명을 잠깐 듣기로는 계좌와 금액만 확인하여 일치 여부를 체크한다고 들었는데, 만약 이름 등 다른 정보가 필요하다면 가상계좌 생성시 정보를 입력할 수 있도록 해야 할 것 같습니다. 가상계좌 생성에 필요한 정보가 무엇인지 확인을 부탁드리겠습니다.

**Comment by 10001if** [comment]
주문서와 관계 있는 경우에는 다음과 같이 요청드리고자 합니다. 

주문서와 관계 있는 경우에는 주문서의 변경이 동반되어야 합니다.
그렇기 때문에 `sms 문자전송`기능을 통해 발송하는 것이 아니라, 주문서 내부에서 바로 계좌를 만들어 전송할 수 있어야 하고 입금 시에는 필요한 상황에 따라 주문서가 변동되어야 합니다. 

주문서와 관계 있는데, 현재 미납/불납 가상계좌 외에 진행되어야 하는 상황은 
1. 미납/불납 이지만 그 금액이 주문서에 들어 있는 금액과 다른 경우
2. 배상비가 발생한 경우
3. 대여금액에 오류가 있는 경우 (ex> 자켓 타이 대여한 경우 금액이 12,000원이어야 하나 타이가 0원으로 설정되어 실수로 10,000원으로 대여금액을 받은 경우)

2, 3의 경우에는 위에 주문서와 관계없는 문자전송 기능을 통해 문제를 해결할 수 있습니다. 하지만 1번의 경우에는 문제를 해결하기가 어렵습니다. 따라서 주문서와 관계 있는 경우에 가상계좌를 보내야 하는 경우는 1번의 경우만 해당됩니다.

이를 위해 다음과 같이 요청드립니다.

![2017-09-13 3 38 31](https://user-images.githubusercontent.com/4696328/30363433-0bfc2eca-989b-11e7-93f4-eae8f70ac360.png)

이와 같이 정상적인 경우에는 가상계좌 버튼을 눌러 문자를 발송하지만, 금액에 차이가 있고 입금시에 주문서의 바로 변동이 필요한 경우에는 가상계좌 전송 버튼 옆에 수정버튼을 눌러 그 금액을 수정하고자 합니다. 다른 이슈는 없고 금액만 수정하면 되는 이슈이기 때문에 수정 버튼을 누르면 완납 버튼을 누르면 
![2017-09-13 3 50 49](https://user-images.githubusercontent.com/4696328/30363488-5bbb941e-989b-11e7-8e0f-cc3c11de83e6.png) 나타나는 화면이 나타나 원래 금액을 안내해주고 하단에 박스에서 수정할 금액을 입력하도록 하여 확인 버튼을 누르게 하여 문자를 전송하고자 합니다.

**Comment by 10001if** [comment]
수정완료 버튼을 누르면 바로 가상계좌가 발송되도록 하고자 합니다.

**Comment by aanoaa** [comment]
> 가상계좌 생성에 필요한 정보가 무엇인지 확인을 부탁드리겠습니다.

> 금액 - 10,000
> 계좌유효기간 - 3일?
> 예금주 - 열린옷장-홍길동
> 은행 - 국민은행?
> 전화번호

https://github.com/opencloset/opencloset/issues/1308#issuecomment-327984081

**Comment by 10001if** [comment]
주문서와 연관 없는 가상계좌를 보낼 때 필요한 정보는

금액 / 상대방 이름(예금주) 로 보여집니다. 계좌유효기간 / 열린옷장 이름(예금주) / 은행 / 전화번호는 상대방이 달라지는 것에 따라 변동이 있는 값이 아니기 때문입니다. 그렇다면 가상계좌 발송 전에 금액과 이름(예금주)를 입력한 뒤 완료를 누르면 매크로 뒤에 계좌가 생성되어 붙을 수 있도록 요청드립니다.

그런데, 전화번호는 열린옷장 전화번호가 맞나요?

**Comment by aanoaa** [comment]
https://staff.theopencloset.net/sms/macros

여기에서 매크로와 함께 발신번호도 함께 관리할 수 있습니다.
열린옷장 전화번호가 맞는지 여부는 모르겠습니다.

**Comment by 10001if** [comment]
@aanoaa 발신번호 관리는 알고 있습니다. 그럼 가상계좌를 만들 때 저희가 새로 입력해야 하는 내용은 사용자의 이름과 금액으로 보여집니다. 가상계좌 생성시 두 가지만 입력할 수 있게 한 뒤에 저희가 입력하여 가상계좌를 생성하도록 요청드립니다.

**Comment by aanoaa** [comment]
결제정보를 `payment` 에 저장하고 있는데, 주문서 번호가 NULL 이면 안됩니다.
실패했을때 추적하기 위해 보험을 들어놓았던 것 같은데,

payment 에 결제 정보를 저장하지 않고 iamport 만을 사용해서 가상계좌를 만들고 후처리를 할 수 있을지
검토해봐야 합니다.

**Comment by aanoaa** [comment]
임의로 주문서를 만들어서 처리하는 방법도 있습니다.

**Comment by aanoaa** [comment]
가상계좌에 입금되면 hook 을 받아야 하는 테스트를 로컬머신에서는 할 수가 없습니다.
배포하고 서버에서 테스트하도록 하겠습니다.

**Comment by aanoaa** [comment]
배포하고 가상계좌를 만들어서 이체했습니다.
입금했는데 아직 미결제라고 나타나고 있습니다.
반영되려면 어느정도 시간이 필요한 것 같습니다.

결제완료로 변경되었을때에 잔디에 메세지가 올바르게 전송되는지 확인해봐야 합니다.

**Comment by aanoaa** [comment]
영수증 링크가 없는 점을 제외하면 정상적으로 동작하고 있습니다.

**Comment by aanoaa** [comment]
미납금 가상계좌가 입금되었을때에 잔디에 메세지가 올바르게 전송되는지 확인이 필요합니다.

**Comment by 10001if** [comment]
@aanoaa 가상계좌를 생성하고 생성된 계좌로 돈이 입금되었을 때 잔디로 알림이 오는 기능까지 확인하였습니다. 

그런데, 다음과 같은 이슈가 있습니다.

1. 주문서와 연관없는 경우
만들어 주신 기능을 이용하면 충분하지만, 다만 주문서와 연관이 없는 경우에는 주문서 자체가 없기 때문에 본 기능을 통해 가상계좌를 전송할 수가 없습니다.

2. 주문서와 연관있는 경우
다음과 같은 기능으로 가상계좌를 발송할 수 있지만, 계좌로 입금된 뒤에는 주문서의 변동이 필요합니다. 그런데 현재는 잔디 알림만 받을 수 있습니다.

1번의 경우에는 현재 주문서가 없이는 가상계좌를 발송할 수가 없는 문제가 있습니다.
2번의 경우에는 가상계좌로 정상입금되면 주문서가 변경되어야 하는데, 현재는 주문서 자동 변경이 이뤄지지 않습니다.

확인 부탁드리겠습니다.

**Comment by 10001if** [comment]
@aanoaa 지금 확인을 해보니 가상계좌 생성 버튼을 누르면 ~api/vbank에서
{"text":"[열린옷장] ***님 국민은행 59519013846*** 열린옷장-*** 1,000 원 입금해주세요."} 
창이 뜨고 정상적으로 가상계좌가 작동하지 않습니다. 확인 부탁드립니다.

**Comment by aanoaa** [comment]
새로고침을 해보세요.

![default](https://user-images.githubusercontent.com/170528/30483374-b73e4ec2-9a61-11e7-8177-fcc346ee5bc0.png)

주문서에서 휴대전화번호를 누르면 임의의 가상계좌를 만들 수 있고,

![default](https://user-images.githubusercontent.com/170528/30483375-b7404ae2-9a61-11e7-9fc2-cef8432f9699.png)

위와같이 결과가 나오게 됩니다.

**Comment by aanoaa** [comment]
> 1번의 경우에는 현재 주문서가 없이는 가상계좌를 발송할 수가 없는 문제가 있습니다.

/sms?vbank=1 로 접속해보세요.

> 2번의 경우에는 가상계좌로 정상입금되면 주문서가 변경되어야 하는데, 현재는 주문서 자동 변경이 이뤄지지 않습니다.

금액을 변경하는 기능
잔디에 메세지를 보내는 기능

을 추가했을 뿐 입금후엔 미납에서 완납처리되는 기능은 변경이 없었습니다.

**Comment by 10001if** [comment]
@aanoaa 
1. /sms?vbank=1 주소를 입력하여 접속하기가 상당히 번거로울 것 같습니다.
![2017-09-16 4 10 05](https://user-images.githubusercontent.com/4696328/30510160-c2ca53f6-9af9-11e7-97ab-99bf968261be.png)
그림처럼 문자전송 페이지에서 가상계좌 문자를 전송할 수 있는 페이지로 넘어갈 수 있는 링크 버튼 생성을 요청드립니다.

2. 완납처리되는 기능의 변경이 없었다는 부분에 대해 이해하였습니다. 

1번 버튼 생성만 요청드립니다. 굉장히 유용하게 사용될 것 같습니다. 감사합니다.
