### ISSUE TITLE
온라인 / 오프라인 통계 페이지의 수정

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1311]
@keedi 온라인으로 이용된 내역은 정산시 온라인으로 처리하는 것이 올바르다는 의견을 주셨습니다. 저희도 그렇게 하는 것이 옳은 방법이라고 생각을 하고 있습니다. 하지만 현재는 정산을 할 수 있는 정보가 존재하지 않습니다. 따라서 다음과 같이 요청드리고자 합니다.

1. 총합산 통계
온라인-오프라인 대여를 합산 한 통계가 필요합니다.

월/주/일별

예약자 | 방문자 | 미방문자 | BestFit | 대여자
-- | -- | -- | -- | --

ㄱ. 전체 통계
 ㄴ. 세부 통계 
  a. 열린옷장 순 이용자
  b. 취업날개 이용자
  c. 안양시 이용자
  d. 기타 등등

2. 오프라인 통계
 ㄱ. 전체 통계
 ㄴ. 세부 통계 
  a. 열린옷장 순 이용자
  b. 취업날개 이용자
  c. 안양시 이용자
  d. 기타 등등

3. 온라인 통계
 ㄱ. 전체 통계
 ㄴ. 세부 통계 
  a. 열린옷장 순 이용자
  b. 취업날개 이용자
  c. 안양시 이용자
  d. 기타 등등

요약하자면 다음과 같습니다. 

1. 온오프 전체 합계 통계
2. 오프라인 합계 통계
3. 온라인 합계 통계
** 열린옷장 순 이용자 + 쿠폰 사용별 횟수 확인

**Comment by aanoaa** [comment]
### 방문자 수 통계 ###

오프라인 - https://staff.theopencloset.net/stat/visitor
온라인 - https://staff.theopencloset.net/stat/visitor/online

### 각종 이벤트 통계 ###

    https://staff.theopencloset.net/stat/events/:event

- `seoul-2017`
- `gwanak`
- `10bob`
- `happybean`
- `incheonjob`
- `anyangyouth`
- `linkstart`

온라인 `?online=1`
오프라인 `?online=1`

https://staff.theopencloset.net/stat/events/seoul-2017
https://staff.theopencloset.net/stat/events/seoul-2017?online=1
https://staff.theopencloset.net/stat/events/seoul-2017?online=0

----------------------------

이것으로 부족하단 말씀인가요?

**Comment by 10001if** [comment]
@aanoaa 방문자 수 통계와 이벤트 수 통계에 대해 제가 제대로 숙지하지 못하고 있었습니다.

취업날*로 정산을 할 때에는 취업날개 이벤트 전체(취업날* 통계 사이트와 동일하다는 가정 하에) 
즉, https://staff.theopencloset.net/stat/events/seoul-2017 를 확인하면 되고

사일렉*에 온라인 정산을 실시할 때에는 온라인 전체 정산금액 + 취업날개 온라인 이용자 총 금액(30,000원*취업날개 온라인 이용자 수)으로 정산을 실시하면 됩니다. 취업날개는 정산금액이 없기 때문에 온라인 금액에서 매출로 잡히지 않기 때문입니다.

서울시에 요청하는 결제 금액과 사일렉*에 정산해야 하는 이슈가 서로 달라 혼동하고 있었습니다. 

결론적으로 다른 추가 작업은 필요하지 않겠습니다. @keedi 아직 온라인 정산을 확인할 수 있는 통계가 없을거라고 하셨는데, 지금 다시 생각해보니 현재 통계로도 정산이 가능한 것으로 보입니다. 혹시 제가 잘못 이해한 부분이 있다면 알려주세요.

**Comment by 10001if** [comment]
이슈 닫겠습니다.
