### ISSUE TITLE
추석 연휴로 인한 온라인 배송

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1313]
추석 연휴로 인한 온라인 배송

[추석 전]
착용일이 9/24인 경우(발송 예정일 9/20) 까지만 주문이 가능하게 해야 합니다.
그 이후에는 배송지연 때문에 제때 못 받아볼 수 있습니다.

[추석 후]
착용일 10/19인 경우 (발송 예정일 10/16) 부터 주문이 가능하게 해야 합니다.
연휴 이후에도 밀린 배송 물량 때문에 배송지연이 발생할 수 있습니다.

적용요청드립니다.

**Comment by aanoaa** [comment]
의류착용일이 09-24(일) 이면 09-20(수) 보내서 09-22(금) 배송받게됩니다.
이게 문제가 있나요?
어떻게 바뀌어야 하나요?

참고할만한 값 입니다.

    # 발송(예정)일 = 주말 + 공휴일 + 0일    # AM 10:00 이전
    # 발송(예정)일 = 주말 + 공휴일 + 1일    # AM 10:00 이후
    # 도착(예정)일 = 발송(예정)일 + 공휴일 + 주말 + 2일
    # 의류착용일   = 도착(예정)일 + 1일
    # 대여일      = 의류착용일 - 1일
    # 반납일      = 대여일 + 대여기간(default 3일)
    # 택배일      = 반납일 - 1일

2017-09-20 은 수요일이고 AM 10:00 이전과 이후로 나누어서 생각해봐야 합니다.

```
2017-09-20 (수) 10:00:00 기준
발송: 2017-09-20(수)
대여: 2017-09-22(금)
착용: 2017-09-23(토)
택배: 2017-09-24(일)
반납: 2017-09-25(월)
```

```
2017-09-20 (수) 11:00:00 기준
발송: 2017-09-21(목)
대여: 2017-09-25(월)
착용: 2017-09-26(화)
택배: 2017-09-27(수)
반납: 2017-09-28(목)
```

**Comment by aanoaa** [comment]
```
2017-10-16 (월) 10:00:00 기준
발송: 2017-10-16(월)
대여: 2017-10-18(수)
착용: 2017-10-19(목)
택배: 2017-10-20(금)
반납: 2017-10-21(토)
```

AM 10:00 이전이라면 10/19(목) 착용하는 주문에 대해선 10/16(월) 보내야 합니다.
별다를게 없어 보입니다.

**Comment by 10001if** [comment]
쉽게 말해서 발송 예정일 9/21부터 10/15까지 주문을 할 수 없도록 해야 합니다. 해당 기간에는 물류대란으로 택배 업무가 정상적으로 이뤄지지 않을 가능성이 크기 때문입니다.

**Comment by aanoaa** [comment]
2017-09-21 ~ 2017-10-15 까지 `택배물류지연` 명목으로 공휴일처럼 지정했습니다.
그기간에 의류착용일을 선택해서 주문하는 사람들은 모두 2017-09-18 일 발송하게 되는 문제가 있습니다.

이것은 원하는 것이 아니고, `2017-09-21 ~ 2017-10-15` 사이를 의류착용일로 지정할 수 없게 해야 합니다.
