### ISSUE TITLE
사용자의 이메일이 없는 경우가 존재함

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#1315]
사용자 id: 9300

는 email 이 비어있습니다.(``)
사용자 정보를 삭제하거나 임의로 이메일을 변경해주어야 합니다.
2015 년도에 한건 반납된 이력이 있습니다.
사용자 정보를 삭제하면 해당 데이터도 잃어버립니다.

**Comment by aanoaa** [comment]
이메일이 없을때에 보통의 경우에는 `휴대전화번호@theopencloset.net` 으로 설정하는데,
이분은 휴대전화번호도 없습니다.

**Comment by keedi** [comment]
진행합니다.

상황 파악 및 어떻게 처리할지 결정하겠습니다.

**Comment by keedi** [comment]
상황 파악 중입니다.

해당 9300 사용자의 정보는 다음과 같습니다.

```
mysql> select * from `user` where email is not null and email = "";
+------+-----------+-------+-----------+----------+------------+---------------------+---------------------+
| id   | name      | email | password  | authcode | expires    | create_date         | update_date         |
+------+-----------+-------+-----------+----------+------------+---------------------+---------------------+
| 9300 | 강****    |       | ...       | NULL     | 1422088979 | 2015-01-24 17:39:19 | 2015-01-27 17:18:16 |
+------+-----------+-------+-----------+----------+------------+---------------------+---------------------+
1 row in set (0.00 sec)

mysql> select id, user_id, staff_id, purpose, create_date, update_date from `order` where id=1290;
+------+---------+----------+-----------+---------------------+---------------------+
| id   | user_id | staff_id | purpose   | create_date         | update_date         |
+------+---------+----------+-----------+---------------------+---------------------+
| 1290 |    9300 |        4 | 결혼식    | 2015-01-24 17:42:59 | 2015-01-27 17:09:38 |
+------+---------+----------+-----------+---------------------+---------------------+
1 row in set (0.00 sec)
```

사용자 생성 및 방문 예약일이 2015년 1월 24일, 반납일이 1월 27일 인것으로 추정됩니다.

**Comment by keedi** [comment]
관련해 내용 파악을 위해 2015년 2월 1일 이전 이슈를 검색해보았습니다. 검색 매개변수는 다음과 같습니다.

`is:issue updated:<2015-02-01`

추억이 돋...는데... 여튼 2014년 12월 17일에 공식 서비스가 오픈했으며, 당시 2015년 1월이면 꽤나 오픈 직후인 초창기로 사료됩니다. 이 당시 상황을 고려하면 물론 이메일 검증을 했지만 이메일과 관련해 입력 검증이 부족했을 수 있습니다. 또는 이 때 관리자 모드로 예약 및 대여를 진행했을 수도 있습니다. 이메일이 `NULL`이 아니라 빈 문자열이므로 가능성은 상기 두 가지 중 하나로 사료됩니다.

**Comment by keedi** [comment]
상기 질의를 살펴봐도 알수 있지만 현재는 더이상 빈문자열 이메일을 가진 사용자는 없습니다. 물론 대여진행을 완료하지 않는 경우는 꽤 많기 때문에 이메일이 `NULL`인 경우는 많으며, 이것이 이상한 것은 아닙니다.

상기 9300 사용자는 현 시점 기준으로 정확한 이메일을 알 방법이 없으므로 전화번호를 이용해 가상의 이메일을 생성하는 것으로 마무리 하겠습니다.

**Comment by keedi** [comment]
전화 번호의 경우 입력할 수 없을 때(그 때 당시 연락처를 공개하지 않는 기증자였습니다.) `999YYMMDD## ` 절차를 따르도록 열린옷장에 조언을 주었습니다. 즉 이메일은 자연스럽게 `999YYMMDD##@theopencloset.net`이 됩니다.

현재 대여자는 2015년 1월 24에 방문했으므로 `99915012401`과 `99915012401@theopencloset.net`으로 셋팅해서 해결합니다.

**Comment by keedi** [comment]
해당 사용자의 경우 대여 목적 부터 시작해, 생년까지 빠진 부분이 무척 많습니다. 아마도 관리자 모드로 추가한 경우가 아닐까 싶긴합니다. 어찌됐든 해당 이슈는 언급한 휴대폰 번호와 이메일 주소를 실 DB에 밀어넣어 처리했습니다.

이슈 닫습니다.
