### ISSUE TITLE
주문서 - 연체중 리스트 들어가면 502 bad gateway 가 발생하는 오류 발견

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1316]
주문서 - 연체중 리스트 들어가면 502 bad gateway 가 발생하여 연체중인 목록을 확인하지 못하고 있습니다. 오류 확인 부탁드립니다.

**Comment by aanoaa** [comment]
미납금액을 수정가능하도록 가상계좌 문자전송을 변경하면서 발생한 문제입니다.

72c7bb3702563929b3bd7b529ec01e43dc6898e9

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
