### ISSUE TITLE
한신대 쿠폰 발행

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1319]
https://github.com/opencloset/opencloset/issues/858 에서 진행해 주셨던 내용입니다.

`한신대 쿠폰`의 쿠폰 발행을 요청드립니다. 
- `suit` 타입으로
- 사용기간은 2017/12/31 까지
- 설명은 `한신대학교`
- 200개
- 총 이용 횟수는 100회로 제한 

한신대학교에서 진행하는 프로젝트를 위해 쿠폰 발급을 요청드립니다. 
열린옷장에서 200개의 쿠폰 번호만 전달하면 한신대학교에서 해당 청년에게 쿠폰번호를 전달하는 방식입니다. 이후 개인이 예약페이지를 통해 쿠폰 입력 후 예약을 진행한다고 합니다. 취업날개와 유사한 형식이지만 한신대학교 내부에서 연령, 나이, 이용횟수(1인당 최대 5회)를 체크하여 선정된 인원에게 쿠폰을 제공한다고 합니다. 따라서 열린옷장은 이상의 조건으로만 쿠폰을 발급하여 제공하면 됩니다. 

통계페이지는 취업날개와 동일하게 요청드립니다. 오프라인으로만 운영하므로 온-오프 구분은 필요하지 않습니다. 

쿠폰번호 발급은 10/18일까지 요청드립니다.

**Comment by aanoaa** [comment]
> 총 이용 횟수는 100회로 제한

이건 200개 쿠폰을 만들되 한신대학교 쿠폰이 100회 이상 사용되면 그 이후는 사용할 수 없어야 하는 건가요?

**Comment by 10001if** [comment]
@aanoaa 네, 맞습니다. 쿠폰 100장을 전달해서 100장이 모두 사용되면 괜찮지만 모두 사용하지 않을 수 있으므로 여유분을 더 전달하려고 합니다. 대학교 측에서 이에 대한 안내는 완료했습니다.

**Comment by aanoaa** [comment]
발행한 곳으로 이용횟수를 제한하는 기능은 없었습니다.
이번에 발행하면서 같이 적용되어야 하겠습니다.

**Comment by 10001if** [comment]
@aanoaa 바쁘시겠지만~ 오늘까지 쿠폰 요청드리겠습니다.

**Comment by aanoaa** [comment]
[OpenCloset-Cron-Visitor-v0.2.4.tar.gz](https://cpan.theopencloset.net/STAFF@THEOPENCLOSET.NET/OpenCloset-Cron-Visitor-v0.2.4.tar.gz) 배포하였습니다.
이를 서버에 설치하고 적용시켜야 합니다.

**Comment by aanoaa** [comment]
이용횟수 제한기능은 쿠폰코드를 입력할때에 쿠폰타입별 이용횟수를 카운트해서 발행을 막는 방법이 있을 수 있습니다.
아직 시간적 여유가 있으니까 이번에는 발행만 하고 이용횟수 제한은 추후에 기능을 넣도록 하겠습니다.

**Comment by aanoaa** [comment]
오늘부터 hanshin_univ 이벤트 사용자 통계가 수집될 것 입니다.

https://staff.theopencloset.net/stat/events/hanshin_univ

지금은 에러화면이 나타나지만 최초 통계가 수집된 이후부터는 제대로 표시될 것입니다.

**Comment by aanoaa** [comment]
```perl
#!/usr/bin/env perl
use utf8;
use strict;
use warnings;

use Algorithm::CouponCode qw(cc_generate cc_validate);

use OpenCloset::Schema;

my $schema = OpenCloset::Schema->connect( {...} );

my $type    = 'suit';
my $desc    = 'hanshin_univ';
my $expires = '2017-12-31T23:59:59';

for ( 1 .. 200 ) {
    my $code = cc_generate( parts => 3 );
    my $coupon = $schema->resultset('Coupon')->create(
        {
            code         => $code,
            type         => $type,
            desc         => $desc,
            expires_date => $expires
        }
    );

    unless ($coupon) {
        print STDERR "Couldn't create a new Coupon\n";
        next;
    }

    print "$code\n";
}
```

**Comment by aanoaa** [comment]
이메일로 전달해드렸습니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
