### ISSUE TITLE
결제대기 주문서의 예약변경(취업날개)

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1320]
#909 이슈와 동일합니다.

기존에는 진행이 잘 되었는데,

추석 연휴 이후(확실하지는 않습니다)부터 결제대기 주문서의 예약변경이 진행되지 않는다고 하네요.

오늘 예약변경이 되지 않았던 주문서 입니다. 확인 부탁드립니다.

/orders/76906 , /orders/76956

**Comment by aanoaa** [comment]
해당 사용자의 Agent 입니다.

    "Mozilla/5.0 (Linux; Android 6.0.1; SM-A500L Build/MMB29M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/61.0.3163.98 Mobile Safari/537.36 NAVER(inapp; search; 550; 8.2.3)"

지난번과 똑같은 상황입니다.
coupon.theopencloset.net 에서 coupon_code 를 암호화한 쿠키에 담아서 visit.theopencloset.net 으로 넘겼고,
visit.theopencloset.net 에서는 암호화된 쿠키를 풀었는데 coupon_code 가 없는 상황입니다.

**Comment by aanoaa** [comment]
이슈가 파편화 되서 #909 는 닫고 이곳에서 진행합니다.

> @aanoaa /orders/77382 주문서에서도 예약변경이 되지 않았다고 합니다. 이 분은 컴퓨터에서 예약을 진행하셨는데 변경이 되지 않았다고 하는데요. 이분은 안양시 쿠폰이라 서울시와는 다르게 쿠폰 입력하는 창을 통해 예약을 진행하였습니다. 혹시 서울시만 예약변경이 되고 다른 쿠폰은 기능 구현이 되지 않았나요? 확인 부탁드립니다~

----------------------------------------

> 발행한 곳과는 상관없습니다.
> 예로 볼때에 모든 결제대기 주문서에서 쿠폰을 사용하도록 예약변경을 해도 적용이 되지 않는 것 같습니다.
> 어떤 패치 이후에 동작하지 않는 것 같습니다.

**Comment by aanoaa** [comment]
찾았습니다.

https://github.com/opencloset/opencloset/commit/12c47e8640cb6122d1efa7d5f5ac4a8a3436cc49
https://github.com/opencloset/OpenCloset-API/blob/develop/lib/OpenCloset/API/Order.pm#L321
https://github.com/opencloset/OpenCloset-API/commit/36f4a9a54e7497421b8183d42a06f1fdc234952c

RESERVATED(방문예약) 뿐만 아니라 PAYMENT(결제대기) 상태일때에도 예약이 변경가능하도록 해야 합니다.

9/20 부터 기능이 동작하지 않았습니다.

**Comment by aanoaa** [comment]
해결책은 OpenCloset::API 의 `update_reservated` 에서 결제대기 주문서도 예약변경이 가능하도록 수정하고 배포한뒤에 staff 에서 새로 배포된 모듈을 사용하면 되겠습니다.

**Comment by aanoaa** [comment]
[OpenCloset-API-v0.1.1.tar.gz](https://cpan.theopencloset.net/STAFF@THEOPENCLOSET.NET/OpenCloset-API-v0.1.1.tar.gz) 을 설치하고 서비스를 재시작하도록 하겠습니다.
버전을 올려서 배포하기에는, https://github.com/opencloset/opencloset/pull/1322#issuecomment-338105671 위험부담이 좀 있습니다.

**Comment by aanoaa** [comment]
반영하였습니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
