### ISSUE TITLE
취업날개 이용자 중 합격명단

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1323]
#1228 동일한 이슈입니다. 서울시에서 자료 협조 공문을 보냈습니다.

@aanoaa 2017년 4월 19일 이후부터 2017년 10월 25일까지의 명단을 요청드립니다.

<취업날개 이용자 중 합격명단>

이름, 전화번호, 이메일, 사용일, 메세지 내용 (1228번 이슈에서 목적을 뺐습니다.)

**Comment by aanoaa** [comment]
이메일로 전달해드렸습니다.

**Comment by 10001if** [comment]
잘받았습니다. 생각보다 훨씬 적네요. 이대로 전달하도록 하겠습니다. 감사합니다.
