### ISSUE TITLE
취업날개 쿠폰을 통해 예약을 하는 대여자는 입사 면접만 목적으로 선택할 수 있도록 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1324]
취업날개의 이용목적은 면접으로만 가능하게 규정이 변경되었습니다.  기존에는 목적과 관계없이 나이와 거주지만 요건을 갖추면 되었는데요. 이제 면접이어야만 대여가 가능합니다. 일자리 포털에서는 그렇게 안내가 되고 있는데요. 

하지만 열린옷장 예약시에는 다른 목적으로 예약이 가능한 상황이라, 현장에서 목적 입력이 가능해서 예약하고 방문했는데 쿠폰을 사용할 수 없다는 원칙을 설명하는 과정에서 문제들이 발생하고 있습니다. 따라서 불필요한 문제들을 미연에 방지하고자 취업날개 쿠폰 사용의 경우에는 입사면접만 목적 선택이 가능하도록 고정 값으로 목적을 설정해 주시기를 요청드립니다.

**Comment by 10001if** [comment]
오늘도 다른 목적으로 대여하는 경우가 있었는데, 이 때문에 불필요한 언쟁이 발생하고 있다고 합니다. 내부 인원들의 요청이 많네요. 빠른 작업을 요청드립니다. @keedi

**Comment by keedi** [comment]
취업날개의 경우 이용 목적을 면접으로만 해야하는데, 사실 사용자가 다른 목적이라 하더라도 면접으로 선택해도 상관없다고 합니다. 이용 목적 입력값을 강제하는 것이 의미는 없어보이는데, 관련해 내부적으로 문제가 발생하고, 정책과도 상반된다고 하니 어찌됐든, 경고를 보여주고 다시 선택하게 하든, 강제로 면접으로 선택되게 하든 어떤 쪽이든 처리하도록 하겠습니다.

오늘의 경우 관련해서 대기실에서 고래고래 소리를 지르고 난리가 벌어지는 상황이 있었다고 합니다. 거참...;;; 별 일이 다 있군요;;;

**Comment by 10001if** [comment]
@keedi 추가적으로 목적 입력란 하단에 안내문구가 추가되면 더 정확한 정보 전달이 가능할 것 같습니다.
‘취업날개는 면접목적으로만 이용이 가능합니다’

**Comment by keedi** [comment]
진행합니다.

**Comment by keedi** [comment]
대여 목적을 선택하는 화면은 다음과 같습니다.

![screenshot-staff theopencloset net local 10301-2017-11-08-11-31-52](https://user-images.githubusercontent.com/138451/32528838-8f972fc4-c478-11e7-8187-9229a75c5b3f.png)

구현 방식은 두 가지가 있을 것 같습니다.

- 아예 선택할 때 면접만 고를 수 있게 함(안보이게 하든, 또는 비활성화 하든...)
- 선택은 할 수 있으나 제일 아래 예약 신청을 누를 때 면접이 아니면 오류를 발생시키게 함

**Comment by keedi** [comment]
전자의 방식으로 구현 중 입니다.

즉 서울시 취업날개 쿠폰 이용건인 경우 면접만 고를 수 있게 하며, 더불어 선택 입력 양식 아래에 관련해 안내 문구도 넣습니다.

**Comment by keedi** [comment]
안내 문구는 다음과 같습니다.

![screenshot-staff theopencloset net local 10301-2017-11-08-22-52-30](https://user-images.githubusercontent.com/138451/32552621-ddc609c2-c4d7-11e7-8e3a-3a8f2ff34e66.png)

**Comment by keedi** [comment]
입력을 제한한 화면은 다음과 같습니다.

![screenshot-staff theopencloset net local 10301-2017-11-08-22-53-15](https://user-images.githubusercontent.com/138451/32552643-ed182216-c4d7-11e7-8843-62b3eb89f3b0.png)

**Comment by 10001if** [comment]
배포 완료되면 확인해보도록 하겠습니다. 감사합니다!

**Comment by 10001if** [comment]
배포가 완료되면 라벨을 확인요망으로 변경해 주시는 건가요? 배포가 되면 제가 어떻게 확인할 수 있을까요?

**Comment by 10001if** [comment]
제가 취업날개 예약이 되지 않아서요. 내일 오전에 옷장지기가 실제로 테스트 해본 뒤에 라벨 제거하도록 하겠습니다.

**Comment by 10001if** [comment]
확인 해보니 아직 적용이 되지 않았네요. 확인 부탁드립니다~

**Comment by Bentleypark** [comment]
금일 출근해서 한번 더 테스트 해봤는데 어제 밤과 동일합니다.  테스트 환경은 아이폰/사파이 브라우저해서 진행했습니다.

**Comment by keedi** [comment]
한 번 더 확인 부탁드립니다. 착오가 있어 staff 만 배포하고 visit 쪽은 배포가 안됐었네요;; 방금 visit 새로 배포했습니다. 적용이 안된 것 같으면 강제 새로 고침 2~3번 부탁드립니다.

**Comment by 10001if** [comment]
확인했습니다. 잘 표시되네요. 감사드립니다.
