### ISSUE TITLE
목둘레의 평균값이 나타나지 않음

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1326]
어제부터 테스트로 키와 몸무게만 측정한 후 나타나는 평균값을 입력하여 대여를 진행하고 있습니다. 

그런데 목둘레의 경우 평균값이 계속해서 N/A 로 나타나고 있습니다. 입력값이 없다면 이 말이 맞을텐데, 목둘레를 측정한지 꽤 오랜 시간이 지났음에도 목둘레의 값이 나타나지 않는 걸 보았을 때 아예 입력값의 평균 내역이 나타나지 않는 것 같습니다. 

목둘레의 평균값이 나타나지 않기 때문에 목둘레는 측정을 하고 있는데요. 목둘레 평균값이 출력되지 않는 부분의 수정을 요청드립니다. 이렇게 수정이 완료되면 본격적으로 사이즈 입력없이 대여를 진행해 볼까 합니다. 확인 부탁드리겠습니다. @yongbin @keedi

**Comment by keedi** [comment]
평균값이 안나오는 주소(앞부분 제외)와 화면 캡쳐도 첨부 부탁드립니다.

**Comment by keedi** [comment]
목둘레 항목 추가는 2015년 11월, #577 항목에서 처리했던 내용입니다.

**Comment by 10001if** [comment]
네~ 캡쳐하겠습니다. 보시는 것처럼
![default](https://user-images.githubusercontent.com/4696328/32211242-f785c9ee-be54-11e7-9994-1dd0f2255eda.jpg) 처럼 목둘레만 나타나지 않는 상황입니다. @keedi

**Comment by keedi** [comment]
진행합니다.

**Comment by keedi** [comment]
`OpenCloset::Size::Guess::DB` 모듈의 버그였습니다.

다른 항목은 평균을 구하나 목 둘레 항목을 빠뜨리고 있었습니다.

**Comment by keedi** [comment]
해당 모듈을 수정했습니다.

```
commit 45f80e9363a6620251947f2378a13910a7cbf36f
Author: Keedi Kim <keedi.k@gmail.com>
Date:   Fri Nov 3 17:34:37 2017 +0900

    Fixed neck average calculation

diff --git a/lib/OpenCloset/Size/Guess/DB.pm b/lib/OpenCloset/Size/Guess/DB.pm
index ac10c14..3d26d1c 100644
--- a/lib/OpenCloset/Size/Guess/DB.pm
+++ b/lib/OpenCloset/Size/Guess/DB.pm
@@ -94,6 +94,7 @@ sub guess {
         hip      => [],
         knee     => [],
         leg      => [],
+        neck     => [],
         thigh    => [],
         topbelly => [],
         waist    => [],
@@ -107,6 +108,7 @@ sub guess {
         hip      => 0,
         knee     => 0,
         leg      => 0,
+        neck     => 0,
         thigh    => 0,
         topbelly => 0,
         waist    => 0,
@@ -122,6 +124,7 @@ sub guess {
             hip
             knee
             leg
+            neck
             thigh
             topbelly
             waist
@@ -146,6 +149,7 @@ sub guess {
         hip      => 0,
         knee     => 0,
         leg      => 0,
+        neck     => 0,
         thigh    => 0,
         topbelly => 0,
         waist    => 0,
@@ -157,6 +161,7 @@ sub guess {
     $ret{hip}      = Statistics::Basic::mean( $item{hip} )->query;
     $ret{knee}     = Statistics::Basic::mean( $item{knee} )->query;
     $ret{leg}      = Statistics::Basic::mean( $item{leg} )->query;
+    $ret{neck}     = Statistics::Basic::mean( $item{neck} )->query;
     $ret{thigh}    = Statistics::Basic::mean( $item{thigh} )->query;
     $ret{topbelly} = Statistics::Basic::mean( $item{topbelly} )->query;
     $ret{waist}    = Statistics::Basic::mean( $item{waist} )->query;
```

**Comment by keedi** [comment]
이 경우 staff의 릴리스 여부와는 별개로 해당 모듈의 버그이므로 모듈의 버그만 수정해서 재설치한 다음 실서비스를 재적재하기만 하면 바로 버그가 수정됩니다.

[OpenCloset::Size::Guess::DB 0.008](https://cpan.theopencloset.net/STAFF@THEOPENCLOSET.NET/OpenCloset-Size-Guess-DB-0.008.tar.gz) 버전을 릴리스했습니다.

더불어 실 서비스에서 바로 확인할 수 있게 적용했습니다.

**Comment by keedi** [comment]
수정된 화면은 다음과 같습니다.

![screenshot-staff theopencloset net-2017-11-03-17-46-43](https://user-images.githubusercontent.com/138451/32366182-5dd08eec-c0c0-11e7-92ae-70d430931bda.png)

**Comment by keedi** [comment]
to. @10001if 
이 이슈는 바로 실서버에 적용되었으므로 바로 확인하시면 됩니다. 더불어 제게 할당하실 때는 따로 저를 언급(@keedi)하실 필요가 없습니다. 또한 특별한 이유가 없다면 @yongbin 을 언급할 필요는 없습니다.

**Comment by keedi** [comment]
코드상으로 살펴본 결과 목둘레가 추가된 이후 계속 발생한 이슈입니다. 아마 최근에 발생한 이슈는 아니고 예전부터 존재했던 버그입니다. 다만, 그동안 별 필요가 없어 모르다가 최근에 인지하게 된 것 같습니다.

**Comment by 10001if** [comment]
@keedi 네 알겠습니다. 이제 따로 요청을 할 사항이 있을 때만 언급을 하도록 하겠습니다. :)

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
