### ISSUE TITLE
예약 화면에서 각 방문 예약 항목 별 부가 설명을 입력할 수 있게 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1327]
/booking/2017-11-01
페이지를 보면 11:00에는 제한 인원이 1명입니다. 이 시간에 단체 대여가 있을 예정이기 때문인데요. 기존에는 내부 메신저로 정보를 공유했는데요. 메세지로 공유가 잘 되지 않아 다른 옷장지기가 제한을 한 숫자를 다시 복귀시키는 일이 발생하기도 했습니다. 따라서 아래와 같이 인원을 수정한 경우 왜 수정했는지 이유를 바로 확인 할 수 있도록 설명란을 만들고자 합니다. 형식은 /tag 를 활용했습니다.

![2017-10-31 5 45 18](https://user-images.githubusercontent.com/4696328/32215336-0d7c9da8-be65-11e7-8b8f-c06956238692.png)

**Comment by keedi** [comment]
주소 앞부분을 제거했습니다. 공개 깃헙은 구글 검색도 잘되는 만큼 가능하면 전체 URL을 가공해서 넣는 것이 좋을 것 같습니다.

**Comment by keedi** [comment]
이 기능은 조금 애매하네요. 각각의 예약 항목에 대해 설명란을 추가할 수는 있지만, 인원 수정 이유를 남길 수 있는 기능을 넣는 것은 고려할 부분이 많습니다. 설명란을 추가하고 그런 용도로 사용하시는 것은 상관없을 것 같구요. 설명란이 추가되면 되는 것인지요?

**Comment by 10001if** [comment]
@keedi 네. 설명란을 추가하고 그런용도로만 사용한다면 충분합니다. 설명란만 추가되도록 요청드릴게요.

**Comment by keedi** [comment]
7일 화요일 지금까지의 변경 사항 중 장애를 유발할 수 있는 기능을 포함한 버전을 릴리스할 계획인지라, 본 이슈는 수요일 이후부터 진행합니다.

**Comment by keedi** [comment]
진행합니다.

**Comment by keedi** [comment]
스키마 쪽 수정 완료한 후 UI 적용합니다.

**Comment by keedi** [comment]
OpenCloset::Schema 0.055 버전을 기준으로 기존 데이터베이스에 적용하기 위해 다음 명령을 실행해야 합니다.

```
$ mysql -u opencloset -p opencloset < db/alter/134-booking-desc.sql 
```

또는 mysql에 접속해서 직접 다음 질의를 실행합니다.

```sql
ALTER TABLE `booking` ADD COLUMN `desc` TEXT DEFAULT NULL AFTER `slot`;
```

**Comment by keedi** [comment]
스키마 수정은 완료했으며, 서버측에 변경 스키마 적용 및 새로운 모듈 설치 및 staff/visit 재기동까지 완료했습니다. UI 작업만 진행한 뒤 서버에 배포 및 적용하면 됩니다.

**Comment by keedi** [comment]
구현한 화면은 다음과 같습니다.

![screenshot-2017-11-17 -](https://user-images.githubusercontent.com/138451/32938752-92efc66e-cbc0-11e7-8556-867ce4dbe15a.png)

수평으로 배치할 경우 화면이 작아지면 열람하거나 수정하기가 어려워지므로 수직으로 두 줄 배치했습니다.

**Comment by keedi** [comment]
작업 완료했으므로 이슈 닫습니다.

**Comment by 10001if** [comment]
수직으로 배치하는게 보기에 더 편하네요. 감사합니다!

**Comment by keedi** [comment]
@10001if 배포 완료되면 말씀드리겠습니다. 다른 작업 상황 봐가며 우선 배포할지 작업을 더 진행한 후 배포할지 결정하겠습니다. :)

**Comment by keedi** [comment]
배포 완료했습니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^

**Comment by 10001if** [comment]
![2017-11-20 12 16 25](https://user-images.githubusercontent.com/4696328/33000687-e05eef1e-cdec-11e7-8c77-ed4a818eebc0.png)
정렬이 왼쪽과 오른쪽이 다른 것 같습니다. 그림처럼 모두 좌측으로 정렬되도록 요청드립니다.

**Comment by 10001if** [comment]
@keedi 예약활성화가 되지 않은 예약일에는 예약현황이 뜨지 않습니다. 현재 12월 1일까지는 예약현황이 뜨나, 12월 2일은 502 에러나 나타나고 있습니다. 확인 부탁드릴게요~

**Comment by keedi** [comment]
알겠습니다. 지금은 제가 별도 이슈로 열겠습니다. 앞으로 닫히고 배포가 끝난 이슈는 별도의 이슈를 열어 문제가 있는 내용을 제목으로 해 기록해주세요.
