### ISSUE TITLE
신체치수 입력란에 평균값을 전부 한번에 넣을 수 있는 버튼의 생성

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1328]
키/몸무게 입력 후 일일이 사이즈를 옮겨 적지 않아도 되도록 평균값 입력 버튼 생성을 요청드립니다.
그러면 평균값이 모두 들어가도록 기능 하여야 합니다. 소수점 뒷자리는 반올림하여 입력이 되도록 요청드립니다.

![2017-11-01 4 45 57](https://user-images.githubusercontent.com/4696328/32265175-4b0066c6-bf25-11e7-90e0-635a67afc6e4.png)

**Comment by 10001if** [comment]
@keedi 현재 평균치수를 입력하여 운영하고 있습니다. 빠른 작업 요청드립니다~

**Comment by keedi** [comment]
진행합니다.

**Comment by keedi** [comment]
몸무게 항목 옆에 버튼을 넣기는 애매한 느낌이 있으므로 몸무게와 목 둘레 사이에 한 줄을 추가해서 버튼을 넣겠습니다.

![screenshot-staff theopencloset net local 10301-2017-11-06-17-47-31](https://user-images.githubusercontent.com/138451/32432353-a92e6cd6-c31a-11e7-81f3-3688e1a20e70.png)

**Comment by 10001if** [comment]
네. 알겠습니다.

**Comment by keedi** [comment]
평균값을 그대로 저장할 때의 문제가 있습니다.

현재 사용자의 신체 치수는 정수형이나 평균값은 필연적으로 부동 소수점 형입니다. 이 값을 그대로 저장하려할 경우 데이터베이스 형식 오류로 저장이 불가하며, 실제로도 저장 시도 전 인자 검사시 저장을 거부하도록 작성을 해두었습니다. 올림을 할지, 내림을 할지, 또는 반올림을 할지 아니면 다른 방법을 사용할지 결정해야 합니다.

**Comment by 10001if** [comment]
기존에도 반올림으로 입력을 하고 있었습니다. 반올림으로 요청드립니다.

**Comment by keedi** [comment]
관련해 피드백을 요청한 결과 반올림한 값을 자동 입력되도록 하면 된다고 합니다. 그대로 진행합니다.

**Comment by 10001if** [comment]
평균값과는 조금 다른 문제이지만 키/몸무게 입력 시에도 반올림값으로 진행하고 있었습니다.

**Comment by keedi** [comment]
완성된 화면은 다음과 같습니다. 불필요한 오해를 줄이기 위해 버튼 옆에 약간의 설명을 추가했습니다.

![screenshot-staff theopencloset net local 10301-2017-11-06-22-34-44](https://user-images.githubusercontent.com/138451/32443554-c1eee840-c342-11e7-9142-16ec28c7f5b3.png)

**Comment by 10001if** [comment]
배로 완료되면 확인하도록 하겠습니다. :)

**Comment by 10001if** [comment]
확인했습니다. 감사합니다. :)

**Comment by keedi** [comment]
#1346 에서 현재 기능의 필요성/유해성/당위성과 관련한 논의를 진행했습니다. 자세한 사항은 이후 더 기록해주신다고 합니다.

정리하면 본 기능은 평균이라는 값을 의미없게(?) 만드는 기능입니다. 따라서 지양해야할 기능으로 보이나, 모니터의 preparation에서 평균값을 볼 수 있는 방법이 없기 때문에 궁여지책으로 사용자 정보에 평균값을 덮어쓰는 기능을 요청했던 것입니다. 가장 적절한 해결책은 모니터 쪽에서 신체 치수랑 별개로(덮어쓰는게 아니라) 평균 치수를 보이도록 하는 것입니다.

아직은 해당 기능이 없기 때문에 바로 현재 버튼이 없어지면, 비록 평균값을 의미없게 만든다 하더라도 업무양이 과도하게 많아지는 관계로 조금 더 사용하기 싶다고 합니다. 이후 이 기능을 비활성화 시킬지, 폐쇄시킬지 등은 다시 논의하기로 했습니다.
