### ISSUE TITLE
제한한 인원보다 많은 수의 대여자가 예약한 경우 해당 예약자의 신청한 시간 확인

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1330]
제한 된 인원보다 많은 수의 대여자가 예약된 경우가 있었습니다.

이 경우가 동시 예약의 문제인지 확인해 보고자 합니다.

2017년 10월 30일부터 11월 2일까지 동시 예약자 수와 동시 예약이 된 시간을 전달받고자 합니다.

일시 | 동시 예약자 수 | 동시 예약시간 1 | 동시 예약시간 2
-- | -- | -- | --
2017-10-30 | 2 | 10:30 | 15:00
2017-11-2 | 0 | - | -

**Comment by keedi** [comment]
진행합니다.

**Comment by keedi** [comment]
2017년 10월 30일 부터 2017년 11월 2일 사이의 방문 예약 건 중 허용한 인원(slot)보다 많은 인원이 신청을 한 방문 예약 시간을 확인하는 질의는 다음과 같습니다.

```sql
SELECT 
    b.id, b.date, b.gender, b.slot, COUNT(*)
FROM
    `order` AS o
        LEFT JOIN
    `booking` AS b ON o.booking_id = b.id
WHERE
    '2017-10-30' <= b.date
        AND b.date <= '2017-11-02'
GROUP BY o.booking_id
HAVING COUNT(*) > b.slot
```

**Comment by keedi** [comment]
결과는 조금 충격(?)적입니다. 요청한 10월 30일 ~ 11월 2일 사이의 초과 인원이 수용된 경우는 단 세 타임 입니다.

- 2017-10-31 16:30:00 남성 5/4
- 2017-10-31 20:00:00 여성 1/0
- 2017-11-01 16:30:00 남성 6/5

굉장히 많을 줄 알았는데 생각보다 별로 없습니다. 물론 초과한 후 허용 가능한 인원을 수정한 경우는 추출하지 못했음을 주의해야 합니다. 예를 들어 11월 1일 17시 남성 허용 인원이 4명이었는데, 6명이 예약 된 후 이후 옷장지기가 허용 인원을 6명 또는 그 이상으로 조정하는 경우는 추려낼 수 없습니다. 허용인원이 4명이었는데 6명이 된 후 허용인원을 수정하지 않거나, 수정해도 6명 미만(즉, 5명, 4명, 3명, ...등)으로 수정한 경우만 확인이 가능합니다.

**Comment by keedi** [comment]
앞의 질의를 하부 질의(subquery)로 이용해 초과 신청 분의 주문서 정보를 뽑는 질의는 다음과 같습니다.

```sql
SELECT 
    oo.id AS order_id,
    oo.booking_id,
    io.booking_date,
    io.booking_gender,
    io.booking_slot,
    io.booked,
    oo.create_date
FROM
    `order` AS oo,
    (SELECT 
        b.id AS booking_id,
            b.date AS booking_date,
            b.gender AS booking_gender,
            b.slot AS booking_slot,
            COUNT(*) AS booked
    FROM
        `order` AS o
    LEFT JOIN `booking` AS b ON o.booking_id = b.id
    WHERE
        o.parent_id IS NULL
            AND (o.status_id <> 12 AND o.status_id <> 14)
            AND (o.online IS NULL OR o.online = 0)
            AND '2017-10-30' <= b.date
            AND b.date <= '2017-11-02'
    GROUP BY o.booking_id
    HAVING COUNT(*) > b.slot) AS io
WHERE
    oo.booking_id = io.booking_id
ORDER BY oo.booking_id , oo.create_date
```

실행 결과는 다음과 같습니다.

```csv
# order_id, booking_id, booking_date, booking_gender, booking_slot, booked, create_date
'78256', '43853', '2017-10-31 16:30:00', 'male', '4', '5', '2017-10-25 23:24:53'
'78664', '43853', '2017-10-31 16:30:00', 'male', '4', '5', '2017-10-28 15:47:58'
'78720', '43853', '2017-10-31 16:30:00', 'male', '4', '5', '2017-10-29 00:23:24'
'78937', '43853', '2017-10-31 16:30:00', 'male', '4', '5', '2017-10-30 16:44:31'
'79094', '43853', '2017-10-31 16:30:00', 'male', '4', '5', '2017-10-31 12:18:59'

'79082', '43885', '2017-10-31 20:00:00', 'female', '0', '1', '2017-10-31 11:06:55'

'77842', '43903', '2017-11-01 16:30:00', 'male', '5', '6', '2017-10-23 18:56:22'
'78191', '43903', '2017-11-01 16:30:00', 'male', '5', '6', '2017-10-25 17:46:00'
'78977', '43903', '2017-11-01 16:30:00', 'male', '5', '6', '2017-10-30 19:40:36'
'79050', '43903', '2017-11-01 16:30:00', 'male', '5', '6', '2017-10-31 01:12:47'
'79308', '43903', '2017-11-01 16:30:00', 'male', '5', '6', '2017-11-01 14:43:55'
'79309', '43903', '2017-11-01 16:30:00', 'male', '5', '6', '2017-11-01 14:44:20'
```

정리하면 다음과 같습니다.

### 2017-10-31 16:30:00 - 남성 - 5/4

- 78256 2017-10-25 23:24:53
- 78664 2017-10-28 15:47:58
- 78720 2017-10-29 00:23:24
- 78937 2017-10-30 16:44:31
- 79094 2017-10-31 12:18:59

### 2017-10-31 20:00:00 - 여성 - 1/0

- 79082 2017-10-31 11:06:55

### 2017-11-01 16:30:00 - 남성 - 6/5

- 77842 2017-10-23 18:56:22
- 78191 2017-10-25 17:46:00
- 78977 2017-10-30 19:40:36
- 79050 2017-10-31 01:12:47
- 79308 2017-11-01 14:43:55
- 79309 2017-11-01 14:44:20

**Comment by keedi** [comment]
@10001if 확인 부탁드립니다.

자료가 이상한 부분이 있으면 알려주세요.

**Comment by 10001if** [comment]
자료는 이상하지 않습니다. 저희가 인원을 조정한 경우가 있을 수도 있는데 내부적으로 확인 후 다시 문의드리도록 하겠습니다. 감사합니다. :)

**Comment by 10001if** [comment]
@keedi 11월 24일 10:00에 남성인원 수가 8명입니다. 이 건이 동시예약으로 인해 예약이 된 것인지 확인 부탁드립니다. 요즘 대여자가 많은 시기라 초과인원에 대해 부담을 느끼는 부분이 더 큰 듯합니다. 확인 부탁드리겠습니다. 

동일 건이라 이슈를 다시 열려 하는데, 이런 경우에도 이슈를 새로 만들어야 한다면 이야기 해주세요. 그럼 다시 열도록 하겠습니다.

**Comment by keedi** [comment]
말씀드렸던 것 처럼 `저장소 없이 처리` 라벨이 있는 경우 기존 이슈 열어서 남겨주시면 됩니다. :)

**Comment by 10001if** [comment]
네! 정확히 이해했습니다~! 알겠습니다~!

**Comment by keedi** [comment]
아직 방문하지 않은 경우이므로 `order.status`를 체크하지 않아야 합니다. 날짜와 `status` 체크 부분만 조금 수정해서 실행합니다.

```sql
SELECT 
    oo.id AS order_id,
    oo.booking_id,
    io.booking_date,
    io.booking_gender,
    io.booking_slot,
    io.booked,
    oo.create_date
FROM
    `order` AS oo,
    (SELECT 
        b.id AS booking_id,
            b.date AS booking_date,
            b.gender AS booking_gender,
            b.slot AS booking_slot,
            COUNT(*) AS booked
    FROM
        `order` AS o
    LEFT JOIN `booking` AS b ON o.booking_id = b.id
    WHERE
        o.parent_id IS NULL
            -- AND (o.status_id <> 12 AND o.status_id <> 14)
            AND (o.online IS NULL OR o.online = 0)
            AND '2017-11-24' <= DATE(b.date) AND DATE(b.date) <= '2017-11-24'
            AND b.gender = 'male'
    GROUP BY o.booking_id
    HAVING COUNT(*) > b.slot) AS io
WHERE
    oo.booking_id = io.booking_id
ORDER BY oo.booking_id , oo.create_date
```

### 2017-11-24 10:00:00 - 남성 - 8/6

- 81451 2017-11-14 13:48:44
- 82440 2017-11-20 17:59:08
- 82512 2017-11-20 23:51:00
- 82676 2017-11-21 20:16:46
- 82701 2017-11-21 23:11:54
- 82890 2017-11-23 14:38:30
- 82891 2017-11-23 14:40:22
- 82892 2017-11-23 14:41:10

결과를 살펴보면 확인할 수 있는데 11월 24일 14시 38분에서 14시 41분 3분 사이에 신청자 3명이 몰린 것을 확인할 수 있습니다.
