### ISSUE TITLE
셋트 대여가 아닌데 셋트 대여로 표시됨

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1332]
/orders/79643 의 주문서의 경우  J08T 과 K1BW 의류가 셋트대여라고 표시가 되지만, 이 둘은 셋트가 아닙니다. 셋트인 경우에만 셋트대여라는 표시가 떠야 하는데 그렇지 못한 상태입니다. 수정을 요청드립니다.

![2017-11-03 8 42 09](https://user-images.githubusercontent.com/4696328/32372355-cadca9b4-c0d7-11e7-9b5b-8b4d372a5e78.png)

**Comment by keedi** [comment]
진행합니다.

**Comment by keedi** [comment]
#1277 에서 교체한 새로운 주문서 페이지에서 셋트 여부를 체크하는 코드가 적절하지 않아보입니다. 이 코드는 단순히 위 아래를 같이 빌렸는지 여부를 확인하는 것으로 보입니다. 위 아래를 같이 빌렸는지 여부를 확인하는 것이라면 적절하지만, 셋트 여부를 체크하는 용도라면, 적절하지 않습니다.

```perl
    my $details = $order->order_details;

    my ( $top, $bottom, $suit );
    while ( my $detail = $details->next ) {
        my $clothes = $detail->clothes;
        next unless $clothes;

        my $category = $clothes->category;
        if ( $category eq $JACKET ) {
            $top = $clothes;
        }
        elsif ( "$PANTS $SKIRT" =~ m/\b$category\b/ ) {
            $bottom = $clothes;
        }

        last if $top and $bottom;
    }
    $details->reset;

    if ( $top and $bottom ) {
        $suit->{top}    = $top;
        $suit->{bottom} = $bottom;
    }
```

**Comment by aanoaa** [comment]
`OpenCloset::Schema::Result::Clothes` 의 `top`, `bottom` 을 활용할 수 있습니다.

    my $top    = $pants->top;
    my $bottom = $jacket->bottom;

**Comment by keedi** [comment]
수정 이후 79643 주문서의 경우 세트 의류가 아니므로 세트 의류 표시가 사라졌음을 확인할 수 있습니다.

![2017-11-14 14-24-06](https://user-images.githubusercontent.com/138451/32764280-08cbaa86-c948-11e7-9df2-defee6732d05.png)

**Comment by keedi** [comment]
진짜 세트 의류에 대해서도 확인을 해야하므로 `J0PQ` 의류에 대해 관련 주문서를 확인합니다.

![2017-11-14 14-25-05](https://user-images.githubusercontent.com/138451/32764310-2a2ded9c-c948-11e7-9a6d-11c091a4d386.png)

확인용 주문서 번호는 77683 입니다.

![2017-11-14 14-25-47](https://user-images.githubusercontent.com/138451/32764328-40ecfc8a-c948-11e7-97f9-e49bfcc70892.png)

세트 의류일 경우 세트로 표시함을 확인할 수 있습니다.

**Comment by keedi** [comment]
수정 완료했으므로 이슈 닫습니다.

**Comment by keedi** [comment]
외국어 국문 표시 맞춤법에 맞게 셋트를 세트로 수정합니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
