### ISSUE TITLE
사용자 정보의 신체 치수의 평균 값이 동적으로 변하지 않음

### ISSUE THREAD

**Issue by keedi** [opencloset/opencloset#1334]
지난 haml -> ep 변환 작업 이후 사용자 정보의 신체 치수 평균 값이 동적으로 변하지 않습니다. 최초 페이지 적재시에는 평균값이 잘 나오나 이후 키 또는 몸무게를 변경할 경우 새롭게 계산한 평균값으로 갱신되지 않는 증상이 발견되었습니다.

**Comment by keedi** [comment]
527a0457 커밋을 확인하면 커피스크립트에서 동적으로 제어하는 신체 치수 div 요소에서 각각의 신체 치수를 의미하는 클래스가 빠진 것 같습니다.

**Comment by keedi** [comment]
최초 페이지 적재 이후 값을 바꿨을 때 평균 값을 반영하지 못하는 현상을 확인할 수 있습니다.

![screenshot-staff theopencloset net local 10301-2017-11-06-17-05-52](https://user-images.githubusercontent.com/138451/32431009-0b6e4d5e-c315-11e7-8562-a40dc7f69c1d.png)

![screenshot-staff theopencloset net local 10301-2017-11-06-17-04-55](https://user-images.githubusercontent.com/138451/32431031-2482b0aa-c315-11e7-9cad-14bb6391696b.png)

**Comment by aanoaa** [comment]
이 똥은 제가 치우겠습니다.
눈으로 보고 옮긴거라서 여기말고도 비슷한 실수가 발생했을 수 있습니다.

**Comment by keedi** [comment]
@aanoaa 어짜피 이쪽 페이지 하고 있는거라서 제가 처리하겠습니다. ㅎㅎ
