### ISSUE TITLE
의류 정보에서 대여일 명칭이 잘못 표시되고 대여율이 보이지 않음

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1344]
![2017-11-14 4 30 51](https://user-images.githubusercontent.com/4696328/32768016-52a27c00-c959-11e7-84c2-fe718d5d71ad.png)
원래는 위 그림과 같이 표시가 되어야 합니다.

하지만 현재는 
![2017-11-14 4 32 36](https://user-images.githubusercontent.com/4696328/32768071-8aa0ebc8-c959-11e7-945a-dfce1473d8db.png)
'대여일' 대신 '대여율' 로 표시되어 있고 대여율이 표시되지 않고 있습니다.

수정 요청드립니다.

**Comment by 10001if** [comment]
#714 이슈와 연관됩니다.

**Comment by keedi** [comment]
언제부터 발생했는지 혹시 기억나시는지요?

**Comment by 10001if** [comment]
명확하지는 않지만 일주일이 넘지는 않았습니다.

**Comment by 10001if** [comment]
일주일 정도 된 것 같네요 ^^;

**Comment by aanoaa** [comment]
확실하진 않지만 haml -> ep 작업의 영향인 것 같습니다.

[v1.12.1] - Wed, 08 Nov 2017 13:54:38 +0900
[v1.12.0] - Thu, 02 Nov 2017 16:37:53 +0900

11/02 에는 태깅만하고 배포는 하지 않았고 11/08 일부터 발생하지 않았나 싶습니다.

**Comment by keedi** [comment]
진행합니다~ :)

**Comment by keedi** [comment]
Haml을 ep로 변경하는 과정에서 대여일과 대여율 항목이 빠지거나 잘못 들어가서 발생한 문제입니다. ( #1322 / f87b570 )

수정 완료했으며 이슈 닫습니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
