### ISSUE TITLE
의류 정보에서 상하의 셋트를 입력하기 위한 바코드 입력 양식이 보이지 않음

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1345]
https://github.com/opencloset/opencloset/pull/667 이슈의 기능 중에 바코드 입력창이 보이지 않습니다.

![5c104b94-bdfa-11e5-919f-9066275e43d4](https://user-images.githubusercontent.com/4696328/32773127-754f94f6-c96b-11e7-92f8-f5389e88eecc.png)
처럼 의류의 쌍을 지정할 수 있는 바코드 창이 존재해야 하는데

![2017-11-14 6 38 49](https://user-images.githubusercontent.com/4696328/32773159-94577df0-c96b-11e7-8517-e87f78b1da18.png)
바코드 입력 창이 없어 쌍을 지정할 수가 없습니다.

오류 수정 요청드립니다.

**Comment by keedi** [comment]
마찬가지로 발생 시점이 언제쯤인지 확인 가능할까요?

**Comment by 10001if** [comment]
정확하지는 않지만 발견한 건 어제입니다. 일주일 기간 정도로 변경이 있었던 것으로 추정됩니다.

**Comment by keedi** [comment]
진행합니다.

**Comment by keedi** [comment]
Haml을 ep로 변경하는 과정에서 `.input-group` 태그 요소가 빠져서 발생한 문제입니다. ( #1322 / f87b570a )

```html
- if (my ($first) = $clothes_code =~ /^(J|P|K)/) {
  %h2 상하의 셋트
  - if ($suit) {
    - my $set = $first eq 'J' ? $suit->code_bottom : $suit->code_top;
    - my $set_code = trim_clothes_code($set);
    %h4
      %a{:href => "#{ url_for('/clothes/' . $set_code) }"}= $set_code
    %div.not-suit
      %a.btn.btn-danger.btn-xs.btn-not-suit{:href => "#{ url_for('/api/suit/' . $set_code) }"} 셋트아님
  - } else {
    %form#form-suit.form-inline{:method => 'POST', :action => "#{ url_for('/api/suit') }"}
      %input{:type => 'hidden', :name => "#{ $first eq 'J' ? 'code_top' : 'code_bottom'}", :value => $clothes_code}
      .input-group
        %input.form-control{:type => 'text', :placeholder => 'code', :name => "#{ $first eq 'J' ? 'code_bottom' : 'code_top'}"}
        %span.input-group-btn
          %button.btn.btn-sm.btn-default{:type => 'submit'} 등록
  - }
  %hr
- }
```

**Comment by keedi** [comment]
빠져있던 `div.input-group`과 그 하부의 `input` 요소를 추가해서 수정 완료했습니다.

이슈 닫습니다.
