### ISSUE TITLE
사용자 정보에서 신체 치수 입력 시 평균의 모집단 수가 표시되도록 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1346]
평균값을 실제 사이즈 대신 이용한지 2주 가량 시간이 지났습니다. 그 결과 특별히 발생되는 문제는 없고 대기기간과 치수 측정 시간이 줄어들면서 총 대여시간이 5~10분 가량 줄어드는 효과가 나타났습니다.

그런데 이렇게 평균값을 활용해 측정을 하면 이 평균값의 전체 수가 얼마인지 확인이 필요할 때가 있습니다. 평균값이 좀 이상하다던지 혹은 특이한 사이즈의 경우 데이터 수가 별로 없어 측정값을 추가하면 좋다던지 하는 경우가 있는데요. 이런 경우를 위해 다음과 같이 그 평균값의 기준이 되는 수를 확인하고자 합니다. 그래서 다음과 같이 요청드립니다.

![2017-11-15 10 16 05](https://user-images.githubusercontent.com/4696328/32814890-600a7820-c9f4-11e7-953d-c08611f69d33.png)

신체치수 예측 화면세어 보이는 수량 확인 방법과 유사합니다.

![2017-11-15 10 14 56](https://user-images.githubusercontent.com/4696328/32814905-799eeef6-c9f4-11e7-8603-fab1cb0b81d6.png)

**Comment by keedi** [comment]
이 기능이 의미가 있는지 의아합니다.

현재 #1328 항목을 통해 요청하셨던 평균값을 자동 입력하는 기능을 추가했는데, 이렇게 자동으로 저장하는 신체 치수 값이 평균의 모수가 될텐데, 과연 모수 값이 의미가 있는지요? 예를 들어 지금 상기에 기록하신 값 중 49가 실제로 20개가 평균값으로 저장한 것일 수도 있고, 만약 시간이 많이 지나 200건이 된다 하더라도 이중 180건은 자동 입력으로 한 것이라면, 실제 모수는 20건도 안되는 것일 뿐입니다.

그럼에도 불구하고 모수 값을 확인하고 싶으신 것인지요?

**Comment by 10001if** [comment]
말씀해주신 부분을 생각하지 못했었네요.. 저는 실제 모수값을 확인하고 싶은 것이지 전체 모수를 확인하고 싶은 것은 아니었습니다. 지적해 주신 것처럼 평균값이 쌓인 모수는 불필요한 정보입니다. 제가 원했던 것은 모수가 적은 사이즈인 경우 모수의 값을 늘리고자 했던 것이었습니다. 이대로 간다면 현재 사이즈 데이터 그대로 화석처럼 굳은 상태가 될텐데, 모수가 30이상인 경우는 일반적인 경우로 받아들일 수 있겠지만 10개 이하인 경우, 특히 건수가 5개 이하인 경우에는 평균 값을 신뢰하기가 힘들 것 같은데. 좋은 방안이 떠오르지 않네요. 아이디어가 떠오르면 다시 남기도록 하겠습니다.. 중요한 포인트 확인해 주셔서 감사합니다. :)

**Comment by keedi** [comment]
네, 일단 평균 값을 사용자 정보에 쓰는 버튼이 생긴 이상 실제로 입력한 자료와 평균값을 자동으로 입력한 자료를 구분할 방법은 없습니다. 기능을 추가하는 것은 문제가 없으나 잘못된 정보를 눈으로 보고 오해할 가능성이 높아보여(이미 평균은 그렇게 변하고 있는 중입니다.) 언급했습니다. 사실 앞으로 평균을 정말 평균이라고 생각한다면 곤란한 시점이 올 것이라고 생각은 듭니다만...

본 이슈는 마일스톤에서 제거합니다.

관련해 이슈가 있다면 우선순위에 따라 적절한 마일스톤으로 등록해주세요.

**Comment by keedi** [comment]
더불어 확인 후 해당 기능을 구현할 필요가 없다면 `invalid` 라벨을 단 후 이슈를 닫아주세요. 필요한 이슈라면 적절한 마일스톤에 넣어주시고 이슈를 닫을 필요없습니다.

**Comment by 10001if** [comment]
이슈에 대해 의견을 남겨주신 뒤 더 생각을 해보았습니다. 매우 중요한 문제라고 생각되기 때문입니다. 

제가 생각한 것은

1. 많은 사람(30명 이상)이 방문한 키/몸무게의 경우 앞으로 사이즈 측정을 계속 해 나가도 평균값에는 큰 차이가 없을 것임
2. 보통으로 방문한(11명~29명) 키/몸무게의 경우 앞으로 사이즈 측정을 계속하여 1번과 같은 수준으로 만들면 평균값에는 큰 차이가 없을 것임
3. 적은 수로 방문한(10명 이하) 키/몸무게의 경우 사이즈 측정을 하여 평균값이 아닌 개별의 값으로 의류를 대여한다. 그리고 이 치수가 누적되어 1번과 같은 수치가 되는 경우 사이즈 측정을 하지 않는다.

입니다.

그런데 문제는 평균값을 계속 사용하면 이 같이 1,2,3을 구분할 수 없습니다. 하지만 1,2,3을 구분하기 위해 모든 사람의 치수를 계속 측정하는 것은 효율적이지 않아 보입니다. 저희는 운영을 하는 것이지 연구 결과를 발표하는 것은 아니기 때문에 어떤 행동에는 반드시 효율성이 전제되어야 합니다.

그렇다면 이를 위해 다음과 같은 방법을 사용하면 어떨까 합니다.

1. 평균으로 입력하는 행위를 부분적으로 멈춤
2. 누적 수 자료를 표시되도록 수정함
3. 방문자 30이상의 키/몸무게의 경우에는 그대로 평균값을 입력함
4. 그렇지 않은 경우에는 측정을 계속 함 (정확한 방문자 수에 대한 조정은 논의 후 결정해야 할 것으로 보임)

그렇게 되면 충분한 모수를 확보한 키/몸무게의 경우에는 그대로 평균치를 활용하고 그렇지 못한 키/몸무게의 경우에는 충분한 모수를 확보할 수 있도록 정보를 누적하는 것입니다. 그리고 일정 시점이 되면 그 키/몸무게도 평균치를 활용하도록 합니다.

**Comment by 10001if** [comment]
따라서 위의 기능이 구현되도록 요청드리고자 합니다. 의견이 있으시면 편하게 남겨주세요~

**Comment by keedi** [comment]
기록해주신 부분 확인 후 의견 남기겠습니다.

**Comment by keedi** [comment]
#1328 이슈에서 버튼을 추가해달라고 하셨을때 벌써 문제를 제기했었던 내용이지만, 다시 말씀드리면, 1이든, 2이든, 3이든 그냥 다 문제가 있습니다. 이것을 평균값이라고 인지를 하는 상황은 무언가 부자연스럽습니다.

1이라고 생각한다면, 이미 충분히 들어가 있으므로 현재 평균값을 넣는다고 평균이 바뀌지 않으므로 넣는다를 반대로 말한다면 1의 경우는 충분히 들어가 있으므로 평균값을 넣을 필요도 없습니다.

2라고 생각한다면 충분하지 않으므로 실제 치수를 입력할 것이므로 해당 버튼을 누를 필요가 없습니다.

3이라고 생각하다면 (왜 나뉘었는지 모르겠네요. 2번과 동일한데...) 역시 충분하지 않으므로 실제 치수를 입력할 것이므로 해당 버튼을 누를 필요가 없습니다.

정리하면, 2와 3의 경우는 치수를 잴 것이므로 평균값 입력 기능이 필요없고, 1의 경우는 이미 평균값이 있으므로 평균값을 굳이 입력할 이유가 없습니다. 그냥 평균값을 보고 판단하면 되지 불필요하게 평균값을 넣는 이유를 잘 모르겠네요.

혹시 이 상황에서 1번의 상황에서 굳이 평균값을 넣는 이유가 있나요?

**Comment by keedi** [comment]
아 물론, 1, 2, 3을 인지하기 위해 누적 수를 표시하려고 하는 것과 별개의 이야기를 하고 있습니다. 1, 2, 3을 인지하기 위해 누적수를 보여주는 것은 필요할 수 있겠네요. 지금 여쭤보는 것은 어쩌면 벌써 구현이 되버린 이슈지만, #1328 에 해당하는 부분을 다시 되여쭙는 것입니다. 물론 현재 이슈와 관련이 있기도 하구요.

**Comment by 10001if** [comment]
남겨주신 부분에 대해 답변을 드리겠습니다.

우선 1,2,3 번이라고 구분해서 말씀드렸지만 이야기 해주신 것처럼 이 경우는 단순하게 2가지 경우로 나뉩니다.

1. 평균값을 사용할 경우 (1번)
2. 실제 측정 값을 사용할 경우 (2번, 3번)

#1328 에서 평균값을 넣을 수 있는 기능을 요청드린 이유는 1가지 입니다.
prepation 화면에서 대여자의 신체치수를 보고 의류를 찾기 위해서는 신체치수의 값이 들어가 있어야 하기 때문입니다.
기존에는 평균값을 눈으로 보고 손으로 옮겨 입력하고 있었던 것에 시간을 단축시키기 위해 다음과 같은 기능을 요청드렸던 것입니다. 

그런데 이야기 해주신 부분을 생각해보니 지금 사이즈 입력 행위에 문제가 있다고 보여지네요. 그 대여자의 신체사이즈 대신 평균값이 대여자의 사이즈로 둔갑하고 있기 때문입니다. 현재 시점에서는 모니터 화면에 보여지는 방법이 평균값을 신체 사이즈에 넣는 방법 뿐이라 이렇게 사용하고 있었는데. 남겨주신 것처럼 평균값을 그냥 활용하면 될 듯 합니다.

정리를 하자면

1. 평균값을 사용할 경우와 아닌 경우를 인지하기 위해 누적 수를 확인하는 것은 필요함
2. 평균값을 사용하지 않을 경우 사이즈를 직접 측정하기 때문에 #1328 이슈를 사용할 필요 없음
3. 평균값을 사용할 경우라도 평균값이 그 대여자의 사이즈가 되는 것은 아니므로 이 경우에는 평균값을 신체 사이즈에 넣는 것이 아니라 그 평균값을 보여주기만 하면 됨

**Comment by keedi** [comment]
그렇다면 이 문제는 해결 방식이 잘못된 것 같습니다.

#1328 버튼은 있으면 안되는 버튼 같네요;;;

정리를 해보겠습니다.

1.
모니터의 preparatioon 화면에 해당 대여자의 신체치수와 별개로 평균 값을 보여주면 될 것 같습니다. 이것이 정말로 원하시는 것 아닐까요? 혹시 그러하시다면 모니터 쪽 이슈에 현재 별도의 이슈를 추가해주시면 될 것 같습니다.

2.
더불어 그럼에도 불구하고 누적 수는 필요하신 것인가요? (신체 치수를 잴지 말지를 결정하기 위해) 그렇다면 모니터 쪽에 별도 이슈를 추가해주시는 것과는 별개로 본 이슈는 진행하겠습니다. 그러면 되는지요?

3.
#1328 에서 구현한 버튼은 비활성화를 시키든 보이지 않게 하든 해야할 것 같은데 어찌 생각하시는지요?

항목 별 확인 부탁드립니다.

**Comment by 10001if** [comment]
네. 문제 해결방식이 잘못 된 것 같네요..

>1. 모니터의 preparatioon 화면에 해당 대여자의 신체치수와 별개로 평균 값을 보여주면 될 것 같습니다. 이것이 정말로 원하시는 것 아닐까요? 혹시 그러하시다면 모니터 쪽 이슈에 현재 별도의 이슈를 추가해주시면 될 것 같습니다.

-> 네. 알겠습니다. 별로도 요청드리도록 하겠습니다.

>2. 더불어 그럼에도 불구하고 누적 수는 필요하신 것인가요? (신체 치수를 잴지 말지를 결정하기 위해) 그렇다면 모니터 쪽에 별도 이슈를 추가해주시는 것과는 별개로 본 이슈는 진행하겠습니다. 그러면 되는지요?

-> 네. 본 이슈는 진행 부탁드립니다.

>3. #1328 에서 구현한 버튼은 비활성화를 시키든 보이지 않게 하든 해야할 것 같은데 어찌 생각하시는지요? 아니면 그럼에도 불구하고 이 버튼은 필요한지요?

-> 이 기능을 사용하면 안되는 기능이지만(마약같은 기능이네요..), 바로 기능을 비활성화 시키면 (원하지는 않았지만) 일이 많아지는 효과가 나타나게 될 듯 합니다. 모니터에서 평균값을 보여주는 기능이 마련되고 나면 다시 정확하게 답변 드리도록 하겠습니다.

**Comment by keedi** [comment]
네, 평균값 덮어 쓰기와는 별도로 신체 치수를 잴지 말지를 판단할 수 있는 근거로 사용되므로, 결과적으로 구현할 기능으로 인해 누적 수가 클 경우 신체 치수를 재지 않을 수 있으므로 업무양이 줄어드는 효과가 있습니다.

진행하겠습니다.

**Comment by keedi** [comment]
추가한 화면은 다음과 같습니다.

![2017-11-20 19-55-41](https://user-images.githubusercontent.com/138451/33015196-367e04ee-ce2d-11e7-82e6-37621615f10c.png)

**Comment by keedi** [comment]
조금 더 가독성이 높도록 각각의 항목이 고정 너비를 가지도록 하고 이에 맞추어 수직 정렬을 했습니다.

![2017-11-21 01-00-50](https://user-images.githubusercontent.com/138451/33027838-90b69af0-ce57-11e7-898a-e9b171df7957.png)

**Comment by keedi** [comment]
작업 완료했으므로 이슈 닫습니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
