### ISSUE TITLE
주문서에서 배상비 항목이 나타나지 않음

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1347]
https://github.com/opencloset/opencloset/issues/315 이슈에서 보면

![1ad9a9d6-95e7-11e4-8ade-ec6c5f8a351d](https://user-images.githubusercontent.com/4696328/32827231-ca85578a-ca2e-11e7-97c0-baa2af080ad3.png)
배상비를 입력하는 란이 존재했는데 
현재는
![2017-11-15 5 58 25](https://user-images.githubusercontent.com/4696328/32827247-d99280fe-ca2e-11e7-9dbe-a160d9878fe8.png)
배상비 기능이 빠져있는 상태입니다.

배상비 입력이 가능하지 못해서 `미납`으로 변경을 할 수 없습니다. 이렇게 되면 분실 손상이 발생한 경우에도 미납자로 구분되지 않아 배상비 지급요청을 하는 것이 어려운 상황입니다. 배상비를 입력할 수 있도록 수정 요청드립니다.

**Comment by 10001if** [comment]
그리고 이와 더불어 실제로는 배상비를 입력하는 시점이 반납을 진행하는 경우도 있지만, 반납을 완료한 후에도 의류의 손상을 확인하는 경우가 많다고 하네요. 반납확정 후에도 배상비를 입력할 수 있는 방법이 있을지, 좋은 아이디어가 떠오르지 않아 문의드립니다.

**Comment by aanoaa** [comment]
https://github.com/opencloset/opencloset/issues/1277#issuecomment-314673796

주문서화면을 변경하면서 빼먹은 기능입니다.

**Comment by keedi** [comment]
@10001if 일단 기존 기능과 관련해 배상비 항목을 기존과 동일하게 사용할 수 있도록 하는 것 까지를 이 이슈의 범위로 잡겠습니다. 반납 확정 후에 배상비를 입력할 수 있는 것과 관련해서는 별개의 이슈로 생성해주세요. 관련해서는 별개의 이슈에서 논의하는 것이 좋을 듯합니다.

본 이슈는 @aanoaa 님께서 처리하시는 것이 효율적일 듯합니다.

**Comment by aanoaa** [comment]
`OpenCloset::API::Order::rental2returned` 에 배상비 관련된 처리는 되어있습니다.
사용자로부터 배상비와 관련된 값을 넘겨받아서 값을 넘겨주어야 합니다.

**Comment by 10001if** [comment]
@keedi 네. 이야기 주신 것처럼 기존 기능을 구현하는 것으로 이해하겠습니다. 그럼 @aanoaa 작업 요청드리겠습니다.

**Comment by aanoaa** [comment]
![screenshot-2017-11-16 - 3](https://user-images.githubusercontent.com/170528/32871858-becf15be-cac6-11e7-9f34-31bbd37aa89c.png)

배상비와 배상비 에누리를 입력할 수 있도록 하고,
배상비 결제방법을 선택한뒤에 전체반납 혹은 부분반납을 하면,
상세 항목에 배상비와 배상비 에누리 금액이 표시됩니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
