### ISSUE TITLE
주문서에 정장 반납 안내 출력 버튼이 보이지 않음

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1349]
https://github.com/opencloset/opencloset/issues/958 이슈에서 정장 반납 안내지를 프린터로 출력하는 버튼을 만들어 주셨습니다. 
![94845b26-a6a9-11e6-8b96-ecd756b60e98](https://user-images.githubusercontent.com/4696328/32828529-b48d4ccc-ca32-11e7-9fea-abe8814d7727.png)
다음과 같은 위치에 있었는데요.
현재 주문서에서는 프린터 출력 버튼이 없습니다.

일반적으로는 포장완료 상태에서 출력을 하나 결제대기, 주문확정 상태에서도 출력을 해야 하는 경우가 있습니다. 그런데 버튼이 보이지 않아 종전에는 임시방편으로 order 로 주문서를 변경하여 뽑고 있었는데 이젠 404 오류가 나서 그마저도 할 수 없게 되었습니다. orders 에서도 버튼을 누를 수 있도록 수정 요청드립니다~

**Comment by aanoaa** [comment]
`정장 반납 안내 출력` 버튼은 포장완료 이거나 결제대기 상태인 주문서에서만 보입니다.

**Comment by 10001if** [comment]
@aanoaa 네. 맞습니다. 결제대기 상태에서 보이지 않는 부분만 수정하면 됩니다.

**Comment by 10001if** [comment]
@aanoaa 다시 확인해보니 order 에서는 주문 확정 후에도 대여중 상태에서도 버튼이 있었다고 하네요. 결제하는 옷장지기가 orders에서도 대여중 상태에서 버튼이 있길 요청했습니다. 주문확정 후에도 안내지를 출력하는 경우가 있다고 하네요. 아마 실수로 봅지 못하고 누른 경우도 포함되지 않나 싶습니다..

**Comment by keedi** [comment]
@10001if 버그인지 기존과는 다르게 동작하기를 원하시는 것인지 확인 부탁드립니다.

한동안 새로 바뀐 주문서 관련 이슈는 @aanoaa 님을 담당자로 처리하겠습니다.

**Comment by keedi** [comment]
버그라면 `bug` 라벨을, 기존과 다르게 동작하기 원하는 것이라면 `enhancement` 라벨을, 착오로 인한 이슈 등록이라면 `invalid`를 붙여주세요~

**Comment by 10001if** [comment]
기존의 order 주문서에서는 대여중 일때도 정장 반납 안내 출력 버튼이 존재했습니다. orders 에서도 기존과 동일하게 대여중인 주문서에서도 반납 안내 출력 버튼이 존재하도록 요청드립니다.

**Comment by 10001if** [comment]
착오로 인한 이슈 등록이라는 개념을 잘 이해하지 못했습니다. 설명 부탁드릴게요~

**Comment by aanoaa** [comment]
환불버튼 옆에 표시되도록 하겠습니다.

![screenshot-2017-11-16 - 1](https://user-images.githubusercontent.com/170528/32870218-32d3d336-cabe-11e7-9561-20e9d2ae7fed.png)

**Comment by keedi** [comment]
> 착오로 인한 이슈 등록이라는 개념을 잘 이해하지 못했습니다. 설명 부탁드릴게요~

버그나 기능 개선이 아닌데, 착각을 해서 입력한 경우를 의미합니다. 예전에 잘 동작했는데, 지금 안되는 경우면 `bug` 구요. 예전 동작과 별개로 예전과 상관없이 추가하거나 변경하는(기능개선하는) 경우는 `enhancement` 입니다.

**Comment by 10001if** [comment]
@aanoaa 네, 환불버튼 옆에 표시되도록 해주시면 됩니다.

**Comment by 10001if** [comment]
@keedi 
>착오로 인한 이슈 등록이라면 `invalid`를 붙여주세요~

라고 작성해 주셨는데 버그와 기능개선은 이해했습니다. 착오로 인한 이슈 등록의 예시를 한번 들어주실 수 있을까요? 아직도 이해를 못했습니다..

**Comment by 10001if** [comment]
그리고 그 전에는 특별히 라벨을 사용하지는 않았는데, 앞으로는 라벨을 적극적으로 사용하도록 하겠습니다. 혹시 놓친 부분이 있다면 그때 그때 알려주세요~

**Comment by keedi** [comment]
버그가 아닌데 버그라고 인지하고 이슈를 등록했거나, 기능 추가 또는 개선이 필요하다고 등록했으나 실제로 필요하지 않는다거나 하는 경우입니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
