### ISSUE TITLE
예약 화면에서 각 방문 예약 항목 별 부가 설명을 좌측으로 정렬함

### ISSUE THREAD

**Issue by keedi** [opencloset/opencloset#1354]
#1327 

@10001if wrote:

![2017-11-20 12 16 25](https://user-images.githubusercontent.com/4696328/33000687-e05eef1e-cdec-11e7-8c77-ed4a818eebc0.png)
> 정렬이 왼쪽과 오른쪽이 다른 것 같습니다. 그림처럼 모두 좌측으로 정렬되도록 요청드립니다.

**Comment by keedi** [comment]
@10001if 새로고침을 해도 그러신지요? 관련해 이미 왼쪽 정렬을 지정해놓았는데요. 브라우저 캐시로 인한 착오 같아 보입니다만... 두세 번 이상 새로 고침 후 확인 부탁드립니다.

![booking](https://user-images.githubusercontent.com/138451/33001844-c044b90a-cdf3-11e7-95e8-0007de7d331a.png)

**Comment by 10001if** [comment]
제가 크롬으로 보고 있었는데, 파이어폭스에서는 정상적으로 좌측 정렬되어 나오네요. 확인 완료했습니다. :)

**Comment by keedi** [comment]
이런 경우 `invalid`로 라벨 설정해주시고 닫아주시면 됩니다. :-)

**Comment by 10001if** [comment]
네~! 알겠습니다~ :)
