### ISSUE TITLE
예약 활성화가 되지 않은 예약일에는 예약 현황이 뜨지 않고 502 오류가 발생

### ISSUE THREAD

**Issue by keedi** [opencloset/opencloset#1355]
#1327 

> 10001if commented 27 minutes ago
> 
> @keedi 예약활성화가 되지 않은 예약일에는 예약현황이 뜨지 않습니다. 현재 12월 1일까지는 예약현황이 뜨나, 12월 2일은 502 에러나 나타나고 있습니다. 확인 부탁드릴게요~

**Comment by keedi** [comment]
진행합니다.

**Comment by keedi** [comment]
수정 완료했습니다.

금일 오후 중 배포 예정입니다.

이슈 닫습니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
