### ISSUE TITLE
예약이 동시에 3번 중복으로 발생함

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1358]
user/79992 의 경우 예약이 동시에 3번 반복해서 되었는데
프로그램 상의 버그 인지 확인요청을 드리기 위해 남겨 놓습니다.

![318ce91114c0c19d578f8cd81755158a](https://user-images.githubusercontent.com/4696328/33104100-ba7c89e0-cf69-11e7-8a03-0b29982960e4.JPG)
11월 24일 14:30분에 3번 예약이 되어 있는 모습입니다.

![2017-11-22 9 40 44](https://user-images.githubusercontent.com/4696328/33104094-b744c6b6-cf69-11e7-8f4a-48ed666a868a.png)
사용자 정보 내용입니다.

예약을 진행한 시간도 동일합니다.

**Comment by keedi** [comment]
확인 중 입니다. 버그인지 아니면 중복 신청인지는 확인해보겠습니다. 일단 관련해 생성된 세 개의 주문서는 82565, 82566, 82567 이군요. 말씀하신대로 세 주문서의 생성 시각은 동일해보입니다.

**Comment by keedi** [comment]
로그를 확인했습니다.

사용자 컴퓨터 환경의 문제였는지, 아니면 의도적으로 여러번 시도를 한 것인지는 모르겠지만, 어찌됐든 사용자가 세 번 연속 예약 신청을 시도한 것은 사실입니다.  다만, 사용자 페이지 하부의 주문서 목록에서 세 주문서의 생성 시각이 동일하게 나온 것은 동시에 하루에 여러건의 주문서를 넣는 경우를 고려하지 않아서 보인 것 같으며, 실제로는 세 주문서의 생성 시각은 다음 시도 시각 목록과 동일합니다.

시도 시각은 다음과 같습니다.

- 2017-11-21 11:00:52
- 2017-11-21 11:00:58
- 2017-11-21 11:01:19

로그는 다음과 같습니다.

```
[Tue Nov 21 11:00:52 2017] [debug] POST "/visit"
[Tue Nov 21 11:00:52 2017] [debug] Routing to controller "OpenCloset::Web::Controller::Booking" and action "visit"
[Tue Nov 21 11:00:52 2017] [debug] type: visit
[Tue Nov 21 11:00:52 2017] [debug] name: 이xxxx
[Tue Nov 21 11:00:52 2017] [debug] phone: 01074xxxxxx
[Tue Nov 21 11:00:52 2017] [debug] service: 
[Tue Nov 21 11:00:52 2017] [debug] privacy: 
...
[Tue Nov 21 11:00:58 2017] [debug] POST "/visit"
[Tue Nov 21 11:00:58 2017] [debug] Routing to controller "OpenCloset::Web::Controller::Booking" and action "visit"
[Tue Nov 21 11:00:58 2017] [debug] type: visit
[Tue Nov 21 11:00:58 2017] [debug] name: 이xxxx
[Tue Nov 21 11:00:58 2017] [debug] phone: 01074xxxxxx
[Tue Nov 21 11:00:58 2017] [debug] service: 
[Tue Nov 21 11:00:58 2017] [debug] privacy: 
...
...
[Tue Nov 21 11:01:19 2017] [debug] POST "/visit"
[Tue Nov 21 11:01:19 2017] [debug] Routing to controller "OpenCloset::Web::Controller::Booking" and action "visit"
[Tue Nov 21 11:01:19 2017] [debug] type: visit
[Tue Nov 21 11:01:19 2017] [debug] name: 이xxxx
[Tue Nov 21 11:01:19 2017] [debug] phone: 01074xxxxxx
[Tue Nov 21 11:01:19 2017] [debug] service: 
[Tue Nov 21 11:01:19 2017] [debug] privacy: 
...
```


관련 주문서를 확인할 수 있는 질의는 다음과 같습니다.

```sql
SELECT
    o.id AS order_id
    , o.user_id
    , u.name
    , o.booking_id
    , b.date
    , o.status_id
    , s.name
    , o.create_date
    , o.update_date
FROM `order` AS o
LEFT JOIN `booking` AS b ON b.id = o.booking_id
LEFT JOIN `user`    AS u ON u.id = o.user_id
LEFT JOIN `status`  AS s ON s.id = o.status_id
WHERE
    (
        user_id=79992
    )
ORDER BY create_date
;
```

**Comment by keedi** [comment]
정리하자면 사용자 페이지 하부에서 3개의 주문서가 생성 시각이 같아 중복으로 보이는 것은 주문서 생성 시각을 표시하는 부분의 오류(버그)로 발생하는 현상이지만, 현재 언급주신 `user/79992`의 경우는 정말로 3번 주문서를 생성한 건입니다.

**Comment by keedi** [comment]
이슈 닫습니다.

**Comment by keedi** [comment]
오해한 부분이 있는 것 같습니다. 시도(요청) 시각과 주문서 생성 시각은 보통 동일하나, 이번 경우 시도 시각과 생성 시각이 다릅니다. 결과적으로 위에서 언급한 것처럼 시도 시각은 11:00:52, 11:00:58, 11:01:19이지만 생성 시각은 11:01:22로 셋 다 동일합니다.

로그 상으로 조금 더 살펴보니, 생성 시각과 시도 시각 사이에 다음과 같은 로그가 있음을 확인했습니다.

...
[Tue Nov 21 11:01:22 2017] [error] Worker 19523 has no heartbeat, restarting
[Tue Nov 21 11:01:22 2017] [debug] Stopping worker 19523 gracefully
...
[Tue Nov 21 11:01:22 2017] [debug] Worker 19520 stopped
[Tue Nov 21 11:01:22 2017] [debug] Worker 7369 started
[Tue Nov 21 11:01:22 2017] [debug] Worker 19523 stopped
[Tue Nov 21 11:01:22 2017] [debug] Worker 7370 started
...

해당 시각 사이에 워커가 종료되고 시작한 흔적이 보입니다. 관련해 사용자는 요청을 시도했지만 응답이 없다고 판단하고 재차 시도했을 가능성이 있으며, 이후 워커가 기동되면서 요청을 한번에 일괄처리한 것으로 보입니다.

상기 시각 이외에도 동일한 로그가 지속적으로 꽤 많이보이며, 산발적으로 분포해있지만 보통 정각 시점에 몰려있는 것으로 보아 시스템 오류를 대비한 1시간 단위 데이터베이스 백업을 시도하고 있는 시간과 맞물려 발생하는 것으로 보입니다. 당시 데이터베이스 설계시 왠만한 양이라할지라도 백업에 큰 부하가 없은 수준으로 스키마를 구성했으나, 이후 주문서 상태 로그라던가, 이미지 저장이라던가 등의 기능을 데이터베이스에 추가하면서 데이터베이스 백업 및 복원이 감내할 수 없는 정도로 소요 시간이 커졌습니다. 데이터베이스 백업의 특성상 IO도 많이 점유할 뿐만 아니라 백업하는 동안 제대로 질의를 수행하지 못할 가능성이 높으므로 현재 현상과 연관이 있을 확률이 매우 높습니다. 관련해서는 더 확인이 필요합니다.

**Comment by keedi** [comment]
일단은 1시간 단위 데이터베이스 백업을 0, 3, 6, 21시 4번만 진행하도록 변경했습니다.

이것은 **임시 방편(!!)**일 뿐 결코 해결책이 될 수 없습니다. 더불어 현재 안티패턴이고 자시고 데이터베이스에 불필요한 내용이 저장되는 상황을 해결해야 합니다. 물론 현재 열린옷장의 자료가 결코 적은 양은 아니지만, 그렇다고 데이터베이스의 백업으로 인한 부하가 시스템 전반적으로 영향을 주는 것은 현재 규모를 기준으로 상식적이지 않습니다. 별도의 이슈를 열어 해결해야 합니다.

**Comment by 10001if** [comment]
우선 내부에 전달했습니다.  

>물론 현재 열린옷장의 자료가 결코 적은 양은 아니지만, 그렇다고 데이터베이스의 백업으로 인한 부하가 시스템 전반적으로 영향을 주는 것은 현재 규모를 기준으로 상식적이지 않습니다.

내부에서는 접속이 잘 되지 않는 상황이 계속해서 발생하면서 오류가 나는 상황에 더 민감해진 분위기 입니다. 문제가 발생하지 않도록 문제 해결이 가능하도록 요청드립니다. :)
