### ISSUE TITLE
신체 치수가 입력되어 있는 경우 평균의 모집단 수 표시가 잘못됨

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1359]
180/75의 경우 아래처럼 50에 가까운 대여자가 방문한 것으로 나타납니다.
![2017-11-22 10 33 07](https://user-images.githubusercontent.com/4696328/33105782-4b9ee622-cf72-11e7-9987-bb1f0235c86b.png)

하지만 이미 신체치수가 입력되어 있는 경우, 해당 사용자의 몸무게 변동이 있어 그 수치를 수정하여 재 입력하면 아래와 같이 누적 수가 제대로 표시되지 않는 현상이 있습니다. 수정 요청드립니다.
![2017-11-22 10 43 18](https://user-images.githubusercontent.com/4696328/33105803-71eb84a2-cf72-11e7-8c37-556adb8a65fc.png)

**Comment by keedi** [comment]
음... 신체 치수가 입력되어 있건, 안되어 있건 또는 몸무게를 수정하든 아니든 잘 보이는데 혹시 수치를 잘못 입력하셨던 것은 아니신지요. 해당 사용자 번호를 알려주시면 확인해보겠습니다.

**Comment by 10001if** [comment]
아까 확인해볼 때는 숫자가 0, 1 과 같이 표현되었는데. 다시 확인해보니 지금은 정상적으로 작동합니다. 제가 뭔가 확인을 할 때 실수가 있었나 보네요. 사용자 번호는 2번이었습니다. 제 것으로 했거든요. 문제가 없으므로 이슈 닫도록 하겠습니다.
