### ISSUE TITLE
미납 주문서가 아닌데 주문서 상세 페이지에서 미납으로 표시됨

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1360]
![2017-11-22 5 46 05](https://user-images.githubusercontent.com/4696328/33117921-905e0f28-cfad-11e7-8bfb-4cb99862f973.png)

orders/81057 의 경우 위 그림처럼 미납인 상태입니다.

그럼에도 불구하고 미납버튼을 클릭하여 미납 주문서로 이동하면 미납 목록에 나타나지 않습니다.
![2017-11-22 5 46 20](https://user-images.githubusercontent.com/4696328/33117970-b2995318-cfad-11e7-9bc4-d7b5a5392571.png)

이름으로 검색하여도 나타나지 않고 전체 미납 목록에도 실제로 존재하지 않습니다.

확인 요청드립니다.

**Comment by keedi** [comment]
확인 후 진행하겠습니다.

**Comment by 10001if** [comment]
/orders/82949 도 동일한 현상이 나타나고 있습니다.

**Comment by 10001if** [comment]
/orders/85769 에서도 동일한 현상이 나타나고 있습니다.

**Comment by 10001if** [comment]
/orders/86196 주문서도 동일한 현상입니다.

**Comment by keedi** [comment]
진행합니다.

**Comment by keedi** [comment]
어떤 현상인지 정확하게 이해를 못한 관계로 우선 현상 파악을 먼저 합니다.

**Comment by keedi** [comment]
현재 `GET /orders/:id` 요청은 `OpenCloset::Web::Controller::Order` 모듈의 `detail()` 메소드에서 처리합니다. 사용하는 템플릿은 `/templates/order/detail.html.ep` 파일 입니다. 이슈 생성시 기록한 화면 갈무리 상의 **미납** 라벨을 표시하는 부분의 코드는 다음과 같습니다.

템플릿의 코드입니다.

```html
      <tr>
        <th>이름</th>
        <td>
          <a href="<%= url_for('/user/' . $user->id) %>">
            <i class="fa fa-<%= $user_info->gender %>" aria-hidden="true"></i>
            <%= $user->name %>
            <small title="나이"><%= age($user_info->birth) %></small>
          </a>
          % if ($unpaid) {
            <a href="<%= url_for('/order')->query(q => $user->name, booking_ymd => 'all', status => 'unpaid') %>">
              <span class="label label-warning">
                <i class="fa fa-exclamation-triangle" aria-hidden="true"></i>
                미납
              </span>
            </a>
          % }
          % if ($nonpaid) {
            <a href="<%= url_for('/order')->query(q => $user->name, booking_ymd => 'all', status => 'nonpaid') %>">
              <span class="label label-danger">
                <i class="fa fa-exclamation-triangle" aria-hidden="true"></i>
                불납
              </span>
            </a>
          % }
        </td>
      </tr>
```

컨트롤러 코드는 다음과 같습니다.

```perl
    my ( $unpaid, $nonpaid );
    my $orders = $user->orders;
    while ( my $row = $orders->next ) {
        my $late_fee_pay_with     = $row->late_fee_pay_with     || '';
        my $compensation_pay_with = $row->compensation_pay_with || '';

        if ( $late_fee_pay_with =~ /미납/ || $compensation_pay_with =~ /미납/ ) {
            $unpaid = 1;
        }

        $nonpaid = is_nonpaid($row) unless $nonpaid;
        last if $unpaid and $nonpaid;
    }
```

**Comment by keedi** [comment]
미납 주문서의 목록을 구하는 요청은 `GET /order` 입니다. 이 요청은 `OpenCloset::Web::Controller::Order` 모듈의 `index()` 메소드에서 처리합니다. 사용하는 템플릿은 `/templates/order/index.html.ep` 파일입니다.

템플릿의 코드입니다.

```html
  <li>
    <a href="<%= url_for->query(booking_ymd => 'all', status => 'unpaid') %>">미납</a>
  </li>
  <li>|</li>
  <li>
    <a href="<%= url_for->query(booking_ymd => 'all', status => 'nonpaid') %>">불납</a>
  </li>
```
컨트롤러의 코드입니다.

```perl
            when ('unpaid') {
                my $cond_ref = unpaid_cond();
                my $attr_ref = unpaid_attr();

                %cond = %$cond_ref;
                %attr = ( %$attr_ref, order_by => 'return_date', );
            }
            when ('nonpaid') {
                %cond = (
                    'order_details.stage' => 4,
                    'order_details.name'  => '불납',
                );
                %attr = ( join => [qw/order_details/], order_by => 'return_date' );
            }
```

컨트롤러 코드를 살펴보면 미납 조건의 질의를 보내기 위해 `unpaid_cond()`와 `unpaid_attr()`을 사용하고 있습니다. 현재 모듈에 존재하지 않는 함수인데 어디서 불러왔나 확인해보니 모듈 상단에 다음과 같은 코드가 있습니다.

```perl
use OpenCloset::Common::Unpaid
    qw/unpaid_cond unpaid_attr is_nonpaid unpaid2fullpaid/;
```

즉 `OpenCloset::Common::Unpaid` 모듈의 함수를 호출하는 것으로 보입니다.

해당 함수의 내용은 다음과 같습니다.

```perl
=head2 unpaid_cond

    SELECT
        o.id                    AS o_id,
        o.user_id               AS o_user_id,
        o.status_id             AS o_status_id,
        o.late_fee_pay_with     AS o_late_fee_pay_with,
        o.compensation_pay_with AS o_compensation_pay_with,
        SUM( od.final_price )   AS sum_final_price
    FROM `order` AS o
    LEFT JOIN `order_detail` AS od ON o.id = od.order_id
    WHERE (
        o.`status_id` = 9
        AND (
            -- 연체료나 배상비 중 최소 하나는 미납이어야 함
            o.`late_fee_pay_with` = '미납'
            OR o.`compensation_pay_with` = '미납'
        )
        AND od.stage > 0
    )
    GROUP BY o.id
    HAVING sum_final_price > 0
    ;

=cut

sub unpaid_cond {
    return {
        -and => [
            'me.status_id'        => $RETURNED,
            'order_details.stage' => { '>' => 0 },
            -or                   => [
                'me.late_fee_pay_with'     => '미납',
                'me.compensation_pay_with' => '미납',
            ],
        ],
    };
}

=head2 unpaid_attr

=cut

sub unpaid_attr {
    return {
        join      => [qw/ order_details /],
        group_by  => [qw/ me.id /],
        having    => { 'sum_final_price' => { '>' => 0 } },
        '+select' => [
            {
                sum => 'order_details.final_price',
                -as => 'sum_final_price'
            },
        ],
    };
}

=head2 is_nonpaid( $order )

=cut

sub is_nonpaid {
    my $order = shift;
    return unless $order;
    return $order->order_details( { stage => 4 }, { rows => 1 } )->single;
}
```

**Comment by keedi** [comment]
일단 당장 보았을때 주문서 내부에서 미납 조건을 확인하는 코드와 주문서 목록에서 미납 조건을 확인하는 코드가 다릅니다. 이로 인해서 문제가 발생하는 것으로 보입니다. 문제는 양 쪽 중 어느 쪽이 정확한 미납 조건식인지 현 시점으로는 알 수 없습니다.

현재 코드 상으로는 `order_detail.stage` 값을 확인하는 부분 때문에 주문서의 미납 라벨과 미납 주문서 목록이 일치하지 않는 것으로 보입니다.

예를 들어 82949 주문서의 경우 `order_detail.stage` 값은 모두 `0`이기 때문에 미납 주문서가 아닙니다. 주문서를 봤을때 되려 82949 주문서는 미납이면 안될 것 같은데 실제로 미납 레이블이 있습니다. 해당 82949 주문서는 기본 3박 4일 기준 25,000원이 발생해야 하나 1일 연장을 했기 때문에 4박 5일 금액인 30,000원이 발생했습니다. 그동안 주문서가 어떻게 바뀌었는지는 모르겠지만, 애초에 최초 대여 시점에 1일 연장을 했다면 아마도 처음에 30,000원을 받았을 것이고, 그렇다면 처음부터 미납일 수 없습니다.

@10001if 
82949 주문서 부터 어떤 상황인지 먼저 파악을 해야합니다. 확인 후 자세한 설명 부탁드립니다.

**Comment by 10001if** [comment]
@keedi 안그래도 그동안 올려놓은 주문서들을 확인했는데요.

말씀하신 것처럼 미납금액이 없는 주문서들이 있었습니다. 제 추정으로는 미납금액이 없으므로 주문서 목록에 나타나지 않는 것이라 생각했는데요. 그렇다면 왜 미납금액이 없는데 미납으로 표시되어 있을까? 를 고민해 보았습니다. 옷장지기들의 반납과정의 행동 패턴을 살펴보니 의심이 되는 부분을 발견하였습니다.

1. 택배 반납이 온 경우, 택배 발송일을 확인. (예> 12월 4일)
2. 택배 발송일을 택배발송/반납일 항목에 입력. (예> 12월 4일)
3. 12월 4일이 반납예정일이라 제 기간에 반납했기 때문에 프로그램상으로는 미납이 아님.
4. 하지만 실제로는 1일 연체임.(택배 반납은 하루 전 반납이므로 3일에 반납했어야 함)
5. 연체비가 있는 상태에서는 반납처리가 되지 않는 다는 사실을 인지하고 있으므로 옷장지기가 먼저 `미납`으로 변경.
6. 이렇게 되면 82949 주문서는 미납금액 없이 `미납` 표시가 된채로 존재하게 됨.

위의 모든 주문서가 연체비가 없었던 것은 아닌데. 연체비가 없이 `미납`표시로 남아 있는 주문서는 상기 이유 때문인 것으로 추정하고 있습니다.

택배발송일에 +1 하여 입력해야 한다는 사실을 정확히 인지하지 못한 옷장지기가 있었습니다. 직관적으로는 4일 반납이면 3일에 반납해야 한다는 사실은 이해하고 있었으나 프로그램에 반납일을 입력할 때 하루를 더해야 한다는 사실은 모르고 있어서 발생한 문제가 아닌가 싶습니다.

하지만, 이번에 미납 주문서를 살펴보니 배상비 결제방법에서 반납 이후에도 자유롭게 `미납`을 입력할 수 있었습니다. 그리고 택배발송/반납일이 고정되지 않고 현재일로 매일 변경되는 것을 확인할 수 있었습니다. 원래부터 그랬던 것인지 명확하지 않은데. 상식적으로는 반납 시 배상비 결제방법을 선택하면 그대로 고정되고 택배발송/반납일도 입력한 날 그대로가 남아 있는 것이 바람직해 보입니다.

관련해서 전화로 한번 더 설명 드리겠습니다.

**Comment by keedi** [comment]
통화 및 주문서 정황 확인 결과 앞서 언급한 82949 주문서의 경우 문제가 없습니다. 정리하면 다음과 같습니다.

- 82949 주문서는 현재 보이는 상태대로라면 미납이 아니다. 따라서 미납 주문서 목록에서 보이지 않는 것은 정상이다.
- 82949 주문서의 **택배 발송/반납일** 항목은 2018-01-05가 되었어야 했는데 담당자가 실수로 2018-01-04로 입력했다. 그렇기 때문에 미납이 아니다.
- 하지만 실수와는 별개로 담당자는 본 주문서가 1일 연체되었음을 알았기 때문에 **배상비 결제 방법** 항목을 **미납**으로 선택했다. 그로 인해 주문서에서는 **미납** 레이블이 붙어서 보이는 것이다.

일단 82949 주문서는 본 이슈와 관련이 없음을 확인했습니다. 해당 주문서를 어찌 처리할지는 별도로 논의하기로 하고 나머지 주문서를 살펴보겠습니다.

**Comment by keedi** [comment]
이와는 별개로 현재 반납일이 최초 시스템을 만들 때와는 다르게 쓰이고 있음을 확인했습니다. 이것은 여러가지 의미에서 문제가 있다고 판단됩니다. 82949 주문서의 경우 정말로 물류를 반납 받은 날은 2017년 12월 6일 입니다. 하지만 반납일은 2017년 12월 4일로 기록되어 있습니다.

더불어 택배 발송/반납일이 주문서를 열람할 때마다 오늘 날짜로 보이는 버그도 있습니다.

관련해 이슈는 2017년 3월쯤 진행되었던 것으로 보입니다.

- 반납일과 반납처리일을 따로 저장 #1213
- 주문서 내 대여자 반납일 항목 추가 #1167

반납일 관련해서도 어찌할지도 고민해야합니다...;;;

**Comment by keedi** [comment]
반납일이 문제가 되는 이유는 지금까지 반납일은 물류를 손에 쥐고 바코드를 찍은 날이라고 가정하고 프로세스나 로직을 짜왔던 부분이 있기 때문입니다. 이 값이 바뀜으로 인해 문제가 없는지와 더불어 앞으로 바코드를 찍은 그 시점 날이 없어지는 현상으로 인해 생길 문제는 없는지 등 이미 고려가 된 것인지 아니라면 고려를 해야하는 것인지도 확인해야 합니다.

**Comment by keedi** [comment]
어려운 문제입니다. 고민해야할 부분은 어짜피 지금 결정하기 어려우니 남겨두고, 나머지 두 주문서의 내용도 확인합니다. 85769와 86196 두 주문서 내역을 확인하겠습니다.

**Comment by keedi** [comment]
우선 86196 주문서의 경우 정상적으로 보입니다. 그러니까 2일 연장을 했고, 2일 연장비가 5,000원에 추가 2,000원이고, 배송료 3,000원을 더해 총 10,000원이 발생했고 대여 시점에 이미 완납을 한 것으로 보입니다. 그러면 해당 주문서는 미납이 아니라 완납인 것 같고 미납 주문서가 아닌 것으로 보입니다. 맞는지 확인 부탁드립니다. 만약 맞다면 이 주문서는 **미납 주문서 목록**에서 안보이는 것이 맞을 것 같고, 주문서에서 **미납**으로 라벨이 표시된 것이 문제일것 같은데 이것 역시 맞는지 확인 부탁드립니다.

만약 아니라면 어떤 상황인지 조금 자세히 설명 부탁드립니다.

**Comment by keedi** [comment]
더불어 85769 주문서도 설명 부탁드립니다. 현재는 미납 금액을 완납해서인지 주문서 상에는 **미납** 라벨이 보이지 않고 있긴합니다. 대여일은 17년 12월 17일, 반납 예정일은 12월 20일이었고, 반납일은 12월 23일로 되어있습니다.  그렇다면 연체일은 21, 22, 23일해서 3일일 것 같은데 12월 21일~28일 사이에 해당 주문서가 미납 주문서 목록에서 보이지 않았다는 말씀이신지요? 더불어 해당 주문서의 설명에 있는 미납금 입금 완료 시점은 언제인지 확인 부탁드립니다.

관련해 정보를 알려주시면 개발 장비에서 데이터베이스를 되돌려 확인할 예정입니다.

**Comment by 10001if** [comment]
>우선 86196 주문서의 경우 정상적으로 보입니다. 그러니까 2일 연장을 했고, 2일 연장비가 5,000원에 추가 2,000원이고, 배송료 3,000원을 더해 총 10,000원이 발생했고 대여 시점에 이미 완납을 한 것으로 보입니다. 그러면 해당 주문서는 미납이 아니라 완납인 것 같고 미납 주문서가 아닌 것으로 보입니다. 맞는지 확인 부탁드립니다. 만약 맞다면 이 주문서는 미납 주문서 목록에서 안보이는 것이 맞을 것 같고, 주문서에서 미납으로 라벨이 표시된 것이 문제일것 같은데 이것 역시 맞는지 확인 부탁드립니다.

적어주신 내용이 맞습니다. 미납으로 라벨이 표시된 것만 문제입니다.

**Comment by 10001if** [comment]
>더불어 85769 주문서도 설명 부탁드립니다. 현재는 미납 금액을 완납해서인지 주문서 상에는 미납 라벨이 보이지 않고 있긴합니다. 대여일은 17년 12월 17일, 반납 예정일은 12월 20일이었고, 반납일은 12월 23일로 되어있습니다. 그렇다면 연체일은 21, 22, 23일해서 3일일 것 같은데 12월 21일~28일 사이에 해당 주문서가 미납 주문서 목록에서 보이지 않았다는 말씀이신지요? 더불어 해당 주문서의 설명에 있는 미납금 입금 완료 시점은 언제인지 확인 부탁드립니다.

이 주문서도 다시 살펴보니. 이 주문서는 해당 이슈와 무관한 문제로 보입니다. 토요근무자가 올린 내용을 제가 깃헙에 기록한 건데. 당시 기록을 보니 "미납 버튼을 눌러도 계좌전송페이지가 안떠서 수동으로 보냈습니다." 라고 적혀 있는데.

이 상황은 이렇게 가상계좌 미납 전송에 오류가 발생하여 나타난 상황이라고 추정됩니다. 해당 이슈에 적을 내용이 아닌데 제가 적은 것으로 보여지네요..

![img_2587](https://user-images.githubusercontent.com/4696328/35611344-1b2785cc-06a8-11e8-9139-1cf54701e9a5.jpg)

**Comment by keedi** [comment]
알겠습니다. 85769 항목은 본 이슈에서 고려하지 않겠습니다. 필요하다면 별도의 이슈를 열어서 남겨주세요. 더불어 해당 사진 촬영 시점 정보도 같이 첨부해주시면 추후 디버깅하는데 도움이 될 것 같습니다. 우선 본 이슈에 해당 시각 정보를 남겨주시고, 별도로 생성하게 된다면 해당 이슈에도 같이 기록 부탁드립니다.

**Comment by keedi** [comment]
> 적어주신 내용이 맞습니다. 미납으로 라벨이 표시된 것만 문제입니다.

미납으로 라벨 표시된 것만 문제라면, 여기까지 이슈의 내용을 추적해서 정리한 결과를 토대로 살펴보면, 미납 주문서가 미납 목록에 나타나지 않은 것이 문제가 아니라 주문서에서 미납이 아닌데 미납으로 표시된 것이 문제이군요.

제목 변경토록 하겠습니다.

**Comment by 10001if** [comment]
@keedi 네. 알겠습니다. 그리고 주문서 85769는 @pingpongworks 님이 새 이슈로 등록해 주실 예정입니다.

**Comment by pingpongworks** [comment]
@keedi opencloset/opencloset #1407 에 새 이슈로 등록했습니다.

**Comment by keedi** [comment]
체인지 로그에 해결되었다고 기록되었으므로 마찬가지로 마일스톤 기록하고 닫습니다.
