### ISSUE TITLE
서울시 쿠폰으로 연장을 한 대여자의 주문서가 미납표시로 나타나는 경우

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1361]
orders/81502 대여자의 경우입니다. 이런 사례가 3번 정도 발생하였다고 하는데요. 주문서를 확인한 건은 이 건 밖에 없습니다. #1360 과 유사하지만 다른 부분이 있어 다른 이슈로 남깁니다.

본 주문서의 경우

1. 반납예정일이 지나 연장(연체)료가 발생하였음
2. 옷장지기는 반납을 하기위해 연장료 결제 방법을 `미납`으로 변경
3. 반납을 누르기 전 서울시 쿠폰 대여자라는 사실을 인지함
4. 서울시 쿠폰 규정을 활용하여 1회 연장버튼을 누름
5. 이로 연장(연체)료는 발생하지 않게 됨
6. 옷장지기는 반납을 누름
7. 미납이 아님에도 미납 표시가 뜸
8. 미납버튼을 눌러도 미납주문서에 나타나지 않음

현재 8번은 #1360 이슈와 동일하지만 1번~7번까지는 #1360 이슈와는 다른 접근내역으로 발생한 문제입니다.
하지만 이 건의 문제는 7번(미납표시가 아님에도 미납표시가 뜸)만 해결되면 문제가 해소되는 이슈입니다.

**Comment by 10001if** [comment]
반납 전후로 언제나 미납으로 설정이 가능하므로 실수로 미납을 선택하여 누른 것이 아닌지 싶네요. 만약, 미납금액이 없는 주문서라면 미납 설정을 하더라도 미납 표시가 되지 않도록 하는 것이 필요해 보입니다.

**Comment by keedi** [comment]
주문서 확인중입니다. 현재 이슈와는 별개로, 주문서 내용에 **구두 반납을 23일에 할 예정**이라는 내용이 있는데 반납이 구분되는 경우에는 부분 반납을 진행하는 것으로 알고 있습니다. 관련해 부분 반납이었던 것인가요? 아니면 완납이었던 것인가요? 주문서 상으로는 한번에 반납한 것으로 보이긴 합니다만...

**Comment by keedi** [comment]
연체료와 배상비 값으로 실 데이터베이스에 저장된 값을 확인해보았습니다.

지금까지 저장된 연체비의 종류를 확인하는 질의는 다음과 같습니다.
빈문자열 등이 입력된 경우를 확인하기 위해 앞뒤로 `[`, `]` 문자열을 표시합니다.

```sql
SELECT
    CONCAT("[", o.late_fee_pay_with, "]")
FROM `order` AS o
GROUP BY o.late_fee_pay_with
;
```

결과는 다음과 같습니다.

```
+---------------------------------------+
| CONCAT("[", o.late_fee_pay_with, "]") |
+---------------------------------------+
| NULL                                  |
| []                                    |
| [가상계좌]                            |
| [결제 방법 선택]                      |
| [계좌이체]                            |
| [미납]                                |
| [세금계산서]                          |
| [카드]                                |
| [현금]                                |
| [현금영수증]                          |
+---------------------------------------+
10 rows in set (0.06 sec)
```

지금까지 저장된 배상비의 종류를 확인하는 질의는 다음과 같습니다.
빈문자열 등이 입력된 경우를 확인하기 위해 앞뒤로 `[`, `]` 문자열을 표시합니다.


```sql
SELECT
    CONCAT("[", o.compensation_pay_with, "]")
FROM `order` AS o
GROUP BY o.compensation_pay_with
;
```

결과는 다음과 같습니다.

```
+-------------------------------------------+
| CONCAT("[", o.compensation_pay_with, "]") |
+-------------------------------------------+
| NULL                                      |
| []                                        |
| [가상계좌]                                |
| [결제 방법 선택]                          |
| [계좌이체]                                |
| [미납]                                    |
| [카드]                                    |
| [현금]                                    |
+-------------------------------------------+
8 rows in set (0.06 sec)
```

**Comment by keedi** [comment]
상황을 정리하면 다음과 같습니다.

연장(연체)기 때문에 연장료 결제 방식을 미납으로 변경했는데, 실제로는 서울시 쿠폰으로 연장해서 미납이 완납이 되었지만 여전히 주문서 상에서는 미납 라벨이 뜨는 경우입니다.  해당 주문서의 연장(연체)료 항목을 보면 **미납**으로 저장이 되어있습니다.

여기서 확인해야할 부분은 다음과 같습니다.

- 미납 주문서 목록에서는 보였는지 여부
- 주문서 내에서만 미납 라벨이 체크된 것이 문제인지 여부
- 서울시 쿠폰으로 연장해서 연장료가 나오지 않을 경우 연장비 항목은 무엇으로 값을 저장해야 하는지 여부

**Comment by keedi** [comment]
> 서울시 쿠폰 규정을 활용하여 1회 연장버튼을 누름
두 가지로 나누어 문제를 살펴보면 이렇습니다.

### 사용자가 연장료를 미납으로 설정하기 전에 쿠폰 1회 연장을 클릭하는 경우

지금과 같은 경우라면 서울시 쿠폰 1회 연장을 클릭하는 시점에 페이지를 강제로 새로 고침한다면 문제를 가장 손쉽게 해결할 수 있지 않을까 싶습니다. 기술적으로는 문제가 없는지, 새로 고침 시점에 관련해서 담당자가 입력한 항목이 없어진다던가 등, 문제가 있을 여부가 있는지 확인할 필요가 있습니다.

### 사용자가 연장료를 미납으로 설정한 후 쿠폰 1회 연장을 클릭하는 경우

이 경우는 현재 이슈와 동일한 상태입니다. 주문서 UI에서 입력하는 항목은 변경하는 즉시 바로 주문서 데이터베이스에 반영됩니다. 따라서 1번의 경우처럼 새로고침을 한다고 기존 데이터베이스의 값이 바뀐다거나 하지 않습니다. 이 경우는 어찌 처리해야할지 고민이 필요합니다.

**Comment by 10001if** [comment]
> 주문서 확인중입니다. 현재 이슈와는 별개로, 주문서 내용에 구두 반납을 23일에 할 예정이라는 내용이 있는데 반납이 구분되는 경우에는 부분 반납을 진행하는 것으로 알고 있습니다. 관련해 부분 반납이었던 것인가요? 아니면 완납이었던 것인가요? 주문서 상으로는 한번에 반납한 것으로 보이긴 합니다만...

확인해보니, 구두만 먼저 반납하시고 다른 품목은 다른 날에 반납하려고 하였는데, 그냥 다 반납하신 거라고 하네요. 정상적인 반납절차로 보시면 될 것 같습니다.

**Comment by keedi** [comment]
> 여기서 확인해야할 부분은 다음과 같습니다.
> 
>     미납 주문서 목록에서는 보였는지 여부
>     주문서 내에서만 미납 라벨이 체크된 것이 문제인지 여부
>     서울시 쿠폰으로 연장해서 연장료가 나오지 않을 경우 연장비 항목은 무엇으로 값을 저장해야 하는지 여부

@10001if 상기 항목도 확인 부탁드립니다.

**Comment by 10001if** [comment]
>미납 주문서 목록에서는 보였는지 여부
미납 주문서 목록에 보이지 않았습니다. (미납금액이 존재하지 않기 때문에 나타나지 않는 것으로 이해했습니다.)

>주문서 내에서만 미납 라벨이 체크된 것이 문제인지 여부
네. 주문서 내에서 미납 라벨이 체크되었다면 미납 주문서 목록을 확인하여 미납 금액에 따른 가상계좌 문자 전송을 실시할텐데, 미납목록에 나타나지 않기 때문에 옷장지기가 오류로 인식하게 됩니다. 이 부분이 문제라고 생각하는데요. 그럼에도 불구하고 주문서 내에 미납 라벨이 붙어 있다고 해서 단지 그 이유만으로 실제로 추가적인 문제를 발생시키지는 않습니다.  

>서울시 쿠폰으로 연장해서 연장료가 나오지 않을 경우 연장비 항목은 무엇으로 값을 저장해야 하는지 여부
상식적으로는 연장비 항목에 연장료가 추가되고, 단벌할인 쿠폰이 이에 따라 기본대여료 + 연장료가 더해진 금액으로 차감되는 것이 맞는 것으로 보입니다. 단벌 할인쿠폰 수정적용이 안된다고, 취업날개 연장비 항목을 따로 생성에 기입하는 것은 바람직 해보이지 않습니다. 사유에 따른 연장비 항목이 추가되는 것은 문제 해결에 큰 도움이 되지 않을 것이라는 판단입니다.

**Comment by keedi** [comment]
> > 서울시 쿠폰으로 연장해서 연장료가 나오지 않을 경우 연장비 항목은 무엇으로 값을 저장해야 하는지 여부
> 
> 상식적으로는 연장비 항목에 연장료가 추가되고, 단벌할인 쿠폰이 이에 따라 기본대여료 + 연장료가 더해진 금액으로 차감되는 것이 맞는 것으로 보입니다. 단벌 할인쿠폰 수정적용이 안된다고, 취업날개 연장비 항목을 따로 생성에 기입하는 것은 바람직 해보이지 않습니다. 사유에 따른 연장비 항목이 추가되는 것은 문제 해결에 큰 도움이 되지 않을 것이라는 판단입니다.

이 부분은 정확하게 의미가 전달되지 않은 것 같습니다. 현재 연장비 항목에 입력되는 항목의 예 **가상계좌**, **결제 방법 선택**, **계좌이체**, **미납**, **세금계산서**, **카드**, **현금**, **현금영수증**와 같습니다. 여기서 연장비가 없는데도 불구하고 **미납**이라고 선택을 해서 불필요한 오해가 생기고 있는 부분을 언급한 것입니다. 가장 평범한 케이스라면 미납이 아니면 미납 체크를 할 필요도 없겠지요. 본 이슈외에도 #1360처럼 체크할 필요가 없는데 굳이 선택을해서 문제가 생기는 이슈인데, 이렇다면 차라리 명확하게 업무 프로세스에 **미납없음**과 같은 항목을 넣는게 좋을지, 또는 좋다면, 어떤 값을 넣는게 좋을지 여쭤본 것입니다.

아니면 제 의미가 정확하게 전달된 것이라면 해당 미납 금액이 없는 경우면 지금까지처럼 암묵적으로 해당 값을 비워두는게 더 적절하다고 판단하시는 것인지요? 연장비 항목을 추가한다는 것은 문제 해결에 도움을 주냐 안주냐의 문제가 아니라 프로세스 적으로 해당 부분을 암묵적으로 표기할 것인가 아니면 명시적으로 표기할 것인가 여부와 명시적으로 표기한다면 무슨 값으로 표기할 것인가 또는 암묵적으로 표기한다면 비워두는 것이 맞는 것인가를 여쭤본 것입니다.

**Comment by 10001if** [comment]
이해했습니다. 연장을 하면 연장비 항목을 입력해야 하는데, 현재 서울시 쿠폰의 경우에는 그런 항목이 없어 물어보신 것이었군요. 명확하게 서울시 쿠폰으로 연장을 한 경우, 연장비 항목을 입력할 때는 명시적으로 `미납없음` 항목을 넣는 것이 좋겠습니다. 앞으로 서울시 쿠폰 외에도 연장을 한 경우에 미납처리를 하지 않는 상황이 생길 수 있는데. 말씀하신 것처럼 미납없음 항목으로 입력하면 문제를 쉽게 해결할 수 있을 것 같네요. 해당 부분을 명시적으로 표기하고 미납없는 경우 `미납없음` 항목을 통해 입력을 하면 될 것으로 보입니다.

**Comment by keedi** [comment]
했던 말을 계속 반복하는 것 같아 헷갈릴 수도 있어 죄송합니다만, 반드시 **미납없음**이라는 항목이 있어야 하는 것은 아닙니다. 다만 지금처럼(맞나요?) 해당 부분이 비어있으면 미납없음으로 해도 상관없는지, 아니면 명시적인 항목이 필요한 것인지 의견을 여쭤본 것이라고 볼 수 있습니다. 명시적인 항목이 생길 경우 앞으로는 담당자가 추가될 항목을 지정해야 할 수 있습니다. 어느쪽이든 상관없습니다. 기존 방식이 좋다면 항목을 굳이 추가하지 않아도 됩니다. 의향?을 여쭤보는 것이라고 보면됩니다. 어느 것이 좋은지는 저도 잘 모르겠습니다.

**Comment by 10001if** [comment]
프로그램 운영에 있어 충돌하거나 예외적인 규정이 발생하는 것이 아니라면, 해당부분이 비어있는 경우 미납없음으로 해도 상관 없습니다. 위에서 명시적으로 표기하는 것이 필요하다고 말씀드린 이유는 그 기능이 없다면 문제가 발생한다고 이해했기 때문입니다. 

이야기 주신 것처럼 명시적으로 하거나 명시적으로 입력하지 않거나 미납없음으로 입력이 되는 결과가 동일하다면, 명시적인 항목을 담당자가 추가할 항목을 지정하는 대신 **_해당 부분이 비어있으면 미납없음으로 입력되도록 요청드립니다._**

**Comment by pingpongworks** [comment]
2017년 서울시쿠폰 관련 이슈 닫습니다. 2019년 같은 오류 발견시 다시 열겠습니다.
