### ISSUE TITLE
동시에 동일한 사람이 여러 번 예약 신청을 할 경우 최근 주문 내역의 주문서 생성 시각이 틀리게 보임

### ISSUE THREAD

**Issue by keedi** [opencloset/opencloset#1362]
#1358 이슈에서 확인한 사항입니다.

@10001if wrote:

> user/79992 의 경우 예약이 동시에 3번 반복해서 되었는데
> 프로그램 상의 버그 인지 확인요청을 드리기 위해 남겨 놓습니다.
> 
> ![318ce91114c0c19d578f8cd81755158a](https://user-images.githubusercontent.com/4696328/33104100-ba7c89e0-cf69-11e7-8a03-0b29982960e4.JPG)
> 11월 24일 14:30분에 3번 예약이 되어 있는 모습입니다.
> 
> ![2017-11-22 9 40 44](https://user-images.githubusercontent.com/4696328/33104094-b744c6b6-cf69-11e7-8f4a-48ed666a868a.png)
> 사용자 정보 내용입니다.
> 
> 예약을 진행한 시간도 동일합니다. 

실제로는 예약을 진행한 시각(`order.create_date`)이 3개가 다르지만 UI상으로는 마치 같은 것으로 보입니다. 다만, 주문서의 아이디는 제대로 각각의 주문서 아이디를 가리키고 있습니다.

**Comment by keedi** [comment]
진행합니다.

**Comment by 10001if** [comment]
#1358 내용을 확인했습니다. 3번을 연속으로 신청했다는 것은 이해가 되는데요. 그런데 3개의 예약이 중복으로 신청되는게 정상적인 상황인지 궁금합니다. 이렇게 3개의 예약이 동시에 진행되는게 가능한가요?

**Comment by keedi** [comment]
이쪽도 제가 착오로 버그를 열었네요. 관련 내용은 #1358 에 적었습니다.

정상적이지 않은 상황입니다. 다만, 몇가지 조건이 맞물려지면, 동시에 진행하는 것이 가능할 수 있습니다. 다만, 지금 발생한 상황은 열린옷장의 만일의 사태를 대비해 매시간 데이터베이스 백업을 시도하고 있는 것과 연계해 데이터베이스 용량이 너무 과도하게 커져서 1시간 단위로 백업을 진행하면서 현재 방문하고 있는 인원을 처리하기 쉽지 않아 생기는 현상으로 보입니다. 물론 아닐수도 있습니다만, 프로그램상의 문제라기 보다는 인프라 및 내부 백업등과 연계한 문제라고 보입니다.

**Comment by keedi** [comment]
오해한 부분이 있는 것 같습니다. 시도(요청) 시각과 주문서 생성 시각은 보통 동일하나, 이번 경우 시도 시각과 생성 시각이 다릅니다. 결과적으로 위에서 언급한 것처럼 시도 시각은 11:00:52, 11:00:58, 11:01:19이지만 생성 시각은 11:01:22로 셋 다 동일합니다.

로그 상으로 조금 더 살펴보니, 생성 시각과 시도 시각 사이에 다음과 같은 로그가 있음을 확인했습니다.

```
[Tue Nov 21 11:01:22 2017] [error] Worker 19523 has no heartbeat, restarting
[Tue Nov 21 11:01:22 2017] [debug] Stopping worker 19523 gracefully
...
[Tue Nov 21 11:01:22 2017] [debug] Worker 19520 stopped
[Tue Nov 21 11:01:22 2017] [debug] Worker 7369 started
[Tue Nov 21 11:01:22 2017] [debug] Worker 19523 stopped
[Tue Nov 21 11:01:22 2017] [debug] Worker 7370 started
```

해당 시각 사이에 워커가 종료되고 시작한 흔적이 보입니다. 관련해 사용자는 요청을 시도했지만 응답이 없다고 판단하고 재차 시도했을 가능성이 있으며, 이후 워커가 기동되면서 요청을 한번에 일괄처리한 것으로 보입니다.

상기 시각 이외에도 동일한 로그가 지속적으로 꽤 많이보이며, 산발적으로 분포해있지만 보통 정각 시점에 몰려있는 것으로 보아 시스템 오류를 대비한 1시간 단위 데이터베이스 백업을 시도하고 있는 시간과 맞물려 발생하는 것으로 보입니다. 당시 데이터베이스 설계시 왠만한 양이라할지라도 백업에 큰 부하가 없은 수준으로 스키마를 구성했으나, 이후 주문서 상태 로그라던가, 이미지 저장이라던가 등의 기능을 데이터베이스에 추가하면서 데이터베이스 백업 및 복원이 감내할 수 없는 정도로 소요 시간이 커졌습니다. 데이터베이스 백업의 특성상 IO도 많이 점유할 뿐만 아니라 백업하는 동안 제대로 질의를 수행하지 못할 가능성이 높으므로 현재 현상과 연관이 있을 확률이 매우 높습니다. 관련해서는 더 확인이 필요합니다.

UI상 주문서의 생성 시각을 표시하는 기능에는 문제가 없습니다. 착오로 인해 잘못 생성한 이슈이므로 닫습니다.
