### ISSUE TITLE
서울시 쿠폰(seoul-2017-2)의 방문 예약을 마감함

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1366]
서울시에서 오늘 연락이 왔습니다. 쿠폰 사용을 2017년 12월 13일까지로 제한하겠다는 내용인데요. 일자리 포털에서 취업날개 예약을 진행할 때 이에 대한 안내를 실시하고 방문 예약일이 13일까지만 예약이 되도록 하겠다고 합니다. 우리의 경우에는 예약 프로세스가 별도로 진행되고 있기 때문에 서울시 가이드라인에 따라 수정이 필요할 것으로 보여지는데요.

온오프라인 모두 대여일이 13일까지 이용 가능합니다. 오프라인은 예약일로 보고 온라인은 대여일(착용일 -1일)이 13일까지인 경우만 이용할 수 있어야 합니다. 제가 알기론 쿠폰 유효기간은 존재하지만 이렇게 예약일을 제한하는 기능은 없었던 것으로 알고 있는데요. 어떻게 진행하는 것이 좋을지 몰라 이슈에 적어둡니다. 의견 주시면 가능한 범위 내에서 예약일을 제한하고자 합니다.

그리고 대여 뿐만 아니라 연장도 마찬가지인데요. 일자리 포털에서 직접 연장하는 것은 서울시에서 제한하겠다고 했고 열린옷장에서 직접 연장하는 것은 연락이 오면 대여자에게 연장이 되지 않는다고 안내만 하면 되므로 13일 이후로(14일부터) 예약이 되지 않도록 하는 것이 필요한 상황입니다.

**Comment by 10001if** [comment]
@aanoaa 추가적으로 현재 취업날개 쿠폰 이용자 중에 반납예정일이 17일 이후인 대여자의 주문서 정보를 전달받고자 합니다. 해당 대여자에게는 직접 연락하여 해당 기간 이후의 대여는 취업날개 연장 쿠폰이 적용되지 않음을 고지해야 하기 때문입니다.

**Comment by 10001if** [comment]
@aanoaa 14일 이후에 예약이 되어 있는 서울시 쿠폰 이용자는 6명 가량입니다. 아직은 예약 활성화 창이 14일까지만 열려 있는데요. 내일부터 추가적으로 열게되면 14일 이후로도 계속 예약이 진행될 것으로 보입니다. 이미 예약이 진행된 분에게는 따로 전화를 드리려고 하는데요. 앞으로 예약되는 모든 분들에게 예약 후에 다시 연락을 드리는게 현실적으로 어려울 것 같습니다. 어떻게 해야 할지 몰라 문의드립니다.

**Comment by keedi** [comment]
오프라인의 경우 "방문 예약" 페이지에서 "방문 일자 선택" 버튼을 눌렀을때 12월 13일까지만 선택할 수 있으면 되는 것인지요? 12월 14일 이후 예약건 부터는 안보여서 결과적으로 선택할 수 없으면 되는 것인지요?

**Comment by keedi** [comment]
혼란을 방지하기 위해 본 이슈에서는 오프라인 방문 예약건에 한해 내용을 정리하고 작업을 처리하도록 한정합니다. 온라인 관련해서는 해당 저장소의 별도의 이슈에 등록해서 논의부탁드립니다. 별개로 동작하는 만큼 구분하는 것이 혼란을 줄일 수 있을 것 같네요.

**Comment by 10001if** [comment]
>오프라인의 경우 "방문 예약" 페이지에서 "방문 일자 선택" 버튼을 눌렀을때 12월 13일까지만 선택할 수 있으면 되는 것인지요? 12월 14일 이후 예약건 부터는 안보여서 결과적으로 선택할 수 없으면 되는 것인지요?

12월 14일 이후 예약건 부터는 안보여서 선택할 수 없도록 해주시면 됩니다. 이야기 주신 것처럼 온라인은 별도 이슈로 등록하도록 하겠습니다.

**Comment by keedi** [comment]
더불어 하나 더 문의 드립니다. 예약 일시 지정이외에 일반 예약으로 방문한 후 마지막에 쿠폰을 등록하는 절차는 현재 없나요? 이 경우 무언가 더 처리가 필요한가요? 아니면 내부적으로 이런 경우는 안내를 해서 불가능을 고지하실 예정이신지요.

**Comment by 10001if** [comment]
@keedi 일반예약으로 방문한 후 마지막에 쿠폰을 등록하는 절차도 존재합니다. 하지만 서울시 쿠폰은 이에 해당되지 않고 직접 예약하는 방법만 존재하기 때문에 현재 문제와는 관계가 없습니다. 따라서 예약일시 수정 절차만 진행해주시면 됩니다~

**Comment by keedi** [comment]
네 알겠습니다. 급한 이슈이니 만큼 가능하면 오늘 중으로 완료하겠습니다. 내일 이후에 예약 가능 일시를 추가적으로 열어도 13일까지만 보이도록 하겠습니다.

**Comment by 10001if** [comment]
@keedi 빠르게 처리해주셔서 감사합니다. 온라인 내용은 다시 적도록 하겠습니다.

**Comment by keedi** [comment]
작업은 완료했습니다. 테스트 서버 기준으로 13일 이후 날짜는 열람이 불가함을 확인할 수 있습니다. 실제 적용 전에는 14일까지 열람이 가능했습니다.

![screenshot-staff theopencloset net local 10301-2017-12-07-18-36-17](https://user-images.githubusercontent.com/138451/33708366-97dd82ac-db7d-11e7-9974-e65a86f08ae2.png)

**Comment by 10001if** [comment]
@keedi 감사합니다. 배포완료되면 다시 확인하도록 하겠습니다.

**Comment by keedi** [comment]
금일 중(내일 업무 시작전까지) 실서버에 반영할 예정입니다.

**Comment by 10001if** [comment]
네. 감사합니다!

**Comment by keedi** [comment]
배포 완료했습니다. 서울시 쿠폰 특성상 제가 실서버에서 확인을 하는 것이 불가능합니다. 이 시점 이후부터 서울시 쿠폰을 통해 예약을 했는데 13일 이후 날짜로 방문 예약이 되는 경우 별도 이슈로 알려주세요.

**Comment by 10001if** [comment]
직접 확인해보니 정상적으로 작동합니다. 확인 완료하였습니다.
