### ISSUE TITLE
서울시 쿠폰 예약 안내 삭제

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1369]
https://github.com/opencloset/opencloset/issues/1239 에서 안내되던 내용을 서울시 쿠폰 대여가 재개 될 때까지 삭제하려고 합니다. 수정 요청드립니다.

![2017-12-12 5 41 38](https://user-images.githubusercontent.com/4696328/33875157-b13919e2-df64-11e7-8243-ec0e4cef4f75.png)

**Comment by keedi** [comment]
확인했습니다. 진행합니다.

**Comment by keedi** [comment]
제거했습니다. 오늘 업무 시간 종료 후 배포 예정입니다.

이슈 닫습니다.

**Comment by 10001if** [comment]
@keedi 배포대기 상태가 너무 오래되는 것 같습니다. 실제로 예약을 할 수 없다고 해도 보이지 않아야 하는 부분입니다. 확인 부탁드리겠습니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
