### ISSUE TITLE
방문일자 선택시 예약인원이 0명인 시간도 예약창에서 확인 가능한 오류

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1374]
![2017-12-14 11 23 45](https://user-images.githubusercontent.com/4696328/33973521-ab3f6cf4-e0c6-11e7-9e31-f106b460a891.png)

보시는 바와 같이 예약인원이 초과되어 예약을 할 수 없는 것이 아니라
애초에 예약인원이 0명으로 닫혀 있는 시간대도 예약창에 나타나 있습니다.
마치 해당시간에도 예약이 가능한 것처럼 오해를 만들 수 있습니다.
기존에는 해당 시간은 아예 예약창에서 보이지 않았습니다.
수정 요청드립니다.

**Comment by 10001if** [comment]
@keedi 제가 로그인 한 상태에서 대여자 예약을 통해 본 내용을 확인했습니다. 로그아웃 뒤에는 정상적인 것으로 나타납니다. 이슈 닫겠습니다.

**Comment by keedi** [comment]
네, 관리자는 0이어도 보이게 해달라는 기능때문에 보이는 것입니다. 왜냐하면, 관리자는 해당 시간에 사용자가 꽉차있거나 심지어 자리가 없어도 예약을 할 수 있게 하는 기능이 필요하다고 하셨기 때문입니다.

혹시나 해서 제가 실서버, 개발서버 모두 확인해보았으나 0인 항목은 열람할 수 없습니다.
