### ISSUE TITLE
서울시 쿠폰 만료 이후에도 쿠폰을 적용해 예약이 됨

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1376]
orders/85630
orders/85624

기존 시간표에서는 4명이었는데, 2명이 사라졌습니다. 그 중 한명은 서울시 쿠폰3회 이용자였는데, 쿠폰 예약자임을 확인하고 옷장지기 미리 통화를 하여 방문하지 않겠다고 한 사용자 경우에는 예약을 취소한 것으로 보입니다.

위의 2명의 주문서는 오늘 서울시 쿠폰으로 예약된 사례입니다.

확인 요청드립니다.

**Comment by 10001if** [comment]
orders/85757

오늘 1분이 서울시 쿠폰으로 예약되어 있습니다.
확인 부탁드리겠습니다~

**Comment by 10001if** [comment]
@keedi 위에 작성한 orders/85757 분의 경우에는 좀 내용이 다른데요.

확인해보니 취업날개로 접속해 예약이 안된다고 하셔서 저희가 다른 방법을 통해 재예약(정상적인 열린옷장 방문예약)을 요청드렸는데, 잘 되지 않아 옷장지기가 직원예약을 통해 직접 예약을 한 경우라고 하는데요.

이 경우에 취업날개 예약이 된 경우라 좀 의아한 부분이 있습니다. 확인 요청드립니다.

**Comment by 10001if** [comment]
orders/85789
orders/85393

오늘은 2명의 서울시 쿠폰 예약자가 있었습니다. 전화로 확인 후 유료대여로 안내 하였습니다.

**Comment by keedi** [comment]
이해가 안되는 현상인데요. 어제 2명의 서울시 쿠폰 예약자가 있다고 하셨는데, 서울시는 아직도 이벤트 페이지를 통해 들어올수 있도록 열어둔건가요?

**Comment by 10001if** [comment]
@keedi 저도 이해가 안되는데요. 서울시는 이벤트 페이지를 막아둔 상태입니다. 일자리 포털을 통해 예약할 수는 없습니다. 페이지 자체를 닫아버린 상태입니다.

**Comment by keedi** [comment]
알겠습니다. 비정상적인 접근이 있었던 것 같네요. 확인해보겠습니다.

**Comment by 10001if** [comment]
@keedi 다행스러운 점은 오늘은 서울시 쿠폰 예약 건이 없었습니다.

**Comment by keedi** [comment]
아 그런데 다른걸 떠나 해당 두 이용자에게 어떻게 예약을 진행했는지 여쭤보셨는지요? 확인 좀 부탁드립니다. 전화를 해서라도 확인이 좀 필요할 것 같네요.

**Comment by keedi** [comment]
85393은 주문서가 없는 것 같은데 확인 부탁드리구요, 85789의 경우 어제 발생한 것이 아니라 예약 시점이 14일입니다. 14일이라면 아마도 서울시가 그 당시 안닫았을 걸로 사료되는데요... 어떠한지요?

**Comment by 10001if** [comment]
@keedi 85789은 어제 시간표에 있었던 것이지만, 14일에 예약을 시도한 것이고 서울시가 서비스를 제한한 건 15일 오전이었습니다. 따라서 14일에는 안닫은 상태이므로 그때는 예약이 가능했겠네요.. 85393은 서울시 쿠폰 이용 불가라고 안내하니 그 분이 예약을 취소하셨기 때문에 주문서가 사라진 것으로 보입니다.

그러니까. 이 모든게 서울시가 예약을 닫기 전에 일어난 상황이었네요. 제가 85393을 확인했을 때는 예약일이 11일이었습니다. 그냥 두 분도 이전과 동일하게 서울시가 닫기 전 들어왔다가 그 상태로 정상 예약을 실시한게 아닌가 싶은데요. 제가 2분께 전화드려 확인해보도록 하겠습니다.

**Comment by keedi** [comment]
일단 현재 이슈에서 언급한 모든 항목은 서울시가 예약 페이지를 닫았어야했는데 닫지 않아 발생한 것으로 보입니다. 따라서 정확히 서울시 쿠폰으로 예약이 안되게 막는 기능을 추가한 후 발생한 오류(버그)는 아닙니다. 방문 예약일이 14일 이후라 마치 14일 이후 예약건으로 보이지만 실제로는 그 이전 예약 건입니다.

제목과 라벨을 수정합니다.

**Comment by keedi** [comment]
비정상적인 이용인 줄 알았는데, 일반적인 절차대로 이용했을 가능성이 높습니다. 특별한 것이 없다면 확인 후 이슈를 닫겠습니다.

**Comment by 10001if** [comment]
추가적으로 문제가 발생하지 않아 이슈를 닫았습니다.
