### ISSUE TITLE
서울시 쿠폰 이용 후 일반 예약시 방문일을 선택할 수 없음

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1377]
user/84686
user/65325

의 경우 최초 서울시 일자리 포털을 통해 예약을 시도 한 뒤 다시 정상적인 루트로 열린옷장 홈페이지를 통해 방문 예약을 실시한 경우입니다. 이 경우에 서울시 쿠폰으로 예약을 시도한 것과 같이 방문일 선택이 되지 않습니다. 세션이 남아 있기 때문이라고 하셨는데. user/84686 사용자의 경우 최초 예약시 컴퓨터를 통해 진행했다고 하여 스마트폰으로 재예약을 요청드렸더니 정상적으로 예약이 된 것을 확인 할 수 있습니다. 

오늘 이런 건이 약 10건 정도 발생하였습니다.

근본적인 문제는 서울시에서 예약 페이지를 그대로 둔 점입니다. 따라서 이 부분에 대해 직접 담당자에게 즉시 수정 요청을 한 상태입니다.

**Comment by keedi** [comment]
쿠폰은 세션 정보를 이용합니다. 당시 서울시 및 관련 업체와의 정확한 가이드라인 없이 혼동속에 서울시 쿠폰 사용이 마감되었기 때문에 발생한 이슈입니다. 버그는 아닙니다만, 앞으로도 유사한 일이 생길 것을 감안하면 유효하지 않은 쿠폰 정보가 세션에 남아있을 경우 초기화 또는 지워줄 수 있는 방법을 만들어야 할 듯 합니다.

**Comment by pingpongworks** [comment]
2017년 서울시쿠폰 관련 이슈 닫습니다. 2019년 같은 오류 발견시 다시 열겠습니다.
