### ISSUE TITLE
방문 예약에서 지난 대여 이력을 선택 시 온라인 주문 내역을 열람할 수 없음

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1392]
![2018-01-03 4 46 47](https://user-images.githubusercontent.com/4696328/34512453-050bdabc-f0a6-11e7-8d97-57205976e4a4.png)

/user/9544 대여이력에서 보면 2/4일에 대여한 기록이 있는데. 방문예약을 시도하면

![150daf567f412c44242e9867a22f7a71](https://user-images.githubusercontent.com/4696328/34512503-4a8ddacc-f0a6-11e7-9e20-6e6977de2ee1.jpg)
아래와 같이 그 내역이 나타나지 않습니다. 실제 대여자가 자신의 대여기록을 확인하지 못해 문의를 해주었는데요.

지난 의류 기록이 보여지는 조건이 따로 없는 것으로 알고 있는데 이런 상황이 왜 발생하는지 궁금합니다.

**Comment by keedi** [comment]
확인 후 진행하겠습니다.

**Comment by keedi** [comment]
해당 부분 코드는 다음과 같습니다.

```html
/templates/visit-info-box.html.ep
% if ($orders->count) {
  <label class="block clearfix">
    <div class="control-group">
      <label class="control-label">예전 대여의류를 원하시면 날짜를 선택해주세요. 의류준비에 도움이 됩니다.</label>
      <select class="width-100 chosen-select" id="select-past-orders" name="past-order" data-placeholder="지난대여기록">
        <option value=""></option>
        % while (my $order = $orders->next) {
          % my $rental_date  = $order->rental_date;
          % my $pre_category = $order->pre_category;
          % next unless $rental_date;
          % next unless $pre_category;
          % my @temp = split /,/, $order->pre_category;
          % my @categories = map { $OpenCloset::Constants::Category::LABEL_MAP{$_} } @temp;
          <option value="<%= $order->id %>">
            %= $rental_date->ymd
            %= join(', ', @categories)
          </option>
        % }
      </select>
    </div>
  </label>
% }
```

**Comment by keedi** [comment]
간단히 설명하면 보이지 않는 의류는 온라인 의류였으며, 온라인 의류의 경우 희망 대여 의류 항목이 없었기 때문에 보여 줄 수 있는 부분이 없어 목록에서 표시하지 못한 것입니다.

**Comment by keedi** [comment]
어찌 해석하느냐에 따라 조금 애매한 부분은 있는데, 냉정하게 말하면 로직이 잘못되었습니다. 이미 대여한 주문서기 때문에 희망 대여 의류인 `pre_category` 값을 기준으로 보여주기 보다는 해당 주문서의 세부 항목인 `order_detail`을 확인해 실제 대여한 의류의 카테고리를 보여주는 편이 나을 것으로 보입니다.

**Comment by keedi** [comment]
지금처럼 `pre_category`로 값을 처리한다면 그나마 간편하게 처리할 수 있으나 온라인 대여의 경우 해당 항목이 없기 때문에 수정이 필요합니다. 더불어 상위/하위 주문서 여부를 체크하는 검증 코드도 없으므로 수정하면서 필요한 부분은 보강하도록 합니다.

**Comment by keedi** [comment]
방문 예약시 지난 주문 내역을 선택하는 UI에서 온라인 주문 내역을 열람하지 못하는 버그를 수정했습니다. 이는 `order.pre_category` 값 기반으로 동작했기 때문인데, 더욱 정확히 `order.order_details.clothes` 값 기반으로 열람할 수 있도록 변경했습니다. 이제는 `pre_category` 값이 없더라도 지난 주문서를 열람하는데 문제가 없습니다. 더불어 이 변경사항으로 인해 당시 희망 의류가 아니라 실제로 대여했던 의류가 보여지는 효과(?)가 있습니다.

**Comment by keedi** [comment]
구현 완료 후 변경된  화면입니다.

![2018-01-03 17-35-47](https://user-images.githubusercontent.com/138451/34513683-c2ff2988-f0ac-11e7-9b00-73f77e59f9e4.png)

@10001if 
이렇게 보이면 되는지요?

**Comment by 10001if** [comment]
네! 맞습니다.

**Comment by keedi** [comment]
작업 완료했으므로 이슈 닫습니다.

**Comment by keedi** [comment]
배포 완료 되었습니다.

**Comment by 10001if** [comment]
확인하였습니다. 감사합니다.
