### ISSUE TITLE
사용자 정보의 착용 여부 선택 항목을 입고감/기록요망으로 변경

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1398]
https://github.com/opencloset/monitor/issues/168 와 관련된 이슈입니다.

1. **사용자정보 착용여부 란의 제목과 선택항목 수정**
현재>착용여부 (안입고감 / 입고감)
수정> 기타 (입고감 / 기록요망)
![image](https://user-images.githubusercontent.com/17288038/34902710-5725097a-f864-11e7-8434-5a328018b87c.png)

2. **'입고감 / 기록요망' 선택 내용이 대여/포장완료 화면에도 반영되도록 함**
현재 포장을 위한 대여 페이지와 결제를 위한 포장완료 페이지에서 안입고감/입고감을 확인할 수 있는 것처럼, 입고감/기록요망이 반영되면 포장/결제 담당자도 확인할 수 있어 문제가 생기는 것을 완벽하게 방지할 수 있을 듯합니다.

**Comment by pingpongworks** [comment]
1>
그 사이에 https://github.com/opencloset/monitor/issues/168 를 통해 
의류준비 중에 `바로 입고 가려는 대여자`를 놓치지 않기 위한 `입고감` 이슈가 해결되었습니다. 

사용자정보에서 `입고감`을 선택하거나 
preparation 화면의 예약시간을 클릭하면
아래 이미지와 같이  `입고감`으로 표시됩니다. 

![image](https://user-images.githubusercontent.com/17288038/37637941-c5b52cc2-2c4d-11e8-9dbc-0283d5dd0cd7.png)


2> 
이에 따라 위에서 요청드렸던 내용을 다시 한번 요청드리고자 합니다.  

현재의 사용자정보 "착용여부" 항목을 수정해서
 `입고감` `기록요망` 중 선택할 수 있도록 하는 요청은 동일합니다. 

----------------------------------------------------------------------------------------------------------------

@aanoaa 님께는
`기록 요망`을 선택했을 경우에도 preparation 예약시간 자리에 
`기록 요망`이 표시되도록 요청드립니다. 

`기록이 필요한 경우`는 대부분 착용일이 많이 남았을 경우
사이즈측정 단계에서 발견되므로 
preparation 화면에서 직접 수정 기능은 없어도 될 듯 합니다. 

(위 내용은 monitor 이슈에도 다시 한번 남기겠습니다)

**Comment by aanoaa** [comment]
`does_wear` 가 `0 or NULL` 이면 false, 그밖에는 true 인데,
1, 2 로 구분하면 schema 변경없이 사용할 수 있을 것 같습니다.

**Comment by aanoaa** [comment]
`NULL or 0`: 입고가지 않고 기록요망 아님
`0b01`: 입고감
`0b10`: 기록요망
`0b11`: 입고가고 기록요망

binary int 로 취급해서 활용하면 문제가 해결될 것 같습니다.

**Comment by aanoaa** [comment]
@keedi `develop` 브랜치에 기능 구현하였습니다.
서버에 반영 부탁드립니다.
현재는 `master` 브랜치로 운영되고 있지 않아서 어떻게 해야될지 모르겠네요.
의존성 모듈은 이미 설치하였고,

    $ grunt

만 해주시면 됩니다.

**Comment by keedi** [comment]
가능하면 체인지로그는 깃헙 이슈의 제목을 그대로 써주세요. 상세한 내용이 필요하다면 해당 항목은 하부 목록으로 적으시면 됩니다.

```
- {{title}}
  - {{detail desc 1}}
  - {{detail desc 2}}
```

**Comment by keedi** [comment]
실서버에 배포 완료 후 `grunt` 실행 및 서비스 재기동 완료했습니다. 릴리스 전이므로 정상 동작하지 않는 경우 본 이슈를 다시 열어서 기록을 남겨주세요. 이슈 닫습니다.

**Comment by pingpongworks** [comment]
테스트했습니다. 잘 사용하겠습니다. 감사합니다~

**Comment by pingpongworks** [comment]
![default](https://user-images.githubusercontent.com/17288038/37891059-d43f9f7e-310d-11e8-8141-aab02387dcd6.png)

문구 수정 하나만 부탁드립니다~
추가로 만들어주신 항목 덕분에 생각이 나서 요청드립니다. 

`입고감+기록요망`은 추가로 만들어주신 항목인데 
입고가는 대여자의 경우는 기록이 필요없습니다. 

필요한 날짜보다 일찍 방문해서 입어보았는데 사이즈가 특이해서 따로 보관이 필요한 경우,
만약을 위해 입어본 옷의 기록이 필요합니다. 
아래와 같이 항목 수정해주시면 요긴할듯 합니다.  

`입고감+기록요망` => `보관+기록요망`

**Comment by keedi** [comment]
완료되서 이슈를 닫은 후 실제 서버에 배포 된 이후에는 항상 별도 이슈로 열어주세요. 닫힌 이슈를 새로 열어서 내용을 추가하면 이후 내용 추적이 몹시 어렵습니다. 간단히 말해 제목이 추가된 내용을 반영할 수가 없습니다. 추가한 내용과 이전 내용의 적용 시기를 판단하기가 매우 어렵기 때문이 이후 문제가 발생했을때 추적이 어렵습니다. 번거로우시겠지만 항상 이슈가 닫힌 뒤에는 그 내용이 작든 크든, 별도 이슈로 열어 등록해주세요. 더불어 새로운 이슈로 등록 해주신 후 본 이슈는 닫아주세요.

**Comment by pingpongworks** [comment]
네~ 알겠습니다. 별도 이슈로 등록하겠습니다~

**Comment by aanoaa** [comment]
제가 이어서 진행하겠습니다.
문구하나만 바꾸는 작업은 아닙니다.
물론 문구만 바꿔서 사용할 수는 있지만, 그렇게 되면 의도와는 다르게 사용되는 것입니다.

"기록요망과 입고감이 같이 사용되면 그때의 입고감은 입고감이 아니라 보관의 의미이다."

이런 내용을 기억해둬야 하는데 이런 내용들이 고려해야하는 포인트를 늘려서 복잡도를 증가시킵니다.

문구만 바꾸는 것이 아니라 올바르게 수정한다면
대여자가 입고가는지 여부를 저장하던 `does_wear` 라는 컬럼의 의미를 확장해서 기록요망 이라는 용도로 사용했는데

- 입고감
- 기록요망

여기에 보관 이라는 의미를 추가해야 합니다.

----------------------------------------

- `NULL or 0`: 안입고감
- `1`: 입고감
- `2`: 기록요망
- `3`: 입고감+기록요망

이었는데

- `NULL or 0`: 안입고감
- `0b001`: 입고감
- `0b010`: 기록요망
- `0b011`: 입고감+기록요망
- `0b100`: 보관
- `0b101`: 입고감+보관
- `0b110`: 기록요망+보관
- `0b111`: 입고감+기록요망+보관

이렇게 변경되어야 합니다.
의미가 하나 더 부여되면 내용이 두배는 더 많아집니다.

이미 does_wear 에 기록요망의 내용을 기록한 것 부터가 적절하지는 않았지만, 여기에 또 다시 의미를 부여하려고 하니 좀 꺼름직합니다.

본래 의도대로 `does_wear` 는 입고감의 용도로만 사용하고 주문서에 기록요망과 보관여부를 저장 할 수 있도록 변경하겠습니다.

**Comment by pingpongworks** [comment]
@aanoaa `보관`의 의미가 추가되어서 복잡도가 증가된다면, 

>0b011: 입고감+기록요망
0b100: 보관
0b101: 입고감+보관
0b110: 기록요망+보관
0b111: 입고감+기록요망+보관

이 부분은 아예 삭제해도 될 듯 합니다. 
필요했던 부분은 입고감 or 기록요망 이었어서요. 

>0b001: 입고감
0b010: 기록요망

`입고감+기록요망`을 `보관+기록요망`으로 수정하는게 간단한 문구수정이라고 생각해서 요청드린 건데요, 복잡해지는 작업이라면 꼭 필요하지 않습니다.  판단 한번 해봐주세요^^  @aanoaa

**Comment by aanoaa** [comment]
문구만 바꿔서 사용하는 것은 적절하지 않은 것 같습니다.
의류를 보관해야 하는지 여부를 주문서에 기록해두고 싶으신 거라면 착용여부에 보관여부를 기록하는 것이 아니라
보관여부를 따로 저장할 수 있도록 주문서를 변경해야 합니다.

그게 필요한 기능이라면 이슈를 새로 만들어주세요.

**Comment by pingpongworks** [comment]
@aanoaa 
그렇다면 일단 `보관` 관련한 작업은 보류해주세요. 

의류를 보관하는 행위는 업무 원칙에도 맞지는 않고 업무효율성과 대여자 배려 차원에서 하고 있는 것이라, 사실상 프로그램에 정식으로 기능추가는 생각을 안 했던 부분입니다. 

말씀해주신 대로 `보관`기능을 정식으로 만든다면, 단지 문구로 언급하는 것 이상을 고려해서 만드는게 맞을 듯 합니다. 주문서 어디에 표기할 것인가? 대여자가 다시 대여하러 왔을 때 어느 시점에 어디서 확인할 것인가? 등등요. 

좀더 정리한 후 꼭 필요할 때 새로 이슈 등록하겠습니다.
