### ISSUE TITLE
방문 예약에서 지난 대여 이력을 선택 시 일부만 열람됨

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1399]
https://github.com/opencloset/opencloset/issues/1392 에서는 
전체 대여이력 중 온라인 이력이 노출되지 않는 것으로 문제점이 파악되었으나

66460 사용자의 경우에는 온라인 대여가 아님에도 불구하고 
3회 대여를 했으나, 4번째 방문예약시 대여이력은 1회만 노출되었습니다. 확인부탁드립니다. 
![image](https://user-images.githubusercontent.com/17288038/34929109-4126baa4-fa05-11e7-93d2-026fc2b5bc31.png)

**Comment by keedi** [comment]
확인 후 진행하겠습니다.

**Comment by keedi** [comment]
구현은 완료되었으나 다른 이슈 완료 후 같이 배포하려고 대기중인 이슈입니다. 나머지 이슈와는 별개로 오늘 배포하도록 하지요. 배포 완료되면 기록해두겠습니다.

**Comment by keedi** [comment]
배포 완료 되었습니다.
