### ISSUE TITLE
2017-01-01 ~ 2017-04-31 기간 동안 서울시 쿠폰을 이용한 대여자의 주소를 포함한 명단

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1401]
서울시에서 주소 통계 분석을 위해 다음과 같은 자료를 요청하였습니다. 
급하게 요청받은 자료이지만, 급하게 보고해야 하는 상황이라고 합니다.
자료 요청드립니다.

no | 이름 | 주소
--|--|--
1 | 홍길동 | 서울시 광진구 아차산로 213

**Comment by keedi** [comment]
해당 기간 쿠폰 발급한 사용자 기준인가요? 아니면 해당 기간 대여를한 사용자 기준인가요? 특별히 명시된 것이 없으면 어떤 날짜를 선택해도 상관없는지요? 아시다시피 쿠폰 발급과 실제 대여일 사이에는 날짜 차이가 있을 수도 있고 없을 수도 있습니다. 느낌에는 쿠폰 발급일 기준일 것 같습니다만... 어찌 확인할까요?

**Comment by keedi** [comment]
관련해 2월 12일 기준 그 이전 요청은 별도의 서울시 쿠폰입니다. 당시 1~2월 사이의 협약 내용을 상기해보시면 될듯한데요. 구분된 쿠폰임은 신경쓰지 않고 언급하신 날짜에 대해서만 확인하면 되나요. 즉 1월 대여분은 2016년 서울시 쿠폰입니다.

**Comment by 10001if** [comment]
@keedi 네. 쿠폰여부를 구분하지 않고 실제로 서울시 쿠폰으로 1월 1일부터 4월 31일까지 사용한 대여자의 목록만 전달해 주시면 됩니다.

**Comment by keedi** [comment]
해당 기간동안 서울시 쿠폰을 사용한 대여자 명단과 주소를 구하는 질의는 다음과 같습니다.

```sql
SELECT
    u.id              AS user_id
    , u.name          AS user_name
    , ui.address2     AS address
FROM `user` AS u
LEFT JOIN `user_info`    AS ui ON ui.user_id = u.id
LEFT JOIN `order`        AS o  ON o.user_id = u.id
LEFT JOIN `order_detail` AS od ON od.order_id = o.id
LEFT JOIN `coupon`       AS c  ON c.id = o.coupon_id
WHERE (
    o.parent_id IS NULL
    AND c.`status` = 'used'
    AND c.`desc` LIKE 'seoul%'
    AND DATE(o.rental_date) BETWEEN '2017-01-01' AND '2017-04-31'
)
GROUP BY u.id
;
```

**Comment by keedi** [comment]
주소를 포함했지만 사용자 개인 정보는 이후 갱신되었을 수 있기 때문에 당시 대여할 당시 살고 있는 주소와 지금 제공해드리는 주소는 다를 수 있음을 참고 바랍니다.

결과는 메일로 첨부드렸습니다. 확인 후 문제 없다면 이슈 닫아주세요.

**Comment by 10001if** [comment]
확인했습니다. 급하게 요청드렸는데, 서둘러 확인해 주셔서 감사드립니다. 이대로 서울시에 전달하도록 하겠습니다.

**Comment by 10001if** [comment]
@keedi 추가적으로 5월 1일부터 5월 21일까지의 자료도 요청하였습니다. 번거로우시겠지만 한번 더 작업 요청드립니다.

**Comment by keedi** [comment]
질의는 다음과 같습니다.

```sql
SELECT
    u.id              AS user_id
    , u.name          AS user_name
    , ui.address2     AS address
FROM `user` AS u
LEFT JOIN `user_info`    AS ui ON ui.user_id = u.id
LEFT JOIN `order`        AS o  ON o.user_id = u.id
LEFT JOIN `order_detail` AS od ON od.order_id = o.id
LEFT JOIN `coupon`       AS c  ON c.id = o.coupon_id
WHERE (
    o.parent_id IS NULL
    AND c.`status` = 'used'
    AND c.`desc` LIKE 'seoul%'
    AND DATE(o.rental_date) BETWEEN '2017-05-01' AND '2017-05-21'
)
GROUP BY u.id
;
```

확인차 결과를 살펴보던 중 `23163 황**` 대여자의 주소에 이상한 문자가 있음을 확인했습니다. 관련해서는 별도로 검증 후 수정해야 할 것 같습니다.

**Comment by keedi** [comment]
결과는 메일로 첨부드렸습니다. 확인 후 문제 없다면 이슈 닫아주세요.

**Comment by 10001if** [comment]
두번째 파일도 확인했습니다. 이슈 닫겠습니다. 감사합니다.
