### ISSUE TITLE
바코드 발급: 조끼, 100개

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1403]
조끼를 등록해서 정식으로 대여하려고 합니다. 

바코드 100개 요청합니다.

**Comment by keedi** [comment]
크게 의미는 없지만 조끼는 내부적으로 waistcoat 라는 용어를 쓰고 있습니다. 혼돈을 방지하기 위해 vest라고 따로 명시하지 않으시고, 조끼라고 명명해주시면 됩니다.

**Comment by keedi** [comment]
바코드 발급은 다음 링크를 참고합니다.

https://github.com/opencloset/opencloset/issues/855#issuecomment-224835820

**Comment by keedi** [comment]
바코드 관련해 첫 자리 이슈가 있는 것으로 보이나 당장 문제가 생길 것 같지는 않습니다. 일단은 따로 수정없이 쓰도록 합니다.

**Comment by keedi** [comment]
실행 명령은 다음과 같습니다.

```
$ cd .../donation.theopencloset.net/
$ script/generate_code.pl waistcoat 100 --save > barcode-waistcoat-`date +%y%m%d`.csv
-------------------------------------------------
'-']/ waistcoat 의류코드가 갱신되었습니다 => W08K
```

**Comment by keedi** [comment]
발급한 바코드는 메일로 전달드렸습니다.

확인 후 문제없으시다면 이슈 닫아주세요~ :)

**Comment by pingpongworks** [comment]
네~ 확인했습니다. 감사합니다^^
