### ISSUE TITLE
2017년 동안 대여한 셔츠의 팔 길이 별 횟수 확인

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1404]
셔츠, 블라우스, 구두, 벨트와 같은 수트 외 품목들을 대여자가 직접 선택할 수 있도록 대여시스템을 바꿀 예정입니다. 
직접 고르고 싶어하는 대여자의 만족도를 높이는 한편, 현재의 1일 가능한 대여인원의 한계를 극복해보고자 함입니다. 

현재는 셔츠를 팔길이(=키)에 따라 ABC군으로 나누고, 하나의 군 내에서 가슴둘레 3cm 단위로 셔츠를 배열하고 있습니다. 현재의 사이즈 배열은 너무 복잡해서 대여자가 직접 맞는 사이즈를 고르기는 어렵습니다. 

일단 팔길이로 구분한 A,B,C 3개의 군을 2개로 줄여보면 어떨까 하는 의견이 있어 고민중입니다. 

2017년 1년 동안 셔츠가 팔길이별로 얼마나 대여되었는지 알 수 있으면 판단을 하는데 도움이 될 듯하여 데이터를 요청드립니다. 

* 기간 : 2017년 1월 ~ 2017년 12월
* 내용 : 셔츠 팔길이별로 대여되었던 횟수

각 품목별로 사이즈 배열과 대여방식이 정리되면 공간 배치도 바꾸고 내부 공사도 진행해야 할 수 있어 가능하면 빨리 부탁드립니다. 진행에 어려움이 있거나, 설명이 부족하면 다시 한번 말씀해주시기 바랍니다.

**Comment by keedi** [comment]
2017년 동안 대여한 셔츠의 팔 길이 별 횟수를 확인하는 질의는 다음과 같습니다.

```sql
SELECT
    c.arm
    , COUNT(*)
FROM `order` AS o
LEFT JOIN `order_detail` AS od ON od.order_id = o.id
LEFT JOIN `clothes`      AS c  ON c.code      = od.clothes_code
WHERE (
    o.parent_id IS NULL
    AND od.clothes_code IS NOT NULL
    AND c.category = 'shirt'
    AND YEAR(o.rental_date) = 2017
)
GROUP BY c.arm
ORDER BY c.arm
;
```

결과는 다음과 같습니다.

```
+------+----------+
| arm  | COUNT(*) |
+------+----------+
| NULL |       92 |
|   17 |       62 |
|   19 |       46 |
|   20 |        3 |
|   22 |       10 |
|   23 |        4 |
|   24 |        7 |
|   25 |        7 |
|   26 |        5 |
|   42 |        5 |
|   54 |        1 |
|   55 |       21 |
|   56 |       21 |
|   57 |      117 |
|   58 |      656 |
|   59 |      863 |
|   60 |     1156 |
|   61 |     1356 |
|   62 |     3078 |
|   63 |     1723 |
|   64 |      836 |
|   65 |      472 |
|   66 |      341 |
|   67 |      265 |
|   68 |       95 |
|   69 |        6 |
|   70 |       52 |
|   71 |        6 |
|   91 |        1 |
+------+----------+
```

결과 중 `NULL` 로 표기 된 것은 팔 길이 정보를 입력하지 않은 의류를 대여한 횟수를 의미합니다.

**Comment by pingpongworks** [comment]
감사합니다. 주신 데이터 참고해서 셔츠 배열 잘 판단해보겠습니다^^

**Comment by keedi** [comment]
이슈가 열려있는데 확인 완료하시면 **확인요망** 라벨 제거해주시고 닫아주시면 됩니다.

이슈가 닫혀있다면 확인 완료하시고 **확인요망** 라벨 제거만 해주시면 되고, 추가로 더 처리해야할 것이 있을경우는 **확인요망** 라벨은 제거하고 이슈를 다시 열고 처리해야할 내용을 추가로 기입해주시면 됩니다.

본 이슈는 완료된 것으로 보이니 이슈 닫겠습니다. :)

**Comment by pingpongworks** [comment]
아, 라벨 제거를 몰랐네요. 알겠습니다^^
