### ISSUE TITLE
쿠폰: gunpo201801 800건 발급 및 200건 제한

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1406]
https://github.com/opencloset/opencloset/issues/858 에서 진행해 주셨던 내용입니다.

`군포청년날개`의 쿠폰 발행을 요청드립니다. 
- `suit` 타입으로
- 사용기간은 2018/12/31 까지
- 설명은 `군포청년날개`
- 800개
- 총 이용 횟수는 200회로 제한 

군포시에서 진행하는 프로젝트를 위해 쿠폰 발급을 요청드립니다. 
열린옷장에서 800개의 쿠폰 번호만 전달하면 군포시에서 해당 청년에게 쿠폰번호를 전달하는 방식입니다. 이후 개인이 예약페이지를 통해 쿠폰 입력 후 예약을 진행한다고 합니다. 서울시 쿠폰과 유사한 형식이지만 군포시 내부에서 연령, 나이, 이용횟수를 체크하여 선정된 인원에게 쿠폰을 제공한다고 합니다. 따라서 열린옷장은 이상의 조건으로만 쿠폰을 발급하여 제공하면 됩니다. 

통계페이지는 서울시 쿠폰과 동일하게 요청드립니다. 온라인, 오프라인 모두 이용 가능합니다. 따라서 전체, 오프라인, 온라인 페이지가 필요합니다. 

쿠폰번호 발급은 2/13일까지 요청드립니다.

**Comment by 10001if** [comment]
@keedi 전달해야 하는 마감일이 2/13입니다. 혹시 놓치실까봐 기록해 둡니다.

**Comment by keedi** [comment]
요청주실 때 해당 쿠폰의 종류에 따른 식별자 정보도 같이 부탁드립니다. 이부분은 열린옷장에서 임의로 정해도 상관없습니다. 다만 영소문자와 숫자를 조합해서 만들어주시면 됩니다. 일종의 아이디로 생각하시면 되는데 예를들면 지금까지 있었던 몇가지 쿠폰의 예는 다음과 같습니다.

- 10bob
- anyangyouth
- gwanak
- hanshin_univ
- incheonjob
- linkstart

800개 발급인데 총 이용 횟수를 200회로 제한하는 이유가 있는지요? 더불어 예전에 그런 선례가 있었는지요. 시스템 자체는 쿠폰을 발급한다는 것 자체가 총 800번 이용하게 하겠다는 의미입니다. 이용횟수가 200회 제한이라면 200개만 발급하거나 또는 800개 발급해서 해당 기관이 200개만 나눠주면 됩니다. 이것을 시스템적으로 발행한 800개의 쿠폰을 200개만 쓰게 하게되면, 마치 예약시간에 추가 인원이 등록되는 것처럼 200개 전후로해서 200개로 딱 끊기 어려울 가능성이 높으며, 쿠폰 별로 관련된 불필요한 유지보수가 어려운(애초에 쿠폰이 그런 의미가 아니므로) 코드가 들어가게 됩니다.

전에 본의 아니게 유사했던 이슈가 있었던 것 같은데, 혹시 총 이용횟수 제한과 관련했던 이슈가 있었는지 여부와 있다면 이슈 번호도 공유 부탁드립니다.

**Comment by 10001if** [comment]
1. 식별자는 gunpoyouth로 요청드립니다.

2. 800개 발급인데 200회로 제한하는 것은 #1298 에서도 진행한 선례가 있었습니다. 
군포시 예산으로 이용가능한 쿠폰 최대 횟수가 200회입니다. 200회를 초과하여 대여를 진행하면 한정된 예산을 벗어나게 됨으로 초과 비용에 대해서는 청구 할 수 없습니다. 그래서 200회를 제한하려는 것이구요. 800장 발급은 쿠폰을 제공했으나 사용하지 않는 인원을 대비하여 4배수로 쿠폰을 발급한 것입니다. 이 부분에 대해서는 군포시에 전달할 계획입니다. 

말씀하신대로 지급받은 당시에는 쿠폰을 사용할 수 있었지만, 이후에 사용하려고 보니 사용을 못하게 되는 경우가 생길 수 있는데. 이를 해결하기 위해 200장의 쿠폰을 발행한다고 하여도 사용하지 않은 쿠폰이 남아 있고 그 이용량을 채우기 위해서는 추가로 발급을 해야 하므로 문제는 동일하게 남아 있을 것으로 보입니다. 

3. 하지만 2번의 이유와는 관계없이 불필요한 유지보수가 어려운 코드가 지나치게 많이 발행되는 것이 문제인 부분이 있다면 2배수 정도로 400장 발행을 진행하여도 큰 문제는 없습니다. 쿠폰을 다량으로 발행하는 것이 프로그램에 영향을 미치는 정도가 별로 크지 않다고 생각해서 800장을 요청드렸었습니다.

**Comment by keedi** [comment]
전 이부분은 금시 초문인데요. 일단 #1298 에서 200회 제한이 언급되어 있지만, 관련된 진행사항이 없었던 것으로 기억하는데요. 정말 당시 300개인데 151회로 제한하는 기능이 추가되었나요? 제가 로그나 기타 코드 상으로 확인했을 때는 해당 부분을 찾을 수가 없는데요. 당시 정말 151회 제한 기능이 추가되었었나요? 추가로 그렇다면 #1364 에서 추가 발급을 요청하셨는데, 이때는 151회 제한은 그대로였던 것인가요? 아니면 제한 사항이 없었던 것인가요? #1364 에서는 제한과 관련된 내용이 전혀 언급되어 있지 않습니다.

@aanoaa @10001if 두 분 확인 부탁드립니다.

**Comment by 10001if** [comment]
@keedi 안양시 경우에는 제가 그렇게 요청을 했지만 적용 되었는지, 되지 않았는지는 확인하지 못했습니다. 다만, 서울시 쿠폰의 경우 기능이 존재했던 것으로 알고 있었습니다. #1218 하지만 해당 내용은 서울시 쿠폰에 국한 된 것이라면 해당 기능을 따로 만들기보다는 180회, 190회, 200회 총 3회에 결쳐 알림을 받을 수 있도록 하는 정도면 충분할 것으로 보입니다.

**Comment by keedi** [comment]
@aanoaa 해당 부분인 쿠폰 n회 제한 적용 여부와, 혹시라도 적용되었다면 코드 어느 부분인지 확인 부탁드립니다.

**Comment by keedi** [comment]
서울시는 실제로 너무 대중이 없었어서 그 부분을 구현했다기 보다는 서울시만을 위해서 아예 따로 작업했었습니다. 쿠폰의 기능 범위를 벗어났다고 보여지긴 했는데, 중요한 부분이지만, 그게 또 어떻게 변경될지 모르는 상황이라 일반화를 시킬수는 없었고, 서울시 쿠폰 용으로만 만들었던 것이라고 보시면 됩니다.

**Comment by keedi** [comment]
상황을 봐가며 쿠폰 발급과 별개로 쿠폰 사용개수 제한을 두는 기능을 구현해야 할지, 한다면 어떻게 해야할지 여부를 결정해야 합니다. 사실 180회 190회 200회 알림을 하는 것이나 200개 제한을 거는 것이나 그게 그것이긴합니다. 따라서 어떤 식으로 이 문제를 해결할지 고민을 해보겠습니다.

어찌됐든 해당 기관 쿠폰을 200개든 800개든 발급 하는 것 자체는 어려움은 없습니다.

**Comment by 10001if** [comment]
서울시 쿠폰용으로 만들어진 기능이라는 사실은 이해했습니다. 다만, 쿠폰 발급 수와 이용횟수를 동일하게 한다면 다음과 같은 문제가 발생합니다.

예) 이용횟수 100회로 제한되어 있는 상황. 따라서 쿠폰도 100장을 발급. 

100장을 모두 소진하여 해당단체에서 쿠폰 추가 발행을 요청. 확인 해보니 발행된 쿠폰 100장이 모두 사용된 경우에는 쿠폰 추가발행을 하지 않음. 그러나 사용된 쿠폰이 100장 미만임. 그래서 쿠폰을 100장 더 발행하여 제공하기로 함.

이렇게 되는 경우. 결과적으로 최초에 200장을 발행하는 것과 이후 추가 100장을 발행하는 것이 같은 효과를 가져오게 됩니다. 이 문제는 발행된 쿠폰 = 사용된 쿠폰 이라는 전제 없이는 성립하기 힘든데요. 애초에 사용된 쿠폰만을 정산하는 것으로 약정되어 있고, 쿠폰을 제공하는 모든 단체(서울시쿠폰-2017 제외)에 예산이 배정되어 있으므로 쿠폰 발행 수와 이용횟수에 차이가 발생하는 것은 필연적으로 발생하는 현상입니다.

핵심은 쿠폰발행은 이용횟수에 초과하여 발행하는 것은 현재 상황에서 반드시 필요한 것으로 보이나 다만, 발행된 쿠폰이 이용횟수를 초과하여서는 안되므로 이용횟수 초과 시 쿠폰 대여가 이뤄질 수 없게 하거나 혹은 미리 그 정보를 숙지하여 관련 단체와 결론을 내는 행위가 필요합니다. 

정리하자면, 이용횟수가 정해져있고(예산이 확정되어 있는) 쿠폰 발행=쿠폰 사용이라는 조건이 성립하지 않는 이상 쿠폰발행 수 > 이용 횟수 가 발생하게 되는 것은 자연스럽고 일반적인 현상입니다. 따라서 이를 위해 적합한 문제 해결 방법이 필요합니다.

**Comment by keedi** [comment]
항상 상황이 동일하지는 않습니다.

추가 발행 건에  대해서는 해당 단체가 결정하고 관리하는 것이라고 생각했었는데요. 즉 300장 발급한 상태에서 250장만 쓰고 50장은 남아있는 상태에서 추가 100장을 발급한다는 것은 150장이 쓰일 가능성이 있다는 것으로 이해 한 것이구요. 그런데 지금 상황은 300장 발급에서 250장만 쓴 상태에서는 50장은 쓸지 안쓸지 모르겠고, 여러가지 이유에서 정말 150장을 더쓰길 바라는 마음에서 추가 100장을 발급한다고 보기보다는 안 쓴 50장은 앞으로도 안 쓸 것 같으니 정말 100장을 쓰리라는 가능성을 가지고 발급 요청하는 것이죠. 무슨차이냐면, 원래 쿠폰은 해당 단체나 나눠주는 열린옷장에서 직접 관리를 하리라고 가정하고 만든 기능인데, (그래서 쿠폰 자체는 단순하게 유효한 쿠폰 생성 및 해당 쿠폰의 유효성 검증 정도로만 이루어져있습니다.) 다시 그 관리라는 부분이 시스템으로 넘어온 것이죠.

어떻게 쓰냐에 따라 다른데요. 쿠폰 자체가 정말 의미를 가지는 문화 상품권 또는 백화점 상품권 사용한다면 쿠폰 발행수가 이용 횟수보다 많거나 같은 상황은 의미가 없습니다. 어짜피 사용가능한 유효한 쿠폰을 발급한 것이고 가져오면 사용할 수 있으니 재화와 같은 것이죠. 지금은 쿠폰 자체를 마트나 쇼핑몰 할인 코드처럼 사용하는 느낌이구요. 저희는 전자를 생각하고 구현한 것이나 현재 후자를 생각하거나, 후자처럼 사용되고 있으니 어쩔 수 없네요.

이렇게 되면 당장 쿠폰 생성에서부터 이를 고려하지 않은 부분이 나타납니다.

예를 들어 현재 등록된 쿠폰의 종류는 다음과 같은데요.

- 10bob
- anyangyouth
- gwanak
- hanshin_univ
- incheonjob
- linkstart
- seoul

`seoul`의 경우 제일 골치가 아픈 케이스인데, 일단 차치하고, 기존 등록건도 그렇고 이번에 요청하시는 건인 `gunpoyouth`도 그렇고 1번 이상 사용함을 고려하지 않은 것이 보입니다. 즉, 개수 제한을 하는 한 기간(term)의 쿠폰은 그 이후 기간(term)의 쿠폰과 구분을 할 수 있어야 하는데, 일단은 전혀 그런 것이 보이지 않죠. 말이 어려운데 정리하면 군포시 쿠폰을 예로 들면, `gunpoyouth`로 5월까지 개수 제한을 걸었다고 친다면, 6월부터 발급하는 군포시 쿠폰은 `gunpoyouth`라는 이름으로 발급하면 안됩니다. 즉 다른 이름이어야 하고 이부분은 염두해서 관리해주셔야 합니다. 일선에서는 추가 발급이라고 생각할 수 있으나, 기간(term)이 달라지면, 아예 다른 쿠폰이 되는 것입니다. 5월까지 개수 제한을 건 상태에서 4~5월에 추가로 발급하는 것은 기존 것과 동일한 쿠폰이겠죠. 그동안 이런 개념없이(필요가 없었다고 생각했었습니다만) 사용했었는데, 이제는 말씀하신 기능을 넣으려면 필연적일 것 같습니다.

앞으로는 새로운 term에 대한 쿠폰 생성 또는 기존 term에 대한 쿠폰 추가에 대해서는 반드시 쿠폰 명과 쿠폰 아이디 및 해당 기간에 대한 누적 제한(limit) 수를 결정해서 알려주셔야 할 것 같습니다. 저희는 쿠폰 아이디를 보고 이것이 추가 발급인지 새로운 기간(term)에 대한 발급인지를 판단할 수 있을 것 같네요.

**Comment by keedi** [comment]
적절한 요청 형식은 다음과 같을 것 같습니다.

```
제목: 쿠폰: busan007 800건 발급

아이디: busan007
이름: 부산시 취업 지원
제한: 200
발급: 800
유형: suit
사용기간: 2018-12-31
```

상기 기준 제한은 200개 그대로이고 500건 추가 발급한다면 다음과 같은 형식이 될 것입니다. 이 때 총 발급량은 1300건이 됩니다.

```
제목: 쿠폰: busan007 500건 추가 발급

아이디: busan007
이름: 부산시 취업 지원
제한: 200
발급: 500
유형: suit
사용기간: 2018-12-31
```

상기 기준 제한을 500개로 변경하면서 200건 추가 발급한다면 다음과 같은 형식이 될 것입니다. 이 때 총 발급량은 1500건이 됩니다.

```
제목: 쿠폰: busan007 200건 추가 발급

아이디: busan007
이름: 부산시 취업 지원
제한: 500
발급: 200
유형: suit
사용기간: 2018-12-31
```

별도의 쿠폰 생성시는 별도의 쿠폰 아이디를 명시해야겠죠. 또한 쿠폰 이름을 별도의 쿠폰 아이디별로 다르게 하지 않는다면 시스템에서는 동일한 명칭으로 보여주니 이점도 고려하셔야 할테구요.

**Comment by keedi** [comment]
쿠폰 수 제한 기능을 위한 별도의 이슈를 생성해서 진행하겠습니다.

**Comment by 10001if** [comment]
>앞으로는 새로운 term에 대한 쿠폰 생성 또는 기존 term에 대한 쿠폰 추가에 대해서는 반드시 쿠폰 명과 쿠폰 아이디 및 해당 기간에 대한 누적 제한(limit) 수를 결정해서 알려주셔야 할 것 같습니다. 저희는 쿠폰 아이디를 보고 이것이 추가 발급인지 새로운 기간(term)에 대한 발급인지를 판단할 수 있을 것 같네요.

네, 알겠습니다. 쿠폰아이디를 명시하여 추가 발행인지 새로운 기간에 대한 발급인지를 판단할 수 있도록 요청드리도록 하겠습니다. :)

**Comment by 10001if** [comment]
```
제목: 쿠폰: gunpo201801 800건 발급 및 200건 제한

아이디: gunpo201801
이름: 군포 청년날개
제한: 200
발급: 800
유형: suit
사용기간: 2018-12-31
```

**Comment by keedi** [comment]
확인했습니다. 제목 부분은 앞으로 이슈 제목에 넣어주시면 됩니다. 쿠폰 새로운 발행이든, 추가 발행이든 모두 별도의 이슈를 열고 제목을 적어주시고 쿠폰 라벨을 붙여주시면 됩니다.

**Comment by 10001if** [comment]
네. 알겠습니다. 쿠폰 발행과 관련해서는 이야기 주신 부분 체크해서 올리도록 하겠습니다.

**Comment by 10001if** [comment]
@keedi 군포시에서 쿠폰 발행 일정 문의가 왔는데, 제한 개수 설정 기능 추가로 발행이 13일 보다 늦어질 수도 있나요? 기존에는 늦어도 설 전에는 메일을 드릴 수 있을거라 임시로 답변을 한 상태였습니다.

**Comment by keedi** [comment]
13일 발행을 염두해 작업중입니다. 발급만 하는 것은 바로 가능하지만 개수 제한 기능 때문에 시간이 걸립니다. 13일 전달에는 문제 없을겁니다.

**Comment by keedi** [comment]
개수 제한 기능은 #1408 에서 처리 중입니다. 별개로 800개의 쿠폰을 발급해서 메일로 전달 드렸습니다.

이슈 닫습니다. 문제가 있다면 다시 열어주세요.

**Comment by keedi** [comment]
> 통계페이지는 서울시 쿠폰과 동일하게 요청드립니다. 온라인, 오프라인 모두 이용 가능합니다. 따라서 전체, 오프라인, 온라인 페이지가 필요합니다.

통계 페이지 관련 요청은 별도의 이슈로 요청해주세요. 추가적으로 요청하실 때 가능하면 주소와, 화면 캡쳐와 함께 자세하게 내용 설명 부탁드립니다. 페이지와 기능이 너무 많기도 하고 최초 구현때와 비교해 달라진 부분이 많아서, 구체적으로 설명해주시지 않으면 확인 및 진행이 어렵습니다.

**Comment by keedi** [comment]
이슈가 쿠폰과 통계가 섞여있는데, 이처럼 이슈가 두 가지 이상의 내용을 담으면서 변경 사항이 많은 경우 아차하면 기억 못하는 경우가 많습니다. 지금 같은 경우가 통계 관련 요청을 지금 인지했는데요. 어찌됐든 가능하면 한 이슈에는 하나의 내용을 담아주시면 좋습니다. 제목은 그 하나의 내용을 가장 잘 설명해야하구요. 그렇지 않을 경우 이후 통계 관련 내용을 다시 찾으려고 할 때 제목만 보고는 현재 이슈에서 진행되었다는 것을 인지하기 어렵겠지요.

**Comment by 10001if** [comment]
@keedi 알겠습니다. 두 가지 이슈가 혼합되어 있으면 해결하기도, 이후에 확인하는데에도 불편함이 있겠네요. https://github.com/opencloset/opencloset/issues/1412 에 작성하였습니다.

**Comment by 10001if** [comment]
@keedi 메일 잘 받았고 해당 단체로 메일 전달하였습니다. 감사합니다.

**Comment by aanoaa** [comment]
400 건으로 제한을 늘려달라고 해서,

```sql
UPDATE coupon_limit SET `limit` = 400 WHERE cid = 'gunpo201801';
```

이렇게 제한을 늘렸습니다.
