### ISSUE TITLE
주문서 목록에서 가상계좌 문자 전송시 아임포트 서버 통신 오류가 발생함

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1407]
1월 27일 / 오전 9시 28분에 orders/89642의 미납처리를 하다가 오류가 발견되어 캡처한 프로그램 화면입니다.
사진과 같이 대여자에게 미납금 요청을 하기 위해 *가상계좌 문자전송*을 누르면 "오류가 발생했습니다"가 뜨는 경우가 자주 일어나고 있습니다. 이럴 경우, 한번 내지 두번 더 시도하면 "정상적으로 발송되었습니다" 처리가 되고 있기는 합니다. 

![image](https://user-images.githubusercontent.com/17288038/35715559-9a5c5cfe-0816-11e8-858a-26989bab6cb0.png)

미납 주문서가 아닌데 주문서 상세 페이지에서 미납으로 표시됨 #1360 에서 언급했던 주문서 85769와 같은 오류입니다.

**Comment by keedi** [comment]
프로그램에서 예외를 처리하고 있으므로 버그는 아닙니다. 다만 계속 해서 발생한다면, 서비스를 사용하는데 문제가 생길 가능성이 있으므로 원인을 파악해서 해결해야 할 것입니다. **bug** 라벨은 제거하고 처리합니다.

**Comment by keedi** [comment]
로그 패턴을 확인해보니 다음과 같습니다.

```
[Sat Jan 27 16:49:37 2018] [debug] PUT "/api/order/90028/send-vbank-sms.json"
[Sat Jan 27 16:49:37 2018] [debug] Routing to controller "OpenCloset::Web::Controller::User" and action "auth"
[Sat Jan 27 16:49:37 2018] [debug] Routing to controller "OpenCloset::Web::Controller::API" and action "api_send_vbank_sms"
[Sat Jan 27 16:49:37 2018] [error] The payment agency failed to process
[Sat Jan 27 16:49:37 2018] [debug] 
[Sat Jan 27 16:49:37 2018] [debug] 500 Internal Server Error (0.323272s, 3.093/s)
```

패턴이 있기 때문에 다음 명령으로 일련의 정황을 확인할 수 있습니다.

```
$ rgrep -B 3 -A 2 'The payment agency' development.log.9
```

1월 27일 기준 오류가 발생한 시스템의 전체 로그는 다음과 같습니다.

```
development.log.9-[Sat Jan 27 09:26:47 2018] [debug] PUT "/api/order/89642/send-vbank-sms.json"
development.log.9-[Sat Jan 27 09:26:47 2018] [debug] Routing to controller "OpenCloset::Web::Controller::User" and action "auth"
development.log.9-[Sat Jan 27 09:26:47 2018] [debug] Routing to controller "OpenCloset::Web::Controller::API" and action "api_send_vbank_sms"
development.log.9:[Sat Jan 27 09:26:48 2018] [error] The payment agency failed to process
development.log.9-[Sat Jan 27 09:26:48 2018] [debug] 
development.log.9-[Sat Jan 27 09:26:48 2018] [debug] 500 Internal Server Error (0.203001s, 4.926/s)
--
development.log.9-[Sat Jan 27 09:28:33 2018] [debug] PUT "/api/order/89642/send-vbank-sms.json"
development.log.9-[Sat Jan 27 09:28:33 2018] [debug] Routing to controller "OpenCloset::Web::Controller::User" and action "auth"
development.log.9-[Sat Jan 27 09:28:33 2018] [debug] Routing to controller "OpenCloset::Web::Controller::API" and action "api_send_vbank_sms"
development.log.9:[Sat Jan 27 09:28:33 2018] [error] The payment agency failed to process
development.log.9-[Sat Jan 27 09:28:33 2018] [debug] 
development.log.9-[Sat Jan 27 09:28:33 2018] [debug] 500 Internal Server Error (0.274298s, 3.646/s)
--
development.log.9-[Sat Jan 27 11:46:17 2018] [debug] PUT "/api/order/88794/send-vbank-sms.json"
development.log.9-[Sat Jan 27 11:46:17 2018] [debug] Routing to controller "OpenCloset::Web::Controller::User" and action "auth"
development.log.9-[Sat Jan 27 11:46:17 2018] [debug] Routing to controller "OpenCloset::Web::Controller::API" and action "api_send_vbank_sms"
development.log.9:[Sat Jan 27 11:46:18 2018] [error] The payment agency failed to process
development.log.9-[Sat Jan 27 11:46:18 2018] [debug] 
development.log.9-[Sat Jan 27 11:46:18 2018] [debug] 500 Internal Server Error (0.41738s, 2.396/s)
--
development.log.9-[Sat Jan 27 14:20:13 2018] [debug] PUT "/api/order/90078/send-vbank-sms.json"
development.log.9-[Sat Jan 27 14:20:13 2018] [debug] Routing to controller "OpenCloset::Web::Controller::User" and action "auth"
development.log.9-[Sat Jan 27 14:20:13 2018] [debug] Routing to controller "OpenCloset::Web::Controller::API" and action "api_send_vbank_sms"
development.log.9:[Sat Jan 27 14:20:14 2018] [error] The payment agency failed to process
development.log.9-[Sat Jan 27 14:20:14 2018] [debug] 
development.log.9-[Sat Jan 27 14:20:14 2018] [debug] 500 Internal Server Error (0.465209s, 2.150/s)
--
development.log.9-[Sat Jan 27 16:49:37 2018] [debug] PUT "/api/order/90028/send-vbank-sms.json"
development.log.9-[Sat Jan 27 16:49:37 2018] [debug] Routing to controller "OpenCloset::Web::Controller::User" and action "auth"
development.log.9-[Sat Jan 27 16:49:37 2018] [debug] Routing to controller "OpenCloset::Web::Controller::API" and action "api_send_vbank_sms"
development.log.9:[Sat Jan 27 16:49:37 2018] [error] The payment agency failed to process
development.log.9-[Sat Jan 27 16:49:37 2018] [debug] 
development.log.9-[Sat Jan 27 16:49:37 2018] [debug] 500 Internal Server Error (0.323272s, 3.093/s)
```

**Comment by keedi** [comment]
`PUT /api/order/<order_id>/send-vbank-sms.json` 요청이 간헐적이지만, 한 번 발생하면 지속적으로 실패함을 확인할 수 있습니다. 원인이 무엇인지 더 살펴보겠습니다.

**Comment by keedi** [comment]
관련있는 해당 코드는 다음과 같습니다.

```
$ rgrep -n 'send-vbank-sms' lib
lib/OpenCloset/Web/Controller/API.pm:3161:    PUT /api/order/:id/send-vbank-sms
lib/OpenCloset/Web.pm:265:    $api->put('/order/:id/send-vbank-sms')->to('API#api_send_vbank_sms');
```

**Comment by keedi** [comment]
오류가 발생했음을 알려주는 코드는 `OpenCloset::Web::Controller::API` 모듈의 `api_send_vbank_sms()` 함수입니다. 이 중 `OpenCloset::Common::Unpaid::create_vbank()` 함수 호출 시 실패하고 발생하는 것으로 보입니다.

https://github.com/opencloset/opencloset/blob/14866c868aa89f652bb7b2615e08c03f10fc3684/lib/OpenCloset/Web/Controller/API.pm#L3198-L3202

**Comment by keedi** [comment]
현 시점 기준 `OpenCloset::Common::Unpaid` 모듈의 `create_vbank()` 함수 중 해당 오류를 출력하는 부분은 다음과 같습니다.

https://github.com/opencloset/OpenCloset-Common/blob/6a2546b9d303b7f5915030b1e2907bc213706750/lib/OpenCloset/Common/Unpaid.pm#L415-L419

`$iamport->create_prepare()` 함수가 호출시 적절한 `$json` 값을 반환 받지 못해 발생합니다.

**Comment by keedi** [comment]
`Iamport::REST::Client` 모듈 쪽 코드를 더 살펴봅니다.

```
$ rgrep -n create_prepare | vim -
lib/Iamport/REST/Client.pm:260:=head2 create_prepare( $merchant_uid, $amount )
lib/Iamport/REST/Client.pm:264:    my $json = $iamport->create_prepare($mercharnt_uid, $amount);
lib/Iamport/REST/Client.pm:268:sub create_prepare {
```

`Iamport::REST::Client` 모듈의 `create_prepare()` 메소드의 내용은 다음과 같습니다.

```perl
sub create_prepare {
    my ( $self, $merchant_uid, $amount ) = @_;
    return unless $merchant_uid;
    return unless $amount;

    my $url = "$IAMPORT_HOST/payments/prepare";
    return $self->post( $url, { merchant_uid => $merchant_uid, amount => $amount } );
}
```

코드상으로 보았을때 `post()` 메소드 호출 결과가 없는 것으로 보입니다. 해당 메소드는 다음과 같습니다.

```perl
sub post {
    my ( $self, $url, $body ) = @_;
    return unless $url;

    my $res = $self->{http}->post_form( $url, $body, { headers => { Authorization => $self->token } } );

    unless ( $res->{success} ) {
        warn "$res->{status}: $res->{reason}";
        return;
    }

    return $res->{content};
}
```

안타까운 점은 요청 성공시에는 json 값을 반환하나 요청 실패시에는 `undef`를 반환합니다.  요청 실패시에도 실패한 내역을 json으로 적절하게 조합해서 결과를 반환해야 해당 라이브러리를 사용하는 2차 코드에서도 오류 처리나 결과를 확인하기 더 용이할 것으로 보입니다.

어찌됐든 현 시점 기준 코드 보았을 때 Iamport로 요청하는 `/payments/prepare` 주소에 대한 요청이 실패하는 것으로 보입니다.  이 때 Iamport로 요청하는 인자가 잘못되었거나, 정말 Iamport 서버의 오류일 수 있는데, 사용자가 여러번 시도했을 때 어느 시점에 성공을 하는 것을 보면 인자가 잘못되었다기 보다는 Iamport 서버의 오류일 가능성이 높아보입니다.  다만 `post()` 메소드에서 실패한 결과를 json으로 반환하지 않아 실패 결과를 확인할 수 없는 점과, 상위 라이브러리 웹 앱에서 더 자세한 오류 로그를 기록하지 않기 때문에 확인은 필요할 것입니다.

로그를 최대한 자세하게 표현하고, 웹 쪽도 Iamport 서버 오류임을 주지시켜 사용자가 시스템의 문제가 아님을 인식하게 하고, 이 경우 어떻게 처리하는 것이 좋을지 고민하거나 Iamport에 문의할 수 있도록 유도하는 것이 필요할 듯 합니다.

**Comment by keedi** [comment]
본 이슈는 아임포트 서버의 문제로 보이며, 우리측에서 할 수 있는 것은 특별히 없습니다. 이미 관련해서 아임포트 서버의 문제가 있을 경우 예외처리 및 오류 표시를 하고 있으므로, 오동작하는 것은 아닙니다. 다만 사용자가 오해할 수 있으니, 오류 메시지를 조금 더 친절하게 변경하고, 추후 확인을 위해 로그를 더 자세하게 찍을 수 있도록 변경하는 선에서 마무리 짓겠습니다.

@pingpongworks 혹시 의문 사항이나 건의하실 부분 있으면 알려주세요.

**Comment by keedi** [comment]
오류 메시지를 다음과 같이 변경할 예정입니다.

![2018-02-05 17-50-30](https://user-images.githubusercontent.com/138451/35795912-23720abe-0a9e-11e8-828e-29811036e95c.png)

로그 콘솔에 출력하는 메시지는 다음과 변경할 예정입니다.

![2018-02-05 17-59-20](https://user-images.githubusercontent.com/138451/35796173-fff24ec2-0a9e-11e8-9dc6-9612fe3cf01b.png)

**Comment by keedi** [comment]
출력하는 오류 메시지만 바뀌지 변경되는 부분은 없습니다.

**Comment by pingpongworks** [comment]
내부적으로 오류가 발생했을 경우, 다시 한번 시도하도록 공유한 상태입니다. *시간차를 두고* 시도해야한다는 부분도 공유하도록 하겠습니다. 

오류의 원인이 아임포트 서버 문제임을 안내하는 오류메시지로 바뀌는 부분에 동의합니다. 오류가 생겼을 때 막연한 것보다는 처리방향을 알 수 있어서 좋을 듯 합니다.  

아임포트 서버 문제에 대해서 아임포트 쪽에 문의 루트를 제가 정확히 모르고 있어서, 이 부분은 @10001if 과 논의하겠습니다. 원인을 알려주셔서 감사합니다.

**Comment by keedi** [comment]
이슈 닫습니다.

**배포대기** 라벨이 붙어 있으면 작업은 완료되었지만 아직 실서버에 반영이 안되었다는 의미입니다. 이후 배포가 완료되면 이슈에 따라 **확인요망** 라벨을 붙이기도 하는데 실제 확인하신 후 해당 라벨을 제거하시면 됩니다. 지금의 경우는 항상 확인할 수 없는 이슈라 **확인요망** 라벨을 붙이지는 않을 예정입니다.

**Comment by keedi** [comment]
배포 완료했습니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다.

**Comment by jangbora** [comment]
저희쪽에서 API 호출 시도에 대한 모든 기록을 남기고 있습니다. 오류가 발생한 시간대를 알려주시면 문제의 원인을 찾는데 용이하지 않을까 생각됩니다. 

앞서 논의된 내용을 토대로 2018년 1월 27일 하루치를 검색해보았는데, 사용하시는 계정 / IP에서 올라온 요청 중에 500응답이 내려간 기록은 찾아내지 못하였습니다. 

1월 27자로 검색된 기록에 남아있는 시간 정보는 아래와 같습니다. 
[/payments/prepare]
| 2018-01-27 09:08:00 |
| 2018-01-27 09:22:39 |
| 2018-01-27 09:23:23 |
| 2018-01-27 09:29:15 |
| 2018-01-27 10:35:00 |
| 2018-01-27 10:35:00 |
| 2018-01-27 13:17:50 |
| 2018-01-27 13:43:32 |

[/vbanks]
| 2018-01-27 09:29:16 |
| 2018-01-27 10:35:00 |
| 2018-01-27 10:35:01 |

참고로 말씀드리자면, /vbanks 호출 전에는 /payments/prepare API로 정보를 등록하지 않으셔도 결제금액 위변조 이슈가 발생하지 않습니다. javascript SDK로 결제창을 통해 진행되는 경우에 해당되는 API입니다. (저희 개발 문서가 부족하여 오해를 드린 것 같습니다. )
