### ISSUE TITLE
쿠폰 별 발급 개수와 별개로 제한 개수를 설정함

### ISSUE THREAD

**Issue by keedi** [opencloset/opencloset#1408]
#1406 에서 본격적으로 나온 이야기입니다. 서울시 쿠폰의 경우 해당 기능을 고려하지 않았는데 중간에 나온 요청이라 어쩔수 없이 임시 방편으로 처리했지만, 이후 유사 사례가 늘고 있고, 현재는 서울시 쿠폰과 동일한 느낌으로 쿠폰을 사용하고 있는 바, 본 기능이 필수적으로 필요하다고 합니다.

> 10001if commented 5 hours ago •
> 
> 서울시 쿠폰용으로 만들어진 기능이라는 사실은 이해했습니다. 다만, 쿠폰 발급 수와 이용횟수를 동일하게 한다면 다음과 같은 문제가 발생합니다.
> 
> 예) 이용횟수 100회로 제한되어 있는 상황. 따라서 쿠폰도 100장을 발급.
> 
> 100장을 모두 소진하여 해당단체에서 쿠폰 추가 발행을 요청. 확인 해보니 발행된 쿠폰 100장이 모두 사용된 경우에는 쿠폰 추가발행을 하지 않음. 그러나 사용된 쿠폰이 100장 미만임. 그래서 쿠폰을 100장 더 발행하여 제공하기로 함.
> 
> 이렇게 되는 경우. 결과적으로 최초에 200장을 발행하는 것과 이후 추가 100장을 발행하는 것이 같은 효과를 가져오게 됩니다. 이 문제는 발행된 쿠폰 = 사용된 쿠폰 이라는 전제 없이는 성립하기 힘든데요. 애초에 사용된 쿠폰만을 정산하는 것으로 약정되어 있고, 쿠폰을 제공하는 모든 단체(서울시쿠폰-2017 제외)에 예산이 배정되어 있으므로 쿠폰 발행 수와 이용횟수에 차이가 발생하는 것은 필연적으로 발생하는 현상입니다.
> 
> 핵심은 쿠폰발행이 이용횟수에 초과하여 발행하는 것은 현재 상황에서 반드시 필요한 것으로 보이나 다만, 발행된 쿠폰이 이용횟수를 초과하여서는 안되므로 이용횟수 초과 시 쿠폰 대여가 이뤄질 수 없게 하거나 혹은 미리 그 정보를 숙지하여 관련 단체와 결론을 내는 행위가 필요합니다.
> 
> 정리하자면, 이용횟수가 정해져있고(예산이 확정되어 있는) 쿠폰 발행=쿠폰 사용이라는 조건이 성립하지 않는 이상 쿠폰발행 수 > 이용 횟수 가 발생하게 되는 것은 자연스럽고 일반적인 현상입니다. 따라서 이를 위해 적합한 문제 해결 방법이 필요합니다.

----

> keedi commented 19 minutes ago
> 
> 항상 상황이 동일하지는 않습니다.
> 
> 추가 발행 건에 대해서는 해당 단체가 결정하고 관리하는 것이라고 생각했었는데요. 즉 300장 발급한 상태에서 250장만 쓰고 50장은 남아있는 상태에서 추가 100장을 발급한다는 것은 150장이 쓰일 가능성이 있다는 것으로 이해 한 것이구요. 그런데 지금 상황은 300장 발급에서 250장만 쓴 상태에서는 50장은 쓸지 안쓸지 모르겠고, 여러가지 이유에서 정말 150장을 더쓰길 바라는 마음에서 추가 100장을 발급한다고 보기보다는 안 쓴 50장은 앞으로도 안 쓸 것 같으니 정말 100장을 쓰리라는 가능성을 가지고 발급 요청하는 것이죠. 무슨차이냐면, 원래 쿠폰은 해당 단체나 나눠주는 열린옷장에서 직접 관리를 하리라고 가정하고 만든 기능인데, (그래서 쿠폰 자체는 단순하게 유효한 쿠폰 생성 및 해당 쿠폰의 유효성 검증 정도로만 이루어져있습니다.) 다시 그 관리라는 부분이 시스템으로 넘어온 것이죠.
> 
> 어떻게 쓰냐에 따라 다른데요. 쿠폰 자체가 정말 의미를 가지는 문화 상품권 또는 백화점 상품권 사용한다면 쿠폰 발행수가 이용 횟수보다 많거나 같은 상황은 의미가 없습니다. 어짜피 사용가능한 유효한 쿠폰을 발급한 것이고 가져오면 사용할 수 있으니 재화와 같은 것이죠. 지금은 쿠폰 자체를 마트나 쇼핑몰 할인 코드처럼 사용하는 느낌이구요. 저희는 전자를 생각하고 구현한 것이나 현재 후자를 생각하거나, 후자처럼 사용되고 있으니 어쩔 수 없네요.
> 
> 이렇게 되면 당장 쿠폰 생성에서부터 이를 고려하지 않은 부분이 나타납니다.
> 
> 예를 들어 현재 등록된 쿠폰의 종류는 다음과 같은데요.
> 
> - 10bob
> - anyangyouth
> - gwanak
> - hanshin_univ
> - incheonjob
> - linkstart
> - seoul
> 
> seoul의 경우 제일 골치가 아픈 케이스인데, 일단 차치하고, 기존 등록건도 그렇고 이번에 요청하시는 건인 gunpoyouth도 그렇고 1번 이상 사용함을 고려하지 않은 것이 보입니다. 즉, 개수 제한을 하는 한 기간(term)의 쿠폰은 그 이후 기간(term)의 쿠폰과 구분을 할 수 있어야 하는데, 일단은 전혀 그런 것이 보이지 않죠. 말이 어려운데 정리하면 군포시 쿠폰을 예로 들면, gunpoyouth로 5월까지 개수 제한을 걸었다고 친다면, 6월부터 발급하는 군포시 쿠폰은 gunpoyouth라는 이름으로 발급하면 안됩니다. 즉 다른 이름이어야 하고 이부분은 염두해서 관리해주셔야 합니다. 일선에서는 추가 발급이라고 생각할 수 있으나, 기간(term)이 달라지면, 아예 다른 쿠폰이 되는 것입니다. 5월까지 개수 제한을 건 상태에서 4~5월에 추가로 발급하는 것은 기존 것과 동일한 쿠폰이겠죠. 그동안 이런 개념없이(필요가 없었다고 생각했었습니다만) 사용했었는데, 이제는 말씀하신 기능을 넣으려면 필연적일 것 같습니다.
> 
> 앞으로는 새로운 term에 대한 쿠폰 생성 또는 기존 term에 대한 쿠폰 추가에 대해서는 반드시 쿠폰 명과 쿠폰 아이디 및 해당 기간에 대한 누적 제한(limit) 수를 결정해서 알려주셔야 할 것 같습니다. 저희는 쿠폰 아이디를 보고 이것이 추가 발급인지 새로운 기간(term)에 대한 발급인지를 판단할 수 있을 것 같네요.

----

> keedi commented 6 minutes ago
> 
> 적절한 요청 형식은 다음과 같을 것 같습니다.
> 
> ```
> 제목: 쿠폰: busan007 800건 발급 및 200건 제한
> 
> 아이디: busan007
> 이름: 부산시 취업 지원
> 제한: 200
> 발급: 800
> 유형: suit
> 사용기간: 2018-12-31
> ```
> 
> 상기 기준 제한은 200개 그대로이고 500건 추가 발급한다면 다음과 같은 형식이 될 것입니다. 이 때 총 발급량은 1300건이 됩니다.
> 
> ```
> 제목: 쿠폰: busan007 500건 추가 발급 및 200건 제한
> 
> 아이디: busan007
> 이름: 부산시 취업 지원
> 제한: 200
> 발급: 500
> 유형: suit
> 사용기간: 2018-12-31
> ```
> 
> 상기 기준 제한을 500개로 변경하면서 200건 추가 발급한다면 다음과 같은 형식이 될 것입니다. 이 때 총 발급량은 1500건이 됩니다.
> 
> ```
> 제목: 쿠폰: busan007 200건 추가 발급 및 500건 제한
> 
> 아이디: busan007
> 이름: 부산시 취업 지원
> 제한: 500
> 발급: 200
> 유형: suit
> 사용기간: 2018-12-31
> ```
> 
> 별도의 쿠폰 생성시는 별도의 쿠폰 아이디를 명시해야겠죠. 또한 쿠폰 이름을 별도의 쿠폰 아이디별로 다르게 하지 않는다면 시스템에서는 동일한 명칭으로 보여주니 이점도 고려하셔야 할테구요.

**Comment by keedi** [comment]
`coupon_limit` 항목이 추가된 `OpenCloset::Schema` 모듈 0.056 버전이 릴리스 되었습니다. 해당 모듈을 사용해서 쿠폰 사용 개수를 제한할 수 있도록 기능을 수정합니다.

**Comment by keedi** [comment]
쿠폰을 사용해 주문 확정을 하는 시점에 제한 개수를 초과하는 쿠폰의 경우 다음과 같은 오류 메시지를 출력하며 더 진행하지 않도록 합니다. 담당자는 오류 메시지를 확인한 후 대여자에게 해당 사실을 설명해야 할 것입니다.

![screenshot-keedi kim 10301-2018-02-12-03-01-35](https://user-images.githubusercontent.com/138451/36076567-2417c280-0fa1-11e8-8c50-1265a9298ea3.png)

**Comment by keedi** [comment]
하지만 이미 등록한 쿠폰을 제거하는 방법과 관련한 논의가 이루어진 적이 없기 때문에 아마도 제한 개수를 초과하는 이용자의 경우 쿠폰 제한을 초과해서 대여는 막아질 것이나, 해당 주문서의 쿠폰을 제거하고 다른 결제 수단을 이용해서 결제하는 방법은 UI적으로 없기 때문에 아마도 그 시점에 어찌해야 하나 당황하는 상황은 생길 수 있을 것 같네요. 관련해서는 별도의 요청이나 이슈 제기가 있으면 그때 처리합니다.

![screenshot-keedi kim 10301-2018-02-12-03-14-58](https://user-images.githubusercontent.com/138451/36076716-6b8900fa-0fa3-11e8-8b1a-d5962630084a.png)

**Comment by keedi** [comment]
구현 완료했습니다.

본 기능을 위해 `coupon_limit` 테이블이 추가되었으며 `OpenCloset::Schema` 모듈은 0.056 버전으로 `OpenCloset::API` 모듈은 v0.1.2 버전으로 업데이트 되었습니다.

**Comment by keedi** [comment]
서버에 배포 완료했습니다.

**Comment by keedi** [comment]
이슈 닫습니다.

**Comment by 10001if** [comment]
추후에 문제가 발생하면 다른 이슈를 통해 기록 하겠습니다. 감사합니다.
