### ISSUE TITLE
쿠폰: gunpo201801 통계 페이지

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1412]
gunpo201801에 대한 통계 페이지 생성을 요청드립니다.

해당 단체에서는 온-오프라인이 통합된 페이지만 로그인 없이 확인 할 수 있도록 요청드립니다.
그러나 온/오프라인은 정산 금액이 다르기 때문에 열린옷장측에서는 이용자의 구분이 필요합니다. 
/stat/events/gunpo201801
/stat/events/gunpo201801?online=1
/stat/events/gunpo201801?online=0
따라서 총합 / 온라인 / 오프라인 으로 나뉘어진 통계 페이지를 요청드립니다.

정리하자면
1. 로그인 없이 다음 페이지를 확인 할 수 있어야 함. /stat/events/gunpo201801
2. /stat/events/gunpo201801?online=1, /stat/events/gunpo201801?online=0 의 2 페이지를 추가로 확인 할 수 있어야 함.
3. 내용은 아래 그림과 같은 형태로 진행하되, 현재처럼 월간/일간 두 지표를 함께 볼 수 있어야 함.

![2018-02-12 9 47 56](https://user-images.githubusercontent.com/4696328/36080837-f88b7722-0fd9-11e8-86fe-4a9f1eb503ad.png)

![2018-02-12 9 50 09](https://user-images.githubusercontent.com/4696328/36080853-2fc7c038-0fda-11e8-986b-0fadfe735950.png)

**Comment by aanoaa** [comment]
제가 작업하겠습니다.
쿠폰이 새로 발급되면 통계와 관련되어서 몇가지 작업을 해주어야 하는데
기존에 했던 작업의 반복수준입니다.

이번 이슈를 진행하면서 다시 한번 자세하게 남기도록 하겠습니다.

**Comment by aanoaa** [comment]
새로운 쿠폰이 발급되고 나면 하루 한번 일일 사용(방문)수 를 수집하는 cron job 을 [OpenCloset::Cron::Visitor](https://github.com/opencloset/OpenCloset-Cron-Visitor) 에 추가해야 합니다.

1. OpenCloset::Cron::Visitor 에 수집할 수 있는 함수를 추가하고,
2. `opencloset-cron-visitor.pl` 에서 담당하는 worker 를 늘려줍니다.
3. 버전을 올려서 배포하고
4. 서버에 설치한 후 서비스 재시작

통계한 한번 수집되고 난 이후부터는

/stat/events/:name # 전체
/stat/events/:name?online=1 # 온라인만
/stat/events/:name?online=0 # 오프라인만

주소에서 확인할 수 있습니다.

**Comment by aanoaa** [comment]
이 경우에는 누락된 통계의 데이터를 직접넣어줘야 하는 작업도 필요합니다.

**Comment by aanoaa** [comment]
자세한 코드입니다.

https://github.com/opencloset/OpenCloset-Cron-Visitor/commit/cfb3d8695719947096ae885c8df7e8b8383e226e

**Comment by aanoaa** [comment]
비어있는 통계는 https://github.com/opencloset/OpenCloset-Cron-Visitor/issues/5#issuecomment-300706625 를 참고해서 기간과 이벤트명을 조금 수정해서 적용할 수 있습니다.

**Comment by aanoaa** [comment]
아래 스크립트를 돌려서 2018-02-01 ~ 2018-02-21 까지의 누락된 통계를 넣어주었습니다.

```perl
use strict;
use warnings;
use DateTime;

use OpenCloset::Schema;
use OpenCloset::Cron::Visitor qw/event_gunpo/;

my $schema = OpenCloset::Schema->connect({ ... });

our $TZ = 'Asia/Seoul';
my $today = DateTime->today( time_zone => $TZ );
my $start = DateTime->new(
    year      => 2018,
    month     => 2,
    day       => 1,
    time_zone => $TZ
);
my $end = $today->clone->subtract( days => 1 );
my $date = $start->clone;
while ( $date <= $end ) {
    my $count = event_gunpo( $schema, $date );
    for my $key (qw/offline online/) {
        my $stat = $count->{$key};
        my $online = $key eq 'online' ? 1 : 0;
        $schema->resultset('Visitor')->create(
            {
                date           => "$date",
                online         => $online,
                visited        => $stat->{male}{visited} + $stat->{female}{visited},
                visited_male   => $stat->{male}{visited},
                visited_female => $stat->{female}{visited},
                visited_age_10 => $stat->{10}{visited},
                visited_age_20 => $stat->{20}{visited},
                visited_age_30 => $stat->{30}{visited},

                unvisited        => $stat->{male}{unvisited} + $stat->{female}{unvisited},
                unvisited_male   => $stat->{male}{unvisited},
                unvisited_female => $stat->{female}{unvisited},
                unvisited_age_10 => $stat->{10}{unvisited},
                unvisited_age_20 => $stat->{20}{unvisited},
                unvisited_age_30 => $stat->{30}{unvisited},

                event => 'gunpo',
            }
        );
    }

    $date->add( days => 1 );
}
```

**Comment by aanoaa** [comment]
https://staff.theopencloset.net/stat/events/gunpo

**Comment by aanoaa** [comment]
인증없이 볼 수 있는 public 주소는 따로 알려드리도록 하겠습니다.

**Comment by aanoaa** [comment]
오늘 이후부터 제대로 수집하는지 확인이 되면 닫도록 하겠습니다.

**Comment by aanoaa** [comment]
한건도 안쓴것이 맞나요?

**Comment by 10001if** [comment]
네! 아직 시행 전이라 사용 한 적이 없습니다. 3월 초부터 시작 예정입니다.

**Comment by aanoaa** [comment]
어제 날짜의 데이터가 들어가 있는 것을 확인했습니다.

**Comment by 10001if** [comment]
@aanoaa 아직 한명도 이용하지 않아 확인이 되지 않겠지만, 공개 URL 메일로 전달 부탁드릴게요~
