### ISSUE TITLE
anyang201801 쿠폰 사용시 사용 개수 제한이 발생함

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1413]
https://github.com/opencloset/opencloset/issues/1364
https://github.com/opencloset/opencloset/issues/1408

를 확인하였습니다.

@keedi 현재 안양시 쿠폰명은 anyangyouth 인데, anyang201801 로 수정해야 하는 것인가요?

![_20180212_121155_1](https://user-images.githubusercontent.com/4696328/36083030-156ef19e-0ff2-11e8-926e-009abab42251.jpg)

쿠폰 제한기능으로 인해 쿠폰 이용을 하지 못했다는 연락이 왔습니다. 

2018년 안양시 쿠폰 이용의 경우에는 발행은 300개를 하였습니다. 위와 같은 에러메세지가 나타나는 것은 제한 수를 추과했기 때문인가요? 그렇다면 제한 수를 조정하는 것이 필요합니다. 

2017년의 정산은 완료되었고
2018년의 계약은 새로이 시작되기 때문에 2018년의 총 이용자는 (예상) 300회 입니다. 하지만 1월에 56명 2월에 36명이 사용 중입니다. 따라서 208회의 여유가 남아 있습니다. 300회 까지 사용할 수 있도록 제한 수가 조정되어야 합니다.

2018년 안양 쿠폰 사용자가 이용 가능하도록 수정을 요청드립니다.

**Comment by keedi** [comment]
발행 제한과 관련 값이 달라질 때마다 쿠폰의 이름(아이디)이 달라져야 합니다.

몇월 몇일 부터 발행한 쿠폰의 이름이 어떻게 되야하는지 해당 쿠폰의 사용 횟수 제한은 어찌되는지 알려주세요.

**Comment by keedi** [comment]
더불어 현재 제한을 원하는 쿠폰 발급을 요청하셨던 이슈 번호도 알려주세요.

**Comment by 10001if** [comment]
https://github.com/opencloset/opencloset/issues/1364

이슈이구요. 2017년 12월 4일 경 anyangyouth 로 발행하였습니다.

해당 쿠폰 사용횟수 제한은 340회 입니다. 확인 부탁드리겠습니다.

**Comment by keedi** [comment]
해당 이슈에서 쿠폰 관련 정보 이야기를 나누시지요. #1364 에서 쿠폰과 관련한 변경사항 작업이 끝나면 다시 이곳에서는 변경된 내용을 바탕으로 상기 제기되었던 주문서가 정상 처리되는지 확인하면 됩니다.

**Comment by keedi** [comment]
우선 지금까지 변경한대로라면 오늘 발생했던 안양시 쿠폰 사용시 개수 제한 오류가 발생한 부분이 해결되었습니다. 해당 주문서 처리하실 수 있으면 진행해주시면 되구요. 혹시라도 예상과 다르게 오동작하는 부분이 있다면 본 이슈에 바로 알려주세요.

**Comment by keedi** [comment]
> @keedi 현재 안양시 쿠폰명은 anyangyouth 인데, anyang201801 로 수정해야 하는 것인가요?

네, 이미 충분히 대화를 나눠서 인지하셨을텐데, 수정해야 한다기 보다는 정확하게는 수정을 요청하셨기 때문에 이제 2017년 12월 기점으로 안양시 쿠폰은 일단은(영원히는 아니니까요) `anyang201801` 이 되겠지요. 관련 결정은 열린옷장에서 하는 것입니다. 그래서 제목과 내용을 명확하게 요청드리는 점입니다. 이런 부분은 저희가 판단하기가 어렵기 때문에 세세하게 명시해주시기를 부탁드리는 부분이 있습니다.

**Comment by keedi** [comment]
92452 상기 주문서 쿠폰 사용 문제 없이 해결되었나요? 아니면 다른 문제가 더 있는지요?

**Comment by 10001if** [comment]
@keedi 문제 없이 해결되었고 다른 문제가 없었습니다.

**Comment by keedi** [comment]
특별한 후속 문제가 없으므로 이슈 닫습니다.
