### ISSUE TITLE
주문서 반납 확인 메모의 가독성을 높이고 첫 화면에서 열람 가능하게 함

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1415]
![default](https://user-images.githubusercontent.com/17288038/36659562-3748d0ce-1b18-11e8-9b0e-8f04372b00bf.JPG)

- 반납시 꼭 확인이 필요한 내용들을 주문서 반납확인메모에 적어 놓고 있는데요, 
현재의 반납확인메모가 가독성이 떨어져 급하게 반납처리를 하다보면 놓치는 경우가 있습니다.  
- 최근 서울시 쿠폰 때문에 환불, 신분증 확인 등의 이슈가 걸려서 반납확인메모의 중요성이 높아졌습니다. 
- 놓치는 경우를 방지할 수 있도록 주문서 들어가기 전에도 반납확인메모를 인지할 수 있고, 주문서 들어가서도 눈에 잘 띄면 좋겠습니다. 아래와 같이 수정 요청드립니다. 

**[주문서 들어가기 전에 '반납확인메모' 삽입]**
![2](https://user-images.githubusercontent.com/17288038/36661115-b94a4882-1b1d-11e8-8431-337e2874552f.JPG)

**[주문서 들어간 후 잘 보이도록 바의 컬러와 글자 크기 및 볼드 수정]**
![default](https://user-images.githubusercontent.com/17288038/36661133-cb8a44b6-1b1d-11e8-884f-174a652064c8.JPG)

**Comment by keedi** [comment]
> **[주문서 들어가기 전에 '반납확인메모' 삽입]**
> ![2](https://user-images.githubusercontent.com/17288038/36661115-b94a4882-1b1d-11e8-8431-337e2874552f.JPG)

주문서 목록에 삽입해달라는 상기 부분의 경우 이미 반납 확인 메모가 있을 경우 비고 란에 표시하고 있습니다. 그럼에도 불구하고 필요한 기능이신지요?

![screenshot-staff theopencloset net local 10301-2018-03-02-12-03-50](https://user-images.githubusercontent.com/138451/36881529-eba7853c-1e11-11e8-8281-d212933c578a.png)

**Comment by keedi** [comment]
그리고 상기 화면 캡쳐하신 부분을 보면 주문서 목록이 아니라 **첫 화면**의 의류 바코드 찍은 후 목록 페이지 입니다. 주문서 목록 페이지 말고 **첫 화면**에서 반납 확인 메모를 확인하시고 싶다는 의미인가요?

**Comment by keedi** [comment]
변경된 화면은 다음과 같습니다.

주문서 상세 페이지입니다.
![screenshot-staff theopencloset net local 10301-2018-03-02-12-23-39](https://user-images.githubusercontent.com/138451/36882268-2a161d48-1e16-11e8-9cbc-9e3bb860aa66.png)

첫 화면입니다.
![screenshot-staff theopencloset net local 10301-2018-03-02-12-24-57](https://user-images.githubusercontent.com/138451/36882271-2e17c69e-1e16-11e8-9355-df2c76468897.png)

**Comment by keedi** [comment]
#1405 작업으로 인해 현재 브랜치에서 서비스 중입니다. 배포를 위해서는 rebase 및 강제 pull 등이 필요하기 때문에 가능하면 저녁 마감 시간 이후에 배포할 예정입니다.

**Comment by keedi** [comment]
작업 완료했습니다. 화면 캡쳐 기준으로 피드백이 있으시다면 이슈 다시 열고 커멘트 달아주세요. 금일 배포 완료 후 관련해 변경 사항은 별도의 이슈를 열어주세요.

**Comment by pingpongworks** [comment]
@keedi  첫 화면 맞습니다. 필요한 작업 그대로 해주셨습니다. 감사합니다^^

**Comment by keedi** [comment]
배포 완료되었습니다.

**Comment by pingpongworks** [comment]
확인했습니다. 감사합니다^^

**Comment by pingpongworks** [comment]
@keedi 제가 테스트해보고 확인한 경우에는 `확인요망`라벨 제거하면 되나요? 아니면 그냥 두면 되나요?
