### ISSUE TITLE
연장중 주문서 목록 열람시 특정일이 아닌 전체를 열람하게 함

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1416]
**현재 수지니 주문서에서 `연장중`을 누르면 다음과 같이  /order?status=extension 로 이동이 됩니다.**

![default](https://user-images.githubusercontent.com/17288038/36708271-94b670c0-1bb5-11e8-9140-3a4d8e0b09fd.JPG)

**현재의 URL에는 예약일이 입력되어 있지 않아 연장 주문서가 보이지 않습니다.
/order?booking_ymd=all&status=extension 로 수정이 필요합니다.**

현재 7일 이상 연장 중인 주문서가 8건 있는데, 주문서가 보이지 않아 관리를 하지 못하고 있습니다. 
url 주소 수정 부탁드립니다~ @keedi

**Comment by keedi** [comment]
원래는 특정 날짜의 목록을 보는 것을 원하셨기 때문에 전체를 보려면 모든 항목에 다 수기로 `&booking_ymd=all`을 붙여야 하는데, 수정했었나보네요? 요구사항이 있었었나봅니다. 흠. 일단 원하시는대로 고쳐질때까지는 주소 끝에 `&booking_ymd=all` 을 붙여서 사용하시면 됩니다.

**Comment by pingpongworks** [comment]
네~ 알겠습니다. 감사합니다^^

**Comment by keedi** [comment]
어라? 마일스톤을 변경하신 이유가 있으신가요?

번호가 낮을 수록 처리 순서가 앞으로 당겨진다는 의미입니다만... 일단 작업중이므로 다시 변경해놓겠습니다.

**Comment by keedi** [comment]
작업 완료했습니다.

#1405 작업으로 인해 현재 브랜치에서 서비스 중입니다. 배포를 위해서는 rebase 및 강제 pull 등이 필요하기 때문에 가능하면 저녁 마감 시간 이후에 배포할 예정입니다.

**Comment by pingpongworks** [comment]
@keedi 아, 제가 마일스톤 변경한 적이 없는데요? 마일스톤은 전혀 감이 없어서 손대고 있지 않거든요^^ 배포된 후 확인해보겠습니다. 감사합니다^^

**Comment by keedi** [comment]
배포 완료 되었습니다.
