### ISSUE TITLE
시간표에서 15개의 탈의실을 지원함

### ISSUE THREAD

**Issue by keedi** [opencloset/opencloset#1419]
https://github.com/opencloset/monitor/issues/172

@pingpongworks wrote:

> 주말에 메일로 공유드린 바와 같이 3월 2일 오후부터 5층 대여공간과 방식에 변화가 생겼습니다. 
> 탈의실이 4개 보강되어 15개로 늘어난 바 
> 다음과 같이 preparation 화면의 탈의실 수와 위치 조정을 요청합니다. 
> 
> ![image](https://user-images.githubusercontent.com/17288038/36895075-e88bbc94-1e50-11e8-8e05-6ba9f9ab80cf.png)
> 
> @aanoaa 정말 크고 좋은 탈의실 4개가 더 들어왔는데 번호가 없어서 사용하지 못하고 있어요ㅠㅠ 가능하면 빠른 작업 부탁드릴게요~

**Comment by keedi** [comment]
가능하면 커밋시 이슈 생성 후 연결 부탁드립니다.

**Comment by keedi** [comment]
9fa7cd8c26c0695068a108c45eaf7431cc9cbc8a

**Comment by keedi** [comment]
서버에 배포 완료 했습니다.

**Comment by keedi** [comment]
시간표에서 새로고침 후 상태변경을 시도하면 탈의실 15까지 보일 것입니다.

**Comment by keedi** [comment]
데이터베이스 상에는 탈의실이 20개까지 선 입력을 했으므로 데이터베이스 상 수정할 내용은 없습니다.

**Comment by pingpongworks** [comment]
preparation과 dashboard, 시간표에서 문제없이 잘 작동했다고 근무자가 확인해주었습니다. 빠르게 작업해주셔서 감사드립니다^^
