### ISSUE TITLE
서울시 쿠폰 이용자가 구두/타이만 대여할 경우 의류준비로 바로 넘어가는 것을 막을 수 있는 방법이 필요함

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1420]
현재 구두/타이만 대여하는 경우, 방문예약확인을 하면 치수측정 단계를 건너뛰고 의류준비로 바로 넘어오도록 기능 설정이 되어 있습니다. 

올해 모든 서울시쿠폰 예약자는 이용대장 기입을 해야하므로 치수측정 단계를 건너뛰면 안되는 상황으로 바뀌었습니다. 

    구두/타이만 대여하는 예약자 중, 
    서울시쿠폰 이용자의 경우에는
    의류준비로 바로 넘어가지 않도록
    수정 부탁드립니다. 

@keedi 모니터 이슈인지, 스태프 이슈인지 판단을 잘 못하겠어서 일단 스태프에 올렸습니다.

**Comment by keedi** [comment]
쿠폰이 연관되는 경우는 번거로우셔도 쿠폰 라벨 선택 부탁드립니다.

말씀하신 내용 우선 확인하고 내용 정리하겠습니다.

**Comment by keedi** [comment]
#1068 이슈 확인 부탁드립니다.

제가 당시 처리하고 완료한 내역을 제대로 이해한 것이 맞다면, 자동으로 넘어가지는 않습니다. 담당자가 화면에서 버튼 클릭을 할 때만 넘어갑니다.

![screenshot-monster silex kr 10301-2017-02-15-21-23-09](https://cloud.githubusercontent.com/assets/138451/22975006/575106de-f3c8-11e6-9e16-55bfcb9759a4.png)

버튼 자체가 의류준비로 넘기는 기능인데 이 버튼을 누르지 않으면 되는 것 아닌지요? 일단 상기 이슈 확인해주시고 자세히 상황 설명 부탁드립니다. 또는 이 문제가 아니라 상기 이슈와 별개의 상황이라면, 해당하는 내용도 설명 부탁드립니다.

**Comment by pingpongworks** [comment]
@keedi 저도 올리기 전에 #1068 이슈확인해보았습니다. 이 이슈는 무인예약확인으로 바뀌기 전의 버전입니다. 

이후에 무인 예약확인 컴퓨터가 생기면서 스태프가 예약확인을 할 필요가 없이 대여자가 직접 방문예약확인을 하게 되었기 때문에, 대여자가 예약확인을 하면 자동으로 의류준비로 넘어가도록 바뀌었습니다. 

아마도 최종적인 내용이 git에 정리가 되어 있지 않거나, 못 찾았거나 인 거 같습니다. 

저도 이 이슈를 보고 혹시나 싶어서 제 이름으로 구두만 대여하는 예약을 해서 확인해보았는데, 현재 위의 `대여`화면에서 넘기는 기능은 구현되어있지 않습니다.

**Comment by keedi** [comment]
그러면 확인하자면, 현재 무인 예약 단말기에서 예약확인을 했을때 구두나 타이를 대여하는 대여자의 경우 직원의 개입이 전혀 없이 바로 의류 준비로 넘어가는데, 이것 자체는 원하는(의도된) 동작이지만, 서울시 쿠폰 사용자의 경우 이렇게 바로 넘어가면 곤란하다는 말씀이신지요?

**Comment by pingpongworks** [comment]
@keedi 네! 그렇습니다.

**Comment by keedi** [comment]
번거로우시겠지만 본 이슈를 monitor에 새로 등록해주셔야 할 것 같습니다. 처음에는 staff 화면에서 버튼을 눌러서 상태를 변경하는 이슈라고 생각했는데 말씀하신 것처럼 무인 예약 이후는 당시 구현한 버튼을 사용하지 않으시는 것 같네요. 따라서 monitor 쪽 이슈에 등록 부탁드립니다. 등록 이후 본 이슈는 직접 닫아주시면 됩니다.

**Comment by pingpongworks** [comment]
네~ 알겠습니다. 모니터로 이동하겠습니다^^

**Comment by keedi** [comment]
https://github.com/opencloset/monitor/issues/175
