### ISSUE TITLE
쿠폰: anyang201801 제한 해제

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#1425]
아이디: anyang201801
이름: anyang201801
발급: 300
제한: 300
유형: suit
사용기간: 2018-12-31

으로 설정되어 있는 anyang201801 쿠폰의 제한 개수 삭제를 요청드립니다.

안양시에서 추경예산 편성을 통해 2018년 한 해 동안은 이용이 문제 없도록 한다는 답변을 받았습니다.
따라서, 2018년에 사용한 쿠폰 수를 모두 정산받을 수 있을 것으로 예상되므로

현재 설정되어 있는 제한 기능은 삭제해주시기 바랍니다.

**Comment by keedi** [comment]
#1406 에 따르면 800건 발급에 200건 제한이었는데 300/300으로 표시하셨는데 변경이 있었나요? 헷갈리는데 확인 부탁드립니다.

**Comment by keedi** [comment]
아 아닙니다 일단 제가 안양시와 군포시를 헷갈렸군요. 다시 확인하겠습니다.

**Comment by keedi** [comment]
헷갈렸습니다. 관련 이슈는 #1364 입니다.

**Comment by keedi** [comment]
제한을 삭제해달라고 하셨는데 현재 안양시 쿠폰의 경우 300개 발급에 300개 제한입니다. 제한을 해제해도 발급은 300건이기 때문에 300건 까지 밖에 쓸 수 없습니다. 제한 개수를 해제해달라고 하셨으니 해제는 할 수 있는데 이 점은 인지하고 계신 것인지요?

**Comment by 10001if** [comment]
네, 사실 저도 좀 헷갈렸던 것 같아요. 300개 제한이 없어진다고 해도 실질적으로 달라지는 건 없겠네요. 제한 삭제 요청은 없는 것으로 정정 하겠습니다. 알려주셔서 감사해요. 이후에 추가 발급이 있을 때 그때에 맞게 재요청 하도록 하겠습니다. ^^

**Comment by keedi** [comment]
아닙니다. 제한을 삭제하는 것은 삭제하는 나름대로 의미가 있습니다. 이후 추가 발급을 100개 했을 때 여전히 제한이 300개라면 발급은 총 400개라도 제한은 300개니까요. 제한을 이 때는 더 늘리고 싶다면 300개 이상으로 설정하던가 해야 합니다. 제한을 제거한다면 이후 발급한 만큼 사용할 수 있는 것이구요.

다만 말씀드리고 싶었던 것은 제한 개수를 삭제 해달라는 요청이 제한을 삭제한다고 발급 개수 이상을 쓸 수 있다는 의미는 아니므로 명확하게 이해하신 것인지 확인하기 위해 기록한 것입니다.

**Comment by 10001if** [comment]
@keedi 그렇군요. 제한 개수 삭제의 의미에 대해 더 정확하게 이해했습니다~ 그리고 발급 개수를 초과하여 사용할 수 없다는 것은 인지하고 있습니다. 그럼 제한 삭제 요청은 그대로 진행 부탁드리겠습니다.

**Comment by keedi** [comment]
알겠습니다.

**Comment by keedi** [comment]
쿠폰이 서울시와 그외의 쿠폰, 그리고 제한이 있는 쿠폰 세 종류로 파편화 되어 관련해 내용을 숙지하는데 시간이 걸렸습니다. 일단 내용을 정리하면 다음과 같습니다.

현재 서울시 쿠폰을 제외하고는 선 발급 시스템입니다. 선 발급을 했으므로 기존 300건은 해당 사업 주관 단체에게 전달을 한 것이며, 따라서 발급건과 관련해 300건은 물리적으로 정해진 상태입니다. 이 상태에서 300건이 별도로 제한이 걸려있는데, 이는 `coupon_limit.limit` 값에 설정해서 결정합니다. 쿠폰 제한을 해제하려면 이 값을 `-1`로 설정해야 합니다. 물론 현재 이 값을 `0`이나 `NULL`로 설정해도 쿠폰 제한이 걸리지는 않습니다. 정확히 말하면 `0`과 `NULL` 값일 경우 제한이 걸리지 않는 것은 기존 쿠폰의 호환성을 위해 추가한 기능이며, 이 값을 사용할 경우 아예 쿠폰 제한 루틴으로 진입하지 않습니다. `-1`의 경우 조금 다르게 명시적으로 값을 설정하는 것이며 이 때는 쿠폰 제한 루틴으로 진입은 하지만 개수 제한이 없는 것으로 인지하고 이후 루틴을 진행합니다. 결과적으로는 동일하지만 미세한 차이는 있습니다.

값을 `0`으로 설정할 경우 이것이 아예 0개를 의미하는 것인지 제한이 없는 것인지 헷갈릴 여지가 있으므로 가능하면 신규 쿠폰 부터는 제한이 없는 경우 명시적으로 `-1`로 설정해서 이해하기 수월하도록 합니다.

**Comment by keedi** [comment]
다음 명령으로 쿠폰의 제한 개수 설정을 해제했습니다.

```sql
UPDATE coupon_limit set `limit`=-1, update_date=NOW() WHERE cid='anyang201801';
```

**Comment by keedi** [comment]
이슈 닫습니다.
