### ISSUE TITLE
과거 주문서의 착용일이, 최종 대여했던 착용일로 바뀌는 오류

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1426]
![default](https://user-images.githubusercontent.com/17288038/37829368-1c6563a2-2ee2-11e8-83c9-20aa510042db.jpg)
 
`orders/47873`의 주문서에서 보여지는 바와 같이 
2016년 12월의 주문서인데, 최근 대여했던 2018년 3월 23일로 착용일이 변경되어 있습니다. 
여러번 대여했던 사용자의 다른 주문서들에서도 같은 현상이 확인되었습니다. 

모든 주문서의 착용일이 최종 대여했던 주문서의 착용일로 덮어씌워지는 듯 합니다. 
오류 수정 부탁드립니다.

**Comment by aanoaa** [comment]
주문서의 착용일과 사용자정보의 착용일이 있는데, 사용자정보의 착용일을 주문서에서 나타내고 있습니다.
2017-05-30 이후에는 주문서에 의류착용일을 입력하고 있지 않았습니다.
관련된 내용을 이슈에서도 찾지 못하겠습니다. #1277 을 진행하면서 빠트린 부분이 아닌가 싶습니다.

의류착용일은 방문예약할때에 선택하는 값이니까 방문예약할때에 의류착용일을 주문서에 기록하고,
주문서에서는 사용자정보의 의류착용일 대신에 주문서의 의류착용일을 나타내면 될 것 같습니다.

**Comment by aanoaa** [comment]
staff 와 visit 양쪽 서비스에 적용되어야 합니다.

    $ closetpan OpenCloset::API

**Comment by keedi** [comment]
배포 완료 했으며 이슈 닫습니다.
