### ISSUE TITLE
연체/연장료가 0원인데 납부방법이 미납인 경우 미납 라벨 제거

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1427]
#1426 에서 언급했던 `orders/47873 `의 주문서에는 또 하나의 오류가 있습니다. 

정확한 상황은 알 수 없으나, 미납금이 없는데 이름 옆에 `미납`으로 표시되어 있습니다. 

원래 미납금이 있었는데, 뭔가 잘못된 조치로 금액만 없어진 건지 현재로서는 원인파악을 정확히 알  수 없습니다. 

원인에 대해서는 같은 상황이 또 발견된다면 자세히 파악해보겠습니다. 

일단 부탁드리고 싶은 것은 대여하러 방문할 때마다 `미납`때문에 논란이 되지 않도록 미납 버튼 삭제 요청 드립니다. 

현재 프로그램에서는 완납으로 처리할 방법을 못 찾았겠습니다.

**Comment by aanoaa** [comment]
미납인지 아닌지 판별하는 것은 주문서에 `연체/연장료 결제방법` 에 `미납` 이라고 적혀있는지를 보는 것 입니다.
실제로 이 주문서의 경우 `미납`으로 적혀있습니다.
하지만 연체/연장료를 계산해보면 `0`원 입니다.
(이부분 때문에 주문서의 `연체/연장료 결제방법`이 `해당사항없음` 으로 나타납니다)

    대여일:    2016-12-18 
    반납예정일: 2016-12-21
    반납희망일: 2016-12-21
    반납일:    2016-12-22

날짜상으로 보면 1일 연체 했습니다.
연체료가 있어야 할 것 같은데 0 원입니다.

연체료/연체일을 계산하는 방법은 복잡한데, 이경우에는 반납된 주문서의 룰을 따라서 상세대여 항목을 참고해서 계산합니다.
`stage` 가 `1` 인 항목이 있어야 할 것 같은데 없습니다.
그래서 연체일을 0일로 간주하고 연체비가 0원 입니다.

이 주문서는 오래전에 대여/반납 되었던 주문서라서 예전버전에서 데이터가 다루어졌습니다.
그때에 사용되던 결제/반납 화면에서 이걸 변경할 수 있는 기능이 있었던게 아닌가 싶습니다.

미납된 주문서가 그리 많지 않으니까 이런 주문서들을 찾아서 `미납` 라벨을 제거해주어야 하겠습니다.

**Comment by aanoaa** [comment]
비슷한 상황의 주문서들 입니다.

```
order(29777): online(0), rental_date(2016-05-23), late_fee(0)
order(30604): online(0), rental_date(2016-05-31), late_fee(0)
order(44097): online(0), rental_date(2016-11-13), late_fee(0)
order(45333): online(0), rental_date(2016-11-21), late_fee(0)
order(46952): online(0), rental_date(2016-12-07), late_fee(0)
order(47873): online(0), rental_date(2016-12-18), late_fee(0)
order(54122): online(1), rental_date(2017-03-09), late_fee(0)
order(63107): online(0), rental_date(2017-06-04), late_fee(0)
order(68736): online(0), rental_date(2017-07-27), late_fee(0)
order(70299): online(0), rental_date(2017-08-16), late_fee(0)
order(70866): online(0), rental_date(2017-08-26), late_fee(0)
order(71863): online(0), rental_date(2017-08-27), late_fee(0)
order(72579): online(0), rental_date(2017-09-02), late_fee(0)
order(72671): online(0), rental_date(2017-09-08), late_fee(0)
order(72831): online(0), rental_date(2017-09-06), late_fee(0)
order(74316): online(1), rental_date(2017-09-21), late_fee(0)
order(74945): online(0), rental_date(2017-09-25), late_fee(0)
order(77443): online(0), rental_date(2017-10-25), late_fee(0)
order(78776): online(0), rental_date(2017-10-31), late_fee(0)
order(79896): online(0), rental_date(2017-11-04), late_fee(0)
order(80685): online(0), rental_date(2017-11-13), late_fee(0)
order(81347): online(0), rental_date(2017-11-16), late_fee(0)
order(81502): online(0), rental_date(2017-11-16), late_fee(0)
order(81944): online(0), rental_date(2017-11-21), late_fee(0)
order(82007): online(0), rental_date(2017-11-20), late_fee(0)
order(82383): online(0), rental_date(2017-11-20), late_fee(0)
order(82450): online(0), rental_date(2017-11-21), late_fee(0)
order(82949): online(0), rental_date(2017-11-30), late_fee(0)
order(83579): online(1), rental_date(2017-11-30), late_fee(0)
order(84585): online(0), rental_date(2017-12-05), late_fee(0)
order(86196): online(1), rental_date(2017-12-20), late_fee(0)
order(86446): online(1), rental_date(2017-12-22), late_fee(0)
order(86816): online(0), rental_date(2017-12-22), late_fee(0)
order(92603): online(0), rental_date(2018-02-18), late_fee(0)
```

오래된 데이터처리의 문제라고 생각했는데 최근에도 발생하고 있습니다.
새로운 결제/반납 화면은 `2017-06-24`(#1277) 에 배포되었는데 그 이후에 건수가 더 많습니다.
가장 최근 주문서를 살펴봤는데 반납방법은 기록에 없는데 `미납` 입니다.

`연체/연장료`가 `해당사항없음` 이라면 `연체/연장료 결제방법` 을 `미납` 으로 선택할 수도 없습니다.
데이터를 변경하기 전에 좀 더 살펴봐야 하겠습니다.

**Comment by aanoaa** [comment]
#1360 에서도 보고된 내용입니다.

92603 주문서의 경우 최근 변경된 시간이 `2018-02-22 09:39:47` 입니다.
추측컨대,

- 택배 반납 혹은 반납함에 들어있던 의류였고, 반납예정일(2018-02-21)이 지난 다음날 오전(2018-02-22)에 확인
- 연체료가 있는데 택배라서 연체료 납부방법을 `미납`으로 수정
- 반납함 혹은 택배반납 이라서 `택배발송/반납일` 을 수정
- 연체료가 0원으로 설정됨
- 전체반납

이렇게 하면 연장/연체료는 0원 이지만 `미납` 라벨이 붙습니다.

**Comment by aanoaa** [comment]
반납일을 기준으로 연체/연장료를 계산하는데 이렇게 되면 반납일을 하루 앞당겨야 해서,
반납일과 반납처리일을 분리할까 했지만 아직 처리되지 않았습니다.(#1213)

**Comment by aanoaa** [comment]
전체반납 혹은 부분반납할때에 연체/연장료가 0원인데 납부방법이 `미납` 이라면,
위와 같은 패턴으로 인해 잘못 기록된 것이라고 판단하고 `미납`을 제거하는 방법이 있을 수 있습니다.

**Comment by pingpongworks** [comment]
내부적으로 정확한 상황 파악이 덜 된 것같아 이슈 삭제 하겠습니다.

**Comment by aanoaa** [comment]
- 주문서내의 `미납` 라벨의 판별식을 변경하거나

or

- 잘못된 패턴의 반납에 대해 `미납` 라벨이 붙지 않도록 처리
- 미납이 아님에도 미납으로 인식되는 주문서들의 `미납` 라벨을 제거

두가지 방법이 있습니다.

주문서내의 `미납` 라벨의 판별식을 변경하도록 하겠습니다.
데이터의 변경도 필요없고 미납 주문서 목록을 뽑는 판별식과 동일합니다.

**Comment by aanoaa** [comment]
서버에 적용하기전에 [OpenCloset-Common-v0.1.7.tar.gz](https://cpan.theopencloset.net/STAFF@THEOPENCLOSET.NET/OpenCloset-Common-v0.1.7.tar.gz) 을 설치해주어야 합니다.

위에 뽑은 주문서 목록의 데이터를 변경해줄 필요는 없습니다.

**Comment by aanoaa** [comment]
@keedi 님이 적용해주시면 서버에서 확인하고 이슈 닫도록 하겠습니다.

**Comment by pingpongworks** [comment]
>주문서내의 미납 라벨의 판별식을 변경하도록 하겠습니다.

판별식을 변경한다는 의미를 제가 정확히 이해하지는 못했습니다만, 결과적으로는 

- 택배 반납 혹은 반납함에 들어있던 의류를 반납예정일이 지난 다음날 오전에 확인하고
- 연체료 납부방법을 미납으로 수정한 후 
- 반납함 혹은 택배반납 이라서 택배발송/반납일을 원래 반납예정일로 수정하더라도 
-` 미납` 버튼이 붙지 않는다

라는 것인가요? @aanoaa

**Comment by pingpongworks** [comment]
> 위에 뽑은 주문서 목록의 데이터를 변경해줄 필요는 없습니다.

이 부분도 궁금해서 여쭤봅니다. 
이미 `미납`버튼이 붙어있는 과거 주문서들의 데이터를 변경하지않는다면, 계속 미납으로 남아있는 건가요? 아니면,  OpenCloset-Common-v0.1.7.tar.gz 설치 작업 후에는 자동으로 문제있던 주문서들의 미납이 사라지는 건가요?

**Comment by aanoaa** [comment]
현재 미납이 아닌데 미납으로 라벨이 표시되는 주문서들은 실수에 의해서 미납으로 기록한 것들 입니다.
배포 후에는, 같은 실수가 반복되더라도 주문서내의 `연장/연체료 납부방법` 은 `미납` 으로 기록은 되지만,
지금처럼 주문서에 `미납` 라벨이 붙지는 않게됩니다.

정확하게 지금까지는 `연장/연체료 납부방법` 이 `미납` 이면 주문서에 `미납` 라벨이 붙었는데,
앞으로는 `연장/연체료 납부방법` 이 `미납` 이면서 실제로 연장/연체료가 0원 초과인 주문서들만 `미납` 라벨이 붙습니다.

문제있던 주문서들의 `미납` 라벨은 사라지게 됩니다.

**Comment by keedi** [comment]
배포 완료 했으며 이슈 닫습니다.
