### ISSUE TITLE
모든 주문서의 "택배반납 발송일"이 "오늘 날짜"로 바뀌는 오류

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1428]
orders/47873 주문서의 미납 문제와 의류착용일을 파악하는 과정에서 발견된 또 하나의 날짜 관련 오류입니다. 

모든 주문서의 택배반납 발송일이 현재 날짜로 바뀌고 있습니다. 

어제 확인했을 때는 3월 23일이었는데 오늘은 3월 24일로 바뀌어 있습니다. 

확인해보니, 모든 주문서의 택배반납 발송일 날짜가 오늘 날짜로 통일되어 있습니다.

**Comment by pingpongworks** [comment]
주문서 관련 오류를 @aanoaa 님이 처리하고 계신 것 같아 Assignees 걸고 이슈우선순위에 올렸습니다.

**Comment by aanoaa** [comment]
이건 오류가 아닙니다.
`택배발송/반납일` 은 저장되는 값이 아닙니다.
단지 기본값이 오늘 날짜인 것 뿐입니다.
날짜가 바뀜에 따라 연체/연장료가 다시 계산됩니다.

보통 반납함 이나 택배로 반납받았을때에 어제 날짜로 연체료를 계산하기 위해 사용됩니다.

**Comment by pingpongworks** [comment]
아, 그런가요? 
저장되는 값이 아닌 건 몰랐습니다. 
마음이 편해지네요 ㅎ  알겠습니다. 
저장될 필요가 있다고 판단될 때 다시 말씀드리겠습니다. 
스스로 이슈 닫겠습니다.
