### ISSUE TITLE
비전 트레이닝 센터에 기증한 의류 수량: 2018년 1월 ~ 3월

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1432]
2018-01-01 ~ 2018-03-30
3개월간 비젼트레이닝에 기증된 각 품목별 의류 수량을 확인하고자 합니다.
비젼트레이닝에 전달하여 기부금 영수증을 발급받아야 하는 건입니다.

#1279 참고 부탁드립니다

**Comment by pingpongworks** [comment]
[추가 질문이 있습니다] 
다음달부터는 매달 말일에 한달 간의 기증의류수 확인서를 보내달라는 비전 측의 요청이 있었습니다.  이런 경우, 매달 말일에 새로 이슈를 올리는게 편하실까요? 아니면 뭔가 다른 방법이 있을까요? 계속 날짜만 바뀌고 계속 반복될 내용이라 혹시 뭔가 다른 방법이 있나 해서 여쭤봅니다. @keedi

**Comment by keedi** [comment]
좋은 방법이 있을지 고민해보겠습니다. 우선은 상기 이슈 제목처럼 이슈를 열어서 해결하는 것이 좋을 듯 합니다. 더불어 우측 라벨에서 **통계** 라벨도 선택 부탁드립니다.

**Comment by keedi** [comment]
특별히 수정사항이 없을 경우 이슈 닫아주시고 아니라면 피드백 부탁드립니다.

**Comment by pingpongworks** [comment]
@keedi 확인했습니다. 감사합니다~
