### ISSUE TITLE
서울시 쿠폰 대여 후, 관리자 페이지 주문 기록에 대여 일시가 없음

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1455]
>orders/106429
orders/106372
orders/106514

위 3건은 서울시 쿠폰으로 대여한 후, 
열린옷장 주문서에는 정상적으로 쿠폰 대여로 처리되었는데, 
취날 관리자페이지 주문기록에 대여일시가 없이 기록된 경우입니다. 
대여일시가 없는 상태로 기록될 경우 '정상대여 건'으로 입력되지않아
비용 정산시 누락되게 됩니다. 

106429 주문자의 경우는 첫번째 발생건으로 
관리자페이지 관리업체에 원인 규명을 요청하였으나 찾지못하여
수동으로 대여일시를 입력하여 수정해놓은 상태입니다. 
이후 같은 현상이 2건 더 발생하여 관리업체에 원인규명을 요청해놓은 상태입니다. 

예약할 때부터 대여일과 대여시간이 누락된 채로 신청서가 만들어지는 것 같기도 한데
혹시 대여 예약시 또는 대여 후, 대여기록이 관리자페이지에 동기화되는 과정에서 생긴 
우리 쪽 시스템의 오류는 아닌지 확인 부탁드립니다.

**Comment by keedi** [comment]
우선 확인 후 내용 공유하겠습니다.

**Comment by keedi** [comment]
내용 및 상황을 정확하게 이해하지는 못했지만 다음 두 이슈와 연관이 있을 것 같습니다.

- #1256 취업날개 서비스의 방문/미방문자의 통계수치 동기화
- #1284 취업날개 통계수치 비교

우선 상기 이슈를 참고해 상황을 먼저 파악하겠습니다.

**Comment by pingpongworks** [comment]
네~ 아이넷에서도 원인파악한 후 7월 3일까지 답변주기로 했습니다. 
6월 정산과 관련된 부분이라 7월 3일까지는 원인이 파악된 후 
정상적인 대여기록으로 복구가 필요합니다.

**Comment by pingpongworks** [comment]
2018년 서울시쿠폰 관련 이슈 닫습니다. 2019년 같은 오류 발견시 다시 열겠습니다.
