### ISSUE TITLE
연체중일 때 연장할 수 없도록 요청

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1457]
이전에 #966 을 통해 요청드렸던 이슈인데
계속 나쁜 사례가 재발하고 있어 다시 한번 요청드립니다. 

user/72304 사용자의 경우에는 두벌의 정장을 대여해놓고
연체 후에도 계속 연장하는 방법으로 반납을 피하고 있습니다. 

#966 에서 요청드렸던 내용 다시 한번 아래 인용하여 요청드립니다. 

>`연체중`일 때 연장을 할 수 없다.

연체중인 자가 연장을 하려고 연장신청 url을 접속하려고 할 때 대여연장신청서가 보여지는 대신 다음과 같이 고지한다

    귀하는 연체 중이므로 더 이상 대여기간을 연장할 수 없습니다.
    금일 중으로 의류 반납과 연체비 납부 이행을 요청합니다.

`연장중`에는 당연히 연장을 할 수 있습니다만, 기한을 제한하고자 하여 별도의 이슈로 남기겠습니다.

**Comment by pingpongworks** [comment]
@aanoaa 이전에 작업하셨던 내용이라 같이 assignees 걸었습니다

**Comment by aanoaa** [comment]
연체중일때

![screenshot-localhost 5001-2018-07-03-16-17-33](https://user-images.githubusercontent.com/170528/42205049-51ba8a36-7ede-11e8-89be-2a6fa4f9b226.png)

----------------------------------------------

연장 중 일때

![screenshot-localhost 5001-2018-07-03-16-17-51](https://user-images.githubusercontent.com/170528/42205081-61f1c680-7ede-11e8-81e5-642fde796396.png)

----------------------------------------------

26일 이상 연장 중 일때

![screenshot-localhost 5001-2018-07-03-16-18-40](https://user-images.githubusercontent.com/170528/42205093-6bac4cb8-7ede-11e8-9544-be313cf50a98.png)

**Comment by aanoaa** [comment]
- 연체중일 때 연장을 할 수 없다.
- 연체중인 자가 연장을 하려고 연장신청 url을 접속하려고 할 때 대여연장신청서가 보여지는 대신 다음과 같이 고지한다(...)
- 연장 중일 때는 추가로 연장할 수 있다. 
- 최대 대여가능 기간은 30일로 제한한다. 연장의 경우에도 동일하게 적용한다.

@pingpongworks 세세하게 논의 되지 않은 내용은 제가 임의로 진행했습니다.
아직 반영하지 않았습니다.
추가하거나 수정일 필요한 부분을 말씀해주세요.

**Comment by pingpongworks** [comment]
정리하신 걸 보니까 제가 미처 세세하게 정리를 못 해드렸네요. 
위와 같이 진행해주시면 될 거 같습니다. 잘 정리해주셔서 감사합니다~

**Comment by aanoaa** [comment]
7/3일에 대여했는데 7/30일 까지만 연장이 가능합니다.
8/2일? 까지 가능해야 합니다.

**Comment by pingpongworks** [comment]
테스트하고 확인했습니다. 감사합니다~
