### ISSUE TITLE
연장중일 때 연장 가능한 기간을 제한하고자 함

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1458]
다수를 위한 공유옷장이고 하는 열린옷장의 취지와 
대여의 특성상 의류관리 가능기간 등을 고려하여
내부논의를 거쳐 **대여가능기간을 30일**로 제한하고자 합니다. 
그 동안의 사례로 보아 30일이 넘는 장기대여의 경우 
대부분 반납기일에 대한 인식이 흐려져 연체가 되거나
재대여가 불가능할 정도로 옷에 문제가 생긴 상태로 반납되는 경우가 많아
적정 대여가능기간을 30일로 제한하고자 합니다. 

**3박4일 기본 대여 기준일 때 연장 가능한 기간은 26일입니다.** 

#1457 을 통해 연체중일 때 연장을 할 수없도록 요청드린 것과 별도로 
**연장 중일 때 연장을 하는 경우, 전체 대여기간이 30일로 제한**되도록 요청드립니다.  

현재 연장 url을 통해 본인이 직접 연장을 하는 방식 내에서 연장기간을 선택할 때
30일 이후의 날짜는 선택이 되지 않도록 하는 방안이 어떨까 하는데 의견 부탁드립니다. 

날짜 선택이 되지 않을 때 
`열린옷장의 최대대여가능기간은 30일입니다`와 같은 안내가 보여지면 좋을 듯하고,
작업이 복잡해진다면 안내가 따로 없더라도 30일 이상의 장기대여는 거의 많지 않은 경우이므로
전화나 카톡으로 문의가 왔을 때 대응하는 방법으로도 충분할 듯도 합니다.

일단, 대여가능기간을 30일로 제한하는 방안에 대한 의견 부탁드립니다.

**Comment by aanoaa** [comment]
#1457 에서 연체 중 이거나 최대 연장기간을 넘어선 사용자가 연장신청을 할 수 없도록 진행
중에 있습니다.

최대연장기간이 26일 이니까 현재 연장일 포함해서 앞으로 신청하는 연장일 또한 26일을 넘기지
못하게 하는 기능인 것 같습니다.

예로 7/1일에 25일째 연장 중인 사용자가 7/26일로 연장을 할 수 없도록 해야 하는 기능입니다.
7/2일 까지만 연장을 허용할 수 있어야 합니다.

**Comment by aanoaa** [comment]
연장신청 달력에서 남은 연장일 까지만 선택 가능하도록 하였습니다.
반납일+26d 까지 선택 가능합니다.

7/1일 기준으로 15일 연장하고 있다면 7/11일 까지만 선택가능합니다.

**Comment by pingpongworks** [comment]
테스트 해보니까 아직은 무한정 연장이 가능하네요. 아직 적용이 안되었나봐요. 내일 다시 한번 테스트해보겠습니다. 감사합니다^^

**Comment by aanoaa** [comment]
네 아직 적용하지 않았습니다.
#1457 피드백 주시면 수정해서 같이 반영하려고요.

**Comment by pingpongworks** [comment]
네~ #1457 내용도 확인했습니다. 같이 부탁드릴게요~

**Comment by pingpongworks** [comment]
테스트하고 확인했습니다. 감사합니다~
