### ISSUE TITLE
중복된 탈의실로 상태변경을 못하도록 함

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#1466]
https://github.com/opencloset/monitor/issues/181

상태변경은 단순하면서 복잡한 작업입니다.
`order.status_id` 의 값을 바꿔주면 상태가 변경되지만,
어떤상태에서 어떤상태로 변경되느냐에 따라 추가작업이 각기 다릅니다.

일반적인 경우 탈의1번에 두개 이상의 주문서가 배치되는 경우는 없습니다.
하지만 가능은 합니다.

실수로 탈의1 에 사람이 있음에도 탈의1 로 배정을 해버린다면 문제가 발생할 수 있기 때문에
그렇게 할 수 없도록 하는 작업입니다.

**Comment by Bentleypark** [comment]
시간표에서 바로 탈의실의 지정하여 하도록 수정하는 코드에서 수정사항이 있어서 요청드립니다. 
대여자 중에 자켓 or 팬츠(스커트) or 자켓/팬츠(스커드) 선택하는 경우, 치수 측정자는 탈의실을 별도로 지정하지 않는 기존의 방법대로 의류준비로 상태를 변경하고 있습니다.  적용된 코드를 사용할 경우에 의류준비 단계에서 탈의실을 지정하면 탈의실 지정은 되지만 다시 한번 의류준비 상태가 됩니다. 


* 자켓/팬츠 혹은 단품만 하는경우 
치수측정 -> 의류 준비 -> 탈의지정 -> 의류준비 상태로 변경됨 

Preparation 화면에서 의류준비 -> 탈의실 지정하는 경우에 다시 한번 의류준비 상태로 변경되지 않도록 수정이 가능할까요?

**Comment by pingpongworks** [comment]
셔츠, 블라우스, 구두, 벨트와 같이 단품만 대여하는 경우에도 품목 변경을 대비해서 탈의실을 지정하고 있지 않나요? (몇몇한테 물어보니까 옷장지기마다 다르게 진행하는 것 같아서 일단 내부적으로 정리가 필요할 것 같습니다)  아마도 자켓,팬츠,스커트와 같이 수트 품목만 대여하는 경우에만 옷장지기가 옷을 준비하는 동안 대여자가 대기실에서 기다릴 수 있도록 치수측정할 때 탈의실을 지정하지 않는 것으로 알고 있습니다. 

그런데 치수측정단계에서 탈의실을 지정 기능이 생긴 이후로는 탈의실을 지정하면 `의류준비` 상태로 한번 머물렀다가 다시 탈의실을 지정했을 때 `탈의실`로 상태가 바뀌도록 구조가 바뀌었기 때문에, 수트류만 대여하는 경우에는 치수측정 단계에서 탈의실을 지정하지 않고 의류준비로 바로 넘겨서 수트가 준비된 후 탈의실에 넣을 때 두번을 넣어야하는 상황입니다. 

일단은 수트만 대여하는 경우에만 다시 예전과 같은 구조가 되어야 하는 것이라 꼭 필요한 작업인가 하는 생각이 듭니다.  아마도 수트만 하거나 단품만 하는 경우는 1일 전체 대여자 중 많지않은 경우일 거 같은데(오늘같은 경우는 4건 정도네요) 그에 비해 작업이 커지는 느낌이라서요,,, 

아예 수트만 하는 경우에도 치수측정단계에서 탈의실을 지정하고 "지정된 탈의실에서 옷이 준비될 때까지 잠시 기다려주세요"라고 하면 어떨까 하는 생각도 해봅니다. 요즘 옷장지기들의 의류준비 속도를 보면 수트 준비에 평균 2분이 넘지 않게 되고있어서 대여자가 많이 불편하지는 않을 듯 합니다. 

옷장지기 입장에서도 대여품목을 보면서 어떤 경우에는 의류준비로 넘기고, 어떤 경우에는 탈의실을 지정하는 것보다는 / 모든 경우에 탈의실을 지정하고 바로 탈의실로 입장하도록 하는게 더 업무가 심플해지는게 아닌가 싶습니다. 

@Bentleypark님이 디테일한 부분의 불편을 잘 지적해주셨는데요, 이 부분은 내부적으로 논의를 한 번 해본 후 작업요청을 드리는게 좋을 거 같네요. **다만, 만약 수트만 대여하는 경우에 치수측정 => 의류준비 => 탈의지정이 바로 되도록 한다면 작업이 가능한지, 간단한 작업인지에 대해서만 @aanoaa 님이 알려주시면 좋겠네요.**

**Comment by aanoaa** [comment]
- 자켓 or 팬츠 or 스커트
- 자켓+팬츠
- 자켓+스커트

만 대여하는 경우인가요?

**Comment by aanoaa** [comment]
작업의 볼륨은 크지 않습니다.
정책이 정해지면 알려주세요.

**Comment by pingpongworks** [comment]
자켓 or 팬츠 or 스커트
    자켓+팬츠
    자켓+스커트

네~ 맞습니다.  어려운 작업이 아니라면 논의한 후 말씀드릴게요^^ 

일단은 **치수측정 시 시간표에서 비어있는 탈의실 번호만 보이는게 좋을 거 같다**부터 작업을 먼저 부탁드리겠습니다. 제가 오늘 해보니까 치수측정자가 시간표, PREPARATION, 사용자정보를 왔다갔다 하면서 탈의실을 지정하는게 꽤 혼란스럽더라고요.  부탁드릴게요.

**Comment by aanoaa** [comment]
동적으로 select box 의 option 목록을 변경하기 위해서는
xeditable 의 `input:select` 의 attrs 중에 `source` 를 활용할 수 있습니다.
`source` 는 `string | array | object | function` 으로 정의될 수 있습니다.

function 안에서 ajax 로 비어있는 탈의실 데이터를 fetch 해오고 그것으로 가능한 탈의실만 추가해주도록 합니다.
backend 에서 비어있는 탈의실 목록을 응답해 줄 수 있는 route 가 추가되어야 합니다.

**Comment by aanoaa** [comment]
변경 가능한 탈의실(상태)목록을 돌려주는 기능이기 때문에 `available_rooms` 혹은 `available_status` 가 적절할 것 같습니다.

- `GET /api/status` : 모든 상태를 응답
- `GET /api/status?available` : 변경 가능한 상태를 응답

------------------------

`json` 으로만 응답하도록 하면 될 것 같습니다.

```
[
  {id: 1, name: "대여가능"},
  {id: 2, name: "대여중"},
  ...
]
```

**Comment by aanoaa** [comment]
원활하게 작업된 것은 아닙니다.
`editable` 의 source 설정은 초기에 binding 할때에 이루어지고 이때에 ajax 옵션을 지원한다는 뜻 이었습니다.
제가 원했던 data source 가 필요할때마다 불려지는 방식이 아니었습니다.

다행히도 data source 만을 변경하는 방식을 찾아서 적용하였습니다.
시간표탭은 적용뒤에 버그가 발견되면 대여업무에 지장이 있습니다.

제가 서포트할 수 있도록 준비하고 옷장지기가 테스트할 수 있는 환경에서 배포하도록 하겠습니다.

**Comment by pingpongworks** [comment]
네~ 그럼 점심시간이 시작되는 시간이나 업무가 마무리되는 시간에 하는게 좋겠네요. 오늘부터 비수기가 시작된 관계로 여유가 있습니다. 언제든 편하실 때 이야기해주세요. 혹시 제가 출근하지 않은 날이라도 @Bentleypark 님이 있으니까 테스트 가능합니다~

**Comment by aanoaa** [comment]
생각해보니 예약된 탈의실을 선택할 수 있습니다.
예약된 탈의실이란 현재는 의류준비 상태이지만 이미 탈의실을 배정받은 것을 뜻합니다.
예약된 탈의실도 선택할 수 없도록 해야 합니다.

**Comment by aanoaa** [comment]
예약된 탈의실의 데이터는 monitor 의 local DB(SQLite) 에 쌓이고 있어서 staff 에서는 접근할 수가 없습니다.

1. `GET /api/status-list?avaiable` 를 대체하는 api 를 monitor 에 추가해주거나
2. monitor 에서 예약된 탈의실의 데이터를 어딘가로 실시간 export 해주도록 해서 그걸 활용해야 합니다.

**Comment by aanoaa** [comment]
물리적으로 같은 서버를 사용하기 때문에 path 를 지정하면 사용할 수 있지만 docker 와 같은 isolate 된 환경에서는 불가능 합니다.

지금 당장의 문제해결을 위해 쉬운 길을 택하지 않고 적절한 방법을 찾아보겠습니다.

**Comment by aanoaa** [comment]
adf61ebff07857e42b21d74968aed4d387d78a44 에서 반영하였습니다.
배포전에 monitor 의 새로운 버전이 반영되어야 합니다.
