### ISSUE TITLE
2017년 7월 이후 주문서에서 대여 목적이 기록되지 않음

### ISSUE THREAD

**Issue by keedi** [opencloset/opencloset#1473]
#1472 이슈를 처리하면서 자료를 살펴본 결과 2017년 7월 이후 주문서부터 주문서 테이블에 대여 목적 관련 정보가 제대로 저장되지 않음을 확인했습니다. 이는 치명적이며, 이로 인해 2017년 7월부터 현시점 2018년 8월까지의 대여 목적 뿐만 아니라 관련 유사 자료의 값을 확인하는데 문제가 있는 이슈입니다.

최초로 발생한 것으로 보이는 것은 2017년 7월 24일로 추정하며, 간간이 대여 목적이 기록된 경우가 있으나 이는 전체 비중의 극히 일부입니다. 정보를 더 확인해본 결과 이는 온라인 주문서의 경우 대여 목적이 기록된 것으로 추정되며 오프라인 대여 주문서의 경우 모조리 유실되어있습니다.

관련해 상황 파악이 필요합니다.

**Comment by pingpongworks** [comment]
아,,, 유실된 원인이 뭘까요? 
지금부터라도 복구하면 다시 데이터를 기록 가능한가요?

**Comment by keedi** [comment]
확인 중인데 주문서 시스템 개편과 관련 있을 것 같습니다. 지나간 자료는 어쩔 수 없고, 원인을 찾아서 수정한다면 앞으로는 기록이 될 것이라고 봅니다. 다만 주문서 관련해서 많은 변화가 있었기 때문에 좀 꼼꼼히 살펴봐야할 것 같네요.

해당 이슈에서는 어찌됐든 유실됐다 하더라도 사용자 정보상의 대여 목적 정보를 활용해 최대한 유사하게 자료 추출은 했습니다. #1472 의 경우 중복 방문자가 많다면 실제 값과 차이가 많이 커지고 그렇지 않다면 실제 값과 큰 차이는 있지 않을 것이나 정확한 값은 아닌점은 고려해주셔야 할 듯합니다.

**Comment by pingpongworks** [comment]
네~알겠습니다

**Comment by aanoaa** [comment]
상세대여목적(`purpose2`)에 대해서 말씀하시는 건가요?
대여목적과 상세대여목적이 `user_info` 테이블에서 참조되어서 사용되고 있습니다.
왜 그런지 언제부터인지는 모르겠습니다.

다행히도 `user_info.purpose2` 에는 데이터가 존재합니다.
여러번 방문하는 대여자의 경우에는 최근 대여목적|상세대여목적만이 덮어써져서 남게됩니다.

주문서마다 존재해야 하는게 맞는거 같은데 아마도 작년여름에 바꿀때 신경쓰지 못한 것 같습니다.

---

사용자 생성은 인증번호 validation 하는 과정에서 이루어집니다.
방문예약을 할때에 purpose 와 pupose2 가 user_info 에 기록됩니다.
order 에 purpose2 를 언제 뺏는지는 더 찾아보고 있습니다.

**Comment by aanoaa** [comment]
포장 -> 결제대기 상태로 변경되면 사용자정보를 주문서에 동기화 시키는 기능이 있었습니다.
그걸 제가 작업하면서 빼먹었습니다. (d1b777f350f1)

```perl
    #
    # 결제 대기 상태이면 사용자의 정보를 주문서에 동기화 시킴
    #
    if ( $order->status_id == 19 ) {
        my $user      = $order->user;
        my $user_info = $user->user_info;
        my $comment   = $user_info->comment ? $user_info->comment . "\n" : q{};
        my $desc      = $order->desc ? $order->desc . "\n" : q{};
        $order->update(
            {
                wearon_date  => $user_info->wearon_date,
                purpose      => $user_info->purpose,
                purpose2     => $user_info->purpose2,
                pre_category => $user_info->pre_category,
                pre_color    => $user_info->pre_color,
                height       => $user_info->height,
                weight       => $user_info->weight,
                neck         => $user_info->neck,
                bust         => $user_info->bust,
                waist        => $user_info->waist,
                hip          => $user_info->hip,
                topbelly     => $user_info->topbelly,
                belly        => $user_info->belly,
                thigh        => $user_info->thigh,
                arm          => $user_info->arm,
                leg          => $user_info->leg,
                knee         => $user_info->knee,
                foot         => $user_info->foot,
                pants        => $user_info->pants,
                desc         => $comment . $desc,
            }
        );
    }
```

**Comment by aanoaa** [comment]
[새로운 결제 및 반납 화면의 구성 #1277](https://github.com/opencloset/opencloset/issues/1277#issuecomment-312540621)

> 브라우저로 결제대기 상태의 주문서를 들어가면,
> 주문서에 사용자정보를 복사하는 기능이 있습니다.
> 결제대기 -> 대여중으로 변경될때가 더 적절하지 않나 싶습니다.

이때에 신체치수 정보는 `사용자정보 -> 주문서` 로 옮겼는데,
대여목적, 착용일, 카테고리 등등은 옮기지 않은 것 같습니다.

https://github.com/opencloset/OpenCloset-API/blob/develop/lib/OpenCloset/API/Order.pm#L750

**Comment by aanoaa** [comment]
wearon_date  => $user_info->wearon_date,
    purpose      => $user_info->purpose,
    purpose2     => $user_info->purpose2,
    pre_category => $user_info->pre_category,
    pre_color    => $user_info->pre_color,
    height       => $user_info->height,
    weight       => $user_info->weight,
    neck         => $user_info->neck,
    bust         => $user_info->bust,
    waist        => $user_info->waist,
    hip          => $user_info->hip,
    topbelly     => $user_info->topbelly,
    belly        => $user_info->belly,
    thigh        => $user_info->thigh,
    arm          => $user_info->arm,
    leg          => $user_info->leg,
    knee         => $user_info->knee,
    foot         => $user_info->foot,
    pants        => $user_info->pants,
    desc         => $comment . $desc,

신체치수를 제외한 데이터입니다.

-   purpose
-   pre_category
-   pre_color
-   desc

위 4개 항목은 주문서에 따라 데이터가 있기도 하고 없기도 합니다.
상태변경 시점에 같은 처리를 하는 것이라면 전부 있거나 전부 없어야 합니다.
monitor 서비스등에서 데이터 변경에 영향을 받은게 아닐까 싶습니다.

-   **wearon_date:** 이건 예약할때 넣어주고 있습니다.
-   **purpose2:** 이건 확실히 없습니다.

기존에는 포장 -> 결제대기 상태로 넘어갈때에 사용자정보 -> 주문서로 데이터를 한방에 저장했다면,
지난해 7월?에 주문서가 개편되면서 데이터가 입력되는 시점에 따라 주문서에 데이터를 넣어주고 있습니다.

`purpose`, `pre_category`, `pre_color`, `desc` 의 값이 언제 어디에서 주문서에 값이 들어가는지 확인이 필요합니다.

**Comment by aanoaa** [comment]
> purpose, pre_category, pre_color, desc 의 값이 언제 어디에서 주문서에 값이 들어가는지 확인이 필요합니다.

못찾겠네..

**Comment by aanoaa** [comment]
데이터가 있기도 하고 없기도 한 것은 `OpenCloset::API` 의 test 에 의해 생성된 데이터 였습니다.
이를 제외하고 쿼리를 해보면 지난 5월 or 7월 부터 아래 데이터가 주문서에 빠져있습니다.

-   purpose
-   pre_category
-   pre_color
-   desc
-   purpose2

아 테스트 데이터때문에 겁나 삽질..

**Comment by aanoaa** [comment]
기존처럼 `결제대기 -> 대여중` 으로 변경될때에 신체치수 이외의 필요한 정보를 주문서에 복사하도록 하면 해결될 것 같습니다.

**Comment by aanoaa** [comment]
다음 버전에 수정될 예정입니다.
배포는 @keedi 님이 해주세요.

staff 는 바뀐게 없는데 의존성 모듈을 업그레이드 하고 서비스를 재시작해주어야 합니다.

**Comment by aanoaa** [comment]
닫으면 찾기 어려울 것 같아서 다시 열겠습니다.
배포 후에 닫히면 될 것 같습니다.

**Comment by aanoaa** [comment]
배포하였습니다.
