### ISSUE TITLE
대여 시스템의 변화에 따라 주중 및 주말 예약 가능 인원을 늘림

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1478]
대여공간 확장, 탈의실 확충 등 대여시스템의 변화로
예약가능 인원을 늘리고자 합니다. 

    [월~금]
    10: 00~5:00 남자 6명 / 여자 6명
    5:30 남자 3명 / 여자 3명

    [토~일]
    10: 00~5:00 남자 5명 / 여자 5명
    5:30 남자 3명 / 여자 3명

예약활성화 예약가능인원 수정부탁드립니다~

주중과 주말 예약인원 활성화를 다르게 하는게 가능하지 않다면 
월~금으로 요청드린 내용을 주말까지 통일해서 해주셔도 됩니다.

**Comment by keedi** [comment]
주중과 주말 또는 요일별 예약 인원 활성화 설정이 가능합니다. 언급해주신대로 처리하겠습니다. :)

**Comment by keedi** [comment]
점심 시간 대역에 예약을 불가하게 하는것은 여전한지, 해당 시간 대역은 동일한지 확인 부탁드립니다.

**Comment by pingpongworks** [comment]
아, 그 부분은 빼먹었네요. 동일합니다. 

오전 예약 >> 10:00 - 11:30
오후 예약 >> 2:00 - 5:30

**Comment by keedi** [comment]
적용했습니다. 이상 있으면 알려주세요. :-)

**Comment by pingpongworks** [comment]
확인했습니다. 감사합니다~
