### ISSUE TITLE
2018년 가을 뉴스레터 발송용 기증자 이메일 리스트

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1480]
2017년 3월 28일부터 현재 2018년 9월 11일까지의 리스트 요청드립니다.
#1216 이슈와 같은 포맷입니다. 추석인사를 겸한 뉴스레터라 9월 16일(일)까지 요청드립니다.

**Comment by keedi** [comment]
> 2017년 3월 28일부터 현재 2018년 9월 11일까지의 리스트 요청드립니다.

혹시나 해서 확인차 여쭤보는데, 2017년 3월  28일인가요? 2018년 3월 28일 인가요?

**Comment by pingpongworks** [comment]
2017년 3월 28일부터 맞습니다. 
이전에 받았던 리스트가 정리가 되어있지 않아서 2017년 3월 28일 이후로 받았으면 한다고 합니다.

**Comment by keedi** [comment]
기증자 이메일 목록을 구하는 질의는 다음과 같습니다.

```sql
SELECT 
    u.id
    , u.name
    , u.email
    , ui.phone
    , DATE_FORMAT(d.create_date, "%Y-%m-%d") AS ymd
FROM
    donation AS d
        LEFT JOIN
    user AS u ON u.id = d.user_id
        LEFT JOIN
    user_info AS ui ON u.id = ui.user_id
WHERE
    DATE(d.create_date) BETWEEN '2017-03-28' AND '2018-09-11'
ORDER BY ymd, name
;
```

지금까지 추출했던 결과와 마찬가지로 동일 기증자가 여러번 기증한 경우 목록에 여러번 나옵니다. 동일 기증자를 한 건으로 표시하려면 말씀해주세요. 대신 이 경우 결과물에서 언제 기증했는지 날짜 정보는 표시할 수 없습니다.

**Comment by keedi** [comment]
실 자료는 메일로 전달드렸습니다.

**Comment by pingpongworks** [comment]
확인했습니다. 감사합니다~
