### ISSUE TITLE
[광주시 쿠폰]  gwangju201801 통계 페이지 오류

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1482]
9월 대여 통계가 잡히지 않고 있습니다. 
오류 해결 부탁드립니다.

**Comment by aanoaa** [comment]
https://github.com/opencloset/OpenCloset-Cron-Visitor/commit/d554db13870e69eb9612d8922a268727d1d4969e

광주 통계 오류를 확인하는 도중에, 용인통계에 문제가 있음을 발견하였습니다.
`yongin` 이라고 해야 하는데 `yongbin` 이라고 적었음.

**Comment by aanoaa** [comment]
의미 없는 로그가 많아서 실제 오류 로그를 찾기가 어려운 점이 있습니다.
10초마다 등록된 이벤트별로 두줄씩 찍히는 로그는 남길 필요가 없어보입니다.

    2018-09-21 00:10:26.687983 +0900 debug OpenCloset::Cron::Worker: insert_event_hanshin_univ_daily: cron[14 00 * * *]
    2018-09-21 00:10:26.688018 +0900 debug OpenCloset::Cron::Worker: insert_event_hanshin_univ_daily: timer is already exists

**Comment by aanoaa** [comment]
이름은 yongbin 으로 했지만 실제 동작은 yongin 으로 됐습니다.

1.  `insert_event_yongbin201801_daily` 함수는 없지만 export 되었습니다.
2.  `insert_event_yongin201801_daily` 함수는 export 되지 않았지만 호출되었습니다.

global namespace 로써 호출되었기 때문에 동작에는 문제가 없었습니다.
통계페이지가 생성되었다는 것이 그것입니다.

일간 통계가 보인다는 것은 수집되었다는 것 입니다.
`gwangju201801` 통계도 일별로 수집되었습니다.

통계는 수집되고 있습니다.
실제로 쿠폰이 사용되었음에도 통계에 0건으로 나온다면, 수집방법에 문제가 있는 것 같습니다.
(정말로 사용되지 않았거나)

**Comment by aanoaa** [comment]
오히려 문제가 발견된 것은 linkstart 의 통계입니다.

    2018-09-21 00:08:00.008035 +0900 info  main: insert_event_linkstart_daily[08 00 * * *] launched
    unhandled callback exception on event (start, OpenCloset::Cron=HASH(0x297bb88), ): Undefined subroutine &main::event_linkstart called at /path/to/bin/opencloset-cron-visitor.pl line 203.

**Comment by pingpongworks** [comment]
@aanoaa 아, 이럴수가! 인내심을 가지고 9월 시간표를 모두 살펴본 결과, 광주시 쿠폰은 사용되지 않았기 때문에 통계가 제로로 나온 것입니다. 9월 3일에 광주시쿠폰으로 예약한 1명이 있었는데, 중복쿠폰사용으로 떠서 쿠폰으로 결제를 하지 못했고, 그 이후로 한건도 없었습니다. 오류가 아닐 가능성이 큽니다.

**Comment by pingpongworks** [comment]
일단은 광주시에 예약기록이 없어서 '0'으로 통계가 뜬 것이라 문제가 없다고 전달하겠습니다. 이후에 이용자가 있는데도 같은 현상이라면 다시 요청하겠습니다. 본 이슈는 용인시, 링크스타트 정리되시면 닫아주셔도 될 거 같습니다.

**Comment by aanoaa** [comment]
https://github.com/opencloset/OpenCloset-Cron-Visitor/issues/16#issuecomment-423723047

그거 제가 여기에 남겨놨는데..

**Comment by pingpongworks** [comment]
추석연휴라 시간이 남아돌아서 직접 한번 더 확인했습니다~ㅎㅎ

**Comment by pingpongworks** [comment]
문제 해결 모두 되었어서 닫습니다~
