### ISSUE TITLE
자신감 프로그램 모집을 위한 대여자 명단

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1490]
자신감 때문에 고민하는 청년을 위한 컨설팅 프로그램 2차를 모집하고 있습니다.
프로그램에 대한 설명은 블로그를 참조해주세요. 
http://blog.theopencloset.net/221373239665

SNS홍보만으로는 잘 알려지지가 않아 지원상황이 생각보다 좋지 않습니다.
좋은 기회를 대여자들에게도 적극적으로 알리고자 문자메시지 홍보를 하려고 합니다. 
아래 요건을 충족하는 대여자들의 명단 (성명, 전화번호, 이메일 포함)을 요청드립니다. 

- 2018년 1월~현재까지 대여자
- 35세 이하 남여
- 주소지 서울, 경기, 인천으로 한정
- 2회 이상 or 3회 이상 대여한 자
 
지원기간이 많이 남지않아 가능하면 빨리 부탁드립니다. 
늦어도 10월 17일 수요일 전까지 가능하다면 좋을 거 같은데 
더 오래 걸린다면 이번에는 문자메시지 홍보를 포기하고
다음에 좀 더 미리 계획하여야 할 듯 합니다. 
답변 부탁드립니다.

**Comment by keedi** [comment]
35세 이하는 현 시점 기준 생년이 1983년을 의미합니다. 더불어 쿠폰 사용여부랑 별개로 2회 또는 3회 이상 대여자 명단을 의미하며, 2회 이상 명단과 3회 이상 명단을 별도로 추출해야 합니다.

**Comment by keedi** [comment]
2회 이상 ~ 3회 이상 대여 횟수는 2018년 기록만으로 판단합니다.

**Comment by keedi** [comment]
조건을 만족하는 대여자 명단을 추출하는 질의는 다음과 같습니다.

```sql
SELECT
    u.id          AS user_id
    , u.name      AS user_name
    , COUNT(*)    AS order_count
    , u.email     AS user_email
    , ui.phone    AS user_phone
    , ui.birth    AS user_birth
    , ui.address2 AS addr2
FROM `order`          AS o
LEFT JOIN `user`      AS u  ON o.user_id    = u.id
LEFT JOIN `user_info` AS ui ON ui.user_id   = u.id
LEFT JOIN `booking`   AS b  ON o.booking_id = b.id
LEFT JOIN `status`    AS s  ON o.status_id  = s.id
WHERE
    (
        o.parent_id IS NULL
        AND s.name = '반납'
        AND                     -- 2018년 1월 ~ 현재
            (
                   ( o.online <> 1 AND YEAR(b.date)        = 2018 )
                OR ( o.online <> 0 AND YEAR(o.rental_date) = 2018 )
                OR ( o.online <> 0 AND o.rental_date IS NULL )
            )
        AND ui.birth >= 1983    -- 35세 이하 남녀
        AND                     -- 서울, 경기, 인천
            (
                ( ui.address2 LIKE '서울%' )
                OR ( ui.address2 LIKE '경기%' )
                OR ( ui.address2 LIKE '인천%' )
            )
    )
GROUP BY u.id
HAVING order_count >= 3         -- 3회 이상 대여
ORDER BY order_count DESC
;
```

**Comment by keedi** [comment]
명단을 추출해본 결과 조건을 만족하는 대여자 중 2회 이상 대여자는 약 3천명, 3회 이상 대여자는 약 900명 이었습니다. 인원이 충분히 많으므로 3회 이상 대여자 명단만 정리해서 첨부드리겠습니다.

**Comment by keedi** [comment]
결과 메일로 첨부드렸습니다. :-)

**Comment by pingpongworks** [comment]
네~ 확인했습니다. 덕분에 오후에 바로 문자 발송할 예정입니다. 감사합니다^^
