### ISSUE TITLE
주기적으로 주소데이터를 업데이트

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#1491]
스크립트 한번 돌려서 되면 좋고,
이게 자동화까지 된다면 아주 좋습니다.

아직 확인된건 아니지만,
https://github.com/opencloset/OpenCloset-Share-Web/issues/211 와 같은 이슈의 발생을 줄일 수 있을 것 같습니다.

**Comment by pingpongworks** [comment]
주소 검색이 안된다는 분들이 계속 발생하고 있습니다. 주소 업데이트 작업은 어려운 작업일까요?

**Comment by aanoaa** [comment]
주기적으로 업데이트 하도록 하려면 볼륨이 있고요.(자동화)
지난 갱신 이후에 지금까지 누락된 데이터를 업데이트 하는 작업이라면 하루+ 정도 소요될 것 같습니다.

**Comment by pingpongworks** [comment]
그럼, 시간 되시는대로 부탁드리겠습니다~

**Comment by aanoaa** [comment]
가장 간단한 방법은 주기를(1개월? 3개월?) 가지고 데이터를 업데이트 하는 방법을 알아두고 새벽시간에 실행하는 것 입니다.

-   업데이트 하는 방법을 파악해야 합니다.
-   php 에 의존성을 가집니다.
    -   서버에 php 와 관련된 패키지를 설치해야 합니다.
-   행정안전부의 데이터를 사용합니다.
-   오늘기준으로 업데이트 파일을 다운로드 할 수 없습니다.(php 스크립트)
    행정안전부에서 제공하는 파일의 다운로드 경로가 바뀐 것 같습니다.

---

이걸 자동화 하고 싶은데 그러려면 매일 특정 시간에 업데이트 되는 데이터가 있는지 확인하고 업데이트 스크립트를 실행시켜야 합니다.
파일을 미리 다운로드 받도록 하고 파일이 존재할때에 실행시키도록 하면 될 것 같습니다.

다운로드가 정상적으로 되지 않고 있는데 이에 대한 패치를 해서 쓰거나 다운로드 하는 스크립트를 새로 만들면 될 것 같습니다.
파일을 파싱해서 db 에 넣어주는 작업이므로 이에 대한 내용을 파악해서 perl 로 포팅해서 사용할 수 도 있습니다.(제가 원하는 거; PHP out!)

주소 데이터는 zip 파일을 다운로드하면 200MB 가 안되지만 압축풀면 2GB ~ 3GB 정도 됩니다.(놀라워라)

파일들을 다운로드해서 캐시하도록 하는 작업까지는 되었습니다.
이 파일을 DB 에 넣어주는 작업을 php 를 활용할지 포팅해서 사용할지 탐구생활을 좀 해봐야 합니다.

**Comment by pingpongworks** [comment]
자동화가 되면 가장 좋겠네요. 안되면 현 시점의 신주소 데이터 업로드라도 서둘러 한번 하면 좋을 거 같고요. 최근에 개편된 주소가 많은건지, 주소 검색이 안된다는 분들이 거의 매일 나타나고 있습니다. 그런 분들은 검색이 되는 아무 주소나 쓰고 비고란에 정확한 주소를 적고 있는데, 운송장 다운로드를 해서 한꺼번에 출력하다보면 담당자가 원래 주소로 보내는 실수가 발생하기도 합니다. 주소 업데이트가 급박한 이슈가 되어버렸네요;;

**Comment by aanoaa** [comment]
대안이 될 수 있을 것 같아서 http://postcode.map.daum.net/guide 기록차 남깁니다.

**Comment by pingpongworks** [comment]
주소 검색이 안뜬다는 분들이 게속 나오고 있습니다. 
신 주소 업데이트 작업 언제쯤 마무리 될까요?

**Comment by aanoaa** [comment]
자동화까지 욕심을 냈는데 언제 될지 모르겠으므로 2018-08 버전으로 DB 를 업데이트 하겠습니다.
테스트를 위해서 검색되지 않는 주소를 알려주세요.

업데이트 이후에 검색되는지 비교해볼 수 있으면 좋을 것 같습니다.

2019-01-22 24:00 이후에 진행하겠습니다.
업데이트 중에는 주소검색이 원활하지 않을 수 있습니다.
한시간 정도 예상합니다.

잘못되었을때를 대비해서 현재 사용중인 주소 DB 를 백업해야 하는데 그건 지금 하겠습니다.

**Comment by aanoaa** [comment]
2017-03-13 버전의 백업파일이 존재합니다.
주소 DB 는 write 되지 않고 read 만 되던 것 이라서 백업이 필요없습니다.

**Comment by aanoaa** [comment]
```
$ mysql -u $USERNAME \
      -p$PASSWORD \
      $DATABASE < postcodify.20180808.v3.mysqldump
```

**Comment by aanoaa** [comment]
23:38 부터 20분간 주소 DB 교체 작업이 진행되었습니다.
없는 주소의 결과가 cache 되어 있을 것을 감안해서 캐시파일을 staff 와 postcodify 서비스에서 삭제하고 다시 생성됨을 확인했습니다.

주소DB를 2017년 이전 데이터에서 2018년 8월 기준 데이터로 변경하였습니다.

**Comment by pingpongworks** [comment]
확인했습니다~ 
그동안 검색안 된다고 했던 지역 몇 곳 검색해서 확인했습니다.

검색해서 바로 나오니까 속이 다 시원합니다. 감사합니다. 이슈닫을게요~

**Comment by aanoaa** [comment]
아 이런 상세한 주소 남기시면 곤란하지 않을까요

**Comment by aanoaa** [comment]
늦어서 죄송합니다.

**Comment by pingpongworks** [comment]
상세주소는 빠진 주소에요. 그래도 확인하셨으면 지우겠습니다.

**Comment by pingpongworks** [comment]
신주소 문제는 당분간 없을 듯 하니까 이슈우선순위에서 삭제하겠습니다.
