### ISSUE TITLE
쿠폰: anyang201801 100건 추가 발급 및 제한없음

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1493]
안양청년옷장의 기존 쿠폰이 거의 소진되어 추가 쿠폰 발행을 요청드립니다.

- 아이디 : anyang201801
- 이름 : 안양 청년옷장
- 발급 : 100
- 유형 : suit
- 택배비 여부: 온라인배송비 / 온오프라인 반납택배비 모두 안양시 부담
- 사용기간 : 2018-12-31

안양시에서 진행하는 프로젝트를 위해 쿠폰 발급을 추가요청드립니다.
쿠폰번호 발급은 10월 26일 (금)까지 요청드립니다.

**Comment by aanoaa** [comment]
100건 발급이니 100건 제한은 필요가 없지않나 싶습니다.

**Comment by aanoaa** [comment]
기존에 사용중이던 청년옷장의 이벤트명은 ` anyangyouth` 이었습니다.
구분이 필요하신건가요?

**Comment by aanoaa** [comment]
이름이 바뀌면 통계가 분리됩니다.

**Comment by pingpongworks** [comment]
네,,100건 제한은 필요없겠네요

**Comment by pingpongworks** [comment]
https://github.com/opencloset/opencloset/issues/1425
https://github.com/opencloset/opencloset/issues/1438
제가 담당하기 전에  `anyang201801`로 이슈가 여러개 올라와있어서요. 어떤게 맞는 걸까요?

**Comment by aanoaa** [comment]
확인해보겠습니다.

**Comment by aanoaa** [comment]
제가 찾은 이력은 이렇습니다.

`anyangyouth` 는 쿠폰 제한 작업이 추가되면서 2018년도 쿠폰이름이 `anyang201801` 으로 변경됨

anyang201801: 800개 2018-12-04, 2018-04-23
anyangyouth: 300개 2017-08-01

---

`anyang201801` 으로 작업해야 합니다.
통계도 수집되고 있습니다.

**Comment by aanoaa** [comment]
이메일로 전달해드렸습니다.

**Comment by pingpongworks** [comment]
네~ 부탁드려요.

**Comment by pingpongworks** [comment]
확인하고 전달했습니다. 감사합니다^^

**Comment by keedi** [comment]
작업하러 들어왔는데 처리하셨군요.

이미 있던 쿠폰이기 때문에 제목 변경하겠습니다.

**Comment by keedi** [comment]
더이상 `anyangyouth` 와 같은 쿠폰 명은 없습니다. 모든 쿠폰은 `<이름><연도><회차>`와 같은 방식으로 사용하고 있습니다. 이 경우 동일 쿠폰이라도 추가 발급이 용이하며 동일 연도에 발행한 쿠폰이라도 회차가 다를 경우 헷갈리지 않기 때문입니다. 더불어 상기 쿠폰명은 특별한 것이 없다면, 열린옷장 측에서 정하고 기억해서 알려주셔야 할 내용입니다. 이미 이슈에서 `anyang201801`이라고 명시했기 때문에 잘 인지하신 것으로 보이며(아니라면 이 부분은 정확하게 관리하셔야 합니다.) 다만 **발급**이 아닌 **추가 발급**으로만 명명해주시면 될 것 같고, 100건에 100건 제한이면 제한이 없는 것이므로 **제한없음**이라고 제목에 적어주시면 됩니다.

**Comment by pingpongworks** [comment]
네~ 알겠습니다
