### ISSUE TITLE
서울시쿠폰 사용자의 온라인 주문내역, 쿠폰 관리자페이지 연동 오류

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1494]
온라인으로 서울시쿠폰으로 결제한 사용자 user/109981의 
최근 주문내역 2건이 취날 관리자페이지에서 검색되지 않고 있습니다.

orders/119972
orders/119835

대여자가 연속 면접이 생겨서 연장을 하려고 했는데
본인의 주문서를 찾을 수가 없어서 열린옷장 쪽으로 문의를 해오는 바람에 발견이 된 건입니다. 
일단 연장대여 처리를 해야해서 주문서를 따로 생성해서 쿠폰처리를 했는데
여전히 주문내역이 관리자페이지에서는 검색이 되지 않고 있습니다. 
 
아이넷에 확인을 해보니 열린옷장 홈페이지에서 온라인 신청한 신호가
취날 관리자페이지로 제대로 전달이 되지 않은 것 같다고 합니다. 

확인부탁드립니다.

**Comment by aanoaa** [comment]
취업날개로 방문예약/방문예약 변경할때에는 예약시간을 변경하는 API 를 호출합니다.
이때에 요청이 실패하면 STDERR 로 남기긴하는데 이걸 capture 해서 로그로 남기지 않았기 때문에 실패 여부를 알 수 없습니다.

쿠폰이 사용되면 다음날 새벽에 쿠폰의 상태를 업데이트 하는 API 를 일괄로 요청하는데 이건 로그로 남깁니다.
최근에 2018-10-13 ~ 오늘까지 실패한게 없습니다.

좀 더 자세한 내용을 파악해봐야 할 것 같습니다.

그리고 주문서 번호 118443 는 온라인 주문서 아닙니다.

**Comment by aanoaa** [comment]
예약시간 변경에 대해 실패하는 건에 대해 로그를 남기도록 하겠습니다.

우리쪽의 쿠폰 상태가 올바르게 바뀌었고 API 콜도 성공했는데 취업날개 쪽에서 검색이 안된다는 것은 더 파악이 필요합니다.
가능하다면 취업날개 관리자 화면에서 id 로 검색을 해보던지 해야 할 것 같습니다.

자세한 쿠폰 id 는 email 로 전달해드리겠습니다.

**Comment by aanoaa** [comment]
로그를 남기도록 하였습니다.
취업날개와 관련된 예약이라 테스트를 못해본게 불안하긴 하지만..

**Comment by pingpongworks** [comment]
>그리고 주문서 번호 118443 는 온라인 주문서 아닙니다.

네 맞습니다. 118443은 예전에 문제가 없었던 방문대여건입니다. 이번 일과는 관계가 없습니다.

**Comment by pingpongworks** [comment]
코드번호로는 모든 주문서가 검색이 됩니다.  대여자는 대부분 이름으로 검색을 하게 되는데 검색이 되지 않습니다.

**Comment by pingpongworks** [comment]
일단 정산 관련해서는 10월 이용내역에 포함이 되어있어서 문제가 없습니다. 이후 같은 문제가 다시 발견되면 다시 말씀드리겠습니다.
