### ISSUE TITLE
쿠폰: anyang201801 300건 추가발급 및 제한없음

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1498]
안양청년옷장의 쿠폰이 또 소진되어 추가 쿠폰 발행을 요청드립니다.

아이디 : anyang201801
이름 : 안양 청년옷장
발급 : 300
유형 : suit
택배비 여부: 온라인배송비 / 온오프라인 반납택배비 모두 안양시 부담
사용기간 : 2018-12-31

안양시에서 진행하는 프로젝트를 위해 쿠폰 발급을 추가요청드립니다.
쿠폰번호 발급은 11월 22일 (목)까지 요청드립니다.

**Comment by keedi** [comment]
정상적으로 발급해 전달 드렸습니다. 이슈 닫습니다.
