### ISSUE TITLE
쿠폰: test201801 100건 발급 및 제한없음

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1499]
쿠폰 대여에 대한 지자체 및 기업의 문의가 많이 오는데 말로만 설명하면 이해도가 떨어집니다. 
테스트용으로 내부에서도 사용하고, 외부에도 전달할 수 있는 테스트용 쿠폰번호가 있으면 좋을 듯 합니다. 

아이디 : test201801
이름 : 열린옷장 테스트용
발급 : 100
유형 : suit
택배비 여부: 온라인배송비 / 온오프라인 반납택배비 모두 사용자 부담
사용기간 : ~~없음~~ 2018-12-31

기업의 사회공헌활동으로 청년들에게 쿠폰을 전달하고자 문의온 기업이 있어서 
안양시 쿠폰과 함께 11월 22일 (목)까지 주시면 
금요일에 쿠폰에 대한 설명 이메일을 전달할까 합니다.

**Comment by keedi** [comment]
Before:
~~쿠폰 : 테스트 및 쿠폰대여 사업설명 시 사용할 용도로 100건 발급 및 제한없음~~

After:
쿠폰: test201801 100건 발급 및 제한없음

**Comment by keedi** [comment]
사용기간은 없을 수 없습니다. 쿠폰 이름을 고려하면 2018년 연말까지만 사용하는 것이 맞을 것으로 생각됩니다. 내년에 새로운 쿠폰이 필요하다면 새로 발급하는 것이 적절할 듯 합니다. 이렇게 제한 날짜가 없는 쿠폰 일 경우 열린옷장 입장에서도 쿠폰 관리하는데 드는 수고가 늘 것입니다. 2018-12-31 까지로 설정해서 생성하겠습니다.

**Comment by keedi** [comment]
특별한 문제는 없는 것 같습니다. 이슈 닫습니다.
