### ISSUE TITLE
방문일시 선택에 열려 있지 않은 시간대의 slot 이 노출됨

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#1508]
![2018-12-12 01-24-22](https://user-images.githubusercontent.com/170528/49814298-b2287c00-fdac-11e8-90dd-9094a3c8f696.png)

방문일시 선택에 열려 있지 않은 시간대의 slot 이 노출됨
아래는 제가 테스트해본 결과입니다.
전체 목록(`2018-12-12 10:00:00` ~ `2018-12-23 17:30:00`)중에 `17:30` 이 넘어가는 결과는 없었습니다.

사용자마다 예약 일시목록이 달라지는 건지는 확인이 필요합니다.

    GET /api/gui/booking-list.json?phone=010xxxxxxxx&sms=xxxxxx&gender=male
    
    [
      {
        "date": "2018-12-12 10:00:00",
        "desc": null,
        "gender": "male",
        "id": 63390,
        "slot": 6,
        "user_count": 5
      },
      {
        ...
      },
      ...
    ]

**Comment by aanoaa** [comment]
방문일시 목록은 사용자와 상관없이 똑같이 return 됩니다.
`ymd` 파라미터가 있을때에 로직이 달라지는 것을 보고 테스트해서 재현했습니다.

보통의 경우에는 `ymd` 파라미터가 없지만, staff의 `예약` 화면에서 대여자 이름을 누를 때에 
`GET /api/gui/booking-list.json?gender=male&ymd=2018-12-12` 처럼 `ymd` 파라미터가 전달됩니다.

이때에는 왜 인지는 탐구생활을 더 해봐야 하겠지만 21:00, 22:00 의 슬롯도 return 됩니다.
아래에서는 `0` 건이라서 staff라고 할지라도 해당 시간대를 선택할 수는 없습니다.

    #!/bin/sh
    curl 'http://localhost:5001/api/gui/booking-list.json?ymd=2018-12-14&gender=male' \
         -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:63.0) Gecko/20100101 Firefox/63.0' \
         -H 'Accept: application/json, text/javascript, */*; q=0.01' \
         -H 'Accept-Language: ko-KR,ko;q=0.8,en-US;q=0.5,en;q=0.3' \
         -H 'Cookie: opencloset=eyJhY2Nlc3NfdG9rZW4iOiI4MTU3IiwiZXhwaXJhdGlvbiI6MzYwMCwiZXhwaXJlcyI6MTU0NDU1MDA3Nn0---e660e44941d1cc67ce41439cd70297a659cb6b27'
    
    [
      ...
      {
        "date": "2018-12-14 21:00:00",
        "desc": null,
        "gender": "male",
        "id": "63512",
        "slot": "0",
        "user_count": "0"
      },
      {
        "date": "2018-12-14 21:30:00",
        "desc": null,
        "gender": "male",
        "id": "63513",
        "slot": "0",
        "user_count": "0"
      },
      {
        "date": "2018-12-14 22:00:00",
        "desc": null,
        "gender": "male",
        "id": "63514",
        "slot": "0",
        "user_count": "0"
      }
    ]

왜 해당 사용자는 staff 의 예약 화면이 아님에도 유효하지 않은 목록을 받은 건지는 더 알아봐야 합니다.

**Comment by aanoaa** [comment]
staff 계정이 로그인 된 상태에서는 모든 데이터가 내려오는 것 입니다.
해당 사용자는 옷장지기의 PC 를 사용한게 아닌가 싶습니다.
관리자 권한의 요청에는 모든 데이터를 내려줍니다.

**Comment by pingpongworks** [comment]
위의 예약시간 노출 화면은 개인 핸드폰입니다. 회사PC로 테스트했을 때 쿠키의 영향을 받을 수 있을거 같아 개인폰으로도 테스트를 한 결과입니다. 

열린옷장 홈페이지를 통해 바로 예약을 시도할 때는 5:30까지만 보이는데, 서울시쿠폰사이트를 로그인하고 쿠폰으로 예약을 하려고 할 때만 5:30이후가 보이는둣 합니다.

**Comment by keedi** [comment]
#1509 에 정리했지만 다시 설명드리면 booking-list 는 사용자마다 다른 결과를 보여줍니다. 여기서 다른 결과를 보여주는 사용자라함은 우선 최소 다음과 같은 경우입니다.

- 일반 대여자
- 쿠폰 대여자
- 쿠폰 대여자 중 서울시 쿠폰 이용자
- 관리자

일반 대여자는 우리 모두가 기대하는 동작을 수행합니다. 쿠폰 대여자의 경우 해당 쿠폰의 마감 시일에 따라 보이는 날짜가 제한됩니다. 서울시 쿠폰 대여자의 경우 초기 구현 상의 이슈로 쿠키값을 사용하며, 쿠폰의 마감 일시에 따라 보이는 날짜가 제한됩니다. 관리자의 경우 자리가 있든 없든, 시간이 지났든 지나지 않았든 모든 슬롯을 열람하고 예약할 수 있습니다.

상기 화면은 쿠키를 피하기 위해 폰으로 진행했지만, 서울시 통해 들어왔기 때문에 쿠키가 써졌고, 거기에 추가로 관리자 계정이기 때문에 날짜 제약이 보이면서 모든 시간대가 보이는 것입니다. 상기 시나리오는 제가 추측을 한 것이지만 화면 캡쳐와 @pingpongworks 님께서 남겨주신 내용을 보았을때는 맞는 듯 하네요.

**Comment by pingpongworks** [comment]
테스트했던 옷장지기에게 확인해본 결과, 관리자 로그인을 한 적이 있는 폰이라 오류가 아니라 쿠키의 영향이 맞는 거 같습니다. 그리고 생각해보니까 10시까지 예약시간이 보여지고 있었다면, 아마도 아무리 예약가능인원이 0명이라도 저녁 시간으로 예약 안되냐는 문의전화가 꽤 많이 왔어야 정상일 거 같습니다. 그런 문의가 없었던 것으로 보아 관리자에게만 5:30분 이후가 보여지고 있다고 봐도 될 거 같습니다. 밤중에 괜한 수고를 하게 해드렸습니다. 죄송합니다. 이슈 닫을게요~
