### ISSUE TITLE
서울시 쿠폰 사용자의 경우 12월 13일 이후 방문 일시를 선택할 수 없음

### ISSUE THREAD

**Issue by keedi** [opencloset/opencloset#1509]
서울시 쿠폰 사용자의 경우 12월 13일까지만 예약 가능한 일시가 보이고 그 이후는 방문 일시가 보이지 않는다고 합니다. 이로 인해 13일 이후 방문 예약이 불가능하다고 합니다.

```
@pingpong:  오류가 하나 발생했는데 시간 되시는대로 확인 좀 부탁드려요~ 제가 춘천가는 기차안이라 이슈 등록은 못하고 행아웃으로 말씀드리네요.
@keedi:     오잉 22:00?
@pingpong:  현재 취업날개로 예약하려는 일부 대여자에게 12월 13일까지만 날짜가 보여지고 있어서요
@keedi:     20:00 이후에도 예약이 열려있네요?
@pingpong:  네,, 직원예약처럼 10시까지 시간도 보여지고 있어요
...
@keedi:     22시까지 보이는건 원래 그러지 않았나요?  버그가 아니라...
@pingpong:  아뇨 대여자에게는 5시 30분까지만 보였었어요
@keedi:     예전에 슬롯이 0이면 안보이게 해달라했다가, 안보이면 헷갈린다고 보이게 해달라해서 0이어도 시간대 자체는 보이게 했던걸로 기억이...
@keedi:     아 그러면 지금 서울시 아니면 5시30분까지 보이나요?  서울시만 22시까지 보이는건가요?
@pingpong:  서울시예약자도 동일하게 5시반이었을거에요. 아니었으면 6시이후로 예약자리없냐는 문의가 많이 왔을거에요^^
@keedi:     음 그래요? 갑자기 변경한것도 없는데 왜그러지...;;;
...
@keedi:     확인할게 2개인가요? 특정 날짜 이후로 안보이는거랑 22시까지 보이는거?
@pingpong:  네~
@pingpong:  user(114823) 참고가 되실까해서요. 김** 님이 오늘 13일 이후 안보인다고 문의한 분이라고 합니다.
@pingpong:  이런 문의건이 어제도 있었고, 옷장지기가 테스트해보았을 때도 같은 현상이었다고 합니다.
@pingpong:  김** 님은 일단 직원예약을 해주고 본인이 다시 취날예약을 하도록해서 덮어씌운 상태라 현재는 문제없이 보입니다.
@aanoaa:    네 고맙습니다
```

![a0296eaa-cc6f-4e78-af0b-89c9001fc21e](https://user-images.githubusercontent.com/138451/49819982-0f76fa00-fdba-11e8-8cc2-980a67b6435b.jpg)

**Comment by keedi** [comment]
관련해서 우선적으로 네트워크 트래픽, coffeescript, template, controller 순서로 동작 확인을 했습니다. 코드의 경우 버그가 있을 가능성이 낮다고 판단해서 역순으로 확인했는데 결과적으로는 버그가 아니었기 때문에 controller 부터 확인했다면 조금 더 빠르게 원인을 확인할 수 있었을 것 같습니다.

해당 예약 가능 목록을 얻어오는 부분은 `O::W::C::API` 모듈의 `api_gui_booking_list()` 함수입니다. 코드를 살펴보면 주석과 함께 정리한 부분이 있습니다.

```perl
    #
    # [GH 1366] 서울시 쿠폰 유효기간의 수정
    #
    if ( $self->session->{coupon_code} ) {
        my $coupon = $self->DB->resultset("Coupon")
            ->find( { code => $self->session->{coupon_code} } );
        if ($coupon) {
            my ( $event_name ) = split /\|/, $coupon->desc;
            if (   $self->config->{events}{$event_name}
                && $self->config->{events}{$event_name}{booking_expires} )
            {
                $self->config->{events}{$event_name}{booking_expires} =~ m/^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2}):(\d{2})$/;                                                                                                              
                $to = DateTime->new(
                    time_zone => $self->config->{timezone},
                    year      => $1,
                    month     => $2,
                    day       => $3,
                    hour      => $4,
                    minute    => $5,
                    second    => $6,
                );
                unless ($to) {
                    my $msg = "cannot create end datetime object";
                    $self->app->log->warn($msg);
                    $self->error( 500, { str => $msg, data => {}, } );
                    return;
                }
            }
        }
    }
```

2017년 서울시 쿠폰을 마감하면서 요청이 들어온 #1366 이슈와 직접적인 연관이 있습니다. 당시 쿠폰의 마감 일시를 정하는 기능을 서울시에서 요구하면서, 열린옷장의 요청으로 추가한 기능입니다. 이후로 쿠폰을 추가할때는 마감 일시를 설정파일에 지정하고, 해당 일시를 확인해 예약시 열람 가능한 목록을 제한한 기능입니다.

현재 2018년 서울시 쿠폰의 마감시각은 2018년 12월 13일 23시 59분 59초로 설정되었으며, 이로 인해 14일 부터의 날짜는 열람할 수 없으며, 이는 정상입니다. 관련해서 마감 일시가 바뀌었다면 마감 일시를 알려주셔서 수정하면 변경한 내용이 적용됩니다. 물론 관리자 권한으로 예약을 진행하는 경우 이런 제약보다 우선 하므로, 이 점 주의해야 합니다.

**Comment by keedi** [comment]
#1508 이슈에서 시간대가 다 보여서 디버깅을 진행하시고 있는데, 상기 갈무리 화면을 보면, 예약자의 이메일 주소가 열린옷장 주소, 즉 관리자임을 알 수 있습니다. 관리자의 경우 모든 시간대 열람이 가능합니다. 따라서 #1508 이슈에서 @aanoaa 님께서 관리자로 예약한 것 같다고 분석한 내용이 맞을 가능성이 높습니다.

다만, 관리자임에도 불구하고, 13일까지 밖에 열람이 되지 않는 것은 해당 기기에서 쿠폰 관련 예약을 시도 한 적이 있기 때문으로 추정됩니다. 쿠폰 관련 예약을 시도시 초창기 예약 코드가 쿠키에 쿠폰 예약임을 기록하는 식으로 구현되었는데, 이것이 서울시 관련 사업이 급하게 커지면서, 그대로 사용하게 되었는데, 이후 절차나 케이스가 복잡해지면서 쿠키로만 판단하기가 어려워져 발생하는 문제입니다. 다만, 관리자가 쿠폰을 사용할 경우가 없으며, 일반 사용자가 쿠폰을 사용할 경우는 있지만 쿠폰 사용자가 일반 사용자가 되는 경우는 현실적으로 없기 때문에 일단 넘어가기로 한 known issues이긴 합니다. 즉, 상기 캡쳐 화면은, 추측컨데, 관리자가 사용자의 요청으로 쿠폰 예약을 시도 했다가, 13일까지 밖에 안보이는 것을 확인 한 뒤, 다시 관리자로 열람을 하는데, 이때는 쿠폰 정보가 있기 때문에 여전히 13일까지만 보이지만, 관리자므로 밤 시간대 슬랏도 열람이 된 것으로 보입니다.

**Comment by pingpongworks** [comment]
본 이슈는 원인이 오류가 아니라, #1366 이슈의 요청이었음이 밝혀졌으므로 닫겠습니다. 올해 쿠폰 마감시한 요청은 새로운 이슈로 요청드리겠습니다.
