### ISSUE TITLE
서울시 쿠폰(seoul-2018-1)의 온라인 주문을 마감함

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1511]
2018년 마감시한에 대해 담당부서에서 **12월 20일 경으로 예상**할 뿐 아직 명확한 날짜를 결정하지 못하고 있습니다. 마감방법에 대해서도 마감날짜를 명확히 하여 이후로 아예 이용을 못 하게 하는 방법과 일단 12월 31일까지 예약이 가능하여 이용한 후 이월하여 내년 1월에 정산하는 방법 두 가지 중 선택을 고려하고 있습니다. 며칠 내에 마감시한과 정산방법을 결정한다고 하니 **일단은 13일 이후로 예약이 가능하도록 마감시한을 변경**해야 할 듯 합니다.

2017년의 경우에는 예산이 완전 소진되었기 때문에 급하게 12월 13일에 마감을 했지만(#1366) 올해는 추가 예산을 편성한 덕분에 담당부서에서 여유있게 마감하여 최대한 많이 이용할 수 있도록 배려하고자 합니다. 그런데 그렇다고 지금부터 12월 31일까지 완전히 열어놓으면 나중에 뒷감당이 불안합니다.

20일 경이라고 이야기하고 있는 것으로 보아, 일단은 12월 19일 이후로 방문예약이 안 되도록 부탁드립니다. **온라인 이용자는 배송일이 12월 19일 (착용일은 12월 20일) 이후로 쿠폰 주문이 안되도록 부탁드립니다.**

**Comment by keedi** [comment]
이 이슈는 opencloset/OpenCloset-Share-Web 쪽에 열어주셔야합니다.

**Comment by keedi** [comment]
https://github.com/opencloset/OpenCloset-Share-Web/issues/215 이슈 쪽으로 내용 옮겼습니다.

**Comment by pingpongworks** [comment]
앗, 그러네요. share 이슈네요. 옮겨주셔서 감사합니다.
