### ISSUE TITLE
쿠폰 시스템의 개선

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#1517]
쿠폰의 만료기간을 염두에 두고 쿠폰을 발급해서 사용했지만, 쿠폰의 만료기간이 무용지물인 상황입니다.
만료기간은 예약가능한 일시 인데, 어떤 지자체가 원하는 것은 대여가능한 일시 입니다.
(20xx 년도 12월 31일 까지 대여할 수 있게 해주세요.)

지금의 시스템은 이를 만족할 수 없습니다.
만료기간이 `2018-12-31` 인 쿠폰은 `2018-12-31` 일에 `2019-01-01` 일로 예약하고,
`2019-01-01` 일에 대여할 수 있기 때문입니다.

---

**오프라인 대여**

지금 시스템대로 예약일을 기준으로 이벤트의 마감일을 원하는 지자체도 있고,
대여일을 기준으로 이벤트 마감일을 원하는 지자체도 있습니다.
(우리의 정책은 예약일을 기준으로 한다 라고 설득하기를 바랐지만 되지 않았습니다.)

이를 가능하게 하기 위해서는 쿠폰타입별로 마감일의 기준이 달라져야 합니다.

-   A 타입의 쿠폰은 예약하는 날짜를 기준으로 마감한다.
-   B 타입의 쿠폰은 대여일을 기준으로 마감한다.

라고 했을때에,
A 타입에 대해서는 지금처럼 예약하는 날은 마감일을 넘길 수 없고, 예약이 되면 언제든지 사용이 될 수 있습니다.
B 타입은 마감일 이후날짜는 예약이 될 수 없고 당연히 마감일 이후에 대여도 될 수 없습니다.

쿠폰을 발급할때에 이러한 부분을 염두에 두고 타입에 따라 동작하도록 변경해야 합니다.
타입이 더 추가될 수도 있으므로 이를 수용할 수 있도록 유연하게 변경해야 하겠습니다.

---

**온라인 대여**

A 타입의 쿠폰은 지금처럼 주문확정일은 마감일을 넘길 수 없고, 주문이 확정되면 대여가 가능합니다.
B 타입의 쿠폰은 대여일은 마감일을 넘길 수 없고 이것을 결제단계에서 사용자에게 안내를 해야 합니다.
(결제를 위해 쿠폰코드를 입력했을때에 `해당 쿠폰은 20xx년 x월 x일 까지 사용가능한 쿠폰입니다.` 라고 예외처리)

처럼 변경해야 하겠습니다.

현재 발급되서 운영중인 쿠폰이벤트들에 대해 각 쿠폰들이 어떠한 타입인지 구분하는 작업이 필요합니다.
그래야 프로그램을 변경하는 과정에서 올바르게 데이터를 마이그레이션 할 수 있습니다.

**Comment by aanoaa** [comment]
현재는 쿠폰종류의 구분을 `coupon.desc` 컬럼에 기록해서 사용합니다.
이벤트별로 관리하고 발급되는 쿠폰들을 이벤트로 연결 시키는 방법을 사용할까 합니다.

[기증시 특정기업을 통한 기증 임을 확인할 수 있는 방법 donation#107](https://github.com/opencloset/donation/issues/107) 에서 필요에 의해 `event` 테이블을 만들고 범용적으로 사용하려고 했는데,
시간이 없어서 꿈을 이루지 못했습니다.

이 테이블에 각 쿠폰 이벤트를 기록하고 이를 활용할 수 있도록 개선하겠습니다.
이벤트가 추가 될때마다 통계작업이 번거로웠는데 시간이 된다면 이부분도 함께 개선하도록 하겠습니다.

**Comment by keedi** [comment]
지금 좀 이해가 안되는게 쿠폰의 만료일시가 무용지물이 아닙니다. 이벤트별 마감일시도 그렇고 지금 다 의도하는대로 동작하고 있구요. 현 동작과 관련해 충분히 논의도 잘 이루어져서 협의하에 진행됐구요. 개선은 더 필요할 수는 있지만 현 상황 인식은 좀 많이 다른 것 같아 걱정입니다. 더불어 앞으로 붙일 시스템은 가능하면 오동작의 가능성을 최대한 줄일 수 있는 방향으로 진행해야할 것 같습니다. 특히 현재 알려진 내재된 원인을 규명하지 못한 오동작를 잡지 못한채로 기능을 추가하는 부분은 음, 글쎄요...

> 지금의 시스템은 이를 만족할 수 없습니다.
> 만료기간이 2018-12-31 인 쿠폰은 2018-12-31 일에 > 2019-01-01 일로 예약하고,
> 2019-01-01 일에 대여할 수 있기 때문입니다.

맞는 부분도 있고 아닌 부분도 있습니다. 지자체 쿠폰은 이벤트 마감이 있기 때문에 이벤트 만료 설정이 제대로 됐다면,  오프라인은 예약일 방문, 대여가 원칙이므로 12월 31일에 와서 1월 1일에 빌릴 수는 없습니다. 오프라인은 예약일이 곧 대여일입니다. 이 부분은 이것이 아니라면 열린옷장의 정책이 또 바뀐건지도 의문이구요.

**Comment by aanoaa** [comment]
예약한 날짜와 예약일의 혼동이 있는 것 같습니다.
사전에 예약하고 대여일에 방문합니다.

지금의 시스템은 12/31일에 1/1일로 예약하고 1/1일 방문해서 대여가능합니다.

**Comment by aanoaa** [comment]
이벤트의 시작일도 마감일과 비슷하게 고려되어야 할 것 같습니다.
2019-01-01 부터 예약을 하는 것과 2019-01-01 부터 대여를 하는 것은 다릅니다.

-   예약한 날짜로 이벤트 시작
-   대여일로 이벤트 시작

시작과 마감의 경우의 수를 고려하면 4개의 쿠폰 유형이 있을 수 있습니다.
이런 부분을 지자체에서 언급한 것은 아니지만 요청이 오기전에 고려해볼만 합니다.

**Comment by aanoaa** [comment]
하나의 컬럼에 `이벤트시작타입|이벤트종료타입` 으로 정의해둘 수 있습니다.
예약한 날짜를 `reserve`, 대여일을 `rental` 로 한다면,
쿠폰타입을 아래와 같이 지정할 수 있습니다.

-   `reserve|reserve`
-   `reserve|rental`
-   `rental|reserve`
-   `rental|rental`

**Comment by aanoaa** [comment]
`event` 가 대여 도메인에서만 쓰이지는 않습니다.

이미 기증 서비스쪽에 이벤트가 있었고 사용 중 입니다.
이를 대여 서비스쪽의 이벤트로 확장해서 사용하고자 스키마 변경이 필요합니다.

계획입니다.

1.  `event_type` 테이블을 추가합니다.
    -   id
    -   type: `시작 타입|마감 타입` (ex. `reserve|rental`)
    -   domain: `rental or donation or volunteer or ...`
2.  coupon 의 테이블 스키마를 변경합니다.
    -   `free_shipping` 은 event 에도 추가합니다.
    -   이미 존재하는 `coupon.free_shipping` 은 `event.free_shipping` 을 override 합니다.
    -   `event.end_date` 가 각 이벤트별 마감일이지만 이미 존재하는 `coupon.expires_date` 가 `NULL` 이 아니라면 이를 override 합니다.

---

DB 스키마가 준비된 이후에는,

-   진행 중인 쿠폰 이벤트를 `event` 테이블의 데이터로 넣고 마이그레이션에 필요한 작업을 수행합니다.
-   이 데이터를 기반으로 application 의 예약/결제/대여 로직을 변경하고 테스트합니다.
-   `event` 테이블을 활용해서 각 이벤트별 일별통계 작업을 교체합니다.
-   각 지자체별 이벤트 타입과 마감일을 올바르게 설정합니다.

**Comment by pingpongworks** [comment]
쿠폰을 처음 발행할 때 거의 모든 쿠폰의 유효기간을 2018년 x월 x일~2018년 12월 31일로 발행했습니다. 12월 31일까지의 의미를 `대여일이 12월 31일 이전이 되어야함`으로 이해했습니다. 말 그대로 `유효기간`이므로 2019년 1월 1일부터는 가지고 있어도 소용이 없어지는 것으로요. 

현재 광주, 군포 같은 경우 처음 발행했던 대로 12월 31일까지 사용할 예정이고, 공백없이 무료대여를 진행할 예정이므로 2019년 1월 1일부터는 새로운 쿠폰을 발행해서 사용해야 한다고 안내했습니다.

>지금의 시스템은 12/31일에 1/1일로 예약하고 1/1일 방문해서 대여가능합니다.

그렇다면 광주, 군포의 경우에도 예약제한일을 12월 31일로 따로 설정해야 하나요?

**Comment by aanoaa** [comment]
`2018년도까지 사용가능한 쿠폰` 이라는 문장에 대해 저와 다르게 생각하신 것 같습니다.

저는 A 타입으로 본 것이고, 지자체와 대령님은 B 타입으로 본 것입니다.
그럴 수 있고 고려되지 못했기에 이번기회에 해결하고자 합니다.

공백없이 이벤트가 진행되는 광주, 군포와 같은 경우는 어떤 타입이든지 상관이 없습니다.
새로 발행하기만 하면 됩니다. 다만 새로 발행할때에는 마감일이 어떤 타입인지 파악해 두어야
하겠습니다.

A 타입은 마감일+1m 후에 정확한 대여자 수 산정이 가능하고,
B 타입은 마감일 다음날 산정이 가능합니다.

내년 계획에 상관없이 현재 진행중인 모든 쿠폰 이벤트 각각에 대해 어느 타입인지
알려주셔야 합니다.

**Comment by pingpongworks** [comment]
>B 타입은 마감일 다음날 산정이 가능

말씀해주신 B타입이 되려면 어떻게 바뀌어야 하는거죠? 온라인도 다음날 산정이 가능해지나요?

**Comment by pingpongworks** [comment]
>A 타입이라면 마감일 이전날짜에 마감일 이후 날짜를 예약할 수 있지만,
B 타입은 마감일 이전날짜로만 방문예약일을 지정할 수 있습니다.

라고 행아웃으로 답변해주셨는데, 질문 하나 더요~

지금 17일 발송/으로 안양쿠폰 온라인 주문이 하나 들어와있는데
그러면, B타입으로 설정할 경우에 17일 발송 주문건은 안양쿠폰으로 무료처리가 안 되는 건가요?

**Comment by aanoaa** [comment]
아직 프로그램이 패치가 되기 전 예외 건들은,
어떻게 할지 정책을 정하고 직접 데이터를 변경해서 처리해야 할 것 같습니다.

**Comment by pingpongworks** [comment]
네, 그럼 타입별로 정리해보겠습니다.

- 서울 - A타입 / 20일 예약 마감 
- 안양 - A타입 / 16일 예약 마감
- 용인 - B타입 / 30일 대여 마감
- 고양 - B타입 / 31일 대여 마감
- 군포 - B타입 / 31일 대여 마감
- 광주 - B타입 / 31일 대여 마감

정산시에는 안양 만 16일 이후에 예약되어 있는 방문대여 건과, 주문되어 있는 온라인대여 건만 포함해서 정산하면 됩니다. 
서울시는 어차피 취날 페이지에서 대여로 확정되어 있는 내역 가지고 정산하는 것이고 온라인 건이 많지 않으니까 별 문제없을 거 같습니다.

**Comment by aanoaa** [comment]
`coupon_limit` 을 고려해야 합니다.
coupon 의 이벤트와 관련된 메타 데이터는 `event` 에서 참조하게 되었는데,
쿠폰의 사용제한 은 `coupon_limit` 테이블이 활용됩니다.

`event.limit` 을 추가해서 사용하면 `coupon_limit` 테이블대신에 사용할 수 있습니다.

이벤트와 쿠폰 생성하는 스크립트에서 처리하도록 하면 무엇을 쓰던지 상관없겠습니다.
`event.limit` 을 사용하고 싶지만 추가작업이 발생하므로 기존의 `coupon_limit` 을 활용하겠습니다.

**Comment by aanoaa** [comment]
이제까지 발급된 모든 쿠폰의 종류중에 만료기간이 아직 끝나지 않은 이벤트는 위에 적어주신 것들 뿐 입니다.
제가 걱정했던 것은 지난 쿠폰중에 만료기간이 없는 쿠폰이 사용되었을때 이벤트로 등록해두지 않으면 통계수집이 아니됩니다.

다행히도 위에 언급해주신 6개의 이벤트만이 현재 active 합니다.
지난 이벤트들은 등록해주지 않아도 되겠습니다.

거기에 테스트를 위한 이벤트 `test201801` 도 추가하도록 하겠습니다.

**Comment by aanoaa** [comment]
서울시를 제외한 모든 이벤트가 배송비 까지 지원합니다.
제가 잘못 알고 있는 것이라면 알려주세요.

**Comment by aanoaa** [comment]
# Table of Contents

1.  [release](#orgddb87ec)
2.  [install & data migration](#org244613d)
3.  [deploy](#org16f328a)
4.  [test](#orge09f2ae)

기능 구현은 완료된 것 같습니다.
많은 테스트를 해봐야 하지만 시간과 인력이 부족합니다.

여러 모듈이 배포되고 의존성 있는 서비스들이 차례대로 배포되어야 합니다.
데이터 마이그레이션 작업도 이루어져야 합니다.

작업절차에 대해 나열하고 이 순서를 지켜야 하겠습니다.


<a id="orgddb87ec"></a>

# release

-   opencloset
-   OpenCloset::Schema
-   OpenCloset::Plugin::Helper
-   OpenCloset::Coupon::Web
-   OpenCloset::Share::Web
-   OpenCloset::Cron::Visitor

에서 feature 브랜치를 master 로 머지하는 작업이 우선되어야 합니다.
여기에서

-   OpenCloset::Schema
-   OpenCloset::Plugin::Helper
-   OpenCloset::Cron::Visitor

모듈은 버전을 올리고 closetpan 에 올려야 합니다.


<a id="org244613d"></a>

# install & data migration

서버에서

`OpenCloset-Schema/db/alter/142-event-type.sql` 쿼리를 실행해서 없는 테이블을 만들고 컬럼을 추가합니다.

-   OpenCloset::Schema
-   OpenCloset::Plugin::Helper
-   OpenCloset::Cron::Visitor

의 새로운 버전을 설치합니다.

아래 shell 스크립트를 실행해서 이벤트를 DB 에 등록합니다.

    #!/bin/sh
    perl bin/event.pl \
         --name        'seoul-2018-1' \
         --title       '취업날개' \
         --type        'reserve|reserve' \
         --desc        'http://dressfree.net' \
         --sponsor     '서울특별시' \
         --year        2018 \
         --start_date  '2018-01-01' \
         --end_date    '2018-12-20 23:59:59'
    
    perl bin/event.pl \
         --name        'anyang201801' \
         --title       '안양시' \
         --type        'reserve|reserve' \
         --desc        '' \
         --sponsor     '안양시' \
         --year        2018 \
         --freeshipping \
         --start_date  '2018-01-01' \
         --end_date    '2018-12-16 23:59:59'
    
    perl bin/event.pl \
         --name        'yongin201801' \
         --title       '용인시' \
         --type        'reserve|rental' \
         --desc        '' \
         --sponsor     '용인시' \
         --year        2018 \
         --freeshipping \
         --start_date  '2018-01-01' \
         --end_date    '2018-12-30 23:59:59'
    
    perl bin/event.pl \
         --name        'goyang201801' \
         --title       '고양시' \
         --type        'reserve|rental' \
         --desc        '' \
         --sponsor     '고양시' \
         --year        2018 \
         --freeshipping \
         --start_date  '2018-01-01' \
         --end_date    '2018-12-31 23:59:59'
    
    perl bin/event.pl \
         --name        'gunpo201801' \
         --title       '군포시' \
         --type        'reserve|rental' \
         --desc        '' \
         --sponsor     '군포시' \
         --year        2018 \
         --freeshipping \
         --start_date  '2018-01-01' \
         --end_date    '2018-12-31 23:59:59'
    
    perl bin/event.pl \
         --name        'gwangju201801' \
         --title       '광주시' \
         --type        'reserve|rental' \
         --desc        '' \
         --sponsor     '광주시' \
         --year        2018 \
         --freeshipping \
         --start_date  '2018-01-01' \
         --end_date    '2018-12-31 23:59:59'
    
    perl bin/event.pl \
         --name        'test201801' \
         --title       '테스트' \
         --type        'reserve|rental' \
         --desc        '테스트를 위한 이벤트' \
         --sponsor     '열린옷장' \
         --year        2018 \
         --start_date  '2018-01-01' \
         --end_date    '2018-12-31 23:59:59'

아래 쿼리를 실행해서 이미 등록되어 있는 쿠폰들에 지금 생성한 이벤트를 연결합니다.
이름이 제멋대로 되어있던 통계 데이터도 수정합니다.

    SET NAMES utf8;
    
    UPDATE `coupon`
      SET `event_id` = (SELECT `id` FROM `event` WHERE `name` = 'seoul-2018-1' LIMIT 1)
      WHERE `desc` LIKE 'seoul-2018-1|%';
    
    UPDATE `coupon`
      SET `event_id` = (SELECT `id` FROM `event` WHERE `name` = 'anyang201801' LIMIT 1)
      WHERE `desc` = 'anyang201801';
    
    UPDATE `coupon`
      SET `event_id` = (SELECT `id` FROM `event` WHERE `name` = 'goyang201801' LIMIT 1)
      WHERE `desc` = 'goyang201801';
    
    UPDATE `coupon`
      SET `event_id` = (SELECT `id` FROM `event` WHERE `name` = 'gunpo201801' LIMIT 1)
      WHERE `desc` = 'gunpo201801';
    
    UPDATE `coupon`
      SET `event_id` = (SELECT `id` FROM `event` WHERE `name` = 'gwangju201801' LIMIT 1)
      WHERE `desc` = 'gwangju201801';
    
    UPDATE `coupon`
      SET `event_id` = (SELECT `id` FROM `event` WHERE `name` = 'yongin201801' LIMIT 1)
      WHERE `desc` = 'yongin201801';
    
    UPDATE `coupon`
      SET `event_id` = (SELECT `id` FROM `event` WHERE `name` = 'test201801' LIMIT 1)
      WHERE `desc` = 'test201801';
    
    UPDATE `visitor` SET `event` = 'anyang201801' WHERE `event` = 'anyangyouth';
    UPDATE `visitor` SET `event` = 'gunpo201801'  WHERE `event` = 'gunpo';
    UPDATE `visitor` SET `event` = 'seoul-2018-1' WHERE `event` = 'seoul-2018';


<a id="org16f328a"></a>

# deploy

-   visit, staff
-   OpenCloset::Coupon::Web
-   share
-   OpenCloset::Cron::Visitor

순서대로 서비스를 업그레이드 하고 재시작 합니다.


<a id="orge09f2ae"></a>

# test

그 다음엔 제대로 동작하는지 테스트 해봐야 합니다.
저는 데이터를 바꿔가며 테스트 해볼 수 있었는데 실제로는
타입과 만료기간이 다양한 몇가지 쿠폰을 미리 발급해놓고 사용해보는 수 밖에 없을 것 같습니다.

이를 고려해서 테스트용 쿠폰을 발급하는 쿼리도 필요하겠습니다.

**Comment by pingpongworks** [comment]
>서울시를 제외한 모든 이벤트가 배송비 까지 지원합니다.
제가 잘못 알고 있는 것이라면 알려주세요.

- 고양시, 광주시 - 온라인발송비만 지원 (반납택배비는 본인 부담)
- 용인시, 안양시, 군포시 - 온라인발송비, 반납택배비 모두 지원

**Comment by aanoaa** [comment]
적용하였습니다.

**Comment by aanoaa** [comment]
https://github.com/opencloset/OpenCloset-Coupon-Web/pull/9

이것만 배포방법을 몰라서 서버에 적용하지 못했습니다.
@keedi 님이 보시고 배포해주시면 되겠습니다.

취업날개 쿠폰발행을 위한 웹서비스 입니다.
배포가 되지 않아도 정상적으로 동작해야 합니다.

**Comment by aanoaa** [comment]
시간이 촉박해서 테스트를 많이 해보지 못했습니다.
내일 운영시간에 지원할 준비를 하고 있겠습니다.
혹시 잘못된 점이 발견되면 전화도 좋고 이슈로도 좋으니 알려주세요.
@pingpongworks

**Comment by aanoaa** [comment]
이벤트별 쿠폰 사용제한을 적용하였습니다.
온라인/오프라인 모두 적용됩니다.

> 서울 - A타입 / 20일 예약 마감
> 안양 - A타입 / 16일 예약 마감
> 용인 - B타입 / 30일 대여 마감
> 고양 - B타입 / 31일 대여 마감
> 군포 - B타입 / 31일 대여 마감
> 광주 - B타입 / 31일 대여 마감

**Comment by pingpongworks** [comment]
감사합니다~ 주말에 수고많으셨습니다^^ 제가 테스트로 확인을 다 해볼 수 없어서 내일 출근해서 문제점 발견되면 연락드리겠습니다. 급하게 요청드렸는데 빠르게 작업해주셔서 감사드립니다.

**Comment by pingpongworks** [comment]
예약마감 / 대여마감 표현에 대한 이해가 달라서 서울시 쿠폰이 24일 이후에도 예약이 되고 있습니다. 마감이 필요한 부분은 예약마감의 의미는 "예약행위 마감"이었습니다. 20일이 대여일로 마감되려면 "대여 마감"으로 요청되어야 합니다. A타입은 예약 마감일 이후에도 예약이 계속 가능하므로, 대여 마감일을 따로 설정해야 합니다. 

**서울시쿠폰이 원하는 것은 20일까지 예약행위가 가능하고, 23일로 반납까지 마감되어서 24일에 정산하기를 원합니다.** 다른 지자체는 연속적으로 진행될 거라 마감에 오차가 있어도 크게 문제되지 않습니다.   

계속 좀 헷갈리는데 둘 중에 어떤 방법이 맞는건지요?

1. A타입으로 두고, 20일을 예약행위마감일, 23일을 대여마감일로 설정한다
2. B타입으로 수정하고, 대여마감일을 23일로 설정한다

**Comment by aanoaa** [comment]
> 예약마감 / 대여마감 표현에 대한 이해가 달라서 서울시 쿠폰이 24일 이후에도 예약이 되고 있습니다. 마감이 필요한 부분은 예약마감의 의미는 "예약행위 마감"이었습니다. 20일이 대여일로 마감되려면 "대여 마감"으로 요청되어야 합니다. A타입은 예약 마감일 이후에도 예약이 계속 가능하므로, 대여 마감일을 따로 설정해야 합니다.
> 
> 서울시쿠폰이 원하는 것은 20일까지 예약행위가 가능하고, 23일로 반납까지 마감되어서 24일에 정산하기를 원합니다. 다른 지자체는 연속적으로 진행될 거라 마감에 오차가 있어도 크게 문제되지 않습니다.
> 
> 계속 좀 헷갈리는데 둘 중에 어떤 방법이 맞는건지요?
> 
> A타입으로 두고, 20일을 예약행위마감일, 23일을 대여마감일로 설정한다
> B타입으로 수정하고, 대여마감일을 23일로 설정한다

대여마감일을 이야기하시면 헛갈립니다.

이 이슈에서 사용한 마감일이라고 하는 것을 쿠폰을 사용함에 있어서 유효한 날짜입니다.
옷장에서 대여 반납 프로세스 한사이클을 의미하는 마감과는 다릅니다.

연체나 연장의 변수가 있어서 20일 대여했다고 23일 반납하는 것은 아닙니다.

---

두개의 쿠폰 타입에 대해서 아래와 같이 정의하였는데, 혼란이 있으셨던 것 같습니다.

> -   A 타입의 쿠폰은 예약하는 날짜를 기준으로 마감한다.
> -   B 타입의 쿠폰은 대여일을 기준으로 마감한다.
> 
> 라고 했을때에,
> A 타입에 대해서는 지금처럼 예약하는 날은 마감일을 넘길 수 없고, 예약이 되면 언제든지 사용이 될 수 있습니다.
> B 타입은 마감일 이후날짜는 예약이 될 수 없고 당연히 마감일 이후에 대여도 될 수 없습니다.

**Comment by aanoaa** [comment]
> 서울시 이 시간 이후로 쿠폰 예약이 안 되도록 부탁드릴게요
> 6시 이후로요
> 지금 작업 어려우면 이따 저녁에라도 부탁해요~

원하셨던 것을 추측해본다면,
서울시 쿠폰으로는 20일까지 대여할 수 있는 B 타입의 쿠폰인 것 같습니다.

아직까지는 A 타입으로 설정되어 있기 때문에, 오늘 자정 전까지는 쿠폰을 사용해서 20일 이후에도 방문예약을 할 수 있습니다.
이것을 B 타입으로 바꾼 이후부터는 그렇게 되지 않습니다.

서울시 이벤트의 타입을 A 에서 B 로 바꾸고 마감일을 `2018-12-20 23:59:59` 로 지정하겠습니다.
그리고 이미 서울시 쿠폰으로 20일 이후에 방문예약한 주문서를 추려서 전달해드리겠습니다.

**Comment by aanoaa** [comment]
실행해야 할 쿼리 입니다.
서울시 이벤트의 타입을 예약일 기준에서 대여일 기준으로 바꿉니다.
마감날짜는 이미 `2018-12-20 23:59:59` 으로 되어있습니다.

    UPDATE `event` SET `event_type_id` = 2 WHERE `id` = 3;

**Comment by aanoaa** [comment]
적용하였습니다.

**Comment by aanoaa** [comment]
```sql
SELECT o.id, b.`date`, u.name, ui.phone, ui.gender FROM `order` o
  JOIN booking b    ON o.booking_id = b.id
  JOIN coupon c     ON o.coupon_id  = c.id
  JOIN user u       ON o.user_id    = u.id
  JOIN user_info ui ON o.user_id    = ui.user_id
  JOIN event e      ON c.event_id   = e.id
  WHERE o.coupon_id IS NOT NULL
  AND e.id = 3
  AND b.id >= 63840;  -- 2018-12-21 10:00:00 이후 예약
```

**Comment by aanoaa** [comment]
결과는 이메일로 전달해 드렸습니다.

**Comment by pingpongworks** [comment]
목록 확인했습니다. 

A타입의 예약일의 개념을 이제 이해했는데, 사실상 현실적으로 이벤트를 마감하려면 대여일 기준이 되어야 일정한 날짜에 매듭이 지어지고 정산을 할 수 있기 때문에 A타입의 “예약하는 날짜”기준으로는 실질적인 ‘마감’이 되기는 어렵습니다. 

내년에는 거의 모든 경우에 **B타입 대여일 기준**으로 마감을 해야하는 것으로 정리가 됩니다. 

감사합니다. 이슈 닫을게요.
