### ISSUE TITLE
쿠폰으로 예약 하고 대여했지만 쿠폰이 사용안된 주문서

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#1522]
주문서 번호 126897 는 대여중이고 쿠폰으로 예약되었지만 카드로 결제되었습니다.
수트 쿠폰으로 예약했으면 보통 쿠폰으로 결제하게 되는데 이 주문서는 그렇지 않습니다.
확인이 필요한 것 같습니다.

**Comment by pingpongworks** [comment]
대여자에게 직접 확인한 결과 쿠폰으로 결제한 분이 맞습니다. 결제담당자가 실수로 '카드'로 선택해서 쿠폰결제가 안 된 거 같습니다. **사용된 쿠폰**으로 변경 요청드립니다.

**Comment by pingpongworks** [comment]
시기가 지난 이슈이므로 닫겠습니다.
