### ISSUE TITLE
지자체 쿠폰 이용내역 통계페이지 업데이트 오류

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1530]
![image](https://user-images.githubusercontent.com/17288038/50960087-e4421080-1507-11e9-8f4b-447e3e1b69b0.png)

2019년 통계페이지가 전혀 업데이트 되고 있지 않습니다. 
이미 안양시, 남양주시, 고양시 등 이용자가 있는데도 모든 지자체의 이용내역 통계페이지가 0으로 뜹니다. 
지자체 담당자가 확인하는 페이지도 같은 현상이라고 합니다. 오류 수정 부탁드립니다.

**Comment by aanoaa** [comment]
저의 잘못입니다.
수집된 날짜부터 계속해서 0건으로 카운트되고 있습니다.
수정 후에 누락된 수치까지 복구하도록 하겠습니다.

**Comment by aanoaa** [comment]
해결되었습니다.

**Comment by pingpongworks** [comment]
확인했습니다~
