### ISSUE TITLE
[서울시쿠폰] 주문서 쿠폰탭과 관리자페이지 연동 오류

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1535]
<img width="612" alt="2019-01-16 10 16 05" src="https://user-images.githubusercontent.com/17288038/51220293-f7c20100-1977-11e9-8978-be9f19e364e0.png">

현재 예약시 수지니와 관리자페이지가 쿠폰탭을 통해 연동되지 않습니다. 대여자가 방문하면 스태프가 주문서의 사용가능 탭을 눌러  관리자 페이지로 이동하여 면접증빙을 확인해야하는데 탭을 눌러도 연동되지 않습니다. 연동되도록 부탁드립니다. 

<img width="612" alt="2019-01-16 12 01 02" src="https://user-images.githubusercontent.com/17288038/51223769-95243180-1986-11e9-8d93-4007a69e1cdf.png">
사용자정보 하단의 쿠폰 탭에서도 관리자페이지 정보로 이동이 가능해야 합니다. 현재는 쿠폰탭을 누르면 주문서로 이동합니다.

**Comment by pingpongworks** [comment]
서울시쿠폰으로 예약하지 않고 온 일반대여자가 
`방문예약``결제대기 `상태에서 쿠폰으로 다시 예약했을 경우 덮어씌워지는 기능도 오류입니다. 
수지니에서는 `대여가능한 서울시쿠폰`상태로 바뀌어 보이는데, 
취날 관리자페이지에는 예약내역이 연동되어 있지 않습니다. 
이럴 경우, 현장에서 면접증빙도 확인할 수가 없고, 나중에 정산에서도 누락됩니다. 

orders/129475
orders/129551
orders/129552

위 3개의 주문서가 그런 경우입니다. 

결제대기 상태에서 덮어씌웠을 때 연동이 늦는 건지, 아예 안 된 건지 확인이 필요합니다.

**Comment by aanoaa** [comment]
라벨의 링크는 수정되었습니다.

```sql
UPDATE event SET title = 'xxxx' WHERE id = 15;
```

**Comment by pingpongworks** [comment]
오류 복구 확인했습니다.
