### ISSUE TITLE
[서울시쿠폰] 방문예약/결제대기 상태에서 쿠폰예약으로 덮어씌우기 기능 오류

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1536]
서울시쿠폰으로 예약하지 않고 온 일반대여자가 
`방문예약` `결제대기 `상태에서 서울시쿠폰으로 다시 예약했을 경우 덮어씌워지는 기능 오류입니다. 

수지니에서는 `대여가능한 서울시쿠폰`상태로 바뀌어 보이는데, 
취날 관리자페이지에는 예약내역이 연동되어 있지 않습니다. 
이럴 경우, 현장에서 면접증빙도 확인할 수가 없고, 나중에 정산에서도 누락됩니다. 

    열린옷장에 예약내역이 있는 자가 
    방문예약/결제대기 상태에서 취날 포털에 로그인해서 쿠폰으로 예약을 해서 
    수지니에서 서울시쿠폰 상태로 바뀌면 
    관리자페이지의 예약내역이 사라지고 있다

라고 밖에 추정되지 않습니다. 이해하기 어려운 상황입니다.

>orders/129475
>orders/129551
>orders/129552

위 3개의 주문서가 그런 경우입니다.

**Comment by aanoaa** [comment]
> 관리자페이지의 예약내역이 사라지고 있다

그냥예약 -> 쿠폰으로 예약 변경
했을때에 검색이 아니되어서 사라지고 있다고 표현하신 것 같습니다.
사라진 것은 아니고 상태가 비어서 검색이 아니되고 있습니다.
이게 원래부터 이랬던 것 인지, 올해들어 바뀐 것 인지 파악이 필요합니다.

**Comment by aanoaa** [comment]
상태변경은 익일에 일괄로 이루어집니다.

`/orders/129475` 주문서를 통해서 상세화면에 접근할 수 있습니다.
전달받은 API 를 통해서 예약시간을 변경하는 request 를 했는데, 예약상태가 비어있습니다.

해당업체에 문의해서 왜 없는 것인지 문의해야 합니다.
지난번에도 같은 이슈가 있었던 것으로 기억합니다.
프로그램의 버그가 아닐까 싶습니다.
@pingpongworks

옷장지기가 예약했던 내역을 가지고 예약상태 변경을 테스트하고 성공했습니다.
익일 일괄로 상태를 변경하는 작업은 동작할 것 같습니다.

**Comment by aanoaa** [comment]
담당자의 휴대폰으로 연락해 봤는데 안받습니다.
이메일로 문의를 해주세요.

**Comment by aanoaa** [comment]
해당 관리자 페이지에서 예약상태가 없을때에 사용자 이름등으로 검색이 아니되어서
예약내역이 사라졌다고 오해하셨지만,

주문서에서 라벨클릭이 안되는 이슈 #1535 가 해결되어서 직접 페이지에 접근할 수 있습니다.

**Comment by pingpongworks** [comment]
방문예약/결제대기 상태에서 덮어씌우기 예약을 했을 때, `예약중` 상태는 되지 않지만, 1시 5분 동기화 이후 `대여완료` 가 되어 관리자페이지에 정상적으로 뜨는 것을 확인했습니다. 일단 정산에서 누락될 우려는 사라졌다고 판단됩니다. 이 이슈는 이만 닫겠습니다.
