### ISSUE TITLE
방문예약 창에 무료대여 안내 정보 추가

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1539]
![-](https://user-images.githubusercontent.com/17288038/51375571-96ea2280-1b49-11e9-9efa-91510577bcfe.jpg)

서울시와 경기지역 무료대여 프로그램이 다양해진 만큼 예약시 정보를 알고 이용할수 있도록 방문예약창 하단의 정보를 위와 같이 보완하고자 합니다. 

- 서울시 무료대여 탭을 클릭하면 서울시 일자리 포털로 연결
http://dressfree.net/main/main.php

- 경기지역 무료대여 탭을 클릭하면 열린옷장 홈페이지의 경기지역 무료대여 안내 페이지로 연결
https://theopencloset.net/%ea%b2%bd%ea%b8%b0%ec%a7%80%ec%97%ad-%eb%ac%b4%eb%a3%8c%eb%8c%80%ec%97%ac-%ed%94%84%eb%a1%9c%ea%b7%b8%eb%9e%a8-%ec%95%88%eb%82%b4/

각 정보로 연결되어 대여자가 무료대여 정보를 알고 활용할 수 있도록 작업 요청드립니다.

**Comment by keedi** [comment]
수정 및 배포 완료했습니다.

![screenshot-visit theopencloset net-2019-01-21-04-47-59](https://user-images.githubusercontent.com/138451/51444187-d37b7100-1d37-11e9-8a38-b5a41c674197.png)

**Comment by pingpongworks** [comment]
![default](https://user-images.githubusercontent.com/17288038/51447863-726a9200-1d65-11e9-8697-08384d513193.JPG)
하단에 무료대여 안내가 타이포로만 보이고 있습니다. 
링크 연결은 잘 되어 있는 거 같습니다. 디자인 수정 부탁드릴게요~

**Comment by keedi** [comment]
이미 적용 되어있는데, 브라우저 캐시 때문에 그런 것 같군요. 새로 고침하셔야 할 듯합니다.

**Comment by pingpongworks** [comment]
아, 브라우저 캐시가 이렇게도 영향을 미치나보네요. 인터넷 익스플로어에서 열어보니까 정상적을 보입니다. 확인 감사드립니다~ 그럼, 이슈 닫겠습니다^^
