### ISSUE TITLE
착용여부 목록에서 "입고감+기록요망" => "온라인 예정"으로 변경

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1548]
<img width="393" alt="2019-02-09 7 41 06" src="https://user-images.githubusercontent.com/17288038/52519691-ac62f000-2ca2-11e9-9834-051105769698.png">

사용자 정보 페이지 중 착용여부 탭의 목록 변경을 요청드립니다.
네번째 목록인 "입고감+기록요망"은 대여현장에서는 사용되지 않는 목록입니다. 
이보다는 미리 방문해서 입어만 보고 일정기간 후에 온라인으로 대여하려는 경우를 스태프가 인지하는 게 더 필요합니다. 

**온라인 예정**으로 변경 부탁드립니다.

**Comment by aanoaa** [comment]
- staff
- monitor
- OpenCloset-Common

세 군데에서 바뀌어야 합니다.

**Comment by aanoaa** [comment]
기존의 `입고감+기록요망` 의 라벨을 `온라인 예정` 으로 바꾸는 대신에,
새로운 카테고리를 추가하고, 목록에서 `온라인 예정` 이 대신 나타날 수 있도록 하겠습니다.

**Comment by aanoaa** [comment]
[OpenCloset-Common v0.1.10](https://cpan.theopencloset.net/STAFF@THEOPENCLOSET.NET/OpenCloset-Common-v0.1.10.tar.gz) 배포되었습니다.
여기에는 입고감의 "온라인예정" 값이 포함되어 있습니다.

**Comment by pingpongworks** [comment]
확인했습니다. 감사합니다.
