### ISSUE TITLE
*.theopencloset.net 서비스 장애

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#1552]
서비스가 정상적으로 되는 곳도 있다고 하는데, 제 기준으로는 아니됩니다.

<https://kr.dnsever.com/> 에서 각 레코드를 관리 중 인데, 관련된 모든 설정 값이 제거 되었습니다.
도메인의 소유권이 사라진게 아닌가 싶습니다.

    $ dig staff.theopencloset.net SOA
    
    ; <<>> DiG 9.11.5-P4-1-Debian <<>> staff.theopencloset.net SOA
    ;; global options: +cmd
    ;; Got answer:
    ;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 12166
    ;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1
    
    ;; OPT PSEUDOSECTION:
    ; EDNS: version: 0, flags:; udp: 4096
    ;; QUESTION SECTION:
    ;staff.theopencloset.net.	IN	SOA
    
    ;; AUTHORITY SECTION:
    net.			900	IN	SOA	a.gtld-servers.net. nstld.verisign-grs.com. 1551494140 1800 900 604800 86400
    
    ;; Query time: 80 msec
    ;; SERVER: 127.0.0.1#53(127.0.0.1)
    ;; WHEN: 토  3월 02 11:36:02 KST 2019
    ;; MSG SIZE  rcvd: 125

<https://www.gdnspc.com/dns-propagation-checker/kr.html#SOA&theopencloset.net> 의 결과입니다.

![2019-03-02 11-39-30](https://user-images.githubusercontent.com/170528/53676008-594bee00-3ce0-11e9-951f-630d6b8887a1.png)

이미 global 하게는 resolve 되는 곳이 없고, 국내 기준으로는 KT 의 수원지역 빼고는 모두 확산되었습니다.

모든 서비스가 아니되는 것이 맞습니다.
되는 곳이 있다면, 시간이 지남에 따라 아니될 것 입니다.(1-2일 이내에?)

**Comment by aanoaa** [comment]
@yongbin 님께 전달받은 내용입니다.
담당자와 통화하고 알아봤는데,

> whois에서 검색된 최종 갱신시간(utc 5:50 / kst 14:50) 에 연장처리 완료되었습니다.

무슨 액션 또는 이벤트에 의한 것인지는 모르겠지만, 다행히도 도메인이 연장되었습니다.
지금은 확산되고 있는 중 입니다.
https://www.gdnspc.com/dns-propagation-checker/kr.html#SOA&theopencloset.net

dnsever 로 네임서버가 올바르게 설정되었습니다.

<img width="436" alt="2019-03-02 4 35 06" src="https://user-images.githubusercontent.com/170528/53678974-b019ed80-3d09-11e9-92fc-a3b4f655423f.png">

옷장 5층 네트워크에서 확인해보았습니다.
옷장에서의 네트워크에서는 서비스에 정상적으로 접근할 수 있는 것으로 보입니다.
각 서비스별로 접속 테스트 해보았고 접속 되었습니다.

임시 방편으로 작업용 PC 에 hosts 파일을 변경해 놓았는데 이를 롤백하도록 하겠습니다.

    $ dig theopencloset.net SOA
    
    ; <<>> DiG 9.10.6 <<>> theopencloset.net SOA
    ;; global options: +cmd
    ;; Got answer:
    ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 27035
    ;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0
    
    ;; QUESTION SECTION:
    ;theopencloset.net.		IN	SOA
    
    ;; ANSWER SECTION:
    theopencloset.net.	3600	IN	SOA	ns231.dnsever.com. root.theopencloset.net. 1524633878 86400 600 1209600 300
    
    ;; Query time: 326 msec
    ;; SERVER: 10.186.130.160#53(10.186.130.160)
    ;; WHEN: Sat Mar 02 16:35:22 KST 2019
    ;; MSG SIZE  rcvd: 93

**Comment by pingpongworks** [comment]
도메인 관련 문제, 정상적으로 2022년 2월 28일까지 기간 연장되었습니다. 오류 나타나지 않고 있습니다. 특별히 마무리 할 내용이 없으시면 이슈 닫아도 될 듯 합니다.
