### ISSUE TITLE
2019-01-01 ~ 2019-02-28 기간 동안 남양주시 쿠폰을 이용한 대여자 명단

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1553]
남양주시에서 2019년 1월~2월 정산을 요청하고 있습니다.

정산 요청시에는 이용자 명단 자료가 필요하기 때문에,
2019년 1월 1일부터 2019년 2월 28일까지
namyangju201901 쿠폰을 사용한 대여자 명단을 요청드립니다.

방문대여와 택배대여가 구분되도록 부탁드립니다.

오늘 바로 급한 요청을 받았으나 내일까지 연기해놓은 상황이라
가능하시다면 내일 오전(3월5일)까지 부탁드립니다.

**Comment by keedi** [comment]
쿠폰 관련해서 내용이 변경되어 정산 방식이 기존과 달라졌을 수 있습니다. 동일한지 다른지 여부 확인이 필요합니다.

**Comment by aanoaa** [comment]
SELECT
        o.id                                     AS order_id
        , u.id                                   AS user_id
        , DATE_FORMAT(b.date, "%Y-%m-%d")        AS booking_ymd
        , DATE_FORMAT(o.rental_date, "%Y-%m-%d") AS rental_ymd
        , u.name                                 AS user_name
        , ui.birth                               AS user_birth
        , c.id                                   AS coupon_id
        , c.code                                 AS coupon_code
        , c.status                               AS coupon_status
        , o.online                               AS online
    FROM `order`          AS o
    LEFT JOIN `coupon`    AS c  ON o.coupon_id  = c.id
    LEFT JOIN `event`     AS e  ON c.event_id   = e.id
    LEFT JOIN `user`      AS u  ON o.user_id    = u.id
    LEFT JOIN `user_info` AS ui ON ui.user_id   = u.id
    LEFT JOIN `booking`   AS b  ON o.booking_id = b.id
    WHERE
        (
                e.id       = 13
            AND c.`status` = "used"
            AND o.parent_id IS NULL
            AND
                (
                       ( o.online <> 1 AND ( b.date        BETWEEN '2019-01-01' AND '2019-02-28' ) )
                    OR ( o.online <> 0 AND ( o.rental_date BETWEEN '2019-01-01' AND '2019-02-28' ) )
                    OR ( o.online <> 0 AND o.rental_date IS NULL )
                )
        )
    ;

**Comment by aanoaa** [comment]
결과는 이메일로 전달해드렸습니다.

**Comment by pingpongworks** [comment]
확인했습니다~ 감사합니다^^
