### ISSUE TITLE
지자체별 쿠폰 사용자 내역 다운로드 기능 

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1554]
![액셀다운로드](https://user-images.githubusercontent.com/17288038/54067047-f200e180-427d-11e9-8e6e-7dbee9273559.jpg)

1. 스태프 `이벤트현황` 페이지에서 각 지자체별로 월 사용자 내역을 **액셀로 다운로드**할 수 있는 기능을 요청드립니다. (위 그림 참조)
2. 쿠폰에 대한 지자체 정산 요청시 사용자 내역을 제출해야 합니다. 
3. 사용자 내역에는 주문서번호, 사용자번호, 대여일시, 사용자이름, 생년, 사용자 폰번호, 사용한 쿠폰코드, 택배대여 여부 항목이 기본적으로 필요합니다. 

10여개 지자체가 한꺼번에 1분기 정산을 하는 4월 1일 전까지 기능 추가가 가능하면 좋을 듯 합니다. 
액셀다운로드 기능의 형태는 1번과 같이 월별 다운로드도 좋고, 기간을 선택해서 다운로드하는 형태도 상관없습니다. 
가능여부 확인 부탁드립니다.

**Comment by pingpongworks** [comment]
요청드린 지자체별 쿠폰 사용자 내역 다운로드 기능, 
이번 주까지 작업이 어렵다면 1분기 정산 요청을 별도 이슈로 드리겠습니다. 

안양시, 군포시, 광주시, 고양시, 남양주시, 안산시, 화성시, 하남시, 성남시
총 9개 지자체 대여내역 요청을 드려야하기 때문에
이슈 1개에 한꺼번에 요청을 드릴까 하고 있습니다. 

9개 개별 이슈로 요청드리는게 낫다면 답변주시기 바랍니다. 

4월 5일전까지 보조금 신청서류와 대여내역 제출, 담당자 확인, 세금계산서 발행까지 마쳐야하므로
3월 31일에 마감된 후 가능한 4월 2일 (화) 저녁까지는 대여내역을 모두 주셔서
제출, 확인, 계산서 발행 과정이 문제없이 진행될 수 있을 듯 합니다. 

일정 참고 부탁드립니다.   

가능하다면 3월 31일 전에 요청드린 다운로드 기능이 되면 좋을 듯 합니다. 
가능 여부 알려주시면 감사하겠습니다.

**Comment by keedi** [comment]
ui 부분에서 약간 다른 방식으로 진행중입니다. 4/2까지 파일 전달은 문제없으나(별도 이슈 생성할 필요없습니다) 본 이슈 마무리는 시간이 더 걸릴 예정입니다. 참고해주세요.

**Comment by pingpongworks** [comment]
네~ 알겠습니다. 
그럼, 4월 2일까지 이용자내역 부탁드립니다.

**Comment by keedi** [comment]
> 안양시, 군포시, 광주시, 고양시, 남양주시, 안산시, 화성시, 하남시, 성남시
> 총 9개 지자체 대여내역 요청을 드려야하기 때문에
> 이슈 1개에 한꺼번에 요청을 드릴까 하고 있습니다.

가능하면 쿠폰 관련 요청을 주실 때는 `anyang201901` 과 같은 이벤트 고유 이름을 이용해서 이슈를 기록해주시면 작업하는데 도움이 될 것 같습니다. 이벤트의 종류와 개수가 점점 많아지기 때문에 요청하실 때 명확하게 명시주시는 것이 혼란의 여지가 없을 것으로 사료됩니다.

무엇보다 시작 일시와 종료 일시가 다들 다르기도 하고, 해가 넘어가도 연속되는 이벤트도 있기도 하는 등, 단순히 지자체 명만으로 구분하기는 어려운 점이 많습니다. 참고 부탁드립니다.

**Comment by keedi** [comment]
언급하신 지자체의 코드를 확인해보았습니다.

- 안양시   anyang201901
- 군포시   gunpo201901
- 광주시   gwangju201901
- 고양시   goyang201901
- 남양주시 namyangju201901
- 안산시   ansan201901
- 화성시   hwaseong201901
- 하남시   hanam201901
- 성남시   seongnam201901

이상한 부분이 있다면 알려주세요.

**Comment by pingpongworks** [comment]
이벤트 고유이름, 모두 맞습니다~

**Comment by pingpongworks** [comment]
리툴로 구현되어서 이슈 닫습니다.
