### ISSUE TITLE
개인 정보 취급 방침 수정 

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1555]
대여자 신체치수 정보 수집과 관련한 부분에 보완이 필요하다는 변호사 의견에 따라 부분 수정을 하였습니다. 보완하면서 기증자와 자원봉사자의 개인정보 보유기간과 관련된 부분도 보완을 하였습니다. 

1) 방문예약할 때
2) 기증신청할 때
3) 자원봉사 신청할 때
4) 온라인대여 회원가입할 때 

**개인정보 취급방침 간단버전** 수정 부탁드립니다. 

이전에는 기증신청, 자원봉사 신청 버전이 조금씩 달랐지만, 아래의 버전으로 통일해서 수정해주시면 될 듯합니다. 

홈페이지 하단 푸터의 **개인정보 취급방침 풀버전**은 이미 수정해놓았으니 가능하면 빠른 수정 부탁드립니다.   

----------------------------------------------------------------------------------------------------------

[열린옷장 개인정보취급방침]

열린옷장은 개인정보보호법, 정보통신망법 등 관련 법령에 따라 이용자의 개인정보 보호 및 권익을 보호하고 개인정보와 관련한 이용자의 고충을 원활하게 처리할 수 있도록 다음과 같은 개인정보처리방침을 두고 있습니다.

1. 수집하는 개인정보의 항목
(1) 열린옷장은 상담, 서비스 신청, 활동 참여 등을 위해 아래와 같은 개인정보를 수집하고 있습니다.

(가) 기증자
– 필수항목 : 아이디, 비밀번호, 성명, 생년월일, 성별, 전화번호, 이메일, 주소
– 선택항목 : 기증경험 여부, 대여경험 여부, 기증편지

(나) 대여자
– 필수항목 : 아이디, 비밀번호, 성명, 생년월일, 성별, 전화번호, 이메일, 주소, 의류의 착용날짜, 대여목적, 대여를 희망하는 품목, 희망색상, 신체치수 (키,몸무게,가슴둘레,허리둘레 등 서비스에 필요한 신체치수 항목)
– 선택항목 : 감사편지

(다) 자원봉사자
– 필수항목 : 아이디, 비밀번호, 성명, 성별, 생년월일, 전화번호, 이메일, 주소, 봉사활동날짜, 활동시간, 1365 승인여부, 활동기간, 직업
– 선택항목 : 1365 신청자 작성 여부, 방문동기, 접한 경로

(2) 서비스 이용과정이나 사업 처리 과정에서 아래와 같은 정보들이 생성되어 수집될 수 있습니다.
– 서비스 이용기록, 접속 로그, 쿠키, 접속 IP 정보, 결제기록, 이용정지 기록

2. 개인정보의 수집 및 이용 목적

‘열린옷장 홈페이지’는 개인정보를 다음의 목적을 위해 처리합니다. 처리한 개인정보는 다음의 목적 이외의 용도로는 사용되지 않으며 이용 목적이 변경될 시에는 사전동의를 구할 예정입니다.

가. 서비스 제공에 관한 계약 이행 및 서비스 제공에 따른 요금 정산

(1) 정장기증 업무
기증자의 정보 및 신원 확인, 연락 및 안내, 소식지 전달 등

(2) 정장대여 업무
대여자의 예약 및 안내, 신체치수 측정, 기증 정장의 손·망실 방지 등

나. 회원관리
본인확인, 개인식별, 불량회원의 부정 이용 방지와 비인가 사용 방지, 가입 의사 확인, 가입 및 가입횟수 제한, 만14세 미만 아동 개인정보 수집 시 법정 대리인 동의여부 확인, 추후 법정 대리인 본인확인, 분쟁 조정을 위한 기록보존, 불만처리 등 민원처리, 고지사항 전달

다. 마케팅 및 광고에 활용
신규 서비스(제품) 개발 및 특화를 위한 연구 및 데이터 분석, 인구통계학적 특성에 따른 서비스 제공 및 광고 게재, 접속 빈도 파악, 회원의 서비스 이용에 대한 통계, 이벤트 등 광고성 정보 전달

라. 기증편지 및 감사편지 공개

마. 자원봉사자 관리                                                                                                             
가입 의사 확인, 가입에 대한 정보 안내, 추후 자원봉사에 대한 피드백 요청 및 고지사항 전달

3. 개인정보의 보유 및 이용기간
원칙적으로 개인정보 수집 및 이용목적이 달성된 후에는 해당 정보를 지체없이 파기합니다. 단, 다음의 정보에 대해서는 아래의 이유로 명시한 기간 동안 보존합니다.

1. 내부 방침에 의한 정보보유 사유
회원이 서비스 이용 동의 철회 또는 회원에서 탈퇴한 경우에도 회사는 원활한 서비스의 제공 및 부정한 서비스의 이용을 방지하기 위하여 아래와 같이 회원정보를 보관합니다.

(1) 서비스 사용기록(결제, 예약 등)
– 보존 이유 : 부정 서비스 회원 관리, 서비스 가입 및 이용 등의 혼선 방지
– 보존 기간 : 1년

(2) 부정가입 및 징계기록 등의 부정이용기록
– 보존이유 : 부정 가입 및 이용 방지
– 보존기간 : 6개월

(3) 관련 법령 및 이용약관을 위반하는 부정거래기록(아이디, 성명, 전화번호, 주소, IP주소, 쿠키)
– 보존이유 : 부정거래 방지 및 다른 선량한 이용자의 보호, 안전한 거래 환경 보장
– 보존기간 : 수집 시점으로부터 1년

(4) 신체치수 정보
– 보존이유 : 서비스 재이용 편의, 회원의 서비스 이용에 대한 통계 및 신규 서비스 개발을 위한 데이터 분석
– 보존기간 : 삭제 요청시까지

(5) 기증자 개인정보
– 보존이유 : 활동보고, 소식지 전달 등 기증자 관리 및 감사편지 전달
– 보존기간 : 삭제 요청시까지

(6) 자원봉사자 개인정보
– 보존이유 : 활동 관리, 정보 공유, 소식지 전달 등 자원봉사자 관리
– 보존기간 : 삭제 요청시까지

2. 관련법령에 의한 정보보유 사유
「전자상거래 등에서의 소비자보호에 관한 법률」, 「정보통신망 이용촉진 및 정보보호등에 관한 법률」, 「통신비밀보호법」등 관련 법령의 규정에 의하여 보존할 필요가 있는 경우, 회사는 관계 법령에서 정한 일정한 기간 동안 회원정보를 보관합니다. 이 경우 회사는 보관하는 정보를 그 보관의 목적으로만 이용하며, 보존기간은 아래와 같습니다.

(1) 계약 또는 청약철회 등에 관한 기록
– 보존 이유 : 전자상거래 등에서의 소비자보호에 관한 법률
– 보존 기간 : 5년

(2) 대금결제 및 재화 등의 공급에 관한 기록
– 보존 이유 : 전자상거래 등에서의 소비자보호에 관한 법률
– 보존 기간 : 5년

(3) 소비자의 불만 또는 분쟁처리에 관한 기록
– 보존 이유 : 전자상거래 등에서의 소비자보호에 관한 법률
– 보존 기간 : 3년

(4) 본인확인에 관한 기록
– 보존 이유 : 정보통신망 이용촉진 및 정보보호 등에 관한 법률
– 보존 기간 : 6개월

(5) 웹사이트 방문(로그인) 기록
– 보존 근거 : 통신비밀보호법
– 보존 기간 : 3개월

(6) 통신사실확인자료 보관
– 보존 이유 : 컴퓨터통신, 인터넷 로그기록자료, 접속지 추적자료
– 보존 근거 :통신비밀보호법
– 보존 기간 : 3개월

**Comment by keedi** [comment]
visit 페이지에 적용 완료했습니다.

**Comment by pingpongworks** [comment]
>1.방문예약할 때
2.기증신청할 때
3.자원봉사 신청할 때
4.온라인대여 회원가입할 때


- 방문예약 시 개인정보취급방침 수정된 거 확인했습니다. 
- 나머지 2,3,4 경우의 개인정보취급방침도 추가로 수정 부탁드립니다.

**Comment by keedi** [comment]
기록해주신 2, 3, 4는 다른 저장소(프로젝트)입니다. 언급해주신 1~4는 다음과 같습니다.

- 방문예약(visit), 관리(staff) - opencloset/opencloset - @keedi / @aanoaa
- 기증신청(donation) - opencloset/donation - @aanoaa
- 자원봉사(volunteer) - opencloset/volunteer - @aanoaa
- 온라인대여(share) - opencloset/OpenCloset-Share-Web - @aanoaa

번거로우시더라도 별개로 이슈를 올려주시는 것이 좋을 것 같습니다.

**Comment by pingpongworks** [comment]
네~ 따로 이슈 올리겠습니다
