### ISSUE TITLE
[바코드] 발급 요청드립니다.

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1558]
품목 | 수량
----|--------
자켓 | 1,000개
바지 | 1,000개
블라우스 | 1,000개
셔츠 | 1,000개
구두(양쪽 2개씩) | 500쌍
원피스 | 500개
코트 | 200개

**Comment by aanoaa** [comment]
# belt, blouse, coat, jacket, onepiece, pants, shirt, shoes, skirt, tie, waistcoat, bag, misc
    perl script/generate_code.pl jacket    1000 --save > jacket.csv
    perl script/generate_code.pl pants     1000 --save > pants.csv
    perl script/generate_code.pl blouse    1000 --save > blouse.csv
    perl script/generate_code.pl shirt     1000 --save > shirt.csv
    perl script/generate_code.pl shoes     500 --save  > shoes.csv
    perl script/generate_code.pl onepiece  500 --save  > onepiece.csv
    perl script/generate_code.pl coat      200 --save  > coat.csv

    -------------------------------------------------
    '-']/ jacket 의류코드가 갱신되었습니다 => JABO
    -------------------------------------------------
    '-']/ pants 의류코드가 갱신되었습니다 => P990
    -------------------------------------------------
    '-']/ blouse 의류코드가 갱신되었습니다 => B3ZI
    -------------------------------------------------
    '-']/ shirt 의류코드가 갱신되었습니다 => S69N
    -------------------------------------------------
    '-']/ shoes 의류코드가 갱신되었습니다 => A2X5
    -------------------------------------------------
    '-']/ onepiece 의류코드가 갱신되었습니다 => O13C
    -------------------------------------------------
    '-']/ coat 의류코드가 갱신되었습니다 => C0X3

**Comment by aanoaa** [comment]
각 파일은 이메일로 전달해드렸습니다.

**Comment by pingpongworks** [comment]
확인했습니다~
