### ISSUE TITLE
정장 반납 안내 출력시 택배 반납 문구 제거

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1562]
택배로 반납할 경우 현재는 반납일 1일전 발송이라, 실질적인 대여기간이 2박3일 밖에 되지 않는 불편이 있습니다. 반납방법을 방문/택배 구분해서 기억해야하는 대여자의 불편도 있습니다.

불편사항 개선을 위해 방문반납, 택배반납 동일하게 3박4일 내에 반납 또는 발송 하면 되는 것으로 택배반납 정책을 변경하려고 합니다. 결제시 프린트하는 반납안내지의 출력 문구 수정 요청드립니다.

![KakaoTalk_20190416_145439013](https://user-images.githubusercontent.com/17288038/56186551-adc1e780-605a-11e9-8644-acd772b060a1.jpg)

빨간 박스 내용 삭제해주시면 됩니다.

**Comment by keedi** [comment]
해당 문구 제거했습니다.

![screenshot--2019-04-17-03-42-05](https://user-images.githubusercontent.com/138451/56236003-979c4180-60c3-11e9-89c0-c55520873abc.png)

**Comment by keedi** [comment]
배포 이후 서비스를 재기동해야 합니다. 서버에 배포 및 재기동 완료했습니다.

클라이언트 쪽에서는 브라우저 캐시가 있을 수 있으므로 캐시를 제거하거나 새로고침을 정확하게 수행해야 합니다.

**Comment by pingpongworks** [comment]
확인했습니다. 감사합니다.
