### ISSUE TITLE
방문 예약 페이지 문구 수정

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1566]
<img width="477" alt="스크린샷 2019-04-29 오후 5 41 38" src="https://user-images.githubusercontent.com/17288038/56884942-32265880-6aa6-11e9-9d09-bb868df8fff3.png">

빨간 박스 내의 내용을 아래 내용으로 수정 부탁드립니다. 

------------------------------------------------------------------------------------

안녕하세요. 열린옷장 방문시간 예약 페이지입니다. 

**방문시간 예약 / 예약내역 확인 / 예약일시 변경 / 예약 취소**를 원하시면 다음을 입력해주세요. 

(휴대전화가 없거나 번호가 변경된 경우, 열린옷장 직접 문의 T. 02-6929-1020)

**Comment by pingpongworks** [comment]
<img width="384" alt="스크린샷 2019-04-29 오후 5 56 07" src="https://user-images.githubusercontent.com/17288038/56885745-289df000-6aa8-11e9-8eea-f202ba5c3e4c.png">

빨간 박스 내의 내용을 아래 내용으로 수정 부탁드립니다.

---------------------------------------------

입사면접인 경우 응시기업 및 분야와 면접복장 규정을 자세히 입력해주세요. 적합한 의류를 준비해드리기 위해 최선을 다하겠습니다.

**Comment by keedi** [comment]
수정 완료 및 서버에 배포 완료했습니다.

**Comment by pingpongworks** [comment]
확인했습니다. 감사합니다.
