### ISSUE TITLE
평일 및 주말 09:30 예약 슬롯 활성화

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1569]
<img width="539" alt="스크린샷 2019-05-07 오후 1 11 48" src="https://user-images.githubusercontent.com/17288038/57272213-c5c2df00-70cd-11e9-8c50-c23f30d7e534.png">
<img width="1025" alt="스크린샷 2019-05-07 오후 1 20 53" src="https://user-images.githubusercontent.com/17288038/57272214-c5c2df00-70cd-11e9-892b-5315c1b463b5.png">
<img width="1025" alt="스크린샷 2019-05-07 오후 1 21 14" src="https://user-images.githubusercontent.com/17288038/57272215-c5c2df00-70cd-11e9-9b96-43cc76d5f90d.png">

성수기 동안 예약가능 시간 확대를 하고자 합니다.
9시 30분 예약이 가능하도록 부탁드립니다. 

- 방문예약시 9: 30 선택이 가능하도록
- staff 시간표와 예약 페이지 9:30 생성

5월 13일 (월)부터 9시 30분 예약이 가능하도록 작업부탁드립니다. 

예약 확대기간은 5월~6월 성수기로 생각하고 있으나, 
끝내는 날짜를 명확히 정하지는 않았습니다.
 
내부적으로 5월 13일부터 9시 30분 대여 태세를 갖추려고 합니다. 
슬롯 추가 작업에 시간이 더 필요하시면 말씀해주세요.

**Comment by keedi** [comment]
변경된 예약 페이지 화면입니다.

![screenshot-staff theopencloset net-2019-05-11-20-57-19](https://user-images.githubusercontent.com/138451/57569442-13be4680-7430-11e9-981e-18dba5436ca3.png)

**Comment by keedi** [comment]
변경된 시간표 페이지입니다.

![screenshot-staff theopencloset net-2019-05-11-20-58-15](https://user-images.githubusercontent.com/138451/57569447-1caf1800-7430-11e9-904d-8f828757a75f.png)

**Comment by keedi** [comment]
변경된 방문 예약 일시 선택 화면입니다.

![screenshot-staff theopencloset net i5 bebop 10301-2019-05-11-21-07-06](https://user-images.githubusercontent.com/138451/57569486-d1493980-7430-11e9-9be1-0f0da4080306.png)

**Comment by keedi** [comment]
몇 명으로 슬롯을 열지 몰라 기본 값은 0으로 했으니 필요에 따라 슬롯 개수를 조절하시면 됩니다.

**Comment by pingpongworks** [comment]
네 확인했습니다. 감사합니다. 
5월 13일 월요일, 9:30의 경우 지금 예약활성화를 눌러도 
기존의 10시 이후 예약 내역은 그대로 있겠죠? 예약 내역이 초기화 되지는 않겠죠?

**Comment by pingpongworks** [comment]
타 시간대와 동일하게, 
월~금은 6 / 6
토일은 5 / 5 로 설정 부탁드립니다.

**Comment by keedi** [comment]
적용했습니다.

예약 활성화는 예약 내역과 무관한 기능으로 해당 예약 시간대 인원을 조정할 수 있도록 해주는 기능입니다. 예약 활성화를 하지 않으면 **CLOSED**로 표시되므로 인원을 조정할 수 없습니다.

**Comment by pingpongworks** [comment]
확인했습니다. 감사합니다.
