### ISSUE TITLE
방문 예약시 방문 일자 선택 화면에서 택배 반납 정보 삭제

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1570]
<img width="539" alt="스크린샷 2019-05-07 오후 1 11 48" src="https://user-images.githubusercontent.com/17288038/57272710-cd838300-70cf-11e9-82c2-410735d404ca.png">

어디선가 끝없이 나오네요. 빨간 밑줄 부분 삭제 요청드립니다.

**Comment by keedi** [comment]
수정 및 적용 완료했습니다. 잘 나오겠지만 경우에 따라 브라우저 새로 고침을 해야할 수도 있습니다.

**Comment by pingpongworks** [comment]
확인했습니다. 감사합니다.
