### ISSUE TITLE
도로명 주소 데이터베이스 갱신

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1576]
`user/123990`
`user/123245`
사용자의 주소 검색이 되지않아 정확한 주소 입력을 하지 못했습니다.
상세주소 란에 기입해놓은 도로명 주소 업데이트 요청 드립니다.

**Comment by aanoaa** [comment]
주소 DB 는 바로바로 적용될 수 없긴 합니다.
upstream 에서 패치된 버전을 export 해두면 그걸 활용하는 방법을 사용하고 있습니다.

최근 DB 가 새로 갱신되었는지 확인해보겠습니다.

**Comment by aanoaa** [comment]
> DB 덤프는 포에시스 파일서버에 부정기적으로 (1년에 몇 차례) 업데이트됩니다. 날짜순으로 정렬되어 있으니 가장 최근의 덤프를 다운로드하시면 됩니다. 단, DB 덤프의 버전과 서버측 검색 API의 버전이 크게 다를 경우 호환이 되지 않을 수도 있으니 주의해 주십시오.

`29-Jan-2019 13:16` 일 파일이 최근파일 입니다.(저희가 사용하고 있는 버전같습니다)
업데이트 될때가 되었는데..

**Comment by keedi** [comment]
현재 포에시스 서버의 가장 최신 주소 DB 파일은 다음과 같습니다.

```
postcodify.20200917.v3.mysqldump.gz                18-Sep-2020 15:20           417945542
postcodify.20200917.v3.sqlite.gz                   18-Sep-2020 15:22           948850069
postcodify.20210131.v3.mysqldump.gz                02-Feb-2021 02:01           423522599
postcodify.20210131.v3.sqlite.gz                   02-Feb-2021 02:01           956936357
```

**Comment by aanoaa** [comment]
`postcodify.20210131.v3.mysqldump.gz` 파일로 영업외 시간에 적용하도록 하겠습니다.

**Comment by aanoaa** [comment]
02:35 에 시작해서 02:54 에 끝났습니다.

    $ zcat postcodify.20210131.v3.mysqldump.gz | mysql -u $username -p$password $database

명령으로 실행했고, 용량 문제로 dumpfile 은 삭제했습니다.
검색이 안되던 주소로 테스트해보고 결과를 살펴봐야 합니다.

**Comment by aanoaa** [comment]
본문에 적어주신 사용자 주소로 테스트해봤고 결과가 있음을 확인했습니다.

**Comment by pingpongworks** [comment]
확인했습니다. 검색이 후련하게 잘 되네요. 감사합니다~
