### ISSUE TITLE
2019-04-01 ~ 2019-06-21 기간 동안 안양시 쿠폰 이용자 명단

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1579]
2019년 4월 1일부터 2019년 6월 21일까지
anyang201901 쿠폰을 사용한 대여자 명단을
방문대여와 택배대여가 구분되도록 요청드립니다.

안양시에서 내부 사정상 중간정산을 요청하고 있습니다.
6월 2일 (일)까지 부탁드립니다.

**Comment by aanoaa** [comment]
제목은 남양주시인데, 안양시를 말씀하시는거겠죠?

**Comment by aanoaa** [comment]
메일로 전달해드렸습니다.

**Comment by pingpongworks** [comment]
네~ 안양시 맞아요. 감사합니다^^

**Comment by pingpongworks** [comment]
근데, 요즘 데이터 받을 때마다 매월 마지막 날 데이터가 누락되어서 옵니다. 다음 번에 데이터 부탁드릴 때 확인 한번 해주세요~

**Comment by keedi** [comment]
마지막 날 데이터 누락은 다음 이슈와 연관 있을 수 있습니다.

#1581
