### ISSUE TITLE
평일 및 주말 09:00 예약 슬롯 활성화

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1580]
#1569 와 유사한 요청입니다. 

이용자 예약 추이를 분석한 결과를 반영하여 예약시간을 확대하려고 합니다.
일단 시범운영을 통해 검증과정을 거치고자 합니다. 
다음 예약시간에 예약이 가능하도록 예약슬롯 조정을 요청드립니다. 

    AM 9:00
    PM 18:00
    PM 18:30
    PM 19:00

- 방문예약시 위 시간 선택이 가능하도록
- staff 시간표와 예약 페이지 시간 생성

7월 초 시범운영을 해본 후 확정하여 확대운영을 하려고 하기 때문에 
일단 확대하는 시간의 예약가능인원수는 0명으로 해주시면 
저희가 수기로 조정하겠습니다. 

6월 28일 (금)까지 작업 부탁드립니다.

**Comment by aanoaa** [comment]
설정파일을 바꾸고 재시작 하였습니다만 적용되지 않은 것 같습니다.
설정파일만 변경해서는 아니되는 것 같습니다.

**Comment by aanoaa** [comment]
```sql
INSERT INTO `booking` (`date`, `gender`, `slot`) VALUES
  ('2019-06-25 09:00:00', 'male', 0),
  ('2019-06-25 09:00:00', 'female', 0),
  ('2019-06-26 09:00:00', 'male', 0),
  ('2019-06-26 09:00:00', 'female', 0),
  ('2019-06-27 09:00:00', 'male', 0),
  ('2019-06-27 09:00:00', 'female', 0),
  ('2019-06-28 09:00:00', 'male', 0),
  ('2019-06-28 09:00:00', 'female', 0),
  ('2019-06-29 09:00:00', 'male', 0),
  ('2019-06-29 09:00:00', 'female', 0),
  ('2019-06-30 09:00:00', 'male', 0),
  ('2019-06-30 09:00:00', 'female', 0),
  ('2019-07-01 09:00:00', 'male', 0),
  ('2019-07-01 09:00:00', 'female', 0),
  ('2019-07-02 09:00:00', 'male', 0),
  ('2019-07-02 09:00:00', 'female', 0),
  ('2019-07-03 09:00:00', 'male', 0),
  ('2019-07-03 09:00:00', 'female', 0),
  ('2019-07-04 09:00:00', 'male', 0),
  ('2019-07-04 09:00:00', 'female', 0),
  ('2019-07-05 09:00:00', 'male', 0),
  ('2019-07-05 09:00:00', 'female', 0),
  ('2019-07-06 09:00:00', 'male', 0),
  ('2019-07-06 09:00:00', 'female', 0),
  ('2019-07-07 09:00:00', 'male', 0),
  ('2019-07-07 09:00:00', 'female', 0),
  ('2019-07-08 09:00:00', 'male', 0),
  ('2019-07-08 09:00:00', 'female', 0),
  ('2019-07-09 09:00:00', 'male', 0),
  ('2019-07-09 09:00:00', 'female', 0),
  ('2019-07-10 09:00:00', 'male', 0),
  ('2019-07-10 09:00:00', 'female', 0),
  ('2019-07-11 09:00:00', 'male', 0),
  ('2019-07-11 09:00:00', 'female', 0),
  ('2019-07-12 09:00:00', 'male', 0),
  ('2019-07-12 09:00:00', 'female', 0),
  ('2019-07-13 09:00:00', 'male', 0),
  ('2019-07-13 09:00:00', 'female', 0),
  ('2019-07-14 09:00:00', 'male', 0),
  ('2019-07-14 09:00:00', 'female', 0);
```

**Comment by aanoaa** [comment]
이미 2019-07-14 일 까지 예약을 열어놓은 상태라서, 09:00 슬롯을 추가합니다.
이러면 edit 가능한 형태가 될 것 같습니다.

**Comment by keedi** [comment]
음 디비를 질의를 날려서 직접 여는 것은 아닌데요. 혹시 직접 질의 날리셨나요?

**Comment by keedi** [comment]
요청하신 09:00, 18:00, 18:30, 19:00 네 개의 시간 중 09:00 을 제외하고는 이미 활성화 되어 있습니다. 수동으로 수정만 해주시면 되는 상황이기 때문에 09:00 만 활성화 시키면 됩니다.

**Comment by keedi** [comment]
기존 열어둔 상태의 날짜의 경우 **예약 활성화** 버튼을 누르면 **CLOSED** 항목의 슬롯이 열리게 됩니다. 참고해주세요.

![screenshot-staff theopencloset net i5 bebop 10301-2019-06-25-01-02-54](https://user-images.githubusercontent.com/138451/60034271-31e0bd00-96e5-11e9-9be5-abf55d76da88.png)


P.S.
데이터베이스에 직접 질의를 날리지 않고 상기 버튼을 이용해 활성화 합니다.

**Comment by keedi** [comment]
이미 @aanoaa 님께서 작업을 해주셔서 별 다른 것은 없고 내용 확인만 추가로 진행했습니다. 기본 값이 6으로 되어 있어 요청대로 0으로 조정했습니다. 가능하면 데이터베이스에 직접 질의를 날리기 보단 UI를 이용해서 활성화시켜주세요. 버그가 없다면 정상 동작할 겁니다.

**Comment by aanoaa** [comment]
07-14 까지 이미 활성화 되어 있어서 쿼리로써 넣었습니다.
활성화를 누르면 CLOSED 된 것들만 활성화되는 줄 몰랐습니다.
앞으로는 그리 하겠습니다.

**Comment by pingpongworks** [comment]
네 확인했습니다. 감사합니다^^
