### ISSUE TITLE
서울시 쿠폰 예약시간 업데이트 실패

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#1585]
방문예약을 거쳐서 예약시간이 확정되면 거꾸로 열린옷장 -> 서울시쿠폰시스템 으로 예약시간을 전송해주고 있는데,
이것이 제대로 동작하지 않습니다.

어느 순간부터 all fail 인 것 같습니다.
발생한 시점이 #1584 와 같아서 비슷한 이슈가 아닐까 생각됩니다.

근데 #1584 를 패치하면서 다른 API 들도 마찬가지일 것 같은
의심이 들어서 저 스스로 테스트해봤었는데,

그때는 302 redirect 는 발생하지 않았지만, 예약시간이 변경되지 않았습니다.
302 응답이 오지 않아서 내가 뭘 잘못했겠거니.. 하고 넘어갔습니다.

API 가 변경되었거나 다른 이유가 있을 것 같습니다.

**Comment by aanoaa** [comment]
서버 로그 입니다.
이런 에러가 발생하고 있습니다.

    Failed to update jobwing booking_datetime: rent_num(xxxxxxxxxx-308), order(144482), datetime(2019-07-09T10:00:00)
    Failed to update jobwing booking_datetime: rent_num(xxxxxxxxxx-490), order(144483), datetime(2019-07-09T11:00:00)
    Failed to update jobwing booking_datetime: rent_num(xxxxxxxxxx-224), order(144484), datetime(2019-07-09T11:00:00)
    ...

**Comment by aanoaa** [comment]
아 기간 연장으로 테스트 했었습니다.

**Comment by aanoaa** [comment]
인증서의 기간이 만료된 것은 맞습니다.
사이트를 https 로 접속하면 인증서 만료에 대한 브라우저 경고창이 나타납니다.

**Comment by aanoaa** [comment]
https -> http 로 바꾸고 테스트해봤는데 동작합니다.
상세내용에는 대여일이 나타나있지 예약일이 나타나있지 않아서 지난번 테스트때는 동작한다고 착각한 것 같습니다.

기간 연장도 같은 이슈가 있을텐데 이번 패치에 의해 함께 해결될 것으로 보입니다.

**Comment by aanoaa** [comment]
패치된 api 클라이언트의 새버전을 배포하고 이를 서비스에 적용하였습니다.
지금부터는 예약일이 정상적으로 반영될 것으로 믿습니다.

**Comment by aanoaa** [comment]
확인되면 닫아주세요

**Comment by pingpongworks** [comment]
7/9 이용자 총 30명 중 27명 대여일시 누락
7/6 이용자 1명 대여일시 누락

**Comment by pingpongworks** [comment]
어제 이용자까지는 누락상태라 업체에 요청해서 일일이 수기로 대여일시 입력해서 살려놔야 할 거 같습니다. 한명씩 시간표에서 확인해서 명단을 만들어야 해서 이 작업이 꽤 번거롭습니다. 내일 아침에는 꼭 정상이면 좋겠습니다. 내일 아침에 오늘 이용자 확인한 후 문제 없으면 이슈 닫겠습니다.

**Comment by aanoaa** [comment]
어제 말씀해주신 것 처럼 패치 전에 예약된 사용자들이 누락된 것 같습니다.
정상적으로 업데이트 되고 있다면, 일정 기간이 지난 이후에는 발생하지 않을 것 입니다.

**Comment by pingpongworks** [comment]
7/10 이용자 총 22명 중 7명 대여일시 누락

누락자가 줄어든 것으로 보아 패치 작업이 효력을 발휘하는 것으로 보입니다. 내일 아침까지 확인해보고 이슈닫겠습니다.

**Comment by pingpongworks** [comment]
7/11 이용자 총 16명 중 2명 대여일시 누락

내일 부터는 누락자가 거의 없을 것으로 보입니다. 이슈닫겠습니다.
