### ISSUE TITLE
평일 및 주말 예약 슬롯 변경

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1586]
약 한 달간 예약시간 확대 시범운영을 끝내고 확정을 하였습니다.
7월 15일 (월)부터 운영시간이 공식적으로 변경됩니다. 
아래와 같이 예약활성화 시간당 예약가능 인원수 변경 요청드립니다. 

<img width="297" alt="스크린샷 2019-07-13 오후 1 28 23" src="https://user-images.githubusercontent.com/17288038/61166969-396fe500-a572-11e9-97f6-263480660ff6.png">

**Comment by keedi** [comment]
적용 및 서버에 배포 완료했습니다.

**Comment by keedi** [comment]
문제 있으면 본 이슈를 다시 열어주세요~ :)

**Comment by pingpongworks** [comment]
다른 건 문제 없는데, 
**주말 14:00 ~ 16:30 / 남자 예약자수는 4명**씩입니다. 
그것만 수정 한번 부탁드립니다~

8월 10일까지 이미 열어놓았으니까 급하진 않습니다. 
저녁에 부탁드릴게요~

**Comment by keedi** [comment]
입력하다 해당 부분 실수한 것 같습니다. 말씀해주신 대로 수정했습니다. 확인해보시고 문제 있으면 다시 이슈 열어주세요~ :)

**Comment by pingpongworks** [comment]
확인했습니다. 감사합니다~
