### ISSUE TITLE
[통계요청] 광진구, 성동구, 동대문구 주소지의 이용자 명단

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1595]
야간지기 채용을 위해 대여자 및 봉사자에게 문자 발송을 하려고 합니다. 

- 출생년도 : 1989~1999
- 주소지 : 광진구, 성동구, 동대문구, 강남구, 송파구
- 2019년 1월 1일~2019년 7월 1일 동안 이용했던 대여자 및 봉사자

위 조건에 부합하는 명단의 이름 / 전화번호 / 이메일주소 요청드립니다. 
야간지기 채용이 급해서 최대한 빨리 부탁드립니다.

**Comment by aanoaa** [comment]
#!/bin/sh
    username=xxxxxxxxxxxx
    password=xxxxxxxxxxxx
    database=xxxxxxxxxxxx
    mysql -u $username -p$password -h 0.0.0.0 $database <<EOF | sed 's/\t/,/g' > volunteer-user.csv
    SELECT DISTINCT v.*
    FROM volunteer v
    JOIN volunteer_work vw ON v.id = vw.volunteer_id
    WHERE v.birth_date BETWEEN '1989-01-01' AND '2000-01-01'
    AND vw.activity_from_date BETWEEN '2019-01-01' AND '2019-07-01'
    AND v.address REGEXP '광진구|성동구|동대문구|강남구|송파구'
    EOF
    
    mysql -u $username -p$password -h 0.0.0.0 $database <<EOF | sed 's/\t/,/g' > order-user.csv
    SELECT DISTINCT ui.user_id, ui.phone, ui.address2, ui.gender, ui.birth
    FROM \`order\` o
    JOIN user_info ui ON o.user_id = ui.user_id
    WHERE ui.birth BETWEEN 1989 AND 1999
    AND o.rental_date BETWEEN '2019-01-01' AND '2019-07-01'
    AND ui.address2 REGEXP '광진구|성동구|동대문구|강남구|송파구'
    EOF

**Comment by aanoaa** [comment]
메일로 결과물 전달해드렸습니다.

**Comment by pingpongworks** [comment]
네~ 확인했어요. 감사합니다^^

**Comment by aanoaa** [comment]
대여자 정보에 이름이 빠져있었습니다.

```sh
mysql -u $username -p$password -h 0.0.0.0 $database <<EOF | sed 's/\t/,/g' > order-user.csv
SELECT DISTINCT ui.user_id, u.name, ui.phone, ui.address2, ui.gender, ui.birth
FROM \`order\` o
JOIN user u ON o.user_id = u.id
JOIN user_info ui ON o.user_id = ui.user_id
WHERE ui.birth BETWEEN 1989 AND 1999
AND o.rental_date BETWEEN '2019-01-01' AND '2019-07-01'
AND ui.address2 REGEXP '광진구|성동구|동대문구|강남구|송파구'
EOF
```
