### ISSUE TITLE
[쿠폰 통계] 2019-07-01 ~ 2019-09-30 기간 동안 지자체 쿠폰 이용자 명단

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1603]
- gunpo201901
- gwangju201901
- goyang201901
- ansan201901
- hwasung201901
- gimpo201901

3분기 정산을 해야 합니다.
2019년 7월 1일부터 2019년 9월 30일까지
각 지자체별 쿠폰을 사용한 대여자 명단을
방문대여와 택배대여가 구분되도록 요청드립니다.

하나의 지자체 데이터가 하나의 파일에 담기게 부탁드립니다.

10월 3일까지 부탁드립니다.

**Comment by aanoaa** [comment]
#!/bin/sh
    username=xxxxxxxxxxxxxxx
    password=xxxxxxxxxxxxxxx
    database=xxxxxxxxxxxxxxx
    
    for month in 7 8 9
    do
        month=$(printf '%02d' $month)
        next=$(expr $month + 1)
        next=$(printf '%02d' $next)
        for event in gunpo201901 gwangju201901 goyang201901 ansan201901 hwaseong201901 gimpo201901
        do
            echo "### $event-$month" >> $event.csv
            mysql -u $username -p$password -h 0.0.0.0 $database <<EOF | sed 's/\t/,/g' >> $event.csv
    SELECT
          e.name                                 AS event_name
        , o.id                                   AS order_id
        , u.id                                   AS user_id
        , DATE_FORMAT(b.date, "%Y-%m-%d")        AS booking_ymd
        , DATE_FORMAT(o.rental_date, "%Y-%m-%d") AS rental_ymd
        , u.name                                 AS user_name
        , ui.birth                               AS user_birth
        , c.id                                   AS coupon_id
        , c.code                                 AS coupon_code
        , c.status                               AS coupon_status
        , IF(o.online = 1, 'online', 'offline')  AS onoff
    FROM \`order\`          AS o
    LEFT JOIN \`coupon\`    AS c  ON o.coupon_id  = c.id
    LEFT JOIN \`event\`     AS e  ON c.event_id   = e.id
    LEFT JOIN \`user\`      AS u  ON o.user_id    = u.id
    LEFT JOIN \`user_info\` AS ui ON ui.user_id   = u.id
    LEFT JOIN \`booking\`   AS b  ON o.booking_id = b.id
    WHERE
        (
                e.name     = "$event"
            AND c.\`status\` = "used"
            AND o.parent_id IS NULL
            AND
                (
                       ( o.online <> 1 AND ( b.date        BETWEEN '2019-$month-01' AND '2019-$next-01' ) )
                    OR ( o.online <> 0 AND ( o.rental_date BETWEEN '2019-$month-01' AND '2019-$next-01' ) )
                    OR ( o.online <> 0 AND o.rental_date IS NULL )
                )
        )
    ORDER BY onoff, rental_ymd, booking_ymd;
    EOF
        done
    done

**Comment by aanoaa** [comment]
결과는 메일로 보내드렸습니다.

**Comment by aanoaa** [comment]
금일 21:00 까지의 데이터입니다.

**Comment by aanoaa** [comment]
파일이 클라이언트에서 안 열릴 수 있는데, notepad 로 `###` 로 시작하는 라인을 삭제해주셔야 합니다.

하나의 파일에서 월별로 구분하기 위해서 넣어둔 라인입니다.

**Comment by pingpongworks** [comment]
아, 왜 그랬는지 모르겠지만 제가 두 군데 지자체를 빼먹었네요. 

- anyang201901은 6월 22일 ~ 9월 30일까지 통계 부탁합니다
- hanam201901

**Comment by aanoaa** [comment]
하남시와 안양시 내역을 이메일로 전달해드렸습니다.

**Comment by pingpongworks** [comment]
확인했습니다. 감사합니다.
