### ISSUE TITLE
[쿠폰 종료] 남양주, 김포, 성남

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1611]
예산소진으로 무료대여사업이 종료된 지자체의 쿠폰이 올해 더이상 사용불가하도록 설정 요청합니다. 
사업종료 후 미리 받았던 쿠폰으로 무료 이용하려는 분들로 인해 혼란이 생깁니다. 

- 남양주
- 김포
- 성남

**Comment by aanoaa** [comment]
3 곳의 지자체 모두 이벤트 종료일이 `2019-12-31 23:59:59` 로 설정되어 있는데,
이 것을 현재 시간으로 변경하겠습니다.

발행된 쿠폰의 갯수로 조절하는 것이 아니라 이벤트 마감일로도 조절하네요.
초기에 예산이 정확하게 측정되었다면 발행/제한 갯수로 조절 하는 것이 더 안전하겠습니다.

```SQL
UPDATE `event` SET end_date = NOW() WHERE `name` IN ('namyangju201901', 'seongnam201901', 'gimpo201901');
SELECT name, end_date FROM `event` WHERE `name` IN ('namyangju201901', 'seongnam201901', 'gimpo201901');
```

**Comment by pingpongworks** [comment]
예산은 미리 정해져있으나, 
이용방법에 따라 온/오프 금액이 다른 지자체가 대부분이고, 쿠폰을 받기만하고 사용하지않는 대상자도 있어서 발행개수를 정확히 예측하고 제한하기는 어려울거 같습니다. 

올해는 예상보다 너무 빠르게 예산이 소진된 지자체가 많네요ㅜㅠ

**Comment by pingpongworks** [comment]
남양주 쿠폰 사용기한 
2019년 12월 31일로 재설정 요청드립니다.  

정식 프로그램 예산은 소진되었으나
취업박람회 단일 행사에서 정장대여 진행을 2회차 정도 할 예정입니다. 

11월 15일 (금) 1차 행사가 있으므로
11월 12일 (화) 밤에 쿠폰 사용이 가능하도록 설정 변경 부탁드립니다.

**Comment by aanoaa** [comment]
```sql
UPDATE `event` SET end_date = '2019-12-31 23:59:59' WHERE `name` = 'namyangju201901'
```

**Comment by aanoaa** [comment]
변경했습니다.
