### ISSUE TITLE
[쿠폰 제한] 고양시쿠폰 사용가능 기간 수정

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1614]
예산 소진으로 이후 11월 19일 (화) 예약자 2명까지만 사용이 가능해야 합니다. 

1.고양시쿠폰의 사용가능 기한을 11월 19일 (화)로 설정해주세요.

2. 이후로 예약된 인원이 있으면 명단 요청드립니다. 
    고양시에 전달하여 무료대여가 불가함을 개개인에게 전달해야 합니다.

**Comment by pingpongworks** [comment]
>2. 이후로 예약된 인원이 있으면 명단 요청드립니다. 
>고양시에 전달하여 무료대여가 불가함을 개개인에게 전달해야 합니다.

급해서 유관으로 체크해서 어제 보냈습니다.
2번 명단은 처리 안해주셔도 됩니다. 

1번은 이미 된거죠?

**Comment by aanoaa** [comment]
네 1번은 그날 했는데.. 2번은 못했습니다.

**Comment by pingpongworks** [comment]
괜찮아요~ 토요일에 1명 밖에 없었어서 체크해서 보냈어요~

**Comment by pingpongworks** [comment]
토요일에 1명은 잔여예산 몇 천원이라도 남아있으면 무료대여 해주기로해서 10월 이후 명단만 부탁해요. #1615
