### ISSUE TITLE
[서울시쿠폰] 19년 사업 종료, 예약가능일 및 사용가능일 설정

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1620]
2019년 사업을 마감하고 청구하기 위해 다음과 같이 이용 제한이 필요합니다. 

- 12월 24일 11시 59분 59초까지만 서울시쿠폰으로 예약행위가 가능하도록 설정해야함
- 24일 자정 전에 예약할 수 있는 기간은 12월 31일 11시 59분 59초까지만 가능하도록 설정해야함
- 24일 자정 전에 예약된 사람에 한해서 31일까지 사용은 가능해야함 

- 정산청구는 26일까지 해야하므로 25일~31일까지 서울시쿠폰으로 예약되어 있는 명단을  25일에 전달받아야함.
  (추후에 이 부분은 따로 이슈 올리겠습니다)

**Comment by aanoaa** [comment]
> 12월 24일 11시 59분 59초까지만 서울시쿠폰으로 예약행위가 가능하도록 설정해야함

이건 서울시쿠폰 예약 사이트에서 유입이 안되면 자연스레 해결되는 문제인데, 그럼에도 막아야 하나요?

> 24일 자정 전에 예약할 수 있는 기간은 12월 31일 11시 59분 59초까지만 가능하도록 설정해야함

이건 이미 그렇게 설정되어 있습니다.

**Comment by pingpongworks** [comment]
네, 아마도 서울시쿠폰 예약사이트에서 먼저 설정을 할 거 같아서 
행아웃으로 바로 작업할 필요는 없다고 이야기했던 거에요^^ 
혹시 우리 쪽에서도 확인해야할 내용이 있을까 해서 내용만 공유했어요. 
31일 지나서 따로 작업할 부분 없으면 이슈 닫을게요.
