### ISSUE TITLE
[쿠폰통계] 2019-10-01~2019-12-10까지 하남 쿠폰 이용자 및 12-10 이후 예약자 

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1621]
2019년 10월 1일부터 2019년 12월 10일까지
hanam201901 쿠폰을 사용한 대여자 명단과

2019년 12월 10일부터 12월 31일까지 
hanam201901 쿠폰으로 예약이 되어 있는 명단을
방문대여와 택배대여가 구분되도록 요청드립니다.

12월 12일 오전까지 서류제출과 계산서 발행이 끝나야하므로 
12월 11일 (수) 오전까지 부탁드립니다.

**Comment by aanoaa** [comment]
#!/bin/sh
    username=xxxxxxxxxxxxx
    password=xxxxxxxxxxxxx
    database=xxxxxxxxxxxxx
    
    mysql -u $username -p$password -h 0.0.0.0 $database <<EOF | sed 's/\t/,/g' > hanam201901-2019-10-to-2019-12-10.csv
    SELECT
          e.name                                 AS event_name
        , o.id                                   AS order_id
        , u.id                                   AS user_id
        , DATE_FORMAT(b.date, "%Y-%m-%d")        AS booking_ymd
        , DATE_FORMAT(o.rental_date, "%Y-%m-%d") AS rental_ymd
        , u.name                                 AS user_name
        , ui.birth                               AS user_birth
        , c.id                                   AS coupon_id
        , c.code                                 AS coupon_code
        , c.status                               AS coupon_status
        , IF(o.online = 1, 'online', 'offline')  AS onoff
    FROM \`order\`          AS o
    LEFT JOIN \`coupon\`    AS c  ON o.coupon_id  = c.id
    LEFT JOIN \`event\`     AS e  ON c.event_id   = e.id
    LEFT JOIN \`user\`      AS u  ON o.user_id    = u.id
    LEFT JOIN \`user_info\` AS ui ON ui.user_id   = u.id
    LEFT JOIN \`booking\`   AS b  ON o.booking_id = b.id
    WHERE
        (
                e.name     = "hanam201901"
            AND c.\`status\` = "used"
            AND o.parent_id IS NULL
            AND
                (
                       ( o.online <> 1 AND ( b.date        BETWEEN '2019-10-01' AND '2019-12-11' ) )
                    OR ( o.online <> 0 AND ( o.rental_date BETWEEN '2019-10-01' AND '2019-12-11' ) )
                    OR ( o.online <> 0 AND o.rental_date IS NULL )
                )
        )
    ORDER BY onoff, rental_ymd, booking_ymd;
    EOF

---

    #!/bin/sh
    username=xxxxxxxxxxxxx
    password=xxxxxxxxxxxxx
    database=xxxxxxxxxxxxx
    
    mysql -u $username -p$password -h 0.0.0.0 $database <<EOF | sed 's/\t/,/g' > hanam201901-rest-reservation.csv
    SELECT
          e.name                                 AS event_name
        , o.id                                   AS order_id
        , u.id                                   AS user_id
        , DATE_FORMAT(b.date, "%Y-%m-%d")        AS booking_ymd
        , DATE_FORMAT(o.rental_date, "%Y-%m-%d") AS rental_ymd
        , u.name                                 AS user_name
        , ui.birth                               AS user_birth
        , c.id                                   AS coupon_id
        , c.code                                 AS coupon_code
        , c.status                               AS coupon_status
        , IF(o.online = 1, 'online', 'offline')  AS onoff
    FROM \`order\`          AS o
    LEFT JOIN \`coupon\`    AS c  ON o.coupon_id  = c.id
    LEFT JOIN \`event\`     AS e  ON c.event_id   = e.id
    LEFT JOIN \`user\`      AS u  ON o.user_id    = u.id
    LEFT JOIN \`user_info\` AS ui ON ui.user_id   = u.id
    LEFT JOIN \`booking\`   AS b  ON o.booking_id = b.id
    WHERE
        (
                e.name     = "hanam201901"
            -- AND c.\`status\` = "used"
            AND o.parent_id IS NULL
            AND
                (
                       ( o.online <> 1 AND ( b.date        BETWEEN '2019-12-11' AND '2020-01-01' ) )
                    OR ( o.online <> 0 AND ( o.rental_date BETWEEN '2019-12-11' AND '2020-01-01' ) )
                    OR ( o.online <> 0 AND o.rental_date IS NULL )
                )
        )
    ORDER BY onoff, rental_ymd, booking_ymd;
    EOF

**Comment by aanoaa** [comment]
메일로 전달드렸습니다.

**Comment by pingpongworks** [comment]
앗, 본문에는 하남으로, 제목에는 남양주로 실수했네요. 하남으로 주셔서 감사합니다. 확인할게요.

**Comment by pingpongworks** [comment]
메일 확인했어요. 감사합니다.
