### ISSUE TITLE
오프라인 대여시 셋트품목이 아님에도 타이의 가격이 0원 으로 계산됨

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#1624]
자켓 + 타이 만 대여했을때에 는 `12,000` 이어야 하는데, `10,000` 으로 계산됩니다.
(품목 타이의 가격이 0 으로 되어 있기 때문에)

타이의 가격을 변경하는 것은 안되고(현재의 프로세스가 망가질 수 있음)
타이의 가격은 유지하되, 주문서의 상태가 포장 혹은 결제대기중 으로 변경될때에
셋트대여가 아닐경우에는 타이의 가격을 `2,000` 으로 업데이트 해주어야 합니다.

**Comment by aanoaa** [comment]
이제는 셋트 대여가 아닐때에는 타이의 가격이 2000원 으로 책정되고 3회 이상 대여등의 할인도 동작할 것으로 믿습니다.

**Comment by pingpongworks** [comment]
네~ 믿으셔도 됩니다. 감사합니다^^
