### ISSUE TITLE
대령님 테스트 데이터 cleaning

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#1626]
history 가 쌓이다보니 개인계정으로 테스트한 주문서가 너무 나도 많습니다.(100개 넘음)
그러다보니 테스트하기도 번거롭고 속도도 느립니다.

사용자 ID `3` 에 대해서 reset 해주어야 합니다.

**Comment by aanoaa** [comment]
UPDATE `order` SET status_id = 40 WHERE user_id = 3;

이렇게 변경을 해도 주문서의 상태를 구분해서 이력을 불러오는 것이 아니기 때문에 여전히 느립니다.
삭제를 해야 합니다.
큰 의미 없는 데이터라서 삭제해도 될 것 같습니다.

**Comment by aanoaa** [comment]
백업파일 있으니까..

```sql
DELETE FROM `order` WHERE user_id = 3;
```

이거 했습니다.
대령님의 주문내역을 삭제했습니다.

**Comment by aanoaa** [comment]
210 개 중에 203 개 삭제되었습니다.

**Comment by pingpongworks** [comment]
확인했어요. 감사합니다^^
