### ISSUE TITLE
예약버퍼가 차면 예약 슬롯을 동적으로 변경하는 기능

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#1627]
한번에 너무 많은 예약이 몰리지 않기 위해서 30분 간격으로 limit 을 두었습니다.

<table border="2" cellspacing="0" cellpadding="6" rules="groups" frame="hsides">

<colgroup>
<col  class="org-right" />

<col  class="org-right" />

<col  class="org-right" />
</colgroup>
<thead>
<tr>
<th scope="col" class="org-right">시간</th>
<th scope="col" class="org-right">남</th>
<th scope="col" class="org-right">여</th>
</tr>
</thead>

<tbody>
<tr>
<td class="org-right">09:00</td>
<td class="org-right">4</td>
<td class="org-right">5</td>
</tr>

<tr>
<td class="org-right">09:30</td>
<td class="org-right">5</td>
<td class="org-right">4</td>
</tr>
</tbody>
</table>

이렇게 했더니 발생하는 문제가 버퍼가 있음에도 남성에 몰리면 해당 시간에는 예약을 받지 못합니다.
물론 사용자들은 융통성있게 앞뒤 시간으로 예약을 시도하겠지만 성수기에는 그러기도 쉽지 않습니다.

해서 고민한 것이 같은 시간대의 다른 성별의 예약 버퍼를 자동으로 땡겨 올 수 있는 기능입니다.

<table border="2" cellspacing="0" cellpadding="6" rules="groups" frame="hsides">

<colgroup>
<col  class="org-right" />

<col  class="org-right" />

<col  class="org-right" />

<col  class="org-left" />

<col  class="org-left" />
</colgroup>
<thead>
<tr>
<th scope="col" class="org-right">시간</th>
<th scope="col" class="org-right">남(reserved,buffer)</th>
<th scope="col" class="org-right">여(reservedbuffer)</th>
<th scope="col" class="org-left">현황 및 버퍼</th>
<th scope="col" class="org-left">desc</th>
</tr>
</thead>

<tbody>
<tr>
<td class="org-right">09:00</td>
<td class="org-right">4(0)</td>
<td class="org-right">0(5)</td>
<td class="org-left">4/5</td>
<td class="org-left">&#xa0;</td>
</tr>

<tr>
<td class="org-right">09:00</td>
<td class="org-right">4(1)</td>
<td class="org-right">0(4)</td>
<td class="org-left">4/5</td>
<td class="org-left">1개 줌</td>
</tr>

<tr>
<td class="org-right">09:00</td>
<td class="org-right">5(0)</td>
<td class="org-right">0(4)</td>
<td class="org-left">5/4</td>
<td class="org-left">&#xa0;</td>
</tr>

<tr>
<td class="org-right">09:00</td>
<td class="org-right">5(1)</td>
<td class="org-right">0(3)</td>
<td class="org-left">5/4</td>
<td class="org-left">1개 줌</td>
</tr>

<tr>
<td class="org-right">09:00</td>
<td class="org-right">6(0)</td>
<td class="org-right">0(3)</td>
<td class="org-left">6/3</td>
<td class="org-left">&#xa0;</td>
</tr>

<tr>
<td class="org-right">09:00</td>
<td class="org-right">6(1)</td>
<td class="org-right">0(2)</td>
<td class="org-left">6/3</td>
<td class="org-left">1개 줌</td>
</tr>

<tr>
<td class="org-right">09:00</td>
<td class="org-right">7(0)</td>
<td class="org-right">0(2)</td>
<td class="org-left">7/2</td>
<td class="org-left">&#xa0;</td>
</tr>

<tr>
<td class="org-right">09:00</td>
<td class="org-right">7(1)</td>
<td class="org-right">0(1)</td>
<td class="org-left">7/2</td>
<td class="org-left">1개 줌</td>
</tr>

<tr>
<td class="org-right">09:00</td>
<td class="org-right">8(0)</td>
<td class="org-right">0(1)</td>
<td class="org-left">8/1</td>
<td class="org-left">&#xa0;</td>
</tr>

<tr>
<td class="org-right">09:00</td>
<td class="org-right">8(0)</td>
<td class="org-right">0(1)</td>
<td class="org-left">8/1</td>
<td class="org-left">1개 남은 버퍼는 줄 수 없음</td>
</tr>

<tr>
<td class="org-right">09:00</td>
<td class="org-right">8(0)</td>
<td class="org-right">1(0)</td>
<td class="org-left">9/0</td>
<td class="org-left">full 예약</td>
</tr>
</tbody>
</table>

극단적인 케이스인데, 9명 수용가능한 시간에 최초 설정은 남(4)/여(5) 로 설정했을때에
여성은 전혀 예약하지 않고 남성의 예약이 늘어난다고 가정합니다.

예약이 될때마다 현황과 예약 버퍼를 확인해서 1개의 버퍼가 남을때까지 다른 성별의 예약 slot 을 가져오는 방식입니다.

**Comment by aanoaa** [comment]
이것도 의존성 패키지를 서버에 설치하고 서비스를 재시작 해주었습니다.
실제 작업은 https://github.com/opencloset/OpenCloset-API/issues/28 에서 이루어졌습니다.
지금부터는 동적으로 예약가능인원이 조절됩니다.

**Comment by aanoaa** [comment]
테스트를 해보시려면 지금 데이터 기준으로 금일 17:00 에 여성으로 예약하면,

남성 slot/여성 slot 이

3/3 -> 2/4 되는 것을 확인하시면 되겠습니다.

**Comment by pingpongworks** [comment]
네, 확인했어요~ 잘 되고 있습니다.
