### ISSUE TITLE
[통계 요청] 2019년 기증, 봉사, 대여 관련 통계

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1642]
한 해 성과 정리를 위해 요청합니다.

**- 기간 : 2019년 1월 1일 ~ 12월 28일**

1. 기증 관련 통계
- 총 기증자수
- 총 기증의류수
-  품목별 기증의류 수 : (남성) 자켓, 팬츠, 셔츠, 타이, 구두, 벨트, 코트 / (여성) 자켓, 팬츠, 스커트, 원피스, 블라우스, 구두
- 기증의류 중 **열린옷장**으로 등록된 품목별 의류수 (구매한 의류의 비중을 보려고 합니다) 
- 재기증 의류수 (활용되지않고 비전트레이닝, 옷캔 등으로 보내진 의류수)

2. 편지 관련 통계
- 기증자 편지 수
- 대여자 편지 수

3. 봉사 관련 통계
- 전체 봉사자 수

4. 대여 관련 통계
- 총 대여자 중 재대여 수 : 1회 재대여 / 2회 재대여 / 3회 재대여 / 4회 재대여 / 5회 재대여
- 전체 대여의류 수 중 **열린옷장**으로 등록된 의류 수 품목별로
- 전체 의류 중 1년 동안 폐기된 의류수 품목별로

**Comment by aanoaa** [comment]
> 품목별 기증의류 수 : (남성) 자켓, 팬츠, 셔츠, 타이, 구두, 벨트, 코트 / (여성) 자켓, 팬츠, 스커트, 원피스, 블라우스, 구두

팬츠는 남성/여성 구분되어 있지 않습니다.

**Comment by aanoaa** [comment]
> 전체 의류 중 1년 동안 폐기된 의류수 품목별로

폐기된 날짜를 기록하지 않고 있어서 이건 구하기 어렵겠습니다.
작년 데이터가 있다면 그걸 차감하면 올해 폐기된 숫자가 됩니다.

**Comment by aanoaa** [comment]
@pingpongworks 기증관련 통계에서 폐기된 의류 숫자도 필요하지 않을까요?

기증의류는 `활용|재활용|폐기` 로 나뉘는데 총 기증의류 수 에서 재활용만 차감하면 활용되는 의류의 숫자가 커질 수 있습니다.

**Comment by pingpongworks** [comment]
@aanoaa 네 , 폐기도 포함입니다.

**Comment by aanoaa** [comment]
> 4-2 전체 대여의류 수 중 열린옷장으로 등록된 의류 수 품목별로

이건 고민을 좀 해봐야해서.. 이거 빼고 우선 전달드리고 구해보겠습니다.

**Comment by aanoaa** [comment]
# Table of Contents

1.  [기증 관련 통계](#orgad4096c)
    1.  [총 기증자수](#org9240737)
    2.  [총 기증 건수](#orgd7fa146)
    3.  [총 기증의류수](#org480053c)
    4.  [품목별 기증의류 수 : (남성) 자켓, 팬츠, 셔츠, 타이, 구두, 벨트, 코트 / (여성) 자켓, 팬츠, 스커트, 원피스, 블라우스, 구두](#org414fe86)
    5.  [기증의류 중 열린옷장으로 등록된 품목별 의류수 (구매한 의류의 비중을 보려고 합니다)](#org26e956d)
    6.  [재기증 의류수 (활용되지않고 비전트레이닝, 옷캔 등으로 보내진 의류수)](#org30ca06c)
    7.  [폐기된 의류 수](#org32e6543)
2.  [편지 관련 통계](#orga08fd9c)
    1.  [기증자 편지 수](#orgddc0ec3)
    2.  [대여자 편지 수](#org9e0e033)
3.  [봉사 관련 통계](#org481f0a3)
    1.  [전체 봉사자 수](#org9eaf091)
4.  [대여 관련 통계](#orge2ee3be)
    1.  [총 대여자 중 재대여 수 : 1회 재대여 / 2회 재대여 / 3회 재대여 / 4회 재대여 / 5회 재대여](#org913ee48)
    2.  [전체 대여의류 수 중 열린옷장으로 등록된 의류 수 품목별로](#org4529909)
    3.  [전체 의류 중 1년 동안 폐기된 의류수 품목별로](#orgcd3e166)


<a id="orgad4096c"></a>

# 기증 관련 통계


<a id="org9240737"></a>

## 총 기증자수

    -- 기증자 수
    SELECT COUNT(d.user_id) FROM (
      SELECT user_id FROM donation WHERE create_date BETWEEN '2019-01-01' AND '2019-12-29' GROUP BY user_id
    ) d;


<a id="orgd7fa146"></a>

## 총 기증 건수

    -- 기증 건수
    SELECT COUNT(1) AS '총 기증 건수' FROM donation WHERE create_date BETWEEN '2019-01-01' AND '2019-12-29';


<a id="org480053c"></a>

## 총 기증의류수

    -- 기증 의류 수
    SELECT COUNT(1) AS '기증 의류 수'
    FROM clothes c
    JOIN donation d ON c.donation_id = d.id
    WHERE d.create_date BETWEEN '2019-01-01' AND '2019-12-29';


<a id="org414fe86"></a>

## 품목별 기증의류 수 : (남성) 자켓, 팬츠, 셔츠, 타이, 구두, 벨트, 코트 / (여성) 자켓, 팬츠, 스커트, 원피스, 블라우스, 구두

    -- 품목별 기증의류 수 : (남성) 자켓, 팬츠, 셔츠, 타이, 구두, 벨트, 코트 / (여성) 자켓, 팬츠, 스커트, 원피스, 블라우스, 구두
    SELECT c.category AS '카테고리', COUNT(c.category) AS '의류 수'
    FROM clothes c
    JOIN donation d ON c.donation_id = d.id
    WHERE d.create_date BETWEEN '2019-01-01' AND '2019-12-29'
    GROUP BY c.category;


<a id="org26e956d"></a>

## 기증의류 중 열린옷장으로 등록된 품목별 의류수 (구매한 의류의 비중을 보려고 합니다)

    -- 기증의류 중 열린옷장으로 등록된 품목별 의류수 (구매한 의류의 비중을 보려고 합니다)
    SELECT c.category AS '카테고리', COUNT(c.category) AS '의류 수'
    FROM clothes c
    JOIN donation d ON c.donation_id = d.id
    WHERE d.create_date BETWEEN '2019-01-01' AND '2019-12-29'
    AND d.user_id = 1
    GROUP BY c.category;


<a id="org30ca06c"></a>

## 재기증 의류수 (활용되지않고 비전트레이닝, 옷캔 등으로 보내진 의류수)

    -- 재기증 의류수 (활용되지않고 비전트레이닝, 옷캔 등으로 보내진 의류수)
    SELECT c.category AS '카테고리', COUNT(c.category) AS '의류 수'
    FROM clothes c
    JOIN donation d ON c.donation_id = d.id
    WHERE d.create_date BETWEEN '2019-01-01' AND '2019-12-29'
    AND c.status_id IN (45, 46, 57)
    GROUP BY c.category;


<a id="org32e6543"></a>

## 폐기된 의류 수

    SELECT c.category AS '카테고리', COUNT(c.category) AS '의류 수'
    FROM clothes c
    JOIN donation d ON c.donation_id = d.id
    WHERE d.create_date BETWEEN '2019-01-01' AND '2019-12-29'
    AND c.status_id IN (8, 47)
    GROUP BY c.category;


<a id="orga08fd9c"></a>

# 편지 관련 통계

    SELECT d.cnt AS '기증편지 수', o.cnt AS '대여편지 수'
    FROM (
      SELECT 1 AS tmp, COUNT(*) AS cnt
      FROM donation AS d
      WHERE
        d.create_date BETWEEN '2019-01-01' AND '2019-12-29'
        AND d.message IS NOT NULL
    ) d
    LEFT JOIN (
      SELECT 1 AS tmp, COUNT(*) AS cnt
      FROM `order` o
      WHERE
        o.create_date BETWEEN '2019-01-01' AND '2019-12-29'
        AND o.message IS NOT NULL
    ) o
    ON d.tmp = o.tmp;


<a id="orgddc0ec3"></a>

## 기증자 편지 수


<a id="org9e0e033"></a>

## 대여자 편지 수


<a id="org481f0a3"></a>

# 봉사 관련 통계


<a id="org9eaf091"></a>

## 전체 봉사자 수

    SELECT COUNT(1)
    FROM volunteer_work
    WHERE activity_from_date BETWEEN '2019-01-01' AND '2019-12-29'
    AND status = 'done';


<a id="orge2ee3be"></a>

# 대여 관련 통계


<a id="org913ee48"></a>

## 총 대여자 중 재대여 수 : 1회 재대여 / 2회 재대여 / 3회 재대여 / 4회 재대여 / 5회 재대여

    SELECT o.cnt AS '재대여횟수', COUNT(o.cnt) AS '합계' FROM (
      SELECT COUNT(user_id) AS cnt
      FROM `order`
      WHERE status_id = 9
      AND return_date BETWEEN '2019-01-01' AND '2019-12-29'
      GROUP BY user_id
    ) o
    GROUP BY o.cnt;


<a id="org4529909"></a>

## 전체 대여의류 수 중 열린옷장으로 등록된 의류 수 품목별로

이건 작업하는 중..


<a id="orgcd3e166"></a>

## 전체 의류 중 1년 동안 폐기된 의류수 품목별로

이건 total 인데, 작년 데이터가 있다면 그걸 차감하면 올해 폐기된 숫자가 됩니다

    SELECT c.category AS '카테고리', COUNT(c.category) AS '의류 수'
    FROM clothes c
    JOIN donation d ON c.donation_id = d.id
    WHERE c.status_id = 8
    GROUP BY c.category;

**Comment by aanoaa** [comment]
결과를 포함한 내용은 메일로 전달드리겠습니다.

**Comment by aanoaa** [comment]
> 전체 대여의류 수 중 열린옷장으로 등록된 의류 수 품목별로

    SELECT c.category, COUNT(c.category)
    FROM `order` o
    JOIN order_detail od ON o.id = od.order_id
    JOIN clothes c ON od.clothes_code = c.code
    JOIN donation d ON c.donation_id = d.id
    WHERE o.status_id = 9
    AND return_date BETWEEN '2019-01-01' AND '2019-12-29'
    AND d.user_id = 1
    GROUP BY c.category;

아래는 전체 대여의류 수 품목별로

    SELECT c.category, COUNT(c.category)
    FROM `order` o
    JOIN order_detail od ON o.id = od.order_id
    JOIN clothes c ON od.clothes_code = c.code
    WHERE o.status_id = 9
    AND return_date BETWEEN '2019-01-01' AND '2019-12-29'
    GROUP BY c.category;

**Comment by pingpongworks** [comment]
대여 목적별 통계도 추가로 부탁드릴게요. 
방문예약할 때 선택 가능한 항목이 다음과 같습니다.

입사면접
결혼식
상견례
대학원면접
모의면접
인턴면접
장례식
사진촬영
세미나
발표
공연
축제
OT
아르바이트
졸업식
입학식
기타

**Comment by aanoaa** [comment]
```
SELECT purpose, COUNT(1)
FROM `order`
WHERE rental_date BETWEEN '2019-01-01' AND '2019-12-29' GROUP BY purpose;
```
