### ISSUE TITLE
남성 키 구역별 / 남성정장의 사이즈별 대여 통계: 2019

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1644]
최근 특이체형인 남성 이용자가 급격히 많아지면서 남성 특이사이즈 의류 수급이 필요해졌습니다. 대여횟수 대비 부족한 의류의 사이즈 파악을 위해 다음의 통계를 요청합니다. 

- 기간 : 2019년 1월 1일 ~12월 31일
- 내용
1. 자켓 팔길이 59cm 이하인 남성정장의 자켓 윗배둘레 별 대여횟수
2. 자켓 팔길이 60~62cm인 남성정장의 자켓 윗배둘레 별 대여횟수
3. 자켓 팔길이 63cm 이상인 남성정장의 자켓 윗배둘레 별 대여횟수
4. 자켓 팔길이 59cm 이하인 남성정장의 팬츠 허리둘레 별 대여횟수
5. 자켓 팔길이 60~62cm인 남성정장의 팬츠 허리둘레 별 대여횟수
6. 자켓 팔길이 63cm 이상인 남성정장의 팬츠 허리둘레 별 대여횟수

**Comment by yongbin** [comment]
@pingpongworks  소령님 질문이 있습니다. 말씀하신 통계에서 *자켓 팔길이* 는 해당 옷을 대여해간 사람의 신체 팔길이를 말씀하시는거죠? 아니라면 팬츠의류는 팔길이가 없어서 말이 안될것 같은데 확인차 문의드립니다.

**Comment by yongbin** [comment]
#1529 와 동일이슈 @keedi 가 확인후 처리하거나 이슈 재배정 예정
