### ISSUE TITLE
[봉사] 날짜 선택 오류

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1649]
![봉사신청 오류_20200123_160205_1](https://user-images.githubusercontent.com/17288038/72964241-aa833580-3dfc-11ea-887b-b9f3f6ecbe8d.png)

봉사자가 봉사신청을 하려고 하는데 날짜 선택이 되지 않는 오류 현상이 나타나고 있습니다. 
확인부탁드립니다.

**Comment by aanoaa** [comment]
지금 시간 기준으로,
2월 21일은 승인된게 없는데 봉사 가능시간대가 없습니다.
2월 25일은 저녁시간대 한개가 유효합니다.

---

신청날짜 및 시간대는 기존에 신청 및 승인된 활동이 있는지 여부로 판단하고 있습니다.

21일은 아직 승인 or 취소가 안된거고.. 26일은 아직 신청되게 없어서 정상적으로 모든 시간대가 유효합니다.

요약하면, 아직 승인을 하지 않은 활동이 있어서 겹치는 시간대에 신청을 못하는 것 입니다.

제가 잘못 이해하고 있는 것이라면 특정 날짜 및 시간을 예로 들어주세요.

**Comment by pingpongworks** [comment]
승인 상황을 확인하지 않고 오류라고 생각한 거네요. 
번거롭게 해드렸습니다. 이슈 닫을게요.
