### ISSUE TITLE
출력물 의류태그에 tag 표시

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#1654]
둘다 tag 라서 좀 그렇긴 한데..

출력해서 사용하고 있는 의류 tag 의 젤 밑에 의류가 속한 soft tag 들을 나열해서 보여주도록 합니다.
출력해서 봤을때 이 의류는 어떠한 용도구나 를 구분하고자 함 입니다.

**Comment by keedi** [comment]
@pingpongworks 혹시 이것 여전히 필요한 작업일까요? 확인 부탁드립니다.

**Comment by pingpongworks** [comment]
현재는 필요하지 않을 걸로 판단됩니다. 닫겠습니다.
