### ISSUE TITLE
[의류 통계] 6개월 이상 상태의 변화가 없는 의류코드 리스트

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1655]
2019년 8월 1일 이후로 상태 변화가 없는 의류들의 리스트를 요청드립니다. 

6개월 이상 '대여가능'이라면 
더이상 대여의 가능성이 없는 의류로 분류해 폐기나 수선을 고려하려고 합니다.

6개월 이상 '수선' 혹은 '세탁'의 상태라면 
상태의 문제가 있는 의류이므로 찾아보거나 폐기로 변경하려고 합니다. 

위 작업을 통해 의류 수량의 허수를 줄이고자 합니다.

**Comment by keedi** [comment]
@pingpongworks 좀 까다로운 작업이라 진행을 못했었는데요. 여전히 필요한지 확인 부탁드려요

**Comment by pingpongworks** [comment]
수지니가 알려주는 의류 수량과 실제 보유수량이 차이가 많이 나고 있어서 오차를 줄이기 위해 요청드렸었는데, 요청했던 시점에서 많이 지난 후라 까다로운 과정을 통해서까지 필요한 작업일지 모르겠습니다. 일단 보류해주세요.
