### ISSUE TITLE
[문자발송] 서울시쿠폰 대상자에게 알림 문자

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1660]
**[열린옷장] 서울시 무료대여 정보알림**
현재 서울시 청년을 위한 연 10회 무료 정장대여 "취업날개 서비스" 진행중입니다. 주소지, 입사면접 증빙 등 자격요건과 필요서류를 확인하시고 소중한 혜택을 누리시기 바랍니다. 

서울시 취업날개 바로가기 => http://bitly.kr/yw53

**Comment by pingpongworks** [comment]
**문자전송 대상자**
- 사용자정보의 주소지 :  서울
- 태어난해 : 1985~2002
- 대여목적 : 입사면접, 인턴면접

위 요건에 해당되는 대여자는 방문예약 직후에 안내문자가 발송되면 좋겠습니다.

**Comment by aanoaa** [comment]
이건 기능은 됐는데 테스트를 못해봐서 쫄려서 배포를 못했습니다.

- OpenCloset::API v0.1.13 버전을 설치
- visit/staff pulling 하고(안해도됨) 서비스 재시작

이후에는 반드시 쿠폰없이 대상 타겟으로써 방문예약을 해보고 문자메세지가 정확하게 오는지 확인해봐야 합니다.
영업시간에 테스트하실 수 있을때 연락주시면 배포하겠습니다.

**Comment by pingpongworks** [comment]
오늘 아무때나 테스트해봐주셔도 됩니다~ 아니면 배포해주시면 저희가 테스트해도 됩니다. 예약자 많지않아서 별 문제 없을거 같아요.

**Comment by aanoaa** [comment]
배포 하고 테스트했을때에 대상자임에도 불구하고 SMS 를 받지 못했습니다.
조건이 잘못되었을 것 같습니다.
탐구생활이 필요합니다.

**Comment by aanoaa** [comment]
대여목적은 대여가 완료된 후에 주문서에 들어가는 정보이고, 입력했을 당시에는 사용자 정보에서 찾아봐야 합니다.

이게 원인이었습니다.

**Comment by aanoaa** [comment]
배포하였습니다. 다시 한번 테스트를 해주세요.

**Comment by pingpongworks** [comment]
성공입니다! 
감사합니다.

**Comment by pingpongworks** [comment]
문자 비용 절감을 위해 "서울시쿠폰 대상자 알림" 문자 발송 중단을 요청드립니다. 
간혹 예약을 안 하고 오는 분이 있더라도 최근 상황에서는 
안내할 시간 여유가 있어서 꼭 필요하지 않은 문자발송은 중단하려고 합니다. 
탐구생활까지 하면서 작업해주셨는데 아쉽지만 발송 중단해주세요.
