### ISSUE TITLE
대여목적 중 '면접 세부 목적별' 대여횟수 통계_2019년

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1667]
원래 3월 28일로 예정되었던 18만명이 응시하는 가장 큰 공무원시험인 
9급 공무원시험이 5월 이후로 잠정 무기한 연기되었습니다. 
사용자 정보에 대여자가 입력하는 대여목적 중 세부목적별 통계를 통해 
공무원 시험 연기가 올해 매출에 미칠 영향을 추정하고 
연기된 일정 이후에 이용자가 몰릴 것을 대비해 의류재고물량 대책 마련을 하고자 합니다. 

통계의 내역은 #1472와 같은 이슈입니다. 

    - 기간 : 2019년 1월 1일 ~12월 31일

다만, 대여자가 직접 기입한 내용이라 같은 '간호'직이라도 여러가지 표현으로 기입하였으므로
다음과 같은 키워드별로 통계를 내주시기를 요청드립니다.

**[직종별 키워드]**
    
    1.
    간호
    '간호'가 포함된
    병원
    '병원'이 포함된

    
    2.
    승무원
    '항공'이 포함된
    스튜어디스
    지상직

    3.
    공무원
    '공무원'이 포함된
    국가직
    '국가직'이 포함된
    공공기관
    '공공기관'이 포함된
    경찰
    '경찰'이 포함된
    소방
    '소방'이 포함된
    시청
    '시청'이 포함된

    4.
    임용직
    '임용직'이 포함된
    교사
    '교사'가 포함된
    교직
    '교직'이 포함된
    선생님

**Comment by aanoaa** [comment]
```sql
DROP TEMPORARY TABLE IF EXISTS temp;
CREATE TEMPORARY TABLE temp
    SELECT
        order_id
        , purpose
        , ymd
        , online
        , IF ( ( purpose LIKE '%간호%' OR purpose LIKE '%병원%' ), '간호/병원'
            , IF ( ( purpose LIKE '%승무원%' OR purpose LIKE '%항공%' OR purpose LIKE '%스튜디어스%' OR purpose LIKE '%지상직%' ), '항공'
                , IF ( ( purpose LIKE '%공무원%' or purpose LIKE '%국가직%' or purpose LIKE '%경찰%' or purpose LIKE '%소방%' or purpose LIKE '%시청%' ), '공무원'
                    , IF ( ( purpose LIKE '%임용직%' or purpose LIKE '%교사%' or purpose LIKE '%교직%' or purpose LIKE '%선생님%' ), '선생님'
                        , '기타'
                        )
                    )
                )
            ) AS purpose_group
    FROM
        (
            SELECT
                o.id                                                                                            AS order_id
                , IF ( o.purpose2 IS NOT NULL, o.purpose2, ui.purpose2 )                                        AS purpose
                , IF ( o.online <> 1, DATE_FORMAT(b.date, "%Y-%m-%d"), DATE_FORMAT(o.rental_date, "%Y-%m-%d") ) AS ymd
                , o.online                                                                                      AS online
            FROM `order`          AS o
            LEFT JOIN `status`    AS s  ON o.status_id  = s.id
            LEFT JOIN `booking`   AS b  ON o.booking_id = b.id
            LEFT JOIN `user`      AS u  ON o.user_id    = u.id
            LEFT JOIN `user_info` AS ui ON ui.user_id   = u.id
            WHERE
                (
                    s.`name` = '반납'
                    AND o.`parent_id` IS NULL
                    AND
                        (
                               ( o.online <> 1 AND YEAR(b.date)        = 2019 AND MONTH(b.date)        BETWEEN 1 AND 12 )
                            OR ( o.online <> 0 AND YEAR(o.rental_date) = 2019 AND MONTH(o.rental_date) BETWEEN 1 AND 12 )
                        )
                )
        ) AS T1
    ;
SELECT
    purpose_group
    , DATE_FORMAT(ymd, '%Y-%m') AS ym
    , COUNT(*)                  AS `count`
FROM temp
GROUP BY purpose_group, ym
;
DROP TEMPORARY TABLE IF EXISTS temp;
```

**Comment by aanoaa** [comment]
<table border="2" cellspacing="0" cellpadding="6" rules="groups" frame="hsides">


<colgroup>
<col  class="org-left" />

<col  class="org-right" />

<col  class="org-right" />
</colgroup>
<thead>
<tr>
<th scope="col" class="org-left">purpose\_group</th>
<th scope="col" class="org-right">ym</th>
<th scope="col" class="org-right">count</th>
</tr>
</thead>

<tbody>
<tr>
<td class="org-left">간호/병원</td>
<td class="org-right">2019-01</td>
<td class="org-right">87</td>
</tr>


<tr>
<td class="org-left">간호/병원</td>
<td class="org-right">2019-02</td>
<td class="org-right">62</td>
</tr>


<tr>
<td class="org-left">간호/병원</td>
<td class="org-right">2019-03</td>
<td class="org-right">61</td>
</tr>


<tr>
<td class="org-left">간호/병원</td>
<td class="org-right">2019-04</td>
<td class="org-right">55</td>
</tr>


<tr>
<td class="org-left">간호/병원</td>
<td class="org-right">2019-05</td>
<td class="org-right">59</td>
</tr>


<tr>
<td class="org-left">간호/병원</td>
<td class="org-right">2019-06</td>
<td class="org-right">89</td>
</tr>


<tr>
<td class="org-left">간호/병원</td>
<td class="org-right">2019-07</td>
<td class="org-right">239</td>
</tr>


<tr>
<td class="org-left">간호/병원</td>
<td class="org-right">2019-08</td>
<td class="org-right">125</td>
</tr>


<tr>
<td class="org-left">간호/병원</td>
<td class="org-right">2019-09</td>
<td class="org-right">140</td>
</tr>


<tr>
<td class="org-left">간호/병원</td>
<td class="org-right">2019-10</td>
<td class="org-right">73</td>
</tr>


<tr>
<td class="org-left">간호/병원</td>
<td class="org-right">2019-11</td>
<td class="org-right">106</td>
</tr>


<tr>
<td class="org-left">간호/병원</td>
<td class="org-right">2019-12</td>
<td class="org-right">53</td>
</tr>


<tr>
<td class="org-left">공무원</td>
<td class="org-right">2019-01</td>
<td class="org-right">18</td>
</tr>


<tr>
<td class="org-left">공무원</td>
<td class="org-right">2019-02</td>
<td class="org-right">16</td>
</tr>


<tr>
<td class="org-left">공무원</td>
<td class="org-right">2019-03</td>
<td class="org-right">117</td>
</tr>


<tr>
<td class="org-left">공무원</td>
<td class="org-right">2019-04</td>
<td class="org-right">44</td>
</tr>


<tr>
<td class="org-left">공무원</td>
<td class="org-right">2019-05</td>
<td class="org-right">185</td>
</tr>


<tr>
<td class="org-left">공무원</td>
<td class="org-right">2019-06</td>
<td class="org-right">74</td>
</tr>


<tr>
<td class="org-left">공무원</td>
<td class="org-right">2019-07</td>
<td class="org-right">169</td>
</tr>


<tr>
<td class="org-left">공무원</td>
<td class="org-right">2019-08</td>
<td class="org-right">533</td>
</tr>


<tr>
<td class="org-left">공무원</td>
<td class="org-right">2019-09</td>
<td class="org-right">95</td>
</tr>


<tr>
<td class="org-left">공무원</td>
<td class="org-right">2019-10</td>
<td class="org-right">51</td>
</tr>


<tr>
<td class="org-left">공무원</td>
<td class="org-right">2019-11</td>
<td class="org-right">98</td>
</tr>


<tr>
<td class="org-left">공무원</td>
<td class="org-right">2019-12</td>
<td class="org-right">68</td>
</tr>


<tr>
<td class="org-left">기타</td>
<td class="org-right">2019-01</td>
<td class="org-right">1652</td>
</tr>


<tr>
<td class="org-left">기타</td>
<td class="org-right">2019-02</td>
<td class="org-right">1314</td>
</tr>


<tr>
<td class="org-left">기타</td>
<td class="org-right">2019-03</td>
<td class="org-right">1441</td>
</tr>


<tr>
<td class="org-left">기타</td>
<td class="org-right">2019-04</td>
<td class="org-right">1610</td>
</tr>


<tr>
<td class="org-left">기타</td>
<td class="org-right">2019-05</td>
<td class="org-right">2357</td>
</tr>


<tr>
<td class="org-left">기타</td>
<td class="org-right">2019-06</td>
<td class="org-right">1873</td>
</tr>


<tr>
<td class="org-left">기타</td>
<td class="org-right">2019-07</td>
<td class="org-right">1549</td>
</tr>


<tr>
<td class="org-left">기타</td>
<td class="org-right">2019-08</td>
<td class="org-right">1733</td>
</tr>


<tr>
<td class="org-left">기타</td>
<td class="org-right">2019-09</td>
<td class="org-right">1645</td>
</tr>


<tr>
<td class="org-left">기타</td>
<td class="org-right">2019-10</td>
<td class="org-right">2012</td>
</tr>


<tr>
<td class="org-left">기타</td>
<td class="org-right">2019-11</td>
<td class="org-right">2886</td>
</tr>


<tr>
<td class="org-left">기타</td>
<td class="org-right">2019-12</td>
<td class="org-right">1900</td>
</tr>


<tr>
<td class="org-left">선생님</td>
<td class="org-right">2019-01</td>
<td class="org-right">39</td>
</tr>


<tr>
<td class="org-left">선생님</td>
<td class="org-right">2019-02</td>
<td class="org-right">10</td>
</tr>


<tr>
<td class="org-left">선생님</td>
<td class="org-right">2019-03</td>
<td class="org-right">1</td>
</tr>


<tr>
<td class="org-left">선생님</td>
<td class="org-right">2019-04</td>
<td class="org-right">6</td>
</tr>


<tr>
<td class="org-left">선생님</td>
<td class="org-right">2019-05</td>
<td class="org-right">6</td>
</tr>


<tr>
<td class="org-left">선생님</td>
<td class="org-right">2019-06</td>
<td class="org-right">2</td>
</tr>


<tr>
<td class="org-left">선생님</td>
<td class="org-right">2019-07</td>
<td class="org-right">5</td>
</tr>


<tr>
<td class="org-left">선생님</td>
<td class="org-right">2019-08</td>
<td class="org-right">4</td>
</tr>


<tr>
<td class="org-left">선생님</td>
<td class="org-right">2019-09</td>
<td class="org-right">6</td>
</tr>


<tr>
<td class="org-left">선생님</td>
<td class="org-right">2019-10</td>
<td class="org-right">5</td>
</tr>


<tr>
<td class="org-left">선생님</td>
<td class="org-right">2019-11</td>
<td class="org-right">15</td>
</tr>


<tr>
<td class="org-left">선생님</td>
<td class="org-right">2019-12</td>
<td class="org-right">11</td>
</tr>


<tr>
<td class="org-left">항공</td>
<td class="org-right">2019-01</td>
<td class="org-right">29</td>
</tr>


<tr>
<td class="org-left">항공</td>
<td class="org-right">2019-02</td>
<td class="org-right">15</td>
</tr>


<tr>
<td class="org-left">항공</td>
<td class="org-right">2019-03</td>
<td class="org-right">77</td>
</tr>


<tr>
<td class="org-left">항공</td>
<td class="org-right">2019-04</td>
<td class="org-right">31</td>
</tr>


<tr>
<td class="org-left">항공</td>
<td class="org-right">2019-05</td>
<td class="org-right">24</td>
</tr>


<tr>
<td class="org-left">항공</td>
<td class="org-right">2019-06</td>
<td class="org-right">13</td>
</tr>


<tr>
<td class="org-left">항공</td>
<td class="org-right">2019-07</td>
<td class="org-right">30</td>
</tr>


<tr>
<td class="org-left">항공</td>
<td class="org-right">2019-08</td>
<td class="org-right">21</td>
</tr>


<tr>
<td class="org-left">항공</td>
<td class="org-right">2019-09</td>
<td class="org-right">22</td>
</tr>


<tr>
<td class="org-left">항공</td>
<td class="org-right">2019-10</td>
<td class="org-right">56</td>
</tr>


<tr>
<td class="org-left">항공</td>
<td class="org-right">2019-11</td>
<td class="org-right">19</td>
</tr>


<tr>
<td class="org-left">항공</td>
<td class="org-right">2019-12</td>
<td class="org-right">7</td>
</tr>
</tbody>
</table>

**Comment by pingpongworks** [comment]
‘선생님’ 통계에 임용직, 교사, 교직이 모두 포함된건가요? 숫자가 생각보다 너무 적어서요

**Comment by aanoaa** [comment]
네 포함되었습니다.
각각 따로 뽑아서 수치를 확인해보겠습니다.

**Comment by aanoaa** [comment]
대여목적이 선생님인 결과는 따로 뽑아봐도 수치가 같습니다(중복건에 의해 오차가 조금 있지만)

**Comment by pingpongworks** [comment]
그런가요. 알겠습니다.
