### ISSUE TITLE
예약 슬롯 조정

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1668]
대여 감소 때문에 근무인원을 축소하고 예약슬롯을 아예 조정하고자 합니다. 매일 전체를 수정하기는 너무 번거로워서 수정 부탁드립니다.  

<img width="462" alt="스크린샷 2020-03-09 오후 5 38 12" src="https://user-images.githubusercontent.com/17288038/76196024-d0d62680-622c-11ea-8f0b-861dbc3af29b.png">

**Comment by aanoaa** [comment]
아직 활성화 되지 않은 2020-04-06 부터는 활성화 하면 위 인원대로 예약인원이 설정될 것으로 믿습니다.

**Comment by pingpongworks** [comment]
4월 6일부터는 반영되었습니다. 근데 예전에는 이미 열려있는 날짜라도 설정을 바꾼 후에 `예약활성화`누르면 바뀐 설정으로 되었던 거 같은데, 4월 6일 이전은 일일이 바꿔야 하는 건가요?
