### ISSUE TITLE
코트 대여횟수 통계 

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1670]
겨울 동안 코트가 대여된 횟수 통계를 요청드립니다. 
코트 대여 현황을 파악한 후 계절이 바뀌는 시기에 코트 기증 요청을 하려고 합니다. 

- 품목 : 남/여 코트
- 기간 : 2019년 11월 1일 ~2020년 2월 29일 
- 통계내용 : 남여별, 월별 코트대여 횟수 / 대여된 코트 중 많이 대여된 순위

**Comment by aanoaa** [comment]
제가 의도를 정확하게 파악한지는 모르겠는데, 수가 그리 많지는 않습니다.
남녀 합쳐서 2019.11 ~ 2020.03 까지의 코드 대여횟수는 87건 입니다.

수가 많지 않아서 따로 보내드리지 않고 코멘트에 첨부합니다.

    SELECT ui.gender as gender, DATE_FORMAT(o.rental_date, '%Y.%m') as 'year.month', COUNT(1) AS 'rental count(coat)'
    FROM `order` o
    JOIN `user_info` ui ON o.user_id = ui.user_id
    JOIN `order_detail` od ON o.id = od.order_id
    WHERE o.rental_date BETWEEN '2019-11-01' AND '2020-03-01'
    AND od.clothes_code LIKE '0C%'
    GROUP BY ui.gender, DATE_FORMAT(o.rental_date, '%Y.%m');

    # 코드 대여 통계 per gender and month
    +--------+------------+--------------------+
    | gender | year.month | rental count(coat) |
    +--------+------------+--------------------+
    | female | 2019.11    |                  8 |
    | female | 2019.12    |                  6 |
    | female | 2020.01    |                  6 |
    | female | 2020.02    |                  6 |
    | male   | 2019.11    |                  7 |
    | male   | 2019.12    |                 22 |
    | male   | 2020.01    |                 13 |
    | male   | 2020.02    |                 19 |
    +--------+------------+--------------------+

---

    SELECT od.clothes_code AS code, COUNT(1) AS 'rental count'
    FROM `order` o
    JOIN `order_detail` od ON o.id = od.order_id
    WHERE o.rental_date BETWEEN '2019-11-01' AND '2020-03-01'
    AND od.clothes_code LIKE '0C%'
    GROUP BY od.clothes_code
    ORDER BY COUNT(1) DESC;

    코드 대여 통계 top rental count
    +-------+--------------+
    | code  | rental count |
    +-------+--------------+
    | 0C0C4 |            8 |
    | 0C0B9 |            6 |
    | 0C07L |            5 |
    | 0C0CJ |            5 |
    | 0C09E |            4 |
    | 0C08Q |            4 |
    | 0C09I |            4 |
    | 0C0BG |            3 |
    | 0C0BM |            3 |
    | 0C097 |            3 |
    | 0C088 |            2 |
    | 0C002 |            2 |
    | 0C0BL |            2 |
    | 0C006 |            2 |
    | 0C07H |            2 |
    | 0C08V |            2 |
    | 0C008 |            2 |
    | 0C07I |            2 |
    | 0C0A6 |            2 |
    | 0C0BS |            2 |
    | 0C07P |            2 |
    | 0C0AN |            2 |
    | 0C0B7 |            2 |
    | 0C048 |            1 |
    | 0C09C |            1 |
    | 0C04F |            1 |
    | 0C089 |            1 |
    | 0C004 |            1 |
    | 0C07F |            1 |
    | 0C09K |            1 |
    | 0C08W |            1 |
    | 0C038 |            1 |
    | 0C090 |            1 |
    | 0C0AA |            1 |
    | 0C0BU |            1 |
    | 0C03A |            1 |
    | 0C092 |            1 |
    | 0C03O |            1 |
    | 0C07Q |            1 |
    +-------+--------------+

**Comment by pingpongworks** [comment]
이렇게 주시면 됩니다. 감사합니다.
