### ISSUE TITLE
사용자 정보에 블라우스 대신 계산된 기성복 사이즈를 나타냄

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#1682]
1.  [남성자켓](#org186ff0a)
    1.  [조건1 - 윗배둘레](#orgf3f52f4)
    2.  [조건2 - 가슴둘레](#orgffe3b35)
2.  [남성팬츠](#org9c6aee2)
3.  [여성자켓](#org2903597)
4.  [여성 스커트/팬츠](#org655f0c9)

기존 사용자정보에 블라우스 종류를 선택하게 되어있는 부분을 대체해야 합니다.

<a id="org186ff0a"></a>

# 남성자켓

키/몸무게/가슴둘레를 입력합니다.

키와 몸무게로 평균 윗배둘레를 알 수 있습니다.

아래 조건1 과 조건2 중에 더 큰것을 선택해야 합니다.

<a id="orgf3f52f4"></a>

## 조건1 - 윗배둘레

<a id="orgffe3b35"></a>

## 조건2 - 가슴둘레

<a id="org9c6aee2"></a>

# 남성팬츠

<a id="org2903597"></a>

# 여성자켓

<a id="org655f0c9"></a>

# 여성 스커트/팬츠

**Comment by aanoaa** [comment]
이렇게 키/몸무게/가슴둘레 를 가지고 대여자의 상의 하의/사이즈를 계산해낼 수 있습니다.
그렇게 계산된 상의/하의 사이즈를 블라우스를 선택하는 버튼을 제거하고 그 공간에 대체하여 넣어야 합니다.

**Comment by aanoaa** [comment]
각각의 케이스 유형을 적어주시면 테스트하는데 도움이 되겠습니다.

cm/kg 으로..

남성/키/몸무게/가슴둘레/윗배둘레/허리둘레 - 일반 사이즈
남성/키/몸무게/가슴둘레/윗배둘레/허리둘레 - 마른 사이즈
남성/키/몸무게/가슴둘레/윗배둘레/허리둘레 - 큰 사이즈

여성/키/몸무게/가슴둘레/윗배둘레/엉덩이둘레 - 일반 사이즈

이러이러한 사이즈일때 상의 xx, 하의 xx 이다.
라는 예측 값 과 함께 적어주세요.

**Comment by aanoaa** [comment]
각각의 조건은 고유해주신 notion 의 본문을 참고하도록 하겠습니다.

**Comment by pingpongworks** [comment]
>남성/키/몸무게/가슴둘레/윗배둘레/허리둘레 - 일반 사이즈 => `user/109136`
>남성/키/몸무게/가슴둘레/윗배둘레/허리둘레 - 마른 사이즈 => `user/29570`
>남성/키/몸무게/가슴둘레/윗배둘레/허리둘레 - 큰 사이즈 => `user/18976`
>여성/키/몸무게/가슴둘레/윗배둘레/엉덩이둘레 - 일반 사이즈 => `user/139123`

**Comment by aanoaa** [comment]
일반사이즈로 테스트해보았습니다.

가슴둘레 평균치(95.3) 으로 기대되는 값은 105 사이즈 입니다.
그런데 말씀해주신 표본의 사이즈는 100 입니다.
또 허리둘레 `84cm` 를 inch 로 변환하면 `33.07` 입니다.
이럴 경우에는 34가 맞는 것이 아닌가요?
표본에는 32로 되어 있습니다.

제가 잘못이해했거나, 테스트 케이스가 잘못되었거나 입니다.

**Comment by aanoaa** [comment]
참조해야 하는 사이즈표가 있습니다.
일반적인 cm 로 계산하면 안됩니다.

열린옷장에서 규격화한 사이즈 체계표를 참고해야 합니다.
해당 체계는 notion 문서에 정리되어 있습니다.

**Comment by aanoaa** [comment]
남성 큰 사이즈의 경우 `125B` 로 예상되는데, `120` 이라고 적혀있습니다.
어느 값이 정확한 것인지 검토해주셔야 합니다.

**Comment by aanoaa** [comment]
여성 일반사이즈의 경우에도 기대값은 `88` 이지만 `77`로 적혀있습니다.
어느 값이 정확한 것인지 검토해주세요.

**Comment by pingpongworks** [comment]
>남성 큰 사이즈의 경우 125B 로 예상되는데, 120 이라고 적혀있습니다.
어느 값이 정확한 것인지 검토해주셔야 합니다.

=> 가슴둘레를 고려하면 125B가 맞습니다.

**Comment by pingpongworks** [comment]
>여성 일반사이즈의 경우에도 기대값은 88 이지만 77로 적혀있습니다.
어느 값이 정확한 것인지 검토해주세요.

=> 이 케이스의 경우는 가슴둘레 .5 때문에 88로 넘어가는게 맞네요. 그런데 실제 입은 옷은 77입니다. 최근 몇가지 케이스를 더 보아도 실측 가슴둘레 때문에 한 사이즈 위로 올라가는데 실제로 입은 옷은 한 사이즈 아래인 경우가 더러 있어서 여성의 경우 가슴둘레보다 크게 하는게 맞을지 내부적으로 검토 한번 해보겠습니다.

**Comment by aanoaa** [comment]
![Screenshot(2)](https://user-images.githubusercontent.com/170528/78467665-dbabaa80-7749-11ea-9d50-c67d1e45914d.png)

블라우스 선택 버튼을 없애고 열린옷장에서 규격화한 사이즈를 상하의로 나타내도록 했습니다.
아직 배포는 하지 않았습니다.

**Comment by pingpongworks** [comment]
와우~ 작업이 다 되었네요. 여성 의류 규칙만 검증해보고 저녁에 전달할게요.

**Comment by aanoaa** [comment]
staff 에 배포되었습니다.
모니터에는 아직 작업 못 했습니다.

**Comment by pingpongworks** [comment]
`user/139260`여성의 상의는 66.5(66반)을 추천했는데
평균윗배 70.9로 하면 66.5이지만 실측치수 70으로 하면 66입니다. 
실측 사이즈가 입력되어 있을 때는 실측사이즈가 우선적으로 적용되어야 할 듯 합니다.

**Comment by pingpongworks** [comment]
`user/139283`남성 케이스는 정확했습니다. 
다만 허벅지둘레까지 고려해서 `34S`로 추천이 되면 의류선택이 더 빠를 거 같습니다. 
참고해주세요.

**Comment by pingpongworks** [comment]
<img width="401" alt="스크린샷 2020-04-08 오전 11 39 05" src="https://user-images.githubusercontent.com/17288038/78738790-ae4f3e80-798d-11ea-9cae-0842f6d3de1b.png">

`user/3`
제 사용자 정보에 해보고 지금 발견한건데, 평균의 반올림값을 자동입력한다고 되어 있는데 실제로는 반올림값이 아니라 소수점을 뗀 수치가 입력되네요. 수지니 자체가 기본적으로 소수점을 패스하는 시스템인지 확인 부탁드립니다.  소수점을 무시할건지, 반올림할건지 통일하는게 좋을 거 같아서요.

**Comment by aanoaa** [comment]
> user/139260여성의 상의는 66.5(66반)을 추천했는데
> 평균윗배 70.9로 하면 66.5이지만 실측치수 70으로 하면 66입니다.
> 실측 사이즈가 입력되어 있을 때는 실측사이즈가 우선적으로 적용되어야 할 듯 합니다.

실측이 우선되어야 하는 것은 맞는데, 윗배는 실측 안하지 않나요?

**Comment by pingpongworks** [comment]
>실측이 우선되어야 하는 것은 맞는데, 윗배는 실측 안하지 않나요?

대부분은 안 하는데 모집군수 30명 이하이면 전체 사이즈를 실측하니까요. 실측사이즈 입력란에 입력이 되어있는 사이즈의 경우는 실측사이즈가 우선되어야 할 거 같아요.

**Comment by pingpongworks** [comment]
`user/139255`

상의사이즈 115가 나와야 맞는 사이즈인데 120이 추천되었습니다. 확인 바랍니다.

**Comment by aanoaa** [comment]
가슴둘레 실측 110 에서 +6 하면 116 이고 이는 가슴둘레 상한치 115를 넘어가기 때문에 120 이 맞는거 아닌가요?

**Comment by pingpongworks** [comment]
남여 자켓의 테이블이 숫자 하나씩 잘못되었습니다. 다시 전달하겠습니다.

**Comment by aanoaa** [comment]
변경된 룰에 의하면 사용자 139123 의 상의는 `77`로 예상되는데 `88`이라고 해놓으셨습니다.
어느 것이 맞는지 확인해주세요.

**Comment by pingpongworks** [comment]
변경된 룰로 하면 77 맞아요.  제가 이전 룰로 적어놓은 거 그냥 둬서 그래요. 이제 문제 없을 거 같아요. 배포 부탁드려요~

**Comment by aanoaa** [comment]
배포했습니다.
운영해보시면서 피드백 주세요.

**Comment by pingpongworks** [comment]
네^^ 감사합니다. 며칠 사용해보고 문제없으면 제가 이슈 닫을게요.

**Comment by aanoaa** [comment]
모니터에도 배포 했습니다.

**Comment by pingpongworks** [comment]
오늘 대여했던 사람들 검증결과는 모두 정확했습니다. 문제 있으면 다시 열겠습니다.

**Comment by pingpongworks** [comment]
`user/139368`
`user/131386`

둘다 바지 사이즈가 오류입니다. 
R로 나와야 하는데 S로 나왔습니다. 
아마도 허벅지둘레 +6이 제대로 안 된 거 같습니다.

**Comment by aanoaa** [comment]
`/user/139368` 사용자는 허벅지 둘레가 64 이고 0~ 69 에 해당하기 때문에 S 가 맞습니다.

**Comment by aanoaa** [comment]
`/user/131386` 사용자도 허벅지 둘레가 66 이고 이는 0 ~ 71 사이라서 S 가 맞습니다.

다른 치수들은 테이블에 pad 값(허벅지의 경우 +6)이 더해져 있지 않은 사용자의 치수인데 허벅지 둘레는 pad 값이 더해져 있는 치수 인가요?

pad 값이 구간마다 다르기 때문에 말씀해주셨던 pad 값을 일괄 적용하지 않았습니다.
테이블을 참고하면 정확하게 비교가 가능하기 때문입니다.

**Comment by pingpongworks** [comment]
> `/user/139368` 사용자는 허벅지 둘레가 64 이고 0~ 69 에 해당하기 때문에 S 가 맞습니다.

신체 허벅지둘레가 64니까 +6 하면 의류 허벅지둘레는 70이라서 R로 넘어가야 해요.

**Comment by pingpongworks** [comment]
> `/user/131386` 사용자도 허벅지 둘레가 66 이고 이는 0 ~ 71 사이라서 S 가 맞습니다.
> 
> 다른 치수들은 테이블에 pad 값(허벅지의 경우 +6)이 더해져 있지 않은 사용자의 치수인데 허벅지 둘레는 pad 값이 더해져 있는 치수 인가요?
> 
> pad 값이 구간마다 다르기 때문에 말씀해주셨던 pad 값을 일괄 적용하지 않았습니다.
> 테이블을 참고하면 정확하게 비교가 가능하기 때문입니다.

131386 사용자도 신체 허벅지둘레가 66이면 +6해서 72니까 R이 맞아요.남자 바지 테이블이 신체 / 의류 따로 계산해서 정리하지 않아서 헷갈리나봐요. 자켓과 같은 형태로 테이블 정리해서 올려놓았습니다. 확인 부탁드립니다.

**Comment by aanoaa** [comment]
허벅지 치수 변경해서 반영했습니다.
위 두개의 케이스 결과 확인했습니다.
