### ISSUE TITLE
[방문예약] 대여목적 선택리스트에 "화상면접" 추가

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1684]
<img width="272" alt="스크린샷 2020-04-09 오후 4 38 03" src="https://user-images.githubusercontent.com/17288038/78871140-36af0b80-7a82-11ea-9378-15807baec037.png">

코로나19로 화상면접이 많아짐에 따라 대여자의 목적에 따라 적절한 서비스를 제공하는 동시에 
화상면접 스타일링을 특화해보려고 합니다. 

맨 첫 줄의 입사면접 항목을 다음과 같이 수정 요청합니다. 

    입사면접 (대면면접)
    입사면접 (화상면접)

**Comment by keedi** [comment]
예약 페이지에서 구현한 화면은 다음과 같습니다. 기본적으로 화상면접과 대면면접을 선택하는 UI는 보이지 않도록 합니다.

![screenshot-visit theopencloset net-2020-04-14-03-15-55](https://user-images.githubusercontent.com/138451/79147179-808b4f00-7dfe-11ea-940d-be43495ef8de.png)

**Comment by keedi** [comment]
입사면접을 선택하면 화상면접 또는 대면면접을 선택할 수 있는 UI가 나타나며, 나타난 이후에 고를 수 있습니다.

![screenshot-visit theopencloset net-2020-04-14-03-14-32](https://user-images.githubusercontent.com/138451/79147301-b0d2ed80-7dfe-11ea-974c-36e0119c8045.png)

**Comment by keedi** [comment]
입사면접 이외의 대여 목적을 선택할 경우에는 UI가 사라집니다.

![screenshot-visit theopencloset net-2020-04-14-03-15-28](https://user-images.githubusercontent.com/138451/79147338-c2b49080-7dfe-11ea-9c7a-4aef3b45983b.png)

**Comment by keedi** [comment]
주문서 페이지에서 화상면접 여부를 확인할 수 있는 화면은 다음과 같습니다.

![screenshot-staff theopencloset net-2020-04-14-03-12-05](https://user-images.githubusercontent.com/138451/79147423-dd870500-7dfe-11ea-80ff-6712e1c46b5e.png)

**Comment by keedi** [comment]
기본적으로 스키마 변경없이 구현했으며, 대신, 의류처럼 주문서도 태그를 가질 수 있도록 추가한 후 태그 기능을 이용해서 본 기능을 구현했습니다. 따로 태그와 관련한 이슈가 아니기 때문에 범용적인 주문서와 태그를 연결짓는 UI를 따로 만들지는 않았습니다.

**Comment by keedi** [comment]
브라우저 캐시가 남아서 동작하지 않을 수 있으므로 새로운 기능을 확인하려면 반드시 브라우저 새로 고침을 여러번 해서 캐시를 비운 뒤 확인해야 합니다.

**Comment by pingpongworks** [comment]
정상동작 확인했습니다. 감사합니더~

**Comment by pingpongworks** [comment]
<img width="351" alt="스크린샷 2020-04-14 오후 3 25 14" src="https://user-images.githubusercontent.com/17288038/79192762-4bb1e300-7e64-11ea-8a3e-d34368c63bc6.png">

마지막 주문서의 대여목적이 사용자정보의 대여목적에서도 보여지도록 요청드립니다. 
이용자가 방문했을 때 스태프는 치수측정을 하면서 대여목적을 알아야 적절한 서비스를 할 수 있습니다.

**Comment by keedi** [comment]
"화상면접" 선택 화면이 보이지 않는다는 보고가 있었습니다.

디버깅 결과 chosen 라이브러리가 모바일에서 비활성화 되는 이슈가 있습니다. 이를 라이브러리 패치로 강제로 활성화 시키도록 변경해서 해결했습니다. 관련해 다음과 같은 이슈가 있습니다.

- 모바일에서 chosen이 부작용(side-effect)이 없는가?
- chosen은 수명이 끝난(deprecated) 라이브러리인데 교체해야 하지 않겠는가?
- bower가 더이상 잘(smooth) 동작하지 않는데 교체해야 하지 않겠는가?

chosen의 경우 selectize로 교체하는 것이 바람직해보이며, bower를 사용하기 보단 npm을 직접 이용하는 것이 나을 것으로 보입니다. 본 이슈에서 해결할 것은 아니지만, 별도의 이슈로 추후 처리하도록 합니다. 더불어 방문 예약 페이지는 신규 페이지를 준비하는 만큼 수정하지 않는 방향으로 진행하되 신규 페이지로 이전이 완전히 완료되면 staff에 한해 상기 내용을 적용하는 것이 적절해보입니다.

**Comment by keedi** [comment]
수정 및 서버 배포, 테스트 완료했습니다.

**Comment by keedi** [comment]
사용자 정보 페이지와 의류 정보 페이지의 최근 주문서 내역에서 화상 면접 여부를 확인할 수 있게 수정했습니다.

구현한 화면은 다음과 같습니다.

![screenshot-staff theopencloset net i5 bebop 10301-2020-04-20-02-04-36](https://user-images.githubusercontent.com/138451/79694681-dd7a7f80-82ac-11ea-9f6f-dec399835916.png)

**Comment by pingpongworks** [comment]
네 확인했습니다. 

> <img alt="스크린샷 2020-04-14 오후 3 25 14" width="351" src="https://user-images.githubusercontent.com/17288038/79192762-4bb1e300-7e64-11ea-8a3e-d34368c63bc6.png">
> 
> 마지막 주문서의 대여목적이 사용자정보의 대여목적에서도 보여지도록 요청드립니다.
> 이용자가 방문했을 때 스태프는 치수측정을 하면서 대여목적을 알아야 적절한 서비스를 할 수 있습니다.

사용자정보의 신체 치수입력 위쪽에 표기되는 건 루트상 어려워서 차선으로 이렇게 작업을 해주신거죠? 일단은 이렇게 사용해보겠습니다. 다음으로 preparation에 적용 부탁드립니다.
