### ISSUE TITLE
[서버] 홈페이지 서버 이관

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1686]
4/10 (목) 논의 내용 올려둡니다. 

매달 큰 비용이 나가는 홈페이지 서버를 이관하는 작업 요청드립니다. 
매월 5일 자동이체가 되고 있으므로 가능하면 빠른 작업 부탁드립니다.

**Comment by keedi** [comment]
음, 홈페이지는 staff 의 영역이 아니긴한데, 이 부분은 좀 오해의 소지가 있어보이네요.

**Comment by yongbin** [comment]
별도 작업을 통해 이장님께서 코로케이션에서 호스팅으로 이관을 완료했습니다.
