### ISSUE TITLE
서울시쿠폰 대상자에게 알림 문자 발송 중단 

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1696]
꼭 필요하지 않은 문자 발송을 중단해야할 부득이한 상황이라 요청드립니다. 
#1660 이슈에서 작업했던 문자입니다.

**Comment by aanoaa** [comment]
https://github.com/opencloset/OpenCloset-Schema/issues/144
의 영향으로 새로운 패키지를 archive 에 업로드하는데에 문제가 있습니다.

직접 build 해서 로컬머신에 설치했습니다.
서버에는 이미 설치되어 있으니 영향이 없겠습니다만, OpenCloset::Schema 의 새로운 버전을 archive 에 업로드해두어야 합니다.

**Comment by aanoaa** [comment]
$ wget https://cpan.theopencloset.net/STAFF@THEOPENCLOSET.NET/OpenCloset-API-v0.1.16.tar.gz
    --2020-05-31 12:00:33--  https://cpan.theopencloset.net/STAFF@THEOPENCLOSET.NET/OpenCloset-API-v0.1.16.tar.gz
    Resolving cpan.theopencloset.net (cpan.theopencloset.net)... 61.100.184.211
    Connecting to cpan.theopencloset.net (cpan.theopencloset.net)|61.100.184.211|:443... connected.
    ERROR: The certificate of `cpan.theopencloset.net' is not trusted.

오잉 cpan.theopencloset.net 에 인증서 문제가 있습니다.

**Comment by aanoaa** [comment]
tarball 을 서버로 옮기고 직접 설치했습니다.
