### ISSUE TITLE
[staff 문자전송] 발신번호 설정  

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1698]
<img width="1177" alt="스크린샷 2020-06-02 오후 4 51 21" src="https://user-images.githubusercontent.com/17288038/83494617-809bf700-a4f1-11ea-8595-ad2ea4efca8a.png">

문자전송할 때 발신번호를 입력할 수 있게 되어 있는데, 열린옷장 대표번호로 발신번호를 입력해야만 문자 발송이 되고 있습니다. 기존에는 다른 번호를 입력해도 가능했었는데 언제부터인가 이렇게 대표번호 `02)6929-1020`으로만 가능하도록 바뀌어 있습니다. 추정해보는 것은 문자발송업체가 바뀐 시점이 아닐까 생각되는데 확인부탁드립니다. 

1) 원인이 무엇일까요? 
2) 원래대로 다른 번호로 발신이 가능하도록 할 수 있을까요?

**Comment by yongbin** [comment]
<img width="1005" alt="image" src="https://user-images.githubusercontent.com/52704/83561899-97733580-a553-11ea-88d7-6c40be5c617b.png">

1. 알리고쪽을 확인해보니 위와 같은 안내가 있었습니다. 알리고를 통해 발송하는 문자의 발송번호는 사전에 알리고 관리자를 통해 미리 등록을 해야만 발신번호 지정이 가능합니다.

2. 위 답변처럼 자주 발신번호로 사용하는 번호는 사전에 미리 등록하셔서 진행하면 되지만, 만약에 매번 변경되는 번호를 알리고 등록없이 웹상에서 보내는 케이스라면 불가능합니다.

ps. 확인해보니 알리고 관리자 웹을 이용한 문자 발송에서도 동일하게 발신번호 변경을 위해서는 추가 인증 및 등록이 필요합니다.

**Comment by pingpongworks** [comment]
추가로 번호등록을 해야겠네요. 확인감사드립니다. 제가 알리고에 요청하겠습니다.
