### ISSUE TITLE
이야기옷장 하단 푸터를 최신 정보로 갱신

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1714]
<img width="962" alt="이야기옷장 하단 푸터" src="https://user-images.githubusercontent.com/17288038/92360129-4ca32400-f127-11ea-80f2-ebd9e533d8d9.png">

이야기옷장 ( https://story.theopencloset.net/ ) 하단푸터에 오래된 내용이 많아서 수정요청드립니다.

**1. 열린봉사자 모집 삭제**
신청페이지도 예전 내용이고, 현재는 코로나 때문에 모집을 하지 않고 있습니다.

**2. 방문예약 / 온라인예약 표현 수정** 
=> 방문대여 예약 / 택배대여 신청

**3. 트위터, RSS구독 삭제**
둘다 운영하지 않고 있는 채널입니다.

**4. 블로그 추가**
https://blog.naver.com/open_closet

**Comment by keedi** [comment]
까맣게 잊고 있었네요;;; 처리 완료했습니다.
