### ISSUE TITLE
방문 예약시 대여 항목에서 원피스를 추가해 고를 수 있도록 함

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1718]
방문예약 페이지 **대여할 품목을 선택하세요**
맨 하단에 **원피스** 추가해주세요.

<img width="353" alt="스크린샷 2020-09-18 오후 4 59 47" src="https://user-images.githubusercontent.com/17288038/93572258-91a14300-f9d0-11ea-9f45-d0e05ab73ffb.png">

원피스를 찾는 분들이 많아졌고, 원피스 보유수량도 많아져 선택한 가능한 품목으로 추가 요청드립니다.

**Comment by keedi** [comment]
원피스를 선택할 수 있도록 수정한 화면은 다음과 같습니다.

![2020-10-11-181324_1916x1044_scrot](https://user-images.githubusercontent.com/138451/95674832-b6fb2880-0bed-11eb-9a43-22238025c449.png)

**Comment by keedi** [comment]
작업 완료했으며 서버에 배포 완료했습니다.

**Comment by pingpongworks** [comment]
네 감사합니다

**Comment by pingpongworks** [comment]
`user/146212`

- 대여희망품목에서 원피스를 삭제해도 삭제가 되지 않습니다.
- 신청 안 한 경우에 추가하려고 해도 품목이 뜨지 않습니다. 

확인부탁드립니다.

![캡처1](https://user-images.githubusercontent.com/17288038/96660523-b8aeb400-1384-11eb-8d3d-0944b595c6d8.JPG)

**Comment by keedi** [comment]
#1725 에서 처리하겠습니다.
