### ISSUE TITLE
[쿠폰 통계] 2020-07-01 ~ 2020-09-30까지 지자체 쿠폰 이용내역

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1721]
화성시 / hwaseong202001
안산시 / ansan202001
안양시 / anyang202001
군포시 / gunpo202001, gunpo202002
광주시 / gwangju202001
충주시 / chungju202001
원주시 / wonju202001
김포시 / gimpo202001

2020년 7월 1일부터 9월 30일까지
8개 지역의 쿠폰이용내역을
온라인과 오프라인 구분해서 부탁드립니다.
10월 5일 (월)까지 요청드립니다.

**Comment by aanoaa** [comment]
메일로 보내드렸습니다.
이벤트가 많아서 쿼리문은 생략합니다.
