### ISSUE TITLE
[의류수 통계] 품목별 '열린옷장' 등록 의류수

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1727]
사업계획 수립에 필요한 통계라 요청드립니다.

가용 수량 ( 대여가능, 대여중, 대여불가, 세탁, 수선, 반납 상태) 중
`열린옷장`이 기증자명으로 되어 있는 의류 수량 통계를 품목별 / 남여별로 요청드립니다. 

열린옷장 | 총계 | 남 | 여
-- | -- | -- | --
자켓 |   |   |  
팬츠 |   |   |  
스커트 |   |   |  
셔츠 |   |   |  
블라우스 |   |   |  
원피스 |   |   |  
코트 |   |   |  
조끼 |   |   |  
구두 |   |   |  
타이 |   |   |  
벨트 |   |   |  
가방 |   |   |  
기타 |   |   |  
합계 |   |   |

**Comment by yongbin** [comment]
```sql
select category, gender
from `clothes` as a
         inner join `status` as b on a.status_id = b.id
where b.name in ('대여가능', '대여중', '대여불가', '세탁', '수선', '반납') and a.gender in ('male', 'female');
```

위 쿼리로 나온 결과를 정맇해서 메일로 보내드렸습니다.

**Comment by pingpongworks** [comment]
보내주신 결과는 프로그램에 등록되어 있는 전체 수량인 거 같습니다. 
전체 수량은 수지니에서 확인이 가능합니다. 

요청드렸던 통계는 전체 의류 중 기증자가 "열린옷장"으로 되어 있는 의류의 수입니다. 
전체 의류 중 구매한 의류가 어느 정도 비율인지 확인하고자 했던 거라서 다시 요청드립니다.

**Comment by yongbin** [comment]
```sql
select category, gender
from `clothes` as a
         inner join `status` as b on a.status_id = b.id
         inner join donation d on a.donation_id = d.id
where b.name in ('대여가능', '대여중', '대여불가', '세탁', '수선', '반납')
  and a.gender in ('male', 'female')
    and d.user_id = 1
```

수정해서 재송부했습니다.
