### ISSUE TITLE
12월 뉴스레터를 위한 2020년 통계 요청

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1742]
`기간 : 2020년 1월 1일 ~ 12월 18일`

1. 기증건 수 
2. 재능나눔에 동의한 기증자 수
3. 기증자이면서 동시에 대여자인 이용자 명단
4. 2020년에 가장 많이 대여된 옷 : 남자 3건 / 여자 3건
5. 목적별 대여건 수 : 입사면접(대면면접) / 입사면접 (화상면접) / 결혼식 / 상견례 / 대학(원)면접 / 모의면접 / 인턴면접 / 장례식 / 사진촬영 / 세미나 / 발표 / 공연(연주회) / 축제(행사) / OT / 아르바이트 / 졸업식 / 입학식 / 기타
6. 이야기옷장에 등록된 기증편지 수/ 대여편지 수 
7. 품목별 기증의류 수량 / 사용 수량 / 재기증 수량 / 폐기 수량
8. 창사 이후 역대 최다회 기증자/ 대여자

12월 20일 (일) 저녁까지 부탁드립니다.

**Comment by yongbin** [comment]
-   기간 : 2020년 1월 1일 ~ 12월 18일
    1.  기증건 수
    2.  재능나눔에 동의한 기증자 수
    3.  기증자이면서 동시에 대여자인 이용자 명단
    4.  2020년에 가장 많이 대여된 옷 : 남자 3건 / 여자 3건
    5.  목적별 대여건 수 : 입사면접(대면면접) / 입사면접 (화상면접) / 결혼식 / 상견례 / 대학(원)면접 / 모의면접 / 인턴면접 / 장례식 / 사진촬영 / 세미나 / 발표 / 공연(연주회) / 축제(행사) / OT / 아르바이트 / 졸업식 / 입학식 / 기타
    6.  이야기옷장에 등록된 기증편지 수/ 대여편지 수
    7.  품목별 기증의류 수량 / 사용 수량 / 재기증 수량 / 폐기 수량
    8.  창사 이후 역대 최다회 기증자/ 대여자
-   참고
    -   <https://github.com/opencloset/opencloset/issues/1642>


<a id="orgd6b4b29"></a>

# DONE 기증건 수

-   State "DONE" from <span class="timestamp-wrapper"><span class="timestamp">[2020-12-20 Sun 18:35]</span></span>

```sql
SELECT COUNT(*) AS '총 기증 건수' FROM donation WHERE create_date BETWEEN '2020-01-01' AND '2020-12-18';
```

855건


<a id="org2c1fae4"></a>

# DONE 재능나눔에 동의한 기증자 수

-   State "DONE" from <span class="timestamp-wrapper"><span class="timestamp">[2020-12-20 Sun 18:41]</span></span>

```sql
select d.create_date, a.name, a.talent_donation from donation_form as a inner join donation d on a.donation_id = d.id where d.create_date  BETWEEN '2020-01-01' AND '2020-12-18';
```


<a id="org0e35d8a"></a>

# DONE 기증자이면서 동시에 대여자인 이용자 명단

-   State "DONE" from <span class="timestamp-wrapper"><span class="timestamp">[2020-12-20 Sun 18:46]</span></span>

```sql

select b.create_date,a.rental_date, a.id, c.name from `order` as a left join donation as b on a.user_id = b.user_id inner join `user` as c on b.user_id = c.id where b.create_date BETWEEN '2020-01-01' AND '2020-12-18';

```


<a id="orgbcbc0c0"></a>

# DONE 2020년에 가장 많이 대여된 옷 : 남자 3건 / 여자 3건

-   State "DONE" from <span class="timestamp-wrapper"><span class="timestamp">[2020-12-20 Sun 18:58]</span></span>


<a id="org5548a62"></a>

# DONE 목적별 대여건 수 : 입사면접(대면면접) / 입사면접 (화상면접) / 결혼식 / 상견례 / 대학(원)면접 / 모의면접 / 인턴면접 / 장례식 / 사진촬영 / 세미나 / 발표 / 공연(연주회) / 축제(행사) / OT / 아르바이트 / 졸업식 / 입학식 / 기타

-   State "DONE" from <span class="timestamp-wrapper"><span class="timestamp">[2020-12-20 Sun 19:00]</span></span>
    
    ```sql
    select `purpose`, count(*) as cnt from `order` where rental_date between '2020-01-01' and '2020-12-31' group by purpose order by cnt desc
    ```


<a id="orgcf4e3ae"></a>

# DONE 이야기옷장에 등록된 기증편지 수/ 대여편지 수

-   State "DONE" from <span class="timestamp-wrapper"><span class="timestamp">[2020-12-20 Sun 21:39]</span></span>

```sql
select count(*) from donation where create_date between '2020-01-01' and '2020-12-31' and message is not null and message != ''
```

```sql
select count(*) cnt from `order` where rental_date between '2020-01-01' and '2020-12-31' and message is not null and message != ''
```

-   기증편지 : 332
-   대여편지 : 797


<a id="org1ee94d3"></a>

# 품목별 기증의류 수량 / 사용 수량 / 재기증 수량 / 폐기 수량


<a id="orgd0d2193"></a>

## 품목별 기증의류수

```sql
SELECT c.category AS '카테고리', COUNT(c.category) AS '의류 수'
FROM clothes c
JOIN donation d ON c.donation_id = d.id
WHERE d.create_date BETWEEN '2020-01-01' AND '2020-12-31'
GROUP BY c.category;
```


<a id="org6071997"></a>

## 품목별 재기증 수량

```sql
SELECT c.category AS '카테고리', COUNT(c.category) AS '의류 수'
FROM clothes c
JOIN donation d ON c.donation_id = d.id
WHERE d.create_date BETWEEN '2020-01-01' AND '2020-12-31'
AND c.status_id IN (45, 46, 57)
GROUP BY c.category;
```


<a id="orgbdce1fe"></a>

## 품목별 폐기 의류수

```sql
SELECT c.category AS '카테고리', COUNT(c.category) AS '의류 수'
FROM clothes c
JOIN donation d ON c.donation_id = d.id
WHERE d.create_date BETWEEN '2020-01-01' AND '2020-12-31'
AND c.status_id IN (8, 47)
GROUP BY c.category;
```


<a id="org504a198"></a>

# 창사 이후 역대 최다회 기증자/ 대여자


<a id="org9ff0c00"></a>

## 역대 기증자 Top 10

```sql
select b.name, b.id, count(*) as cnt from donation as a left join `user` as b on a.user_id = b.id group by a.user_id order by cnt desc limit 10
```

<a id="org4ba0026"></a>

## 역대 대여자 Top 10

```sql
select b.name, b.id, count(*) as cnt from `order` as a left join `user` as b on a.user_id = b.id group by a.user_id order by cnt desc limit 10
```

**Comment by yongbin** [comment]
각 쿼리에 대한 결과는 메일로 정리해서 보내들렸습니다.

**Comment by pingpongworks** [comment]
추가 데이터 요청드립니다. 

1. 2020년 전체 이용자의 연령대 
- 10대/20대/30대/40대/50대/60대/70대
- 전체 방문자의 평균연령 

2. 2020년 전체 이용자의 재이용횟수

3. 2020년 이용자 예약시 `웨딩촬영` `웨딩사진촬영`으로 메모를 기입한 사람의 주문서

**Comment by pingpongworks** [comment]
- 2020년 전체이용자의 재이용횟수도 부탁드립니다.

**Comment by yongbin** [comment]
```sql

-- 1
select a.id, c.birth, floor((2020 - c.birth) / 10) * 10 as age_group from `order` as a inner join user u on a.user_id = u.id inner join user_info as c on u.id = c.user_id
where a.rental_date between '2020-01-01' and '2020-12-31' and floor((2020 - c.birth) / 10) * 10 >= 0


-- 2
select avg(2020 - c.birth) from `order` as a inner join user u on a.user_id = u.id inner join user_info as c on u.id = c.user_id
where a.rental_date between '2020-01-01' and '2020-12-31' and floor((2020 - c.birth) / 10) * 10 >= 0

-- 3
select a.user_id, count(*) as cnt from `order` as a inner join user u on a.user_id = u.id inner join user_info as c on u.id = c.user_id
where a.rental_date between '2020-01-01' and '2020-12-31' group by a.user_id

-- 4

select a.id, a.purpose  from `order` as a inner join user u on a.user_id = u.id inner join user_info as c on u.id = c.user_id
where a.rental_date between '2020-01-01' and '2020-12-31' and a.purpose like '%웨딩%'

```

**Comment by yongbin** [comment]
메일로 회신드렸습니다.
