### ISSUE TITLE
8일 이상 장기대여 내역 

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1765]
3박4일 기본대여 외의 장기대여 가격정책을 만들어보고자 합니다. 
열린옷장 운영 이후 8일 이상 대여한 주문의 횟수를 알고자 합니다. 

- 기간 : 2014년 프로그램 도입 이후부터 최근까지
- 대상 : 8일 이상의 대여기간으로 대여한 주문서
- 목록 : 8일 대여 / 9일 대여 / 10일 대여 / 11일 대여 / 12일 대여.... 대여기간 별 대여횟수

**Comment by yongbin** [comment]
```sql
select datediff(return_date, rental_date) as duration, count(*) as cnt from `order` group by duration having duration >= 8
```

결과 메일로 송부드렸습니다.
