### ISSUE TITLE
웨딩 대여 활성화를 위한 예약시스템 수정

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1768]
예약시 웨딩 목적 임을 미리 알고 대응하고자 예약시 대여목적 부분의 수정을 요청드립니다. 

**1) 대여목적 목록 기존보다 간단하게 수정**

    - 입사면접
    - 결혼식
    - 대학(원) 면접
    - 모의면접
    - 장례식
    - 졸업/입학식
    - 세미나/발표
    - 공연/축제
    - 사진촬영
    - 기타

**2) `결혼식` 선택시 하위메뉴 생성** 

    - 하객
    - 혼주
    - 웨딩촬영
    - 본식       

![스크린샷 2021-02-10 오후 7 41 19](https://user-images.githubusercontent.com/17288038/107502929-ab8c2e00-6bdc-11eb-86d4-166ea40f427c.png)
* 입사면접 선택시_대면면접 / 화상면접이 하위메뉴로 나타나는 것과 같은 방식입니다. #1684 참고

**3) `결혼식-웨딩촬영` `결혼식-본식` 선택시 시간표에 노출**
![스크린샷 2021-02-10 오후 7 44 12](https://user-images.githubusercontent.com/17288038/107503800-b98e7e80-6bdd-11eb-95b4-31c52574ecb2.png)
* 쿠폰예약시 시간표에 노출되는 것과 같은 방식입니다.

**4) `결혼식-웨딩촬영` `결혼식-본식` 선택시 치수측정할 때 스태프가 인지할 수 있도록 사용자정보 하단에 노출**
![스크린샷 2021-02-10 오후 7 45 07](https://user-images.githubusercontent.com/17288038/107503904-de82f180-6bdd-11eb-81dd-ff6870de1eea.png)
* 화상면접 선택시 노출되는 것과 같은 방식입니다.

**5) `결혼식-웨딩촬영` `결혼식-본식` 선택시 의류준비시 preparation에 노출**
![스크린샷 2021-02-10 오후 8 31 04](https://user-images.githubusercontent.com/17288038/107504946-5b629b00-6bdf-11eb-8918-344600d8654c.png)

**6) `결혼식-웨딩촬영` `결혼식-본식` 선택시 예약가능한 시간이 매일 10:00 / 2:00 만 노출**
웨딩촬영, 본식 대여자의 경우 다른 대여자처럼 30분 단위로 업무 처리가 불가능하여 오전 10시 1인 / 오후 2시 1인 만 에약을 받고자 합니다.

**Comment by aanoaa** [comment]
연관된 곳이 여러군데이긴 하지만 복잡한 기능은 아닙니다.
작업을 시작하고 연속해서 작업한다면 더 빨리 끝날 수도 있겠지만,
구현하고 적용하는데 2주 정도 예상합니다.

> 1.  결혼식-웨딩촬영 결혼식-본식 선택시 예약가능한 시간이 매일 10:00 / 2:00 만 노출

이게 기존이랑 많이 다른 부분입니다.
예약 시간표를 두개로 운영하고 10 ~ 14 에는 두개의 시간표를 merge 해서 나타내야 할지 어떨지 고민이 필요합니다.

**Comment by pingpongworks** [comment]
> 구현하고 적용하는데 2주 정도 예상합니다.

2월 28일 (일)까지로 일정 생각하고 웨딩 소개 페이지 제작 등 나머지 작업을 진행하겠습니다. 

> 예약 시간표를 두개로 운영하고 10 ~ 14 에는 두개의 시간표를 merge 해서 나타내야 할지 어떨지 고민이 필요합니다.

좀더 자세히 설명해주시면 제가 고민해야할 부분, 생각해보겠습니다.

**Comment by aanoaa** [comment]
지금까지의 예약정보는

-   datetime
-   성별
-   가능인원

으로 이루어져 있습니다.
성별과 시간대로 예약 가능한 시간표를 제공합니다.

지금 이슈는,
대여목적에 따른 예약시간표를 제공해야 합니다.

---

1.  결혼식만을 예외케이스로 둔다면,
    결혼식의 예약정보를 따로 관리하면서, 예약테이블의 결과값을 보정하는 방식.
2.  모든 예약에 대해서, 예약정보에 대여목적을 기록.

하는 방식이 있을 수 있겠습니다.

2번째 방법이 더 일반적인 목적으로 사용할 수 있을 것 같습니다.

booking 테이블에서 대여목적을 가질 수 있도록 변경되어야 합니다.
또한 이를 저장하고, 호출하는 API 등의 인터페이스도 변경되어야 합니다.

**Comment by aanoaa** [comment]
잘못 생각했습니다.
예약테이블 정보는 운영자가 관리합니다.
예약이 체결되었을때에 변경되는 정보가 아닙니다.

예약 테이블의 시간 및 성별에 맵핑된 주문서 건수를 조회해서,
동적으로 예약 가능 시간표를 만듭니다.

지금 날짜별로 템플릿을 사용해서 예약 인원을 제한하듯이,
대여목적에 따라 사용될 예약정보를 따로 기록해야 합니다.

예약이 체결되었을때에 주문서에는 대여목적이 기록되지 않습니다.
대여목적이 기록되는 순간은 대여가 되었을때 입니다.

---

정리하면,

지금의 예약 테이블과 같은 기능을 하되, 특수한 경우(대여목적이 결혼식인 경우) 대여목적마다 예약인원을 제한해야 합니다.

1.  booking 테이블과 같은 목적인 booking\_purpose 테이블을 만들고 운영자가 이를 날짜및시간/성별/대여목적 별로 예약을 허용할 slot 의 갯수를 확정합니다.
2.  예약 테이블 API 에서 대여목적이 입력된 경우, 해당 대여목적에 해당하는 예약시간표를 return 합니다.
    이때 고려해야 하는 것이 주문서에는 대여목적이 기록되어 있지 않고, 사용자 정보에 기록되어 있습니다.
3.  1 에서 필요한 운영상의 기능을 만들어야 합니다.

이슈를 살펴보니까, 작업 볼륨이 생각보다 큽니다.
3의 경우 배보다 배꼽이 큽니다.

**Comment by aanoaa** [comment]
대여목적용 예약 테이블에 날짜및시간을 고려하지 않는다면,
운영상의 기능은 필요 없을 수 있습니다.

일괄로 퉁쳐서 결혼식의 경우 10:00 에 한건, 14:00 한건씩 고정값을 사용한다는 가정입니다.

예약 테이블 API 에서 대여목적이 입력된 경우,
사용자 정보의 대여목적에서 10:00 와 14:00 에 예약건수가 존재하는지 여부를 체크해서 예약테이블을 생성해주면 되겠습니다.
이렇게 처리할 경우 입력된 데이터로 처리하는 것이 아니고, application 에 예외케이스가 늘어나는 거라서 복잡도가 증가합니다.

**Comment by aanoaa** [comment]
방문일자를 선택한 이후에, 대여목적을 선택하게 되는데 대여목적이 결혼식이면서 웨딩촬영/본식인 경우에는 방문일자에 제약이 생겨버립니다.
선택한 사용자에게 다시 선택하도록 유도해야 합니다.

**Comment by pingpongworks** [comment]
>6) 결혼식-웨딩촬영 결혼식-본식 선택시 예약가능한 시간이 매일 10:00 / 2:00 만 노출
웨딩촬영, 본식 대여자의 경우 다른 대여자처럼 30분 단위로 업무 처리가 불가능하여 오전 10시 1인 / 오후 2시 1인 만 에약을 받고자 합니다.

방문일자 선택이 먼저라는 걸 생각하지 못했습니다. 죄송합니다.  6번 부분 제외하고 작업 부탁드립니다. 예약시간을 제한하는 방법을 예약추이보면서 다시 한번 고민해서 요청드리겠습니다. 웨딩 안내 홈페이지에서 따로 구글폼으로 예약을 받고 직원예약으로 진행하거나, 예약시 방문일자 선택 순서를 바꾸거나 다른 방법을 생각해봐야할 거 같습니다.

**Comment by aanoaa** [comment]
6번을 제외하고 완료되었습니다.
배포하면 확인하실 수 있는데, 저녁에 @yongbin 님 작업이후에 가능합니다.
익일 영업시간 전에 배포하고 연락드리겠습니다. @pingpongworks

**Comment by pingpongworks** [comment]
네~

**Comment by aanoaa** [comment]
@pingpongworks 배포했습니다.
영업시간전에 반드시 테스트 해보시고 연락주세요.

**Comment by pingpongworks** [comment]
<img width="380" alt="스크린샷 2021-02-28 오전 9 44 02" src="https://user-images.githubusercontent.com/17288038/109404486-edbdb980-79a9-11eb-83fb-1cf602764707.png">

테스트했습니다. 결혼식 관련해서는 문제가 없는데, 결혼식 상세목적 선택이 입사면접이나 다른 목적을 선택해도 계속 뜹니다. 확인 부탁드립니다.

**Comment by pingpongworks** [comment]
브라우저 인터넷 기록 문제였던 거 같습니다. 해결되었습니다.

**Comment by pingpongworks** [comment]
시간표 상단에 당일 웨딩대여 예약자 수 표기를 추가로 요청드립니다. `웨딩촬영` `본식`으로 예약한 경우만 해당됩니다.
오늘부터 벌써 웨딩촬영, 본식 예약자가 생기기 시작해서 빠르게 예약상황을 인지하기 위해서 필요한 기능입니다. 

![웨딩대여 수 표기](https://user-images.githubusercontent.com/17288038/109894380-b82e0e80-7cd0-11eb-85fd-5db8a9b6f189.jpg)

**Comment by aanoaa** [comment]
추가하였습니다.

**Comment by pingpongworks** [comment]
![IMG_2542](https://user-images.githubusercontent.com/17288038/111053317-38f5c300-84a6-11eb-8134-e7117a5aa288.PNG)
웨딩촬영으로 예약을 했는데 시간표 상단 웨딩대여 예약자수에 반영이 되지 않습니다. 반영되는데 걸리는 시간이 따로 설정되어 있나요?

**Comment by aanoaa** [comment]
bestfit 을 바라보고 있었습니다.
human 에러 입니다.
수정해서 반영하였습니다.

**Comment by pingpongworks** [comment]
시간표 상단 웨딩대여자수에 결혼식-하객, 결혼식-혼주까지 포함되고 있습니다. 
결혼식-웨딩촬영, 결혼식-본식 만 카운트되도록 해주세요. 
하객, 혼주까지 포함되면 주말에는 너무 많아서 다 체크하기가 어려워집니다.

**Comment by pingpongworks** [comment]
>시간표 상단에 당일 웨딩대여 예약자 수 표기를 추가로 요청드립니다. 웨딩촬영 본식으로 예약한 경우만 해당됩니다.

요 내용 한번 더 확인해주세요~

**Comment by pingpongworks** [comment]
결혼식 에약자 중 하객, 혼주는 웨딩대여 카운팅에 포함되지 않도록 부탁드립니다.

**Comment by aanoaa** [comment]
늦어서 죄송합니다.
적용하였습니다.

**Comment by pingpongworks** [comment]
확인했습니다. 감사합니다.
