### ISSUE TITLE
최신 ace 테마 적용

### ISSUE THREAD

**Issue by keedi** [opencloset/opencloset#177]
현재 1년전 테마를 기준으로 사이트를 작성했습니다.

부트스트랩이 3.0이며 폰트오썸도 구 버전입니다. 관련해서 라이브러리 이슈( #166 )도 있기 때문에 테마 및 관련 라이브러리를 갱신해야 합니다. 다행히 며칠 전 ace 테마가 가장 최신 라이브러리를 기반으로 갱신이 되었습니다. bower / grunt 까지 모두 적용되도록 적용해야 합니다. 역시 다행히 테마가 gruntfile과 bower 관련 설정도 이미 지원하고 있습니다.

본 이슈는 이번 마일스톤과 별개로 진행해야 합니다. 관련해서 사이드 이펙트가 크기 때문에 여유를 두고 작업해야 합니다.

**Comment by aanoaa** [comment]
테마를 구입해야 하나요?
관련된 가이드의 주소를 좀 적어주세요.

**Comment by keedi** [comment]
일단 우선순위가 가장 낮다고 보여집니다. 당장 처리하지 않을 예정이라 "지금안함" 라벨을 붙여두겠습니다.

**Comment by keedi** [comment]
의미가 없다고 생각합니다. 진행하지 않습니다. 이슈 닫습니다.
