### ISSUE TITLE
"미리 오지 마세요" 팝업문구 수정

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1775]
![image](https://user-images.githubusercontent.com/17288038/111055563-52086f00-84ba-11eb-8788-b73b33af0579.png)

예약시 방문대여일과 착용일이 4일 이상 차이나는 경우, "미리 오지 마세요" 안내가 뜨고 있습니다. 현재는 보관료, 장기대여료 등의 정책을 통해 미리 방문하는 경우를 강하게 제한하고 있지 않아 아래 문구로 수정을 요청드립니다. 

    실제 대여일보다 4일 이상 미리 방문하는 경우 기간 연장료나 의류 보관료가 발생할 수 있습니다. 고려하여 방문일을 예약해주세요.

**Comment by keedi** [comment]
수정한 문구는 다음과 같습니다.

![screenshot-visit theopencloset net-2021 03 15-01_34_05](https://user-images.githubusercontent.com/138451/111076216-c7158c00-852e-11eb-9d30-05f5ff3fc44c.png)

**Comment by pingpongworks** [comment]
문구 전체를 교체하려는 의도였는데 전달이 잘못 된 거 같습니다. 지금은 "미리 오지 마세요"라고 제한 할 상황이 아니라서요. 

>방문예약일과 의류착용일이 4일 이상 (12일) 차이가 납니다. 실제 대여일보다 4일 이상 미리 방문하는 경우 기간 연장료나 의류 보관료가 발생할 수 있습니다. 고려하여 방문일을 예약해주세요.

위 문구만 남기고  다 지우는 수정이 가능할까요?

**Comment by pingpongworks** [comment]
![111076216-c7158c00-852e-11eb-9d30-05f5ff3fc44c](https://user-images.githubusercontent.com/17288038/111088426-73289880-856a-11eb-884e-a48234c47136.png)

다시 한번 수정 요청 드립니다.

**Comment by keedi** [comment]
방문 예약 시간 선택 쪽에 팝업이 하나가 더 있는데 이 쪽은 따로 수정이 필요 없는지요?

![screenshot-staff theopencloset net i5 bebop-2021 03 15-12_44_44](https://user-images.githubusercontent.com/138451/111101024-62891a00-858c-11eb-8b2e-00b215c02b35.png)

**Comment by pingpongworks** [comment]
<img width="601" alt="스크린샷 2021-03-15 오후 12 55 35" src="https://user-images.githubusercontent.com/17288038/111101828-0a531780-858e-11eb-9daa-337b3aa75984.png">

이 팝업에서는 "미리 오지 마세요" 만 삭제해주세요. 확인해주셔서 감사합니다.

**Comment by keedi** [comment]
수정 사항 반영 화면입니다.

![screenshot-visit theopencloset net-2021 03 15-14_08_40](https://user-images.githubusercontent.com/138451/111106246-147a1380-8598-11eb-8c32-744ddab46af7.png)

![screenshot-visit theopencloset net-2021 03 15-14_09_06](https://user-images.githubusercontent.com/138451/111106253-17750400-8598-11eb-989a-d14ad30ee4d6.png)

**Comment by pingpongworks** [comment]
확인했습니다. 감사합니다.
