### ISSUE TITLE
테스트용 쿠폰번호 요청

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1781]
**테스트용 쿠폰 1)** 
- 아이디 : test202101
- 이름 : 테스트2021
- 발급 : 30
- 유형 : B타입
- 택배비 여부: 온라인배송비 이용자 부담 / 온오프라인 반납택배비 모두 본인 부담
- 사용기간 : 2021-03-24~2022-12-31
- 사용시간만 길 뿐 기존 지자체 무료대여 쿠폰과 같습니다.

**테스트용 쿠폰 2)**
- 아이디 : test202102
- 이름 : 테스트2021
- 발급 : 30
- 유형 : B타입
- 택배비 여부: 온라인배송비 이용자 부담 / 온오프라인 반납택배비 모두 본인 부담
- 사용기간 : 2021-03-24~2022-12-31
- 기존 지자체 쿠폰과 달리 쿠폰 하나당 2만원 한도로 정장 한세트 (남자는 넥타이 포함) 만 무료로 대여할 수 쿠폰입니다. 

테스트용 쿠폰 1은 가능하면 빠르게 부탁드리고,
테스트용 쿠폰 2는 의문사항 있으시면 내일 미팅에서 논의후 주셔도 됩니다.

**Comment by aanoaa** [comment]
> 기존 지자체 쿠폰과 달리 쿠폰 하나당 2만원 한도로 정장 한세트 (남자는 넥타이 포함) 만 무료로 대여할 수 쿠폰입니다.

3종류의 쿠폰이 있습니다.

-   suit: 금액과 상관없이 suit 한벌을 대여할 수 있음
-   price: 결제금액에서 지정된 금액만큼 차감됨
-   rate: 결제금액에서 지정된 비율만큼 금액이 차감됨

정장 한셋트를 대여할 수 있는데 2만원 한도는 무언지 모르겠습니다.
새로운 쿠폰 종류가 생겨야 하는 건가요?

**Comment by aanoaa** [comment]
```sh
#!/bin/sh
perl bin/event.pl \
    --name='test202101' \
    --title='테스트2021' \
    --type='reserve|rental' \
    --sponsor='opencloset' \
    --year=2021 \
    --nth=1 \
    --start_date='2021-03-24' \
    --end_date='2022-12-31' \
    --coupon-type='suit' \
    --coupon-count=30 \
    --coupon-out='test202101.txt'
```

**Comment by aanoaa** [comment]
첫번째 쿠폰만 메일로 보내드렸습니다.

**Comment by pingpongworks** [comment]
>price: 결제금액에서 지정된 금액만큼 차감됨

정장 한세트가 여성의 경우에는 자켓+원피스가 될 수도 있고, 이용자가 원하는 경우에는 자켓+자켓이 될 수도 있습니다. 선물로 한벌 이용권을 받았는데 본인 비용을 추가해서 셔츠, 타이까지 대여하려는 이용자도 있을 수가 있고요. 결제금액에서 지정된 금액 2만원만큼 차감되는 price 형태가 되면 맞을 거 같습니다. 

그런데, price 형태가 되었을 때 타이 결제는 어떻게 될까요?  
자켓+팬츠+타이를 2만원 이용권으로 계산하면 타이는 0원으로 나올까요? 자켓+자켓+타이를 대여하면 타이 2,000원은 결제비용으로 나올까요?

**Comment by aanoaa** [comment]
대여 품목의 종류와 상관없이 대여비 중에 금액만큼만 차감됩니다.
10,000 원짜리 쿠폰은 만원처럼 사용할 수 있는 겁니다.
보통 수트 한벌을 대여하면 2만원이 넘어가기 때문에 수트 한벌을 대여하기 위해서는 추가금을 내어야 합니다.

**Comment by pingpongworks** [comment]
테스트용 쿠폰 이미 확인한 내용이라 이슈 닫습니다.
