### ISSUE TITLE
방문예약 페이지 하단 배너를 쿠폰 입력 링크로 교체

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1785]
https://visit.theopencloset.net/visit 
방문예약 페이지 하단의 "경기지역 무료대여 안내" 내용 교체를 요청합니다. 
현재는 충청, 강원까지 지역이 포함되어 있어 문구가 맞지않는 면도 있고,
쿠폰번호 입력 페이지로 바로 넘어가는게 쿠폰 대여자에게는 더 편리할 듯 하여 
문구수정과 함께 쿠폰번호 입력 페이지로 바로 연결되도록 수정 부탁드립니다. 

![방문예약-페이지-수정](https://user-images.githubusercontent.com/17288038/113480398-fe90ac00-94ce-11eb-9858-07a90e356e7b.jpg)

연결페이지 => https://visit.theopencloset.net/coupon

**Comment by keedi** [comment]
확인했습니다~

**Comment by keedi** [comment]
브라우저 캐시 때문에 제대로 보이지 않을 수 있습니다. 적용 내역을 확인하려면 브라우저에서 강제 새로 고침이 필요할 수 있습니다.

**Comment by pingpongworks** [comment]
확인했습니다. 빠르게 수정해주셔서 감사드립니다.
