### ISSUE TITLE
추동복일 경우 출력용 의류 태그를 녹색으로 표현

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1787]
_
현재 계절별 의류의 구분은 3종입니다. 

- 하복
- 동복
- 춘추복

<img width="1057" alt="스크린샷 2021-04-06 오후 1 32 41" src="https://user-images.githubusercontent.com/17288038/113659256-96171a00-96dc-11eb-8535-928e3270c02d.png">
<img width="1227" alt="스크린샷 2021-04-06 오후 1 32 27" src="https://user-images.githubusercontent.com/17288038/113659263-9c0cfb00-96dc-11eb-92eb-d8735d883b24.png">

_
춘추복 중 두터운 재질의 의류를 구분하여 서비스할 필요가 있다고 판단되어
`추동복`으로 구분하여 등록하고자 합니다. 

의류 등록시 스태프가 `#추동복` 태그를 거는 경우 출력할 때 
상단의 색상이 다른 색으로 표시되도록 요청드립니다. 

컬러는 하복,동복과 구분되도록 `#4BAF4B`로 부탁드립니다. 

_
https://github.com/opencloset/opencloset/issues/852 참조

**Comment by keedi** [comment]
현재 온라인 의류의 경우 `#279773` 색상을 사용합니다. **추동복**을 위한 `#4BAF4B` 색상과 비슷해 헷갈릴 수 있습니다. 관련해 @pingpongworks 님께 확인했는데, 2014년 이후 온라인 의류 태그는 사용하지 않는다고 합니다. 따라서 육안상 색상은 겹치지만 헷갈릴 이유는 없어보입니다. 요청대로 진행합니다.

**Comment by keedi** [comment]
작업 및 배포 완료했습니다.

@pingpongworks :
테스트 시 브라우저 캐시 때문에 제대로 동작하지 않을 수 있으므로 몇 번 새로고침을 수행할 필요가 있습니다.

**Comment by pingpongworks** [comment]
확인했습니다. 감사합니다.
