### ISSUE TITLE
[쿠폰 발행] 열린옷장 정장대여쿠폰 번호 발행 

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1794]
열린옷장 정장대여쿠폰 2종 쿠폰번호 발행 요청드립니다.

1. 
- 아이디 : opencloset30000-202105
- 이름 : 열린옷장 3만원 쿠폰
- 발급 : 100
- 유형 : price 타입
- 택배비 : 본인 부담
- 유효기간 : 2021년 5월 1일 ~ 2022년 5월 31일 

2. 
- 아이디 : opencloset20000-202105
- 이름 : 열린옷장 2만원 쿠폰
- 발급 : 100
- 유형 : price 타입
- 택배비 : 본인 부담
- 유효기간 : 2021년 5월 1일 ~ 2022년 5월 31일

----

- 매달 30일에 다음 달 판매할 쿠폰 2종 (3만원권 / 2만원권) 발행
- 쿠폰의 유효기간은 2021년 00월 1일 ~ 2022년 00월 31일로 365일 이상의 유효기간을 가지도록 한다.
- 매달 판매 후 남은 쿠폰은 폐기한다
- 쿠폰금액의 60% 이상을 사용하는 경우 잔액 환불이 가능한 쿠폰이므로 사용하지 않은 잔액 계산이 쉬운 price 타입 이었으면 함. 

5월 3일 부터 신규 사이트에서 판매예정이므로 5월 2일까지 쿠폰발행 요청드립니다.

**Comment by keedi** [comment]
쿠폰 생성 코드는 다음과 같습니다.

```bash
#!/bin/bash

perl bin/event.pl \
    --name='opencloset30000-202105' \
    --title='열린옷장 3만원 쿠폰' \
    --type='reserve|reserve' \
    --desc='열린옷장 2021-05 3만원 쿠폰 / 캠페인어스' \
    --sponsor='열린옷장' \
    --year=2021 \
    --nth=1 \
    --start_date='2021-05-01' \
    --end_date='2022-05-31' \
    --coupon-type='price' \
    --coupon-price=30000 \
    --coupon-count=100 \
    --coupon-out='opencloset30000-202105.txt'

perl bin/event.pl \
    --name='opencloset20000-202105' \
    --title='열린옷장 2만원 쿠폰' \
    --type='reserve|reserve' \
    --desc='열린옷장 2021-05 2만원 쿠폰 / 캠페인어스' \
    --sponsor='열린옷장' \
    --year=2021 \
    --nth=1 \
    --start_date='2021-05-01' \
    --end_date='2022-05-31' \
    --coupon-type='price' \
    --coupon-price=20000 \
    --coupon-count=100 \
    --coupon-out='opencloset20000-202105.txt'
```

**Comment by keedi** [comment]
쿠폰 유형(event)은 `reserve|reserve` 입니다. 유형의 종류는 다음과 같습니다.

- `reserve|reserve `: 예약하는 날짜부터 이벤트 시작, 마감날짜 = 예약하는날짜
- `reserve|rental  `: 예약하는 날짜부터 이벤트 시작, 마감날짜 = 대여일
- `rental|reserve  `: 대여일부터 이벤트 시작, 마감날짜 = 예약하는날짜
- `rental|rental   `: 대여일부터 이벤트 시작, 마감날짜 = 대여일

보통 지자체 쿠폰은 `reserve|rental` 이지만 열린옷장 쿠폰의 경우 `reserve|reserve` 입니다. 이것은 유효기간 마감이 05-31 이라고 가정할 때 05-31에 06-12일로 방문 예약한 경우 이를 허용할 것인가와 관련한 이슈로, 이를 허용하려면 `...|reserve` 유형으로 결정해야합니다. `rental`로 결정할 경우 마감이 05-31 이라면 방문 예약도 05-31을 넘기지 말아야합니다.

**Comment by keedi** [comment]
쿠폰 생성 스크립트(`bin/event.pl`)에서 `price` 유형의 쿠폰 생성시 `--coupon-price` 명령줄 옵션으로 입력한 금액을 설정하지 않는 문제가 있었습니다. 명령줄 옵션값을 적용하도록 수정했습니다.

**Comment by keedi** [comment]
결과는 메일로 첨부드렸습니다.

**Comment by keedi** [comment]
쿠폰 관련 참고 링크는 다음과 같습니다.

- https://github.com/opencloset/opencloset/issues/1517#issuecomment-447367065 쿠폰 시스템의 개선
- #1408 쿠폰 별 발급 개수와 별개로 제한 개수를 설정함

**Comment by pingpongworks** [comment]
5월용으로 받은 쿠폰이 거의 사용되지 않아서 새로 발급보다는 유효기간을 바꿔주시면 좋겠습니다. 

2021년 6월 1일 ~ 6월 30일
