### ISSUE TITLE
착용여부 목록에서 "입고감+기록요망"을 "보관요망"으로 변경

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1796]
<img width="463" alt="스크린샷 2021-05-11 오후 12 06 03" src="https://user-images.githubusercontent.com/17288038/117752345-8fd30b00-b251-11eb-9748-dbf322a6a05d.png">

사용자 정보 페이지 중 `착용여부` 탭의 목록 중 
"입고감+기록요망"을 "보관 요망"으로 변경 요청 드립니다. 

미리 방문한 경우 7일간 무료보관, 이후에는 1일 2,000원의 보관료를 정식으로 부과하고 있어서 "보관요망" 인지가 필요합니다. 

- staff
- monitor
- OpenCloset-Common

세 군데에서 변경 부탁드립니다.

**Comment by keedi** [comment]
#1398 연관 이슈입니다. 이 때도 유사한 논의를 진행했으나, 최종 결론이 나지는 않았습니다. 단순 이름 변경 이슈인지 항목 추가인지 확인하고 진행합니다. 현 시점 기준으로는 정말 보관 기능이 생긴 것으로 알고 있습니다.

**Comment by pingpongworks** [comment]
1398 논의 당시에는 보관을 하지 않는게 업무 원칙이었어서 보류했었는데, 지금은 보관 관련 규정이 정식으로 운영되고 있는 상황입니다. 입고감+기록요망은 그 때나 지금이나 필요하지 않은 목록이고요.

현재는 "보관요망"의 주기능이 스태프들이 보관을 해야하는 이용자라는 것을 인지하고 놓치지 않기 위한 것이라서 문구 수정으로 충분하지 않나 합니다. 보관 관련해서도 선결제인 경우, 후결제인 경우 등이 다앙햐게 있을 수 있는데 그런 부분을 모두 수지니에 기능으로 넣기에는 너무 복잡합니다. 차후에 보관이 중요한 부분을 차지하게 되면 추가로 요청드리는게 좋을 거 같아요.  

입고감+기록요망은 전혀 필요하지 않은 항목이어서 새로운 항목을 추가하는 것보다는 변경하는게 좋을 거 같습니다.

**Comment by keedi** [comment]
큰 의미는 없지만, 현 시점, `wear_on`이 기존 "입고감+기록요망" 상태의 주문서 목록은 다음과 같습니다.

```sql
mysql> SELECT id, does_wear FROM `order` WHERE does_wear = 3;
+--------+-----------+
| id     | does_wear |
+--------+-----------+
|  98306 |         3 |
| 141586 |         3 |
| 188095 |         3 |
+--------+-----------+
3 rows in set (0.22 sec)
```

**Comment by keedi** [comment]
서버 배포까지 완료했으며 필요에 따라 브라우저 새로고침이 필요할 수 있습니다.

**Comment by pingpongworks** [comment]
정상작동 확인했습니다. 감사합니다.
