### ISSUE TITLE
예약페이지 문구 수정 

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1801]
![예약페이지-문구수정](https://user-images.githubusercontent.com/17288038/118430119-4c274800-b70e-11eb-86d1-2d1ecbf4931e.jpg)

10% 할인 쿠폰이 도입되면서 모든 쿠폰이 무료는 아니기 때문에 
예약 페이지의 **쿠폰번호로 무료대여하기**의 표현이 수정되어야 합니다. 
취업날개 안내 문구도 좀더 간략하게 함께 수정 요청드립니다.

**Comment by keedi** [comment]
![screenshot-visit theopencloset net-2021 05 22-10_52_42](https://user-images.githubusercontent.com/138451/119211263-0bec0f00-baec-11eb-8336-8f86ce6812d4.png)

**Comment by keedi** [comment]
서버 배포 완료했습니다.

**Comment by pingpongworks** [comment]
확인 했습니다. 감사합니다~
