### ISSUE TITLE
사용된 쿠폰으로 뜨는 오류

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1809]
방문예약이나 택배대여 신청을 쿠폰으로 했으나 대여 완료를 하지는 않은 쿠폰이 

`이미 사용된 쿠폰`으로 상태가 변경되어 다시 사용하려고 하면 중복된 쿠폰으로 뜹니다. 

취업날개용 쿠폰은 그런 일이 없는데 

다른 지자체 쿠폰만 열린옷장 예약시스템에서 오류 상황이 생깁니다. 

최근 잦아져서 지자체 담당자가 쿠폰을 사용하지 않았는데 사용한 것으로 오류나는 상황에 대해

문제제기를 하고 있어 원인파악과 대책이 필요합니다. 

확인 부탁드립니다.

**Comment by keedi** [comment]
@aanoaa 

기록된 이슈만으로 보면 사용하지 않은 쿠폰이 사용된 것으로 보여지는 것처럼 보이는데, 실제로는 쿠폰을 이용해 최초 온오프라인 예약을 진행하고, 실제로 대여하지 않은뒤 해당 쿠폰 번호로 다시 온오프라인 예약을 진행하려고 할 때 발생하는 이슈로 보입니다. 오프라인 기준으로는 노쇼 또는 예약 취소인 경우에 발생하는 것 같고 온라인은 동작방식이 좀 다를거 같네요.

관련해서 어떻게 처리하면 좋을지 이야기 나눠보시지요.

**Comment by keedi** [comment]
오프라인에서는 다음 두 경우에 대해 이미 기입한 쿠폰을 되살릴 수 있도록 하기로 했습니다.

- 사용자가 예약 취소를 함
- 스태프가 노쇼 주문서를 **방문안함** 상태로 바꿈
- 스태프가 방문은 했지만 입어만 보고 택배로 신청하겠다는 주문서를 **대여안함** 상태로 바꿈

**Comment by pingpongworks** [comment]
리툴로 대처하고 있어 이슈 닫습니다.
