### ISSUE TITLE
대여회전율 페이지 정상작동 복구 요청

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1815]
https://staff.theopencloset.net/stat/clothes/rent/jacket?gender=male&limit=10&sort=asc&status_ids%5B%5D=1&status_ids%5B%5D=2&status_ids%5B%5D=3&status_ids%5B%5D=4&status_ids%5B%5D=5&status_ids%5B%5D=6&status_ids%5B%5D=9&status_ids%5B%5D=10&status_ids%5B%5D=11&status_ids%5B%5D=16&status_ids%5B%5D=17&status_ids%5B%5D=18&status_ids%5B%5D=19

의류보관 공간이 부족해서 기증된지 오래되었지만 대여되지 않고 있는 의류들을 분류해서 정리하려고 합니다. 
대여회전율 페이지가 정상작동하면 따로 데이터 요청 없이 분류가 가능할 거 같습니다. 
현재 페이지 상태가 남성=>여성, 자켓=>팬츠 등으로 조건값을 바꾸어도 검색이 되지 않습니다. 복구요청 드립니다.

**Comment by aanoaa** [comment]
`templates/statistic/clothes_rent_category.html.ep` 파일에서, button id 가 `btn-hit-search` 로 되어있는데,
js 에서는 `btn-rent-search` 를 셀렉터로 사용해서 동작하지 않았습니다.

```diff
-        <button id="btn-hit-search" class="btn btn-info pull-right" type="button">
+        <button id="btn-rent-search" class="btn btn-info pull-right" type="button">
```

히스토리를 살펴봤는데, `haml` 템플릿으로 작성된 파일을 `ep` 템플릿으로 바꾸는 과정에서 변경되었습니다.
이제 발견되었다는 것은 꽤 오랜기간동안 사용되지 않은 기능입니다.

서버에는 임시로 패치 했습니다만, 저장소에 올바르게 반영되도록 고쳐놓겠습니다.

**Comment by pingpongworks** [comment]
확인했습니다. 감사합니다.
