### ISSUE TITLE
[쿠폰 통계] 2021-07-01 ~ 2021-09-30의 안산시/안양시/하남시 쿠폰 사용내역

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1824]
- 기간 : 2021년 7월 1일부터 2021년 9월 30일까지
- 대상쿠폰 : ansan202101 / anyang202101 / hanam202101

방문대여와 택배대여가 구분되도록
10월 1일 (금까지 부탁드립니다

**Comment by aanoaa** [comment]
```sql
SELECT
      e.name                                 AS event_name
    , o.id                                   AS order_id
    , u.id                                   AS user_id
    , DATE_FORMAT(b.date, "%Y-%m-%d")        AS booking_ymd
    , DATE_FORMAT(o.rental_date, "%Y-%m-%d") AS rental_ymd
    , u.name                                 AS user_name
    , ui.birth                               AS user_birth
    , c.id                                   AS coupon_id
    , c.code                                 AS coupon_code
    , c.status                               AS coupon_status
    , IF(o.online = 1, 'online', 'offline')  AS onoff
FROM `order`          AS o
LEFT JOIN `coupon`    AS c  ON o.coupon_id  = c.id
LEFT JOIN `event`     AS e  ON c.event_id   = e.id
LEFT JOIN `user`      AS u  ON o.user_id    = u.id
LEFT JOIN `user_info` AS ui ON ui.user_id   = u.id
LEFT JOIN `booking`   AS b  ON o.booking_id = b.id
WHERE
    (
            e.name       = "ansan202101"
        AND c.`status` = "used"
        AND o.parent_id IS NULL
        AND
            (
                   ( o.online <> 1 AND ( b.date        BETWEEN '2021-07-01' AND '2021-10-01' ) )
                OR ( o.online <> 0 AND ( o.rental_date BETWEEN '2021-07-01' AND '2021-10-01' ) )
                OR ( o.online <> 0 AND o.rental_date IS NULL )
            )
    )
ORDER BY onoff, rental_ymd, booking_ymd;
```

**Comment by aanoaa** [comment]
```sql
SELECT
      e.name                                 AS event_name
    , o.id                                   AS order_id
    , u.id                                   AS user_id
    , DATE_FORMAT(b.date, "%Y-%m-%d")        AS booking_ymd
    , DATE_FORMAT(o.rental_date, "%Y-%m-%d") AS rental_ymd
    , u.name                                 AS user_name
    , ui.birth                               AS user_birth
    , c.id                                   AS coupon_id
    , c.code                                 AS coupon_code
    , c.status                               AS coupon_status
    , IF(o.online = 1, 'online', 'offline')  AS onoff
FROM `order`          AS o
LEFT JOIN `coupon`    AS c  ON o.coupon_id  = c.id
LEFT JOIN `event`     AS e  ON c.event_id   = e.id
LEFT JOIN `user`      AS u  ON o.user_id    = u.id
LEFT JOIN `user_info` AS ui ON ui.user_id   = u.id
LEFT JOIN `booking`   AS b  ON o.booking_id = b.id
WHERE
    (
            e.name       = "anyang202101"
        AND c.`status` = "used"
        AND o.parent_id IS NULL
        AND
            (
                   ( o.online <> 1 AND ( b.date        BETWEEN '2021-07-01' AND '2021-10-01' ) )
                OR ( o.online <> 0 AND ( o.rental_date BETWEEN '2021-07-01' AND '2021-10-01' ) )
                OR ( o.online <> 0 AND o.rental_date IS NULL )
            )
    )
ORDER BY onoff, rental_ymd, booking_ymd;
```

**Comment by aanoaa** [comment]
```sql
SELECT
      e.name                                 AS event_name
    , o.id                                   AS order_id
    , u.id                                   AS user_id
    , DATE_FORMAT(b.date, "%Y-%m-%d")        AS booking_ymd
    , DATE_FORMAT(o.rental_date, "%Y-%m-%d") AS rental_ymd
    , u.name                                 AS user_name
    , ui.birth                               AS user_birth
    , c.id                                   AS coupon_id
    , c.code                                 AS coupon_code
    , c.status                               AS coupon_status
    , IF(o.online = 1, 'online', 'offline')  AS onoff
FROM `order`          AS o
LEFT JOIN `coupon`    AS c  ON o.coupon_id  = c.id
LEFT JOIN `event`     AS e  ON c.event_id   = e.id
LEFT JOIN `user`      AS u  ON o.user_id    = u.id
LEFT JOIN `user_info` AS ui ON ui.user_id   = u.id
LEFT JOIN `booking`   AS b  ON o.booking_id = b.id
WHERE
    (
            e.name       = "hanam202101"
        AND c.`status` = "used"
        AND o.parent_id IS NULL
        AND
            (
                   ( o.online <> 1 AND ( b.date        BETWEEN '2021-07-01' AND '2021-10-01' ) )
                OR ( o.online <> 0 AND ( o.rental_date BETWEEN '2021-07-01' AND '2021-10-01' ) )
                OR ( o.online <> 0 AND o.rental_date IS NULL )
            )
    )
ORDER BY onoff, rental_ymd, booking_ymd;
```

**Comment by aanoaa** [comment]
> 형석님~ 안양시 3분기 내역이 나한테 준 이용자 수는 75명인데,
> 수지니 이벤트현황에는 73명이야. 왜 차이날까?

통계페이지 상의 9월 온라인 대여는 0건 이지만, 일괄로 사용 건 수를 뽑아봤을때에는 1건이 있습니다.
이를 바탕으로 추적해봤습니다.

<table border="2" cellspacing="0" cellpadding="6" rules="groups" frame="hsides">


<colgroup>
<col  class="org-right" />

<col  class="org-right" />

<col  class="org-right" />

<col  class="org-right" />

<col  class="org-left" />
</colgroup>
<thead>
<tr>
<th scope="col" class="org-right">MM</th>
<th scope="col" class="org-right">online</th>
<th scope="col" class="org-right">offline</th>
<th scope="col" class="org-right">all</th>
<th scope="col" class="org-left">특이사항</th>
</tr>
</thead>

<tbody>
<tr>
<td class="org-right">09</td>
<td class="org-right">0</td>
<td class="org-right">6</td>
<td class="org-right">6</td>
<td class="org-left">집계상에서는 온라인 대여 1건</td>
</tr>


<tr>
<td class="org-right">08</td>
<td class="org-right">3</td>
<td class="org-right">17</td>
<td class="org-right">20</td>
<td class="org-left">&#xa0;</td>
</tr>


<tr>
<td class="org-right">07</td>
<td class="org-right">5</td>
<td class="org-right">42</td>
<td class="org-right">47</td>
<td class="org-left">&#xa0;</td>
</tr>
</tbody>
</table>

주문서 번호 `196269` 가 그 것 입니다.

통계에서 수집 조건 입니다.

1.  [ ] 주문서의 rental\_date 가 수집일 -1d (2021-09-04 일 수집했다면 대여일은 2021-09-03 일)
2.  [X] 수집 당시의 주문서의 상태가 `대여중` 혹은 `반납`
3.  [ ] 수집 당시의 쿠폰 상태가 "used"

2 번은 데이터가 남아 있어서 확인이 가능했지만,
1, 3번은 변경되는 데이터라서 수집 당시의 데이터가 지금은 변했습니다.

&#x2014;

1.  [X] 현재 주문서의 rental\_date: `2021-09-03 00:00:00`
2.  [X] 현재 주문서의 상태: `반납`
3.  [X] 현재 주문서의 쿠폰 사용 상태: `used`

&#x2014;

정리하면, 현재 주문서 데이터가 수집 당시에 쓰였다면 수집되었어야 합니다.
하지만 수집할때에 어떤 이유에서인지 수집되지 못했습니다.
수집 당시에 주문서의 대여일 또는 주문서상의 쿠폰의 상태가 일치하지 않았을 수 있습니다.
관리자에 의해 변경되었거나 혹은 예외케이스일 수 있습니다.(이 주문서의 경우 퀵 발송 인데 특이하게도 운송장 번호가 있습니다)

**Comment by aanoaa** [comment]
예외 사례가 발견되었기에 선조치 후탐구 하겠습니다.
간략한 사례와 주문번호를 남겨주세요. @pingpongworks 

    -- 남양주는 9월 3일, 1명 추가
    SELECT * FROM visitor WHERE online = 0 AND event = 'namyangju202101' AND `date` = '2021-09-03'\G
    UPDATE visitor SET visited = 1, visited_female = 1, visited_age_20 = 1 WHERE online = 0 AND event = 'namyangju202101' AND `date` = '2021-09-03';
    
    -- 안양은 7월 6일, 1명
    SELECT * FROM visitor WHERE online = 0 AND event = 'anyang202101' AND `date` = '2021-07-06'\G
    UPDATE visitor SET visited = 1, visited_female = 1, visited_age_20 = 1 WHERE online = 0 AND event = 'anyang202101' AND `date` = '2021-07-06';
    
    -- 7월 16일, 1명 추가
    SELECT * FROM visitor WHERE online = 0 AND event = 'anyang202101' AND `date` = '2021-07-16'\G
    UPDATE visitor SET visited = 1, visited_female = 1, visited_age_20 = 1 WHERE online = 0 AND event = 'anyang202101' AND `date` = '2021-07-16';

**Comment by pingpongworks** [comment]
> 196269
위 주문서는 퀵으로 신청했는데 상황이 바뀌어서 우체국으로 발송한 케이스입니다. 그래서 운송장번호를 입력한 경우입니다. 이번 오류와 연관성은 없지 않을까요?
