### ISSUE TITLE
[쿠폰] dakkyoungsa202101 쿠폰의 폐기

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1839]
#1830 이슈에서 요청드렸던 쿠폰 전체를 사용할 수 없는 쿠폰으로 폐기 처리 요청드립니다. 

쿠폰번호를 전달한 이후 제휴 관련한 진행이 정상적으로 되지 않아
혹시라도 운영진이 쿠폰을 임의로 사용하는 것을 방지하고자 합니다.

**Comment by aanoaa** [comment]
발행된 쿠폰은 모두 만료 시켰고, 이벤트 기간도 만료 했습니다.

**Comment by aanoaa** [comment]
만료 방법은..
쿠폰과 이벤트의 만료시간을 현재 시간으로 변경했습니다.

    UPDATE event SET end_date = NOW() WHERE id = 69;
    UPDATE coupon SET expires_date = NOW() WHERE event_id = 69;
