### ISSUE TITLE
통계요청 : 3회 이상 대여 할인 / 주문서의 사용자 상세정보 

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1868]
#1863 연관 이슈입니다. 
할인정책 리뉴얼을 하다보니까 그동안 할인받은 대상자에 대한 좀더 깊은 연구가 필요해졌습니다. 나이, 대여목적 등에 따라 판단이 달라질 수 있는 부분이 있습니다.  #1863 에서 주신 2021년 1월 1일 ~2022년 3월 현재까지 3회 이상 대여 할인받은 주문서의 사용자 상세정보를 요청드립니다. 

_
- 기간 : 2021년 1월 1일 ~ 2022년 3월 20일
- 대상 : 3회 이상 대여로 할인을 받은 사용자

_
- 이름
- 휴대폰번호
- 태어난해
- 성별
- 대여목적
- 대여품목
- 금액 (원래 금액 / 최종결제액)
- 방문대여 / 택배대여 여부
- 총 대여횟수 / 3회 이상 대여할인받은 대여횟수

**Comment by yongbin** [comment]
```sql
SELECT
       d.*
     , b.id          AS 'order_id'
     , b.rental_date AS 'rental_date'
     , a.price
     , a.final_price
     , a.name
     , b.online
     , c.price           as price
FROM `order_detail` AS a
         LEFT JOIN `order` AS b ON a.order_id = b.id
        inner join clothes c on a.clothes_code = c.code
        inner join `user` d on b.user_id = d.id
        inner join `user_info` e on e.user_id = d.id

WHERE b.rental_date BETWEEN '2021-01-01' AND '2021-12-31'
  AND a.desc = '3회 이상 방문(셋트 이외 무료)'
```

처리하고 메일로 회신드렸습니다.
