### ISSUE TITLE
방문 예약시 선택 품목에 "코트" "가방" 추가

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1869]
![스크린샷 2022-03-28 오후 9 04 59](https://user-images.githubusercontent.com/17288038/160396959-798c2d8d-2be3-43fd-8afd-cb6c0bfdafd5.png)

방문예약시 선택 품목에 코트와 가방을 추가 요청드립니다.

**Comment by keedi** [comment]
해당 두 항목 추가했습니다. 이상 동작 있을 경우 본 이슈에 이어서 남겨주세요.

![Screenshot_2022-05-01-02-45-11-835_org mozilla firefox](https://user-images.githubusercontent.com/138451/166116602-37285824-09ee-4669-8bdc-531d40cb156e.jpg)

**Comment by pingpongworks** [comment]
확인했습니다. 감사합니다~
