### ISSUE TITLE
예약슬롯 조정

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1879]
근무인원 변경으로 예약슬롯 조정하고자 합니다. 수정 부탁드립니다.

![스크린샷 2022-04-30 오후 6 37 16](https://user-images.githubusercontent.com/17288038/166100367-c7c7e7cb-4a3a-4737-9edd-ccb5053fe443.png)

**Comment by keedi** [comment]
수정 및 서버에 적용 완료했습니다.

피드백 부탁드립니다.

**Comment by pingpongworks** [comment]
지금 예약활성화 했을 때 아직 적용이 안 된 거 같습니다. 서버 적용에 시간이 걸리는 걸까요?

**Comment by keedi** [comment]
서버에 적용했는데, 재기동이 필요한 건 이네요. 방금 재기동했으니, 한 번 더 확인 부탁드립니다.

**Comment by pingpongworks** [comment]
확인했습니다. 감사합니다~
