### ISSUE TITLE
이벤트통계 페이지 개선_쿠폰의 월별 대여횟수 표 및 쿠폰의 상태 확인 기능 추가

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1885]
1.
![스크린샷 2022-06-25 오전 9 32 56](https://user-images.githubusercontent.com/17288038/175758298-b2a913ab-c4bc-432d-aa76-451ec16784e0.png)
쿠폰의 종류가 많아지면서 쿠폰이름이 너무 길게 나열되어 구분하여 보기가 어렵습니다. 연도 별 탭내에 각 지자체의 이용자수를 월별로 볼 수 있도록 페이지 수정 요청드립니다. 지자체 담당자에게 이벤트통계를 볼 수 있는 페이지를 공유했었으나, 담당자들이 실제로는 페이지를 거의 보지않아 현재는 페이지의 주소 공유를 하고 있지 않습니다. 현재는 남/여 구분, 이용자 나이대 통계보다는 지자체별, 월별 이용자수를 한 눈에 보는 페이지가 더 필요한 것으로 생각되어 요청드립니다.  => 섬네일 하단 첨부

2. 
이용자가 지자체 무료대여 쿠폰으로 예약을 시도하다가 오류뜨는 상황이 많아 이벤트 통계 페이지에 쿠폰 상태를 확인할 수 있는 기능 추가를 요청합니다.  => 섬네일 하단 첨부

-----
[수정 섬네일]
1.
![수지니 수정안 01 001](https://user-images.githubusercontent.com/17288038/175875045-69ec209b-9292-49b8-b06b-398afd954749.jpeg)
- 위치 : `staff 페이지` >> `통계 `>> `이벤트이용현황` >> `이벤트통계`
- 각 쿠폰별로 월별 이용자수를 알 수 있도록 표로 구성
- 월별 이용자수를 다운로드할 수 있는 기능 추가 => 매달 개발팀에 요청하고 있는 이용자 내역을 스태프가 바로 액셀파일로 다운로드 할 수 있으면 업무상 편할 듯 합니다. 

2.
![수지니 수정안 001](https://user-images.githubusercontent.com/17288038/175892528-da8ec9d8-4379-4da6-881a-99ce8d38f473.jpeg)
- 쿠폰상태 확인 기능
1) 쿠폰코드를 입력하면 `null` `used` 등 상태 확인이 가능하도록
2) `used`인 경우 사용한 주문서 확인이 가능하도록
3) 필요한 경우 쿠폰 상태를 사용된쿠폰 / 사용가능한 쿠폰 중 선택해서 변경 가능하도록

**Comment by keedi** [comment]
@pingpongworks 

담당자 변경했습니다. 이후 @yongbin 님과 논의 이어가주시면 됩니다.

**Comment by pingpongworks** [comment]
일단은 리툴로 쿠폰 상태 확인과 쿠폰 상태 변경이 가능하도록 되었습니다. 이슈 닫겠습니다.
