### ISSUE TITLE
쿠폰 통계 : 안산시/구리시/남양주시/세종시/강원도/하남시/충주시/안양시 쿠폰 사용내역 

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1886]
1.
기간 : 2022년 6월 1일부터 2022년 6월 30일까지
대상쿠폰 : guri202201, namyangju202201

2.
기간 : 2022년 4월 1일부터 2022년 6월 30일까지
대상쿠폰 : ansan202201, hanam202201, anyang202201, sejong202202,  gangwon202201

3.
기간 : 2022년 1월 1일부터 2022년 6월 30일까지 
대상쿠폰 : chungju202201

방문대여와 택배대여가 구분되도록 하여
7월 1일까지 전달 부탁드립니다.

**Comment by aanoaa** [comment]
메일로 보내드렸습니다.

**Comment by pingpongworks** [comment]
확인했습니다. 감사합니다.
