### ISSUE TITLE
의복 사진과 썸네일 등록

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#19]
현재는 의복에 대한 사진을 등록할 수 없습니다.
이를 고려해야 합니다.

**Comment by keedi** [comment]
의복 사진과 관련해서는 페이지에 업로드 기능을 넣거나 데이터베이스에 넣지 않고 파일 시스템을 이용해서 접근해서 보여주도록 구현할 예정입니다. 3차 오픈때 진행합니다.

**Comment by keedi** [comment]
일단 공식적으로 letters, visit 작업을 제외하고는 제가 처리하지 않을 예정입니다. 기존 제가 처리하려고 했던 이슈는 모두 담당자를 제거한 이후, 그 이후에 새롭게 담당자로 제가 지목되는 이슈에 한해 처리하겠습니다. 관련해서 제가 할당된 이슈의 담당자를 모두 제거하겠습니다.

**Comment by aanoaa** [comment]
https://github.com/opencloset/opencloset/issues/869 에서 해결되었습니다.
