### ISSUE TITLE
쿠폰 발행 : namyangju202301 / ansan202301 쿠폰의 신규 발급

### ISSUE THREAD

**Issue by yesminnn** [opencloset/opencloset#1925]
1.
아이디 : namyangju202301
이름 : 남양주 꿈날개옷장 2023
발급 : 610
유형 : B타입
택배비 여부: 온라인 배송비는 대여자 부담 / 온오프라인 반납택배비는 지자체 부담
사용기간 : 2023-01-01~2023-12-31    

2.
아이디 : ansan202301
이름 : 안산 취업옷장 2023
발급 : 610
유형 : B타입
택배비 여부: 온라인 발송비 / 온오프라인 반납택배비 모두 안산시 부담
사용기간 : 2023-01-01~2023-12-31

- 테스트 후 전달할 수 있도록 10개씩 더 요청했습니다. 
- **쿠폰기한, 택배비 부담 여부, 단벌할인금액 남여 모두 34,000원**  확인해서 발행 부탁드립니다. 
- 1월 5일 전달할 수 있도록 발행 부탁드립니다.

**Comment by aanoaa** [comment]
메일로 보내드렸습니다.

**Comment by yesminnn** [comment]
남양주/안산 쿠폰 모두 정상사용 가능합니다~!  (오프라인에서 단벌할인 40,000원 적용 제외). 감사합니다~!
