### ISSUE TITLE
2023년도 서울시 쿠폰 오픈 준비

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1926]
2023년도 서울시 무료대여 서비스를 시작해야 해서 서울시 예약사이트와 열린옷장 예약페이지 연결작업 요청드립니다.
서울시 예약사이트에서 넘어오는 신호를 `/seoul/2022/1` => /seoul/2023/1 으로 바꿔야 정상적으로 동작하는 것으로 알고 있습니다.

#1855
#1759  참고 부탁드립니다. 

1월 4일부터 예약이 가능하도록 부탁드립니다.

**Comment by pingpongworks** [comment]
<img width="791" alt="168F7589-4934-4534-BC58-A5E73C0E3D99" src="https://user-images.githubusercontent.com/17288038/210500702-e5b5ecc7-c0c8-48b5-83cc-f08a02343303.png">
온라인 주문시 위와같이 뜹니다. 쿠폰기한 변경이 필요합니다. 2023-01-04 ~ 2023-12-31로 변경 부탁드립니다. 

방문예약하려고 할 때 예약할 일자가 뜨지않는 오류가 있는데 같은 이유인듯 합니다. 

#1855 이슈를 참고하여 3곳의 저장소룰 변경하고 약간의 db 작업이 필요하다고 합니다.

**Comment by aanoaa** [comment]
작업이 간략해져서 아래 2개를 진행하면 해결될 것으로 보입니다.

- [x] DB 에 이벤트 정보 추가
- [x] OpenCloset-Coupon-Web 에서 요청되는 경로 변경 후에 배포

**Comment by aanoaa** [comment]
이벤트 정보는 있으나 누락된 정보가 있어서 업데이트 했습니다.

    SET NAMES utf8;
    UPDATE event SET title = '취업날개',  sponsor = '서울특별시 일자리정책과' WHERE id = 132;

시작일이 2023-01-14 일로 잘못 반영되어 있어 수정했습니다.

    UPDATE event SET start_date = '2023-01-04 00:00:00' WHERE id = 132;

**Comment by aanoaa** [comment]
작업해서 배포했습니다.
테스트할 수 있습니다.

**Comment by pingpongworks** [comment]
온라인/ 오프라인 모두 정상입니다. 감사합니다.
