### ISSUE TITLE
쿠폰 발행 : wonju202301/ iksan202301쿠폰의 신규 발급

### ISSUE THREAD

**Issue by yesminnn** [opencloset/opencloset#1928]
1.

    아이디 :  wonju202301
    이름 : 원주 정장대여 2023
    발급 : 210
    유형 : B타입
    택배비 여부: 온라인배송비 / 온오프라인 반납택배비 모두 원주시 부담
    사용기간 : 2023-1-10~2023-12-31

2.

    아이디 :  iksan202301
    이름 : 익산 정장대여 2023
    발급 : 210
    유형 : B타입
    택배비 여부: 온라인배송비 / 온오프라인 반납택배비 모두 익산시 부담
    사용기간 : 2023-1-10~2023-12-31

- 테스트용 10개씩 추가 발급 요청했습니다.
- 단벌할인금액 남녀 모두 34,000원 확인 부탁드립니다. 
- 1/11(수)까지 발급 부탁드립니다.

**Comment by pingpongworks** [comment]
테스트 결과 배송비 설정이 본인 부담으로 되어 있습니다. 
일반택배로 주문시 배송비 결제를 하지 않도록 수정 요청합니다.

**Comment by pingpongworks** [comment]
다시 발행한 쿠폰의 배송비 설정, 정상으로 되었습니다.쿠폰 설정은 잘 되었습니다. 
다만, 원주 쿠폰으로 주신 코드로 주문을 하니까 이름이 "익산 정장대여 2023"으로 뜹니다. 이름을 "원주 정장대여 2023"으로 부탁드립니다.

**Comment by pingpongworks** [comment]
수정확인했습니다. 감사합니다.

**Comment by pingpongworks** [comment]
익산시 쿠폰 중 일부가 단벌할인 적용이 잘못되어 있습니다. 34,000원 이상 추가해서 주문하면 전체 금액이 모두 할인됩니다. 정상 쿠폰인 것도 있고, 오류 있는 쿠폰도 있어서 확인 부탁드립니다. 
![IMG_0431](https://github.com/opencloset/opencloset/assets/17288038/6114022c-61ba-4097-8996-f931db980759)
