### ISSUE TITLE
OpenCloset::Schema 를 별도 저장소로 분리후 관리

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#193]
schema 는 종종바뀌고 이를 사용하는 저장소는 두개 입니다.
이를 darkpan 에 배포해도 되지만, submodule 로 맨들면 더 간편합니다.

**Comment by keedi** [comment]
1차 오픈 및 피드백 관련 작업이 모두 종료되었습니다! (드디어... ㅎㄷㄷ)

이 작업을 진행할 최적의 타이밍이라고 사료됩니다. 진행하겠습니다!

**Comment by keedi** [comment]
현재 라이브러리 디렉터리 구조는 다음과 같습니다.

> lib
> └── OpenCloset
>     ├── Cron
>     │   └── Worker.pm
>     ├── Cron.pm
>     ├── Patch
>     │   ├── AnyEvent
>     │   │   └── HTTPD.pm
>     │   └── Object
>     │       └── Event.pm
>     ├── Role
>     │   └── Ping.pm
>     ├── Schema
>     │   ├── Base.pm
>     │   └── Result
>     │       ├── Booking.pm
>     │       ├── Clothes.pm
>     │       ├── ClothesTag.pm
>     │       ├── Donation.pm
>     │       ├── Group.pm
>     │       ├── Order.pm
>     │       ├── OrderDetail.pm
>     │       ├── OrderStatusLog.pm
>     │       ├── SMS.pm
>     │       ├── Satisfaction.pm
>     │       ├── Status.pm
>     │       ├── Tag.pm
>     │       ├── User.pm
>     │       ├── UserBooking.pm
>     │       └── UserInfo.pm
>     ├── Schema.pm
>     └── Util.pm
> 
> 8 directories, 23 files

이 중 `lib/OpenCloset/Schema.pm`과 `lib/OpenCloset/Schema/` 디렉터리를 분리할 예정입니다.

**Comment by keedi** [comment]
새로 생성하는 저장소 이름은 다음 중 하나가 될 예정입니다.

- OpenCloset-Schema
- p5-OpenCloset-Schema
- opencloset-schema
- p5-opencloset-schema

**Comment by keedi** [comment]
특별한 이유가 없다면 관례적으로 펄 모듈은 CamelCase를 사용하며 더불어 `::`기호는 `-`로 대체합니다. 따라서 `OpenCloset-Schema`가 제일 무난합니다.

**Comment by keedi** [comment]
저장소를 생성했습니다.

https://github.com/opencloset/OpenCloset-Schema

**Comment by keedi** [comment]
더불어 `db/` 디렉터리 및 하부 파일도 이동하거나 통폐합 될 예정입니다.

**Comment by keedi** [comment]
다음 명령을 이용해서 별도 저장소로 분리했습니다.

```bash
git filter-branch --prune-empty --index-filter '\
  git rm -r --cached --ignore-unmatch \
    README.md \
    templates \
    lib/OpenCloset/Cron.pm \
    lib/OpenCloset/Util.pm \
    lib/OpenCloset/Role \
    lib/OpenCloset/Patch \
    lib/OpenCloset/Cron \
    coffee \
    public \
    package.json \
    Gemfile \
    app.psgi \
    app.conf.sample \
    cpanfile \
    sass \
    scripts \
    bin \
    Gruntfile.js \
    Gemfile.lock \
    config.rb \
    .gitignore \
    lib/OpenCloset/Constant.pm \
    import.pl \
    lib/Text \
    assets \
    app.conf \
  ' HEAD
git remote rm origin
git update-ref -d refs/original/refs/heads/master
git reflog expire --expire=now --all
git repack -ad
git remote add origin git@github.com:opencloset/OpenCloset-Schema.git
git push -f origin develop
```

참고한 내용은 다음과 같습니다.

- http://stackoverflow.com/questions/359424/detach-subdirectory-into-separate-git-repository
- git help filter-branch

**Comment by keedi** [comment]
유사한 방식으로 옮긴 파일의 로그를 제거할 수는 있지만, 열람의 용이성을 위해 기존 저장소에선 굳이 로그를 지우지 않고 `git rm`을 하는 수준에서 끝내려고 합니다. 최종적으로 제거하는 시점은 분리한 저장소에서 완전히 모듈 형태로 작성한 다음 타르볼까지 나오고 업로드까지 완료되면 그 시점에 제거하도록 합니다.

**Comment by keedi** [comment]
완료된 내역입니다.

- OpenCloset::Schema 모듈의 저장소를 분리
- OpenCloset::Schema 모듈을 CPAN 모듈 형태로 수정
- OpenCloset::Schema 모듈을 [열린옷장 CPAN 주소](https://cpan.theopencloset.net)로 설치 가능하게 함

**Comment by keedi** [comment]
이제 남은 것은 기존 파일들을 제거하는 것입니다. 기존 저장소에서 정확하게 옮긴 파일을 제거한 후 이슈를 닫겠습니다. 관련해서 별도 가지에서 작업하던 내용들은 아마도 opencloset/OpenCloset-Schema 저장소에서 별도 이슈를 생성한 후 계속 진행해 나가야 할 것입니다. (@aanoaa, @yongbin 참고해주세요.)

**Comment by keedi** [comment]
완료되었으며 제거한 목록은 다음과 같습니다.

- `db/init.sql`
- `db/schema-loader.pl`
- `db/test-data.sql`
- `lib/OpenCloset/Schema.pm`
- `lib/OpenCloset/Schema/Base.pm`
- `lib/OpenCloset/Schema/Result/Booking.pm`
- `lib/OpenCloset/Schema/Result/Clothes.pm`
- `lib/OpenCloset/Schema/Result/ClothesTag.pm`
- `lib/OpenCloset/Schema/Result/Donation.pm`
- `lib/OpenCloset/Schema/Result/Group.pm`
- `lib/OpenCloset/Schema/Result/Order.pm`
- `lib/OpenCloset/Schema/Result/OrderDetail.pm`
- `lib/OpenCloset/Schema/Result/OrderStatusLog.pm`
- `lib/OpenCloset/Schema/Result/SMS.pm`
- `lib/OpenCloset/Schema/Result/Satisfaction.pm`
- `lib/OpenCloset/Schema/Result/Status.pm`
- `lib/OpenCloset/Schema/Result/Tag.pm`
- `lib/OpenCloset/Schema/Result/User.pm`
- `lib/OpenCloset/Schema/Result/UserBooking.pm`
- `lib/OpenCloset/Schema/Result/UserInfo.pm`

**Comment by keedi** [comment]
실서버에 배포 또한 완료했으며 서비스가 문제없이 돌아감도 확인했습니다. 이를 위해 실서버의 서비스 구동 계정에 `cpanm --mirror=https://cpan.theopencloset.net --mirror=http://cpan.silex.kr OpenCloset::Schema` 명령을 이용해 가장 최신 버전의 스키마 파일을 설치했습니다.

**Comment by keedi** [comment]
처리한 내역은 다음과 같습니다.

- `OpenCloset::Schema` 모듈 관련 파일 및 데이터베이스 스키마 관련 파일 제거
- `cpanfile`의 의존 모듈 목록 갱신

**Comment by keedi** [comment]
앞으로 스키마 관련 이슈는 opencloset/OpenCloset-Schema 저장소의 이슈에서 논의하도록 합니다.

**Comment by keedi** [comment]
작업 완료했으므로 이슈 닫습니다! :-)
