### ISSUE TITLE
<반납택배발송알리미>에 운송장번호를 입력했을 때 운송장번호를 확인할 수 있는 방법 

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1943]
<img width="551" alt="스크린샷 2023-06-01 오전 9 31 04" src="https://github.com/opencloset/opencloset/assets/17288038/3ede6cae-7282-4709-be43-1f5f573165ca">

대여자가 택배로 반납의류를 발송한 후 `반납택배 발송알리미`에 운송장번호를 입력했을 때
운송장번호는 어디에 저장되나요?
스태프가 확인할 수 있는 방법이 있을까요?

#330 이슈에서 주문서에 운송장번호를 저장할 수 있도록 작업을 했던 거 같은데 지금은 구현되어 있지 않은데 이유가 있을까요?

**Comment by keedi** [comment]
근 10년 전 작업이라 다 기억은 못하지만 운송장 번호는 당시 기준 주문서 내에 저장했습니다. 아마도 `order.return_method` 와 같은 필드에 택배사 이름과 함께 저장했던 것으로 기억합니다. 운송장 번호가 없으면 택배사 추적 링크를 보여드릴수가 없으니까요.

구현되어 있지 않다는게 어떤 의미이신지 조금만 더 자세하게 설명해주실 수 있을까요? 되던게 안되는건지, 기능이 없지만 필요한 것인지, 정확하게 필요한 기능이 무엇인지 확인 부탁드려요.

**Comment by pingpongworks** [comment]
현재는 CJ 대한통운과 우체국만 왼쪽의 `반납방법`을 누르면 대여자가 입력한 운송장번호를 확인할 수 있습니다. 

예시 `orders/236234` 
<img width="631" alt="스크린샷 2023-06-01 오후 5 27 45" src="https://github.com/opencloset/opencloset/assets/17288038/7f6322f5-14ef-4deb-b57b-222783322ae7">

CVS편의점 택배나 로젠, 동부, 한진과 같이 그 외 택배사의 경우에는 대여자가 입력한 택배사는 주문서에서 확인이 가능한데
운송장번호는 확인을 할 수가 없습니다. 

대여자가 반납택배발송 알리미에 입력한 운송장번호가 어딘가 저장된 곳이 있을 거 같은데 스태프가 확인할 방법이 없어서요.   

#330 이슈를 보니까 주문서에 택배사 하단에 운송장번호가 들어가는 칸이 만들어졌던 거 같은데 현재는 없어서 문의드립니다. 
![image](https://github.com/opencloset/opencloset/assets/17288038/2d9c14e6-0e80-4693-8b9a-c3c420b05d7a)

**Comment by keedi** [comment]
택배사 별로 따로 처리하는 로직이 들어가진 않았는데 대여자가 정의한 택배사라고 하시니, 그러면 해당 이슈 개발 당시에는 없던 기능이긴 합니다. 사용자 입력 택배사 지원은 이후에 지원된 기능일거에요.

지금 찾아보니 해당 이슈는 #609 에서 처리된 이슈로 보입니다. 기능 자체는 들어간지 오래되었는데요. 해당 이슈 때 기준으로 지금 말씀주신 이슈는 없었나요? 아니면 계속 존재한 이슈인데 지금 알려주신 것일까요?

@aanoaa 께서도 이 부분 확인 부탁드릴게요~

**Comment by keedi** [comment]
#1166 도 관련있는 이슈인 것 같네요. 역시 같이 확인 부탁드립니다.

**Comment by pingpongworks** [comment]
>지금 찾아보니 해당 이슈는 https://github.com/opencloset/opencloset/issues/609 에서 처리된 이슈로 보입니다. 기능 자체는 들어간지 오래되었는데요. 해당 이슈 때 기준으로 지금 말씀주신 이슈는 없었나요? 아니면 계속 존재한 이슈인데 지금 알려주신 것일까요?

#609 이슈를 통해서 대여자가 운송장번호와 택배사를 입력할 수 있도록 하는 기능이 만들어졌는데
#1166 이슈에서 대한통운과 우체국 외의 택배사의 운송장번호는 볼 수 없도록 작업이 된 거 같네요. 

대한통운과 우체국 외의 택배사를 모두 연결하기가 어렵다는 사실은 알고 있었습니다. 
그래서 기타 택배사인 경우에는 택배 발송을 했다는 사실만 확인하고 운송장번호는 따로 확인을 하지 않았습니다.

그런데 요즘 택배 반납을 하는 사람이 많아지면서 발송일이나 운송장 확인을 해야하는 경우가 생기고 있어서
대한통운이나 우체국처럼 대여자가 입력한 운송장을 확인해볼 수 있었으면 합니다. 

편의점 택배를 이용하는 분이 많은데 편의점 택배 운송장은 조회가 되지 않는다면 조회는 안되더라도
반납택배발송 알리미에 입력한 운송장번호가 주문서로 들어와서 스태프가 볼 수 있으면 좋을 거 같아요.

**Comment by aanoaa** [comment]
#1651 에서 리포팅 해주셨는데 하직 해결되지 않았습니다.
유효한 운송장일 경우에만 나타내고 있는 것 같은데, 유효성과 상관없이 택배관련정보를 나타내야 합니다.

반납방법에 운송장 입력은 #609 에서 staff 이 입력하는 방식에서 사용자에게 입력을 요구하는 방식으로 변경되면서 간소화 되었습니다.

**Comment by pingpongworks** [comment]
주문서에 운송장번호 입력되고 있습니다. 그 사이에 작업을 해주신 거죠?
