### ISSUE TITLE
크롬(chrome)  접속 오류

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1953]
<img width="456" alt="스크린샷 2023-10-27 오후 2 10 10" src="https://github.com/opencloset/opencloset/assets/17288038/cb4c30f6-4f40-487f-8376-f685cd14e037">

이용자가 대여를 위한 방문예약, 택배대여, 기증신청 등 *.theopencloset.net 도메인에 크롬 브라우저에서 접속하려고 할 때 위와 같은 오류가 뜨고 있습니다. 전체 이용자가 그런 것은 아니라서 SSL소프트웨어 노후화로 인한 문제가 아닐까 예측하고 있습니다. 

이용자 문의가 있을 때마다 일단은 다른 브라우저 이용을 안내하고 있습니다만 조속한 원인 규명과 개선이 필요할 듯 합니다. 

최근에 크롬 업데이트 이후에 뜨는 오류인 거 같아서 인터넷 검색해보니까 다른 곳에서도 같은 현상을 겪고 있더라고요.
ERR_SSL_PROTOCOL_ERROR 에러
https://blog.naver.com/design_top/223228826716

chrome://flags에서 몇 가지 변경하면 된다고 블로그에 나와있어서 해보니까 정상 접속이 되기는 합니다만, 이용자들에게 안내하기는 어려운 내용이고요. 일단은 다른 브라우저 이용을 권하고 있는데 내부에서 뭔가 해결할 방안이 있을까요?

**Comment by keedi** [comment]
해당 이슈는 길면 7\~8년, 짧으면 1\~5년 정도 되었는데요.

해당 이슈 뿐만 아니라 몇가지 보안 및 운영체제 지원 이슈로 서버 장비 이전과 운영체제 업그레이드(7\~8년전), 운영체제 교체(1\~5년전) 요청을 했는데, @yongbin 님께서 진행하지 않은 상태고, 관련해서 이슈가 발생한 것으로 보입니다. 관련한 문제 원인과 해결책을 간단히 설명드립니다. 우선 문제의 원인 및 히스토리는 다음과 같습니다.

- 서버의 openssl 버전은 1.0.1e 이고, 현 시점 기준 크롬에서 해당 버전 지원을 종료한 것으로 보입니다.
- 크롬 종료와 별개로 몇가지 시그널은 있었기 때문에 대응 요청을 했으나 관련해서는 진행되지 않은 것으로 보입니다.
- 보통 openssl 은 운영체제 여러 구성요소와 엮여 있기 때문에, openssl 만 단독으로 관리하는 것은 번거롭기 때문에 운영체제 업데이트 및 업그레이드 시기와 맞추어 openssl 버전 업그레이드를 진행합니다. openssl 단독 버전 업그레이드가 불가능한 것은 아니나, 여러가지 이유로 까다롭습니다.
- 현재 7-8년 전 운영체제 EOS 를 고려해서, 진행하려 했던 것, 이후 EOS 므로, 운영체제 업 또는 openssl 버전업 을 고려했었던 것입니다.
- 원칙적으로는 인증서 자체에는 문제가 없으나, 여러 브라우저 중 크롬이 해당 openssl 버전을 사용할 경우 취약하다고 판단했기 때문에, 막은 것이라, 다른 브라우저도 길지 않은 시간 내에 차단할 것으로 보입니다.
- 크롬과 별개로 curl, wget 등 시스템 유틸리티는 이미, 5여년 전부터 관련 오류가 발생하고 있었고, 이로 인해 staff 와 monitor 쪽 통신 이슈가 발생해서, 당시, 이 문제를 보고 했고, 관련해 진행되지 않아, ssl을 사용하지 않고 내부통신을 하는 식으로 임시 우회 처리를 했으며, 이것이 그대로 이어진 상태입니다.

해결책은 다음과 같습니다. 해결책 자체는 간단하나 운영체제의 EOS 시기를 놓쳤기 때문에 간단하게 해결할 수 있는 방법은 없습니다. 본 이슈는 서버 구성의 문제기 때문에 사용자가 할 수 있는 것은 없다고 볼 수 있습니다. (설정 변경을 해야하는데, 현실적으로 고객에게 요청하기는 어렵습니다. 내부 직원 장비의 경우 설정은 가능하나, 보안에 취약해지므로 추천하는 설정은 아닙니다.)

- openssl 을 크롬에서 문제가 없는 버전으로 업데이트 합니다. 관련 연관 소프트웨어의 리빌드 및 동작 검증이 필요합니다. 다만 운영체제의 EOS 문제는 해결되지 않습니다.
- 운영체제를 재설치하고, 서버 및 연관 소프트웨어를 설치, 리빌드 후 동작 검증이 필요합니다.

**Comment by yongbin** [comment]
말씀하신것 처럼 오래된 이슈인데 처리가 너무 늦었습니다. 죄송합니다. 이번 주말에 debian wheezy 에서 jessie 로 업데이트 진행해서 결과적으로 어느정도 상황은 해결된것 같습니다. 현재 상태는 다음과 같습니다.

- wheezy 에서 jessie 로 dist upgrade 형태의 upgrade 진행
- jessie 도 eos 된 상태이기때문에 archive 에 존재하는 repo 를 대상으로 진행했으며, 공식 repo 이외에 저장소 및 패키지들은 모두 삭제(libpam-ssh-agent-auth, icinga2, 외 다수) 
- 그 밖에 설정상 기동에 이슈가 있는 서버 설정 및 이슈들은 제거하고 정상적으로 기동완료
- mysql, ubic, sshd, redis-server(*) 등 주요 데몬 상태 확인했고 openssl 은 `OpenSSL 1.0.1t  3 May 2016` 으로 업그레이드 되었으며, 크롬에서 특별한 경고없이 접속됨을 확인
- 소령님 통해서 1차적으로 서비스 상태 확인 요청했으며 대여등 DB기반 동작 및 redis 기반 동작 확인완료
- 다음이슈는 발견되었지만 당장 서비스에 직접적인 영향이 없어서 원복하지 않고 이상태로 진행하기로 결정
   -  libpam-ssh-agent-auth 가 없기때문에 키 기반 sudo 가 동작하지 않음 : 개별사용자 계정을 기본 비밀번호로 reset (sudo group 이기때문에 키인증 접속후 sudo su - 에서 자기비밀번호로 재인증 하면 권환획득 가능)
   - redis-server 가 정상기동후 systemd 에 정상상태등록이 실패함 : 아마 /var/run 권한이슈인것으로 보이나 동작에는 이상없음
- 기존 서버는 terra.silex.kr 에 localbackup 하부에 별도 백업했고(1차), 어제자 dist upgrade 이전 상태에 대해서 별도 snapshot LVM 스넵샷 보관중(vg-ssd/snap)

금주 주중에 특별하게 이슈가 없다면 주말통해서 동일한방식으로 buulseye 나 bookworm 으로 업그레이드 해두겠습니다.

**Comment by pingpongworks** [comment]
@yongbin 서버작업 이후 업무 진행 과정에서 확인된 오류입니다. 추가 작업하실 때 확인 부탁드립니다.

1. monitor (monitor, preparation,repair) 화면이 새로고침해야 새로운 정보가 반영됨
2. 서울시 쿠폰 대여 내역이 연동되지 않았음 => 해당 오류는 작업시간과 연동시간 중복으로 연동되지 않았을 것으로 보여서 좀 더 확인해보겠습니다.
