### ISSUE TITLE
2023 연말 뉴스레터 제작을 위한 데이터 요청 (5/24~12/15)

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1956]
기간 : 2023년 5월 24일 ~ 2023년 12월 15일
    
1. 기증
- 기증자 수
- 기증 건수
- 기증의류 전체수량
- 기증품 품목별 수량 : 자켓/바지/치마/셔츠/타이/벨트/구두/원피스/코트/가방/베스트/기타)
- 기증의류 사용 비율 : 열린옷장 사용가능 / 재기증 / 폐기
- 2023년 기증된 것 중 가장 대여 많이 된 옷 상위 5개 (열린옷장 기증품목 제외)

2. 편지
- 전체 기증편지 수
- 전체 대여편지 수

3. 대여
- 목적별 대여건수 : 입사면접, 결혼식, 대학(원)면접, 모의면접, 장례식, 졸업/입학식, 세미나/발표, 공연/축제, 사진촬영, 기타
- 남여별 대여건수 : 남, 여
- 연령비율 : -2005년생까지 (10대) / 2004년생-1995년생 (20대) / 1994년생-1985년생 (30대) / 1984년생-1975년생 (40대) / 1974년생 이후
- 전체 대여 지역별 분포 : 서울특별시, 부산직할시, 인천시, 대전광역시, 세종특별자치시, 경기도, 강원도, 경상남도, 경상북도, 전라남도, 전라북도, 충청남도, 충청북도, 제주도
- 택배대여 지역별 분포 : 서울특별시, 부산직할시, 인천시, 대전광역시, 세종특별자치시, 경기도, 강원도, 경상남도, 경상북도, 전라남도, 전라북도, 충청남도, 충청북도, 제주도

**Comment by bek9** [comment]
1. 기증

- 기증자 수: 359
- 기증 건수: 361
- 기증의류 전체수량: 2664
- 기증품 품목별 수량 : 자켓/바지/치마/셔츠/타이/벨트/구두/원피스/코트/가방/베스트/기타)
  - 자켓: 764
  - 바지: 726
  - 치마: 181
  - 셔츠: 260
  - 타이: 225
  - 벨트: 30
  - 구두: 110
  - 원피스: 80
  - 코트: 77
  - 가방: 4
  - 베스트: 16
  - 기타: 25
  - 블라우스: 166
- 기증의류 사용 비율 : 열린옷장 사용가능 / 재기증 / 폐기
  - 사용가능: 936
  - 재기증: 1649
  - 폐기: 79
- 2023년 기증된 것 중 가장 대여 많이 된 옷 상위 5개 (열린옷장 기증품목 제외)
  - 0E1NZ: 45회
  - 0E1OD: 30회
  - 0T7YP: 27회
  - 0A4FO: 22회
  - 0E1OK: 20회

2. 편지

- 전체 기증편지 수: 179
- 전체 대여편지 수: 138

3. 대여

- 목적별 대여건수 : 입사면접, 결혼식, 대학(원)면접, 모의면접, 장례식, 졸업/입학식, 세미나/발표, 공연/축제, 사진촬영, 기타
  - 입사면접: 6387
  - 결혼식: 1033
  - 대학(원)면접: 360
  - 모의면접: 116
  - 장례식: 235
  - 졸업/입학식: 160
  - 세미나/발표: 336
  - 공연/축제: 319
  - 사진촬영: 420
  - 기타: 391
- 남여별 대여건수 : 남, 여
  - 남: 5712
  - 여: 4325
- 연령비율 : -2005년생까지 (10대) / 2004년생-1995년생 (20대) / 1994년생-1985년생 (30대) / 1984년생-1975년생 (40대) / 1974년생 이후
  - 2005년생까지 (10대): 311
  - 2004년생-1995년생 (20대): 7063
  - 1994년생-1985년생 (30대): 2283
  - 1984년생-1975년생 (40대): 220
  - 1974년생 이후: 154
- 전체 대여 지역별 분포 : 서울특별시, 부산직할시, 인천시, 대전광역시, 세종특별자치시, 경기도, 강원도, 경상남도, 경상북도, 전라남도, 전라북도, 충청남도, 충청북도, 제주도
  - 서울특별시: 6581
  - 부산직할시: 41
  - 인천시: 112
  - 대전광역시: 44
  - 세종특별자치시: 97
  - 경기도: 2339
  - 강원도: 183
  - 경상남도: 46
  - 경상북도: 49
  - 전라남도: 20
  - 전라북도: 258
  - 충청남도: 47
  - 충청북도: 147
  - 제주도: 15
- 택배대여 지역별 분포 : 서울특별시, 부산직할시, 인천시, 대전광역시, 세종특별자치시, 경기도, 강원도, 경상남도, 경상북도, 전라남도, 전라북도, 충청남도, 충청북도, 제주도
  - 서울특별시: 50
  - 부산직할시: 1
  - 인천시: 19
  - 대전광역시: 6
  - 세종특별자치시: 6
  - 경기도: 46
  - 강원도: 13
  - 경상남도: 7
  - 경상북도: 9
  - 전라남도: 8
  - 전라북도: 11
  - 충청남도: 10
  - 충청북도: 10
  - 제주도: 1
