### ISSUE TITLE
상반기 성과 정리를 위한 통계 요청

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1961]
- 통계 기간 : 2024년 1월 1일 ~ 2024년 6월 30일
- 통계 내역 

1. 기증
- 기증자 수
- 기증 건수
- 기증의류 전체수량
- 기증품 품목별 수량 : 자켓/바지/치마/셔츠/타이/벨트/구두/원피스/코트/가방/베스트/기타)
- 기증의류 사용 비율 : 열린옷장 사용가능 / 재기증 / 폐기

2. 편지
- 전체 기증편지 수
- 전체 대여편지 수

3. 대여
- 목적별 대여건수 : 입사면접, 결혼식, 대학(원)면접, 모의면접, 장례식, 졸업/입학식, 세미나/발표, 공연/축제, 사진촬영, 기타
- 남여별 대여건수 : 남, 여
- 연령비율 : -2005년생까지 (10대) / 2004년생-1995년생 (20대) / 1994년생-1985년생 (30대) / 1984년생-1975년생 (40대) / 1974년생 이후
- 전체 대여 지역별 분포 : 서울특별시, 부산직할시, 인천시, 대전광역시, 세종특별자치시, 경기도, 강원도, 경상남도, 경상북도, 전라남도, 전라북도, 충청남도, 충청북도, 제주도
- 택배대여 지역별 분포 : 서울특별시, 부산직할시, 인천시, 대전광역시, 세종특별자치시, 경기도, 강원도, 경상남도, 경상북도, 전라남도, 전라북도, 충청남도, 충청북도, 제주도

**Comment by bek9** [comment]
1. 기증

- 기증자 수: 241
- 기증 건수: 244
- 기증의류 전체수량: 1689
- 기증품 품목별 수량 : 자켓/바지/치마/셔츠/타이/벨트/구두/원피스/코트/가방/베스트/기타)
  - 자켓: 530
  - 바지: 561
  - 치마: 88
  - 셔츠: 143
  - 타이: 132
  - 벨트: 19
  - 구두: 54
  - 원피스: 37
  - 코트: 45
  - 가방: 4
  - 베스트: 8
  - 기타: 5
  - 블라우스: 63
- 기증의류 사용 비율 : 열린옷장 사용가능 / 재기증 / 폐기
  - 사용가능: 618
  - 재기증: 999
  - 폐기: 72
- 2023년 기증된 것 중 가장 대여 많이 된 옷 상위 5개 (열린옷장 기증품목 제외)
  - 0E1OD 49회
  - 0E1NZ 47회
  - 0T7YN 40회
  - 0E1NF 36회
  - 0T7WY 33회

2. 편지

- 전체 기증편지 수: 113
- 전체 대여편지 수: 184

3. 대여

- 목적별 대여건수 : 입사면접, 결혼식, 대학(원)면접, 모의면접, 장례식, 졸업/입학식, 세미나/발표, 공연/축제, 사진촬영, 기타
  - 입사면접: 4965
  - 결혼식: 958
  - 대학(원)면접: 117
  - 모의면접: 100
  - 장례식: 242
  - 졸업/입학식: 235
  - 세미나/발표: 344
  - 공연/축제: 347
  - 사진촬영: 346
  - 기타: 312
- 남여별 대여건수 : 남, 여
  - 남: 4836
  - 여: 3137
- 연령비율 : -2005년생까지 (10대) / 2005년생-1996년생 (20대) / 1995년생-1986년생 (30대) / 1985년생-1976년생 (40대) / 1975년생 이후
  - 2005년생까지 (10대): 350
  - 2005년생-1996년생 (20대): 5040
  - 1995년생-1986년생 (30대): 2190
  - 1985년생-1976년생 (40대): 234
  - 1975년생 이후: 154
- 전체 대여 지역별 분포 : 서울특별시, 부산직할시, 인천시, 대전광역시, 세종특별자치시, 경기도, 강원도, 경상남도, 경상북도, 전라남도, 전라북도, 충청남도, 충청북도, 제주도
  - 서울특별시: 5179
  - 부산직할시: 49
  - 인천시: 101
  - 대전광역시: 35
  - 세종특별자치시: 78
  - 경기도: 1899
  - 강원도: 147
  - 경상남도: 41
  - 경상북도: 61
  - 전라남도: 16
  - 전라북도: 117
  - 충청남도: 41
  - 충청북도: 122
  - 제주도: 12
- 택배대여 지역별 분포 : 서울특별시, 부산직할시, 인천시, 대전광역시, 세종특별자치시, 경기도, 강원도, 경상남도, 경상북도, 전라남도, 전라북도, 충청남도, 충청북도, 제주도
  - 서울특별시: 53
  - 부산직할시: 0
  - 인천시: 3
  - 대전광역시: 11
  - 세종특별자치시: 4
  - 경기도: 58
  - 강원도: 7
  - 경상남도: 14
  - 경상북도: 9
  - 전라남도: 5
  - 전라북도: 6
  - 충청남도: 5
  - 충청북도: 9
  - 제주도: 0

**Comment by pingpongworks** [comment]
감사합니다!
