### ISSUE TITLE
2024 연말 뉴스레터 제작을 위한 데이터 요청

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/opencloset#1964]
# 기간 : 2024년 1월 1일 ~ 2024년 12월 5일

[기증 관련]
1. 기증자 수
2. 기증 건수
3. 기증의류 전체수량
4. 기증품 품목별 수량 : 자켓/바지/치마/셔츠/타이/벨트/구두/원피스/코트/가방/베스트/기타
5. 기증의류 사용 비율 : 열린옷장 사용가능 / 재기증 / 폐기

[편지 관련]
1. 전체 기증편지 수
2.  전체 대여편지 수

[대여 관련]
1. 목적별 대여건수 : 입사면접, 결혼식, 대학(원)면접, 모의면접, 장례식, 졸업/입학식, 세미나/발표, 공연/축제, 사진촬영, 기타
2. 남여별 대여건수 : 남, 여
3. 연령별 대여건수 : -2005년생까지 (10대) / 2004년생-1995년생 (20대) / 1994년생-1985년생 (30대) / 1984년생-1974년생 (40대) / 1973년생 이후
4. 지역별 대여자수 : 서울특별시, 부산직할시, 인천시, 대전광역시, 세종특별자치시, 경기도, 강원도, 경상남도, 경상북도, 전라남도, 전라북도, 충청남도, 충청북도, 제주도
5. 택배대여 지역별 대여자수 : 서울특별시, 부산직할시, 인천시, 대전광역시, 세종특별자치시, 경기도, 강원도, 경상남도, 경상북도, 전라남도, 전라북도, 충청남도, 충청북도, 제주도

**Comment by bek9** [comment]
1. 기증

- 기증자 수: 420
- 기증 건수: 429
- 기증의류 전체수량: 3096
- 기증품 품목별 수량 : 자켓/바지/치마/셔츠/타이/벨트/구두/원피스/코트/가방/베스트/기타
  - bag: 15
  - belt: 39
  - blouse: 96
  - coat: 88
  - jacket: 962
  - misc: 26
  - onepiece: 77
  - pants: 1046
  - shirt: 259
  - shoes: 108
  - skirt: 174
  - tie: 192
  - waistcoat: 14
- 기증의류 사용 비율 : 열린옷장 사용가능 / 재기증 / 폐기
  - 대여가능: 629
  - 대여불가: 283
  - 대여중: 51
  - 반납: 20
  - 사용못함: 23
  - 세탁: 1
  - 수선: 28
  - 재활용(비백): 2
  - 재활용(옷캔): 1917
  - 폐기: 140
  - 환불: 2

2. 편지

- 전체 기증편지 수: 205
- 전체 대여편지 수: 353

3. 대여

- 목적별 대여건수 : 입사면접, 결혼식, 대학(원)면접, 모의면접, 장례식, 졸업/입학식, 세미나/발표, 공연/축제, 사진촬영, 기타
  - ?: 56
  - OT: 9
  - 결혼식: 1735
  - 결혼식 축의금: 1
  - 공연(연주회): 68
  - 공연/축제: 541
  - 기타: 585
  - 대학(원)면접: 480
  - 대학원 면접: 1
  - 대학원면접: 1
  - 모의면접: 211
  - 모임: 1
  - 발표: 51
  - 비즈니스: 1
  - 사진촬영: 715
  - 사진촬영(웨딩촬영): 27
  - 상견례: 9
  - 세미나: 43
  - 세미나/발표: 657
  - 아르바이트: 7
  - 인턴면접: 75
  - 입사면접: 9666
  - 장례식: 475
  - 졸업/입학식: 300
  - 졸업식: 87
  - 첫날출근: 1
  - 촬영: 2
  - 축제(행사): 35
  - 학교행사: 1
- 남여별 대여건수 : 남, 여
  - ?: 3
  - 남: 6319
  - 여: 9519
- 연령비율 : -2005년생까지 (10대) / 2004년생-1995년생 (20대) / 1994년생-1985년생 (30대) / 1984년생-1975년생 (40대) / 1974년생 이후
  - 10대: 609
  - 20대: 11352
  - 30대: 3229
  - 40대: 362
  - 50대 이상: 280
- 전체 대여 지역별 분포 : 서울특별시, 부산직할시, 인천시, 대전광역시, 세종특별자치시, 경기도, 강원도, 경상남도, 경상북도, 전라남도, 전라북도, 충청남도, 충청북도, 제주도
  - ?: 9
  - 강원도: 288
  - 경기도: 3818
  - 경상남도: 82
  - 경상북도: 96
  - 광주광역시: 57
  - 대구광역시: 44
  - 대전광역시: 93
  - 부산광역시: 102
  - 서울특별시: 10167
  - 세종특별자치시: 176
  - 울산광역시: 27
  - 인천광역시: 200
  - 전라남도: 40
  - 전라북도: 277
  - 제주특별자치도: 29
  - 충청남도: 84
  - 충청북도: 252
- 택배대여 지역별 분포 : 서울특별시, 부산직할시, 인천시, 대전광역시, 세종특별자치시, 경기도, 강원도, 경상남도, 경상북도, 전라남도, 전라북도, 충청남도, 충청북도, 제주도
  - 강원도: 131
  - 경기도: 548
  - 경상남도: 33
  - 경상북도: 37
  - 광주광역시: 21
  - 대구광역시: 12
  - 대전광역시: 42
  - 부산광역시: 32
  - 서울특별시: 665
  - 세종특별자치시: 128
  - 울산광역시: 10
  - 인천광역시: 50
  - 전라남도: 19
  - 전라북도: 206
  - 제주특별자치도: 2
  - 충청남도: 33
  - 충청북도: 148
