### ISSUE TITLE
옷장지기 계정일 경우 방문 예약시 SMS 인증 과정중 비밀 번호가 변경됨

### ISSUE THREAD

**Issue by keedi** [opencloset/opencloset#199]
현재 방문자는 방문 예약시 SMS 인증 과정을 거치며 이때 임시 비밀번호를 발급받습니다. 문제는 옷장지기 계정으로 테스트를 진행하면 계정의 비밀번호가 SMS 문자 내용으로 바뀌면서 옷장지기가 로그인을 할 수 없는 문제가 발생합니다.

**Comment by aanoaa** [comment]
결국 비밀번호 바꾸라는데 안바꿔서 expired..

**Comment by aanoaa** [comment]
$ echo "`date +%s` + 86400 * 30" | bc
    1424241638

이 결과를 가지고 직접 쿼리로 update 시키면 비밀번호를 바꾸지 않아도 됩니다.
