### ISSUE TITLE
개별 옷을 등록하지 않고 기증행위가 등록이 가능해야 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#211]
현재는 기증행위 등록시 옷이 등록되어야 진행이 가능합니다.
하지만 개별 옷을 넣지 않고도 빈 기증행위가 등록될 수 있어야 합니다.

그 이유는 다음과 같습니다.

1. 직원의 실수로 여러벌의 옷을 다른 기증행위에 넣었을 때, 그 중 한가지 개별의류를 빼내어 다른 기증행위에 옮겨야 하는 경우가 발생할 수 있습니다. 이때 다른 기증행위로 옮기기 위해서는 빈 기증행위가 등록가능해야 합니다. (기증행위 자체를 통채로 옮기는 것은 가능한 상태입니다.)

2. 기증행위에 메세지를 입력하는 작업을 하고 있습니다. 그런데 기증행위가 없는 메세지가 존재합니다. 가령 10벌을 기증했으나 전부다 옷캔으로 재기증되어 실제 프로그램에서는 새옷등록이 이뤄지지 않는 경우가 대표적인 예입니다. 현재 기증메세지를 전부 등록했으나, 메세지만 남은 경우가 100~200 여건에 이르고 있습니다. 메세지를 등록하기 위해서는 개별 옷 등록이 필요없는 기증행위 등록이 필요합니다. :)

**Comment by keedi** [comment]
진행합니다.

**Comment by keedi** [comment]
추가할 옷을 선택하지 않은 경우 다음 단계로 넘어가지 못하도록 검사하는 부분의 코드를 주석처리해서 해결했습니다. 이제 옷 없이도 기증행위 등록이 가능합니다. :)

**Comment by keedi** [comment]
옷 없이 기증 행위 2개를 추가해본 화면입니다.

![- 2015-02-12 14-34-37](https://cloud.githubusercontent.com/assets/138451/6162336/82ca1fa4-b2c4-11e4-97f4-062023a618f9.png)

**Comment by keedi** [comment]
예전의 경우 추가할 옷의 목록이 없거나 선택을 하지 않으면 다음 단계로 넘어가지 않았지만 이제는 다음 버튼을 누르면 기증행위가 등록됩니다.

![- 2015-02-12 14-37-34](https://cloud.githubusercontent.com/assets/138451/6162349/b517deb0-b2c4-11e4-84f0-ea865085d712.png)

**Comment by keedi** [comment]
작업 완료했으므로 이슈 닫습니다.
