### ISSUE TITLE
방문 예약시 SMS 인증 만료 시간을 10분으로 늘림

### ISSUE THREAD

**Issue by keedi** [opencloset/opencloset#244]
현재 방문 예약시 SMS 인증을 수행하는데 SMS 인증 코드는 만료 시간이 5분입니다. 원래 예상했던 기존 만료 시간은 3분이었으나 여유있게 5분으로 설정한 것이었습니다. 하지만 그 당시에 비해 입력해야 할 항목이 많이 늘어나긴 했습니다. @neofu 님의 설명으로는 사람에따라 5분이 약간 간당간당하다는 의견이 있습니다.

문제를 가장 간단하게 해결하기 위해 일단 인증 코드 만료 시간을 10분으로 늘리겠습니다.

**Comment by 10001if** [comment]
오늘 회의시간에 이야기가 나왔는데, 10분이 넘어서 예약을 진행하지 못하는 분들이 하루에 2~3분 정도 꾸준히 발생하고 있다고 합니다. 연장시간을 늘리는 것으로 해결될 문제는 아닌 것 같은데, 어떤 방법이 좋을지 잘 모르겠습니다. 성일님 의견으로는 SMS 인증하기 버튼을 누르면 타이머가 멈추는 방안을 이야기 하셨습니다. 하지만, 로그인이 된다면 문제는 해결될 것 같습니다.. ^^:

**Comment by yongbin** [comment]
원래 본 이슈는 SMS 인증만료시간을 10분으로 늘리는것이었고 이슈에서 원하는 작업은 완료되었습니다. 하지만 이후에도 동일한 문제가 발생하고 그 문제에 대한 구체적인 해결방법은 없기때문에 이슈가 wontfix로 오래동안 묵혀진 상태입니다. @10001if 님과 의논한 결과 이 이슈자체는 닫고. 열린옷장에서 구체적으로 원하는 안이 생기면 별도 이슈를 열어서 진행하기로 했습니다. 본이슈는 해결되었기때문에  wontfix 라벨 제거하고 이슈닫겠습니다.
