### ISSUE TITLE
익스플로어에서 방문 예약 가능 일시 라디오 버튼 선택이 불가함

### ISSUE THREAD

**Issue by keedi** [opencloset/opencloset#245]
익스플로어에서 테스트해본 결과 방문 예약 가능 일시 목록까지는 뜨나 선택했을때 라디오 버튼이 체크되어야 하지만 실제로 선택되지 않는 이슈가 있습니다. 그외에는 모든 동작이 잘 동작하는 것으로 보입니다. 이슈가 많으면 익스플로어를 지원하지 않을 생각도 있었으나 라디오 버튼만 동작하면 될것 같으므로 이 이슈를 우선적으로 해결하도록 합니다.

**Comment by aanoaa** [comment]
이미 낮은 버전의 IE 에서의 예약을 포기했기 때문에 의미가 없습니다.
