### ISSUE TITLE
SMS 서비스 제공사 지원: KTH

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#264]
지금은 CoolSMS 를 사용중인데 건당 20원 입니다.
월정액요금이 있고 더 저렴하게 이용할 수 있다면 마땅히 변경해야 하겠습니다.

http://www.apistore.co.kr/api/apiView.do?service_seq=151
여기는 건당 10.8원 이네요.

**Comment by 10001if** [comment]
KTH에서 제공하는 API 스토어와 계약을 체결하였습니다. :)

**Comment by 10001if** [comment]
sms 발송 이슈가 많아지고 있어서.. 변경을 요청드리고 싶습니다. ^^

**Comment by keedi** [comment]
`SMS::Send::KR::KTH` 모듈을 제작해서 구현할 예정입니다. `SMS::Send::KR::CoolSMS`와 마찬가지로 완성 후 CPAN에 릴리즈한 후 사용하도록 하겠습니다.

**Comment by keedi** [comment]
https://github.com/keedi/SMS-Send-KR-KTH 저장소에서 모듈 제작을 완료한 후 이어서 진행합니다.

**Comment by 10001if** [comment]
따로 키 값을 받은 적은 없는 것 같아요. 메일이나 서류를 확인해봐도 그런건 없었던 것 같습니다. 그냥 등기 보내고 계약만 체결한 상태인 듯 합니다. ^^;

**Comment by keedi** [comment]
전화로 담당자께 문의하셔야 할 것 같습니다. 접속 정보이므로 키 취득 방법을 확인 하신 후에는 따로 말씀해주세요~

**Comment by keedi** [comment]
조금 늦어졌는데 진행합니다.

**Comment by keedi** [comment]
담당자와 문의한 결과 키는 취득했으며, 다만 해당 SMS 전송 기능 API가 HTTP만 제공하는 관계로 고민을 좀 했습니다. 담당자에 따르면 HTTPS는 현재 지원하지 않고 있으며 개발중이며 조만간 지원할 예정이라고 합니다. 하지만 이것이 오래전부터의 이슈였던 것으로 볼 때 언제 HTTPS를 지원할지는 가늠할 수 없는 상태입니다.

HTTP 통신 특성상 전송 내역이 네트워크를 통해 보이는 문제점이 있어 찜찜하지만, 일단은 별 방법이 없으므로 진행하도록 합니다. :-(

**Comment by keedi** [comment]
오늘 중으로 마무리 합니다.

**Comment by keedi** [comment]
sms와 lms 테스트를 진행해본 결과 확인한 내용은 다음과 같습니다.

- sms은 대략 30초 내외로 전송이 완료됨
- lms는 전송까지 최소 1분 이상 소요됨
- sms로 보내더라도 내용이 길면 알아서 lms로 전송됨
- sms로 보냈는데 lms로 변경되어 느린 것이 아니라 처음부터 lms로 지정해도 전송 소요시간이 오래걸림

apistore가 lms의 경우 전송완료 시킬때까지 걸리는 시간이 coolsms와 비교했을 때 상대적으로 꽤 오래 걸리는 것 같습니다. 이점은 참고하도록 합니다.

**Comment by keedi** [comment]
curl을 이용해 sms를 전송 테스트 방법은 다음과 같습니다.

```bash
curl -i \
    --request POST \
    --header 'x-waple-authorization: MjQxxxxxxx==' \
    --data 'send_phone=07043257521&dest_phone=01025116893&msg_body=메시지내용' \
    http://api.openapi.io/ppurio/1/message/sms/<login id>
```

**Comment by keedi** [comment]
curl을 이용해 lms를 전송 테스트하는 방법은 다음과 같습니다.

```bash
curl -i \
    --request POST \
    --header 'x-waple-authorization: MjQxxxxxxx==' \
    --data 'send_phone=07043257521&dest_phone=01025116893&subject=<제목>&msg_body=<내용>' \
    http://api.openapi.io/ppurio/1/message/lms/<login id>
```

**Comment by keedi** [comment]
curl을 이용해 전송 결과를 확인하는 방법은 다음과 같습니다.

```bash
curl -i \
    --request POST \
    --header 'x-waple-authorization: MjQxxxxxxx==' \
    --data 'cmid=<cmid>' \
    http://api.openapi.io/ppurio/1/message/report/<login id>
```

**Comment by keedi** [comment]
오류 코드는 다음과 같습니다.

### SMS

- 4100 전달
- 4421 타임아웃
- 4426 재시도한도초과
- 4425 단말기호처리중
- 4400 음영지역
- 4401 단말기전원꺼짐
- 4402 단말기메시지저장초과
- 4410 잘못된번호
- 4422 단말기일시정지
- 4427 기타단말기문제
- 4405 단말기 busy
- 4423 단말기착신거부
- 4412 착신거절
- 4411 NPDB 에러
- 4428 시스템에러
- 4404 가입자위치정보없음
- 4413 SMSC 형식오류
- 4414 비가입자,결번,서비스정지
- 4424 URL SMS 미지원폰
- 4403 메시지삭제됨
- 4430 스팸
- 4420 기타에러

### MMS

- 6600 전달
- 6601 타임아웃
- 6602 핸드폰호처리중
- 6603 음영지역
- 6604 전원이꺼져있음
- 6605 메시지저장개수초과
- 6606 잘못된번호
- 6607 서비스일시정지
- 6608 기타단말기문제
- 6609 착신거절
- 6610 기타에러
- 6611 통신사의 SMC 형식오류
- 6612 게이트웨이의형식오류
- 6613 서비스불가단말기
- 6614 핸드폰호불가상태
- 6615 SMC 운영자에의해삭제
- 6616 통신사의메시지큐초과
- 6617 통신사의스팸처리
- 6618 공정위의스팸처리
- 6619 게이트웨이의스팸처리
- 6620 발송건수초과
- 6621 메시지의길이초과
- 6622 잘못된번호형식
- 6623 잘못된데이터형식
- 6624 MMS 정보를찾을수없음
- 6670 이미지파일크기제한

### 공통

- 9903 선불사용자 사용금지
- 9904 Block time(날짜제한)
- 9082 발송해제
- 9083 IP 차단
- 9023 Callback error
- 9905 Block time(요일제한)
- 9010 아이디 틀림
- 9011 비밀번호 틀림
- 9012 중복접속량 많음
- 9013 발송시간 지난 데이터
- 9014 시간제한(리포트 수신대기 timeout)
- 9020 Wrong Data Format
- 9021
- 9022 Wrong Data Format(cinfo 가 특수 문자/,공백을 포함하고 있다)
- 9080 Deny User Ack
- 9214 Wrong Phone Num
- 9311 Fax File Not Found
- 9908 PHONE, FAX 선불사용자 제한기능
- 9090 기타에러
- -1 잘못된 데이터 형식 발송오류

**Comment by keedi** [comment]
확인 결과 SMS의 경우 정확히 한글 40글자까지만 허용했으며 그 이후에는 자동으로 LMS로 변경되어 전송합니다. 따라서 euc-kr 기준으로 80바이트까지가 SMS 전송 한계라고 볼 수 있습니다.

**Comment by aanoaa** [comment]
HTTP..

**Comment by keedi** [comment]
@aanoaa ㅇㅇ http ...... ㄷㄷㄷ

**Comment by keedi** [comment]
[SMS::Send::KR::APIStore 0.001 버전](https://metacpan.org/pod/release/KEEDI/SMS-Send-KR-APIStore-0.001/lib/SMS/Send/KR/APIStore.pm)을 릴리스했습니다.

저장소 주소: https://github.com/keedi/SMS-Send-KR-APIStore

**Comment by keedi** [comment]
문자 메시지를 보내는 테스트 코드는 다음과 같습니다.

```perl
#!/usr/bin/env perl

use utf8;
use strict;
use warnings;

use Encode qw( decode_utf8 );
use SMS::Send;

my ( $to, $msg ) = @ARGV;
die "Usage: $0 <to> <msg>\n" unless $to && $msg;

# create the sender object
my $sender = SMS::Send->new('KR::APIStore',
    _id            => '...',
    _api_store_key => '...',
    _from          => '07043257521',
);

# send a message
my $sent = $sender->send_sms(
    text => decode_utf8($msg),
    to   => $to,
);

use DDP; p $sent;
```

**Comment by keedi** [comment]
상기 코드의 경우 터미널에서 입력을 받기 때문에 입력 받은 문자열을 utf8 인코딩으로 디코드할 필요가 있습니다. `use utf8;` 프라그마를 켠 utf8 인코딩으로 되어 있는 소스 코드 내의 한글일 경우 다시 디코드할 필요가 없습니다.

**Comment by keedi** [comment]
[OpenCloset::Schema 0.011 버전](https://cpan.theopencloset.net/STAFF@THEOPENCLOSET.NET/OpenCloset-Config-0.001.tar.gz)을 릴리스했습니다.

저장소 주소: https://github.com/opencloset/OpenCloset-Schema

**Comment by keedi** [comment]
구현을 마무리 짓기 위해 처리해야 할 내역은 다음과 같습니다.

- `OpenCloset::Schema` 모듈의 변경 내역에 맞게 `sms.method`와 `sms.detail` 값을 사용하도록 수정
- `bin/opencloset-sms-notifier.pl` 스크립트가 여러 종류의 SMS 서비스 제공사를 지원할 수 있도록 변경
- 설정 파일 업데이트

**Comment by keedi** [comment]
헥헥 미션 클리어 ;ㅁ;

**Comment by keedi** [comment]
최종 테스트 및 서버에 배포 및 실서버에 대한 테스트까지 완료했습니다.

실서버에 APIStore의 SMS 전송 드라이버를 사용하도록 설정 또한 완료되었습니다.

**Comment by keedi** [comment]
@aanoaa: 다음 항목을 로컬 계정에서 갱신해야 정상 동작 가능합니다. 참고해주세요. :)

- [데이터베이스 스키마 갱신](https://github.com/opencloset/OpenCloset-Schema/issues/24#issuecomment-112803623)
- `OpenCloset::Schema` 0.012 버전 설치: https://cpan.theopencloset.net 미러 사용
- CPAN에서 `SMS::Send::KR::APIStore` 모듈 설치
- 2e36429 커밋의 `app.conf.sample` 파일의 변경 내역 확인 후 실 설정에 적용

**Comment by keedi** [comment]
작업 완료했으므로 이슈 닫습니다. (갑자기 아침에 문자가 안된다거나 하는 일은 없길 바라며;;; )

**Comment by 10001if** [comment]
확인 완료했습니다. 문자는 정말 잘되네요. 감사합니다. :)
