### ISSUE TITLE
익스플로어에서 방문 예약 기능을 비활성화 하고 다른 브라우저 설치를 권유함

### ISSUE THREAD

**Issue by keedi** [opencloset/opencloset#299]
#245 항목에서 언급하고 있지만 익스플로어에서 방문 예약 기능이 제대로 동작하지 않습니다. 따라서 익스플로어에서 정상 동작할 때까지는 막도록 합니다.

현재 @neofu 님이 https://www.theopencloset.net/redirect/ 주소를 이용해서 익스플로어일 경우 다른 브라우저를 설치할 수 있도록 권유하는 페이지를 보여주고 있습니다. 굳이 이렇게 나누지 않고 접속하면 웹앱에서 바로 감지한 다음 다른 브라우저 설치를 권유하는 페이지를 보여주도록 합니다.

**Comment by neofu** [comment]
![2015-01-02 12 06 39](https://cloud.githubusercontent.com/assets/2075180/5594015/dc4faa3e-9277-11e4-9afa-3a4797b28901.png)

오늘자 Windows 8.1 IE 11입니다.

**Comment by aanoaa** [comment]
IE11 에서 예약기능을 사용할 수 있으면 이슈가 닫혀도 될 것 같습니다.
@neofu 확인 좀 해주세요.

**Comment by keedi** [comment]
IE11에서 라디오 버튼 클릭 이 안된다는 것 같네요.

**Comment by keedi** [comment]
진행합니다. IE11에서 되게 하든가 또는 IE11 역시 해당 페이지로 이동하게 하던가 처리하겠습니다.

**Comment by keedi** [comment]
IE11 이상으로 접근 시 현재 열린옷장 방문 예약 페이지 접근이 가능합니다. 그런데 다른 기능은 다 정상 동작하나 방문 예약 일시 선택 시점에 라디오 버튼을 클릭할 수 없는 현상이 존재합니다.  디버깅을 통해 확인해보니 ace 테마가 사용하는 CSS대로라면 IE에서는 라디오 버튼이 눈으로 보이는 것보다 앞에 위치하는 것으로 인지해 클릭이 불가능한 현상이었습니다.  이것이 이상한 것이 다른 페이지에선 상관이 없으나 유독 모달로 띄워 동적으로 생성한 테이블 안의 라디오 버튼일 경우 오동작합니다.  어쨌든 ace 테마의 css를 사용하지 않을 경우 문제없이 클릭이 되는 것을 확인했습니다. 따라서 라디오 버튼의 CSS에서 ace 테마 적용 부분을 제거했으며 이 경우 IE11에서 정상 동작하며 예약에 문제가 없음을 확인 했습니다.

**Comment by keedi** [comment]
IE11에서 방문 일시 모달을 띄운 후 특정 항목을 선택한 화면입니다.

![2015-01-13 17 18 54](https://cloud.githubusercontent.com/assets/138451/5717699/b7f3669c-9b48-11e4-95c6-80e2ba051af3.png)

IE10은 확인해보지 않았으며, 어쨌거나 IE11은 앞으로 동작하는데 큰 이상은 없을 것으로 보입니다.

**Comment by keedi** [comment]
이슈닫습니다. :)
