### ISSUE TITLE
직원전용 예약화면 디자인 오류

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#308]
제 PC 에서만 그런지는 모르겠는데,

![q](https://cloud.githubusercontent.com/assets/170528/5546858/e0244a5a-8b8f-11e4-88f1-212c19d16095.png)

이렇게 보입니다.
확인이 필요합니다.

**Comment by keedi** [comment]
로컬 머신으로 띄운건가요? 아니면 서버에 접속했을 때 인가요?

**Comment by aanoaa** [comment]
음? 지금은 둘다 제대로 보입니다.
이슈 닫겠습니다.
