### ISSUE TITLE
주문서 별 환불 절차 구현

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#314]
반납과 관련하여 전체반납, 부분반납, 전체교체, 부분반납시 

1.환불
2. 재주문

으로 진행하려고 합니다. 이때 기존의 반납 +에누리 형식이 아닌 환불을 위한 독립적인 버튼이 있어야 합니다. 환불과 관련된 프로세스가 추가적으로 필요하며 이때, 환불시 "환불에누리, 환불연체에누리" 항목이 함께 존재해야 할 것으로 보입니다. :)

**Comment by keedi** [comment]
처리한 내역은 다음과 같습니다.

- 대여중 주문서일 경우 '환불 진행' 버튼 추가
- 환불 진행시 환불 금액 입력을 위한 모달 표시
- 환불 금액 및 환불 수수료에 문제가 없을 경우 항목 추가 및 자동 반납처리

**Comment by keedi** [comment]
대여중인 주문서일 경우 하단에 **환불 진행** 버튼이 보입니다.

![- 2015-01-12 16-23-09](https://cloud.githubusercontent.com/assets/138451/5699987/f9ebc14c-9a77-11e4-8802-2e40e461f54e.png)

**Comment by keedi** [comment]
**환불 진행** 버튼을 클릭할 경우 모달을 띄워 환불 금액과 환불 수수료를 입력할 수 있습니다.

![- 2015-01-12 16-23-51](https://cloud.githubusercontent.com/assets/138451/5699994/1c58f2e0-9a78-11e4-8b7d-f4545d6bb0ce.png)

**Comment by keedi** [comment]
모달에서 문제없이 환불을 완료할 경우 주문서에 환불 금액이 추가되며 더불어 모든 의류 품목은 자동으로 반납처리됩니다.

![- 2015-01-12 16-24-48](https://cloud.githubusercontent.com/assets/138451/5700002/347bd54a-9a78-11e4-83cb-f01873701285.png)

**Comment by keedi** [comment]
정리하면 환불 개념에는 부분 환불이라는 개념은 없습니다. 따라서 환불을 하겠다면 전체 환불을 진행합니다. 이후 부분 환불이라면 세부 항목에 대해 별도의 주문서를 만들어서 결제를 진행합니다.

**Comment by keedi** [comment]
작업 완료했으므로 이슈 닫습니다. 피드백을 받은 후 현재 이슈에서 처리할지 또는 별도 이슈에서 처리할지는 피드백 내용에 따라 판단해서 처리하겠습니다.

**Comment by keedi** [comment]
환불 시 주문서에 해당하는 의류 항목을 **반납**이 아닌 **환불** 상태로 표시해달라는 의견이 있었습니다. 수정합니다.

**Comment by keedi** [comment]
처리한 내역은 다음과 같습니다.

- 주문서가 환불될 경우 모든 옷과 주문서의 상태를 환불로 표시
- status 테이블에 환불 상태 추가
- JS 라이브러리에 환불 상태 추가
- 의류 목록 열람시 포장취소 및 환불 상태 열람 가능하게 함
- 의류 상태 열람시 포장취소 및 환불 상태 열람 가능하게 함

실제 데이터베이스에는 다음 질의를 적용합니다.

> INSERT INTO `status` (`id`, `name`) VALUES ('42', '환불');

**Comment by keedi** [comment]
완료했으므로 이슈 닫습니다.
