### ISSUE TITLE
의류의 손상이나 분실시 배상비용을 청구 할 수 있게 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#315]
의류의 손상이나 분실시 배상규정에 따라 5배의 배상비를 지급받습니다.
이때는 반납시 진행되는 절차이므로 반납시 배상비 항목이 추가되어야 합니다.
물론 이때도 에누리가 필요합니다. ^^;

**Comment by keedi** [comment]
처리한 내역은 다음과 같습니다.

- `order.compensation_pay_with` 컬럼 추가
- DBIC 라이브러리 갱신
- 부분 반납이 아닌 전체 반납일 경우에 한해서 배상비 입력이 가능하도록 함
- 최종 연체료는 `order_detail`의 `stage`가 1인 항목의 총합으로 계산함
- 최종 배상비는 `order_detail`의 `stage`가 2인 항목의 총합으로 계산함

**Comment by keedi** [comment]
구현한 화면입니다.

![- 2015-01-06 20-55-23](https://cloud.githubusercontent.com/assets/138451/5628185/1ad9a9d6-95e7-11e4-8ade-ec6c5f8a351d.png)

**Comment by keedi** [comment]
일단 피드백은 필요한데 버그나 이슈가 있으면 별도의 버그를 열어서 처리하겠습니다.

**Comment by keedi** [comment]
이슈 닫습니다.
