### ISSUE TITLE
베스트핏 의류 항목을 의류와 대여자 신체 치수 정보와 함께 표시

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#316]
현재 베스트 핏을 기록하고는 있으나, 베스트 핏을 따로 볼 수 있는 곳이 없습니다.
베스트핏은 세 가지 이유로 중요하다고 생각합니다

1. 사람의 치수와 옷의 치수를 비교하여 가장 최적의 사이즈 차이를 찾기 위함입니다.
2. 베스트 핏이 많이 기록된 의류는 온라인을 통해 사람들에게 자신에게 잘맞을 수 있다는 확실성을 부여하기 위함입니다.
3. 베스트 핏을 많이 기록한 의류를 바탕으로 옷의 사이즈의 최적화된 상태를 파악하고 다른 의류 또한 베스트 핏의 의류 사이즈에 비교하여 수선시 정보로 사용합니다.

이 정보의 경우 대쉬보드에서 보여지는 것이 좋을지 다른 의류 항복에서 보여지는 것이 좋을지 의견을 여쭈어보고 진행하면 좋을 것 같습니다.

**Comment by keedi** [comment]
베스트 핏(어울림)에 대한 정의를 좀 더 명확히 짚고 넘어가야 할 것 같네요.

베스트 핏인 주문서를 보고 싶다는 것인지, 아니면 베스트 핏의 신체 치수 정보를 보고 싶은 것인지 또는 베스트 핏일 경우 빌려간 경우의 옷의 치수를 보고 싶다는 것인지...

여튼 명확하게 같이 정의하고 지나가야 할 것 같습니다. 이것을 정의하지 않은 상태에서는 대시보드에서 보일지 아니면 다른 페이지에서 보일지 고민하는 것은 크게 의미가 없을 것 같습니다. :)

**Comment by 10001if** [comment]
@keedi 좋은 지적이십니다~ ^^ 
베스트 핏의 주문서를 보는 것은 큰 의미가 있다고 보긴 힘들 것 같구요.

1. 베스트 핏의 의류 사이즈 정보를 보고 싶습니다.
- 베스트 핏으로 기록된 의류는 의류의 사이즈가 최적의 상태라는 것을 반증하는 자료이므로 ( 드시 그런 건 아닐 수 있다는 점은 감안하고) 대여 횟수가 많은 베스트 핏의 의류 사이즈를 토대로 수선/의류관리 기본 데이터로 사용하려고 합니다.

2. 베스트 핏의 의류사이즈와 옷을 입은 사람의 신체사이즈를 함께 알고 싶습니다.
- 베스트 핏의 의류 사이즈와 그 옷을 입은 사람의 신체사이즈 차이를 통해 검색에 필요한 정보를 알기 위함입니다. 


![2015-01-23 11 34 19](https://cloud.githubusercontent.com/assets/4696328/5868912/0e5ead04-a2f4-11e4-94d0-3a0ff7446a82.png)

전에 공유해드린 바와 같이 기존에는 이런 방식으로 사이즈를 체크하고 있었습니다.

**Comment by keedi** [comment]
이런 느낌으로 보여줄 수 있도록 구현합니다.

```
+-------------------------------------------------------------+ 
| 상의 의류 코드, 의류 종류, 베스트핏 횟수, 기증자, 옷 사이즈 |
| 하의 의류 코드, 의류 종류, 베스트핏 횟수, 기증자, 옷 사이즈 |
| 대여자 평균 신체 치수                                       |
+-------------------------------------------------------------+ 
| 상의 의류 코드, 의류 종류, 베스트핏 횟수, 기증자, 옷 사이즈 |
| 하의 의류 코드, 의류 종류, 베스트핏 횟수, 기증자, 옷 사이즈 |
| 대여자 평균 신체 치수                                       |
+-------------------------------------------------------------+ 
| 상의 의류 코드, 의류 종류, 베스트핏 횟수, 기증자, 옷 사이즈 |
| 하의 의류 코드, 의류 종류, 베스트핏 횟수, 기증자, 옷 사이즈 |
| 대여자 평균 신체 치수                                       |
+-------------------------------------------------------------+ 
| ...                                                         |
```

**Comment by keedi** [comment]
추가로 대여자 평균 신체 치수 부분을 클릭하면 대여자 전체 목록과 함께 각각의 대여자의 평균 신체 치수를 보여주도록 합니다.

**Comment by keedi** [comment]
여기까지 오늘 미팅에서 논의했으며 확인 받았습니다. :)

**Comment by keedi** [comment]
진행합니다.

**Comment by keedi** [comment]
해당 내용의 양이 많을 것으로 사료되기 때문에 대시보드 형태로 보여주는 것은 무리입니다. 베스트핏 의류 관련 정보를 보여주기 위한 페이지를 별도로 생성합니다.

**Comment by keedi** [comment]
**통계** 메뉴 하부에 **어울림** 페이지를 신설해서 이쪽에서 처리하겠습니다.

![- 2015-02-13 08-08-15](https://cloud.githubusercontent.com/assets/138451/6178960/9a77d13a-b357-11e4-876d-b261b2b8528b.png)

**Comment by yongbin** [comment]
통계텝++

**Comment by keedi** [comment]
구현한 내역은 다음과 같습니다.

- 사이드바 메뉴에 통계와 어울림 항목 추가
- 어울림 통계 페이지 구현

**Comment by keedi** [comment]
구현 완료한 화면은 다음과 같습니다.

![- 2015-02-13 12-55-07](https://cloud.githubusercontent.com/assets/138451/6182065/702e1d0c-b380-11e4-88c8-bd34e9e80915.png)

**Comment by keedi** [comment]
최초 미팅 내역과 비교했을 때 다음과 같은 차이점이 있습니다.

1. 베스트핏 정보는 주문서 별로 존재하기 때문에 주문서 단위로 보여준다면 중복 의류가 보일 수 있습니다. 베스트핏 단위로 보겠다면 어쩔수 없는 사항입니다. 물론 의류별로 통합한 다음 중복을 걸러내서 보일수도 있지만, 이 경우 여자는 혼용이 가능하더라도 남자는 혼용이 불가능하기 때문에 이렇게 보여줄 경우 자료를 읽는 사람이 오해할 여지가 있습니다. 특별히 아이디어가 없다면 그대로 두겠습니다.

2. 하나하나 주문서 마다의 대여자 평균 신체 치수 하부에 실제 사용자의 신체 치수를 보이려고 했으나 변경의 여지가 있을 가능성이 있는데다가, 여자의 경우 의류에 따라 혼용이되고 있기 때문에 실제로 보여줌으로 인해 더 혼란스러울 여지가 있어 보이지 않습니다. 아이디어가 있다면 추가하거나 수정하겠습니다.

3. 대여자 평균 신체 치수를 바로 위의 대여 의류 정보에 나오는 품번 별로 따로 표시했습니다. 이는 여자는 혼용이 가능하고 남자는 혼용이 불가능한데 이로 인해 품번별로 표시하지 않으면 엉뚱한 값으로 평균을 내는 상황이 벌어질 수 있기 때문입니다.

**Comment by keedi** [comment]
작업 완료했으므로 이슈 닫습니다.

**Comment by keedi** [comment]
실서버에 배포도 완료했습니다.

**Comment by keedi** [comment]
해당 페이지에 대해 설명 역시 완료했습니다.
