### ISSUE TITLE
키 몸무게를 기준으로 신체사이즈 확인하기

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#317]
데이터를 누적하여 통계상으로 확인할 수 있어야 하는 정보들이 몇가지 있는데 그 대표적인 것이 키 몸무게를 입력하면 평균적인 사이즈가 나오도록 하는 것입니다.

가령 180cm 72kg인 분이 계시다고 하면요.

온라인으로 신청이 들어오는 상당수의 분들이 사이즈를 정확하게 재지 못하시는 경우가 많습니다.
물론 저희가 사이즈를 정확하게 재실 수 있도록 가이드나 방법에 대해 더 설명을 드려야 겠지만, 그렇게 하더라도 사이즈에 대해 정확도가 저희가 재는 것보다는 상대적으로 떨어질 것이라 생각합니다.

그래서 보내주신 사이즈를 보고 저희가 한번 확인하는 작업을 거치는데요. 과거에는 일일이 질문을 통해 그 답을 찾았습니다. 예컨대, 배가 많이 나오셨나요? 팔이 좀 기신편인가요? 운동 때문에 허벅지가 굵으신가요? 등등 질문을하면서 그분의 몸을 그려나갔는데요. 아무래도 이렇게 하다보니 시간이 너무 오래걸렸습니다.

그래서 앞으로는 키와 몸무게를 입력하면 가슴둘레, 허리둘레, 중동, 팔길이, 다리길이, 허벅지둘레, 엉덩이둘레, 무릎길이 등등 필요한 모든 정보의 평균 사이즈 값을 얻고 싶습니다. (180/72 입력하면 96/84/83/60/100/60/103) 이렇게 추출된 평균값과 입력해주신 사이즈값을 비교하여 평균에서 벗어나는 부위에 대해서만 간략히 질문하고 사이즈를 추론하는 과정을 가지려고 합니다.

그리고 사이즈가 확신이 되면, 그 사이즈를 입력하여 검색된 옷을 온라인으로 발송하려고 합니다. 이렇게되면 자원봉사자도 쉽게 이 일을 할 수 있지 않을까 하는 생각이 듭니다.  :)

이 정보도 첫화면 대쉬보드에서 보여주는 것이 좋을지 여쭤보고 진행하면 좋겠습니다. :)

**Comment by aanoaa** [comment]
키와 몸무게에 오차범위를 두고 (`+-3`) 그 범위 내에서 검색한 평균을
구했습니다.

`180/70` 남자라면 키가 177cm ~ 183cm 이면서 몸무게가 67kg ~ 73kg 인
남자의 사이즈의 평균을 알려주게 되는겁니다.


이 범위내에서 가장 적합하지 않은 사람이라면

- 177/73
- 183/67

이 됩니다.

**Comment by 10001if** [comment]
@aanoaa 혹시 키와 몸무게에 오차범위 없이 178/78을 입력하면 가슴둘레, 중동, 허리둘레, 팔길이, 다리길이, 허벅지둘레, 엉덩이둘레가 평균값으로 나오도록 할 수 있을까요?
![2015-01-21 4 02 16](https://cloud.githubusercontent.com/assets/4696328/5832335/169a3b0a-a187-11e4-95e7-4363bf662b3a.png)
제가 기존에 엑셀로 평균값을 하나씩 쪼개서 넣어보려고 했거든요. :(

**Comment by aanoaa** [comment]
이걸 웹에서 보고 활용 할 수 있으면 좋겠는데 메뉴를 하나 추가할 지 어찌해야 할지 모르겠네요.
일단 스크립트만 추가해놓겠습니다.
@keedi 님이나 @10001if 님의 의견을 듣도록 하겠습니다.

**Comment by aanoaa** [comment]
$ MOJO_CONFIG=app.psgi.conf perl scripts/guess-size.pl male 168 59
    [남][168/59] 중동: 76.1, 가슴: 85.9, 팔: 56.4, 허벅지: 52.8, 허리: 75.9, 다리: 93.9, 발: 248.5
    $ MOJO_CONFIG=app.psgi.conf perl scripts/guess-size.pl female 165 55
    [여][165/55] 중동: 70.6, 가슴: 84.3, 팔: 54.8, 엉덩이: 93.2, 허리: 72.7, 무릎: 52.9, 발: 237.1

**Comment by aanoaa** [comment]
> @aanoaa 혹시 키와 몸무게에 오차범위 없이 178/78을 입력하면 가슴둘레, 중동, 허리둘레, 팔길이, 다리길이, 허벅지둘레, 엉덩이둘레가 평균값으로 나오도록 할 수 있을까요?

네 가능합니다.
다만 꼭 맞는 키와 몸무게를 가진 사용자를 찾을 수 없으면 결과를 볼 수 없습니다.

**Comment by aanoaa** [comment]
$ OPENCLOSET_RANGE_OF_ERROR=0 MOJO_CONFIG=app.psgi.conf perl scripts/guess-size.pl male 168 59
    [남][168/59] 중동: 72.0, 가슴: 85.0, 팔: 60.0, 허벅지: 53.0, 허리: 75.0, 다리: 98.0, 발: 250.0
    $ MOJO_CONFIG=app.psgi.conf perl scripts/guess-size.pl male 168 59
    [남][168/59] 중동: 76.1, 가슴: 85.9, 팔: 56.4, 허벅지: 52.8, 허리: 75.9, 다리: 93.9, 발: 248.5

**Comment by aanoaa** [comment]
저런 표가 필요하신 건가요?
데이터가 쌓일 수록 신뢰도가 높아지겠지만
지금 쌓인 데이터만으로도 저 표를 완성시킬 수 는 있습니다.

저런 표만 한개 있으면 직접 검색할 필요도 없겠네요.

**Comment by yongbin** [comment]
> 제가 기존에 엑셀로 평균값을 하나씩 쪼개서 넣어보려고 했거든요. :(

키와, 몸무게를 x축으로 옮기면 표 하나로 원하시는 평균값을 한눈에 볼수 있는 형태를 만들수 있을꺼 같습니다. 시험으로 만들어본 표는 아래와 같습니다. XLS 버전은 제가 가지고 있습니다. 필요하면 보내드리겠습니다. 

# 남성

![screenshot 2015-01-22 11 20 53](https://cloud.githubusercontent.com/assets/52704/5849420/cfecca0e-a228-11e4-8c61-91c9f662d1b1.png)

# 여성

![screenshot 2015-01-22 11 21 07](https://cloud.githubusercontent.com/assets/52704/5849421/d24974d2-a228-11e4-89ed-43c4e56a866a.png)

보이는것 처럼 오픈이후 누적된 자료를 기준으로 하기떄문에 치수별로 측정값이 아직 1~4 번 미만이거나 없는경우도 있습니다. 측정값이 적거나 없다면 근처에 있는 값을 참고하면 되며 누적값이 많아진다면 해결될꺼 같습니다.

위 표를 작성하는에 사용한 SQL 쿼리는 다음과 같습니다.

```SQL
SELECT
	c.`gender` AS `성별`
	,a.`height` AS `키`
	,a.`weight` AS `몸무게`
	,COUNT(*)   AS `측정값 수`
	,AVG(a.`bust`) AS `평균 가슴둘레`
	,AVG(a.`waist`) AS `평균 허리둘레`
	,AVG(a.`hip`) AS `평균 엉덩이둘레`
	,AVG(a.`belly`) AS `평균 중동`
	,AVG(a.`arm`) AS `평균 팔길이`
	,AVG(a.`thigh`) AS `평균 허벅지 둘레`
	,AVG(a.`leg`) AS `평균 다리길이`
FROM `order` AS a
	INNER JOIN `user` AS b ON a.`user_id` = b.`id`
	INNER JOIN `user_info` AS c ON b.`id` = c.`user_id`
GROUP BY c.`gender`,a.`height`,a.`weight`
HAVING c.gender ='female'
```

**Comment by aanoaa** [comment]
현재 데이터를 기반으로 남성,여성의 신체치수표를 만들었습니다.

```perl
#!/usr/bin/env perl
use utf8;
use strict;
use warnings;

use open ':std', ':encoding(utf8)';

use Class::CSV;

use OpenCloset::Schema;
use OpenCloset::Util;

$ENV{OPENCLOSET_RANGE_OF_ERROR} = 0;

use OpenCloset::Size::Guess;

my $CONF
    = OpenCloset::Util::load_config( $ENV{MOJO_CONFIG} || 'app.psgi.conf' );
my $schema = OpenCloset::Schema->connect(
    {
        dsn      => $CONF->{database}{dsn},
        user     => $CONF->{database}{user},
        password => $CONF->{database}{pass},
        %{ $CONF->{database}{opts} },
    }
);

my $guess = OpenCloset::Size::Guess->new(
    schema => $schema,
    gender => 'female',
    height => 0,
    weight => 0
);

my @height = ( 140 .. 200 );
my @weight = ( 40 .. 200 );

my $csv
    = Class::CSV->new( fields => ['weight', @height], line_separator => "\n",
    );
$csv->add_line( ['weight', @height] );

for my $weight (@weight) {
    my @line;
    $guess->weight($weight);
    for my $height (@height) {
        $guess->height($height);
        my $size = $guess->belly ? "$guess" : '';
        if ($size) {
            $size = substr $size, 3;
            $size =~ s/[ㄱ-힣: ]//g;
            $size =~ s/,/ \/ /g;
            $size =~ s/]/] /g;
        }
        push @line, $size;
    }
    $csv->add_line( [$weight, @line] );
}

$csv->print();
```

    ~/repo/opencloset/opencloset $ OPENCLOSET_RANGE_OF_ERROR=0 MOJO_CONFIG=app.psgi.conf perl a.pl > male.csv
    ~/repo/opencloset/opencloset $ OPENCLOSET_RANGE_OF_ERROR=0 MOJO_CONFIG=app.psgi.conf perl a.pl > female.csv

**Comment by aanoaa** [comment]
https://github.com/opencloset/opencloset/blob/%23317-size-guess/csv/male.csv
https://github.com/opencloset/opencloset/blob/%23317-size-guess/csv/female.csv

여기서 확인할 수 있습니다.
github 이 짱이라서 검색도 됩니다.

따로 파일로 가지고 있지 않아도 됩니다.

**Comment by yongbin** [comment]
이 이슈는 기존에 축적된 자료의 누적된 값을 이용해서 키와 몸무게별 각 사이즈 매트릭스를 만들어내는 **통계** 이슈인지, 아니면 `치수측정`에서 측정된 키와 몸무게를 이용해서 시스템적으로 `의류준비`과정에 도움이될 정보를 제공하는것인지를 먼저 확인해야합니다. 만약 후자라면, @aanoaa 님께서 이미 처리해주신 #376 PR을 기반으로 진행이 가능하고, 전자라면 기존에 진행했던 통계이슈들과 유사한 방식으로 진행되어야 합니다. (둘 다 일수도 있습니다)

@keedi 한대표님과 미팅때 그 부분을 확인해서 업데이트 해주셨으면 하는 의미에서 '확인요망' 라벨을 부착합니다. 부탁드립니다 ;-)

**Comment by aanoaa** [comment]
이게 전화로 예약하는 사람들의 키와 몸무게만 듣고 사이즈표를 참고해서 적절한 의상을 추천해드리려고 하는거라고 얘길 들었습니다.

**Comment by keedi** [comment]
미팅 완료했으며 필요한 기능을 최종 확인했습니다.

사이트에 키와 몸무게를 입력하면 평균 신체 치수를 보여주고 10명 정도 실데이터를 같이 보여주기로 했습니다.

**Comment by aanoaa** [comment]
메뉴의 어디에 들어갈지 정해주시고 어떻게 보여져야 할지 알려주시면 제가 작업할 수 있습니다.

**Comment by 10001if** [comment]
@aanoaa 키디님께 말씀드렸습니다. :)

**Comment by aanoaa** [comment]
`2015-02-01` ~ 현재까지를 기준으로 데이터를 갱신한 csv 파일을 맨들어야 합니다.

**Comment by aanoaa** [comment]
주문서를 기준으로 통계를 내야 합니다.
주문서에 신체치수가 기록되어 있습니다.

**Comment by aanoaa** [comment]
온라인 대여의 주문서는 예약시간은 19:00 입니다.
5/29 일 이후로 주문서의 예약시간은 22:00 입니다.

이걸 고려해서 데이터를 뽑아야 합니다.

**Comment by aanoaa** [comment]
SELECT blah
    FROM booking
    JOIN blah...
    WHERE DATE_FORMAT(`booking.date`,'%H') < 19

이런식의 쿼리를 맨들어야 하는데 DBIx::Class 에서는 좀 어렵습니다(혹은 불가능).
DBI 를 가지고 raw 쿼리를 만들어야 할 것 같습니다.

**Comment by aanoaa** [comment]
5/29 이전과 이후의 데이터에 차이가 좀 많이 나는 게 있습니다.
치수 측정이 잘못 된 것 같은데 분석이 필요할 것 같습니다.

    $ perl scripts/guess-size.pl male 168 57
    belly data looks wrong: 72.6 < 5/29, 58.8 > 5/29
    [남][168/57] 중동: 65.7, 가슴: 86.5, 팔: 57.7, 허벅지: 51.3, 허리: 76.4, 다리: 96.7, 발: 251.0

**Comment by aanoaa** [comment]
딱맞아 떨어지는 이력이 없을때, 범위 오차에 따른 걸로 보입니다.
위에서 말했듯이 지금은 기본 오차 값이 `3` 입니다.

`168/57` 은 `165~171/54~60` 의 사이즈 평균 값을 구합니다.

범위가 없으면 정확한 치수에 대한 이력이 적기 때문입니다.

    $ OPENCLOSET_RANGE_OF_ERROR=0 perl scripts/guess-size.pl male 168 57
    [남][168/57] 중동: 0.0, 가슴: 83.5, 팔: 60.0, 허벅지: 51.0, 허리: 75.5, 다리: 96.5, 발: 247.5

**Comment by aanoaa** [comment]
> 5/29 이전과 이후의 데이터에 차이가 좀 많이 나는 게 있습니다.
> 치수 측정이 잘못 된 것 같은데 분석이 필요할 것 같습니다.

몇건인지 주문서를 뽑아서 직접 확인해보는 방법이 있겠습니다.

**Comment by aanoaa** [comment]
더 정확한 데이터를 뽑기 위해서 오차범위를 1로 줄였습니다.

**Comment by aanoaa** [comment]
구해야할 키/몸무게별 사이즈의 범위로는

- 남자
  - 키 150cm ~ 200cm
  - 몸무게 40kg ~ 160kg
- 여자
  - 키 140cm ~ 200cm
  - 몸무게 30kg ~ 100kg

**Comment by aanoaa** [comment]
https://github.com/opencloset/opencloset/blob/%23317-size-guess/csv/male.2015.06.29.csv
https://github.com/opencloset/opencloset/blob/%23317-size-guess/csv/female.2015.06.29.csv

@10001if 뽑아보았습니다.

**Comment by aanoaa** [comment]
남자는 중동, 가슴, 팔, 허벅지, 허리, 다리, 발
여자는 중동, 가슴, 팔, 엉덩이, 허리, 무릎, 발

입니다.

**Comment by aanoaa** [comment]
> 메뉴의 어디에 들어갈지 정해주시고 어떻게 보여져야 할지 알려주시면 제가 작업할 수 있습니다.

적당히 메뉴하나 맨들고 거기에 키와 몸무게를 입력하면 위아래 양옆 사이즈까지 9개의 2차원 테이블로 보여주면 되겠습니다.
`151/61` 을 검색하면 아래와 같이 보여주는 겁니다.

    150/60 151/60 152/60
    150/61 151/61 152/61
    150/62 151/62 152/62

**Comment by aanoaa** [comment]
![screenshot-localhost 5001 2015-07-06 14-37-04](https://cloud.githubusercontent.com/assets/170528/8516241/88dd1df8-23ec-11e5-85d9-aebd2bf62235.png)

이런거 어떤가요?

**Comment by aanoaa** [comment]
여기에 bodylabs 를 활용해서 같이 보여주거나 할 수 있습니다.

**Comment by 10001if** [comment]
와! 감사합니다. 추후에 body labs가 추가로 들어갈 수 있다니 더 좋을 것 같습니다. ^^

**Comment by aanoaa** [comment]
uh.. bodylabs 는 대표님이 결제 해서 API key 를 얻어와야 할 수 있는거고요,
신체치수 예측을 어떻게 할지는 아이디어가 없었기 때문에 제가 임의로 한건데 어떠신지 의견이 궁금합니다.

**Comment by aanoaa** [comment]
남녀 선택해서 보여줄 수 있으면 좋겠다고 합니다.

**Comment by aanoaa** [comment]
몇건의 평균인지에 대해 나타내면 좋겠습니다.

**Comment by aanoaa** [comment]
남자의 경우 중동과 윗배를 같이 보여줘야 합니다.

**Comment by keedi** [comment]
#524에서 언급한 대로 @yongbin 님이 온라인 여부를 판단하는 컬럼을 넣게 되면 본 이슈는 물론 전체적으로 온라인 여부를 시간이 아닌 해당 컬럼을 기준으로 판단해야 합니다. 일단 현재 PR에는 적용되어 있습니다.

**Comment by keedi** [comment]
머지 완료되었으며 배포 진행합니다.

**Comment by keedi** [comment]
배포 완료했습니다.

**Comment by keedi** [comment]
최종 결과 화면은 다음과 같습니다.

![screenshot-monster silex kr 10301 2015-08-03 13-50-27](https://cloud.githubusercontent.com/assets/138451/9031358/04e0440a-39ed-11e5-8c52-3d8d94670228.png)

**Comment by keedi** [comment]
작업 완료했으므로 이슈 닫습니다.

**Comment by aanoaa** [comment]
엉덩이 사이즈도 보여져야 합니다.

**Comment by aanoaa** [comment]
키와 몸무게의 편차를 `+-1` 로 해서 보여져야 합니다.

요런식으로..

![oops](https://cloud.githubusercontent.com/assets/170528/8666844/f2c46bfe-2a31-11e5-8fb1-3011630296ee.png)

정확하지 않은 데이터가 많아서 위아래 사이즈를 같이 비교해보려고 합니다.

**Comment by keedi** [comment]
확인 결과 요구사항은 다음과 같습니다.

- 남녀 구분없이 엉덩이 치수도 보여야 함
- 172cm / 72kg 라고 하면 171~173cm, 71~73kg 범위에 해당하는 사람의 평균이 아닌 정말 172cm, 72kg인 사람의 평균을 원함
- 172cm / 72kg 평균을 보여줄때 171~173 / 71~72 사이의 평균 즉 9개를 모두 보기를 원함
- 이때 9개의 평균을 보여줄 때는 몇 개의 평균인지는 표시하지 않아도 된다고 함

**Comment by keedi** [comment]
배포 완료했습니다. 이슈 닫습니다.

**Comment by 10001if** [comment]
확인 완료하였습니다. 감사합니다.
