### ISSUE TITLE
전체 의류에 대한 사이즈별/품목별/수량별 정보 확인이 필요함

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#319]
이 내용도 대쉬보드에 들어가는게 맞는지 확인 후 진행해야 할 것 같습니다.

현재 열린옷장에는 2000점의 의류/잡화가 있습니다.
하지만 현재는 품목별로 몇 벌의 자켓이 있는지 바지가 있는지 확인이 되지 않습니다.

1. 보유하고 있는 전체 중 품목별 수량이 확인가능해야 할 것 같습니다.
2. 그리고 전체 의류 중에서 대여 중인 품목이 얼마나인지 수량으로 확인히 가능해야 할 것 같습니다.  
3. 더불어 전체의류/대여의류 모두 사이즈별 분류가 가능해야 할 것 같습니다.

사이즈 구간별로 나눠진 상태에서 보유하고 있는 품목별 의류 / 사이즈 구간별로 나눠진 상태에서 "대여중" 의류 / 수선 중 의류 / 세탁 중 의류의 수량을 확인하고 싶습니다.

이렇게 되면 전체 보유량 중에 사이즈별 구분이 가능하고, 대여중인 의류의 수량을 차감하면 지금시점에서 보유 중인 의류 수를 확인할 수 있고, 이는 열린옷장이 보유해야할 사이즈별 수량을 알려주므로 수선/기증에 더 확실한 도움을 줄 수 있지 않을까 생각하고 있습니다. 

더불어 사이즈별 대여비율을 알게된다면 사이즈별 보유해야 하는 보유비율의 추정이 가능해지므로 항상 적정 재고(?) 유지가 가능해지며 그에따라 대여인원의 관리도 더 원활하게 운영될 수 있을 것 같습니다. :)

**Comment by keedi** [comment]
@aanoaa #316 이슈와 유사하게 처리해주시면 될 것 같습니다. 통계 메뉴가 신설 되었으니 하부 페이지로 빼고 그 페이지 안에서 보여주는 것이 이상적이리라 생각됩니다. #리뷰후머지

**Comment by aanoaa** [comment]
### 품목별 수량 ###

품목 | 수량 | 대여중
-----|------|-------
쟈켓 | 200  |   50
셔츠 | 250  |   40
...  | ...  |   ...

에서 각 품목을 누르면 아래 내용이 보여지면 어떨까 합니다.

### 상태별 수량 ###

**셔츠**

사이즈 | 수량 | 대여중 | 수선중 | 세탁중
------:|-----:|------:|-------:|------:
    90 |  250 |    40 |     10 |    30

**Comment by aanoaa** [comment]
두개의 routes 를 추가 합니다.

- `GET /stat/clothes/amount`
- `GET /stat/clothes/amount/category/:category`

**Comment by yongbin** [comment]
@aanoaa 이 이슈에서 정리해주신 품목별 수량과 상태별 수량이외에 `3. 더불어 전체의류/대여의류 모두 사이즈별 분류가 가능해야 할 것 같습니다.` 도 처리가 되어야 합니다. 사이즈별 분류시 기준이 되는 **구간**에 대한 논의는 #375에 있는 내용을 참고하시면 됩니다.

**Comment by yongbin** [comment]
13일에 @10001if 님과 확인한 결과 #319 이슈와 #375 이슈는 동일하기 때문에 #319쪽에서 진행되도록 #375번을 닫겠습니다.

**Comment by aanoaa** [comment]
사이즈별 수량도 고려하고 있습니다.
제 코멘트의 두번째 테이블을 보시면 되겠습니다.

**Comment by yongbin** [comment]
> 사이즈별 수량도 고려하고 있습니다.
> 제 코멘트의 두번째 테이블을 보시면 되겠습니다.

#375가 저한테 할당되어 있었기 때문에 인계차원에서 말씀드렸습니다. 그러면 저 **90**이 중동 + 팔길이 값이신거죠??

**Comment by aanoaa** [comment]
>  사이즈별 분류시 기준이 되는 구간에 대한 논의

는 아래 링크인가요?

https://github.com/opencloset/opencloset/issues/375#issuecomment-72787342

> 우선 표로 표현하는 방법을 논의했습니다.
> 
> 남자의 경우 다음과 같습니다.
> 
> - 상의: 중동+팔길이
> - 하의: 허리+허벅지
> 
> 여자의 경우 다음과 같습니다.
> 
> - 상의: 중동+팔길이
> - 하의: 허리+엉덩이

이걸로는 부족합니다.

예를들어 셔츠를 사이즈별로 분류한다 라고 했을때 중동사이즈 분류와
가슴사이즈 분류가 있을 수 있습니다.

각 품목별 사이즈의 기준이 필요합니다.

일반적으로 상의는 가슴, 하의는 허리 입니다.

품목 | 기준
-----|-----
벨트 | 없음
블라우스 | 가슴둘레
코트 | 가슴둘레
자켓 | 가슴둘레
원피스 | 모르겠음
팬츠 | 허리둘레
셔츠 | 가슴둘레
슈즈 | 발크기
스커트 | 허리둘레
타이 | 없음
조끼 | 가슴둘레

@10001if 위 표에서 변경하고 싶은 혹은 잘못된 기준을 말씀해주세요

**Comment by aanoaa** [comment]
> #375 가 저한테 할당되어 있었기 때문에 인계차원에서 말씀드렸습니다. 그러면 저 90이 중동 + 팔길이 값이신거죠??

음 아닙니다. 바로위의 코멘트를 참고해주세요.

**Comment by yongbin** [comment]
> 음 아닙니다. 바로위의 코멘트를 참고해주세요.

넵 @10001if 님과 정리하시면 될것 같습니다.

**Comment by keedi** [comment]
PR 확인 진행합니다.

**Comment by keedi** [comment]
진행합니다.

**Comment by keedi** [comment]
확인 완료했습니다. 기존 PR에 추가적으로 진행한 사항은 다음과 같습니다.

- 코딩 스타일 수정
- CSS 추가

**Comment by keedi** [comment]
작업 완료했으므로 이슈 닫습니다.

**Comment by keedi** [comment]
배포 완료했습니다. 피드백만 확인하면 됩니다. :)

**Comment by keedi** [comment]
확인  완료했습니다. :)
