### ISSUE TITLE
주문서에 택배 운송장 번호를 저장할 수 있어야 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#330]
방문대여나 온라인 대여 모두 택배 반납이 가능합니다.
현재는 택배 발송 기준으로 대여기간을 정하고 있습니다. 
택배 도착여부는 개인이 관리할 수 없는 문제이기 대문입니다.

때문에 개인이 택배 반납을 원할 경우 그에 대해 설명을 드리고 반납시 택배회사와 운송장번호를 SMS로 보내도록 하고 있습니다. SMS를 받아 따로 정리하는 것은 아니며, 형식적으로 운영하기 위한 방법 중 하나였습니다. (이렇게 하면 반납에 관한 강제성 내지는 압박감 등이 생길 수 있을 것이라는 느낌적인 느낌이 들었습니다..)

하지만 앞으로는 조금 체계적으로 관리해야겠다는 생각이 들었습니다. 반납과 관련한 이슈가 계속 발생하고 있기 때문인데요. 그래서 택배 운송장번호가 SMS 오면 주문서에 그 내용을 입력할 수 있는 항목이 필요하다고 보여집니다. 가능하다면 삽입한 운송장번호를 클릭하면 현재 위치가 나오는 (배송사에서 제공한 페이지) 곳으로 이동하여 위치 정보를 확인 할 수 있다면 더 좋을 것 같습니다.

**Comment by aanoaa** [comment]
이쯤에 운송장번호를 입력할 수 있도록 하려고 합니다.

간단히 알아봤을때 배송조회가 되는 서비스들은 아래가 있습니다.
해서 택배사를 선택하고 운송장번호를 입력할 수 있도록 하겠습니다.
`배송조회` 를 누르면 해당 서비스로 직접 이동하도록 하려고 합니다.

- CJ
- DHL
- Fedex
- KGB
- UPS
- 경동
- 동부
- 로젠
- 옐로우캡
- 우체국
- 한진
- 현대
- 기타(etc)

![- 2015-01-12 13-34-41](https://cloud.githubusercontent.com/assets/170528/5699032/6e02e0aa-9a60-11e4-9450-1401cb17c75a.png)

**Comment by aanoaa** [comment]
택배회사명을 선택하게 하고 운송장 번호를 넣게끔 하려고 했는데,, js lib 인 x-editable 을 커스텀해서 사용해야 합니다.

http://vitalets.github.io/x-editable/demo-bs3.html

에 샘플이 있습니다.

**Comment by keedi** [comment]
상기 내역대로 변경하기 위해 요청할 질의 내역은 다음과 같습니다. 일단 테스트 서버에서만 확인했습니다.

```sql
UPDATE `order`
  SET
    `status_id`='9',
    `return_date`='2014-12-23 23:59:59',
    `return_method`='직접방문',
    `late_fee_pay_with`=''
  WHERE `id`='189';

UPDATE `order_detail` SET `status_id`='9' WHERE `id`='398';
UPDATE `order_detail` SET `status_id`='9' WHERE `id`='399';
UPDATE `order_detail` SET `status_id`='9' WHERE `id`='400';
UPDATE `order_detail` SET `status_id`='9' WHERE `id`='401';
UPDATE `order_detail` SET `status_id`='9' WHERE `id`='402';
UPDATE `order_detail` SET `status_id`='9' WHERE `id`='403';
```

**Comment by keedi** [comment]
커스텀 안하고도 가능할 것 같은데요. 커스텀 저거 손 가는 코드가 많아서...

일단 궁금한 부분은 db 테이블 및 컬럼은 어떤 것을 사용하실 것인지요?

**Comment by keedi** [comment]
현재 `/user/:id` 쪽의 대여 희망 품목과 대여 희망 색상의 경우 커스텀까지는 아니고 아마 힌트될만한 부분이 있을 것이라고 사료되는데요. `$(el).editable params`에서 `params.display`와 `params.url`만 잘 손 보시면 택배 회사명과 운송장 번호를 따로 xeditable 2 요소로 표시한 후 둘 다 입력이 끝난 시점에 웹으로 자료를 전송할 수 있습니다. 아마 그 편이 데모의 커스텀하는 코드보다 손이 덜 가실 겁니다.

**Comment by keedi** [comment]
제가 사용했던 코드는 이런 식이었습니다.

```coffee
params.type    = 'select2'
params.source  = ( { id: i, text: OpenCloset.color[i] } for i in [ 'staff', 'dark', 'black', 'navy', 'charcoalgray', 'gray', 'brown', 'etc' ] )
params.select2 =
  width:                250
  placeholder:          '희망 색상을 선택해주세요.'
  allowClear:           true
  multiple:             true
  maximumSelectionSize: 3
params.display = (value, sourceData) ->
  unless value
    $(this).empty()
    return
  mapped_values = []
  for i in value
    item = OpenCloset.color[i]
    continue unless item
    str = item.replace /^\s+|\s+$/, ""
    continue if str is ''
    mapped_values.push str
  $(this).html mapped_values.join(',')
params.url = (params) ->
  url = $('#profile-user-info-data').data('url')
  data = {}
  data[params.name] = params.value.join(',')
  $.ajax url,
    type: 'PUT'
    data: data
$(el).editable params
```

**Comment by aanoaa** [comment]
헉 감사합니다.
제가 필요로하던 부분 같네요.

schema 는 0cfedf8 와 같이 변경하고자 합니다.

**Comment by keedi** [comment]
이미 예전 데이터베이스 설계하실 때 택배를 고려하셨는지, `order.return_method`라는 항목을 넣으셨었던데, 스키마 변경없이 이 항목을 그대로 이용하는 것은 어떨까요? 아마 현재 32글자라서 길이는 더 확보해야 할 수는 있겠습니다만.

**Comment by keedi** [comment]
`옐로우캡,12345678901234` 이런 식으로 저장되어도 충분할 것 같은데 어찌 생각하시는지요? 일단은 현재 UI에서 반납은 모두 `직접방문` 이라는 문자열을 해당 컬럼에 저장하는 방식을 이용하고 있습니다.

**Comment by aanoaa** [comment]
안바꾸면 더 편하겠지만, 택배서비스 마다 운송장 번호로 화물 조회하는 URL 이 있는데
이를 활용하려면 schema 를 변경하는게 유리하겠습니다.

운송장번호를 누르면(있다면) 조회하는 곳으로 이동하고 싶어합니다.

**Comment by keedi** [comment]
음 그러면 여전히 질문 3가지 더 드립니다.

- `SMS::Send::*` 류의 모듈처럼 `Parcel::KR::*` 모듈이 있어서 `Parcel::KR::YellowCap->new( '운송장번호' )->url`과 같은 식으로 처리하는 것은 어떻게 생각하시는지요? 물론 `Parcel::KR::*`를 종류 별로 다 만들고 나면 `Parcel::KR->new( 'YellowCap', '운송장번호' )->url`도 가능하겠죠.
- 상기 방식이 ok라면 스키마 변경이 굳이 필요하겠는가?
- 추가로 기존에 만드셨던 `order.return_method`는 어떤 식 및 용도로 사용하실 것인지요?

**Comment by aanoaa** [comment]
- 각 모듈별로 만들면 제가 귀찮겠지요.
- 이 프로젝트는 @keedi 님 원하는 방향으로 가는게 옳다고
  생각합니다. 스키마 변경을 원하지 않으신다면 모듈을 추가하겠습니다.
- 단순하게 `반납방법` 을 나타내는 용도였습니다. 택배반납 혹은 방문반납

**Comment by keedi** [comment]
귀찮음을 감수해주신다면 미리 고맙습니다. =3 일단 열린옷장에서 공식적으로 사용하는 택배 종류가 제가 알기론 현재 하나 뿐이니 모두 만들 필요는 없고, 해당 택배 종류가 무엇인지 @10001if 님께 확인해 하나만 구현하면 될 것 같습니다.

**Comment by yongbin** [comment]
대표님께 문자로 여쭤봤습니다. 보내는 택배는 `CJ 대한통운`만 사용하신다고 합니다.

**Comment by aanoaa** [comment]
옷종류를 여러개 선택하는 것과는 다릅니다.
택배사를 선택하고(select), 운송장번호(text)를 입력해야 합니다.

custom 이 필요할 것 같습니다.

**Comment by keedi** [comment]
방금 이야기 들었는데 두 가지를 사용한다고 합니다.

- CJ 대한통운
- 우체국

**Comment by aanoaa** [comment]
![- 2015-01-20 16-24-28](https://cloud.githubusercontent.com/assets/170528/5813460/f40b6db4-a0c0-11e4-9dec-8c261cc32dc5.png)
![- 2015-01-20 16-24-06](https://cloud.githubusercontent.com/assets/170528/5813458/f17f8b34-a0c0-11e4-9752-70345b39c0ad.png)

**Comment by keedi** [comment]
코드 리뷰 후 머지하겠습니다.

진행합니다.

**Comment by keedi** [comment]
택배 관련 모듈 몇 가지를 정리하고 CPAN에 올리느라 조금 지체되었습니다. 관련해서 마저 진행합니다.

**Comment by keedi** [comment]
제작해 업로드한 모듈은 다음과 같습니다.

- [Parcel::Track](https://metacpan.org/pod/Parcel::Track) - Driver-based API for tracking parcel
- [Parcel::Track::KR::CJKorea](https://metacpan.org/pod/Parcel::Track::KR::CJKorea) - Parcel::Track driver for the CJ Korea Express (CJ 대한통운)
- [Parcel::Track::KR::Dongbu](https://metacpan.org/pod/Parcel::Track::KR::Dongbu) - Parcel::Track driver for the KG Dongbu Express (KG 동부택배)
- [Parcel::Track::KR::Hanjin](https://metacpan.org/pod/Parcel::Track::KR::Hanjin) - Parcel::Track driver for the Hanjin (한진택배)
- [Parcel::Track::KR::KGB](https://metacpan.org/pod/Parcel::Track::KR::KGB) - Parcel::Track driver for the KGB LOGIS
- [Parcel::Track::KR::PostOffice](https://metacpan.org/pod/Parcel::Track::KR::PostOffice) - Parcel::Track driver for the ePOST Korea (우체국)
- [Parcel::Track::KR::Yellowcap](https://metacpan.org/pod/Parcel::Track::KR::Yellowcap) - Parcel::Track driver for the Yellowcap (옐로우캡택배)

[Parcel::Track](https://metacpan.org/pod/Parcel::Track) 모듈은 [SMS::Send](https://metacpan.org/pod/SMS::Send) 모듈과 비슷하게 각 드라이버별 공통 API를 제공하는 모듈입니다.  현재 구현한 드라이버는 여섯 개이며 이는 주변 지인을 통해 확인할 수 있는 운송장 번호를 기준으로 작업한 것입니다.  추후 이외의 운송장 번호를 더 확보하면 그때 추가로 드라이버를 제작하도록 합니다.

waybill 가지에서 `OpenCloset::Parcel::*`로 제작한 모듈을 상기 모듈로 대체하는 작업을 진행합니다.

**Comment by keedi** [comment]
기존 브랜치에서 다음 작업을 추가로 더 수행했습니다.

- Parcel::Track::KR::* 모듈로 대체
- `public/lib/x-editable/inputs/waybill.js` 파일을 `coffee/returnmethod.coffee` 파일로 대체
- 반납 시점에만 값을 변경할 수 있도록 함 (열린옷장의 요구사항에 따라 수정의 여지가 있음)

**Comment by keedi** [comment]
추가로 테스트 코드도 같이 제거했습니다.

실 서버 배포해야 하나 현재 서비스를 사용중이므로 오늘 저녁, 방문객의 예약 방문이 모두 종료되면 그 시점에 반영하겠습니다.

일단 이슈 닫습니다.

**Comment by keedi** [comment]
택배 운송장 번호 입력은 반납 시점과 상관없이 입력이 가능해야 한다고 합니다. 왜냐하면 운송장 번호를 알려주는 시점에는 실제로 물품이 배송중이고 그 상태에서는 반납 처리를 할 수 없기 때문입니다. @aanoaa 님께서 원래 작업 하셨듯이 주문서 상태랑 상관없이 수정할 수 있도록 변경합니다.

**Comment by keedi** [comment]
처리한 내역은 다음과 같습니다.

- 언제든지 반납 방법을 수정할 수 있도록 함
- `직접반납` 문자열을 `방문반납`으로 변경해서 명확하게 이해할 수 있도록 함
- 부트스트랩 X-에디터블 버튼이 너비가 부족해 클릭할 수 없는 영역에 표시되는 것을 조정해서 양식 아래에 위치하게해 클릭에 문제가 없도록 함

**Comment by keedi** [comment]
작업 완료한 화면은 다음과 같습니다.

![- 2015-02-03 22-13-15](https://cloud.githubusercontent.com/assets/138451/6020680/31caa4a8-abf2-11e4-8cd8-a04c7e13d42e.png)

수정시 화면은 다음과 같습니다.

![- 2015-02-03 22-13-50](https://cloud.githubusercontent.com/assets/138451/6020686/39f474c4-abf2-11e4-8389-e89434cffa80.png)

**Comment by keedi** [comment]
완료했으므로 이슈 닫습니다. :)

**Comment by keedi** [comment]
다음 두 가지 문제가 발생했습니다. 수정해야 합니다.

1. 파이어폭스에서는 정상 동작하지만 크롬에서 제대로 동작하지 않는다고 함
2. 택배 운송장 번호를 입력했는데 반납을 진행하면 입력했던 기록이 사라진다고 함

**Comment by keedi** [comment]
반납 진행시 기존 코드에서 반납 방식을 **직접반납**으로 값을 설정하고 있었습니다. 이전에는 반납 방법을 따로 입력 받지 않았기 때문에 모두 직접 반납 처리를 했으나 이제는 정확하게 직원이 입력하게 되었으므로 더이상 강제로 값을 넣지 않도록 수정했습니다.

**Comment by keedi** [comment]
크롬에서 확인하는 작업 진행합니다.

**Comment by keedi** [comment]
크롬에서 확인했는데 잘 동작합니다... 흐음... 확인이 필요합니다. **확인요망** 라벨 추가합니다.

크롬 버전은 다음과 같습니다.

> 버전 40.0.2214.91 Built on 8.0, running on Debian 8.0 (64-bit)

@10001if 확인 부탁드립니다.

**Comment by keedi** [comment]
크롬 관련 문제를 확인하고 나면 이슈 닫겠습니다.

**Comment by keedi** [comment]
크롬과 관련해 피드백이 없습니다. 우선 이슈를 닫고 최종 확인이 끝나면 **확인요망** 라벨을 제거하거나 또는 다시 이슈를 열거나 결정하겠습니다.

**Comment by 10001if** [comment]
@keedi 크롬에서도 잘 됩니다! 확인했습니다. 감사합니다. ^^
