### ISSUE TITLE
주소 검색에 실패할 경우 예외처리가 필요함

### ISSUE THREAD

**Issue by keedi** [opencloset/opencloset#334]
로그를 분석해보니 생각보다 주소 검색에 실패하는 경우가 많습니다. 실패할 경우 로그는 다음과 같습니다.

```
[Wed Jan  7 11:43:28 2015] [debug] GET "/api/postcode/search".
[Wed Jan  7 11:43:28 2015] [debug] Routing to a callback.
[Wed Jan  7 11:43:28 2015] [debug] Routing to a callback.
[Wed Jan  7 11:43:28 2015] [error] Can't call method "next" on an undefined value at /home/opencloset/.perlbrew/libs/perl-5.18.2@service/lib/perl5/Postcodify/Result.pm line 25.

[Wed Jan  7 11:43:28 2015] [debug] Template "exception.development.html.ep" not found.
[Wed Jan  7 11:43:28 2015] [debug] Rendering cached template "exception.html.ep".
[Wed Jan  7 11:43:28 2015] [debug] Rendering template 'layouts/error.html.haml'.
[Wed Jan  7 11:43:28 2015] [debug] Rendering template 'layouts/default/meta.html.haml'.
[Wed Jan  7 11:43:28 2015] [debug] Rendering template 'layouts/default/before-css.html.haml'.
[Wed Jan  7 11:43:28 2015] [debug] Rendering template 'layouts/default/before-js.html.haml'.
[Wed Jan  7 11:43:28 2015] [debug] Rendering cached template "layouts/default/theme.html.ep".
[Wed Jan  7 11:43:28 2015] [debug] Rendering template 'layouts/default/after-css.html.haml'.
[Wed Jan  7 11:43:28 2015] [debug] Rendering template 'layouts/default/after-js.html.haml'.
[Wed Jan  7 11:43:28 2015] [debug] Rendering cached template "layouts/default/navbar.html.ep".
```

아마도 사용하는 사용자는 상기 오류 발생으로 인해 hang이 발생해 몇초 이상씩 웹이 멈추는 듯한 느낌을 받고 있을 수도 있습니다. 수정이 필요합니다.

수정해야 할 내역은 다음과 같습니다.

- 검색 결과를 찾지 못할 경우 이후 연산을 수행하지 않고 적절한 오류 메시지를 보여줌. 예외 처리가 필요함
- 로그상으로 사용자가 어떤 질의를 보냈는지 알 수 없으므로 로그에 사용자가 입력한 질의를 표시해서 디버깅이나 개선이 용이하도록 함

**Comment by aanoaa** [comment]
[Wed Jan  7 16:00:05 2015] [debug] GET "/api/postcode/search.json".
    [Wed Jan  7 16:00:05 2015] [debug] Routing to a callback.
    [Wed Jan  7 16:00:05 2015] [debug] Routing to a callback.
    [Wed Jan  7 16:00:05 2015] [error] api_postcode_search failed: 한글뿅뿅

위처럼 로그를 남기도록 하겠습니다.

**Comment by keedi** [comment]
@aanoaa 실패 여부를 떠나서 질의는 로그에 남기는 것이 좋을 것 같습니다. 더불어 남기는 것과 별개로 예외 처리는 필요하구요.

**Comment by keedi** [comment]
```
[info] postcode search query: ...
[warn] postcode search failed <-- 결과가 없다면.
```

정리하면 error가 나야할 경우는 아니므로 예외처리(exception handling)해서 웹 응용 단의 로그에서는 warn 정도로 보여주었으면 합니다.

**Comment by keedi** [comment]
최종적으로 UI에서 결과가 없을 경우 *주소를 검색할 수 없습니다. 더 자세한 정보를 입력해주세요.* 등과 같은 메시지를 보여야 할 것입니다.

**Comment by keedi** [comment]
상기 두 부분까지 #336 PR에서 마무리 짓고 머지 후 이슈를 닫았으면 합니다.

**Comment by aanoaa** [comment]
![- 2015-01-07 16-13-58](https://cloud.githubusercontent.com/assets/170528/5642109/502b98be-9688-11e4-868f-151c76d8e259.png)

결과가 없을때가 아니라 특정 쿼리에대해(아직은 알지못함) 예상치못한 오류를 찾아내기 위함입니다.

**Comment by keedi** [comment]
그러니까 예상치 못한 오류가 발생했을 때도 검색 결과가 없다는 메시지를 동일하게 보여주어야 할 것 같다는 의미입니다. 방문 예약하려는 사용자에게 예상치 못한 오류가 발생했다고 알려주는 것은 의미가 없으니까요.

**Comment by aanoaa** [comment]
네

**Comment by keedi** [comment]
ㅎㅎ 이미 검색결과가 없는 것으로 보여주고 계시다면 그냥 성공이든 실패든 항상 쿼리만 보여주는걸로 수정해주시면 충분할듯합니다.

**Comment by aanoaa** [comment]
`요 퍽` 이라는 검색어를 입력하면 내부오류가 발생합니다.
이참에 모듈에서 이에 대한 처리를 하겠습니다.

**Comment by aanoaa** [comment]
`요 퍽` 과 같은 쿼리가 들어왔을때에 문제가 발생해서 이에 대한 예외처리 작업을 했지만,
모듈에서 이에 대한 처리가 이루어졌으므로 `Postcodify v0.2.6` 을 사용하면 simple 하게 해결됩니다.

**Comment by aanoaa** [comment]
$ cpanm --installdeps .

해주셔야 합니다.

**Comment by aanoaa** [comment]
배포하였습니다.
