### ISSUE TITLE
기증 페이지에서 의류 품번으로 기증 행위를 검색할 수 있게 함

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#338]
되었으면 좋겠습니다.

**Comment by keedi** [comment]
현재 기증 페이지에서 기증자 정보(이름, 이메일, 주소 등등)로만 검색이 됩니다. 기증 정보를 잘못 연결한 경우 이를 수정해야 하는데 특정 옷이 어느 기증 행위에 연결되어 있는지 목록을 일일이 봐야하는 번거로움이 있습니다. 따라서 검색시 의류 품번으로 기증 행위를 검색할 수 있다면 훨씬 편리할 것 같다고 합니다.

**Comment by keedi** [comment]
진행합니다. :)

**Comment by keedi** [comment]
처리한 내역은 다음과 같습니다.

- 테이블의 의류 코드 컬럼을 230픽셀로 고정
- 의류 코드 라벨을 고정폭 폰트로 표시
- 의류 코드로 기증 행위 검색이 가능하게 함

**Comment by keedi** [comment]
구현 완료한 화면은 다음과 같습니다.

![- 2015-02-12 23-38-57](https://cloud.githubusercontent.com/assets/138451/6169399/99c3e90a-b310-11e4-864a-b702fcad5112.png)

**Comment by keedi** [comment]
작업 완료했으므로 이슈 닫습니다. :)
