### ISSUE TITLE
시간표 페이지에서 사용자의 재방문 표시 여부가 정확하지 않음

### ISSUE THREAD

**Issue by keedi** [opencloset/opencloset#339]
실 사용중 보고된 버그입니다.

시간표 페이지에서 사용자의 재방문 표시 여부가 정확하지 않다고 합니다. 확인 후 수정이 필요합니다. 즉 재방문임에도 불구하고 재방문이라고 표시되지 않는 경우가 있다는 의미입니다. 반대로 재방문이 아닌데 재방문으로 표기하는 경우는 보고된 바 없습니다.

**Comment by 10001if** [comment]
![2015-01-08 2 21 50](https://cloud.githubusercontent.com/assets/4696328/5658246/f011148a-9741-11e4-8923-9c14b117c971.png)
2015-01-08 14:00 예약 중에 송후경 박혜빈님의 경우에도 재방문 표시가 되지 않습니다.

**Comment by 10001if** [comment]
이 화면을 보니까요.
![2015-01-08 3 05 55](https://cloud.githubusercontent.com/assets/4696328/5658614/f58a73a6-9747-11e4-8c00-afc6bc13e929.png)
혹시 기존에 대여기록이 있는 사람이 오늘 대여를 하면 그 사람에 특정하여 재방문이라는 기록이 뜨는 건 아닌지.. 하는 생각이 드네요.
노승언님은 재방문이란 표시가 뜨지 않는 걸 보니까 그런가 싶은 생각이 들어 글 남깁니다. ^^

**Comment by keedi** [comment]
진행합니다.

**Comment by keedi** [comment]
재방문 여부를 판단하는 데이터베이스 질의를 조금 더 세분화했습니다. 이전과 달리 현재 주문서 아이디는 제외하고 더 많은 상태에 대해 방문한 경우로 판단하도록 수정합니다.

**Comment by keedi** [comment]
작업 완료했으므로 이슈 닫습니다. 오작동하는 보고가 또 들어올 경우 현재 이슈를 다시 열어서 처리하겠습니다.
