### ISSUE TITLE
대여 화면에서 대여 희망 품목을 확인할 수 있어야 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#340]
현재 열린옷장 대여시스템에서 가장 실수가 많이 일어나는 곳이 포장상태입니다.
프로그램 자체는 매우 우수하나 저희의 적용 미숙으로 실수가 많이 일어나고 있습니다.
때문에 더욱 엄격한 포장과 재확인이 필요하다고 판단하고 있습니다.
하지만 한가지 기능이 추가된다면 오류를 방지하는데 큰 도움이 될 것으로 생각합니다.

포장을 하는 과정은 다음과 같습니다.

1. 옷을 결정한 고객이 옷장지기에게 결과를 통보
2. 옷장지기는 그 옷(구두, 벨트 등 악세서리 포함)을 가지고 포장하는 인원에게 정보를 전달
 2-1. 현재는 행거에 1번부터 11번까지 구획을 한 행거에 의류를 걸어놓고 있음
 2-2. 이때 의류에 테이프에 싸인펜으로 대여자명과 탈의실 번호를 추가로 작성하여 옷걸이에 붙임
3. 포장 담당자는 한 명씩(혼란을 초래할 우려가 있어 단 한명씩만 포장을 처리하기로 함) 탈의 상태였던 대여자의 상태를 포장으로 변경시킴
4. 이후 의류의 바코드를 찍어 포장을 완료함
5. 이를 통해 결제대기 상태로 전환됨

현재 1번, 2번, 3번, 5번의 과정이 순조롭게 잘 이뤄지고 있으나,  4번의 경우 약간의 문제가 있습니다.
테이프에 대여자명과 탈의번호를 작성하여 헹거에 걸려있는 의류가 누구의 대여품목인지 여부는 오류가 발생하지 않으나, 품목의 오류가 있을 여지가 있습니다.

가령 한만일 대여자는 3가지 항목(자켓, 바지, 셔츠)을 대여하길 원하나 옷장지기의 실수로 2가지 항목(자켓, 바지)을 포장 인원에게 전달했을 경우 포장을 하는 사람은 셔츠가 빠져있는지를 확인 할 수 없다는 것입니다.

물론 탈의실이 보이는 /room 화면이나 /select 화면에서는 확인이 가능하나 포장하는 사람이 그 모든 화면을 확인하기는 매우 어렵습니다. 때문에 아래와 같이 포장을 하는 대여 페이지(/rental)에서 대여하고자 하는 품목이 보일 수 있으면 좋겠습니다. 

![2015-01-08 2 28 16](https://cloud.githubusercontent.com/assets/4696328/5658411/bdd6b72e-9744-11e4-91ea-fc20987183fb.png)

그렇다면 포장을 하는 사람이 품목을 확인 한뒤 문제가 있는 부분은 옷을 건네 준 담당자에게 체크할 수 있기 때문입니다. (여기서 고객이 원한다고 했던 정보가 현장에서 바뀌어 그 정보가 확실한지 여부는 별개로 해도 될 것 같습니다. ^^)

**Comment by keedi** [comment]
처리한 내역은 다음과 같습니다.

- 대여 페이지에서 대여 희망 품목을 보여줌
- 익명 전자우편 주소가 너무 긴 관계로 연락처 테이블 컬럼을 조금 더 늘림
- 포장시 전혀 참고하지 않는 사용자 신체 치수를 더이상 보여주지 않음

**Comment by keedi** [comment]
결과 화면은 다음과 같습니다.

![- 2015-01-12 12-45-33](https://cloud.githubusercontent.com/assets/138451/5698782/88c4b6fe-9a59-11e4-8506-9071a4bbc2ff.png)

**Comment by keedi** [comment]
완료했으므로 이슈 닫습니다.

**Comment by aanoaa** [comment]
awesome-screenshot 인가요?
어떻게 네모로 블러처리 하나요? 옵션이 있나요?
마우스에 자대고?

**Comment by keedi** [comment]
@aanoaa 갈무리는 awesome-screenshot을 사용한 것 맞고 이외 모든 처리ᅟ는 gimp를 사용하고 있습니다.
