### ISSUE TITLE
방문 예약 최종 확정시 문구 수정

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#342]
방문예약이 정상적으로 완료된 경우 방문시간 안내가 포함된 문자가 발송됩니다. 문자가 발송되지 않은 경우 예약이 완료된 것이 아니니 다시한번 예약을 진행해주시고, 방문예약완료가 정상적으로 되지 않는 경우 열린옷장(070-4325-7521) 혹은 카카오톡 (goto.kakao.com/@열린옷장)으로 문의해주세요.

**Comment by keedi** [comment]
위치는 다음과 같습니다.

![- 2015-01-09 14-08-47](https://cloud.githubusercontent.com/assets/138451/5675735/21f67022-9809-11e4-89bf-9bb5721616b5.png)

**Comment by keedi** [comment]
완료한 화면은 다음과 같습니다.

![- 2015-01-09 14-19-05](https://cloud.githubusercontent.com/assets/138451/5675802/82a50b08-980a-11e4-8df5-b4035ed888b8.png)

**Comment by keedi** [comment]
완료되었으므로 이슈 닫습니다. :)
