### ISSUE TITLE
포장에서 결제대기로 상태를 변경시 해당 의류 상태를 대여 가능하지 않도록 상태를 변경함

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#343]
의류가 결제대기 상태가 되어도 여전히 대여가능 상태이므로 다른 대여자의 주문서에 여러번 같은 품목의 의류를 결제대기 상태로 만드는 일이 가능합니다.

따라서 결제대기 상태에서는 다른 사람의 포장상태에 엮이지 않도록 강제로 제한하는 조치가 필요합니다 :)

**Comment by keedi** [comment]
정리하면 포장 -> 결제대기로 변화할때 의류를 대여가능에서 결제대기로 바꾸어야 할 것 같습니다. 더불어 결제대기에서 새로주문을 클릭해서 다시 포장상태로 역으로 바꿀 경우 각각의 의류는 모두 결제대기에서 다시 대여가능 상태로 바꾸어야 합니다.

**Comment by keedi** [comment]
진행합니다.

**Comment by keedi** [comment]
처리한 내역은 다음과 같습니다.

- 데이터베이스의 상태 테이블에 포장취소 상태 추가
- 자바스크립트 라이브러리에 포장취소 상태 추가
- 포장시 주문서에 해당하는 모든 의류 상태를 결제대기로 변경
- 새로 주문시 주문서에 해당하는 모든 의류 상태를 포장취소로 변경
- 주문서 목록 페이지에서 포장 상태 열람 가능하도록 함

기존 데이터베이스에는 다음 질의를 적용합니다.

> INSERT INTO `status` (`id`, `name`) VALUES ('41', '포장취소');

**Comment by keedi** [comment]
다음은 포장 직전 화면입니다.

![- 2015-01-12 22-10-11](https://cloud.githubusercontent.com/assets/138451/5703340/c7f3d478-9aa8-11e4-9a36-c18790fe57e0.png)

포장을 수행한 이후 주문서에 모든 의류 항목은 결제대기 상태로 보입니다.

![- 2015-01-12 22-10-03](https://cloud.githubusercontent.com/assets/138451/5703344/d04411ba-9aa8-11e4-8809-e7aa3d5dffb5.png)

물론 주문서 이외의 다른 페이지에서 의류를 검색해도 동일하게 결제대기 상태로 보입니다.

![- 2015-01-12 22-11-08](https://cloud.githubusercontent.com/assets/138451/5703353/ea46f78a-9aa8-11e4-91dd-eaa8f502c819.png)

주문서에서 새로 주문을 누른 후 다시 의류를 검색하면 결제대기가 아닌 포장취소 상태로 보입니다.

![- 2015-01-12 22-11-52](https://cloud.githubusercontent.com/assets/138451/5703355/fd2c3fcc-9aa8-11e4-9a99-9f878e8cf6ad.png)

**Comment by keedi** [comment]
구현 완료했으므로 이슈 닫습니다.
