### ISSUE TITLE
2014-12-17 주문서에서 제거해야 할 목록 #2

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#344]
![2015-01-10 9 13 02](https://cloud.githubusercontent.com/assets/4696328/5689488/2ef0649a-98a9-11e4-9c75-1867113a41ca.png)
삭제 시도 해보았으나 삭제가 되지 않습니다.
삭제 요청드립니다. :)

**Comment by keedi** [comment]
@10001if UI에서 삭제 기능이 없는데 어떻게 삭제 시도해보셨던 건가요? (궁금해서... +_+)

**Comment by keedi** [comment]
- 홍한솔 90

**Comment by keedi** [comment]
서버에 적용 완료했습니다.

```bash
$ cd <project_home>
$ perl -Ilib bin/opencloset-order.pl app.conf list 90
$ perl -Ilib bin/opencloset-order.pl app.conf delete 90
```

**Comment by keedi** [comment]
이슈 닫습니다. :)
