### ISSUE TITLE
주문서 목록 페이지에 주문서의 비고를 보여줌

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#345]
/order?booking_ymd=all&p=1&status=late 페이지에서 매일 연체자를 체크하고 있는데요.
연락을 반복해서 할 확률이 높습니다.

가령, 김철수씨가 연체자를 15일 15:00에 확인하여 연락을 취했다고 가정해보면
김철수씨가 연락을 했다는 사실을 모르는 김영희씨가 15일 16:00에 재연락을 취할 수 있습니다.
때문에 비고란을 생성하여 연락을 취했는지 여부를 쉽게 확인 할 수 있게 하였으면 좋겠습니다.

물론 주문서 자체 비고란을 확인하여 조치를 취할 수는 있으나, 한눈에 확인하는 작업이 필요하다고 판단되어 요청드립니다. 제가 생각한 그림을 아래에 첨부하겠습니다. ^^

![2015-01-10 9 16 48](https://cloud.githubusercontent.com/assets/4696328/5689562/7ce2a25c-98aa-11e4-8645-f0a5488f652f.png)

**Comment by keedi** [comment]
진행합니다.

**Comment by keedi** [comment]
처리한 내역은 다음과 같습니다.

- 주문서 목록 테이블의 **기타** 항목을 **대여 품목**으로 정확하게 명시함
- 주문서 목록 테이블에 **비고** 항목을 추가함

**Comment by keedi** [comment]
결과 화면은 다음과 같습니다.

![- 2015-01-12 13-10-02](https://cloud.githubusercontent.com/assets/138451/5698912/ed87bd04-9a5c-11e4-9c44-e554f6d8a41c.png)

**Comment by keedi** [comment]
완료했으므로 이슈 닫습니다.
