### ISSUE TITLE
주문서 별로 대여 메시지를 입력 및 열람할 수 있어야 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#347]
프로그램에서 대여가 진행된 주문에서 대여메세지를 삽입할 수 있는 란이 필요합니다.
기능 추가 요청드립니다. :)

**Comment by keedi** [comment]
자원 봉사자 분들의 도움을 받아서 진행할 실질적인 업무이며, 이 업무를 통해 자원 봉사자 분들이 의미있는 일을 명확하게 하게 될 확률이 높습니다. 우선 순위가 높은 작업입니다. 현재 구현하지 않은 관계로 완료되기를 기다리고 있는 이슈 중 하나입니다.

**Comment by keedi** [comment]
상기 라벨 수정은 실수입니다. 데헷. =3

**Comment by keedi** [comment]
진행합니다.

**Comment by keedi** [comment]
방금 확인한 사실인데, 놀랍지만 아직까지 대여 메시지를 입력할 컬럼이 데이터베이스에 없었습니다. 어쨌든 OpenCloset-Schema 쪽에서 스키마 변경 이슈를 추가 및 처리한 후 진행하겠습니다.

**Comment by keedi** [comment]
`OpenCloset::Schema` 모듈 수정을 완료했습니다.

기존 데이터베이스에 적용하려면 다음 질의를 실행합니다.

```sql
ALTER TABLE `order` ADD COLUMN `message` TEXT DEFAULT NULL AFTER `desc`;
```

다음 명령으로 설치합니다.

```
$ cpanm --mirror=https://cpan.theopencloset.net OpenCloset::Schema
```

**Comment by keedi** [comment]
처리한 내역은 다음과 같습니다.

- OpenCloset::Schema 0.005 버전을 사용하도록 함
- 웹응용에서 `order.message` 를 입력 및 수정할 수 있도록 지원함
- 주문서 페이지에서 대여 메시지를 입력할 수 있도록 수정함

**Comment by keedi** [comment]
대여 메시지 입력시 보이는 화면은 다음과 같습니다.

![screenshot-monster silex kr 7730 2015-02-08 18-05-42](https://cloud.githubusercontent.com/assets/138451/6096019/d3315afc-afbd-11e4-9101-34d4766e1206.png)

대여 메시지 입력 후 보이는 화면은 다음과 같습니다.

![screenshot-monster silex kr 7730 2015-02-08 18-05-30](https://cloud.githubusercontent.com/assets/138451/6096020/e1fa192a-afbd-11e4-8acf-2e193671849a.png)

**Comment by keedi** [comment]
작업 완료했으며 @10001if 님 확인을 받은 후 이슈 닫겠습니다. *확인요망* 태그를 붙입니다. :)

**Comment by keedi** [comment]
완료했는데 이슈를 열어두니 작업을 덜한 이슈를 찾기가 힘든 측면이 있습니다. 완료한 작업은 이슈를 닫고 닫은 이슈에서 확인요망 라벨에 따라 피드백을 받고 라벨을 제거할지 또는 다시 이슈를 열지를 결정하겠습니다.

대표님의 확인을 받을 때까지는 **확인요망** 라벨을 붙이겠습니다. 확인 완료후 라벨을 제거합니다.

**Comment by 10001if** [comment]
@keedi 만들어주신 이미지 확인했습니다. 작성란 만들어 주셔서 감사합니다! ^^

**Comment by keedi** [comment]
확인 완료함 :)
