### ISSUE TITLE
반납처리시 배상비 금액이 0원임에도 현금, 카드, 계좌이체등을 표시해야 반납이 완료되는 현상

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#363]
675번 주문서 김의주님의 경우에는 전체 품목을 체크박스에서 체크한 뒤
반납을 진행하려고 하면 연체금액이 0원임에도  배상비 금액을 표시해야 진행이 되고 있는데요.
이 경우 현금 카드 계좌이체를 입력해도 시제에 문제가 없는지 여쭤보고 싶어 글 남깁니다.
확인 부탁드릴게요 ^^

![2015-01-13 7 59 47](https://cloud.githubusercontent.com/assets/4696328/5719851/ade03c18-9b5f-11e4-873c-3c1d83f52b22.png)
![2015-01-13 7 59 27](https://cloud.githubusercontent.com/assets/4696328/5719853/adeabed6-9b5f-11e4-804a-d0f02815e144.png)
![2015-01-13 7 59 54](https://cloud.githubusercontent.com/assets/4696328/5719852/ade60c74-9b5f-11e4-9a75-bca3a223d5f0.png)

**Comment by keedi** [comment]
음 적어주신 내용이 정확한지 일단 확인이 필요합니다.

1. 갈무리 해주신 첫번째 화면 기준으로 대여일은 1월 6일 반납 예정일은 1월 9일이기 때문에 이미 연체가 발생했습니다. 따라서 연체료가 0원이 아닙니다. 연체료가 0원이 아니기 때문에 연체료를 납부받지 않았다는 메시지(빨간색)가 표시된 것이구요.

2. 다음으로 언급하신 배상비 이야기가 나오는데 배상비를 떠나서 연체료를 납부하지 않았기 때문에 배상비와는 현 상황이 관련이 없어보이는데요. 단순한 오타인지 아니면 다른 현상이 있는지 정확하게 말씀해주셔야 할 것 같습니다.

**Comment by keedi** [comment]
화면 갈무리 상태로만 봤을때는 연체료가 24,000원 존재하고 이것이 현재 미납이기 때문에 당연히 반납이 진행되지 않은 것으로 보입니다.

**Comment by keedi** [comment]
조금 더 확인이 필요하고 추가 정보가 없다면 invalid 이슈로 처리할 예정입니다. :)

**Comment by keedi** [comment]
확인 결과 착오가 있었던 것 같다고 합니다. 이슈 닫습니다. :)
