### ISSUE TITLE
여러 브라우저에서 동일 아이디 중복 로그인이 안됨

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#368]
현재는 한개의 아이디당 여러개의 기기에 접속할 수 있는 것으로 알고 있습니다.
그런데 김호님의 경우 한개의 아이디는 1개의 기기에만 접속 하게 되어있다고 하네요.
여러번 실행해봤는데 그런 결과가 나온다고 합니다. 확인을 부탁드려도 될까요? ^^
(4층에서 컴퓨터를 이용하다가, 5층에서 스마트 폰으로 확인하는 상황이 발생합니다. ^^)

**Comment by keedi** [comment]
일단 재현되지 않고 있습니다. 문제가 다시 발생하면 바로 확인한 후 처리할 예정입니다. 일단은 이대로 둡니다.

**Comment by 10001if** [comment]
@keedi 어제도 로그인이 안된다는 소식을 들었습니다. 혹시 시간 나실 때 4층 사무실로 가셔서 김호님 아이디로 확인 좀 부탁드려도 될까요? 지금 전 5층입니다. ^^;

**Comment by keedi** [comment]
금일 18시 즈음 실제 방문해서 확인해보았습니다. 일단 아이패드와 휴대폰 모두 로그아웃한 상태에서 기억하기 옵션을 켠 상태에서 두 기기 모두 로그인을 했습니다. 이후 이슈가 발생하면 디버깅을 수행하도록 합니다. 하지만 현재 웹응용에서 일정시간 이후로 동작을 수행하지 않으며 로그아웃하도록 되어있기 때문에 자연스러운 동작이라고 사료되지만, 어쨌든 피드백을 기다라겠습니다.

자연스럽다고 생각하는 이유는, 일단 퇴근하면 그 다음날 출근할 때까지 웹서비스를 해당 장비에서 사용하지 않기 때문에 자연스레 로그아웃이 되고 있다고 생각은 하지만... 흠... 어쨌든 피드백을 확인한 후 정상 상황인데도 이것이 문제라면 이것은 로그인이 안되서 불편한 것 이 아니라 자동 로그아웃이 너무 빨리 이루어지기 때문에 불편하다는 의미입니다. 이 경우 로그인 내역 저장 세션 길이를 훨씬 더 길게 하는 식으로 처리해야 할 것입니다.

**Comment by keedi** [comment]
이후 특별히 업데이트된 내역이 없습니다.

오늘 중으로 다른 피드백이 없다면 이슈 닫겠습니다. 확인 바랍니다. :)

**Comment by keedi** [comment]
방금 확인했는데 따로 피드백이 없다고 합니다.

invalid로 처리하고 닫습니다. :)
