### ISSUE TITLE
프로젝트의 라이센스 명시

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#369]
저장소에 LICENSE 파일을 맨들어 두는 것이 좋겠습니다.

**Comment by keedi** [comment]
좋은 생각입니다. 특별히 생각하고 계신 라이센스는 있으신지요?

**Comment by aanoaa** [comment]
저는 별 생각 없습니다.
누구나 맘대로 쓸 수 있도록 http://choosealicense.com/licenses/mit/ 면 어떨까 합니다.
제 의견보다는 @10001if 님 의견이 중요할 것 같습니다.

이 소스코드의 라이센스에 대해 어떻게 하실건지 결정해야 합니다.
위임하신다면 제 맘대로 하겠습니다.

**Comment by keedi** [comment]
저는 펄 모듈이니만큼 Perl 5와 동일한 라이센스면 깔끔할 것 같긴합니다. 개인적으로는 GPL도 선호하구요.

**Comment by aanoaa** [comment]
http://choosealicense.com/licenses/

조..좋은 후보들입니다.

**Comment by keedi** [comment]
Perl 프로젝트 처럼 굳이 LICENSE 파일을 따로 만들지 않고 README 내부의 한 섹션으로 추가했습니다.

참고한 저장소와 파일은 다음과 같습니다.

https://github.com/Perl/perl5/blob/blead/README

**Comment by keedi** [comment]
이슈 닫습니다.
