### ISSUE TITLE
배 둘레를 윗배 둘레와 배꼽 둘레로 세분화

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#372]
현재 중동(배둘레) 사이즈를 '윗배둘레'로 변경해야 할 것 같습니다.

12월 17일 이후 측정한 사이즈는 모두 윗배둘레로 측정했기 때문에 큰 문제는 없을 것으로 보입니다.

그리고 중동(배둘레) 사이즈는 추가적으로 생성하는 것이 좋을 것 같습니다. 다만, 이 부분에 대해 @keedi 의견을 청취 후 진행하는 것이 좋을 것 같습니다. 추가로 생성해야 하는 사이즈들은 별도 이슈에 기록하겠습니다. ^^

**Comment by keedi** [comment]
정확하게 정리가 되어야 진행할 수 있는 이슈입니다. 확인이 완료될 때까지 **확인요망** 라벨을 붙입니다.

**Comment by 10001if** [comment]
1. 기존의 배꼽둘레(중동)을 윗배둘레로 변경 
2. 윗배둘레 항목 추가

함께 추가되어야 하는 항복에 대해서는 다시 말씀드리겠습니다.
함께 작업하는 것이 유리하실 것 같으니 빠른 시간 안에 답변 드리겠습니다.

**Comment by keedi** [comment]
추가할 항목이 언제 확정될지 모르니 바로 작업하도록합니다.

상기 기록해주신 부분이 모호한 부분이 있으니 다시 정확하게 정리합니다.

- 기존 belly를 top_belly로 수정(스키마 변경 및 데이터도 이전)
- belly가 top_belly로 바뀌었으니 다시 belly를 추가

**Comment by keedi** [comment]
작업하는데 필요한 부분은 모두 확인했으니 **확인요망** 라벨을 제거합니다.

**Comment by keedi** [comment]
opencloset/OpenCloset-Schema#16 항목을 처리 완료하면 마저 진행합니다.

**Comment by keedi** [comment]
처리해야 할 항목은 모두 세 군데 입니다.

- `user_info`
- `order`
- `clothes`

**Comment by keedi** [comment]
opencloset/OpenCloset-Schema#16 항목을 처리 완료했습니다. 더불어 OpenCloset::Schema 0.007 버전을 릴리스 했습니다.

다시 진행합니다. :)

**Comment by keedi** [comment]
웹응용과, 템플릿, 자바스크립트 모두 belly가 있는 곳에는 topbelly 항목을 추가했으며 각각 belly는 배꼽 둘레, topbelly는 윗배 둘레로 라벨을 수정했습니다.

**Comment by keedi** [comment]
작업 완료했으므로 이슈 닫습니다.

**Comment by keedi** [comment]
실서버에도 적용 완료했습니다. :)
