### ISSUE TITLE
의류 및 신체 사이즈 항목 추가

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#373]
추가적으로 필요한 사이즈를 정리해보았습니다. 아직 추가될 사항이 있을 여지가 있어 확정되면 다시 말씀드리도록 하겠습니다. :)

1. 목둘레
2. 어깨너비 
3. 등길이 
4. 종아리둘레
5. 윗가슴둘레
6. 밑가슴둘레
7. 윗팔둘레
8. 발목둘레
9. 손목둘레
10. 밑위길이

**Comment by keedi** [comment]
확인하고 싶은 내용이 있습니다.

상기 언급해주신 사이즈가 신체 사이즈인지 아니면 의류 사이즈인지요? 또는 양쪽 모두 적용되어야 하는 항목인가요?

**Comment by 10001if** [comment]
둘 다 적용되어야 한다고 생각합니다. 모든 의류와 신체 사이즈는 검색을 예상하고 있으므로 어느 한쪽의 데이터만 가지고는 활용도가 극히 낮을 것으로 예상됩니다. 추가될 사이즈는 최종 확인이 되면 다시 말씀드리겠습니다. ^^

**Comment by 10001if** [comment]
사이즈에 대한 정보를 조금 더 확인 한 후 내용을 확인하여 라벨을 제거하도록 하겠습니다.

**Comment by keedi** [comment]
아직 열린옷장 내부적으로 정리된바가 없다고 합니다. 더욱 구체화 되면 진행하겠습니다. 이번 마일스톤에서 제거합니다.

**Comment by keedi** [comment]
여전히 확정된 바가 없습니다. 확실하게 정해지면 그때 논의 후 진행하겠습니다.

일단 이슈 닫습니다.
