### ISSUE TITLE
태그 별 의류 검색

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#374]
태그를 의류마다 달아놓고 있지만 그 태그를 검색 할 수 있는 곳을 확인할 수 없습니다. 검색 할 수 있는 기능 생성을 요청드립니다. :)

![2015-01-21 3 23 21](https://cloud.githubusercontent.com/assets/4696328/5832049/fab2dc58-a181-11e4-8136-19ba47de8809.png)

**Comment by keedi** [comment]
태그는 의류의 속성 중 하나입니다. 태그를 기준으로 검색을 한다는 것은 의류를 검색하겠다는 의미입니다. 의류 목록페이지에서 태그별로 열람이 가능하도록 기능을 추가하겠습니다.

**Comment by keedi** [comment]
진행합니다.

**Comment by keedi** [comment]
처리한 내역은 다음과 같습니다.

- 화면에서 의류 상태별 보기와 마찬가지로 태그별로 열람할 수 있는 링크를 제공
- 컨트롤러에서 `tag` 매개변수를 받아 매개변수에 따라 의류를 열람하도록 함

**Comment by keedi** [comment]
결과 화면은 다음과 같습니다.

![- 2015-01-22 22-47-55](https://cloud.githubusercontent.com/assets/138451/5856717/f7178988-a288-11e4-973f-c28a32b4084e.png)

**Comment by keedi** [comment]
현재 화면에서 모든 태그별로 항목의 개수 0으로 보이는 이유는 각 태그별로 지정한 의류가 없기 때문입니다. 추가하면 개수는 변경됩니다. 일단 일차원적으로 태그를 검색하도록 했는데, 다른 UI적인 아이디어가 없기 때문에 일단 이정도로 마무리 짓겠습니다.

바로 피드백을 받았을 때 추가 의견이 더 있을 경우 현재 이슈를 다시 열어서 처리하고 피드백이 나오는데 시간이 더 걸린다면 이후에 별도의 이슈를 열어서 처리합니다.

**Comment by keedi** [comment]
@10001if 많은 피드백 및 아이디어 부탁드립니다.

**Comment by keedi** [comment]
완료했으므로 이슈 닫습니다.
