### ISSUE TITLE
의류 보유 현황 확인

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#375]
의류의 정보를 확인하는 이유는 크게 2가지 입니다.

1. ~~~고객의 몸에 잘 맞는 사이즈의 의류를 찾기 위함~~~
2. 보유해야 하는 의류의 적정량을 추론하기 위함

~~~1번의 경우에는 (1) 의류의 사이즈가 정확하게 기입되어 있어야 하고 (2) 사람의 사이즈가 정확하게 측정하였다는 전제 하에 (3) "사이즈별로 신체와 의류의 오차를 감안하여 검색할 수 있도록" 지정하면 될 것 으로 생각하는데요. 다만 여러 요인들이 복합적으로 섞여 있으므로 @keedi 말씀해주셨던 종합점수로 계산할 필요가 있을 것으로 보여집니다. (사실 아직도 어떻게 해야할지 정확히 판단이 서질 않습니다. 조금 더 대화가 필요할 것 같습니다. ^^)~~~

> #388 항목에서 처리하기로 한 부분과 연관되므로 무시해도 됩니다. - keedi

----

2번의 경우에는 1번을 서포트 하는 개념이긴 하지만, 실제 현장에서 매우 필요한 것입니다.
방문자의 사이즈를 평균하여 방문자의 신체 사이즈를 유추합니다.
그리고 보유한 의류의 수량을 파악하여 과부족을 체크하여 매일 매주 매월 열린옷장 옷 창고에 보유해야 하는 의류의 수를 적정하게 맞추는 것이 필요합니다. 

남는 의류의 경우에는 기준에 비해 지나치게 많을 경우 다른 의류 창고로 이동하여 보관하거나 극단적인 경우 폐기를 하는 방법이 있을 수도 있습니다. 하지만 모자란 의류의 경우 수선을 통해 그 의류양을 채워넣거나 추가 기증 혹은 의류 구입의 방법으로 해결하려고 합니다. 현재는 어떤 의류의 사이즈가 부족한지 대략적으로만 알고 있으며 그 날의 부족분을 가지고 추론을 하기 때문에 실제로 그 옷이 부족한 것인지 확인하기가 매우 어렵습니다. (갑자기 그 사이즈의 대여량이 폭증하여 없었던 것인지도 확인하기가 어려움)

~~~또한 현재는 사람들이 많이 입는다고 판단한 사이즈로 수선하고 있습니다. 그런데 그 사이즈만 계속 수선을 하다보니 실제 그 사이즈가 부족한지 여부는 확인이 되지 못한 상태로 수선이 진행되고 있는 부분이 있습니다.~~~

~~~여기에 의류의 전체 대여횟수를 보고 대여가 많이 되는 의류의 품번과 사이즈를 확인하는 작업을 위해 대여횟수 순으로 누적된 정보를 확인하고 싶습니다. :)~~~

> #385 항목에서 처리하기로 한 부분과 연관되므로 무시해도 됩니다. - keedi

**Comment by yongbin** [comment]
#385와 유사한 이슈입니다. 작성되었던 쿼리를 평가하고 화면에 어떻게 표현할지를 결정해야합니다.

**Comment by keedi** [comment]
논의를 통해 이슈가 구체화 되었습니다. 제목이 의류 보유 현황 확인으로 바뀌었습니다. #385 항목과는 다른 이슈입니다. 제목대로 진행하면 될것 같습니다.

**Comment by keedi** [comment]
알고 싶은 보유 현황의 종류는 다음과 같습니다.

- 전체 의류 현황
- 대여 의류 현황
- 보유 의류 현황

**Comment by keedi** [comment]
현황에서 궁금한 것은 각각의 의류 코드가 아니라 특정 구간(?? 확인이 필요함)에 속하는 의류의 **개수** 라고 합니다.

**Comment by keedi** [comment]
현재 이슈는 **특정 구간** 이라는 정의가 **매우** 중요합니다. 이 구간에 대한 정의가 되어야지만 각 구간에 속하는 의류의 개수를 뽑아낼 수 있습니다. 따라서 구간에 대한 정의를 확인받을 필요가 있습니다. 피드백이 올 때까지 **확인요망** 라벨로 표시합니다.

**Comment by keedi** [comment]
**구간**을 정의하는데 애를 먹고 있습니다. 구간 자체를 정의할지 말지도 고민할 것 같습니다.

**Comment by keedi** [comment]
우선 표로 표현하는 방법을 논의했습니다.

남자의 경우 다음과 같습니다.

- 상의: 중동+팔길이
- 하의: 허리+허벅지

여자의 경우 다음과 같습니다.

- 상의: 중동+팔길이
- 하의: 허리+엉덩이

여자는 의류를 셋트 단위로 묶어 대여하지 않고 섞어(크로스) 대여하기 때문에 상기 표 두 개만 나오면 충분할 것 같습니다. 다만 남자의 경우 *무조건* 셋트(위 아래 한 벌) 단위로 대여하기 때문에 상기 표 두 개는 상하의 자료가 따로 놀게 되기 때문에 의미가 충분하지 않을 수 있습니다. 하지만 딱히 다른 대안이 없으므로 우선은 이렇게 진행을 하고 결과를 보고 더 좋은 아이디어가 있다면 추가로 더 구현하도록 합니다.

**Comment by keedi** [comment]
일단 구현하는데 필요한 사항은 모두 확인했습니다. **확인요망** 라벨을 제거합니다.

**Comment by 10001if** [comment]
표로 논의하는 방법 중 보여져야 하는 기준 수정을 요청드립니다.

남자의 경우 다음과 같습니다.

   현재> 상의: 중동+팔길이    ->   변경요청 상의: 중동+가슴 (팔길이 대신 가슴으로 변경)
            하의: 허리+허벅지                        하의: 허리+허벅지

여자의 경우 다음과 같습니다.

    현재> 상의: 중동+팔길이    ->  변경요청 상의: 중동+가슴(팔길이 대신 가슴으로 변경)
             하의: 허리+엉덩이                       하의: 허리+엉덩이

현재 상의에 대해서는 1. 중동 2. 가슴 3. 팔길이가 경합하는데, 
가슴과 팔길이 중 무엇이 더 중요한지는 논란이 있습니다. 
다만, 더 많은 인원이 가슴에 손을 들고 있기에 이렇게 요청드립니다.

**Comment by keedi** [comment]
@10001if 대표님~ 가능하면 화면 캡처는 이미지로 하더라도 커멘트는 **꼭** 텍스트로 부탁드릴게요~

**Comment by keedi** [comment]
> via @10001if:
> 
> 표로 논의하는 방법 중 보여져야 하는 기준 수정을 요청드립니다.
> 
> 남자의 경우 다음과 같습니다.
> 
> 현재> 상의: 중동 + 팔길이
>       하의: 허리 + 허벅지
> 
> 변경> 상의: 중동 + 가슴
>       하의: 허리 + 허벅지 (동일)
> 
> 여자의 경우 다음과 같습니다.
> 
> 현재> 상의: 중동 + 팔길이
>       하의: 허리 + 엉덩이
> 
> 변경> 상의: 중동 + 가슴
>       하의: 허리 + 엉덩이 (동일)
> 
> 현재 상의에 대해서는 1. 중동, 2. 가슴, 3. 팔길이가 경합하는데, 가슴과 팔길이 중 무엇이 더 중요한지는 논란이 있습니다. 다만, 더 많은 인원이 가슴에 손을 들고 있기에 이렇게 요청드립니다.

**Comment by yongbin** [comment]
이 이슈는 #319 이슈와 중복인것으로 보이며 좀 더 구체적으료 내용으 확인이 필요한 이슈입니다.

**Comment by yongbin** [comment]
13일에 @10001if 님과 확인한 결과 #319 이슈와 #375 이슈는 동일하기 때문에 #319쪽에서 진행되도록 #375 번을 닫겠습니다.

**Comment by keedi** [comment]
중복 이슈라고 하니 중복 라벨을 붙입니다.
