### ISSUE TITLE
RFID 를 이용한 대여/반납/탈의 상태변경

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#377]
반납 받은 아이템을 바코드로 찍고 반납상태로 변경하는 과정에서 같은
실수가 매번 발생하고 있어서(바코드를 안찍는다) 이를 대체할 수단으로
알아본게 RFID 라고 합니다.

    물건(대여중) -> | 리더기(통과) | -> 물건(반납)

만 시켜주면 예약된 작업을 처리 할 수 있다는건데,
반납받은 아이템을 통과시켜주면 반납 상태로 변경하는 겁니다.

반납 뿐 아니라 각 의류의 상태를 `대여가능`에서 탈의실로 들어간 옷들이
`탈의`상태로 변경도 고려하고 있다고 합니다.

지금 사용되고 있는 의류코드 + 바코드를 RFID 로 변경하는 것에 대해 고려해봐야
합니다.

http://www.scpoint.co.kr/index.php 에서 견적을 알아본 바로는, 리더기 120 만원
에 tag 가 각 500원 입니다.

**Comment by keedi** [comment]
현재 데이터베이스 기준 의류가 약 2500건, 리더기는 아마도 4, 5층을 통틀어 4개 이상을 사용하리라 사료됩니다.

이 경우 리더기 480만원(120만원 x 4) + 125만원(500원 x 2500)해서 600만원 이상이 소요됩니다. 리더기가 4개 더 필요할 경우 소요금액은 1000만원입니다.

일단 참고하시라고 기록해둡니다.

**Comment by keedi** [comment]
시스템 입장에서는 바코드든 RFID든 상관없습니다. 어짜피 RFID라고 해도 동일한 코드가 들어갈 것이기 때문입니다. 열린옷장의 내부 결정 후 어느쪽이든 선택하시면 될듯합니다.

**Comment by 10001if** [comment]
@keedi 리더기 얘기해주시니까 정신이 번쩍 드네요! ㅎㅎ 그래도 동일한 코드가 들어가서 괜찮다고 있야기 해주시니 마음이 편해지네요. 좀 더 생각하고 알아보겠습니다. ^^

**Comment by keedi** [comment]
아마도 지금 안하겠죠? ㅎㅎ

**Comment by 10001if** [comment]
@keedi 네! 지금 당장은 아닙니다! ^^

**Comment by keedi** [comment]
이슈 닫습니다.
