### ISSUE TITLE
아파트 주소 검색의 어려움

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#383]
![a](https://cloud.githubusercontent.com/assets/170528/5952985/58e78e10-a7c5-11e4-9a27-b8767032c2a3.png)

아파트주소의 경우 구/신 주소를 알아보기 어렵습니다.

**Comment by keedi** [comment]
@10001if 어떤식으로 처리하길 원하시는지요?

**Comment by aanoaa** [comment]
보통 아파트주소는 어디의 무슨아파트 몇동 몇호 이렇게 부르는데,
위에 사진을 보시면 `xxxx아파트명` 이런식으로 되어 있습니다.

**Comment by keedi** [comment]
@aanoaa BTW, 첨부 그림의 첫번째 항목은 한글이 깨진 것 같은데 왜 그런 것일까요?

**Comment by aanoaa** [comment]
원본 데이터가 저렇지 않나 싶습니다.

**Comment by aanoaa** [comment]
https://github.com/kijin/postcodify/pull/5

**Comment by aanoaa** [comment]
https://github.com/kijin/postcodify/pull/5#issuecomment-76690642

`hideOldAddresses : false` 설정을 해주면 더 많은 정보가 노출되어서 도움이 될 것 같습니다.

**Comment by aanoaa** [comment]
![7603611](https://cloud.githubusercontent.com/assets/170528/6455310/d9b0c694-c195-11e4-90b0-9ad2b340c45e.png)

**Comment by keedi** [comment]
배포 완료했습니다.
