### ISSUE TITLE
주소 검색의 예시가 필요

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#384]
placeholder 를 두긴했지만, 그래도 여전히 사용자들이 주소 검색을 잘 하지 못해서
어려움이 있다고 합니다.

주소검색란 바로 밑에 적절한 예를 적어두면 도움이 될 것 같습니다.

**Comment by keedi** [comment]
@aanoaa 처리 부탁드립니다. :)

**Comment by keedi** [comment]
@aanoaa 간단한 작업이므로 작업 후 직접 머지해주시면 될 것 같습니다.

**Comment by aanoaa** [comment]
저의 게으름에 슬픔+1

**Comment by keedi** [comment]
완료된 화면은 다음과 같습니다.

![- 2015-02-12 21-47-58](https://cloud.githubusercontent.com/assets/138451/6167656/fc9ab8ac-b300-11e4-97cb-778b93a0839f.png)

**Comment by keedi** [comment]
작업이 완료되었으므로 이슈 닫습니다. :-)

++@aanoaa

**Comment by keedi** [comment]
@aanoaa 수정이후 검색시 후보 팝업이 기존 양식에 가려보입니다. 저만 그런 줄 알았는데 한만일 대표님 맥북에서도 동일하게 발생합니다. 확인 후 수정이 필요합니다. 현재 상태대로라면 주소 선택이 거의 불가능한 상태입니다.

**Comment by aanoaa** [comment]
맥부기에서 작업했었는데 주소 DB 가 없어서 테스트를 못해봤습니다.
예시를 입력창에 바짝 붙이려고 했는데 그냥 내비두겠습니다.

**Comment by aanoaa** [comment]
$ grunt

**Comment by aanoaa** [comment]
![- 2015-02-16 13-00-15](https://cloud.githubusercontent.com/assets/170528/6207063/e92015b4-b5db-11e4-954e-4d6bcb1c31f0.png)

**Comment by keedi** [comment]
정상 동작함을 확인했습니다.

**Comment by keedi** [comment]
실서버에 배포 또한 완료했습니다.
