### ISSUE TITLE
많이 대여된 옷 TOP 50

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#385]
email 로 전달된 내용입니다.

> 예전에 만들어 주셨던 원조 프로그램 URL 좀 알려주세요~
> 
> 그리고.
> 
> 12월 17일 이후 가장 많이 대여된 옷 TOP20 좀 뽑아주시겠어요?
> 그리고 혹시 그 옷을 입었던 사람 중에 BSET-FIT이 있었으면 그 대여자 정보도 같이 알 수 있을까요?
> 
> 그리고 가장 대여가 많이 된 옷 말고 가장 대여가 많이된 기증자도 알고 싶어요. ^^
> (기증자가 여러벌 기증한 사람이 있을 수 있으니까요.)
> 
> 부탁드릴게요 ^^

~~- [ ] 12월 17일 이후 가장 많이 대여된 옷 을 카테고리별 TOP50~~
~~- [ ] 그리고 혹시 그 옷을 입었던 사람 중에 BSET-FIT이 있었으면 그 대여자 정보도 같이 알 수 있을까요?~~

**Comment by aanoaa** [comment]
제가 뽑아 본 겁니다.

```sql
SELECT c.category, c.code, COUNT(c.code) as `cnt`
FROM `order` o
JOIN `order_detail` od
ON o.id = od.order_id
JOIN clothes c
ON od.clothes_code = c.code
WHERE o.rental_date >= STR_TO_DATE('2014-12-17', '%Y-%m-%d')
GROUP BY c.category, c.code
ORDER BY `cnt` DESC
LIMIT 20;
```

**Comment by yongbin** [comment]
이 쿼리도 문제가 있습니다. SQL 조합 순서상 ORDER BY와 LIMIT 은 가장 마지막에 평가되기때문에, 이 SQL은 **카테고리별 TOP 20** 이 아니라 카테고리별 카운트를 계산한 뒤 가장 상위 20개를 뽑아내기 때문에 의미가 다릅니다. 

즉 원한 결과는 아래 쿼리의 결과를 그룹별로 20개(혹은 50개)로 나누는것입니다. 

```
SELECT 			b.`category`
				,b.`code`
				,count(*) AS `rent_count`
FROM 			`order_detail` AS a 
				INNER JOIN `clothes` AS b ON a.`clothes_code` = b.`CODE`
				INNER JOIN `order` AS c ON a.`order_id` = c.`id`
WHERE 			c.rental_date >= STR_TO_DATE('2014-12-17', '%Y-%m-%d')
GROUP BY		b.`category`, b.`code`
ORDER BY  		b.`category`, `rent_count` DESC
```

하지만 안타깝게도 mysql은 window function을 거의 제공하지 않기떄문에 **그룹 별 상위 N개**를 뽑아내는 깔끔한 방법이 없습니다. 

http://www.xaprb.com/blog/2006/12/07/how-to-select-the-firstleastmax-row-per-group-in-sql/

**Comment by yongbin** [comment]
> 하지만 안타깝게도 mysql은 window function을 거의 제공하지 않기떄문에 그룹 별 상위 N개를 뽑아내는 깔끔한 방법이 없습니다.

깔끔하진 않지만 문제를 해결하는 쿼리는 다음과 같습니다.

```SQLSET @n := 0, @g := '';
SELECT 	y.`category`
		,y.`code`
		,y.`rent_count`
FROM 
(
SELECT x.*
                        ,@n := IF(@g = x.`category`, @n + 1, 1) AS row_number
                        ,@g := x.`category` AS `dummy`

FROM 
(
SELECT                  b.`category`
                        ,b.`CODE`
                        ,count(*) AS `rent_count`
FROM                    `order_detail` AS a 
                        INNER JOIN `clothes` AS b ON a.`clothes_code` = b.`CODE`
                        INNER JOIN `order` AS c ON a.`order_id` = c.`id`
WHERE                   c.rental_date >= STR_TO_DATE('2014-12-17', '%Y-%m-%d')
GROUP BY                b.`category`, b.`CODE`
ORDER BY                b.`category`, `rent_count` DESC
) AS x 
) AS y
WHERE y.row_number <= 20;
```

마지막 where 조건에 `row_number`를 조절하면 수를 설정할 수 있습니다.

**Comment by yongbin** [comment]
참고로 postgresql 은 `ROW_NUM`을 제공하고, 윈도우 함수도 있기때문에 훨씬 간결하게 문제를 해결할 수 있습니다.
```SQL
SELECT * 
FROM (SELECT ROW_NUMBER() OVER (PARTITION BY field order by field2 DESC) AS r,
    t.*
    from table1 t
    where field3 = 'data' ) x
where x.r <= 20
```
http://stackoverflow.com/questions/1124603/grouped-limit-in-postgresql-show-the-first-n-rows-for-each-group

**Comment by keedi** [comment]
@10001if 대표님께서 본 기능이 사이트에 정말 필요한 것인지 **진지**하게 고민하신 후, 피드백 주신다고 합니다. 일단 **확인요망** 라벨을 붙이고 **높음** 우선순위를 제거합니다.

**Comment by yongbin** [comment]
> From: Han Manil (theopencloset)
> To: Yongbin Yu
> Cc: Hyungsuk Hong, 김도형
> Subject: Re: 형석님 부탁드리고 싶은게 있어요~
> Flags: seen
> Date: Fri Jan 30 20:02:12 2015
> Maildir: /yongbin.yu/INBOX
> 
> 유용빈 대표님 자료 잘 받았습니다.
> 보내주신 자료 보고 있으니 정말 재미있네요.
> 저희의 대여가 이런 결과로 나타나고 있다는 걸 눈으로 보는게 이렇게 재미있다니요! ^^
> 
> 효율측면에서 분석해 주신 기증자 자료 정말 잘봤습니다.
> 이 부분은 잘 생각해보지 못했는데 앞으로 기증자에게 기증을 받을 때 고려하여 기증요청을 할 수 있을 것 같아요.
> 
> 한가지 더 부탁드리려고 메일을 보냅니다.
> 
> 복종별로 가장 많이 대여된 탑 50의 의류를 보고 있으니, 코드로만은 어떤 의류인지 확인이 어렵네요.
> 괜찮으시다면 보내주신 자료에 더해서 
> 1. 기증자명 2. 기증일 3. 기증자 연락처 4. 기증자 이메일 5. 의류의 색상 6. 의류의 사이즈 (전체 모든 사이즈) 7. 태그
> 까지 한번에 부탁드릴게요.
> 
> 이 자료는 현재 열린옷장에서 어떤 의류가 가장 인기가 좋은지 확인하는 것이라서 최대한 많인 정보가 함께 들어가 있으면 좋을 것 같습니다.
> 팀원 모두 공유하여 보고 싶어서요.
> 
> 부탁드리겠습니다.
> 
> p.s)월요일 미팅은 이롭게 사정으로 연기되었습니다. 
> 일정 확인되는대로 다시 말씀드리겠습니다. ^^

**Comment by yongbin** [comment]
다음 정보들을 추가한 쿼리를 작성해야합니다. 

1. 기증자명 
2. 기증일 
3. 기증자 연락처 
4. 기증자 이메일 
5. 의류의 색상 
6. 의류의 사이즈 (전체 모든 사이즈) 
7. 태그

**Comment by yongbin** [comment]
> From: Han Manil (theopencloset)
> To: Yongbin Yu
> Cc: Hyungsuk Hong, 김도형
> Subject: Re: 형석님 부탁드리고 싶은게 있어요~
> Flags: seen
> Date: Fri Jan 30 20:26:54 2015
> Maildir: /yongbin.yu/INBOX
> 
> 지금 데이터를 쭈욱 살펴보고 있으니까
> 전체 데이터로 보니 좀 아쉬운 부분이 있어서요.
> 다음에 주실 땐 남녀로 구분하여 주시면 더 감사할 것 같습니다.
> 
> 부락드릴게요 ^^

**Comment by yongbin** [comment]
- [ ] 남/여의 자료 구분

**Comment by yongbin** [comment]
이 이슈 역시 웹에 추가되어야 합니다.

**Comment by yongbin** [comment]
한만일 대표님이 원하시는 내용이 모두 반영된 쿼리는 아래와 같습니다.

```SQL
SELECT          b.`category`
                ,b.`code`
                ,e.`name` AS `doner_name`
                ,count(*) AS `rent_count`
                ,b.`color`
                ,b.`bust`
                ,b.`waist`
                ,b.`hip`
                ,b.`topbelly`
                ,b.`belly`
                ,b.`arm`
                ,b.`thigh`
                ,b.`length`
                
FROM            `order_detail` AS a 
                INNER JOIN `clothes` AS b ON a.`clothes_code` = b.`CODE`
                INNER JOIN `order` AS c ON a.`order_id` = c.`id`
                INNER JOIN `donation` AS d ON b.`donation_id` = d.id
                INNER JOIN `user` AS e ON d.`user_id` = e.id
WHERE           c.rental_date >= STR_TO_DATE('2014-12-17', '%Y-%m-%d')
GROUP BY        b.`category`, b.`code`
ORDER BY        b.`category`, `rent_count` DESC
```

이 화면 역시 웹에서 구현되어야 하며 웹에서 필요한 인자는 다음 3가지 입니다.

 - 시간 날짜
 - 종료 날짜 
 - 랭킹의 리밋(TOP 10 인지 TOP 100인지)

한가지 고민해야 하는 사항은 다양한 복종을 한 화면에 어떻게 효과적으로 보여줄지에 대한 부분은 @yongbin이 좀 더 고민해봐야합니다.

**Comment by keedi** [comment]
필요한 세부 내역을 확인했으므로 확인요망 라벨을 제거합니다.

**Comment by keedi** [comment]
@yongbin 2015-02-16 저녁 미팅때 같이 정리한 내용 정리바랍니다. :)

**Comment by keedi** [comment]
정리 안하면 까먹을텐데...

**Comment by yongbin** [comment]
2월 16일(월) @keedi 과 논의한 내용을 정리합니다. 

1. 이 이슈는 다른 '통계' 카테고리의 이슈들과 마찬가지로  신설된 '통계' 메뉴 하부에 위치시킵니다.
2. 지금까지 이 이슈는 카테고리별 많이 대여된 옷의 상위 N개를 한번에 가지고 올수 있는 SQL 쿼리를 작성하고, 작성된 쿼리로 만든 자료를 @10001if 님께 확인받는 과정으로 진행되었습니다. 
3. 기존 작성했던 SQL 쿼리는 전체 카테고리에 대해 대여수가 많은 자료를 가지고 오는 작업과, 카테고리별 대여수 상위 항목들을 **각각 카테고리별로** 잘라내는 작업 2가지로 구성되어있었는데 후자의 작업은 MySQL에서 지역변수를 사용하는 방식으로 해결해야하는 제한점이 있었기 때문에 응용프로그램 수준에서 perl로 작업을 고려했었습니다.
4. 하지만 최종적으로 @keedi 님께서 의견 주신것 처럼, 사용자에게 `카테고리`를 인자로 전달받아서 구현을 단순화 하는 방향으로 결정했습니다. 이렇게 진행될 경우 그룹별로 상위 N개를 잘라내는 복잡한 문제를 고려할 필요가 없으며 단순하게 `limit`을 시용해서 구현할수 있기때문에 문제가 훨씬 쉬워집니다.
5. 따라서 이 기능을 처리하는 웹페이지는 다음 4가지를 사용자로부터 인자로 받아서 처리합니다.
  * 시작날짜
  * 종료날짜
  * 카테고리
  * LIMIT COUNT

**Comment by yongbin** [comment]
시작합니다.

**Comment by yongbin** [comment]
![- 2015-02-23 19-50-55](https://cloud.githubusercontent.com/assets/52704/6326491/9d8f4060-bb95-11e4-8522-cc5f85378210.png)

**Comment by keedi** [comment]
최종적으로 완료된 화면입니다.

![- 2015-02-23 21-25-43](https://cloud.githubusercontent.com/assets/138451/6327728/af4d226a-bba2-11e4-9b8f-cbb7788092c2.png)

**Comment by keedi** [comment]
작업 완료되었습니다. 서버에 실배포 되어야 하며 확인이 필요합니다.

**Comment by keedi** [comment]
이슈 닫습니다. :)

**Comment by keedi** [comment]
서버에 배포 또한 완료했습니다. :)

**Comment by keedi** [comment]
확인 완료했습니다. :)
