### ISSUE TITLE
가장 대여가 많이된 기증자 정보

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#386]
#385 와 관련 있습니다.

2014-12-17 일 이후에 가장 대여가 많이된 기증자(열린옷장 제외) 역시 알고 싶어 합니다.

**Comment by aanoaa** [comment]
역시 제가 뽑은 쿼리입니다.

```
SELECT u.name, u.email, c.category, c.code, COUNT(c.code) as `cnt`
FROM `order` o
JOIN `order_detail` od ON o.id = od.order_id
JOIN clothes c ON od.clothes_code = c.code
JOIN donation d ON c.donation_id = d.id
JOIN user u ON d.user_id = u.id
WHERE o.rental_date >= STR_TO_DATE('2014-12-17', '%Y-%m-%d') AND u.id != 1
GROUP BY u.name, u.email, c.category, c.code
ORDER BY `cnt` DESC
LIMIT 20;
```

**Comment by yongbin** [comment]
수정한 쿼리입니다.
```SQL
SELECT      u.`name`
            , u.email
            , COUNT(c.`code`) AS `cnt`
FROM        `order` AS o
            INNER JOIN `order_detail` AS  od ON o.`id`            = od.`order_id`
            INNER JOIN `clothes`      AS   c ON od.`clothes_code` = c.`code`
            INNER JOIN `donation`     AS   d ON c.`donation_id`   = d.`id`
            INNER JOIN `user`         AS   u ON d.`user_id` = u.`id`
WHERE       o.`rental_date` >= STR_TO_DATE('2014-12-17', '%Y-%m-%d') AND u.`id` != 1
GROUP BY    u.`id`
ORDER BY    `cnt` DESC
LIMIT 20;
```
인덴트를 수정한것을 제외하고 가장 큰 차이는 `GROUP BY` 구문의 변경입니다. `GROUP BY`는 COUNT같은 aggregation 함수의 대상을 나눠주는 역활을 하기 때문에 대부분의 경우 유일식별자를 사용해야 합니다. 따라서 `GROUP BY u.name, u.email, c.category, c.code` 은 `GROUP BY u.id, c.code` 와 동일합니다. 그리고 대여된 옷들 전체를 대상으로 해당 옷을 대여한 사람만을 원하는것이기 때문에 `c.code`는 불필요해 보이며 그렇기 때문에 SELECT에서 c.category, c.code도 제거했습니다.

**Comment by yongbin** [comment]
위 쿼리 결과를 확인해보면 유난히 기업 후원이 눈에 많이 띱니다. 생각해보면 발생한 대여에대해 기증자를 추적하는 방식이기때문에 당연히 **옷을 많이 기증**하면 합산된 대여수가 증가하기때문에 당연한 결과입니다. 

만약 이러한 옷의 대여한 수에 영향을 받지 않고, **가장 효과적인(대여가 잘 되는) 옷을 대여해준 기증자** 를 찾는것이 목적이라면 쿼리를 다음과 같이 수정해 볼 수 있습니다.

```SQL
SELECT  x.*
		, y.donation_count
		, x.rent_count / y.donation_count AS `rdratio`

FROM 

(

SELECT      u.`id` AS `user_id`
			,u.`name`
            , u.email
            , COUNT(c.`CODE`) AS `rent_count`
FROM        `order` AS o
            INNER JOIN `order_detail` AS  od ON o.`id`            = od.`order_id`
            INNER JOIN `clothes`      AS   c ON od.`clothes_code` = c.`CODE`
            INNER JOIN `donation`     AS   d ON c.`donation_id`   = d.`id`
            INNER JOIN `user`         AS   u ON d.`user_id`       = u.`id`
WHERE       o.`rental_date` >= STR_TO_DATE('2014-12-17', '%Y-%m-%d') AND u.`id` != 1
GROUP BY    u.`id`
) AS x INNER JOIN
(
SELECT b.`id` AS `user_id`, count(*) AS `donation_count` FROM `donation` AS a INNER JOIN `user` AS b ON a.`user_id` = b.`id` INNER JOIN `clothes` AS c ON a.`id` = c.`donation_id` GROUP BY b.`id`
) AS y ON x.user_id = y.user_id

ORDER BY `rdratio` DESC
LIMIT 10;
```
이 쿼리는 해당 옷의 대여수를 해당 기증자가 기증한 옷 수로 나눈 `rdratio`라는 수치를 추가했습니다. 결과적으로 `rdratio`가 4~5 이상의 개인 기증자들이 위주로 나타남을 확인할 수 있습니다.

**Comment by aanoaa** [comment]
우왕 쿼리왕 @yongbin

**Comment by keedi** [comment]
@10001if 대표님께서 본 기능이 사이트에 정말 필요한 것인지 **진지**하게 고민하신 후, 피드백 주신다고 합니다. 일단 **확인요망** 라벨을 붙이고 **높음** 우선순위를 제거합니다.

**Comment by yongbin** [comment]
> From: Han Manil (theopencloset)
> To: Yongbin Yu
> Cc: Hyungsuk Hong, 김도형
> Subject: Re: 형석님 부탁드리고 싶은게 있어요~
> Flags: seen
> Date: Fri Jan 30 20:26:54 2015
> Maildir: /yongbin.yu/INBOX
> 
> 지금 데이터를 쭈욱 살펴보고 있으니까
> 전체 데이터로 보니 좀 아쉬운 부분이 있어서요.
> 다음에 주실 땐 남녀로 구분하여 주시면 더 감사할 것 같습니다.
> 
> 부락드릴게요 ^^

**Comment by yongbin** [comment]
이 이슈는 데이터의 전달로 완료되지 않고 구체적인 통계카테고리로 구현되어야 합니다. 

`rdratio`는 사용하지 않으며, 각 대여의 총 수를 옷의 카테고리에 따라서 나눠서 표현해 주는것이 필요합니다. 

```sql
SELECT      u.`name`
            , u.email
            , COUNT(c.`code`) AS `cnt`
FROM        `order` AS o
            INNER JOIN `order_detail` AS  od ON o.`id`            = od.`order_id`
            INNER JOIN `clothes`      AS   c ON od.`clothes_code` = c.`code`
            INNER JOIN `donation`     AS   d ON c.`donation_id`   = d.`id`
            INNER JOIN `user`         AS   u ON d.`user_id`       = u.`id`
WHERE       o.`rental_date` >= STR_TO_DATE('2014-12-17', '%Y-%m-%d') AND u.`id` != 1
GROUP BY    u.`id`
ORDER BY    `cnt` DESC
LIMIT 20;
```

즉 위 쿼리 결과에 우측에 아래 항목의 컬럼들이 추가되어야 합니다.


- belt
- blouse
- coat
- jacket
- onepiece
- pants
- shirt
- shoes
- skirt
- tie
- waistcoat

이 항목들은 웹상에서 정렬(sort)가 되면 좋겠습니다. 

그리고 이 페이지는 `시작시점`과 `종료시점`을 인자로 전달받아야 합니다.

**Comment by keedi** [comment]
필요한 세부 내역을 확인했으므로 확인요망 라벨을 제거합니다.

**Comment by keedi** [comment]
@yongbin 님과 구현 관련해서 논의할 부분이 조금 더 있습니다. 아직 더 세부적인 쿼리를 만들기 위해 진행할지 펄 코드로 어느정도 대체할지 확실하게 결정을 못한 상태이므로 더 정확하게 논의를 한 후 진행하겠습니다.

따라서 현재 2차 오픈에서는 빼도록 합니다.

**Comment by keedi** [comment]
@yongbin 2차 오픈에서 밀린 작업이니 진행 요망합니다. 논의해야할 부분이 있다면 역시 진행해주세요.

**Comment by yongbin** [comment]
넵 알겠습니다 제가 진행하겠습니다.

**Comment by yongbin** [comment]
@10001if  내일 이 이슈에 대해서도 같이 논의하겠습니다.

**Comment by yongbin** [comment]
@10001if  님과 확인한 결과 이 이슈는 #385 에서 해결되었기 때문에 처리하지 않기로 했습니다. 추후 필요하다면 새로 열어서 진행하도록 하겠습니다.
