### ISSUE TITLE
시간표에서 베스트핏 여부를 입력 가능하도록 함

### ISSUE THREAD

**Issue by keedi** [opencloset/opencloset#388]
현재 의류를 검색해서 탈의실로 배달하는 사람과 포장하는 사람이 나뉘어 있기 때문에 각 주문서에 대한 베스트핏 여부를 입력하기가 어렵다고 합니다. 포장하는 사람에게까지 베스트핏 여부가 전달이 되면 좋은데 현재 이것이 어렵다고 합니다. 탈의실로 의류를 배달하는 사람이 베스트핏 여부를 아는데 이 사람이 입력하려면 시간표 페이지에서 입력이 가능해야 합니다.

시간표 페이지에서 비록 빌릴 의류가 결정되지 않은 시점이라 하더라도 해당 주문서에 대해 베스트 핏 여부를 수정할 수 있도록 합니다.

**Comment by keedi** [comment]
진행합니다.

**Comment by keedi** [comment]
구현 완료한 화면입니다.

![- 2015-02-09 18-21-01](https://cloud.githubusercontent.com/assets/138451/6103528/c2cdf802-b088-11e4-9034-7cf35fbc9bc7.png)

**Comment by keedi** [comment]
주문서의 상태와 마찬가지로 어울림의 오른쪽 옆 영역을 클릭해서 보통 또는 Best-Fit을 선택해서 입력할 수 있습니다.

**Comment by keedi** [comment]
작업 완료했으므로 이슈 닫습니다.

대표님의 확인을 받을 때까지는 **확인요망** 라벨을 붙이겠습니다. 확인 완료후 라벨을 제거합니다.

**Comment by 10001if** [comment]
@keedi 정말 감사합니다! 이 정도면 불편해서 못한다는 말은 나오지 않을 듯 합니다! 감사합니다. ^^
