### ISSUE TITLE
바코드 표준 규격에 맞게 데이터베이스 자료 구조 변경

### ISSUE THREAD

**Issue by keedi** [opencloset/opencloset#39]
바코드 표준 규격을 따른다면 바코드의 길이는 고정입니다.
해당 바코드 표준 규격에서 지원하는 고정 길이를 사용하도록 데이터베이스의
자료구조를 변경하고 코드에 영향이 있는 부분이 있다면 같이 수정합니다.

**Comment by yongbin** [comment]
한만일 대표님께서 셔츠 200벌에 대한 코드생성을 요청하셨습니다. 생성된 코드는 아래와 같습니다.

```
J0RS
J0RT
J0RU
J0RV
J0RW
J0RX
J0RY
J0RZ
J0S0
J0S1
J0S2
J0S3
J0S4
J0S5
J0S6
J0S7
J0S8
J0S9
J0SA
J0SB
J0SC
J0SD
J0SE
J0SF
J0SG
J0SH
J0SI
J0SJ
J0SK
J0SL
J0SM
J0SN
J0SO
J0SP
J0SQ
J0SR
J0SS
J0ST
J0SU
J0SV
J0SW
J0SX
J0SY
J0SZ
J0T0
J0T1
J0T2
J0T3
J0T4
J0T5
J0T6
J0T7
J0T8
J0T9
J0TA
J0TB
J0TC
J0TD
J0TE
J0TF
J0TG
J0TH
J0TI
J0TJ
J0TK
J0TL
J0TM
J0TN
J0TO
J0TP
J0TQ
J0TR
J0TS
J0TT
J0TU
J0TV
J0TW
J0TX
J0TY
J0TZ
J0U0
J0U1
J0U2
J0U3
J0U4
J0U5
J0U6
J0U7
J0U8
J0U9
J0UA
J0UB
J0UC
J0UD
J0UE
J0UF
J0UG
J0UH
J0UI
J0UJ
J0UK
J0UL
J0UM
J0UN
J0UO
J0UP
J0UQ
J0UR
J0US
J0UT
J0UU
J0UV
J0UW
J0UX
J0UY
J0UZ
J0V0
J0V1
J0V2
J0V3
J0V4
J0V5
J0V6
J0V7
J0V8
J0V9
J0VA
J0VB
J0VC
J0VD
J0VE
J0VF
J0VG
J0VH
J0VI
J0VJ
J0VK
J0VL
J0VM
J0VN
J0VO
J0VP
J0VQ
J0VR
J0VS
J0VT
J0VU
J0VV
J0VW
J0VX
J0VY
J0VZ
J0W0
J0W1
J0W2
J0W3
J0W4
J0W5
J0W6
J0W7
J0W8
J0W9
J0WA
J0WB
J0WC
J0WD
J0WE
J0WF
J0WG
J0WH
J0WI
J0WJ
J0WK
J0WL
J0WM
J0WN
J0WO
J0WP
J0WQ
J0WR
J0WS
J0WT
J0WU
J0WV
J0WW
J0WX
J0WY
J0WZ
J0X0
J0X1
J0X2
J0X3
J0X4
J0X5
J0X6
J0X7
J0X8
J0X9
J0XA
J0XB
```
아울러 다음생성을 위해서 기억해야할 LAST코드는 다음과 같습니다.


```
[ last code ]
A0KT
B06X
C022
E0I1
H00O
J0XB
K0B3
O022
P0JF
S0F9
T0D6
W01D
```

**Comment by keedi** [comment]
@yongbin 경과 사항 적어주시고 완료되었을 경우 이슈 닫아주세요.

**Comment by keedi** [comment]
@yongbin 

더불어 이후 추가 바코드 출력 건은 별도의 이슈를 열어서 진행해주세요. 본 이슈는 원래 **바코드 표준 규격에 맞게 데이터베이스 자료 구조 변경**이었으니 현 이슈에 계속 붙이는 것은 의미가 없을듯 합니다.

라벨에 **바코드** 항목을 추가하고 앞으로 바코드 이슈는 **바코드** 라벨을 붙여주세요.

**Comment by yongbin** [comment]
> @yongbin 경과 사항 적어주시고 완료되었을 경우 이슈 닫아주세요.

넵 처리완료했으니 이슈 닫겠습니다.


> @yongbin
> 
> 더불어 이후 추가 바코드 출력 건은 별도의 이슈를 열어서 진행해주세요. 본 이슈는 원래 바코드 표준 규격에 맞게 데이터베이스 자료 구조 변경이었으니 현 이슈에 계속 붙이는 것은 의미가 없을듯 합니다.
> 
> 라벨에 바코드 항목을 추가하고 앞으로 바코드 이슈는 바코드 라벨을 붙여주세요.

넵 바코드 라벨 추가하고 추가 요청이슈는 항상 새로 열어서 처리하겠습니다.

**Comment by keedi** [comment]
바코드 라벨 장착.

**Comment by yongbin** [comment]
이 이슈는 열린옷장에 바코드시스템을 초기도입하기 위해서 진행한 내용이지만 초기 바코드의 last 코드 처리에 미숙한 점들때문에  이후 발생하는 혼란(#588)의 원인이 됩니다. 따라서 바코드와 관련된 이슈를 추적하고자 할 경우 이 이슈의 내용을 수차적으로 읽기보다는 #588의 내용을 먼저 파악한 뒤 이 이슈의 내용을 확인하는 편이 어 옳습니다.

**Comment by yongbin** [comment]
향후 바코드 생성과 관련한 혼란을 줄이기 위해서 별도의 wiki 페이지를 생성했습니다.

https://github.com/opencloset/opencloset/wiki/barcode
