### ISSUE TITLE
문자 전송 페이지에서 장문 전송을 지원

### ISSUE THREAD

**Issue by keedi** [opencloset/opencloset#392]
현재 문자 전송 페이지에서는 단문만 전송이 가능합니다. 비용 절감 및 대부분의 내용은 단문으로 충분하다는 판단하에 진행한 것이지만 막상 실제로 사용하면서 90바이트 이내로 글을 쓰는 것이 어렵다고 합니다. 내부적으로 장문이 꼭 필요하며 장문을 사용할 수 없어 구성원이 개인적으로 휴대폰을 이용하거나 또는 문자 발송 사이트를 이용하고 있다고 합니다. 따라서 장문을 전송 가능하도록 수정합니다.

**Comment by keedi** [comment]
진행합니다.

**Comment by keedi** [comment]
기존에는 LMS가 아닌 SMS만 전송한다고 고려했기 때문에 데이터베이스 스키마에 메시지를 저장하는 영역이 `VARCHAR(256)`으로 설정되어 있습니다. LMS는 보통 2000바이트(아마도 euc-kr 기준)까지 전송할 수 있기 때문에 현재 스키마는 부족합니다. 문자열 길이는 보내는 어플리케이션에서 처리하기로 하고 `TEXT` 영역으로 저장하는 것이 좋을 듯합니다.

**Comment by keedi** [comment]
opencloset/OpenCloset-Schema#14 이슈를 해결한 이후 계속 진행합니다.

**Comment by keedi** [comment]
OpenCloset::Schema 0.006 버전을 릴리스 했습니다. opencloset/OpenCloset-Schema#14 이슈에 적혀있는대로 실서버에도 적용해야 합니다.

**Comment by keedi** [comment]
처리한 내역은 다음과 같습니다.

- SMS::Send::KR::CoolSMS 1.003 버전을 사용하도록 함
- OpenCloset::Schema 0.006 버전을 사용하도록 함
- UI에서 글자수를 확인 후 전송을 막는 부분을 제거함
- 글자수 확인 API 제거함

**Comment by keedi** [comment]
작업 완료했으므로 이슈 닫습니다. :-)

**Comment by 10001if** [comment]
작업해주셔서 감사합니다. 그런데 확인해보니 44자 이상 작성한 경우에
44자만 발송이 되고 나머지 문자는 발송이 되지 않습니다. 확인 부탁드립니다. :)

![2015-02-13 2 11 03](https://cloud.githubusercontent.com/assets/4696328/6182589/589e4eaa-b38a-11e4-9494-cbf0077eba9b.png)
-> 보낸 문자
![2015-02-13 2 11 27](https://cloud.githubusercontent.com/assets/4696328/6182592/5d8156d8-b38a-11e4-9bda-4351316f0286.png)
-> 받은 문자

**Comment by keedi** [comment]
> 작업해주셔서 감사합니다. 그런데 확인해보니 44자 이상 작성한 경우에
> 44자만 발송이 되고 나머지 문자는 발송이 되지 않습니다. 확인 부탁드립니다. :)

해당 이슈는 sms 데몬을 재기동하지 않아서 발생한 문제입니다. 지난주 금요일 장문 문자 잘 전송되는 것을 @10001if 대표님과 최종 확인 완료했습니다.

**Comment by yongbin** [comment]
참고로 #413 을 진행하는 과정에서도 장문이 정상적으로 전송됨을 확인했습니다.
