### ISSUE TITLE
주문서 상세 페이지에 상태추적 기록을 표시

### ISSUE THREAD

**Issue by yongbin** [opencloset/opencloset#395]
주문서 상세 페이지에 주문서의 상태변화 기록과 각 상태의 통계값을 보여줄수 있는 표를 추가합니다.

#318 에서 진행되어 작성한 https://github.com/opencloset/opencloset/pull/387 을 다시 진행하기 위해서 별도이슈를 분리해서 열었습니다.

**Comment by yongbin** [comment]
![19654f1e-ab0f-11e4-92ba-d511fe949550](https://cloud.githubusercontent.com/assets/52704/6096359/20dc0b64-afd0-11e4-8bfa-312273442780.png)

결과화면은 #387 에서 진행되었던 내용을 참고하면 됩니다. 다만 화면을 2 커럼으로 나누지 않고 하나의 컬럼에 표를 나열하는 방식으로 표현하고 이후에 표를 접을수 있도록 하는 방향으로 결정되었습니다.

**Comment by yongbin** [comment]
![- 2015-02-15 02-31-36](https://cloud.githubusercontent.com/assets/52704/6200474/80dfc4dc-b4bd-11e4-851b-fe1f4e980365.png)

**Comment by keedi** [comment]
PR 확인 진행합니다.

**Comment by keedi** [comment]
#414 PR을 체리피킹한 후 약간 개선했습니다.

- 통계용 테이블 두 개를 각각의 위젯으로 분리
- 통계 테이블에 CSS 적용
- 통계용 위젯에 접힘 기능 추가
- 통계용 위젯은 기본으로 접혀있도록 함

**Comment by keedi** [comment]
구현 완료한 화면은 다음과 같습니다.

![- 2015-02-16 23-33-09](https://cloud.githubusercontent.com/assets/138451/6213567/5f94c502-b634-11e4-904a-82df82ffe52f.png)

접힌 위젯 박스를 열었을 때의 화면은 다음과 같습니다.

![- 2015-02-16 23-33-50](https://cloud.githubusercontent.com/assets/138451/6213569/69505de0-b634-11e4-967c-4b45930b3639.png)

**Comment by keedi** [comment]
완료되었으므로 이슈 닫습니다. :)

**Comment by keedi** [comment]
실서버에 배포 완료했습니다.

**Comment by keedi** [comment]
@10001if 대표님과 확인 완료했습니다. :)

**Comment by keedi** [comment]
다만 수정 이후 반납을 할 수 없는 버그가 발생되었습니다. 증상은 반납 진행 버튼을 누른 다음 반납할 품목 체크박스를 클릭했을때 선택할 수 없는 이슈입니다. 처리한 후 반납에 문제가 없으면 이슈 닫겠습니다.

**Comment by keedi** [comment]
수정 및 배포 완료했습니다. 피드백 확인하겠습니다.

**Comment by keedi** [comment]
order-detail 클래스는 editable로 설정하기 위해 사용한 클래스인데 코드 리팩터링 과정에서 테이블에도 order-detail 클래스 속성을 주는 바람에 테이블 자체가 x-edtiable 객체가 되어 내부 요소를 제대로 클릭할 수 없는 문제가 있었습니다. 이 버그를 수정했습니다.

**Comment by keedi** [comment]
이제 반납 진행에 문제가 없음을 확인 완료했습니다. 이슈 닫습니다. :)
