### ISSUE TITLE
주문서 처리 통계 페이지 추가

### ISSUE THREAD

**Issue by yongbin** [opencloset/opencloset#396]
#318 에서 파생된 #389 PR이 https://github.com/opencloset/OpenCloset-Schema/issues/8 에 변경때문에 수정될 필요가 생겼습니다. 더 이상 #318에서 진행하지 않고 ~~이쪽 이슈에서 별도로~~ 본 이슈에서 진행하겠습니다.

**Comment by yongbin** [comment]
![- 2015-02-22 19-27-38](https://cloud.githubusercontent.com/assets/52704/6322297/6d00f36c-bb54-11e4-828c-e178c0123bbc.png)

**Comment by keedi** [comment]
@yongbin 그림을 붙일때는 가능하면 간단한 설명이라도 부탁드려요. 아무것도 없으면 뜬금없어서 무슨 의미인지 이해하기가 힘듭니다.

**Comment by keedi** [comment]
OpenCloset-Schema 0.008 버전 기준 소요시간

```
[Mon Feb 23 22:05:43 2015] [debug] GET "/stat/status/2015-02-12".
[Mon Feb 23 22:05:48 2015] [debug] 200 OK (5.496368s, 0.182/s).
```

OpenCloset-Schema 0.009 버전 기준 소요시간

```
[Mon Feb 23 22:06:13 2015] [debug] GET "/stat/status/2015-02-12".
[Mon Feb 23 22:06:17 2015] [debug] 200 OK (4.049548s, 0.247/s).
```

제 장비 기준 약 26%의 성능 향상이 있습니다.

**Comment by keedi** [comment]
추가로 기존 PR에서는 30일에 대해서 통계를 내는데 반해 e4b85a4 패치에서는 사용자가 선택한 날을 기준으로 이전 2일 이후 2일, 도합 5일에 대해 주문서 상태 변화 내역을 계산해서 보여줍니다. 일반적으로 31일에 대해 계산할 것이 5일에 대해 계산하기때문에 평균적으로 6배 가량 속도 향상이 있다고 볼 수 있습니다.

더불어 기존 코드에서는 데이터베이스 상수를 이용해서 질의를 보내는데 더 정확하게 datetime_parser를 이용해서 질의를 보낼 수 있도록 수정했습니다.

**Comment by keedi** [comment]
최종적으로 구현 완료한 화면은 다음과 같습니다.

![- 2015-02-23 23-03-02](https://cloud.githubusercontent.com/assets/138451/6329019/2b1b42e8-bbb0-11e4-826f-925d67ee4b83.png)

**Comment by keedi** [comment]
실서버에 배포 완료했습니다.

**Comment by keedi** [comment]
실서버 기준 e4b85a4 패치 적용 전에는 약 7초가 소요되었으며 현재는 약 2.5초 가량 소요됩니다. 만족스러운 속도는 아니지만 사용하는데 큰 지장은 없는 정도이므로 이 정도에서 마무리 짓습니다. 속도 관련해서는 이슈가 있을 경우 별도의 이슈를 열어서 튜닝하도록 합니다.

**Comment by keedi** [comment]
작업 완료했으므로 이슈 닫습니다. :)

**Comment by yongbin** [comment]
> 실서버 기준 e4b85a4 패치 적용 전에는 약 7초가 소요되었으며 현재는 약 2.5초 가량 소요됩니다. 만족스러운 속도는 아니지만 사용하는데 큰 지장은 없는 정도이므로 이 정도에서 마무리 짓습니다. 속도 관련해서는 이슈가 있을 경우 별도의 이슈를 열어서 튜닝하도록 합니다.

자주 보지 않는 분석용 페이지인점을 감안하면, e4b85a4 패치를 적용한 후 2.5초는 납득가능한 수준이라고 생각합니다. e4b85a4 패치내용도 합리적이라고 보입니다.

**Comment by keedi** [comment]
확인 완료했습니다. :)
