### ISSUE TITLE
대여목적의 종류를 정규화해서 입력 받음

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#401]
대여자가 방문예약신청을 할 때 입력하는 대여목적란에 목적을 수정하고 싶습니다.

입사면접
결혼식
대학(원)면접
장례식
사진촬영(웨딩촬영)
세미나
발표
공연(연주회)
축제(행사)
OT
아르바이트
졸업식
입학식

지난 번 만들어 주신 대여목적을 토대로 숫자를 세어본 결과
이상의 목적들은 상세목적이 아닌 기본대여목적에 적는 것이
나중에 목적별 분류하는데 도움이 될 것으로 판단됩니다.

이상의 목적은 이름변경없이 픽스되어 입력할 수 있게하고
기타의 경우에만 구체적인 목적을 받을 수 있도록 했으면 좋겠습니다.

**Comment by keedi** [comment]
진행합니다.

**Comment by keedi** [comment]
@10001if 상기 목록 중 하나를 입력받는 것인지 아니면 복수 개를 입력받는 것인지요?

**Comment by keedi** [comment]
확인 완료되면 다시 진행합니다. 일단 보류합니다.

**Comment by 10001if** [comment]
하나입니다. ^^

나의 iPhone에서 보냄

2015. 2. 13. 오전 3:31 Keedi Kim <notifications@github.com> 작성:

@10001if <https://github.com/10001if> 상기 목록 중 하나를 입력받는 것인지 아니면 복수 개를 입력받는
것인지요?

—
Reply to this email directly or view it on GitHub
<https://github.com/opencloset/opencloset/issues/401#issuecomment-74124875>.

**Comment by keedi** [comment]
사용자가 복수 개가 아닌 단 하나를 선택하는 것이므로 콤보 박스 형태로 처리할까 싶습니다. 확인요망 라벨을 제거합니다.

**Comment by keedi** [comment]
@10001if 더불어 현재 대여 목적과 대여 상세 목적이 있는데 기타일 경우에만 따로 대여 목적을 입력받는 것은 애매한 것 같습니다. 아예 상기 기술하신 항목에 기타를 추가한 다음 이 경우도 자연스럽게 대여 상세 목적을 입력하도록 유도하는 것이 나을 것 같은데 어떻게 생각하시는지요?

**Comment by 10001if** [comment]
네! 좋은 생각인 것 같습니다. 저도 좀 애매하다고 생각하고 있었거든요~

나의 iPhone에서 보냄

2015. 2. 13. 오전 8:01 Keedi Kim <notifications@github.com> 작성:

@10001if <https://github.com/10001if> 더불어 현재 대여 목적과 대여 상세 목적이 있는데 기타일 경우에만
따로 대여 목적을 입력받는 것은 애매한 것 같습니다. 아예 상기 기술하신 항목에 기타를 추가한 다음 이 경우도 자연스럽게 대여 상세
목적을 입력하도록 유도하는 것이 나을 것 같은데 어떻게 생각하시는지요?

—
Reply to this email directly or view it on GitHub
<https://github.com/opencloset/opencloset/issues/401#issuecomment-74172393>.

**Comment by keedi** [comment]
진행합니다.

**Comment by keedi** [comment]
처리한 내역은 다음과 같습니다.

- 대여 목적을 정규화해서 chosen 콤보 박스로 입력 받도록 함
- 상세 대여 목적을 반드시 입력해야 하도록 점검함
- visit 페이지 및 visit2 페이지 모두 적용

**Comment by keedi** [comment]
구현 완료한 화면은 다음과 같습니다.

![- 2015-02-13 17-17-09](https://cloud.githubusercontent.com/assets/138451/6184420/a974f83c-b3a4-11e4-8aa5-08018d53f4dc.png)

**Comment by keedi** [comment]
기타 항목도 있기도 하고, 대여 목적에서 고를 수 있는 내용이 한정되었으므로 상세 대여 목적을 무조건 입력해야 하도록 수정했습니다. 참고 바랍니다.

**Comment by keedi** [comment]
작업 완료했으므로 이슈 닫습니다.

**Comment by 10001if** [comment]
상견례, 모의면접, 인턴면접 추가 요청드립니다. 모의면접, 인턴면접은 대학원면접 아래에 붙여주시면 더 좋을 것 같습니다. ^^

**Comment by keedi** [comment]
@10001if 추가 완료했습니다.

**Comment by keedi** [comment]
실서버에 배포 또한 완료했습니다.
