### ISSUE TITLE
예약시 예상 대여 비용을 보여줌

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#407]
방문예약시 착용일자를 받고
3박4일 보다 추가되는 경우에 예상되는 대여 금액을 표시해주는 단계가 추가로 신설되었으면 합니다.
물론, 품목과 대여금액도 모두 표시되었으면 좋겠습니다.

**Comment by keedi** [comment]
@10001if 착용일자는 단순히 예상 대여 비용을 보여주기 위한 용도인지요? 아니면 실제로 시스템에서 착용일자를 저장해서 쓰려고 하시는 것인지요?

**Comment by 10001if** [comment]
착용일자에 대해 논란이 있어서 어제부터 오늘까지 모든 분들에게 의견을 물었는데요.
결론적으로 착용일자는 대여할 때 칠요한 정보라는 것이 중론이네요.
착용일자 관련한 내용은 이슈를 따로 작성하도록 하겠습니다. ㅠ

**Comment by keedi** [comment]
착용일자가 시스템에 꼭 필요한 것이라고 한다면 예약시 예상 대여 비용을 보여주는 기능은 오히려 착용일자보다 우선순위가 떨어집니다. 다르게 말하면 착용일자를 입력 받고 시스템에서 사용할 수 있는게 우선이라는 의미입니다. #411 항목을 우선 처리하고 이후 처리하도록 합니다.

**Comment by keedi** [comment]
2차 오픈에서 일단 제거합니다. 착용일자 기능을 구현 완료한 후 여전히 필요한지 그때 확인하도록 합니다.

**Comment by 10001if** [comment]
@keedi 내부적으로 한번 더 논의해본 뒤 말씀드리도록 하겠습니다.

**Comment by keedi** [comment]
착용 일자 구현이 사실 완료 되었습니다. 진행합니다.

**Comment by keedi** [comment]
pass~

**Comment by keedi** [comment]
@aanoaa: 어디까지나 예상 대여 비용이니 실제와 다를수는 있을 것입니다. 다만 검증 가능하게 어떤식으로 계산 하는지를 이슈트래커에 정리해주시면 확인하기 좋을 것 같습니다.

**Comment by aanoaa** [comment]
대여일이 `06/15` 이고 대여기간이 3박 4일이면, `15,16,17,18` 일 입니다.
18일까지 반납을 해야 하는데, 착용일이 20일이고 20일 반납한다고
가정한다면, `19,20` 일 이틀을 연장(연체) 한 것이 되니까 이틀연장한
값을 계산해서 보여주면 되는건가요?

**Comment by aanoaa** [comment]
대여할 옷의 종류를 선택할때마다
예상비용을 계산해서 보여주면 어떨까 싶습니다.

연장일에 대한 계산은 그 다음 단계에서 하고요.

**Comment by aanoaa** [comment]
칸이 좁으니 우측이나 좌측에 보여주면 좋겠는데 모바일에서 하는 경우가
많으니까 모바일에서의 테스트도 이루어져야 하겠습니다.

**Comment by keedi** [comment]
착용일이 3박 4일에서 벗어나는 경우 연장을 고려해서 금액을 보여줄지 여부는 @10001if 님이 판단 및 결정해야 할 것 같습니다.

@10001if 님께서 특별히 선호하는 예상 대여비용 위치가 없기 때문에 우선 작업하기 용이한 쪽에 구현하시고 이후 피드백을 받으면 될것 같습니다. @10001if 대표님께서는 선호하는 위치가 있다면 지금 언급을 해주시면 좋겠죠 ㅎㅎ

**Comment by keedi** [comment]
다른 부분은 모르겠는데 현재 위/아래 한벌을 빌릴 경우 넥타이는 무료로 알고 있습니다. 이 부분을 고려하셔야 할 것 같습니다. 현재 데이터베이스상 타이는 0원으로 책정되어 있긴 합니다.

**Comment by keedi** [comment]
하긴 굳이 예상 금액 측정에 데이터베이스를 참고할 필요는 없겠지요. 그리고 위/아래 한벌이 아닌 경우는 타이 비용을 청구한다고 합니다.

**Comment by 10001if** [comment]
선호하는 위치는 없습니다.

**Comment by aanoaa** [comment]
연장일에 대한 값은 따로 보여줘야 합니다.

**Comment by aanoaa** [comment]
@10001if 각 의류별 대여비용을 알아야 합니다.

- 자켓
- 팬츠
- 셔츠
- 타이
- 구두
- 벨트
- 스커트
- 블라우스

**Comment by 10001if** [comment]
자켓 10000
팬츠 10000
셔츠 5000
블라우스 5000
구두 5000
타이 2000 (단, 세트 대여시 무료)
벨트 2000
입니다.

**Comment by aanoaa** [comment]
어떻게 해야 세트인가요?

**Comment by aanoaa** [comment]
`자켓 + 팬츠` 면 타이가 0 원 입니다.

**Comment by aanoaa** [comment]
![screenshot-localhost 5001 2015-06-17 14-31-08](https://cloud.githubusercontent.com/assets/170528/8200276/8f9c3474-14fd-11e5-933d-2781569064fa.png)

이런식으로 보여주면 어떨까요?
`예상연체비`는 착용일이 대여기간의 범위를 넘어갈때에만 보여주고요.

**Comment by 10001if** [comment]
기본 대여비
추가 연장비
로 부탁드립니다 ^^

**Comment by keedi** [comment]
기본 대여비와 추가 연장비를 더한 최종 금액도 보여주어야 할 것입니다. 대여자는 본인이 추가 연장 한다는 사실도 모르고 있을수 있기 때문입니다. @10001if 대표님께서는 두 가지 합한 금액에 대한 라벨을 무엇으로 표시할지도 @aanoaa 님께 알려주셔야 할 것 같습니다.

**Comment by aanoaa** [comment]
50,000(총대여비)

----------------------------------

    50,000(총대여비) = 30,000(기본대여비) + 20,000(추가연장비)
* 대여기간은 3박4일 입니다. 너무 일찍 대여하시면 대여기간에 따른 연장료가 발생합니다.

이런식으로 보여지길 원합니다.

**Comment by aanoaa** [comment]
![screenshot-localhost 5001 2015-06-18 10-07-21](https://cloud.githubusercontent.com/assets/170528/8222116/e63c786c-15a1-11e5-84ad-9f12b47d507b.png)
![screenshot-localhost 5001 2015-06-18 10-07-42](https://cloud.githubusercontent.com/assets/170528/8222119/eb469072-15a1-11e5-8091-af5df4dccf2a.png)

**Comment by aanoaa** [comment]
문제가 있습니다.
모바일에서는 대여할 의류를 선택할 수 없습니다.
html 태그 문제 + responsible design 때문인 것 같은데 찾아서 해결해야 합니다.

![2015 6 18 10 10 45](https://cloud.githubusercontent.com/assets/170528/8222153/6d0b20f0-15a2-11e5-88b5-63517fa5c650.png)

**Comment by aanoaa** [comment]
아이폰 4s 를 기준으로 테스트중인데
해상도는 `640 x 960` 이고 브라우저 해상도는 `320 x 480` 입니다.

firefox 등에서 테스트할때에 `320 x 480` 으로 하면 같은 화면을 볼 수 있습니다.

**Comment by aanoaa** [comment]
firefox 에서 테스트할때에는 같은 해상도에서 의류선택이 가능하지만, 실제 단말기기에서는 그렇지 않습니다.
user-agent 를 바꿔서 테스트해보면 같은 결과를 기대할 수 있을 것 같습니다.

![2015-06-18 10 26 27](https://cloud.githubusercontent.com/assets/170528/8222306/855e7920-15a4-11e5-8e7f-4ef93095b3ea.png)

**Comment by aanoaa** [comment]
user-agent 를 바꿔봐도 똑같습니다.

**Comment by aanoaa** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta

**Comment by aanoaa** [comment]
<meta content='width=device-width, initial-scale=1.0' name='viewport' />

로 되어 있는데, firefox 에서는 device-width 가 단말기기랑 다르지 않을까 하고 추측만 해봅니다.

**Comment by aanoaa** [comment]
`initial-scale=0.5` 로 하면 모바일에서 해상도가 2배가 됩니다.
개인적으로는 더 보기 편한데요?
한번 고려해볼만 합니다.

그리고 인증번호 입력란이 핸드폰번호 입력과 같이 숫자만 가능하다면 더 좋겠습니다.

**Comment by aanoaa** [comment]
> 그리고 인증번호 입력란이 핸드폰번호 입력과 같이 숫자만 가능하다면 더 좋겠습니다.

    inputmode="numeric"

를 추가하였지만 아직 iOS 의 크롬에서는 동작하지 않습니다.

**Comment by aanoaa** [comment]
직접 단말기기에서 태그 바꿔가면서 테스트하는 수밖에 없습니다.
아래 두개로는 여전히 대여의류를 선택할 수 없습니다.

    %meta{:content => "width=device-width, height=device-height, initial-scale=1.0", :name => "viewport"}
    %meta{:content => "width=device-width, initial-scale=0.5", :name => "viewport"}

**Comment by aanoaa** [comment]
오랜만에 느껴보는 단말기 문제입니다. 아 고통..

**Comment by aanoaa** [comment]
이 이슈 전에도 아이폰 4s 에서 대여의류를 선택할 있는지 먼저 확인해봐야 합니다.

**Comment by aanoaa** [comment]
이전부터(지금도) 의류선택과 대여목적은 입력할 수 없었습니다.
chosen 라이브러리를 사용한 것들이 아닐까 합니다.

**Comment by aanoaa** [comment]
`<meta name="viewport"...>` 태그 없이 PC 화면과 동일하게 보여지게 해도 대여목적과 의류선택은 여전히
iOS - 크롬에서 선택할 수 없습니다.

**Comment by aanoaa** [comment]
https://github.com/harvesthq/chosen/pull/1388

chosen 라이브러리는 모바일 기기를 지원하지 않습니다.
근데 사람들이 어떻게 예약한거지..

**Comment by aanoaa** [comment]
예약한 사람들의 user-agent 별로 통계를 내어보는 것도 좋겠습니다.

**Comment by aanoaa** [comment]
http://brianreavis.github.io/selectize.js 는 모바일에서도 동작한다고 하네요.

**Comment by aanoaa** [comment]
모바일기기 지원은 #485 에서 따로 진행하도록 하겠습니다.

**Comment by keedi** [comment]
@aanoaa 저장소에 없는 파일중 혹시 로컬 버전과 다른 항목이 있는지 체크해보신 다음 서버쪽 파일을 땡겨와보시고 확인 부탁드립니다.

**Comment by keedi** [comment]
> 예약한 사람들의 user-agent 별로 통계를 내어보는 것도 좋겠습니다.

일단 google analytics가 들어가 있으니 구글 관리 페이지에서 확인이 가능할 것 같습니다. visit 사이트 쪽 id는 `UA-57477360-1` 입니다.

**Comment by keedi** [comment]
아래는 크롬 동작 화면입니다. 잘 동작하는 것으로 보입니다.

![default](https://cloud.githubusercontent.com/assets/138451/8223600/084a53bc-15b5-11e5-868d-1556697fdc21.png)

아래는 아이폰 4S에서 동작 화면입니다. 역시 잘 동작하는 것으로 보입니다.

![15 6 18 11 44 51](https://cloud.githubusercontent.com/assets/138451/8223606/237b4c90-15b5-11e5-9b48-3804ffb94d38.png)

**Comment by aanoaa** [comment]
아이폰의 크롬이요

**Comment by keedi** [comment]
잘됩니다.

![img_1155](https://cloud.githubusercontent.com/assets/138451/8223689/58616434-15b6-11e5-992a-d453eb550a25.jpg)

**Comment by aanoaa** [comment]
서버와 제 로컬의 static 파일이 달라서인지는 모르겠는데 제 환경에서는
아이폰 사파리에서도 안되네요(안보입니다). 서버랑 비교해보고 어떤파일이 어떻게
다른지 확인해보겠습니다.

**Comment by aanoaa** [comment]
테마에 포함된 css 파일을 바꿔주고 해결되었습니다. 자세한 내용은 #485

**Comment by keedi** [comment]
모바일 및 피씨에서 모두 잘 동작하는 것 확인했습니다.

**Comment by keedi** [comment]
서버에 배포 및 실서버 대상 테스트 또한 완료했습니다.
이슈 닫습니다. :-)

**Comment by 10001if** [comment]
금액이 나타나는 숫자 부분을 30000 -> 30,000원 으로 변경 요청드립니다.
가독성이 훨씬 높아질 듯 합니다. :)

**Comment by aanoaa** [comment]
아이폰 사파리에서는 `toLocaleString()` 이 제대로 동작하지 않는 것 같습니다.
내장 함수대신에 금액 포맷팅 후에 보여줘야 합니다.

또 `원` 을 붙여달라고 합니다.
예를들면,

    20,000원 = 10,000원 + 10,000원

**Comment by keedi** [comment]
서버에 배포 및 확인 완료했습니다. 이슈 닫습니다. :-)

**Comment by 10001if** [comment]
확인완료하였습니다.
