### ISSUE TITLE
의류 정보페이지의 신체 치수 평균값 하단에 최근 5개의 주문서에 기입된 신체 치수를 보여줌

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#410]
ex) ~/clothes/P0B1

![2015-02-13 2 27 15](https://cloud.githubusercontent.com/assets/4696328/6182706/f5fdf34c-b38c-11e4-8187-b98380439228.png)
이상의 화면에서 보듯이,
더셔츠스튜디오의 바지는 2번 대여되었고
따라서 2번의 대여기록이 평균으로 계산되었습니다.

하지만 2번의 신체 사이즈 모두를 하단에 바로 보여줄 수 있으면 더 좋겠다는 내부 의견이 있어서 요청드립니다.

**Comment by keedi** [comment]
@10001if 음. 지금은 2개가 있어서 그러한데 그러면 10개 또는 50회이상 대여했을 때는 어떻게 하는지요? 50개를 다 보여주면 되는지요?

**Comment by 10001if** [comment]
아~ 네! 혹시 최근 5개의 데이터만 보여줄 수 있다면 그렇게 보여주실 수 있을까요?

**Comment by keedi** [comment]
진행합니다.

**Comment by keedi** [comment]
구현 완료한 화면은 다음과 같습니다.

![j001 - 2015-02-16 16-22-59](https://cloud.githubusercontent.com/assets/138451/6208223/23bdaae4-b5f8-11e4-807b-d3cb481ab6ea.png)

**Comment by keedi** [comment]
작업 완료했으므로 이슈 닫습니다. 더불어 확인요망 라벨을 붙입니다.

**Comment by keedi** [comment]
실서버에 배포 완료했습니다.

**Comment by keedi** [comment]
@10001if 님과 확인 완료했습니다. :)
