### ISSUE TITLE
대여자에게 착용 일자를 입력 받고 시스템에서 열람 및 수정이 가능해야 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#411]
어제 키디님이 말씀해주신 소중한 이야기를 듣고 정신을 번쩍차리고 다시 정리해서 말씀드립니다.
여러사람들의 의견을 종합해보면 착용일자는 필요하고, 착용일자 정보를 아는 것은 대여를 하는데 직/간접적인 도움이 된다고 판단이 됩니다.

착용일자의 필요성이 계속 제기되고 있음에도 이를 무시하고 그냥 진행한다면 언젠가는 착용일자 항목을 추가해야 하는 상황이 발생할 것 같습니다.

방문 예약시 착용일자를 받고, 이 정보가 대여자 정보란에도 보여져야 합니다.
들어가야 할 순서는 크게 중요한 것은 아니나, 대여목적 전 후로 삽입되는 것이 가장 자연스러워 보입니다.

요청 부탁드립니다. ^^

**Comment by keedi** [comment]
진행합니다.

**Comment by keedi** [comment]
본 기능은 스키마 수정이 필요합니다. OpenCloset-Schema 저장소에서 관련 이슈를 연 다음 처리 후 진행하도록 합니다.

**Comment by keedi** [comment]
opencloset/OpenCloset-Schema#18 항목에서 스키마 수정을 완료했습니다. 작업을 위해서는 가장 최신 버전인 OpenCloset-Schema 0.008 버전을 설치해야 합니다.

더불어 해당 이슈에 있는대로 기존 데이터베이스의 스키마를 변경해야 합니다.

**Comment by keedi** [comment]
진행합니다.

**Comment by keedi** [comment]
우선 실서버에 다음 처리를 미리 해두었습니다.

- 스키마 변경
- OpenCloset::Schema 0.008 버전 설치

**Comment by keedi** [comment]
처리한 내역은 다음과 같습니다.

- OpenCloset::Schema 버전을 0.008로 설정
- 주문서와 사용자 정보 API에서 wearon_date 인자를 처리할 수 있게 수정
- 방문 예약 페이지에서 착용 날짜를 입력할 수 있게 함
- 직원 전용 방문 예약 페이지에서 착용 날짜를 입력할 수 있게 함
- 사용자 프로필 페이지에서 착용 날짜를 확인하고 수정할 수 있게 함
- 주문서 페이지에서 착용 날짜를 확인할 수 있게 함

**Comment by keedi** [comment]
방문 예약 페이지에 적용된 내역은 다음과 같습니다.

![- 2015-02-16 21-37-28](https://cloud.githubusercontent.com/assets/138451/6212059/5616f8ca-b624-11e4-84ec-d99780ca315c.png)

날짜는 datepicker를 이용해서 선택합니다.

![- 2015-02-16 21-38-03](https://cloud.githubusercontent.com/assets/138451/6212066/634acf62-b624-11e4-8310-79463f7c6733.png)

**Comment by keedi** [comment]
사용자 프로필 페이지에 적용한 화면은 다음과 같습니다.

![- 2015-02-16 21-35-23](https://cloud.githubusercontent.com/assets/138451/6212072/75654b64-b624-11e4-828a-ef016298436e.png)

bootstrap-xeditable 플러그인은 날짜 선택시 datepicker를 사용하지 못하기 때문에 combodate 형식으로 처리합니다.

![- 2015-02-16 21-41-53](https://cloud.githubusercontent.com/assets/138451/6212082/a482f900-b624-11e4-8dd9-0aa84415884c.png)

**Comment by keedi** [comment]
주문서 페이지에 적용한 화면은 다음과 같습니다.

![- 2015-02-16 21-34-48](https://cloud.githubusercontent.com/assets/138451/6212093/c4584f14-b624-11e4-97da-f594cd8ff2a1.png)

딱히 필요 없을 것으로 보아 주문서에서는 열람만 가능하도록 구현합니다.

**Comment by keedi** [comment]
작업 완료했습니다. 이슈 닫습니다. :)

**Comment by keedi** [comment]
실서버에 배포 완료했습니다. :)

**Comment by keedi** [comment]
@10001if 님과 확인 완료했습니다. :)
