### ISSUE TITLE
문자 메세지 발송 요청드립니다.

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#413]
저희가 다음 주 화요일(17일)만 영업을 하고 구정연휴에 접어들었다가, 토요일(21일)은 쉬기로 했습니다. 그래서 이번주 목금토(12일, 13일, 14일) 대여한 분들은 다음 주 화요일(17일)에 반납하지 않으면 반납을 하실 수가 없는데요. 

그래서 목금토(12일, 13일, 14일)에 대여를 진행하신 분들 중에 현재 대여중인 분들에게 문자를 일괄로 발송하고 싶습니다.

안녕하세요. 열린옷장입니다. 
귀하의 대여의류 반납일은 2월 17일 (화)입니다. 혹시 연체가 될 경우 설연휴 관계로 
2월 24일 (화)에야 반납이 가능하시므로 7일 연체료가 부과됩니다. 반드시 반납기한 엄수를 부탁드립니다.

월요일 출근하셔서 발송해주시면 될 것 같아요. 

감사합니다. ^^

**Comment by yongbin** [comment]
대여시점을 기준검색과, 반남시점 기준검색 두가지로 확인한결과 동일한 결과를 얻었습니다.

```SQL
SELECT
	a.id
	,b.name
	,c.phone
	,d.name
	,a.`rental_date`	
FROM `order` AS a
		INNER JOIN `user` AS b ON a.`user_id` = b.id
		INNER JOIN `user_info` AS c ON c.`user_id` = b.id
		INNER JOIN `status` AS d ON a.`staff_id` = d.id
WHERE a.`rental_date` >= '2015-02-12' AND a.`rental_date` < '2015-02-15' AND d.name = '대여중'


SELECT
	a.id
	,b.name
	,c.phone
	,d.name
	,a.`rental_date`
	,a.`target_date`
FROM `order` AS a
		INNER JOIN `user` AS b ON a.`user_id` = b.id
		INNER JOIN `user_info` AS c ON c.`user_id` = b.id
		INNER JOIN `status` AS d ON a.`staff_id` = d.id
WHERE a.`target_date` >= '2015-02-16' AND a.`target_date` < '2015-02-18' AND d.name = '대여중'
```

발송해야할 주문서는 주문서 번호 2151번 강XX님과 2176 김XX님 두건입니다.

**Comment by yongbin** [comment]
수량이 얼마되지 않기때문에 사이트에 있는 보내기 기능을 이용해서 발송하겠습니다.  두명에게 발송하기전에 제 핸드폰으로 발송해서 장문메세지 처리에 이상없을을 확인했고, 발송완료했습니다.

**Comment by aanoaa** [comment]
어라 장문메세지 발송 되나여?

**Comment by yongbin** [comment]
> 어라 장문메세지 발송 되나여?

넵 #392 에서 처리되었습니다
