### ISSUE TITLE
시간표의 주문서 별로 착용 일자를 표시

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#421]
![2015-02-24 6 16 47](https://cloud.githubusercontent.com/assets/4696328/6346367/abe27390-bc52-11e4-90a8-b98969233c73.png)
이상처럼 착용일자가 시간표에서도 보여지도록 수정 요청드립니다. :)

**Comment by keedi** [comment]
진행합니다.

**Comment by keedi** [comment]
시간표 페이지에서 각 개별 주문서 별로 착용 날짜를 열람할 수 있도록 표시합니다. 이때 주문서의 상태에 따라 주문서에 착용 날짜 정보가 없을 수 있으므로 이 때는 사용자 정보에서 확인한 착용 날짜를 보여줍니다.

**Comment by keedi** [comment]
구현 완료한 화면은 다음과 같습니다.

![- 2015-02-25 17-24-06](https://cloud.githubusercontent.com/assets/138451/6367204/359e50f2-bd13-11e4-987c-e6644a583f7a.png)

**Comment by keedi** [comment]
작업 완료했으므로 이슈 닫습니다.

**Comment by keedi** [comment]
배포 및 확인 완료했습니다. :)
