### ISSUE TITLE
의류 정보에서 최근 대여 기록의 각 항목이 무엇을 의미하는지 이해하기 어려움

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#422]
의류정보화면(~/clothes)에서 의류 정보의 평균값 아래에 치수이름이 들어가야 합니다.

![2015-02-24 6 25 00 5](https://cloud.githubusercontent.com/assets/4696328/6346928/2850cd56-bc57-11e4-9a41-c28a7e25986d.png)
이상의 그림처럼 평균값 하단에 치수가 뜻하는 이름이 들어가야 합니다.
그림의 이름은 예시로 적어놓았습니다.

**Comment by keedi** [comment]
좀 더 나은 디자인이 있을 수 있을 것 같은데 고민해서 논의해보겠습니다.

**Comment by keedi** [comment]
![j0ak - 2015-03-01 15-54-36](https://cloud.githubusercontent.com/assets/138451/6429711/ae646270-c028-11e4-85ce-699c0b09512e.png)

아예 기존 의류 정보 위에 대여 정보 라는 섹션을 만들고 표 형태로 보여주는 것은 어떠실런지요?

**Comment by keedi** [comment]
확인 후 진행합니다. :)

**Comment by keedi** [comment]
@10001if 이런 식으로 보여줄까 싶은데 어떻게 생각하시는지요?

![j0ak - 2015-03-01 18-12-35](https://cloud.githubusercontent.com/assets/138451/6430053/e6faf1c2-c03b-11e4-9776-747245bba552.png)

**Comment by keedi** [comment]
상기 디자인의 경우 녹색, 파란색, 주황색 라벨을 빼고 싶으면 빼고 싶다고 확인해주세요. 이미 각 항목별로 테이블 헤더가 있는 상태라 색상 구분이 의미가 있는지는 모르겠습니다.

**Comment by 10001if** [comment]
훨씬 보기 좋네요! 좋습니다 ^^ 그리고 색상은 그냥 두어부셔도 될 것 같아요. 그래도 구분되어 있으면 눈에 더 편하게 보이는 것 같아서요. ^^

**Comment by keedi** [comment]
수정 및 배포 완료했습니다. 이슈 닫습니다.
