### ISSUE TITLE
의류 정보에서 최근 대여 기록에 부분 반납으로 인한 중복 정보가 보임

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#423]
![default](https://cloud.githubusercontent.com/assets/4696328/6346955/6208f190-bc57-11e4-9a8b-125667f8108e.png)

~/clothes/J0AK
김성환님이 기증하신 J0AK 의류의 경우 김재혁이라는 대여자가 부분반납을 여러번 진행하며 대여기록이 여러번 남아있게 되었습니다. 따라서 최초 대여시에만 대여기록이 남을 수 있도록 중복값은 제거해주시기 바랍니다. :)

**Comment by keedi** [comment]
수정 및 배포 완료했습니다. 이슈 닫습니다.
