### ISSUE TITLE
의류 정보에서 최근 대여 기록을 보여줄 때 어울림 여부도 표시

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#424]
의류정보화면(~/clothes)에서 대여기록의 BEST-FIT 여부를 보여주어야 합니다.

![2015-02-24 6 25 00](https://cloud.githubusercontent.com/assets/4696328/6347004/c10e8f4c-bc57-11e4-897d-c983ffc049f5.png)

그림과 같이 대여기록 중 베스트핏인 경우의 기록은 따로 표시를 하여 베스트 핏임을 알 수 있도록 보여주어야 합니다. :)

**Comment by keedi** [comment]
진행합니다.

**Comment by keedi** [comment]
수정 및 배포 완료했습니다. 이슈 닫습니다.
