### ISSUE TITLE
통계의 인기 의류 및 수량 페이지에서 의류를 남성, 여성 기준으로 나누어 자료를 표현

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#425]
현재는 기증자의 성별만 구분하여 확인할 수 있으며 의류별로 남성의 의류인지 여성의 의류인지는 확인 할 수 없습니다. 향후에는 남성, 여성으로 의류의 성별을 구분할 수 있어야 합니다.

**Comment by keedi** [comment]
스키마 변경이 필요한 이슈입니다. OpenCloset-Schema 저장소에서 진행해야 합니다.

**Comment by keedi** [comment]
opencloset/OpenCloset-Schema#21 항목에서 처리합니다.

**Comment by keedi** [comment]
opencloset/OpenCloset-Schema#21 항목에서 확인했더니 이미 스키마상은 지원하고 있었으며 웹 응용에서도 의류 등록 시점에 성별을 집어 넣고 있었습니다.

**Comment by keedi** [comment]
이미 의류 정보 페이지에서는 해당 의류에 적합 성별을 보여주고 있으며 수정 역시 가능한 상태입니다.

![screenshot-monster silex kr 7730 2015-04-08 16-09-28](https://cloud.githubusercontent.com/assets/138451/7040401/d37554c6-de09-11e4-871b-0cf783c814dc.png)

**Comment by keedi** [comment]
어떤 부분에서 의류의 남녀 구분이 안되는지, 그래서 어떻게 수정되면 더 나을지를 확인해야 합니다.

**Comment by keedi** [comment]
제목을 변경했습니다.

최종 원하는 결과는 다음과 같습니다.

- 통계 -> 인기의류 페이지에서 의류를 남자/여자 구분해서 통계 자료를 표현함
- 통계 -> 수량 페이지에서 의류를 남자/여자 구분해서 통계 자료를 표현함

**Comment by keedi** [comment]
진행합니다.

**Comment by keedi** [comment]
일단 급하진 않다고 전해들었습니다. 마일스톤에서 계속 진행할지 말지 여부는 다시 확인 후 정리하겠습니다.

**Comment by keedi** [comment]
진행합니다.

**Comment by keedi** [comment]
매우 묵은 이슈입니다. 다시 진행합니다.

**Comment by keedi** [comment]
데이터베이스에서 무결성을 위해 의류 자료를 점검해보았습니다. 일단 의류중 성별을 표시하지 않은 의류가 얼마나 되는지 확인해보았습니다. 이 때 사용한 데이터베이스 질의는 다음과 같습니다.

```sql
SELECT * FROM `clothes` WHERE NOT ( gender = 'male' OR gender = 'female' );
```

다행히 현재 27건만 성별 표시를 하지 않은 것으로 보입니다. 해당 의류 목록은 다음과 같습니다.

- A02D
- A0MD
- B037
- E00A
- E0H7
- J05H
- P0OV
- P0V1
- P0VA
- P163
- P19N
- S017
- S07E
- S083
- S09Y
- S0G2
- S0LE
- S0QA
- S0U6
- S0V4
- S0X0
- S10L
- S132
- T0H7
- T0HZ
- T0J9
- T0KQ

**Comment by keedi** [comment]
@10001if:

상기 의류에 대해서는 열린옷장에서 성별을 기입해주셔야 합니다.

**Comment by keedi** [comment]
전체 의류는 현 시점 기준으로 5763건이며 이중 27건을 제외한 5736건은 성별이 제대로 기입되어 있으므로 상기 예외 의류는 신경쓰지 않고 현 이슈를 진행하도록 합니다.

**Comment by keedi** [comment]
금일 중 마무리될 예정입니다.

**Comment by keedi** [comment]
처리한 내역은 다음과 같습니다.

- 통계 - 인기 의류 페이지를 성별로 분리해서 열람할 수 있도록 함
- 통계 - 수량 페이지를 성별로 분리해서 열람할 수 있도록 함

**Comment by keedi** [comment]
금일 6시 이후에 배포 진행하겠습니다.

**Comment by keedi** [comment]
배포 완료했습니다. 이슈 닫습니다.

**Comment by keedi** [comment]
@10001if 확인 후 피드백 부탁드립니다.

**Comment by 10001if** [comment]
확인하였습니다. 그런데 요청사항이 있습니다. 폐기나 분실처럼 현재 보유하고 있지 않은 의류의 수량은 뺀 합계를 보고 싶다는 의견이 많아서요. 분실, 페기, 대여불가를 뺀 수량의 합계를 첫화면에서 보고 싶습니다. 이따 찾아뵙고 다시 설명드리겠습니다.

**Comment by keedi** [comment]
내용 자세하게 설명 부탁드립니다.

**Comment by keedi** [comment]
#538 이슈와 헷갈리신 것 같습니다. 현재 이슈는 닫겠습니다.
