### ISSUE TITLE
문자 메세지를 보낼 때 단문인지 장문인지 확인 할 수 있게함

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#426]
현재는 44자 이내이면 단문으로, 44자 이상이면 장문으로 전환되는데,
문자를 보낼 때 현재 44자를 넘었는지 안넘었는지 확인할 수 없습니다.
확인이 가능하도록 기능을 추가해 주시면 감사하겠습니다. :)

**Comment by keedi** [comment]
진행합니다.

**Comment by keedi** [comment]
처리한 내역은 다음과 같습니다.

- 번들 자바스크립트 라이브러리에 문자열의 너비(screen width)를 계산하는 메소드 추가
- 해당 메소드를 이용해서 사용자가 입력한 문자 메시지의 길이를 보여주어 LMS인지 SMS인지 분간 할 수 있도록 함

**Comment by keedi** [comment]
구현 완료한 화면은 다음과 같습니다.

![- 2015-02-24 22-48-15](https://cloud.githubusercontent.com/assets/138451/6350450/48626af8-bc77-11e4-82c6-cb72f7964f7f.png)

**Comment by keedi** [comment]
작업 완료했으므로 이슈 닫습니다. :)

**Comment by keedi** [comment]
배포 완료했습니다. :)

**Comment by keedi** [comment]
배포 및 확인 완료했습니다. :)
