### ISSUE TITLE
수량 통계 화면의 품목별 검색 기준 변경

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#427]
![2015-02-24 7 32 38](https://cloud.githubusercontent.com/assets/4696328/6347543/048b9f7c-bc5c-11e4-9215-e9fe60e4a188.png)

**Comment by 10001if** [comment]
벨트 - 길이
블라우스 - 가슴둘레
코트 - 중동
자켓 - 중동
원피스 - 중동
팬츠 - 허리
셔츠 - 가슴
슈즈 - 길이(발크기)
스커트 - 엉덩이둘레
타이 - 색상
조끼 - 중동

으로 변경 요청드립니다. :)

**Comment by aanoaa** [comment]
중동이 윗배둘레인가요?

**Comment by keedi** [comment]
@10001if 중동이라는 용어는 최대한 안쓰는게 좋을 것 같습니다. 이미 중동에서 세분화 되었기 때문에 가능하면 윗배 둘레와 배꼽 둘레라는 말을 썼으면 합니다.

@aanoaa 그러고보니 저도 지금 말씀하신 중동이 윗배 둘레를 말씀하시는건지 배꼽 둘레를 말씀하시는건지 모르겠군요. 하지만 아마도 현재 배꼽 둘레 정보는 스키마에만 존재하고 데이터는 없기 때문에 윗배 둘레를 의미하는게 아닐까 싶습니다.

**Comment by aanoaa** [comment]
#319 에 이어서 작업합니다.

품목 | 기준
-----|-----
벨트 | 길이
블라우스 | 가슴둘레
코트 | 윗배둘레
자켓 | 윗배둘레
원피스 | 윗배둘레
팬츠 | 허리둘레
셔츠 | 가슴둘레
슈즈 | 발크기
스커트 | 엉덩이둘레
타이 | 색상
조끼 | 윗배둘레

**Comment by keedi** [comment]
작업이 완료되었을 때의 최근의 프로세스입니다. 참고해주세요. :)

----

실서버에 배포가 필요하면 배포대기 라벨을 붙여주세요.
최종 @10001if 님의 피드백이 필요하면 확인요망 라벨을 붙여주세요.

상기 두 라벨이 붙었을때는 이슈 닫아주세요.

이후 배포가 완료되면 배포대기 라벨을 지워주세요.
최종 @10001if 님의 피드백이 끝나면 확인요망 라벨을 제거해주세요.

**Comment by 10001if** [comment]
네! 알겠습니다. :)

**Comment by keedi** [comment]
배포 완료했습니다. :)
