### ISSUE TITLE
방문 예약의 착용 날짜 양식 위치 변경

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#430]
방문예약 페이지에서 착용날짜 기입 위치 변경 요청(~/visit)

현재는 방문일자 - 착용날짜 - 대여목적 - 상세목적으로 되어 있습니다.
하지만 방문일자와 착용날짜가 연달아 있어 혼동을 가져온다는 의견이 많네요.

그래서 착용날짜 기입란의 위치 변경을 요청드립니다.
![2015-02-27 12 24 56 3](https://cloud.githubusercontent.com/assets/4696328/6407062/b0b59c18-be7c-11e4-9914-ea7d6a1b8522.png)
이상과 같이 방문일자 - 대여목적 - 상세목적 - 착용날짜 순으로 변경 요청드립니다. :)

**Comment by keedi** [comment]
수정 및 배포 완료했습니다. 이슈 닫습니다.
