### ISSUE TITLE
방문 예약 중 방문 일자 선택 시 예약 가능 시간이 상단 안내 글에 가림

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#431]
방문예약 페이지(~/visit)에서 대여예약시간이 보일 수 있도록 상단 멘트 수정 요청

![2015-02-27 12 34 40](https://cloud.githubusercontent.com/assets/4696328/6407142/cec53ff0-be7d-11e4-85c2-f04cdf1c23a9.png)
컴퓨터 화면에서 보면 이렇게 아래 대여시간이 보이지 않습니다. 스크롤해서 내려야 함에도 그렇게 인식하지 못하고 시간을 예약하지 못하는 일이 계속 발생하고 있다고 합니다. 

어떤 방법을 해야 할지 정확히는 모르겠지만, 그냥 상단의 멘트를 좀 줄이면 조금이라도 보이지 않을까 하는 생각이 들었습니다. 그래서 멘트 수정을 요청드립니다.
 
### 기존

> 가장 경제적으로 정장 대여하는 방법, 알려드릴께요.
> 
> 열린옷장의 정장 대여 기간은 3박 4일입니다. 옷이 필요한 날로부터 1~2일 전 방문시간을 예약하신 후 대여하고 반납하셔야 기본금액으로 대여하실 수 있습니다. 너무 미리 예약하고 대여하시면 추가비용이 있습니다. 참고하셔서 경제적으로 알뜰하게 대여하시기 바랍니다. 

### 변경요청

> 열린옷장의 정장 대여 기간은 3박 4일입니다. 옷이 필요한 날로부터 1~2일 전 방문시간을 예약하신 후 대여하고 반납하셔야 기본금액으로 대여하실 수 있습니다.  참고하셔서 경제적으로 대여하시기 바랍니다.

**Comment by keedi** [comment]
일단 일부러 보이지 않게 한 것인데요. ㅎㅎ 사람들이 내용을 읽지 않는 경우가 있다고 생각해서...

어쨌든 지금 적어주신대로 변경하면 되는지요?

**Comment by keedi** [comment]
@10001if 참... 확인요망 라벨이 붙으면 답글을 달아주시고 해당 라벨을 제거해주세요. 제거해주시지 않으면 제거될때까지 제가 안 읽을 확률이 높습니다. :)

**Comment by 10001if** [comment]
@keedi 아.. 그렇군요.. 확실히 미리와서 대여하겠다고 우기시는 분이 거의(완전) 없으셨어요! ㅎㅎ 하지만 예약자체가 어렵다고 하시는 분들이 계셔서.. 시간이 보일 수 있도록 변경 요청드립니다! ^^

**Comment by 10001if** [comment]
확인요망 라벨은 확인한 뒤 바로 제거하겠습니다. ^^

**Comment by keedi** [comment]
`/visit`, `/visit2` 양쪽 모두 확인해야 하는데 아마도 `/visit`에만 해당 내용이 들어 있을 것으로 기억합니다.

**Comment by keedi** [comment]
수정 및 배포 완료했습니다.

**Comment by keedi** [comment]
다만 문구를 수정했지만 원하시는 만큼 날짜 선택 항목이 보이는지는 모르겠습니다. 확인해보시고 수정이 더 필요하다면 추가 수정 내역과 함께 라벨 제거 후 이슈를 다시 열어주세요.

일단 이슈 닫습니다.
