### ISSUE TITLE
방문 예약의 선호 색상 선택 양식을 2개로 줄임

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#432]
방문예약 페이지(~/visit)에서 색상선택을 3가지에서 2가지로 변경요청

![2015-02-27 12 47 05](https://cloud.githubusercontent.com/assets/4696328/6407197/e80cdf94-be7e-11e4-895e-a3cbcf1ff16f.png)
실제로 예약과 대여를 진행해보니 색상 선택이 2번째를 넘어서는 것은 의미가 없다고 판단이 됩니다.
가장 원하는 색, 두번째로 원하는 색 이렇게 2가지만 존재하는 것이 좋다는 의견이 대부분이라 수정 요청드립니다.

**Comment by keedi** [comment]
`/visit`, `/visit2` 양쪽 모두 작업해야 합니다.

**Comment by keedi** [comment]
더불어 3개 기준으로 처리되어 있는 커피스크립트 및 펄스크립트, 템플릿 모두 수정해야 합니다. 깜빡하고 제거하는 것을 빠뜨리면 영원히 남을 코드가 될 위험이 있습니다.

**Comment by keedi** [comment]
수정 및 배포 완료했습니다. 이슈 닫습니다.
