### ISSUE TITLE
방문 예약 화면에서 전자우편을 이메일로 표시

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#433]
방문예약 페이지(~/visit)에서 전자우편을 이메일로 변경요청

![2015-02-27 12 50 14](https://cloud.githubusercontent.com/assets/4696328/6407782/996a0c70-be8a-11e4-9809-794099cd1357.png)

현재는 전자우편이라고 씌여있습니다.
그런데 전자우편이 뭔지 몰라 물어보시는 상황이 꽤 발생되고 있습니다. ^^;;
그래서 "이메일"로 변경 요청드립니다.

이메일 (예 : info@theopencloset.net) 로 변경 요청드립니다.

이메일을 어떻게 적는지 몰라 예시를 둔 것은 아니구요.
이렇게 적으면 이메일 적는란이 더 분명하게 보여 안적고 그냥 넘어가는 일이 줄어들 것 같습니다.
전자우편 항목을 잘 이해하지 못하시는 분과 그냥 넘어가시는 분들이 많이 계시는 것 같아서요. :)

**Comment by keedi** [comment]
`/visit`, `/visit2` 양쪽 모두 수정해야 합니다.

**Comment by keedi** [comment]
수정 및 배포 완료했습니다. 이슈 닫습니다.
