### ISSUE TITLE
기본 예약 인원을 3명에서 4명으로 변경

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#434]
현재는 예약활성화를 시키면 30분당 예약을 할 수 있는 인원이 3명으로 고정되어 있습니다.
운영이 점차 안정화 되고 있어 4명으로 1명 추가하여 변경하려고 합니다.
수정 요청드립니다. ^^

**Comment by keedi** [comment]
커밋 로그에 오타가 있어서 수정했습니다.

**Comment by keedi** [comment]
설정 완료했으며 배포 역시 완료했습니다. 이슈 닫습니다.
