### ISSUE TITLE
대여 화면에서 포장 상태로 넘어온 주문서를 실시간으로 갱신함

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#435]
주소 예: /rental/2015-01-23

시간표와 마찬가지로 대여페이지를 실시간 갱신할 수 있도록 요청드리고자 합니다.
시간표에서 탈의중이거나 수선 중이었던 사람을 포장으로 변경하여도 대여페이지에서 새로고침하지 않으면 목록에 나타나지 않는데, 방문예약 인원이 많아지고 바빠질 수록 본 기능의 필요성이 요청되고 있습니다. 수정 요청드립니다. ^^

**Comment by keedi** [comment]
대여 페이지는 현재 포장하는 담당자가 사용하는 페이지인데 담당자 입장에서는 한 건에 대해서는 새로 고침을 수행한다면 전혀 문제가 없습니다. 즉, 담당자가 누군가의 옷을 전달 받았을 때 그때 한번 새로 고침을 누르면 무조건 보이게 되어있습니다. 즉 포장 진행 1회당 새로 고침 한번만 누르면 됩니다. 바코드 찍는것과 비슷하게 바코드 찍기 전에 F5 한번이면 되리라고 보는데, 혹시 제가 생각하고 있는 것과 다르게 절차가 이루어지는지 궁금하네요.

혹시 현재 어떻게 작업하고 계신지요?

**Comment by 10001if** [comment]
말씀하신 것처럼 작업을 하고 있습니다~ 다만, 요즘엔 대여자가 늘고 있어서 포장에 밀리는 경우가 종종 있어서 다른 컴퓨터에서 포장을 동시에 진행하기도 합니다. ^^

**Comment by keedi** [comment]
음 현재 포장의 경우 통계를 내보았을때 1인당 평균 2~3분 정도 걸리는 것으로 보고 있습니다. 밀리는 것처럼 보이지만 생각보다 효율이 좋아보이기는 합니다만... 흠... 이 문제는 다시 같이 고민해봐야겠네요.

**Comment by 10001if** [comment]
@keedi 안그래도 한번 여쭤보고 이슈에 올릴까 싶었었는데~ 오늘 안나오신다고 하셔서 우선 올려봤습니다. ^^

**Comment by 10001if** [comment]
@keedi 이건 종전대로 F5를 이용하여 사용하겠습니다! ^^
