### ISSUE TITLE
옐로우 레터용 자료 사진 요청

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#436]
옐로우 레터에 들어갈 자료사진을 위해 "꽉찬 모니터 스크린샷"을 요청드립니다.

어제 말씀드린 것 처럼 옐로우레터에 들어갈 자료화면이 필요합니다.

사진은
1. duflsdhtwkdahslxj(대시보드)
2. /room
3. /select 

부탁드립니다. ^^

**Comment by keedi** [comment]
@10001if 이건 https://github.com/opencloset/monitor/issues 이쪽에 올려주셔야 합니다. ㅎ

**Comment by 10001if** [comment]
앗! 방금 다시 작성해서 올렸습니다. ^^;;

**Comment by keedi** [comment]
opencloset/monitor#35 에서 처리해야 합니다. 이슈 닫습니다.
