### ISSUE TITLE
통계 상태 페이지에서 1분 이내의 값은 평균 계산시 제외함

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#440]
통계 상태페이지(~/stat/status/2015-03-03)에서 상태별 시간 계산시 수정요청사항.

방문을 한 뒤 재방문인 경우에는 신체치수 측정을 할 필요가 없어
방문- 신체치수- 의류준비-탈의-수선-포장-결제의 순으로 진행하지 않고
바로 방문-의류준비- 탈의로 진행되기도 합니다.
하지만 방문-신체치수-의류준비-탈의로 진행하기도 하는데요.
이때 신체치수 측정이 1분 이내로 빠르게 진행될 경우에는 이 값을 빼는 것이 더 정확할 것 같습니다.
평균을 인위적으로 줄이는 결과가 나타나고 있다고 생각이 되어지네요. 

방문 
치수측정 1분 이내
의류준비 1분 이내
탈의 1분 이내
수선 1분이내 
포장 1분 이내
결제 1분 이내

방문을 제외하고(방문에서 치수측정이 바로 이뤄지는 것은 상식적으로 충분히 가능한 일입니다.)
나머지 상황의 경우 1분 이내에 발생한 값은 평균값에서 제하고 계산해주시는 것이 가능할까요?
요청드립니다. ^^

**Comment by keedi** [comment]
2980 주문서의 경우 포장을 25초만에 처리했습니다. 그렇다고 하더라도 여전히 포장도 1분 이내의 값은 제외하고 평균을 내면 되는지요?

**Comment by keedi** [comment]
일단 최초 요청대로 수정했습니다.

**Comment by keedi** [comment]
실서버에 배포 완료했습니다.

**Comment by 10001if** [comment]
내일 오전에 사람이 많이 없을 때 확인해보고 라벨 제거하겠습니다. ^^
