### ISSUE TITLE
의류 정보 화면 엉덩이와 팔의 위치 변경

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#441]
의류정보화면(~/clothes/0J141)에서 엉덩이와 팔의 위치변경을 요청드립니다.

![2015-03-03 5 16 35](https://cloud.githubusercontent.com/assets/4696328/6458715/0a05eee4-c1ca-11e4-8cbd-4f6e741c34f1.png)
이상처럼 엉덩이와 팔의 위치의 변경을 요청드립니다.

**Comment by 10001if** [comment]
전체적으로 위치 조정을 요청드립니다. ^^

현재 : 가슴-허리-엉덩이-윗배-배꼽 / 허벅지-팔-다리-무릎-발
요청: 윗배-가슴-팔-배꼽 / 허벅지-엉덩이-허리-다리-무릎-발

감사합니다.

**Comment by aanoaa** [comment]
![screenshot-localhost 5001 2015-03-03 17-43-58](https://cloud.githubusercontent.com/assets/170528/6458966/14e5ae14-c1cd-11e4-9881-0027b02c4f35.png)

**Comment by 10001if** [comment]
윗배,가슴,팔,배꼽은 - 파란색(기존)
허벅지, 엉덩이, 허리, 다리, 무릎, 발은 - 노란색(기존)
으로 색상 변경 요청드립니다.

**Comment by keedi** [comment]
배포 완료했습니다.
