### ISSUE TITLE
일/주/월 별 방문자 정보 확인

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#443]
현재는 일별 방문자 수를 체크하고 있습니다.
하지만 방문은 했으나 대여를 하지 않은 경우도 발생하고 있습니다.
실제로 대여한 인원이 몇 명인지 일별, 주별, 월별로 확인하고 싶습니다.

**Comment by keedi** [comment]
@yongbin: @10001if 님과 미팅 해보시고 정말 필요한 부분이 무엇인지 어떤 내용을 보고 싶어하시는지 명확하게 확인한 후 이슈 정리해주세요. 구현 방법 및 위치, 페이지 등은 이후 결정하죠~

**Comment by yongbin** [comment]
@keedi 넵 알겠습니다.

**Comment by keedi** [comment]
미팅 일시 논의하시고 구현 직전 요구 사항 정리를 마감할 날짜를 정해주시고 진행해주세요. :)

**Comment by yongbin** [comment]
@keedi 넵 내일 한대표님과 뵙고 이야기나눈뒤 업데이트하겠습니다.

**Comment by keedi** [comment]
> @keedi 넵 내일 한대표님과 뵙고 이야기나눈뒤 업데이트하겠습니다.

ㅎㄷㄷ

@yongbin 상황 정리 및 이슈 갱신, 진행 부탁드립니다.

**Comment by yongbin** [comment]
@10001if  만일님 내일 이 이슈관련해서 미팅했으면 합니다. 시간되실때 저희사무실로 들러주세요!

**Comment by yongbin** [comment]
![screenshot 2015-07-12 22 16 51](https://cloud.githubusercontent.com/assets/52704/8637919/5938ba06-28e4-11e5-8013-7f333ff1c9e8.png)

우선 일감 떠오르는 생각은 현재 제공되고 있는 `시간표` 내부의 일일 기준 `예약자수`, `방문자수`, `미방문자수`, `Best-fit 수` 항목에 `대여자 수` 를 신설하고 추가적으로 금주, 금월 관련 항목을 표시해주면 좋을것 같습니다.

**Comment by yongbin** [comment]
@10001if 대표님 이 이슈 관련해서 논의가 필요합니다. 시간괜찮으실때 저를 찾아와 주시기 바랍니다.

**Comment by 10001if** [comment]
오늘은 좀 어려울 것 같구요.. 내일 오후에나 찾아뵐 수 있을 것 같습니다. 늦게 인사드려 죄송해요. ㅠ

**Comment by yongbin** [comment]
@10001if 아 아닙니다 아무때나 말씀주세요

**Comment by yongbin** [comment]
한만일대표님과 논의했습니다.

먼저 위에 적은 `시간표` 메뉴에 `대여자` 항목을 추가하는 건은 열린옷장 직원분들의
심리적인부분을 고려해서 진행하지 않기로 했습니다.

대신 `통계`-`상태` 메뉴와 유사한 형태로 년/월/일의 `예약자`, `방문자`,
`미방문자`, `BestFit`, `대여자` 수를 표시해주는 방식으로 의견이 모아졌습니다.

대략적인 UI는 다음과 같습니다.

- 기본적인 레이아웃은 `통계`-`상태`와 유사한 형태
- 날짜를 선택하는 입력폼이 존재하고 기본적으로 오늘날짜가 선택되지만 사용자는
  날짜를 변경가능함
- 가장 상단의 표는 선택된 날짜 기준으로 +2 ~ -2 일간의 예약자, 방문자, 미방문자,
  BestFit, 대여자 수를 표시
- 다음표는 선택된 날짜가 포함된 년의 **월별** 예약자, 방문자, 미방문자, BestFit,
  대여자 수를 표시
- 다음표는 선택된 날짜가 포함된 년의 **주차별** 예약자, 방문자, 미방문자, BestFit,
  대여자 수를 표시
- 구현가능하다면 날짜의 입력폼은 두개로 구성해서 기간별 검색의 지원을
  고려함(2011년 7월 2일부터 2011년 8월 6일)

**Comment by keedi** [comment]
@yongbin 수요일까지 부탁드립니다~ :)

**Comment by yongbin** [comment]
@10001if  대표님께 제 로컬 가지에 있는 구현화면을 보여드리고 피드백을 받았습니다. 기능상 원하시는 내용이 구현된것으로 의견주셨습니다. 코드만 리뷰된 뒤 배포되면 될 것 같습니다.

**Comment by keedi** [comment]
후웁. 드디어 마지막 이슈...(과연...)
어쨌든 코드 리뷰 및 머지 진행합니다.

**Comment by keedi** [comment]
방금 머지 완료했습니다.

**Comment by keedi** [comment]
캐싱을 위해 실서버에 다음 명령을 수행합니다.

```
$ bin/opencloset-stat-visitor-cache.pl app.conf 2015-11-17
caching: day-20150101000000-20150101235959
caching: day-20150102000000-20150102235959
caching: day-20150103000000-20150103235959
...
caching: month-20150701000000-20150731235959
caching: month-20150801000000-20150831235959
caching: month-20150901000000-20150930235959
caching: month-20151001000000-20151031235959
$
```

**Comment by keedi** [comment]
상기 캐싱은 매일 매일 동작해야 하므로 크론탭을 이용해 설정하겠습니다.

**Comment by keedi** [comment]
다음 크론탭 항목을 추가했습니다.

```
0 2 * * * bash -c 'source /opt/perl5/perlbrew/etc/bashrc && /opt/perl5/perlbrew/perls/perl-5.18.2/bin/perl /home/opencloset/service/staff.theopencloset.net/bin/opencloset-stat-visitor-cache.pl /home/opencloset/service/staff.theopencloset.net/app.conf' > /dev/null 2>&1
```

**Comment by keedi** [comment]
구현 및 실서버에 배포 완료했습니다.
이슈 닫습니다.

**Comment by keedi** [comment]
구현 완료한 화면입니다.

![screenshot-staff theopencloset net 2015-11-17 16-36-33](https://cloud.githubusercontent.com/assets/138451/11205234/81f4f670-8d49-11e5-9300-8b8cb907fd2e.png)

**Comment by 10001if** [comment]
확인 완료하였습니다! 감사합니다. ^^
