### ISSUE TITLE
여성 대여 의류 중 대여자의 신체 치수보다 4cm 이상 크지 않은 경우의 정보를 csv로 추출

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#444]
여성 윗배둘레와 가슴둘레의 상관관계에 대해 조사 중인데요. 필요 자료를 요청드립니다.

팀원 분들이 요청을 하셔서요. 

여성 대여자의 윗배둘레와 대여를 한 의류의 윗배둘레 차이가 +4 나는 기록을 제외하고 나머지 정보를 엑셀로 제공받을 수 있을까요? 
> (+4를 의미하는 것은 ex. 홍하나 윗배둘레 70, J0AK 윗배둘레 74 인 경우를 의미합니다.)

필요한 정보는 이름, 대여의류(코드), 신체윗배둘레, 의류윗배둘레, 차이값(의류윗배둘레 - 신체윗배둘레), 신체가슴둘레, 의류가슴둘레,  차이값(의류가슴둘레 - 신체가슴둘레) 입니다.

**Comment by yongbin** [comment]
마일스톤이 `2차오픈 피드백`으로 잘못지정된것 같아서 `3차오픈`으로 수정했습니다. ;-) 데이터 관련 이슈니 제가 처리하겠습니다.

**Comment by keedi** [comment]
csv 추출 이슈이니 데이터베이스 질의를 정리하고 자료를 넘기고 나면 이슈를 닫습니다.

**Comment by 10001if** [comment]
본 이슈는 현재시점에서는 큰 의미가 없으므로 이슈를 닫아도 될 것 같습니다. @keedi 그냥 이슈를 닫아도 될런지요?
