### ISSUE TITLE
주문서에 '사이즈없음' 상태를 추가

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#445]
시간표(~/timetable/~)에서 "사이즈없음" 항목추가를 요청드립니다.

![2015-03-06 12 32 31](https://cloud.githubusercontent.com/assets/4696328/6521764/ffcef2ca-c41e-11e4-8b3a-c25fb4ea4c4a.png)

사이즈가 없는 분들을 따로 입력하여 사이즈 없는 분들에 대한 의류를 구입이나 수선을 통해 준비하려고 합니다.

**Comment by keedi** [comment]
대여안함 상태로 두고 주문서의 상세 내역에 사이즈 없음을 기입하는 방법을 사용할 경우 굳이 상태를 추가할 필요가 없으나 상태를 추가하는 것을 선호하시는 것 같으니 요청대로 진행합니다.

**Comment by keedi** [comment]
상태는 `status` 테이블에 각각의 자료로 저장하기 때문에 스키마를 변경할 필요는 없습니다. 하지만 상태를 보여주거나 수정하는 곳에서 맵핑을 위해 하드 코딩하고 있기 때문에 웹응용, 템플릿, coffee 스크립트에서 관련 부분을 모두 수정해야 합니다.

**Comment by keedi** [comment]
기존 데이터베이스에는 다음 질의를 수행해 자료를 갱신합니다.

```sql
INSERT INTO `status` (`id`, `name`) VALUES ('43', '사이즈없음');
```

**Comment by keedi** [comment]
구현 및 배포 완료했습니다.

**Comment by 10001if** [comment]
확인했습니다!
