### ISSUE TITLE
주문서에서 결제 대기시 새로 주문을 눌렀을 때 진행 여부 확인(경고)창 생성

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#446]
오늘 주문서번호 2807(~/order/2807) 대여자의 주문을 하던 중 결제대기 상태에서 결제자가 실수로 주문확정을 누르지 않고 새로주문을 누르는 바람에 대여기록이 사라졌습니다.
갑자기 많은 수의 대여자가 방문하셔서 결제자도 정신이 없었는지 그냥 금액을 지불받고 결제를 진행한 것 같습니다. (어떻게 이게 가능했는지는 의문입니다. 본인도 잘 기억을 못하네요.. ^^;) 그런데 주문확정 옆에 새로주문이 있다보니 실수로 그럴 수도 있겠다 싶네요. (그래도 평소엔 이렇게 누를 일이 없을 것 같습니다..) 
그래서 새로주문을 누르면 "정말 새로주문을 하겠냐"는 확인창이 뜨게 해주시면 더 감사할 것 같습니다. 그러면 오류가 거의 일어나지 않을까 생각이 되네요. 혹시 다른 생각이 있으시면 이야기 부탁드립니다. ^^

![2015-03-06 4 39 45](https://cloud.githubusercontent.com/assets/4696328/6521878/3acd68ec-c420-11e4-8f00-f85835b60098.png)

**Comment by keedi** [comment]
#447과 마찬가지로 원래 3차 마일스톤이었으나 상대적으로 밀려 마일스톤을 제거했으나 @aanoaa 님의 이슈 처리 속도가 빠르므로 이번 마일스톤에서 처리하는 것도 좋을 것 같습니다. ;-)

**Comment by keedi** [comment]
방금 실 서버에 배포 완료했습니다. 이슈 닫습니다. :-)

**Comment by 10001if** [comment]
확인 완료 하였습니다. ^^
