### ISSUE TITLE
주문서에서 환불 진행을 눌렀을 때 진행 여부 확인(경고)창 생성

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#447]
#446 이슈와 비슷한 개념입니다.
환불진행을 누르면 "정말 환불진행을 하겠냐"는 확인창이 뜨게 해주시면 더 감사할 것 같습니다. 그러면 오류가 거의 일어나지 않을까 생각이 되네요. 혹시 다른 생각이 있으시면 이야기 부탁드립니다. ^^
![2015-03-06 4 46 48](https://cloud.githubusercontent.com/assets/4696328/6522223/c5e4d2c6-c425-11e4-8d45-9747a77b9c54.png)

**Comment by keedi** [comment]
원래 3차 마일스톤이었으나 상대적으로 밀려 마일스톤을 제거했으나 @aanoaa 님의 이슈 처리 속도가 빠르므로 이번 마일스톤에서 처리하는 것도 좋을 것 같습니다. ;-)

**Comment by aanoaa** [comment]
![screenshot-localhost 5001 2015-06-25 10-12-54](https://cloud.githubusercontent.com/assets/170528/8344920/cc805836-1b22-11e5-86dc-90d4a293c57c.png)

@10001if 환불진행은 이미 팝업창이 나타나고 있습니다.
별다른 처리가 필요하지 않을 것 같습니다.

**Comment by 10001if** [comment]
@aanoaa 말씀하신 것 처럼 확인 창이 뜨고 있네요. 확인해주셔서 감사합니다. :)
