### ISSUE TITLE
사용자 정보에 바지 길이 항목을 추가

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#448]
사용자자 정보화면(~/user/~)에서 바지길이 추가를 요청드리고자 합니다.

현재 재방문 한 대여자 경우
같은 옷을 입고싶다는 의사표시를 하시면
의류가 있는지 확인하고 의류가 있으면
탈의실에서 다시 입어보시도록 권하는데요.
그렇게 하는 가장 큰 이유는 바지기장을 체크하기 위해서 입니다.
다리길이를 보고 바지기장을 맞춰 대여해드리고 싶지만
다리길이와 바지기장이 맞지 않는다는 경험적인 의견이 많아
바지기장 항목을 추가 요청드립니다. 

![2015-03-06 5 36 46](https://cloud.githubusercontent.com/assets/4696328/6522482/966e6054-c428-11e4-92bc-fd504c9d5506.png)

**Comment by keedi** [comment]
스키마 변경이 완료될 경우 진행합니다.

**Comment by keedi** [comment]
@10001if 바지 길이를 열람해야 하는 페이지가 있다면 해당 페이지와 위치를 알려주세요~

**Comment by aanoaa** [comment]
`대여` 화면에서 바지기장을 입력할 수 있도록 합니다

**Comment by keedi** [comment]
i :cry:

**Comment by keedi** [comment]
> aanoaa commented a day ago
> 
> 대여 화면에서 바지기장을 입력할 수 있도록 합니다

오늘 다시 말씀해주셨는데 사용자 정보에서만 수정할 수 있어도 된다고 합니다!

i :laughing:

**Comment by keedi** [comment]
진행합니다.

**Comment by keedi** [comment]
주문서에서도 빌렸던 바지 길이 정보를 저장해야 할 것 같습니다. 주문서 테이블에도 추가하고 주문 체결될때 신체 사이즈 복제하는 시점에 적용해주어야 합니다.

**Comment by keedi** [comment]
opencloset/OpenCloset-Schema#22 이슈를 처리 했으므로 `OpenCloset::Schema` 0.016 버전을 기준으로 작업 진행하도록 합니다.

**Comment by keedi** [comment]
기존 데이터베이스에는 다음 질의를 적용합니다.

```sql
ALTER TABLE `user_info` ADD COLUMN `pants` INT NULL DEFAULT NULL AFTER `foot`;
ALTER TABLE `order`     ADD COLUMN `pants` INT NULL DEFAULT NULL AFTER `foot`;
```

**Comment by keedi** [comment]
현재 실 서버에는 일단 스키마에는 이미 상기 질의를 적용시켜두었습니다.

**Comment by keedi** [comment]
작업 완료했으며 배포 대기 중입니다. 저녁 6시 이후에 적용할 예정입니다.

**Comment by keedi** [comment]
배포 완료했습니다. 이슈 닫습니다.

**Comment by 10001if** [comment]
확인완료하였습니다. 감사합니다.
