### ISSUE TITLE
넥타이 대여 비용을 2000원에서 0원으로 변경

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#451]
넥타이의 경우 수트를 대여하는 경우 무료로 처리하고 있습니다.
하지만 수트를 대여하는 경우가 전체 대여건수의 70-80%를 차지한다고 판단하고 있는 바
금액을 0원으로 변경하고 수트를 빌리지 않고 단품으로 대여하는 경우에만 금액을 2000원으로 변경하여 
대여비용을 책정하도록 하겠습니다. :)

> 넥타이의 대여비용을 2000원에서 0원으로 변경 요청드립니다.

**Comment by aanoaa** [comment]
헉 넥타이만 빌리는 사람도 있나요?

**Comment by 10001if** [comment]
네에~ 가끔 그런 경우도 있답니다 ㅎㅎ

**Comment by keedi** [comment]
실서버에 다음 질의를 적용할 예정입니다.

```
UPDATE clothes SET price=0 WHERE category='tie';
```

**Comment by keedi** [comment]
의류 추가 시에도 기본 타이 대여 가격은 0원이도록 수정했습니다.

**Comment by keedi** [comment]
서버에 적용 완료했습니다. 이슈 닫습니다.
