### ISSUE TITLE
연체 사용자에게 전송할 문자 메시지 매크로 추가

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#452]
000님 열린옷장 대여기간이 0일 연체되었습니다 00000원 입금부탁드립니다. 국민은행 20570104-269524

**Comment by keedi** [comment]
매크로를 추가하는 것은 어렵지 않습니다만, 결국 이름과 날짜와 금액을 입력해야 하는데 관련해서 더 편리하게 적용할 수 있는 방법이 있을 것 같습니다. 논의가 필요합니다. :)

**Comment by keedi** [comment]
누가 어떤 프로세스 중 어떤 페이지에서 해당 문구를 보내려고 하는지가 명확해지면 클릭 한번으로 이름, 연체일 수, 금액까지 자동으로 입력되게 할 수 있을 것 같습니다. 그렇다면 사용자는 최종 문구를 보고 확인만 한 다음 메시지를 보내면 훨씬 편리할 것이라고 예상합니다.

**Comment by 10001if** [comment]
네! 훨씬 편리할 것 같습니다. 반납을 하셨지만 연체된 분들에게 연체비 입금을 요청드리기 위해 발송하는 문자입니다.

**Comment by keedi** [comment]
연체 사용자에게 실제로 문자 메시지 보내기를 담당하고 있는 옷장 지기와 이야기를 나눠본 결과 주문서 목록에서 바로 원클릭으로 보낼 수 있으면 좋겠다는 의견이 있습니다. 주문서 목록의 각각의 주문서 정보를 표시하는 한 줄 한 줄마다 연체 문자 메시지를 보낼 수 있는 링크 또는 버튼을 추가하겠습니다.

**Comment by keedi** [comment]
@10001if 문구와 관련해서 더 자세한 내용이 들어가야 굳이 또 전화로 구구절절 설명하지 않아도 될 것 같다는 의견이 있었습니다. 관련해서는 논의해보시고 말씀해주세요. :)

**Comment by keedi** [comment]
진행합니다.

**Comment by keedi** [comment]
옷장지기와 논의해본 결과 연체자는 연체 목록 화면에서 확인 한 후 사용자 링크를 누르고 다시 SMS 보내기 누르기 과정을 거친 다음 전송할 메시지를 입력한다고 합니다. 따라서 연체 목록 화면에서 바로 해당 주문서 별로 연체 관련 문자 메시지를 보낼 수 있는 링크를 추가하면 담당자의 수고가 몇 배 이상으로 수월해집니다.  이를 위해 주문서 목록에서 연체인 경우에 한해 연체 문자 보내기 링크를 추가합니다.

**Comment by keedi** [comment]
주문서 목록에 링크를 추가한 화면입니다.

![screenshot-monster silex kr 7730 2015-04-03 17-21-15](https://cloud.githubusercontent.com/assets/138451/6980022/e40d68aa-da26-11e4-8fb2-6ebee26b5b3a.png)

**Comment by keedi** [comment]
상기 링크를 클릭했을 때 문자 메시지를 전달 받을 상대와 메시지가 자동으로 입력된 화면입니다.

![screenshot-monster silex kr 7730 2015-04-03 17-22-57](https://cloud.githubusercontent.com/assets/138451/6980027/fd4a1386-da26-11e4-8e42-e77340fb6b8d.png)

**Comment by keedi** [comment]
작업 완료했으므로 이슈 닫습니다.

**Comment by keedi** [comment]
실서버에 배포 완료 했습니다.

**Comment by keedi** [comment]
음 그런데... 문자 메시지가 저런 형식이어서는 좀 이슈가 있을 것 같습니다. 예를 들어 반납은 안했는데 문자를 받은 시점 연체료를 송금했다고 가정하고, 여전히 계속 연체중일 경우 다음 번 문자 메시지를 보낼때 이전에 받은 대여비를 계산할 방법이 없습니다. 어쨌든 이런 부분은 감안해야 할 것입니다. (주문서를 반납 처리하고 재대여로 처리하는 방법이 있긴 하겠습니다만...)

**Comment by 10001if** [comment]
아.. 그러네요. 이 부분은 고민이 필요할 것 같은데, 지금은 딱 좋은 방법이 떠오르지 않네요.. 다음 주에 만나뵙고 이야기를 나눠보면 좋을 것 같습니다.

**Comment by 10001if** [comment]
어떻게 하면 좋을지 현재시점에서는 아이디어가 생각나지 않습니다.

**Comment by 10001if** [comment]
다시 생각을 해보니.. 근본적으로 연체자에게 연체금액을 알려주어 반납을 유도하는 것은 맞지만, 그 시점의 연체금액을 입금하도록 유도하는 것은 잘못된 방법인 것 같습니다. 반납시에 금액을 지급받기로 한 원칙에 위배된다고 보여지기 때문입니다. 이 부분에 대해서는 다시 논의가 필요할 것 같습니다.

**Comment by keedi** [comment]
문구를 정해서 알려주시면 수정하겠습니다.

**Comment by 10001if** [comment]
@keedi 네! 문구 정하여 다시 말씀드리겠습니다. :)

**Comment by 10001if** [comment]
[열린옷장] ooo님 대여기간이 oo일 연체되었습니다. 확인하시고 반납 바랍니다.

**Comment by 10001if** [comment]
문구 정했습니다. 확인 부탁드려요 ^^

**Comment by keedi** [comment]
배포 완료했습니다. 이슈 닫습니다.

**Comment by 10001if** [comment]
확인 완료하였습니다
