### ISSUE TITLE
어울림이 best-fit 인 경우 옷 치수와 신체치수의 차이값을 요청드립니다.

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#453]
키디님이 5층을 방문해 주신 뒤, 옷장지기들이 첫번째로 옷을 찾고(중동, 허벅지에 +7,8 처럼 더하기를 한 값으로) 정확한 값의 치수가 없는 경우 두번째로 옷을 찾는 기준을 고민하여 만들고 있습니다. 대략적으로 만들어 지면 빨리 말씀드리겠습니다. 

첫번째 기준이 되는 차이를 구하는데, 현재처럼 +7, +8을 하는 것이 맞는지에 대한 의문이 들었습니다.

혹시 가능하다면 https://docs.google.com/a/theopencloset.net/spreadsheets/d/1gBLI63aIOxpDn8oe0wfd_UQGwfCYPHY3U61t11eo6a8/edit#gid=133907965 처럼 

1. 남자/여자의 차이 평균
2. 중동 구간으로 본 차이값
3. 허리 구간으로 본 차이값 을 알 수 있을까요? ^^

**Comment by keedi** [comment]
현 시점 기준으로 필요없는 기능이라고 합니다. 이슈 닫습니다. :)
