### ISSUE TITLE
셔츠 500벌 바코드 생성

### ISSUE THREAD

**Issue by yongbin** [opencloset/opencloset#454]
@10001if 님께서 유선으로 셔츠 500벌의 바코드 생성을 요청하셨습니다. 진행합니다.

```
[ last code ]
A0KT
B06X
C022
E0I1
H00O
J0RR
K0B3
O022
P0JF
S0KT
T0D6
W01D
```

**Comment by yongbin** [comment]
```perl
#!/usr/bin/env perl

use 5.010;
use utf8;
use strict;
use warnings;

use Math::Fleximal;
use DDP;

my %last = (
    A => q{06X},
    B => q{06X},
    C => q{022},
    E => q{045},
    H => q{00O},
    J => q{0RR},
    K => q{0B3},
    O => q{022},
    P => q{0JF},
    S => q{0F9},
    T => q{0D6},
    W => q{01D},
);

my %code = (
    A => 0,
    B => 100,
    C => 0,
    E => 100,
    H => 0,
    J => 300,
    K => 0,
    O => 0,
    P => 300,
    S => 100,
    T => 200,
    W => 0,
);

my %next;

my @digits = ( 0 .. 9, 'A' .. 'Z' );

for my $k ( sort keys %code ) {
    my $n = $code{$k};

    my $last = Math::Fleximal->new( $last{$k}, \@digits );
    for ( 0 .. $n - 1 ) {
        my $code = Math::Fleximal->new($_)->change_flex( \@digits )->add($last)
            ->add( $last->one )->to_str;
        printf( "%s%03s\n", $k, $code );
        $next{$k} = $code;
    }
}
%next = ( %last, %next );

print STDERR "[ last code ]\n";
foreach my $k ( sort keys %next ) {
    print STDERR sprintf( "%s%03s\n", $k, $next{$k} );
}
```

```sh
perl code.pl > code.txt 2> lastcode.txt
```

**Comment by yongbin** [comment]
## code.txt 
```
S0KU
S0KV
S0KW
S0KX
S0KY
S0KZ
S0L0
S0L1
S0L2
S0L3
S0L4
S0L5
S0L6
S0L7
S0L8
S0L9
S0LA
S0LB
S0LC
S0LD
S0LE
S0LF
S0LG
S0LH
S0LI
S0LJ
S0LK
S0LL
S0LM
S0LN
S0LO
S0LP
S0LQ
S0LR
S0LS
S0LT
S0LU
S0LV
S0LW
S0LX
S0LY
S0LZ
S0M0
S0M1
S0M2
S0M3
S0M4
S0M5
S0M6
S0M7
S0M8
S0M9
S0MA
S0MB
S0MC
S0MD
S0ME
S0MF
S0MG
S0MH
S0MI
S0MJ
S0MK
S0ML
S0MM
S0MN
S0MO
S0MP
S0MQ
S0MR
S0MS
S0MT
S0MU
S0MV
S0MW
S0MX
S0MY
S0MZ
S0N0
S0N1
S0N2
S0N3
S0N4
S0N5
S0N6
S0N7
S0N8
S0N9
S0NA
S0NB
S0NC
S0ND
S0NE
S0NF
S0NG
S0NH
S0NI
S0NJ
S0NK
S0NL
S0NM
S0NN
S0NO
S0NP
S0NQ
S0NR
S0NS
S0NT
S0NU
S0NV
S0NW
S0NX
S0NY
S0NZ
S0O0
S0O1
S0O2
S0O3
S0O4
S0O5
S0O6
S0O7
S0O8
S0O9
S0OA
S0OB
S0OC
S0OD
S0OE
S0OF
S0OG
S0OH
S0OI
S0OJ
S0OK
S0OL
S0OM
S0ON
S0OO
S0OP
S0OQ
S0OR
S0OS
S0OT
S0OU
S0OV
S0OW
S0OX
S0OY
S0OZ
S0P0
S0P1
S0P2
S0P3
S0P4
S0P5
S0P6
S0P7
S0P8
S0P9
S0PA
S0PB
S0PC
S0PD
S0PE
S0PF
S0PG
S0PH
S0PI
S0PJ
S0PK
S0PL
S0PM
S0PN
S0PO
S0PP
S0PQ
S0PR
S0PS
S0PT
S0PU
S0PV
S0PW
S0PX
S0PY
S0PZ
S0Q0
S0Q1
S0Q2
S0Q3
S0Q4
S0Q5
S0Q6
S0Q7
S0Q8
S0Q9
S0QA
S0QB
S0QC
S0QD
S0QE
S0QF
S0QG
S0QH
S0QI
S0QJ
S0QK
S0QL
S0QM
S0QN
S0QO
S0QP
S0QQ
S0QR
S0QS
S0QT
S0QU
S0QV
S0QW
S0QX
S0QY
S0QZ
S0R0
S0R1
S0R2
S0R3
S0R4
S0R5
S0R6
S0R7
S0R8
S0R9
S0RA
S0RB
S0RC
S0RD
S0RE
S0RF
S0RG
S0RH
S0RI
S0RJ
S0RK
S0RL
S0RM
S0RN
S0RO
S0RP
S0RQ
S0RR
S0RS
S0RT
S0RU
S0RV
S0RW
S0RX
S0RY
S0RZ
S0S0
S0S1
S0S2
S0S3
S0S4
S0S5
S0S6
S0S7
S0S8
S0S9
S0SA
S0SB
S0SC
S0SD
S0SE
S0SF
S0SG
S0SH
S0SI
S0SJ
S0SK
S0SL
S0SM
S0SN
S0SO
S0SP
S0SQ
S0SR
S0SS
S0ST
S0SU
S0SV
S0SW
S0SX
S0SY
S0SZ
S0T0
S0T1
S0T2
S0T3
S0T4
S0T5
S0T6
S0T7
S0T8
S0T9
S0TA
S0TB
S0TC
S0TD
S0TE
S0TF
S0TG
S0TH
S0TI
S0TJ
S0TK
S0TL
S0TM
S0TN
S0TO
S0TP
S0TQ
S0TR
S0TS
S0TT
S0TU
S0TV
S0TW
S0TX
S0TY
S0TZ
S0U0
S0U1
S0U2
S0U3
S0U4
S0U5
S0U6
S0U7
S0U8
S0U9
S0UA
S0UB
S0UC
S0UD
S0UE
S0UF
S0UG
S0UH
S0UI
S0UJ
S0UK
S0UL
S0UM
S0UN
S0UO
S0UP
S0UQ
S0UR
S0US
S0UT
S0UU
S0UV
S0UW
S0UX
S0UY
S0UZ
S0V0
S0V1
S0V2
S0V3
S0V4
S0V5
S0V6
S0V7
S0V8
S0V9
S0VA
S0VB
S0VC
S0VD
S0VE
S0VF
S0VG
S0VH
S0VI
S0VJ
S0VK
S0VL
S0VM
S0VN
S0VO
S0VP
S0VQ
S0VR
S0VS
S0VT
S0VU
S0VV
S0VW
S0VX
S0VY
S0VZ
S0W0
S0W1
S0W2
S0W3
S0W4
S0W5
S0W6
S0W7
S0W8
S0W9
S0WA
S0WB
S0WC
S0WD
S0WE
S0WF
S0WG
S0WH
S0WI
S0WJ
S0WK
S0WL
S0WM
S0WN
S0WO
S0WP
S0WQ
S0WR
S0WS
S0WT
S0WU
S0WV
S0WW
S0WX
S0WY
S0WZ
S0X0
S0X1
S0X2
S0X3
S0X4
S0X5
S0X6
S0X7
S0X8
S0X9
S0XA
S0XB
S0XC
S0XD
S0XE
S0XF
S0XG
S0XH
S0XI
S0XJ
S0XK
S0XL
S0XM
S0XN
S0XO
S0XP
S0XQ
S0XR
S0XS
S0XT
S0XU
S0XV
S0XW
S0XX
S0XY
S0XZ
S0Y0
S0Y1
S0Y2
S0Y3
S0Y4
S0Y5
S0Y6
S0Y7
S0Y8
S0Y9
S0YA
S0YB
S0YC
S0YD
S0YE
S0YF
S0YG
S0YH
S0YI
S0YJ
S0YK
S0YL
S0YM
S0YN
S0YO
S0YP
```
## lastcode.txt
```
[ last code ]
A0KT
B06X
C022
E0I1
H00O
J0RR
K0B3
O022
P0JF
S0YP
T0D6
W01D
```

**Comment by yongbin** [comment]
요청받은대로 생성 완료했습니다. 이슈 닫겠습니다.

**Comment by 10001if** [comment]
감사합니다. ^^

**Comment by 10001if** [comment]
저희가 코드를 붙여 새옷 등록을 하던 중에 중복된 코드가 다량으로 나왔습니다.
가령 S0PF의 경우 DB에서는 홍명*님의 의류인데 새로 발급해 주신 코드 안에 들어가 있습니다.
혹시 마지막 코드가 기록이 잘못 되어 있는 것은 아니였는지 확인 요청드립니다. :)

**Comment by 10001if** [comment]
@yongbin 대표님 혹시 전에 주셨던 코드 중에 S0PF 코드가 있는지 확인 부탁드릴게요. 어쩌면 저희 팀원분이 임의의 코드를 만들어 붙인 것 같기도 하네요. ^^;

**Comment by yongbin** [comment]
> @yongbin 대표님 혹시 전에 주셨던 코드 중에 S0PF 코드가 있는지 확인 부탁드릴게요. 어쩌면 저희 팀원분이 임의의 코드를 만들어 붙인 것 같기도 하네요. ^^;

안녕하세요? 유용빈입니다. 말씀을듣고 #39 이슈를 다시확인해본 결과 한가지 이상한 기록이 눈에 띕니다. 

https://github.com/opencloset/opencloset/issues/39#issuecomment-64180788

현재 바코드는 36진법을 이용해서 순차적으로 품번이 올라가는 방식인데 이 코드에서 나타나있는 `S0T5`는 기존에 진행되었던 코드보다 훨씬 더 뒤에 순번이며 심지어 최근 생성된 `S0PF` 보다도 더 뒷 순번입니다. 작년 11월 24일에 제가 보내드렸던 메일등을 확인해셔서 당시에 제가 발송했던 코드를 알려주시면 이번 사태의 원인을 좀 더 확실하게 규명할 수 있을것 같습니다. 다행인점은 다음 이슈에서 다시 코드가 정상적인 순번인 `S0I1`으로 돌아왔다는 점인데 만약 작년 11월 24일에 실수로 잘못 코드가 대량생성되었다면 지금 확인해서 처리해야할 필요기 있습니다.

**Comment by 10001if** [comment]
대표님 

11월 24일에 보내주신 코드입니다.
확인 부탁드립니다. ^^



————————————————————————————————

“You must be the change you want to see in the world.” 
―Mahatma Gandhi

열린옷장
한 만 일 (Man Of Action)
Manil Han

T 070. 4325. 7521
F 02. 6974. 1521
M 010. 6225. 7709
E 10001if@theopencloset.net
H www.theopencloset.net

Address 
서울특별시 광진구 화양동 48-3 웅진빌딩 403호 (우편번호 : 143-917)
#403, Woongjin B/D, 48-3, Hwayang-dong, Gwangjin-gu, Seoul, Korea

**Comment by 10001if** [comment]
대표님
파일 첨부하여 보내드렸습니다.
혹시 몰라 다시 보내드립니다.
확인 부탁드릴게요 ^^


————————————————————————————————

“You must be the change you want to see in the world.” 
―Mahatma Gandhi

열린옷장
한 만 일 (Man Of Action)
Manil Han

T 070. 4325. 7521
F 02. 6974. 1521
M 010. 6225. 7709
E 10001if@theopencloset.net
H www.theopencloset.net

Address 
서울특별시 광진구 화양동 48-3 웅진빌딩 403호 (우편번호 : 143-917)
#403, Woongjin B/D, 48-3, Hwayang-dong, Gwangjin-gu, Seoul, Korea

**Comment by yongbin** [comment]
제가 11월 24일에 발송했던 메일을 찾았습니다.

> from:	Yongbin Yu <yongbin.yu@gmail.com>
> to:	"Han Manil (theopencloset)" <10001if@theopencloset.net>
> cc:	Yongbin Yu <yongbin.yu@silex.kr>
> date:	Mon, Nov 24, 2014 at 1:09 PM
> subject:	Re: 바코드 마지막 정보입니다.
> mailed-by:	gmail.com
> 
> 대표님 안녕하세요? 유용빈입니다.
> 
> 요청하신 코드 보내드립니다.(첨부파일 #1) 그리고 이번 코드까지 적용된
> 마지막 코드번호는 아래와 같습니다.
> 
> A06X
> B09P
> C022
> E06X
> H00O
> J103
> K0B3
> O022
> P0RR
> S0I1
> T0IQ
> W01D
> 
> 다음 요청때 참고해 주시면 됩니다.
> 
> 감사합니다.
> 
> 유용빈
> 
> Han Manil (theopencloset) writes:
> 
> >          category  code     last     number
> >                             code
> > 1        Blouse    B        B02R     100
> > 2        Coat      C        C01D     0
> > 3        Hat       H        H00O     0
> > 4        Jacket    J        J0DV     300
> > 5        Onepiece  O        O01D     0
> > 6        Pants     P        P0B3     300
> > 7        Shirts    S        S06X     100
> > 8        Shoes     A        A045     100
> > 9        Skirt     K        K05J     100
> > 10       Tie       T        T045     200
> > 11       Waistcoat W        W00O
> > 12       Belt      E        E02R     100
> >                                          1300
> >
> > 동일한 엑셀 자료 참부합니다. :)
> >
> >
> >
> > -----------------------------------------------------------------
> >
> > 열린옷장
> > 한 만 일 (Man Of Action)
> > Manil Han
> >
> > T 070. 4325. 7521
> > F 02. 6974. 1521
> > M 010. 6225. 7709
> > E 10001if@theopencloset.net
> > H www.theopencloset.net
> >
> > Address
> > 서울특별시 광진구 화양동 48-3 웅진빌딩 403호 (우편번호 : 143-917)
> > #403, Woongjin B/D, 48-3, Hwayang-dong, Gwangjin-gu, Seoul, Korea

**Comment by yongbin** [comment]
작년 11월 24일에 생성한 코드는 `S06Y` 부터 `S0F9` 까지 총 300벌 입니다.

**Comment by yongbin** [comment]
김소령 대표님과 유선으로 통화해서 확인한 결과 현재 열린옷장에서 가장 마지막에 사용한 의류코드는 `S0QN` 이라고 합니다. 하지만 DB상에서 등록된 코드를 정렬했을때 가장 마지막 코드는 `S0SL` 입니다. 아마도 의류의 코드를 순차적으로 사용하고 있지 않은 상황으로 보입니다.  다음과 같이 진행하도록 하겠습니다.

 1. DB상 마지막 코드인 `S0SL`을 기준으로 500벌의 셔츠코드를 생성해서 열린옷장에 제공
 2. 기존에 발급된 전체코드와 DB코드의 차이를 확인후 사용할지 여부를 논의
 3. 바코드생성기에서 Lastcode를 수동으로 관리하던것을 DB 값을 확인해서 처리할수 있는 방향으로 개선

**Comment by yongbin** [comment]
생성된 코드입니다.

## Code
```
S0SM
S0SN
S0SO
S0SP
S0SQ
S0SR
S0SS
S0ST
S0SU
S0SV
S0SW
S0SX
S0SY
S0SZ
S0T0
S0T1
S0T2
S0T3
S0T4
S0T5
S0T6
S0T7
S0T8
S0T9
S0TA
S0TB
S0TC
S0TD
S0TE
S0TF
S0TG
S0TH
S0TI
S0TJ
S0TK
S0TL
S0TM
S0TN
S1TO
S0TP
S0TQ
S0TR
S0TS
S0TT
S0TU
S0TV
S0TW
S0TX
S0TY
S0TZ
S0U0
S0U1
S0U2
S0U3
S0U4
S0U5
S0U6
S0U7
S0U8
S0U9
S0UA
S0UB
S0UC
S0UD
S0UE
S0UF
S0UG
S0UH
S0UI
S0UJ
S0UK
S0UL
S0UM
S0UN
S0UO
S0UP
S0UQ
S0UR
S0US
S0UT
S0UU
S0UV
S0UW
S0UX
S0UY
S0UZ
S0V0
S0V1
S0V2
S0V3
S0V4
S0V5
S0V6
S0V7
S0V8
S0V9
S0VA
S0VB
S0VC
S0VD
S0VE
S0VF
S0VG
S0VH
S0VI
S0VJ
S0VK
S0VL
S0VM
S0VN
S0VO
S0VP
S0VQ
S0VR
S0VS
S0VT
S0VU
S0VV
S0VW
S0VX
S0VY
S0VZ
S0W0
S0W1
S0W2
S0W3
S0W4
S0W5
S0W6
S0W7
S0W8
S0W9
S0WA
S0WB
S0WC
S0WD
S0WE
S0WF
S0WG
S0WH
S0WI
S0WJ
S0WK
S0WL
S0WM
S0WN
S0WO
S0WP
S0WQ
S0WR
S0WS
S0WT
S0WU
S0WV
S0WW
S0WX
S0WY
S0WZ
S0X0
S0X1
S0X2
S0X3
S0X4
S0X5
S0X6
S0X7
S0X8
S0X9
S0XA
S0XB
S0XC
S0XD
S0XE
S0XF
S0XG
S0XH
S0XI
S0XJ
S0XK
S0XL
S0XM
S0XN
S0XO
S0XP
S0XQ
S0XR
S0XS
S0XT
S0XU
S0XV
S0XW
S0XX
S0XY
S0XZ
S0Y0
S0Y1
S0Y2
S0Y3
S0Y4
S0Y5
S0Y6
S0Y7
S0Y8
S0Y9
S0YA
S0YB
S0YC
S0YD
S0YE
S0YF
S0YG
S0YH
S0YI
S0YJ
S0YK
S0YL
S0YM
S0YN
S0YO
S0YP
S0YQ
S0YR
S0YS
S0YT
S0YU
S0YV
S0YW
S0YX
S0YY
S0YZ
S0Z0
S0Z1
S0Z2
S0Z3
S0Z4
S0Z5
S0Z6
S0Z7
S0Z8
S0Z9
S0ZA
S0ZB
S0ZC
S0ZD
S0ZE
S0ZF
S0ZG
S0ZH
S0ZI
S0ZJ
S0ZK
S0ZL
S0ZM
S0ZN
S0ZO
S0ZP
S0ZQ
S0ZR
S0ZS
S0ZT
S0ZU
S0ZV
S0ZW
S0ZX
S0ZY
S0ZZ
S100
S101
S102
S103
S104
S105
S106
S107
S108
S109
S10A
S10B
S10C
S10D
S10E
S10F
S10G
S10H
S10I
S10J
S10K
S10L
S10M
S10N
S10O
S10P
S10Q
S10R
S10S
S10T
S10U
S10V
S10W
S10X
S10Y
S10Z
S110
S111
S112
S113
S114
S115
S116
S117
S118
S119
S11A
S11B
S11C
S11D
S11E
S11F
S11G
S11H
S11I
S11J
S11K
S11L
S11M
S11N
S11O
S11P
S11Q
S11R
S11S
S11T
S11U
S11V
S11W
S11X
S11Y
S11Z
S120
S121
S122
S123
S124
S125
S126
S127
S128
S129
S12A
S12B
S12C
S12D
S12E
S12F
S12G
S12H
S12I
S12J
S12K
S12L
S12M
S12N
S12O
S12P
S12Q
S12R
S12S
S12T
S12U
S12V
S12W
S12X
S12Y
S12Z
S130
S131
S132
S133
S134
S135
S136
S137
S138
S139
S13A
S13B
S13C
S13D
S13E
S13F
S13G
S13H
S13I
S13J
S13K
S13L
S13M
S13N
S13O
S13P
S13Q
S13R
S13S
S13T
S13U
S13V
S13W
S13X
S13Y
S13Z
S140
S141
S142
S143
S144
S145
S146
S147
S148
S149
S14A
S14B
S14C
S14D
S14E
S14F
S14G
S14H
S14I
S14J
S14K
S14L
S14M
S14N
S14O
S14P
S14Q
S14R
S14S
S14T
S14U
S14V
S14W
S14X
S14Y
S14Z
S150
S151
S152
S153
S154
S155
S156
S157
S158
S159
S15A
S15B
S15C
S15D
S15E
S15F
S15G
S15H
S15I
S15J
S15K
S15L
S15M
S15N
S15O
S15P
S15Q
S15R
S15S
S15T
S15U
S15V
S15W
S15X
S15Y
S15Z
S160
S161
S162
S163
S164
S165
S166
S167
S168
S169
S16A
S16B
S16C
S16D
S16E
S16F
S16G
S16H
```
## Lastcode

```
[ last code ]
A0KT
B06X
C022
E0I1
H00O
J0RR
K0B3
O022
P0JF
S16H
T0D6
W01D
```

**Comment by yongbin** [comment]
> 김소령 대표님과 유선으로 통화해서 확인한 결과 현재 열린옷장에서 가장 마지막에 사용한 의류코드는 S0QN 이라고 합니다. 하지만 DB상에서 등록된 코드를 정렬했을때 가장 마지막 코드는 S0SL 입니다. 아마도 의류의 코드를 순차적으로 사용하고 있지 않은 상황으로 보입니다. 다음과 같이 진행하도록 하겠습니다.
> 
>     DB상 마지막 코드인 S0SL을 기준으로 500벌의 셔츠코드를 생성해서 열린옷장에 제공
>     기존에 발급된 전체코드와 DB코드의 차이를 확인후 사용할지 여부를 논의
>     바코드생성기에서 Lastcode를 수동으로 관리하던것을 DB 값을 확인해서 처리할수 있는 방향으로 개선

소령대표님께 연락해서 마지막으로 발급해 드린 코드를 별 문제 없이 사용중임을 확인했습니다. 추후 바코드 생성작업을 진행할때는 Last코드를 DB에서 확인하는 작업이 필요합니다.
