### ISSUE TITLE
열린옷장 방문일자 선택란 문구 변경

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#455]
현재 

"미리 오지 마세요."
열린옷장의 정장 대여 기간은 3박 4일입니다. 옷이 필요한 날로부터 1~2일 전 방문시간을 예약하신 후, 대여하고 반납하셔야 기본금액으로 대여하실 수 있습니다. 참고하셔서 경제적으로 대여하시기 바랍니다.

예)
옷이 필요한 날 - 12월 5일
적절한 예약일 - 12월 3일 또는 12월 4일

이렇게 적혀 있습니다. 하지만 앞으로는 택배반납인 경우에도 3박 4일의 대여기간을 준수하게 할 예정입니다. 따라서 27일 반납인 경우 기존에는 27일 택배 발송으로 마무리 하였지만 앞으로는 26일 발송하여 27일 도착하여야 연체가 발생되지 않도록 규정을 변경하였습니다. 이에 따른 문구의 수정을 요청드립니다.

----------------------------------------------------------------------------------

"미리 오지 마세요."
열린옷장의 정장 대여 기간은 3박 4일입니다. 옷이 필요한 날로부터 1~2일 전 방문시간을 예약하신 후, 대여하고 반납하셔야 기본금액으로 대여하실 수 있습니다. (단, 택배 반납시에는 반납일자 1일 전에 발송을 완료해주셔야합니다. 예> 반납예정일 27일, 택배 발송일 26일)  참고하셔서 경제적으로 대여하시기 바랍니다.

예)
옷이 필요한 날 - 12월 5일
적절한 예약일 - 12월 3일 또는 12월 4일

**Comment by 10001if** [comment]
@keedi 택배반납에 대한 이슈 문제가 있어서, 택배 반납도 방문 반납과 동일하게 처리하려고 합니다. 월요일 출근 후 바로 적용해주시면 감사하겠습니다. :)

**Comment by keedi** [comment]
실서버에 적용 완료했습니다. :)

이슈 닫습니다.

**Comment by 10001if** [comment]
확인 완료했습니다.
