### ISSUE TITLE
'잘안맞음' 입력란 추가 요청  

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#458]
주문서의 어울림 표시 부분을 보면 현재는 보통과 베스트핏 두가지로 이루어져 있습니다.
이부분에 '잘안맞음' 항목을 추가 요청드립니다.
현재 잘 맞지 않는 경우를 체크할 수 있는 부분이 존재하지 않아 저희가 부족한 사이즈의 의류를 체크하는데 어려움을 겪고 있습니다. 잘안맞음 항목을 추가해 주시면 저희가 수선을하거나 제작을 하는데 큰 도움이 될 것 같습니다.

추가적으로 구체적으로 어느부분이 잘 안맞았는지 여부를 입력하는게 좋은것인지에 대해서는 의견을 여쭤보고 싶습니다. @yongbin 대표님과 이야기 하던 중에 베스트 핏의 경우 부분별로 잘 맞았는지 여부를 체크하는 (가슴둘레 베스트, 허리둘레 베스트..) 것이 큰 의미가 없을 수도 있다고 하셔서 글을 남겨봅니다. 

![2015-04-04 10 05 39](https://cloud.githubusercontent.com/assets/4696328/6990877/61af93a6-dab2-11e4-9a9f-a1fc9cb1c505.png)

**Comment by keedi** [comment]
현재 시간표에서 사이즈가 없어서 빌려드리지 않는 경우 주문서 상태를 **사이즈 없음**으로 처리하는 것으로 알고 있습니다. 그 **사이즈 없음**과 지금 말씀하신 어울림에서 **잘 안맞음**은 다른 것인지, 다르다면 어떻게 다른 것인지요?

**Comment by 10001if** [comment]
일 전에 한번 이야기 드린 적 있는 걸로 기억하는데요. 

사이즈 없음은 사이즈가 없어 대여하지 못한 분들께 입력하는 것이지만
> 잘 안맞음은 베스트 핏의 반대입니다. 대여는 하였으나 사이즈가 잘 맞지 않은 경우에 입력하는 것이구요.

잘 안맞음과 사이즈 없음의 자료를 통해 수선, 제작이 필요하다고 판단하고 있습니다.
사이즈 없음으로 대여하지 못하고 돌아가시는 경우가 일주일에 1-2건으로 매우 미미한 상태라서
실제로 활용하기엔 너무 그 수가 적다고 판단하고 있기 때문입니다.

**Comment by keedi** [comment]
사이즈 없음의 경우 대여하지 못한 경우라는 것은 이해했습니다. 그렇다면 새로 추가했으면 하는 **잘 안맞음**의 경우 **보통**과도 다른 것인지요?

**Comment by keedi** [comment]
현재 **베스트핏** 여부 체크도 잘 안되고 있기 때문에 현재 기능이 당장 있어도 사용하기 어려울 것 같습니다. 금일 회의 결과 일단 중요도를 낮춰 당장 처리하지 않기로 했습니다. 마일스톤에서 제거합니다.

**Comment by keedi** [comment]
수선의 목적으로 생성했던 이슈이나 다른 방법 더 고민해보신다고 합니다. 다시 필요하다고 느끼게 되면 그때 다시 요청하기로 했기 때문에 일단 이슈 닫습니다.
