### ISSUE TITLE
키와 몸무게 기준으로 대여자의 방문 횟수 표 생성

### ISSUE THREAD

**Issue by keedi** [opencloset/opencloset#459]
세로는 키, 가로는 몸무게를 기준으로 대여자의 방문 횟수를 보여주는 표가 필요합니다.

이 정보를 기반으로 많이 방문하는 대여자의 신체 치수와 적더라도 방문하는 신체 치수의 분포를 확인하고 그에 맞게 많으면 많은대로, 적으면 적은대로 의류의 구비 여부를 확인하고 수선 여부를 판단하고 싶다고 합니다.

상기 자료는 웹에 통합될 필요는 없으며 CSV 형태로 정기적으로 열린옷장에 제공할 수 있으면 됩니다.

**Comment by keedi** [comment]
상기 자료를 추출하기 위해 일차적으로 사용한 질의는 다음과 같습니다.

```sql
SELECT
    ui.gender,
    ui.height   AS 키,
    ui.weight   AS 몸무게,
    COUNT(*)    AS popular
FROM user_info AS ui
LEFT JOIN user AS u
    ON ui.user_id = u.id
WHERE
    (
        u.create_date > '2014-12-17'
        AND (
            (
                ui.gender = 'male'
                AND ui.height > 140
            )
            OR
            (
                ui.gender = 'female'
                AND ui.height > 130
            )
        )
    )
GROUP BY ui.gender, ui.height, ui.weight
ORDER by
    popular   DESC
    ;
```

유효하지 않은 자료를 구분하기 위해 다음과 같은 조건을 붙였습니다.

- 남자일 경우 키가 140cm 이상일 것 / 여자일 경우 키가 130cm 이상일 것
- 사용자 등록 날짜가 2014년 12월 17일 이후일 것

**Comment by keedi** [comment]
유효하지 않은 자료를 구분하기 위해 다음 조건을 추가했습니다.

- 남녀 모두 몸무게가 0 초과 200 미만일 경우

```sql
SELECT
    ui.gender,
    ui.height   AS 키,
    ui.weight   AS 몸무게,
    COUNT(*)    AS popular
FROM user_info AS ui
LEFT JOIN user AS u
    ON ui.user_id = u.id
WHERE
    (
        u.create_date > '2014-12-17'
        AND (
            (
                ui.gender = 'male'
                AND ui.height > 140
                AND ui.weight > 0
                AND ui.weight < 200
            )
            OR
            (
                ui.gender = 'female'
                AND ui.height > 130
                AND ui.weight > 0
                AND ui.weight < 200
            )
        )
    )
GROUP BY ui.gender, ui.height, ui.weight
ORDER by
    popular   DESC
    ;
```

**Comment by keedi** [comment]
상기 질의로 뽑아낸 csv 파일(mysql 이용)을 파싱해서 2차원 테이블로 표현하는 스크립트는 다음과 같습니다. 일단 웹에서 상시 확인하시고 싶은 내용은 아니라고 하셔서 스크립트를 첨부하는 수준에서 끝냅니다. 추가로 더 웹페이지에 내용을 추가한다거나 필요한 내용이 있으면 현재 이슈를 다시 열어서 웹 응용에 추가하겠습니다.

```perl
#!/usr/bin/env perl

use v5.20;
use utf8;
use strict;
use warnings;

use Text::CSV;
use List::MoreUtils;

binmode STDOUT, ":utf8";

my $csv_file = shift;
die "Usage: $0 <csv_file>\n" unless $csv_file;

my $csv = Text::CSV->new({
    binary    => 1,
    auto_diag => 1,
    sep_char  => "\t",
});
open my $fh, "<:encoding(utf8)", $csv_file or die "$csv_file: $!";

my @headers = map { s/(^\s+|\s+$)//g; $_ } @{ $csv->getline($fh) };
$csv->column_names(@headers);

my %male = (
    height  => [],
    weight  => [],
    popular => {},
);

my %female = (
    height  => [],
    weight  => [],
    popular => {},
);

while ( my $row = $csv->getline_hr($fh) ) {
    my $gender  = $row->{'gender'};
    my $height  = $row->{'키'};
    my $weight  = $row->{'몸무게'};
    my $popular = $row->{'popular'};

    {
        use experimental qw( switch );

        given ($gender) {
            when ('male') {
                push @{ $male{height} }, $height;
                push @{ $male{weight} }, $weight;
                $male{popular}{$weight}{$height} = $popular;
            }
            when ('female') {
                push @{ $female{height} }, $height;
                push @{ $female{weight} }, $weight;
                $female{popular}{$weight}{$height} = $popular;
            }
            default {
                die "undefined gender: $gender\n";
            }
        }
    }
}

say "남자 방문표";
say "-----------";
display_visit_count(\%male);
say "여자 방문표";
say "-----------";
display_visit_count(\%female);

sub display_visit_count {
    my $data = shift;

    my ( $min_height, $max_height ) = List::MoreUtils::minmax( @{ $data->{height} } );
    my ( $min_weight, $max_weight ) = List::MoreUtils::minmax( @{ $data->{weight} } );

    say "height: $min_height ~ $max_height";
    say "weight: $min_weight ~ $max_weight";

    say join ',', "몸무게/키", $min_height .. $max_height;
    for my $weight ( $min_weight .. $max_weight ) {
        print $weight;
        for my $height ( $min_height .. $max_height ) {
            print ",";
            print $data->{popular}{$weight}{$height} || '-';
        }
        print "\n";
    }
}
```

**Comment by keedi** [comment]
메일로 상기 스크립트를 실행한 결과는 @10001if 님께 첨부드렸습니다. 요구사항은 만족했기 때문에 이슈 닫습니다.

**Comment by 10001if** [comment]
기본 데이터는 공유해서 확인했는데요. 일 전에 말씀드린 것처럼 X축 Y축에서 많이 방문한 비율로 색상을 진하게 표시하던지, 아니면 많이 방문한 키와 몸무게를 큰 원으로 표시하던지 해서, 한 눈에 어느 사이즈가 많이 오는지 확인할 수 있게 해주시면 감사할 것 같습니다. 보내주신 세부 데이터는 수선 담당자가 확인하고 있는데요. 모든 팀원들에게 공유하기 위해서는 한 눈에 확인할 수 있는 것이 훨씬 용이할 것 같아서요. 부탁드릴게요 ^^

**Comment by keedi** [comment]
진행합니다.

**Comment by keedi** [comment]
d3으로 처리하려고 고려했는데 일단 계속해서 보려는 자료가 아니기도 하고 샘플 그래프 중 적절하게 빈도 숫자와 함께 강약 여부를 동시에 표시할 적당한 그래프를 찾지 못했습니다. 따라서 일단은 스프레드시트의 조건부 서식 기능을 이용해서 처리했습니다.

**Comment by keedi** [comment]
메일로 전달 드렸으며 확인 받았습니다. 이슈 닫습니다. :-)

**Comment by keedi** [comment]
기존 질의의 경우 사용자 정보로만 처리했기 때문에 실제 방문 후 대여한 사용자의 정보와는 차이가 있습니다. 더욱 정확하게 자료를 뽑기 위해 주문서를 기반으로 계산한 질의는 다음과 같습니다.

변경 및 추가한 조건은 다음과 같습니다.

- 사용자 정보가 아닌 주문서를 대상으로 조회
- 주문서 상태를 반납으로 한정
- 주문서 날짜를 2015년 1월 1일 이후로 한정
- 부분 반납이 아닌 주문서 만으로 한정

```sql
SELECT
    ui.gender,
    o.height   AS 키,
    o.weight   AS 몸무게,
    COUNT(*)   AS popular
FROM      `order`   AS o
LEFT JOIN user_info AS ui
    ON o.user_id = ui.user_id
WHERE
    (
        (
            (
                   o.status_id = 9
            )
            AND o.parent_id IS NULL
            AND o.create_date > '2015-01-01'
        )
        AND (
                ui.gender = 'male'
                AND o.height > 140
                AND o.weight > 0
                AND o.weight < 200
            )
            OR
            (
                ui.gender = 'female'
                AND o.height > 130
                AND o.weight > 0
                AND o.weight < 200
            )
    )
GROUP BY ui.gender, o.height, o.weight
ORDER by
    popular   DESC
    ;
```

**Comment by 10001if** [comment]
키/몸무게 별로 얼마나 많은 수의 사람이 방문했는지 현재 시점에서 다시 체크하려 합니다. 동일한 자료를 다시 요청드립니다.

**Comment by 10001if** [comment]
@keedi 동일한 자료 요청인 경우에는 이슈를 다시 열어서 작업을 요청드려도 되는 건가요?

**Comment by keedi** [comment]
네 동일한 자료 요청의 경우 보통 `저장소 없이 처리`와 `통계` 라벨이 붙어 있을 것 같은데요. 아래에 한 번 더 요청해주시면 됩니다. 여셔도 되고 닫힌 채로 요청하셔도 되구요. 다만 마일스톤은 굳이 넣어주시지 않으셔도 됩니다.

**Comment by keedi** [comment]
메일로 첨부 드렸습니다. 자료와 관련해 이상한 부분이 있거나 궁금한 부분이 있으면 관련해 남겨주세요.

**Comment by 10001if** [comment]
@keedi 네. 마일스톤은 굳이 넣지 않도록 하겠습니다. 감사합니다.

**Comment by 10001if** [comment]
>상기 질의로 뽑아낸 csv 파일(mysql 이용)을 파싱해서 2차원 테이블로 표현하는 스크립트는 다음과 같습니다. 

-> 이렇게 진행해주시겠다고 남겨주신 뒤에 제가 추가로 요청드린 것이 있는데요.

>기본 데이터는 공유해서 확인했는데요. 일 전에 말씀드린 것처럼 X축 Y축에서 많이 방문한 비율로 색상을 진하게 표시하던지, 아니면 많이 방문한 키와 몸무게를 큰 원으로 표시하던지 해서, 한 눈에 어느 사이즈가 많이 오는지 확인할 수 있게 해주시면 감사할 것 같습니다. 

-> 이 이후에 아래와 같이 답변해 주셨습니다.

>d3으로 처리하려고 고려했는데 일단 계속해서 보려는 자료가 아니기도 하고 샘플 그래프 중 적절하게 빈도 숫자와 함께 강약 여부를 동시에 표시할 적당한 그래프를 찾지 못했습니다. 따라서 일단은 스프레드시트의 조건부 서식 기능을 이용해서 처리했습니다.

메일을 받아보니 다음과 같은 형식이었습니다.

gender | 키 | 몸무게 | popular
-- | -- | -- | --
female | 160 | 50 | 146
female | 162 | 50 | 143
female | 162 | 52 | 141
female | 160 | 51 | 130
female | 160 | 53 | 130
... | ... | ... | ...

하여 위에서 요청드린 것처럼 X축은 키, Y축은 몸무게로 나타난 자료를 요청드리고자 합니다. 본 파일은 시트 내에 남/여로 구분되거나 남/여 파일이 구분된 채로 전달받고자 합니다.

male | 50 | 51 | 52 | ...
-- | -- | -- | -- | --
150 | 0 | 0 | 1 | ..
151 | 1 | 2 | 0 | ..
152 | 2 | 3 | 1 | ..
153 | 0 | 4 | 2 | ..
154 | 2 | 4 | 5 | ..
... | ... | ... | ...

female | 30 | 31 | 32 | ...
-- | -- | -- | -- | --
140 | 0 | 0 | 1 | ..
141 | 1 | 2 | 0 | ..
142 | 2 | 3 | 1 | ..
143 | 0 | 4 | 2 | ..
144 | 2 | 4 | 5 | ..
... | ... | ... | ...
