### ISSUE TITLE
월요일을 영업 시간으로 변경함

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#460]
예약에서 월요일 활성화시킬 때 제한인원 "0"명에서 "4"명으로 변경요청

월요일 근무가 진행되기 때문에 월요일 시간표 활성화시 다른날과 마찬가지로 4명으로 슬롯이 적용되도록 수정 요청드립니다. :)

**Comment by keedi** [comment]
처리 및 배포 완료했습니다. 이슈 닫습니다.
