### ISSUE TITLE
대여 화면에서의 의류 상태 변경

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#461]
`GET /rental/:yyyy-mm-dd` 에서 모든 의류가 `대여가능` 상태가 아니면
대여할 수가 없는데 이를 `대여가능으로 변경` 같은 버튼을 두고 쉽게 옷의
상태를 변경하고 싶어합니다.

하루에도 여러건 발생하고 있는 상황이라 직원들이 불편이 크다고 합니다.

의류의 상태의 변경에 대한 기술적인 검토가 필요합니다.

`수선` 이나 `세탁` 같은 상태에서 `대여가능`으로 바꾸는 건 괜찮지만,
(실수 혹은 어떤 이유로) `대여중`인 의류가 정상적인 절차를 거치지 않고
`대여가능` 으로 바뀔때 가지게 되는 문제점 등을 고민해 봐야 합니다.

**Comment by keedi** [comment]
흠 의류 상태 변경 기능 자체를 넣는 것은 상관없는데... @10001if 님께 궁금한 것이 있습니다.

상태를 변경해야 할 의류를 상태 변경(현재 이름은 첫 화면) 페이지에서 상태를 변경 하는 것(정리하자면 별도의 페이지에서 변경하는 것)이 불편하다는 의미이신지요?

**Comment by 10001if** [comment]
아닙니다! 상태가 "반납"일 때 그것 때문에 다시 바코드를 찍어야 하는데, 이런 일이 일어나면 안되겠지만 실제로 하루에 4-5건씩 일어나고 있는데, 이 부분에서 소요되는 시간과 에너지가 너무커서 스트레스가 많이 일어나는 것 같아서요. 대여현장에서 본 기능을 강력히 원하고 있네요. 가능하다면 첫화면에서 진행되는 기능과 중복되지만, 추가를 요청드리고 싶습니다. ^^

**Comment by keedi** [comment]
@10001if 대표님과 논의해본 결과 이 문제는 반납 및 수선 관리 섹션에서 해결했어야 할 문제인데 미처 절차를 확립하지 못하다보니 대여 팀이 결과적으로 맞닥뜨리게 된 문제입니다. 이를 해결하기 위해 5층 의류 수납 공간에 섹션을 두고 의류 상태를 변경할 수 있도록 절차를 개선하기로 했습니다. 이를 통해 이 문제가 원천적으로 해결될 수 있는지 확인한 다음 그럼에도 불구하고 문제가 여전히 발생한다면 그때 이 기능을 추가하기로 했습니다.

따라서 지금 당장은 본 기능을 추가하지 않고 추이를 살펴보기로 했습니다. :-)

**Comment by keedi** [comment]
일단 이슈 닫습니다.
