### ISSUE TITLE
대여 가능 시간을 오후 10시까지로 변경

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#464]
야간대여를 테스트로 진행해 보려고 합니다. 야간 대여를 위해 대여가능시간을 22:00까지 확장 부탁드립니다. ^^

**Comment by keedi** [comment]
현재 19:00시 까지 열려있습니다. 말씀인즉 다음 항목을 열어달라는 말씀이신지요?

- 19:30
- 20:00
- 20:30
- 21:00
- 21:30
- 22:00

**Comment by 10001if** [comment]
네. 맞습니다 :)

**Comment by keedi** [comment]
처리 및 배포 완료 했습니다.
이슈 닫습니다.

**Comment by keedi** [comment]
@10001if 님께서 확인하셨다고 합니다. 라벨 제거합니다.
