### ISSUE TITLE
문자 전송 서식 추가: 내용 증명

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#465]
빈번하게 문자를 발송할 이슈가 발생하여 요청드립니다. 입력해 주실 내용은 다음과 같습니다.

내용증명 문자 서식

xxx님 열린옷장 대여기간이 xx일 연체되었습니다. Xx일 금요일까지 반납이 되지 않을 시, 반납의사가 없다고 판단되어 채무불이행과 횡령죄가 성립됩니다. 

따라서 내용증명서를 발송한 후, 서울 광진경찰서와 법적 절차를 통한 손해배상청구를 진행할 예정입니다. 꼭 반납 부탁 드립니다. 감사합니다.

**Comment by keedi** [comment]
@aanoaa: `/coffee/sms.coffee` 파일 수정 건입니다. :)

**Comment by aanoaa** [comment]
> xxx님 열린옷장 대여기간이 xx일 연체되었습니다. Xx일 금요일까지 반납이 되지 않을 시, 반납의사가 없다고 판단되어 채무불이행과 횡령죄가 성립됩니다.

항상 금요일 인가요?

**Comment by keedi** [comment]
아 X요일 이겠네요 ㅎㅎ

**Comment by keedi** [comment]
@aanoaa 이후 다음 단계로 본 이슈 처리 부탁드립니다. (다른 이슈도 마찬가지로 부탁드립니다.)

1. 배포 완료 후 배포 완료했다는 메시지와 함께 *배포대기* 라벨 제거
1. 제거 후 @10001if 님의 확인이 필요하며, 이슈 닫는다는 메시지와 함께 이슈 닫기
1. *확인요망* 라벨 추가

**Comment by keedi** [comment]
배포 완료했습니다. 이슈 닫습니다. :-)

**Comment by 10001if** [comment]
확인 완료 했습니다.
