### ISSUE TITLE
최초 예약시 위치를 안내하는 문자 발송

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#466]
<열린옷장 위치안내>
건대입구역 1번 출구로 나오신 뒤 오른쪽으로 꺾어 100M 가량 직진하시면 1층에 국민은행이 있는 건물 5층으로 올라오시면 됩니다. (도보로 2~3분 소요)
네이버 지도 안내 http://map.naver.com/index.nhn?enc=utf8&mapMode=0&level=2&lng=127.0671726&lat=37.5414246&pinTitle=%EC%97%B4%EB%A6%B0%EC%98%B7%EC%9E%A5&pinId=21258910&pinType=site

- 이렇게 적어주시면 될 것 같습니다. (URL은 열린옷장 검색하면 나오는 주소로 입력하였습니다.)

**Comment by keedi** [comment]
문구를 조금 더 정리해보았습니다.

```
<열린옷장 위치안내>
서울특별시 광진구 아차산로 213 국민은행
건대입구역 1번 출구로 나오신 뒤 오른쪽으로 꺾어 100M 가량 직진하시면 1층에 국민은행이 있는 건물 5층으로 올라오시면 됩니다. (도보로 2~3분 소요)
네이버 지도 안내: http://me2.do/xMi9nmgc
```

**Comment by keedi** [comment]
기존 최초 예약시 문자를 보내던 부분은 다음과 같습니다.

```perl
                        my $msg = sprintf(
                            "%s님 %s으로 방문 예약이 완료되었습니다.",
                            $user->name,
                            $order_obj->booking->date->strftime('%m월 %d일 %H시 %M분'),
                        );
                        $DB->resultset('SMS')->create({
                            to   => $user->user_info->phone,
                            from => app->config->{sms}{from},
                            text => $msg,
                        }) or app->log->warn("failed to create a new sms: $msg");
```

**Comment by keedi** [comment]
대표님께 확인 결과 기존 메시지와 별도로 메시지를 발송하는 것이 아니라 기존메시지에 줄 바꾸고 신규 메시지를 추가로 더 넣어 보내달라고 합니다. 즉 두 개가 아닌 하나의 메시지를 보내는 것입니다.

**Comment by keedi** [comment]
기존 코드에서 `$msg`에 내용을 추가하면 될 것 같습니다.

**Comment by keedi** [comment]
해당 영역은 `/visit` 부분입니다.

**Comment by aanoaa** [comment]
아 맥부기에 postcodify 가 없어서 고통받는중..

**Comment by keedi** [comment]
배포 완료했습니다. 이슈 닫습니다. :-)

**Comment by 10001if** [comment]
정말 너무 좋습니다 ㅠㅠ 확인 완료 했습니다.
