### ISSUE TITLE
제품 반납시 바코드를 입력하는 부분에서 영어만 인식되도록 요청

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#468]
현재는 한글도 인식하고 있어서 한글로 글씨를 입력하다가 바코드를 찍으면 인식하지 못하는 부분이 있습니다.
영어만 인식할 수 있도록 변경 부탁드립니다. :)
![Uploading 스크린샷 2015-05-29 오후 5.21.00.png…]()

**Comment by keedi** [comment]
구현 완료 및 서버에 배포 완료했습니다. :)

**Comment by 10001if** [comment]
지금 확인해보니 한글 입력이 가능한 것으로 보입니다. 확인 부탁드릴게요. ^^
![2015-06-10 9 47 12](https://cloud.githubusercontent.com/assets/4696328/8072763/af2c9fc0-0f55-11e5-8195-ac181f95f49a.png)

**Comment by keedi** [comment]
크롬의 버그로 보입니다. 파이어폭스는 문제가 없으며 현재 크롬에서 ime-mode 속성 값이 모두 제대로 동작하지 않기 때문에 바코드를 입력하는 모든 입력 양식에서 한글이 사용 가능한 상태입니다.

크롬이 언제 고쳐질지 모르는 상황이기 때문에 일단 파이어폭스를 사용하실 것을 권해드립니다.

**Comment by aanoaa** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/ime-mode

**Comment by 10001if** [comment]
확인 완료 하였습니다. 파이어폭스에서는 정상 작동하네요. 저희 식구 모두 파이어폭스를 사용하도록 전달하였습니다. :)
