### ISSUE TITLE
외부서비스에서의 주문서 상태변경

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#470]
monitor 에서 주문서의 상태를 변경하고자 합니다.
직접 DB 에 접근할 수 있지만 정상적인 절차로 주문서를 변경하기 위해,
opencloset 에 HTTP request 를 보내려합니다.

인증절차없이 api 를 호출하는 것이기 때문에 예방책을 마련해야합니다.

**Comment by aanoaa** [comment]
간단한 방법으로는 secret 문자열을 설정파일에 넣어두고,
요청 헤더에 붙여주는 방법입니다.

    PUT /api/order/100
    User-Agent: HTTP::Tiny
    Host: staff.theopencloset.net
    Accept: */*
    X-API-SECRET: xxxxxxxxxxxxxxx

**Comment by aanoaa** [comment]
혹은 확장헤더 대신에 `WWW-Authenticate` 헤더를 사용할 수 있겠습니다.
방법은 마찬가지입니다.

**Comment by keedi** [comment]
일단 현재 `/api` 하부에서 사용자 인증이 된 경우는 하부 호출이 가능하므로 HTTP헤더 쪽에 인증 토큰을 보내지 말고 모니터 계정을 만들고 모니터 계정으로 `POST /login` 요청 이후 api 호출 하는 방식이었으면 합니다. 그게 아니면 아예 계정 별 토큰 관리 기능을 다 넣었으면 하는데, 아직은 일이 좀 커보입니다.

`HTTP::Tiny` 및 `HTTP::CookieJar` 두 모듈을 사용하면 로그인 이후 api 호출은 간단히 해결될 것 같습니다.

**Comment by aanoaa** [comment]
`WWW-Authenticate` 가 아니라 `Authorization` 헤더입니다.

**Comment by aanoaa** [comment]
주문서의 상태가 변경되면 OPENCLOSET 에서는 MONITOR 에 결과를 알려줍니다.

    MONITOR --(상태변경)--> OPENCLOSET --(상태변경후 알람)--> MONITOR

    ********************** OPENCLOSET **********************
    [Mon Jun  1 17:33:19 2015] [debug] PUT "/api/order/7403.json"
    [Mon Jun  1 17:33:19 2015] [debug] Routing to a callback
    [Mon Jun  1 17:33:19 2015] [debug] Routing to a callback
    [Mon Jun  1 17:33:20 2015] [error] Failed to posting event: Internal Exception
    [Mon Jun  1 17:33:20 2015] [debug] 200 OK (1.055055s, 0.948/s)

로그를 보면 `PUT "/api/order/7403.json"` 요청이 들어온건 `200 OK` 로 응답했지만 중간에 monitor 로의 request 는 실패 했다고 나옵니다.

하지만 monitor 쪽 로그를 보면,

    ********************** MONITOR **********************
    [Mon Jun  1 17:33:19 2015] [debug] PUT "/api/orders/7403.json"
    [Mon Jun  1 17:33:19 2015] [debug] Routing to controller "OpenCloset::Monitor::Controller::User" and action "auth"
    [Mon Jun  1 17:33:19 2015] [debug] Routing to controller "OpenCloset::Monitor::Controller::API" and action "order"
    [Mon Jun  1 17:33:20 2015] [debug] 200 OK (1.142547s, 0.875/s)
    [Mon Jun  1 17:33:20 2015] [debug] POST "/events"
    [Mon Jun  1 17:33:20 2015] [debug] Routing to controller "OpenCloset::Monitor::Controller::User" and action "auth"
    [Mon Jun  1 17:33:20 2015] [debug] Routing to controller "OpenCloset::Monitor::Controller::Event" and action "create"
    [Mon Jun  1 17:33:21 2015] [debug] 201 Created (0.086425s, 11.571/s)
    [Mon Jun  1 17:33:21 2015] [debug] WebSocket closed with status 1001
    [Mon Jun  1 17:33:21 2015] [debug] GET "/preparation"

요청받은 `PUT "/api/orders/7403.json"` 는 정상응답했고, 이후 opencloset 에서 들어온 `POST "/events"` 역시 `201 Created` 정상응답했습니다.

정상으로 응답했는데 요청한쪽에서 Internal Exception 이 발생되는 상황입니다.

**Comment by aanoaa** [comment]
599 에러인데, 

http://httpstatus.es/599 에서 찾아보면,

> 599 / Network connect timeout error
> “This status code is not specified in any RFCs, but is used by some HTTP proxies to signal a network connect timeout behind the proxy to a client in front of the proxy.“ — 

라고 나옵니다.

timeout 을 1 해놔서 그런게 아닌가..

**Comment by aanoaa** [comment]
헉 3초로 늘리니까 발생하지 않습니다.

**Comment by aanoaa** [comment]
헉 3초로 늘려도 

    [Mon Jun  1 17:59:01 2015] [error] Failed to posting event: Internal Exception

같은에러가 발생합니다.
이왕 이런거 걍 1초로 냅두겠습니다.

**Comment by aanoaa** [comment]
외부서비스에서 계정을 만들고 인증하고 cookie 를 같이 보내면 됩니다.
