### ISSUE TITLE
주문서의 각 의류 항목 옆에 기증자 이름과 기증 행위 식별 번호를 표시

### ISSUE THREAD

**Issue by keedi** [opencloset/opencloset#473]
대여 과정 중 최종 결제 시점에 주문서의 의류를 확인한 후 기증자 한 명을 선택하고 그 이름을 대여자 카드에 작성합니다. 이는 대여자가 기증자에게 대여 메시지를 남길 수 있도록 유도하는 방법인데, 이를 위해 특정 의류를 클릭한 후 들어가서 정보를 확인하고 있습니다. 이 과정을 간소화 시키기 위해 주문서 안에서 각각의 의류 정보 옆에 누가 기증했는지 여부를 보여주도록 합니다.

더불어 대여자 카드의 우측 상단에 해당 대여자가 쓰게 될 대여 메시지가 가리키는 기증자를 판단하기 위해 기증 행위 식별자 번호를 기입하기로 했기 때문에 기증자 이름 뿐만 아니라 해당 의류가 속하는 기증행위 식별자 번호도 같이 표시해주어야 합니다.

이는 추후 메시지를 어떤 기증자에게 보이게 할지 판단하는데 사용할 예정입니다. 원래는 메시지를 주문서의 의류 항목을 기증한 모든 기증자에게 보이게 할 계획이었으나 열린옷장의 내부 정책으로 인해 특정 1인이게만 전달해야 한다고 합니다.

![screenshot-monster silex kr 10301 2015-06-02 13-37-37](https://cloud.githubusercontent.com/assets/138451/7928528/a93bd97a-092c-11e5-81bd-b318cd16aacd.png)

**Comment by keedi** [comment]
구현 완료했습니다.

![screenshot-monster silex kr 10301 2015-06-02 13-52-36](https://cloud.githubusercontent.com/assets/138451/7928660/bdd4c53e-092e-11e5-93a8-667cdf5912a9.png)

**Comment by keedi** [comment]
서버에 배포도 완료했습니다.
이슈 닫습니다.

**Comment by 10001if** [comment]
확인 완료입니다.
