### ISSUE TITLE
반납 시 연체료 결제 방식에 미납 항목을 추가

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#481]
반납 시 현재는 연체비가 미납되었더라도, 연체료를 에누리 해야만 반납으로 진행이 가능합니다.
때문에 연체비가 미납되었더라도, 연체비를 미납했는지 여부를 확인 할 수 없습니다.

따라서 연체비 에누리 없이 미납으로 진행할 수 있도록 체크할 수 있는 항목이 필요합니다. 
현금, 카드 등에 미납 항목을 신설해주시기 바랍니다. (미납항목은 붉은색으로 다르게 표시해주시면 좋을 것 같습니다.)

그리고 주문서 페이지에서 미납중인 주문서만 따로 확인하고 싶습니다.

다만, 
1. 이때 날짜는 **반납일 기준**으로 확인하고 싶습니다.
2. 미납된 금액을 입금하거나, 완납하였을시 이를 입력 할 수 있는 기능이 필요합니다.
3. 주문서 상에서 오른쪽에 완납 버튼이 있어서 주문서에서 바로 완납을 처리할 수 있는 기능이 생기면 좋겠습니다.

**Comment by keedi** [comment]
현재는 미납 항목이 있지만 이것은 아무것도 선택하지 않았을때 보이는 것입니다. 따라서 진정한 미납은 아닙니다. 이제는 현금/카드 등과 마찬가지로 돈을 받지 않았을 경우 미납을 선택해서 반납을 진행하는 것입니다.

이것은 반납을 진행했지만 반납 시점에 연체 비용을 지불하지 못하는 경우를 의미합니다.

**Comment by keedi** [comment]
진행합니다.

**Comment by 10001if** [comment]
미납 중 항목을 따로 볼 수 있고 미납 중인 대여자에게 문자를 발송하는 기능 추가를 요청드립니다.
![2015-06-25 11 30 02](https://cloud.githubusercontent.com/assets/4696328/8345703/0a04e806-1b2e-11e5-95e4-2ec23b82a217.png)

문자 내용은 다음과 같습니다. 

- 미납금 요청 문자 : [열린옷장] 안수봉님 0일 연체되어 00000원 입금바랍니다. 국민은행 205701-04-269524

**Comment by keedi** [comment]
진행합니다.

**Comment by keedi** [comment]
처리한 내역은 다음과 같습니다.

- 연체료 입력시 미납으로 저장할 수 있게 함
- 미납 중 항목을 따로 열람할 수 있게 함
- 미납 중인 대여자에게 문자를 발송할 수 있게 함

**Comment by keedi** [comment]
테스트상은 정상 동작하는 것 같으나 예상치 못한 부분이 있을수도 있습니다. 그런 부분은 피드백을 받은 후 처리하겠습니다. 오늘 중으로 배포 완료하겠습니다.

**Comment by keedi** [comment]
부분반납의 경우 명확한 명세나 요구사항이 없어서 고려하지 않았습니다. 부분반납 건에 대해 잘 동작할지, 제대로 동작할지는 의문입니다. 부분 반납의 경우 보이기를 원하는 그림이나 예가 있으면 좋겠지만, 현재 없으므로 따로 진행하지 않았습니다.

**Comment by keedi** [comment]
배포 완료했습니다. 이슈 닫습니다.

**Comment by keedi** [comment]
연체료 및 연체료 에누리를 계산하는 부분에서 반납인 경우에 한해 계산하도록 했는데, 반납이라 하더라도 해당 컬럼이 없는 경우가 있기 때문에 파라미터가 `unpaid`인 경우에 한해 열람하도록 수정했습니다. 본 문제로 인해 ᅟexception이 발생했는데 이를 8c48898 커밋에서 수정했습니다.

실서버에 배포 또한 완료했습니다.

**Comment by 10001if** [comment]
현재까지는 문제없이 정상적으로 작동하고 있습니다.

**Comment by 10001if** [comment]
미납금 요청 문자의 계좌번호 수정을 요청드립니다.

기존 - [열린옷장] 안수봉님 0일 연체되어 00000원 입금바랍니다. 국민은행 205701-04-269524
변경요청 - [열린옷장] 안수봉님 0일 연체되어 00000원 입금바랍니다. 국민은행 205737-04-003013

계좌번호가 변경되었기에 수정 요청드립니다.

**Comment by keedi** [comment]
@10001if 대표님 이런 이슈는 별개의 이슈니까 별도의 이슈를 만들어서 적어주시는게 적절합니다. 일단 이슈 닫습니다. 별도 이슈로 등록 부탁드립니다. :)
