### ISSUE TITLE
주문서의 항목 검색 및 반납 관련 버튼을 주문서 항목 위로 옮김

### ISSUE THREAD

**Issue by keedi** [opencloset/opencloset#482]
검색 및 반납 관련 버튼이 아래쪽에 있어서 반납 진행시 보기가 힘들다고 합니다. 따라서 주문서 항목 윗 부분으로 위치를 변경합니다.

![screenshot-monster silex kr 10301 2015-06-16 14-59-53](https://cloud.githubusercontent.com/assets/138451/8176768/b2998ff0-1438-11e5-8ece-4430d0bd5a69.png)

**Comment by keedi** [comment]
커피스크립트 및 CSS와 관련해 부작용이 있는지도 확인이 꼭 필요합니다.

**Comment by aanoaa** [comment]
현재 부분반납에 문제가 있어 보입니다.
부분반납 했는데 전체 반납이 되어버려요.

**Comment by aanoaa** [comment]
해당 DOM 의 위치를 변경해도 반납 및 환불은 처리됩니다.

**Comment by aanoaa** [comment]
![screenshot-localhost 5001 2015-06-22 11-44-26](https://cloud.githubusercontent.com/assets/170528/8274841/2f974ebc-18d4-11e5-9180-66f91a32b316.png)

`부분반납` 버튼을 누르면

![screenshot-localhost 5001 2015-06-22 11-44-42](https://cloud.githubusercontent.com/assets/170528/8274843/39100e66-18d4-11e5-9ac3-70ebc26c3e9f.png)

전체반납이 되어버립니다.

이부분 먼저 수정해야합니다.

**Comment by aanoaa** [comment]
부분반납을 눌렀을때 처리되는과정입니다.

    [Mon Jun 22 11:47:20 2015] [debug] POST "/api/order_detail.json"
    [Mon Jun 22 11:47:20 2015] [debug] Routing to a callback
    [Mon Jun 22 11:47:20 2015] [debug] Routing to a callback
    Object-oriented Mojo::Loader API is DEPRECATED at /home/aanoaa/.plenv/versions/5.20.0/lib/perl5/site_perl/5.20.0/Mojolicious/Plugin/Validator.pm line 34.
    [Mon Jun 22 11:47:20 2015] [debug] 201 Created (0.009032s, 110.717/s)
    [Mon Jun 22 11:47:20 2015] [debug] PUT "/api/order/8323/return-part.json"
    [Mon Jun 22 11:47:20 2015] [debug] Routing to a callback
    [Mon Jun 22 11:47:20 2015] [debug] Routing to a callback
    Object-oriented Mojo::Loader API is DEPRECATED at /home/aanoaa/.plenv/versions/5.20.0/lib/perl5/site_perl/5.20.0/Mojolicious/Plugin/Validator.pm line 34.
    Object-oriented Mojo::Loader API is DEPRECATED at /home/aanoaa/.plenv/versions/5.20.0/lib/perl5/site_perl/5.20.0/Mojolicious/Plugin/Validator.pm line 34.
    Object-oriented Mojo::Loader API is DEPRECATED at /home/aanoaa/.plenv/versions/5.20.0/lib/perl5/site_perl/5.20.0/Mojolicious/Plugin/Validator.pm line 34.
    [Mon Jun 22 11:47:20 2015] [error] Failed to posting event: Internal Exception
    Object-oriented Mojo::Loader API is DEPRECATED at /home/aanoaa/.plenv/versions/5.20.0/lib/perl5/site_perl/5.20.0/Mojolicious/Plugin/Validator.pm line 34.
    Object-oriented Mojo::Loader API is DEPRECATED at /home/aanoaa/.plenv/versions/5.20.0/lib/perl5/site_perl/5.20.0/Mojolicious/Plugin/Validator.pm line 34.
    Use of uninitialized value $_ in numeric eq (==) at /home/aanoaa/repo/opencloset/opencloset/bin/opencloset.pl line 679.
    Object-oriented Mojo::Loader API is DEPRECATED at /home/aanoaa/.plenv/versions/5.20.0/lib/perl5/site_perl/5.20.0/Mojolicious/Plugin/Validator.pm line 34.
    [Mon Jun 22 11:47:20 2015] [debug] overriding height from user for order creation
    [Mon Jun 22 11:47:20 2015] [debug] overriding weight from user for order creation
    [Mon Jun 22 11:47:20 2015] [debug] overriding bust from user for order creation
    [Mon Jun 22 11:47:20 2015] [debug] overriding waist from user for order creation
    [Mon Jun 22 11:47:20 2015] [debug] overriding topbelly from user for order creation
    [Mon Jun 22 11:47:20 2015] [debug] overriding thigh from user for order creation
    [Mon Jun 22 11:47:20 2015] [debug] overriding arm from user for order creation
    [Mon Jun 22 11:47:20 2015] [debug] overriding leg from user for order creation
    Odd number of elements in hash assignment at /home/aanoaa/repo/opencloset/opencloset/bin/opencloset.pl line 295.
    [Mon Jun 22 11:47:20 2015] [debug] 201 Created (0.070239s, 14.237/s)

- POST "/api/order_detail.json"
- PUT "/api/order/8323/return-part.json"

두개의 routes 가 처리하고 있습니다.

    [Mon Jun 22 11:47:20 2015] [error] Failed to posting event: Internal Exception

이거는 monitor 를 띄워놓지 않아서 발생한 것이고,

    Use of uninitialized value $_ in numeric eq (==) at /home/aanoaa/repo/opencloset/opencloset/bin/opencloset.pl line 679.
    Odd number of elements in hash assignment at /home/aanoaa/repo/opencloset/opencloset/bin/opencloset.pl line 295.

이부분이 의심스럽습니다.

**Comment by aanoaa** [comment]
UPDATE `clothes` SET `status_id` = ? WHERE ( `id` = ? ): '9', '4471'
    UPDATE `clothes` SET `status_id` = ? WHERE ( `id` = ? ): '9', '1691'
    UPDATE `clothes` SET `status_id` = ? WHERE ( `id` = ? ): '9', '3398'
    UPDATE `clothes` SET `status_id` = ? WHERE ( `id` = ? ): '9', '3397'
    UPDATE `clothes` SET `status_id` = ? WHERE ( `id` = ? ): '9', '4979'

부분반납에서 반납되지 않은 의류는 `대여중` 으로 남아 있어야 하는데, `반납`으로 상태가 변경됩니다.

---------------------------------------------

새로운 주문서에는 반납되지 않은 의류가 포함됩니다.(4979, 4471, 1691)

    INSERT INTO `order_detail` ( `clothes_code`, `final_price`, `name`, `order_id`, `price`, `status_id`) VALUES ( ?, ?, ?, ?, ?, ? ): '0S0VM', '5000', 'S0VM - 셔츠', '8484', '5000', '2'
    INSERT INTO `order_detail` ( `clothes_code`, `final_price`, `name`, `order_id`, `price`, `status_id`) VALUES ( ?, ?, ?, ?, ?, ? ): '0T0C7', '0', 'T0C7 - 넥타이', '8484', '0', '2'
    INSERT INTO `order_detail` ( `clothes_code`, `final_price`, `name`, `order_id`, `price`, `status_id`) VALUES ( ?, ?, ?, ?, ?, ? ): '0A0KX', '5000', 'A0KX - 신발', '8484', '5000', '2'


부분반납임에도 주문서의 모든 의류의 상태를 `반납`으로 변경하는 버그가 아닌가 싶습니다.

**Comment by aanoaa** [comment]
@keedi

https://github.com/opencloset/opencloset/blob/develop/bin/opencloset.pl#L1968

에서(update the order) 부분반납임에도 주문서에 포함된 의류의 상태를
모두 반납으로 고치는데, 이게 정상적인건가요?

**Comment by keedi** [comment]
음 다른 작업 때문에 답변이 늦어졌는데 부분 반납은 기존 주문서의 모든 항목을 반납한 후에 하위 주문서를 생성해서 부분 반납한 항목을 제외한 나머지 항목을 대여 목록에 넣습니다. 간단하게 말씀드리면 다음과 같습니다.

- 10번 주문서에서 A, B, C, D, E, F를 빌렸다.
- A, B, C, D, E, F 모두 대여중이다.
- C, E, F를 부분 반납한다.
- 10번 주문서에서 A, B, C, D, E, F 모두 반납이다.
- 새로운 주문서 15를 만든 후 A, B, D를 대여중 상태로 만든다.

이때 15번 주문서는 10번 주문서의 하위주문서이고 10번 주문서는 15번 주문서의 상위 주문서입니다. 주문서 상단의 상위 주문서 하위 주문서를 확인하면 해당 주문서가 부분 반납인지 아닌지를 확인할 수 있습니다. 말씀만 봤을때는 정상으로 보입니다만, 혹시 이상한 부분이 있으면 말씀해주세요.

**Comment by aanoaa** [comment]
하위 주문서에서도 부분반납인데 상태가 `반납` 으로 되어있습니다.
주문서를 확정해야 반납에서 대여중으로 바뀌는군요.

이해했습니다.
주문서를 새로 만들어주고, 담당자가 그걸 확인하는 절차를 거치면 예상한대로 동작하네요.

**Comment by keedi** [comment]
확인 후 머지 진행합니다.

**Comment by keedi** [comment]
실 서버에 배포 및 확인 완료했습니다. 이슈 닫습니다.
