### ISSUE TITLE
좌측 메뉴 항목의 단축키 지원

### ISSUE THREAD

**Issue by keedi** [opencloset/opencloset#483]
하기 목록을 1번 부터 9번 단축 숫자키로 링크가 동작하도록 지원합니다. 더불어 사이드바에 해당 단축 키를 보여주어야 사용자가 헷갈리지 않습니다.

- 첫 화면
- 새 옷
- 사용자
- 기증
- 방문 예약
- 문자 전송
- 시간표
- 주문서
- 대여

![screenshot-monster silex kr 10301 2015-06-16 15-19-42](https://cloud.githubusercontent.com/assets/138451/8177028/3d1f6850-143b-11e5-969c-b872802c7456.png)

**Comment by aanoaa** [comment]
- 예약
- 방문예약(직원전용)

이렇게 있는데 둘중에 하나만 단축키로 지정되어야 하는건가요?

**Comment by aanoaa** [comment]
단축키가 매번 보여질 수도 있지만, 참고해서 사용할 수 있어도 좋습니다.
gmail / github 처럼 `?` 를 누르면 어디에서나 단축키에 대한 내용을 참고할 수 있도록 하고,
표시는 안 할수도 있습니다.

**Comment by aanoaa** [comment]
그리고 첫화면 같은 경우에는 자동으로 input 에 focus 가 있기 때문에 `1` 을 눌렀을때에 `1` 이 입력이 되어 버립니다.

이런건 불편하니까, `Ctrl + 1` 이런식으로 하거나 `Home` 의 `h` 를 빌려와서 `Ctrl + h` 를 누르면 home 으로 기억하기 쉽도록 할 수도 있습니다.

**Comment by aanoaa** [comment]
제 맘대로 하겠습니다.

`ctrl+h` => home
`ctrl+n` => 새옷 new clothes
`ctrl+u` => 사용자 user
`ctrl+d` => 기증 donation
`ctrl+T` => 태그 tag
`ctrl+b` => 예약 booking
`ctrl+s` => 문자전송 sms
`ctrl+t` => 시간표 timetable (더 자주 사용하는거라서 `t`, 태그는 `T`)
`ctrl+o` => 주문서 order
`ctrl+r` => 대여 rental

**Comment by aanoaa** [comment]
`input` 영역에 포커스가 있을때에는 동작하지 않습니다.
이를 해결해야 합니다.

**Comment by aanoaa** [comment]
포커스를 벗어나야 하는데, 가장 쉬운 방법은 tab 한번 누르는 것입니다.

**Comment by keedi** [comment]
`ctrl` 키나 `command` 키 대신에 열린옷장을 의미하는 `o` 키를 누르고 시작하도록 수정했습니다. 물론 숫자 키는 그대로 두었습니다.

**Comment by keedi** [comment]
@aanoaa 고생하셨습니다. :)

**Comment by keedi** [comment]
서버에 배포 및 실서버 대상 테스트 또한 완료했습니다.
이슈 닫습니다. :-)

**Comment by 10001if** [comment]
확인 하였는데요.  메뉴 옆에 숫자 표시가 되었으면 좋겠습니다.
![2015-06-19 4 29 16](https://cloud.githubusercontent.com/assets/4696328/8249009/b4609b0c-16a0-11e5-8b22-fc50f692d0c9.png)
그리고 제가 직접 해봤는데 첫화면, 새옷등의 경우에는 숫자를 누르면 입력창에 값이 들어가네요. 그럼 마우스로 다른 곳을 눌러줘야 할 것 같은데, 여기에 control 같은 키를 더해 가령 ctrl + 1을 하면 어떨지 궁금합니다. 
![2015-06-19 4 34 36](https://cloud.githubusercontent.com/assets/4696328/8249076/8d18ba1a-16a1-11e5-82f0-9bc51ca4c984.png)

**Comment by keedi** [comment]
ctrl / shift / alt / command 와 조합하는 것은 브라우저 및 운영체제 단축키와 겹치기 때문에 좋은 방법이 아닙니다. 위에 언급되었던 것 처럼 탭키를 한 번 누른 후 단축키를 입력하시면 됩니다. 확인 후 답변 달아주세요.

**Comment by keedi** [comment]
더불어 물음표를 누르시면 단축키 목록이 나오는데 이것 말고 메뉴 옆에 표기해딜라는 말씀이신지요?

**Comment by 10001if** [comment]
@keedi  예비군 끝나셨나요? 이렇게 실시간으로 답을 주시다니.. 대단하세요. ^^; ctrl 버튼과 관련해서는 제가 조금 늦게 숙지 했습니다. tab 누르고 사용토록 하겠습니다. 그리고 숫자가 메뉴옆에 표시되는 건은 @aanoaa 님이 옆에 계셔서 말씀드려 놓았습니다. 물음표를 누르면 나오는 단축키 목록은 빼고 숫자만 표시되면 됩니다. ^^

**Comment by keedi** [comment]
@10001if ㅎㅎ 방금 끝나고 복귀중입니다. 탭 관련은 이해해주신다니 다행입니다 ㅋㅋ 메뉴 옆 숫자는 @aanoaa 님만 믿고 가는걸로...=3 :)

**Comment by 10001if** [comment]
@keedi 네! 탭누르는 정도야 수고도 아니죠~! 만들어 주셔서 감사할 따름이예요. 빨리 들어가서 푹 쉬세요~ 고생 많으셨습니다. 형석님이 옆에서 열심히 작업해 주고 계시니~ 믿어주셔도 될 듯 합니다. ^^

**Comment by keedi** [comment]
PR 머지 완료했습니다.

**Comment by keedi** [comment]
실서버에 배포 및 테스트 완료했습니다. 이슈 닫습니다.

**Comment by 10001if** [comment]
확인 완료하였습니다.

**Comment by aanoaa** [comment]
input field 에 포커스가 되어 있어도 이동할 수 있을 것 같습니다.

https://craig.is/killing/mice#api.stopCallback

**Comment by aanoaa** [comment]
지금 `1` ~ `9` 까지 binding 되어 있는 단축키를 `ctrl+1` ~ `ctrl+9` 로 바꾸는건 어떨까요?
포커스에 상관없이 단축키 사용할 수 있는 장점이 있습니다.

단점이라면 브라우저 기본바인딩을 덮어쓴다는점?
하지만 firefox 에선 다행히도 `ctrl+1` ~ `ctrl+9` 는 사용되지 않습니다.

https://support.mozilla.org/ko/kb/keyboard-shortcuts-perform-firefox-tasks-quickly

**Comment by keedi** [comment]
바꾸지 않는 것이 나을 것 같습니다. 이유인즉 윈도우즈에서는 ctrl+1 ~ ctrl+9로 탭을 이동합니다. 운영체제 마다 브라우저들의 단축키 설정이 다르지욥. :-)

**Comment by aanoaa** [comment]
장점이라면 input field 에서 포커스를 벗어나야 하는 불편함을 덜 수 있습니다.

**Comment by aanoaa** [comment]
그리고 포커스가 있다고 생각하고 숫자키를 눌렀을때 화면이 이동되는 불편함도 있다고 합니다.

**Comment by 10001if** [comment]
첫화면에서 마우스 커서가 커서창에 있지 않고 외부에 있을 때 의류 바코드를 스캐너로 찍을 경우에 그 바코드안에 1~9의 숫자가 있으면 해당 창으로 이동해 버리는 분제가 발생하고 있습니다. 물어보니 단축키를 사용하는 옷장지기가 거의 없다고 하네요. 단축키 기능 삭제를 요청드립니다. 고생해서 만들어 주셨는데, 잘 사용을 못했네요.

**Comment by aanoaa** [comment]
헉 컨트롤 누르고 단축키는 어떨까요?

**Comment by 10001if** [comment]
네! 문제만 없다면 상관 없을 것 같습니다~

**Comment by keedi** [comment]
사실 단축키 아무도 안쓸것 같긴했는데...

**Comment by aanoaa** [comment]
탭 선택 (1 에서 8) 	Alt + 1 로부터 8

Ctrl 로 적용합니다.

**Comment by aanoaa** [comment]
기억이 잘 안나지만 전에는 input field 안에 focus 가 있어도 ctrl 과 같이 누르면 이동할 수 있엇는데,
지금 해보니 안됩니다.

걍 삭제 ㄱㄱ

**Comment by aanoaa** [comment]
헉 찾음

**Comment by aanoaa** [comment]
적용하였습니다.

**Comment by 10001if** [comment]
@aanoaa 제 맥에서는 잘되는데 윈도우에서는 컨트롤 + 번호키를 누르니까 상단 탭이 지정됩니다~ ^^;

**Comment by aanoaa** [comment]
단축키 기능은 짬시키도록 하겠습니다.

**Comment by aanoaa** [comment]
너무 불편해서 없애는 걸로..
