### ISSUE TITLE
모바일기기에서 예약할때 의류와 대여목적을 선택할 수 없음

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#485]
http://harvesthq.github.io/chosen/#faqs

> What browsers are supported?
> 
> All modern desktop browsers are supported (Firefox, Chrome, Safari
> and IE9). Legacy support for IE8 is also enabled. Chosen is disabled
> on iPhone, iPod Touch, and Android mobile devices (more
> information).

chosen 라이브러리를 사용한 input 은 모바일기기에서 동작하지 않습니다.
이를 대체가능한 라이브러리로 바꾸거나 동작할 수 있도록 수정해야 합니다.

**Comment by keedi** [comment]
제 아이폰 및 안드로이드 장비에서 장상적으로 의류 선택 및 대여 목적 입력이 되고 있습니다. 무엇이 문제인지요?

**Comment by aanoaa** [comment]
테스트과정에서 아이폰 크롬에서 입력을 할 수 없어서 찾아보니까
공식적으로 지원하지 않더라고요.

> Chosen is disabled on iPhone, iPod Touch, and Android mobile devices

**Comment by keedi** [comment]
지원을 하지 않는 것이 아니라 chosen이 disable되어 일반적인 셀렉스 박스나 콤보 박스로 동작한다는 의미입니다. 4S에서 선택 및 동작하는 화면은 다음과 같습니다. 안드로이드도 동일하긴 합니다.

![15 6 18 11 44 51](https://cloud.githubusercontent.com/assets/138451/8223375/adb82670-15b1-11e5-9c13-b79fef0097e5.png)

**Comment by keedi** [comment]
@aanoaa 저장소에 없는 파일중 혹시 로컬 버전과 다른 항목이 있는지 체크해보신 다음 서버쪽 파일을 땡겨와보시고 확인 부탁드립니다.

**Comment by aanoaa** [comment]
`/public/theme/ace/css/ace.min.css` 파일이 달랐습니다.
minify 되어 있어서 어느부분이 다른지는 확인이 어렵습니다.

파일을 교체하고 대여목적과 의류를 선택할 수 있습니다.

**Comment by aanoaa** [comment]
서버와 sync 맞추기가 번거로우니까 `bower` 의 사용을 검토해볼만 합니다.

https://github.com/opencloset/opencloset/pull/219 에서는 최신버전의
ace-theme 까지 같이 적용시키느라 문제가 좀 있엇는데, theme 는 빼고
front-end 패키지들만이라도 관리 시키면 좋을 것 같습니다.

근데 생각해보니까 theme 에서 직접 다른 패키지 의존성을 포함하기 때문에
사용하기 어렵겠네요.

**Comment by aanoaa** [comment]
MD5 (ace.min.css.local) = 9c309756017a2a31c6dde98b2045c60b
MD5 (ace.min.css.server) = 17fa362df4305e2e2d369ef039efffb9

`17fa362df4305e2e2d369ef039efffb9` 를 사용해야 합니다.
