### ISSUE TITLE
온라인 주문 관련 문자 매크로 추가

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#487]
추가 매크로 작성 내용

- 온라인 배송 후 안내 문자
[열린옷장] 00님 송장번호:CJ대한통운/1234-5678-9000 반납 시, 받은 상자에 담아 보내주세요^^

- 온라인 입금 안내 문자  
[열린옷장] 결제금액:00000원입니다. 금일 00시까지 입금해주세요. 국민은행 205701-04-269524

- 온라인 자동 취소 문자
   [열린옷장] 00님 금일 00시까지 온라인대여 입금 확인이 안 될 경우 발송 취소 됨을 알립니다.

**Comment by keedi** [comment]
진행합니다.

**Comment by keedi** [comment]
서버에 배포 및 테스트도 완료했습니다.
이슈 닫습니다. :)

**Comment by 10001if** [comment]
확인 완료 했습니다.

**Comment by 10001if** [comment]
- 온라인대여 배송 후 안내 문자
[열린옷장] CJ대한통운/1234-5678-9000 반납 시, 받은 상자에 담아 보내주세요. ^^ 


- 온라인대여 입금 안내 문자  
[열린옷장] 대여 금액 32000원, 1시까지 입금해주세요. 국민은행 205701-04-269524

- 온라인대여 자동 취소 문자

[열린옷장] 00님 금일 3시까지 입금되지 않을 경우 발송 취소 됨을 알립니다.

**Comment by 10001if** [comment]
기존에 남겼던 문자들이 40자를 넘어 수정된 문구를 다시 보내드립니다. 확인 부탁드립니다. :)

**Comment by keedi** [comment]
@10001if 대여 금액은 32000원으로 설정하나요? 아니면 00000원으로 설정하나요?

**Comment by keedi** [comment]
특별히 언급이 없어서 00000원으로 설정했습니다. 배포 완료했으며 이슈 닫습니다.

**Comment by 10001if** [comment]
확인 완료하였습니다.
