### ISSUE TITLE
이미 대여중인 주문서에 포장을 진행할 경우 포장으로 상태가 변경되며 항목이 아래에 추가됨

### ISSUE THREAD

**Issue by keedi** [opencloset/opencloset#493]
8413, 8433 주문서에서 확인한 버그입니다.

이미 대여가 끝난 주문서에 대해 포장을 진행할 경우 대여중인 주문서임에도 불구하고 강제로 포장 상태로 상태가 변경되며 바코드로 찍은 의류가 해당 주문서 아래에 추가됩니다. 이런 문제가 발생한 사례는 다음과 같습니다.

- 방문자가 많아 포장을 2명 이상이 2대 이상의 장비에서 진행함
- 포장 페이지는 실시간 갱신이 되지는 않음
- 한쪽에서 포장을 진행한 후 결제가 끝나고 대여까지 끝남
- 다른 한쪽에서 실수로 다른 의류를 이미 끝난 주문서에 대해 포장을 진행함

문제의 원인은 다음과 같습니다.

- 애초에 포장은 워낙 간단하기 때문에 1명이 진행한다고 고려함
- 페이지가 실시간 갱신이 되지 않음
- 포장 진행시 주문서의 상태를 확인해서 포장을 진행하면 안되는 경우를 고려하지 않았음

모두 다 수정하는 방법도 있겠지만, 이 중 하나만 해결해도 치명적인 문제는 해결할 수 있을 것으로 보입니다. 일단 실시간 갱신은 생각보다 고려할 상황이 많기 때문에 논외로 둡니다. 마지막 원인만 해결하면 치명적인 버그는 해결될 것으로 보입니다.

**Comment by keedi** [comment]
정리하면 포장 진행시 선택한 주문서가 특정 상태일 경우 상단에 오류 사유를 출력합니다. 오류를 출력한 후에는 바로 하단의 포장 대기 상태의 주문서 목록을 갱신해줍니다. 오류 사유에 해당하는 주문서 상태는 다음과 같습니다.

- 대여중
- 반납
- 부분반납
- 반납배송중
- 방문안함
- 결제대기
- 대여안함
- 환불
- 사이즈없음

즉 상시 실시간 갱신을 하는 대신 오류가 발생한 경우에만 테이블을 갱신을 합니다.

**Comment by keedi** [comment]
@aanoaa 잘 부탁드립니다~ =3

**Comment by aanoaa** [comment]
포장 페이지가 뭔가요?

**Comment by keedi** [comment]
일명 대여 페이지입니다. 대여 페이지에서 포장을 진행하거든요.

**Comment by keedi** [comment]
오류 메시지 후에 테이블 갱신이 까다롭다면 오류 메시지를 상단 출력 대신 팝업으로 대체하고 확인을 누를 경우 해당 대여 페이지를 강제 갱신해도 됩니다. 작업량은 훨씬 줄어들 것입니다. 어떤 쪽이든 편하신 방향으로 부탁드립니다.

**Comment by keedi** [comment]
@aanoaa++

**Comment by keedi** [comment]
배포 완료 했습니다. 이슈 닫습니다.
