### ISSUE TITLE
반납시 연체료 처리를 하지 않았는데 반납이 되는 주문서가 있음

### ISSUE THREAD

**Issue by keedi** [opencloset/opencloset#494]
현재 시스템 구조상 연체료 처리를 하지 않을 경우 반납을 할 수 없도록 구현되어 있습니다. 그럼에도 불구하고 가끔 주문서 중에는 연체료 처리를 하지 않았는데도 반납이 된 경우가 있습니다. 문제의 원인을 찾고 해결해야 합니다.

**Comment by yongbin** [comment]
@10001if  대표님 이 이슈 혹시 다시 발생한적이 있는지 확인 부탁드립니다.

**Comment by 10001if** [comment]
@yongbin 사실 이 이슈가 언제 발생했는지 잘 기억이 나지 않는데, 현재는 발생하지 않고 있습니다.

**Comment by yongbin** [comment]
작년 6월 이후로 재현되지 않고 최근에는 발생하는 이슈가 아니기 때문에 이슈 닫도록 하겠습니다. 만약 동일한 이슈가 발생하면 새로운 이슈에서 진행하면 됩니다.
