### ISSUE TITLE
이미 반납한 주문서에도 연체 문자 전송이 보임

### ISSUE THREAD

**Issue by keedi** [opencloset/opencloset#497]
반납하지 않았으면서 연체된 경우에 한해 연체 문자 전송 항목이 보여야 합니다. 지금은 반납이 되었더라도 해당 링크가 보입니다.

![screenshot-monster silex kr 10301 2015-06-23 16-35-20](https://cloud.githubusercontent.com/assets/138451/8301113/2ceb3488-19c6-11e5-917a-07540c7e73a3.png)

**Comment by keedi** [comment]
작업한 내역은 다음과 같습니다.

- 대여중인 주문서 중 연체 항목에 한해 연체 문자 전송 링크를 보여줌
- 연체중이라도 반납 희망일이 지나지 않은 경우 연체 문자 전송 링크를 보여주지 않음

**Comment by keedi** [comment]
이슈 닫습니다.

**Comment by keedi** [comment]
서버에 배포도 완료되었습니다.

**Comment by 10001if** [comment]
잘 이해가 되지 않는 부분이 있습니다. 이따 찾아뵙고 여쭤보겠습니다.
