### ISSUE TITLE
반납 희망일이 반납 예정일보다 앞서는 경우가 존재함

### ISSUE THREAD

**Issue by yongbin** [opencloset/opencloset#499]
#477 을 처리하면서 확인하게된 자료상의 정합성 문제입니다.

**연장**은 `반납희망일`에서 `반납예정일`을 뺀 값입니다. 이 값이 음수가 나오는경우는 대여자가 자신이 반납을 약속한 시점보다 먼저 반납을 하기로 별도로 연락을 주고 방문한 경우라고 볼수 있습니다. 하지만  @10001if 님에 말씀에 따르면 현장에서 이런 경우는 발생하지 않으며 대부분이 옷장지기가 목,금에 옷을 대여하는 분들의 대여일을 4박 5일로 변경할때 `반납예정일`만 변경하고 `반납희망일`을 변경하지 않은 실수라고 합니다. 

추가적으로 @keedi 님과 확인한 결과 현재 주문서 생성 프로세스에서 대여기간을 변경하는 시점에는 `반납예정일`과 `반납희망일`이 모두 변경되지만 `반납예정일`만 변경하는 경우에는 `반납희망일`이 변경되지 않음을 확인했습니다. 따라서 한대표님이 말씀하신 시나리오가 발생할 수 있습니다. 

이 이슈에서는 DB상의 625건의 자료를 검토한 뒤 조정하는 작업을 진행하도록 하겠습니다.

**Comment by yongbin** [comment]
참고로 현재 DB상 `반납희망일`이 `반납예정일`보다 이전인 625건의 현황입니다. 

extend | count
-------| -------
-8|1
-7|1
-5|4
-4|8
-3|20
-2|215
-1|376

**Comment by yongbin** [comment]
몇건 되지 않으니 -3 이하인건들은 @10001if 님 께서 전수확인해주셨으면 합니다.

### -3 인 주문서 
- https://staff.theopencloset.net/order/1178
- https://staff.theopencloset.net/order/1771
- https://staff.theopencloset.net/order/2416
- https://staff.theopencloset.net/order/2596
- https://staff.theopencloset.net/order/2597
- https://staff.theopencloset.net/order/2675
- https://staff.theopencloset.net/order/2677
- https://staff.theopencloset.net/order/2678
- https://staff.theopencloset.net/order/2679
- https://staff.theopencloset.net/order/2748
- https://staff.theopencloset.net/order/2749
- https://staff.theopencloset.net/order/2773
- https://staff.theopencloset.net/order/2786
- https://staff.theopencloset.net/order/2787
- https://staff.theopencloset.net/order/2813
- https://staff.theopencloset.net/order/3166
- https://staff.theopencloset.net/order/3398
- https://staff.theopencloset.net/order/3883
- https://staff.theopencloset.net/order/3936
- https://staff.theopencloset.net/order/7589

## -4인 주문서 

- https://staff.theopencloset.net/order/520
- https://staff.theopencloset.net/order/556
- https://staff.theopencloset.net/order/1327
- https://staff.theopencloset.net/order/1329
- https://staff.theopencloset.net/order/1770
- https://staff.theopencloset.net/order/2203
- https://staff.theopencloset.net/order/2209
- https://staff.theopencloset.net/order/4613

## -5인 주문서

- https://staff.theopencloset.net/order/1905
- https://staff.theopencloset.net/order/1914
- https://staff.theopencloset.net/order/2174
- https://staff.theopencloset.net/order/6461

## -7인 주문서 
- https://staff.theopencloset.net/order/2175

## -8인 주문서
 - - https://staff.theopencloset.net/order/2125

**Comment by yongbin** [comment]
@10001if  님께서 저 주문서들을 모두 수정해 주시면 이후 -1, -2 인 경우는 쿼리로 한번에 `반납희망일`을 `반납예정일`과 동일하게 조정하도록 하겠습니다.

**Comment by yongbin** [comment]
지금 확인하고 있는 쿼리는 아래와 같습니다.

```SQL
SELECT * FROM
(
            SELECT
                        a.`id`
                        ,DATE(a.`rental_date`)          AS `rental`
                        ,MONTH(a.`rental_date`)         AS `rental_month`
                        ,DAYOFWEEK(a.`rental_date`)     AS `rental_wd` -- 1 = Sunday, 2 = Monday, …, 7 = Saturday
                        ,DATE(a.`target_date`)          AS `target`
                        ,DATE(a.`user_target_date`)     AS `user_target`
                        ,DATE(a.`return_date`)          AS `return`
                        ,a.`return_method`              AS `method`
                        ,a.`purpose`                    AS `purpose1`
                        ,a.`purpose2`                   AS `purpose2`
                        ,c.`gender`                     AS `gender`
                        ,IF(DAYOFWEEK(a.`rental_date`) = 5 OR DAYOFWEEK(a.`rental_date`) = 6,4,3) AS rent_dur
                        ,additional_day                 AS `additional_day`
                        ,DATEDIFF(DATE(a.`user_target_date`),DATE(a.`target_date`)) AS `extend`
                        ,DATEDIFF(DATE(a.`return_date`),DATE(a.`user_target_date`)) AS `late`
                        ,DATEDIFF(DATE(a.`target_date`),DATE(a.`rental_date`)) AS `promised_rent_dur`
                        ,DATEDIFF(DATE(a.`return_date`),DATE(a.`rental_date`)) AS `real_rent_dur`
                        ,DATEDIFF(DATE(a.`user_target_date`),DATE(a.`target_date`)) + DATEDIFF(DATE(a.`return_date`),DATE(a.`user_target_date`)) AS `total_delay`
                        ,d.`deley_fee`
                        ,DATEDIFF(DATE(a.`user_target_date`),DATE(a.`target_date`)) * d.`deley_fee` AS `extend_fee`
                        ,( DATEDIFF(DATE(a.`target_date`),DATE(a.`rental_date`)) - IF(DAYOFWEEK(a.`rental_date`) = 5 OR DAYOFWEEK(a.`rental_date`) = 6,4,3) ) * d.`deley_fee` AS `extend_fee2`
                        ,DATEDIFF(DATE(a.`return_date`),DATE(a.`user_target_date`)) * d.`deley_fee` AS `late_fee`
                        ,( DATEDIFF(DATE(a.`user_target_date`),DATE(a.`target_date`)) * d.`deley_fee` ) + ( DATEDIFF(DATE(a.`return_date`),DATE(a.`user_target_date`)) * d.`deley_fee` )  AS `total_delay_fee`

            FROM
                        `order` AS a
                        INNER JOIN `user`       AS b ON a.`user_id` = b.`id`
                        INNER JOIN `user_info`  AS c ON b.`id`      = c.`user_id`
                        INNER JOIN (
                        SELECT
                        order_id
                        ,MAX(CASE WHEN `name` = '연체료'         THEN `price` END) AS deley_fee
                        ,MAX(CASE WHEN `name` = '연체료 에누리'  THEN `price` END) AS deley_fee_discount
                        FROM `order_detail`
                        WHERE `name` = '연체료' OR `name` = '연체료 에누리'
                        GROUP BY `order_id`
                        ) AS d ON a.`id` = d.`order_id`
) AS a
WHERE extend < 0 
```

**Comment by 10001if** [comment]
-3 이하인건들은 전수확인 하였습니다. 특별히 이상이 있는 건은 없었습니다. 모든 주문서의 반납희망일을 수정하였습니다.

**Comment by yongbin** [comment]
남은건들은  SQL로 변경하도록 하겠습니다. 먼저 변경대상이 되는 주문서의 수를 확인합니다.

```SQL
SELECT DATEDIFF(DATE(`user_target_date`),DATE(`target_date`)) AS `extend` FROM `order` WHERE DATEDIFF(DATE(`user_target_date`),DATE(`target_date`)) < 0 
```

확인결과 596건이 대상입니다.

다음 변경을 진행합니다.

```SQL
UPDATE `order` SET `user_target_date` = `target_date` WHERE DATEDIFF(DATE(`user_target_date`),DATE(`target_date`)) < 0 LIMIT 596;
```

결과는 다음과 같습니다.

```
No errors; 596 rows affected, taking 33.8 ms
```

잘 반영되었습니다.

**Comment by yongbin** [comment]
DB 상에 자료는 확인해서 모두 수정을 완료했습니다. 기존 자료는 모두 수정했지만 사용자가 자주 실수하는 상황은 여전히 존재하기 때문에 시간이 자나면 동일한 자료가 계속 쌓일것으로 예상됩니다. 만약 그런 부분에서 사용자의 실수를 줄이는 방향으로 변경을 한다면 별도의 이슈에서 처리되어야 합니다. @keedi 님께서 확인후 이슈닫아주시기 바랍니다.

**Comment by keedi** [comment]
확인 진행중입니다. 이후 이슈 닫겠습니다.

**Comment by keedi** [comment]
최초 커멘트를 보면 다음과 같은 내용이 있습니다.

> #477 을 처리하면서 확인하게된 자료상의 정합성 문제입니다.

결론적으로 말하면 정합성과 아무 상관이 없으며, 반납 희망일이 반납 예정일보다 이른 것은 시스템적으로 아무런 영향을 미치지 않기 때문에 신경 쓸 필요가 아예 없습니다. 따라서 반납 희망일이 반납 예정일보다 앞서는 경우의 자료를 굳이, 반납 예정일로 일치하게 수정하는 일은 불필요하며, 의미가 없으며, 되려 할 이유도 없습니다.

통계적으로 처리하는데는 애로사항이 있을지는 모르나 의도된 상황이기 때문에 시스템적으로 수정할 계획은 없을듯 합니다. 통계 자료를 처리할 때 희망일이 예정일보다 이른 경우는 희망일과 예정일이 동일한 경우와 똑같이 처리하면 됩니다. 앞으로는 서로 다른 날이 생겨도 굳이 자료를 수정하지 않는 것이 좋을 것 같습니다.

**Comment by keedi** [comment]
딱히 통계 이슈는 아닙니다.

**Comment by keedi** [comment]
시스템 상 허용하는 케이스기 때문에 실DB 이슈도 아닙니다.

**Comment by keedi** [comment]
확인 완료했으며 이슈 닫습니다.

**Comment by yongbin** [comment]
제가 표현을 잘못했네요 시스템상에서 자료의 정합성이슈는 아니고 따라서 버그도 아닙니다. 다만 사용자 실수를 통해 발생된 입력실수를  일부는 확인후 수동으로 수정하고 일부는 DB에 직접 쿼리를 통해서 수정했기때문에 실DB 테그를 포함했습니다. 의도된 결과이며 수정계획이 없다는점은 모두 이해했습니다.
