### ISSUE TITLE
Body Labs의 BodyKit 서비스를 활용해 키와 몸무게로 신체 치수 예측

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#509]
키와 몸무게를 가지고 대략 신체치수를 알아내기 위해서 #317 을 진행하고 있습니다.
이와 더불어 http://www.bodylabs.com/bodykit.html 서비스를 한달에 20~30 불로 이용할 수도 있습니다.

온라인 대여자들을 위해 키와 몸무게를 가지고 신체치수를 알아내기 위함인데 사용가능여부를 검토합니다.

**Comment by aanoaa** [comment]
[flexible schema](http://developer.bodylabs.com/measurement_guide.html#Flexible-Scheme) 를 활용할 수 있습니다.

http://developer.bodylabs.com/instant_api_reference.html 에 자세히 나와 있는데,
키와 몸무게를 가지고 여러가지 신체치수 데이터를 얻어올 수 있습니다.

각 부위별 명칭은 아래 문서에서 확인할 수 있습니다.
http://developer.bodylabs.com/bower_components/assets.measurement_guides/measurement_guide.pdf

**Comment by aanoaa** [comment]
1. 한국 사이즈 44, 55, 66등등 측량을 뭐애요? 예이를 들어서 한국 여성
  사이즈 44의 가슴, 허리, 힢의 측량이 어떻게되요? 이측량을 다 알면
  Instant API의 미국사이즈를 다 한국 사이즈로 바꿀수있어요.
2. 연린옷장은 소프트웨어 개발자 (software developer)이랑
  협력하고있어요? Body Labs은 소프트웨어 개발자가 사이즈를 다
  한국사이즈으로 바꿀수있다고 말했어요. 아니면 연린옷장에 할수있는
  사람 있어요?
3. 소프트웨어 개발자이랑 협력안하는데 협력하고싶으면 Body Labs은
 연린옷장와 소프트웨어 개발자이랑 동화할수있어요. 그렇치만 소프트웨어
 개발자랑 협력안하고 하나 임차하고싶으면 요금은 $1000쯤
 될꺼같아요. 너무 비싸면 Body Labs은 좀 도와줄수있다고 말했어요. 
4. 연린옷장은 Body Labs의 Instant API를 쓰고싶으면 설치 타임라인있어요?

4번은 뭔지 모르겠고, 1,2,3 번은 같은말인데 제가 할 수 있을 것
같습니다.

**Comment by aanoaa** [comment]
> Instant API가 아직은 beta이고 현재는 무료로 쓸수있다고 해요. 
> Instant API가 공식적으로 시작되면 월에 20$씩 청구되는 것으로 진행한다고 하네요.
> 
> 저희 쪽 프로그래머가 Body Labs이랑 통화하거나 이메일을 통해 연락을 주고받은 뒤에 
> Body Labs가 저희 프로그래머에게 API key를 주면 Instant API를 바로 쑬수 있다고 하네요.

email 주소는 제가 가지고 있고 직접 연락해보도록 하겠습니다.

**Comment by aanoaa** [comment]
@10001if http://developer.bodylabs.com/bower_components/assets.measurement_guides/measurement_guide.pdf

이거 한번 보시고 bodykit은 어떻게 치수를 재고 있는지 참고하면 좋을 것 같습니다.
우리는 무릎길이를 허리부터 무릎까지로 재고있는데,
저쪽에서는 바닥부터 무릎까지의 높이로 보고 있거든요.

기준이 허리가 아닌 바닥이 된다는 점에서 더 좋은방법인 것 같습니다.

**Comment by 10001if** [comment]
말씀을 듣고 보니 그러네요.
그런 측면에서는 훨씬 더 정확할 것 같은데.

스커트를 실측할 때에는 허리에서 무릎으로 해야만 사이즈를 확인 할 수 있을 것 같다는 생각도 들어요.
고민을 해봐야겠습니다.

**Comment by aanoaa** [comment]
아래는 주문서를 토대로 예측한 사이즈입니다.

    [남][168/57] 중동: 74.8, 윗배: 71.4, 가슴: 84.9, 팔: 57.3, 허벅지: 52.1, 허리: 74.6, 다리: 96.7, 발: 248.7

아래는 bodykit 을 사용했습니다.
차이가 너무 많이 납니다.
서로 다르게 치수를 측정하고 있기 때문인데, `waist_height - knee_height` 로 계산하면 열린옷장에서 사용하고 있는
무릎길이로 사용할 수 있습니다.

    [남][168/57] 중동: , 윗배: , 가슴: 93.01, 팔: 75.5, 허벅지: 53.61, 허리: 76.15, 다리: 107.55, 발: 
    {
      "output": {
        "measurements": {
          "armscye_girth": 46.84,
          "ankle_girth": 26.07,
          "ankle_height": 7.27,
          "above_bust_girth": 94.85,
          "across_back_shoulder_width": 40.04,
          "across_back_width": 35.7,
          "across_front_width": 35.47,
          "back_arm_length": 58.29,
          "back_neck_height": 145.8,
          "back_neck_to_across_back": 14.38,
          "back_neck_to_mid_neck": 2.27,
          "back_neck_to_waist": 44.03,
          "bicep_girth": 27.95,
          "bust_girth": 93.01,
          "bust_height": 123.05,
          "calf_girth": 34.49,
          "calf_height": 33.04,
          "elbow_girth": 23.74,
          "forearm_girth": 24.05,
          "front_neck_height": 137.22,
          "front_neck_to_across_front": 5.16,
          "front_neck_to_mid_neck": 5.03,
          "front_neck_to_waist": 35.56,
          "full_sleeve_length": 75.5,
          "high_hip_girth": 87.38,
          "high_hip_height": 92.79,
          "inseam": 76.67,
          "knee_girth": 35.68,
          "knee_height": 46.92,
          "low_hip_girth": 91.65,
          "low_hip_height": 86.82,
          "mid_neck_girth": 35.71,
          "neck_base_girth": 42.85,
          "outseam": 101.58,
          "height": 168,
          "weight": 57,
          "shirt_sleeve_length": 80.46,
          "shoulder_drop": 5.53,
          "shoulder_length": 13.38,
          "side_arm_length": 56.44,
          "side_neck_to_bust_point": 26.17,
          "thigh_girth": 53.61,
          "thigh_height": 73.32,
          "total_rise_length": 69.66,
          "vertical_trunk_girth": 158.97,
          "waist_girth": 76.15,
          "waist_height": 107.55,
          "waist_to_high_hip": 9.72,
          "waist_to_low_hip": 20.06,
          "wrist_girth": 16.02
        }
      },
      "input": {
        "measurements": { "height": 168, "weight": 57 },
        "unitSystem": "metric",
        "gender": "male",
        "scheme": "flexible"
      }
    }

**Comment by 10001if** [comment]
@ 180/73으로 한번 더 확인 부탁드려도 될까요? 제가 사이즈는 눈으로 확인하면 더 정확하게 이해할 수 있을 것 같습니다. :)

**Comment by aanoaa** [comment]
[남][180/73] 중동: 82.0, 윗배: 80.3, 가슴: 94.0, 팔: 61.7, 허벅지: 56.7, 허리: 84.1, 다리: 103.0, 발: 263.3
    [남][180/73] 중동: , 윗배: , 가슴: 98.61, 팔: 80.03, 허벅지: 56.99, 허리: 82.26, 다리: 115.53, 발: 
    {
      "output": {
        "measurements": {
          "armscye_girth": 50.16,
          "ankle_girth": 27.4,
          "ankle_height": 7.92,
          "above_bust_girth": 100.25,
          "across_back_shoulder_width": 41.84,
          "across_back_width": 37.35,
          "across_front_width": 37.17,
          "back_arm_length": 62.16,
          "back_neck_height": 155.89,
          "back_neck_to_across_back": 15.44,
          "back_neck_to_mid_neck": 2.4,
          "back_neck_to_waist": 46.83,
          "bicep_girth": 29.7,
          "bust_girth": 98.61,
          "bust_height": 131.65,
          "calf_girth": 36.31,
          "calf_height": 35.71,
          "elbow_girth": 25.31,
          "forearm_girth": 25.28,
          "front_neck_height": 146.85,
          "front_neck_to_across_front": 5.52,
          "front_neck_to_mid_neck": 5.31,
          "front_neck_to_waist": 37.98,
          "full_sleeve_length": 80.03,
          "high_hip_girth": 93.68,
          "high_hip_height": 99.5,
          "inseam": 82.72,
          "knee_girth": 37.81,
          "knee_height": 50.66,
          "low_hip_girth": 97.82,
          "low_hip_height": 93.45,
          "mid_neck_girth": 37.24,
          "neck_base_girth": 44.91,
          "outseam": 108.72,
          "height": 180,
          "weight": 73,
          "shirt_sleeve_length": 85.39,
          "shoulder_drop": 5.58,
          "shoulder_length": 13.95,
          "side_arm_length": 60.18,
          "side_neck_to_bust_point": 27.97,
          "thigh_girth": 56.99,
          "thigh_height": 79.1,
          "total_rise_length": 74.28,
          "vertical_trunk_girth": 169.39,
          "waist_girth": 82.26,
          "waist_height": 115.53,
          "waist_to_high_hip": 10.44,
          "waist_to_low_hip": 21.39,
          "wrist_girth": 16.9
        }
      },
      "input": {
        "unitSystem": "metric",
        "scheme": "flexible",
        "measurements": { "weight": 73, "height": 180 },
        "gender": "male"
      }
    }

**Comment by 10001if** [comment]
@aanoaa 팔, 다리 길이 측정방법이 좀 다른 것 같구요.. 서양인 체격이 동양인과 좀 다른 부분도 있는 것 같은데 제가 조금 더 들여다 보도록 하겠습니다.

**Comment by aanoaa** [comment]
measurement_guide.pdf 보시면 각 치수가 어떤지 설명되어 있습니다.

**Comment by yongbin** [comment]
오늘자 기사입니다. 
http://newspeppermint.com/2015/07/09/bmi/

**Comment by aanoaa** [comment]
이러면 키/몸무게로 사이즈 재는게 별 의미가 없을 수 있는데..

**Comment by 10001if** [comment]
그러게요..

**Comment by 10001if** [comment]
Body Labs 사이즈 비교하면 아래와 같습니다.

![2015-07-13 2 33 31](https://cloud.githubusercontent.com/assets/4696328/8643239/32a8cdb2-296c-11e5-8212-5e42f6f4dffc.png)

                                                     남                                            여
가슴둘레                   ABOVE CHEST GIRTH                     BUST GIRTH
윗배둘레
허리둘레                        HIGH HIP GIRTH                      HIGH HIP GIRTH
팔길이                          SIDE ARM LENGTH                SIDE ARM LENGTH
무릎길이               OUTSEAM - KNEE HEIGHT       OUTSEAM - KNEE HEIGHT
다리길이                           OUTSEAM                                  OUTSEAM
허벅지둘레                     THIGH GIRTH                             THIGH GIRTH
엉덩이둘레                   LOW HIP GIRTH                         LOW HIP GIRTH
배꼽둘레                        WAIST GIRTH                             WAIST GIRTH
-------------
어깨둘레 : ACROSS BACK SHOULDER WIDTH
목둘레 : MID NECK GIRTH
윗팔둘레 : BICEP GIRTH
손목둘레 : WRIST GIRTH
발목둘레 : ANKLE GIRTH
종아리둘레 : CALF GIRTH
상의총장 : BACK NECK TO WAIST
팔길이 : SHOULDER LENGTH + SIDE ARM LENGTH 할지 고민 중 (FULL SLEEVE LENGTH 값과의 차이는?)

**Comment by 10001if** [comment]
표로 깔끔하게 보여드리고 싶었는데, 표 만드는 법을 몰라서 우선 만든 표를 이미지로 옮겼습니다. 복붙하시기 수월하게 아래에 텍스트도 넣었습니다. Body Labs 사이즈를 비교해보니 우선 Body Labs에서는 윗배둘레가 없습니다. 배꼽둘레로 추정되는 사이즈가 있는데요. 윗배둘레는 아마 저희만 쓰는 사이즈가 아닐까? 하는 생각이 들었습니다. 배꼽둘레로 변경하여도 대여에 문제가 생기지는 않을 것으로 생각하고 있습니다. (개인적으로는) 그리고 어때둘레로 시작되는 하단 사이즈는 향후에 필요할 것으로 예상되는 사이즈들을 입력한 것입니다. 향후에는 오프라인 대여자의 사이즈는 좀 더 구체적으로 측정 할 수 있도록 하려고 합니다. 신체 사이즈 측정 방법과 관련하여 스트라**에서 어떻게 사이즈를 재는지 확인해 보기로 하였습니다.

**Comment by aanoaa** [comment]
https://help.github.com/articles/github-flavored-markdown/#tables

참고하시면 됩니다.

이런식으로 하시면 됩니다.

    First Header  | Second Header
    ------------- | -------------
    Content Cell  | Content Cell
    Content Cell  | Content Cell

또는

    | Name | Description          |
    | ------------- | ----------- |
    | Help      | Display the help window.|
    | Close     | Closes a window     |

이렇게..

**Comment by 10001if** [comment]
| First Header  | Second Header |
| ------------- | ------------- |
| Content Cell  | Content Cell  |
| Content Cell  | Content Cell  |

**Comment by 10001if** [comment]
@aanoaa 감사합니다. :)

**Comment by keedi** [comment]
#317 이슈가 마무리 되면 같이 이슈를 닫겠습니다.

**Comment by keedi** [comment]
최종 결과 화면은 다음과 같습니다.

![screenshot-monster silex kr 10301 2015-08-03 13-50-27](https://cloud.githubusercontent.com/assets/138451/9031390/40481568-39ed-11e5-8350-8c5418e9caac.png)

**Comment by keedi** [comment]
이슈 닫습니다.
