### ISSUE TITLE
사용자 정보 화면에서 예약 방문 일시를 확인하고 해당 시간표 위치로 바로 이동하는 링크 추가

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#510]
가령, 대시보드 화면에 결제대기로 이름이 떠있는 분이 있을 때
이 사람을 대시보드 화면에서 지우려면, 방문일자의 시간표를 확인하여 시간표 화면으로 들어가 상태를 변경해야 합니다.
그렇지만 현재는 사용자 검색을 통해 알 수 있는 정보로는 이 분이 언제 몇시에 방문 예약을 했는지 확인하는 것이 어렵습니다. 때문에 다음과 같은 기능을 추가 요청드립니다.  
![2015-07-04 10 52 25](https://cloud.githubusercontent.com/assets/4696328/8506082/9c4a623e-223d-11e5-888a-05938da73ee5.png)

**Comment by aanoaa** [comment]
/timetable/yyyy-mm-dd#timetable-hhmm

위와 같은 주소로 보내주면 되겠습니다.

**Comment by keedi** [comment]
확인 완료했으며 실 서버에 배포 진행하겠습니다.

**Comment by keedi** [comment]
배포 완료했습니다.

**Comment by keedi** [comment]
이슈 닫습니다. :-)
