### ISSUE TITLE
SMS 인증 관련 문자 매크로 추가

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#512]
* SMS 인증발송

"열린옷장입니다. 전화번호 확인을 위해 SMS 확인 문자를 발송하였습니다. 인증번호는 OOOO입니다. 발송된 인증번호를 담당자에게 보여주시기 바랍니다." 

현장에서 직원예약기능을 통해 예약하는 사람들에게 예약 확인을 위해 발송하는 문자입니다. 입력 추가 요청드립니다.

**Comment by keedi** [comment]
현재 업무시간 중이기 때문에 배포 대기 상태입니다. 저녁 6시가 되면 배포 진행한 후 이슈 닫겠습니다. :)

**Comment by keedi** [comment]
배포 완료했습니다. 이슈 닫습니다.

**Comment by 10001if** [comment]
확인완료하였습니다.
