### ISSUE TITLE
팔길이 수선을 위해 의류의 베스트핏 누적 정보 생성

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#515]
의류의 팔길이 수선을 위해 정보를 요청드립니다.

의류는 성별로 특정되지는 않았으나 대여자의 성별은 구분이 되었으므로 구분이 가능할 것이라 생각합니다.
2015년 1월 부터 현재까지 베스트핏 의류에서 다음과 같은 정보를 요청드립니다.

<여성의류>
1. 의류코드 2. 의류의 팔 길이 3. 의류를 입은 사람의 팔 길이 4. 의류를 입은 사람의 키 5. 의류를 입은 사람의 몸무게
(다만, 가능하다면.. 의류코드별로 여러명이 존재할 경우, 개별값 하단에 평균값을 따로 알고 싶습니다.)

<남성의류>
1. 의류코드 2. 의류의 팔 길이 3. 의류를 입은 사람의 팔 길이 4. 의류를 입은 사람의 키 5. 의류를 입은 사람의 몸무게
(다만, 가능하다면.. 의류코드별로 여러명이 존재할 경우, 개별값 하단에 평균값을 따로 알고 싶습니다.)

**Comment by yongbin** [comment]
@10001if  대표님께 확인결과 이 이슈는 간단하게 DB에 질의한 결과파일만 전달드리면 되는 이슈라고 합니다.

**Comment by yongbin** [comment]
요구사항을 조합해서 다음과 같은 쿼리를 작성했습니다.

```SQL
SELECT
    e.`code`                AS 'cloth_code'
    ,e.`arm`                AS 'cloth_arm'
    ,a.`arm`                AS 'order_arm'
    ,e.`arm` - a.`arm`       AS 'diff'
    ,d.height               AS 'order_height'
    ,d.`weight`             AS 'order_weight'
    ,d.`gender`             AS 'order_gender'

FROM `order` AS a
    LEFT  JOIN `order_detail` AS b ON a.`id`           = b.`order_id`
    INNER JOIN `user`         AS c ON a.`user_id`      = c.`id`
    INNER JOIN `user_info`    AS d ON c.`id`           = d.`user_id`
    INNER JOIN `clothes`      AS e ON b.`clothes_code` = e.`code`

WHERE a.`bestfit` = 1
    AND e.`category` = 'jacket';
```

**Comment by yongbin** [comment]
생성한 자료를 @10001if  님께 피드백 받았고, 메일을 통해 전달드렸습니다. 이슈 닫겠습니다.
