### ISSUE TITLE
SMS 계좌이체 및 온라인 입금 안내 문자 매크로 변경 요청

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#517]
열린옷장의 법인격 변경에 따라 기존 계좌번호의 변동이 발생하였습니다.

따라서 SMS 발송 항목 중

* 계좌이체
<현재> 열린옷장에 결제할 금액은 X만Y천원 입니다. 국민은행 205701-04-269524
-> <변경요청> 열린옷장에 결제할 금액은 X만Y천원 입니다. 국민은행 205737-04-003013

* 온라인 입금 안내 항목의 내용을 수정요청드립니다.
<현재> [열린옷장] 대여 금액 00000원, 1시까지 입금해주세요. 국민은행 205701-04-269524
-> <변경요청> [열린옷장] 대여 금액 00000원, 1시까지 입금해주세요. 국민은행 205737-04-003013

문자 변경은 가능하면, 차 주 수요일에 작업을 부탁드립니다. 
중간에 변동되면 혼선을 빚을 것 같아. 차 주 목요일 부터 변경된 계좌를 사용하려고 합니다.

**Comment by keedi** [comment]
7월 22일 수요일 부터 적용되어야 합니다.

**Comment by keedi** [comment]
열린옷장의 공식 계좌 번호를 가장 최신 정보로 변경합니다.

배포 이후 `grunt` 명령을 수행해야 합니다.

**Comment by keedi** [comment]
배포 완료 했습니다. 이슈 닫습니다. :-)

**Comment by 10001if** [comment]
확인 완료 하였습니다.
