### ISSUE TITLE
방문 예약시 이메일 입력 양식의 플레이스 홀더 수정 

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#518]
이메일 입력란에 배경으로 보이는 글씨문구 수정 
현재 : info@theopencloset.net -> 변경 : 이메일을 입력해주세요

**Comment by aanoaa** [comment]
현재 placeholder 는 `이메일 (예: info@theopencloset.net)` 입니다.

**Comment by keedi** [comment]
#526 에서 이메일과 주소 두 가지의 플레이스 홀더를 수정했습니다.

**Comment by keedi** [comment]
배포 완료 했습니다. 이슈 닫습니다. :-)

**Comment by 10001if** [comment]
확인완료하였습니다.
