### ISSUE TITLE
방문 예약시 주소 입력 양식의 플레이스 홀더 수정

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#519]
주소 입력란에 배경으로 보이는 글씨문구 수정
현재 : 동과 번지수 혹은 동과 건물이름 -> 변경 : 동과 번지수 혹은 아파트 이름

**Comment by keedi** [comment]
#526 에서 이메일과 주소 두 가지의 플레이스 홀더를 수정했습니다.

**Comment by keedi** [comment]
배포 완료 했습니다. 이슈 닫습니다. :-)

**Comment by 10001if** [comment]
확인완료하였습니다.
