### ISSUE TITLE
방문 예약시 키와 몸무게를 입력받지 않음

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#520]
키 / 몸무게 입력란 제거 
현재 : 입력란 존재 -> 입력란 제거 (방문 시에는 키/몸무게를 직접 측정하고 있고 온라인시에는 구글독스로 받고 있습니다.)

**Comment by keedi** [comment]
진행합니다.

**Comment by keedi** [comment]
수정 완료 및 배포 완료했습니다.

이슈 닫습니다. :)
