### ISSUE TITLE
방문 예약시 상세 대여 목적과 두번째 선호 색상을 필수가 아닌 선택 사항으로 변경함

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#521]
상세대여목적, 두번째 선호 색상 입력란은 필수 입력이 아니라 선택입력으로 변경요청
현재 : 상세대여목적, 두번째 색상 입력해야만 예약가능 -> 변경 : 입력하지 않아도 예약이 되도록 변경

**Comment by keedi** [comment]
진행합니다.

**Comment by keedi** [comment]
수정 및 실서버 배포 완료했습니다.

이슈 닫습니다.
