### ISSUE TITLE
방문 예약시 주소 입력 및 검색 방법을 변경

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#523]
주소를 입력하는 창에서 입력을 잘 하지 못하는 분들이 많다는 이야기가 많은데요.
그래서, 입력 폼의 변경을 요청드립니다.

현재는 화양동 48-3 을 입력하거나 화양동 웅진빌딩을 입력하는 방식으로 검색이 가능한데요.
이 방식이 기존 사용자들에게는 익숙하지 않은 탓인지, 자꾸만 동으로 입력을 하여 수 많은 번지수 속에서 본인의 주소를 찾지 못하는 문제가 발생하고 있습니다. 

아마도 대부분의 주소 검색 시스템에서는 "화양동"만 입력하면 화양동 1~10, 화양동 11~20, 화양동 21~30 이런식으로 포괄적인 주소를 입력하고 그 뒤에 세부 주소를 입력하는 방식으로 되어 있는데, 우리의 주소 시스템은 처음에 바로 세부 주소를 찾도록 하고 있어 사용자들이 어색해하는 것이라고 생각되어집니다.

@aanoaa 이에 대한 의견을 전달해주시면 감사하겠습니다. :)

**Comment by aanoaa** [comment]
입력예시를 좀 더 넣어주거나 옆에 참고할만한 링크를 달아주는 건
어떨까요? help 메세지를 보여주는거죠.

주소검색 시스템을 바꾸는 건 좀 큰일이기도 하고, 더 불편하잖아요.
쉽게 쓰려고 해논거니까 쉽게 쓸 수 있도록 안내해주면 좋지 않을까합니다.

gif 파일 만들어서 보여준다거나..

**Comment by aanoaa** [comment]
주소에 대한 예시를 좀 더 눈에 띄게 바꾸고,
검색결과 제일 위에 자세한 검색방법에 대한 안내(**시,구,동을 강조해서**)를 표시하도록 바꿉니다.

**Comment by aanoaa** [comment]
사람들이 `화양동` 처럼 동만 입력하는 경우가 많다고 합니다.
그렇게 되면 검색 결과가 많아져서 선택하기 어렵고,
`화양동 48-3` 으로 입력해야 합니다. 그렇게 할 수 있도록 도와주어야 합니다.

**Comment by aanoaa** [comment]
나중에 필요하면 논의하도록 합니다.
