### ISSUE TITLE
통계-상태에서 5월 29일 기준 오후 10시 예약 건을 연산하지 않아야 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#524]
오후 10시는 온라인 이용자인데. 온라인의 경우에는 주문서에 머무는 시간이 상대적으로 긴 경우가 많습니다. 입금 전 결제대기 상태가 특히 긴데요. 정보가 누적되어 체크되어 불명확한 상태 정보를 확인하게 되는 것 같습니다. 오후 10시 주문서는 데이터 생성시 제거 될 수 있도록 빼주시면 좋겠습니다.  5/29일 부터 오후 10시 예약분이 온라인 예약자입니다.

**Comment by yongbin** [comment]
이 이슈는 '통계'-'상태' 메뉴에서 온라인 대여주문서가 포함될 경우 통계값이
부정확해 지는 문제를 해결하기 위한 이슈입니다. 한만일대표님께서 말씀해주신 '5월
29일 기준 오후 10시' 기준은 기존 7시 주문서를 '온라인 주문서'로 사용하던 형식이
야간대여가 사용되어서 더이상 사용할 수 없게되어 10시로 조정되어서 변경된
것입니다. 따라서 주문서의 접수 시점에 따라 온라인 대여인지 여부를 판단하는
기준이 달라지는 문제도 있고 10시기준 역시 완전하지 않기때문에 다음과 같이
진행했으면 합니다.

1. OpenCloset::Schema에 온라인 주문여부를 표시하는 컬럼을 추가
2. 2015년 5월 29일을 기준으로 이전 주문서는 7시, 이후 주문서는 10시 주문서를
   온라인 주문여부 컬럼에 업데이트
3. 통계 - 상태 메뉴상에서는 대상이 되는 주문서를 '오프라인 주문서'로 한정

먼저 현재 내부 구조상 OpenCloset::Schema에 온라인 주문여부를 표시하는 컬럼을
추가하는것이 적절한지에 대해 제가 정확하게 잘지 못하기 때문에 @keedi 님께 의견을
구합니다. (검색해본결과 비슷해 보이는 논의가 #110, #109에 있습니다)

추가하지 않는쪽으로 결정된다면 단순하게 '통계'-'상태' 에서 기간별로 예외처리를
하도록 하겠습니다.

**Comment by aanoaa** [comment]
이건 다른건데 5/29 일에 관한 이슈가 있었습니다.
https://github.com/opencloset/opencloset/issues/317#issuecomment-115128439

**Comment by yongbin** [comment]
@aanoaa 아 저 이슈와도 관련이 있었네요 알려주셔서 감사합니다. 만약 변경이 생기게 된다면 #317 에도 반영되어야 합니다.

**Comment by keedi** [comment]
@yongbin 말씀하신 것처럼 online 여부를 기록하는 컬럼 필요합니다. 진행해주세요. 단, 가지에서 꼭 진행 후 모든 확인 후 머지 및 배포가 이루어져야 합니다. 스키마기 때문에 확인없이 머지되면 장애날 수도 있으니까요.

**Comment by keedi** [comment]
@yongbin 다만 해당 건은 별도 이슈로 만들어서 진행해주시고 현재 건은 요청 사항 그대로 처리했으면 합니다. 즉 현재 건은 웹응용 쪽의 코드 수정으로 마무리 짓고 별도 이슈에서는 스키마를 변경하는 방식으로 진행하면 일처리가 빠를 것으로 사료됩니다.

**Comment by yongbin** [comment]
OpenCloset::Schema에 별도 이슈등록을 완료했습니다. 임시적으로 웹쪽에 요청사항을 반영하는 작업은 별도로 진행하며 지금 시작합니다.

**Comment by yongbin** [comment]
@keedi PR을 작성해서 보냈습니다. #536

**Comment by keedi** [comment]
머지 완료했습니다. 오늘 중 배포 예정입니다.

**Comment by keedi** [comment]
배포 완료했습니다. 이슈 닫습니다.

**Comment by 10001if** [comment]
@keedi 이건 제가 확인하기가 조금 어려울 것 같은데, 혹시 어떻게 확인할 수 있는지 방법을 알려주시면 확인해보고 라벨을 지우도록 하겠습니다. :)

**Comment by 10001if** [comment]
keedi님께 문의드려보니 현재로서는 제가 확인할 수 있는 방법이 없기 때문에 확인하지 못했지만, 잘 되었을거라 생각하고, 확인완료 라벨을 지우도록 하겠습니다.

**Comment by yongbin** [comment]
@10001if 확인하실수 있는 방법이 있습니다. `통계` - `상태` 메뉴상에서 특정일을 선택하셨을때 까장 마지막에 보이는 주문서의 시간을 확인해보시면 의도한대로 적용되었는지 여부를 확인할 수 있습니다. 즉 `통계` - `상태` 메뉴에서 5월 29일을 기점으로 이전에는 7시의 주문들이 존재하지 않는지 여부와 이후에는 10시의 주문서가 존재하지 않는지 여부를 확인하시면 됩니다.

**Comment by 10001if** [comment]
@yongbin 말씀해 주신 방법으로 찾아보니 오늘의 경우 10시의 주문서가 보이지 않네요. 잘 적용된 것 같습니다. 감사합니다~
