### ISSUE TITLE
자원 봉사 메뉴 추가

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#527]
매일같이 자원봉사자들이 방문하고 있기 때문에 이를 더 효율적으로
관리하고 싶습니다.

현재는 google form 을 이용해서 신청서를 받고, 연락후에 naver band
서비스를 활용해서 봉사시간을 정하고 있습니다.

이를 하나의 채널에서 관리 및 활용하고 싶습니다.
이를 위해서는,

- 신청서 관리
- 봉사자 관리
- google? calendar 사용

등이 있겠습니다.

**Comment by aanoaa** [comment]
### 자원봉사 workflow ###

- 자원봉사 신청서 작성
  - 희망일/시간 을 입력
  - 봉사자와 담당자는 달력을 공유
  - 달력에는 이름과 생년을 표시해주어야 함
- 담당자가 신청확인 후 승인
  - 신청자의 할일목록을 선택가능하도록 함
  - 신청자에게 문자전송
- 봉사자가 방문
- 담당자의 출석확인
  - 1365 홈페이지(관리자모드)에 들어가서 확인문서 작성
- 방명록작성해달라고 문자전송
- 방명록을 작성
- 직원이 봉사자에 대한 코멘트를 남길 수 있음(staff only)

관리자 계정을 알고 1365 홈페이지에서 신청자에 대한 내용을 긁어올 수
있다면, 위 workflow 는 변경될 수 있습니다.

**Comment by 10001if** [comment]
봉사자가 방문 
-> 방문한 봉사자를 옷장지기가 체크
봉사가 끝나면 봉사자는 그냥 집으로 감

방문한 봉사자에게만 당일 저녁 7시에 문자가 발송
문자는 방명록 + 그 날 봉사한 시간 묻는 항목 추가 (1365 봉사시간 인정 원하는지 물음)
그러면 방영록도 모두 쓰고 봉사시간 체크도 종이로 하지 않아도 될 것 같습니다.
종이로 하다보면 잊고 그냥 지나가는 경우가 종종 발생합니다.

**Comment by aanoaa** [comment]
> 관리자 계정을 알고 1365 홈페이지에서 신청자에 대한 내용을 긁어올 수
있다면, 위 workflow 는 변경될 수 있습니다.

아이디와 비밀번호를 알고 있어도 보안어쩌고 프로그램을 설치하지 않으면 로그인할 수 없습니다.
API 같은게 혹시 있는가 찾아보고 있지만 없는 것 같습니다.

**Comment by aanoaa** [comment]
- [신청서](https://docs.google.com/forms/d/10YxjEoWoor8FazdqDGWMiLp4OQ_eA0QYnVkhckA6GVQ/viewform?edit_requested=true)
- [달력](https://www.google.com/calendar/embed?src=volunteer%40theopencloset.net&ctz=Asia/Seoul)

**Comment by aanoaa** [comment]
- calendar 보여줘야함

- 몇시에 신청되었는지 보여준다
- 수정하기위한 주소를 알려준다
- 문자로 위치랑 시간을 알려준다
- edit 할 수 있도록 한다.(수정하시려면 버튼 눌러달라라고 적는다)

- 관리자가 활동시간을 변경할 수 있어야 한다
- 목록은 날짜별로 
- 재방문여부
- 활동 승인? approve 하면 문자가 간다
- 활동 종료 (지정된 시간에 오후 7시 방명록을 적게끔한다 + 봉사시간 + 1365 필요한지)


- 신청/승인/완료 가 구분되어서 보였으면 좋겠다
- google calendar 를 보여준다

**Comment by aanoaa** [comment]
https://developers.google.com/google-apps/calendar/v3/reference/events/insert

구글 캘린더에 이벤트를 등록하기 위한 문서입니다.

**Comment by aanoaa** [comment]
https://developers.google.com/youtube/v3/guides/auth/server-side-web-apps?hl=ko

google api 를 사용하기위한 인증에 관한 문서입니다.

**Comment by aanoaa** [comment]
- https://console.developers.google.com/ 에서 새로운 application 을
  등록한다
- API key 를 생성한다(oauth 대신에)
  - end-user 의 인증정보를 활용하지 않기 때문에 더욱 단순한 요청으로
    처리합니다.
  - 이때에 api 를 호출할 서버의 ip address 를 등록해야 하는데,
    `visit.theopencloset.net` 이랑 제 개발환경의 ip 를 등록하였습니다.
- api 문서를 보고 이를 활용한다. 이때 `api key` 는 `key` 라는
  parameter 이름으로 넣는다.
  - `https://www.googleapis.com/~~~?key=API_KEY`

**Comment by aanoaa** [comment]
사용하려는 api key 는 volunteer@theopencloset.net 계정으로 만들었습니다.
google developer console 에서 API 및 인증 - 사용자 인증 정보 에서 자세한 정보를 확인할 수 있습니다.

**Comment by aanoaa** [comment]
테스트해봤는데 calendar 의 event 를 만들때 api key 를 사용할 수 없습니다.
로그인 하라고 나옵니다.

    {
     "error": {
      "errors": [
       {
        "domain": "global",
        "reason": "required",
        "message": "Login Required",
        "locationType": "header",
        "location": "Authorization"
       }
      ],
      "code": 401,
      "message": "Login Required"
     }
    }

왜? 인지는 모르겠습니다만 api key 를 이용할 수 없으므로 oauth2 를
활용해야 합니다.

신청서가 승인되면 달력에 이벤트가 추가되어야 하는 시나리오
입니다. 신청자(end-user)가 구글에 인증하고 이벤트를 추가하는게 아니라
어떤 신청자이든 상관없이 서버에서 알아서 달력에 추가해야 합니다.

이에 알맞은 인증방법이
[Service Accounts](https://developers.google.com/identity/protocols/OAuth2ServiceAccount)
입니다.

**Comment by aanoaa** [comment]
엄청 삽질했는데, json 파일에서 private_key_string 을 복사해서 token 을
얻어오려고 하면 안되고, json 파일을 decode 한 다음에 사용하니 됩니다.
`""` 로 감싸져있는 문자열과 decode 된 문자열이 다른가봅니다.

**Comment by 10001if** [comment]
고생해주셔서 감사합니다~!

**Comment by aanoaa** [comment]
token 을 넣어서 캘린더에 이벤트를 추가하고자 하는데,

    {
     "error": {
      "errors": [
       {
        "domain": "global",
        "reason": "forbidden",
        "message": "Forbidden"
       }
      ],
      "code": 403,
      "message": "Forbidden"
     }
    }

다른 에러가 발생합니다.
알아보기 어렵습니다.

**Comment by aanoaa** [comment]
캘린더 설정에 보면

> 캘린더 ID: volunteer@theopencloset.net

라고 되어 있지만 혹시나 하는 마음에 calendar list 를 확인해보았습니다.

https://developers.google.com/google-apps/calendar/v3/reference/calendarList/list

    GET https://www.googleapis.com/calendar/v3/users/me/calendarList
    {
     "kind": "calendar#calendarList",
     "etag": "\"1438080296983000\"",
     "nextSyncToken": "00001438080296983000",
     "items": []
    }

아무것도 없다는 거 같네요.
뭔지 모르겠습니다.

**Comment by aanoaa** [comment]
http://stackoverflow.com/questions/24062762/google-calendar-api-calendarlist-list-return-empty-element

아 선조들이여..

**Comment by aanoaa** [comment]
공유설정에서 api 를 사용하기 위해 만들어진 email 주소를 등록해주어야 했습니다.

**Comment by aanoaa** [comment]
일정등록에 성공하였습니다.
api key 로도 될것 같아서 해봤는데 안되네요.
캘린더 공유설정과 관련이 있는 것 같습니다.

**Comment by aanoaa** [comment]
승인되었을때 신청자에게 문자메세지를 보내야 하는데 어떻게 보낼까요?

이름, 신청일, 관심있는 활동, 활동일 등을 알고 있습니다.

- 김개똥
- 7/30
- 다림질 봉사, 정리 봉사..
- 2015-07-30 10:00:00 ~ 2015-07-27 18:00:00

예를들면,

    홍형석님 7/30일 봉사활동에 참가해주세요. 어디로 오시면 됩니다. 어쩌고 저쩌고

이걸 좀 정해주세요.

**Comment by aanoaa** [comment]
사용자가 신청서 수정도 가능해야 하기 때문에 이메일 혹은 SMS 로도 알려주는 것이 좋지 않을까 합니다.
신청서를 수정하기 위한 URL 에 authcode 가 포함되어 있기 때문에 링크 없이는 접근할 수가 없거든요.

**Comment by 10001if** [comment]
* 자원봉사 신청접수 완료시
000님이 00월 00일 00~00시에 신청하신 자원봉사신청이 정상적으로 접수되었습니다.
현재 열린옷장 담당자가 접수된 봉사신청 내역을 확인하고 있습니다. (최종승인까지 소요기간 1일 이내) 
신청하신 봉사시간 및 봉사활동내역에 대해 변경사항이 없는 경우 000님이 신청해 주신 자원봉사에 대한 최종승인여부가 SMS로 발송될 예정입니다. 
봉사 승인에 대한 SMS 또는 전화연락이 없는 경우 070-4325-7521 혹은 카카오톡 옐로아이디를 통해 문의해주시기 바랍니다. 감사합니다.

**Comment by 10001if** [comment]
* 자원봉사 신청승인시 *
-
축하합니다! 000님이 00월 00일 00~00시에 신청하신 봉사활동이 최종 승인 완료되었습니다.
000님은 봉사당일 열린옷장에서 000(봉사내용)를 통해 힘을 보태주시게 될 것입니다. (당일 상황에 따라 변동이 이루어질 수 있습니다.) 열린옷장은 ~ 위치해 있습니다.
추가로 궁금한 점이 있는 경우에는 070-4325-7521 혹은 카카오톡 옐로아이디를 통해 문의해주시기 바랍니다. 봉사당일 밝은 얼굴로 인사드리겠습니다. 감사합니다. 

작성중입니다.. 이따 다시 수정하도록 하겠습니다.

**Comment by aanoaa** [comment]
다시한번 피드백이 필요한 시점입니다.

- [ ] 1365 필요한지 여부를 어디서 어떻게 물어볼 것인가?
- [ ] 신청자가 수정할 수 있게 해달라고 했는데 sms 에 URL을 남길 것인가?
- [ ] 방명록 다 쓰고 나서 뭘 보여줘야 하는가?
- [ ] 신청완료 후에 SMS 는 보내는데 웹페이지에선 뭐라고 보여줘야 하는가?

**Comment by 10001if** [comment]
1365 필요한지 여부를 어디서 어떻게 물어볼 것인가?
-> 저녁 7시에 발송되는 SMS 혹은 이메일에 들어갈 URL을 클릭하면 방명록 + 활동한 봉사시간 + 1365 필요여부를 묻는질문이 들어가야 합니다. 방명록은 폼이 있으니 그대로 해주시면 될 것 같구요. 방명록 폼 위에 1365 승인 내용과 봉사시간 입력란을 만들어 놓았습니다.

 신청자가 수정할 수 있게 해달라고 했는데 sms 에 URL을 남길 것인가?
-> 시간을 수정해야 할 필요가 있을텐데 현재로선 로그인이 어려우니 url들어가서 수정하는 방법밖에는 없는거죠? 그럼 남겨주세요~ ^^

 방명록 다 쓰고 나서 뭘 보여줘야 하는가?
-> 000님 응답에 답해주셔서 감사합니다. 1365 봉사시간 승인을 원하신 경우 담당자의 확인을 거쳐 1365 봉사시간 승인절차가 최종완료될 예정입니다. (소요시간 1일 이내) 다음 날 저녁에도 승인이 완료되지 않는 경우에는 전화나 카카오톡 옐로아이디를 통해 문의주시기 바랍니다. 오늘도 열린옷장은 000 봉사자님 도움으로 한뼘 더 성장하였습니다. 앞으로 또 인사드릴 수 있으면 좋겠습니다. 봉사활동에 참여해주셔서 진심으로 감사드립니다.

 신청완료 후에 SMS 는 보내는데 웹페이지에선 뭐라고 보여줘야 하는가? (sms와 동일하게 보여지면 될 것 같아요 ^^)
-> 안녕하세요. 000님이 00월 00일 00~00시에 신청하신 자원봉사신청이 정상적으로 접수되었습니다.
현재 열린옷장 담당자가 접수된 봉사신청 내역을 확인하고 있습니다. (최종승인까지 소요기간 1일 이내) 
신청하신 봉사시간 및 봉사활동내역에 대해 변경사항이 없는 경우 000님이 신청해 주신 자원봉사에 대한 최종승인여부가 SMS로 발송될 예정입니다. 
봉사 승인에 대한 SMS 또는 전화연락이 없는 경우 070-4325-7521 혹은 카카오톡 옐로아이디를 통해 문의해주시기 바랍니다. 감사합니다.

**Comment by 10001if** [comment]
이 분이 봉사활동을 실제로 한 시간을 입력하면 별도의 승인절차없이 봉사시간이 입력되도록 하였으면 좋겠습니다. ^^

**Comment by aanoaa** [comment]
1365 봉사시간 승인은 어디에서 어떻게 하고 있나요?
1365 홈페이지에서라면 답없습니다.

**Comment by 10001if** [comment]
@aanoaa 1365 승인은 별도의 프로그램에서 이루어지고 있습니다. 최종승인은 어쩔 수 없이 다시 한번 해야할 것 같습니다. 만들어주시는 봉사프로그램에서는 1365 승인이 필요한 사람이 몇 시간 봉사했는지만 확인 할 수 있으면 될 것 같습니다~ ^^

**Comment by aanoaa** [comment]
https://github.com/opencloset/volunteer

새로운 저장소를 만들었습니다.
모니터 처럼 별도의 프로그램으로 분리해서 작업합니다.
staff 는 기존처럼 재고관리 내에서 관리할 수 있도록 합니다.

**Comment by aanoaa** [comment]
1365 가 필요한 사용자는 먼저 신청해야 하는데 이에 대한 안내가 신청서에 필요합니다.

**Comment by aanoaa** [comment]
봉사활동 시간을 고정하는게 좋겠다고 합니다.
봉사활동은 3시간 이상해야 하고, 점시시간을 피해서 입력을 유도하기
위함입니다.

1. 10 ~ 13
2. 14 ~ 18
3. 10 ~ 18
4. 10 ~ 19
5. 14 ~ 19
6. 14 ~ 17

**Comment by aanoaa** [comment]
@10001if `volunteer.theopencloset.net` 를 `visit.theopencloset.net` 과 같은 주소로 맵핑해주셔야 합니다.
서비스 받고 있는 업체가 있다고 들었습니다.

**Comment by 10001if** [comment]
봉사시간 고정하는게 훨씬 좋겠네요. 감사합니다. 그리고 서비스 관련 정보에 대해서는 이따 연락주시면 찾아뵙고 말씀드릴게요. ^^

**Comment by aanoaa** [comment]
`완료`를 눌렀을때 방명록 안내문자가 전송되는게 아니라,
매일 오후 7:00 에 일괄로 완료된 자원봉사자들에게 방명록 안내문자가 발송되어야 합니다.

라벨이 `완료` 대신에 `방문` 으로 바뀌어야 합니다.

**Comment by aanoaa** [comment]
@10001if 

- 방명록 다 적은 후에 뭘 보여줄지,
- 방명록 안내 문자

를 알려주세요.

**Comment by aanoaa** [comment]
희망활동이 너무길어서 알아보기 어렵습니다.
@10001if 님이 바꿔주신답니다.

**Comment by aanoaa** [comment]
1365 신청자목록이 필요합니다.

**Comment by aanoaa** [comment]
> 1365 가 필요한 사용자는 먼저 신청해야 하는데 이에 대한 안내가 신청서에 필요합니다.

@10001if 이것도 해주셔야 합니다.(신청서 상단에 문구?)

**Comment by aanoaa** [comment]
> volunteer.theopencloset.net 를 visit.theopencloset.net 과 같은 주소로 맵핑해주셔야 합니다.
> 서비스 받고 있는 업체가 있다고 들었습니다.

DNSever 를 사용중입니다. 등록하였습니다.

**Comment by 10001if** [comment]
* 방명록 다 적은 후에 *
- 000님 응답에 답해주셔서 감사합니다. 1365 봉사시간 승인을 원하신 경우 담당자의 확인을 거쳐 1365 봉사시간 승인절차가 최종완료될 예정입니다. (소요시간 1일 이내) 다음 날 저녁에도 승인이 완료되지 않는 경우에는 전화나 카카오톡 옐로아이디를 통해 문의주시기 바랍니다. 오늘도 열린옷장은 000 봉사자님 도움으로 한뼘 더 성장하였습니다. 앞으로 또 인사드릴 수 있으면 좋겠습니다. 봉사활동에 참여해주셔서 진심으로 감사드립니다.

**Comment by 10001if** [comment]
* 방명록 안내문자 *
안녕하세요. 000님 아래 주소에서 오늘 봉사해주신 자원봉사시간과 "1365 봉사시간 승인" 필요유무 등을 꼭 적어주세요. 열린옷장과 함께해주셔서 진심으로 감사드립니다.

**Comment by 10001if** [comment]
@aanoaa 희망활동은 조금 더 고민해서 말씀드리도록 하겠습니다. 우선 이대로 진행하였으면 좋겠습니다. 다만, 캘린더에는 희망활동이 표시되지 않았으면 좋겠습니다.

**Comment by 10001if** [comment]
* 봉사 신청서 상단에 들어갈 1365 안내 문구 *
- 자원봉사 시간 인정을 받아야 하는 봉사자님은 1365 사이트 (주소)에서 열린옷장에 봉사신청을 하신 후, 본 신청서를 작성해 주시기 바랍니다. 봉사시간 인증은 1365 사이트에서 봉사 신청을 하신 분에게만 확인해 드릴 수 있습니다.

**Comment by aanoaa** [comment]
- 방문 상태는 일주일간 표시
- 이름으로 검색
- 나머지 상태는 다 보여준다

**Comment by aanoaa** [comment]
1365 승인이 필요한지 여부를 방명록이 아니라 신청서에 적어야 합니다.

**Comment by aanoaa** [comment]
1365 에서 이미 신청한 사용자인지 확인할 수 있어야 합니다.
해서,

1365 승인이 필요하면서 아직 1365에서 신청하지 않은 사용에게만
문자메세지를 보내야 합니다.

@10001if 해당 문자메세지 내용을 입력해주세요.

**Comment by 10001if** [comment]
<변경> 방명록 안내문자 *
안녕하세요. 000님 열린옷장과 함께해주셔서 진심으로 감사드립니다. 아래 주소에서 오늘 참여해주셨던 봉사활동 소감을 작성해주세요. 작성해주신 내용은 열린옷장이 더 많은 분들과 즐거운 나눔을 공유하는데 중요한 자원이 될 것입니다. 감사합니다.

**Comment by 10001if** [comment]
* 봉사 신청서 상단에 들어갈 1365 안내 문구 *
자원봉사시간 인증이 필요한 봉사자님은 1365 홈페이지 (주소)에서 열린옷장에 봉사신청을 하신 후, 본 신청서를 작성해 주시기 바랍니다. 봉사시간 인증은 1365 홈페이지에서 신청을 하신 분에게만 승인이 가능합니다. (봉사시간 인증은~ 부터 빨간색 글씨로 부탁드려요.)

**Comment by 10001if** [comment]
* 1365 승인이 필요하고 신청서를 작성하지 않은 사람에게 발송될 문자 * 
- 000 봉사자님 안녕하세요. 자원봉사시간 인증을 받으시려면 1365 홈페이지 (주소)에서 열린옷장에 봉사신청을 해주세요. 봉사시간 인증은 1365 홈페이지에서 신청을 하신 분에게만 승인이 가능합니다. 감사합니다.

**Comment by aanoaa** [comment]
> 000 봉사자님 안녕하세요. 자원봉사시간 인증을 받으시려면 1365 홈페이지 (주소)에서 열린옷장에 봉사신청을 해주세요. 봉사시간 인증은 1365 홈페이지에서 신청을 하신 분에게만 승인이 가능합니다. 감사합니다.

에서 인사는 신청에 관련된 SMS 에서 이미 `안녕하세요 OOO님` 을 하기 때문에 불필요하지 않을까 생각됩니다.

**Comment by 10001if** [comment]
@aanoaa 네~ 불필요하겠네요~ 빼주시면 되겠어요~ 감사합니다~!

**Comment by 10001if** [comment]
* 자원봉사 신청접수 완료시 *
- 안녕하세요. 000님이 00월 00일 00~00시에 신청하신 자원봉사신청이 정상적으로 접수되었습니다.
현재 열린옷장 담당자가 접수된 봉사신청 내역을 확인하고 있습니다. (최종승인까지 소요기간 1일 이내) 
신청하신 봉사시간 및 봉사활동내역에 대해 변경사항이 없는 경우 000님이 신청해 주신 자원봉사에 대한 최종승인여부가 SMS로 발송될 예정입니다. 
봉사 승인에 대한 SMS 또는 전화연락이 없는 경우 070-4325-7521 혹은 카카오톡 옐로아이디를 통해 문의해주시기 바랍니다. 감사합니다.

-> 이 내용은 SMS 로는 발송하지 않고 신청서를 다 작성한 경우 웹 상에서만 보여지면 될 것 같습니다.
현재 자원봉사 신청과정에서 발송하는 SMS가 과잉상태인 듯 합니다..

**Comment by aanoaa** [comment]
1365 관련된 문자 매크로가 필요합니다.
@10001if 님이 적어주실겁니다.

**Comment by aanoaa** [comment]
> 이 내용은 SMS 로는 발송하지 않고 신청서를 다 작성한 경우 웹 상에서만 보여지면 될 것 같습니다.
현재 자원봉사 신청과정에서 발송하는 SMS가 과잉상태인 듯 합니다..

아닙니다 SMS 보내도록 합니다.

**Comment by 10001if** [comment]
* 1365 신청자에게 보내는 SMS 문자 매크로 내용 *

- [열린옷장] 안녕하세요. 1365를 통해 열린옷장 자원봉사를 신청해주셔서 감사합니다. 아래 주소에서 참여하고자 하는 봉사 날짜와 시간 등을 작성해 주시기 바랍니다. 자원봉사는 아래 주소를 통한 신청서 작성 완료 후 정상적으로 접수됩니다. 감사합니다.

**Comment by aanoaa** [comment]
http://www.1365.go.kr/nanum/prtl/web/vols/vol/selectWrkView.do?menuNo=P9130&progrmRegistNo=1715602

**Comment by aanoaa** [comment]
> 그 이외에 열린옷장과 연관된 재능이 있다면 적어주세요

라는 질문이 신청서에 포함되어야 합니다.

**Comment by aanoaa** [comment]
승인이 완료되었을때 SMS 로

> 열린옷장의 소식이나 열린옷장 봉사자분들과 친목을 위한 네이버 밴드가 있습니다.
> 관심있음 가입하셔서 누구나 열린옷장을 즐길 수 있습니다. 
> http://www.band.us/#!/band/53901580

위 메세지를 보내야 합니다.

**Comment by aanoaa** [comment]
배포가 늦어지고 있는데, 아래 두개의 이슈를 해결하면 완료될 것 같습니다.

- [ ] OpenCloset::Schema 를 배포 하고 서버에 반영해야 합니다.
- [ ] 위의 의존성문제를 해결하고 배포해야 합니다.

**Comment by keedi** [comment]
@aanoaa OpenCloset::Schema 배포라는게 무슨 말씀이신지요?

**Comment by aanoaa** [comment]
@keedi cpan.opencloset.net 에 새로운 버전을 업로드해야 하는거요.

어떤 계정을 사용해야 하나요?

**Comment by aanoaa** [comment]
visit 에는 적용하지 않았고, staff 에만 적용했습니다.
신청서를 작성하고 승인하고 하는 일련의 과정을 실무자와 함께 확인해봐야 합니다.

**Comment by 10001if** [comment]
1365 홈페이지에서 신청서를 작성하셨습니까?
자원봉사시간 인증이 필요한 봉사자님은 1365 홈페이지에서 열린옷장에 봉사신청을 하신 후, 본 신청서를 작성해 주시기 바랍니다. 봉사시간 인증은 1365 홈페이지에서 신청을 하신 분에게만 승인이 가능합니다.

이 문구를 아래 멘트로 수정요청드립니다.
-> 1365 홈페이지에서 신청서를 작성하셨습니까?
자원봉사시간 인증이 필요한 봉사자님은 본 신청서를 작성하신 후, 추가적으로 1365 홈페이지에서 열린옷장에 봉사신청을 작성해 주시기 바랍니다. 봉사시간 인증은 1365 홈페이지에서 신청을 하신 분에게만 승인이 가능합니다.

**Comment by 10001if** [comment]
그리고 신청 완료후 나오는 웹 화면

한만일님 열린옷장 자원봉사에 신청해주셔서 감사합니다.
안녕하세요. 한만일님이 8월 26일 10 ~ 13시에 신청하신 자원봉사신청이 정상적으로 접수되었습니다.

현재 열린옷장 담당자가 접수된 봉사신청 내역을 확인하고 있습니다. (최종승인까지 소요기간 1일 이내)

신청하신 봉사시간 및 봉사활동내역에 대해 변경사항이 없는 경우 한만일님이 신청해 주신 자원봉사에 대한 최종승인여부가 SMS로 발송될 예정입니다.

봉사 승인에 대한 SMS 또는 전화연락이 없는 경우 070-4325-7521 혹은 카카오톡 옐로아이디를 통해 문의해주시기 바랍니다. 감사합니다.

을 아래 멘트로 수정 요청드립니다.
->

000님 열린옷장 자원봉사에 신청해주셔서 감사합니다.
안녕하세요. 000님이 0월 0일 00 ~ 00시에 신청하신 자원봉사신청이 정상적으로 접수되었습니다.

현재 열린옷장 담당자가 접수된 봉사신청 내역을 확인하고 있습니다. (최종승인까지 소요기간 1일 이내)

자원봉사시간 인증이 필요한 봉사자님은 추가적으로 1365 홈페이지에서 열린옷장에 봉사신청을 작성해 주시기 바랍니다. 봉사시간 인증은 1365 홈페이지에서 신청을 하신 분에게만 승인이 가능합니다. (이 부분은 빨간색으로 표시 부탁드립니다. ^^) 

신청하신 봉사시간 및 봉사활동내역에 대해 변경사항이 없는 경우 000님이 신청해 주신 자원봉사에 대한 최종승인여부가 SMS로 발송될 예정입니다.

봉사 승인에 대한 SMS 또는 전화연락이 없는 경우 070-4325-7521 혹은 카카오톡 옐로아이디를 통해 문의해주시기 바랍니다. 감사합니다.

**Comment by 10001if** [comment]
제가 테스트를 하고 있는데~ 자원봉사 승인을 눌러도 달력에 표시가 되지 않습니다. 확인 부탁드릴게요. :)

**Comment by 10001if** [comment]
그리고 1365 봉사 승인을 할 때 실수로 두번 누르거나 할 경우가 있을 것 같습니다. 팝업을 통해 다시한번 확인을 묻도록 해주셨으면 좋겠습니다.

**Comment by 10001if** [comment]
항목을 제대로 작성하지 않는 경우에 신청하기를 누르니 이런 화면이 나왔습니다. 대여신청을 할 때처럼 입력하지 않는 경우 신청이 되지 않고, 어떤 항목을 입력하지 않았는지 상단에서 알려주는 기능의 추가를 요청드립니다.
![2015-08-20 4 43 59](https://cloud.githubusercontent.com/assets/4696328/9378924/4e9ee256-4760-11e5-80af-99eae0d1c2ef.png)

**Comment by aanoaa** [comment]
위에 말씀해주신 모든내용 반영하였습니다.

**Comment by 10001if** [comment]
오늘 못가서 죄송합니다. 이번 주내내 정말 정신이 없이 바쁘네요 ㅠ
활동시간 선택에서 10~18시가 8시간 10~19시는 9시간으로 되어 있는데요.
점심시간 1시간은 불포함이므로 10~18시는 7시간 10~19시는 8시간으로 수정 부탁드립니다.

**Comment by 10001if** [comment]
@aanoaa 메세지 사이트 오픈을 위해서 3차 오픈을 정리하고 있는데요. 3차 오픈 마일스톤을 제거하지 않고 그대로 내버려두면 될까요?

**Comment by aanoaa** [comment]
이 이슈는 끝난 것 아닌가요?
완료된 이슈는 닫아주시면 되겠습니다.

**Comment by keedi** [comment]
끝난 이슈로 보입니다. 이슈 닫습니다.
