### ISSUE TITLE
입금문자를 프로그램에서 볼 수 있는지 확인

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#529]
온라인 대여자가 특정 계좌로 입금하면 등록된 번호로 SMS 가 전송됩니다.
이걸 휴대폰이 아닌 컴퓨터에서 보고 싶습니다.

가능할 것 같긴한데 탐구생활을 해봐야 합니다.

**Comment by aanoaa** [comment]
https://ifttt.com/recipes/177775-archive-my-received-sms-to-evernote

**Comment by 10001if** [comment]
확인해 보니 이 부분은 PG사에서 제공을 해준다고 하네요. 굳이 이번 작업에서는 손대지 않으셔도 될 것 같습니다. ^^
