### ISSUE TITLE
기증에서 기증자간 의류 이동이 되지 않음

### ISSUE THREAD

**Issue by keedi** [opencloset/opencloset#531]
재현 방법:

1. 기증 페이지 접속
1. `K05C` 의류 검색
1. 해당 의류 더블 클릭으로 상단 섹션으로 이동시킴
1. `이은종` 이름 검색
1. 해당 의류를 검색한 해당 기증자에게 이전하려고 할 때 이동되지 않음
1. 때때로 상단 섹션에서 더블 클릭했던 `K05C` 의류가 보이지 않을 때 있음

워커 개수와 연관이 있을 수도 있으므로 로컬에서 테스트할 때도 가능하면 한개의 워커가 아닌 여러 워커를 띄워서 테스트를 수행해야 할 것 같습니다.

**Comment by aanoaa** [comment]
#194 와 관련이 있습니다.

**Comment by aanoaa** [comment]
브라우저의 localStroage 를 사용하기 때문에 서버의 worker 와는 상관없습니다.

사용방법에 문제가 있던게 아닐까요?

1. 의류품번으로 검색해서 버킷으로 옮긴다.
2. 기증자를 검색한다.
3. 기증자를 선택하고, 품번을 더블클릭한다.

여기서 기증자로 들어가서 버킷에 있는 품번을 기증자에게 넣어줘야 합니다.
**목록에서 누르는게 아니라요.**
목록에서 누르면 버킷에 담았던 원래 사용자한테 돌아가요.

**Comment by keedi** [comment]
@aanoaa @10001if 님께서 확인 후 직접 말씀해주신다고 합니다.

**Comment by aanoaa** [comment]
사용방법을 다시한번 말씀드렸습니다.
