### ISSUE TITLE
주문서의 신체 치수를 변경

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#534]
주문서내의 신체치수가 잘못입력되는 경우가 있는데(오타), 그럴때에는
의류정보평균이 잘못계산됩니다.

> http://localhost:8080/clothes/K042

이를 수정하기 위해서 대여자의 신체치수를 변경해도 주문서에서는 여전히
잘못된 신체 치수가 남아 있기때문에 이를 해결할 방법이 없습니다.

**Comment by keedi** [comment]
일단 대여자의 신체 치수를 변경시킨다고 주문서를 같이 변경시켜주면 안됩니다. 지나간 주문서에 영향을 미칠 수 있기 때문에 그렇습니다. 이 기능이 필요하다면 말 그대로 주문서에 기록된 신체치수만 변경하는 기능 및 UI가 되어야 합니다.

**Comment by keedi** [comment]
당장 필요하지 않은 기능이라 구현하지 않습니다. 주문서에 신체 치수가 잘못된 경우는 특수한 경우로 사료되고 이 경우는 사용자와 관리자의 확인을 거쳐 데이터베이스에 접속해 수정해야 할 것 같습니다.

이슈 닫습니다.
