### ISSUE TITLE
통계-수량에 가용 수량 컬럼 추가

### ISSUE THREAD

**Issue by keedi** [opencloset/opencloset#538]
`/stat/clothes/amount` 화면에서 **수량**을 표시할 때 다음 다섯가지 상태의 합만을 보여주도록 합니다.
라벨은 **수량**대신 **가용 수량**으로 변경합니다.

> 1,  '대여가능'
> 2,  '대여중'
> 5,  '세탁'
> 6,  '수선'
> 9,  '반납'

`/stat/clothes/amount/category/belt/gender/male` 화면에서 기존 **수량** 뒤에 **가용 수량** 컬럼을 추가합니다. 더불어 **분실**과 **폐기** 컬럼도 끝에 추가합니다.

**Comment by keedi** [comment]
수량 페이지입니다.
![screenshot-monster silex kr 10301 2015-08-10 14-45-40](https://cloud.githubusercontent.com/assets/138451/9160065/eee793b0-3f6e-11e5-9f60-c67eb38cd672.png)

항목별 수량 페이지입니다.
![screenshot-monster silex kr 10301 2015-08-10 14-47-07](https://cloud.githubusercontent.com/assets/138451/9160066/f2643cf0-3f6e-11e5-9f39-b2e087717a84.png)

**Comment by keedi** [comment]
진행합니다.

**Comment by keedi** [comment]
구현 완료된 수량 페이지입니다.
![screenshot-monster silex kr 10301 2015-10-02 12-58-19](https://cloud.githubusercontent.com/assets/138451/10239231/9afbbca2-6905-11e5-957a-c5560c646dde.png)

구현 완료된 항목별 수량 페이지입니다.
![screenshot-monster silex kr 10301 2015-10-02 12-59-11](https://cloud.githubusercontent.com/assets/138451/10239235/9ffc433e-6905-11e5-9f0d-45c3fcc12e4a.png)

**Comment by keedi** [comment]
서버에 적용 완료했으므로 실섭에서 확인 가능합니다.

**Comment by 10001if** [comment]
확인하였습니다.
