### ISSUE TITLE
시간표에서 재방문인 경우 방문 횟수 표시

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#542]
![2015-08-18 5 25 58 2](https://cloud.githubusercontent.com/assets/4696328/9325643/d86a4270-45ce-11e5-82cb-740afcb475d4.png)
시간표(~timetable/) 페이지에서 재방문이라는 표시대신, 대여횟수가 나타나도록 요청드립니다.
1회 대여는 제외하고 재방문 즉, 2회 대여부터 표시되도록 요청드립니다.

**Comment by 10001if** [comment]
여러번 대여를 하신 분에 경우에는 조금 더 신경 써야 하는 부분이 있습니다. 안내시에 바로 확인 할 수 있도록 횟수 표시를 요청드립니다. ^^

**Comment by keedi** [comment]
일단 공식적으로 letters, visit 작업을 제외하고는 제가 처리하지 않을 예정입니다. 기존 제가 처리하려고 했던 이슈는 모두 담당자를 제거한 이후, 그 이후에 새롭게 담당자로 제가 지목되는 이슈에 한해 처리하겠습니다. 관련해서 제가 할당된 이슈의 담당자를 모두 제거하겠습니다.

**Comment by aanoaa** [comment]
부분반납인 경우에 하위주문서가 생성되면서 방문횟수가 늘어납니다.
부분반납은 방문횟수로 계산되면 아니됩니다.

**Comment by keedi** [comment]
기존 조건에 `order.parent_id`가 없는 조건을 동시에 적용하면 하위주문서를 대여 횟수에서 제거할 수 있습니다.

**Comment by keedi** [comment]
이런 경우는 별도 이슈 "시간표에서 재방문 횟수가 잘못 표시됨"등으로 여는게 더 추적에 좋을 것 같습니다만, 별 상관은 없겠죠.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
