### ISSUE TITLE
대리로 빌리거나 단체로 빌리는 경우를 구분할 수 있어야 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#545]
총 대여인원은 8명인데 대표자 1명이 나머지 7명의 사이즈를 들고와서 대여를 하는 경우가 현실적으로 발생하고 있습니다. 이런 경우 대여 기록과 의류 사이즈의 매칭이 이뤄지지 않아야 할 것 같은데요. 이 부분에 대한 해결방법이 필요합니다.

**Comment by keedi** [comment]
대리로 빌리는 경우도 있고 한 명이 대표로 빌리는 경우도 있습니다. 물론 한 명이 대표로 여러 벌의 옷을 대리로 빌릴 수도 있습니다. 이 경우를 구분하는 이유는 해당 대여자의 신체 치수와 빌려간 의류의 치수 정보를 이용해서 2차적으로 자료를 조합하지 않아야하기 때문 입니다.

**Comment by 10001if** [comment]
#71 이슈와 연관이 되는 부분도 있을 것 같습니다. 대리로 오시는 경우가 하루에도 1-2 건 정도 꾸준히 발생하고 있습니다.

**Comment by aanoaa** [comment]
#71 이슈와 중복됩니다.
해당이슈에서 대리로 대여하는 경우도 고려해야합니다.

**Comment by aanoaa** [comment]
단체대여에 관련한 이슈는 여기서 다루고 #71 에서는 기증에 대해 다루겠습니다.

**Comment by aanoaa** [comment]
예약하고 대리하는 경우는 대리자는 원 예약자대신에 몸만 오는 것일테니
상관없을 것 같고, 예약없이 대리로 올 경우에는 실제 대여자의 정보를
입력받아야 할 것 같습니다.

대리로 오신분이 나중에 대여하러 오게되면 이게 또 문제가 될 수 있을 것
같습니다.

**Comment by aanoaa** [comment]
대표로 대여한다고 해도 두가지 이상의 경우가 있을 것 같습니다.

- 개인이 대표로 대여(친구들)

    친구들 사이즈를 가지고 와서 여러벌 대여

- 어느단체로 대여(기업등)

    열린옷장에서 왔는데 10벌을 빌리는 것

첫번째는 개인으로써 예약을 하고(개인정보), 주문서에 `단체`로 표시 해야
할 것 같고, 두번째는 단체를 대표하는 정보를 입력받는게 좋을 것
같습니다.

**Comment by aanoaa** [comment]
여러벌 대여의 경우 주문서를 여러개 만들면 이게 근본적인 해결방안 인 것
같지만 여기에서는 하나의 주문서에 여러벌의 대여일때를 얘기합니다.

**Comment by aanoaa** [comment]
대리인의 경우를 고려한다면(하고싶지않지만), 성별에 `미정`등을 두어야
통계를 계산할때에 도움이 되겠습니다.

그래야 해당 주문서는 통계를 계산할때 빼버릴 수 있으니까요.

실질적인 문제로 이미 대리인의 정보로 예약을 하고 옷장에 왔는데 다시
실제 대여자의 정보로 기입하라고 하기 어렵습니다.(어렵죠?)
이때 어쩔 수 없이 실대여자(아들, 딸)의 신체치수를 적어야 staff 가 옷을
고를 수 있습니다.(치수가 있어야 고르지)

그렇게 되면 대리인 홍길동씨의 신체치수에는 실대여자인 홍금보(아들)씨
의 치수가 입력될텐데 그렇게 되면 재방문 혹은 통계를 낼 때 문제가
발생할 수 있습니다. (홍길동씨는 남자인데 홍금보씨가 여자인 경우 라던지)

**Comment by aanoaa** [comment]
지금 주문서에는 `성별`이 없습니다.
주문서에 성별을 나타내는 컬럼을 추가하고,
지금까지의 주문서를 뒤져서 알맞은 성별을 넣어주고, 통계를 구하는
곳에서 실사용자의 성별대신에 주문서의 성별을 참고하도록 수정해야
합니다.

생각보다 볼륨이 커지는 작업입니다.

**Comment by yongbin** [comment]
저는 근본적으로 이 이슈를 꼭 해야하는지에 대한 회의감이 있습니다. 과연 대리로 빌리는 경우와 단체로 빌리는 경우 (혹은 그 곱)이 시스템에 도입해야할 만큼 빈번하게 일어나고 고려해야할 일인지 판단했으면 좋겠습니다. @10001if

**Comment by aanoaa** [comment]
주문서마다 성별을 넣으면 실제 대여자의 성별과는 상관없이 구분 할 수
있습니다.

또 문제가 되는 것이 대리자인 경우에 주문서에 신체치수를 넣어야 하는데
그런 기능은 없습니다. 사용자의 신체치수를 넣으면 그 정보가 주문서에
복사는 되고 있습니다.

**Comment by aanoaa** [comment]
주문서에 `성별`이 있으면 좋겠다고는 오래전부터 생각해왔습니다.

**Comment by aanoaa** [comment]
`order -> user -> user_info` 로 성별을 가지고 오는 작업이 귀찮았거든요

**Comment by yongbin** [comment]
형석님이 잘 지적해주신것 처럼 무언가를 `대리`로 한다는것을 시스템에 반영한다는건 기존 시스템을 필요이상으로 복잡하게 만드는 경향이 있습니다. 저는 `대리`로 빌리는주문이 정말로 어느정도 일어나는지를 먼저 지난 자료로 확인해봤으면 좋겠습니다.

**Comment by aanoaa** [comment]
제 생각은 주문서에 성별을 넣는 작업은 볼륨이 있습니다

통계와 관련된 작업에서 성별을 참고하는 코드가 변경되어야 하기
때문입니다.

하지만 주문서에 성별에 관련된 컬럼이 들어가고나면 대리로 빌리던 단체로
빌리던 이 작업 자체는 단순합니다.

**Comment by aanoaa** [comment]
볼륨이 있다고는 해도 여기저기 찾아서 바꾸면 되는 것이라서 크리티컬한 작업은 아닙니다.

**Comment by yongbin** [comment]
> 주문서에 성별이 있으면 좋겠다고는 오래전부터 생각해왔습니다.
> order -> user -> user_info 로 성별을 가지고 오는 작업이 귀찮았거든요

만약 `order -> user -> user_info->gender`에 접근하는게 번거로운것만 이유라면 `Order.pm` 에서 `gender` 함수를 만들어서 단축접근을 제공할수 있을것 같습니다. 혹은 `user`와 `user_info` 테이블을 합치는 방법도 있습니다. 저도 개인적으로는  `user`와 `user_info`를 분리할이유가 있나 생각한적은 있습니다.

**Comment by aanoaa** [comment]
한가지더, 기존의 주문서들에 성별에 관련한 데이터를 넣어주는 작업이
필요합니다.

**Comment by aanoaa** [comment]
주문서에 성별에 관련된 컬럼이 추가가 된다면 시스템이 복잡해지지는
않습니다. 이 작업이 필요한가 아닌가가 중요한 것 같습니다.

**Comment by yongbin** [comment]
> 총 대여인원은 8명인데 대표자 1명이 나머지 7명의 사이즈를 들고와서 대여를 하는 경우가 현실적으로 발생하고 있습니다. 이런 경우 대여 기록과 의류 사이즈의 매칭이 이뤄지지 않아야 할 것 같은데요. 이 부분에 대한 해결방법이 필요합니다.

> 대리로 빌리는 경우도 있고 한 명이 대표로 빌리는 경우도 있습니다. 물론 한 명이 대표로 여러 벌의 옷을 대리로 빌릴 수도 있습니다. 이 경우를 구분하는 이유는 해당 대여자의 신체 치수와 빌려간 의류의 치수 정보를 이용해서 2차적으로 자료를 조합하지 않아야하기 때문 입니다.

단지 대여기록과 의류 사이즈 매칭사이에 정보 불일치가 문제라면 해당자료들을 표시해줄수 있는 플레그를 추가해주고 검색등 처리에서 해당 부분자료를 걸러내면 될것 같습니다. 사실상 #715 와 비슷한 작업이 됩니다

**Comment by aanoaa** [comment]
오히려 이런 예외처리들이 시스템을 더 복잡하게 만든다고 생각합니다.

예로 온라인 구분을 22:00 로 하고 있는 지금 이 상황이..

**Comment by aanoaa** [comment]
플래그를 하나둬서 온라인을 구분하던지 22:00 로 구분하던지 상황은
같다고 봅니다. 단지 구분만 할 수 있으면 되니까요.

하지만 22:00 로 사용하는 건 예외 상황 처럼 느껴져서 더 복잡하다고
여겨지고 on/off 를 사용하게 된다면 좀 더 직관적으로 느껴져서 그런 것
같습니다.

**Comment by aanoaa** [comment]
핫이슈 :hotsprings:

**Comment by yongbin** [comment]
넵 저도 공감합니다. 온라인은 좀더 일직 별도의 플레그로 빠졌어야 했는데 (적어도 2015년 5월 27일에는) 여러가지 이유때문에 미뤄졌고 결과적으로 시스템에 불필요한 예외처리 코드들이 많이들어갔습니다 (5월 27일 전이면 7시 후면 10시) 제 말은 단지 열린옷장에서 우려하는게 단순하게 기록된 자료의 **불일치** 만이라면 그 자료를 확인하지 않을 표시만남기면 된다는 이야기였습니다 어차피 단체나 대리로 빌리는 경우에 정확하고 쓸만한 신체정보를 수집할 가능성도 적으니까요

**Comment by yongbin** [comment]
최근 유사하게 '주문서에 성별을 넣는 논의'는 #829에서도 있었습니다.

**Comment by aanoaa** [comment]
대리인지 단체인지 구별해야 하는 이유가
사용자의 대여기록 및 의류 사이즈 매칭때문이라면,

지금의 대여절차를 손봐야 합니다.

현재는 사용자의 신체치수를 측정하면 사용자정보가 갱신되고,
측정된 사이즈가 주문서에 복사됩니다.

대리자의 경우에는 사용자의 신체치수가 사용자정보에 갱신되면 안되고,
주문서에 입력되어야 합니다.

하지만 지금은 이렇게 할 수 있는 방법이 없습니다.

**Comment by aanoaa** [comment]
1. 여러벌 대여

    본인 치수를 넣고, 나머지는 종이로 써서 대여해야 합니다.

2. 대리인의 치수로 대여

    대리인의 치수를 넣되, 주문서에만 들어가게 해야 합니다.
    혹은 이경우에도 종이로 써서 대여합니다.
    변경없이 처리할 수도 있습니다.
    재방문했을때에도 치수측정을 할테니까 다른 사이즈는 문제가 되지 않습니다.
    성별이 문제가 될 수 있습니다. 남자인데 스커트를 빌린다거나..

**Comment by aanoaa** [comment]
> 총 대여인원은 8명인데 대표자 1명이 나머지 7명의 사이즈를 들고와서 대여를 하는 경우가 현실적으로 발생하고 있습니다. 이런 경우 대여 기록과 의류 사이즈의 매칭이 이뤄지지 않아야 할 것 같은데요.

재방문했을때 다시 치수측정을 하기 때문에 의류사이즈 매칭은 걱정하실 필요가 없을 것 같습니다.

cc @10001if @yongbin

**Comment by yongbin** [comment]
다들 아시는 내용이지만 DB 스키마 관점에서 현재 상황을 정리해보면 다음과 같습니다.

 - `사용자`는 한 사람이며 본인입니다.
 - `주문`은 `사용자` 1인과 관련된 행위입니다 

따라서 현재 구조를 그대로 유지하면서 대리로 옷을 빌리거나 단체로 옷을 빌려주는것을 구현할 방법은 없습니다. 만약 진행해야 한다면 대리대여와 단체대여 둘다 각각 분리해서 스키마에 해당내용을 표현해 줄수 있는 새로운 개념이 반영되어야 합니다. 

만약에 진행하다고 가정하고 잠깐 고민해봤을때 당장 떠오르는 아이디어는 다음과 같습니다.

## 대리로 대여

 - `사용자`와 `대여프로필`을 분리합니다. 즉 온오프라인 사용자는 열린옷장에 방문하거나 사이트에 로그인하는 주체이지만 하나이상의 `대여프로필`을 가질수 있습니다.
 - 대부분의 경우 자신의 대여프로필을 사용하지만 대리로 빌리는 경우 다신의 프로필 이외에 다른 대여프로필을 만들어서 대여합니다. 

## 단체로 대여

 - `사용자`가 여러개의 `대여프로필`을 만들고 대여
 - 개념적으로 대리로 만드는것과 동일하지만 이 경우는 UI상으로 단체대여에 대한 별도의 지원이 필요합니다.
 - 단체대여 의류의 반납역시 마찬가지로 별도의 UI가 필요합니다.

## 의류사이즈 매칭

 - 기존에는 사용자  == 대여자로 가정했지만 만약에 대여프로필이 추가될 경우 실질적으로 의류메칭의 대상은 더이상 사용자가 아니라 대여프로필의 대상이 되어야 합니다. 
 - 즉 사용자 A가 a,b,c,d,e 5명의 대여프로필을 가지고 와서 대여를 할때 A 의 사이즈는 의미가 없으며 각각 a,b,c,d,e의 치수정보를 대상으로 매칭이 이루어져야 합니다.
 - 현재도 대여시점에 의류의 사이즈와 신체의 사이즈는 참조(referenc)방식이 아니라 복사(copy)하고 있기 때문에 일부 처리가 되는 부분도 있지만 (예를 들면 지난번에 친구옷을 빌리고 이번엔 내옷을 빌릴경우) 완전하지는 않습니다. 만약 스키마가 변경될 경우 기존 자료는 약간의 부정확함을 감안하고 이전해서 사용해야합니다  

당장 생각나는것은 이정도 입니다. 기존에 시스템 전체가 사용자 == 대여자 로 가정하고 만들어졌기 때문에 모든 기능에서 영향받는 부분을 어떻게 처리할지도 고려해야합니다.

**Comment by aanoaa** [comment]
> 총 대여인원은 8명인데 대표자 1명이 나머지 7명의 사이즈를 들고와서 대여를 하는 경우가 현실적으로 발생하고 있습니다. **이런 경우 대여 기록과 의류 사이즈의 매칭이 이뤄지지 않아야 할 것 같은데요.**

제가 얘기하고 싶은 것은 바꾸지 않아도 될 것 같다 입니다.
대리로 빌린다고 하더라도 재방문해서 자신의 의류를 대여하고자 할때 치수측정이 다시 이루어지기 때문이고,
단체일 경우에는 시스템을 이용하는 것이 아니라, 종이에 적어서 하거든요.

**Comment by yongbin** [comment]
매칭에 사용되는 의류정보의 경우도 대리일경우는 해당사항이 없고, 단체일경우 종이로 적은 신체정보가 DB에 저장되지 않기는 하지만 빈도가 그리 많지 않을꺼라고 생각하기때문에 문제없습니다. 종이로 적을경우 주문서는 각각 생성하나요??

**Comment by aanoaa** [comment]
아닙니다 종이는 사용후 폐기됩니다.

**Comment by aanoaa** [comment]
A 씨가 대리로 여러벌을 대여했는데 다양한 사이즈의 의류입니다.
이 의류들을 대여하면 기록이 남습니다.

의류검색을 하게 된다면 위와 같은 기록들이 무시될까요?

**Comment by aanoaa** [comment]
@yongbin 위에꺼 답변 좀 해주세영

**Comment by yongbin** [comment]
무시되지 않습니다. 만약에 의류검색이슈라면 위에 적은거처럼 `order`에 `type` 속성 컬럼을 만들고 '일반', '대리', '단체'를 넣은뒤 의류검색용 학습셋을 만들때 '일반' 셋만 넣으면 될거 같습니다.

**Comment by aanoaa** [comment]
주문서에 **검색에 무시됨** 과 같은 컬럼을 추가하기로 했습니다.
단체이건, 대리이건 또 그 이외의 상황이건 검색에 부정적인 영향을 줄 수 있는
주문서를 걸러내고 검색에서는 이를 활용하기로 했습니다.

**Comment by yongbin** [comment]
@aanoaa 님과 대화하다가 알게되었습니다. `단체`의 경우 대여기록에서 하나의 주문서에 하나이상의 대여를 하기때문에 데이터에서 걸러낼수 있습니다. 따라서 이 이슈에서 걱정하는 문제를 해결하는 방법은 다음 3가지가 있습니다.

 1. 현재 상태로 유지하고 데이터쪽에서 한 주문서에서 한세트 이상이 빌려진 주문서들을 학습대상에서 뺌
 2. `type` 같은걸 추가하고 '대리','단체' 같은 값을 넣은 뒤 그 값들을 학습에서 제거 
 3. `ignore` 같은걸 추가하고 TRUE인걸 학습에서 제거

저는 어떤쪽으로 처리해도 상관없지만 다음과 같이 처리하겠습니다.

이 이슈가 처리되기 전 시점의 경우 보수적으로 주문서중 한벌이상 대여된 주문서를 제거하고 학습시키겠습니다. 이 이슈가 처리된 이후에는 명시적으로 ignore 가 TRUE인 주문서를 제거하고 학습시키겠습니다.

**Comment by yongbin** [comment]
결국 이 이슈는 #776 과 관련있습니다. @10001if 님과 원래 한달에 한번 진행하려고 했지만 2달이상 밀려있는 상태입니다. 이번 #776 처리때 이 내용들을 반영하겠습니다.

**Comment by aanoaa** [comment]
@yongbin 검색을 위해 주문서를 한번 분석하고 끝인가요?
아니면 매번 검색할때에 모든 주문서를 분석하나요?

전자라면 어느시점에 주문서의 분석이 이루어지나요?

**Comment by yongbin** [comment]
전자입니다. #720 때 시스템 도입 이후 2016-02-21까지 분석했고 #776 에서 2016년 5월말자료를 업데이트할 예정입니다.

**Comment by yongbin** [comment]
> 주문서에 검색에 무시됨 과 같은 컬럼을 추가하기로 했습니다.

신의 한수입니다. @10001if 님과 의논한 결과 대리, 단체 대여뿐만 아니라 열린옷장 입장에서 찝찝한 모든 주문서를 무시하는 용도로 사용하신다고 합니다.

**Comment by aanoaa** [comment]
어떤 스크립트를 실행해서 한번 분석하고 결과를 만들어두고 사용하는건가요?
그 실행은 임의로 @yongbin 님이 직접하는거고요?

그렇다면 주문서의 상태와 관계없이 언제 어느때고 **검색에서 제외** 버튼 같은 것을 누를 수 있도록 해야 겠습니다.

**Comment by yongbin** [comment]
대략 이런 방식으로 진행됩니다.

1. 특정시점 DB를 내려받음 
2. 특정쿼리로 CSV파일을 떨굼
3. 해당 CSV파일중 일부를 나눠  R을 통해 전처리한뒤 검색모델 학습시킴
4. 남은 CSV파일의 내용을 통해 3에서 만든 모델의 검색성능을 테스트함
5. 완성된 검색모델 + CSV를 opencpu.theopencloset.net 장비에 올리고 배치 
6. 의류검색에서 REST API 호출해서 사용



> 그렇다면 주문서의 상태와 관계없이 언제 어느때고 검색에서 제외 버튼 같은 것을 누를 수 있도록 해야 겠습니다.

넵 어차피 기존에 넣었던 주문서들을 빼는건 2번 단계에서 처리가 가능하니까 상태에 상관없이 검색제외가 적용되면 좋습니다.

**Comment by aanoaa** [comment]
주문서 상세 화면에서 눈에 잘 띄지 않는 곳에 작게 표시하도록 하겠습니다.

**Comment by aanoaa** [comment]
![screenshot-localhost 5001 2016-05-26 17-32-58](https://cloud.githubusercontent.com/assets/170528/15568669/0e9cc080-2368-11e6-9b63-aac925102523.png)
![screenshot-localhost 5001 2016-05-26 17-33-20](https://cloud.githubusercontent.com/assets/170528/15568670/0ed7713a-2368-11e6-92df-fc9a084beba8.png)

OpenCloset::Schema 에 의존성이 걸려있습니다.

**Comment by aanoaa** [comment]
@yongbin 님의 작업이 남아 있는데 닫아버렸습니다.

**Comment by yongbin** [comment]
아 닫으셔도 됩니다. 여기서 처리된 주분서를 검색자료에서 제거하는작업은 #776 에서 진행하도록 하겠습니다. 처리해주셔서 감사합니다!

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
