### ISSUE TITLE
대여에서 대여가능 이외에도 반납, 세탁, 수선, 포장취소, 예약 상태도 결제대기로 바꿀 수 있게 함

### ISSUE THREAD

**Issue by keedi** [opencloset/opencloset#546]
대여가능 이외의 의류가 대여 및 포장 단계에서 찍히는 경우가 많다고 합니다. 이것 때문에 다시 상태 변경 페이지에서 상태를 변경한 후 바코드로 항목을 다시 찍는 것은 번거롭다는 지적이 있어서 의류가 다음 상태일 경우도 선택이 가능하도록 변경합니다.

- 반납(9)
- 세탁(5)
- 수선(6)
- 포장취소(41)

![screenshot-monster silex kr 10301 2015-08-31 15-06-04](https://cloud.githubusercontent.com/assets/138451/9573022/f2ceed78-4ff1-11e5-82aa-abaa08c784ad.png)

**Comment by keedi** [comment]
예약 상태도 가능하도록 하기로 했습니다.

**Comment by yongbin** [comment]
`대여` 화면에서 선택이 가능해야하는 의류의 상태는 아래와 같습니다. 

 - 반납(9)
 - 세탁(5)
 - 수선(6)
 - 포장취소(41)
 - 예약(4)

**Comment by yongbin** [comment]
## 대여화면에서 '반납' 상태인 의류를 입력

![screenshot 2016-03-02 00 56 55](https://cloud.githubusercontent.com/assets/52704/13432625/ce829aae-e011-11e5-80ad-ebbd84efddb4.png)

## 체크박스 클릭시 확인

![screenshot 2016-03-02 00 57 03](https://cloud.githubusercontent.com/assets/52704/13432627/d1aacc6a-e011-11e5-8a2e-cd8b11d23b0c.png)

## 확인후 변경

![screenshot 2016-03-02 00 57 09](https://cloud.githubusercontent.com/assets/52704/13432628/d40618ac-e011-11e5-818f-4b298740da5a.png)

## 변경후 선택가능

![screenshot 2016-03-02 00 57 45](https://cloud.githubusercontent.com/assets/52704/13432636/d712b546-e011-11e5-861d-c9983425363c.png)

**Comment by aanoaa** [comment]
PR 에 관련된 스샷은 PR 에 남겨주세여
저는 그게 더 편합니다.

**Comment by aanoaa** [comment]
@10001if 영업시간 이후에 배포한뒤에 말씀드리겠습니다.
그리고 나면 테스트 주문서 만들어서 확인해주세요.

**Comment by yongbin** [comment]
> PR 에 관련된 스샷은 PR 에 남겨주세여
> 저는 그게 더 편합니다.

넹

**Comment by 10001if** [comment]
@aanoaa 네! 알겠습니다.

**Comment by yongbin** [comment]
한만일대표님 확인 완료했습니다. 이슈 닫겠습니다.

**Comment by aanoaa** [comment]
배포하였습니다.

**Comment by aanoaa** [comment]
`대여불가` 일때에도 변경될 수 있어야 합니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
