### ISSUE TITLE
방문 일자 선택 화면에서 시간이 한 화면에 나타날 수 있도록 수정

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#547]
![2015-08-31 5 40 28](https://cloud.githubusercontent.com/assets/4696328/9575047/7fe9eb76-5007-11e5-9e99-cbd4b91f28d9.png)
현재는 위 그림과 같이 방문일자를 선택했을 때, 하단에 시간이 표시되지 않습니다. 스크롤하여 내려가면 시간이 보이지만, 이것으로 인해 시간을 확인할 수 없다는 질의가 반복적으로 들어오고 있습니다. 때문에 화면의 길이를 늘여 하단에 시간이 스크롤 없이도 보일 수 있도록 수정 요청드립니다.

**Comment by keedi** [comment]
메시지 중 하기 내용을 제거해서 시간 표시 영역을 좀 더 끌어올리기로 했습니다.

```
예)
옷이 필요한 날 - 12월 5일
적절한 예약일 - 12월 3일 또는 12월 4일
```

**Comment by keedi** [comment]
진행합니다.

**Comment by keedi** [comment]
완료된 화면은 다음과 같습니다.
![screenshot-monster silex kr 10301 2015-10-02 15-59-23](https://cloud.githubusercontent.com/assets/138451/10241084/3ac8d954-691f-11e5-9365-e61ead69d568.png)

**Comment by keedi** [comment]
처리 및 배포 완료했으므로 이슈 닫습니다.

**Comment by 10001if** [comment]
확인하였습니다.
