### ISSUE TITLE
방문 예약시 예약 마감된 시간을 표시할 수 있도록 수정

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#548]
![2015-08-31 5 43 47](https://cloud.githubusercontent.com/assets/4696328/9575106/e42af508-5007-11e5-96e5-992194f5448f.png)
현재는 예약이 가능한 시간만 표시되고 있습니다.
예약이 만료된 시간은 처음부터 보여지지 않아 대여자는 표시된 시간 중에 가능한 시간을 골라 예약하면 되지만
예약 많아 전 날 이미 완료된 경우에는 시간이 보이지 않아 예약할 수 없다는 연락이 많이 옵니다. 대여자 입장에서는 예약을 하고 싶으나 시스템 오류로 인해 예약을 할 수 없는 것으로 오해를 하는 경우가 있습니다. 때문에 예약이 만료된 경우에도 시간을 정상적으로 보여주고 다만 예약만료로 인해 선택을 할 수 없다는 것을 알려주었으면 좋겠습니다.
![2015-08-31 5 43 47](https://cloud.githubusercontent.com/assets/4696328/9575233/e720c6a6-5008-11e5-860d-d4ff8a497dbf.png)
제가 아이디어가 딱히 떠오르지 않는데, 이런 형식이면 어떨까 합니다. ^^;

**Comment by keedi** [comment]
진행합니다.

**Comment by keedi** [comment]
현재 열린옷장에서 사용하고 있는 시간대입니다.

```perl
    booking => {
        male => {
            '10:00' => 4,
            '10:30' => 4,
            '11:00' => 4,
            '11:30' => 4,
            '12:00' => 0,
            '12:30' => 0,
            '13:00' => 0,
            '13:30' => 0,
            '14:00' => 4,
            '14:30' => 4,
            '15:00' => 4,
            '15:30' => 4,
            '16:00' => 4,
            '16:30' => 4,
            '17:00' => 4,
            '17:30' => 2,
            '18:00' => 0,
            '18:30' => 0,
            '19:00' => 0,
            '19:30' => 0,
            '20:00' => 0,
            '20:30' => 0,
            '21:00' => 0,
            '21:30' => 0,
            '22:00' => 0,
        },
        female => {
            '10:00' => 4,
            '10:30' => 4,
            '11:00' => 4,
            '11:30' => 4,
            '12:00' => 0,
            '12:30' => 0,
            '13:00' => 0,
            '13:30' => 0,
            '14:00' => 4,
            '14:30' => 4,
            '15:00' => 4,
            '15:30' => 4,
            '16:00' => 4,
            '16:30' => 4,
            '17:00' => 4,
            '17:30' => 2,
            '18:00' => 0,
            '18:30' => 0,
            '19:00' => 0,
            '19:30' => 0,
            '20:00' => 0,
            '20:30' => 0,
            '21:00' => 0,
            '21:30' => 0,
            '22:00' => 0,
        },
    },
```

예약할 수 없는 시간대를 모두 표시해줄 경우 실제로 예약 완료로 표시되는 영역이 너무 길게 보여질 것으로 예상됩니다.  차선으로 slot이 0보다 큰데 꽉 찬 경우에 한해서 예약완료로 보여주는 방법이 있습니다.

다만 이것이 열린옷장에서 원하는 것인지는 확인이 필요합니다.

**Comment by keedi** [comment]
서버측 또는 클라이언트측 중 처리하는 위치에 따른 몇가지 권한이나 abuse와 관련한 우려가 있어 걱정되지만, 꼭 필요한 기능이라고 하니 일단 진행합니다. 향후 abuse를 확인하게 될 경우 좀 더 세심하게 프로세스 자체를 바꿔야할 수도 있습니다.

**Comment by keedi** [comment]
열린옷장 워크샵 관계로 몇가지 확인하고 싶은 부분을 확인하지 못했습니다.

상식적인 수준에서 상기에 기록한대로 처리(slot이 0보다 크고 예약자 수가 slot과 같거나 많은 경우에 한해서 예약 불가로 선택이 불가능하도록)했습니다.

**Comment by keedi** [comment]
구현한 화면은 다음과 같습니다.
![screenshot-monster silex kr 10301 2015-10-02 18-28-04](https://cloud.githubusercontent.com/assets/138451/10243422/6f0db8ce-6933-11e5-8c83-bd3605ed7240.png)

**Comment by keedi** [comment]
작업 및 서버에 배포 완료했습니다.

이슈 닫습니다.

**Comment by 10001if** [comment]
확인하였습니다.
