### ISSUE TITLE
새 옷 등록시 바코드 자동생성 기능 요청

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#550]
@yongbin  대표님과 간단히 이야기를 나눴는데요.

현재 의류 새옷 등록 상황은 다음과 같습니다. 

1. 셔츠의 경우 새 옷이 들어오면, 대표님이 메일로 보내주신 자료를 구글독스에 옮겨놓고 필요에 따라 하나씩 사용합니다. 독스에 적혀있는 코드를 복사해서 바코드를 생성하는 프로그램에 입력하여 출력한 뒤 구글독스에 적혀있던 코드에 사용여부를 체크합니다.

2. 그 외 의류의 경우 새 옷이 들어오면, 기존에 출력했던 의류코드를 확인하고 그 코드를 눈으로 확인 한 뒤 바코드를 생성하는 프로그램에 입력하여 출력한 뒤 본 코드는 휴지통에 버립니다.

1과 2가 다른 이유는 2는 봅아놓은 코드가 있기 때문이고 1의 경우에는 뽑아놓은 코드를 다 사용했기 때문입니다.

그리고 1번(셔츠)의 경우 온라인으로 코드를 복사하여 사용하는 이유는 기존에는 코드명만을 출력하여 사용하였는데, 코드에 기증일자와 기증자명이 한꺼번에 들어가야 한다는 결정을 내렸습니다. 그래서 코드명만 확인하고 그 코드에 맞는 기증자와 기증일자를 입력하여 개별적으로 출력하기 때문입니다. 

그래서 현재는 코드명만을 확인하여 일일이 출력을 하고 있습니다.

하지만 이로 인해 코드가 중복되는 문제들이 발생하고 있는데요. 이에 대한 해결책으로 새옷 등록 시 코드 자동 생성을 요청드리고 싶습니다. 코드를 만들어서 프로그램에 입력하는 것이 아니라, 새옷을 등록하면 코드가 자동생성되어 부여되고, 그 코드를 프린터해서 옷에 붙이는 방식으로 진행하고 싶습니다. 

그러면 코드를 일일이 받아 입력하여 중복되는 문제가 발생하지 않을 것이라 생각합니다. 

이에 대한 @keedi 의 의견 부탁드립니다. :)

**Comment by keedi** [comment]
@10001if 님께서 더 내용을 정리해주시면 그 때 진행 여부를 결정하겠습니다.

**Comment by 10001if** [comment]
논의 중인데 결정나면 바로 말씀드리겠습니다.

**Comment by 10001if** [comment]
말씀해 주신 방법으로 진행해 보려 합니다. 그 전에 기본 바코드를 숫자로 변환시킬 수 있는 페이지 생성을 요청드립니다. 기존에 바코드 입력되있던 것은 새로 만들어서 붙이지 않고 기존 바코드에 수정을 하여 숫자를 입력할까 합니다. 기존 바코드에 스캐너로 찍으면 숫자로 변환할 수 있는 창이 있다면 바로 수정이 가능할 것 같습니다. 

그리고 앞으로는 프로그램에서도 의류코드 하단에 의류의 숫자가 씌여져 있도록 란을 하나 추가해 주시면 감사하겠습니다. 바코드 크기와 양식이 결정되면 바로 말씀드리도록 하겠습니다.

**Comment by 10001if** [comment]
바코드 크기와 양식을 결정하는데 있어서 싷제로 붙일 것인지 미싱을 이용해서 의류에 바느질 방식으로 박을 것인지 결정이 되지 않아 조금 늦어 지고 있습니다. 결정되면 다시 말씀드리겠습니다.

**Comment by 10001if** [comment]
바코드를 옷에 부착하는 방식대신 재봉틀을 이용해서 의류에 박는 형식으로 활용하기로 하였습니다. 어제 재봉틀을 구입했으니 연습과정을 거쳐서 저확한 크기랑 방법에 대해서 다시 말씀드리겠습니다.

**Comment by 10001if** [comment]
바코드 크기와 양식은 거의 결정이 되었는데요. 000000 6가지 숫자에 대해 질문이 있습니다. 6자리 숫자만 보고도 J, P 처럼 복종 구분이 되는 것인지 궁금합니다. 다시 말해서, J001 -> 000000으로 변환 될 때 J가 6자리 숫자 안에 포함이 되어 있는 것인지 궁금합니다.

**Comment by 10001if** [comment]
이 작업을 사용하게 된다면 J001을 특벙 숫자로 변환시켜주는 별도의 창이 필요할 것 같습니다. 확실히 결정되면 작업을 요청드리겠습니다.

**Comment by 10001if** [comment]
본 이슈는 바코드를 출력하여 사용하는 것으로 완료된 것으로 보입니다. 이슈 닫도록 하겠습니다. ^^
