### ISSUE TITLE
기증된 의류의 새옷등록시 사용할수 없어 폐기되는 경우

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#551]
현재는

 1. 기증박스 도착
 2. 새옷등록
  1. 사용가능의 경우 `대여가능`
  2. 수선수 사용이 가능하면 수선이 필요하면 `수선` 후 `대여가능`
  3. 사용이 불가능한 경우(각각 기증자에게 문자 연락)
    - 옷캔
    - 비백

사용가능의 경우나, 수선이 필요한 경우 결과적으로는 대여가능 상태가 되어 모두 5층으로 올라갑니다.

하지만 사용 불가능한 경우는 "폐기" 상태로 변경하는 것이 프로그램상 할 수 있는 마지막입니다.

그래서 "폐기"의 경우 1. 어디로 의류가 보내졌는지 2. 폐기되는 이유는 무엇인지 를 작성하는 란이 필요하구요.
이렇게 입력이 완료되면 자동으로 문자 또는 이메일을 통해 기증자에게 폐기상황을 알려주었으면 합니다.

"분실"의 경우에도 1. 왜 분실이 되었는지 를 작성하는 란이 필요하구요. 이렇게 입력이 완료되면 자동으로 문자 또는 이메일을 통해 기증자에게 폐기상황을 알려주었으면 합니다.

**Comment by 10001if** [comment]
#625 랑 결국에는 연관이 될 것 같습니다~ ^^

**Comment by aanoaa** [comment]
높음, 매우 높음이 있는데, 매우높음 부터 처리하면 되는건가요?

**Comment by aanoaa** [comment]
이게 매우높음이라 할지라도 #625 하 해결되지 않으면 진행할 수 없습니다.
#625 는 높음인데 이리되면 라벨이 이상해집니다.

급한맘은 알겠습니다.
영화 인크레더블에서 신드롬이 한말입니다.

> When everyone's super, no one is!

**Comment by 10001if** [comment]
@aanoaa  방금 라벨 수정하였습니다. 이런 내용이 있다싶으시면 편하게 이야기 해주세요. 하나씩 해결할 수 있도록 저도 맘을 모으겠습니다. ^^

**Comment by yongbin** [comment]
이 이슈는 처리방향에 따라서 https://github.com/opencloset/donation/issues/6 과 선행의존성이 있습니다. 처리방향을 논의하고 만약 의존성이 있다면 앞에 이슈를 먼저 처리합니다.

**Comment by yongbin** [comment]
> "분실"의 경우에도 1. 왜 분실이 되었는지 를 작성하는 란이 필요하구요. 이렇게 입력이 완료되면 자동으로 문자 또는 이메일을 통해 기증자에게 폐기상황을 알려주었으면 합니다.

@10001if  대표님 제가 이 이슈를 다시 정리해보니 이슈는 의류등록단계에서 `폐기`인 경우와 의류를 `분실`한 경우가 프로세스상 완전히 다른것 같습니다. 이슈를 명확하게 하기 위해서 이 이슈는 새옷등록시 `폐기`인 프로세스만 다루고 대여중이던 의류가 `분실`된 경우는 별도이슈에서 처리하겠습니다.

**Comment by yongbin** [comment]
본 이슈는 기존 재고관리의 `new-clothes` 의 새옷등록과정중 `사용이 불가능한 옷`을 별도로 처리하는 UI를 구현하고, 후속적으로 필요한 처리를 구현해야하는 이슈입니다. 마찬가지로 향후 기존 재고관리의 새옷등록과 독립된 별도의 새옷등록 프로세스를 개발할 계획 ( opencloset/donation#6 ) 이기때문에  본 이슈는 여기서 진행하지 않고 신규 새옷등록프로세스에 포함시켜서 진행하겠습니다. 

v1.1.0 에서 제거하고 이슈 닫겠습니다.
