### ISSUE TITLE
오프라인 대여 가능 상태와 온라인 대여 가능 상태를 구별해야 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#552]
@keedi 님께 이야기 드렸지만, 이슈에 옮겨 적습니다.

온라인 의류의 경우 미리 의류를 빼놓아야하는 경우가 많이 발생하는데, 이때 적용시킬 의류상태를 "예약"으로 적용하려 합니다. 하지만 향후 온라인이 정착되는 경우에는 근본적으로 오프라인과 온라인 의류를 구분해야 할 필요가 있습니다. 때문에 '온라인-대여가능' 과 같이 현재 존재하는 오프라인의류와 구분을 하는 기능이 필요합니다.

**Comment by keedi** [comment]
다음 이슈와 연관이 있습니다.

- opencloset/opencloset/issues/552
- opencloset/OpenCloset-Schema/issues/27
- opencloset/monitor/issues/70

**Comment by keedi** [comment]
다음 이슈와 연관이 있습니다.

- opencloset/opencloset/issues/552
- opencloset/OpenCloset-Schema/issues/27
- opencloset/monitor/issues/70

**Comment by keedi** [comment]
일단 공식적으로 letters, visit 작업을 제외하고는 제가 처리하지 않을 예정입니다. 기존 제가 처리하려고 했던 이슈는 모두 담당자를 제거한 이후, 그 이후에 새롭게 담당자로 제가 지목되는 이슈에 한해 처리하겠습니다. 관련해서 제가 할당된 이슈의 담당자를 모두 제거하겠습니다.

**Comment by yongbin** [comment]
@10001if 어제 한만일 대표님과 논의한 결과 현재 논의되고 있는 온라인 대여에서는 온/오프라인 의류를 통합해서 대여할 예정이기때문에 별도로 온/오프라인 대여가능상태를 구분할 필요성이 없다고 보입니다. 대신에 예전부터 논의된것 처럼 주문서의 속성에 온/오프라인 주문서여부를 기록하고 과거 자료를 소급해서 저장하는것은 별도로 진행되어야 합니다. 해당 이슈는 별도로 열어서 진행하도록 하겠습니다.
