### ISSUE TITLE
검색 및 SMS 전송할때에 전화번호에 `-` 를 허용

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#555]
사용자 검색할때 전화번호에서 `-` 자동 제거
sms 보낼때에도 `-` 를 허용가능하도록 변경

**Comment by aanoaa** [comment]
hyphen 을 허용했는데, 문자메세지가 전송이 안됩니다.
아마도 `send_sms` 할때 hyphen 을 빼줘야 하는 모양입니다.

**Comment by keedi** [comment]
UI는 상관없지만 전송할 때는 숫자 이외의 문자가 들어가면 안됩니다. 필터쪽을 수정하기 보다는 필터로 보내기 전 숫자만 남기도록 추출하는 편이 오류 및 사이드이펙트 발생 여지가 적을 것으로 사료됩니다.

그와는 별개로 이슈 등록시 요청사항이라면 가능하면 이슈가 등록되게 된 연유(why)를 기록하면 파악에 도움이 될 것 같습니다.

**Comment by aanoaa** [comment]
사용자를 검색하거나 SMS 를 보낼때 어디에서 복붙하는데,
`010-1234-5678` 같은 형식일 경우가 많은데 검색이 되지 않고 SMS 전송이 안되었기 때문입니다.

**Comment by keedi** [comment]
확인 후 이미 완료된 내역이면 이슈를 닫고 수정할 부분이 있다면 수정한 후 이슈를 닫겠습니다.

**Comment by keedi** [comment]
진행합니다.

**Comment by keedi** [comment]
1756005 커밋에서 입력시 `-` 기호를 받아 들이고 문자 전송 요청을 한 다음 요청 받은 문자 메시지에서 `-` 기호를 제거하는 방식으로 바뀌었습니다. 이를 수정해서 입력시 `-`기호를 받아 들이자마자 `-` 기호를 제거하는 방식으로 브라우저의 js를 이용해서 선처리한 후 나머지 동작은 모두 전화번호에서 숫자만 받아 들이도록(기존 방식) 수정하겠습니다.

**Comment by keedi** [comment]
처리한 내역은 다음과 같습니다.

- 문자 전송 페이지에서 브라우저 차원에서 숫자 이외의 기호를 제거하도록 했으며 서버측에서는 전화번호는 숫자만 허용하는 예전 방식으로 되돌립니다.
- 사용자 검색시 검색 질의 생성할 때 전화번호에 한해서만 질의에서 숫자 이외의 기호를 제거하도록 합니다.

**Comment by keedi** [comment]
기존 @aanoaa 님께서 처리하셨던 내역과 비교하면 내부적으로 처리 로직이 변경된 부분을 제외하면 사용자 입장에서는 차이는 거의 없습니다. 세세하게 사용자 검색시 질의한 내역에서 `-`가 사라지지 않는다던가 하는 정도의 차이는 있지만 별 의미는 없습니다.

**Comment by keedi** [comment]
구현 및 서버에 배포 완료 했습니다. 이슈 닫습니다.

**Comment by keedi** [comment]
본 기능은 반드시 문자 전송 및 사용자 검색 페이지에서 새로 고침을 한(여러번) 후에 확인해야 합니다. 브라우저의 캐시 정책에 따라 새로 고침을 하지 않을 경우 기능 확인이 어려울 수도 있습니다.

**Comment by keedi** [comment]
@10001if 이미 되고 있다고 생각하실 수도 있는데 내부적으로 변경된 부분이 있으니 한 번 더 확실하게 테스트 부탁드립니다.
