### ISSUE TITLE
첫 화면에서 의류코드를 넣으면 좌측에 순서대로 넘버링이 붙도록 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#556]
![1 2015-09-15 6 25 19](https://cloud.githubusercontent.com/assets/4696328/9873094/7d17d6d8-5bd8-11e5-9ea2-49b10e94cc9e.png)
반납시 다 찍은 의류의 합을 체크해야 할 경우가 있는데 좌측에 넘버링이 되어 있다면 훨씬 편리할 것 같습니다.

**Comment by keedi** [comment]
진행합니다.

**Comment by keedi** [comment]
다시 진행합니다.

**Comment by keedi** [comment]
#557 이슈와 유사 항목입니다.

**Comment by keedi** [comment]
이전 이슈와 마찬가지로 체크박스가 중요하기 때문에 숫자를 세는 부분은 체크박스 오른쪽에 위치하도록 처리하겠습니다.

**Comment by keedi** [comment]
구현한 화면입니다.

![screenshot-monster silex kr 10301 2015-12-15 14-41-47](https://cloud.githubusercontent.com/assets/138451/11803052/3389baa0-a33a-11e5-80d3-2b1424fbf607.png)

**Comment by keedi** [comment]
구현 및 서버에 배포 완료했습니다.

이슈 닫습니다.

**Comment by 10001if** [comment]
확인 완료하였습니다.

**Comment by keedi** [comment]
의류의 상태 변경시 실제 의류의 상태는 변경되나 화면에서 보이는 부분에서는 변경이 되지 않는 버그가 있습니다. 컬럼을 추가하면서 이를 수정하지 않은 것 같습니다.

**Comment by keedi** [comment]
자바스크립트의 버그를 수정 및 실서버에 배포 완료했습니다.

확인하려면 해당 페이지를 새로고침해야 합니다.

**Comment by keedi** [comment]
확인 후 문제 없으면 이슈 닫겠습니다.

**Comment by 10001if** [comment]
확인 완료하였습니다. 제가 이슈 닫도록 할게요~ 감사합니다~
