### ISSUE TITLE
대여화면에서 의류코드를 넣으면 좌측에 순서대로 넘버링이 붙도록 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#557]
![2015-09-15 6 25 47](https://cloud.githubusercontent.com/assets/4696328/9873116/9f84f8b8-5bd8-11e5-8df5-5d4d66d42715.png)
대여시에도 대여자가 대여한 품목의 수를 쉽게 눈으로 확인 할 수 있다면 훨씬 실수를 줄 일 수 있을 것 같습니다.

**Comment by keedi** [comment]
진행합니다.

**Comment by keedi** [comment]
구현한 화면은 다음과 같습니다.

![screenshot-monster silex kr 10301 2015-12-15 14-27-43](https://cloud.githubusercontent.com/assets/138451/11802852/6b9d782a-a338-11e5-897f-1722f3dbaeb1.png)

체크 박스 클릭이 주 목적이기 때문에 최초 @10001if 님께서 만들어주신 시안과는 달리 항목 개수를 보여주는 숫자를 체크박스 우측에 표기했습니다.

**Comment by keedi** [comment]
구현 및 실서버에 배포 완료했습니다.

이슈 닫습니다. :-)

**Comment by 10001if** [comment]
확인 완료하였습니다.
