### ISSUE TITLE
의류 상세 페이지의 의류 정보 하단에 베스트핏 주문서만 모아 별도의 테이블로 표시

### ISSUE THREAD

**Issue by keedi** [opencloset/opencloset#558]
키와 몸무게 기준으로 의류를 선택해서 빌려주려는 시도를 해보려고 한다고 합니다. 의류 상세 페이지에 베스트핏 주문서만 모아서 별도의 테이블로 추가 표시해달라는 요청이 있었습니다.

정확한 위치는 다음과 같습니다.

![screenshot-monster silex kr 10301 2015-09-16 17-57-46](https://cloud.githubusercontent.com/assets/138451/9900557/8eb8464c-5c9c-11e5-9adc-1c3b12c23d82.png)

**Comment by 10001if** [comment]
본 이슈가 적용되면 바로 의류의 키/몸무게를 가정하여 설정하여 키/몸무게로 의류를 대여하며 가능성을 타진해 보고 싶습니다. 우선순위를 상위에 두고 작업 부탁드립니다.

**Comment by 10001if** [comment]
@keedi 메세지 사이트 만드느라 정신이 없으실텐데 자꾸 이슈가 중간에 끼어드는 것 같아 죄송합니다~ ㅠ

**Comment by keedi** [comment]
@10001if 괜찮습니다~ 꼭 필요한 기능이면 넣어야지요~ :)

**Comment by keedi** [comment]
진행합니다.

**Comment by keedi** [comment]
구현 결과 화면입니다.
![screenshot-monster silex kr 10301 2015-10-05 15-37-29](https://cloud.githubusercontent.com/assets/138451/10274327/94af4bec-6b77-11e5-8b7a-6529b2c14140.png)

**Comment by keedi** [comment]
구현 및 서버에 배포 완료했습니다.

이슈 닫습니다.

**Comment by 10001if** [comment]
확인 완료 하였습니다.
