### ISSUE TITLE
"최종통보" 문자 매크로 추가 

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#559]
"최종통보"라는 제목으로 문자 매크로 추가 요청드립니다.

[열린옷장] ooo님 대여기간이 oo일 연체되었습니다. 더 이상 반납의사가 없다고 판단되어 명일(0/0) 내용증명서가 발송됩니다. 추후 광진경찰서에 고소장 접수 후 법적 절차를 통해 정장을 회수할 예정입니다. 참고 바라며, 최종 고지하는 것이오니 바로 답변바랍니다.

**Comment by keedi** [comment]
진행합니다.

**Comment by keedi** [comment]
작업 및 서버에 적용 완료했습니다.

**Comment by 10001if** [comment]
확인하였습니다.
