### ISSUE TITLE
사용자정보 화면에서 휴대전화 넣는 란에서 '-'를 허용

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#561]
![2015-09-21 2 51 38](https://cloud.githubusercontent.com/assets/4696328/9985961/a3b953b0-6070-11e5-81be-9acbf6f2ba11.png)
전화번호를 넣을 때 "-"를 넣어도 입력이 가능하도록 수정 부탁드립니다.

**Comment by 10001if** [comment]
@aanoaa 기능이 완료된 것 같은데. 이슈 닫아도 될까요? ^^

**Comment by keedi** [comment]
@10001if 근데 이게 정확하게 넣었는데 넣은걸 유지하는 걸 원하는건가요? 아니면 입력은 넣을 수 있게 하더라도 저장은 - 기호를 빼도 되는건가요?

**Comment by 10001if** [comment]
@keedi 복사해서 붙여넣기 하는 경우가 많은데, - 때문에 검색이 안되는 경우에 문제를 해결하기 위해 요청드렸던 것입니다. 저장은 - 기호를 빼도 됩니다.

**Comment by keedi** [comment]
@10001if 네 알겠습니다. 전자라면 시스템 전반적으로 확인해야할 부분이 많은데 후자라면(저장시에는 -를 뺀다면) 휴대전화를 넣는 란만 고민하면 되겠네요.

**Comment by keedi** [comment]
@aanoaa 해당 커밋이나 작업하신 PR 있으면 참조할 수 있게 붙여주세요~

**Comment by aanoaa** [comment]
@keedi 
17560056fa794bced272e2627d507537d8a9edef
c6699ea9cb92cf7f4cf6f2f76420eba7b114185d

**Comment by aanoaa** [comment]
끝나지 않은 이슈입니다.

#555, https://github.com/opencloset/volunteer/issues/16

이슈와 헛갈리신것 같습니다.

**Comment by keedi** [comment]
@aanoaa roger

**Comment by keedi** [comment]
진행합니다.

**Comment by keedi** [comment]
입력할 시점에는 `-` 기호를 가능하게 하더라도 바로 처리하는 과정에서 `-` 기호를 제거하고 저장하도록 합니다. 저장하자마자 화면에서도 `-` 기호는 사라진 상태로 보이게 합니다.

**Comment by keedi** [comment]
처리한 내역은 다음과 같습니다.

- bootstrap editable에서 서버에 업데이트 직전에 사용자가 입력한 문자에서 숫자를 제외한 모든 문자를 제거함
- bootstrap editable에서 서버에 업데이트 하는 것과는 별도로 화면에 보일때 사용자가 입력한 문자에서 숫자를 제외한 모든 문자를 제거한 상태로 화면에 보이게 함

두 가지가 비슷한 듯 보이지만 완전히 다른 별개의 영역이며, 둘 다 처리해야지만 사용자가 느끼기엔 버그 없이 동작하는 것처럼 보입니다.

**Comment by keedi** [comment]
구현 및 실서버에 반영 완료했습니다. 이슈 닫습니다.

**Comment by keedi** [comment]
본 기능은 반드시 사용자 정보 페이지에서 새로 고침을 한(여러번) 후에 확인해야 합니다. 브라우저의 캐시 정책에 따라 새로 고침을 하지 않을 경우 기능 확인이 어려울 수도 있습니다.

**Comment by 10001if** [comment]
네~ 확인 완료하였습니다.
