### ISSUE TITLE
신체 치수 예측 화면 하단에 동일한 키/몸무게로 대여되었던 의류의 코드/사이즈 나타내기 

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#562]
신체치수 예측화면은 현재 열린옷장의 누적데이터와 바디랩스의 데이터를 보여주고 있습니다.

온라인 대여를 하다보면 가장 많이 느끼는 부분인데. 

1. 우선 주문자의 신체 사이즈를 정확히 아는 것이 가장 중요합니다.

2. 하지만 궁극적으로는 어떤 옷을 입어야 하는지를 알아야 합니다.

따라서 바디랩스 데이터 하단에 

검색한 키 몸무게로 대여한 다른사람의 대여기록이 있는 경우

베스트핏이었던 대상 의류의 자켓/(바지or스커트)의 코드와 사이즈를 알고 싶습니다.

ex) J0P3/P23R 자켓 가슴/윗배/중동/팔길이 바지 허리/엉덩이/허벅지/다리길이

~~없는 경우에는 열린옷장 데이터와 같이 몸무게 +_1kg 키 +_1cm 단위로 나머지 8개의 자료의 의류정보를 확인하고 싶습니다.~~

**Comment by aanoaa** [comment]
키와 몸무게로 bestfit 이었던 의류가 없는 경우도 있으니까, DB 처럼 키와
몸무게를 +-1 해서 9개의 표로 보여주고 자세한건 클릭해서 상세화면을
구성하면 좋겠습니다.

**Comment by keedi** [comment]
bestfit 뿐만 아니라 +/-1 정보도 같이 보고 싶은 것입니다. bestfit이 없을 경우만 보려는 것이 아니라고 합니다.

**Comment by keedi** [comment]
172 / 72 의 경우 172 / 72 의 bestfit 의 결과만 원하는 줄 알았는데 그게 아니라 171/71, 171/72, 171/73, 172/71, 172/72, 172/73, 173/71, 173/72, 173/73 모두의 bestfit 결과도 필요하다고 합니다.

**Comment by keedi** [comment]
더 정확하게 정리합니다.

bestfit이 아닌 경우의 의류 대여 내역은 필요 없다고 합니다. 즉 9개의 영역에 대해 bestfit 대여 내역을 원하는 상황입니다.

**Comment by keedi** [comment]
각 9개의 영역 치수 별로 클릭을 해서 상세 화면을 보기 보다는 한번에 쭉 나열하기를 원한다고 합니다.

**Comment by keedi** [comment]
한번에 나열할때의 조건은 다음과 같습니다. 172/72를 기준으로 제시합니다.


- 172/72 - 하단에 표시를 하지만 굳이 한번 더 표시를 함. 다른 색상을 표시해서 인지 가능하도록 함
- 171/71
- 171/72
- 171/73
- 172/71
- 172/72 -  다른 색상을 표시해서 인지 가능하도록 함
- 172/73
- 173/71
- 173/72
- 173/73

**Comment by keedi** [comment]
비교적 다른 이슈들에 비해 중요도가 높은 이슈라 이번 마일스톤에서 진행합니다.

**Comment by keedi** [comment]
진행합니다.

**Comment by keedi** [comment]
구현 완료한 화면은 다음과 같습니다.

![screenshot-monster silex kr 10301 2015-11-03 17-26-19](https://cloud.githubusercontent.com/assets/138451/10903790/ca5d9d62-8250-11e5-8e9c-d6e61c98e9b4.png)

**Comment by keedi** [comment]
화면을 보면 알 수 있지만 정확하게 172/ᅟᅟ72 검색 인자에 일치하는 베스트핏 주문서 정보는 **어울렸던 의류 정보**라는 섹션에 보이게 하고 172/72 +/-1 에 해당하는 베스트핏 주문서 정보는 **어울렸던 유사 의류 정보** 섹션에 보이게 했습니다.

**Comment by keedi** [comment]
구현 및 실버서에 적용 완료했습니다. 이슈 닫습니다.

**Comment by 10001if** [comment]
확인 완료하였습니다.
