### ISSUE TITLE
부분반납시 하위 주문서에서 대여금액이 0원임에도 현금, 카드등 결제를 입력하지 않으면 주문확정을 할 수 없음

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#563]
부분 반납시 하위 주문서에서 주문확정을 해야 다시 대여 중인 상태로 변경되는데 이때 대여금액이 0원일 때도 현금, 카드 등의 버튼을 입력해야 확정이 됩니다. 0원일 때에는 따로 입력하지 않고 확정을 할 수 있다면 좋겠습니다.

**Comment by aanoaa** [comment]
절차가 어떻게 되나요?

- 대여
- 부분반납
  - 이때 하위주문서가 생성됨?
  - 하위주문서의 주문확정?
- 전체반납

**Comment by 10001if** [comment]
- 대여
- 부분반납
  - 이때 하위주문서가 생성됨
  - 하위주문서의 주문확정 -> 이때 대여금액이 0원임에도 주문확정을 바로 누르면 결제수단 등록을 하지 않았다는 메세지가 뜹니다. 이 부분의 수정을 요청드립니다. ^^
- 전체반납

**Comment by 10001if** [comment]
잘 해주셨을 것 같은데.. 실제로 써보고 이상이 있다 싶으면 다시 이슈를 열겠습니다!
