### ISSUE TITLE
신체치수 예측 화면에서 특정 키/몸무게로 확인한 열린옷장의 누적 데이터를 개별로 볼 수 있도록 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#565]
![2015-09-23 5 55 29](https://cloud.githubusercontent.com/assets/4696328/10041149/ff12b5fa-621c-11e5-8795-24617cd150fd.png)

7명의 평균 데이터만을 보고 있으므로 특정 인원의 사이즈가 평균과 차이가 얼마나 나는지를 확인할 수 없습니다. 차이의 확인을 위해 개별 데이터를 전부 보기 위해 다음과 같이 요청드립니다.

7명의 기록을 클릭하면 새 창이 떠서 7명의 기록이 나열된 정보를 확인 할 수 있도록 요청드립니다.

**Comment by aanoaa** [comment]
#694 ~ #700 까지에서 잘못기입된 데이터를 제거하고 있기 때문에 닫습니다.
