### ISSUE TITLE
신체치수 측정시 누적 평균데이터와의 차이를 알 수 있도록 기능 추가

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#566]
![2015-09-23 6 05 27](https://cloud.githubusercontent.com/assets/4696328/10041306/580f9f78-621e-11e5-8a10-2dd5d7adf93f.png)

사이즈를 입력 할 때 전체 누적 평균 데이터와의 차이를 실시간으로 알고 싶습니다.

그 이유는 다음과 같습니다.

1. 사이즈의 평균치와 비교하며 차이가 생각보다 클 경우 치수 측정을 다시 할 수 있도록 하여 사이즈의 정확성을 더 확보하려 합니다. 
2. 사이즈의 평균치와 비교하며 개별 사이즈와의 차이 정도를 개괄적으로 체감하려 합니다.

**Comment by 10001if** [comment]
신발크기는 차이를 알 필요성이 없을 것 같아 - 처리 하였습니다. (다만, 평균 값은 알고 싶습니다)

**Comment by keedi** [comment]
비교적 다른 이슈들에 비해 중요도가 높은 이슈라 이번 마일스톤에서 진행합니다.

**Comment by keedi** [comment]
진행합니다.

**Comment by keedi** [comment]
처리한 내역은 다음과 같습니다.

- 사용자 정보 페이지에서 해당 사용자의 성별, 키, 몸무게 값을 기준으로 각 신체 치수 항목의 평균 및 편차를 치수 옆에 표시하도록 함
- 사용자 정보 페이지에서 사용자의 성별, 키, 몸무게 값을 수정할 때 마다 즉석에서 서버로 평균 및 편차 값을 요청해서 가장 최신의 값으로 갱신하도록 함

**Comment by keedi** [comment]
구현한 화면은 다음과 같습니다.

![screenshot-monster silex kr 10301 2015-11-09 12-34-26](https://cloud.githubusercontent.com/assets/138451/11025440/59c1ae8a-86de-11e5-97ce-87fcec72aae6.png)

**Comment by keedi** [comment]
구현 및 실서버에 반영 완료했습니다. 이슈 닫습니다.

**Comment by keedi** [comment]
본 기능은 반드시 사용자 정보 페이지에서 새로 고침을 한(여러번) 후에 확인해야 합니다. 브라우저의 캐시 정책에 따라 새로 고침을 하지 않을 경우 기능 확인이 어려울 수도 있습니다.

**Comment by 10001if** [comment]
확인 완료하였습니다.

**Comment by 10001if** [comment]
이 기능 덕분에 사이즈 측정이 훨신 정확해 질 것 같습니다~!
