### ISSUE TITLE
SMS 가 보내지지 않을때가 있음

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#568]
로그를 확인해서 실패사유를 확인해보고,
일별 실패율을 확인해봐야 합니다.

**Comment by keedi** [comment]
실패한 건의 정보를 확인한 후 데이터베이스의 `sms` 테이블의 `detail` 컬럼을 참조하면 APIStore의 응답 값을 확인할 수 있습니다. 여기의 cmid값을 확인해서 문제없이 전송했는데도 정말 전송되지 않았다면 APIStore 측에 문의해야할 것 같습니다. 물론 `detail` 쪽을 확인했는데 전송이 실패했을 수도 있습니다. 경우를 확인해야 합니다.

**Comment by keedi** [comment]
cmid를 이용해서 apistore 관련 정보를 확인하려면 다음 링크를 확인해주세요.

http://www.apistore.co.kr/api/apiView.do?service_seq=151&api_group_seq=18&api_info_seq=213

**Comment by 10001if** [comment]
권일광 01035849629
예약 확인 문자 수신 안되셨다고 합니다

**Comment by 10001if** [comment]
이현희 01050141741
예약시 인증문자 발송이 안되었습니다.

**Comment by 10001if** [comment]
최희진 01047945728
박하상 01090413972
서은재 01090129627
3분은 공통적으로 인증번호는 받았으나 인증번호를 입력하니 "인증번호 오류"라는 메세지를 받았다고 합니다.

**Comment by 10001if** [comment]
양세훈 / 01089401809 / 인증번호 안옴
한승현 / 01055249028 / 인증번호 문자 X
정은선 / 01098040406 / 인증번호 요청 시 계속 새로고침현상
이시윤 / 01040806720 / 예약확인 문자 X
정세영 / 01096163070 / 인증번호 요청 시 계속 새로고침현상
이금재 / 01037108219 / 인증번호 요청 시 계속 새로고침현상 (3회 정도 재시도한 후 예약 진행하였으나 예약이 되지 않았다고 함. > 직원예약으로 신청해드렸습니다.) 12:31 PM
김은지 / 01057288370 / 예약확인 문자 X (LG유플러스)
임정민 / 01066213140 / 인증번호 문자 X 
정준 / 01068059575 / 예약확인 문자 X (LG유플러스)

**Comment by 10001if** [comment]
박기락 / 01047254527 / 인증번호 문자 X

**Comment by 10001if** [comment]
박가람 / 01065981208 / 예약문자X (LG)
한상헌 / 01062255284 / 인증번호 문자 X (현장에서 예약시도 중에 인증번호 문자가 안와서 직원예약으로 하였습니다. 통신사는 KT입니다.) 
이상인 / 01022262840 /인증번호는 받고 예약확인 문자 못받으심

**Comment by 10001if** [comment]
이름/전화번호를 기입하는 기존의 방식은 실효성을 거두기가 어려워보입니다. 따라서 @keedi 제안해 주신 것처럼 발송이 주로 안되는 통신사가 LG 유플러스입니다. 회사에 확인하여 금지어나 발송금지로 지정되는 상황을 확인해보도록 하겠습니다.

**Comment by aanoaa** [comment]
관련자와 직접 연락을 시도했지만 답변이 늦어지고 있습니다.
후에 다시 이슈화하도록 하겠습니다.
