### ISSUE TITLE
택배회사와 운송장번호를 대여자가 직접 입력할 수 있게 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#569]
현재는 문자로 전송하여 옷장지기가 입력하는 방식입니다. 하지만 대여자분들이 문자로만 보내주시지 않고 옐로아이디, 메일 등으로 나누어 보내주시고 계셔서 이를 수집하는데 어려움을 겪고 있습니다. 그리고 이를 다시 재입력하는 절차가 생각보다 어렵다고 합니다. 따라서 반납과 연장의 의무를 지니고 있는 대여자 스스로 입력을 할 수 있도록 하는 과정의 추가를 요청드립니다. 로그인시 인증번호는 한번만 발송하여 처리하고 그 이외에는 비밀번호로 로그인 할 수 있도록 하였으면 합니다.

**Comment by keedi** [comment]
로그인과 관련된 이슈입니다. 로그인 및 세션 처리에 맞게 프로세스가 변경되기 전까지는 진행할 수 없습니다.

**Comment by MoDoLEE** [comment]
#609 이슈와 중복되는 것 같습니다.

**Comment by 10001if** [comment]
@MoDoLEE #609 이슈와 다르게 로그인 후 적용되는 부분인 것 같아서 이슈 남겨두었습니다. @keedi 보시고 동일한 이슈라고 판단되시면 닫아주셔도 될 것 같습니다. ^^
