### ISSUE TITLE
대여 메세지 입력할 수 있는 UI가 필요함

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#570]
대여 메세지를 입력할 수 있는 UI를 만들어 주시면 저희가 스캔된 자료를 텍스트로 옮겨 입력하도록 하겠습니다.

**Comment by keedi** [comment]
진행합니다.

**Comment by keedi** [comment]
DB 스키마를 수정해야 하는 일이라 #448 항목과 함께 동시에 진행합니다.

**Comment by keedi** [comment]
확인했는데 이미 주문서 테이블 안에 대여 메시지를 입력할 수 있는 컬럼이 존재합니다. 항목은 `order.message` 입니다. 따라서 DB 스키마 수정없이 바로 진행하면 됩니다.

**Comment by keedi** [comment]
이미 올해 2월 8일, #347 이슈에서 처리한 내용입니다.
흠... 지금까지 안쓰고 계셨다는 것과 그래서 저도 잊어먹고 있었다는 사실이 놀랍군요;;;

**Comment by keedi** [comment]
이슈 닫습니다.

**Comment by 10001if** [comment]
확인하였습니다.
