### ISSUE TITLE
사용자 정보와 의류 정보에 목 둘레 항목 추가

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#577]
사용자 정보화면(~/user/~)과 의류 사이즈 항목에 목둘레 추가를 요청드리고자 합니다.

목둘레를 알 수 없어 셔츠를 대여할 때 여러번 의류를 제공해야 하는 문제가 있기 때문입니다.

![2015-10-05 6 25 22](https://cloud.githubusercontent.com/assets/4696328/10277220/7f5b3a22-6b8f-11e5-9151-fe4860cc7f43.png)
위치는 키/몸무게 바로 아래이며

![2015-10-05 6 27 43](https://cloud.githubusercontent.com/assets/4696328/10277230/8a2b7336-6b8f-11e5-9578-8fc28e0d02ea.png)
~preparation 화면에서는 발사이즈, 키/몸무게 왼쪽에 목둘레가 표시되었으면 합니다.

**Comment by 10001if** [comment]
![2015-10-05 6 34 45](https://cloud.githubusercontent.com/assets/4696328/10277331/44cbadb4-6b90-11e5-948e-d6f70786c16d.png)
리고 새 옷 등록시 셔츠의 경우에는 목둘레 항목을 추가로 입력할 수 있도록 요청드립니다.

**Comment by keedi** [comment]
opencloset/OpenCloset-Schema#32 이슈를 처리 했으므로 `OpenCloset::Schema` 0.016 버전을 기준으로 작업 진행하도록 합니다.

**Comment by keedi** [comment]
주문서에서도 빌렸던 바지 길이 정보를 저장해야 합니다. 주문 체결될때 신체 사이즈 복제하는 시점에 적용해주어야 합니다.

**Comment by keedi** [comment]
기존 데이터베이스에는 다음 질의를 적용합니다.

```sql
ALTER TABLE `user_info` ADD COLUMN `neck` INT NULL DEFAULT NULL AFTER `weight`;
ALTER TABLE `clothes`   ADD COLUMN `neck` INT NULL DEFAULT 0    AFTER `code`;
ALTER TABLE `order`     ADD COLUMN `neck` INT NULL DEFAULT NULL AFTER `weight`;
```

**Comment by keedi** [comment]
현재 실 서버에는 일단 스키마에는 이미 상기 질의를 적용시켜두었습니다.

**Comment by keedi** [comment]
작업 완료했으며 배포 완료했습니다. 이슈 닫습니다.

**Comment by 10001if** [comment]
확인완료하였습니다. 감사합니다.

**Comment by aanoaa** [comment]
사용자의 목둘레를 입력하면 가슴둘레가 입력됩니다.

**Comment by keedi** [comment]
@10001if 

버그로 인해 사용자 프로필 페이지(신체 치수를 입력하는 곳)에서 목 둘레를 입력하면 목 둘레가 아닌 가슴 둘레가 입력되었었습니다. 번거로우시겠지만 10월 20일부터 10월 28일 까지의 주문서에 있는 사용자 정보를 확인해보셔야 할 것 같습니다.

다만 목둘레부터 재서 입력했다면 결국 가슴둘레를 입력하면서 덮어써져서 목 둘레만 없고 가슴 둘레는 제대로 살아 있지 않을까 싶지만 일단 확인 후 조치 부탁드립니다. 가슴 둘레가 멀쩡하다면 목 둘레만 0으로 처리하시면 되고 가슴 둘레가 이상하다면 그 값을 목 둘레로 넣고 가슴 둘레는 0으로 처리하면 됩니다.

**Comment by keedi** [comment]
일단 배포 완료 했습니다.

**Comment by 10001if** [comment]
@keedi 목둘레를 넣으면 가슴둘레가 달라진다는 사실은 바로 확인하였었습니다. 모니터에서 다르게 표시되는 관계로 완전히 정상화되면 하려고 목둘레를 입력하지 않고 있었습니다. 혹시 몰라 20일부터 다시 확인해보았는데, 목둘레는 입력되어 있지 않습니다.

**Comment by keedi** [comment]
@10001if 수정해서 배포 완료했는데 정상 동작하는지 확인하셨는지요? 피드백 부탁드립니다.

**Comment by keedi** [comment]
잘 동작한다고 피드백 받았습니다. 이슈 완전히 닫습니다.
