### ISSUE TITLE
통계-수량-의류 종류에서 수량 숫자를 누르면 해당 조건의 의류 목록을 볼 수 있도록 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#578]
통계수량 화면에서 의류 종류를 틀릭하면 사이즈별로 누적된 숫자가 나옵니다.
이때 이 숫자를 누르면 의류화면에서 동 사이즈만 검색된 결과를 화면에서 보고 싶습니다.

이는 잘못 입력된 숫자를 찾아 다시 바로잡고자 함입니다.

**Comment by keedi** [comment]
진행합니다.

**Comment by keedi** [comment]
의류 목록을 보여주는 `/clothes` 페이지로 연결을 시켜주는 것이 가장 간결한 해결책일 것 같습니다. 해당 페이지가 검색 인자를 받아들일 수 있도록 구현합니다.

**Comment by keedi** [comment]
지체되었었네요. 다시 진행합니다.

**Comment by keedi** [comment]
의류 목록 페이지에서 이제 다음 항목을 검색 질의로 이용해서 목록을 필터링할 수 있습니다.

- arm
- belly
- bust
- category
- color
- gender
- hip
- length
- neck
- thigh
- topbelly
- waist

**Comment by keedi** [comment]
구현 완료한 화면입니다.

![screenshot-monster silex kr 10301 2015-11-02 20-44-45](https://cloud.githubusercontent.com/assets/138451/10881142/c2bd779c-81a3-11e5-914b-289b38e6c5a6.png)

**Comment by keedi** [comment]
waist가 82면서 대여중인 남자 바지를 검색하는 질의는 다음과 같습니다.

`/clothes?category=pants&gender=male&waist=82&status=2`

**Comment by keedi** [comment]
구현 완료 및 서버에 배포 완료했습니다.
이슈 닫습니다.

**Comment by 10001if** [comment]
확인 완료하였습니다.
