### ISSUE TITLE
의류정보 화면 중 개별 어울림정보의 주문서 번호를 확인할 수 있고 이를 클릭하면 해당 주문서로 이동하도록 함 

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#579]
![2015-10-07 12 11 31](https://cloud.githubusercontent.com/assets/4696328/10328265/6c54c16e-6ced-11e5-9a80-5f5b88824298.png)

베스트 핏 자료를 보다보니 키/몸무게가 다른 데이터와 상대적으로 큰 차이를 보이는 자료들이 눈에 띄었습니다. 
이런 자료들의 경우 데이터가 맞는지 확인하는 작업이 진행되면 더 좋을 것 같은데요. 현재는 해당 주문서 번호를 알 수가 없습니다. 

키/몸무게 왼쪽에(제일 첫번째) 주문서 번호를 삽입해 주시면 해당 주문서로 가서 키/몸무게가 정확한지(과거 데이터는 저희가 직접 측정한 것이 아니기 때문에  조금 부정확할 수 있습니다) 확인 할 수 있을 것 같습니다. 빨리 진행해야 하는 급한 이슈는 아닙니다.

**Comment by keedi** [comment]
진행합니다.

**Comment by keedi** [comment]
구현 완료한 화면은 다음과 같습니다.

![screenshot-localhost 8001 2015-12-10 22-50-07](https://cloud.githubusercontent.com/assets/138451/11717019/ed633738-9f90-11e5-9525-5a5e2b104d55.png)

**Comment by keedi** [comment]
구현 및 서버에 배포 완료했습니다.
이슈 닫습니다. :-)

**Comment by 10001if** [comment]
확인 완료하였습니다.
