### ISSUE TITLE
신체치수 예측화면에서 여성의 경우 무릎길이가 표시되도록 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#585]
~guess  화면에서 여성으로 검색하면 무릎길이가 표시되지 않습니다.
무릎길이가 표시될 수 있도록 요청드립니다.

**Comment by keedi** [comment]
구현 완료한 화면은 다음과 같습니다.

![screenshot-monster silex kr 10301 2015-12-14 19-06-38](https://cloud.githubusercontent.com/assets/138451/11778142/fae923ce-a295-11e5-907e-954c6c8a2ad1.png)

**Comment by keedi** [comment]
**어울렸던 의류 정보** 및 **어울렸던 유사 의류 정보** 페이지의 경우 의류의 정보를 보여주는데 의류 정보에는 무릎 길이라는 것이 존재하지 않기 때문에 따로 보여줄수가 없습니다. 사용자 신체 치수에 한해 무릎 길이를 보여주도록 했습니다.

**Comment by keedi** [comment]
구현 및 실 서버에 배포 완료되었습니다.

이슈 닫습니다.

**Comment by 10001if** [comment]
![2015-12-16 9 39 30](https://cloud.githubusercontent.com/assets/4696328/11830952/4c74d230-a3ed-11e5-8c86-4b7e744e0316.png)
@keedi  데이터를 보니 무릎과 허리길이가 서로 바뀐 것 같은데 확인 좀 부탁드려도 될까요? ^^

**Comment by keedi** [comment]
수정 완료했습니다. 다시 꼼꼼히 확인 부탁드려요~ :-)

**Comment by 10001if** [comment]
확인 완료하였습니다. 감사합니다. ^^
