### ISSUE TITLE
바코드 발행 오류

### ISSUE THREAD

**Issue by yongbin** [opencloset/opencloset#588]
#581 이슈를 진행하는 과정에서 타이와 바지등에서 광범위하게 바코드의 발행오류가 발생함을 확인했습니다. 이 이슈의 원인을 파악해서 해결해야합니다.

**Comment by yongbin** [comment]
@10001if  대표님과 면담으로 파악한 대략의 히스토리는 아래와 같습니다.

 * 2014년 11월 24일 대량으로 바코드를 업체에 위임해서 출력했으며 수량이 많지않은 일부 품목은 이후 약 1년간 (2015년 10월 말) 이때 생성한 바코드만을 사용하고 있었음

 * 당시 업체에 생성을 요청하는 엑셀자료를 만들어 드린 뒤, 한대표님께 보낸 메일은 아래와 같습니다.

```
from:	Yongbin Yu <yongbin.yu@gmail.com>
to:	"Han Manil (theopencloset)" <10001if@theopencloset.net>
cc:	Yongbin Yu <yongbin.yu@silex.kr>
date:	Mon, Nov 24, 2014 at 1:09 PM
subject:	Re: 바코드 마지막 정보입니다.
mailed-by:	gmail.com
:	Important according to our magic sauce.

대표님 안녕하세요? 유용빈입니다.

요청하신 코드 보내드립니다.(첨부파일 #1) 그리고 이번 코드까지 적용된
마지막 코드번호는 아래와 같습니다.

A06X
B09P
C022
E06X
H00O
J103
K0B3
O022
P0RR
S0I1
T0IQ
W01D

다음 요청때 참고해 주시면 됩니다.

감사합니다.

유용빈
```

이후 모든 요청은 Github 이슈를 통해 진행했으며 진행된 사항은 다음과 같습니다. (시간순)

 * ( #454 ) 셔츠 500벌 바코드 생성
 * ( #463 ) 구두 50개의 바코드 생성
 * ( #469 ) 구두 300개, 벨트 300개 추가 코드 생성 
 * ( #475 ) 셔츠 500개 바코드 생성 
 * ( #549 ) 스커트 500벌 바코드 생성
 * ( #581 ) 넥타이 코드 300개 및 바지코드 100개 신규 발급

위 이슈들 중 현재까지 중복이 확인된 이슈는 #581 하나뿐입니다. 본 이슈에서는 시간의 역순으로 기존 이슈들의 작업에도 오류가 없었는지 여부를 확인해 보도록 하겠습니다.

**Comment by yongbin** [comment]
첫번째 혼란은 https://github.com/opencloset/opencloset/issues/39#issuecomment-64150345 에서 부터 시작됩니다.  확인결과 #454 에서 셔츠 코드의 중복문제가 발생해서 **DB에서 임의의 코드를 차장서 우회하는 방식의 처리** 를 한 기록이 있는데 ( https://github.com/opencloset/opencloset/issues/454#issuecomment-93882615 ) 그 오류가 발생한 원인은 https://github.com/opencloset/opencloset/issues/39#issuecomment-68031065 에서 찾아냈습니다. 이 이슈를 보면 @10001if 님이 보낸 요청 메일에는 셔츠의 last코드가 `S0I1`으로 맞게 되어있는 반면, 제가 작업한 결과로 드린 코드를 보면 그 시점 요청에 셔츠가 없었음에도 불구하고 셔츠의 last코드가 `S0F9` 으로 변경되어 있음을 확인할 수 있습니다.

셔츠와 관련해서 정리하면 다음과 같습니다. https://github.com/opencloset/opencloset/issues/39#issuecomment-68031065 에서 제가 실수를 해서 #454 에서 중복이슈가 발생을 했고 당시 발생했던 이슈를 우회해서 시작코드는 `S0SL`으로 고정됨 이때 생성후 고정된 last 코드 `S16H`은 이후 #475 를 처리하는데도 잘 사용되었기 때문에 이후에 문제가 발생하지 않음 셔츠의 현재 last 코드는 `S1KD`

**Comment by yongbin** [comment]
구두도 잘못 처리되어있습니다. 11월 24일 기준 last 코드는 `A06X` 인데, https://github.com/opencloset/opencloset/issues/463#issuecomment-101905641 을 보면 last 코드를 `A0KT`로 잘못 사용되어있는것을 볼 수 있습니다. 중간에 메일등을 통한 요청이 있었는지는 확인할 수 없지만 github 이슈 기준으로 봤을때는 잘못된 처리입니다. 다만 `A0KT`는 `A06X` 보다 이후 코드이기때문에 중복등의 문제는 발생하지 않았고 이때 생성된 last 코드 `A0M7`은 문제 없이 #469 로 전달되어서 처리되었기 때문에 후속적인 문제가 발생하지 않았습니다. 현재 구두의 last 코드는 `A0UJ`입니다.

**Comment by yongbin** [comment]
벨트의 경우 초기 시작코드가 `E0I1`으로 지정되어야 하지만, https://github.com/opencloset/opencloset/issues/469#issue-82399464 을 보면 `E06X` 으로 잘못 지정되어있습니다. 하지만 실행코드인 다음 코멘트인 https://github.com/opencloset/opencloset/issues/469#issuecomment-106783564 을 보면 정상적으로 `E0I1`이 사용되었기 때문에 결과적으로 맞는 코드가 생성되어서 문제가 발생하지 않았습니다. 벨트의 last 코드는 `E0QD` 입니다.

**Comment by yongbin** [comment]
스커트의 경우 다행이도 작년 11월 24일에 문제가 없이 처리가 된 코드입니다. 당초 코드 `K0B3`로 부터 시작해서 #549 에서 500개 생성을 진행했고 이 과정에서 바코드 이상이 발견되었지만, 당시 열린옷장 직원의 실수로 판명(https://github.com/opencloset/opencloset/issues/549#issuecomment-141784851) 되어 정상종료 되었습니다. 스커트의 바른 last 코드는 `K0OZ` 입니다.

**Comment by yongbin** [comment]
바지도 잘못되었습니다. 올바른 last 코드는 `P0RR` 임에도 불구하고 #581 에서는 `P0JF` 으로 잘못된 코드로 부터 생성합니다. 위에 언급한 `셔츠`와 정확하게 같은 원인떄문에 오류가 발생한 케이스입니다. #581 에서는 DB에 마지막 코드를 확인하는 방식으로 우회해서 잘못된 last 코드 `P0I5` 으로 부터 생성한 코드가 존재하지만 ** 이 코드는 사용하면 안됩니다. ** 따라서 #589 에서 사용해야할 올바른 last 코드는 `P0RR` 입니다.

**Comment by yongbin** [comment]
작년 11월 24일 코드 
```
A06X
B09P
C022
E06X
H00O
J103
K0B3
O022
P0RR
S0I1
T0IQ
W01D
```

----

#581 을 시작하던 시점의 

```
A0UJ
B06X
C022
E0QD
H00O
J0RR
K0B3
O022
P0JF
S1KD
T0D6
W01D
```

**Comment by yongbin** [comment]
위에 정리된 내용을 바탕으로 최종적으로 정리한 **바른** last 코드는 아래와 같습니다.

```
A0UJ
B09P
C022
E0QD
H00O
J103
K0B3
O022
P0RR
S1KD
T0ZE
W01D
```
다음과 같은 방식으로 처리합니다. 

 * 기본적으로 추적된 히스토리가 없다면 2014년 11월 24일 자료가 맞다고 봅니다. 
 * 추적된 히스토리가 있는 경우 진행된 모든 내용을 고려해서 맞는 last 코드를 사용합니다. (셔츠,구두,벨트 등)
 * 두 코드가 동일한 경우 채택합니다.

**Comment by yongbin** [comment]
후속이슈 #589 와 #590 을 모두다 위에서 정리한 last 코드를 기준으로 진행하도록 하겠습니다. 이번 확인에서 기존 바코드작업에 헛점이 많았던 점을 거울삼아 앞으로 바코드 작업을 진행할때 좀 더 이슈 기록과 작업을 꼼꼼하게 진행하도록 하겠습니다.

**Comment by yongbin** [comment]
> 바지도 잘못되었습니다. 올바른 last 코드는 P0RR 임에도 불구하고 #581 에서는 P0JF 으로 잘못된 코드로 부터 생성합니다. 위에 언급한 셔츠와 정확하게 같은 원인떄문에 오류가 발생한 케이스입니다. #581 에서는 DB에 마지막 코드를 확인하는 방식으로 우회해서 잘못된 last 코드 P0I5 으로 부터 생성한 코드가 존재하지만 이 코드는 사용하면 안됩니다. 따라서 #589 에서 사용해야할 올바른 last 코드는 P0RR 입니다.
> 
> 하지만 DB를 확인해본 결과 현재 DB에 저장된 가장 최근에 코드가 P1B7 입니다. 따라서 바지의 경우는 github에 추적되지 않은 경로로 코드발급이 이루어진적이 있는것으로 보입니다. 현재 바지코드가 다 떨어져서 요청을 받은 상황이므로 DB를 기준으로 last 코드를 결정한다면 P1C0 입니다. (P1B8 ~ P1BZ는 만약을 위해 비워둡니다)

@keedi 님의 도움으로 `P0RR`의 행방을 찾았습니다. https://github.com/opencloset/opencloset/issues/39#issuecomment-64180788 어제 제가 확인했던 #39 의 코드가 12월 24일날 마지막으로 반영된 코드인점을 감안하면 이 부분을 확인하지 못한것은 역시 저의 실수입니다. 하지만 기록상의 부족으로 왜 11월 24일의 코드와 12월 24일의 코드가 서로 상이 한지, 또 12월 24일의 코드에서도 한만일 대표님이 보낸코드와 제가 작성한 코드가 왜 다른지를 확인할 수 있는 방법은 현재로서는 없습니다. 

다만 `바지`의 경우 보수적으로 `P1C0`을 새로운 last 코드로 사용해서 100개의 코드를 만들었지만 과거 이력인 `P1B7`의 근거를 찾았기 때문에 `P1B8` 부터 `P1C0` 코드를 버릴 필요가 없어졌습니다. 따라서 #589 이슈에 새로 생성한 추가 29개 코드를 더 발행했습니다. https://github.com/opencloset/opencloset/issues/589#issuecomment-153574065

**Comment by yongbin** [comment]
https://github.com/opencloset/opencloset/issues/39#issuecomment-64180788 을 확인한 뒤 정리했던 최종 코드를 다시한번 비교해서 확인했습니다. DB기준으로는 이상이 없지만 이미 발급된 코드가 존재할 수 있기때문에 최종적으로 다음과 같이 변경하는것이 타당합니다.

```
A0UJ
B09P -> B0F9
C022
E0QD
H00O
J103 -> J1JJ
K0B3
O022
P1C0 -> P1B7
S1KD
T0ZE
W01D
```

변경이 반영된 last 코드는 다음과 같습니다.

```
A0UJ
B0F9
C022
E0QD
H00O
J1JJ
K0B3
O022
P1B7
S1KD
T0ZE
W01D
```

**Comment by yongbin** [comment]
위 변경내용을 #589, #590 두 이슈에도 소급해서 적용해야합니다.

**Comment by yongbin** [comment]
앞으로 바코드와 생성과 관련해서 동일한 문제가 발생하지 않도록 별도 위키페이지를 만들어서 좀 더 이력을 적극적으로 관리하기로 했습니다.

https://github.com/opencloset/opencloset/wiki/barcode

**Comment by keedi** [comment]
> yongbin commented 2 hours ago
> 
> 위 변경내용을 #589, #590 두 이슈에도 소급해서 적용해야합니다.

결과 알려주시고 적용 완료됐다면 이슈 닫으면 될 것 같습니다.

**Comment by yongbin** [comment]
> 위 변경내용을 #589, #590 두 이슈에도 소급해서 적용해야합니다.

소급 적용 완료했습니다. https://github.com/opencloset/opencloset/issues/589#issuecomment-153585428 , https://github.com/opencloset/opencloset/issues/590#issuecomment-153585718

**Comment by yongbin** [comment]
발급요청이 있었던 사항들을 처리했고 기존에 문제가 발생하던 중복문제의 원인도 규명했으며 재발방지을 위한 대책도 수립했습니다. 이슈를 종결하도록 하겠습니다.
