### ISSUE TITLE
바지 바코드 129개 생성

### ISSUE THREAD

**Issue by yongbin** [opencloset/opencloset#589]
#581 에서 분리한 이슈이며 #588 의 자식이슈입니다. 앞으로 이슈의 추적을 용이하게 하기 위해서 바코드 생성의 요청은 각각의 분리된 이슈에서 요청하고 처리하도록 합니다.

**Comment by yongbin** [comment]
#588 에서 제공받은 last code 는 아래와 같습니다.

```
A0UJ
B09P
C022
E0QD
H00O
J103
K0B3
O022
P1C0
S1KD
T0ZE
W01D
```

**Comment by yongbin** [comment]
`P1C0` 으로부터 100개의 바지를 생성했으며 생성후 마지막 코드는 `P1ES` 입니다. 

## 새로 생성된 바지 코드

```
P1C1
P1C2
P1C3
P1C4
P1C5
P1C6
P1C7
P1C8
P1C9
P1CA
P1CB
P1CC
P1CD
P1CE
P1CF
P1CG
P1CH
P1CI
P1CJ
P1CK
P1CL
P1CM
P1CN
P1CO
P1CP
P1CQ
P1CR
P1CS
P1CT
P1CU
P1CV
P1CW
P1CX
P1CY
P1CZ
P1D0
P1D1
P1D2
P1D3
P1D4
P1D5
P1D6
P1D7
P1D8
P1D9
P1DA
P1DB
P1DC
P1DD
P1DE
P1DF
P1DG
P1DH
P1DI
P1DJ
P1DK
P1DL
P1DM
P1DN
P1DO
P1DP
P1DQ
P1DR
P1DS
P1DT
P1DU
P1DV
P1DW
P1DX
P1DY
P1DZ
P1E0
P1E1
P1E2
P1E3
P1E4
P1E5
P1E6
P1E7
P1E8
P1E9
P1EA
P1EB
P1EC
P1ED
P1EE
P1EF
P1EG
P1EH
P1EI
P1EJ
P1EK
P1EL
P1EM
P1EN
P1EO
P1EP
P1EQ
P1ER
P1ES
```

## last code

```
[ last code ]
A0UJ
B09P
C022
E0QD
H00O
J103
K0B3
O022
P1ES
S1KD
T0ZE
W01D
```

**Comment by yongbin** [comment]
@10001if  대표님 확인 부탁드리고 이상없으면 닫아주세요

**Comment by yongbin** [comment]
@keedi  님과 추가적으로 #588 이슈와 #39 를 리뷰해본 결과 기존에 기록을 유실한 줄 알았던 바지의 last 코드를 에서 확인할 수 있었습니다. 따라서 `P1B7` 부터 `P1C0` 사이의 29 개 코드를 버릴 이유가 없어졌습니다.

@10001if  대표님 아래의 코드까지 사용해주시면 됩니다. 

```
P1B8
P1B9
P1BA
P1BB
P1BC
P1BD
P1BE
P1BF
P1BG
P1BH
P1BI
P1BJ
P1BK
P1BL
P1BM
P1BN
P1BO
P1BP
P1BQ
P1BR
P1BS
P1BT
P1BU
P1BV
P1BW
P1BX
P1BY
P1BZ
P1C0
```

이 사항은 last 코드에는 영향을 끼치지 않습니다.

**Comment by 10001if** [comment]
바지 바코드 129개 확인완료하였습니다.

**Comment by yongbin** [comment]
https://github.com/opencloset/opencloset/issues/588#issuecomment-153584931 으로 인해서 last 코드에 변경이 발생했습니다

```
A0UJ
B0F9
C022
E0QD
H00O
J1JJ
K0B3
O022
P1ES
S1KD
T0ZE
W01D
```

**Comment by yongbin** [comment]
이 이슈는 바코드 위키에 반영되었습니다.

https://github.com/opencloset/opencloset/wiki/barcode
