### ISSUE TITLE
미납시 발송되는 문자 매크로의 내용을 수정

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#593]
미납금 요청 문자의 계좌번호 수정을 요청드립니다.

기존 - [열린옷장] 안수봉님 0일 연체되어 00000원 입금바랍니다. 국민은행 205701-04-269524
변경요청 - [열린옷장] 안수봉님 0일 연체되어 00000원 입금바랍니다. 국민은행 205737-04-003013

계좌번호가 변경되었기에 수정 요청드립니다.

**Comment by keedi** [comment]
작업 및 적용 완료했습니다. 이슈 닫습니다.

**Comment by 10001if** [comment]
확인 완료하였습니다.
