### ISSUE TITLE
사용자 검색이 아니됨

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#597]
https://staff.theopencloset.net/user

전화번호로 검색하고 사용자링크를 누르면 Bad Gateway 가 발생함

**Comment by aanoaa** [comment]
패치 후 반영하였습니다.

**Comment by aanoaa** [comment]
`q_phone` 이 비었을때,

    ... user_info.phone LIKE %% ...

처럼 검색되어져 버려서 발생했던 현상입니다.

**Comment by aanoaa** [comment]
그리고 사용자 링크로 넘어가지 않았던 문제는 비교값을 나타내기 위해 추가되었던
Size::Guess 에서

    # OpenCloset::Size::Guess::Role::Base
    ...
    has gender => ( is => 'rw', isa => Enum [qw( male female )] );

인데 `user_info->gender` 가 `undefined` 일때 발생하는 문제입니다.

이것 역시 같이 패치후에 반영하였습니다.

**Comment by keedi** [comment]
#561 과 #566 작업의 side-effect 입니다.

**Comment by aanoaa** [comment]
문제가 또 있습니다.
`xxxx2@example.com` 과 같이 숫자가 들어간 검색어를 입력했을때 쓸모없는 결과가 너무 많습니다.
전화번호에 `2` 가 들어간 모든 사용자가 검색되는 것 같습니다.

**Comment by keedi** [comment]
`xxxx2@example.com` 같은 경우는 해결된 것을 확인했습니다. 다른 이슈가 있으면 추가로 수정하겠습니다.
