### ISSUE TITLE
포장완료 상태의 추가

### ISSUE THREAD

**Issue by keedi** [opencloset/opencloset#599]
opencloset/monitor#65 와 연결된 이슈입니다.

포장과  결제 사이 단계에서 버퍼 역할을 할 포장완료 상태가 필요하다고 합니다. 이유인즉 포장에서 결제로 넘길 때 병목이 이루어지지 않게 눈치를 보면서 한명씩 넘긴다고 합니다. 결제 상태로 바뀌면 사람들이 결제하는 장소에 몰리기 때문입니다. 이를 해결하기 위해 가운데 영역의 상태가 필요합니다.

**Comment by aanoaa** [comment]
https://github.com/opencloset/OpenCloset-Schema/issues/36#issuecomment-155677860
기존 데이터베이스에는 다음 질의를 추가로 실행해야 합니다.

```sql
INSERT INTO `status` (`name`) VALUES ('포장완료');
```

**Comment by aanoaa** [comment]
또한

    $ grunt

도 잊지말아야 합니다.

**Comment by aanoaa** [comment]
> opencloset/OpenCloset-Schema#36 (comment)
> 기존 데이터베이스에는 다음 질의를 추가로 실행해야 합니다.
> 
> INSERT INTO `status` (`name`) VALUES ('포장완료');

서버에 적용하였습니다.

**Comment by keedi** [comment]
배포까지 마무리 하시고 라벨을 확인요망으로 바꾸고 이슈 닫으면 될 것 같습니다.

**Comment by 10001if** [comment]
확인 완료하였습니다. 다들 정말 너무~ 좋아하네요~! ^^
