### ISSUE TITLE
방문 일자 선택 시 예약이 만료된 경우 예약 인원 초과 문구를 보여줌

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#601]
![2015-11-13 4 39 32](https://cloud.githubusercontent.com/assets/4696328/11141227/8f7432dc-8a26-11e5-9d5e-0c057ac3a651.png)
**예약인원 초과** 문구를 가장 우측에 삽입하면 예약이 완료되어 예약을 진행할 수 없다는 사실을 명확하게 인지하게 될 것 같습니다. 문구 추가 요청드립니다.

**Comment by keedi** [comment]
진행합니다.

**Comment by keedi** [comment]
결과 화면은 다음과 같습니다.

![screenshot-localhost 8001 2015-12-10 17-16-52](https://cloud.githubusercontent.com/assets/138451/11710581/ac2b6c4a-9f63-11e5-9408-0ddc30f60577.png)

**Comment by keedi** [comment]
구현 및 서버에 배포 완료 했습니다.
이슈 닫습니다. :-)

**Comment by 10001if** [comment]
감사합니다. 확인 완료하였습니다. :)
