### ISSUE TITLE
신체 사이즈 항목에 스커트 둘레 추가

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#602]
여성의 신체사이즈 중 허리둘레의 명칭을 골반둘레로 수정

현재 여성의 허리둘레 치수를 측정하는 위치가 골반지점입니다.
실제 허리라고 보여지는 곳은 스커트를 입는 위치이기 때문에, 
허리둘레 사이즈는 새로 만들어 사용하려고 합니다.

본 이슈에서는 기존의 허리둘레를 *골반둘레*로 수정하는 것을 요청드립니다.

**Comment by keedi** [comment]
정확히는 본 이슈는 골반 둘레를 추가하는 것입니다. 기존 허리 둘레의 값을 여성에 한해 추가한 골반 둘레로 옮기고 여성의 허리 둘레 값은 모두 0 또는 값 없음으로 설정해야 한다는 의미입니다.

**Comment by 10001if** [comment]
골반둘레에서 -> 윗골반둘레로 변경 요청드립니다.

**Comment by 10001if** [comment]
@keedi @yongbin 과 이야기 나눠본 결과 "스커트둘레"를 추가하는 것이 가장 좋은 방법인 것 같습니다.

**Comment by keedi** [comment]
이게 정확히 스커트 둘레인가요? 바지 둘레인가요? 하의 둘레인가요?

**Comment by 10001if** [comment]
스커트 둘레입니다~!

**Comment by 10001if** [comment]
부정확한 사이즈로 입력되고 있는 부분들을 바로잡고 사이즈 기준 교육을 통해 정확한 사이즈를 측정하려고 합니다. 그 전에 본 과정이 진행되어야 할 것으로 보입니다. ^^

**Comment by aanoaa** [comment]
우선 order, user_info 에 skirt 둘레가 추가되는 스키마 변경이 필요합니다.
이후에는 추가된 컬럼을 추가/수정/삭제 할 수 있는 기능을 만들어야 합니다.

**Comment by aanoaa** [comment]
스커트 둘레는 치수측정할때 입력되나요?
입력만 되고 따로 보여질 곳은 없나요?
치수측정은 https://staff.theopencloset.net/user/2 이런 곳에서 하나요?

**Comment by aanoaa** [comment]
preparation 에서 여성의 허리 대신에 스커트 둘레가 표시되야 합니다.

**Comment by aanoaa** [comment]
> preparation 에서 여성의 허리 대신에 스커트 둘레가 표시되야 합니다.

여기서는 이슈가 끝났고요, 모니터 쪽에서 새로운 이슈를 만들겠습니다.

**Comment by aanoaa** [comment]
스커트 둘레 짬 됐습니다.
스키마에서는 그대로 두되, 스커트둘레가 사용되는 곳은 찾아서 없애줘야 합니다.

**Comment by aanoaa** [comment]
https://github.com/opencloset/monitor/issues/106 이슈도 같이 해결되어야 합니다.

**Comment by 10001if** [comment]
확인 하였습니다. ^^
