### ISSUE TITLE
여성의 신체사이즈 중 허리둘레 사이즈를 추가

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#603]
기존의 허리둘레가 골반둘레로 변경됨에 따라 허리둘레가 존재하지 않기 때문에
허리둘레를 새로 추가해주실 것을 요청드립니다.

@aanoaa 기존에 ~preparation에서 보여지던 허리둘레 사이즈는 골반둘레로 변경되는 것이므로
새로 만들어진 허리둘레가 보여질 수 있도록 수정을 요청드립니다.

**Comment by aanoaa** [comment]
"preparation" 는 의류준비화면 이라고 해주세요.

**Comment by 10001if** [comment]
@aanoaa 네~ 알겠습니다. ^^

**Comment by keedi** [comment]
허리 둘레는 이미 있는 것입니다. 남성의 경우에도 사용하는데 여성이라고 허리 둘레 항목을 뺄 순 없겠죠. 즉 허리 둘레를 추가하는 것이 아니라 골반 둘레를 추가한 후 허리 둘레의 값을 골반 둘레로 옮겨야 하는 것입니다. 이때 기존 허리 둘레의 값은 모두 초기화 해야겠죠.

**Comment by keedi** [comment]
#602 와 겹치는 이슈 입니다. 해당 이슈에서 처리하겠습니다.
