### ISSUE TITLE
'채권추심' SMS 매크로 추가

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#605]
ooo님, 열린옷장입니다. 수 차례 연락을 드렸지만 전혀 어떠한 답변조차 받지 못하는 상태네요. 따라서 마지막으로 메세지 드립니다. 현재 ooo님의 연체금액은 x원이며 이 금액에 대해 채권추심회사와 연계하여 추징금 회수를 검토할 예정이고, 회수하지 못한 의류에 대해서는 명일 ooo님 주소, 전화번호를 토대로 서울 광진경찰서에 고소장을 접수할 것입니다. 이에 대해 금일 중으로 어떠한 답변을 듣지 못한다면 다소 불편한 상황이 되더라도 더 이상 방법이 없음을 알려드립니다. 감사합니다.

**Comment by 10001if** [comment]
이렇게 문자를 삽입해 달라는 의견을 받았습니다. 그래서.. SMS 매크로 문구 삽입을 요청드립니다.

**Comment by socmaster** [comment]
메시지가 조금 잘못 쓰여진 것 같은데요?
채권추심자와 열린옷장이 동일시 되도록 쓰는 것은 좋지 않다고 생각합니다.
문장에 대해 한 번 더 고민해주시면 어떨까요?

2015-11-24 14:44 GMT+09:00 Han manil <notifications@github.com>:

**Comment by 10001if** [comment]
@socmaster 네.. 저도 조금 마음이 걸리는 부분이 있습니다. 문구가 조금 지나친 부분이 있는 것 같은데요. 한번 더 고민해 보고 말씀드리겠습니다. 이 이슈는 잠시 보류해주시길 부탁드립니다. @keedi

**Comment by 10001if** [comment]
채권 추심에 관련하여서는 약관상에 정해져 있는 내용이 없기 때문에, 위법성 소지가 있는 것으로 보입니다. 이슈 닫도록 하겠습니다.
