### ISSUE TITLE
통계 페이지 중 상태 화면에서 주/월별로 평균데이터를 확인할 수 있게 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#606]
현재 상태 페이지에서는 당일의 세부 정보와 지정일 앞뒤로 각각 2일씩 총 5일의 정보를 확인 할 수 있습니다.
하지만 전체 시간 추이를 보고 확인하는 것은 어렵습니다.

방문자 페이지를 보면 주별로, 월별로 합계 정보를 볼 수 있는데,

상태 페이지에서도 방문자 페이지와 같은 형식의 포맷으로 주별, 월별로 
대기	치수측정	의류준비	탈의	수선	포장	결제의 평균 데이터를 보고 싶습니다.

![2015-11-26 5 23 26](https://cloud.githubusercontent.com/assets/4696328/11418470/62bc0962-9463-11e5-9ee6-833dd0bb6661.png)
![2015-11-26 5 23 26 2](https://cloud.githubusercontent.com/assets/4696328/11418473/661bee2e-9463-11e5-9d5f-91157ede29cf.png)

**Comment by yongbin** [comment]
> 방문자 페이지를 보면 주별로, 월별로 합계 정보를 볼 수 있는데,
> 상태 페이지에서도 방문자 페이지와 같은 형식의 포맷으로 주별, 월별로
> 대기 치수측정 의류준비 탈의 수선 포장 결제의 평균 데이터를 보고 싶습니다.

워크샵때 논의되었던 이슈입니다. `통계` - `상태` 페이지에 주,월별 변화추이를 확인하기를 원하고 있습니다. 예전에 `상태` 값의 변경 시각화를 진행한적이 있는데 이때 진행했던 그래프를(아래) `상태` 화면에 띄우는 형식을 고려하고 있습니다.

**Comment by keedi** [comment]
21일 월요일 부터 23일 수요일까지의 일정으로 진행한다고 합니다. via @yongbin

**Comment by keedi** [comment]
@yongbin 현재 진행 상태는 어떤지요?

**Comment by yongbin** [comment]
아직 진척이 없습니다. 다만 #627이 끝나면 OpenCPU 호출부가 정리되기때문에 바로 진행할 수 있습니다.

**Comment by yongbin** [comment]
매일 업데이트된 그래프를 보여주기 위해서는 열린옷장 DB의 정보를 opencpu 장비에서 접근할 수 있어야 합니다.

**Comment by yongbin** [comment]
DB 접근 문제가 해결된다면 다음과 같은 식으로 진행할 예정입니다.
 1. 크론을 이용해서 하루 한번 OpenCPU의 세션 API 생성
 2. 생성한 세션을 #627 과 비슷하게 persistant 하게 유지
 3. stat-status 페이지에서 해당 세션에 이미지 결과를 `<img>` 테그를 이용해서 불러오기

아래는 위 과정중 일부를 테스트한 화면입니다. 


![screen shot 2016-02-29 at 1 27 32 pm](https://cloud.githubusercontent.com/assets/52704/13385781/3ac839f6-dee8-11e5-8d9b-26fe66269bb9.png)

**Comment by yongbin** [comment]
https://mifosforge.jira.com/wiki/display/MIFOS/How+to+enable+MySQL+SSL+on+Ubuntu

**Comment by yongbin** [comment]
# 2016-06-13 일자  비율

![rplot04](https://cloud.githubusercontent.com/assets/52704/16001167/a93ef67c-318b-11e6-8a82-e8975237c5dc.png)

# 2016-06-13 일자  절대값

![rplot05](https://cloud.githubusercontent.com/assets/52704/16001178/b3f8280e-318b-11e6-8e7c-328e0bc25107.png)

**Comment by keedi** [comment]
@yongbin 본 이슈 이외에 관련있는 연관 이슈가 있나요? 없다면 인수인계 바랍니다.

**Comment by keedi** [comment]
직접 진행한다고 합니다.

**Comment by yongbin** [comment]
넵 기존 진행해주셨던 통계에 `대여회전율`, `방문자` 처리를 참고해서 그래프 없이 처리하겠습니다.

**Comment by yongbin** [comment]
진행합니다.

**Comment by yongbin** [comment]
#904 를 통해 작업이 완료되었습니다. 월요일에 확인후에 머지하겠습니다.

**Comment by yongbin** [comment]
@10001if 님과 상의한결과 다음과 같은 피드백을 받았습니다.

 - [ ] 기존 '상태' 메뉴에 있던 당일 방문자 목록을 표시
 - [ ] 당일 방문자 목록과, 주차 목록을 접기형태로 나타내고 기본 접기
 - [ ] 순서는 일별, 당일방문자, 주차, 월차

**Comment by yongbin** [comment]
@10001if 추가 요구사항을 모두 반영했습니다. 다시한번 피드백 받아야 합니다.

**Comment by 10001if** [comment]
@yongbin 보여주시면 피드백 드릴게요. ^^

**Comment by yongbin** [comment]
@10001if 님과 확인끝났습니다. 머지 진행해도 됩니다.

**Comment by keedi** [comment]
@yongbin 작업이 됐으면 구현한 부분 화면 갈무리해서 붙여주세요. 그래야 확인하기가 쉽겠지요.

**Comment by yongbin** [comment]
작업된 내용입니다. 

## 처음 접속했을때 (일별 상세와 주차별 접힘상태)

![screenshot-localhost 5001 2016-07-25 15-48-25](https://cloud.githubusercontent.com/assets/52704/17092752/a1d27b4c-527f-11e6-9af0-cf2a659efc87.png)


## 모두펼쳤을때

![screenshot-localhost_5001_2016-07-25_15-48-58](https://cloud.githubusercontent.com/assets/52704/17092758/a8b0ab46-527f-11e6-89f5-df53a996f7c5.png)

**Comment by yongbin** [comment]
@10001if 님 피드백 완료했고, @keedi 님 코드리뷰 마쳤습니다. 오늘 저녁 `v1.8.13` 으로 배포될 예정입니다. 이슈닫습니다.

**Comment by yongbin** [comment]
배포완료했습니다. 확인해주세요

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
