### ISSUE TITLE
의류 세트의 대푯값으로서 키와 몸무게를 추론

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#608]
최근에 키/몸무게를 의류의 종이택에 써넣는 작업을 하고 있습니다.

그런데, 의류의 코드로 검색을 하여 확인할 때 

1. 베스트 핏이 있는 경우에는 그 옷을 입은 사람의 키/몸무게를 결정
2. 베스트 핏은 아니나 입은 기록이 남아 있는 경우에는 입은 사람들의 사이즈를 살펴보고 키/몸무게를 결정 
3. 아예 기록이 없는 경우에는 - 의류의 사이즈를 보고 키/몸무게를 역추론

1,2번의 경우에는 어느정도 유추가 가능하지만, 3번의 경우에는 키/몸무게를 추론하는 과정이 어렵고 시간도 오래걸립니다. 따라서 새옷 등록시 의류의 사이즈를 입력하면 다른 의류의 사이즈를 보고 가장 잘 어울릴 것 같은 사람의 키/몸무게를 보여주어서 선택할 수 있게 하거나 혹은 자동으로 키/몸무게가 의류의 기록에 삽입 될 수 있도록 하였으면 좋겠습니다.

**Comment by yongbin** [comment]
#607 과 관려니 있어보입니다.

**Comment by yongbin** [comment]
> 3번의 경우에는 키/몸무게를 추론하는 과정이 어렵고 시간도 오래걸립니다. 따라서 새옷 등록시 의류의 사이즈를 입력하면 다른 의류의 사이즈를 보고 가장 잘 어울릴 것 같은 사람의 키/몸무게를 보여주어서 선택할 수 있게 하거나 혹은 자동으로 키/몸무게가 의류의 기록에 삽입 될 수 있도록 하였으면 좋겠습니다.

#627 을 진행하면서 대여된 기록이 없어도 의류사이즈로 몸무게를 추측할수 있는 수단이 생겼습니다. 하지만 아직도 이 방법이 필요한지 확인이 필요합니다. @10001if

**Comment by 10001if** [comment]
@yongbin 키 / 몸무게를 추정해야 하는 이슈는 재고관리를 위해 진행해야 할 것으로 보입니다. 정확하게 필요한지 여부는 다시 말씀드리도록 하겠습니다.

**Comment by yongbin** [comment]
#627 에서 진행된 내용은 사람의 사이즈를 옷의 사이즈로 추론하는 과정이고 이 이슈에서 필요한건 그 계산의 반대인 옷의 사이즈로 사람의 사이즈를 결정하는 문제입니다. 의류가 속성으로서 키와 몸무게를 가진다는것은 조금 부자연스럽게 느껴지는 측면이 있지만 열린옷장에서 옷의 부족분을 파악하고 그 정보를 기반으로 옷을 수선하거나 수급하게는 보조적인 지표로서 필요하기때문에 분석을 진행하겠습니다.

**Comment by yongbin** [comment]
#778 이슈의 `키`, `몸무게` 항목과도 관련이 있습니다.

**Comment by yongbin** [comment]
2016년 2월 21일자 열린옷장 대여자료 전체 73588건 중 남성 자켓 대여자료 10894건을 대상으로 대여기록을 분석했습니다.

![figure-18996s8c](https://cloud.githubusercontent.com/assets/52704/14946721/486280fc-1062-11e6-8dd4-b0bcd6c2223b.png)

대여된 의류의 가슴사이즈(bust)는 대여자의 키를 결정하는데 적절한 인자가 아닙니다. 위 표에서 보이는것 처럼 부분적으로 가슴사이즈의 증가가 대여자의 키와 선형적인 관계가 있는 구간도 있지만(90~97)그 효과가 미약하고 거의 대부분의 구간에서 대여자의 가슴사이즈의 평균, IQR, 전체 분포에서 눈에 띄는 차이가 있다고 보기 힘듭니다.  

![figure-189964nq](https://cloud.githubusercontent.com/assets/52704/14946733/654fa01e-1062-11e6-9b76-0a471abc1131.png)

 윗배둘래(topbelly)의 경우돠 거의 비슷합니다. 전체 구간에서 대여자 의류의 윗배둘래사이즈는 대여자의 키에 영향을 준다고 생각하기 어렵습니다. 

![figure-18996sqp](https://cloud.githubusercontent.com/assets/52704/14946748/9341b534-1062-11e6-877f-9db7ca5b4bd0.png)

자켓을 구성하는 사이즈중 유일하게 팔길이만 키와 어느정도 상관이 있는것으로 보입니다.

![rplot02](https://cloud.githubusercontent.com/assets/52704/14946773/19572654-1063-11e6-8d87-6eb14db38c18.png)

가슴사이즈는 체중과 상관이 커 보입니다. 

![rplot03](https://cloud.githubusercontent.com/assets/52704/14946774/1aab906c-1063-11e6-9abf-de2a36ab6648.png)

마찬가지로 윗배둘래역시 체중과 상관이 큽니다.

![rplot04](https://cloud.githubusercontent.com/assets/52704/14946775/1c5a0e5c-1063-11e6-8388-86308870bc15.png)

마지막으로 팔길이는 체중과 상관이 크지는 않습니다.

**Comment by yongbin** [comment]
이 자료를 이용해서 특정 모델을 만들고 해당 모델을 통해 새로운 값을 예측하는 방향으로 진행하도록 하겠습니다.

```R
  z <- ddply(data.raw[clothes_category == 'jacket' & height > 100], 
             .(clothes_code),summarise,
             height = mean(height,na.rm=T),
             weight = mean(weight, na.rm=T),
             cnt = length(clothes_code),
             clothes_bust = mean(clothes_bust, na.rm=T),
             clothes_topbelly = mean(clothes_topbelly,na.rm=T),
             clothes_arm = mean(clothes_arm,na.rm=T))
```

기존자료를 `clothes_code`를 기준으로 빌려간 사람의 키, 몸무게, 가슴, 윗배, 팔길이의 평균과 대여수를 먼저 구합니다.

```R
  z <- ddply(z, .(clothes_bust, clothes_topbelly, clothes_arm), mutate, cnt_total = sum(cnt),  cnt_ratio = cnt / cnt_total)
```

이제 의류코드를 버리고, 동일한 의류의 사이즈별로 묶어서 총 대여 수량(cnt_total), 각 의류별 대여비율(cnt_ratio)를 구합니다.

```R
  z <- ddply(z[ z$cnt_total > 5,], .(clothes_bust, clothes_topbelly, clothes_arm), summarise, height = weighted.mean(height, cnt_ratio), weight = weighted.mean(weight,cnt_ratio))
```

마지막으로 5번 이상 대여된 의류를 사이즈별로 키와 몸무게의 평균을 구하되 대여수만큼 가중치를 두고 가중평균을 구합니다.

**Comment by yongbin** [comment]
이렇게 구한 결과는 대략 아래와 같습니다.

![rplot05](https://cloud.githubusercontent.com/assets/52704/14946897/10c9ba72-1065-11e6-91c0-ab2a6fa5809a.png)

전체 자료를 기준으로 알아본 내용과 비슷하지만, 전체적으로 평균을 취했기때문에 값의 분포가 smoothing 된것으로 보입니다.

**Comment by yongbin** [comment]
이 결과를 통해 randomForest 를 이용해서 간단하게 모델을 만들고 예측했습니다.

```R
  hmodel <- randomForest(height   ~ clothes_bust + clothes_topbelly + clothes_arm, data = z,na.action=na.omit)
  wmodel <- randomForest(weight   ~ clothes_bust + clothes_topbelly + clothes_arm, data = z,na.action=na.omit)

  predict(hmodel,newdata = data.frame(clothes_bust = 101, clothes_topbelly = 92, clothes_arm = 59))
  predict(wmodel,newdata = data.frame(clothes_bust = 101, clothes_topbelly = 92, clothes_arm = 59))
```

```
Call:
 randomForest(formula = height ~ clothes_bust + clothes_topbelly +      clothes_arm, data = z, na.action = na.omit) 
               Type of random forest: regression
                     Number of trees: 500
No. of variables tried at each split: 1

          Mean of squared residuals: 5.549749
                    % Var explained: 87.98

Call:
 randomForest(formula = weight ~ clothes_bust + clothes_topbelly +      clothes_arm, data = z, na.action = na.omit) 
               Type of random forest: regression
                     Number of trees: 500
No. of variables tried at each split: 1

          Mean of squared residuals: 11.5742
                    % Var explained: 96.04
```

가슴사이즈 101, 윗배 92, 팔길이 59 인 사람의 키는 171.99 몸무게는 73.04 로 추측합니다.

**Comment by yongbin** [comment]
현재 5층에서 사용되고 있는 5개의 의류택을 임의로 수거해서 적혀있는 값과 모델을 이용한 값을 비교해봤습니다.

![img_0769](https://cloud.githubusercontent.com/assets/52704/14948007/70ab549e-1076-11e6-83a1-c60cb2a496ee.jpg)
![img_0772](https://cloud.githubusercontent.com/assets/52704/14948010/70f5c48e-1076-11e6-9881-157fbf2d3ad6.jpg)
![img_0773](https://cloud.githubusercontent.com/assets/52704/14948009/70f2a8f8-1076-11e6-8e71-ea508457a075.jpg)
![img_0770](https://cloud.githubusercontent.com/assets/52704/14948011/70f8893a-1076-11e6-9c65-cac18b463a33.jpg)
![img_0771](https://cloud.githubusercontent.com/assets/52704/14948008/70d19348-1076-11e6-828f-2da363c9bb5b.jpg)

## 결과
```
|---+------+----------+------+--------+----------+--------+----------|
|   | bust | topbelly |  arm | height |  predict | weight |  predict |
|---+------+----------+------+--------+----------+--------+----------|
| 1 |  101 |       92 | 61.5 |    173 | 173.0146 |     73 | 74.09748 |
| 2 |  100 |       94 |   66 |    186 | 181.5268 |     75 | 78.56713 |
| 3 |   98 |       92 |   63 |    176 |  177.675 |     76 | 70.86751 |
| 4 |   99 |       92 |   60 |    174 | 171.8653 |     71 | 71.42824 |
| 5 |   98 |       91 |   62 |    182 |   174.87 |     68 | 70.89182 |
|---+------+----------+------+--------+----------+--------+----------|
```

**Comment by yongbin** [comment]
@10001if 결과 확인하고 말씀해주시기 바랍니다. 혹은 모델을 통해서 얼마가 나오는지 궁금한 사이즈가 있으면  알려주시기 바랍니다. 결과에 문제가 없다면 남자 바지, 여성 자켓, 여성 스커트도 진행하겠습니다.

**Comment by yongbin** [comment]
현재 결과는 해당 자켓을 대여한 사람의 신체사이즈의 가중편균을 통해 모델을 만들었기때문에 세트인 바지의 정보이외에 세트가 아닌 의류와 함께 대여된 경우도 포함될 수 있습니다 결과에 영향을 미비할것으로 생각하지만 이후 바지에 대한 예측까지 진행하면 두 값을 다시 평균내는 형태가 필요할 것 같습니다.

**Comment by yongbin** [comment]
- 추정치에서 베스트핏 가중치 적용(가중치를 임의로 결정)
- 남자 세트제고 파악
- 여자 세트제고 파악
- 세트의 결정방법은 임의 선택

**Comment by aanoaa** [comment]
아까 얘기하시는거 훔쳐들었는데, *suit* 테이블에 height, weight 컬럼을
추가한다면 셋트의류별로 키/몸무게를 기록할 수 있습니다.

**Comment by yongbin** [comment]
네 하지만 `suit`의 키, 몸무게던 `clothes`의 키 몸무게던 *옷은 키 몸무게라는 고정된 값을 가질수 없고 값이 계속 바뀔수 밖에 없기때문에* DB에 저장하지는 않을 예정입니다. 지금은 기존값뿐만 아니라 한번도 대여되지 않은 세트에 대한 값이 필요한 상황이기도 하구요

**Comment by yongbin** [comment]
의류 대푯값으로서의 키와 몸무게는 대여기록을 바탕으로 파악되는 **현실적인 값** 과 열린옷장에서 **이상적으로 생각하는값** 사이에 존재합니다. 예를들면 남성 자켓 [J09R](https://staff.theopencloset.net/clothes/J09R)의 경우 이 자켓은 현실적으로 32회 대여되었으며 빌려간 이들의 키와 몸무게의 평균은 174.3과 71.1 입니다. 하지만 이 옷의 베스트 핏은 2회 기록되어있으며 각각 177 / 66, 182 / 68입니다. 

![screenshot 2016-05-06 22 40 53](https://cloud.githubusercontent.com/assets/52704/15074767/b00bf892-13db-11e6-9beb-21001db9dce9.png)

그리고 이 옷의 의류 텍에는 182 / 68 이 기록되어있습니다. 

![70d19348-1076-11e6-828f-2da363c9bb5b](https://cloud.githubusercontent.com/assets/52704/15074778/bfd16a8c-13db-11e6-9a56-d081de883bf8.jpg)

이 옷의 대여정보와, 이 옷과 사이즈가 동일한 자켓의 대여정보를 모두 반영한 이 옷의 대푯값으로서의 키와 몸무게는  174.87  /  70.89182 으로 키에서 8cm 정도 차이가 납니다.  열린옷장은 이 대푯값에 **이상적으로 생각하는값** 이 좀 더 반영되기를 윈합니다. 

기존에는 베스트핏 정보를 별도로 예측에 활용하지 않고 있는데 이렇게 진행되기위해서는 베스트핏 대여에 대해서 가중치를 줘야하니다.

**Comment by aanoaa** [comment]
@yongbin 진행상황에 대한 업데이트 바랍니다.

**Comment by yongbin** [comment]
2주전 세트로 진행하기로 결정한 이후 진행된 사항이 없습니다.

**Comment by aanoaa** [comment]
pending 되어 있는거라면 적절하게 마일스톤 조절해주세여
이미 기간이 지나버렸거든요.

**Comment by yongbin** [comment]
넵 1.9로 변경했습니다.

**Comment by yongbin** [comment]
진행을 위해서 이슈를 리뷰하면서 전체적으로 다시 생각을 해봤습니다.  기존 예측 결과가 열린옷장에서 기대한 결과와 차이가 나는 이유는 기존 접근방식에서 bestfit 정보를 무시하고 계산했기때문입니다. 따라서 다음과 같은 방식으로 대푯값을 결정하면 이런 문제를 해소할 수 있을것 같습니다.

```
의류 대푯 신체 사이즈 = 0..2 x non-bestfit 착용자의 사이즈 평균 + 0.8 x bestfit 착용자의 사이즈 평균
```

2:8 의 비율을 추후 조정이 가능하겠지만, 지금까지의 논의 내용을 바탕으로 볼때 최소한 bestfit 착용자의 사이즈 평균에 50% 이상의 가중이 할당되어야 열린옷장에서 원하는 유의미한 결과가 나올수 있을것 같습니다.

이 내용을 바탕으로 위에서 진행했던 예측을 다시 진행한뒤 결과를 확인해보겠습니다.

**Comment by yongbin** [comment]
가중평균 아이디어를 적용한 코드입니다.

```{r}
library(ocarina)
library(reshape2)
library(data.table)
library(randomForest)

data.raw <- data.table(data)
set.seed(1234)

z <- ddply(data.raw[clothes_category == 'jacket' & height > 100], 
             .(clothes_code, is_bestfit),summarise,
             height = mean(height,na.rm=T),
             weight = mean(weight, na.rm=T),
             cnt = length(clothes_code),
             clothes_bust = mean(clothes_bust, na.rm=T),
             clothes_topbelly = mean(clothes_topbelly,na.rm=T),
             clothes_arm = mean(clothes_arm,na.rm=T))
x<-z[,c("clothes_code","is_bestfit", "height","weight","cnt")]
x <- reshape(x, idvar='clothes_code', timevar = 'is_bestfit', direction = 'wide')
x$height <- ifelse( ! is.na(x$height.TRUE), x$height.TRUE * 0.8 + x$height.FALSE * 0.2, x$height.FALSE )
x$weight <- ifelse( ! is.na(x$weight.TRUE), x$weight.TRUE * 0.8 + x$weight.FALSE * 0.2, x$weight.FALSE )
x$count  <- ifelse( ! is.na(x$cnt.TRUE), x$cnt.TRUE + x$cnt.FALSE, x$cnt.FALSE )


a <- ddply(data.raw[clothes_category == 'jacket' & height > 100], 
             .(clothes_code),summarise,
             height = mean(height,na.rm=T),
             weight = mean(weight, na.rm=T),
             cnt = length(clothes_code),
             clothes_bust = mean(clothes_bust, na.rm=T),
             clothes_topbelly = mean(clothes_topbelly,na.rm=T),
             clothes_arm = mean(clothes_arm,na.rm=T))


merged <- merge(x, a, by.x = 'clothes_code', by.y = 'clothes_code')

merged <- merged[,c("clothes_code","height.y","weight.y","count","clothes_bust","clothes_topbelly","clothes_arm")]
colnames(merged) <- c("clothes_code","height","weight","cnt","clothes_bust","clothes_topbelly","clothes_arm")


merged <- ddply(merged,
             .(clothes_bust, clothes_topbelly, clothes_arm),
             mutate,
             cnt_total = sum(cnt),
             cnt_ratio = cnt / cnt_total)

merged <- ddply(merged[ merged$cnt_total > 5,],
             .(clothes_bust, clothes_topbelly, clothes_arm),
             summarise,
             height = weighted.mean(height, cnt_ratio),
             weight = weighted.mean(weight,cnt_ratio))

hmodel <- randomForest(height   ~ clothes_bust + clothes_topbelly + clothes_arm, data = merged,na.action=na.omit)
wmodel <- randomForest(weight   ~ clothes_bust + clothes_topbelly + clothes_arm, data = merged,na.action=na.omit)

predict(hmodel,newdata = data.frame(clothes_bust = 101, clothes_topbelly = 92, clothes_arm = 59))
predict(wmodel,newdata = data.frame(clothes_bust = 101, clothes_topbelly = 92, clothes_arm = 59))
```

### 결과

```
> predict(hmodel,newdata = data.frame(clothes_bust = 101, clothes_topbelly = 92, clothes_arm = 59))
       1 
171.4652 
> predict(wmodel,newdata = data.frame(clothes_bust = 101, clothes_topbelly = 92, clothes_arm = 59))
       1 
73.05878 
```

**Comment by yongbin** [comment]
```{r}
predict(hmodel,newdata = data.frame(clothes_bust = 101, clothes_topbelly = 92, clothes_arm = 61.5))
predict(wmodel,newdata = data.frame(clothes_bust = 101, clothes_topbelly = 92, clothes_arm = 61.5))


predict(hmodel,newdata = data.frame(clothes_bust = 100, clothes_topbelly = 94, clothes_arm = 66))
predict(wmodel,newdata = data.frame(clothes_bust = 100, clothes_topbelly = 94, clothes_arm = 66))


predict(hmodel,newdata = data.frame(clothes_bust = 98, clothes_topbelly = 92, clothes_arm = 63))
predict(wmodel,newdata = data.frame(clothes_bust = 98, clothes_topbelly = 92, clothes_arm = 63))


predict(hmodel,newdata = data.frame(clothes_bust = 99, clothes_topbelly = 92, clothes_arm = 60))
predict(wmodel,newdata = data.frame(clothes_bust = 99, clothes_topbelly = 92, clothes_arm = 60))


predict(hmodel,newdata = data.frame(clothes_bust = 98, clothes_topbelly = 91, clothes_arm = 62))
predict(wmodel,newdata = data.frame(clothes_bust = 98, clothes_topbelly = 91, clothes_arm = 62))



```
위에 테스트를 똑같이 적용한 결과는 아래와 같습니다. 

```
   |---+------+----------+------+--------+----------+--------+----------|
   |   | bust | topbelly |  arm | height |  predict | weight |  predict |
   |---+------+----------+------+--------+----------+--------+----------|
   | 1 |  101 |       92 | 61.5 |    173 |  173.689 |     73 | 74.58735 |
   | 2 |  100 |       94 |   66 |    186 | 181.4231 |     75 | 78.22723 |
   | 3 |   98 |       92 |   63 |    176 | 177.7454 |     76 | 70.81406 |
   | 4 |   99 |       92 |   60 |    174 | 172.1167 |     71 | 71.88809 |
   | 5 |   98 |       91 |   62 |    182 | 174.6481 |     68 | 70.11472 |
   |---+------+----------+------+--------+----------+--------+----------|
```

**Comment by yongbin** [comment]
극단적으로 만약 bestfit 이 있는 경우 대여수 전체를 bestfit 평균 사이즈로 대여했다고 가정하고 모델을 만들어 테스트 했습니다.

```
> predict(hmodel,newdata = data.frame(clothes_bust = 98, clothes_topbelly = 91, clothes_arm = 62))
       1 
174.6481 
> predict(wmodel,newdata = data.frame(clothes_bust = 98, clothes_topbelly = 91, clothes_arm = 62))
       1 
70.11472 
```

결과가 차이가 없습니다.

결과로 미루어볼때  가중치의 이슈라기보다는 의사결정 회귀나무 모형상 강력한 상위 feature에 영향을 받고있는것으로 추측됩니다.

**Comment by yongbin** [comment]
결과적으로 모델만으로 원하는 결과를 얻기는 어렵다고 판단합니다. 현재 고려할 수 있는 대안은 다음과 같습니다.

 1. 모델의 결과를 선택적로 사용 : 일정수 이상의 대여기록과 bestfit 정보가 있다면, 모델에 질의하지 않고 bestfit 기준 결과를 사용. 모델은 기존 대여결과가 없는 치수에 한정해서 질의.

 2. 모델 결과를 보조적으로 사용 : 기존 대여기록이 있다면 기존 대여 평균, bestfit 가중한 결과와 모델에서 예측한 결과를 산술평균해서 이용

관련해서 @10001if 님과 상의해서 결정하겠습니다.

**Comment by 10001if** [comment]
@yongbin 오시면 뵙고 논의하도록 하겠습니다. ^^

**Comment by 10001if** [comment]
@yongbin 당장 급하게 필요하고, 그 중요도도 매우 높으므로 마일스톤을 가장 빠른 쪽으로 옮기겠습니다.

**Comment by yongbin** [comment]
키와 몸무게를 의류의 대표값으로 사용하는것과 관련해서 @10001if 님과 오래동안 이야기했고 결론적으로 이 방식으로 진행하는것이 적절하지 않다는점을 서로가 이해했습니다. 따라서 이 이슈는 종결하도록 하겠습니다.
