### ISSUE TITLE
대여자가 택배 발송 후 택배 운송장 번호와 업체를 직접 입력할 수 있도록 함 

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#609]
현재는 메일 또는 문자, 카톡 메세지를 통해 전달을 하고 있습니다.
과거에는 문자 메세지를 보고 주문서에서 입력을 하였지만 최근에는 번거로움 때문에 입력을 하지 못하고 있습니다.
대여자가 택배 발송 후에 택배 운송장번호와 업체등을 직접 입력할 수 있도록 하는 방법이 도입되었으면 좋겠습니다.

**Comment by 10001if** [comment]
로그인이 되고나면 달라질지는 모르겠지만 현재는 @aanoaa 님이 만들어 주신 문자 발송 시스템으로 본 이슈가 해결되었습니다.

**Comment by aanoaa** [comment]
사용자들이 잘 입력하고 잇나요?

**Comment by 10001if** [comment]
@aanoaa 제가 전해듣기로는 입력창이 안뜨거나 어려워서 입력을 못했다는 연락은 1~2건에 불과했구요. 실제로 택배 반납시 주문서를 살펴보면 아주 높은 비율로 입력을 진행하고 있는 걸 확인할 수 있었습니다.

**Comment by aanoaa** [comment]
@10001if 이슈가 끝난 것 같아 보입니다. 확인해서 닫아주시거나 추가로 해야 할 일들에 대해 남겨주세요.

**Comment by 10001if** [comment]
@aanoaa 본 건은 이슈가 마무리 되었습니다. 이슈 닫도록 할게요. 감사합니다. ^^
