### ISSUE TITLE
대여자가 자신의 반납일을 스스로 연장할 수 있도록 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#610]
현재 연장을 원하는 대여자는 전화를 하거나, 메일, 문자를 통해 연장 신청을 하고 있습니다.
실제로는 연장신청을 하지 않고 반납을 하여도 발생하는 추가 비용은 동일합니다. 하지만 반납과 연장에 대한 생각을 더 분명하게 하기 위해 연장신청을 받고 있습니다. 하지만 반납일을 스스로 연장할 수 있도록 하였으면 좋겠습니다.

**Comment by 10001if** [comment]
로그인이 되고나면 달라질지는 모르겠지만 현재는 @aanoaa 님이 만들어 주신 문자 발송 시스템으로 본 이슈가 해결되었습니다.

**Comment by MoDoLEE** [comment]
안드로이드의 경우 반납일 입력란에서 달력이 뜨지 않아서,
어떤식으로 입력을 해야 될지 모르는 사용자가 있는 것 같습니다.
"1월 12일"이라고 입력했다는 대여자의 답변을 들어서 #660 이슈에서
Placeholder 문구 수정을 진행하였습니다.
P.S. "1월 12일"이라고 입력 할 경우 반납 예정일이 아예 NULL이 되어 버리는 것 같습니다.

**Comment by aanoaa** [comment]
@10001if 님 뿐만 아니라 staff 이 직접 참여하는게 아주 좋습니다. :+1: 
@MoDoLEE ++

제가 안드로이드로 테스트 할 수 없기 때문에 직접 찾아가서 확인해보도록 하겠습니다.

**Comment by 10001if** [comment]
@MoDoLEE ++ 두 개나 받으셨네요~ ㅎㅎ

**Comment by aanoaa** [comment]
https://github.com/opencloset/opencloset/pull/622#issuecomment-187539497
