### ISSUE TITLE
주문서에 '반납알림' 기능 추가

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#611]
종종 기존에 대여하였던 의류를 원하는 대여자가 있습니다. 그런데 그 옷은 대여 중 상태입니다. 그래서 대여가 돌아올 때까지 기다립니다. 반납시 확인해야 하는 의류가 있는 경우에 따로 코드를 입력해두고 그 이유를 반납시 팝업이 크게 떠서 "확인이 필요한 물품"입니다. 라고 창에 뜨게 하면 반납시 바로 체크하여 두번 씩 찾는 일을 하지 않아도 될 것 같습니다.

**Comment by 10001if** [comment]
팝업의 내용은 저희가 직접 입력 할 수 있도록 하였으면 좋겠습니다. 예를들면, 팝업이 떠야 하는 의류의 코드를 입력하고 그 이유를 적어놓으면 본 위류가 반납되었을 때 그 이유와 연락해야 할 사람 등이 모니터에 떠서 의류를 별개로 운영할 수 있도록 하는 기능이 필요합니다.

**Comment by aanoaa** [comment]
궁금한 점입니다.

- 알림이 필요한 옷에 대한 코멘트를 어디에서 추가하는가?
- 대여중인 옷에만 코멘트를 추가할 수 있는가?
- 반납후에 작성된 코멘트가 어디에 보여져야 하는가?

**Comment by 10001if** [comment]
- 알림이 필요한 옷에 대한 코멘트를 어디에서 추가하는가?
따로 작업을 하지 않고 진행할 수 있다고 생각했을 때, 비고(주문서 메모란)에서 추가하도록 생각하였습니다. 그런데 비고가 있는 모든 의류에 다 적용이 되면 반납 때마다 모든 의류의 비고가 뜰테니 구분이 필요할 것 같습니다.
- 대여중인 옷에만 코멘트를 추가할 수 있는가?
대여가능 상태를 제외한 모든 의류의 경우에 코멘트가 추가될 수 있어야 합니다.
- 반납후에 작성된 코멘트가 어디에 보여져야 하는가?
제 의도로는 반납 완료가 되면 팝업으로 코멘트의 내용이 나타날 수 있도록 생각하였습니다.
팝업으로 뜨면 반드시 창을 닫아야 하고 의류에 대한 이슈가 있는 경우 반드시 확인을 할 수 있기 때문입니다.

**Comment by yongbin** [comment]
> 반납후에 작성된 코멘트가 어디에 보여져야 하는가? 제 의도로는 반납 완료가 되면 팝업으로 코멘트의 내용이 나타날 수 있도록 생각하였습니다. 팝업으로 뜨면 반드시 창을 닫아야 하고 의류에 대한 이슈가 있는 경우 반드시 확인을 할 수 있기 때문입니다.

이 부분은 ** 누구에게** 이슈도 있습니다. 팝업이 모든사람에게 공유되어야 하는지 특정사용자에게 보여야하는지도 정해져야합니다

**Comment by aanoaa** [comment]
clothes.theopencloset.net ㅋㅋ

**Comment by 10001if** [comment]
@yongbin 열린옷장 직원 모두에게 공유되어야 합니다.

**Comment by aanoaa** [comment]
> 따로 작업을 하지 않고 진행할 수 있다고 생각했을 때, 비고(주문서 메모란)에서 추가하도록 생각하였습니다. 그런데 비고가 있는 모든 의류에 다 적용이 되면 반납 때마다 모든 의류의 비고가 뜰테니 구분이 필요할 것 같습니다.

의류가 아닌 주문서에서 코멘트를 입력하나요?

**Comment by aanoaa** [comment]
> 제 의도로는 반납 완료가 되면 팝업으로 코멘트의 내용이 나타날 수 있도록 생각하였습니다.
팝업으로 뜨면 반드시 창을 닫아야 하고 의류에 대한 이슈가 있는 경우 반드시 확인을 할 수 있기 때문입니다.

팝업은 방법이고요, 어디에서 보여져야 하는건가요?
4층에서 `전체반납` 버튼을 누른후에 작성된 코멘트가 보여져야 하는건가요?

**Comment by yongbin** [comment]
@aanoaa 제가 내용을 좀 정리해서 올리겠습니다.

**Comment by yongbin** [comment]
@10001if 님과 내용을 정리했습니다. 열린옷장에서는 대여중인 옷들중 반납되었을때 후속적으로 처리를 해야할 의류들을 관리하고 싶어서 기능을 요구하기 때문에 다음과 같은 (가상의) 시나리오로 진행될것 같습니다.

1. 마닐씨는 전화로 `P07J` 의류의 주머니가 터졌다는 전화를 받음 
2. 검색결과 `P07J` 의류가 현재 대여중이며 704번 주문서에 연결되어있음을 확인 
3. 마닐씨는 704번 주문서의 `주문서 메세지` 란에 "바지 주머니가 터졌답니다 반납되면 마닐에게 주세요" 라고 기록함
4. 추가적으로 주문서의 `반납알림` 항목을 `예`로 변경함
5. 몇일후
6. 의류를 반납반은 수봉씨는  반납에서 704번 주문서를 찍고 전체 반납을 누름
7. 반납이 완료된 순간 화면에 팝업(혹은 어떤 형태던) "바지주머니가 터졌답니다 반납되면 마닐에게 주세요" 라는 메세지가 보입

이런시나리오입니다. 나머지 모든 항목은 열린옷장에서 해야할 일이고 시스템적으로 구현이 필요한 부분은 4번과 7 번입니다. 

4번의 위치는 대략 아래그림이 될것 같고 7번의 경우 "반납알림 메세지가 있습니다. 주문서 메세지를 확인해주세요" 처럼 일반적인 메세지를 말씀드렸지만 @10001if 님은 가능하면 주문서 메제시 자체가 뜨는것을 더 선호했습니다.

![_ _-_ _and_user-id_coffee____dropbox_yongbin_repository_active_opencloset_coffee__-_vim](https://cloud.githubusercontent.com/assets/52704/13485926/b36fa6f0-e14f-11e5-9ebb-2f82258e1e78.png)


@10001if 틀린거 있으면 말씀해주세요

**Comment by 10001if** [comment]
@yongbin  대표님~완벽합니다~! ^^

**Comment by aanoaa** [comment]
`주문서 메세지` 가 이미 사용되고 있는 `주문서 메모`를 말씀하시는 건가요?
아니면 알람기능에 활용될 메세지칸이 추가되는 건가요?

**Comment by aanoaa** [comment]
default 로 반납되었을때 주문서 메모가 있는 경우에 메모를 보여주는건 어떤가요?

**Comment by yongbin** [comment]
> 주문서 메세지 가 이미 사용되고 있는 주문서 메모를 말씀하시는 건가요?
> 아니면 알람기능에 활용될 메세지칸이 추가되는 건가요?

기존에 있는 `주문서 메모` 입니다

> default 로 반납되었을때 주문서 메모가 있는 경우에 메모를 보여주는건 어떤가요?

위 4번째 코맨트를 보면 

> 따로 작업을 하지 않고 진행할 수 있다고 생각했을 때, 비고(주문서 메모란)에서 추가하도록 생각하였습니다. 그런데  ** 비고가 있는 모든 의류에 다 적용이 되면 반납 때마다 모든 의류의 비고가 뜰테니 구분이 필요할 것 같습니다**. 

라는 내용이 있습니다.

**Comment by aanoaa** [comment]
이래도 저래도 상관없다고 했습니다.
새로만들든 기존의 주문서 메모를 활용하든

**Comment by aanoaa** [comment]
`반납알림` 설정을 해야 한다는게 좀 자연스럽지 않습니다.
메모만 작성하면 알아서 알림이 떠야 하지 않나 싶습니다.

주문서 메모는 대여 전반에서 활용되나요, 아니면 반납에 관련된 용도로 쓰이고 있나요?

**Comment by aanoaa** [comment]
위의 이유로 해서 생각난것이, 반납이 되었을때 메모가 있으면 팝업으로 메모를 보여준다.

는 어떤가요?

**Comment by yongbin** [comment]
> 주문서 메모는 대여 전반에서 활용되나요, 아니면 반납에 관련된 용도로 쓰이고 있나요?

DB 확인해보니까 다양한 용도로 활용되는거 같습니다.

```
흰색 셔츠
흰색 셔츠
8/31 내용증명 문자
반납한다고 문자옴 - 8/31
9/16 최후통보 문자
9/16 14:24 최대한 빨리 반납하겠다고 전화 옴 (성일)
9/17 자켓, 벨트 택배 반납하겠다 함 (자켓을 잘못 가져옴) 아르바이트 급여가 3~5일 후 입금된다 하여 택배 보낸 후 연체금액 입금예정 - 안수봉
9/19 반납 확인 후 19만원 연장비 안내 문자 발송 - 김혜리
```

```
회색 정장은 입어만 보신데요, 준비 같이 부탁드립니다 11/6
```

```
하늘색 셔츠 // 체크 셔츠
발 볼 넓은 구두
하늘색 셔츠 // 체크 셔츠
발 볼 넓은 구두
하늘색 셔츠 // 체크 셔츠
발 볼 넓은 구두
```
그럼 차라리 `반남 메모` 항목을 따로 만드는것도 괜찮을꺼 같은데요??

**Comment by aanoaa** [comment]
반납알림 대신에 반납메모를 추가하고 거기에 내용을 적으면 반납후에 알려주는걸로 하겠습니다.

**Comment by yongbin** [comment]
넵 어차피 둘다 스키마를 건드려야 하긴 하지만 그방향이 더 직관적일거 같습니다.

**Comment by aanoaa** [comment]
완료되었지만 DB 스키마가 변경되었습니다.
영업시간 이후에 배포하도록 하겠습니다.

선행작업

- [ ] OpenCloset::Schema 배포
- [ ] db schema 변경

**Comment by 10001if** [comment]
확인 완료하였습니다~

**Comment by aanoaa** [comment]
부분반납이 되었을때 하위주문서에 `반납 메세지` 가 복사 되어야 합니다.

**Comment by 10001if** [comment]
부분반납시에도 반납 메세지가 나타날 수 있도록 부탁드립니다.

**Comment by MoDoLEE** [comment]
반납 메세지가 부분 반납, 전체 반납 완료시 보여지면 처리하지 못하는 부분이 있습니다.
예: "연체료 에누리 해주세요." 와 같은 경우에는 반납 처리 버튼을 누른 후에 메세지가 보이면 이미 에누리 적용이 불가능한 상태입니다.
그래서 반납 메세지가 주문서에 들어가면 바로 보였으면 합니다.

**Comment by aanoaa** [comment]
반납메세지를 확인하는 수밖에 없을 것 같은데..
반납메세지가 있다면 주문서에서 항상 팝업을 보여주도록 하면 될까요?

**Comment by MoDoLEE** [comment]
내일 의견 취합해서 코멘트 남기겠습니다.

**Comment by aanoaa** [comment]
반납 메세지가 있을 경우에 최상단에 내용을 나타내도록 합니다.

라고 하셨습니다.

**Comment by aanoaa** [comment]
`반납 메세지` 대신에 `반납 확인 메모` 로 라벨을 변경해야 합니다.

**Comment by 10001if** [comment]
확인 하였습니다. ^^
