### ISSUE TITLE
의류, 사람의 사이즈가 달라졌을 때 기존 기록과 구별시킴

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#612]
재방문시 사이즈를 재 측정하는 경우가 있습니다. 재측정된 사이즈는 기존 사이트 위에 새로 입력됩니다. 때문에 그 전의 의류의 기록과 섞이게 됩니다. 그리고 기존 의류의 경우에도 수선을 하게되면 의류의 사이즈의 변동이 생깁니다. 수선을 한 의류의 경우에도 기존의 대여기록과 섞이게 되는데. 이를 위해 구분을 할 수 있도록 하는 것이 필요해 보입니다. 하지만 어떻게 해야할지 생각을 하지 못하겠습니다. 우선 이슈에 작성해놓도록 하겠습니다.

**Comment by yongbin** [comment]
말씀해 주신 내용을 확인해봤습니다.

## 사용자 치수 변화

> 재방문시 사이즈를 재 측정하는 경우가 있습니다. 재측정된 사이즈는 기존 사이트 위에 새로 입력됩니다. 때문에 그 전의 의류의 기록과 섞이게 됩니다.

그렇지 않습니다. 현재 재고관리 화면에는 사용자의 최종 치수만 보이고 있지만 DB상에는 매번 반복측정했던 실측 치수들이 모두다 기록되어있습니다.

예를들면 사용자번호 13174 김XX 씨가 대여하신 5번 대여의 치수정보는 아래와 같습니다. 

<table border="2" cellspacing="0" cellpadding="6" rules="groups" frame="hsides">


<colgroup>
<col  class="org-right" />

<col  class="org-right" />

<col  class="org-left" />

<col  class="org-left" />

<col  class="org-left" />

<col  class="org-right" />

<col  class="org-right" />

<col  class="org-left" />

<col  class="org-right" />

<col  class="org-right" />

<col  class="org-left" />

<col  class="org-right" />

<col  class="org-left" />

<col  class="org-right" />

<col  class="org-right" />

<col  class="org-right" />

<col  class="org-left" />

<col  class="org-right" />

<col  class="org-left" />

<col  class="org-right" />
</colgroup>
<thead>
<tr>
<th scope="col" class="org-right">주문번호</th>
<th scope="col" class="org-right">사용자번호</th>
<th scope="col" class="org-left">&#xa0;</th>
<th scope="col" class="org-left">목적</th>
<th scope="col" class="org-left">&#xa0;</th>
<th scope="col" class="org-right">Size</th>
<th scope="col" class="org-right">&#xa0;</th>
<th scope="col" class="org-left">&#xa0;</th>
<th scope="col" class="org-right">&#xa0;</th>
<th scope="col" class="org-right">&#xa0;</th>
<th scope="col" class="org-left">&#xa0;</th>
<th scope="col" class="org-right">&#xa0;</th>
<th scope="col" class="org-left">&#xa0;</th>
<th scope="col" class="org-right">&#xa0;</th>
<th scope="col" class="org-right">&#xa0;</th>
<th scope="col" class="org-right">&#xa0;</th>
<th scope="col" class="org-left">&#xa0;</th>
<th scope="col" class="org-right">&#xa0;</th>
<th scope="col" class="org-left">&#xa0;</th>
<th scope="col" class="org-right">BestFit</th>
</tr>
</thead>

<tbody>
<tr>
<td class="org-right">13174</td>
<td class="org-right">20818</td>
<td class="org-left">09/19/15 12:00 AM</td>
<td class="org-left">입사면접</td>
<td class="org-left">보미건설</td>
<td class="org-right">175</td>
<td class="org-right">88</td>
<td class="org-left">NULL</td>
<td class="org-right">102</td>
<td class="org-right">99</td>
<td class="org-left">NULL</td>
<td class="org-right">94</td>
<td class="org-left">NULL</td>
<td class="org-right">64</td>
<td class="org-right">61</td>
<td class="org-right">102</td>
<td class="org-left">NULL</td>
<td class="org-right">270</td>
<td class="org-left">NULL</td>
<td class="org-right">0</td>
</tr>


<tr>
<td class="org-right">13424</td>
<td class="org-right">20818</td>
<td class="org-left">09/19/15 12:00 AM</td>
<td class="org-left">입사면접</td>
<td class="org-left">보미건설</td>
<td class="org-right">175</td>
<td class="org-right">88</td>
<td class="org-left">NULL</td>
<td class="org-right">102</td>
<td class="org-right">99</td>
<td class="org-left">NULL</td>
<td class="org-right">94</td>
<td class="org-left">NULL</td>
<td class="org-right">64</td>
<td class="org-right">61</td>
<td class="org-right">102</td>
<td class="org-left">NULL</td>
<td class="org-right">270</td>
<td class="org-left">NULL</td>
<td class="org-right">0</td>
</tr>


<tr>
<td class="org-right">15021</td>
<td class="org-right">20818</td>
<td class="org-left">10/20/15 12:00 AM</td>
<td class="org-left">입사면접</td>
<td class="org-left">&#xa0;</td>
<td class="org-right">175</td>
<td class="org-right">88</td>
<td class="org-left">NULL</td>
<td class="org-right">102</td>
<td class="org-right">99</td>
<td class="org-left">NULL</td>
<td class="org-right">94</td>
<td class="org-left">NULL</td>
<td class="org-right">64</td>
<td class="org-right">61</td>
<td class="org-right">102</td>
<td class="org-left">NULL</td>
<td class="org-right">270</td>
<td class="org-left">NULL</td>
<td class="org-right">0</td>
</tr>


<tr>
<td class="org-right">15669</td>
<td class="org-right">20818</td>
<td class="org-left">10/28/15 12:00 AM</td>
<td class="org-left">입사면접</td>
<td class="org-left">면접</td>
<td class="org-right">175</td>
<td class="org-right">88</td>
<td class="org-left">NULL</td>
<td class="org-right">102</td>
<td class="org-right">95</td>
<td class="org-left">NULL</td>
<td class="org-right">87</td>
<td class="org-left">93</td>
<td class="org-right">58</td>
<td class="org-right">61</td>
<td class="org-right">102</td>
<td class="org-left">NULL</td>
<td class="org-right">270</td>
<td class="org-left">NULL</td>
<td class="org-right">1</td>
</tr>


<tr>
<td class="org-right">17676</td>
<td class="org-right">20818</td>
<td class="org-left">11/19/15 12:00 AM</td>
<td class="org-left">입사면접</td>
<td class="org-left">기업 입사</td>
<td class="org-right">175</td>
<td class="org-right">88</td>
<td class="org-left">NULL</td>
<td class="org-right">102</td>
<td class="org-right">95</td>
<td class="org-left">NULL</td>
<td class="org-right">87</td>
<td class="org-left">93</td>
<td class="org-right">58</td>
<td class="org-right">61</td>
<td class="org-right">102</td>
<td class="org-left">NULL</td>
<td class="org-right">270</td>
<td class="org-left">NULL</td>
<td class="org-right">0</td>
</tr>


<tr>
<td class="org-right">19452</td>
<td class="org-right">20818</td>
<td class="org-left">12/12/15 12:00 AM</td>
<td class="org-left">장례식</td>
<td class="org-left">&#xa0;</td>
<td class="org-right">174</td>
<td class="org-right">83</td>
<td class="org-left">41</td>
<td class="org-right">101</td>
<td class="org-right">93</td>
<td class="org-left">NULL</td>
<td class="org-right">88</td>
<td class="org-left">90</td>
<td class="org-right">58</td>
<td class="org-right">61</td>
<td class="org-right">102</td>
<td class="org-left">NULL</td>
<td class="org-right">270</td>
<td class="org-left">NULL</td>
<td class="org-right">1</td>
</tr>
</tbody>
</table>

만약 매번 측정정보를 눈으로 확인하는게 필요하시다면 현재 주문서 정보화면(아래)에서 우측 박스 영역에 보이는 마지막 정보 이외에 좌측에 주문서별 측정 정보를 보여주는 방식등으로 가능할것 같습니다.

![screen_shot_2015-12-14_at_12_03_22_pm](https://cloud.githubusercontent.com/assets/52704/11772032/53da9cfa-a25b-11e5-9e7f-7d920fa46974.png)

## 옷의 치수 변화

역시 DB에서 확인해본 결과 옷의 치수 변화는 따로 기록되는 테이블이 없습니다. 옷의 치수 변화에대해서는 생각해본적이 없었는데 말씀을 들어보니 수선등의 상황에서 의류ID를 동일하게 유지한다면 과거에 대여한 옷과 현재 대여한 옷이 동일한 ID라 하더라도 치수가 달라지기 때문에 예측등에 사용하는 정보로써 정합성에 문제가 발생할 것 같습니다. 현재 수선이 되는 빈도가 어느정도 인지에 따라 우선순위는 다르겠지만 옷의 치수정보도 `order_detail` 테이블에 대여시점마다 기록하는편이 이후 활용에는 용이할것 같습니다.

**Comment by 10001if** [comment]
주문별 신체치수는 말씀해 주신 위치에 보여주시는게 좋겠습니다.
신체 치수의 변화를 알면 대여자와 적극적으로 커뮤니케이션 할 수 있을 것 같습니다.

그리고 의류의 사이즈가 변화하는 것은 필수적으로 발생하게 되므로, 이 부분에 대해 @yongbin 께서 아이디어를 제시해 주시면 감사하겠습니다..

**Comment by keedi** [comment]
12월 30일 완료 일정으로 진행한다고 합니다. via @yongbin

**Comment by yongbin** [comment]
진행시작합니다.

**Comment by yongbin** [comment]
신체치수는 단일 값(컬럼)의 집합이기때문에 `order` 테이블에 치수를 업데이트 하는
방식으로 보존이 가능하지만, 주문의 경우 주문을 구성하는 각각의 옷에따라 사이즈
정보가 다르기때문에 보존을 위해서는 별도의 테이블을 구성해야합니다.

**Comment by yongbin** [comment]
> 주문별 신체치수는 말씀해 주신 위치에 보여주시는게 좋겠습니다.
> 신체 치수의 변화를 알면 대여자와 적극적으로 커뮤니케이션 할 수 있을 것 같습니다.

#688 로 처리했습니다. 남은 내용은 주문시점에 의류사이즈를 별도 테이블로 저장하는 이슈입니다.

**Comment by yongbin** [comment]
각각 대여시점의 의류정보를 기록하는 방법으로 `order_status_log`와 유사하게 `order_size_log` 테이블을 만든뒤 `order_detail` 테이블의 `INSERT` 시점 트리거로 동작시키는 방법이 있습니다.

```SQL
CREATE TABLE `order_size_log` (
  `order_id` int(10) unsigned NOT NULL,
  `clothes_code` int(10) unsigned NOT NULL,
  `timestamp` datetime NOT NULL,
  `category` varchar(32) NOT NULL,
  `color` varchar(32) DEFAULT NULL,
  `gender` varchar(6) DEFAULT NULL COMMENT 'male/female/unisex',
  `neck` int(11) DEFAULT '0',
  `bust` int(11) DEFAULT '0',
  `waist` int(11) DEFAULT '0',
  `hip` int(11) DEFAULT '0',
  `topbelly` int(11) DEFAULT '0',
  `belly` int(11) DEFAULT '0',
  `arm` int(11) DEFAULT '0',
  `thigh` int(11) DEFAULT '0',
  `length` int(11) DEFAULT '0',
  `price` int(11) DEFAULT '0',
  KEY `order_id` (`order_id`),
  KEY `clothes_code` (`clothes_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```


```SQL
INSERT INTO `order_size_log`
(
    `order_id`, `clothes_code`, `timestamp`, `neck`
)
(
    SELECT
            a.order_id
            ,a.clothes_code
            ,now()
            ,b.category
            ,b.color
            ,b.gender
            ,b.neck
            ,b.bust
            ,b.waist
            ,b.hip
            ,b.topbelly
            ,b.belly
            ,b.arm
            ,b.thigh
            ,b.length
            ,b.price
    FROM `order_detail` AS a INNER JOIN `clothes` AS b ON a.`clothes_code` = b.`code`
    WHERE a.order_id = NEW.order_id AND b.code = NEW.clothes_code
    LIMIT 1
)
```

**Comment by yongbin** [comment]
위 트리거를 실서버에 임의로 테스트하다가 다음과 같은 오류로 문제를 발생시켰습니다.

```
[Mon Feb  1 14:30:44 2016] [error] DBIx::Class::Storage::DBI::_dbh_execute(): DBI Exception: DBD::mysql::st execute failed: Column count doesn't match value count at row 1 [for Statement "INSERT INTO `order_detail` ( `clothes_code`, `final_price`, `name`, `order_id`, `price`, `status_id`) VALUES ( ?, ?, ?, ?, ?, ? )" with ParamValues: 0='0B05N', 1='5000', 2="B05N - ë¸<94>ë<9d>¼ì<9a>°ì<8a>¤", 3='22240', 4='5000', 5=19] at /home/opencloset/service/staff.theopencloset.net/bin/opencloset.pl line 5846
[Mon Feb  1 14:30:44 2016] [error] DBIx::Class::Storage::DBI::_dbh_execute(): DBI Exception: DBD::mysql::st execute failed: Column count doesn't match value count at row 1 [for Statement "INSERT INTO `order_detail` ( `clothes_code`, `final_price`, `name`, `order_id`, `price`, `status_id`) VALUES ( ?, ?, ?, ?, ?, ? )" with ParamValues: 0='0B05N', 1='5000', 2="B05N - ë¸<94>ë<9d>¼ì<9a>°ì<8a>¤", 3='22240', 4='5000', 5=19] at /home/opencloset/service/staff.theopencloset.net/bin/opencloset.pl line 5846
```
트리거 발생시접에 INSERT가 처리되지 않아서 발생하는 문제로 로컬에서 충분하게 테스트해보지 않아서 생긴문제입니다. 충분하게 테스트 못한점과, 실서버에 임의반영한점때문에 물의를 일으켰습니다. 죄송합니다. 주의하겠습니다.

**Comment by yongbin** [comment]
#688 에서 사소하지만 디자인 오류가 있습니다. 수정해야합니다.

**Comment by yongbin** [comment]
#712 등을 통해서 기존 1년치 대여자료가 검증되고 수정되었습니다. 지난 1년자료가 현시점을 기준으로 freezing 되었기 때문에 의류정보도 현시점을 기준으로 보존하도록 합니다.

**Comment by yongbin** [comment]
로컬에서 확인해본 결과 위에서 작성한 `order_size_log` 에 몇가지 실수가 있었습니다. 스키마는 아래와 같이 수정되어야 합니다.

```sql
DROP TABLE IF EXISTS `order_size_log`;
CREATE TABLE `order_size_log` (
  `order_id` int(10) unsigned NOT NULL,
  `user_id` int(10) unsigned NOT NULL,
  `clothes_code` char(5) NOT NULL DEFAULT '',
  `timestamp` datetime NOT NULL,
  `category` varchar(32) NOT NULL,
  `color` varchar(32) DEFAULT NULL,
  `gender` varchar(6) DEFAULT NULL COMMENT 'male/female/unisex',
  `neck` int(11) DEFAULT '0',
  `bust` int(11) DEFAULT '0',
  `waist` int(11) DEFAULT '0',
  `hip` int(11) DEFAULT '0',
  `topbelly` int(11) DEFAULT '0',
  `belly` int(11) DEFAULT '0',
  `arm` int(11) DEFAULT '0',
  `thigh` int(11) DEFAULT '0',
  `length` int(11) DEFAULT '0',
  `price` int(11) DEFAULT '0',
  KEY `order_id` (`order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

```

트리거 역시 다음과 같이 수정되어야 합니다.

```sql
DROP TRIGGER IF EXISTS `logging`
CREATE TRIGGER `logging` AFTER INSERT ON `order_detail` FOR EACH ROW
INSERT INTO `order_size_log`
(
    SELECT
            a.order_id
            ,c.id
            ,a.clothes_code
            ,now()
            ,b.category
            ,b.color
            ,b.gender
            ,b.neck
            ,b.bust
            ,b.waist
            ,b.hip
            ,b.topbelly
            ,b.belly
            ,b.arm
            ,b.thigh
            ,b.length
            ,b.price
    FROM `order_detail` AS a 
      INNER JOIN `clothes` AS b ON a.`clothes_code` = b.`code`
      INNER JOIN `order`   AS c ON a.`order_id` = c.`id`
    WHERE a.order_id = NEW.order_id AND a.clothes_code = NEW.clothes_code
    LIMIT 1
)

```

이후 다음 쿼리를 통해서 정상동작 여부를 확인할 수 있습니다.

```sql
INSERT INTO `order_detail` ( `clothes_code`, `final_price`, `name`, `order_id`, `price`, `status_id`) VALUES ( '0J003', '10000', 'J003 - 재킷', '23386', '10000', '19' )
```

**Comment by yongbin** [comment]
로컬에 이 트리거를 적용시킨 뒤 정상동작확인을 위해서 다음 절차를 진행했습니다.

 1. `order_size_log` 테이블 , `logging` 트리거 생성
 2. `order_detail` 테이블에 전체 내용을 CSV로 dump
 3. `order_detail` 테이블 TRUNCATE (테이블은 유지하고 전체 내용 삭제)
 4. `order_detail`에 2번에서 덤프받은 내용을 다시 IMPORT(이과정에서 INSERT 이벤트가 대량발생)
 5. `order_size_log` 내용 확인

전체과정에서 에러발생이 없으며 `order_size_log` 테이블에 자료가 잘 쌓여있는것을 확인할 수 있습니다. 다음 두가지 이슈를 처리하면 이 트리거를 적용하고 현재 시점을 기준으로 한 과거기록을 import 할 수 있을것으로 보입니다.

 - `order_size_log` 테이블 자료의 정합성
 - timestamp 이슈

**Comment by yongbin** [comment]
이 이슈를 진행하다가 `order_size_log` 테이블의 수와 `order_detail`수가 맞지 않는경우를 발견하고 좀더 확인을 해 보던중 이상한 주문서들을 발견했습니다.

 - [ ] https://staff.theopencloset.net/order/93
 - [ ] https://staff.theopencloset.net/order/184
 - [ ] https://staff.theopencloset.net/order/234
 - [ ] https://staff.theopencloset.net/order/286
 - [ ] https://staff.theopencloset.net/order/1037
 - [ ] https://staff.theopencloset.net/order/1558
 - [ ] https://staff.theopencloset.net/order/1598
 - [ ] https://staff.theopencloset.net/order/2009
 - [ ] https://staff.theopencloset.net/order/2127
 - [ ] https://staff.theopencloset.net/order/2492
 - [ ] https://staff.theopencloset.net/order/2678
 - [ ] https://staff.theopencloset.net/order/3320
 - [ ] https://staff.theopencloset.net/order/3460
 - [ ] https://staff.theopencloset.net/order/5995
 - [ ] https://staff.theopencloset.net/order/6210
 - [ ] https://staff.theopencloset.net/order/6792
 - [ ] https://staff.theopencloset.net/order/7918
 - [ ] https://staff.theopencloset.net/order/7921
 - [ ] https://staff.theopencloset.net/order/8089
 - [ ] https://staff.theopencloset.net/order/8634

@10001if 님께 여쭤본 결과 특별한 아이디어가 없습니다.

**Comment by yongbin** [comment]
> 이 이슈를 진행하다가 order_size_log 테이블의 수와 order_detail수가 맞지 않는경우를 발견하고 좀더 확인을 해 보던중 이상한 주문서들을 발견했습니다.

@aanoaa 님께 확인을 요청한 결과 아래와 같이 재현가능한 시스템상에 버그임을 확인했습니다.

> 11:57 hshong: yongbin: 빙고
> 11:57 hshong: 대여화면에서
> 11:57 yongbin: ?
> 11:57 hshong: https://staff.theopencloset.net/rental/2016-02-24
> 11:57 misskim_: [로그인 - 열린옷장] - https://staff.theopencloset.net/rental/2016-02-24
> 11:57 hshong: 여기죠
> 11:57 hshong: 아무튼 저거를 두개 띄워놓은 상태에서
> 11:57 hshong: 한쪽에서 바코드를 찍고 대여할 주문서를 선택해서 `대여` 버튼을 눌르고
> 11:58 hshong: 옆 쪽에서 똑같이 바코드를 찍고 대여를 누르면 저렇게 해서 중복으로 들어 갈 수 있습니다
> 11:58 hshong: 무슨이유에서건 두번 바코드를 찍고 두번 대여버튼을 누른 것 같아요
> 11:58 hshong: 화면이 똑같이 갱신되는게 아니라서
> 11:59 hshong: 같은 옷을 두번 포장하면 저렇게 생기는 것 같아요
> 12:00 yongbin: 아
> 12:00 hshong: A 가 대여 누르면 해당 주문서는 대여 화면에서 안보이기 때문에 괜찮은데
> 12:00 hshong: B가 쓰던 컴터에선 문제가 되는 주문서가 대여 화면에 남아잇을 수 잇죠
> 12:00 yongbin: ㅇㅇ 그러네요
> 12:00 yongbin: 대여로 넘어가는 시점에
> 12:00 yongbin: 값이 이미 있는지 한번더 확인해보는 부분이 추가되거나
> 12:00 yongbin: 그럴꺼 같네요
> 12:01 hshong: 상태로써 체크하면 해결될 수 있습니다
> 12:01 yongbin: 재현이 됏으니까
> 12:01 hshong: 주문서 상태가 포장완료인데
> 12:01 yongbin: 재현됐으니까 그럼 버그로 등록좀 해주세요
> 12:01 hshong: 다시 포장을 하려들면
> 12:01 hshong: 에러
> 12:01 hshong: 이런식으로 처리해주면 될 것 같아요
> 12:01 yongbin: 지금은 사람들이하는 물리적인 프로세스상 발생하기 어려운상황인거 같긴 한데
> 12:01 yongbin: 그래도 이슈는 남아있어야 할거 같아서

이 이슈관련해서는 별도 이슈에서 처리하도록 하겠습니다.

**Comment by aanoaa** [comment]
56037d4750e489c6dd31ab9fda556715c5b3b363 에서 처리하였습니다.

**Comment by yongbin** [comment]
잘못들어가있는 자료는 오늘 업무시간이 종료된 이후 DB에서 직접 삭제하도록 하겠습니다.

**Comment by yongbin** [comment]
@10001if 아래 케이스는 다른경우와 다르게 `final_price`까지도 두번들어가있기때문에 최종 결재금액에 중복된 내용이 반영되어있습니다. 확인부탁드립니다.

 - [ ]  https://staff.theopencloset.net/order/3460 
 - [ ]  https://staff.theopencloset.net/order/7918 
 - [ ]  https://staff.theopencloset.net/order/7921

**Comment by yongbin** [comment]
트리거를 통해서 기록되는 자료의 정합성을 확인하기위해서 로컬에서 다음과 같은 테스트를 진행했습니다.

1 . `order_detail` 를 CSV를 통해 export 
2. `order_size_log` , `order_detail` 을 TRUNCATE
3. 1번에서 export 했던 CSV를 `order_detail`에 다시 IMPORT(이 과정에서 INSERT EVENT 발생)
4. 나온 결과테이블에 대해서 과거 주문자료를 예측에 활용하는 Query를 이용해서 한쪽은 기존 처럼 `clothes`를 통해서 질의하고, 나머지 한쪽은 `query_size_log` 테이블을 통해서 질의(#627)
5. 4번에서 나온 결과를 비교 

### clothes 를 이용하는 쿼리

```sql
    SELECT *
    FROM (
    SELECT          
                    a.`id` AS  `order_id`
                    ,a.`user_id`
                    ,a.`rental_date`
                    ,b.`date` AS `booking_date`
                    ,IF(HOUR(b.`date`) = 19, '1', '0') AS is_online
                    ,a.`bestfit` AS `is_bestfit`
                    ,d.`gender`
                    ,d.`birth`
                    ,YEAR(a.`rental_date`) - d.`birth` + 1 AS `age`
                    ,a.`height`
                    ,a.`weight`
                    ,a.`bust`
                    ,a.`waist`
                    ,a.`hip`
                    ,a.`topbelly`
                    ,a.`belly`
                    ,a.`thigh`
                    ,a.`arm`
                    ,a.`leg`
                    ,a.`knee`
                    ,a.`foot`
                    ,SUBSTR(f.`code`,2)         AS `clothes_code`
                    ,f.`category`               AS `clothes_category`
                    ,f.`bust`                   AS `clothes_bust`
                    ,f.`waist`                  AS `clothes_waist`
                    ,f.`hip`                    AS `clothes_hip`
                    ,f.`topbelly`               AS `clothes_topbelly`
                    ,f.`belly`                  AS `clothes_belly`
                    ,f.`thigh`                  AS `clothes_thigh`
                    ,f.`length`                 AS `clothes_length`
                    ,f.`arm`                    AS `clothes_arm`
    FROM `order` AS a
            INNER JOIN `booking`        AS b ON ( a.`booking_id` = b.`id` )
            INNER JOIN `user`           AS c ON ( a.`user_id` = c.`id` )
            INNER JOIN `user_info`      AS d ON ( d.`user_id` = c.`id` )
            LEFT  JOIN `order_detail`   AS e ON ( a.`id` = e.`order_id` )
            INNER JOIN `clothes`        AS f ON ( e.`clothes_code` = f.`code` )
    WHERE `rental_date` IS NOT NULL 
    ORDER BY `rental_date`, `booking_date`, `order_id`,`clothes_code`
    ) AS x
```

### clothes_size_log 를 이용하는 쿼리

```sql
    SELECT *
    FROM (
    SELECT          
                    a.`id` AS  `order_id`
                    ,a.`user_id`
                    ,a.`rental_date`
                    ,b.`date` AS `booking_date`
                    ,IF(HOUR(b.`date`) = 19, '1', '0') AS is_online
                    ,a.`bestfit` AS `is_bestfit`
                    ,d.`gender`
                    ,d.`birth`
                    ,YEAR(a.`rental_date`) - d.`birth` + 1 AS `age`
                    ,a.`height`
                    ,a.`weight`
                    ,a.`bust`
                    ,a.`waist`
                    ,a.`hip`
                    ,a.`topbelly`
                    ,a.`belly`
                    ,a.`thigh`
                    ,a.`arm`
                    ,a.`leg`
                    ,a.`knee`
                    ,a.`foot`
                    ,SUBSTR(f.`clothes_code`,2)         AS `clothes_code`
                    ,f.`category`               AS `clothes_category`
                    ,f.`bust`                   AS `clothes_bust`
                    ,f.`waist`                  AS `clothes_waist`
                    ,f.`hip`                    AS `clothes_hip`
                    ,f.`topbelly`               AS `clothes_topbelly`
                    ,f.`belly`                  AS `clothes_belly`
                    ,f.`thigh`                  AS `clothes_thigh`
                    ,f.`length`                 AS `clothes_length`
                    ,f.`arm`                    AS `clothes_arm`
    FROM `order` AS a
            INNER JOIN `booking`        AS b ON ( a.`booking_id` = b.`id` )
            INNER JOIN `user`           AS c ON ( a.`user_id` = c.`id` )
            INNER JOIN `user_info`      AS d ON ( d.`user_id` = c.`id` )
            LEFT  JOIN `order_detail`   AS e ON ( a.`id` = e.`order_id` )
            INNER JOIN `order_size_log`        AS f ON ( a.id = f.order_id AND e.`clothes_code` = f.`clothes_code` )
    WHERE `rental_date` IS NOT NULL 
    ORDER BY `rental_date`, `booking_date`, `order_id`,`clothes_code`
    ) AS x
```
### 결과

```
silexui-iMac:Desktop yongbin$ md5 -r query_result-clothes.csv query_result-log.csv
e68103f9ebfd00e78523927a605338ae query_result-clothes.csv
e68103f9ebfd00e78523927a605338ae query_result-log.csv
silexui-iMac:Desktop yongbin$ diff -urN query_result-clothes.csv query_result-log.csv
```

위에서 보는바와 같이 두 결과가 완전히 동일함을 알수 있습니다. 이정도면 `order_size_log` 테이블과 트리거 동작의 안정성에 대해서 신뢰할수 있다고 판단합니다.

**Comment by yongbin** [comment]
`order_size_log` 테이블이 신규 생성과 트리거를 추가해서 실 서버에 배포하는 작업은 오늘 저녁에 반영하도록 하겠습니다.

**Comment by yongbin** [comment]
> @10001if 님께 여쭤본 결과 확실하지는 않지만 과거에 포장을 두군대서 나눠서 진행하던 시절에 양쪽에서 입력이들어가서 발생한 문제일수 있다고 추측했습니다. 그 근거로 2015년 6월 이후로 사례가 없는걸 드셨습니다.

발견했던 20건자료에 대해서 중복된 대여기록을 실서버에서 아래와 같이 삭제했습니다.

```sql
DELETE FROM `order_detail` WHERE `id` IN ('1085','1086','1087','1088','1089','1090');
DELETE FROM `order_detail` WHERE `id` IN ('1152','1153','1154','1155','1156');
DELETE FROM `order_detail` WHERE `id` IN ('1255','1256','1257','1258');
DELETE FROM `order_detail` WHERE `id` IN ('1140','1141','1142','1143');
DELETE FROM `order_detail` WHERE `id` IN ('5837','5838','5839','5840','5841','5842');
DELETE FROM `order_detail` WHERE `id` IN ('8761','8762','8763','8764','8765','8766','8767');
DELETE FROM `order_detail` WHERE `id` IN ('10226','10227','10228','10229','10230','10231');
DELETE FROM `order_detail` WHERE `id` IN ('11237','11238','11239');
DELETE FROM `order_detail` WHERE `id` IN ('12111','12112','12113','12114','12115','12116','12117','12118','12119','12120','12121','12122');
DELETE FROM `order_detail` WHERE `id` IN ('14083','14084','14085','14086','14087');
DELETE FROM `order_detail` WHERE `id` IN ('15514','15515','15516','15517','15518','15519','15520','15521');
DELETE FROM `order_detail` WHERE `id` IN ('19424','19425','19426','19427','19428','19429','19430','19431','19432','19433','19434','19435','19436','19437','19438','19439','19440','19441');
DELETE FROM `order_detail` WHERE `id` IN ('20119','20120','20121','20122','20123','20124','20125','20126','20127','20128','20129','20130','20131','20132','20133','20134','20135','20136','20137','20138','20139','20140','20141','20142','20143','20144','20145','20146','20147','20148','20149','20150','20151','20152','20153','20154','20155','20156','20157','20158','20159','20160','20161','20162','20163','20164','20165','20166','20167','20168','20169','20170','20171','20172','20173','20174','20175','20176','20177','20178','20179','20180','20181','20182','20183','20184');
DELETE FROM `order_detail` WHERE `id` IN ('33748','33749','33750');
DELETE FROM `order_detail` WHERE `id` IN ('35368','35369','35370','35371','35372');
DELETE FROM `order_detail` WHERE `id` IN ('39100','39101','39102','39103','39104','39105');
DELETE FROM `order_detail` WHERE `id` IN ('45884','45885','45886','45887');
DELETE FROM `order_detail` WHERE `id` IN ('45869','45870','45871','45872','47444','47445');
DELETE FROM `order_detail` WHERE `id` IN ('47043','47044','47045','47046','47047','47048','47049','47050');
DELETE FROM `order_detail` WHERE `id` IN ('50986','50987','50988');
```

**Comment by yongbin** [comment]
실서버에 반영완료했으며, 오늘시점으로 과거 대여기록을의 정보를 `order_size_log`에 저장했습니다. import 된 기록의 수는 72548건 입니다.
