### ISSUE TITLE
사용자 정보화면에서 착용날짜 입력란에 2016년이 입력되도록 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#613]
![2015-11-30 6 58 03](https://cloud.githubusercontent.com/assets/4696328/11468622/4f816ffc-9794-11e5-823a-0e23d51cdba7.png)
위의 그림처럼 2016년을 입력할 수 없습니다. 2016년을 입력할 수 있도록 부탁드립니다.

**Comment by keedi** [comment]
#600 과 유사한 이슈입니다.

**Comment by keedi** [comment]
진행합니다.

**Comment by keedi** [comment]
수정 완료한 화면은 다음과 같습니다.

![2015-12-09-134835_1366x768_scrot](https://cloud.githubusercontent.com/assets/138451/11676990/07aa08d0-9e7c-11e5-9816-86b8ef6f5028.png)

**Comment by keedi** [comment]
구현 및 서버에 배포 완료했습니다.
이슈 닫습니다.

**Comment by keedi** [comment]
브라우저 캐시 이슈가 있을 수 있으니 반드시 각 피씨마다 주문서 페이지에서 새로 고침을 한 번은 수행한 후 확인해야 합니다.

**Comment by 10001if** [comment]
확인완료하였습니다.
