### ISSUE TITLE
결제를 진행하면(대여중 상태) 문자로 택배 반납과 대여기간 연장에 관한 안내문구와 URL 발송.

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#614]
현재는 택배 발송의 경우 택배 발송 후 문자로 택배회사와 운송장번호를 보내달라고 요청드리고 있고
대여기간 연장의 경우는 메일로 성함, 전화번호, 연장기간을 받고 있습니다.

하지만 두 과정 모두 확인이 어렵거나 일일이 답장을 해야 하는 이슈가 있어서, 매우 번거로운 상태입니다.

따라서 다음과 같이 요청드립니다.

1. 결제대기에서 주문확정을 하여 대여중으로 상태가 변경되면 다음의 문자가 발송됩니다.

* 택배 반납 시에는 발송확인을 위해 택배 발송 후 다음 URL을 클릭하여 택배회사와 운송장번호를 남겨주세요. 열린옷장 주소와 전화번호 등은 본 URL에서 확인 가능합니다.

* 대여기간 연장이 필요하시면 다음 URL을 클릭하여 성함, 전화번호, 연장기간을 남겨주세요. 연장비용은 본 URL에서 함께 확인하실 수 있습니다.  

2-1. 택배 반납시 발송되는 URL에서는 

*열린옷장 주소 : 서울시 광진구 아차산로 213(화양동 48-3) 웅진빌딩 403호, (우) 05019
전화번호 : 070-4325-7521

* 발송일자 :
* 택배회사 : 
* 운송장 번호 :

-> 입력이 완료되면, 

* 감사합니다. 택배 발송확인을 위한 정보가 정상적으로 접수되었습니다. 

2-2. 대여기간 연장이 필요한 경우 발송되는 URL에서는 

* 이름 :
* 전화번호 :
* 대여일 : 
* 반납예정일 :
* 대여품목 :

이렇게 하면 연장금액이 표시가 되어서 연장금액을 확인 할 수 있도록 진행이 되었으면 좋겠습니다.

**Comment by 10001if** [comment]
@aanoaa 대여자가 입력 후 정보를 확인 할 수 있는 별도의 창이 필요할 것 같은데요. 하시는 업무 마무리 되면 찾아뵙고 말씀드릴게요. 나중에 시간 되실 때 불러주세요~ ^^

**Comment by aanoaa** [comment]
주문서마다 택배반납신청서와 연장신청서를 만들고 사용자가 입력해서
전송할 수 있도록 해야 합니다.

자원봉사프로그램의 수정, 방명록과 같은 기능입니다.
아무나 입력할 수 없도록 해야하므로 주문서마다 인증이 필요합니다.

**Comment by aanoaa** [comment]
이미 사용자에게 나눠주고 있는 안내서에 해당기능을 사용하도록 유도하고
있기 때문에 기능구현의 우선순위가 높습니다.

**Comment by aanoaa** [comment]
사용자가 입력한 내용을 확인할 수 있는 목록도 필요합니다.

**Comment by aanoaa** [comment]
사용자의 입력이 주문서의 `반납방법` 으로 업데이트되면 별도의 목록은
필요가 없습니다.

**Comment by aanoaa** [comment]
연장신청서는 연장료와 반납예정일이 갱신되면 될 것 같습니다.

**Comment by aanoaa** [comment]
SMS 의 링크를 통해 입력할 것이기 때문에 거의 모든 사용자가 모바일로
입력함에 불편함이 없도록 해야합니다.

**Comment by aanoaa** [comment]
택배반납신청서

    GET  /order/:order_id/return?authcode=xxXxxX
    POST /order/:order_id/return

연장신청서

    GET  /order/:order_id/extension?authcode=xxXxxX
    POST /order/:order_id/extension

이렇게 구성하면 어떨까 합니다.

PR 로 만들고 @keedi 님께 confirm 을 받도록 하겠습니다.

**Comment by 10001if** [comment]
여러가지로 많이 바쁘실텐데, 빨리 도움주셔서 정말 감사해요.. ^^

**Comment by aanoaa** [comment]
공휴일과 일요일에는 연장비에 대한 과금을 하지 않고 계산해야 합니다.
그렇게 계산된 추가연장비를 나타내주어야 합니다.

**Comment by aanoaa** [comment]
> 연장신청서는 연장료와 반납예정일이 갱신되면 될 것 같습니다.

이게 아니라 `반납 희망일` 이 변경되어야 합니다.

**Comment by aanoaa** [comment]
추가적인 기능인데,
운송장번호를 입력한 사용자에게는 연체에 관한 문자를 보내지 않도록 합니다.

**Comment by aanoaa** [comment]
스키마 변경없이
`주문서id` + `핸드폰번호` 를 가지고 인증을 하면 아무나 입력할 수 없으니까 괜찮지 않을까 합니다.

**Comment by 10001if** [comment]
연장 안내에서 제가 실수한게 있에요. 총 대여비 30000원 2일 추가하면 12000원입니다. 제가 6000원으로 써놓았거든요~ 수정 부탁드립니다 ^^

**Comment by aanoaa** [comment]
a6f9ef514aafb528526f68817b441867fe30203b
