### ISSUE TITLE
포장완료시 주문서에서 주문서 번호가 아닌 포장완료를 클릭한 순서대로 정렬이 되도록 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#616]
![2015-12-01 4 48 44](https://cloud.githubusercontent.com/assets/4696328/11495056/6bb38356-984b-11e5-96d9-c31a769a6c6b.png)

현재는 주문서 순으로 정렬이 되는데요.
포장을 완료한 순대로 의류들을 결제 하는 곳에 배열하다보니
순서가 뒤죽박죽이 되어서요.
포장완료를 누른 시간 순으로 정렬이 되었으면 좋겠습니다.

**Comment by 10001if** [comment]
@aanoaa 작업 중이시니까.. 이어서 요청을 드려도 괜찮을까요..? ^^;

**Comment by aanoaa** [comment]
제가 잘못 설명드렸습니다.
정렬 기준이 주문서의 id 가 아니라 예약날짜입니다.

이것을

1. 예약날짜
2. 최근 업데이트 순

으로 변경하겠습니다.

**Comment by 10001if** [comment]
확인완료하였습니다. 감사합니다.
