### ISSUE TITLE
에누리 금액을 입력하지 않고 전체 감액하고자 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#617]
![2015-12-03 5 03 49](https://cloud.githubusercontent.com/assets/4696328/11554998/44cbc2d0-99e0-11e5-8b4a-7ab73665f4cc.png)
에누리 항목 옆에 버튼을 달아 클릭을 하면 에누리 전체 금액이 -로 삽입되도록 하였으면 합니다.
그렇게 되면 숫자를 입력하지 않고도 진행할 수 있을 것 같습니다.

**Comment by 10001if** [comment]
안수봉님의 아이디어입니다.

**Comment by keedi** [comment]
진행합니다. :-)

**Comment by keedi** [comment]
구현 완료한 화면은 다음과 같습니다.

![screenshot-localhost 8001 2015-12-11 01-04-45](https://cloud.githubusercontent.com/assets/138451/11720656/9f52459e-9fa3-11e5-8a24-e1877c21c3ad.png)

**Comment by keedi** [comment]
구현 및 서버에 배포 완료했습니다.
이슈 닫습니다.

**Comment by keedi** [comment]
브라우저 캐시 이슈가 있을 수 있으니 반드시 각 피씨마다 주문서 페이지에서 새로 고침을 한 번은 수행한 후 확인해야 합니다.

**Comment by keedi** [comment]
더불어 이슈 특성상 바로 확인이 어려울 수 있으므로 당장 테스트가 힘들다면, 나중에라도 문제가 발생한 경우 꼭 알려주세요. :-)

**Comment by 10001if** [comment]
확인완료하였습니다~ ^^
