### ISSUE TITLE
월요일 예약 슬롯을 2~3명으로 조정

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#618]
월요일 근무자가 5~6명으로 조정됨에 따라 예약 슬롯 조정이 필요하게 되었습니다.

10:00 부터 남자, 여자 인원 각각 3명, 2명으로 조정 요청드립니다.

예)

10:00 남자 3명, 여자 3명
10:30 남자 2명, 여자 2명
11:00 남자 3명, 여자 3명

**Comment by keedi** [comment]
@10001if 월요일 모든 시간에 다 적용인지요?

**Comment by 10001if** [comment]
네! 맞습니다. ^^

**Comment by keedi** [comment]
진행합니다.

**Comment by keedi** [comment]
설정만 변경하면 될 줄 알았는데 기존의 경우 설정이 요일과 상관없이 동일했습니다. 요일을 고려할 수 있도록 설정을 변경하면서 관련해서 코드도 해당 내역을 적용할 수 있도록 수정해야 합니다.

**Comment by keedi** [comment]
구현 및 실서버에 적용 완료했습니다.
이슈 닫습니다. :-)

**Comment by keedi** [comment]
@10001if 정상 동작하는지 확인 부탁드릴게요~ :-)

**Comment by 10001if** [comment]
확인 완료하였습니다.
