### ISSUE TITLE
사용자정보에서 기증한 옷을 클릭하면 기증한 옷의 내역을 확인할 수 있도록 함.

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#624]
![2015-12-10 9 12 16](https://cloud.githubusercontent.com/assets/4696328/11703094/9b1e5e38-9f1f-11e5-8464-da5656126c41.png) 
기증한 옷을 클릭하면 기증에서 기증자 이름으로 검색된 화면으로 이동했으면 합니다. 빌렸던 옷도 클릭할 수가 없는데, 빌렸던 옷의 경우에는 구축되어 있는 페이지가 존재하지 않는 것 같고, 이를 위해 따로 만들어 주셔야 할 것 같은데 어떻게 만드는게 좋을지 특별히 의견이 없기 때문에 우선 기증한 옷을 클릭하면 페이지가 이동할 수 있도록 하는 부분만 작업 요청드립니다.

**Comment by aanoaa** [comment]
기증한 옷에 링크가 추가되었으면 좋겠습니다.
예로 아래처럼..

https://staff.theopencloset.net/donation?q=%ED%95%9C%EB%A7%8C%EC%9D%BC

**Comment by yongbin** [comment]
간단하니까 제가 하겠습니다.

**Comment by yongbin** [comment]
`/donation` 쪽 코드를 확인해보니 `q`의 형태에 따라서 적절하게 검색하도록 작성되어있습니다. 이름은 중복이 가능하지만 email주소는 중복될수 없으니 email주소로 연결되도록 연결하겠습니다. ( @10001if  혹이 문제있으면 다시 알려주세요)

**Comment by yongbin** [comment]
마찬가지로 간단한 작업이니 적절할때 배포해주시면 될거 같습니다.

**Comment by 10001if** [comment]
@yongbin 그렇게 진행해 주시면 될 것 같습니다. 감사합니다. ^^
