### ISSUE TITLE
기증신청을 구글독스로 받지 않고 직접 프로그램을 통해 받도록 함.

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#625]
현재 구글독스를 통해 기증신청을 받고 있습니다. 때문에 이후에 구들독스에 들어온 정보를 프로그램에 옮겨 다시 입력하는 작업을 진행하고 있습니다. 구글독스를 사용하지 않는 방법에 대해서 @keedi 과 논의를 해보아야 할 것 같습니다.

**Comment by aanoaa** [comment]
자원봉사와 같이 신청을 위한 form 과 관리를 위한 목록이 시스템에
반영된다면 좋을 것 같다고 합니다.

**Comment by aanoaa** [comment]
[아름다운가게](https://www.beautifulstore.org/Join/Giving/Join.aspx)의
기증프로세스와 비슷했으면 좋겠다고 합니다.

"기증자가 직접 새옷을 등록한다" 는 아닙니다.
사용할 수 있을지 여부를 staff 이 판단해서 사용가능 한 상태라면
새옷으로 등록할 것이고, 아니라면 그 이후의 절차가 진행되겠죠.

기증자가 웹페이지를 통해 자신의 정보와 기증물품을 입력하면,
원하는 날짜에 택배기사님이 방문해서 수령해오고 하는 절차의 자동화입니다.

------------------------------------

지금의 자원봉사와 좀 비슷합니다.

- 자원봉사를 신청
- staff 이 목록에서 확인후에 진행

**Comment by aanoaa** [comment]
자꾸 도메인이 늘어나는데, donation.theopencloset.net 이 필요하지 않나
싶습니다.

**Comment by aanoaa** [comment]
기증에 관련한 안내와 컨텐츠등이 필요한데 이런거는 @10001if 님이
해주실테니, 현재 google form 에 들어가 있는 내용을 그대로 옮길 수
있도록 합니다.

**Comment by 10001if** [comment]
필요한 부분 여쭤보고, 체크해서 정리하도록 하겠습니다

**Comment by aanoaa** [comment]
지금은 새옷을 등록하면 비로소 기증에 등록됩니다.
기증에 관련된 이슈를 해결하려면 이 절차가 변경될 필요가 있어 보입니다.

https://www.theopencloset.net/apply 에서 처럼 많은 항목을 입력받게됩니다.
이것이 활용될 수 있으면 좋습니다.

1. 온라인으로 기증신청을 하고
2. 확인이 되면 기증내역에 추가
3. 새옷을 등록할때에 선택을 할 수 있도록 변경

해야 하지 않나 싶습니다.


온라인 기증신청 없이 기증들어온 의류들에 대한 처리도 고려해야 합니다.

**Comment by aanoaa** [comment]
제가 생각한 절차입니다.

- 기증신청 form 작성 및 택배전송
- 택배확인 및 신청된 기증 확인
- 기증목록에 추가
- 받은 의류를 새옷등록
- 새옷등록할때에 기증검색을 통해 새옷과 기증을 연결

**Comment by aanoaa** [comment]
donation 에 많은 column 이 추가되어야 할 것 같습니다.

    donation
    +-------------+
    | Field       |
    +-------------+
    | id          |
    | user_id     |
    | message     |
    | create_date |
    +-------------+

- 이름
- 예전에 열린옷장에 기증하신 적이 있나요?
- 예전에 열린옷장에서 대여하신 적이 있나요?
- 생년월일
- 성별
- 전화번호
- 이메일
- 주소
- 보내실 의류 종류
- 보내실 의류 수량
- 열린옷장을 알게된 경로
- 방송매체를 통해 알게된 경우 프로그램 이름을 입력해주세요
- 인터넷 검색을 통해 알게 된 경우, 검색어를 입력해주세요
- 정장을 기증하시게 된 동기가 궁금합니다
- 기증하신 정장이 열린옷장에서 사용되기에 부적합한 경우 다음과 같이 쓰이는 것에 동의하십니까?
- 새로운 시작을 계획하며 열린옷장을 찾아오는 분들에게 본인이 가진 재능까지 나눌 의사가 있으십니까?
- 재능나눔 의사가 있으시다면, 어떤 분야 혹은 어떤 회사에서 일하고 계신지 상세히 알려주세요

기증신청을 할때에 사용자검색을 통해 기증자 본인을 선택하거나 입력할 수 있도록 해야 합니다.

**Comment by aanoaa** [comment]
익명기부를 원하시는 분이 있을텐데,
이런분들은 열린옷장의 주소만 알면 되지 않나요?

익명기부로 등록되고 말이죠.

**Comment by aanoaa** [comment]
@10001if 익명기부에 대해서는 어떻게 해야 할까요?

**Comment by 10001if** [comment]
@aanoaa 익명기부는 없는 것으로 판단하고 진행하시면 됩니다. ^^

**Comment by 10001if** [comment]
## 기증 프로세스 정리 ##

**Comment by 10001if** [comment]
* 기증신청 폼은 다시 정리하여 말씀드리겠습니다.
* 기증신청이 들어오면 확인을 하고 택배를 발송하기 전까지 신청내역을 확인 할 수 있는 리스트가 필요합니다. (현재 기증신청 응답목록의 역할) 주문서를 보면 전체신청, 신청접수, 발송완료, 반송완료 등 처럼 구분된 내역이 필요합니다.
* 택배발송 후에는 대부분 반송을 신청하시므로 택배 발송시 운송장번호를 기입하여 반송신청을 대리할 경우 쉽게 반송신청내역을 확인할 수 있는 것이 필요합니다.
* 반송이 완료되면 기증신청을 한 내역과 대조하고 기증신청은 하였으나, 반송을 신청하지 않거나 보내지 않은 분을 확인 할 수 있어야 합니다. 반송신청접수가 잘 되지 않았는지 여부를 확인하기 위해서 입니다.
* 문자는 총 4회 발송됩니다. 
1. 택배 발송 시 - 반송하는 방법(반송신청 폼)과 손편지 작성요령, 직접 작성 가능한 URL을 전송
2. 반송을 직접하지 못하시는 경우 반송신청 폼으로 이름, 전화번호, 반송가능일를 보내주시고 그 분들의 경우 반송신청이 완료되면 반송예정일 등을 전송
3. 기증품이 열린옷장에 정상도착 했을 때. 잘 받았다는 확인 문자 발송
4. 새옷등록/폐기시 몇 벌의 의류 중 몇 벌이 최종적으로 쓰였는지 안내 문자 발송
* 키디님이 제안해 주셨던 코드북을 통해 기증 품목 전체를 등록하고 열린옷장 사용여부, 옷캔, 비백 등 다른 곳으로 이관된 상황을 등록/관리하려고 합니다.
* 기증신청 응답목록 외에 기증자의 내역을 볼 수 있는 리스트가 필요합니다. 현재는 기증자의 정보를 확인 할 수 있는 리스트 확인을 할 수 있는 곳이 없습니다.

**Comment by aanoaa** [comment]
기증신청을 하고 나면 무언가 완료되었다는 메세지가 전달되어야 할 것입니다.
뭐라고 할까요?

    감사합니다.
    박스가 도착하면 의류를 담아서 반송해주세요.

cc @10001if

**Comment by 10001if** [comment]
OOO님. 기증신청이 정상적으로 접수되었습니다.
기증신청이 접수되면 1-2일 이내(휴일 제외)에 기입해주신 주소로 기증박스를 보내드립니다.
기증박스가 도착하면 기증하실 의류를 박스에 넣어 열린옷장으로 반송해주세요.
감사합니다.

**Comment by aanoaa** [comment]
주소를 직접 넣는 것이 아니라 postcodify 를 활용해서 검색해서 넣을 수 있도록 해야합니다.

**Comment by aanoaa** [comment]
@10001if 필수 입력을 콕 집어주세요.

**Comment by 10001if** [comment]
필수 입력 값은, 이름, 전화번호, 이메일, 주소입니다. 다만, 이메일은 이메일(대여자가 감사메세지를 보낼 수 있도록 활용됩니다.) 라고 적어주시면 될 것 같습니다.

**Comment by 10001if** [comment]
* 상태는 신청 / 발송대기 / 발송완료 / 반송신청 / 반송완료 / 취소 로 진행되면 됩니다.

**Comment by 10001if** [comment]
기증자가 정보를 입력하여 신청을 완료하면 사용자 정보에 등록이 완료되었으면 좋겠습니다. 그리고 이후에 기증행위가 발생하지 않아도(아직 기증 전, 그러나 기증 박스를 준비하다가 바로 메세지를 작성함) 메세지를 입력할 수 있는지 여부가 궁금합니다.

**Comment by aanoaa** [comment]
기증신청서들에 대한 목록이 필요합니다.
현재 재고관리의 `기증` 목록에 어떻게 활용되면 좋을 것 같습니다만, 성격이 달라서
새로운 목록 `기증신청`을 넣을까 합니다.

궁극적으로는 하나로 합쳐져야 하지 않을까 합니다.

**Comment by aanoaa** [comment]
> 기증자가 정보를 입력하여 신청을 완료하면 사용자 정보에 등록이 완료되었으면 좋겠습니다.

이름, 이메일, 전화번호를 입력받기 때문에 가능합니다.

기증신청 목록에서 확인이 되고 나면 등록되는게 어떨까요?

**Comment by aanoaa** [comment]
staff.theopencloset.net 에서 로그인한 사용자는
donation.theopencloset.net 의 private routes 에 접근가능하도록 하려고
합니다.

`theopencloset.net` 서브도메인끼리의 인증문제를 해결해야합니다.

기증목록은 인증된 사용자만 볼 수 있게하되, subdomain 에서는 한번만
인증해서 사용할 수 있게 하기 위함입니다.

subdomain 별로 기능의 모듈화를 위함이기도 합니다.

**Comment by 10001if** [comment]
Page 4 

정장기증신청 
- 기본정보 (1~4번은 필수 입력 값, 5~8번은 선택사항)
1. 이름
2. 연락처
3. 주소 
4. 이메일(대여자가 감사메세지를 보낼 수 있도록 활용됩니다.)
5. 생년월일 
6. 성별
7. 기증경험 
8. 대여경험  

- 기증의류 정보 
1. 보낼 의류 품목 별 수량 
• 자켓 • 팬츠 • 셔츠 / 블라우스 • 구두 • 벨트 • 코트 

- 추가정보 
1. 재기증 동의 
열린옷장에 기증된 의류는 분류과정을 거쳐 활용이 어려운 기증의류는 의미 있게 쓰일 수 있는 곳으로 재기증 되거나 업싸이클링 작업을 통해 새로운 물건으로 재탄생 됩니다. 활용불가 의류 재기증처 옷캔 : 기증된 의류를 제 3세계로 보내 판매한 수익금으로 제 3세계 어린이의 교육개선 사업에 지원합니다. 업싸이클링 협업 비백 : 활용이 힘들거나 손상으로 폐기할 정장의 원단을 공급하여, 협업을 통해 ‘오픈클로젯 백’을 만들어 판매하고 있으며, 판매 수익금의 일부는 기증자를 위한 활동 등에 의미 있게 사용됩니다. 소중한 기증의류가 부득이하게 용도에 따라 분류됨을 양해바랍니다. 위의 분류과정에 동의하십니까? 

2. 재능나눔 의사확인

> 보내드린 이메일에 4번째 단계에서 기증신청서를 작성하는 항목인데요. 구글독스랑 조금 차이가 있는 것 같아 다시 올렸습니다. 이슈 발생할 때 불러주시면 다시 설명 드릴게요. ^^

**Comment by 10001if** [comment]
기증자에게 발송하는 문자메시지 내용입니다. 
메시지에 따라 약간의 차이가 발생하지만 기본적으로 이렇게 보내고 있다고 하네요. 변경될 프로세스에 맞게 내용이 수정될 필요가 있어 보입니다. (가령, 담당자 OOO입니다. 이런 표현은 없어져야 할 것 같기도 하네요) 우선 현재 보내고 있는 내용으로 정리해서 올립니다. 최종 확인은 다시 수정하여 말씀드리겠습니다. ^^

- 기증상자 발송 후
OOO 기증자님 안녕하세요. 저는 열린옷장 기증 담당자 OOO입니다. 기증신청 진심으로 감사드립니다. ^^
의류 보내실 수 있는 기증상자를 댁으로 발송하였습니다. 산간 도서 지방을 제외하고는 약 2~3일 내에 도착하리라 예상됩니다. 

* 기증 방법 안내 
1. 도착한 상자에 의류를 담아주세요. 
2. 동봉한 '나의 정장 기증이야기' 레터지에 기증하시는 옷에 담긴 이야기와 경험, 응원을 담아주세요. 
3. 받으셨던 송장번호로 cj대한통운 택배에 '반송신청'을 해주세요.(착불로 신청!)
[황은진 님 반송 운송장번호 2021-5835-2873] 
전화 반송신청 : 1588-1255
온라인 반송신청 : www.doortodoor.co.kr 

기증과정에서 불편한 점 있으시면 언제라도 연락주세요. 다시 한 번 기증신청 감사드립니다.^^ 
열린옷장 OOO 드림.

- 기증상자 확인 후 

(모두사용)
OOO 기증자님, 안녕하세요. 열린옷장 기증 담당자 OOO입니다. 
보내주신 기증의류와 기증메시지 잘 도착했습니다. 감사드립니다 😍 
보내주신 의류 잘 관리해서 더 많은 분들이 입으실 수 있도록 노력하겠습니다. 
나눠주신 행복보다 더 큰 행복으로 늘 가득하시길 바랍니다. 고맙습니다. 💕 
열린옷장 OOO 드림 

(사용/옷캔)
OOO 기증자님, 안녕하세요. 열린옷장 기증 담당자 OOO입니다. 
보내주신 기증의류와 기증이야기 잘 도착했습니다. 감사드립니다 😍 
보내주신 의류들 꼼꼼하게 확인해보았습니다. 확인 결과, 보내주신 의류 중 남성 정장 한 벌이 저희 열린옷장에서 사용될 예정입니다. 소중한 기증의류 많은 분들이 입으실 수 있도록 노력하겠습니다^^ 

그리고 다른 한 벌은 열린옷장에서는 쓰임이 어려워 재기증이 진행되었습니다. 재기증은 '옷캔(otcan)'이라는 비영리단체로 이루어졌으며, 제 3세계 어린이들의 교육개선을 위해 노력하는 곳입니다! 더 가치있게 쓰일 수 있도록 노력하고 있으니 재기증이 진행된 점 양해부탁드립니다. 
나눠주신 행복보다 더 큰 행복으로 늘 가득하시길 바랍니다. 고맙습니다. 💕 
열린옷장 OOO 드림 

(사용/비백)
OOO 기증자님, 안녕하세요. 열린옷장 기증 담당자 OOO입니다. 
보내주신 기증의류 잘 도착했습니다. 감사드립니다 😍 
보내주신 의류들 꼼꼼하게 확인하고 논의해보았습니다. 그 결과 남성수트(3set), 셔츠(6), 구두(1), 벨트(2)가 저희 옷장에서 사용될 예정입니다. 소중한 기증 의류 많은 분들이 멋지게 입으실 수 있도록 최선을 다하겠습니다 ^^

그리고 다른 의류는 저희 옷장에서 쓰이지 않을 거 같아서요. 너무 안타깝지만 재기증이 진행될 예정입니다. 재기증은 업사이클링 기업인 B.bag으로 이루어집니다. B.bag으로 간 옷은 예쁜 가방으로 재탄생 예정이에요~ 더 가치있는 쓰임을 위해 재기증이 이루어지오니 양해바랍니다! 
열린옷장에 나누어주신 마음에 감사드리며, 나눠주신 행복보다 더 큰 행복으로 늘 가득하시길 바랍니다. 고맙습니다. 💕 
열린옷장 OOO 드림 

- 폐기 후 알림 
OOO 기증자님 안녕하세요^^ 저는 열린옷장에서 기증 담당하는 OOO입니다. 
저희 열린옷장과 봄에 인연을 맺고 벌써 겨울이 되었네요^^ OO님과 같은 기증자님들의 응원으로 열린옷장은 더 활짝 열린 마음으로 열심히 일하고 있답니다^^ 그동안 OO님께서 기증해주신 의류 중 수트 세 벌이 열린옷장에서 그 역할을 다해 부득이하게 폐기 되었다는 점을 알려드립니다. 😭😭😭 

요번에 연락드리면서 확인해보니 OO님께서 기증하신 의류는 수트 두 벌이 남아있더라구요. 옷장에 있는 옷들 많은 분들과 나누고 또 소중히 잘 관리하겠습니다^^ 벌써 한 해가 지고 있는데요, 열린옷장과 나누셨던 마음 기억하면서 더 따뜻하게 한 해 마무리하세요💕💕 언제나 감사드립니다! 
열린옷장 OOO 드림

**Comment by aanoaa** [comment]
subdomain 에서 쿠키를 공유해서 사용하기 위해 프로그램이
변경되었습니다.

배포될때 설정파일의 수정이 필요합니다.

    secrets       => [$ENV{OPENCLOSET_SECRET}],
    cookie_domain => '.theopencloset.net',

환경변수를 이용하거나 설정파일에 직접 적어줘야 합니다.

**Comment by aanoaa** [comment]
>  상태는 신청 / 발송대기 / 발송완료 / 반송신청 / 반송완료 / 취소 로 진행되면 됩니다.

- 신청되었을때의 상태가 `신청` 인가요?
- 언제 발송대기/발송완료/반송신청/취소 로 변경되나요?

운송장을 입력했을때?
반송버튼을 눌렀을때?
기증자로부터 연락을 받아서 상태를 변경할 필요가 있나요?

**Comment by aanoaa** [comment]
https://www.doortodoor.co.kr/parcel/doortodoor.do

에서 검색 가능한 운송장 번호와 전화번호가 필요합니다.

**Comment by aanoaa** [comment]
`배송중` 에서 택배를 받은 후에 자동으로 `배송완료` 상태로 변경해야 합니다.

**Comment by aanoaa** [comment]
상태입니다.

- 신청
- 발송대기
- 배송중 <- new
- 발송완료
- 반송신청
- 반송완료
- 취소

**Comment by aanoaa** [comment]
재고관리에서는 링크만 제공하고 실제구현은 https://github.com/opencloset/donation/issues/1 에서 진행하도록 하겠습니다.
