### ISSUE TITLE
사용자정보에서 신체치수를 입력하면 선행정보에 따라 변화한 평균값을 보여줌

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#626]
본 이슈는 #566 과 유사합니다.
하지만, 566번 이슈는 키와 몸무게의 평균만 보여주지만
본 이슈에서는 키, 몸무게, 가슴둘레, 허리둘레, 윗배둘레, 배꼽둘레, 허벅지둘레, 엉덩이둘레 순으로 
선행정보에 따라 변화한 평균값을 나타내주었으면 좋겠습니다.

목둘레, 팔길이, 다리길이, 무릎길이, 발크기, 다리길이는 키와 몸무게로 예측한 결과 값과 크게 다르지 않을 것으로 보입니다. 

1. 그래서 키, 몸무게, 가슴둘레, 허리둘레, 윗배둘레, 배꼽둘레, 허벅지둘레, 엉덩이둘레만 선행정보에 따라 변화한 평균값을 보여주고

2. 목둘레, 팔길이, 다리길이, 무릎길이, 발크기, 다리길이는 기존처럼 키/몸무게의 평균값을 보여주었으면 합니다.

본 정보는 신체사이즈 우측에 보여지고, 키/몸무게로 계산한 평균값은 가장 우측에 보여지도록 하여 총 3개의 사이즈가 사이즈 정보에 나타나도록 하였으면 좋겠습니다.

**Comment by yongbin** [comment]
워크샵때 논의되었던 이슈입니다. `/user/:id` 하부에서 키,몸무게등 사이즈를 입력할때 값을 입력해 나갈수록 평균을 구하는 대상의 범위를 좁혀 아직 입력하지 않은 치수의 평균값을 구해서 보여주는 기능입니다. @keedi 님과 논의한 결과 기존 평균을 보여주는것과 동일한 화면에서 추가적으로 값을 제시해주는 방법이 제안되었습니다.

![screen_shot_2015-12-14_at_12_29_55_pm](https://cloud.githubusercontent.com/assets/52704/11772329/dc2f2e7e-a25e-11e5-8bd3-4a81c5a56b00.png)

치수측정의 입력순서등의 이슈를 좀 더 논의해야할 것 같습니다.

**Comment by keedi** [comment]
치수 측정의 입력 순서는 필요 없습니다.
그냥 구하면 됩니다.

이미 기존 평균도 입력 순서와 별개로 구하고 있습니다.

**Comment by keedi** [comment]
진행합니다.

**Comment by keedi** [comment]
@10001if wrote:
> 본 정보는 신체사이즈 우측에 보여지고, 키/몸무게로 계산한 평균값은 가장 우측에 보여지도록 하여 총 3개의 사이즈가 사이즈 정보에 나타나도록 하였으면 좋겠습니다.

흠 보여지는 위치 때문에 문의를 드리려고 했었는데요...

@yongbin:

> @keedi 님과 논의한 결과 기존 평균을 보여주는것과 동일한 화면에서 추가적으로 값을 제시해주는 방법이 제안되었습니다.

정리하면 현재는 가장 좌측에 신체 치수가 보이고 바로 옆에 괄호로 평균과의 차이가 보이고 그 오른쪽 옆에 평균 값이 보입니다.

@10001if 님의 원 요청 사항은 신체 치수가 보인 뒤 변화한 평균 값, 그리고 평균 값을 보여달라는 것입니다.

그런데 이때 확인할 것이 원래대로 보이던 평균값과 사용자의 차이 값은 그럼 어느 위치에서 보여야 하냐는 것입니다. 좌측이 신체치수 최 우측이 평균 가운데가 변화 평균이라고 쳤을때 신체 치수 옆에 예전처럼 보이면 되는 것인지 아니면 이것이 헷갈리니까 다른 곳에 보여야 할 것인지가 의문입니다.

@yongbin 님께서 그려주신 그림대로라면 평균값 우측에 보이는 것인데 이것을 원하시는 것인지 아니면 배치를 어떻게 하실 것인지 답변 부탁드릴게요.

**Comment by keedi** [comment]
일단 @10001if 님의 답변을 듣기 전 구현한 화면은 다음과 같습니다.

![screenshot-monster silex kr 10301 2015-12-16 20-42-56](https://cloud.githubusercontent.com/assets/138451/11840001/aa518ab8-a435-11e5-8a11-c192fb66fc14.png)

조심스럽게 예측하자면 과연 이 기능이 유용할지는 조금 회의적입니다.
어쨌든 자세한 사항은 내일 미팅시 이야기 나누도록 하겠습니다.

**Comment by keedi** [comment]
미팅 했습니다. 우선 구현한 방식인 우측에 표기 되도록 하는 것도 상관없다고 합니다. 그대로 진행합니다.

**Comment by keedi** [comment]
구현 및 서버에 배포 완료했습니다.

이슈 닫습니다. :)

**Comment by 10001if** [comment]
지금 확인해보니 @yongbin 우려해 주시고 @keedi 께서 회의적이라는 의미를 정확히 알 것 같습니다. 이렇게 해서는 기능의 활요도가 매우 낮을 것 같습니다. 추가적으로 작업을 요청드리고 싶은데요. 그렇다면 방법은 동일하나 키, 몸무게, 가슴둘레, 허리둘레, 윗배둘레, 배꼽둘레, 허벅지둘레, 엉덩이둘레만 선행정보에 따라 변화한 평균값을 보여주지만 모든 키, 몸무게, 가슴둘레부터 엉덩이둘레까지 넣는 값의 -1 ~ +1값의 평균값을 보여주시면 좋겠습니다.

가령,                  평균(기존과 동일)        선행변수 평균
키 180                                               
몸무게 73
목둘레 36
가슴둘레 96                                               96 (95~97 값의 평균)
허리둘레 84                                               85 (83~86 값의 평균)
~~

**Comment by keedi** [comment]
구현 및 배포 완료했습니다.
다만 범위를 지정했기 때문에 이전 보다는 값을 보여줄 확률은 높아졌지만
그래도 체감상은 비슷하실겁니다. ㅎㅎ

이슈 닫습니다.

**Comment by keedi** [comment]
확인 부탁드립니다.

**Comment by 10001if** [comment]
네.. 이런다고 갑자기 숫자들이 튀어나오진 않겠지요? ㅠ 추론이 필요할텐데.. 여튼 감사합니다! 사용해보고 다시 말씀드릴게요. ^^

**Comment by 10001if** [comment]
우선 확인 완료하였습니다.
