### ISSUE TITLE
신체치수로 검색하여 잘 맞을 의류를 검색하여 보여줌

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#627]
@yongbin 

남자 자켓은 팔길이
남자 바지는 다리길이

여자 자켓은 추가된 것 없음 
여자 스커트는 스커트 길이

**Comment by keedi** [comment]
본 이슈를 끝내는 기준이 아닌 개발자가 열람할 수 있는수 준까지 끝내는 것의 예상 데드라인이 21일 월요일이라고 합니다. via @yongbin

**Comment by keedi** [comment]
웹과 연동해서 완전히 끝내는 것은 23일 수요일 일정이라고 합니다. via @yongbin

**Comment by yongbin** [comment]
**신체치수로 잘 맞을 의류를 검색** 기능은 다음과 같은 흐름으로 동작합니다.

1. 기존 대여기록의 자료를 모델로 학습시켜 예측할 수 있는 모델을 만든다.
2. 1)에서 만든 모델을 REST API로 접근할 수 있는 형태로 제공한다.
3. 사용자의 신체치수를 2) REST API 로 호출해서 사용자에게 가장 잘 맞을 옷의 **사이즈** 를 얻는다.
4. 3) 에서 얻은 사이즈로 DB검색을 통해 사용자에게 빌려줄 수 있는 옷들을 특정한다.

### 1. 모델

모델의 구축은 2015년 5월 김상진님과 열린옷장 한만일 대표님, 그리고 Silex 유용빈이 논의해서 1차 진행했습니다. 김상진님께 최종적인 통계분석용 R 코드를 전달받은시점은 9월 9일이며 해당 코드를 리팩토링해서 재사용하기 용이한 형태로 개선완료한 시점은 12월 5일경입니다.  모델은 다음과 같은 특징을 가지고 있습니다. 

 - [randomforest](https://cran.r-project.org/web/packages/randomForest/index.html) 알고리즘을 이용한 학습/예측 방법 사용
 - 남성,여성의 상의, 하의 4가지 경우에 대한 예측 제공
 - 각각의 경우의 수에 대해서 2가지 주요 옷의 치수를 제공
 - 기존 대여자료중 베스트핏 자료들을 학습에 사용함

 이 모델과 관련한 좀 더 상세한 내용은 리펙토링 과정을 정리한 [문서](https://github.com/yongbin/refactoring-r/blob/master/refactoring-r.org) 를 참고하면 됩니다. 

### 2. REST API 구축

작성된 R 코드를 REST API 형태로 연결시키는것은 [OpenCPU](https://www.opencpu.org/)를 활용했습니다. OpenCPU는 R을 사용해 작성된 수리/통계 관련 연산을 HTTP API 형태로 손쉽게 노출할 수 있도록 고안된 도구입니다. 

silex 내부 장비중 LXC로 운영되는 장비들의 경우 OpenCPU 구축후 커널리소스 관련 오류를 발생시키는 문제가 있어서 물리장비인 brompton 에 구축했습니다. debian 장비에서 OpenCPU를 구축시키는 방법은 아래 문서에 자세히 설명되어있으며 brompton 에 구축은 아래내용과 동일하게 진행했습니다.

https://github.com/jeroenooms/opencpu-server/tree/master/debian#readme

그리고 기존 1에서 작업했던 코드를 R package 형태로 만들어서 사용자 이름공간이나 서버 이름공간으로 배포해야만 OpenCPU에서 접근할 수 있기 때문에 기존 코드와 구동코드를 간단한 R package형태로 만드는 작업도 별도로 진행했습니다.

추가적으로, OpenCPU가 내부적으로 session을 24시간마다 초기화하며 매번 새롭게 생성한 세션이름을 돌려주는 방식으로 구현되어있는데 우리의 경우 웹 응용프로그램이 접근해야 하는 API의 접근지점(end-point)가 동일하게 유지되어야 하기 때문에 심볼릭 링크를 이용해서 별도의 API endpoint 이름을 재지정해 주는 작업과, 세션의 유지에 대한 예외처리를 하는 부분을 추가적으로 작업했습니다. 관련 상세내용을 별도로 정리하겠습니다.

### 3. REST API 사용

OpenCPU의 REST API  사용방법은 아래문서에 잘 정리되어있습니다.

https://www.opencpu.org/api.html

핵심적으로 현재 서버에 배포되어있는 기능중 예측과 관련된 호출부분은 아래와 같습니다.

### 질의

```sh
curl http://brompton.silex.kr//ocpu/tmp/ocarina/R/male -d "height=183 &weight=82 &bust=102 &waist=88 &topbelly=85 &thigh=61 &arm=64 &leg=105"
```

### 결과

```
     /ocpu/tmp/x086109d51c/R/.val
     /ocpu/tmp/x086109d51c/stdout
     /ocpu/tmp/x086109d51c/source
     /ocpu/tmp/x086109d51c/console
     /ocpu/tmp/x086109d51c/info
     /ocpu/tmp/x086109d51c/files/DESCRIPTION
```

### 2차 질의

```sh
curl http://brompton.silex.kr//ocpu/tmp/x086109d51c/R/.val/json
```

### 결과

```
{
  "jacket": {
    "bust": [99.1105],
    "topbelly": [90.4439],
    "arm": [62.2842]
  },
  "pants": {
    "thight": [62.9617],
    "waist": [83.459]
  }
}
```

즉 남성을 기준으로 할때 `http://brompton.silex.kr//ocpu/tmp/ocarina/R/male` API 요청에 인자들을 넣어서 전달하면 결과값을 볼 수 있는 자료의 URL이 돌아오면 해당 URL을 호출하면 JSON 형태로 예측값을 얻어올 수 있는 구조입니다. 서버의 설정상 예측 API 세션은 서버가 가동되고 있는 동안계속 유지되며, 질의를 통해 얻어온 결과 세션은 10분마다 서버에서 삭제됩니다. 

### 4. DB Query

위 질의 (한만일 대표님의 신체사이즈)에 대한 예측 결과를 기준으로 서버에 전달하는 실제 의류검색 쿼리는 아래와 같습니다.

```SQL
    SELECT
            b.name
            ,y.*
            ,x.rent_count
    FROM
        (
            SELECT
                    b.clothes_code
                    ,SUM(DATEDIFF(a.`return_date`, a.`rental_date`))        AS rent_count
            FROM
                    `order` AS a LEFT JOIN `order_detail` AS b ON a.id = b.order_id
            WHERE
                    b.clothes_code IS NOT NULL
                    AND a.return_date IS NOT NULL
            GROUP BY b.clothes_code
        ) AS x INNER JOIN `clothes` AS y ON x.`clothes_code` = y.`code`
        INNER JOIN `donation` AS a ON y.`donation_id` = a.id
        INNER JOIN `user`     AS b ON a.`user_id` = b.id
    WHERE
        y.`bust` BETWEEN 99 AND 100
        AND y.`topbelly` BETWEEN 90 AND 91
        AND y.`arm`      BETWEEN 62 AND 63
        AND y.`category` = 'jacket'
        AND y.`gender`   = 'male'
        AND y.`status_id` = 1
    ORDER BY x.`rent_count` DESC
```

예측에서 나왔던 bust 99.1105 를 버림과 올림을 취해 99~100, 마찬가지로 topbelly 90~91, arm 62~63 범위로 지정했으며 대여가능(`status_id` = 1) 인 옷을 검색했을때 결과는 7벌이나옵니다.

**Comment by yongbin** [comment]
나온 결과를 바탕으로 @10001if 님과 검색기능과 관련해서 구체적인 이야기를 더 나눴습니다. 추가적으로 기존에는 고려하지 않았던 대여가능한 **세트** 개념이 도입되면서 큰틀에서 검색기능은 다음과 같은 흐름으로 구현되어야 할것으로 확인되었습니다.

 1. 기존 예측을 통해 상의와 하의 **사이즈** 를 얻는다. 
 2. 상의를 일정 수준의 마진(1~2)범위의 검색하되, 이때 기존 대여기록에서 **가장 많이 함께** 대여된 하의의 사이즈가 하의의 예측수준 범위 밖이면 목록에서 제거한다. 
 3. 최종적으로 상의를 선택하면 기존에 가장 많이 함께 대여되었던 하의를 같이 제시한다.
 4. 만약 검색결과의 수가 적을 경우 마진의 범위를 점진적으로 늘려 일정수 이상의 검색 결과를 확보한다. 

기존에 생각했던 방식의 검색과는 조금 다르지만 현재 열린옷장에서 오프라인/온라인대여시 가장 필요한 워크플로우라고 하시기 때문에 일단 말씀하신 내용을 있는그대로 구현하기위해서 노력하겠습니다.(위 내용들 중 4번은 현재로서 우선순위가 낮습니다)

검색 UI와 관련해서는 구체적으로 다음과 같은 요구사항을 말씀하셨습니다.

 * 별도 메뉴를 통해서 제공
 * 기존 사용자메뉴에서 링크를 통해서 별도의 사이즈 입력없이 질의 가능하도록 기능 제공
 * 모니터와 연동

이 내용중 모니터를 제외한 부분은 참고해서 진행하도록 하겠습니다. 모니터와 연동부분은 기능구현이 완료된 이후에 형석님과 상의하도록 하겠습니다.

**Comment by yongbin** [comment]
> 상의를 일정 수준의 마진(1~2)범위의 검색하되, 이때 기존 대여기록에서 가장 많이 함께 대여된 하의의 사이즈가 하의의 예측수준 범위 밖이면 목록에서 제거한다.
> 최종적으로 상의를 선택하면 기존에 가장 많이 함께 대여되었던 하의를 같이 제시한다.

이 내용을 구현하기 위해서는 각 상의와 함께 가장 많이 대여된 하의의 세트(pair)를 뽑아내는 쿼리가 필요합니다.

아래 쿼리를 통해서 남성의 `jacket`과 `pants`의 세트별 대여수를 확인할 수 있습니다. 

```sql
              SELECT
                  `jacket`
                  ,`pants`
                  ,COUNT(*) AS 'rent_count'
              FROM
              (
                  SELECT
                      `gender`
                      ,MAX(CASE WHEN b.`category` = 'jacket' THEN `clothes_code` END)            AS 'jacket'
                      ,MAX(CASE WHEN b.`category` = 'pants'  THEN `clothes_code` END)            AS 'pants'
                  FROM        `order_detail` AS a INNER JOIN `clothes` AS b ON a.`clothes_code` = b.code
                  WHERE       b.`category` IN ('jacket', 'pants')
                  GROUP BY    `order_id`
                  HAVING      `gender` = 'male'
              ) AS x
              WHERE       `jacket` IS NOT NULL AND `pants` IS NOT NULL
              GROUP BY    `jacket`,`pants`
```

결과는 아래와 같습니다.

| jacket | pants | rent_count |
|-------- | ------- | ------------|
| 0J00I  | 0P0IU |          1 |
| 0J00X  | 0P02Z |         25 |
| 0J00Y  | 0P02Y |         26 |
| 0J00Z  | 0P0BK |         26 |
| 0J00Z  | 0P0MU |          1 |
| 0J013  | 0P0BA |         14 |
| 0J015  | 0P02T |          1 |
| 0J01Y  | 0P04M |         21 |
| 0J01Z  | 0P031 |         21 |
| 0J022  | 0P00O |         11 |
| 0J025  | 0P16G |          6 |

이 결과를 바탕으로 세트검색결과에 사이즈 검색결과를 결합한 최종적인 쿼리는 아래와 같습니다.

```sql
      SELECT
          d.name
          ,a.rent_day_count
          ,b.code
          ,b.category
          ,b.gender
          ,b.neck
          ,b.bust
          ,b.waist
          ,b.hip
          ,b.topbelly
          ,b.belly
          ,b.arm
          ,b.thigh
          ,b.length
          ,b.color
          ,b.gender
          ,e.rent_count
          ,f.code
          ,f.category
          ,f.gender
          ,f.neck
          ,f.bust
          ,f.waist
          ,f.hip
          ,f.topbelly
          ,f.belly
          ,f.arm
          ,f.thigh
          ,f.length
          ,f.color
          ,f.gender
      FROM
          (
              SELECT
                      `clothes_code`
                      ,SUM(DATEDIFF(a.`return_date`, a.`rental_date`))        AS 'rent_day_count'
              FROM
                      `order` AS a LEFT JOIN `order_detail` AS b ON a.id = b.order_id
              WHERE
                      b.`clothes_code`    IS NOT NULL
                      AND a.`return_date` IS NOT NULL
              GROUP BY b.`clothes_code`
          ) AS a
          INNER JOIN `clothes`  AS b ON a.`clothes_code` = b.`code`
          INNER JOIN `donation` AS c ON b.`donation_id`  = c.id
          INNER JOIN `user`     AS d ON c.`user_id`      = d.id
          INNER JOIN
          (
              SELECT
                  `jacket`
                  ,`pants`
                  ,COUNT(*) AS 'rent_count'
              FROM
              (
                  SELECT
                      `gender`
                      ,MAX(CASE WHEN b.`category` = 'jacket' THEN `clothes_code` END)            AS 'jacket'
                      ,MAX(CASE WHEN b.`category` = 'pants'  THEN `clothes_code` END)            AS 'pants'
                  FROM        `order_detail` AS a INNER JOIN `clothes` AS b ON a.`clothes_code` = b.code
                  WHERE       b.`category` IN ('jacket', 'pants')
                  GROUP BY    `order_id`
                  HAVING      `gender` = 'male'
              ) AS x
              WHERE       `jacket` IS NOT NULL AND `pants` IS NOT NULL
              GROUP BY    `jacket`,`pants`
          ) AS e ON e.jacket = b.code
          INNER JOIN `clothes` AS f ON e.pants = f.code
      WHERE
          b.`category` = 'jacket'
          AND b.`gender`   = 'male'
          -- jacket size
          AND b.`bust`        BETWEEN 97 AND 101                      -- 99.1105 +/- 2
          AND b.`topbelly`    BETWEEN 88 AND  92                      -- 90.4439 +/- 2
          AND b.`arm`         BETWEEN 61 AND  63                      -- 62.2842 +/- 1
          -- pants size
          AND f.`thigh`       BETWEEN 60 AND  64                      -- 62.9617 +/- 2
          AND f.`waist`       BETWEEN 83 AND  85                      -- 83.459  +2
          AND b.`status_id` = 1
      ORDER BY `rent_count` DESC
```
결과는 다음과 같습니다. 

| name           | rent_day_count | code  | category | gender | neck | bust | waist | hip | topbelly | belly | arm | thigh | length | color        | gender | rent_count | code  | category | gender | neck | bus | wist | hip | topbelly | belly | arm | thigh | length | color        | gender |
|---------------- | ---------------- | ------- | ---------- | -------- | ------ | ------ | ------- | ----- | ---------- | ------- | ----- | ------- | -------- | -------------- | -------- | ------------ | ------- | ---------- | -------- | ------ | ----- | ------ | ----- | ---------- | ------- | ----- | ------- | -------- | -------------- | --------|
| 더셔츠스튜디오 |            154 | 0J0Q8 | jacket   | male   |    0 |  101 |     0 |   0 |       92 |     0 |  61 |     0 |      0 | navy         | male   |         44 | 0P0AE | pants    | male   |    0 |   0 |   85 |   1 |        0 |     0 |   0 |    63 |    113 | navy         | male   |
| 더셔츠스튜디오 |            152 | 0J0OW | jacket   | male   |    0 |   98 |    83 |   0 |       88 |     0 |  63 |    63 |    113 | navy         | male   |         40 | 0P050 | pants    | male   |    0 |  98 |   83 |   0 |       88 |     0 |  63 |    63 |    113 | navy         | male   |
| 하지현         |            127 | 0J141 | jacket   | male   |    0 |  101 |     0 |   0 |       88 |     0 |  62 |     0 |      0 | navy         | male   |         37 | 0P0LA | pants    | male   |    0 |   0 |   83 |   1 |        0 |     0 |   0 |    64 |    110 | navy         | male   |
| 더셔츠스튜디오 |            100 | 0J0Q6 | jacket   | male   |    0 |  101 |     0 |   0 |       92 |     0 |  63 |     0 |      0 | navy         | male   |         29 | 0P0AI | pants    | male   |    0 |   0 |   84 |   1 |        0 |     0 |   0 |    63 |    114 | navy         | male   |
| 더셔츠스튜디오 |            104 | 0J0PQ | jacket   | male   |    0 |  100 |     0 |   0 |       91 |     0 |  63 |     0 |      0 | navy         | male   |         27 | 0P0B1 | pants    | male   |    0 |   0 |   85 |   0 |        0 |     0 |   0 |    63 |    113 | navy         | male   |
| 김지혜         |             97 | 0J09R | jacket   | male   |    0 |   98 |     0 |   0 |       91 |     0 |  62 |     0 |      0 | black        | male   |         26 | 0P089 | pants    | male   |    0 |   0 |   84 |   1 |        0 |     0 |   0 |    62 |    106 | black        | male   |
| 이상욱         |             96 | 0J00Z | jacket   | male   |    0 |   99 |     0 |   0 |       90 |     0 |  63 |     0 |      0 | navy         | male   |         26 | 0P0BK | pants    | male   |    0 |   0 |   84 |   1 |        0 |     0 |   0 |    64 |    111 | navy         | male   |
| 배성우         |            109 | 0J1JD | jacket   | male   |    0 |  100 |     0 |   1 |       92 |     0 |  63 |     0 |      0 | black        | male   |         18 | 0P0P8 | pants    | male   |    0 |   0 |   84 |   1 |        0 |     0 |   0 |    63 |    105 | black        | male   |
| 선호동         |             37 | 0J0CS | jacket   | male   |    0 |   99 |     0 |   0 |       91 |     1 |  63 |     0 |      0 | black        | male   |         10 | 0P0MH | pants    | male   |    0 |   0 |   85 |   1 |        0 |     0 |   0 |    64 |    108 | black        | male   |
| 더셔츠스튜디오 |             34 | 0J0LD | jacket   | male   |    0 |   98 |     0 |   0 |       90 |     1 |  62 |     0 |      0 | navy         | male   |          8 | 0P1C9 | pants    | male   |    0 |   0 |   83 |   1 |        0 |     0 |   0 |    61 |    114 | navy         | male   |
| 이민우         |             28 | 0J0F7 | jacket   | male   |    0 |  101 |     0 |   0 |       92 |     0 |  61 |     0 |      0 | navy         | male   |          7 | 0P0DH | pants    | male   |    0 |   0 |   84 |   1 |        0 |     0 |   0 |    64 |    106 | navy         | male   |
| NH농협생명     |              9 | 0J0RA | jacket   | male   |    0 |   99 |     0 |   0 |       92 |     0 |  62 |     0 |      0 | gray         | male   |          3 | 0P0AO | pants    | male   |    0 |   0 |   83 |   1 |        0 |     0 |   0 |    60 |    102 | gray         | male   |
| 더셔츠스튜디오 |             13 | 0J0LC | jacket   | male   |    0 |   98 |     0 |   0 |       90 |     1 |  63 |     0 |      0 | navy         | male   |          2 | 0P1C8 | pants    | male   |    0 |   0 |   83 |   1 |        0 |     0 |   0 |    62 |    115 | navy         | male   |
| 김태훈         |              9 | 0J0KB | jacket   | male   |    0 |   98 |     0 |   0 |       91 |     1 |  62 |     0 |      0 | gray         | male   |          2 | 0P0HE | pants    | male   |    0 |   0 |   83 |   1 |        0 |     0 |   0 |    62 |    102 | gray         | male   |
| F2F            |              9 | 0J1LB | jacket   | male   |    0 |  101 |     0 |   0 |       91 |     1 |  63 |     0 |      0 | gray         | male   |          2 | 0P1DO | pants    | male   |    0 |   0 |   85 |   1 |        0 |     0 |   0 |    64 |    104 | gray         | male   |
| 스트라입스     |             10 | 0J0I5 | jacket   | male   |    0 |  100 |     0 |   0 |       92 |     1 |  62 |     0 |      0 | charcoalgray | male   |          2 | 0P0FK | pants    | male   |    0 |   0 |   83 |   1 |        0 |     0 |   0 |    64 |    105 | charcoalgray | male   |
| 익명           |              3 | 0J1G9 | jacket   | male   |    0 |   99 |     0 |   0 |       91 |     0 |  62 |     0 |      0 | gray         | male   |          1 | 0P0LS | pants    | male   |    0 |   0 |   84 |   1 |        0 |     0 |   0 |    62 |    101 | gray         | male   |
| 김현주(이창돈) |              4 | 0J1MO | jacket   | male   |    0 |   99 |     0 |   0 |       92 |     1 |  62 |     0 |      0 | navy         | male   |          1 | 0P1ER | pants    | male   |    0 |   0 |   85 |   1 |        0 |     0 |   0 |    61 |    105 | navy         | male   |
| 정하은         |            125 | 0J1GA | jacket   | male   |    0 |   99 |    84 |   0 |       90 |     0 |  62 |    67 |    105 | black        | male   |          1 | 0P0BK | pants    | male   |    0 |   0 |   84 |   1 |        0 |     0 |   0 |    64 |    111 | navy         | male   |
| 김영일         |             56 | 0J1HH | jacket   | male   |    0 |  100 |     0 |   0 |       92 |     1 |  63 |     0 |      0 | navy         | male   |          1 | 0P0BK | pants    | male   |    0 |   0 |   84 |   1 |        0 |     0 |   0 |    64 |    111 | navy         | male   |
| F2F            |              3 | 0J1LH | jacket   | male   |    0 |  101 |     0 |   0 |       91 |     1 |  63 |     0 |      0 | navy         | male   |          1 | 0P1DU | pants    | male   |    0 |   0 |   85 |   1 |        0 |     0 |   0 |    64 |    104 | gray         | male   |
| 박가량         |             60 | 0J1BU | jacket   | male   |    0 |   99 |     0 |   0 |       91 |     1 |  61 |     0 |      0 | black        | male   |          1 | 0P0YL | pants    | male   |    0 |   0 |   84 |   1 |        0 |     0 |   0 |    63 |    115 | black        | male   |

즉 상의를 선택한 시점에 하의는 고정되며, 전체 검색결과를 만들어낼때 하의의 예측 사이즈도 조건에 포함시키는 부분까지 반영이 끝났습니다. 한만일 대표님 사이즈로 테스트해본 결과 꽤 신뢰할 수 있는 결과가 나온것으로 보입니다.

**Comment by yongbin** [comment]
추가적으로 열린옷장의 남자옷장지기인 이성일님, 안수봉님 사이즈로 테스트를 진행했지만 검색결과가 만족스럽지 못했습니다. 하지만 이는 데이터와 모델과 관련된 문제이기때문에 추후 개선하는것으로 하고 이 이슈에서 진행하는 검색기능은 현재 내용대로 진행하기로 결정했습니다. 이제 다음과 같은 작업들이 필요합니다.
 - [ ] 사이즈예측을 위한 REST API 호출부 펄 구현
 - [ ] 사이즈 검색을 위한 SQL부 DBIC 구현
 - [ ] 검색 화면 구현

**Comment by yongbin** [comment]
> 사이즈예측을 위한 REST API 호출부 펄 구현

https://github.com/opencloset/OpenCloset-Size-Guess-Ocarina 에 v0.002 에서 구현이 완료되었습니다.

**Comment by yongbin** [comment]
> 사이즈 검색을 위한 SQL부 DBIC 구현

위에 작성했던 SQL 쿼리를 DBIC 코드로 적절하게 변환한뒤 `OpenCloset::Size::Guess::Ocarina` 와 결함해서 결과를 얻어오는 테스트 코드를 작성했습니다. 

```perl
use strict;
use warnings;
use utf8;

use v5.16;
use Data::Dumper;
use List::MoreUtils qw/ any /;
use POSIX qw/ ceil /;

use OpenCloset::Schema;
use OpenCloset::Size::Guess;

my $guesser = OpenCloset::Size::Guess->new(
    'Ocarina',
    gender    => 'male',
    height    => 183,
    weight    => 82,
    _bust     => 102,
    _waist    => 88,
    _topbelly => 85,
    _thigh    => 61,
    _arm      => 64,
    _leg      => 105,
);

my $result = $guesser->guess;
my %guess = map { $_ => $result->{$_} } grep { $result->{$_} } keys %{$result};

my $gender = 'male';

my %config = (
    male => {
        upper_name   => 'jacket',
        lower_name   => 'pants',
        upper_params => [qw/bust topbelly arm/],
        lower_params => [qw/thigh waist/],
        range_rules  => {
            bust     => sub { ( ceil( $_[0] ) - 2, ceil( $_[0] ) + 2 ) },
            topbelly => sub { ( ceil( $_[0] ) - 2, ceil( $_[0] ) + 2 ) },
            arm      => sub { ( ceil( $_[0] ) - 1, ceil( $_[0] ) + 1 ) },
            thigh    => sub { ( ceil( $_[0] ) - 2, ceil( $_[0] ) + 2 ) },
            waist    => sub { ( ceil( $_[0] ),     ceil( $_[0] ) + 2 ) },
        }
    },
    female => {
        upper_name   => 'jacket',
        lower_name   => 'skirt',
        upper_params => [qw/bust topbelly/],
        lower_params => [qw/hip waist/],
        range_rules  => {
            bust     => sub { ( ceil( $_[0] ) - 2, ceil( $_[0] ) + 2 ) },
            topbelly => sub { ( ceil( $_[0] ) - 2, ceil( $_[0] ) + 2 ) },
            hip      => sub { ( ceil( $_[0] ) - 2, ceil( $_[0] ) + 2 ) },
            waist    => sub { ( ceil( $_[0] ),     ceil( $_[0] ) + 2 ) },
        }
    }
);

my $upper_name      = $config{$gender}{upper_name};
my $lower_name      = $config{$gender}{lower_name};

my %guess_range;
for my $k ( keys %guess ) {
    next unless exists $config{$gender}{range_rules}{$k};
    $guess_range{$k} = [ &{ $config{$gender}{range_rules}{$k} }( $guess{$k} ) ];
}

my $DB = OpenCloset::Schema->connect( "dbi:mysql:dbname=xxxhost=127.0.0.1",
    'opencloset', xyz', );

my $rent_pair = $DB->resultset('Clothes')->search(
    {
        'category' => { '-in' => [ $upper_name, $lower_name ] },
        'gender'   => $gender,
        'order_details.order_id' => { '!=' => undef },
    },
    {
        join      => 'order_details',
        '+select' => ['order_details.order_id'],
        '+as'     => ['order_id'],
    }
);

my %order_pair;
while ( my $cloth = $rent_pair->next ) {
    my $order_id = $cloth->get_column('order_id');
    my $category = $cloth->get_column('category');
    my $code     = $cloth->get_column('code');

    $order_pair{$order_id}{$category} = $code;
}

my %pair_count;
while ( my ( $order_id, $pair ) = each %order_pair ) {
    next unless exists $pair->{$upper_name};
    next unless exists $pair->{$lower_name};
    next unless keys %{$pair} == 2;

    $pair_count{ $pair->{$upper_name} }->{ $pair->{$lower_name} }++;
}

my %pair;
for my $upper_code ( keys %pair_count ) {
    my $max_rented_pair_lower_code = (
        sort { $pair_count{$upper_code}{$b} <=> $pair_count{$upper_code}{$a} }
            keys %{ $pair_count{$upper_code} }
    )[0];

    $pair{$upper_code} = {
        $upper_name => $upper_code,
        $lower_name => $max_rented_pair_lower_code,
        count       => $pair_count{$upper_code}{$max_rented_pair_lower_code},
    };
}

my $upper_rs = $DB->resultset('Clothes')->search(
    {
        'category'  => $upper_name,
        'gender'    => $gender,
        'status.id' => 1,
        map { $_ => { -between => $guess_range{$_} } } @{ $config{$gender}{upper_params} }
    },
    { prefetch => [ { 'donation' => 'user' }, 'status' ], }
);

my $lower_rs = $DB->resultset('Clothes')->search(
    {
        'category'  => $lower_name,
        'gender'    => $gender,
        'status.id' => 1,
        map { $_ => { -between => $guess_range{$_} } } @{ $config{$gender}{lower_params} }
    },
    { prefetch => [ { 'donation' => 'user' }, 'status' ], }
);

my %upper_map = map { $_->code => $_ } $upper_rs->all;
my %lower_map = map { $_->code => $_ } $lower_rs->all;

my @result;
for my $up ( keys %upper_map ) {
    next unless $pair{$up};
    next unless any { $_ eq $pair{$up}{$lower_name} } keys %lower_map;

    my $upper_code = $pair{$up}{$upper_name};
    my $lower_code = $pair{$up}{$lower_name};
    my $pair_count = $pair{$up}{'count'};

    push @result,
        [
            $upper_code,
            $lower_code,
            $upper_map{$upper_code},
            $lower_map{$lower_code},
            $pair_count
        ];
}

print Dumper [
    map { [ $_->[0], $_->[1], $_->[4] ] }
    sort { $b->[4] <=> $a->[4] } @result
];
```
결과는 아래와 같습니다.

```
$VAR1 = [
          [
            '0J0A7',
            '0P08O',
            20
          ],
          [
            '0J1IL',
            '0P0TR',
            18
          ],
          [
            '0J03B',
            '0P01W',
            13
          ],
          [
            '0J0Z4',
            '0P0Q1',
            4
          ],
          [
            '0J1L8',
            '0P1DL',
            2
          ],
          [
            '0J1JC',
            '0P0LD',
            2
          ],
          [
            '0J1GO',
            '0P127',
            1
          ]
        ];
```
사이즈에 해당하는 사람의 대여가능한 의상의 코드와 묶음 대여수가 역순으로 정렬되어 보여집니다.  문자열로 출력가능한 형태만 출력했기때문에 코드와 수치만 보이지만 내부적으로 각각의 상의와 하의 쌍에 대한 DBIC rs를 같이 보유하고 있기때문에 이를 이용하면 원하는 결과화면을 만들어 낼 수 있을것으로 보입니다.

기존 DB쿼리 한번으로 검색하던 방식을 DB에 단순한 쿼리를 3번 질의하고 주요 검색관련 처리를 perl 에서 처리하는 방식으로 변경했습니다. 속도적인 측면에서는 약간의 저하가 있지만 심각하진 않고, 대신 추후 검색관련 요구사항이 복잡해지더라도 좀 더 유연하게 대응할수 있는 여지가 있는방향으로 고려했습니다.

이제 상기코드의 내용을 `app.conf`와 `app.psgi`에 적절하게 배분하고 UI와 연결하면 최종적인 작업이 완료될것으로 보입니다.

**Comment by yongbin** [comment]
> 검색 화면 구현

1차적으로 검색결과화면을 구현했습니다.. 동작상으로는 문제가 없지만 성능상에 이슈가 있습니다. 확인한 결과 검색결과 화면이 동작하는데 있어 각 부분별 누적 시간이 아래와 같이 소요됩니다.

 * 인자의 검증
  * [Tue Jan  5 18:55:01 2016] [debug] 200 OK (0.102008s, 9.803/s)
 * + OpenCloset::Size::Guess:Ocarina REST API 호출 2회
  * [Tue Jan  5 18:52:07 2016] [debug] 200 OK (1.360542s, 0.735/s)
 * + DB 질의 3회
  * [Tue Jan  5 18:53:37 2016] [debug] 200 OK (4.103217s, 0.244/s)

저의 2010년 macbook pro 기준으로 검색결과화면을 구성하는데 4.1초가 소요됩니다. 정식으로 오픈될 경우 검색페이지가 상대적으로 사용빈도가 높은점과 4.1초동안 Mojolicios의 워커하나를 점유한다는 점을 고려할때 성능개선을 고려해야합니다. 

@keedi 님과 다양한 방식으로의 성능개선안들이 논의되었습니다. 해당 개선은 별도의 이슈에서 진행하겠습니다.

**Comment by yongbin** [comment]
간단하게 @keedi 님께 코드리뷰를 받은뒤 아래와 같은 피드백을 받았습니다. 이중 *우선순위가 낮음* 이슈는 별도 이슈에서 처리하고 나머지는 본 이슈에서 처리합니다. 

   - [ ] 검색화면은 단독으로 구성하지 않고 /user/:id/search/clothes URL에서
     처리하도록 설정한다.
   - [ ] 위와같이 호출하면, :id 사용자의 신체사이즈를 기준으로 검색한 결과를
     화면에 표시하는 구조로 구현한다.
   - [ ] 단 원활한 디버깅등을 위해 기존과 동일한 형태로 GET 파라매터들도
     전달받되, 이 경우 DB에서 가지온 값을 덮어쓴뒤 처리한다.
   - [ ] OpenCPU 서버(현 https://brompton.silex.kr 은
     https://opencpu.theopencloset.net 으로 변경한다.
   - [ ] 물리장비에 세팅한 opencpu 를 LXC에서 동작하도록 한다(우선순위 낮음)
   - [ ] opencpu REST API 호출에 인증을 도입한다. (우선순위 낮음)
   - [ ] 검색결과화면은 bundle.coffee 코드를 참고해서 개선한다.
	 - [ ] 테이블 헤더
	 - [ ] 컬럼의 한글명
	 - [ ] 컬러 표기
	 - [ ] 의류코드앞 0 제거

**Comment by yongbin** [comment]
기존에 `OpenCloset::Size::Guess::Ocarina` 모듈이 `OpenCloset::Size::Guess::OpenCPU::RandomForest` 로 변경되면서 릴리즈 되었습니다. (v0.003)

https://github.com/opencloset/OpenCloset-Size-Guess-OpenCPU-RandomForest 

주요 변경사항은 다음과 같습니다.

```
0.003     2016-01-21 19:01:24+09:00 Asia/Seoul
   - Change driver name from Ocarina -> OpenCPU::RandomForest
   - Apply changed API server URL (https://opencpu.theopencloset.net)
   - Add 'hip' attribute to support female query
```

**Comment by yongbin** [comment]
@aanoaa  @keedi 님과 상의한 결과 PR 리뷰와 별도로 `monitor`에 붙이기로 결정했습니다. 바로 진행해주시면 됩니다.
