### ISSUE TITLE
온라인 이용자에게는 기존 사용자와 다른 번호로  문자가 발송되도록 함.

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#635]
전에 말씀드린 것과 같이 온라인 이용시에는 먼저 예약을 진행하여 등록하고 온라인 배송을 진행하도록 하겠습니다.

하지만 이것과 별도로
![2015-12-16 12 22 02](https://cloud.githubusercontent.com/assets/4696328/11831203/b0ad6b20-a3ef-11e5-919a-b9ffedaf28f3.png)
이 3가지 매크로에 대해서는 070-7583-7521로 발송되도록 요청드립니다.

**Comment by 10001if** [comment]
온라인 담당자분께 확인해보니 @aanoaa 께서 작업해 주신 https://github.com/opencloset/monitor/issues/92 이슈를 사용하려면 다른 번호로 전송되는 프로세스가 마련이 되어야 실행이 가능하다고 합니다. 작업이 마무리 되지 않으면 사용하기가 어렵다고 하네요. 참고 부탁드립니다. :)

**Comment by keedi** [comment]
흠. 일전에 말한대로 주문서 번호를 넣으면 해당 사용자에게 전송되는 방식으로 진행하면 될까요?

**Comment by keedi** [comment]
사용해야 하는 번호는 다음과 같습니다.

070-7583-7521

**Comment by keedi** [comment]
기본적으로 문자 전송의 from 영역 번호, 즉 열린옷장 번호는 바뀌지 않는다는 전제 및 조건하에 모든 부분이 만들어져 있기 때문에 관련해서 검토 및 수정이 필요합니다. :(

**Comment by keedi** [comment]
일단 현재 기준으로는 웹 응용에서 설정 파일에 있는 번호를 사용해서 보내는 부분만 온라인 오프라인을 구별해 전송하면 될 것 같습니다.

**Comment by keedi** [comment]
구현 및 서버에 배포 완료했습니다.
이슈 닫습니다.

**Comment by 10001if** [comment]
확인 해보았는데, 여전히 4325 번호로 발송되고 있습니다. 확인 부탁드릴게요. ^^

**Comment by keedi** [comment]
03c3a2f Fix typo: booking time string comparison

예약 시간이 22:00시인지 검사할때 콜론 문자를 빠뜨려서 예약 시간을 문자열로 변환할때 2200이 되버려 온라인 주문서를 감지하지 못하는 버그가 있었습니다.

**Comment by keedi** [comment]
수정 완료했습니다.

**Comment by keedi** [comment]
정상 전송 되는 것 까지 확인했습니다. :)
