### ISSUE TITLE
J001을 "1234-5678"로 변환할 수 있는 페이지 생성

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#636]
기존 코드를 32진법을 통해 숫자로 변환하는 페이지가 필요합니다. 차 주까지는 주문을 해서 바코드를 제공받으려 합니다. 이전에 코드를 숫자로 변환할 수 있는 페이지가 필요합니다.

**Comment by 10001if** [comment]
메세지 사이트로 정신이 없으시겠지만, 이 페이지 생성을 요청드려야 할 것 같습니다. 오늘 바코드 주문을 완료하여서요. 2~3일 내로 바코드가 도착할 것 같은데, 도착하면 기존 의류와 함께 바코드 수정 작업을 대대적으로 진행하려고 합니다. ^^

**Comment by 10001if** [comment]
@keedi 부탁드리겠습니다. ^^

**Comment by 10001if** [comment]
@keedi 께서 잘 만들어 주신 것 같습니다. 감사합니다. ^^

**Comment by aanoaa** [comment]
https://barcode.theopencloset.net/
