### ISSUE TITLE
통계-방문자에서 금월 또는 금주 기록도 보여줌

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#637]
현재는 전 월 자료까지만 숫자가 뜨고 있습니다. 하지만 이번 달 방문 숫자는 확인이 되지 않습니다. 1일부터 금일까지의 방문자 수, 미방문자 수, 대여자 수 등을 알고 싶습니다.

**Comment by 10001if** [comment]
![2015-12-16 4 04 02](https://cloud.githubusercontent.com/assets/4696328/11834354/11bf91b2-a40f-11e5-8730-8354ad9c4421.png)

**Comment by keedi** [comment]
현재 금월의 통계를 내지 않는 것은 기술적인 이슈입니다.
간단히 말씀드리면 예약자와 방문자는 시시각각 변합니다.
어제와 오늘이 다르고 오늘도 아침과 저녁이 다르며
1시간 전과 1시간 후가 다릅니다.

즉 금월의 통계는 해당 페이지를 볼때마다 매번 연산을 해야합니다.
해당 통계(월별)는 처리하는데 오랜 시간이 걸리는 관계로
페이지를 로딩할때 마다 계산하는 것은 무리가 있습니다.

12월이 마무리되면 12월 자료는 더이상 갱신이 있을수  없으므로(타임머신이 있지 않은 한)
이 때는 미리 고비용의 연산을 수행한 후 보여지는데 무리가 없으며
현재 이런 방식으로 이뤄지고 있습니다.

따라서 페이지를 여는 그 시점 기준 금월의 통계는 제공하는 것이 어렵다는 것이 결론입니다.
대신 그 상황도 고려해 주별 방문자 데이터를 이미 제공하고 있습니다.

![screenshot-staff theopencloset net 2015-12-17 10-21-04](https://cloud.githubusercontent.com/assets/138451/11858794/fb82cf24-a4a7-11e5-84fd-76d5978c5e4a.png)

따라서 현 시점 기준의 금월 자료는 주별 자료를 합산해서 계산하면 됩니다.
주별 자료도 월별 자료와 마찬가지로 금주의 자료는 연산하지 않습니다.
금주의 자료는 일별 자료를 제공하고 있으므로 일별자료를 기준으로 합산해서
계산하면 됩니다.

즉 금월의 자료는 시스템이 제공하지는 않지만 다음과 같은 방식으로 구할 수 있습니다.

**주별 자료 중 금주를 제외한 이번 달에 해당하는 주별 자료의 합 + 금주에 해당하는 일별 자료의 합**

**Comment by 10001if** [comment]
@keedi 알겠습니다. 본 이슈가 현저히 문제를 가져오는 것은 아니였기 때문에 말씀해 주신 방식으로 누적하여 계산하도록 하겠습니다. 이슈 닫도록 하겠습니다. 감사합니다. :)

**Comment by yongbin** [comment]
#443

**Comment by keedi** [comment]
내용 정리하다 보니  흠... 계산이 아닌 캐시에 저장된 값을 누적하는 방식으로 표현할 수도 있겠다라는 생각이 문득 들었네요.

계산은 너무 오랜 시간이 걸리지만 사람이 더할 영역을 더해서 금주 또는 금월 영역에 보이게 하는 것은 그리 비싼 연산이 아니라는 생각이 들었습니다.

조금 고민해보겠습니다.

**Comment by keedi** [comment]
연산이 좀 복잡하긴 한데 최대한 기존 연산과 캐시 값을 활용해서 금주와 금월의 값을 표시할 수 있도록 했습니다. 해당 값은 캐싱하지 않기 때문에 페이지를 열람할 때 마다 현재 상황에 따라 값이 달라질 수 있도록 처리했습니다.

**Comment by keedi** [comment]
구현한 화면은 다음과 같습니다.

![screenshot-monster silex kr 10301 2015-12-17 16-29-14](https://cloud.githubusercontent.com/assets/138451/11863914/8cd192d4-a4db-11e5-9c7b-f5dca5e1c726.png)

**Comment by keedi** [comment]
구현 및 실서버에 배포 완료했습니다.

이슈 닫습니다.

**Comment by 10001if** [comment]
확인 완료하였습니다! 감사합니다! ^^
