### ISSUE TITLE
전 품목의 바코드 생성 요청

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#639]
![- -](https://cloud.githubusercontent.com/assets/4696328/11860627/186a1b58-a4ba-11e5-8486-9a342f29c4b5.jpg)
이렇게 3가지 종류로 나누어 바코드를 받으려 합니다.
@yongbin 확인해주시고 문제가 없으면 코드를 받아서 주문을 하려고 합니다.

**Comment by 10001if** [comment]
요청 수량은 다음과 같습니다. 
 
자켓 1000개
바지 500개
스커트 500개
코트 100개
셔츠 1000개
블라우스 500개
원피스 100개
타이 500개
구두 500개
벨트 500개

**Comment by yongbin** [comment]
10 진코드 생성이 필요한 #640 이슈와 10 진코드 생성이 필요없는 #641 로 나눠서 진행하겠습니다. 각각이 완료되면 이 이슈를 닫겠습니다.

**Comment by keedi** [comment]
십진 코드 필요 여부에 대해 확인하기로 함.
확인 완료되면 그 결과 정리하고 진행 바랍니다.

**Comment by yongbin** [comment]
십진코드를 모든 경우에 대해서 다 생성하기로 했기떄문에 #640, #641 로 나눠서 진행할 필요가 없어졌습니다.

![cd331498-a4d0-11e5-9b52-56d8d20095ab](https://cloud.githubusercontent.com/assets/52704/11865138/7911d9de-a4e5-11e5-9463-58fe758969f9.jpg)

**Comment by keedi** [comment]
#640, #641은 중복 처리 하고 이슈 닫았습니다.

모든 시안에 8자리 표기법을 병행하기로 했습니다.

**Comment by keedi** [comment]
8자리 표기법을 병행해서 생성할 수 있도록 코드 수정했습니다.

https://github.com/opencloset/opencloset/blob/develop/bin/opencloset-barcode.pl

`bin/opencloset-barcode.pl` 파일이니 참고 바랍니다.
저장소에 커밋한 관계로 위키의 소스 코드는 제거하겠습니다.

**Comment by yongbin** [comment]
```perl
my %last = (
    A => q{A0UJ},    # 신발      / shoes
    B => q{B0F9},    # 블라우스  / blouse
    C => q{C022},    # 코드      / coat
    E => q{E0QD},    # 벨트      / belt
    H => q{H00O},    # 모자      / hat
    J => q{J1RV},    # 자켓      / jacket
    K => q{K0B3},    # 스커트    / skirt
    O => q{O022},    # 원피스    / onepiece
    P => q{P1HK},    # 바지      / pants
    S => q{S1N5},    # 셔츠      / shirt
    T => q{T0ZE},    # 타이      / tie
    W => q{W01D},    # 조끼      / waistcoat
);

my %code = (
    A => 500,      # 신발      / shoes
    B => 500,      # 블라우스  / blouse
    C => 100,      # 코드      / coat
    E => 500,      # 벨트      / belt
    H => 0,      # 모자      / hat
    J => 1000,      # 자켓      / jacket
    K => 500,      # 스커트    / skirt
    O => 100,      # 원피스    / onepiece
    P => 500,      # 바지      / pants
    S => 1000,      # 셔츠      / shirt
    T => 500,      # 타이      / tie
    W => 0,      # 조끼      / waistcoat
);
```

위와 같은 인자로 수행했습니다.

**Comment by yongbin** [comment]
@10001if 생성한 5200개의 코드를 메일로 보내드렸습니다. 확인부탁드립니다.

**Comment by 10001if** [comment]
@yongbin 중복여부 등을 확인하고 다시 말씀드리겠습니다.

**Comment by yongbin** [comment]
> @yongbin 중복여부 등을 확인하고 다시 말씀드리겠습니다.

넵 확인하고 이상있으시면 다시 열어주시기 바랍니다.

**Comment by yongbin** [comment]
> K => q{0B3}, # 스커트    / skirt

스커트의 라스트코드에 문제가 있었습니다. 과거에 #549 에서 변경된 코드를 업데이트하지 못해서 발생했던 문제였습니다. 공교롭게도 당시의 요청도 500개였기 때문에 이번 이슈에서 생성된 마지막 last 코드를 기준으로 아래와 같이 추가 스커트코드를 생성합니다.

```perl
my %last = (
    A => q{18F},    # 신발      / shoes
    B => q{0T5},    # 블라우스  / blouse
    C => q{04U},    # 코드      / coat
    E => q{149},    # 벨트      / belt
    H => q{00O},    # 모자      / hat
    J => q{2JN},    # 자켓      / jacket
    K => q{0OZ},    # 스커트    / skirt
    O => q{04U},    # 원피스    / onepiece
    P => q{1VG},    # 바지      / pants
    S => q{2EX},    # 셔츠      / shirt
    T => q{1DA},    # 타이      / tie
    W => q{01D},    # 조끼      / waistcoat
);

my %code = (
    A => 0,      # 신발      / shoes
    B => 0,      # 블라우스  / blouse
    C => 0,      # 코드      / coat
    E => 0,      # 벨트      / belt
    H => 0,      # 모자      / hat
    J => 0,      # 자켓      / jacket
    K => 500,      # 스커트    / skirt
    O => 0,      # 원피스    / onepiece
    P => 0,      # 바지      / pants
    S => 0,      # 셔츠      / shirt
    T => 0,      # 타이      / tie
    W => 0,      # 조끼      / waistcoat
);
```

**Comment by yongbin** [comment]
새로 발급한 스커트 500건을 메일을 통해 @10001if 님께 전달했습니다. 아울러 라스트코드 변경내역을 위키페이지에 업데이트 했습니다. 추가적으로 신발코드를 2번씩 표시되도록 생성해달라는 요청을 아래와 같은 원라이너를 통해서 처리했습니다.

```sh
cat ~/Desktop/opencloset-code-20151218.csv | perl -anE 'print "$_" x 2' > ~/Desktop/opencloset-code-20151218-double.csv
```

@10001if 다시확인 부탁드립니다. 문제있으면 재오픈해주시기 바랍니다.

**Comment by 10001if** [comment]
대표님 파일을 확인하지 못했습니다. 번거로우시겠지만 한번만 더 보내주실 수 있을까요? ^^

2015년 12월 18일 오후 6:09, Yongbin Yu <notifications@github.com>님이 작성:

> 새로 발급한 스커트 500건을 메일을 통해 @10001if <https://github.com/10001if> 님께 전달했습니다.
> 아울러 라스트코드 변경내역을 위키페이지에 업데이트 했습니다. 추가적으로 신발코드를 2번씩 표시되도록 생성해달라는 요청을 아래와 같은
> 원라이너를 통해서 처리했습니다.
>
> cat ~/Desktop/opencloset-code-20151218.csv | perl -anE 'print "$_" x 2' > ~/Desktop/opencloset-code-20151218-double.csv
>
> @10001if <https://github.com/10001if> 다시확인 부탁드립니다. 문제있으면 재오픈해주시기 바랍니다.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencloset/opencloset/issues/639#issuecomment-165719303>
> .
>



-- 
——————————————————————————————

“You must be the change you want to see in the world.”
―Mahatma Gandhi


*열린옷장한 만 일 (Man Of Action)*

*Manil Han*
T 070. 4325. 7521
F 02. 6974. 1521
M 010. 6225. 7709
E 10001if@theopencloset.net
H www.theopencloset.net

Address
서울특별시 광진구 화양동 48-3 웅진빌딩 403호 (우편번호 : 143-917)
#403, Woongjin B/D, 48-3, Hwayang-dong, Gwangjin-gu, Seoul, Korea

**Comment by yongbin** [comment]
@10001if Gmail로 보내드렸습니다!

**Comment by 10001if** [comment]
대표님~ 제가 메일을 확인하고 있는데 기존에 주셨던 5200개의 코드 외에 새로 주신 파일이 어디 있는지 모르겠네요.

번거로우시겠지만 월요일에 출근하시면 한번 보내주실 수 있을까요? ^^

편안한 주말오후 보내세요 ^^

2015-12-18 19:12 GMT+09:00 Yongbin Yu <notifications@github.com>:

> @10001if <https://github.com/10001if> Gmail로 보내드렸습니다!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencloset/opencloset/issues/639#issuecomment-165738216>
> .
>



-- 
——————————————————————————————

“You must be the change you want to see in the world.”
―Mahatma Gandhi


*열린옷장한 만 일 (Man Of Action)*

*Manil Han*
T 070. 4325. 7521
F 02. 6974. 1521
M 010. 6225. 7709
E 10001if@theopencloset.net
H www.theopencloset.net

Address
서울특별시 광진구 화양동 48-3 웅진빌딩 403호 (우편번호 : 143-917)
#403, Woongjin B/D, 48-3, Hwayang-dong, Gwangjin-gu, Seoul, Korea

**Comment by yongbin** [comment]
@10001if 넵 대표님 이상하네요 저는 보낸편지함에 18일에 발송된것으로 나오고 있습니다. 아무튼 다시한번 발송했습니다. 확인부탁드립니다.

**Comment by 10001if** [comment]
대표님. 오늘 바코드 주문을 넘기려고 하는데요. 요청사항이 있습니다. 
저희가 주문을 하려고 하니까 주문받는 쪽에서 헷갈릴 수 있으니 파일을 나누어서 보내달라고 요청해주시더라구요.
저도 생각을 해보니 그 편이 깔끔할 것 같아서요. 몇 번씩 번거롭게 부탁드려 죄송한데요.

1번 : 자켓, 바지, 스커트, 코트
2번 : 셔츠, 블라우스, 원피스, 넥타이
3번 : 구두, 벨트 (구두는 2번 연속 출력)

이렇게 3개의 파일로 나눠서 다시 한번 작업 부탁드려도 될까요?
바쁘신데 번거롭게 부탁드려 죄송합니다. ^^

**Comment by 10001if** [comment]
파일 보내주시면 확인 후 바코드 제작업체에 메일 보내도록 하겠습니다.

**Comment by 10001if** [comment]
파일도 받고 확인도 완료하였습니다. 주문하였으므로 이슈 닫도록 하겠습니다.
