### ISSUE TITLE
자켓, 바지, 스커트, 코드 바코드와 10진코드 생성요청

### ISSUE THREAD

**Issue by yongbin** [opencloset/opencloset#640]
#639 
![screen shot 2015-12-17 at 12 38 52 pm](https://cloud.githubusercontent.com/assets/52704/11860727/2e2a5a10-a4bb-11e5-9c14-df5ca55a1095.png)

자켓 1000개
바지 500개
스커트 500개
코트 100개

**Comment by 10001if** [comment]
십진 코드는 모두 넣기로 하였습니다. 확인 부탁드립니다.

**Comment by 10001if** [comment]
![- -](https://cloud.githubusercontent.com/assets/4696328/11862681/14255730-a4d1-11e5-8c63-de8ca17d0ffd.jpg)
최종안입니다.

**Comment by keedi** [comment]
최종적으로 #639 에서 진행하기로 했습니다.
