### ISSUE TITLE
셔츠, 블라우스, 원피스, 타이 바코드 생성

### ISSUE THREAD

**Issue by yongbin** [opencloset/opencloset#641]
#639 

![screen shot 2015-12-17 at 12 41 41 pm](https://cloud.githubusercontent.com/assets/52704/11860762/93152d06-a4bb-11e5-88e7-ee0c7a891d51.png)

셔츠 1000개
블라우스 500개
원피스 100개
타이 500개
구두 500개
벨트 500개

**Comment by yongbin** [comment]
10진 코드 생성이 필요없기때문에 일상적인 바코드생성과 동일하게 진행하면 됩니다. 진행합니다.

**Comment by keedi** [comment]
십진 코드 필요 여부에 대해 확인하기로 함.
확인 완료되면 그 결과 정리하고 진행 바랍니다.

**Comment by 10001if** [comment]
십진 코드는 모두 넣기로 하였습니다. 확인 부탁드립니다.

**Comment by 10001if** [comment]
![- -](https://cloud.githubusercontent.com/assets/4696328/11862650/cd331498-a4d0-11e5-9b52-56d8d20095ab.jpg)
최종안입니다.

**Comment by keedi** [comment]
최종적으로 #639 에서 진행하기로 했습니다.
