### ISSUE TITLE
첫화면에서 대여중인 의류가 대여가능으로 변경되지 않도록 요청

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#646]
성일님께서 남겨주신 내용을 옮김니다. 
-----------------------------------------------------------------------------------------
"대여중인 의류의 상태가 왜 대여가능이 될까?"의 의문이 풀렸습니다. 대여탭에서 바코드를 찍다가 반납, 수선 등으로 인해 첫화면에서 상태변경을 한 경우 찍은 바코드를 그대로 두고 이용하는 경우가 많습니다. 이때 해당 의류가 대여가 된 후 또 다른 의류의 상태변경을 위해서 첫화면에서 바코드를 찍고 상태 변경을 할 때에 기존에 찍혀 있던 의류가 대여중임에도 불구하고 상태변경이 됩니다.

월요일날 직접 뵙고 다시 설명드리도록 하겠습니다.

**Comment by keedi** [comment]
방금 내용 전달 받았습니다. 정확하게 이해했고 해당 사항이 현재 발생하고 있는 대여중인 의류가 대여 가능으로 바뀌는 버그와 관련이 있을지는 확신은 못하겠습니다. 다만 이 문제를 해결하고 기존 버그로 의심되는 현상이 없어지면 좋겠지만...

어쨌든 말씀해주신 케이스는 충분히 발생 가능하고 심각한 것이므로 수정 진행하겠습니다! :)

**Comment by keedi** [comment]
일단 공식적으로 letters, visit 작업을 제외하고는 제가 처리하지 않을 예정입니다. 기존 제가 처리하려고 했던 이슈는 모두 담당자를 제거한 이후, 그 이후에 새롭게 담당자로 제가 지목되는 이슈에 한해 처리하겠습니다. 관련해서 제가 할당된 이슈의 담당자를 모두 제거하겠습니다.

**Comment by yongbin** [comment]
@aanoaa 말씀하신 내용으로  이 이슈 정리해주시고 새로 이슈 열어주세요

**Comment by aanoaa** [comment]
이런 상황이 왜 발생하냐면,
반납후에 `대여가능` 으로 상태가 변경되지 않은 의류를 포장할때에
`대여` 메뉴에서는 상태변경을 할 수 없기 때문에
첫화면으로 가서 의류를 `대여가능` 으로 바꾸고 다시 `대여`로 돌아와서 포장업무를 하게 됩니다.

대여에서 의류의 상태변경을 할 수 있게 된다면 첫화면에서 의류의 상태를 변경해야할 일은 적어집니다.

해서 이 이슈는 자연스럽게 해결되지 않을까 기대합니다.

**Comment by yongbin** [comment]
넵 그럼 이 이슈는 닫고 #546 만 처리하면 될까요?
