### ISSUE TITLE
주문서의 포장완료 목록을 실시간으로 갱신

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#647]
https://github.com/opencloset/monitor/issues/93

의 이슈입니다.

웹소켓을 사용해서 주문서의 상태변경에 따라 실시간으로
새로고침없이 포장완료 목록을 갱신해야 합니다.

**Comment by aanoaa** [comment]
@10001if 배포했습니다 기능확인해주세요.

**Comment by 10001if** [comment]
기능 확인하였습니다. 감사합니다. ^^

**Comment by 10001if** [comment]
그런데, 포장탭이 라이브로 변경 된 후 포장완료에서 결제대기로 넘길 때 자동으로 주문서로 이동하지 않습니다.

**Comment by aanoaa** [comment]
주문서로 이동하지 않는 문제를 해결해서 배포했지만,
문제가 있는게, 버튼을 누르는 클라이언트와 그렇지 않은 클라이언트 간의
동기화 문제가 있습니다.

이를 해결한 후 다시 배포하겠습니다.

**Comment by 10001if** [comment]
확인 완료하였습니다.

**Comment by 10001if** [comment]
다시 확인해보니 포장완료 버튼을 누른 순서대로 정렬이 되지 않고 있습니다. 포장완료를 가장 먼저 누른 것이 가장 맨 위로 올라가서 그 다음부터 아래로 쌓였으면 좋겠습니다. 확인 요청드립니다. :)

**Comment by aanoaa** [comment]
10:00 예약한 사람과 10:30 예약한 사람이 있다면,
포장완료 상태 변경 시간과 상관없이 10:00 예약한 손님먼저 나타나게 됩니다.

주문서 화면에는 여러가지 상태에 대한 목록이 있는데,
다른 상태일때의 목록은 그대로 두고, 포장완료 상태에 대해서만 변경시간을 우선으로해서 보여드리겠습니다.

**Comment by aanoaa** [comment]
테스트와 적용은 되었는데, 확인이 쉽지는 않을 것 같습니다.
확인하려면 대여자가 예약시간 보다 먼저와서 포장완료 상태가 1명 이상일때 포장완료에 들어가야 합니다.

**Comment by aanoaa** [comment]
일단 닫겠습니다 목록의 정렬 상태가 이상하면 알려주세요.

**Comment by aanoaa** [comment]
확인되었습니다.
하지만, 정렬이 역순으로 되어야 합니다.
가장 먼저 포장완료된 주문서가 가장 위로 갈 수 있도록.

**Comment by aanoaa** [comment]
@10001if 반영하였습니다 확인하시고 닫아주세요.

**Comment by 10001if** [comment]
확인완료하였습니다. 감사합니다. ^^

**Comment by 10001if** [comment]
잘 되었다고 생각했는데. 오늘 다시 확인해보니 가장 먼저 포장완료를 누른 사람의 주문서가 가장 아래에 있다고 합니다. 가장 위에서 순차적으로 아래로 쌓일 수 있도록 수정 요청드립니다.

**Comment by aanoaa** [comment]
아닌데.. 젤 빨리 누른사람이 젤 위에 올텐데..

**Comment by aanoaa** [comment]
아니구나 제가 잘못했네요.
바꿔놓겠습니다.

**Comment by 10001if** [comment]
@aanoaa 넵! 다시 확인해보겠습니다. ^^

**Comment by 10001if** [comment]
확인 완료하였습니다. ^^
