### ISSUE TITLE
입고가는 사람에 대한 상태표시

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#648]
포장해가지 않고 직접 입고 가는 사람이 많은데,
이를 구분해서 활용하고 싶습니다.

입고가는 사용자와 자리비움 사용자를 구분할 방법이 없는데 이런 문제가 해결될 수 있습니다.

order 테이블에 column 이 추가되어야 할 것 같습니다.

**Comment by aanoaa** [comment]
이게 필요했던 이유가 아마도..

`대여` 에서 주문서와 옷을 선택한 후에 `선택한 항목을 대여합니다` 버튼을 누르면 `포장완료` 상태로 넘어갑니다.
하지만 옷을 입고 있는 대여자에게는 이렇게 할 수가 없기 때문입니다.

일반적으로는

    의류준비 - 탈의 - 포장 - 포장완료 - 결제대기

인데 옷을 입고가는 대여자는

    의류준비 - 탈의 - 결제대기

입니다.

**Comment by aanoaa** [comment]
하지만 입고가는 사람의 프로세스에 대해 더 구체화되어야 할 것 같습니다.

**Comment by aanoaa** [comment]
저의 아이디어 입니다.

- 주문서에 탈의 목록을 만들고,
- staff 이 판단해서 입고가는사람을 해당목록에서 `탈의 ->  포장`
  버튼을 누르고 `대여` 화면으로 넘어가서 포장절차대로 하는 겁니다.

**Comment by aanoaa** [comment]
의류준비와 마찬가지로 bestfit 여부를 강제해야 할 수도 있습니다.

**Comment by aanoaa** [comment]
이미 의류코드를 입력하는 대여의 절차는 정상적으로 되고 있다고 합니다.
제가 잘못 생각했습니다.

**Comment by aanoaa** [comment]
포장하는사람이 입고가는지 여부를 체크해주고 결제해주는 사람이 확인할
수 있어야 합니다.

**Comment by aanoaa** [comment]
포장완료 목록에서 입고가는사람에 대한 flag 를 확인 할 수 있으면 됩니다.

**Comment by aanoaa** [comment]
정확하게는

`대여`화면에서 주문서에 대해 "입고간다" 를 체크해 주고,
`주문서`의 포장완료 목록에서 "입고간다" 가 표시되어야 합니다.

**Comment by aanoaa** [comment]
스키마 변경이 필요한 이슈입니다.

`is_wearing` 또는 `on_wearing` 의 컬럼을 추가해서 해결할 수 있습니다.
default 는 `0` 안입고간다 가 될테고 `0` 이외의 경우에는 입고간다로
판단해서 보여줄 수 있겠습니다.

**Comment by 10001if** [comment]
배경 색깔을 조금 더 많이 진하게 바꿔달라는 의견입니다.

**Comment by aanoaa** [comment]
포장완료 목록 뿐 아니라 모든 목록에서 입고가는 주문서에 대해 강조되고 있습니다
이것도 같이 수정하겠습니다.

**Comment by 10001if** [comment]
확인완료하였습니다.
