### ISSUE TITLE
미납상태의 주문서들에 대해 완납 불납 기능추가

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#649]
- `완납`
- `불납`

버튼이 있어서 이를 누르면 목록에서 제거 되고 알아서 스슥되어야 합니다.

- 정상적인 반납
- 완납후 반납
- 불납

의 경우를 구분했으면 좋겠다고 합니다.

**Comment by aanoaa** [comment]
@keedi `order` 테이블의 `compensation_pay_with` 의 용도가 무엇인가요?

**Comment by aanoaa** [comment]
연체료를 완납한 주문서는 `compensation_pay_with` 를 `완납` 으로 변경하고,
`late_fee_pay_with` 에 `카드 | 현금 | 계좌이체` 등으로 변경하면 될 것 같습니다.

**Comment by aanoaa** [comment]
`불납`인 경우에는 `compensation_pay_with` 를 `불납` 으로 하고,
`late_fee_pay_with` 를 `null` 로 바꾸면 될 것 같습니다.

**Comment by aanoaa** [comment]
#650 과 함께 처리되어야 합니다.

**Comment by aanoaa** [comment]
`compensation_pay_with`는 의류를 분실했거나 훼손되었을때 사용하는 컬럼입니다.

**Comment by keedi** [comment]
답이 늦어져 죄송합니다. 이게 배상비 관련이라서 어쨌든 미납과는 좀 별개고, 이 미납이란것도 미묘한게 연체비 미납 뿐만 아니라 배상비 미납일수도 있고... 흠...  미납 또는 불납 자체는 통틀어서 최종 금액적으로 미납 또는 불납이긴한데... 어쨌든 일단 그러합니다.;;

**Comment by aanoaa** [comment]
완납일때

    compensation_pay_with => NULL
    late_fee_pay_with     => 카드 or 현금 or 계좌이체

불납일때

    compensation_pay_with => NULL
    late_fee_pay_with     => 불납

으로 변경하고,

완납은 상태가 반납 이면서 `late_fee_pay_with` 가 `카드 | 현금 | 계좌이체` 일때로 확인 할 수 있겠고,

불납은 `late_fee_pay_with` 가 `불납` 일때로 판단 할 수 있겠습니다.

**Comment by keedi** [comment]
현실적으로 불납을 처리하려면... 아마도... 이런식이 될 것 같습니다.

`order_detail` 미납금(배상비든 연체비든)을 표기하고 추가로 불납금액을 표시하고(이때는 마이너스로 표시) 처리하는것이죠.

compensation_pay_with <-- 이건 배상비를 냈을수도 있고 안냈을수도 있으니 null여부는 그때그때 다를테구요.

**Comment by aanoaa** [comment]
잘못 생각했습니다.

    미납금 = 연체비 or 배상비

입니다.
완납에 대한 의미도 연체비 완납 과 배상비 완납이 있을 수 있습니다.
불납도 마찬가지 입니다.

**Comment by keedi** [comment]
완납 및 불납 UI와 변경된 화면, 금액 입력하는 화면 등 기존과 변경되거나 추가된 모든 화면을 갈무리해서 정리 부탁드립니다. 가능하면 PR보다는 원래 이슈에 붙여주시면 좋을 것 같습니다.

**Comment by aanoaa** [comment]
이슈가 생기면 이것저것을 이슈에 적다가
PR 이 생기면 해당기능에 대해 PR 에 적어내려가고
merge 되고 나면 다시 이슈에 적다가
다른 PR 이 생기면 반복하는게 좋지 않을까여?

**Comment by aanoaa** [comment]
완납 절차 입니다.

![screenshot-localhost 5001 2015-12-26 14-01-38](https://cloud.githubusercontent.com/assets/170528/12005195/b9990620-abda-11e5-973b-a49d768351ad.png)

주문서 정보를 보면 `미납` 했던 이력이 있는 사용자라는 걸 알 수 있습니다.
![screenshot-localhost 5001 2015-12-26 14-03-09](https://cloud.githubusercontent.com/assets/170528/12005196/c13d3a4a-abda-11e5-8f23-2239c0cbf911.png)
![screenshot-localhost 5001 2015-12-26 14-05-01](https://cloud.githubusercontent.com/assets/170528/12005197/c63e46b0-abda-11e5-9b9f-7d456955ecee.png)

`완납` 버튼을 누른 다음 받은 금액과 결제방법을 입력합니다.
![screenshot-localhost 5001 2015-12-26 14-05-57](https://cloud.githubusercontent.com/assets/170528/12005198/d49c3c76-abda-11e5-973c-adf8f997516e.png)

정상적으로 처리되었다면 안내표시가 나타나고 목록에서 사라집니다.
![screenshot-localhost 5001 2015-12-26 14-07-15](https://cloud.githubusercontent.com/assets/170528/12005199/d9e31074-abda-11e5-9bce-54d9b8cb2417.png)

다시 주문서 정보를 확인하면 `미납` 태그가 사라지고 완납에 대한 이력이 추가됩니다.
![screenshot-localhost 5001 2015-12-26 14-08-53](https://cloud.githubusercontent.com/assets/170528/12005201/de1252ea-abda-11e5-82ac-9ebe718869a9.png)

**Comment by keedi** [comment]
> 이슈가 생기면 이것저것을 이슈에 적다가
> PR 이 생기면 해당기능에 대해 PR 에 적어내려가고
> merge 되고 나면 다시 이슈에 적다가
> 다른 PR 이 생기면 반복하는게 좋지 않을까여?

아... 이게 적을때는 상관은 없는데... 흠...
설명드리자면... 

> 이슈가 생기면 이것저것을 이슈에 적다가

이건 아무 문제가 없구요...

> PR 이 생기면 해당기능에 대해 PR 에 적어내려가고

요게 조금 문제인데요... 깃헙이 검색이 좀 시원찮아서 하나 처리하고 있는 내용을 이슈랑 pr이랑 나눠서 기록하면 다시 복기할때 좀 힘들더라구요. 복기까진 아니어도 따라갈때 계속 링크를 클릭해야 해서...

> merge 되고 나면 다시 이슈에 적다가
> 다른 PR 이 생기면 반복하는게 좋지 않을까여?

일단 PR에서는 해당 코드에 대한 부분, 코드 리뷰라던가, 머지 전략이라던가 등등... 구현상의 이슈에 대한 것으로 최대한 축소시키고 본래의 이슈에 이슈 자체에 대한 내용을 정리하면 그나마 해당 이슈에 대한 내용의 파편화를 최대한 막을 수 있습니다.

아무리 간단한 PR이라도 설정 수정 빼고는(심지어 설정 수정이라 하더라도) 계속 이슈를 만들고 거기에 PR을 남기는 이유가 이 때문입니다. 작성하는 우리들 입장에선 PR로 바로 처리하고 남기는게 좀 더 편하긴 한데 문제가 생겼을때 다시 이력을 확인해야 하는 디버깅 상황이나, 논의 내역을 다시 찾아본다거나 할때는 PR로만 처리하면 찾기가 너무 어려워요.

여튼 이러한 연유로 가능하면 내용은 이슈에 몰아서 적는 것이 좋을 것 같다는게 제 의견입니다. =3

**Comment by aanoaa** [comment]
PR 이 merge 가 안될 수 있으니까 PR 에 대한 기능은 PR 에 적어야죠

**Comment by keedi** [comment]
머지가 안된 내역 조차도 feature에 대한 내용이라면 이슈에서 이야기가 논의 되야겠죠. 이슈에서 논의도 없이 PR에서 진행되는 경우는 이슈없이 PR을 만들지 않고는 불가능할 것 같은데요. 예를 들어 **미납 상태의 주문서에 대해 완납 불납 기능을 추가**하는 이슈라면 이 기능에 대한 구현이 PR에 있는거고 관련된 PR이 머지가 되지 않더라도 이슈에 적는게 맞을 것 같아요. 해당 구현 관련된 내용을 PR에만 적는다면 이슈를 읽던 사람이 해당 PR을 클릭하지 않으면 내용을 모르기도 하구요. 더불어 이슈에도 누군가가 커멘트를 달고 PR에도 누군가가 커멘트를 달았다고 하면 두 창을 동시에 띄워서 타임라인별로 어느게 먼저인지 확인하면서 읽는건 인간에게는 불가능하다고 생각되요.

**Comment by aanoaa** [comment]
이슈를 해결하기 위해 기능을 구현하고 PR 하는거니까
기능 A 에 대한 내용을 PR A 에다가 적고 기능 A 와 상관없는 건
이슈에 적으면 안되겠습니까?

그리고 이슈에서 다른 기능이 구체화 되면 PR B 가 생기고 거기서
관련된 걸 해결하고요.

나름 그래프화 해보면,

- 이슈가 생김
  - 코멘트..
  - 코멘트..
  - 무슨일이 있음
  - 무슨일에 대한 PR
    - ...A
    - 인덴트가 거지같다
    - ...A
  - 다른일이 있음
  - 다른일에 대한 PR
    - ...B
    - ...B
  - 코멘트..
  - 코멘트..

---------------------

- 이슈가 생김
  - 코멘트..
  - 코멘트..
  - 무슨일이 있음
  - 무슨일에 대한 PR
  - ...A
  - 인덴트가 거지같다    <- 요런게 문제인듯 이슈에 대한 내용이 아니라 PR 에 대한 내용이니까
  - ...A
  - 다른일이 있음
  - 다른일에 대한 PR
  - ...B
  - ...A    <- 요런것도 중간에 끼니까
  - ...B
  - 코멘트..
  - 코멘트..

요런 느낌입니다.

**Comment by keedi** [comment]
이게 이슈와 PR이 UI가 비슷해서 자연스럽게 오해하게 되는데(깃헙이 잘못한거라고 생각함) 이슈를 처리하던 중 무슨 일이 있어서 작업하다가 다른 일이 있다면 그건 별도 이슈인게 맞습니다. 만약 그게 원래 이슈에 있는게 맞다면 그것은 별도 일이 아니라 원래 이슈에 포함된 것입니다.

깃헙에서 명명하는 PR은 말그대로 코드리뷰라고 보셔야 할 것 같습니다. 아니 봐야합니다. 즉 코드 자체에 대한 검증과 관련된 것은 PR에서 이야기 나누고 코드의 동작이나 기타 등등 코드의 목적이라든가 등등은 원래의 이슈에서 다루어야 할 것입니다. 예를 들어 코드 들여쓰기라던가, 코딩 스타일이라던가, 유닛테스트라던가, 주석이라든가, 눈에 보이는 버그라던가, 메모리 누수라던가... 등등. 정리하자면 소스코드에 가한 변경에 관한 이야기를 나누는 공간이 PR인 셈입니다.

다음 링크는 깃헙과 스태시(아틀라시안)에서 PR을 설명한 링크입니다. 역시 비슷한 이야기를 하고 있다고 생각되요.

- [GitHub - Using Pull Requests: Pull Request Discussion](https://help.github.com/articles/using-pull-requests/#pull-request-discussion)
- [Atlassian Stash - Pull Request In Stash - Discussing a pull request]https://confluence.atlassian.com/stash/using-pull-requests-in-stash-299570995.html#UsingpullrequestsinStash-discussDiscussingapullrequest

**Comment by 10001if** [comment]
@keedi @aanoaa 본 기능을 사용하려면 조금 시간이 더 필요할까요? 바쁘시겠지만 사용이 가능하다면 사용을 해보고 싶어서요. ^^

**Comment by keedi** [comment]
@10001if 네 @aanoaa 님께서 만들어주신 부분 검토 중이구요. 몇가지 더 수정 중입니다. 확실한 것은 오늘까지는 안될 것 같습니다 ㅋ

**Comment by 10001if** [comment]
네! 답변 주셔서 감사합니다. ^^

**Comment by aanoaa** [comment]
PR이 어떻게 생겼든 편리하게 사용하면 된다고 생각합니다.

코드리뷰의 도구니까 그정도로 사용하자고 하신다면 그리하겠습니다.
opencloset/opencloset 프로젝트는 @keedi 님이 주도적으로 하시니까 따르겠습니다.

근데 저는 어떠한 기능의 mockup 부터 피드백을 통한 구현의 완성까지 하나의 PR 에서 처리하고 싶은 맘이 있습니다.
제가 주도적인 프로젝트에서는 좀 더 자유롭게 쓰고 싶습니다.
이렇게도 해보고, 저렇게도 해보고..

오래전에 봤던건데 아래의 링크의 내용이 인상적이었습니다.
[How we use Pull Requests to build GitHub](https://github.com/blog/1124-how-we-use-pull-requests-to-build-github)


결론은 코드리뷰에 관한 내용은 PR 에 적고 나머지는 해당이슈에 적도록 하겠습니다.

**Comment by keedi** [comment]
머지 및 실 서버에 배포 완료했습니다. 이슈 닫습니다.

**Comment by keedi** [comment]
@10001if 테스트는 일단 테스트 서버로 했으면 합니다. 테스트 직전에 말씀해주세요.

**Comment by keedi** [comment]
PR 관련해서는 선배들이 그리했던 건 다 이유가 있겠건희... 생각 및 공감하지만 어쨌든 각자의 의견에 절충점이 없으니 결론적으로는 프로젝트별로 알아서 진행되는 것으로 알겠습니다. ㅎㅎ

**Comment by 10001if** [comment]
지금 완납시 선택할 수 있는 종류로 현금, 카드 계좌이체가 있습니다.
계좌이체와 현금은 다른 형태의 개념 이므로 
적격증빙 용어로 구분될 수 있도록

현금, 카드, 현금영수증, 세금계산서 이렇게 4가지 항목으로 구분을 요청드립니다. :)

**Comment by aanoaa** [comment]
fc2307234737fddd881f2f162325c19f227837cf

pay_with 로 잘못 구현되어 있는데 이것을 stage 를 보고 `미납`, `불납` 을 표시해주어야 합니다.

**Comment by aanoaa** [comment]
#650 에서 처리하겠습니다.

**Comment by keedi** [comment]
미납이라면 late_fee_pay_with 와 compensation_pay_with 로 판단하는 것이 맞습니다. 불납은 다르지만 어쨌든 미납은 결제 방식에 해당하는 거고 불납은 결제방식 중 하나가 아닌 미납금중 0원을 납부한 경우입니다.

**Comment by 10001if** [comment]
@aanoaa  결제시 미납된 사람이 기존 미납 주문서의 금액을 지불하여 완납처리를 해야할 경우, (제가 이해한 바는) 완납처리를 하려면 주문서 페이지에서 전체일을 입력하고 미납버튼을 누른 뒤, 대여일을 기준으로 이름을 찾아 완납으로 바꿔야 하는데요. 완납으로 조금 더 쉽게 바꿀 수 있는 방법이 있었으면 좋겠습니다. 제 생각으로는 미납 버튼을 누르면 전체 미납 주문서 중 대여일이 속해 있는 화면으로 이동을 할 수 있도록 할 수 있다면 어떨까 합니다. ^^

**Comment by 10001if** [comment]
작동하는 것은 확인하였습니다. ^^

**Comment by aanoaa** [comment]
미납처리를 위해 주문서를 찾는게 어렵다는건 알겠는데,

> 미납 버튼을 누르면 전체 미납 주문서 중 대여일이 속해 있는 화면으로 이동을 할 수 있도록 할 수 있다면 어떨까 합니다

라는 말을 이해하지 못했습니다.
좀 더 자세하게 설명해주세요.

**Comment by 10001if** [comment]
제가 컴퓨터가 없어서~ 사진 첨부를 못하는데요~ 미납 주문서를 완납처리하려면 (현재는) 주문서탭에서 미납으로 정렬된 페이지로 이동해야 하는 것으로 이해하고 있습니다. 그래야 만들어 주신 완납/불납 버튼을 눌러 완납이든 불납이든 처리할 수 있게되는데요. 그 페이지로 바로 이동할 수 있으면 좋겠다는 말이었습니다~ 잘 이해 안되시면 다음주에 찾아뵙고 설명드리도록 하겠습니다! ^^

**Comment by 10001if** [comment]
그런데 반드시 그 페이지에서 수정해야 하는게 아니라면 다른 방법을 사용해도 관계는 없습니다. 저는 단지 미납 주문서를 조금 거 쉽게 완납처리한 방법을 생각하다가 남겨놓은 이슈입니다 ^^

**Comment by aanoaa** [comment]
자주 말씀드리지만 어렵지 않을까 걱정마시고 필요하신거면 편하게 얘기하세영

**Comment by aanoaa** [comment]
주문서의 `미납` 버튼은 선택된 날짜의 `미납` 주문서 목록을 나타내는 목록인데,
이게 필요치 않다면 모든 미납주문서에 대한 버튼으로 변경하는게 더 좋을 수 있겠습니다.

**Comment by 10001if** [comment]
너무 좋은 생각인데요~ 미납화면을 주로 보는 담당자에게 확인해보고 글 남기겠습니다 ^^

**Comment by 10001if** [comment]
@aanoaa 확인해보니~ 네 모든 미납주문서에 대한 버튼으로 변경해 주시면 좋겠습니다. ^^

**Comment by aanoaa** [comment]
https://staff.theopencloset.net/order?booking_ymd=all&status=unpaid

수정하였습니다.
`미납` 버튼을 누르면 위 링크로 이동합니다.

**Comment by 10001if** [comment]
확인 완료하였습니다.
