### ISSUE TITLE
주문서에서 미납 혹은 불납한 사용자에 대해 추가 정보를 표시

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#650]
제곧내

**Comment by aanoaa** [comment]
제 아이디어 입니다.

![screenshot-localhost 5001 2015-12-24 11-47-15](https://cloud.githubusercontent.com/assets/170528/11988505/4c1764b8-aa34-11e5-84d1-f1c2a5708ab0.png)

미납, 불납등에 관한 이력이 있는 사용자에 대해서 위 주문서 화면에서 확인 할 수 있도록 표시해주고,

![screenshot-localhost 5001 2015-12-24 11-47-46](https://cloud.githubusercontent.com/assets/170528/11988518/6dec490a-aa34-11e5-8c91-b9507a5ddae5.png)

사용자 정보의 대여 이력에 미납등에 관한 이력을 남겨주면 직접 들어가서 확인 할 수 있지 않을까 합니다.

**Comment by aanoaa** [comment]
![screenshot-localhost 5001 2015-12-24 14-19-03](https://cloud.githubusercontent.com/assets/170528/11989918/833a8e4c-aa49-11e5-950f-1583ccddc8f7.png)

미납 혹은 불납의 이력이 있는 사용자의 어떠한 주문서에 들어가도 위와 같이 표시되게하고,
자세한건 사용자의 주문서 이력을 통해 확인할 수 있도록 하였습니다.

![screenshot-localhost 5001 2015-12-24 14-20-02](https://cloud.githubusercontent.com/assets/170528/11989927/abeed3e8-aa49-11e5-82a6-3f20f64c749e.png)

**Comment by aanoaa** [comment]
@10001if 의견을 말씀해주세여.

**Comment by aanoaa** [comment]
fc2307234737fddd881f2f162325c19f227837cf

pay_with 로 잘못 구현되어 있는데 이것을 stage 를 보고 `미납`, `불납` 을 표시해주어야 합니다.

**Comment by keedi** [comment]
미납이라면 반납인 상태이면서 late_fee_pay_with 와 compensation_pay_with 로 판단하는 것이 맞습니다. 불납은 다르지만 어쨌든 미납은 결제 방식에 해당하는 거고 불납은 결제방식 중 하나가 아닌 미납금중 0원을 납부한 경우입니다.

**Comment by keedi** [comment]
stage로 보면 그게 그거일수도 있고... 여튼 이미 알고 계시겠지만 아까 이야기대로라면 부분 완납은 납부한 금액이 얼마이든지 간에 표시하지 않는다고 합니다.

**Comment by aanoaa** [comment]
주문서의 order_detail 에 stage `4` 가 있다면 해당 사용자는 `불납` 으로 봐도 되지 않을까요?

**Comment by aanoaa** [comment]
미납에 대해서는 주문서의 `late_fee_pay_with` 또는 `compensation_pay_with` 가 `미납` 인지 확인해보면 될테고,
불납은 사용자의 주문서중에 stage 가 `4` 인 이력이 있다면 될 것 같습니다.

**Comment by aanoaa** [comment]
불납이면서 미납인 사용자도 있을 수 있기 때문에,
둘중 한개만 보여줄 것인지 둘다 표시할 것인지도 판단해야 합니다.

cc @10001if

**Comment by aanoaa** [comment]
![screenshot-localhost 5001 2016-01-06 15-41-41](https://cloud.githubusercontent.com/assets/170528/12136540/47083ef4-b48c-11e5-9afe-aa1a6fb86b81.png)

해당 주문서에 대해 미납인지 불납인지 나타내주고,

![screenshot-localhost 5001 2016-01-06 15-42-20](https://cloud.githubusercontent.com/assets/170528/12136546/525d7c60-b48c-11e5-97cf-b306bda2929f.png)

미납, 불납 둘다 해당된다면 사용자의 모든 주문서에 미납과 불납의 이력을 표시해줍니다.

불납의 이력이 없다면,

![screenshot-localhost 5001 2016-01-06 15-43-08](https://cloud.githubusercontent.com/assets/170528/12136557/6b1e6b06-b48c-11e5-8342-c2c96f35c997.png)

미납의 이력만 표시됩니다.

**Comment by 10001if** [comment]
네~ 말씀해 주신 것 처럼 둘 다 표시해주시는게 깔끔하게 이해될 것 같습니다! ^^
