### ISSUE TITLE
예약 취소를 옷장지기가 직접 할 수 있도록 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#652]
직접 예약을 취소할 수 있음에도 불구하고 전화로 예약을 취소하는 비율이 훨씬 많습니다.

그래서 전화가 왔을 때, 예약화면에서 직접 취소를 해드리면 빠르고 간편할 것 같은데요. 요즘은 취소전화가 와도 그냥 듣고만 말아버리는 것 같습니다. 최소를 쉽게 할 수 있는 방법이 있다면 요청드리고 싶습니다.
![2015-12-24 2 39 29](https://cloud.githubusercontent.com/assets/4696328/11990160/de8e1446-aa4c-11e5-9693-23e6c14d139e.png)

**Comment by aanoaa** [comment]
사용자 이름을 누르면 여러 기능 버튼들을 보여주고 클릭하면 동작하도록 하려합니다.
bootstrap 3.0 을 사용중이라서 http://getbootstrap.com/javascript/#collapse 사용하는데 제약이 있습니다.

**Comment by aanoaa** [comment]
dropdown 을 사용하는 것도 괜찮을 것 같습니다.

**Comment by aanoaa** [comment]
http://bootstrapdocs.com/v3.0.0/docs/javascript/#dropdowns

**Comment by aanoaa** [comment]
4명 slot 인데 3명 예약인 상태에서 1명을 취소하면 2명을 더 예약 받을 수 있는지 확인해봐야 합니다.

**Comment by aanoaa** [comment]
취소 상태가 없습니다.
대체할 수 있는지 찾아보고 없으면 취소 상태 추가에 대한 논의가 필요합니다.

**Comment by aanoaa** [comment]
직접 예약 취소하는 절차가 어떻게 되나요?

**Comment by aanoaa** [comment]
POST /visit

    booking=-1

HTTP request 를 보내면 됩니다.
내부적으로 호출하면 될 것 같습니다.(어떻게?)

취소 절차는

    xxx님 xx월 xx일 xx시 xx분 방문 예약이 취소되었습니다.

안내 문자메세지를 보내고, 주문서에서 상태를 변경하는 것이 아니라 주문서 자체를
삭제합니다.

**Comment by 10001if** [comment]
확인하였습니다. 감사합니다. ^^

**Comment by 10001if** [comment]
문자 내용 수정을 요청드릴게요 ^^
** [열린옷장] xxx님 xx월 xx일 xx시 xx분 방문 예약이 취소되었습니다. 감사합니다. ** 
이렇게 부탁드립니다. ^^

**Comment by aanoaa** [comment]
수정하고 배포하였습니다.

**Comment by keedi** [comment]
resultset 검색 이후 바로 `->first` 호출하는 부분으로 인해 반환 객체가 undefined임에도 불구하고 메소드 접근하는 경우가 있었습니다. 관련해 해당 경우 반복문의 다음 과정으로 넘어가 더이상 접근하지 않도록 수정했습니다.

실서버에도 배포했습니다.
