### ISSUE TITLE
합격자를 확인할 수 있는 버튼 추가

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#655]
대여자가 합격을 한 경우, 합격여부를 기록해 놓으려고 합니다. 따로 합격 여부를 체크하려고 하는데 쉽게 반납시 합격 여부를 확인하려고 합니다. 그래서 반납 버튼 좌측에 합격버튼을 만들어 넣으려고 합니다. 합격자라는 상태가 추가되어야 할 것 같은데, 이해가 되지 않는 부분이 있으시면 이야기 해주시기 바랍니다.

![2015-12-30 12 39 45](https://cloud.githubusercontent.com/assets/4696328/12046060/7871ecb8-aef3-11e5-8b7c-739e4196da9a.png)

**Comment by 10001if** [comment]
합격버튼을 누르면 이 옷을 기증한 기증자에게 문자메세지로 연락이 갈 수 있도록 하였으면 합니다.

**Comment by aanoaa** [comment]
대여자와 주문서로 나뉘어서 생각해 볼 수 있습니다.

1. 이 주문서를 통해 대여해간 사용자는 합격이다.
2. 어떤 주문서이건 한번 합격한 사용자는 합격이다.(무슨말이지..)

> 합격버튼을 누르면 이 옷을 기증한 기증자에게 문자메세지로 연락이 갈 수 있도록 하였으면 합니다.

이게 목적이라면, 주문서에 합격에 관련된 정보를 넣는 것으로 충분할 것 같습니다.

**Comment by aanoaa** [comment]
어느 상황에서 쓰여질 것인지 알아야 합니다.
재방문자에 대해 합격여부를 알아야 하는건지등에 대한거요.

**Comment by aanoaa** [comment]
어떻게 쓰일지는 잘 모르겠지만, 주문서에 대해 합격여부를 기록할 수 있으면 됩니다.

**Comment by 10001if** [comment]
어떤 상황에서 필요한 것인지는 다시 한번 확인해보겠습니다.

**Comment by aanoaa** [comment]
주문서에 합격 여부가 필요합니다.
이 컬럼을 `order` 와 `order_detail` 중 어디에 놓을지 선택해야 합니다.

컬럼명으로는,

- acceptance
- pass
- get_pass
- success

등을 고려해볼만 합니다.

**Comment by 10001if** [comment]
확인하였습니다. 감사합니다.

**Comment by 10001if** [comment]
합격 버튼이 현재는 반납 진행하기 전에만 보이는데 반납 진행 중(바코드 찍는 과정 중)에도 보였으면 좋겠다는 요청이 들어 왔습니다. 검토부탁드립니다. ^^

**Comment by 10001if** [comment]
@aanoaa  반납 진행 중에도 버튼이 있어야 하는 이유는 오자마자 합격여부를 묻지는 않고 반납을 진행하면서 묻는 경우가 대부분이기 때문입니다.

**Comment by MoDoLEE** [comment]
`반납`이 모두 완료된 이후 (주문서가 닫힌 이후)에도 `합격` 여부를 변경할 수 있게 해달라는 요청이 있었습니다.
`반납`이 완료된 후 대여자의 메세지를 입력하는 도중 `합격` 사실을 알게 됐을 때, 현재는 입력할 수 있는 방법이 없어서 구글 독스에 정리하고 있습니다.

**Comment by MoDoLEE** [comment]
소령님께서 확인하시고 대만족해 하십니다~^^
