### ISSUE TITLE
방문자 통계에서 입력하는 날짜에 따라 주별, 월별 기록도 변화하도록 함 

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#659]
![2016-01-07 1 56 41](https://cloud.githubusercontent.com/assets/4696328/12162527/bebe39de-b546-11e5-836c-221fa5d463c0.png)

2015년 11월 19일로 검색하여도 주별, 월별 기록은 오늘 기준인 1월 7일에 머물러 있습니다. 때문에 작년 기록을 살펴보려고 할 때 기록을 확인하기가 어려운데요. 입력하는 날자에 따라 주별, 월별 기록도 변경이 되었으면 좋겠습니다.

**Comment by keedi** [comment]
> 일단 공식적으로 letters, visit 작업을 제외하고는 제가 처리하지 않을 예정입니다. 기존 제가 처리하려고 했던 이슈는 모두 담당자를 제거한 이후, 그 이후에 새롭게 담당자로 제가 지목되는 이슈에 한해 처리하겠습니다. 관련해서 제가 할당된 이슈의 담당자를 모두 제거하겠습니다.

상기 상황과 같으나 본 이슈는 제가 처리하는 것이 가장 효율적이고 빠르므로 담당자를 제거하지 않고 진행하겠습니다.

**Comment by keedi** [comment]
진행합니다.

**Comment by keedi** [comment]
시간이 지나고 지나 5월이 되어 주차가 쌓이고 월별이 쌓여서 처리해달라는 요청이 안들어오고 있습니다만, 내년에도 반복될 문제이므로 처리하겠습니다.

**Comment by keedi** [comment]
명확하지 않은 요구사항은 다음과 같습니다.

- 입력한 날짜를 기준으로 몇 개의 **지난 주** 또는 **지난 개월** 정보가 보고 싶은 것인가?
- 입력한 날짜가 속한 주 또는 개월이 가운데 위치하는가 또는 가장 끝에 위치하는가?

**Comment by keedi** [comment]
특별히 언급이 없으므로 우선 임의로 진행합니다.

- 52개주와 12개월을 보이게 함
- 입력한 날짜가 목록의 가장 마지막에 위치하게 함

**Comment by keedi** [comment]
구현 완료했습니다. 피드백 받은 후 그 결과를 반영하겠습니다.

**Comment by keedi** [comment]
구현한 화면입니다.

![screenshot-monster silex kr 10301 2016-05-17 17-58-07](https://cloud.githubusercontent.com/assets/138451/15316999/8a2ef872-1c5a-11e6-9896-bbf1d1097f8c.png)

**Comment by keedi** [comment]
피드백 내역입니다.

- 현재 날짜 기준으로 이전 2일, 이후 2일 보이는데 이전 7일, 이후 7일을 보이게 함
- 현재 날짜 기준으로 이전~이후 날짜를 보이게 할때 요일을 표시함

**Comment by keedi** [comment]
피드백 처리 완료했습니다.

**Comment by keedi** [comment]
완료한 화면은 다음과 같습니다.

![screenshot-monster silex kr 10301 2016-05-17 18-23-23](https://cloud.githubusercontent.com/assets/138451/15317559/fbc1e844-1c5c-11e6-8e6d-2f38fadf58e5.png)

**Comment by keedi** [comment]
@10001if 피드백 부탁드립니다.

**Comment by keedi** [comment]
피드백 받았으며 기능에 문제 없다고 합니다.
PR 머지 후 이슈 닫으면 될 것 같습니다. :)

**Comment by aanoaa** [comment]
관행대로 `배포대기` 라벨을 제거하고 배포후에 `확인요망` 라벨을 붙여놓도록 하겠습니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^

**Comment by 10001if** [comment]
![2016-05-31 10 52 50](https://cloud.githubusercontent.com/assets/4696328/15660972/1c86c010-271e-11e6-90da-2b76c49bc51d.png)
@keedi 이유는 잘 모르겠지만 2015-12월의 자료가 나타나지 않습니다. 확인 부탁드릴게요.

**Comment by keedi** [comment]
@10001if 피드백 이후 이슈가 닫히고 난 뒤 발생하는 문제는 기존 이슈를 열어서 추가하지 마시고 별도 이슈를 생성해서 남겨주세요.

**Comment by keedi** [comment]
v1.5.5에 적용 되었으므로 마일스톤을 v1.6으로 변경합니다.

**Comment by keedi** [comment]
@10001if 당시 해가 바뀔때 내부 캐싱 문제 때문에 12월 분량이 연산되지 않았던 이슈입니다. 실서버에 강제로 연산시켜 결과를 캐싱시켜놓았으니 이제 잘 보일 겁니다. :)

해당 페이지 관련해서 이슈가 있을 경우 별도 이슈를 열어서 기록해주세요~~

**Comment by 10001if** [comment]
@keedi 네! 확인했습니다. 새로운 문제가 생기면 새 이슈 열도록 하겠습니다! ^^
