### ISSUE TITLE
사용자의 사진을 업로드

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#662]
gravatar 를 사용하거나 avatar.theopencloset.net 을 사용해서 사용자의 프로필사진을
등록하고 보여줍니다.

우선 https://github.com/opencloset/volunteer/issues/15 의 자원봉사자 사진문제를 해결하기 위해 필요합니다.

1. 사용자의 email 을 가지고 gravatar 에 있는지 확인
2. 없으면 avatar.theopencloset.net 에서 확인

하도록 합니다.
없으면 default 이미지를 보여줍니다.

**Comment by aanoaa** [comment]
gravatar 를 사용할때에,

    %= gravatar('email@example.com')

으로 사용하는데 이는,

    <img src="https://secure.gravatar.com/avatar/5bd1bbd346a935f379c0db007cdbc81a>

이런식으로 바뀝니다.

https://secure.gravatar.com/avatar/5bd1bbd346a935f379c0db007cdbc81a 에
대한 응답이 어떨지는 브라우저에서 해결하는거고, application 에서는
관여치 않습니다.

`5bd1bbd346a935f379c0db007cdbc81a` 에 대한 이미지가 존재하지 않는다면
gravatar 에서 응답하는 기본 이미지가 보여지게 될 것입니다.

요는 사용하는 입장에서는 응답결과는 상관없습니다.

    avatar = gravatar || avatar.theopencloset.net

가 어려운 이유는 gravatar 에 요청한 결과를 application 에서 컨트롤해야
합니다.

보통 브라우저에 url 만 전달해주면 끝인데, 각 이미지의 응답을
컨트롤해서 gravatar 에 없으면 avatar.theopencloset.net 을 사용해야
하는 점이 어렵습니다.

**Comment by keedi** [comment]
d 404 매개변수를 이용하면 응답 코드로 이미지 여부를 확인할 수 있습니다.

http://codex.wordpress.org/Using_Gravatars

HTML렌더링 타임에 응답보고 처리해도 되고 avatar 사이트가 cgi로 처리해도 될거 같습니다.

**Comment by keedi** [comment]
곰곰히 생각해보니 그라바타를 신경쓰는게 무의미한 것 같기도 하네요. 특별히 진행하신 것 없으시면 걍 avatar.theoc.net 만 쓰는 원안대로 가시죠.

**Comment by aanoaa** [comment]
한번 가입해놓으면 많은 곳에서 사용할 수 있는 gravatar 를 직접 쓰는게
좋을 것 같지만, 여기서 원하는건 직원이 자원봉사자를 대신해서 얼굴을
기억하기 위해 사진을 등록하게 될 것입니다.

gravatar 의 default 이미지를 내부서비스로 변경하면 둘 다 사용할 수
있을 것 같습니다.

    http://gravatar.com/avatar/12345?d=https://avatar.theopencloset.net/avatar/12345

gravatar 에서 12345 에 대한 이미지가 등록되어 있지 않으면, default
이미지인 https://avatar.theopencloset.net/avatar/12345 을 가지고 와서
보여주게 될 것입니다.

**Comment by aanoaa** [comment]
자원봉사쪽에서 해결하도록 하겠습니다.
