### ISSUE TITLE
통계 - 어울림 메뉴 표시 방법 수정

### ISSUE THREAD

**Issue by MoDoLEE** [opencloset/opencloset#663]
현재 모든 `Best- fit` 데이터가 한 페이지에 표시됩니다.
`Best-fit` 데이터양이 적을 때에는 문제가 없었는데,
데이터가 많아 지면서 페이지 로딩에 많은 시간이 걸립니다.

페이지를 나눠서 페이지 당 20개 가량의 `Best-fit` 데이터를 보여 주고,
밑에는 페이지 이동 숫자 표기가 있으면 좋겠습니다.
다른 더 좋은 방법이 있으면 그렇게 해주시면 더 좋을 것 같습니다! ^^

**Comment by 10001if** [comment]
과거에는 베스트 핏을 볼 수 있는 곳이 없어서 본 페이지 구축을 요청드렸지만 현재는 의류별로 베스트 핏을 확인할 수 있는 구조가 되어서 본 이슈의 필요성이 상대적으로 적어졌습니다. 우선 이슈를 닫고 다시 요청드릴 필요가 있을 때 열도록 하겠습니다.

**Comment by 10001if** [comment]
> 과거에는 베스트 핏을 볼 수 있는 곳이 없어서 본 페이지 구축을 요청드렸지만 현재는 의류별로 베스트 핏을 확인할 수 있는 구조가 되어서 본 이슈의 필요성이 상대적으로 적어졌습니다. 우선 이슈를 닫고 다시 요청드릴 필요가 있을 때 열도록 하겠습니다.

이상에 적은 것처럼 큰 의미가 없어 보이기 때문에 이슈를 닫았습니다.
