### ISSUE TITLE
미납받은 것을 찾아서 입력하기 어려움

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#664]
미납금을 완납으로 바꾸려면 전체목록에서 해당 사용자의 특정 주문서를 찾아서 `완납` 버튼을 눌러줘야 합니다.
이를 찾기가 매우 어렵습니다.
검색이라도 되어야 합니다.

**Comment by aanoaa** [comment]
`미납` 탭에서 이름으로 검색하시면 됩니다.

**Comment by 10001if** [comment]
@aanoaa 이름으로 검색하는 부분이 어디에 있는지 잘 모르겠습니다~

**Comment by aanoaa** [comment]
![screenshot-staff theopencloset net 2016-03-10 10-24-30](https://cloud.githubusercontent.com/assets/170528/13656451/54e90896-e6aa-11e5-83ab-f5f474a95719.png)

**Comment by 10001if** [comment]
확인완료하였습니다. ^^
