### ISSUE TITLE
대여화면에서의 정렬

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#665]
포장이 먼저 이루어져야 하는 사람이 가장 위로 갈 수 있도록 목록의 순서를 정렬해야 합니다.

**Comment by aanoaa** [comment]
지금은 예약시간 기준인데, 이것을 상태변경시간으로 바꾸면 될 것 같습니다.

**Comment by aanoaa** [comment]
젤 위에 있는 주문서가 가장 먼저 포장해야 되는 주문서가 되도록

**Comment by 10001if** [comment]
확인완료하였습니다.
