### ISSUE TITLE
전체반납 후에 400 error

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#666]
가끔씩 전체반납버튼을 누르고 나면 `/order/undefined` 로 redirect 되서 400 error 가 발생합니다.
주소이동에만 문제가 있을 뿐, 반납은 처리됩니다.

**Comment by keedi** [comment]
이 건의 경우 언제 몇번 주문서를 처리했을 때를 안다면 백업 데이터베이스를 이용해서 재현이 가능할 것 같고 그렇다면 디버깅이 좀 용이할 수 있을 것 같습니다. 우선 재현이 안된다면 수정하기가 쉽지 않겠죠.

@10001if 최근에 전체 반납 이후 400 오류가 발생한 경우가 있나요?

**Comment by 10001if** [comment]
@keedi 따로 전달받은 건은 없는데, 그래도 다시 확인해보겠습니다. ^^

**Comment by 10001if** [comment]
@keedi 확인해 본 결과 최근엔 400오류가 발생한 적이 없다고 하네요.

**Comment by yongbin** [comment]
재현되지 않으므로 invalid 로 처리하겠습니다. 재현될 경우 새로운 이슈로 열어주세요
