### ISSUE TITLE
부분반납 하위 주문서에 대여가능 상태가 존재함

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#670]
김슬기님(주문서번호 : 상위주문서(21125) 하위주문서 (21437)) 반납의류 부분반납 상태인데, 
하위주문서에 있는 반납의류가 대여가능 상태입니다. 조금 이상한 것 같아 우선 이슈에 남겨놓습니다.

**Comment by yongbin** [comment]
@aanoaa 어떻게 결정되었는지 내용 기록해주세요
