### ISSUE TITLE
신체 치수 예측의 어울렸던 의류 정보에 다른 성별의 의류가 표시 됨

### ISSUE THREAD

**Issue by MoDoLEE** [opencloset/opencloset#672]
![image](https://cloud.githubusercontent.com/assets/14110661/12436160/11c4e9ca-bf56-11e5-9783-2c4e5650639c.png)
키 몸무게 남성으로 입력 한 후 예측을 눌렀는데, 여성의 베스트핏 정보가 뜹니다.

**Comment by 10001if** [comment]
![2016-03-10 10 25 11](https://cloud.githubusercontent.com/assets/4696328/13656460/6d1e7504-e6aa-11e5-9fc6-3dcdc0d27548.png)
여전히 여성의 의류정보가 뜨는 것 같습니다~ 확인 부탁드릴게요~

**Comment by aanoaa** [comment]
검색을 어떻게 하셨나요?

**Comment by aanoaa** [comment]
168/55 남성으로 했다고 합니다.

**Comment by aanoaa** [comment]
`어울렸던 유사 의류 정보` 에서 수정했는데, `어울렸던 의류 정보` 가 수정되어야 합니다.

**Comment by aanoaa** [comment]
@MoDoLEE @10001if 수정되었습니다.

**Comment by 10001if** [comment]
확인완료하였습니다.
