### ISSUE TITLE
`대여`에서 의류의 상태변경이 가능하도록 함

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#673]
지난번에 이슈화 되었었는데, 바람직하지 않다고 해서 짬됐었습니다.
하지만, 어차피 의류를 대여하는 과정에서 `대여가능` 상태로 변경되지
않은 의류가 발생하면 첫화면으로 이동해서 상태를 변경하고 다시
대여프로세스를 거쳐야 하는 번거로움이 있습니다.

이는 포장단계에서 번거롭기때문에 해결되어야 합니다.

**Comment by 10001if** [comment]
#546 이슈와 동일한 것으로 보입니다 ^^
