### ISSUE TITLE
사이즈 측정자의 이름을 입력

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#674]
@yongbin 대표님께서 사이즈을 측정하는 담당자의 이름을 입력하는 것이 필요하다는 의견을 주셨는데, 동감합니다. 기 능 추가를 요청드립니다.

**Comment by yongbin** [comment]
@10001if 이 기능은 사이즈 측정자가 업무를 시작할때 자신의 id로 staff 에 로그인하고 업무가 종료되면 로그오프해야만 가능한 시나리오입니다. 실제 어떻게 운영중인지 알려주세요

**Comment by aanoaa** [comment]
아직은..
