### ISSUE TITLE
방문예약시 이메일 중복 여부를 표시되도록 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#675]
방문예약을 신청하거나, 직원예약으로 예약을 진행할 경우 예약창에서 이메일이 중복되는지 여부를 확인할 수 없어 다 입력을 하고도 완료가 되지 않는 경우가 많았습니다. 예약시 이메일 중복 여부를 확인 할 수 있도록 하는 작업을 요청드립니다.

**Comment by aanoaa** [comment]
이메일이 이미 등록되어 있다는건, 핸드폰 번호가 바뀌어서 그런 것 같습니다.

@10001if 님의 정보로 시뮬레이션 해봤더니 `10001if@theopencloset.net` 으로 나타납니다.
만약에 핸드폰 번호가 바뀌엇다고 가정해보면, 처음 보는 폰번호라서 시스템에서는 못찾을테고
동일한 이메일을 입력한다면 중복오류가 발생할 것 같습니다.

**Comment by 10001if** [comment]
@aanoaa 네 맞습니다. 핸드폰 번호가 바뀐 경우가 대부분인데요. 동일한 이메일에 다른 전화번호가 입력되는 경우에 이미 입력된 전화번호가 있다고 안내를 해주었으면 좋겠습니다. 이 상황을 모르면 전부 입력을 다 하더라도 저장이 되지 않아 베드게이트 오류가 뜨는 경우가 많기 때문입니다. ^^

**Comment by aanoaa** [comment]
핸드폰 번호가 바뀌었을때의 고려를 해야합니다.

**Comment by MoDoLEE** [comment]
"동일한 이메일이 이미 존재합니다. 타인의 이메일을 사용하실 경우 예약이 불가능 합니다. 지난 번 대여하실 때 입력 하셨던 휴대전화 번호와 현재 입력하신 휴대전화 번호가 다른 경우 열린옷장으로 전화 문의 바랍니다." 정도의 에러 메세지를 띄워주면 되지 않을까요?

**Comment by aanoaa** [comment]
적절한 대안이라고 생각합니다.
예약하면서 email 입력후에 존재하는지 체크후에 에러메세지를 보여주도록 하겠습니다.

근본적인 대안은 다음으로 미루도록 하겠습니다.

**Comment by MoDoLEE** [comment]
@10001if 에러 문구 최종 확인 부탁드립니다.

**Comment by 10001if** [comment]
확인완료하였습니다.

**Comment by aanoaa** [comment]
재방문자를 고려하지 못했습니다.
재방문자가 예약하려고 하면 중복된 이메일 알람을 받게됩니다.

기능을 예전처럼 되돌리고 근본적인 해결방안을 고민해봐야 합니다.

**Comment by aanoaa** [comment]
배포시에

    $ grunt

해주어야 합니다.

**Comment by aanoaa** [comment]
@MoDoLEE 기능을 롤백하였습니다.
재방문자의 경우 예약이 가능한지 테스트해주세요.

**Comment by MoDoLEE** [comment]
@aanoaa 재방문자 예약 정상 동작합니다.

**Comment by aanoaa** [comment]
인증번호입력후에,

- 처음사용자라면

email 입력후에 이메일이 존재하는지 확인하고 안내메세지를 보여줍니다.

- 재방문이라면

email 을 변경할 수 없도록 합니다.

**Comment by 10001if** [comment]
확인완료하였습니다.
