### ISSUE TITLE
최초 예약 신청시 발송되는 SMS에 첨부되는 지도 변경

### ISSUE THREAD

**Issue by MoDoLEE** [opencloset/opencloset#678]
현재 열린옷장 안내 홈페이지에 지도와 함께 동영상을 추가 하였습니다.
그래서 네이버 지도 대신 홈페이지에 찾아 오시는 길 페이지를 링크하려 합니다.
https://goo.gl/UuJyrx

**Comment by aanoaa** [comment]
배포하고나면 알아서 닫도록 하겠습니다.
