### ISSUE TITLE
동일한 기증자가 같은 날 기증한 경우 "함께 기증된 의류"로 표시될 수 있도록 함.

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#681]
지난 번에 말씀드린 것처럼 실제 한번의 기증행위이지만 수선, 세탁이나 바코드를 다는 이슈와 맞물려서 여러번 나눠 기증행위로 새 옷 등록을 한다고 합니다. 같은 기증자가 같은 날 기증을 한 것이라면 모두 "함께 기증된 의류"에 뜰 수 있도록 요청드립니다.

**Comment by aanoaa** [comment]
현재의 `기증` 메뉴를 활용해서 원하는 기능을 대체할 수 있습니다.
새로운 새옷등록에서 해결하도록 하겠습니다.
