### ISSUE TITLE
의류준비화면 액션이 안 먹힘

### ISSUE THREAD

**Issue by MoDoLEE** [opencloset/opencloset#683]
의류 준비화면 ~/preparation 에서 어떠한 액션도 먹히질 않습니다.
탈의실 넣기, 의류 준비로 빼기, 수선, 포장으로 바꾸는 액션이 아무것도 안됩니다.
시간표 상에서 상태 변경은 가능합니다.

**Comment by MoDoLEE** [comment]
1/30
10시 ~ 10시 20분 사이 잠시 발생했다가 현상이 사라졌습니다.

**Comment by aanoaa** [comment]
상태변경을 서로 업데이트하기 위해서 모니터와 staff 가 서로 통신하고
있습니다. 모니터쪽에서 staff 에 API 를 사용하기 위해서 인증하고 효율을
위해 cookie 를 저장해두고 사용합니다. 어제 저녁에 subdomain 에서의
재인증을 막기위해서 cookie 와 관련된 작업을 하였습니다.

https://github.com/opencloset/opencloset/issues/625#issuecomment-176519104

그것에 대한 영향이 아닐까 합니다.

모니터에서 cookie 파일이 유효하다고 생각해서 인증시도를 하지않고
통신을 시도했고, 유효시간이 지난다음에야 재인증을 시도해서 해결되었을
것 입니다.

이런 사이드 이펙트가 있을 거라고 미처 생각하지 못했습니다.

**Comment by aanoaa** [comment]
@yongbin 이 이슈는 쿠키 파일이 갱신되면서 해결된 것 같은데요?

**Comment by yongbin** [comment]
아 냅 그냥 모든 이슈는 가능하면 테깅하고 처리한사람 등록해두려고 지정해놓은겁니다. Reopen이 아니면 신경안쓰셔도 됩니다!
