### ISSUE TITLE
반납후에 문자메세지 발송

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#690]
반납직후에 정해진 포맷으로 문자메세지가 발송

**Comment by yongbin** [comment]
@10001if 반납직후 보낼 문자의 포맷을 정리해주세요

**Comment by 10001if** [comment]
[열린옷장] 000이 반납하신 의류가 정상적으로 반납완료되었습니다. 감사합니다.

**Comment by aanoaa** [comment]
택배도 그렇고 보통 받기전엔 문자 보내고 주고 나선 안그러던데..

이게 필요한가 싶습니다.
그냥 제 생각이에요.

**Comment by 10001if** [comment]
@aanoaa 무인 반납함이 생기고 나서 반납처리가 잘 되었는지 문의하는 분들이 꾸준히 계시다고 해서요. 좀 불필요하게 느껴지는 부분이 있기도 하지만, 받는 분들 입장에서는 명확하고 해서 나쁘지는 않을 것 같아요 ^^

**Comment by aanoaa** [comment]
부분반납이나 환불후에는 해당하지 않나요?

**Comment by 10001if** [comment]
@aanoaa 네! 전체 반납인 경우에만 해당됩니다.

**Comment by aanoaa** [comment]
> [열린옷장] 000이 반납하신 의류가 정상적으로 반납완료되었습니다. 감사합니다.

`반납완료되었습니다` 문장이 좀 이상한데요?
`반납되었습니다` 가 자연스럽습니다.

**Comment by 10001if** [comment]
@aanoaa 네~ 그게 더 자연스럽네요 ^^ 반납되었습니다로 부탁드릴게요~

**Comment by 10001if** [comment]
확인완료하였습니다.
