### ISSUE TITLE
완납 후에 문자메세지 발송

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#691]
미납금이나 배상비들을 완납한 후에 정해진 포맷으로 문자 메세지를 보내야 합니다.

**Comment by keedi** [comment]
wontfix라던가 상태가 변경되었을 때는 어떤 연유로 그리 되었는지를 남겨주시면 좋을 것 같습니다. 보통은 "@10001if 님과 논의했는데 ... 한 이유로 처리하지 않기로 했다..." 겠지요? :)

**Comment by aanoaa** [comment]
네 저는 기억이 나질 않습니다.

**Comment by 10001if** [comment]
@keedi  이건 제가 말씀드려서 태그를 달아주신 것입니다. 완납이라는 뜻이 아직 모호하기 때문입니다. 돈을 다 받아야만 문자를 발송하는 건지 일부만 받았을 때에도 문자를 발송하는 것인지 개념이 명확하지 않아 그 부분을 명확하게 한 뒤에 다시 요청드리려고 합니다.

**Comment by 10001if** [comment]
논의 해보니 아직 생각이 결정되지 않은 것으로 보입니다. 이번 주 중으로 생각을 정리해서 다시 말씀드리도록 하겠습니다.

**Comment by 10001if** [comment]
전체반납 후 반납확인 문자가 발송되는 것처럼 전체 완납 후 입금확인 문자가 발송되었으면 합니다.

**Comment by keedi** [comment]
제가 진행하겠습니다. :)

**Comment by 10001if** [comment]
@keedi 크게 중요한 이슈가 아닙니다. 우선 이슈 닫았다가 문제 제기가 다시 생기면 그때 열어서 요청드리겠습니다.
