### ISSUE TITLE
반납예정일을 동기화

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#693]
![screenshot-duflsdhtwkdahslxj theopencloset net 2016-02-05 10-53-14](https://cloud.githubusercontent.com/assets/170528/12835809/c169e90a-cbf6-11e5-9551-28e7e6589170.png)
![screenshot-staff theopencloset net 2016-02-05 10-52-03](https://cloud.githubusercontent.com/assets/170528/12835810/c17b00b4-cbf6-11e5-90ae-48ff6438dd07.png)

한번 반납예정일을 지정하게 되면 주문서에서 반납예정일이 바뀌어 있어야 합니다.

**Comment by aanoaa** [comment]
적용하였습니다.
@10001if 제대로 동작하는지 확인 꼭 좀 해주세요.

**Comment by aanoaa** [comment]
저는 확인했습니다.

**Comment by MoDoLEE** [comment]
대여 기간을 3박 4일에서 다른 것으로 변경할 경우 반납 예정일이 오늘 날짜가 되어 버립니다.

예:
대여기간 : 3박4일
대여일 : 2016-02-11
반납 예정일 : 2016-02-14

대여기간 변경
대여기간 : 5박6일
대여일 : 2016-02-11
반납 예정일 : 2016-02-11 (원래대로라면 2016-02-16 이 정상입니다.)

**Comment by aanoaa** [comment]
https://duflsdhtwkdahslxj.theopencloset.net/target_date.json

이대로 변경되어야 합니다.
왜 그렇지..

위 주소에 접근했을때 400 에러가 발생하는 곳에서는 사용할 수 없습니다.
IP 주소가 허가된 곳에서만 가능하거든요.

**Comment by aanoaa** [comment]
@MoDoLEE 이건 배포되자마자 제가 확인해봤을때는 제대로 동작했습니다.
5층의 결제용 PC에서 발생하고 있는 건가요?
지금도 발생하고 있나요?

**Comment by MoDoLEE** [comment]
넵 5층 결제용에서 지금도 발생합니다.
다른 곳에서 할 경우엔 대여일 반납예정일을 아예 불러오지 못해서, 비어있음으로 표시됩니다.

**Comment by aanoaa** [comment]
직접 확인 했습니다.
`대여기간` 을 눌러서 `3박 4일` 을 `4박 5일` 로 바꾼다던지 했을때에
반납예정일이 같이 변경되지 않고 있습니다.

**Comment by 10001if** [comment]
확인완료하였습니다.
