### ISSUE TITLE
의류의 가슴사이즈 자료 DB 일괄 수정

### ISSUE THREAD

**Issue by yongbin** [opencloset/opencloset#694]
![index](https://cloud.githubusercontent.com/assets/52704/12948917/7d184b1a-d048-11e5-97f5-cf869b8b9145.png)

지난 1년간의 대여자료의 리뷰를 통해서 기존 DB에서 잘못 입력되 의류치수 관련 정보를 제거합니다.

 - [x] pants는 가슴둘레가 없다.
 - [x] skirt도 가슴둘레가 없다.
 - [x] jacket에 가슴둘레가 0인값은 삭제
 - [x] blous에서 가슴둘레가 0인값 삭제
 - [x] 가슴둘레가 있는 옷 종류는 : blues, coat, shirt, jacket, onepice
 - [x] shirt에서 가슴둘레가 < 15 삭제

이 이슈와 동일한 형태로 모든 의류의 사이즈 항목에 대한 처리를 진행할 예정입니다.

**Comment by yongbin** [comment]
> pants는 가슴둘레가 없다.

```SQL
SELECT `code`, bust FROM `clothes` WHERE `category` = 'pants' AND `bust` IS NOT NULL 
```

2일전 덤프한 로컬 디비 기준으로 영향을 받는 의류의 수는 1860건입니다.

**Comment by yongbin** [comment]
> skirt도 가슴둘레가 없다.

```sql
SELECT `code`, bust FROM `clothes` WHERE `category` = 'skirt' AND `bust` IS NOT NULL 
```
2일전 덤프한 로컬 디비 기준으로 영향을 받는 의류의 수는 508건입니다.

**Comment by yongbin** [comment]
> jacket에 가슴둘레가 0인값은 삭제

```sql
SELECT `code`, bust FROM `clothes` WHERE `category` = 'jacket' AND `bust` < 10
```

2일전 덤프한 로컬 디비 기준으로 영향을 받는 의류의 수는 51건입니다.

**Comment by yongbin** [comment]
> blous에서 가슴둘레가 0인값 삭제

```sql
SELECT `code`, bust FROM `clothes` WHERE `category` = 'blouse' AND `bust` = 1
```

2일전 덤프한 로컬 디비 기준으로 영향을 받는 의류의 수는 21건입니다.

**Comment by yongbin** [comment]
> 가슴둘레가 있는 옷 종류는 : blues, coat, shirt, jacket, onepice

```sql
SELECT `code`, bust FROM `clothes` WHERE `category` NOT IN ( 'coat', 'blouse', 'shirt','jacket','onepiece' ) AND `bust` IS NOT NULL 
```

2일전 덤프한 로컬 디비 기준으로 영향을 받는 의류의 수는 4264건입니다.(위 확인된 수와 중복됨)

**Comment by yongbin** [comment]
- [ ] shirt에서 가슴둘레가 < 15 삭제

```sql
SELECT `code`, bust FROM `clothes` WHERE `category` = 'shirt' AND `bust` < 15
```

2일전 덤프한 로컬 디비 기준으로 영향을 받는 의류의 수는 217건입니다.

**Comment by yongbin** [comment]
이 이슈를 어떤식으로 처리할지 내일 같이 논의한후에 결정되면 이후 동일한 이슈를 등록하고 처리하겠습니다.

**Comment by yongbin** [comment]
제가 진행과정을 꼼꼼하게 기록하고 업무시간 이후에 적용하기로 했습니다. @10001if 님께서 한번 더 확인해주시면 좋을것 같습니다.

**Comment by yongbin** [comment]
> 2일전 덤프한 로컬 디비 기준으로 영향을 받는 의류의 수는 1860건입니다.

```sql
UPDATE `clothes` SET `bust` = NULL WHERE `category` = 'pants' LIMIT 1874;
```
적용 완료

**Comment by yongbin** [comment]
> 2일전 덤프한 로컬 디비 기준으로 영향을 받는 의류의 수는 508건입니다.

```sql
UPDATE `clothes` SET `bust` = NULL WHERE `category` = 'skirt' LIMIT 517;
```
적용 완료

**Comment by yongbin** [comment]
> 2일전 덤프한 로컬 디비 기준으로 영향을 받는 의류의 수는 51건입니다.

```sql
UPDATE `clothes` SET `bust` = NULL WHERE `category` = 'jacket' AND `bust` < 10 LIMIT 51;
```

적용완료

**Comment by yongbin** [comment]
> 2일전 덤프한 로컬 디비 기준으로 영향을 받는 의류의 수는 21건입니다.

```sql
UPDATE `clothes` SET `bust` = NULL 
WHERE
  `category` = 'blouse' AND `bust` = 1
LIMIT 21;
```

적용완료

**Comment by aanoaa** [comment]
지금 영업시간인데 막 적용하시면 안됩니다.

**Comment by yongbin** [comment]
> SELECT `code`, bust FROM `clothes` WHERE `category` NOT IN ( 'coat', 'blouse', 'shirt','jacket','onepiece' ) AND `bust` IS NOT NULL

```sql
UPDATE `clothes` SET `bust` = NULL 
WHERE
  `category` NOT IN ( 'coat', 'blouse', 'shirt','jacket','onepiece' ) AND `bust` IS NOT NULL 
LIMIT 1899;
```

적용완료

**Comment by yongbin** [comment]
> shirt에서 가슴둘레가 < 15 삭제

```sql
UPDATE `clothes` SET `bust` = NULL 
WHERE
  `category` = 'shirt' AND `bust` < 15
LIMIT 217;
```
적용 완료
