### ISSUE TITLE
방문예약 페이지에 예약 가이드 버튼 추가

### ISSUE THREAD

**Issue by MoDoLEE** [opencloset/opencloset#701]
예약 가이드 블로그로 이동할 수 있는 버튼 추가
http://blog.theopencloset.net/220614995880

**Comment by MoDoLEE** [comment]
@aanoaa 제가 고친 코드가 어떤 화면으로 나오는지 보려면 어떻게 해야 될까요?
고친 부분은 https://github.com/opencloset/opencloset/commit/b4a931b491b1f85d5b6919b4e3c936b415f1c64e 입니다.

**Comment by aanoaa** [comment]
개발환경이 마련되어있지 않은 상태에서 `develop` 브랜치에 커밋하는 것은 위험할 수 있습니다.
테스트가 되지 않은채로 배포될 수 있거든요.

개발환경을 마련해서 보는 수 밖에 없습니다.
노트북 가지고 오시면 도와드리겠습니다.

리눅스와 맥북에서는 동작합니다.
윈도우즈는 해봐야 알 것 같습니다.

**Comment by aanoaa** [comment]
배포되었습니다.

**Comment by aanoaa** [comment]
새창에서 열려야하고, 배경이 녹색이어야 합니다.
