### ISSUE TITLE
방문예약페이지에 접근 할 수 없음

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#702]
이런 에러가 나타나면서 https://visit.theopencloset.net/ 에 접속할 수 없습니다.

```
[Fri Feb 12 10:41:59 2016] [error] Can't write to log:  at /home/opencloset/.perlbrew/libs/perl-5.18.2@service/lib/perl5/Mojolicious.pm line 105.
```

**Comment by aanoaa** [comment]
```
opencloset@opencloset1:~/service/visit.theopencloset.net/log$ df -h
Filesystem                                     Size  Used Avail Use% Mounted on
rootfs                                         9.8G  9.0G  301M  97% /
/dev/vg-vol0/lxc_opencloset1.silex.kr          9.8G  9.0G  301M  97% /
udev                                            10M     0   10M   0% /dev
/dev/vg-vol0/lxc_opencloset1.silex.kr_storage  197G  6.9G  180G   4% /storage
tmpfs                                          3.2G   52K  3.2G   1% /run
tmpfs                                          5.0M     0  5.0M   0% /run/lock
tmpfs                                           11G   76K   11G   1% /run/shm
```

**Comment by aanoaa** [comment]
nginx 의 access_log 가 `630MB` 입니다.

**Comment by aanoaa** [comment]
`hypnotoad` 를 재시작 해주었습니다.
동작합니다.

**Comment by aanoaa** [comment]
왜 장애가 발생했는지 탐구생활을 해봐야 합니다.
cc @yongbin @keedi

**Comment by yongbin** [comment]
오전에 한만일 대표님  전화를 받았던 시점에 (오전 9시 30분경) opencloset1 장비가 디스크가 풀이난적이 있습니다 당시 staff 는 프로세스가 죽었었고 나머지는 정상이었기때문에 따로 재기동하지 않았는데 나중에 monitor 가 정상동작하지 않는다는 연락을 받고 reload 했었습니다. 아마 그 이슈와 관련이 있을것 같습니다.

**Comment by aanoaa** [comment]
지난번에 로그 로테이션 안되서 디스크 풀난 적이 있엇는데,
이번은 뭔가요?

**Comment by yongbin** [comment]
> 지난번에 로그 로테이션 안되서 디스크 풀난 적이 있엇는데,
> 이번은 뭔가요?

이번에는 #695 ~ #700 번이 진행되면서 단계별로 SQL 백업을 받았던것이 원인이었습니다. 현재는 제 컴퓨터로 복사해서 공간을 확보했습니다.

**Comment by aanoaa** [comment]
Fri, 01 Apr 2016 12:07:38 +0900

또 다시 디스크 풀입니다.
근본적인 대책이 필요합니다.

**Comment by aanoaa** [comment]
급한대로 postcodify 백업 파일을 삭제해서 300MB 가량 용량을 비웠습니다.

**Comment by aanoaa** [comment]
`100MB` 넘는 파일들입니다.

    $ find . -type f -size +100M
    ./home/opencloset/service/p5-postcodify/db/postcodify.20141112.v2.sqlite.xz
    ./home/opencloset/service/story.theopencloset.net/.git/objects/pack/pack-83d9fa56e303d01651d067e2e1e5e825d0454e71.pack
    ./storage/mysql/ibdata1
    ./storage/mysql/postcodify/postcodify_addresses.ibd
    ./storage/mysql/postcodify/postcodify_keywords.ibd
    ./storage/mysql/postcodify/postcodify_numbers.ibd
    ./storage/mysql/ib_logfile0
    ./storage/mysql/ib_logfile2
    ./storage/mysql/ib_logfile1
    ./var/log/nginx/visit.theopencloset.net/access.log.1
    ./var/log/nginx/visit.theopencloset.net/access.log
    ./var/log/nginx/duflsdhtwkdahslxj.theopencloset.net/access.log
    ./var/log/nginx/staff.theopencloset.net/access.log.1
    ./var/log/nginx/staff.theopencloset.net/access.log
    ./tmp/story.theopencloset.net.tar.gz
    ./proc/kcore

**Comment by aanoaa** [comment]
`./home/opencloset/service/p5-postcodify/db/postcodify.20141112.v2.sqlite.xz`

파일은 안쓰니까 지워도 되겠습니다.

**Comment by aanoaa** [comment]
nginx 의 access_log 들이 많은 용량을 차지하네요.

**Comment by aanoaa** [comment]
현재 `800MB` 정도의 여유공간을 확보해두었습니다.
@yongbin 님은 재발하지 않도록 어케 좀..
모니터링 하라면 하겠습니다.

**Comment by keedi** [comment]
데이터베이스는 항상 주기적으로 백업하고 있는데 이미 열린옷장 데이터베이스 용량 자체가 너무 커졌기 때문에 그 빈도수가 빨라진 것 같네요. (서버 접속 없이하는 대충 추정입니다) 현재는 제 개인 장비로 데이터베이스 백업을 항상 하고 있는데 사무실 네트워크 문제가 생긴다거나 그러면 옮기고 지우는 작업이 인증 세션 만료 등으로 끊겨 안되서 용량이 제법 찰겁니다. 제가 자동으로 가져오고 지우게 하고는 있지만 근원적으로 해결하려면 백업서버가 있어야 합니다. 최소 현 서버 백업을 시간 단위로 하는 것(제가 크론으로 셋팅해두었습니다.)을 막을 것이 아니라 정해진 공식 백업 서버에 자동적으로 옮기고 지우는 절차가 필요할 겁니다.

**Comment by keedi** [comment]
일단 제가 조금있다 접속해서 세션 만료된 제 장비 기준으로 백업 파일들을 좀 옮겨 놓겠습니다. 그러면 용량이 조금 여유가 생길겁니다.

다만 여전히 해당 가상 장비의 하드 공간은 적기 때문에 디스크 용량 증가는 필수이며  백업 및 로그 파일 이전에 대한 정책은 현재 전무한 것도 문제입니다.

**Comment by yongbin** [comment]
디스크 용량 증설 및 백업로그 이전 작업 진행하겠습니다.

**Comment by yongbin** [comment]
@keedi 님과 상의한 결과 다음과 같은 방향으로 진행하기로 했습니다.
 - 현재 루트 파일 시스템에서 가장 큰 비중을 차지하는 `var` 디렉토리 하부를 LVM 디스크 이미지로 attach 하고 시스템에서 마운트 하는 형식으로 변경(30G 할당)
 - 백업을 위해 사용되는 ~opencloset/backup 디렉토리를 /storage 하부로 심볼릭 링크 연결

**Comment by yongbin** [comment]
backup 디렉토리 이전은 완료했습니다. 별도로 var 디렉토리 마운트의 경우 LVM 할당이후 마운트를 위해서 시스템 재기동이 필요하기 때문에 금일 야간에 진행하도록 하겠습니다.

**Comment by yongbin** [comment]
`var` 디렉토리 분리와 관련한 이슈는 버그질라에서 진행하도록 하겠습니다.

https://bz4.silex.kr/show_bug.cgi?id=895

**Comment by yongbin** [comment]
var 디렉토리 분리완료되었습니다.

https://bz4.silex.kr/show_bug.cgi?id=895

**Comment by keedi** [comment]
@yongbin 버그 url 풀로 적지마세요.

**Comment by keedi** [comment]
Bug XXX 형식으로 수정해주세요. 링크는 달지 말구요. 모바일이라 전 편집이 안되네요.
