### ISSUE TITLE
사용자 지정 날짜로 반납 지원

### ISSUE THREAD

**Issue by keedi** [opencloset/opencloset#706]
현재 반납은 초기 요구사항대로 반납 절차를 수행하는 그 시점을 기준으로 반납 날짜(return_date)를 지정합니다.

지난 3~6개월 전 반납 실패건이 틈틈히 발생해 디버깅을 위해 반납을 수행하지 않은 건이 있었습니다. 관련해서는 주문서의 반납 페이지와 첫 페이지의 상태 변경 기능을 동시에 이용할 경우 렌더링된 화면이 실시간으로 갱신되지 않아 발생했던 문제로 추정은 하고 있으나 최근 1~3개월 사이에는 조심을 해서인지 따로 발생한 것 같지는 않습니다.

어쨌든 현재 이런 연유로 제 날짜에 반납 처리를 못한 주문서들은 정상적으로 반납 절차를 수행하면 엄청난 연체 또는 연장을 한 것으로 보입니다. 이는 자료의 신빙성을 떨어뜨리므로 당시 실제로 반납된 날짜에 시스템적으로 반납이 되어야 합니다. 또는 꼭 이 경우가 아니라하더라도 내부 사정상 제 날짜에 반납 처리를 못한 경우 부득이하게 반납 날짜를 지정해야 하는 경우도 있을 것입니다.

이런 두 가지 경우를 지원하기 위해 사용자 지정 날짜로 반납을 지원하는 기능이 필요합니다. 다만 본 기능은 빈번하게 발생하지 않는 것이 적절하므로 UI적으로는 지원하지 않고 URL 주소에 인자를 기록해서 처리하는 방식으로 지원하려고 합니다.

**Comment by keedi** [comment]
기능 구현은 완료했습니다. 내일 목요일에 @10001if 님께 보여드리고 당시 시스템 오류로 반납하지 않았던 항목들의 실 반납일을 확인한 후 해당 기능을 이용해 반납 테스트한 후 문제가 없다면 실 서버에서 반납 처리할 예정입니다.

**Comment by keedi** [comment]
구현한 기능을 사용하지 않았을 때의 화면입니다.

![order-custom-return-date-01](https://cloud.githubusercontent.com/assets/138451/13109468/c757b0a2-d5bc-11e5-9d56-1291e5abc0c1.png)

구현한 기능을 사용했을 때의 화면입니다. 주소 인자에 `today` 항목이 있음을 알 수 있습니다.

![order-custom-return-date-02](https://cloud.githubusercontent.com/assets/138451/13109472/cbeeb8ea-d5bc-11e5-8e8e-feff0951c0f9.png)

**Comment by aanoaa** [comment]
@10001if 어떠한 기능인지 이해하셨나요?
이걸로 문제를 해결 할 수 있나요?

**Comment by aanoaa** [comment]
#646 의 근본적인 해결을 원하지만 이 기능을 활용하면 사용못하고 있던 의류들을 `대여가능` 으로 변경해서 사용 할 수 있다고 합니다.
