### ISSUE TITLE
새옷 등록 시 의류 사이즈에 "0"이 입력될 수 있도록 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#708]
새 옷 등록시 의류 사이즈 입력시 "0"이 입력되지 않아 불편한 부분이 많다고 합니다. @yongbin 검색이슈에 문제가 없다면 0으로도 입력할 수 있도록 수정 부탁드립니다.

**Comment by yongbin** [comment]
@10001if  새옷을 등록할때 0을 입력해야할 경우가 어떤경우가 있을까요?

**Comment by 10001if** [comment]
0은 입력하지 않고 입력 가능한 사이즈는 최대한 입력하고, 검색이 필요하지 않은 의류의 경우에는 필요없는 사이즈를 제거하도록 요청드리겠습니다. 이슈의 의미가 없으므로 닫도록 하겠습니다.
