### ISSUE TITLE
기증자 성별에서 "단체" 항목 추가 요청

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#71]
기증자/대여자 성별시 남, 여가 아닌 "단체"라는 항목을 추가했으면 좋겠습니다.

**Comment by 10001if** [comment]
최근에 단체에서 기증해주신 의류들이 있어 단체 항목이 필요한 것 같다는 생각을 하였는데, 전에 올려놓은게 있는 것 같아 찾아서 다시 들어와봅니다. 메세지 사이트에서는 기증자, 대여자, 기업(단체)로 구분되어 있는 것 같은데. 의류 등록시 단체로 등록하지 않아도 사이트에서 보여주는 것은 큰 문제가 없는지 궁금합니다.

**Comment by 10001if** [comment]
단체 대여 자체는 상관없는데. 그럼 회원가입시에도 단체명으로 가입하는 것인지요?
> 네. 단체명으로 가입합니다. 
해당 회원(단체)의 경우 신체 치수는 어떻게 기입하는지요?
> 신체치수는 기입하지 않습니다.
주문서(대여행위)에 빌려간 옷의 수치는 해당 단체 대여와 매치시킬 수 없으니(각기 치수가 다른 여러벌의 옷과 각기 치수가 다른 단체에 속한 여러 사람) 단체가 빌려간 옷에 대해서는 추후 고려하시는 검색이라던가 통계를 낼때 참고할 수 없는 값이 됩니다. 괜찮으신지요?
> 네. 괜찮습니다.
단체 대여자로 가입한 경우 이메일이나 전화번호가 등록된 다음 해당 단체 대여자의 대표가 개인 자격으로 왔을때 어떻게 처리할 것인지요? 새로 가입을 받을 것인지요? 아니면 단체로 대여하는지요? 새로 가입 받는다면 휴대폰과 이메일의 중복되는데 어떻게 하실 것인지요?
> 개인자격으로 대여를 진행한다면 새로 가입을 받도록 하겠습니다. 

단체로 대여를 하고 기증을 하는 이슈들이 점점 늘어나고 있습니다. 때문에 단체 개념이 추가될 필요성이 종전에 비해 상대적으로 높아졌습니다.

**Comment by aanoaa** [comment]
대리로 대여하는 경우를 고려해야 합니다.

**Comment by keedi** [comment]
흠 이 이슈는 대여가 아닌 기증 관련입니다. #545와 중복이 아닙니다. 내용이 섞이는 것보다 정리하려면 따로 열고 구분하는게 나을 것 같네요.

**Comment by 10001if** [comment]
당장 필요성이 커 보이지 않습니다. 우선 닫고 필요해지면 다시 열도록 하겠습니다.
