### ISSUE TITLE
비고와 대여메세지를 더 쉽게 구분할 수 있도록 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#710]
![2016-02-19 4 49 08](https://cloud.githubusercontent.com/assets/4696328/13169463/0a0be734-d729-11e5-8fb1-6a5a35afd345.png)

비고와 대여메세지 입력란이 위 아래에 나뉘어져 있는데
비고란에 대여메세지를 작성하고 대여메세지란에 비고내용을 작성하는 일이 발생하고 있습니다.
기존에는 확인하기가 힘들었지만 지금은 stroy 사이트로 인해 작성이 잘못된 것을 확인할 수 있게 되었습니다.

대여메세지 작성란과 비고 작성란의 분명한 구분 표시가 요구됩니다. 화요일에 찾아뵙고 말씀드리도록 하겠습니다.

**Comment by yongbin** [comment]
이건 간단한거니까 제가 해보겠습니다.

**Comment by yongbin** [comment]
아직 push 안했습니다. 간단한 변경이니 @10001if 님께 확인후에 commit, push 하겠습니다.

**Comment by 10001if** [comment]
@yongbin 네! 이렇게 진행해주시면 될 것 같습니다. ^^

**Comment by 10001if** [comment]
@yongbin 대표님  총액:15,000원 밑에 있는 긴 줄 있잖아요. 그 아래 주문서 메모를 그 위에 올려서 주문서 메모랑 대여메세지를 완전히 구분 할 수 있으면 더 좋겠습니다.

**Comment by yongbin** [comment]
> @yongbin 대표님 총액:15,000원 밑에 있는 긴 줄 있잖아요. 그 아래 주문서 메모를 그 위에 올려서 주문서 메모랑 대여메세지를 완전히 구분 할 수 있으면 더 좋겠습니다.

![Uploading Screen Shot 2016-03-02 at 12.51.56 PM.png…]()

반영했습니다.

**Comment by yongbin** [comment]
한만일대표님 확인 완료했습니다. 이슈 닫겠습니다.

**Comment by aanoaa** [comment]
#725 는 짬입니까?
짬되고 이슈 끗?

**Comment by yongbin** [comment]
> #725 는 짬입니까?
> 짬되고 이슈 끗?

아 아니요 #725 머지했습니다.

**Comment by 10001if** [comment]
확인 완료하였습니다.
