### ISSUE TITLE
새옷 등록시 필요없는 항목의 제거

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#713]
새옷등록 삭제 요청 부위   

* 셔츠 (윗배/배꼽) 
* 코트(기장) 
* 조끼 (허리/배꼽)

이상의 사이즈는 새옷 등록시 해당 품목을 클릭 했을 때 의류 정보 입력란이 나타나지 않도록 제거를 요청드립니다.

**Comment by yongbin** [comment]
요것도 간단하니까 제가 해보겠습니다.

**Comment by yongbin** [comment]
#708과 관련이 있습니다.

**Comment by yongbin** [comment]
이 이슈에서 삭제되는 항목은 기존 DB에서 이미 이력된 내용도 확인후에 삭제합니다.

**Comment by yongbin** [comment]
## 셔츠 
 - `topbelly` 입력된 옷 20건
 - `belly` 입력된 옷 4건 (전부 1)

## 코트 
  - `length` 33건

## 조끼
  - `waist` 1건 
  - `belly`  0건

직접 확인해본 결과 전무 의미없는 입력값들입니다. 삭제하도록 하겠습니다.

**Comment by yongbin** [comment]
서버에서 다음 쿼리를 통해서 삭제되었습니다.

```sql
DELETE FROM `clothes`  WHERE `category` = 'shirt' AND `topbelly` IS NOT NULL  LIMIT 20;
DELETE FROM `clothes`  WHERE `category` = 'coat'  AND `length`   IS NOT NULL  LIMIT 33;
```

**Comment by yongbin** [comment]
@keedi 님이 손쉽게 수정할수 있도록 만들어놔서 정말 간단하게 수정했습니다. @keedi++

## 셔츠 

![screen shot 2016-03-02 at 1 27 02 pm](https://cloud.githubusercontent.com/assets/52704/13450606/a21978de-e07a-11e5-9151-bb2e851d4ee4.png)


## 코트

![screen shot 2016-03-02 at 1 27 13 pm](https://cloud.githubusercontent.com/assets/52704/13450607/a680a258-e07a-11e5-9ce7-968f75c94a51.png)


## 조끼

![screen shot 2016-03-02 at 1 27 22 pm](https://cloud.githubusercontent.com/assets/52704/13450612/aafb1be2-e07a-11e5-9806-9dff764d1bef.png)

참고로 현재의 의류종류별 수집 항목입니다.

```coffee
        when 'jacket'    then types = [ 'bust', 'arm', 'topbelly', 'belly'         ]
        when 'pants'     then types = [ 'waist', 'hip', 'thigh', 'length'          ]
        when 'shirt'     then types = [ 'neck', 'bust', 'arm'                      ]
        when 'waistcoat' then types = [ 'topbelly'                                 ]
        when 'coat'      then types = [ 'bust', 'arm'                              ]
        when 'onepiece'  then types = [ 'bust', 'waist', 'hip', 'arm', 'length'    ]
        when 'skirt'     then types = [ 'waist', 'hip', 'length'                   ]
        when 'blouse'    then types = [ 'bust', 'arm'                              ]
        when 'belt'      then types = [ 'length'                                   ]
        when 'shoes'     then types = [ 'foot'                                     ]
```

**Comment by yongbin** [comment]
@10001if 확인부탁드립니다.

**Comment by yongbin** [comment]
https://github.com/opencloset/opencloset/pull/726

**Comment by 10001if** [comment]
네! 확인 완료하였습니다. 감사합니다~!
