### ISSUE TITLE
의류정보내에 대여일과 보유일 그리고 의류회전율을 표시하도록 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#714]
![2016-02-23 3 31 23](https://cloud.githubusercontent.com/assets/4696328/13243532/e735fd40-da42-11e5-8818-1ea5418de7de.png)

@yongbin 과 논의 뒤 올려놓았습니다. 통계에 회전율 정보가 붙는 것과 별도로 개별 의류정보에도 의류회전율 추가를 요청드렸습니다.

**Comment by yongbin** [comment]
#540

**Comment by yongbin** [comment]
![screen_shot_2016-02-25_at_4_11_46_pm](https://cloud.githubusercontent.com/assets/52704/13312573/1f3bb9d4-dbdb-11e5-8af5-f2db3e1f3fe2.png)

**Comment by yongbin** [comment]
@10001if 확인해주세요

**Comment by yongbin** [comment]
확인끝났습니다. 이대로 배포하면 됩니다.

**Comment by yongbin** [comment]
https://github.com/opencloset/OpenCloset-Schema/releases/tag/release-0.022 릴리즈 되었습니다.
