### ISSUE TITLE
주문서에서 명시적으로 온/오프라인을 구분함

### ISSUE THREAD

**Issue by yongbin** [opencloset/opencloset#715]
#552 등에서 논의된것 처럼 현재 `order` 테이블에 온오프라인 여부를 별도로 저장하는 작업을 아래 이슈에서 진행할 예정입니다.

https://github.com/opencloset/OpenCloset-Schema/issues/27

위 작업이 완료될 경우 현재 `staff`, `monitor`등에서 광범위하게 예외처리로 처리하고 있는 (7시 혹은 10시 슬랏의 주문서) 온라인주문서 추정부분 코드를 수정해야합니다.
- https://github.com/opencloset/monitor/issues/70

**Comment by yongbin** [comment]
#524 이슈도 본 이슈와 관련이 있습니다.

**Comment by keedi** [comment]
이거 새로운 서비스와 연관도 있고 이제 슬슬 진행해야 할 것 같습니다. 마일스톤 변경할게요.

**Comment by yongbin** [comment]
현재 staff 에서 예약시간을 이용해서 온오프라인 구분동작하는 부분을 확인중입니다.  opencloset/OpenCloset-Schema#27 이 변경되면 아래 부분의 코드들은 모두 수정되어야 합니다.

## lib/OpenCloset/Web/Plugin/Helpers.pm

`user_avg2` 헬퍼 함수에서 온라인 대여 주문을 제외하고 계산하기 위한 목적으로 사용

## lib/OpenCloset/Web/Controller/Statistic.pm

'통계/상태'를 처리하는 'status_ymd' 함수에서 핼퍼 함수 'mean_status'의 호출 인자로 온라인 주문시점을 전달함

## lib/OpenCloset/Web/Plugin/Helpers.pm

'mean_status' 에서 전달받은 온라인 시간을 제외한 나머지 주문의 평균 시간을 계산함

## lib/OpenCloset/Web/Controller/Income.pm

'ymd' 함수에서 수입의 정산에서 온/오프라인 매출을 구분하기 위한 용도로 사용함

## lib/OpenCloset/Web/Controller/API.pm

'api_create_sms' 함수에서 주문에 대한 발송 문자를 생성할때 온/오프 라인주문의 발송번호를 구분하기 위해서 호출함

**Comment by yongbin** [comment]
`monitor` 에서는 다음과 같은 예외처리들이 있습니다.


## lib/OpenCloset/Monitor/Controller/Dashboard.pm

- `online` 함수. 열린옷장 Online dashboard 에서 온라인 주문을 구분하는 목적으로 22시 이후 주문을 온라인으로 처리함
- `index` 함수. 오프라인 대기 화면에서 온라인 주문자를 표현하지 않기 위해 예약시간을 확인함

## lib/OpenCloset/Monitor/Controller/Region.pm

- `selects` 함수. prepare 대시보드에서 주문의 목록을 표시할때 온라인 주문을 제외하기 위해 처리함
- `status_boxing` 함수. `포장중` 목록을 만들때 온라인주문을 제외하기 위해 처리함

## lib/OpenCloset/Monitor.pm

성별/상태별 대기인원의 수를 돌려주는 `_waiting_list` 함수에서 온라인 주문서를 제거하기 위해 사용됨

**Comment by yongbin** [comment]
`OpenCloset-Size-Guess-DB` 에서 다음과 같은 예외처리가 있습니다.

## lib/OpenCloset/Size/Guess/DB.pm
`guess` 함수에서 예측치를 만들때 온라인 주문서를 제거하고 계산하기 위해서 사용함

**Comment by yongbin** [comment]
그밖에 검색에 사용되는 예측 모델을 만드는 기초 SQL 쿼리에서도 온라인 대여를 제거하기위해 사용하고 있습니다.

**Comment by yongbin** [comment]
지금 고려하고 있는 방향입니다.

1. OpenCloset::Schema::ResultSet::Order 에 온라인 주문과 오프라인 주문을 구분해서 돌려주며 동일하게 search 인자를 받는 [Predefined_searches](http://search.cpan.org/~ribasushi/DBIx-Class-0.082840/lib/DBIx/Class/Manual/Cookbook.pod#Predefined_searches) 를 구현 (테스트 코드 포함)
2. 기존 코드에서 온라인 주문을 조회하는 모든코드를 1에서 구현한 predefined_search 로 변경
3. 기존 코드에서 resultset('order')를 사용하는 모든 부분을 리뷰해서 온오프라인 여부를 판별해서 적절하게 변경
4. 여기까지 해서 문제가 없다면 `Order` 테이블에 `is_online`  컬럼 추가
5. 기존 조건으로 is_online 컬럼자료 migrate
6. predefined_search 에 online/offline 구현부 변경

혹시 제가 고려하고 있지 못한 부분이 있으면 의겨주세요

**Comment by yongbin** [comment]
OpenCloset::Schema::ResultSet::Order 에 `offline` 메소드와 OpenCloset::Schema::Result::Order에 `is_online` 메소드를 추가했습니다. 변경된 인터페이스를 바탕으로 위에 나열된 staff, monitor 쪽 코드를 수정하고 동작을 확인하는 중입니다.

**Comment by yongbin** [comment]
> 지금 고려하고 있는 방향입니다.
> 
>     OpenCloset::Schema::ResultSet::Order 에 온라인 주문과 오프라인 주문을 구분해서 돌려주며 동일하게 search 인자를 받는 Predefined_searches 를 구현 (테스트 코드 포함)
>     기존 코드에서 온라인 주문을 조회하는 모든코드를 1에서 구현한 predefined_search 로 변경
>     기존 코드에서 resultset('order')를 사용하는 모든 부분을 리뷰해서 온오프라인 여부를 판별해서 적절하게 변경
>     여기까지 해서 문제가 없다면 Order 테이블에 is_online 컬럼 추가
>     기존 조건으로 is_online 컬럼자료 migrate
>     predefined_search 에 online/offline 구현부 변경
> 
> 혹시 제가 고려하고 있지 못한 부분이 있으면 의견주세요

진행하지 않기로 했습니다. 그냥 단순하게 `is_online` 컬럼을 참고하는 쿼리를 각각 상황에 맞게 수정하면 됩니다.

**Comment by yongbin** [comment]
## bin/opencloset-stat-status-cache.pl 

상태 통계를 위해 크론으로 처처리하는 스크립트입니다. 이 파일에서도 온/오프라인 구분이 들어갑니다.

**Comment by yongbin** [comment]
이 이슈는 제가 진행할 가능성이 낮습니다. 이슈를 닫거나 담당자를 재지정해야합니다.

**Comment by 10001if** [comment]
@yongbin 담당자를 재지정해주시면 감사하겠습니다 ^^

**Comment by 10001if** [comment]
담당자를 지정해 주셨었네요~ 제가 확인을 못했습니다. ^^;

**Comment by aanoaa** [comment]
여지껏 온라인 주문서가 900개가 안됩니다.
해당하는 주문서의 `online` 컬럼을 `1` 로 일괄 변경해줘야 합니다.

**Comment by aanoaa** [comment]
helper `mean_status` 에서 사용되는 `$online_order_hour` 는 2015-05-29 이전/이후에 따라 온라인 주문서의 예약시간이 바뀝니다.

`order.online` 컬럼을 업데이트할때에 고려해야 되는 것인가요?

**Comment by aanoaa** [comment]
온라인주문서를 staff 이 만들 수 있는 방법이 없습니다.
직원예약을 통해 온라인 주문서를 대신 만들고 있는 상황입니다.

주문서 상세화면 에서 online 여부를 수정할 수 있도록 하면 되지 않을까 합니다.

**Comment by aanoaa** [comment]
![screenshot-localhost 5001 2016-10-18 17-55-21](https://cloud.githubusercontent.com/assets/170528/19470986/7ae18eb8-955c-11e6-8bae-eaa843c863a2.png)
![screenshot-localhost 5001 2016-10-18 17-56-20](https://cloud.githubusercontent.com/assets/170528/19470985/7ad78b52-955c-11e6-8007-fe67265fddf9.png)

**Comment by yongbin** [comment]
네 2015-05-29 이전에는 오후 7시, 2015-05-29 이후에는 오후 10시 주문서를 온라인 주문서로 변경해야 합니다. 그리고 최소 제가 위에 나열한 코드들을 적절하게 변경된 코드에 따라 구현을 수정해야합니다.

**Comment by aanoaa** [comment]
2015-05-29 이전의 19:00 주문서 및 이후의 22:00 주문서의 `online` 컬럼을 `1` 로 변경하는
쿼리를 만들어서 실행시켜야 합니다.

**Comment by aanoaa** [comment]
opencloset 및 monitor 의 22:00 를 참고하는 코드들은 수정되었습니다.

**Comment by yongbin** [comment]
넵 말씀하신 쿼리 지금 작성해서 여기에 업데이트 하겠습니다.

**Comment by yongbin** [comment]
```SQL
-- 2015-05-29 이전 오후 7시 예약 주문서를 online = 1 (약 328건)

UPDATE `order` SET `online` = 1 WHERE `id` IN ( 
  SELECT  a.id FROM `order` AS a INNER JOIN `booking` AS b ON a.booking_id = b.id WHERE DATE(b.`date`) < '2015-05-29' AND TIME(b.`date`) = '19:00:00'
)


-- 2015-05-29 이후  오후 10시 예약 주문서를 online = 1 (약 1188건)

UPDATE `order` SET `online` = 1 WHERE `id` IN ( 
  SELECT  a.id FROM `order` AS a INNER JOIN `booking` AS b ON a.booking_id = b.id WHERE DATE(b.`date`) >= '2015-05-29' AND TIME(b.`date`) = '22:00:00'
)
```

**Comment by aanoaa** [comment]
적용만 시키면 되는데 monitor 와 같이 배포해야 해서 미루고 있습니다.

**Comment by aanoaa** [comment]
위 쿼리를 적용하던 중에 오류가 발생했습니다.

```
mysql> UPDATE `order` SET `online` = 1 WHERE `id` IN ( 
    ->   SELECT  a.id FROM `order` AS a INNER JOIN `booking` AS b ON a.booking_id = b.id WHERE DATE(b.`date`) < '2015-05-29' AND TIME(b.`date`) = '19:00:00'
    -> );
ERROR 1093 (HY000): You can't specify target table 'order' for update in FROM clause
```

**Comment by aanoaa** [comment]
SQL 의 `IN` 절에서 에서 처리할 수 있는 한계가 있는 걸로 알고 있습니다.
100개 라던지.. 자세한 내용은 이슈 처리후에 찾아보도록 하겠습니다.

**Comment by aanoaa** [comment]
```perl
#!/usr/bin/env perl
use strict;
use warnings;

use OpenCloset::Schema;

my $config = {
    database => {
        dsn  => $ENV{OPENCLOSET_DATABASE_DSN},
        name => $ENV{OPENCLOSET_DATABASE_NAME},
        user => $ENV{OPENCLOSET_DATABASE_USER},
        pass => $ENV{OPENCLOSET_DATABASE_PASS},
        opts => {
            quote_char        => q{`},
            mysql_enable_utf8 => 1,
            on_connect_do     => 'SET NAMES utf8',
            RaiseError        => 1,
            AutoCommit        => 1,
        },
    },
};

my $db     = $config->{database};
my $schema = OpenCloset::Schema->connect(
    {
        dsn      => $db->{dsn},
        user     => $db->{user},
        password => $db->{pass},
        %{ $db->{opts} },
    }
);

my $rs    = $schema->resultset('Order');
my $guard = $schema->txn_scope_guard;
while ( my $id = <DATA> ) {
    chomp $id;
    next unless $id;
    my $order = $rs->find( { id => $id } );
    next unless $order;
    $order->update( { online => 1 } );
}
$guard->commit;

__DATA__
7216
7214
...
```

SELECT 쿼리의 결과를 `__DATA__` 섹션에 넣고 위 스크립트를 돌려서 처리하였습니다.

**Comment by aanoaa** [comment]
44012 주문서가 모니터의 의류준비탭에 보여집니다.
@10001if 님 주문서입니다.

**Comment by aanoaa** [comment]
지난번에 문제가 되었던 그 주문서 입니다.
상태를 변경하도록 하겠습니다.

**Comment by aanoaa** [comment]
`방문안함` 으로 변경하였습니다.

```sql
UPDATE `order` SET status_id = 12 WHERE id = 44012;
```

**Comment by aanoaa** [comment]
@10001if 온라인 주문서를 위해서 직원예약을 사용하실때에,
예약시간 22:00 대신에 online 컬럼을 사용해주셔야 합니다.
예약시간은 어느것으로 하던지 상관은 없습니다.

**Comment by aanoaa** [comment]
@10001if 모니터의 의류준비, 대기실등 대기열목록이 이상하면 말씀해주세요

**Comment by 10001if** [comment]
확인 하였습니다. 아침회의시간에 공유하였습니다. 체크해서 문제가 발생하지 않도록 잘 이용하겠습니다. 감사합니다. ^^

**Comment by yongbin** [comment]
위 쿼리는 제 환경에서도 실패합니다.  아래 쿼리는 동작합니다.

```sql
UPDATE `order` AS a
    INNER JOIN `booking` AS b ON a.`booking_id` = b.`id`
SET `online` = 1
WHERE DATE(b.`date`) < '2015-05-29'
    AND TIME(b.`date`) = '19:00:00'
```


```sql
UPDATE `order` AS a
    INNER JOIN `booking` AS b ON a.`booking_id` = b.`id`
SET `online` = 1
WHERE DATE(b.`date`) >= '2015-05-29'
    AND TIME(b.`date`) = '22:00:00'
```

**Comment by keedi** [comment]
> SELECT 쿼리의 결과를 __DATA__ 섹션에 넣고 위 스크립트를 돌려서 처리하였습니다.

`OpenCloset::Config` 최신 버전을 사용할 경우 반복되는 코드를 조금 더 줄여 쓸 수 있습니다.

```perl
use OpenCloset::Schema;

my $config = {
    database => {
        dsn  => $ENV{OPENCLOSET_DATABASE_DSN},
        name => $ENV{OPENCLOSET_DATABASE_NAME},
        user => $ENV{OPENCLOSET_DATABASE_USER},
        pass => $ENV{OPENCLOSET_DATABASE_PASS},
        opts => {
            quote_char        => q{`},
            mysql_enable_utf8 => 1,
            on_connect_do     => 'SET NAMES utf8',
            RaiseError        => 1,
            AutoCommit        => 1,
        },
    },
};

my $db     = $config->{database};
my $schema = OpenCloset::Schema->connect(
    {
        dsn      => $db->{dsn},
        user     => $db->{user},
        password => $db->{pass},
        %{ $db->{opts} },
    }
);
```

상기 코드는 다음과 같이 줄여 쓸 수 있습니다.


```perl
use OpenCloset::Config;
use OpenCloset::Schema;

my $config_file = shift || "$Bin/../app.conf";

my $occ = OpenCloset::Config->new( file => $config_file );
my $dbic_conf = $occ->dbic;
die "$config_file: database is needed\n" unless $dbic_conf;

my $schema = OpenCloset::Schema->connect($dbic_conf);
```
