### ISSUE TITLE
방문 대여시 개인정보 동의와 이용약관 규정의 내용 변경

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#719]
방문 대여시 1)개인정보이용 동의 내용과 2)이용약관 규정이 변경되었습니다.

본 내용읠 수정을 요청드립니다. 내용은 아래와 같습니다.

**Comment by 10001if** [comment]
열린옷장 서비스 개인정보수집‧이용‧제공 동의서

열린옷장은 개인정보보호법, 정보통신망법 등 관련 법령에 따라 열린옷장 웹사이트를 통하여 옷을 대여하고자 하는 분께 수집하는 개인정보의 항목, 개인정보의 수집 및 이용목적, 개인정보의 보유 및 이용기간 등을 안내 드리오니 자세히 읽은 후 동의하여 주시기 바랍니다. 

1. 수집하는 개인정보의 항목
(1) 열린옷장은 상담, 서비스 신청 등을 위해 아래와 같은 개인정보를 수집하고 있습니다.
- 필수항목 : 아이디, 비밀번호, 성명, 생년월일, 성별, 전화번호, 이메일, 주소, 의류의 착용날짜, 대여목적, 대여를 희망하는 품목, 희망색상
- 선택항목 : 감사편지

(2) 서비스 이용과정이나 사업 처리 과정에서 아래와 같은 정보들이 생성되어 수집될 수 있습니다.
- 서비스 이용기록, 접속 로그, 쿠키, 접속 IP 정보, 결제기록, 이용정지 기록

2. 개인정보 수집방법
열린옷장은 다음과 같은 방법으로 개인정보를 수집합니다.
- 홈페이지, 서면양식
- 생성정보 수집 툴을 통한 수집

3. 개인정보의 수집 및 이용 목적
'열린옷장 홈페이지'는 개인정보를 다음의 목적을 위해 처리합니다. 처리한 개인정보는 다음의 목적 이외의 용도로는 사용되지 않으며 이용 목적이 변경될 시에는 사전동의를 구할 예정입니다.

가. 서비스 제공에 관한 계약 이행 및 서비스 제공에 따른 요금 정산
(1) 정장기증 업무
기증자의 정보 및 신원 확인, 연락 및 안내, 소식지 전달 등
(2) 정장대여 업무
대여자의 예약 및 안내, 신체치수 측정, 기증 정장의 손·망실 방지 등

나. 회원관리
본인확인, 개인식별, 불량회원의 부정 이용 방지와 비인가 사용 방지, 가입 의사 확인, 가입 및 가입횟수 제한, 만14세 미만 아동 개인정보 수집 시 법정 대리인 동의여부 확인, 추후 법정 대리인 본인확인, 분쟁 조정을 위한 기록보존, 불만처리 등 민원처리, 고지사항 전달

다. 마케팅 및 광고에 활용
․신규 서비스(제품) 개발 및 특화, 인구통계학적 특성에 따른 서비스 제공 및 광고 게재, 접속 빈도 파악, 회원의 서비스 이용에 대한 통계, 이벤트 등 광고성 정보 전달

라. 기증편지 및 감사편지 공개

4. 개인정보의 제3자 제공
열린옷장은 이용자의 개인정보를 원칙적으로 외부에 제공하지 않습니다.
다만, 아래의 경우에는 예외로 합니다.
- 이용자들이 사전에 동의한 경우
- 법령의 규정에 의거하거나, 수사 목적으로 법령에 정해진 절차와 방법에 따라 수사기관의 요구가 있는 경우

5. 개인정보의 취급위탁
열린옷장은 서비스 이행을 위하여 아래와 같이 개인정보 취급 업무를 외부 전문업체에 위탁하여 운영하고 있습니다.

수탁자 : KG이니시스
위탁업무 내용 : 결제처리업무(카드결제 및 현금영수증 등)

수탁자 : 사일렉스
위탁업무 : 개인정보 데이터베이스화, 관리 및 보관

**Comment by 10001if** [comment]
열린옷장 서비스 이용약관

열린옷장은 기증자와 대여자가 함께 공유의 가치를 실천하는 '모두를 위한 옷장'으로서 원활하고 올바른 운영을 위해 아래와 같이 이용약관을 규정합니다.

제1조 목적
본 약관은 의류의 대여와 관련하여 열린옷장이 제공하는 모든 서비스를 이용함에 있어 대여자와 열린옷장의 권리, 의무 책임사항과 기타 필요한 사항을 규정함을 목적으로 합니다.

제2조 용어의 정의
① “대여”란 열린옷장이 대여자에게 약관에서 규정한 금액을 받고 약정된 기간 동안 열린옷장의 의류를 대여자에게 임대하는 것을 말합니다. 대여에는 방문대여와 온라인대여가 있습니다.
② “방문대여”는 대여자가 방문을 예약한 후 직접 열린옷장에 방문하여 의류를 대여하는 것을 말합니다.
③ “온라인대여”는 대여자가 온라인으로 대여신청서를 작성하고 열린옷장에게 송부하여 열린옷장이 대금 수령을 확인 후 의류를 발송하는 방식으로 의류를 대여하는 것을 말합니다.
④ “서비스”는 의류 대여 등 열린옷장이 사이트를 통하여 제공하는 모든 서비스를 의미합니다.
⑤ “의류”는 정장, 바지, 벨트, 구두 등 열린옷장에서 대여하는 모든 제품을 의미합니다.
⑥ “대여자”는 의류의 대여를 위하여 열린옷장 홈페이지를 이용하는 자를 의미합니다.
⑦ “대여기간”은 이 약관에 규정된 대여 의류의 사용기간을 말합니다. 
⑧ “사이트”란 열린옷장이 의류를 대여자에게 제공하기 위하여 컴퓨터 등 정보통신설비를 이용하여 재화 등을 거래할 수 있도록 설정한 가상의 영업장입니다. 현재 회사에서 운영하는 웹사이트는  다음과 같으며, 향후 변경될 수 있습니다.
- https://www.theopencloset.net/

제3조 개인정보의 취급 
① 열린옷장은 대여자의 서비스 이용에 필요한 최소한의 개인정보를 대여자의 동의를 얻어 수집할 수 있습니다. 해당 개인정보에 대해서는 개인정보 취급 관련 법령이 적용됩니다. 
② 수집된 개인정보는 관련 법령 및 열린옷장의 개인정보 취급방침에 따라 보호, 관리됩니다. 

제4조 대여 방법
① 대여 방법에는 방문대여와 온라인대여가 있습니다. 
② 방문대여 시 다음의 각 항목에 따릅니다.
 1. 대여자는 대여기간을 준수하여 의류를 대여하고자 하는 날로부터 1-2일 전에 사이트를 통하여 방문시간을 예약한 후 열린옷장에 방문합니다. 
 2. 방문 시 대여자와 의류를 실제로 착용할 자(이하 “실착용자”)가 일치하여야 함이 원칙이나, 대여자가 실착용자의 신체치수와 개인정보를 지참한 경우에는 실착용자와 일치하지 않더라도 대여할 수 있습니다.
 3. 방문한 자가 사이트에서 예약 신청을 하지 않고 방문한 경우, 현장에서 예약 신청을 한 후에 의류를 대여할 수 있습니다.
 4. 예약을 하지 않고 방문할 경우, 예약자의 대여가 우선합니다.
 5. 방문 시 예약시간 정시에 맞춰서 방문합니다. 사전 연락 없이 예약시간을 어기는 경우, 예약이 임의 취소 될 수 있습니다.
③ 온라인대여 시 다음의 각 항목에 따릅니다.
 1, 대여자는 대여신청서를 작성하여 열린옷장에 송부하며, 열린옷장이 이를 접수한 후 대여가 가능하다는 판단 하에 대여자에게 대여안내 전화를 하는 경우에 대여계약이 성립합니다. 대여자가 대여비 및 택배비를 입금하면 열린옷장은 입금확인 후 의류를 발송합니다.
 2. 열린옷장은 의류 발송 시 대여자에게 발송한 택배운송장번호를 문자로 전송합니다. 
 3. 대여자는 대여하고자 하는 날부터 최소 5일 전에 대여신청을 하여야 합니다.
④ 열린옷장이 요구하는 정보를 정확히 입력하지 않을 시에 예약이 임의 취소될 수 있습니다.
⑤ 미성년자는 원칙적으로 법정대리인의 동의가 있는 경우 대여가 가능합니다.

제5조 대여기간
대여기간은 3박 4일이며, 해당 기간은 어떠한 경우에도 대여의 기준이 됩니다.

제6조 대여 연장 
① 대여 결제 완료 시 택배 발송 및 대여 연장에 관한 문자가 각각 발송됩니다. 연장을 원하는 경우 문자를 통하여 연장 신청을 하는 경우 자동적으로 연장되며, 연장신청은 전화로도 가능합니다. 대여 연장 신청은 대여기간 내에 하여야 합니다.
② 대여가 연장된 경우 연장비용이 청구되며, 1일당 의류 대여비의 20%에 해당하는 금액이 청구됩니다. 예를 들어 의류 대여비가 20,000원일 경우, 1일 대여 연장비는 4,000원입니다.

제7조 대여 연장 및 연체
① 대여 연체 시 자동적으로 연체 알림 문자가 발송됩니다. 연체 시 연체 비용이 청구되며, 1일당 의류 대여비의 30%에 해당하는 금액이 청구됩니다.
② 대여자가 의도적으로 연체하는 경우 열린옷장은 별도의 절차를 밟을 수 있습니다.
③ 택배로 반납 시 반납예정일 1일 전 발송하여야 하며, 택배로 1일 전에 발송하였음에도 택배사의 과실로 반납이 지연되는 경우 대여 시 발송된 택배 발송에 관한 문자에 택배사와 운송장번호를 입력하여 열린옷장에 보내는 경우 연체로 보지 않습니다.

제8조 손상 및 분실
① 대여자는 대여한 의류의 손상 및 분실 시 열린옷장 담당자에게 즉시 알려야 합니다.
② 열린옷장은 대여된 의류의 손상 및 분실에 대하여 책임이 없습니다. 
③ 대여한 의류가 손상된 경우 대여자에게 손상비가 산정되어 청구되고, 손상으로 인하여 사용이 불가능한 경우 대여 금액의 5배에 해당하는 금액이, 분실의 경우에는 금액의 10배에 해당하는 금액이 청구됩니다.
④ 의류 대여 이전에 손상이 발견된 경우, 열린옷장은 그 손상비를 청구할 수 없습니다.

제9조 환불 및 취소
① 대여 성립 시 대여자의 단순 변심으로 인한 환불 및 교환은 불가능합니다.
② 온라인 대여의 경우, 대여자가 제공한 신체치수를 기준으로 발송이 이루어지기 때문에 잘못된 치수 측정으로 인한 피해는 열린옷장에게 책임이 없으며, 환불이 불가합니다.

제10조 반납
① 대여 의류의 반납은 택배 반납 또는 방문 반납 중 선택하여 반납할 수 있습니다.
② 방문 반납의 경우 약정된 반납일에 맞추어 열린옷장에 방문하여 반납합니다.
③ 택배 반납의 경우 대여자가 선불로 별도의 박스에 대여한 의류를 손상이 생기지 않도록 포장하여 최소 반납일 1일전에 발송해야 합니다. 

제11조 감사 편지 작성
① 대여자는 대여한 의류를 반납시 의류를 기증한 자(이하 “기증자”)에게 보내는 감사 편지를 작성하여 열린옷장에 전달하고, 열린옷장은 정기적으로 감사 편지를 모아 기증자에게 전달합니다. 
② 대여자가 작성한 감사 편지는 홈페이지 및 SNS에 게재되어 공유될 수 있으며, 대여자는 이에 포함된 본인의 정보 공유에 동의합니다. 만약 이에 동의하지 않는 경우 대여자는 편지 작성 시에 열린옷장에 감사 편지의 홈페이지 및 SNS 게재에 동의하지 않는다고 이메일 또는 전화로 고지하고, 이 경우 열린옷장은 해당 편지를 홈페이지 및 SNS에 게재하지 않습니다. 이미 홈페이지 및 SNS에 게재된 경우 열린옷장은 이를 홈페이지에서 삭제합니다.
③ 기증자는 기증 편지를 작성하여 열린옷장에 전달할 수 있으며, 이 편지는 홈페이지 및 SNS에 게재되어 공유될 수 있습니다. 기증자는 이에 포함된 본인의 정보 공유에 동의합니다. 만약 이에 동의하지 않는 경우 기증자는 편지 작성 시에 열린옷장에 기증 편지의 홈페이지 및 SNS 게재에 동의하지 않는다고 이메일 또는 전화를 통하여 고지하고, 이 경우 열린옷장은 해당 편지를 홈페이지 및 SNS에 게재하지 않습니다. 이미 홈페이지 및 SNS에 게재된 경우 열린옷장은 이를 홈페이지에서 삭제합니다.

제12조 서비스의 중단
열린옷장은 컴퓨터 등 정보통신설비의 보수점검·교체 및 고장, 통신두절이 발생하거나 정기점검 등의 필요로 인하여 서비스의 제공을 일시적으로 중단할 수 있고, 새로운 서비스로의 교체 기타 열린옷장이 적절하다고 판단하는 사유에 기하여 현재 제공되는 서비스를 완전히 중단할 수 있습니다. 

제13조 정보 제공 및 홍보물 게재
① 열린옷장은 서비스를 운영함에 있어서 각종 정보를 서비스에 게재하는 방법 등으로 대여자에게 제공할 수 있습니다.
② 열린옷장은 서비스에 적절하다고 판단되거나 활용 가능성 있는 홍보물을 게재할 수 있습니다.

제14조 열린옷장의 의무
① 열린옷장은 법령과 본 약관이 금지하거나 공서양속에 반하는 행위를 하지 않으며 본 약관이 정하는 바에 따라 지속적이고, 안정적으로 서비스를 제공하기 위해서 노력합니다. 

② 열린옷장은 대여자의 개인 신상 정보를 본인의 승낙 없이 타인에게 누설, 배포하지 않습니다. 다만, 전기통신관련법령 등 관계법령에 의하여 관계 국가기관 등의 요구가 있는 경우에는 그러하지 않습니다.
③ 열린옷장은 대여자가 안전하게 인터넷 서비스를 이용할 수 있도록 대여자의 개인정보보호를 위한 보안 시스템을 구축합니다. 

제15조 대여자의 의무
① 대여자는 다음 행위를 하여서는 안 됩니다.
1. 서비스 신청 시 허위 내용의 등록
2. 타인의 정보 도용
3. 열린옷장이 정한 정보 이외의 정보(컴퓨터 프로그램 등) 등의 송신 또는 게시
4. 열린옷장 및 기타 제3자의 저작권 등 지적재산권에 대한 침해
5. 열린옷장 및  기타 제3자의 명예를 손상시키거나 업무를 방해하는 행위
6. 외설 또는 폭력적인 메시지, 화상, 음성, 기타 공서양속에 반하는 정보를 열린옷장에 공개 또는 게시하는 행위
8. 범죄행위를 목적으로 하거나 기타 범죄행위와 관련된 행위
9. 선량한 풍속, 기타 사회질서를 해하는 행위
10. 해킹행위 또는 컴퓨터바이러스의 유포행위
11. 타인의 의사에 반하여 광고성 정보 등 일정한 내용을 지속적으로 전송하는 행위
12. 서비스의 안전적인 운영에 지장을 주거나 줄 우려가 있는 일체의 행위
13. 사이트에 게시된 정보의 변경
② 대여자는 열린옷장의 사전 승낙 없이 서비스를 이용하여 어떠한 영리행위도 할 수 없습니다.

부 칙
1. (시행일) 본 약관은 2016년 3월 2일부터 시행됩니다.

**Comment by 10001if** [comment]
홈페이지 푸터에 들어갈 1)이용약관 2)개인정보 취급방침은 성일님이 해주실 예정입니다. :)

**Comment by aanoaa** [comment]
해주시는 건 좋은데, 개발환경을 마련하고 해주시면 더 좋습니다.

**Comment by aanoaa** [comment]
랄까 일단 뭐라도 해주시면 ㄱㅅㄱㅅ

**Comment by MoDoLEE** [comment]
제가 수정하는 내용은 staff 페이지 말고 그냥 열린옷장 홈페이지 입니다~^^
그리고 얼른 노트북 가져가서 개발환경 세팅하겠습니다.

**Comment by aanoaa** [comment]
지금은 대여할때에

- 정장 대여규정
- 개인정보 이용안내

에 동의해야 합니다

이것을

- 개인정보 이용동의
- 이용약관

으로 변경해야 하면서 안의 내용까지 변경해야 하나요?

**Comment by aanoaa** [comment]
맞다고 합니다.

**Comment by 10001if** [comment]
확인완료하였습니다.

**Comment by aanoaa** [comment]
https://github.com/opencloset/volunteer/issues/57#issuecomment-215296718

처럼 수정되어야 합니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
