### ISSUE TITLE
대여에서 의류의 상태변경

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#722]
대여가능한 의류만 포장이 가능한데,
첫화면에서와같이 의류의 상태를 손쉽게 변경할 수 있어야 합니다.

https://github.com/opencloset/opencloset/issues/646#issuecomment-190112132

**Comment by yongbin** [comment]
ㄴㄴ #546 과 중복이고 1.1.0에 들어가있는 이슈입니다.
