### ISSUE TITLE
분실된 의류의 후속 처리

### ISSUE THREAD

**Issue by yongbin** [opencloset/opencloset#723]
@10001if 님이 작성해주신 #551 이슈에서 파생된 이슈입니다. 

> "분실"의 경우에도 1. 왜 분실이 되었는지 를 작성하는 란이 필요하구요. 이렇게 입력이 완료되면 자동으로 문자 또는 이메일을 통해 기증자에게 폐기상황을 알려주었으면 합니다.

**Comment by yongbin** [comment]
@10001if 좀 더 내용을 구체화 해주세요!

**Comment by 10001if** [comment]
@yongbin 분실에 대한 논의를 조금 더 진행해 보고 다시 말씀드리겠습니다. :)

**Comment by 10001if** [comment]
이슈를 우선 닫도록 하겠습니다. 추가로 의견이 발생한 경우 다시 열도록 하겠습니다.
