### ISSUE TITLE
신체 치수 변경 후에 다음 치수로 자동 포커싱

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#728]
현재는 `키` 클릭 -> 사이즈 입력 엔터
다시 `몸무게` 클릭 -> 사이즈 입력 엔터

이런식인데,

엔터 누르고 나면 다음 치수로 포커스가 자동으로 이동되어서
키보드만으로 신체치수를 입력하도록 하는 것이 목표입니다.

**Comment by 10001if** [comment]
확인완료하였습니다.

**Comment by aanoaa** [comment]
대여 희망 품목
    대여 희망 색상
    착용날짜
    설명
    키
    몸무게

순서를 위와같이 바꾸고
설명에서 enter 누르면 키로 내려갈 수 잇게해야 합니다.

**Comment by aanoaa** [comment]
설명에서는 자동 포커싱이 되지 않아야 합니다.

**Comment by aanoaa** [comment]
설명 은 여러 줄 입력가능합니다.
Enter 를 누르면 개행이 됩니다. 키/몸무게 처럼 `Enter = 입력` 이 되지 않습니다.

    설명입력 -> Enter -> 바로 키입력

이게 안됩니다.
순서만 바꾸도록 하겠습니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
