### ISSUE TITLE
방문 예약시 SMS 인증 만료 시간을 20분으로 늘림

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#729]
#244 과 관련이 있는 이슈입니다.

현재 인증 만료시간이 10분입니다. 하지만 이 시간내에 모든 입력을 완료하지 못해 예약이 진행되지 못하는 경우가 발생하고 있다고 합니다. 따라서 20분으로 인증 만료시간을 늘려주시기 바랍니다.

**Comment by aanoaa** [comment]
#718 과 함께 처리하겠습니다.

**Comment by aanoaa** [comment]
27dacf460d7cbf5de6b970c8039678583417feef

**Comment by 10001if** [comment]
제가 확인하기는 어려운 이슈입니다. 잘 적용되었을거라 생각하고 확인완료 라벨을 제거하겠습니다.
