### ISSUE TITLE
쿠폰을 발행하고 발행된 쿠폰을 통해 예약을 받는 기능

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#730]
특정 사용자 혹은 특정 그룹에 속한 사용자가 열린옷장을 이용하게 되는 경우 해당 이용자에 대해서는 일반 열린옷장 이용자와는 구분된 예약페이지가 존재해야 하며 본 예약페이지를 통해 예약이 된 이용자의 경우 일반 이용자와는 다르게 식별이 가능한 표시가 있어야 할 것으로 보입니다. 더불어 구분된 이용자의 누적정보를 알 수 있도록 본 정보가 저장되도록 하는 기능이 필요합니다. 자세한 내용은 @yongbin 이 더욱 구체적으로 이해하고 계시리라 생각합니다.

**Comment by yongbin** [comment]
일단 마일스톤에서는 제거합니다.

**Comment by 10001if** [comment]
@yongbin @aanoaa 본 이슈는 늦어도 4/3일까지 마무리 되어야 하는 이슈입니다. 하지만 그보다 더 일찍 완료 될 수록 진행하는데 여유가 많이 생길 것 같습니다. 일정에 제한이 있었던 이슈가 거의 없었는데, 다른 기관과 함게 진행해야 하는 이슈라 조금 특별한 이슈입니다. 조금 더 신경 써 주시면 감사할 것 같습니다. :)

**Comment by 10001if** [comment]
하루에 너무 많은 수의 이용자가 발생할 경우 일반 사용자의 예약이 불가능해질 수도 있으므로 본 프로젝트를 통해 예약을 진행하는 인원의 예약 제한 기능이 필요해 보입니다. 예> 일당 10명, 20명

**Comment by 10001if** [comment]
온라인 대여를 원하는 경우가 발생할 수도 있습니다. 이런 경우에는 기존 방식처럼 열린옷장 직원이 직접 사용자 추가를 하여 의류를 대여하는 방식으로 진행해야 하는데. 이때에도 구별되는 페이지에 접속하여 예약을 진행하는 것이 가능한지 궁금합니다. @yongbin  서울시에서 문의가 왔습니다. 확인 부탁드리겠습니다~ ^^

**Comment by aanoaa** [comment]
우선순위가 ASAP이고, 담당자가 @yongbin 님인데 제가 작업하게 될 것 같으므로 변경하겠습니다.
앞으로 관련된 이야기는 저와 이야기 하시면 됩니다.

**Comment by yongbin** [comment]
이런 상황일때 저랑 상의하고 변경하는게 맞다고 생각합니다.

**Comment by aanoaa** [comment]
상의하고 저한테 토스해주세요.
필요하면 부르겠습니다.

**Comment by aanoaa** [comment]
이게 ASAP 이기 때문에 마일스톤 변경합니다.

**Comment by aanoaa** [comment]
어떻게 쿠폰시스템을 하고싶다 가 있으면 좋겠지만
제가 먼저 아이디어를 꺼내보면,

- 열린옷장에서 종이쿠폰을 만든다(혹은 전자쿠폰?)
  - 쿠폰은 고유번호가 있어야 한다
  - 쿠폰을 입력할 수 있는 웹주소가 포함(http://visit.theopencloset.net/coupon 어떤 주소가 좋을지 모르겠다..)
- 브라우저로 쿠폰을 입력할 수 있는 페이지에 접속
- 쿠폰번호를 입력하고 유효하다면 나머지는 방문대여 예약과 같음
- 쿠폰예약을 구별할 수 있도록 해서 결제방법 선택시 `쿠폰`으로 자동 등록되어 있도록 한다

------------------------------------

- 일일 최대 쿠폰제한

    이건 좀 이상합니다.
    쿠폰입력할때에 예약일을 지정해야 하는 것도 이상하고요,
    하루 쿠폰 사용건 수 가 넘어서 쿠폰 예약을 할 수 없습니다?
    어차피 쿠폰 대여는 서울시에서 가격을 선불해서 지급되는거 아닌가요?

- 온라인 쿠폰대여

    구글독스에 쿠폰번호를 입력하거나, 전화로 쿠폰번호를 받아야 할 것 같습니다.
    아직 온라인 대여에 대한 시스템이 없기 때문에 어렵다고 봅니다.

**Comment by aanoaa** [comment]
쿠폰번호가 너무 길어지면 입력하기 어렵고, 너무 짧거나 예측될 수 있다면 도용될 가능성이 있습니다.
적절한 길이의 쿠폰을 만들어 내야 합니다.

**Comment by yongbin** [comment]
쿠폰코드는 CPAN에 `Algorithm::CouponCode` 를 사용할 생각이었습니다. 쿠폰시스템 관련해서 아래 링크도 읽어보시면 도움되실것 같습니다.

http://stackoverflow.com/questions/22333237/generating-unique-hard-to-guess-coupon-codes

**Comment by yongbin** [comment]
대표님과 논의했던 요구사항중에 이번처럼 쿠폰을 이용하는 이벤트가 동시에 여러게 진행될수 있는 상황을 고려해야합니다. `Promotion` 이라고 지칭했었는데 현재 서울시와 진행하는 프로모션이외에 십시일반팀과 진행하는 프로모션이 있고 둘은 동시에 진행될수 있습니다. 따라서 애초에 구상했던 방식은 https://visit.theopencloset.net/visit/seoul/7JHB-XOXO 같은 방식으로 `visit/:promotion/:coupon` 으로 생성할 생각이었습니다.

`Algorithm::CouponCode` 모듈에서 쿠폰 생성은 난수를 사용해서 중복을 피하기때문에 독립된 실행으로 발행한 코드는 중복될 가능성이 있습니다. 당초 생각은 `CouponSeed` 라는 테이블에 한번에 미리 생성한 10만개 정도의 쿠폰코드를 미리 넣어두고 `Promotion`와 `CouponSeed` 를 연결한 `Coupon` 테이블을 `Order`가 가지는 구조를 생각해습니다. 아니면 쿠폰번호가 프로모션안에서만 독릭접이라면 프로모션때마다 그냥 필요한 수 만큼 발행해서 추가하는 방법도 있을거 같습니다. 참고만 해주시기 바랍니다.

**Comment by aanoaa** [comment]
시스템적인 것만 필요한 것이 아니라,
@10001if 님은 쿠폰내용, 인쇄등에 대한 절차도 생각해야 합니다.

생각나는건 이정도네요.

- 서울시에서 발행한 20,000 원 짜리 대여가능 쿠폰
- 이벤트 당첨된 한달 무제한 쿠폰
  - 혹은 30장 준다

-----------------------------------------

쿠폰

- 번호(uniq)
- (group|type)
- 유효기간
- 발행일
- 사용일
- 상태?
  - 발행됨
  - 지급됨
  - 사용됨
  - 폐기됨
  - ...
- 가격?

**Comment by aanoaa** [comment]
가격에 대한 문제가 있습니다.

쿠폰대여 라는 의미가 어느것을 빌리던 1셋트라는 의미인지,
이 쿠폰은 1만원짜리이고, 나머지는 현금으로 받아야 한다.

라는 의미인지 구별할 필요가 있을까요?

**Comment by yongbin** [comment]
우선 서울시건에서 쿠폰은 별도로 우리가 생각하는 쿠폰형태가 아니라 단지 A4 형식의 안내문에 쿠폰번호를 출력하는 방식으로 진행하신다고 했습니다. 십시일반 이벤트의 경우 어떻게 할지 아직 정해지지 않았습니다. 가격의 경우 `1회 무료 이용권` 개념으로 생각하면됩니다. 쿠폰을 제시한 사람이 구입한 옷은 조합이 어떻든 열린옷장에서 전액 애누리하기로 했습니다 (한벌이상은 안되겠죠 한사람당이니까) 에누리에 대한부분은 수작업으로 처리하기로 했습니다.

**Comment by aanoaa** [comment]
가격 또는 셋트의 개념이 쿠폰에 필요하겠습니다.

- 1셋트짜리 쿠폰
- 구두 쿠폰
- 1만원 상당의 쿠폰(상품권?)
  - 남은돈은 돌려주나?

**Comment by aanoaa** [comment]
결제방식도 쿠폰의 종류에 따라 변경되어야 하겠습니다.

- 현금
- 카드
- 쿠폰
- 쿠폰+현금
- 쿠폰+카드

**Comment by aanoaa** [comment]
이벤트와도 관계가 있을 것 같지만 거기까지는 고려하지 않겠습니다.

E 이벤트에 당첨되어서 받은 쿠폰 C

**Comment by aanoaa** [comment]
이걸로 테스트용 쿠폰을 만들어서 사용합니다.

``` perl
#!/usr/bin/env perl

use v5.18;
use utf8;
use strict;
use warnings;
use open ':locale';

use Algorithm::CouponCode qw(cc_generate cc_validate);

use OpenCloset::Config;
use OpenCloset::Schema;

my $CONF   = OpenCloset::Config::load('app.conf');
my $schema = OpenCloset::Schema->connect(
    {
        dsn      => $CONF->{database}{dsn},
        user     => $CONF->{database}{user},
        password => $CONF->{database}{pass},
        %{ $CONF->{database}{opts} },
    }
);

my $code = cc_generate( parts => 3 );
$schema->resultset('Coupon')->create(
    {
        code => $code,
        desc => 'test',
    }
);
```

**Comment by aanoaa** [comment]
결제방식이 

- `쿠폰+현금`
- `쿠폰+카드`

일때는 현재 쿠폰의 금액을 주문서에 보여줘야 합니다.
그래야 쿠폰에서 모자른 금액을 청구할 수 있을테니까요.

이게 자동으로 된다면 좋을 것 같습니다.

**Comment by aanoaa** [comment]
기능 확인이 되고나면, 쿠폰을 등록할 수 있는 스크립트를 만들어서
필요할만큼 쿠폰을 등록할 수 있도록 해야 합니다.

생성된 쿠폰번호를 가지고 인쇄하면 될 것 같습니다.

**Comment by aanoaa** [comment]
사용할 수 있도록 배포하였습니다.

**Comment by aanoaa** [comment]
사진관과 같이 사용할 수 있는 기능이 추가 되어야 합니다.

**Comment by aanoaa** [comment]
사진관관련된 쿠폰은 다른 쿠폰입니다.
사진촬영이 가능한 쿠폰이고 일일 방문자가 15명이 넘지 않도록 예약할 수 있는 기능이 필요합니다.

정장/사진쿠폰에 대해 월별 사용내역을 볼 수 있는 관리 화면도 필요합니다.

**Comment by aanoaa** [comment]
사진관관련된 일은 짬됐습니다.

**Comment by aanoaa** [comment]
서울시에서 쿠폰 2000장을 요청해서

```perl
#!/usr/bin/env perl

use v5.18;
use utf8;
use strict;
use warnings;
use open ':locale';
use Try::Tiny;

use Algorithm::CouponCode qw(cc_generate cc_validate);

use OpenCloset::Config;
use OpenCloset::Schema;

my $CONF   = OpenCloset::Config::load('app.conf');
my $schema = OpenCloset::Schema->connect(
    {
        dsn      => $CONF->{database}{dsn},
        user     => $CONF->{database}{user},
        password => $CONF->{database}{pass},
        %{ $CONF->{database}{opts} },
    }
);

my $guard = $schema->txn_scope_guard;
try {
    for my $i ( 1 .. 2000 ) {
        my $code = cc_generate( parts => 3 );
        $schema->resultset('Coupon')->create(
            {
                code => $code,
                type => 'suit',
                desc => '서울시이벤트',
            }
        );
    }

    $guard->commit;
}
catch {
    my $err = $_;
    print STDERR "Failed to generate coupon: $err\n";
};
```

으로 생성하였습니다.

**Comment by aanoaa** [comment]
유효기간이나 이벤트이름등은 변경가능합니다.

**Comment by aanoaa** [comment]
서울시에서 전화로 연락이 왔습니다.
쿠폰번호 없이 서울시 무슨 서비스 로그인된 사용자가 방문예약하면 바로 사용할 수 있게 할 수 없겠느냐고요.

실무담당하시는 분이 아니기 때문에 이해하지 못했고 실무자가 다시 연락준다고 합니다.

cc @10001if

**Comment by aanoaa** [comment]
실무담당자분과 통화를 했습니다.

쿠폰을 월 500 건 제한 / 사용자별 2 건 제한 등의 조건이 필요한데
서울시 무슨 서비스에서 그런걸 관리 하지 않고 로그인된 사용자의 개인정보를
열린옷장 서비스에 넘겨줄테니 알아서 해야 한다 4월 20일 까지

이런 내용이었습니다.

cc @10001if

**Comment by aanoaa** [comment]
서울시에서 걱정하는건 쿠폰을 선점해두는 그런 현상이었습니다.
지금 당장 필요한 사람한테 연 2회 제공해주는 취지에 어긋난다고 생각하고 있습니다.

필요한 시기에 신청하고 사용할 수 있도록 변경해야 합니다.

**Comment by aanoaa** [comment]
서울시의 무슨 서비스를 `S` 라고 하겠습니다.
열린옷장의 예약 버퍼는 1주 ~ 2주 가량입니다.

    S 로그인 -> 열린옷장 -> 방문예약

형태가 되어야 합니다.

S 에 미리 발행된 쿠폰을 전달해주는 것이 아니라, 수요가 있을때
열린옷장에 쿠폰을 요청하면 기간 2주짜리 쿠폰을 발행하는 것도 하나의
방법입니다.

**발행방법**

- S 서비스에서 S 사용자의 ID 로 쿠폰요청
- 열린옷장에서 ID 로 체크해서 2번 이상 발행되지 않은 ID 에 한해 쿠폰
  생성 및 발급
- S 에서 쿠폰 전달

이렇게 하면 필요한 사람이 신청할 수 있으면서 개인정보를 노출도
없습니다.

S 서비스에서는 요청후에 발행 또는 적절한 예외처리를 해야 합니다.


제가 생각한 방법입니다.
@10001if 검토해주세요.

**Comment by aanoaa** [comment]
이렇게 된다면 요청할때마다 쿠폰을 발행해줘야 하는가?
라는 이슈가 생기게 됩니다.

지원금 이상의 쿠폰발행이 발행된다면 열린옷장에서는 손해를 보게되기
때문입니다.

최대 몇장을 발행할 것이지 염두해둔다면 괜찮을 것 같습니다.

**Comment by aanoaa** [comment]
> 안녕하세요.
> 오전에 회의에 참석했던 홍형석이라고 합니다.
> 
> 서울시에서 걱정하는 건
> 
>     사용자가 갑자기 몰리는 것
>     쿠폰을 선점해두는 현상
> 
> 이라고 이해했습니다.
> 
> 사용자가 갑자기 몰리는 것 에 대한 해결은 이미 되어 있습니다.
> 열린옷장에서는 예약가능일 버퍼를 1주 ~ 2주 정도로 두고 있습니다.
> 오늘(4/15)을 기준으로 4/23 까지만 예약을 할 수 있습니다.
> 
> 그리고 대여자가 너무 많아도 대여업무를 소화해내지 못하기 때문에,
> 매일 정해둔 인원 이상 예약을 받지 않습니다.
> 
> 이것으로 갑자기 사용자가 몰리는 것에 대한 우려는 안하셔도 될 것
> 같습니다.
> 
> 쿠폰을 선점해두는 현상 을 해결하고자 고민해봤습니다.
> 
>     필요한 시기에 신청해야 한다.
>     연 2회 까지만 제공한다.
> 
> 이 조건을 만족시키기 위해서,
> 
> 사용자의 요청이 있을때 2주간 예약 가능한 쿠폰을 발급한다.
> 
> 면 어떨까 합니다.
> 
> 쿠폰발급에 대해서는 서울시 서비스의 협력이 필요합니다.
> 
>     열린옷장에서 미리 마련해둔 채널을 통해 사용자의 ID 를 가지고 쿠폰을
>     요청합니다.
> 
>      GET https://visit.theopencloset.net/xxxxxxx?secret=xxxxx&sid=xxxxx
> 
>      {"code:"ABCD-ABCD-ABCD",...}
> 
>     열린옷장에서는 sid 를 가지고 2회 이상 발급되지 않도록 합니다.
>     서울시 서비스에서 적절한 예외처리를 하고 발행된 쿠폰코드를
>     알려줍니다.
> 
> 이런 방식이라면 유효기간이 2주 짜리 이기 때문에 선점해둘 수 없습니다.
> 
> 사용자입장에서는 필요한시기에 방문예약 버튼 같은걸 눌러서 방문예약을
> 합니다.
> 
> 제가 생각한 해결방법은 이렇습니다.
> 검토해보시고 답변 부탁드립니다.
> 
> 더 나은 제안이 있다면 알려주세요.
> 
> 참고로 열린옷장의 이슈 및 서비스는 오픈소스로 운영되고 있습니다.
> 쿠폰시스템에 관한 논의는 아래링크에서 진행되고 있습니다.
> 
> https://github.com/opencloset/opencloset/issues/730
> 
> 그럼 수고하세요.

**Comment by aanoaa** [comment]
> 안녕하세요. 서울일자리플러스센터 송의형 입니다.
> 
> 아래의 내용은 최초의 원점으로 돌아가는듯 하여 의견을 남깁니다.
> 
>  
> 
> 금번의 이슈는 서울시 일자리정책과에서 추진하고자 하는 '취업날개서비스'에 있어서
> 
> 최소한의 절차를 통해 정장대여서비스를 제공하고자 함에 따라
> 
> 쿠폰을 발행하게 되는 형태의 경우 크게 2가지 문제점을 해결 하고자 함 입니다.
> 
>  
> 
> 첫째는 이용자에게 번거로운 절차로 인한 불편을 초래한다는 점입니다.
> 
> 원래의 기본 흐름은 '서울일자리플러스센터 회원가입 -> 쿠폰발급신청 -> 예약 -> 사용' 입니다.
> 
> 그러나 '쿠폰발급신청 절차 없이 시용자가 필요로 하는 시기에 바로 예약을 할 수 있도록 한다'
> 
> 의 취지에 따라 '서울일자리플러스센터 회원가입 -> 예약 -> 사용'의 단계를 최소화 하고자 하는 것입니다.
> 
>  
> 
> 둘째는 쿠폰 유효기간이 장기간임에 따라 미리 선점하게 되면 특정 시기에 실제 필요한 구직자에게
> 
> 제공하지 못하는 현상이 발생될 수 있다는 점입니다.
> 
> 이부분에 대해서 2주간의 유효기간을 가진 쿠폰을 발급한다는 것은 대안이 될 수 있으나
> 
> 쿠폰발급신청의 절차를 생략하고 바로 예약서비스를 이용할 수 있도록 하고자 함에 있어
> 
> '첫번째 문제점인 절차 간소화'에는 부합되지 못한다는 점입니다.
> 
>  
> 
> 이와 같은 검토로 인해 금일 오전에 회의에서 내용을 함께 공유하였으며,
> 
> 쿠폰 발행없이 이용자가 필요시 바로 예약서비스를 이용할 수 있도록 추진하자는 내용에 대하여
> 
> 양자 이해가 된것으로 생각했는데
> 
> 메일 주신 내용에 따르면 이야기가 원점으로 돌아가는 듯 해서 의견 남깁니다.
> 
>  
> 
> 이상입니다.

**Comment by aanoaa** [comment]
> 서울일자리플러스센터 회원가입 -> 예약 -> 사용
> 
> 예약 전에 내부적인 신청 절차가 필요합니다.
> 모든 사용자에게 지급되는게 아니고 신청하는 사용자에 한해 2회까지 지급될 수 있습니다.
> 신청과 동시에 지급되도록하고 적절한 링크를 사용자에게 제공해서 쿠폰입력의 절차를 생략할 수 있습니다.
> 
> 사용자는 예약 버튼을 누르고 양 서비스끼리 쿠폰의 신청/발급 절차를 거친다면 단계를 최소화 할 수 있습니다.

**Comment by aanoaa** [comment]
> 아래 말씀하시는 의미는 충분히 이해가 갑니다.
> 다만, 제가 이해가 안되는 부분이 있습니다.
>  
> 쿠폰발행을 이용자는 알수 없도록 시스템 내부 프로세스에 의해서 발급처리 한다고는 하지만,
> 이용자는 예약을 하기 위해서 접근하는 것이고 예약처리가 되기만 하면 됩니다.
> 그런데 이과정에서 열린옷장과의 시스템 인터페이스가 의미가 없을 것으로 판단되는데
> 인터페이스를 통해 무엇을 하고자 하는 것인지요?
>  
> 즉, 내부적으로 쿠폰이 발행된다해도 열린옷장에서 체크로직이 수행되므로
> 일자리플러스센터 시스템과 인터페이스하는 등의 수고 할 필요없이
> 열린옷장 시스템내에서 일자리플러스센터로부터 전달된 ID값을 가지고
> 쿠폰 발급이 필요하면 내부적으로 자동발급처리하고 이미 발급된 쿠폰이 있다면 skip하고
> 이용자는 바로 예약할 수 있도록 처리하면 될것으로 판단됩니다.
>  
> 이상입니다.

**Comment by aanoaa** [comment]
> 아무나 유의미한 신청을 할 수 없도록 하기 위함입니다.
> 인증을 통과한 요청을 통해서만 신청이 가능하게요.
> 
> 여기서 인증이라는건 저희쪽에서 추측하기 어려운 긴 비밀번호를 전달해드리려고 했습니다.
> 
> 3회 이용자에게 이러이러한 사유로 더이상 사용할 수 없다.
> 라는 예외처리 또한 필요하지 않을까 생각했습니다.
> 
> GET https://visit.theopencloset.net/xxxx?sid=xxx&secret=xxxxx
> 
> 양서비스간 통신을 skip 하면 사용자에게 secret 이 노출되어 버리기 때문에 악용의 가능성이 있습니다.
> 그렇다고 secret 없이 신청가능하게 하면, sid 를 추측해서 신청해버릴 수도 있고요.
> 
> 의견 부탁드립니다.

**Comment by aanoaa** [comment]
> 아래와 같은 의미라면, 저희도 검토하고 있는 부분이었습니다.
> 
> 이에 대하여, 순수한 ID값을 전달할것이 아니라
> 
> 기본 Java Security 모듈을 활용하여 양측 암/복호화 key를 정하고
> 
> 일자리플러스센터 시스템에서 예약사이트 링크 연계시
> 
> 정해진 key를 기준으로 ID값을 암호화하여 열린옷장측으로 전달하고,
> 
> 열린옷장측에서는 같은 key를 이용하여 복호화하여 활용하는 방안을 생각해보았습니다.
> 
>  
> 
> 첨부된 test.java 파일은 암복호화 기본 예제 소스코드입니다.
> 
> 이를 참고해서 key값만 상호 공유하면 될것으로 판단합니다.
> 
>  
> 
> 또한, 2회이상 사용자의 요청에 대해서는 예약사이트 화면에서 체크하고
> 
> 메시지(Alert) 표시하면 될것 같습니다.
> 
> (어차피 일자리플러스센터에서 체크할 로직이 없는 상태에서 예외처리 관리할것이 없을듯 합니다)
> 
>  
> 
> 이상입니다.

**Comment by aanoaa** [comment]
> 네 복호화 가능한 방식으로 암호화해서 ID 를 전달해 주신다면, 처리할 수
> 있을 것 같습니다.
> 
> 다만 열린옷장에서는 추가작업이 필요합니다.
> 
> 특정페이지에 query 파라미터로 암호화된 사용자 식별자를 가지고 연 2회
> 제한을 두고 무료 대여 할 수 있는 작업을 해야 합니다.
> 
> 이건 개발 이슈와는 다른 얘기인데, 
> 지원금 이상으로 사용자들이 들어오게 되면 열린옷장에서는 손해인데
> 몇명까지 사용할 수 있도록 해야 하나요?

**Comment by aanoaa** [comment]
```perl
use strict;
use warnings;
use Crypt::CBC;
use Crypt::Cipher::AES;

my $key = 's3cr3t';
my $cipher = Crypt::CBC->new( -key => $key, -cipher => 'Cipher::AES' );

my $ciphertext = $cipher->encrypt_hex('hello world');
my $plaintext  = $cipher->decrypt_hex($ciphertext);
print "$ciphertext\n";
print "$plaintext\n";

__DATA__
53616c7465645f5fcfb6701124e913d62f8177036d63efe5d8cb71fedb60fce9
hello world
```

암호화/복호화 예시 입니다.

**Comment by aanoaa** [comment]
위의 예제는 잘못되었습니다.
CBC 방식을 사용하지 않기 때문입니다.

문자열 key 가 `EncTestByKimByoungKi` 이고 이메일에 첨부된 java 파일로
`tds` 라는 문자열을 암호화한 hex string 은
`A81F368A9771CE2E8DB7D98A50B52068` 입니다.

프로그램내에서 key 를 가지고 다시 변환하는데 이 결과가 항상
일정합니다.

변환된 key의 hex string 은 `672A9495B1D834CD357D979A7BC81859` 이고
이를 가지고 `ECB` 방식으로 encrypt, decrypt 해서 같은 결과를 얻었습니다.

``` perl
use strict;
use warnings;
use Crypt::Mode::ECB;
my $key = pack( 'H*', '672A9495B1D834CD357D979A7BC81859' );
my $m = Crypt::Mode::ECB->new('AES');

my $ciphertext = $m->encrypt( 'tds', $key );
my $hexstring = unpack( 'H*', $ciphertext );
print "$hexstring\n";
my $plaintext = $m->decrypt( $ciphertext, $key );
print "$plaintext\n";
__DATA__
a81f368a9771ce2e8db7d98a50b52068
tds
```

**Comment by aanoaa** [comment]
`2016-12-30` 까지 진행되는 이벤트입니다.
4000건 이상 사용되면 역시 조기 종료되어야 합니다.

**Comment by aanoaa** [comment]
지급과 사용이라는 단어가 구분되어야 합니다.

지급과 동시에 사용으로 해버리면 두번연속 페이지를 로딩하게 되면
사용되지 않은 쿠폰이 바로 짬되는 현상이 나타날 수 있어서 구분해야
합니다.

**Comment by aanoaa** [comment]
사용건수로 제한을 걸면 4000개 이상 발급될 수 있습니다.
그 이후에는 4000개가 사용될때까지 선착순

**Comment by aanoaa** [comment]
![screenshot-localhost 5001 2016-04-20 14-22-32](https://cloud.githubusercontent.com/assets/170528/14664177/5eb56b48-0703-11e6-9c51-129f445c37c3.png)

**Comment by aanoaa** [comment]
이미 발급되었던 이벤트용 쿠폰은 짬시키도록 하겠습니다.

**Comment by aanoaa** [comment]
방문예약할때에 의류선택에 따라 자동으로 계산되는 예상대여비를 보이지 않게 하였습니다.

**Comment by aanoaa** [comment]
배포하였습니다.
서울시에 테스트 요청을 해도 됩니다.

**Comment by aanoaa** [comment]
저희가 서울시 개발파트에 알려줘야 할 건

https://visit.theopencloset.net/events/seoul?MberSn=xxxxx

입니다.

**Comment by 10001if** [comment]
![2016-04-20 5 09 52](https://cloud.githubusercontent.com/assets/4696328/14668228/1d389008-071e-11e6-80c1-43f9efa3ebda.png)
@aanoaa 오타가 있습니다. `대여이리` 라고 표기되어 있는 부분을 `대여일`로 수정 요청드립니다.

**Comment by aanoaa** [comment]
> 안녕하세요.
> 
> https://visit.theopencloset.net/events/seoul?MberSn=xxxxx
> 
> 처럼 링크를 만들어서 사용해보세요.
> 그럼 수고하세요.

**Comment by 10001if** [comment]
![20160421_ - _](https://cloud.githubusercontent.com/assets/4696328/14695627/d2f15232-07ae-11e6-8582-b158c6f727ca.jpg)
서울특별시
지자체 최초의 취업전문기관인 <서울시 일자리
플러스 센터>를 통해 현재 24명의 전문상담사가 
취업 및 창업 상담과 알선을 진행하고 있으며, 
면접의상 등의 취업서비스도 지원하고 있습니다. 

하나은행
함께 성장하며 행복을 나누는 금융을 지향하는 
KEB하나은행은 기업의 사회적 책임을 다하고자 
사회공헌기금을 사단법인 열린옷장에 전달하여
취준생의 면접정장 대여비용으로 사용됩니다. 

열린옷장
옷장 속에 잠들어있는 사회선배들의  정장과 
이야기를 기증받아 면접을 앞둔 청년구직자들에게 
공유함으로써 취업비용에 대한 실질적인 부담을 
덜어주는 정장공유 활동을 하고 있습니다.

@aanoaa 서울시에서 내용이 조금 많다고 수정을 요청하셨습니다. 오후까지 수정을 부탁드리고 싶은데, 괜찮으실까요?

**Comment by aanoaa** [comment]
네 수정은 했습니다.
배포는 아무때나 하면 되긴 하는데,
급할게 없는데 자꾸 급하게 요청하네요.

**Comment by 10001if** [comment]
고생하셨습니다~ 확인완료하였습니다. ^^
