### ISSUE TITLE
Mojolicious::Lite to Mojo

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#733]
간단하게 시작했다가 기능이 많이 붙었습니다.
더 강력하고 관리하기 쉬운 Mojo 로 옮겨탑니다.

**Comment by yongbin** [comment]
:+1:

**Comment by aanoaa** [comment]
네임스페이스를 정해야합니다.

- `OpenCloset`
- `OpenCloset::Staff`
- `OpenCloset::Manager`

이거말곤 더 생각나는게 없습니다.
무난하게 `OpenCloset` 으로 할까 생각중입니다.

**Comment by aanoaa** [comment]
기존 프로그램에서 `OpenCloset::Web` 이라는 단어가 보입니다.
`OpenCloset::Web` 으로 진행하겠습니다.

**Comment by yongbin** [comment]
개인적으로는 OpenCloset::XXX 에서 XXX가 일반명사가 아니라 전혀 새로운 고유명사로 붙었으면 좋겠습니다.

**Comment by aanoaa** [comment]
저도 그러고 싶은데 재고관리 및 대여에 관해 사용되고 있는 지금의 프로젝트에 딱히 들어 맞는게 없네요.

단어를 만들거나 전혀 상관없는거라면 추천해주세요.

**Comment by aanoaa** [comment]
`OpenCloset::Diablo` 같은거 말씀하시는거죠?

**Comment by aanoaa** [comment]
request path 에 따라서 인증 절차가 다른 부분이 있습니다.
바꾸는 거 없이 그대로 옮기기만 하려고 했는데 어쩔 수 없이 고쳐야 하는 부분도 발생할 것 같습니다.

**Comment by aanoaa** [comment]
`site_type` 에 `all` 은 사용되고 있지 않으므로 고려하지 않겠습니다.

**Comment by yongbin** [comment]
넵 `OpenCloset::Diablo` 같은걸로 정해졌으면 하는 바램이 있습니다. (Web으로 가도 전혀 불만없습니다) 단어 한번 궁리해보겠습니다.

**Comment by aanoaa** [comment]
오늘 점심시간을 활용해서 배포하도록 하겠습니다.

- [ ] ubic 의 실행방법 변경

    `app.psgi` 대신에 `script/web` 을 실행

- [ ] visit, staff 모두 반영
- [ ] 전체적인 테스트
