### ISSUE TITLE
템플릿에서 초기화 되지 않은 값 사용 경고 발생

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#735]
제가 haml 을 안좋아하는 이유이기도 한데, 템플릿 디버깅이 더 어려운 것 같습니다.
지금 템플릿쪽에 warning 이 많은데 이걸 줄여야 합니다.

```
Use of uninitialized value
Use of uninitialized value in addition (+) 
```

이런 오류들이 대부분입니다.
- `/clothes/J03Y`
- `/visit2`
- `/order/24100`
- `/size/guess`
- `/stat/bestfit`
- `/stat/clothes/hit/jacket?start_date=2016-02-10&end_date=2016-03-10&gender=male&limit=10`
- `/stat/visitor/2016-03-10`

warning 이 발생하고 있는 페이지들 입니다.
더 있을 수 있습니다.

**Comment by keedi** [comment]
다른 이유(의존성을 줄이려고)로 haml을 안쓰고 있긴 하지만 uninitialized value 이슈는 stash로 넘길 때의 이슈지 딱히 ep랑 비교해서 haml이 템플릿 디버깅이 더 어려운 것 같지는 않습니다.(이거나 저거나 뭐...)

**Comment by aanoaa** [comment]
ep 를 사용했을때는 템플릿내에서 어디서 초기화 되지 않은 값이
사용되었는지 알려주지만 haml 은 그렇지 않습니다.

**Comment by keedi** [comment]
#927 항목을 진행하면서 제가 처리하겠습니다.

**Comment by keedi** [comment]
#927에서 제가 진행하지 않았고 #1322 이슈에서 @aanoaa 님께서 haml -> ep로 변환이 진행했었습니다.

초기화하지 않은 값을 사용할 때 경고가 발생하는 것은 비단 haml 만의 문제는 아니나, ep 로 변환한 현 시점 기준 더이상 유효하지 않은 이슈이며, 처리해야하면 별도의 이슈를 생성해 진행하거나, 본 이슈를 다시 열어서 진행합니다.

이슈 닫습니다.
