### ISSUE TITLE
본인 인증 서비스 변경

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#736]
기존에는 입력한 번호로 인증번호를 발송하였으나, 앞으로는 번호와 이름을 확인하는 서비스로 변경하려고 합니다. 서비스 가입은 모두 완료했구요. 관련 내용은 이메일로 발송하였습니다.

**Comment by aanoaa** [comment]
> 연속되거나 중복되지 않은 영어알파벳, 숫자, 특수문자( !@#$%^&* ) 3종류 조합의 최소 8 자리이상 최대 20 자리 이하의 문자열 

을 비밀번호로 만들어야 하는데..

**Comment by aanoaa** [comment]
이메일에 안내된 사이트 들어가봤는데 본인인증에 관련된 내용을 찾을 수 없었습니다.

**Comment by aanoaa** [comment]
비밀번호를 변경해야 사용할 수 있다고 해서 임의로 제가 변경했습니다.
변경한 비밀번호는 이메일로 전달했습니다.

**Comment by 10001if** [comment]
서비스 관련해서 문의 드려야 할 담당자에게 형석님 메일을 참조로 걸어 내용을 전달하였습니다. @aanoaa 메일 수신인에게 관련 정보를 문의하시면 됩니다. :)

**Comment by aanoaa** [comment]
이거 좀 더 연구해봐야 합니다.
본인인증서비스 업체를 통해서만 가능한건지 어떤지 부터요.
그리고 볼륨이 좀 잇을 것 같습니다.
마일스톤 변경하겠습니다.

**Comment by aanoaa** [comment]
http://www.neis.go.kr/pas_mms_nv13_001.do

암걸리겠다

**Comment by 10001if** [comment]
@aanoaa 잘은 모르겠지만, 굉장히 복잡해 보이네요. 어려운 주제를 던져드린것 같아 죄송스런 맘이 ^^;

**Comment by aanoaa** [comment]
airbnb 에서는 본인인증을 위해서 아래 서비스를 사용합니다.

https://www.jumio.com/netverify/

**Comment by aanoaa** [comment]
http://runean.com/website-identification/

> 본인확인 또는 실명인증 방법 분석, 주민번호는 완전히 사라진다!

의 내용을 빌리자면,

- 본인인증
- 실명인증

으로 나누어서 생각할 수 있습니다.

한발 더 나아가면,

- 본인명의 휴대폰번호 인증

도 있을 수 있겠습니다.

본인인증은 지금도 되고 있습니다.
지금 필요한것이 실명인증인데,
본인명의 휴대폰번호 인증도 필요한지 답변해주세요.

**Comment by aanoaa** [comment]
후보

https://www.impay.co.kr/serviceInfo11.do

**Comment by aanoaa** [comment]
실명인증방법은 주민번호와 이름을 가지고 할 수 있고,
i-pin 으로도 할 수 있습니다.

하지만 제가 하고 싶은건 휴대폰번호를 가지고 휴대폰명의인증과 실명확인, 인증번호를 동시에 처리하고 싶습니다.

**Comment by aanoaa** [comment]
인증서비스사 처럼 통신사와 직접 붙어서 할 수 있는 방법이 있지 않을까 싶은데 못찾겠습니다.

**Comment by aanoaa** [comment]
https://www.uplus.co.kr/sys/comm/RetrieveAuthSMSPage.hpi

이걸로 꼼수쓸 수 있을 것 같긴 하지만 묻어두겠습니다.

**Comment by aanoaa** [comment]
>  (정보통신망법 개정에 따라 이름과 주민등록번호를 이용하여 본인인증을 할수 없습니다.)

**Comment by aanoaa** [comment]
실명인증을 할 수 있는 방법

- 본인명의 휴대폰을 통한 방법
- 공인인증서
- ipin

가 아닐까 싶습니다.

더 탐구생활 해봐야 합니다.

공인인증서를 웹서비스에 사용하려면 더러워질 것 같아서 pass 하고,
(만약에 쉽게 사용가능하다면 뺄 이유가 없습니다)

ipin 은 개인적으로 서비스의 질이 같이 떨어지는 느낌

해서 휴대폰을 통한 본인인증을 하려고 합니다.

**Comment by aanoaa** [comment]
본인인증방법을 통해서 본인인증된 사용자의 정보를 저장해야 합니다.

이게 무슨말인가하면, 아들이 엄마껄로 예약 했다면 엄마 이름으로 와서 빌려야 한다는 겁니다.
이때 엄마의 정보는 본인인증된거겠죠?

반납이 안되었을때는 엄마가 책임을 지게 됩니다.

**Comment by aanoaa** [comment]
### 본인인증방법 ###

http://platum.kr/archives/26023

- my-pin
- i-pin
- 휴대폰

    > 방송통신위원회는 공인인증서와 아이핀을 서비스하는 한국신용정보, 한국신용평가정보, 서울신용평가정보, 한국정보인증, 코리아크레딧 뷰로 등 5개 업체를 본인확인기관으로 뒀는데 2012년 12월 여기에 KT와 SK텔레콤, LG유플러스 등 3개 통신회사를 추가했다. 정보통신망법 제23조의2와 개인정보보호법이 주민번호 수집을 금지한 상황에서 8개 업체에 주민번호가 모여 저장되는 상황인 게다.

- 신용카드

    > 신용카드 인증은 본인명의로 발급 받은 신용카드의 카드번호, 유효기간과 본인이 설정한 해당 신용카드의 비밀번호 앞 2자리를 입력한 뒤 이를 각 신용카드 발급기관에 확인함으로써 본인 인증을 받는 방식입니다.

- 공인인증서


등이 있는 것 같습니다.


국가에서 지정한 본인확인기관이 제공하는 방식을 통해 해야 하는 것 같습니다.

**Comment by aanoaa** [comment]
인증방법이 다양하지만, 휴대폰번호로 본인인증기관인 통신사를 통해서
본인인증을 하는 방법이 해결되어야 합니다.

가장 편리한 방법인 것 같습니다.

필요하다면 i-pin 이나 다른 방법들 역시 이후에 추가될 수 있습니다.

**Comment by aanoaa** [comment]
탐구생활이 더 필요하겠습니다.
구려도 상관없다면 인증대행사 서비스 아무거나 붙여도 되지만
그렇게 하더라도 결제 및 대행사와의 커뮤니케이션등 시간이 더 필요합니다.

마일스톤을 변경하도록 하겠습니다.

**Comment by keedi** [comment]
진행합니다.

**Comment by keedi** [comment]
본인 인증은 현재 하지 않고 있으며 정확히는 휴대폰 문자 인증을 수행하고 있습니다. 이 과정은 현재 방문 예약 시점에 진행하고 있습니다. 따라서 본 이슈는 #365 이슈와 연관이 있습니다. #365 이슈를 처리한 뒤 바로 이어서 본 이슈를 처리하겠습니다.

**Comment by yongbin** [comment]
참고하시라고  최근에 가입했던 서비스(위매프)에 본인인증 절차를 캡쳐했습니다. 

----

![img_0794](https://cloud.githubusercontent.com/assets/52704/15346282/68b8ed6e-1cf1-11e6-92ec-bba0f5e20171.png)
![img_0795](https://cloud.githubusercontent.com/assets/52704/15346283/68b9acea-1cf1-11e6-843f-6e94329cb061.png)
![img_0796](https://cloud.githubusercontent.com/assets/52704/15346284/68bc3cee-1cf1-11e6-82bf-9a4b2483c3ec.png)
![img_0797](https://cloud.githubusercontent.com/assets/52704/15346285/68c326f8-1cf1-11e6-907a-cfce4b202225.png)
![img_0798](https://cloud.githubusercontent.com/assets/52704/15346286/68c4457e-1cf1-11e6-9b2e-bd29425db0c2.png)
![img_0799](https://cloud.githubusercontent.com/assets/52704/15346287/68c88152-1cf1-11e6-9a23-40f2b6ff9e25.png)

**Comment by aanoaa** [comment]
계속해서 뒤로 미뤄져서 걱정입니다만, 다시 미루겠습니다.

**Comment by aanoaa** [comment]
LG U+ 의 휴대폰 본인 확인 서비스 이용약관 입니다.

https://www.uplus.co.kr/css/rfrm/prvs/RetrieveUbDnUseTermsPop_7.hpi

> 제 12조 (개인정보의 처리)
> 1. 회사는 서비스 제공을 위하여 수집된 본인확인정보의 취급 및 관리 등의 업무를 스스로 수행함을 원칙으로 하나, 필요한 경우 아래 표와 같이 회사가 선정한 사업자에게 위탁할 수 있습니다.

해서 몇개의 업체 목록이 나와 있습니다.

직접 통신사의 서비스를 이용하는 방안은 모르겠고,

아래는 LG U+ 의 본인확인 서비스 안내 주소입니다.

http://www.uplus.co.kr/css/pord/cosv/cosv/RetrievePsMbSDmsgInfo.hpi?catgCd=50901&prodCdKey=Z100001128

처음 생각했던 사용자의 입력을 wrapping 해서 우아하게 처리하기는 힘들 것 같고,
LG U+ 의 팝업창을 띄우고 이를 대행해서 결과를 받는 식으로 활용할 수 있을 것 같습니다.

그전에 서비스 가입 신청을 하기 위해서

![screenshot-www uplus co kr 2016-07-04 15-22-18](https://cloud.githubusercontent.com/assets/170528/16552340/358642c8-41fb-11e6-9aa2-ad589b7daa9e.png)


몇가지 서류를 제출해야 합니다.

**Comment by aanoaa** [comment]
우선

http://www.uplus.co.kr/css/pord/cosv/cosv/RetrievePsMbSDmsgInfo.hpi?catgCd=50901&prodCdKey=Z100001128

를 참고해서 서비스 가입해야 합니다.

그 이후에 매뉴얼등을 참고해서 어떻게 진행해야 할지 연구해야 합니다.
사용방법을 파악하고 난 다음에 실제 서비스에 붙여서 사용할 수 있을 것 같습니다.

**Comment by aanoaa** [comment]
위는 법인고객의 본인인증 서비스에 대한 내용일 수 있습니다.
좀 더 확인해 보도록 하겠습니다.

**Comment by aanoaa** [comment]
제가 찾던 인증대행에 관련된 내용이 아닙니다.

이용자에 대한 안내 입니다.
이용자는 대행사를 이용해서 본인인증을 할 수 있고 이것이 무료라는 뜻 인듯.

- 이용자가 개인일때
- 이용자가 법인명의 휴대폰일때

'이렇게 나뉘어서 설명하고 있고 법인명의 휴대폰의 경우 별도의 서비스 가입 신청을 해야지
본인인증을 할 수 있다.' 라는 안내입니다.

> ※ 본인확인 인증 창은 인증 대행사에 따라 디자인이 조금씩 다르지만 입력하는 정보는 동일합니다.

@10001if 서비스에 가입할 필요 없습니다.

**Comment by 10001if** [comment]
@aanoaa 네~ 알겠습니다~

**Comment by yongbin** [comment]
FYI

지난주 아임포트 미팅때 아임포트에 본인인증관련 모듈이 추가되었다는 이야기를 들어서 공유합니다. 현재 우리가 원하는 디자인을 수정할 수 있는 수준은 아니지만 도입했을때 이점이 있을지 고려해볼 필요가 있습니다.

https://github.com/iamport/iamport-manual/tree/master/SMS%EB%B3%B8%EC%9D%B8%EC%9D%B8%EC%A6%9D

**Comment by 10001if** [comment]
필요한 말인지는 모르겠지만, 몇 일 전에 서류가 도착해서 우선 말씀드립니다. 에이치엔한국사이버결제와 맺은 본인확인서비스 이용 계약서가 도착했습니다. 계약서 작성일은 2016년 7월 25일인데, 몇 일 전에 도착했더라구요. 혹시 몰라 남겨놓습니다.

**Comment by 10001if** [comment]
이슈 닫고 다시 필요할 때 열도록 하겠습니다.
