### ISSUE TITLE
새옷 등록시 폐기할 의류도 가상의 바코드로 등록하도록 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#737]
기존에는 사용할 의류만 바코드를 만들어 붙였는데, 앞으로는 사용하지 않을 의류에도 바코드를 붙이고 입력을 완료한 뒤 폐기처리하고 모든 의류의 기증 기록을 남기려고 합니다. 구체적으로 필요한 내용을 다시 정리해서 올리겠습니다.

**Comment by aanoaa** [comment]
https://github.com/opencloset/donation/issues/6

여기에서 페기되는 의류에 대한 바코드를 자동발급하도록 하였습니다.
@10001if 폐기되는 의류에 대해서도 바코드를 등록하실 건가요?

읽어보시고 닫아주시거나 코멘트 남겨주세요.

**Comment by 10001if** [comment]
@aanoaa 제가 설명이 미진했던 것 같습니다. 구현해 주신 것처럼 자동으로 발급되면 됩니다. 의류에는 바코드를 등록하지 않을 것입니다. 이슈 닫도록 하겠습니다. ^^
