### ISSUE TITLE
불필요한 서버에서의 작업

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#738]
필요/불필요는 모르겠지만 이런일이 없으면 좋겠습니다.

```
opencloset@opencloset1:~$ pwd
/home/opencloset
opencloset@opencloset1:~$ ll
total 40
drwxr-xr-x  3 opencloset opencloset 4096 Dec 22  2014 backup
drwxr-xr-x  2 opencloset opencloset 4096 Dec 17  2014 cache
-rw-r--r--  1 opencloset opencloset   18 Dec 10 07:22 dump.rdb
drwxrwxr-x  2 yongbin    yongbin    4096 Nov 15 12:41 lnav-0.8.0
-rw-r--r--  1 opencloset opencloset 9802 Jun  1  2015 npm-debug.log
drwxr-xr-x 13 opencloset opencloset 4096 Feb 26 13:49 service
drwxr-xr-x  3 opencloset opencloset 4096 Jan 26 18:43 tmp
drwxr-xr-x  5 opencloset opencloset 4096 Dec  5  2014 ubic
```

**Comment by yongbin** [comment]
불피요한 파일이 아닙니다. lnav는 서버에서 로그 모니터링을 위한 실행파일이고 debian 패키지가 존재하지 않기떄문에 바이너리가 필요하기 때문에 복사했습니다.

**Comment by aanoaa** [comment]
로그 모니터링을 어떻게 하나요?

처음보는 디렉토리가 다른 owner 로 만들어져 있는 상황인데, 앞으로도 이런거는 필요하려니 해서 넘어가나요?

**Comment by yongbin** [comment]
```sh
lnav-0.8.0/lnav service/monitor.theopencloset.net/
```

이렇게 사용하시면 됩니다. owner는 변경했습니다.

**Comment by aanoaa** [comment]
서버에 무슨 파일이 어떻게 있던 상관하지 않겠습니다.

**Comment by yongbin** [comment]
예전에 서버의 공용계정(aka `opencloset`) 홈디렉토리를 깨끗하게 유지해줬으면 좋겠다고 말씀하신적이 있는데, 제가 이를 무시하고 별도 상의 없이 부주의하게 파일을 서버에 올려서 불쾌하게 해드렸습니다. 죄송합니다. 현재 해당 디렉토리는 삭제했고 별도로 `~/opencloset/bin` 디렉토리 하부에 위치시킨뒤 `~/.bashrc` 에서 PATH 로 연결해서 사용할 수 있도록 설정해두었습니다. 향후 이런일이 반복되지 않도록 공용계정에 발생하는 변경에 대해서는 꼭 사전에 미리 상의하도록 하겠습니다.
