### ISSUE TITLE
내가 뭘 잘못했나보다

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#744]
배포를 하지 말걸

**Comment by yongbin** [comment]
https://github.com/opencloset/opencloset/pull/734 에서 배포하고나면 모니터링하겠다고 말씀드렸고 모니터링에서 발생된 사항들을 알려드리는겁니다. 왜이렇게 예민하게 반응하시는지 솔직히 잘 모르겟네요

**Comment by aanoaa** [comment]
이상한 이슈가 왜 자꾸 올라오는지 모르겠네요.

**Comment by aanoaa** [comment]
이슈 막올려도 되는 거 같아서 막 한번 올려봤습니다.

**Comment by yongbin** [comment]
확인이 필요한걸 나눠서 이슈올리는게 뭐가 문제인가요? 이슈없으면 닫으면 그뿐인데 저희가 이슈등록하는게 규칙이 있는것도 아니고 단지 커뮤니케이션 수단으로 사용한거 뿐인데

**Comment by aanoaa** [comment]
문제 없습니다
계속 그렇게 해주십쇼

**Comment by yongbin** [comment]
개인적으로 관심이 있던 구글 딥마인드 알파고 vs 이세돌 이벤트에 너무 심취한 나머지 이벤트기간(약 일주일)동안 팀에서 진행하나는 일에 집중하지 못했습니다. 그 사이에 코드구조를 변경하는 이슈(#734)도 있었고 그 이슈에 대해 형석님께서 별도로 도움을 요청하시기도 했었지만 딥마인드 이벤트와 저의 개인적인 일정들이 겹치면서 솔직히 그렇게 많은 시간을 할애해서 테스트를 못했습니다. 이 부분은 제가 시간을 잘 관리하지 못했기 때문에 생긴문제로 제 책임입니다. 죄송합니다.생각해보면  이 이슈가 발생하게된 근본원인(저의 모니터링 및 이슈과다 등록) 역시 같은 연장선상에서 이벤트가 끝나고 실서버 배포가 된다고 하는 상황인데 제가 그동안 너무 테스트에 기여한 부분이 없었기때문에 만회해야하겠다는 생각으로 의욕적으로 진행을 하다가 서버에 모니터링을 위한 파일을 설치하는 문제(#738) 나 다수의 invalid한 이슈를 등록하는 문제(#739, #742, #743) 들을 야기했고 이런 부분들이 총체적으로 형석님 기분을 상하게 해드린것 같습니다. 그리고 당시에는 형석님 반응에 대해서 방어적으로 반응했기때문에 위에 코맨트같은 반응을 했던것 같습니다. 근본적으로 제가 좀 더 같이 일하는 사람으로서 신뢰를 받는것이 먼저인데 그런부분에 많이 부족했기때문에 발생한 문제이고 제 책임이 더 큰 이슈인것 같습니다. 시간을 좀 더 잘 관리하고 스스로 좋은 상태를 유지할 수 있도록 좀 더 노력해서 같이 문제를 해결하는데 도움이 될 수 있도록 노력하겠습니다.

**Comment by aanoaa** [comment]
남을 배려하지 않고 제멋대로 행동한다고 느껴서였던 것 같습니다.
그게 맘에 안든다고 사사건건 재수없게 굴었습니다. 죄송합니다.

삐뚤어져서 태도가 냉소적으로 변하면 문제를 해결하려기 보다 내버려두는 나쁜 버릇도 있습니다.
