### ISSUE TITLE
테스트 서버 구축

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#754]
배포가 되기 전에 열린옷장 staff 들이 마음껏 기능을 테스트해볼 수 있는 공간이 필요합니다.
돌아가고 있는 서비스가 여러개이지만 그래도 필요합니다.

**Comment by aanoaa** [comment]
실제 대여자의 주문서를 가지고 테스트하게 될텐데,
그렇게 되면 SMS가 발송되어서는 아니됩니다.

**Comment by keedi** [comment]
어찌 될지는 모르겠지만 테스트 서버 구축 관련해서는 공개 이슈 트래커에 적기 어려운 부분도 많을 수 있으므로 다른 곳에서 논의하는 것이 적절할 수 있습니다. 테스트 서버 구축 자체에는 찬성입니다.

**Comment by yongbin** [comment]
내부 이슈트래커에 이슈 열었습니다. 이슈 번호 : 904
