### ISSUE TITLE
직원예약을 할 수 없음

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#755]
직원예약예약 화면에서 `999` 로 시작하는 번호일때에 SMS 전송실패에 관련된 메세지와 함께
예약을 할 수 없습니다.

핸드폰이 없으신 분들을 구별하기 위해서 `999` 로 시작하도록 부탁받았다고 합니다.

**Comment by aanoaa** [comment]
이게 갑자기 안된게 아니라 꽤 오래전부터 안되었을 것 같은데요.

`999` 로 시작하는 번호를 입력했다면 직원예약이 안되었을 것 같습니다.
2014년도부터요.

대신 예약해주는 경우는 종종 발생했지만 휴대폰이 없는 분을 대신 예약 하는 건이 극히 드물어서
이제 발견된게 아닌가 싶습니다.

**Comment by aanoaa** [comment]
if /^999/.test( phone )

로 시작하는 부분이 더 있었습니다.
아직 제대로 수정되지 않았습니다.

**Comment by 10001if** [comment]
아직 수정이 되지 않아 확인요망 라벨을 제거하지 못하였습니다~

**Comment by 10001if** [comment]
확인 하였습니다. ^^
