### ISSUE TITLE
대여중 상태인 의류가 대여됨

### ISSUE THREAD

**Issue by MoDoLEE** [opencloset/opencloset#757]
![image](https://cloud.githubusercontent.com/assets/14110661/13866567/16299df4-ecfa-11e5-8dfa-c65524d44c62.png)

J0PP/P0XW 의류에 대한 오류

3/12 이준만님이 대여
택배로 의류 발송했음
정상 반납 처리 되었다고 문자를 받았다고 함

3/17일 이영균님이 대여
현재 대여 중

현재 상태는 두 주문서에서 모두 대여중으로 표시 됨
첫화면에서 해당 의류 바코드를 검색하면
이영균님이 더 최신 주문서임에도 불구하고, 이준만님의 주문서를 보여줌

**Comment by aanoaa** [comment]
> 3/12 이준만님이 대여
택배로 의류 발송했음
정상 반납 처리 되었다고 문자를 받았다고 함

반납 문자를 보낸 이력이 없습니다.

**Comment by aanoaa** [comment]
시스템상에서 반납처리 되지 않은 의류의 상태를 대여가능으로 변경하는 것이 가능한가요?

**Comment by aanoaa** [comment]
이 이슈에 관련된 건 아닌데, 한가지 부탁드리고 싶은건,
이곳은 public 한 공간이기 때문에, 개인정보 노출이 우려될 경우에는
다른 채널을 통해 말씀해주세요

@10001if @MoDoLEE 이 점을 염두해주세요.

**Comment by aanoaa** [comment]
이 이슈에서는 고객의 이름이 나와있습니다.
주문서 번호로 다루어졌다면 노출되지 않았을 것 입니다.

**Comment by aanoaa** [comment]
문제를 추측해보면, 고객은 전주문서를 택배를 통해 반납했지만 실제
반납처리는 되지 않았습니다.
그럼 여전히 의류는 `대여중` 상태이기 때문에 정상정인 반납절차를 거치지
않고서는 `대여가능` 으로 변경할 수 없습니다.

그런데 후주문서에 `대여중`인 의류가 대여가 되었습니다.

어떻게 그게 가능했을까? 를 우선 찾아봐야 합니다.

**Comment by aanoaa** [comment]
후주문서의 담당자는 윈도우즈 플랫폼에서 firefox 를 사용한 것으로 보입니다.

    Mozilla/5.0 (Windows NT 6.1; rv:44.0) Gecko/20100101 Firefox/44.0
    Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36

**Comment by aanoaa** [comment]
Fri, 18 Mar 2016 17:36:44 +0900 즈음해서 전주문서를 반납처리 하였습니다.

**Comment by aanoaa** [comment]
반납처리 하지 않았던 전주문서를 반납해서 추가적인 이슈는 없습니다.

반납된 의류를 반납처리를 해야..

하지만

> 그런데 후주문서에 대여중인 의류가 대여가 되었습니다.
> 어떻게 그게 가능했을까? 를 우선 찾아봐야 합니다.

이건 의문입니다.

**Comment by 10001if** [comment]
@aanoaa 개인정보 노출에 더 신경 쓰도록 하겠습니다~ ^^

**Comment by MoDoLEE** [comment]
@aanoaa 앞으로 더 신경 쓰겠습니다! ^^

**Comment by aanoaa** [comment]
음 탐구생활을 더 해봐야 알겠지만 재현하기가 어렵습니다.
재발하면 살펴보겠습니다.
