### ISSUE TITLE
반납완료 SMS enable/disable 체크박스

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#758]
장기간 미반납건이라던지, 어떠한 사유에 의해 미반납된 의류를 처리하기
위해서 `대여중` 인 의류의 상태를 변경하기 위해서 반납되지 않았지만
반납처리를 하는 경우가 있습니다.

이때 반납하지 않았지만 고개에게 반납완료 문자가 전송됩니다.
이럴때를 대비하기 위해 체크박스를 둬서 특별한 경우에는 문자가 전송되지
않도록 할 수 있어야 합니다.

**Comment by 10001if** [comment]
감사합니다! 확인 완료하였습니다. ^^ 라벨은 내일 팀원들과 공유 후에 제거하겠습니다.
