### ISSUE TITLE
부분반납했는데 하위주문서가 두개 생성됨

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#760]
벨트를 안가지고 와서 부분반납 했는데, 하위 주문서가 두개 생겼음

https://staff.theopencloset.net/order/24948

**Comment by MoDoLEE** [comment]
동일 현상 또 발생했습니다.
주문서 번호 26372

**Comment by aanoaa** [comment]
추측인데,
서버가 잠시 내려간 사이에 부분반납이 되어서(delayed reponse)
두번 처리가 되었거나..

더 알아보겠습니다.

**Comment by MoDoLEE** [comment]
같은 증상입니다. 주문서 26501

**Comment by aanoaa** [comment]
더블클릭이 원인이 아닌가 싶습니다.
버튼을 누르고 진행중인 상태에서 한번 더 누르는 거죠.

문제가 발견된 3개의 주문서 모두 상위주문서(origin)를 보면 연장료가 두번 입력된 것을 볼 수 있습니다.

부분반납중에 다시 부분반납버튼을 누를 수 없도록 패치해야 합니다.

**Comment by aanoaa** [comment]
이미 두개의 하위주문서가 생성된 주문은 staff 의 역량껏 해결해주시기를 바랍니다.
둘중 하나만 반납처리 하고 나머지 주문서는 무시하셔도 무방할 것 같습니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
