### ISSUE TITLE
주문서 또는 대여절차에서 입고가는 사람에 대한 상태를 변경

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#761]
대여에 관련된 열린옷장의 대여프로세스가 변경되었기 때문에
어딘가에 적절하게 변경할 수 있도록 해야 합니다.

**Comment by aanoaa** [comment]
지금은 `대여` 메뉴의 목록중에 `입고감` 버튼을 눌러서 입고가는 사람의 상태를 변경하고 있습니다
이 기능이 어디에 옮겨져야 할까요?

**Comment by 10001if** [comment]
이 기능은 사용자 화면에서 나타나야 합니다. 방문시 사이즈를 측정하는 인원이 착용일자와 품목등 상세 내용을 확인하고 사이즈를 측정하는데 그 때 확인하도록 하려고 합니다. 다만, 사이즈 측정 이후 입고 가겠다고 이야기 할 수 있으니 그 건은 이슈가 크지 않을 것 같아 우선 이렇게 적용하고 추가 이슈가 발생하면 다시 이야기 드리도록 하겠습니다. 
![2016-04-13 1 43 47](https://cloud.githubusercontent.com/assets/4696328/14483082/282613aa-017e-11e6-89b9-de5682871176.png)

**Comment by aanoaa** [comment]
사용자가 아닌 주문서별로 착용여부를 표시하고 있긴한데..

오늘 방문예약을 한 사용자에 한해서 착용여부를 주문서에 업데이트 하도록 할 수는 있습니다.

오늘 날짜로 방문예약을 하지 않은 사용자는 착용여부가 안보일거고,
오늘 날짜로 방문예약 한 사용자는 착용여부가 보이고 수정도 가능하고 이런식으로요

**Comment by aanoaa** [comment]
사용자 정보에 당일 방문예약여부에 따라 착용여부를 기록할 수 있도록 하였습니다.

**Comment by 10001if** [comment]
@aanoaa 착용여부를 기록하는 란이 어디에 있는지 잘 모르겠습니다. 나중에 알려주시면 감사하겠습니다. ^^

**Comment by 10001if** [comment]
확인하였습니다. ^^;;
