### ISSUE TITLE
포장 시 대여 희망 항목과 실제 포장 항목이 다를 경우 확인할 수 있게 함

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#762]
일단 어떻게 비교해서 보여줄 수 있을 지에 대한 아이디어가 필요합니다.

**Comment by aanoaa** [comment]
어디서 어떻게 비교를 할 것인가..

**Comment by aanoaa** [comment]
일단 asignee 를 바꿔놓겠습니다.
다른 이슈를 처리하고 제가 처리할 여력이 된다면 다시 가져오겠습니다.

**Comment by 10001if** [comment]
@aanoaa 저도 아이디어가 생기면 적도록 하겠습니다.

**Comment by aanoaa** [comment]
pre_category 와 실제 대여하는 의류의 category 를 비교해서
꼭 맞지 않으면 확인하라는 경고창을 띄우는 정도로 생각하고 있습니다.

**Comment by keedi** [comment]
선택한 항목을 대여합니다를 클릭했을때 포장 완료가 되는데 이 시점에 pre_category 항목과 확인해서 꼭 맞지 않으면 경고를 보여주는 기능이 필요합니다. 이는 포장할 때 실수가 잦기 때문에 본 기능을 구현할 경우 최대한 실수를 줄일 수 있다고 합니다.

**Comment by keedi** [comment]
급한 이슈가 아니므로 제가 진행합니다.

**Comment by keedi** [comment]
@10001if 관련해서는 저랑 논의하시죠.

**Comment by keedi** [comment]
진행합니다.

**Comment by keedi** [comment]
단순히 경고창을 띄울 뿐만 아니라 해당 대여자가 누군지는 물론 최초 원했던 항목을 보여주고, 현재 선택한 항목을 비교해주어야 합니다. 더불어 확인 후 계속 진행하게 할지 아니면 그만 진행하게 할지 선택할 수 있는 UI도 필요합니다. 계속 진행할 경우 기존의 포장 완료 상태가 되면 되고 진행하지 않을 경우 이전 화면으로 가는데 이때 바코드로 찍은 의류 목록은 그대로 두고 담당자가 선택한 대여자는 목록은 남아있되 선택은 지워져야 한다고 합니다.

**Comment by keedi** [comment]
작업 중인 시안은 다음과 같습니다.

![screenshot-monster silex kr 10301 2016-06-07 17-38-19](https://cloud.githubusercontent.com/assets/138451/15851337/4cdf1046-2cd7-11e6-9806-bdd5e414a735.png)

**Comment by keedi** [comment]
@10001if 상기 화면을 보시고 피드백 부탁드립니다.

- 문구
- 글자 크기나 색깔 등
- 기타 등등

**Comment by 10001if** [comment]
![2016-06-08 2 40 23](https://cloud.githubusercontent.com/assets/4696328/15883843/f3546110-2d86-11e6-9bce-e9f65d767439.png)
문구, 글자 크기 색깔은 모두 좋다고 하구요. 다만, 대여희망품목과 포장항목을 비교할 때 더 쉽게 확인하기 위해 이상의 표현방식으로 표시가 된다면 더 좋을 것 같습니다. 포장품목 중 빨간색은 빠져 있어 부족한 것을 의미하며, 파란색은 대여희망품목 중 포장항목이 더 추가되어 있는 상황을 말합니다.

**Comment by 10001if** [comment]
![2016-06-08 3 27 34](https://cloud.githubusercontent.com/assets/4696328/15884748/9107a7a4-2d8d-11e6-9f04-4a010f898b15.png)

`자켓` `바지` `치마` `셔츠` `블라우스` `구두` `타이` `벨트` `원피스` `코트` 순으로 순서 조정을 요청드립니다.
그리고 여러개의 품목을 대여하는 경우 그 수량이 맞지 않으면 초록색으로 표시해주시길 요청드립니다. 초록색 표시는 복수의 품목을 대여할 때 수량이 맞지 않는 것이라고 이해하도록 하겠습니다.

**Comment by aanoaa** [comment]
처음 아이디어처럼 알림정도로 사용헤보는것도 좋지 않을까요?
데여품목과 포장품목이 다를떼 다시한번 확인하는 용도로..

부족하면 그떼 게선을 하는 방향으로 하면..?
라는 재 셍각이었습니다.

**Comment by keedi** [comment]
@aanoaa ;;; 일부러 맞춤법을 틀릴 필요는...

**Comment by keedi** [comment]
@10001if & @aanoaa 논의해보시고 정리해주세요.

**Comment by aanoaa** [comment]
재 의견데로 진헹하기로 헸습니다.

**Comment by aanoaa** [comment]
https://github.com/opencloset/monitor/issues/94#issuecomment-223537135

이거 떼문애 몇일간만..

**Comment by keedi** [comment]
채팅은 모르겠는데 이슈 트래커는 좀 아닌듯합니다.

**Comment by aanoaa** [comment]
저도 고통스럽지만 그가 와서 볼떼까지만..
오늘만..

**Comment by keedi** [comment]
상기 추가 의견은 적용하지 않기로 했습니다. 1차 버전의 화면 캡쳐 기준으로 피드백을 받는 수준으로 진행합니다.

**Comment by keedi** [comment]
피드백 받은 최종 화면은 다음과 같습니다.

대여 희망 항목과 실제 포장 항목이 같은 경우입니다.
![screenshot-monster silex kr 10301 2016-06-08 17-13-46](https://cloud.githubusercontent.com/assets/138451/15887328/9c86099a-2d9c-11e6-82c4-a48f569e6868.png)

대여 희망 항목과 실제 포장 항목이 다른 경우입니다.
![screenshot-monster silex kr 10301 2016-06-08 17-14-12](https://cloud.githubusercontent.com/assets/138451/15887332/a07e1d1c-2d9c-11e6-8051-f2795ffe9ba2.png)

**Comment by keedi** [comment]
동작하는 방식은 다음과 같습니다.

- 기존 **선택한 항목을 대여합니다** 버튼을 클릭시 추가적인 모달이 나오도록 함
- 모달에서 대여 희망 항목과 실제 포장 항목을 비교해서 적절한 메시지를 출력함
- 모달에서 **대여 진행** 버튼을 클릭시 기존과 동일하게 동작하고 **대여 취소** 버튼을 클릭시 더 이상 대여를 진행하지 않도록 함

**Comment by keedi** [comment]
구현은 완료되었으나 제대로 동작하는지 조금 더 테스트해보고 머지하겠습니다.

**Comment by keedi** [comment]
테스트 해보았는데 로컬 서버 기준으로는 일단 동작에 문제가 없습니다. 머지 진행하겠습니다.
