### ISSUE TITLE
하위 주문서의 연장료 계산 오류

### ISSUE THREAD

**Issue by MoDoLEE** [opencloset/opencloset#771]
이미 연장이 된 상태에서 부분 반납을 할 경우 상위 주문서에서 이미 부과된 연장료가 하위 주문서까지 그대로 따라 옵니다.

예를 들어 `24624` 주문서의 경우 8일 연장을 해서 `30,000 * 20% * 8 = 48,000원`의 연장료를 상위 주문서에서 미납으로 처리했습니다. 이 후에 자켓, 치마를 더 사용해야 된다고 하여, 나머지 품목은 부분 반납 처리하고 자켓, 치마만 하위 주문서(`25295`)로 빠졌습니다.
이 때 상위 주문서의 연장료 48,000원에는 자켓, 치마의 8일 연장료 `20,000 * 20% * 8 = 32,000원`이 이미 포함되어 있는 것인데, 이것이 그대로 하위 주문서에 넘어와서, 하위 주문서 생성 시에 이미 연장료 32,000원이 기본으로 세팅됩니다.

제 생각에는 상위 주문서에서 부분 반납 시 연장료를 1차 정산하는 것이므로, 하위 주문서의 연장료는 0원으로 초기화 시키는게 맞는것 같습니다.
그래서 나머지 항목에 대해서 하위 주문서가 생각된 시점부터 다시 연장료 계산이 되어야 합니다.

**Comment by MoDoLEE** [comment]
현재는 하위주문서의 반납 예정일을 상위주문서가 반납 처리된 날의 날짜로 변경하여 처리하고 있습니다.

**Comment by 10001if** [comment]
@MoDoLEE 나중에 저한테 설명 한번 부탁드릴게요~ ^^

**Comment by 10001if** [comment]
@MoDoLEE 현재도 동일하게 문제가 발생하고 있나요?

**Comment by 10001if** [comment]
우선 이슈 닫고 필요하면 다시 열겠습니다.
