### ISSUE TITLE
대여자의 신체사이즈를 문자 메세지로 전송하는 기능

### ISSUE THREAD

**Issue by MoDoLEE** [opencloset/opencloset#773]
대여자가 신체사이즈를 요구할 경우 현재는 사진을 찍어 가시거나,
신체 사이즈를 복사하여 평균 사이즈를 제거한 후 문자 메세지로 전송하고 있습니다.

이것을 사용자 정보 페이지에 들어가서, `SMS보내기`, `메일보내기`, `의류 검색`이 있는 부분에
`신체 사이즈 전송` 버튼을 추가(또는 `메일 보내기` 기능을 사용하지 않으니 교체)하여

**[열린옷장] 000님의 신체사이즈
키 000cm
몸무게 00kg
가슴둘레 00cm
.
.
.
발크기 00mm**

와 같이 대여자의 신체사이즈를 바로 문자로 전송할 수 있게 해주셨으면 합니다.

**Comment by aanoaa** [comment]
성별에 따라서 달라지는 부분도 있을 겁니다.
윗배둘레 이런거는 일반적인 사이즈가 아니기도 합니다.

몇가지를 선별해서 보내주나요 아니면 측정되지 않은 모든 신체 치수를 보내주나요?

- [ ] height 키
- [ ] weight 몸무게
- [ ] neck 목둘레
- [ ] bust 가슴둘레
- [ ] waist 허리둘레
- [ ] hip 엉덩이둘레
- [ ] topbelly 윗배둘레
- [ ] belly 배둘레
- [ ] thigh 허벅지 둘레
- [ ] arm 팔길이
- [ ] leg 다리길이
- [ ] knee 무릎길이
- [ ] foot 발크기
- [ ] pants 바지길이
- [ ] skirt 스커트 길이

**Comment by aanoaa** [comment]
보내져야 하는 신체치수를 선택해주세요.

**Comment by 10001if** [comment]
@aanoaa 모든 항목을 보낼 필요는 없을 것 같구요. 아래 항목만 보내주세요.
 
> height 키
>  weight 몸무게
>  neck 목둘레
>  bust 가슴둘레
>  waist 허리둘레
>  hip 엉덩이둘레
>  belly 배꼽둘레
>  thigh 허벅지 둘레
>  arm 팔길이
>  leg 다리길이
>  knee 무릎길이
>  foot 발크기

그리고 이 항목만 보내주되, 측정되지 않은 사이즈는 보내지 않도록 하였으면 합니다. 
예시를 아래에 적어놓도록 하겠습니다.

<예>
[열린옷장] 000님의 신체사이즈
키 : 180cm
몸무게 : 73kg
목둘레 : 37cm
가슴둘레 : 97cm
허리둘레 : 84cm
엉덩이둘레 : 96cm
배꼽둘레 : 84cm
허벅지 둘레 : 57cm
팔길이 : 60cm
다리길이 : 100cm
무릎길이 : 52cm
발크기 : 270mm
본 사이즈는 열린옷장의 기준에 의해 측정된 사이즈입니다. 목적이나 상황에 따라 측정방법이 상이할 수 있으니 참고용으로 활용해 주시기 바랍니다. 감사합니다.

**Comment by aanoaa** [comment]
배꼽둘레는 어딘가여?
belly? topbelly?

**Comment by 10001if** [comment]
@aanoaa belly입니다~ belly는 배꼽둘레이고, topbelly는 윗배둘레입니다~ ^^

**Comment by 10001if** [comment]
확인하였습니다. ^^

**Comment by aanoaa** [comment]
- 윗배둘레
- 엉덩이둘레

도 추가해야 합니다.

**Comment by aanoaa** [comment]
`OpenCloset::Common v0.0.8` 이상의 버전이 필요합니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
