### ISSUE TITLE
반납 확인 메세지 문구 수정

### ISSUE THREAD

**Issue by MoDoLEE** [opencloset/opencloset#774]
000님이 반납하신 의류가 정상적으로 반납되었습니다. 감사합니다.
-> 000님의 의류가 정상적으로 반납되었습니다. 감사합니다.

**Comment by MoDoLEE** [comment]
제가 하려고 했는데, 수정이 안되네요. 해당 파일이 들어 있는 브랜치에 수정 권한이 없는건가요? ^^;;

**Comment by aanoaa** [comment]
https://github.com/orgs/opencloset/teams/dev

글세요. 쓰기 권한 있으신데..

**Comment by 10001if** [comment]
잘 수정되었을 것이라 생각합니다. ^^; 반납문자 확인 후 이상 있으면 다시 열도록 하겠습니다. 라벨은 내일 팀원들과 공유 후에 제거하겠습니다.
