### ISSUE TITLE
새 옷 등록시 자켓 입력란에 length를 추가

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#775]
새옷 등록시에 자켓 입력란에 length 추가를 요청드립니다~

**Comment by aanoaa** [comment]
`length` 는 신발일때는 발크기를 나타내고, 팬츠일때는 바지길이를 나타냅니다.
자켓일때는 뭔가요? 소매길이 인가요?

**Comment by yongbin** [comment]
이 length랑 cuff 가 관계가 있는건가요??

**Comment by aanoaa** [comment]
노 관계입니다.

**Comment by 10001if** [comment]
@aanoaa 자켓일 때는 총장이라고 알고 있습니다. 총장은 자켓의 전체 길이를 의미합니다. 총장의 사이즈를 입력하기 위해 본 이슈를 요청드렸습니다. ^^

**Comment by 10001if** [comment]
확인 하였습니다. ^^
