### ISSUE TITLE
검색 모델 업데이트

### ISSUE THREAD

**Issue by yongbin** [opencloset/opencloset#776]
#720 과 동일하게 2016년 3월 자료를 리뷰하고 모델에 반영해야합니다. @10001if

**Comment by yongbin** [comment]
## 원래 계획했던 작업

   - [ ] 데이터 검증 정례화 (매월 마지막주 주말마다 실행)
   - [ ] 이상치 자료 재확인
   - [ ] 현재 이상치를 찾아내는 조건을 세분화
	 - 성별, 의류의 종류별 조건을 추가할수 있도록 로직을 수정
	 - hard limit 이외에 boxplot에서 표시해주는 이상치도 확인할 수 있는 로직
       추가
	 - 단순한 제한 조건이외에 값들의 관계를 통해 추가적인 조건들을 추가 (ex:
       몸무게보다 키가 작은 사람들)
   - [ ] 현재 주문자료만 검증한것을 사용자, 의류의 원시자료에서 적용



## 추가 논의된 작업 

- [ ] #545 주문서에 추가된 ignore를 반영
- [ ] #545 과거 대여이록을 기준으로 한세트 이상 대여한 의류를 학습목록에서 제거
- [ ] 팔길이 성능

**Comment by yongbin** [comment]
https://github.com/opencloset/monitor/issues/94 이 진행되는 만큼 모델 업데이트도 진행해야합니다.

**Comment by yongbin** [comment]
진행하겠습니다

**Comment by yongbin** [comment]
## 여성의류의 팔길이 예측을 못함

![screenshot_2016-06-10_11_24_07](https://cloud.githubusercontent.com/assets/52704/15952715/57df020c-2efe-11e6-8798-f35cdc2b677c.png)

## 남성 과체중자의 가슴과 허리사이즈가 작게 추정됨

![screenshot_2016-06-10_11_24_12](https://cloud.githubusercontent.com/assets/52704/15952721/6b2b2926-2efe-11e6-8993-544c294ceb76.png)

**Comment by yongbin** [comment]
2016년 6월 12일자 열린옷장 DB로 부터 자료를 추출해서 총 92801건의 주문정보를 기초자료조 저장합니다. 이번 작업에서 DB 추출부분에서 다음과 같은 변경이 있었습니다.
 
 - e398a10 : #776-update-model Adjust trivial vertical alignment
 - c821882 : Add explicit order by 'order_id'
 - b5f1a6b : Add 'clothes_cuff'
 - a3c9337 : Add 'clothes_color'
 - 20df4d6 : Add 'ignore' column from `order`
 - f158867 : Exclude online orders and remove 'is_onlie' column
 - f6ad392 : Indent inner query statement

**Comment by yongbin** [comment]
> #545 과거 대여이록을 기준으로 한세트 이상 대여한 의류를 학습목록에서 제거

다음 쿼리를 통해서 기존 주문에서 아이템이 하나이상 대여된 모든 경우를 뽑아보면 1336건임을 알 수 있습니다. 이 자료들은 대리대여이거나 혹은 단체대여일 가능성이 있으므로 학습자료에서 제거하겠습니다.

```sql
SELECT  order_id
        ,`type`
        ,COUNT(*) AS 'cnt'
FROM
(
    SELECT  `order_id`
            ,SUBSTR(`clothes_code`,2,1) AS 'type'
    FROM    `order_detail`
    WHERE   `clothes_code` IS NOT NULL
) AS x
GROUP BY order_id, TYPE
HAVING `cnt` > 1
```

**Comment by yongbin** [comment]
1차 이상치 보고서를 @10001if 님께 보냈습니다. 이상치가 수정되면 자료를 갱신해야합니다.

**Comment by yongbin** [comment]
> 팔길이 성능

현재 의류의 팔길이는 단순하게 대여자의 팔길이와 키에 의해서 의해서 결정된다고 보고있습니다. 하지만 확인해본 결과 생각보다 대여자의 팔길이 대비 대여되는 옷의 팔길이의 변동폭이 넓습니다.

![rplot01](https://cloud.githubusercontent.com/assets/52704/15996341/7f449c3e-3161-11e6-89c1-9c6ca00ae8e8.png)

평균팔길이(60)이 대여한 의류의 팔길이 산점도

![rplot02](https://cloud.githubusercontent.com/assets/52704/15996353/92e7955c-3161-11e6-94ea-03dc83708e05.png)

키와 대여의류 팔길이의 상관

```
Call:
lm(formula = clothes_arm ~ arm)

Residuals:
     Min       1Q   Median       3Q      Max 
-14.4121  -1.2061   0.0392   1.1712   8.9443 

Coefficients:
             Estimate Std. Error t value Pr(>|t|)    
(Intercept) 39.058166   0.359071  108.78   <2e-16 ***
arm          0.377312   0.005951   63.41   <2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.836 on 12866 degrees of freedom
  (138 observations deleted due to missingness)
Multiple R-squared:  0.2381,	Adjusted R-squared:  0.238 
F-statistic:  4020 on 1 and 12866 DF,  p-value: < 2.2e-16
```
결과적으로 단순 회귀로 봤을때 `clothes_arm`을 추측하는데 `arm`의 결정개수는 0.238정도로 아주 낮습니다. 

대여되는 팔길이를 설명할수 있는 추가적인 새로운 변수(feature)를 추가해야합니다.

**Comment by 10001if** [comment]
의류의 자켓 총장 사이즈 범위는 50 ~ 90입니다. @yongbin

**Comment by yongbin** [comment]
허리둘레 상한 140

**Comment by yongbin** [comment]
엉덩이 상한 140

**Comment by yongbin** [comment]
배꼽 150

**Comment by yongbin** [comment]
기존 스크립트와 CSV 형태로 관리하던 ocarina의 소스를 R 패키지 형식으로 변경했습니다. 앞으로 모델업데이트에서 반영되는 `data`와 `parameter`는 R 패키지에 포함하는 `data/` 문법을 이용해서 배포합니다(http://r-pkgs.had.co.nz/data.html ) 

아울러 기존 서버에서 검색 세션 설치를 위해서 사용하던 스크립트 및 배포관련 작업들도 하나의 스크립트로 정리해서 자동화했습니다.

**Comment by yongbin** [comment]
```
./deploy.sh
* installing to library ‘/home/yongbin/R/x86_64-pc-linux-gnu-library/3.3’
* installing *source* package ‘ocarina’ ...
** R
** data
*** moving datasets to lazyload DB
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (ocarina)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   217    0   217    0     0      0      0 --:--:--  0:07:10 --:--:--    54 q
 qlrwxrwxrwx 1 root root 42  7월  1 19:20 /tmp/ocpu-www-data/tmp_library/ocarina -> /tmp/ocpu-www-data/tmp_library/x03d4b8e1e2
Session ID : x03d4b8e1e2
```
서버 배포 완료했으며, 검색기능 동작에 이상없음을 확인했습니다. 이슈닫습니다.
