### ISSUE TITLE
의류 검색 실패

### ISSUE THREAD

**Issue by yongbin** [opencloset/opencloset#777]
#740 의 변경으로 발생한 이슈로 보입니다. 현재 `사용자` -> `의류검색` 이 항상 실패합니다. 이 이슈는 staff 쪽 구현을 바꿔야 할지 https://github.com/opencloset/OpenCloset-Size-Guess-OpenCPU-RandomForest 쪽 return 을 변경해야할지 먼저 확인해야합니다.

**Comment by aanoaa** [comment]
#740 에서 진행합니다.
