### ISSUE TITLE
새 옷 등록시 바지 입력란에 밑단을 추가

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#779]
새 옷 등록시 바지의 경우에는 허리 둘레, 엉덩이 둘레, 허벅지 둘레, 기장 사이즈를 입력하고 있습니다. 여기에 밑단 둘레 항목을 추가하고자 합니다. 일반적으로 밑단은 인치 단위를 사용하여 7인치 8.25인치 처럼 사용하고 있습니다. 그래서 밑단 둘레는 인치 단위가 되었으면 합니다.

**Comment by aanoaa** [comment]
새옷등록은 `donation` 도메인에서 처리하더라도, 다른 의류의 크기와 마찬가지로 보여지는 건 물론이고, 수정가능해야합니다.

**Comment by aanoaa** [comment]
@10001if 소수점도 사용되나여?
왜 다른둘레는 전부 cm 인데 밑단만 inch 를 쓰시는건가여?

**Comment by aanoaa** [comment]
일반적인 쓰임새를 고려한다면 인치가 많이 사용되지만 열린옷장에서는 그럼에도 cm 를 사용하고 있습니다.
허리사이즈도 일반적으로 인치를 쓰지만 cm 로 기록하고 있습니다.

하고싶은말은 cm 써서 안되는게 아니면 cm 쓰자 입니다.

**Comment by aanoaa** [comment]
휴일이라서 허락을 받은 건 아니지만 `cm` 로 진행하겠습니다.
단위의 변경이 필요하다면 말씀해주세요.
변경하도록 하겠습니다.

**Comment by aanoaa** [comment]
대여과정(모니터)에서 웬지 밑단둘레가 보여져야 될 것 같은데..

**Comment by aanoaa** [comment]
배포에 앞서 OpenCloset-Schema-0.027 를 설치하고 `57-clothes-cuff.sql` 파일을 적용해야 합니다.

**Comment by 10001if** [comment]
@aanoaa 저도 cm를 쓰는게 맞다고 생각합니다. ^^ cm를 쓰도록 하겠습니다. 그리고 모니터화면에서는 의류 사이즈를 확인하는 란이 현재도 존재하지는 않는데요. 다만, 기존에 대여했던 의류정보가 마우스를 오버하면 나타납니다. 그 때 밑단 둘레가 표시되면 좋을 것 같습니다. ^^

**Comment by 10001if** [comment]
라벨은 내일 팀원들과 공유 후에 제거하겠습니다.

**Comment by 10001if** [comment]
@aanoaa 그리고 인치를 쓰는 이유는 수선업체에서 모두 인치를 사용하기 때문인데요. 사실 의류의 사이즈는 일반적으로 인치로 사용하고 있습니다. 저희가 센치를 쓰기로 하였으면 밑단도 통일되게 센치를 사용하는 것이 맞는 것 같습니다. 그런데 바지 밑단 둘레는 1단위로 상승하거나 하락하고 그 사이는 1/4 2/4 3/4 4/4 이렇게 4등분하여 관리합니다. 그러니까 바지단이 7이라면 7.25, 7.5, 7.75, 8 이렇게 진행되는데요. 이를 센치로 변환하면(오차는 조금 있지만) 18.5cm 19cm 19.5cm 20cm 으로 진행됩니다. 그래서 소수점이 필요합니다. 본 이슈는 내일 다시 설명드리도록 하겠습니다. ^^
