### ISSUE TITLE
대여 주문확정 후 발송되는 문자메시지에 이야기옷장 안내를 추가하고자 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#784]
https://github.com/opencloset/OpenCloset-Story-Web/issues/9 이슈입니다.
제 생각엔 이 저장소에서 처리하는 것이 옳은 것 같아, 이슈를 가져왔습니다. @aanoaa 보시고 처리 해주실 수 있는지 확인 부탁드립니다~

**Comment by 10001if** [comment]
기존에 발송되는 문자에

3.기증이야기 안내 : https://story.theopencloset.net/letters/o/22852/d 를 클릭하시어 오늘 대여하신 의류의 기증이야기를 만나보세요.

대여자에 맞는 URL이 추가로 발송되어야 합니다.

**Comment by aanoaa** [comment]
SMS를 보내는건 이곳이라서 이쪽에서 계속해서 진행하겠습니다.

    https://story.theopencloset.net/letters/o/:order_id/d

인 것 같습니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
