### ISSUE TITLE
volunteer에서 방문안함 상태로 캘린더에서 이름이 사라지도록 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#786]
https://github.com/opencloset/volunteer/issues/56 이슈입니다.

**Comment by aanoaa** [comment]
전에도 말씀드렸지만 가능하시다면 레퍼런스를 거꾸로 달아주세요.

**Comment by aanoaa** [comment]
그래야 여기 이슈 들어왔을때 열려있는지 닫혀있는지 바로 확인이 가능하기 땜시..

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
