### ISSUE TITLE
의류의 세트를 묶음으로 입력할 수 있는 UI

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#79]
자켓, 바지
자켓, 스커트
자켓, 바지1, 바지2
자켓, 바지, 베스트 

처럼 단품이 세트로 등록되어 세트로 인식할 수 있도록 입력을 할 수 있는 기능을 요청드립니다. 세트 확인은 향후 의류 관리시 공간 내에 세트를 동일한 위치에 보관하고, 기타(세탁, 수선) 상황 발생시 짝짝이로 떨어져 있는 의류들의 정렬을 위해 필요한 것입니다.

세트 확인과 상태(대여가능, 수선, 세탁) 확인의 기능만 있으면 될 것 같구요. 추가적으로 세트로 동작할 다른 이유는 없을 것 같습니다. :)

**Comment by 10001if** [comment]
의류 묶음 개념은 사용하지 않겠습니다.
세트만 처리할 수 있도록 확인 부탁드립니다.

**Comment by keedi** [comment]
진행합니다.

**Comment by 10001if** [comment]
감사합니다. :)

**Comment by keedi** [comment]
3차 오픈 이슈가 많은 관계로 아직 현재 항목의 경우 자세한 그림이나 방향이 나오지 않아 시간이 많이 소요될 것으로 보입니다. 일단 다음 마일스톤으로 넘기도록 합니다.

**Comment by keedi** [comment]
@10001if 
셋트 관련 어떤 페이지에서 어떤 식으로 사용하고 싶으신 건지를 세세하게 명시해주시면 작업을 진행하는데 도움될 것 같습니다.

**Comment by aanoaa** [comment]
우선순위가 높기 때문에 협의해서 진행해보도록 하겠습니다.

**Comment by aanoaa** [comment]
`Group` 이라는 테이블이 존재합니다.

무엇에 쓰이는지 자세히는 모르겠습니다.

유일하게 사용되는 곳이 새옷을 등록할때 입니다.
기증받은 옷을 등록했을때에 새로운 Group 을 만들고 해당 의류에 만들어진
group 의 id 를 부여합니다.

대략 등록된 옷이 8000 여벌인데, 만들어진 Group 은 4400 여개 입니다.

하나의 기증행위에 대해 같은 그룹으로 묶어주는 역할이 아닌가 합니다.

이를 활용한 기능은 없지만 새옷이 등록될때 이미 같이 묶어주고 있었습니다.

**Comment by aanoaa** [comment]
그럼 이것을 어떻게 활용할지는 @10001if 님이 생각해주셔야 합니다.

예로 https://staff.theopencloset.net/clothes/J0N6 와 같이 등록되었던
의류로는, https://staff.theopencloset.net/clothes/P0J7 이 있습니다.

**Comment by aanoaa** [comment]
group_id 가 없는 의류는 없는데, 이는 좀 당연합니다.
새로운 옷이 등록될때마다 새로운 그룹이 만들어지기 때문입니다.

같은 기증행위인데, 여기서 staff 의 실수로 인해 두번에 걸쳐서 의류가
등록되었다면 이를 수정할 수 있는 기능이 필요할 것 같습니다.

**Comment by aanoaa** [comment]
쟈켓 3벌, 바지 3벌이 한번의 기증행위에 포함된 경우에
6개의 의류가 같은 그룹으로 묶입니다.

이렇게 되면 위아래 셋트를 사용하기가 어렵습니다.

이를 해결해주어야 합니다.

**Comment by aanoaa** [comment]
쟈켓 - 팬츠간에는 한벌씩만 연결이 되어야 합니다.

    쟈켓A - 팬츠A (O)
    쟈켓B - 팬츠B (O)
    쟈켓A - 팬츠C (X)   # 쟈켓A 는 이미 팬츠A 와 짝임

**Comment by aanoaa** [comment]
1. 첫화면 의류검색에 대해 그룹의류를 보여준다
2. 의류정보에서 같은 그룹의류를 보여준다
3. 세트의류를 등록할 수 있도록 한다(의류정보에서 select 버튼처럼 연결)
4. 새옷 등록 완료후에 세트의류를 연결 할 수 있도록 한다.
5. 폐기되면 셋트의류를 삭제한다
6. 셋트의류가 없으면 의류코드로 등록 가능하도록 한다

**Comment by keedi** [comment]
남성의 경우 상의, 바지의 경우 한벌씩만 연결이라고 합니다. 하지만 이 경우 여전히 예외가 있을 것 같습니다. 왜냐면 정장을 주문(구입시)할 때 상의 한 벌에 바지 두 벌 이상을 맞추는 경우가 많은 것을 보았습니다. @10001if 님께서도 알고 계실 것 같은데... 여튼 이런 사람의 의류 기증이 들어온 경우 상의와 바지가 상의 1개에 바지 2개가 셋트로 들어올 수 있을 것 같네요.

여성의 경우 상의, 바지는 어떤 전략인지 모르겠습니다. 들었는데 기억이 안나는 것일 수 있습니다.

여성 상의, 치마의 경우 기증 내역과는 별개로 묶음으로 묶는다고 들었습니다. 아마도 남성 의류와는 달리 N:N 매치가 예상되구요.

**Comment by keedi** [comment]
일단 그룹 아이디는 처음에 기획했던 의도와 많이 달라진 부분도 있고 해서 등록 시점이외에는 전혀 사용하지 않고 있는 것이 사실입니다. 따라서 개념이 변하는 것 자체는 크게 상관없을 것 같구요.

**Comment by keedi** [comment]
묶음으로 입는 옷의 경우 @10001if 님의 확인이 필요한 부분이 또 있는데, 서로 묶음으로 연결된 옷의 경우 진짜, 정말로, 레알로(?) 크로스로 입을 수 있는지 부분입니다. 예를 들어 여성의류의 경우 상의 A, B, C와 치마 D, E, F그리고 바지 G, H가 묶음이라면 A,D / A,F / C,G 이런식으로 막 빼서 줘도 상관없는 것인지, 아니면 이 안에서도 안되는 조합이 있는 것인지 말입니다. 안되는 조합이 있다면 다시 좀 더 생각해봐야 합니다.

**Comment by keedi** [comment]
현재 의류는 단 하나의 그룹 아이디를 가집니다. 바로 앞의 커멘트 여부에 따라 하나의 그룹 아이디를 가져야 하는지 복수개의 그룹 아이디를 가져야 하는지가 나뉘어지기 때문입니다. 물론 이외에도 다른 복잡한 이슈가 있을 수도 있구요. 일단 생각나는 부분만 먼저 적어 놓습니다.

**Comment by keedi** [comment]
몇가지 이슈가 더 있는데, 서로 연결되서 비슷하긴합니다.

- 현재 group이 의미가 있는지 검토한 후 미세하게라도 의미가 있다면 살리고 그렇지 않다면 DB상에 폐기한다.
- 현재 group이 의미가 있고 살린다면 묶음으로 활용할지 아니면 다른 용도로 사용하는지 결정한다. 이 경우 group의 이름이 적절한지 아니면 묶음에게 group이라는 이름을 양도할지 결정한다.
- 묶음에 적절한 스키마를 고민한 후 추가하거나 group을 묶음에 맞게 사용한다.

**Comment by keedi** [comment]
묶음과 관련해서는 열린옷장 측의 최종 변론(?)을 들은 후 명세를 확실하게 정한 다음 DB 변경 및 UI 구현이 들어가면 좋을 것 같습니다.

**Comment by keedi** [comment]
어짜피 group테이블과 group_id는 아직까지 등록만 하고 있었지 사용하고 있진 않았으므로, @10001if 님과 논의 후 결정되시면 결정 내역 기록해주시고 그냥 진행하시면 될 것 같습니다.

대신 기존 의류 등록시 group을 생성하고 추가하고는 있으므로 이를 수정하거나 조정할 수 있는(관리자든, 열린옷장 직원이든) UI는 필요할 것 같습니다.(그것을 만드는 이슈니 당연하긴 하지만 ㅎ)

**Comment by keedi** [comment]
현재 기증 시점에 그룹을 만들기 때문에 마치 기증과 그룹 테이블이 엮인 것 같지만 아마도(그렇길 바라는데 아니라면 수정해야 할 부분이 있다는 의미) 전혀 관련없기 때문에 별로 상관없습니다. 확인 및 수정만 된다면 기증과 그룹을 엮을 이유는 딱히 없습니다. (전혀 별개라는 의미)

**Comment by aanoaa** [comment]
group 은 의미가 있습니다.
하나의 기증행위에 대해 관련된 의류를 묶어주는 역할을 합니다.

그리고 의류의 관계에 대해선 N:N 관계는 없습니다.
확인을 받았습니다. 1:1 입니다.

같은 셋트의류가 아님에도 빌려줄 수 있고 그렇게 하고 있긴 하지만,
그럼에도 상하의 셋트가 필요하다고 합니다.

경우에 따라서는 다른 기증행위에 들어온 의류를 묶어서 셋트로 할 수도
있습니다.

A 님으로부터 자켓A, 팬츠A 를 받았고,
B 님으로부터 팬츠B 를 받았는데, 팬츠A 가 폐기 된후에

자켓A 와 팬츠B 가 셋트가 될 수 있습니다.

--------------------------------

셋트의류의 관계를 담고있는 테이블이 필요할 것 같습니다.

    clothes_codeA | clothes_codeB
    -----------------------------

primary key 로는 clothes_codeA
clothes_codeB 는 unique key

group 과 관계없이 A 와 B 의 관계를 저장합니다.
어떠한 의류라도 1:1 관계를 맺을 수 있습니다.

**Comment by aanoaa** [comment]
table clothes
    ----------------------------------
    ... | code | relation_code(unique)
    ----------------------------------

처럼 하나의 컬럼이 추가되어도 될 것 같습니다.

**Comment by keedi** [comment]
> group 은 의미가 있습니다.
> 하나의 기증행위에 대해 관련된 의류를 묶어주는 역할을 합니다.

이건 상관없습니다. 어짜피 모든 옷마다 `donation_id`로 묶어주고 있습니다. 기증 행위와 그룹은 직접적으로는 연관이 없습니다. 다만 기증행위를 등록하는 새옷 등록시 기증행위도 생성하고 그룹도 생성하고 있죠. 다만 그룹이 기증행위 하부에 존재하는 것은 아닙니다. 기증행위는 기증행위, 그룹은 그룹입니다.

**Comment by keedi** [comment]
1:1이고 기증 행위와 상관없이 옷을 묶어줄수도 있다고 한다면 그냥 group 테이블 그대로 써도 될 것 같습니다. 기존 테이블에서 group정보는 모두 날리고(별 상관없을 것 같은데 아니라면 체크 바랍니다) group 별로 두개의 의류만 저장되도록 하면 될 것 같네요. 의류 테이블에는 category가 존재하고 더불어 의류 코드도 존재하기 때문에 상/하의는 물론 바지 치마를 구분하는 것은 별 문제 없을 것 같아요.

기존 코드에서 새 의류 등록 시점에 그룹 생성하고 그룹에 추가하는 컨트롤러와 js, template쪽만 제거하면 이후 불필요하게 그룹을 추가하는 기본 동작은 없어질 것 같습니다.

**Comment by aanoaa** [comment]
테이블 스키마를 변경하지 않고 테이블을 추가해서 해결하려 합니다.
(Group 을 변경하지 않고, Set 의류의 대한 정보를 기록할 수 있는 테이블 추가)

지금 해결하고자 하는 문제는(앞으로 어떻게 변경될지 고려하지 않고),
자켓과 팬츠, 자켓과 스커트의 연결입니다.

``` sql
DROP TABLE IF EXISTS `suit` ;
CREATE TABLE `suit` (
  `code_top`    CHAR(5) NOT NULL,
  `code_bottom` CHAR(5) NOT NULL,

  PRIMARY KEY (`code_top`),
  UNIQUE KEY  (`code_bottom`),

  CONSTRAINT `fk_suit1` FOREIGN KEY (`code_top`)    REFERENCES `clothes` (`code`) ON DELETE CASCADE,
  CONSTRAINT `fk_suit2` FOREIGN KEY (`code_bottom`) REFERENCES `clothes` (`code`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

"a suit" 의 의미는 위아래 한벌 입니다. 더 기억하기 쉽고 좋은 테이블
명이 필요합니다.

위아래 한벌을 나타내는 테이블에

윗옷에 대한 code 와 아래옷의 code 를 저장합니다.
각각은 유일해야 합니다.

한번에 한개씩만 연결될 수 있습니다.

자켓A 는 팬츠A 하고만 set 일 수 있습니다.
동시에 팬츠B 와 set 일 수 없습니다.

**Comment by aanoaa** [comment]
의류끼리 연결할 수 있는 기능이 추가되었습니다.
새옷 등록할때에 셋트의류를 연결해 줄 수 있는 기능이 필요합니다.

**Comment by 10001if** [comment]
@aanoaa 지난 번에 말씀드린 것처럼 실제 한번의 기증행위이지만, 수선, 세탁이나 바코드를 다는 이슈와 맞물려서 여러번 나눠 기증행위로 새 옷 등록을 한다고 합니다. 같은 기증자가 같은 날 기증을 한 것이라면 모두 "함께 기증된 의류"에 뜰 수 있도록 요청드립니다.

**Comment by aanoaa** [comment]
> @aanoaa 지난 번에 말씀드린 것처럼 실제 한번의 기증행위이지만, 수선, 세탁이나 바코드를 다는 이슈와 맞물려서 여러번 나눠 기증행위로 새 옷 등록을 한다고 합니다. 같은 기증자가 같은 날 기증을 한 것이라면 모두 "함께 기증된 의류"에 뜰 수 있도록 요청드립니다.

이건 다른 이슈입니다.
위아래 셋트의류를 입력하는 기능이 있기 전부터 새옷등록당 하나의 기증행위로 인식되고 있기 때문입니다.

**Comment by 10001if** [comment]
네! 그럼 다른 이슈로 등록해 놓도로 하겠습니다. ^^

**Comment by yongbin** [comment]
> 지금 해결하고자 하는 문제는(앞으로 어떻게 변경될지 고려하지 않고),
> 자켓과 팬츠, 자켓과 스커트의 연결입니다

@10001if 님과 논의해본결과 여성의 경우 블라우스와 스커트의 조합이 필요합니다. 이 이슈를 통해DB에서  `suit` 테이블을 통해서 1:1 연결하는 작업은 완료되었으니 우선 이 이슈는 종결하고 이후 파생되는 이슈는 별도로 열어서 진행하면 좋겠습니다.

**Comment by yongbin** [comment]
이 이슈는 처리방향에 따라서 https://github.com/opencloset/donation/issues/6 과 선행의존성이 있습니다. 처리방향을 논의하고 만약 의존성이 있다면 앞에 이슈를 먼저 처리합니다.

**Comment by yongbin** [comment]
현재 열린옷장에서 `세트의류`를 처리하는 구현은 총 3가지가 존재합니다. 

1. `Group` 테이블과 `Clothes`의 `group_id`를 이용한 1:1 연결방법
2. 본 이슈에서 처리한 `suit` 테이블과  `code_top`, `code_bottom` 를 이용한 1:1 연결방법
3. 의류검색에서 구현한 기존 대여기록을 기반으로 한 경험적인 연결방법 https://github.com/opencloset/opencloset/blob/develop/bin/opencloset.pl#L7138 

위 세가지 방법중에 2번째 방법이 전체에서 의류의 `세트` 개념을 처리하는 주된 방법으로 선택될 가능성이 높은 상황입니다. 다만 의류의 `세트` 의류의 검색및 추천과도 연결이 있기때문에 이후 관련기능을 구현할때 주의할 필요가 있습니다.

아울러 본 이슈에서 처리하고자 한 내용중 남은 사항은 기존 재고관리의 `new-clothes` 의 새옷등록과정중 동일한 `기증행위`에 들어온 다수의 의류들 중에서 새옷을 등록하는 행위와 세트를 묶는 행위를 같이 할수 있는 추가적인 UI를 구현하는 내용이었습니다. 하지만 논의결과 향후 기존 재고관리의 새옷등록과 독립된 별도의 새옷등록 프로세스를 개발할 계획  ( https://github.com/opencloset/donation/issues/6 ) 이기 본 이슈의 남은 작업은 본 저장소에서 진행하지 않고 신규 새옷등록프로세스에 포함시키지로 결정했습니다.

따라서 이 이슈는 닫고 v1.1.0 에서도 제거하도록 하겠습니다.
