### ISSUE TITLE
3회째 대여자 부터 대여자의 부담을 줄이기 위해 비용을 할인함

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#790]
대여 횟수가 많아질 수록 부담이 가중되는 것으로 판단하였습니다. 따라서 3회 부터 대여자의 대여금액을 50% 할인된 금액으로 대여하고자 합니다. 자세한 내용은 다시 서술하도록 하겠습니다.

**Comment by 10001if** [comment]
3회 대여부터는 원 대여 금액에서 50% 할인된 금액으로 대여를 제공하고자 합니다. 필요한 것은 다음과 같습니다.

1. 3회 이상 대여자에게는 주문서에서 50% 할인된 금액으로 결제를 할 수 있도록 자동 조정될 것
2. 결제 금액 우측에 `3회 이상`이라는 표시가 나타나도록 할 것
3. 취업날개 처럼 쿠폰을 통해 대여된 값은 빠지고 순수하게 열린옷장에 비용을 지불한 횟수만 체크가 되어 결제 횟수가 3회 이상일 경우에만 대여금액을 할인하도록 할 것.

**Comment by 10001if** [comment]
@aanoaa 품목에 대해서도 고민이 필요할 것 같습니다. 생각나는대로 다시 작성하도록 하겠습니다. ^^

**Comment by keedi** [comment]
쿠폰을 통해 대여된 값이 빠진다는 것이 무슨 의미인지요? 쿠폰을 통해 대여한 경우는 3회 대여 기준에서 제외한다는 의미이신지요? 더불어 이 경우 쿠폰을 통해 대여한 경우 제외한다고 할때 쿠폰을 쓰더라도 추가 금액이 있는 경우가 있는데 이 경우도 제외하는 것인지 쿠폰을 쓰더라도 추가 비용을 납부했다면 제외하지 않는지요?

**Comment by aanoaa** [comment]
쿠폰을 통해 대여했다고 할지라도 3회 이상 이용자에게 혜택을 주는 건 좋은 취지 같습니다.
복잡성을 줄이는데도 도움이 되고요.

**Comment by 10001if** [comment]
>쿠폰을 통해 대여된 값이 빠진다는 것이 무슨 의미인지요? 쿠폰을 통해 대여한 경우는 3회 대여 기준에서 제외한다는 의미이신지요? 
-> 네. 쿠폰을 통해 대여한 경우는 대여횟수로 계산하지 않는 다는 뜻입니다.

>더불어 이 경우 쿠폰을 통해 대여한 경우 제외한다고 할때 쿠폰을 쓰더라도 추가 금액이 있는 경우가 있는데 이 경우도 제외하는 것인지 쿠폰을 쓰더라도 추가 비용을 납부했다면 제외하지 않는지요?
->쿠폰을 사용했다면 추가비용이 2만원을 넘지 않는 경우에는 제외하고, 쿠폰을 쓰더라도 추가비용이 2만원 이상일 경우에는 제외하지 않아야 합니다.

**Comment by keedi** [comment]
그렇다면 3회를 빌렸는데 1회 타이, 2회 신발, 3회 셔츠 를 빌린 경우를 예로 들어보죠. 이 대여자의 경우 4회차때 대여금액을 50% 할인하면 되나요?

**Comment by 10001if** [comment]
@aanoaa 복잡성을 줄이는데 도움이 되고 3회 이상 이용자에게 혜택을 주는 건 좋은 취지라고 생각합니다. 하지만, 문제가 되는 점은 취업날개 서비스가 서울에 거주하는 특정연령대의 인원에게만 적용된다는 점입니다. 내부 팀원들과 논의 해보니 무상대여(취업날*, 관악고*, 십시일*)의 경우에는 제하는게 좋겠다는 의견이네요.

**Comment by keedi** [comment]
저는 오히려 쿠폰 자체는 이미 할인이 되거나(스폰서가 부담), 또는 지원의 측면(열린옷장이 모두 부담)에서 발행이 된 것이고, 이 경우 쿠폰을 사용한다는 것 자체가 할인이 되었다는 의미이며, 더불어 여기에 대여자가 추가로 비용을 더 지불한다고 치더라도 이미 이것은 50~80%에 가까운 할인이 들어간 것입니다. 따라서 단순히 복잡성이 문제라면 쿠폰으로 대여한 경우는 아예 3회 대여 카운트에서 제외하는 것이 적절하다고 생각합니다. 물론 단순히 제 생각일 뿐이니 결정은 열린옷장이 해야겠죠.

**Comment by keedi** [comment]
더불어 무상 대여인 경우 제하는게 좋겠다고 했는데 쿠폰이라고 반드시 무상 대여가 아닌 경우가 있는 것인지요? 아니면 쿠폰은 무상 대여인것인가요? 전자라면 쿠폰은 횟수에 고려하지 않는다는 의미고 후자라면 쿠폰이라 할지라도 횟수에 고려할수도 있고 아닐수도 있다는 의미입니다.

**Comment by aanoaa** [comment]
3회이상 대여자에게 할인일때에는 악용될 수 있습니다.
친구들한테 대신 예약해주고 대리인이 와서 할인 받아서 대여 할 수 있습니다.

**Comment by aanoaa** [comment]
3회마다 할인적용은 어떨까요?

**Comment by aanoaa** [comment]
2회 반납후에 할인쿠폰을 문자로 보내준다?

**Comment by 10001if** [comment]
@keedi 여러가지로 결정해야할 사항이 제법 있네요. 내일 회의 때 다시 논의해보고 생각을 정리해서 남기도록 하겠습니다. 궁금하신 점 있으시면 다 남겨주세요 ^^

**Comment by 10001if** [comment]
@keedi 정리된 결과는 다음과 같습니다.

1. 3회 대여부터 아래의 규정을 적용한다. 이때 3회 대여는 품목, 금액과 상관없이 대여 횟수만을 기준으로 한다.
2. 자켓-바지 or 자켓-스커트 를 대여하는 경우에는 그 외 다른 품목에 대해서 무상으로 대여를 실시한다.
-  다만, 1가지의 품목만 무상으로 진행한다.
3. 자켓-바지 or 자켓-스커트가 아닌 경우에는 30%의 할인율을 적용한다.
4. 연장/연체비의 경우에는 실제 발생한 대여비에 20%/30%의 기존 룰을 그대로 적용한다.
5. 단체 대여의 경우에는 본 규정을 제외하기로 한다.
- 단체 대여의 기준은 같은 품목을 2개 초과하여 빌리는 경우를 말한다. 1인당 같은 품목으로 2개까지는 대여가 가능하나, 2개를 초과하는 품목이 발생하면 단체 대여로 취급하기로 한다.
- 하지만, 단체 대여의 경우 자동으로 단체대여를 인식하도록 할 것인지, 사람이 단체대여로 지정하여 입력할 것인지 고민이 필요해 보인다.

**Comment by 10001if** [comment]
@keedi 내부적으로는 9월 1일부터는 본 제도를 시행하는게 좋겠다고 의견이 모아졌습니다. 9월 1일부터 적용이 가능할 지 일정 문의 드립니다~

**Comment by keedi** [comment]
@10001if 알겠습니다. 9월 1일까지 정도면 별 문제 없을 것 같습니다.

**Comment by 10001if** [comment]
@keedi 감사합니다. 장기 대여자 할인 정책도 고민해보겠습니다.

**Comment by keedi** [comment]
정리한 결과가 조금 복잡하긴 한데 일단 다시 정리해보겠습니다.

- 대여 횟수를 감안할 때 각각의 대여시 무엇을 빌렸는지를 고려하지 않음. 실제 대여를 수행했으면 대여 1회라고 판단함.
- 다만 쿠폰을 사용해 대여한 경우는 대여 횟수에 포함하지 않음. 쿠폰을 사용할때 추가 비용을 지불했다 하더라도 대여 횟수에 포함하지 않음.
- 상기 두 항목을 고려해서 3회 대여하러 오는 경우 부터 비용 할인 대상임
- 재킷+바지+ α 인 경우 재킷1벌, 바지1벌을 제외한 나머지 종류별로 1개 항목씩은 비용을 받지 않음. 즉 2만원.
- 재킷+치마+ α인 경우 재킷1벌, 치마1벌을 제외한 나머지 종류별로 1개 항목씩은 비용을 받지 않음. 즉 2만원.
- 재킷+바지만 대여할 경우 30% 할인. 즉 1.4만원
- 재킷+치마만 대여할 경우 30% 할인. 즉 1.4만원
- 이외의 모든 항목의 조합이거나 이외의 조합이 추가될 경우 30% 할인을 일괄 적용함.

헷갈릴 수 있으니 쿠폰 사용 제외 3회째 방문을 기준으로 예를 들면 다음과 같습니다.

재킷1벌, 바지1벌 -> 1.4만원
재킷1벌, 바지1벌, 타이1벌, 신발1켤레, 셔츠1벌 -> 2만원
재킷1벌, 바지1벌, 타이1벌, 신발1켤레, 셔츠2벌 -> 2만원 + 3500원(셔츠1벌 30%)
재킷1벌, 치마1벌 -> 1.4만원
치마1벌, 블라우스1벌 -> 10500원 ( 10000 + 5000 값에 30% )
재킷2벌, 바지2벌 -> 2.8만원 ( 4만원의 30% )
재킷2벌, 치마1벌, 바지1벌, 셔츠2벌, 구두2벌 -> 2만원 + 2.1만원(재킷1벌, 바지1벌, 셔츠1벌, 구두1벌의 30%)
재킷2벌, 치마1벌, 바지1벌, 셔츠2벌, 구두2벌, 타이 3벌 -> 2만원 + 2.24만원(재킷1벌, 바지1벌, 셔츠1벌, 구두1벌, 타이1벌의 30%)

**Comment by keedi** [comment]
상기 내용에서 잘못된 부분을 정정합니다.

> - 재킷+바지+ α 인 경우 재킷1벌, 바지1벌을 제외한 나머지 종류별로 1개 항목씩은 비용을 받지 않음. 즉 2만원.
> - 재킷+치마+ α인 경우 재킷1벌, 치마1벌을 제외한 나머지 종류별로 1개 항목씩은 비용을 받지 않음. 즉 2만원.

재킷+바지 또는 재킷+치마 셋트 구성일 경우 개수에 상관없이 종류별로 1개 항목씩 비용을 받지 않습니다. 즉 재킷2+바지2벌이면 종류별 2개 항목씩은 비용을 받지 않는 것입니다.

다시 예를 들면 다음과 같습니다.

재킷2벌, 바지2벌 -> 2.8만원 ( 4만원의 30% )
재킷2벌, 치마1벌, 바지1벌, 셔츠2벌, 구두2벌 -> 2만원 + 2만원
재킷2벌, 치마1벌, 바지1벌, 셔츠2벌, 구두2벌, 타이 3벌 -> 2만원 + 2만원 + 0.14만원 (타이1벌의 30%)

**Comment by keedi** [comment]
조정한 사항은 다음과 같습니다.

- 자켓1+바지1 대여일 경우, 셔츠1, 타이1, 구두1, 벨트1 만 무료
- 자켓2+바지2 대여일 경우, 셔츠2, 타이2, 구두2, 벨트2 만 무료
- 자켓1+스커트1 대여일 경우, (셔츠1 또는 블라우스1), 타이1, 구두1 만 무료
- 자켓2+스커트2 대여일 경우, (셔츠2 또는 블라우스2), 타이2, 구두2 만 무료
- 이외의 경우 추가되는 항목은 30% 할인을 적용
- 자켓3벌 이상이거나, 바지3벌 이상이거나, 스커트3벌 이상이거나, 기본 대여일 기준 대여금액이 10만원 이상이면 단체 대여로 간주하고 무상 대여 품목 또는 30% 할인을 적용하지 않음

**Comment by aanoaa** [comment]
부분반납이 되었을때에 하위주문서가 생성되고, 반납횟수가 2회로 계산됩니다.
현재 계산방식대로 적용되면 안됩니다.

    /order/23219

는 2회대여 라고 나오지만 실제로는 1회대여 입니다.

**Comment by keedi** [comment]
반납 여부 확인 + parent_id가 없는 조건을 동시에 적용하면 하위주문서를 대여 횟수에서 제거할 수 있습니다.

**Comment by keedi** [comment]
어제부터 진행중입니다. 9월 1일이라고는 하는데 아마 이번 주 중이면 완료되어 배포될 것 같습니다. 일정상 큰 문제는 없습니다.

**Comment by keedi** [comment]
자켓1 + 바지1 + 타이1 이면 지금까지 논의했던 대로라면 타이1만 무료여야 하지만 오늘 다시 확인해본 결과 이 경우 30% 할인해야 한다고 합니다. :-1: 

언제부턴가 타이는 시스템에 0원으로 책정되어 있는데 타이가 이래저래 예외를 너무 많이 만드네요;;;

**Comment by keedi** [comment]
일단 기능은 구현했습니다. 세세하게 여러가지 경우에 대해 테스트를 진행해야 합니다. 더불어 9월에 적용 예정이라고 했는데 기능이 머지되고 나면 일괄적으로 적용됩니다. 관련해서 설정 값을 이용해서 할인 기능을 적용 시킬지 말지 판단하도록 할지 아니면 다른 방법이 있는지 확인해야 합니다.

**Comment by keedi** [comment]
구현 완료한 화면입니다.

![screenshot-monster silex kr 10301 2016-08-11 16-39-16](https://cloud.githubusercontent.com/assets/138451/17581723/714ba4e2-5fe2-11e6-8d35-44c56a20169f.png)

**Comment by keedi** [comment]
갈무리한 화면을 보면 확인할 수 있는 내용은 다음과 같습니다.

- 대여자는 4번째 방문자임(3번째 방문이라도 할인 적용)
- 대여자는 재킷, 치마, 신발, 블라우스를 대여함
- 이 때 재킷, 치마 금액은 정상 금액, 신발, 블라우스 금액은 책정되지 않음
- 원래는 총액 3만원이지만 2만원으로 계산됨

실제로는 여러가지 케이스가 있으며 다음과 같은 경우에 대해 테스트 완료했습니다.

- 재킷이나 치마 또는 바지가 3벌 이상일때 할인을 적용하지 않는가?
- 재킷, 바지 또는 치마, 타이를 대여할 때 30% 할인을 적용하는가?
- 위 아래 두셋트 이상일 때 할인이 제대로 적용되는가?
- 등등...

실제로 버그가 있을수는 있겠지만 일단 확인하기로는 문제없어 보입니다.

**Comment by keedi** [comment]
설정 파일을 이용해서 할인 여부를 결정할 수 있도록 했으며 실제 할인을 적용하기 전까지는 본 기능을 끄고 사용할 수 있을 것으로 보입니다.

**Comment by keedi** [comment]
`develop` 가지에 병합 완료했습니다. 이슈 닫습니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^

**Comment by 10001if** [comment]
@keedi 취업날개와 3회 이상 대여와의 관계가 있나요? @aanoaa 문의 주셔서 질문 드립니다. 취업날개가 1인 2회에서 10회로 조정 되었습니다. 이와 관련해서 관련 이슈가 있는지 문의 드립니다.

**Comment by aanoaa** [comment]
쿠폰으로 대여하는 것은 금액과 상관없기 때문에 할인여부는 중요치 않습니다.

쿠폰으로 여러번 대여하고 그 이후에 쿠폰없이 대여하고자 할때에 금액할인과는 상관이 있습니다.
3회 이상 대여자는 할인해주고 있는데, 쿠폰으로만 n회 대여하고 다시 찾아왔을때 할인을 할 것인가?

지금은 할인금액을 계산할때에 쿠폰으로 대여한 이력은 포함되고 있지 않습니다.
예로, 쿠폰4회 대여 이후에 쿠폰없이 대여하고자 할때는 할인된 금액이 아닙니다.

**Comment by keedi** [comment]
본 이슈 내용을 보면 당시 취업날개를 포함 쿠폰을 이용한 경우 할인 대상에서 제외를 원한다고 요청 받았습니다. 따라서 현재 쿠폰(취업날개도 쿠폰이므로 포함)을 사용하지 않고 2번 사용 후 3번 째 쿠폰 없이 방문한 경우 할인 금액이 적용됩니다. 관련해서 변경되어야 한다면 새로운 이슈를 등록해서 새로운 방침을 정해주세요.
