### ISSUE TITLE
사용 중인 의류를 폐기할 때 폐기사유를 입력할 수 있도록 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#791]
사용 중인 의류를 폐기할 때 폐기사유를 입력할 수 있는 란의 추가를 요청드립니다. 이는 향후 폐기가 된 의류의 폐기 내역과 이유를 기증자에게 전달해 드리기 위함입니다.

**Comment by aanoaa** [comment]
`comment` 로 충분히 사용할 수 있습니다.

    blahblah
    blahblah
    폐기사유: 어쩌고 저쩌고

이런식의 입력이 가능하기 때문입니다.

하지만 폐기사유의 전달을 자동화 하기 위한다면 comment 와 폐기사유는
구분되어야 합니다.

**Comment by aanoaa** [comment]
의류의 상태별로 무언가 컬럼이 필요하다고 할때,
컬럼을 계속해서 추가해 나간다면 40개도 넘게 추가될 수 있습니다.

대여사유, 수선사유 등등

이렇게 되는것보다는 각 상태별로 추가 작업이 필요하다면 테이블을 따로
만들어서 추가하는 것이 더 나을 수도 있습니다.

이번 이슈를 예로하면

`폐기된 의류` 테이블을 만들고,

- 언제
- 누구꺼
- 어디로
- 설명
- 등등

필요한 만큼 커스텀해서 더 편리하게 사용할 수 있기 때문입니다.

**Comment by yongbin** [comment]
폐기는 말 그대로 열린옷장 시스템 입장에서는 더 이상 관리할 대상이 아니기 때문에 말씀하신것 처럼 별도의 테이블(`disuse_clothes` 정도?)에 clothes를 FK로 연결하고 폐기 관련 정보를 넣는것도 좋을거 같습니다.

**Comment by aanoaa** [comment]
폐기된 의류에 대해 기증자에게 알려주기 위한 목적이 있습니다.
폐기시점에 알려줄수도 있겟지만 폐기된 내역을 연단위로 알려줄 수도
있습니다.

comment 의 사용은 적절치 않아 보입니다.

**Comment by aanoaa** [comment]
연단위 리포트는 계획이 없다고 합니다.

**Comment by aanoaa** [comment]
#792 이슈와 비슷한 주제입니다. 함께 처리하도록 하겠습니다.
