### ISSUE TITLE
사용 중인 의류를 폐기할 때 옷캔, 비백, 사용못함으로 구분되어 입력 할 수 있도록 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#792]
처음 의류를 등록하는 것과 마찬가지로 사용 중인 의류를 폐기할 때에도 옷캔, 비백, 사용못함으로 구분되어 입력 할 수 있도록 하고 싶습니다. 옷캔이나 비백 등으로 발송되는 의류의 양을 체크하기 위함입니다.

**Comment by aanoaa** [comment]
지금도 의류의 상태를 구분할 수는 있습니다.

- 폐기
- 재활용(옷캔)
- 재활용(비백)

그런데 이런식이 아니라
사용되다가 재활용되는 옷들의 구분 또한 필요하다는 말씀인가요?

- 폐기(옷캔)
- 폐기(비백)

처럼요

**Comment by 10001if** [comment]
네. 맞습니다. 사용되다가 폐기하는 의류도 동일하게 기록할 수 있도록 요청드립니다.

2016. 4. 22. 오후 5:54 Hyungsuk Hong <notifications@github.com> 작성:

**Comment by aanoaa** [comment]
예외적이라고 생각했던 옷의상태 `재활용(옷캔)`, `재활용(비백)` 이외에
사유가 상태에 추가되는 이슈입니다.

위 두개의 상태는 바코드 자동발급을 위해 꼼수로써 추가된 것입니다.

이번 같은 경우에는 `comment` 를 활용할 수 있지 않을까 합니다.

의류의 수량 파악이 목적이라면 comment 에 `옷캔`, `비백` 등을 적어주는
것으로도 충분합니다.

**Comment by aanoaa** [comment]
폐기사유와 폐기장소? 및 기타 알림을 위해서는 *폐기의류* 에 관련된
데이터를 따로 저장할 필요가 있습니다.

*폐기의류* 테이블을 추가할까 합니다.

- id
- clothes_code
- reason? comment? desc?(폐기사유)
- 어디로 가는지(옷캔|비백|...|사용못함)
- create_date(폐기일)
- update_date

정도면 폐기사유와 폐기장소등을 기록할 수 있습니다.

**Comment by aanoaa** [comment]
첫화면에서의 의류 상태변경을 할때에 `폐기` 되는 의류에 대해 위의
추가정보를 입력받아야 합니다.

해서 어떻게 추가정보를 입력받을지에 대한 작업 역시 필요합니다.

**Comment by aanoaa** [comment]
폐기된 의류의 추가 정보를 입력 했다고 가정하고,

`/clothes?status=8` 는 폐기의류의 목록입니다.
여기에 폐기사유, 폐기장소, 페기일 등을 보여주어야 할까요?

**Comment by aanoaa** [comment]
첫화면은 지금처럼 의류의 상태만 변경하고,
의류의 상세정보를 나타내는 `/clothes/J003` 에서 폐기상태일때에,
폐기의류정보를 추가로 나타내고 수정가능하게 하면 어떨까 합니다.

**Comment by aanoaa** [comment]
폐기사유와 폐기장소기능을 위해서는
새로운 버전의 OpenCloset::Schema 가 먼저 설치되어야 합니다.

**Comment by aanoaa** [comment]
의류 목록에서도 폐기사유와 폐기장소가 나타나도록 하였습니다.

![screenshot-localhost 5001 2016-05-18 13-49-12](https://cloud.githubusercontent.com/assets/170528/15347734/5f9b9476-1cff-11e6-8c69-0cd50d32a3f9.png)

**Comment by aanoaa** [comment]
배포전에 OpenCloset-Schema-0.034 의 설치가 필요합니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
