### ISSUE TITLE
수시로 폐기내역을 기증자에게 발송

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#793]
사용 중인 의류를 폐기할 때 처음 의류를 등록할 때처럼 의류 폐기 내역을 메세지로 발송하고자 하였으나, 의류가 폐기될 때마다 알림이 가는 것은 기증자에게 귀찮은(?)일이 될 것 같아. 폐기 내역을 1년에 한번 씩만 알려드리려고 합니다. 그리고 이 때 열린옷장의 전체 대여현황 등을 정리한 에뉴얼 리포트를 함께 전달하고자 합니다.

**Comment by 10001if** [comment]
> 사용 중인 의류를 폐기할 때 처음 의류를 등록할 때처럼 의류 폐기 내역을 메세지로 발송하고자 하였으나, 의류가 폐기될 때마다 알림이 가는 것은 기증자에게 귀찮은(?)일이 될 것 같아. 폐기 내역을 1년에 한번 씩만 알려드리려고 합니다. 그리고 이 때 열린옷장의 전체 대여현황 등을 정리한 에뉴얼 리포트를 함께 전달하고자 합니다.

이렇게 하려고 하였으나, 폐기 상황은 수시로 알려드리는 것이 좋다고 판단이 되었습니다. 다만, 이 내용은 폐기 알림을 원하는 분들에게만 전달하는 것이 맞는 것 같습니다. 본 내용이 전제가 된다면 수시로 알려드려도 문제가 없을 것으로 보입니다. 

때문에, 처음 신청 시 폐기 알림을 원하는지 동의를 받고 (내용은 정리해서 올리겠습니다) 나중에라도 폐기 알림을 원하지 않는 분은 문자가 발송되지 않도록 체크를 해제할 수 있는 방법이 필요해 보입니다.

**Comment by 10001if** [comment]
> 그리고 이 때 열린옷장의 전체 대여현황 등을 정리한 에뉴얼 리포트를 함께 전달하고자 합니다.

에뉴얼 리포트는 구체적인 계획이 없으므로 우선 없는 것으로 생각해주시면 될 것 같습니다~

**Comment by aanoaa** [comment]
SMS 가 편리하긴 하지만 사용자가 스팸으로 여겼을때, 간단하게 취소할 수 있는 방법이 없습니다.
하지만 email 이라면 `수신거부` 링크를 제공함으로써 쉽게 수신을 취소할 수 있습니다.

그리고 이런 내용이라면 sms 보다는 email 이 더 적절해 보입니다.

**Comment by aanoaa** [comment]
> 때문에, 처음 신청 시 폐기 알림을 원하는지 동의를 받고 (내용은
> 정리해서 올리겠습니다) 나중에라도 폐기 알림을 원하지 않는 분은
> 문자가 발송되지 않도록 체크를 해제할 수 있는 방법이 필요해
> 보입니다. 

현재는 모든의류가 위의 동의를 얻지 못했습니다.
알림을 보낸다고 한다면 email 을 통해서 앞으로 동의한 사용자들에게만
보내는게 적절하지 않나 생각됩니다.

그리고 어떻게 어디에서 무슨 동의를 구할 것인지 구체적으로 고민해야
합니다.

**Comment by aanoaa** [comment]
이전에 기증해줬던 모든 분들에게 *수신거부* 링크와 함께 email 을 보내고
앞으로 기증신청할때에 수신동의에 관한 내용이 추가되어야 합니다.

**Comment by aanoaa** [comment]
@10001if 님이 완성해주어야 하는 일입니다.

- [ ] 의류가 폐기 되었을때 이메일 내용
- [ ] 동의를 구하는 내용 혹은 동의를 구하지않고 그냥 보냄

**Comment by 10001if** [comment]
@aanoaa 확인해서 다시 알려드리겠습니다.

**Comment by 10001if** [comment]
질문 주신 두 가지 중 2번째 항목의 경우 동의를 구해야 함으로 다음과 같은 내용을 기증 신청서에 삽입해주시길 요청드립니다. ^^

- [ ] 동의 요청 내용

열린옷장은 기증 이후 의류가 손상되거나 수명을 다하여 폐기되는 경우 이메일을 통해 알려드리고 있습니다.  기증하신 의류가 폐기될 때마다 알림 전송에 동의하십니까?

**Comment by 10001if** [comment]
- [ ] 의류가 폐기 되었을때 이메일 내용

의류폐기 이메일 내용 : - 날짜, 기증자 성함, 의류 or 구두 부분만 교체

![-](https://cloud.githubusercontent.com/assets/4696328/15168450/94152a8e-176c-11e6-8d58-9471aeb6553e.jpg)

이렇게 전달 받았는데.. 이미지라 뭔가 문제가 있을 것 같네요. 찾아뵙고 다시 말씀드리겠습니다. ^^;

**Comment by aanoaa** [comment]
네 간결하게 텍스트로 우선 진행하는게 좋겠습니다.

꼭 필요한 내용만 추려서요.

**Comment by 10001if** [comment]
@aanoaa 네! 알겠습니다. ^^

**Comment by aanoaa** [comment]
의류가 폐기될때마다 사용자에게 이메일을 보내나요?
등록되자 마자 폐기된다면?

원클릭 unsubscribe 기능도 추가되어야 합니다.
스팸메일로 느껴진다면 사용자가 쉽게 메일을 안받게 하기 위함입니다.

**Comment by aanoaa** [comment]
대여가능 -> 폐기 -> 수선 -> 폐기

이럴리야 없겟지만 가능한 시나리오 입니다.
아이고야 잘못해서 수선으로 바꿨네 다시 폐기로..

이 경우엔 똑같은 메일을 2번 받게 됩니다.

한번 보낸 경우에는 안보내야 하지 않나 싶습니다.

**Comment by aanoaa** [comment]
user_info

- email_notify
- sms_notify


discard_clothes

- notify_sent

---------------------------

컬럼을 추가하면 해결 할 수 있을 것 같습니다.

사용자의 원클릭취소는 user_info.email_notify 로 하고,
의류의 폐기 email 송신여부는 discard_clothes.notify_sent 로 하고..

**Comment by aanoaa** [comment]
알림 같은 경우에는 좀 신중하게 접근할 필요가 있다고 생각합니다.
그래서인지 웬지 조심스럽군요

**Comment by aanoaa** [comment]
확장성 같은걸 고려한다면 고민고민 해야할테고 이번 이슈만 해결하고자 한다면
제가 제안한 정도로도 충분합니다.

**Comment by aanoaa** [comment]
discard_clothes.notify_sent 같은 건 굳이 필요가 없는 것이, 값이 존재한다면 이미 보낸 것 입니다.

**Comment by aanoaa** [comment]
하지만 실제로 email 발신에 실패할 수 있으므로, 역시 컬럼을 따로 두는게 좋겠습니다.

**Comment by aanoaa** [comment]
언제 이메일을 보낼 것인가를 정해야 합니다.

상태를 `폐기` 로 바꾸었을때?
폐기사유를 입력했을때?
폐기장소와 폐기사유가 입력되었을때?
하루치를 모아서 한번에?

**Comment by aanoaa** [comment]
아쉽지만, 이별합니다.
    2016년 5월 4일 이후로 한만일님이 기증해주신 소중한 의류와 아쉬운 이별을 하게 되었습니다.
    기증자님을 통해 열린옷장과 만난 후 정장이 필요한 수많은 이들을 위해 참 많은 수고를 해주었습니다.
    그 동안의 수고에 뜨거운 감사를 전하며 따뜻한 이야기 소중히 간직하겠습니다.
    
    -- 열린옷장

**Comment by aanoaa** [comment]
알림 치고는 너무 서정적이지 않나..싶습니다.

**Comment by aanoaa** [comment]
제가 사랑하는 github 의 결제 알림 이메일 입니다.

    We received payment for your GitHub.com subscription. Thanks for your business!
    
    Questions? Contact us anytime at support@github.com.
    
    ------------------------------------
    GITHUB RECEIPT - ORGANIZATION SUBSCRIPTION - silexkr
    
    Silver organization plan
    
    Amount: USD 
    
    Charged to: 
    Transaction ID: 
    Date: 15 May 2016 02:56AM PDT
    For service through: 2016-06-14
    
    
    GitHub, Inc.
    88 Colin P. Kelly Jr. Street
    San Francisco, CA 94107
    ------------------------------------
    
    * EU customers: Prices inclusive of VAT, where applicable

**Comment by aanoaa** [comment]
@10001if 우선 이메일의 내용이 필요합니다.
위에 내용이 괜찮으시다면 그대로 진행하겠습니다.
그렇다면 폐기사유나 장소와도 상관없이 보낼 수 있습니다.

**Comment by 10001if** [comment]
@aanoaa 생각보다 결정해야 할 이슈들이 많네요. 우선 말씀해 주신 것처럼 텍스트로 옮겨놓으니 조금 서정적인 느낌이 드네요. 아무래도 폐기라는 내용이 부정적인 의미가 있는 단어이다보니 이렇게 작성이 된 것 같네요. 그래도 조금 객관적인 느낌이 나면 좋을 것 같기도 합니다. 그리고 등록시 바로 폐기가 되는 최초1회의 경우에는 일괄로 문자 전송을 하지만 그 이후에는 실시간으로 바로 가기보다는 하루치를 한번에 보내는게 적당해 보입니다. 본 이슈는 다시 결정해서 전달해 드리도록 하겠습니다. ^^

**Comment by aanoaa** [comment]
이건 뒤로 미루도록 하겠습니다.
이것 때문에 폐기사유랑 폐기장소 이슈까지 같이 미뤄지거든요.

**Comment by keedi** [comment]
결제 알림 메일은 돈과 관련되었기 때문에 딱딱해야 합니다.

하지만 가입이나 해지 등의 경우 깃헙이든 드롭박스등 글로벌한 어느 서비스든 "잘왔다", "네가 떠난다니 마음이 아프다."등 다양한 메시지를 보냅니다. 기증자에게 소중했을 기증 의류를 떠나(정확히 냉정하게 폐기)보내게 되는 상황에서 결제 메일처럼 보내면 받은 사람에 따라 황당할 수 있을거라 사료됩니다.

어찌했든 관련해서는 열린옷장이 감수해야 할 부분이고, 그 메시지가 서정적이든, 또는 사무적이든 열린옷장이 원하는 방식으로 알림을 보내는 것이 맞을 것입니다. 그러니 관련해서 메시지를 감성적으로 보낼지 사무적으로 보낼지 또는 적절하게 혼용할지는 내부적으로 논의하신 후 확실하게 입장을 취해주시기 바랍니다. @10001if 

더불어 본 이슈 진행할때 말씀해주시면 이미지가 포함된 이메일 양식은 제가 최대한 비슷하게 만들도록 하지요.

**Comment by 10001if** [comment]
@keedi 알겠습니다. 이 부분은 중령대표님과 논의를 더 해봐야 할 것 같습니다. 결정되면 다시 말씀드리겠습니다.

**Comment by 10001if** [comment]
새로운 언급이 없습니다. 우선 이슈 닫도록 하겠습니다.
