### ISSUE TITLE
프로그램에서 요청드리고 싶은 것들 적어보아요~

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#80]
1. 주문서에서 반납처리가 되지 않습니다. 전체반납을 누르면 연체료 항목만 추가되는 것 같습니다. 수정 요청드릴게요~
![2014-07-17 2 48 20](https://cloud.githubusercontent.com/assets/4696328/3609254/1d36e1f2-0d76-11e4-8b0b-97947184e1a4.png)

2. 새로운 대여자 방문시 개인정보 및 대여목적을 작성하면 종료될 수 있도록 수정 부탁드릴게요. 사이즈는 전에 말씀해주셨던 것처럼 리스트로 나열된 항복에서 직접 수정 할 수 있도록 해주시면 될 것 같습니다. 그리고 새로운 대여자가 개인정보 적는 란은 새창으로 독립적으로 띄울 수 있는지 문의가 있어서요. 대여자분들이 재고관리 프로그램 자체를 함께 보는게 바람직하지 않을 것 같다는 의견이 있는데 이게 가능할런지요?

3. 휴대폰 인증이 가능하도록 수정해주시면 감사할 것 같습니다. :)

**Comment by keedi** [comment]
1 / 2 / 3 모두 처리 완료되었습니다. 이슈 닫습니다.

1번의 경우 버그였으며 수정되었습니다.

2번의 경우 방문 예약 페이지를 아예 방문자만 접근할 수 있는 형식으로 완전히 변경했습니다.

3. 휴대폰 인증 기능 역시 추가되었습니다.

이슈 닫습니다.
