### ISSUE TITLE
맞춤 의류 제안 기능

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#800]

**Comment by keedi** [comment]
@10001if 이슈 설명이 있어야 할 것 같아요~

**Comment by aanoaa** [comment]
아 이것이 https://github.com/opencloset/monitor/issues/94 이슈의 레퍼런스 입니다.

**Comment by 10001if** [comment]
@keedi 님~ @yongbin 대표님이 만들어 주신 검색기능을 preparation 화면에 붙이는 작업입니다. 조금 덩어리가 커서 이슈들이 정리되면 작업 해주시기로 하셨습니다. ^^

**Comment by aanoaa** [comment]
@yongbin: 색상에 따른 검색은 할 수 없나요?

**Comment by aanoaa** [comment]
@yongbin

OpenCloset::Size::Guess::OpenCPU::RandomForest 를 사용하는 것이 좋을까요 아님 staff 의 `/user/:id/search/clothes` 를 사용하는 것이 좋을까요?

**Comment by yongbin** [comment]
지금 의류검색은 O::S::G::O::RandomForest 결과와 DB질의를 조합한 결과입니다. 색상은 DB조합부분에 추가하면 될거 같은데  지금 `/usr/:id/search/clothes`에 있는 코드를 API 로 빼내고 거기에 색상을 지원하도록 변경해야합니다.

**Comment by aanoaa** [comment]
@yongbin 해서, 둘중에 뭘 쓰는게 더 좋을까요?

**Comment by aanoaa** [comment]
재고관리에 추가 API 로 맨들어서 사용하도록 하는게 좋습니다.

**Comment by yongbin** [comment]
내일 @10001if 님과 화면구성에 대해서 결정해야합니다.

**Comment by aanoaa** [comment]
API 에서 바뀌어야 하는 부분이, 의류에서 대표하는 사이즈와 색상까지 나타내야 합니다.

현재는 

    [윗도리,아랫도리,대여횟수]
    [J001,P001,30]

인데,

    [윗도리,윗도리대표치수,윗도리색상,아랫도리,아랫도리대표치수,아랫도리색상,대여횟수]
    [J001,87,검정,P001,81,검정,30]

같은식으로 나와야합니다.
추가로 질의에 대한 무슨 신체치수가 있다고 하는데 그것도 주어야 합니다.

**Comment by aanoaa** [comment]
옛버전의 monitor 와 새로운 버전의 monitor 에서
redis 에서의 `opencloset:storage` 키가 중복되는 이슈가 있어서
https://monitor.theopencloset.net 에서 오류가 발생할 수 있습니다.

    $ redis-cli
    redis> del opencloset:storage

명령으로 해결할 수 있지만
옛버전이 계속해서 떠 있으면 언제든지 같은 문제가 발생할 수 있습니다.

옛버전의 도메인주소를 사용하고 있는 서비스가 있기 때문에 이를 바꾸고 적용해야 합니다.

**Comment by aanoaa** [comment]
관련된 서비스에서의 옛도메인주소를 변경하였습니다.(staff 의 설정)

**Comment by aanoaa** [comment]
opencloset.test-monitor

서비스와 이와 관련된 디렉토리 및 설정파일을 제거 하였습니다.

    opencloset.suggestion

서비스가 새로 추가되었습니다.
사용자의 추천의류를 작업하는 데몬입니다.

**Comment by aanoaa** [comment]
@yongbin 

opencloset.suggestion 서비스의 stdout, stderr 의 redirect 가 제대로 동작하지 않습니다.
괜히 두개로 나눴나 싶기도 하고요.

stdout, stderr 모두 같은 파일로 제대로 출력될 수 있도록 봐주세요

**Comment by yongbin** [comment]
넵 확인해보겠습니다.

**Comment by aanoaa** [comment]
냅두세요 제가 하겠습니다.

**Comment by aanoaa** [comment]
https://groups.google.com/forum/#!topic/ubic-perl/K_7nLskCixQ

**Comment by aanoaa** [comment]
/SERVICE_HOME/log/suggestion.log

에 쌓입니다.
파일이 커질 수 있습니다.

**Comment by 10001if** [comment]
@aanoaa 이것도 제가 확인할 이슈는 없는 거죠? 오랫동안 확인요망 상태로 남아 있는데 제가 확인해야 하는데 못한 건지 싶어서요.

**Comment by aanoaa** [comment]
모니터에서 추천의류가 뜨는건데 뭐 이미 확인하셨겟죠 문제가 없어보이므로 라벨을 제거합니다.

**Comment by 10001if** [comment]
@aanoaa 알겠습니다~!
