### ISSUE TITLE
새옷 등록 후 수선 절차를 진행할 수 있는 프로세스를 추가하도록 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#802]

**Comment by aanoaa** [comment]
![default](https://cloud.githubusercontent.com/assets/4696328/14732521/78ab8994-0896-11e6-8d18-e7bdf4b77327.png)

**Comment by aanoaa** [comment]
> `수선` 상태인 의류에 대해 `치수변경`? 버튼을 둬서 누르면 위 그림에 맞게끔
수정된 사이즈가 사용자에게 제안되고, 사용자는 확인을 눌러서 사이즈를
변경

되는 기능이 필요합니다.

**Comment by aanoaa** [comment]
@10001if 
남자, 여자로 구분해놓으셨지만 팬츠와 스커트로 이해해도될까요?

의류에는 성별이 없기 때문입니다.

**Comment by aanoaa** [comment]
윗배는 자켓이고 허리는 바지의 사이즈입니다.
셋트의류일때에만 동작이 가능하다는 얘기입니다.

**Comment by aanoaa** [comment]
이것보다는 기증 관련 서비스에서 해결되는게 더 좋을 것 같다고 합니다.

**Comment by 10001if** [comment]
배포해주시면 확인해서 라벨을 제거하겠습니다. ^^

**Comment by aanoaa** [comment]
어제 저녁에 구두로 아직 쓰지말아달라고 했는데 수정하였습니다.
사용하셔도 될 것 같습니다.

**Comment by 10001if** [comment]
확인완료하였습니다. 이 기능은 기존에 진행되었던 여러 이슈들보다 덩어리가 컸을 것 같은데 많이 고생해 주셨네요.. 아마 새 옷이 기증되고 등록되기까지 기존보다 훨씬 빠르게 처리될 것 같습니다. 정말 감사드립니다. ^^
