### ISSUE TITLE
카카오 알림톡 서비스 도입 검토

### ISSUE THREAD

**Issue by MoDoLEE** [opencloset/opencloset#803]
현재 SMS메시지의 문제점이 있어 다른 서비스 검토를 진행 중입니다. 문제점은 다음과 같습니다.

1. 070 번호로 인해 스팸으로 인식하여 문자를 받지 못하는 경우가 하루 5건 이상 발생하고 있습니다. (예약 확인 문자를 못받았다는 경우에 한해서 카운트 한 것이고, 미납 문자는 별도 확인이 불가능하지만 더 많을 것으로 생각됩니다.
** 사례 : 인증번호를 받지 못했다는 전화를 받아서, staff페이지의 문자전송과 인터넷 전화기 자체에서 문자를 보내봤지만 모두 받지 못했다고 합니다.**
2. 현재 070 번호로 문자를 보내서 대여자가 답장을 할 경우 인터넷 전화기를 통해서 확인해야하고, 저희쪽에서 답장시 다시 PC를 이용해서(인터넷 전화 자판은 타자치기가 많이 힘듭니다 ㅠㅠ) 답장을 보내야되는 번거로움이 있습니다.

이 와 같은 문제점을 해결하기 위해서 카카오 알림톡 도입을 검토 중입니다. 카카오 알림톡은 전화번호가 있고, 카카오톡이 설치되어 있다면 별도의 친추추가 없이 알림 메세지를 전송할 수 있는 서비스 있습니다. 대여자가 답장을 할 경우 옐로아이디와 연동되어 저희쪽에서 PC로 바로 확인하고 바로 답장이 가능합니다.

알림톡 서비스는 카카오에서 직접 서비스를 제공하지 않고, 대행사를 통해서 진행합니다. 6개의 대행사가 있으며, 문의를 한 결과 1개의 대행사에서만 답장이 왔고, 설치 가이드 문서로 받았습니다. 설치 가이드 문서를 첨부하오니, 내용 확인하시고 도입이 가능한지 판단해 주시면 감사하겠습니다! ^^

**Comment by MoDoLEE** [comment]
[엠지기 알림톡 에이전트 설치 가이드_v1.4.pdf](https://github.com/opencloset/opencloset/files/232770/_v1.4.pdf)

**Comment by yongbin** [comment]
좋은 고민 감사합니다. 일단 SMS에 있는 문제를 해결하는 이슈와 카카오 알림톡을 사용하는 이슈는 분리해서 생각해야 할것 같습니다. 왜냐하면 SMS와 카카오톡은 서로 성격이 다르고 현재 발생하는 문제를 카카오톡을 사용하지 않고 해결하는 방법도 고민해 볼 수 있기 때문입니다.

**Comment by yongbin** [comment]
알림톡과는 별개이슈지만 얼마전에 카카오톡에 '나에게 메세지 보내기' API가 오픈되었다고 해서 간단하게 테스트 해봤습니다.

https://developers.kakao.com/docs/restapi#%EC%B9%B4%EC%B9%B4%EC%98%A4%ED%86%A1-%EB%82%98%EC%97%90%EA%B2%8C-%EB%B3%B4%EB%82%B4%EA%B8%B0


1. 카카오 개발자 로그인
1. 앱 생성
1. 앱 사용자 보안 설정 
1. REST 개발자 도구에서 Access Token 생성(HTTP로 처리가능)
1. 메세지 템플릿 등록 
1. curl 호출

```sh
curl -v \
      -X POST "https://kapi.kakao.com/v1/api/talk/memo/send" \
      -H "Authorization: Bearer XXX" -d 'template_id=842' \
      --data-urlencode 'args={"${userName}": "난 널 믿었던것 만큼 난 내  친구도 믿었기에 난 아무런 부담없이 널 내 친구에게 소개시켜줬고 그런 만남이 있은후 부터 우린 자주 함께 만나며 즐거운 시간을 보내며 함께 어울렸던 것뿐인데"}''
```
![screen shot 2016-07-06 at 4 20 53 pm](https://cloud.githubusercontent.com/assets/52704/16611439/2c12098c-439c-11e6-9529-494c65d87af5.png)

**Comment by 10001if** [comment]
알림톡 서비스가 필요하다고 생각 될 때 이슈를 다시 열도록 하겠습니다.
