### ISSUE TITLE
사용자의 설명란의 매크로버튼

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#807]
자주 사용하는 설명에 대해 버튼 눌러서 업데이트 하고 싶습니다.
이때 설명을 덮어쓰는 건 아니고 append 되어야 합니다.

@10001if 자주 사용되는 설명을 적어주세요.

**Comment by aanoaa** [comment]
- 라운드 반팔 블라우스
- 라운드 민소매 블라우스
- 탑 블라우스
- 셔츠 블라우스
- 승무원 블라우스

라고 합니다.

**Comment by 10001if** [comment]
@aanoaa 설명을 다 적었으므로 제 태그를 제거하도록 하겠습니다.

**Comment by keedi** [comment]
진행합니다.

**Comment by keedi** [comment]
관련해서 @10001if 님께 설명을 들은 후 이슈를 좀 더 정리하겠습니다.

**Comment by aanoaa** [comment]
제가 알고 있습니다.

치수측정할때에 `설명` 란이 자주 활용되는데,
여성분의 경우에 원하시는 블라우스 타입을 여쭤보고 설명란에 적는다고 합니다
이게 빈번하게 발생되고 있어서 매번 입력하기 번거롭다고합니다.

하지만 블라우스말고 다른 설명도 입력할 수 있어야 하므로,
위에 적어놓은 블라우스 종류 외에 직접 입력할 수도 있어야 하고,

현재 설명이 적혀져 있다면 덮어쓰는 것이 아니라 개행 후 추가되어야 합니다.

**Comment by 10001if** [comment]
- 라운드 반팔 블라우스
- 라운드 민소매 블라우스
- 탑 블라우스
- 셔츠 블라우스
- 승무원 블라우스

본 내용을 입력하지 않고 클릭하여 설명란에 삽입하고자 합니다. ^^

**Comment by keedi** [comment]
본 기능은 `/user/:id` 페이지에서 처리해야 하는 이슈입니다.

**Comment by keedi** [comment]
방금 확인한 결과 갈무리한 화면의 선택 영역에 매크로 버튼이 위치하면 좋겠다고 합니다.

![screenshot-monster silex kr 10301 2016-05-19 15-17-54](https://cloud.githubusercontent.com/assets/138451/15384462/bf1ecb58-1dd5-11e6-969b-6da6c6b54eed.png)

**Comment by keedi** [comment]
상기 내역 이외에 오늘 날짜를 입력할 수 있는 버튼도 필요하다고 합니다.

5월 19일일 경우 `---- 2016-05-19` 형식으로 넣기로 했습니다.

**Comment by aanoaa** [comment]
오늘날짜 버튼이 따로 있는것보다는 버튼을 누르면 오늘날짜 들어가는게 좋지 않을까여?

어차피 이버튼의 용도가 딱 이거밖에 없는데..

**Comment by keedi** [comment]
@aanoaa 저도 그 부분을 문의했는데 여성이 아니라 남성인 경우에는 따로 키보드로 입력한 다음에 날짜를 넣어야 한다고 합니다. 그런 연유로 날짜 버튼이 따로 필요하다고 하네요.

**Comment by keedi** [comment]
구현한 화면은 다음과 같습니다.

![screenshot-monster silex kr 10301 2016-05-19 16-42-43](https://cloud.githubusercontent.com/assets/138451/15386123/ed4df3b8-1de0-11e6-8430-3f303f81e033.png)

**Comment by keedi** [comment]
to @aanoaa @10001if 
작업 완료했습니다. 수정할 부분있으면 말씀해주세요~

**Comment by aanoaa** [comment]
설명은 업데이트할때 입력한 텍스트 뒤에 무조건 오늘 날짜를 추가하는 것은 어떤가요?
그렇지 않다고 하더라도, 블라우스에 대한 매크로 버튼이 오늘 날짜까지 넣어주는게 더 좋지 않을까합니다.
한단계 더 나아간다면 성별이 여성인 경우에만 매크로버튼을 보여주는 것도 좋을 것 같습니다.

라는게 그냥 저의 생각

**Comment by keedi** [comment]
@10001if 상기 커멘트 확인 부탁드립니다.

**Comment by keedi** [comment]
피드백 받았습니다.

현재 사용자의 설명 부분이 주문서 포장 시점에 주문서로 복사됩니다. 따라서 기존 사용자의 설명 정보는 지난 주문서에 항상 복사됩니다. (예외 상황: 예약 후 신체치수만 입력하고 빌리지 않는 경우 등등) 그렇기 때문에 사용자 정보에는 지난 정보를 제거한 후 오늘의 정보만 입력해도 충분합니다. 이렇게 될 경우 굳이 날짜를 저장할 필요가 없어집니다. 날짜는 여러 정보가 있을 경우 의류 준비하는 측에서 오늘에 해당하는 정보를 확인하기 위해 필요했지만 항상 오늘 정보라면 이를 고민할 필요가 없기 때문입니다.

다른 측면에서 신체 치수를 측정하고 사용자의 설명 정보를 입력하는 사람의 경우 지나간 정보가 필요하다고 합니다. 그래서 날짜로 구분해서 입력을 했는데, 주문서에 이미 복사가 되었으므로 역시 마찬가지로 더이상 날짜를 넣거나 예전 정보를 가지고 있을 필요가 없습니다. 하지만 지난 사용자 정보(설명)을 볼 필요가 있는데, 이는 지난 주문서의 정보(설명)을 보는 것으로 해결할 수 있습니다.

사용자 정보 페이지 아래쪽에는 최근 주문 내역이 보이는데 여기서 대여정보와 반납정보를 클릭없이 바로 열람할 수 있게 하면 현재 이슈가 해결하려는 진짜 문제를 궁극적으로 해결할 수 있습니다.

**Comment by keedi** [comment]
최신 주문서 내역 목록에서 주문서 메모 5F와 반납 확인 메모 4F을 바로 확인할 수 있도록 보여줍니다.

![screenshot-staff theopencloset net hp850 30200 2016-05-25 15-25-00](https://cloud.githubusercontent.com/assets/138451/15530184/d54573c0-228d-11e6-8775-925c2d99da65.png)

**Comment by keedi** [comment]
기술적으로는 다음과 같은 이슈가 있습니다. 주문서 목록은 기본적으로 최초 주문서, 즉 부모 주문서를 보여줍니다. 하지만 대여 진행중 부분 반납 등의 이슈로 담당자가 주문서 메모와 반납 확인 메모를 하위 주문서에 기록하는 경우가 있다는 것입니다. 따라서 실제로는 해당 주문서에 연결된 하위 주문서에는 메시지가 존재하지만 최상위 주문서를 열람할 때는 메시지가 보이지 않을 수 있습니다. 일단 이를 해결하기 위해 부모 주문서 하부에 주문서가 있을 경우 해당 주문서에 대해서도 모두 메시지를 확인해서 (정확히는 1단계 자식 주문서만 확인함, 2단계 이상은 확인하지 않음) 보여줍니다.

이런 연유로 주문서 메모나 반납 확인 메모가 있는 것을 보고 해당 주문서를 클릭해도 해당 주문서 페이지에서는 주문서 메모나 반납 확인 메모가 없을 수도 있습니다. 이 경우는 하위 주문서를 확인해야 합니다.

**Comment by keedi** [comment]
@10001if 상기 화면 갈무리 내용 보시고 디자인적으로나 표현적으로 의견 있으면 남겨주세요.

**Comment by keedi** [comment]
오늘 날짜를 추가하는 기능은 제거했습니다.

**Comment by keedi** [comment]
버튼을 눌러서 내용을 추가하는 기능은 제대로 동작하고 있으나 다음과 같은 오류 메시지가 발생하고 있습니다.  원인을 찾아서 해결해야 합니다.

```
[Wed May 25 15:42:00 2016] [debug] PUT "/api/user/7940.json"
[Wed May 25 15:42:00 2016] [debug] Routing to controller "OpenCloset::Web::Controller::User" and action "auth"
[Wed May 25 15:42:00 2016] [debug] Routing to controller "OpenCloset::Web::Controller::User" and action "auth"
[Wed May 25 15:42:00 2016] [debug] Routing to controller "OpenCloset::Web::Controller::API" and action "api_update_user"
[Wed May 25 15:42:00 2016] [error] Failed to posting event: Internal Exception
[Wed May 25 15:42:00 2016] [debug] 200 OK (0.020035s, 49.913/s)
```

**Comment by keedi** [comment]
프로젝트 최상위 디렉터리에서 검색해보면 해당 오류 메시지와 연관있는 곳은 다음 세 곳입니다.

```bash
$ rgrep 'Failed to posting event: '
lib/OpenCloset/Web/Plugin/Helpers.pm:        $self->app->log->error("Failed to posting event: $res->{reason}")
lib/OpenCloset/Web/Plugin/Helpers.pm:            $self->app->log->error("Failed to posting event: $res->{reason}")
lib/OpenCloset/Web/Controller/Order.pm:            $self->app->log->error("Failed to posting event: $res->{reason}")
$
```

**Comment by keedi** [comment]
`PUT "/api/user/7940.json"` 접속 주소는 `PUT /api/user/:id`에 해당하며 이는 현재 `OpenCloset::Web::Controller::API::api_update_user()` 부분입니다.
`api_update_user()` 메소드에서 오류가 발생하고 있는 위치는 다음과 같습니다.

`OpenCloset::Web::Controller::API::api_update_user()`:

```perl
    ...
    my ( $user, $msg ) = try {
        $self->update_user( \%user_params, \%user_info_params );
    }
    ...
```

`$self->update_user()` 메소드는 `OpenCloset::Web::Plugin::Helpers` 모듈의 `update_user()` 메소드 입니다.
디버깅 결과 전송 오류를 발생시키는 코드는 다음과 같습니다.

```perl
        #
        # event posting to opencloset/monitor
        #
        my $res = HTTP::Tiny->new( timeout => 1 )->post_form(
            $self->config->{monitor_uri} . '/events',
            { sender => 'user', user_id => $user->id }
        );

        $self->app->log->error("Failed to posting event: $res->{reason}")
            unless $res->{success};
```

해당 부분은 [monitor 웹 응용](https://github.com/opencloset/monitor)으로 변경 내역을 통지하는 것입니다.
이 부분은 로컬 개발 서버에 해당 웹 응용을 띄우지 않았기 때문에 발생하는 이슈입니다.
진짜 오류가 아닙니다.

로그를 보다가 착각할 가능성이 있으므로 알아보기 쉽게 로그 메시지를 수정하겠습니다.

**Comment by keedi** [comment]
사용자나 주문서의 상태가 변경될 때 모니터 웹응용에게 통지를 하는데 이 때 서버상에 모니터 웹응용이 떠 있지 않으면(개발서버처럼) 통지에 실패합니다. 이는 치명적인 것이 아니므로 로그 수준을 오류에서 경고로 격하시키고 더불어 로그 메시지 내역을 자세하게 기록해 로그를 참조하는 사람이 이 오류는 모니터 웹응용에게 보내는 것이 실패한 것임을 인지할 수 있도록 합니다.

수정 완료했습니다.

**Comment by keedi** [comment]
마지막 피드백한 부분까지 최종 구현 완료되었으며 최종 확인 후 추가 수정을 하든지 또는 머지 진행을 하든지 하면 됩니다.

**Comment by keedi** [comment]
최종 확인 받았습니다. 작업 완료되었습니다.

**Comment by aanoaa** [comment]
관행대로 배포대기 라벨 대신에 이슈 닫고, 배포후에 확인용망 라벨을 붙이도록 하겠습니다.
