### ISSUE TITLE
서울시 이벤트 이용현황 전달

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#808]
![2016-04-27](https://cloud.githubusercontent.com/assets/170528/14876757/79802990-0d52-11e6-80a5-63b9080367a1.png)

오늘 04-28 까지 보내주어야 합니다.

**Comment by aanoaa** [comment]
[seoul-event.xlsx](https://github.com/opencloset/opencloset/files/240048/seoul-event.xlsx)

**Comment by aanoaa** [comment]
![2016-04-28 16-59-56](https://cloud.githubusercontent.com/assets/170528/14879225/eb58f000-0d62-11e6-8c9d-f1c98b5f2593.png)

**Comment by 10001if** [comment]
오늘(4/28) 자료는 내일 오전 중으로 요청하였습니다. 번거로우시겠지만 부탁드리겠습니다. ^^

**Comment by 10001if** [comment]
수요일까지의 내용은 확인 하였습니다.

**Comment by aanoaa** [comment]
[seoul-event.xlsx](https://github.com/opencloset/opencloset/files/241748/seoul-event.xlsx)

![2016-04-29 12-33-06](https://cloud.githubusercontent.com/assets/170528/14907652/f00894a8-0e06-11e6-8582-c3877fbb8beb.png)

**Comment by aanoaa** [comment]
@10001if 이용현황입니다.

| date  | 열린옷장 예약 | 열린옷장 방문 | 취업날개 예약 | 취업날개 방문 |
| ------| ------------- | ------------ | ------------ | ------------ |
| 04-28 | 110 | 103 | 13 | 13 |
| 04-29 | 92 | 79 | 15 | 11 |
| 04-30 | 113 | 96 | 16 | 9 |
| 05-02 | 101 | 89 | 30 | 25 |
| 05-03 | 100 | 83 | 26 | 23 |

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^

**Comment by aanoaa** [comment]
@10001if 이용현황입니다.

| date  | 열린옷장 예약 | 열린옷장 방문 | 취업날개 예약 | 취업날개 방문 |
| ------| ------------- | ------------ | ------------ | ------------ |
| 05-04 | 73 | 60 | 12 | 12 |
| 05-05 | 0 | 0 | 0 | 0 |
| 05-06 | 89 | 75 | 13 | 13 |
| 05-07 | 92 | 85 | 26 | 23 |
| 05-08 | 0 | 0 | 0 | 0 |
| 05-09 | 113 | 104 | 34 | 31 |
| 05-10 | 107 | 95 | 24 | 22 |

**Comment by 10001if** [comment]
@aanoaa 어제 바로 전달하였습니다. 감사합니다. ^^

**Comment by aanoaa** [comment]
이벤트 이용현황에 대해 어떠한 자료가 필요한지 문의했었는데 일별
열린옷장의 방문자 수와 이용자 수, 이벤트를 통한 예약자 수 와 이용자 수
가 필요하다고 했습니다.

민원이 들어왔다며 위 내용에 추가로 연령대별/성별 이용자수를 보내달라고
합니다.

유감인것은

- 전화문의로 처리 하는 것
- 모든 것이 ASAP 인 것

입니다.

매번 쿼리를 통해 뽑아 주면 귀찮은 작업이 될테니까
이벤트용 통계 화면을 만들어서 처리하고자 합니다.

**Comment by aanoaa** [comment]
``` sql
SELECT DATE_FORMAT(b.date, '%Y-%m-%d'), status, COUNT(*)
FROM `order` o JOIN booking b ON o.booking_id = b.id JOIN coupon c ON o.coupon_id = c.id
WHERE coupon_id IS NOT NULL AND b.date BETWEEN '2016-05-01%' AND '2016-05-10%' GROUP BY DATE_FORMAT(b.date, '%Y-%m-%d'), status;
```

이 raw query 를 DBIx 로 변환하기가 쉽지 않습니다.

**Comment by aanoaa** [comment]
연령대별이라고 하면,

    연령대   total
    10대       100
    20대       100
    30대       100

이렇게 달라는 건가요? 성별도 마찬가지 입니다.
정확히 원하는 포맷이 필요합니다.

개발이슈를 저희가 담당하면서 이용현황까지 챙기려니 번거롭습니다.
앞으로 어떤 요구가 더 잇을지 걱정됩니다.

**Comment by aanoaa** [comment]
통계를 뽑으려면 날짜/연령별, 연령/성별, 예약인원/성별, 방문인원/연령별 등등
열라 많습니다. 뭘 원하는 건지 알아야 합니다.

**Comment by aanoaa** [comment]
![screenshot-staff theopencloset net 2016-05-17 18-16-38](https://cloud.githubusercontent.com/assets/170528/15317232/925aee56-1c5b-11e6-893d-397c912dd2be.png)

@10001if 새로운 통계메뉴가 추가되었습니다.

**Comment by aanoaa** [comment]
@10001if 서울시에 전달한 이메일을 확인했습니다.
그런데 연령대별, 성별 현황에 대한 자세한 내용이 필요합니다.

**Comment by 10001if** [comment]
@aanoaa    

```
   연령대    
    10대       100
    20대       100
    30대       100
    합 계       300
```

```
    성별   total
    남     100
    여     100
   합계   200
```

로 정리해주시면 됩니다. 그리고 불필요한 요청은 제가 확인해서 체크하도록 하겠습니다. ^^

**Comment by 10001if** [comment]
취업 날개 이벤트 페이지 확인하였습니다. ^^

**Comment by aanoaa** [comment]
말씀해주신대로 연령대/성별은 누적으로 계산하겠습니다.

**Comment by aanoaa** [comment]
연령대별/성별 누적 통계를 추가하였습니다.

**Comment by aanoaa** [comment]
매주 월요일 마다 이메일로 보내달라고 하는데, 번거로우니까 통계 화면을 public 하게 변경하고
URL을 알려주도록 하겠습니다.

알아서 보라고요.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^

**Comment by aanoaa** [comment]
정산을 위해 월별 이용현황이 추가되어야 합니다.

**Comment by aanoaa** [comment]
월별 열린옷장 미방문인원의 수치가 부정확합니다.
확인이 필요합니다.

**Comment by aanoaa** [comment]
- 월별 성별
- 월별 연령별

이용현황도 필요합니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
