### ISSUE TITLE
시간표에 쿠폰을 통해 예약한 이용자는 시간표에 표시가 뜨도록 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#809]
![2016-04-28 3 39 59](https://cloud.githubusercontent.com/assets/4696328/14877379/872a8f2c-0d57-11e6-87bd-35671919e12d.png)
실제로 시간표에서 쿠폰 이용자인지 확인해야 하는 이슈가 빈번히 일어나고 있다고 합니다. 취업날개라는 단어가 표시되도록 수정을 요청드립니다.

**Comment by aanoaa** [comment]
![screenshot-localhost 5001 2016-05-20 14-51-23](https://cloud.githubusercontent.com/assets/170528/15418585/54ffb2c0-1e9b-11e6-839b-bdcbeffdb794.png)

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
