### ISSUE TITLE
이벤트 사용자의 세션타임아웃 에러

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#813]
서울시 이벤트 사용자가 세션만료기간내에 신청하지 못하면 `인증코드가
만료되었습니다` 라는 에러메세지를 계속해서 나타납니다.

쿠폰 사용시에 session 을 사용하고 있는데 이와 관련이 있지 않을까 합니다.

**Comment by 10001if** [comment]
하루에 한 두명씩 이슈가 발생하고 있습니다. 판단해 보시고 이슈가 크지 않다면 바로 진행해 주시고 이슈가 크다면 마일스톤을 옮겨주셔도 됩니다. ^^

**Comment by aanoaa** [comment]
"이것만 마무리하고" 라는 생각에 이슈 하나를 너무 오래 잡고 있어서 금방 처리될 수 있는 이슈들이 뒤로 밀려버렸네요.

오늘까지만 하던거 마무리 해보고 안되면 내일부터는 처리할 수 있는 것부터 해결하겠습니다.

**Comment by aanoaa** [comment]
**테스트방법**

- 임의로 쿠폰을 발급
- 쿠폰번호를 입력해서 예약진행
- 인증번호를 입력하고 만료시간이 지나도록 변경
- 다시 인증번호를 입력하고 나머지 절차를 진행
- 예약성공

`인증코드가 만료되었습니다` 라는 메세지는 이벤트와는 상관없이
인증번호를 입력하고 10분 내에 예약을 완료하지 못한 사용자는 누구나
받는 메세지입니다.

이때에는 다시 인증번호를 받아서 진행해야 합니다.

-----------------------------------

예약은 성공했지만 문제를 발견

주문서의 `create_date` 가 `NULL`
주문서가 만들어질때에 create_date 는 자동으로 만들어져야 합니다.
하지만 왜 안되었는지가 의문입니다.

이벤트와 관련성은 모르겠지만 이것부터 해결해야 합니다.

**Comment by aanoaa** [comment]
> 서울시 이벤트 사용자가 세션만료기간내에 신청하지 못하면 인증코드가 만료되었습니다 라는 에러메세지를 계속해서 나타납니다.

제가 테스트해봤을때는 계속해서 나타나지 않았습니다.
시간이 만료되었을때는 다시 인증번호를 발급받아서 진행할 수 있습니다.

이는 이벤트와 상관없이 다른 사용자들에게도 해당되는 내용입니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
