### ISSUE TITLE
택배 발송일을 입력하면 연장비 계산이 되도록 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#815]
현재 반납일은 다음과 같이 지정됩니다. 

대여일이 12일이고 반납예정일이 15일인 경우 (3박 4일 대여의 경우)

1. 방문반납시 15일까지만 반납하면 됨
2. 택배 반납시는 택배 발송일 1일을 계산하여 반납예정일 하루 전인 14일까지 반납해야 함
> 이때, 택배 반납의 기준은 택배 송장에 적혀 있는 발송일이 기준이 됨.

때문에 홍길동이 보낸 택배를 16일 오전에 반납택배를 푼다고 하더라도 
택배상자에 적혀 있는 운송장의 발송일이 14일 인 경우
> 본 경우에는 연장비를 청구하지 않음.

하지만 운송장 발송일이 15일인 경우 
> 1일의 연장비용을 청구해야 함

하지만 택배 발송일은 눈으로 확인해야 하며 이를 머리 속으로 계산하여 연장비용을 청구하는데 실수가 되풀이 되어 연달아 발생하고 있음

따라서 주문서 안에 택배 발송일을 입력할 수 있는 폼을 추가하여
입력한 택배 발송일에 따라 연장비용을 다시 계산할 수 있는 기능이 추가되었으면 함.

예) 반납 예정일 15일, 택배 발송일 18일 
> 택배를 발송해야 하는 반납 예정일은 14일이고 18일에 발송했으므로 14, 15, 16, 17, 18 / 5일의 연장비 발생
> 총 대여금액은 30,000원이었으므로 6,000 * 5 = 30,000원의 연장비용 발생

**Comment by 10001if** [comment]
다만, 택배 발송일이 월요일인 경우
편의점 사정상 일요일날 택배 발송을 하지 못하는 경우들이 존재하므로  
반납 예정일이 월요일인 경우 일요일에 반납해야 하지만,  
월요일 반납도 일요일 반납으로 생각하여 처리하고 있습니다..

**Comment by aanoaa** [comment]
사용자가 반납을 위해 택배를 발송한뒤에 할 수 있는 행동

1. 아무것도 하지 않는다
2. (고맙게도) 대여했을때의 SMS 를 찾아서 링크를 누르고 운송장번호를 입력한다
3. 전화한다

2번은 사용자 입장에서 번거로운 일입니다.
여기에 추가로 택배 발송일을 넣어야 합니다.
결정적으로 1,3번 사용자가 있으면, 사람이 계산해야 합니다.

택배를 받으면 우선 판단을 해야 합니다.
운송장번호를 입력했나?
택배 발송일도 입력했나?

택배 발송일을 입력할 수 있다고 하더라도, 지금과 똑같이 어렵습니다.

운송장번호를 입력한날을 택배 발송일로 가정할 수는 있지만 정확하지 않습니다.
웹서비스를 제공하는 택배사라면 운송장번호를 가지고 언제 발송했는지 알 수 있지만,
그렇지 않은 택배사의 경우에는 이것도 알 수 없습니다.

**Comment by aanoaa** [comment]
*연장비/연체비 계산기* 같은 것은 어떨까요?

입력은

- 주문서번호
- 택배발송일

출력은

- 연장비
- 연체비


가능여부에 따라서 입출력이 달라질 수 있습니다.

무엇이 다른가하면,

- 고객은 택배 발송일을 입력하지 않아도 된다.
- 정확한 택배 발송일을 입력할 수 있다.

입니다.

처리절차가 번거로워 지겠지만 실수는 줄어들 수 있을 것 같습니다.

**Comment by MoDoLEE** [comment]
처음 의도는 대여자가 택배 발송일을 직접 등록하는 것이 아니라,
열린옷장 직원이 택배를 풀면서 직접 택배 발송일을 입력하는 것이었습니다.
@aanoaa 께서 두번째 말씀 하신 내용이 조금 더 가까운 것 같습니다.

**Comment by 10001if** [comment]
@MoDoLEE 열린옷장 직원이 택배 발송일을 직접 입력하는 안을 이야기 드렸는데, 택배 발송을 하는 사용자가 직접 할 수 있는 방법을 고민해 보신 듯 합니다. @aanoaa 이야기 하신 것 처럼 직원이 택배 발송일을 입력하면 연장비, 연체비 값을 알 수 있는 방법이 있다면 좋을 것 같습니다. ^^

**Comment by aanoaa** [comment]
연체비와 연장비를 따로 구분하지 않고 연장비라는 개념으로 사용되고 있었는데,
이작업을 위해서는 우선 둘을 분리해야 합니다.

**Comment by aanoaa** [comment]
용어의 혼란을 막기위해 용어정리부터 하겠습니다.
옳은지는 모르겠지만,

연장비: extension-fee
연체비: overdue-fee
연장비+연체비: late-fee

라고 하겠습니다.

**Comment by aanoaa** [comment]
연체/연장비와 연체/연장일이 helper(**calc_late_fee, calc_overdue**)로 계산되고 있는데,
주문서에서만 쓰이는 것이 아니라, 첫화면과, 의류목록에서 현재 연장/연체비가 얼마인지 보여주는데
사용되고 있습니다.

이름을 바꾸거나 내용을 건드리면 안됩니다.

새로운 helper 를 추가하도록 해야 합니다.

**Comment by aanoaa** [comment]
이번 기회에 문서도 같이 업데이트하면 나중을 위해 도움이 될 것 같습니다.

**Comment by yongbin** [comment]
#477 이슈도 연체/연장비를 다룹니다.

**Comment by aanoaa** [comment]
SMS 와도 관련이 있습니다.
안내된 SMS 와 실제로 받는 금액이 다르다면 불평이 있을 수 있습니다.
정확하게 안내하도록 합니다.

**Comment by aanoaa** [comment]
SMS 라는건 연체된 사용자에게 보내는 SMS 를 말합니다.

**Comment by aanoaa** [comment]
SMS 는 이미 처리되었습니다.

**Comment by 10001if** [comment]
확인 하였습니다. 이 덕분에 반납시간이 훨씬 빨리지고 스트레스가 많이 줄어들 것 같습니다! 감사합니다. ^^

**Comment by aanoaa** [comment]
당분간은 주의해서 연체/연장비를 봐주세요.
테스트를 많이 해보지 못해서 오류가 있을 수 있거든요

**Comment by 10001if** [comment]
@aanoaa 알겠습니다. 주의해서 보도록 하겠습니다.
