### ISSUE TITLE
대여 탭 화면에서 수선을 마치고 돌아온 사람의 이름에 수선완료의 표시가 뜨도록 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#816]
수선절차를 마치고 돌아온 경우

1. 포장담당자가 preparation 화면에서 수선완료된 대여자의 이름을 확인하고 포장버튼을 누름

2. 대여탭에서 포장담당자가 포장을 실시

이때, 포장을 담당하는 사람은 수선을 마치고 돌아온 대여자의 의류를 우선적으로 포장해야 함.
>왜냐하면 수선을 마치고 돌아온 대여자의 경우 대기 시간이 일반 사용자에 비해 더 길었기 때문.

3. 따라서, 포장담당자는 대여탭에서 수선 절차를 통해 포장으로 등록된 사람 먼저 포장을 진행해야 함

4. 이를 위해, 수선이 완료된 사용자의 경우 수선과정을 거친 사용자라는 정보를 확인할 수 있어야 함.

**Comment by aanoaa** [comment]
![screenshot-localhost 5001 2016-05-20 13-53-55](https://cloud.githubusercontent.com/assets/170528/15417624/ffb6add0-1e92-11e6-8023-59650dab61be.png)

**Comment by aanoaa** [comment]
4bb3d007fccc05e38aa5b30d0ff22a943a6a7d0f

재고관리에서도 redis 를 사용하게 되었습니다.

cc @keedi @yongbin

**Comment by yongbin** [comment]
그럼 앞으로 로컬에서 띄우려면 redis를 구동해야하나요? 간단하게 개발환경 세팅관련 내용을 README에 업데이트 해주시면 테스트 해보겠습니다.

**Comment by aanoaa** [comment]
네 README 적어야 하는건 알고잇엇는데 패스하니깐 이런일이.. ㅜ

**Comment by aanoaa** [comment]
003d6e5f404020bf677919ef66d155ab90c0902d

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^

**Comment by aanoaa** [comment]
이번 monitor 의 변경으로 인해 제대로 동작하지 않을 것 같습니다.

**Comment by aanoaa** [comment]
monitor 에서 근본적으로 바뀌어야 해결된 문제이긴 합니다.
캐시 문제로 제대로 동작하지 않습니다.

**Comment by aanoaa** [comment]
https://github.com/opencloset/monitor/issues/122
