### ISSUE TITLE
짝벌 or 세트  반납시 반납 담당자에게 정보를 알리기 

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#817]
열린옷장의 의류는 `세트`와 `짝벌`로 나뉩니다.

여기서 `세트`란 자켓 + 바지 혹은 자켓 + 스커트 입니다.
두 가지의 경우에는 두 개의 의류가 개별 코드를 가지고 있고 독립적으로 존재하지만
한 옷걸이에 함께 물려 있어야 합니다.

> 때문에, 자켓만 대여가 된 경우. 바지는 4층의 짝벌 보관장소에 보관되고
> 4층으로 자켓이 반납 된 경우 짝벌 보관장소에 놓여 있던 바지를 찾아 세트를 맞춥니다.

> 또한, 자켓과 바지를 서로 다른 짝으로 대여한 경우에도 반납 시 원래 짝을 찾아 의류의 세트를 일치시킵니다.

따라서, **_남성의류의 경우_** 반납 시에 세트가 아닌 짝벌이 들어오는 경우 
반납 담당자가 이를 확인하여 의류의 원래 짝을 찾을 수 있도록 해야 하기 때문에
반납시 셋트 의류가 아닌 경우에는 팝업 형식의 알림을 통해 짝벌 여부를 알려줄 수 있도록 해야 합니다.

하지만 **_여성의류의 경우_**에는 반대로 세트가 들어오는 경우, 반납 담당자가 알고 있어야 합니다.
남성의류의 경우에는 대부분이 세트이고 단품으로 대여하는 수가 극히 적기 때문에 세트 여부를 알아야 하지만, 여성의류는 대부분 단품의류이므로 세트 의류를 빌려가고 반납하는 비율이 크지 않았습니다.

**Comment by aanoaa** [comment]
반납했을때 알려주는 방식이 아니라,
언제든지 확인이 가능한 방식은 어떤가요?

주문서에 들어가서 보면 대여한 의류의 목록이 보입니다.
여기에서 자켓과 팬츠 혹은 스커트가 셋트의류인지 아닌지 나타내준다면
반납받을때 확인하고 처리할 수 있습니다.

**Comment by aanoaa** [comment]
![screenshot-donation theopencloset net 2016-06-15 13-55-47](https://cloud.githubusercontent.com/assets/170528/16068458/f1ff1510-3300-11e6-8de3-271e00d44a62.png)

새옷등록한 후의 화면입니다.
셋트 의류는 녹색으로 표시되고, 그렇지 않은 의류는 파란색으로 표시됩니다.

이와 비슷하게 색으로 구별할 수 있도록 해놓으면 남성의류이던지, 여성의류이던지 쉽게 확인하고
그에 따른 행동을 취할 수 있습니다.

의류의 상세화면을 보고 어떤 의류와 셋트인지 확인하는 수고를 덜어주게 됩니다.

**Comment by 10001if** [comment]
@aanoaa 좋은 아이디어 같습니다. 그렇게 셋트를 확인할 수 있다면 문제가 많이 해결될 것 같습니다!

**Comment by 10001if** [comment]
@aanoaa 반납시 세트와 짝벌을 주문서에서 바로 확인할 수만 있어도 훨씬 더 효율적인 운영이 가능해 보입니다. ^^
