### ISSUE TITLE
OpenCloset::Schema-0.031 버전업 후 주문서 생성시간에 의한 장애

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#818]
오늘 오후 1시쯤 (5월 12일 목요일)
https://github.com/opencloset/donation/issues/33 이슈해결을 위해서
OpenCloset::Schema 의 새로운 버전을 배포하고 설치하였습니다.

0.030 -> 0.031

https://github.com/opencloset/OpenCloset-Schema/compare/release-0.030...release-0.031

이후에 생성된 주문서들의 생성시간이 `NULL` 로 들어갔습니다.

16:14 즈음에 

0.031 -> 0.030 로 rollback 하고 서비스 재시작후했습니다.

이후에는 생성시간이 제대로 들어감을 확인했습니다.

불편을 겪었던걸로는 /user/35633
사용자의 화면이 들어가지지 않아서 신체치수를 입력하지 못했습니다.

**Comment by aanoaa** [comment]
임시로 생성시간이 NULL 인 주문서들의 생성시간을 넣어 두었습니다.

**Comment by aanoaa** [comment]
테스트로 0.031 을 사용해서 방문예약을 했을때 생성시간이 NULL 로
들어갔습니다.

0.030 으로 했을때에는 생성시간이 정상적으로 들어갔습니다.

두버전간의 차이를 분석해야합니다.

**Comment by aanoaa** [comment]
스키마와 관련있는 배포였던 donation v0.2.0 과 staff 와 visit 의 v1.5.3
역시 이전버전으로 되돌리겠습니다.

**Comment by aanoaa** [comment]
주문서가 만들어질때의 code 입니다.

``` perl
my $order_obj = $user->create_related(
    'orders',
    {
        status_id  => 14,        # 방문예약: status 테이블 참조
        booking_id => $booking,
        coupon_id  => $coupon_id,
    }
);
```

이와 비슷하게 테스트해서 create_date 왜 안만들어지는지 파악해야 합니다.

**Comment by keedi** [comment]
#813 의 `create_date` NULL 값 들어가는 이슈와 관련 있는지 확인이 필요하겠네요. 연결차 남겨놓습니다.

**Comment by aanoaa** [comment]
``` perl
package OpenCloset::Schema::Result::Order;

...

    "create_date",
    {
        data_type                 => "datetime",
        datetime_undef_if_invalid => 1,
        inflate_datetime          => 1,
        is_nullable               => 1,
        set_on_create             => 1,
    },

...
```

    my $order = $schema->resultset('Order')->create( { user_id => 35620, status_id => 14 } );

0.031 에서 `create_date` 의 `set_on_create => 1` 로 되어있지만 위 구문의 실행 결과는 null 입니다.

**Comment by aanoaa** [comment]
#813 은 0.031 배포후에 테스트하다가 발견된거라서 관련이 없을 것 같습니다.
이 장애의 발견요인이기도 하죠.

**Comment by aanoaa** [comment]
volunteer_work 의 `create_date` 도 NULL 로 들어갔습니다.
모든 set_on_create 컬럼은 모두 null 값으로 들어간 듯 보입니다.

**Comment by aanoaa** [comment]
create_date 가 null 인 값들

user: 35
coupon: 10
order_detail: 157924
sms: 228
volunteer_work: 3

**Comment by aanoaa** [comment]
create_date 를 가지고 undef 값을 사용하려는 모든 서비스의 페이지에 문제가 있습니다.

**Comment by aanoaa** [comment]
order_detail: 157924

의 수치는 create_date 를 쌓고있지 않다가 얼마전 일일정산이슈에서 추가되었습니다.
그래서 기존의 값들은 전부 null 인 것입니다.

order_detail.create_date 는 완납/불납/미납 처리에 사용됩니다.
나머지 행들은 create_date 가 상관없습니다.

**Comment by aanoaa** [comment]
http://ix.io/DuS id 를 기록해두었습니다.
임시방편으로 현재시각으로 create_date 를 업데이트 하겠습니다.

**Comment by aanoaa** [comment]
``` sql
UPDATE user SET create_date = UTC_TIMESTAMP() WHERE create_date IS NULL;
UPDATE coupon SET create_date = UTC_TIMESTAMP() WHERE create_date IS NULL;
UPDATE sms SET create_date = UTC_TIMESTAMP() WHERE create_date IS NULL;
UPDATE volunteer_work SET create_date = UTC_TIMESTAMP() WHERE create_date IS NULL;
```

**Comment by aanoaa** [comment]
다시 정리하면, OpenCloset::Schema-0.031 로 업데이트한 이후에

set_on_create 로 설정된 모든 column 이(create_date 처럼) timestamp 대신에 null 로 들어갔습니다.
set_on_create 가 정상적으로 동작하지 않았습니다.

**Comment by aanoaa** [comment]
역시 같은 이유로 `update_date` 도 null 로 들어간 값이 있습니다.

    user: 5
    coupon: 9
    order: 37

**Comment by aanoaa** [comment]
`cm <-> inch` 변환을 쉽게 하기 위해서 했던 추가작업에서 발생한 오류였습니다.

https://github.com/opencloset/OpenCloset-Schema/commit/b0f5afb0b48c4d9e4a47315d93be988a54c55748

에서 `lib/OpenCloset/Schema/Base.pm` 파일에 `FilterColumn` component 를 추가해서 발생했습니다.
이 순서를 바꿔주면 문제가 발생하지 않습니다.

관련해서 문서를 찾아보면,

https://metacpan.org/pod/distribution/DBIx-Class/lib/DBIx/Class/Manual/Component.pod#USING

> The order in which is you load the components may be very important, depending on the component. If you are not sure, then read the docs for the components you are using and see if they mention anything about the order in which you should load them.

해서 FilterColumn 의 문서를 찾아보았습니다.

https://metacpan.org/pod/DBIx::Class::FilterColumn#SYNOPSIS

> In your Schema or DB class add "FilterColumn" to the top of the component list.

하지만 문서에서 언급한 것 처럼 젤 처음에 두면 안되고, TimeStamp 뒤에 두어야 동작합니다.

**Comment by aanoaa** [comment]
OpenCloset::Schema 0.032 를 설치하고 적용하도록 하겠습니다.

모니터링 해보고 문제 없으면 닫겠습니다.
