### ISSUE TITLE
사용자 정보 화면의 최근 주문 내역에서 방문자의 신체사이즈에 따라 기존 의류의 대여 적합/부적합 여부를 보여줌

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#819]
대여자 재방문시 신체 사이즈의 변화가 있는 경우
신체 치수를 다시 측정하여 입력합니다.

신체 치수를 다시 측정하기 때문에 preparation 화면에서 보여지는 
지난 대여 의류의 기록은 큰 의미가 없습니다. 오히려 그대로 의류를 찾아드리면 문제가 발생합니다.

하지만 현재는 preparation 화면 사이즈가 변경되었다는 내용을 알 수가 없습니다. 
때문에 설명란에 '사이즈 변화'라고 적어 놓고 있습니다. 하지만 설명란에 기입하는 것을 잊어버리는 경우가 많습니다.
버튼으로 존재한다면 사이즈 변경시에도 잊지 않고 입력 할 수 있을 것으로 기대합니다.

사이즈 변경이라는 뜻은  일반적으로 성인의 경우에는 키는 고정되어 있고 체중의 변화만 있으므로 체중 증가 / 체중 감소 버튼이 있다면 쉽게 눌러 표시하고 사이즈 변경 여부에 대한 기록을 잊지 않을 수 있을 것이라 생각합니다.

**Comment by 10001if** [comment]
모니터 이슈도 있는 것으로 보이지만, 기본적으로는 staff 페이지에서 수정되어야 하는 것으로 보여 이 곳에 남겼습니다.

**Comment by 10001if** [comment]
@aanoaa 종전대로 설명란에 텍스트 기록으로 진행하는게 좋겠다고 생각되시면 의견 남겨주세요~ 해야할 작업이 많으신데 반드시 필요한 작업 부터 진행하시는 게 좋은 것 같네요. 요즘 너무 부담을 드리는 것 같아 죄송합니다..

**Comment by keedi** [comment]
급한 이슈가 아닌 것으로 보이니 제가 진행합니다.

**Comment by keedi** [comment]
@10001if 구현을 원하는 방식을 화면 캡쳐후 첨부 부탁드렸는데 어떻게 되셨는지요? 화면을 좀 봐야 이해하기 쉬울 것 같네요. 해당 url도 앞부분 제거 후 같이 알려주세요.

**Comment by 10001if** [comment]
@keedi 처음엔 블라우스를 비고란에 넣는 것처럼 키/몸무게 우측에 `사이즈변화`라는 버튼 추가를 요청드리려고 했습니다. 하지만 조금 더 생각을 해보니 직전 방문과 비교하여 몸무게의 변화가 -3kg, -2kg, -1kg, 변화없음, +1kg, +2kg, +3kg 를 제외하고 -4kg 이하이거나 +4kg 이상인 경우에는 자동으로 `사이즈변화`라는 값이 비고란에 들어가도록 하였으면 좋겠습니다. 이렇게 하면 대부분의 경우 신경 쓰지 않아도 해결이 될 것 같고, 부득이 예외적인 경우에는 저희가 직접 수기로 입력하여도 큰 문제는 없을 것 같습니다. 다시 확인해보니 본 이슈에서 가장 중요한 것은 사이즈가 변화하였음에도 기존의 의류를 찾아 건네주거나 기존의 의류 사이즈와 동일한 의류를 제공하는데 문제가 있는 것이므로 기존의 신체 사이즈가 변화하였다는 정보만 빠뜨리지 않고 알려줄 수 있다면 큰 이슈를 해결될 것으로 보입니다. ^^

**Comment by keedi** [comment]
진행합니다.

**Comment by keedi** [comment]
`/user/7940` 페이지 즉 사용자 프로필 정보 페이지를 말한다고 합니다.

**Comment by keedi** [comment]
최근 주문 내역에 해당 주문서에 포함된 빌린 내역의 의류를 보여주고 해당 의류들의 현재 상태도 보여주기로 했습니다. 이 기능을 추가할 경우 신체 치수를 재는 사람은 해당 주문서의 의류가 대여가능한지 여부를 바로 확인해서 대여자에게 가능 여부를 알려줄 수 있습니다.

**Comment by keedi** [comment]
더불어 최근 주문 내역에 대여자의 몸무게를 확인해서 현재 몸무게랑 비교한 후 -3kg ~ +3kg 이내일 경우 **대여 적합**을 이외일 경우 **대여 부적합**이라고 태그를 달아주기로 했습니다. 이 기능을 추가할 경우 어떤 주문서에 해당 하는 의류가 현재 대여하기 적합한지 신체 치수 측정자가 판단하기 용이해집니다.

**Comment by keedi** [comment]
추가로 **대여 적합** 태그를 클릭할 경우 사용자 정보의 추가 설명란에 현재 주문서에 해당 하는 의류를 요청한다는 문구를 추가하기로 했습니다. 이 기능은 대여자가 특정 일의 주문서에 해당하는 의류를 원할 때 의류 준비하는 사람들한테 전달하기 위한 기능입니다. 기존의 경우 신체 치수 재면서 직접 키보드로 입력했다고 합니다.

**Comment by keedi** [comment]
@10001if 모니터쪽 이슈는 모니터 쪽에 이슈 등록하시면 됩니다.

**Comment by keedi** [comment]
마지막 글 이후 지체되었는데 다시 진행합니다.

**Comment by keedi** [comment]
피드백 받은 내용입니다.

- 최근 주문서의 기존 태그와 같은 줄에 보이길 원합니다.
- 기존 태그보다 조금 크게 보이길 원합니다.
- 대여 적합은 녹색으로 대여 부적합은 붉은색으로 보이길 원합니다.

결과적으로 다음과 같은 모양으로 진행중입니다.

대여 적합일 경우입니다.
![screenshot-monster silex kr 10301 2016-06-23 17-28-44](https://cloud.githubusercontent.com/assets/138451/16296738/a488dd0c-3968-11e6-9f21-0fcb75dd2e03.png)

대여 부적합일 경우입니다.
![screenshot-monster silex kr 10301 2016-06-23 17-29-27](https://cloud.githubusercontent.com/assets/138451/16296743/a9c1885a-3968-11e6-9b12-067e7c499b12.png)

**Comment by keedi** [comment]
대여 적합 버튼을 클릭할 경우 사용자 정보의 설명 하단에 해당 주문서의 의류를 요청한다는 문구를 추가합니다.

![screenshot-monster silex kr 10301 2016-06-23 17-57-08](https://cloud.githubusercontent.com/assets/138451/16297496/0ba72478-396c-11e6-8207-0b98273b7df8.png)

**Comment by keedi** [comment]
각각의 최근 주문 내역에 주문서에서 빌렸던 의류의 현재 상태를 볼 수 있도록 했습니다.

![screenshot-monster silex kr 10301 2016-06-24 14-17-18](https://cloud.githubusercontent.com/assets/138451/16328636/0ce16406-3a17-11e6-90ec-6cdf7703f64a.png)

**Comment by keedi** [comment]
@10001if 피드백 부탁드립니다.

**Comment by keedi** [comment]
`clothes2link` 헬퍼를 사용한 경우 화면입니다.

![screenshot-monster silex kr 10301 2016-06-24 15-12-27](https://cloud.githubusercontent.com/assets/138451/16329511/272c86fe-3a1e-11e6-9f10-24f76c702a8f.png)

**Comment by 10001if** [comment]
네! 지금 확인했습니다~ 다 좋습니다! 다만 의류현황이 대여중일 때는 빨간색으로 대여가능일 때는 파란색으로 반납이나 다른 상태일 때에는 회색으로 표시해주시면 좋을 것 같습니다. ^^

**Comment by keedi** [comment]
`clothes2link`는 클래스를 덮어쓸 수 없고 추가만 할 수 있기 때문에 상기 피드백의 내용을 적용시킬 수가 없습니다. 적용시킨다면 별로 css 클래스를 정의하고 less에서 처리해야 합니다.

**Comment by keedi** [comment]
피드백 받은 내역을 적용한 화면입니다.

![screenshot-monster silex kr 10301 2016-06-24 17-21-51](https://cloud.githubusercontent.com/assets/138451/16332350/710c2880-3a30-11e6-8672-a33e4403f0a9.png)
![screenshot-monster silex kr 10301 2016-06-24 17-22-21](https://cloud.githubusercontent.com/assets/138451/16332351/732f667c-3a30-11e6-8430-22e05fc70146.png)

**Comment by keedi** [comment]
@10001if 피드백 부탁드립니다.

**Comment by keedi** [comment]
피드백 결과 지금 기능이면 된다고 합니다.

P.S.
@10001if 피드백은 가능하면 깃헙에 부탁드립니다.

**Comment by keedi** [comment]
작업 완료됐으므로 이슈 닫습니다.

**Comment by 10001if** [comment]
@keedi @aanoaa 혹시 이 이슈에서 제가 확인할 사항이 있는건가요~?

**Comment by aanoaa** [comment]
아직 배포가 되지 않은 것 같고요.
@10001if 님 확인 절차에 대해선 저희끼리 얘기해서 통일해보도록 하겠습니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
