### ISSUE TITLE
주문서에서의 연장비/연체비 의 자동계산

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#824]
현재는 모두 20% 로 계산하고 있습니다.
하지만 약관이 변경되면서 연체비는 30% 받아야 합니다.

연체비: 오늘 - 반납희망일
연장비: 오늘 - 반납희망일 - 반납 예정일

- `반납 예정일` 과 `반납 희망일` 이 같다면 이 주문서는 연장신청을 하지 않은 것이고 **연체비**를 받아야 합니다.
- `반납 예정일` 과 `반납 희망일` 이 같지 않다면(`반납 희망일` 이 더 커야함) 주문서는 연장신청이 되었고 **연장비**를 받아야 합니다.
- `반납 예정일` 과 `반납 희망일` 이 같지 않고 오늘이 `반납 희망일` 보다 크다면 **연장비 + 연체비**를 받아야 합니다.

예를들어,

오늘이 2016-05-17 이고 반납희망일이 05-10 이고 반납예정일이 05-10 이라면? -> 모두 연체료로 계산(7일)
오늘이 2016-05-17 이고 반납희망일이 05-17 이고 반납예정일이 05-10 이라면? -> 모두 연장료로 계산(7일)
오늘이 2016-05-17 이고 반납희망일이 05-13 이고 반납예정일이 05-10 이라면? -> 연장 3일 연체 4일로 계산

--------------------------------------------

택배를 고려하면, `오늘 = 택배 발송일` 로 계산해야 합니다.

#815 이슈 이후에 진행하면 택배발송일 이슈와 함께 해결될 수 있습니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
