### ISSUE TITLE
출력 가능한 의류 태그

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#827]
새옷등록에서 파생한 이슈이고, 구체적인 내용은 아래 PR 에서 다루어졌습니다.

https://github.com/opencloset/opencloset/pull/778

**Comment by aanoaa** [comment]
Smartmatch is experimental at lib/OpenCloset/Web/Controller/Clothes.pm line 334.

경고메세지가 발생합니다.

    if ( "온라인" ~~ @tags ) {

@keedi: smartmatch 를 사용하지 않고 해결할 수 있을까요?

**Comment by keedi** [comment]
코드 한줄이 빠졌네요. 수정후 PR 하겠습니다.

**Comment by keedi** [comment]
PR 남겨두었습니다.

**Comment by MoDoLEE** [comment]
FujiXerox DocuPrint CP225W 구매 후 설치까지 완료했습니다.
인쇄용지 설정 시 가장 짧게 설정할 수 있는 길이가 76.2mm 입니다.
그래서 일단은 76.2mm x 210mm 로 설정한 상태에서 출력해 봤습니다.
프린터는 2층 사무실에 설치되어 있으니, 확인 부탁드립니다.^^

**Comment by 10001if** [comment]
@keedi 현재 만들어 주신 의류태그는 출력하여 실제 사용하고 있습니다. 하지만, 하복과 동복의 구분이 필요하다는 요청이 추가되었습니다. 의류태그 상단의 색상 표시 변경이 필요한 이슈인데요.

1. `태그명`이 `하복`인 경우 의류 태그 상단의 색상을 `투명색`으로. 즉, 상단에 색상을 넣지 않도록 하구요.
1. `태그명`이 `동복`인 경우 의류 태그 상단의 색상을 `차콜그레이색`으로 출력되도록 하였으면 합니다.

계절별로 하복과 동복을 구분해서 사용해야 하기 때문입니다.

**Comment by keedi** [comment]
@10001if 별도 이슈로 분리 부탁드립니다. :)
