### ISSUE TITLE
주문서에 성별 정보를 넣도록 함

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#829]
주문서와 성별을 연계해서 하는 작업이 좀 되는데 주문서에 성별 정보가 없으니
user 를 통해 user_info 의 성별로 접근해야 해서 불편합니다.

**Comment by yongbin** [comment]
단지 `user`에서 `user_info`로 가는게 불편한 문제라면 `user_info`에 있는 성별을 `user`에 옮기는건 어떨까요? 혹은 `user_info`랑 `user`를 합치는것도 생각해 볼 수 있을거 같습니다.

**Comment by aanoaa** [comment]
제 경우에는 DBIC 사용할때 말고 raw 쿼리할때에
항상 user_info 를 참조해야 하는게 불편합니다.

주문서에 성별 정보가 있으면 더 좋을 것 같습니다.
하지만 기존의 주문서의 성별이 NULL 인것이 문제가 될 수 있을 것 같습니다.

user_info 랑 user 를 합치는 것도 괜찮은 것 같은데,
그러면 일이 너무 커질 것 같습니다.

**Comment by yongbin** [comment]
일단 기본적으로 주로 구현하는 @aanoaa 님이나 @keedi 님 의견이 가장 중요하다고 생각하지만 그냥 제가 원하는바를 그냥 편하게 말씀드리면

1 . `user`랑 `user_info`는 합치되 `user_info`에 `wearon_date` 이후 컬럼은 별도 테이블로 분리하고 update가 아니라 insert형태가 되면 좋겠습니다. 

 2. `order`에 `gender`가 들어가는건 할수는 있지만 여러가지로 악용될 소지가 높기때문에 가능하면 안했으면 좋겠습니다. 

3. 열린옷장 재고관리 시스템이 계속 발전되면서 처음생각했던거랑 지금 사용되는 모양이 다르기때문에 단순하게 컬럼추가하는 수준이 아니라 스키마 구조 자체를 새롭게 수정하는 이슈들을 피할 수 없을거 같습니다.

방향은 두분이 잘 상의해서 결정하면 따르겠습니다. 시키실일 있으면 말씀해주세요

**Comment by aanoaa** [comment]
구조 변경이 필요하다면 미루는 것보다 해야하는게 좋을 것 같습니다.
하지만 온라인 전까지는 뒤로 미루어두는 것이 어떨까 합니다.
(나중에 더 고생할 수도 잇지만..)

**Comment by aanoaa** [comment]
해서 *일단* 닫겠습니다.

**Comment by yongbin** [comment]
넵 저도 같은생각입니다.
