### ISSUE TITLE
반납 직후 서베이가 SMS가 전송되어 피드백을 받음

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#83]
반납한 대여자에게 SMS를 전송하여 필요한 질문사항에 대한 답을 받을 수 있도록 함.
피드백을 요청하고자 하는 질문과 내용은 다시 작성해드리겠습니다.
기명서베이를 요청할 예정임.

**Comment by keedi** [comment]
현재 전혀 아이디어가 없다고 합니다.

이슈 닫습니다. :)
