### ISSUE TITLE
의류 정보 출력 시 밑단 둘레 값이 이상함

### ISSUE THREAD

**Issue by keedi** [opencloset/opencloset#839]
의류 정보에서 밑단 둘레의 값이 이상하게 출력된다고 합니다.

해당 호출 포인트는 다음과 같습니다.

`GET /clothes/:code/pdf`

**Comment by keedi** [comment]
관련 이슈 입니다.

- 의류 정보를 종이로 출력함 #778 
- 출력 가능한 의류 태그 #827

**Comment by keedi** [comment]
데이터베이스에 저장하는 값 자체는 cm이고 UI와 모든 곳에서는 이 값을 inch로 변환해서 보여주고 있(었)습니다. 최근 DBIC에서 `cuff` 메소드를 호출해서 값을 불러오거나 값을 쓸 경우 cm <-> inch 변환을 자동으로 하게 변경된 내역이 있습니다. 관련해서 변경될 때 의류 정보 출력 쪽에 적용되지 않아 발생한 문제로 보입니다.

**Comment by keedi** [comment]
DBIC의 기능을 이용해 자동 cm <-> inch 변환 관련 이슈 항목은 다음과 같습니다.

- OpenCloset::Schema-0.031 버전업 후 주문서 생성시간에 의한 장애 #818

**Comment by keedi** [comment]
배포 후 확인하면 될 것 같습니다.

**Comment by aanoaa** [comment]
배포하시려거든,

fb36a2bef22dee13f2c5577d5f60f137c76524f5

참고 하셔서 몇군데 버전업 해주시고, `develop -> master` merge 하신후에 버전명으로 태그 달아주시면 됩니다. (ex `v1.7.2`)

master 를 다시 develop 으로 merge 하지는 않습니다.

**Comment by keedi** [comment]
그럼 현재 마일스톤 및 버전은 몇이 되야하나요?

**Comment by aanoaa** [comment]
1.8 마일스톤 이슈가 모두 닫히면 그때 `v1.8.0` 이고요,
지금은 `vX.Y.Z` 에서 Z 만 1씩 올립니다.

해서 지금이 `v1.7.1` 이니까 `v1.7.2` 입니다.

**Comment by keedi** [comment]
v1.7.2 릴리스 및 배포 완료 했습니다.

**Comment by keedi** [comment]
이슈 닫습니다.

**Comment by keedi** [comment]
@10001if 의류 태그 출력 기능 확인 부탁드립니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
