### ISSUE TITLE
기증/대여 메세지를 대여자/기증자에게 전달

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#84]
기증자는 기증행위를 한 후 본인의 의류의 대여메세지를
대여자는 대여행위를 한 후 본인이 대여하셨던 의류의 기증/대여메세지를 SMS나 메일로 확인 할 수 있었으면 좋겠습니다.

~~그리고 대여자의 대여메세지는 주문서에 사진을 스캔하여 올릴 수 있게 해주시면 좋을 것 같아요.~~
~~사진을 올리면 정보는 자동으로 저장되어 정리되었으면 좋겠습니다.~~ edited by @keedi

**Comment by keedi** [comment]
> @10001if wrote:
> 주문서에 스캔한 메세지를 업로드 할 수 있는 창구를 만들어 주시면 좋을 것 같습니다. :)

상기 항목은 완전 별도의 이슈입니다. 해당 내역은 본 이슈에서 처리하지 않습니다. 이미지 업로드 관련해서는 따로 말씀드렸던 바가 있는 방식으로 처리할 예정입니다. 즉 페이지에 업로드 기능을 따로 추가하진 않을 계획입니다.

**Comment by keedi** [comment]
역시 시간이 많이 지났으며 현재 시스템이 오픈하기 전에 나누었던 이슈입니다. 여전히 동일하게 생각하시는지 아니면 세부적으로 생각이 바뀐 부분이 있는지 등을 확인하기 위해서라도 새로 논의가 필요합니다.

**Comment by keedi** [comment]
별도의 시스템으로 처리하기로 했습니다. 현재 저장소에서 처리할 필요가 없는 이슈입니다. 추후 진행은 별도의 저장소에서 처리합니다. 이슈 닫습니다.
