### ISSUE TITLE
의류 검색 결과가 정확하지 않음

### ISSUE THREAD

**Issue by yongbin** [opencloset/opencloset#841]
#800 이 진행되는 과정에서 기존 의류검색에서 잘못된 부분이 발견되었습니다. 해당 문제들을 해결해야합니다.

**Comment by yongbin** [comment]
최초 사용자로 부터 받은 정보를 OpenCloset::Size::Guess로 전달하는 과정에서 `topbelly` 항목에 `waist`값을 넣는 실수가 있었습니다. 해당 부분을 수정했고 이후 검색결과를 좀 더 잘 모니터링할 수 있도록 로깅항목들을 개선했습니다. 제 환경에서 테스트할때 체감상 이전보다 검색결과가 훨씬 많아진것 같습니다.

**Comment by yongbin** [comment]
@10001if 배포이후에 한번 확인부탁드립니다.

**Comment by aanoaa** [comment]
관행대로라면
`Change` 에 적고 해결된 이슈는 닫습니다.

그리고 배포후에 Changes 를 보고 해당 이슈로 찾아가서 `확인요망` 라벨을 붙입니다.

**Comment by aanoaa** [comment]
더이상 `배포대기` 는 사용되지 않습니다.

**Comment by yongbin** [comment]
배포가 급한건 아닌데 그럼 그냥 Changes에 timestamp 없이 항목만 추가해두면 될까요?

**Comment by aanoaa** [comment]
네

**Comment by yongbin** [comment]
push 했습니다. ad4f03a15e86091939c1083b3bb8b3524ee7e3ab

**Comment by yongbin** [comment]
## 수정 전

![screen shot 2016-06-03 at 2 46 39 pm](https://cloud.githubusercontent.com/assets/52704/15770054/b2b89aca-299b-11e6-89ac-7a9366484ab3.png)


## 수정후 

![screen shot 2016-06-03 at 2 46 39 pm](https://cloud.githubusercontent.com/assets/52704/15770045/a5fb32f2-299b-11e6-8901-8cd8a5949a19.png)
