### ISSUE TITLE
 의류 태그 PDF 출력시 코트와 원피스의 코드 및 사이즈 내역이 표기되지 않음

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#843]
현재 코트와 원피스의 경우 

1. 상의/하의의 코드명이 표기가 되지 않음
2. 하단의 사이즈 정보에도 사이즈 내역이 표기되지 않음

두 가지 내역에 대해 아래와 같이 수정을 요청드립니다.

1. 상의에 코트, 원피스의 코드가 들어 갈 수 있도록 함
2. 하단에 사이즈 정보에 기존에 입력되어 있는 사이즈가 나타날 수 있도록 함

**Comment by keedi** [comment]
이는 애초에 본 기능이 상의와 하의 세트가 존재하는 의류를 대상으로 만들었기 때문입니다. 원피스와 코트에 대해서도 해당 결과물을 출력해서 의류에 걸어야한다고 하니 예외상황이라고 봐야합니다. 코트와 원피스에 대해 열린옷장이 원하는 방향으로 결과물이 비슷하게 보일 수 있도록 수정합니다.

**Comment by keedi** [comment]
다른 세트 의류와는 다르게 코트와 원피스의 경우 상의 코드에 해당 의류 코드를 표시하고 하의 코드는 비워둡니다. 더불어 색상을 제외한 나머지 세트 상의 치수 정보와 세트 하의 치수 정보 모두  해당 코트나 원피스의 치수 정보를 보이도록 했습니다.

**Comment by keedi** [comment]
작업 완료한 화면은 다음과 같습니다. 치수 정보는 임의로 넣은 것입니다.

![screenshot-05](https://cloud.githubusercontent.com/assets/138451/15770078/df7427dc-299b-11e6-871a-b716858707e5.png)

**Comment by keedi** [comment]
피드백 받은 후 수정 사항이 없다면 ᅟv1.7.3 릴리스 및 배포할 예정입니다.

**Comment by keedi** [comment]
피드백 받았습니다. 문제 없다고 합니다. :)

**Comment by keedi** [comment]
v1.7.3 릴리스 및 실서버에 배포 완료 했습니다.
