### ISSUE TITLE
의류 태그 PDF 출력시 기증자의 이름이 긴 경우 제대로 표시되지 않음

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#844]
기증자의 이름이 8자가 넘는 경우 의류 태그 출력시 비정상적으로 짤리는 현상이 나타나고 있습니다.

본 현상에 대해 수정을 요청드립니다.

**Comment by keedi** [comment]
두 가지 증상이 있습니다.

- 기증자의 이름이 띄어쓰기 없이 긴 경우 테이블이 우측으로 확장되면서 테이블이 제대로 표시되지 않습니다.
- 기증자의 이름이 띄어쓰기가 있지만 긴 경우 한 페이지에 표시가 되지 않고 두 페이지에 나뉘어 표시됩니다.

**Comment by keedi** [comment]
띄어쓰기 없이 긴 경우 갈무리 화면입니다.

![screenshot-01](https://cloud.githubusercontent.com/assets/138451/15766921/86a8218e-297e-11e6-965b-e18f0b9d4482.png)

**Comment by keedi** [comment]
띄어쓰기가 있지만 긴 경우 갈무리 화면입니다.

![screenshot-02](https://cloud.githubusercontent.com/assets/138451/15766930/9c5afd80-297e-11e6-9b3f-c4f9facdc615.png)

**Comment by keedi** [comment]
진행합니다.

**Comment by keedi** [comment]
우선 아래쪽 종이 여백을 줄여서 이름에 띄어쓰기가 제대로 있을 경우 제대로 출력시킨 결과는 다음과 같습니다.

![screenshot-01](https://cloud.githubusercontent.com/assets/138451/15769647/f67d890e-2997-11e6-8957-c73616677215.png)

**Comment by keedi** [comment]
이름에 띄어쓰기가 없을 경우도 있기 때문에 이를 고려해 강제 끊어쓰기를 한 결과는 다음과 같습니다.

![screenshot-02](https://cloud.githubusercontent.com/assets/138451/15769651/fefb480a-2997-11e6-8403-f1fd61978871.png)

**Comment by keedi** [comment]
수정한 내역은 다음과 같습니다.

- 기증자의 이름에 공백이 있고 길 경우 한 줄이 넘어가면 페이지가 추가되는 현상 수정
- 기증자의 이름에 공백이 없고 길 경우 테이블 레이아웃이 깨지는 현상 수정

이로써 한글 기준 약 21자 정도까지는 문제없이 보여줄 수 있을 것으로 사료됩니다.

**Comment by keedi** [comment]
피드백 받은 후 수정 사항이 없다면 ᅟv1.7.3 릴리스 및 배포할 예정입니다.

**Comment by keedi** [comment]
피드백 받았습니다. 문제 없다고 합니다. :)

**Comment by keedi** [comment]
v1.7.3 릴리스 및 실서버에 배포 완료 했습니다.
