### ISSUE TITLE
의류 태그 PDF 출력시 의류 색상 이름이 긴 경우 제대로 출력되지 않음

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#845]
의류 색상이 5음절 이상인 경우에 의류 태그의 우측이 짤리는 현상이 발생하고 있습니다.
차콜그레이의 경우 5단어 인데 이 경우 의류 태그의 짤림 현상을 확인하였습니다. 
수정을 요청드립니다. ^^

**Comment by keedi** [comment]
발생하는 현상을 갈무리한 화면입니다.

![screenshot-03](https://cloud.githubusercontent.com/assets/138451/15767075/199d9cd4-2980-11e6-8124-12d26ef5dce2.png)

**Comment by keedi** [comment]
수정 완료한 화면입니다.

![screenshot-01](https://cloud.githubusercontent.com/assets/138451/15768185/b848f9e2-2989-11e6-937c-a8bfc5b64b6f.png)

**Comment by keedi** [comment]
피드백 받은 후 수정 사항이 없다면 ᅟv1.7.3 릴리스 및 배포할 예정입니다.

**Comment by keedi** [comment]
피드백 받았습니다. 문제 없다고 합니다. :)

**Comment by keedi** [comment]
v1.7.3 릴리스 및 실서버에 배포 완료 했습니다.
