### ISSUE TITLE
출력용 의류 태그 상단에 하복과 동복의 색상을 다르게 표시

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#852]
@keedi 현재 만들어 주신 의류태그는 출력하여 실제 사용하고 있습니다. 하지만, 하복과 동복의 구분이 필요하다는 요청이 추가되었습니다. 의류태그 상단의 색상 표시 변경이 필요한 이슈인데요.

태그명이 `하복`인 경우 의류 태그 상단의 색상을 `투명색`으로. 즉, 상단에 색상을 넣지 않도록 하구요.
태그명이 `동복`인 경우 의류 태그 상단의 색상을 `차콜그레이색`으로 출력되도록 하였으면 합니다.
계절별로 하복과 동복을 구분해서 사용해야 하기 때문입니다.

**Comment by keedi** [comment]
확인할 부분이 있습니다.

현재 의류 색상 구분은 다음과 같습니다.

- 온라인 남성 의류
- 온라인 여성 의류
- 오프라인 남성 의류
- 오프라인 여성 의류

즉 온라인/오프라인과 남성/여성 두가지로 조합해 4가지인 것 입니다. 현재 하복과 동복이라 하심은 하복과 동복이면 상기 4가지를 무시하고 하복용 투명색, 동복용 차콜그레이색으로 표현해달라는 말씀이신지? 아니면 상기 4가지 조합에 2가지를 추가 조합해 8가지 경우를 하시려는 것인지요?

예1)
- 온라인 남성 의류
- 온라인 여성 의류
- 오프라인 남성 의류
- 오프라인 여성 의류
- 하복
- 동복

예2)
- 하복 온라인 남성 의류
- 하복 온라인 여성 의류
- 하복 오프라인 남성 의류
- 하복 오프라인 여성 의류
- 동복 온라인 남성 의류
- 동복 온라인 여성 의류
- 동복 오프라인 남성 의류
- 동복 오프라인 여성 의류

상기 예시 중 1번인지 2번인지 확인 부탁드립니다.

**Comment by keedi** [comment]
피드백 중입니다.

**Comment by keedi** [comment]
온라인은 하복과 동복을 고려하지 않는다고 합니다.

**Comment by keedi** [comment]
오프라인 남성 의류에 한해 동복과 하복 구분을 한다고 합니다. 이때 오프라인 남성 의류도 존재하고 오프라인 남성 하복, 오프라인 남성 동복이 있다고 합니다.

**Comment by keedi** [comment]
최종 결론은 다음과 같습니다.

- 온라인 남성 의류
- 온라인 여성 의류
- 오프라인 남성 의류
- 오프라인 여성 의류
- 하복 오프라인 남성 의류
- 동복 오프라인 남성 의류

**Comment by keedi** [comment]
차콜 그레이는 `#848484` 색상 코드를 이용해달라고 합니다.

**Comment by keedi** [comment]
작업 완료했으나 내부 논의가 더 필요하다고 합니다. 논의를 더 진행한 후 더 좋은 방법이 나온다면 그에 맞게 다시 수정하도록 합니다. 그때까지 일단 병합은 미뤄두겠습니다.

**Comment by keedi** [comment]
일단 언제 결론이 날지 모르므로 마일스톤 변경했습니다. 피드백이 오는 상황에 따라 다시 원래대로 마일스톤을 변경할 수도 있습니다. 아마 다음 주에 최종 결론이 날 것 같습니다.

**Comment by 10001if** [comment]
![2016-06-10 4 16 57](https://cloud.githubusercontent.com/assets/4696328/15957007/24c7fc38-2f27-11e6-8b8c-f532198880aa.png)
논의 결과는 다음과 같습니다.

1. 좌측에 남성/여성/온라인남성/온라인여성을 표시 
2. 우측에 춘추/하복/동복을 표시

* 이때 춘추는 기존 색상으로 표시 / 하복은 #FAED7D / 동복은 #848484 으로 진행 부탁드리겠습니다.

**Comment by 10001if** [comment]
@keedi 의견은 위에 적은 내용으로 모아졌습니다~ ^^

**Comment by keedi** [comment]
진행합니다.

**Comment by keedi** [comment]
춘추 의류의 경우 따로 태그를 확인하지 않는다고 합니다. 춘추라고 태그가 붙기도 하지만 안붙어있어도 춘추라고 인식한다고 합니다. 정리하면 명확히 하복 태그가 붙으면 하복, 동복 태그가 붙으면 동복, 그외에는 다 춘추라고 판단하면 될 것 같습니다.

**Comment by keedi** [comment]
피드백 받으면 오늘 마무리 할 수 있을 것 같습니다. 마일스톤을 v1.8로 변경합니다.

**Comment by keedi** [comment]
최종 확인을 받았습니다. 이대로 머지 진행하겠습니다.

**Comment by keedi** [comment]
머지 완료했습니다.

서버에서 `grunt`를 수행해야 갱신한 내역이 적용됩니다.

**Comment by keedi** [comment]
이슈 닫습니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
