### ISSUE TITLE
사용자 이름의 앞 또는 뒤에 불필요한 빈 칸이 들어감

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#854]
사용자 id `38385` 입니다

인증번호를 받기 위해서 이름과 전화번호를 입력하니까 이름과 전화번호가 일치하지 않는다고..
이름뒤에 공백을 하나 넣으면 된다고 합니다.

**Comment by aanoaa** [comment]
이름에 공백이 포함되어 있습니다.
이름에 공백이 들어갈 수 없도록 해야 할 것 같습니다.

    mysql> select concat(`name`, '<<<') from user where id = 38385;
    +-----------------------+
    | concat(`name`, '<<<') |
    +-----------------------+
    | 홍길동 <<<            |
    +-----------------------+

**Comment by aanoaa** [comment]
staff 가 사용할 수 있는 꼼수로는,
이름을 다르게 변경했다가 다시 원래 이름으로 또 변경하면 됩니다.

**Comment by keedi** [comment]
진행합니다.

**Comment by keedi** [comment]
우선 처리하는 포인트는 다음과 같습니다.

- 온라인 예약시 최초 인증번호를 받기 위해 전화번호와 이름을 입력하는 시점
- 직원 예약의 경우 사용자 추가를 통해 추가 후 진행하므로 처리할 필요가 없음
- 사용자 목록 페이지에서 추가 버튼을 누르는 시점
- 사용자 프로필 화면에서 이름을 클릭 후 수정하는 시점

**Comment by keedi** [comment]
총 세군데에서 이름 앞 뒤로 공백 문자가 들어가는 것을 막아야 합니다.

- `/visit`
- `/user`
- `/user/:user-id`

이 중 `/user/:user-id`의 경우 API를 통해서 처리하는데 이 때 내부적으로 사용하는 `Mojolicious::Plugin::Validator` 모듈이 인자 검증시 앞뒤에 붙는 공백 문자를 처리하지 못해 걸러내지 못하는 현상이 발견되고 있습니다. 예상으로는 내부적으로 앞뒤의 트레일링 스페이스를 순간적으로 떼고 검증하는 것 같은데 어디까지나 추측이고 정확하게 어느 포인트에서 발생하는 문제인지 확인해야 합니다.

**Comment by keedi** [comment]
`Input::Validator::Field` 객체는 무조건 기본 동작으로 값의 앞 뒤 공백을 제거하고 매개변수 검증을 수행합니다. `trim` 메소드가 있는데 이 값이 기본값으로 `1`이었기 때문에 이름의 앞 뒤 공백을 인지해서 처리하기가 힘들었습니다. `trim(0)` 으로 설정하면 제대로 원래 값을 기준으로 검증을 수행할 수 있습니다.

https://metacpan.org/pod/Input::Validator::Field#trim

**Comment by keedi** [comment]
작업 완료했으므로 이슈 닫습니다.

**Comment by keedi** [comment]
결과 화면은 다음과 같습니다.

대여자용 방문 예약 화면에서 오류가 발생하는 경우입니다.
![screenshot-monster silex kr 10301 2016-06-30 17-14-57](https://cloud.githubusercontent.com/assets/138451/16481574/eb9375d0-3ee6-11e6-866d-60c7ab20421f.png)

직원용 방문 예약 화면에서 오류가 발생하는 경우입니다.
![screenshot-monster silex kr 10301 2016-06-30 17-16-20](https://cloud.githubusercontent.com/assets/138451/16481575/efd6296c-3ee6-11e6-88d9-ce79cf2ed5db.png)

사용자 목록에서 사용자 추가시 오류가 발생하는 경우입니다.
![screenshot-monster silex kr 10301 2016-06-30 17-15-40](https://cloud.githubusercontent.com/assets/138451/16481585/f3ba45a4-3ee6-11e6-8141-2825722014c8.png)

사용자 정보 화면에서 이름을 수정할 때 오류가 발생하는 경우입니다.
![screenshot-monster silex kr 10301 2016-06-30 17-17-30](https://cloud.githubusercontent.com/assets/138451/16481589/f86c204a-3ee6-11e6-9f2e-5a6948d3c447.png)

**Comment by 10001if** [comment]
배포대기 중이라 확인은 하지 못하였습니다~

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
