### ISSUE TITLE
자켓 바코드 1000개, 바지 바코드 1500개 요청드립니다.

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#855]
자켓 바코드 1000개, 바지 바코드 1500개 요청드립니다.

**Comment by yongbin** [comment]
donation 에서 LAST CODE를 직접 관리하는 구조로 변경되었기 때문에 @aanoaa 님으로 변경합니다.

**Comment by aanoaa** [comment]
$ ./script/generate_code.pl -h
    Usage:
            $ script/generate_code.pl jacket 10
            $ script/generate_code.pl jacket 10 --save
            $ script/generate_code.pl jacket 10 --save > jacket.csv
    
            $ script/generate_code.pl --list
            $ script/generate_code.pl --help
    
    $ ./script/generate_code.pl jacket 1000 --save > jacket.csv
    -------------------------------------------------
    '-']/ jacket 의류코드가 갱신되었습니다 => J3KY
    $ ./script/generate_code.pl pants 1500 --save > pants.csv
    -------------------------------------------------
    '-']/ pants 의류코드가 갱신되었습니다 => P3B5

**Comment by aanoaa** [comment]
[pants.xlsx](https://github.com/opencloset/opencloset/files/306474/pants.xlsx)
[jacket.xlsx](https://github.com/opencloset/opencloset/files/306475/jacket.xlsx)

**Comment by aanoaa** [comment]
생성하는 법은 donation 의 서비스 디렉토리로 가서,

`/script/generate_code.pl` 스크립트를 실행하면 됩니다.

`--save` 옵션을 주어야지만 DB의 마지막 의류코드가 갱신됩니다.
save 옵션없이하는건 마지막 의류코드가 바꾸지않습니다.
테스트를 위해서 save 옵션없이 해보고, 문제가 없으면 save 옵션을 주시기 바랍니다.

cc @yongbin @keedi

**Comment by yongbin** [comment]
> save 옵션없이하는건 마지막 의류코드가 바뀌지않습니다.

그럼 실서버에서 실행해야겠네요?

**Comment by aanoaa** [comment]
그렇죠
