### ISSUE TITLE
봉사신청 시 `1365 로그인 아이디를 적는 란`의 추가

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#856]

**Comment by aanoaa** [comment]
![screenshot-localhost 5001 2016-06-10 17-37-21](https://cloud.githubusercontent.com/assets/170528/15958811/ad8903d6-2f32-11e6-8f02-96ce9e585a81.png)

**Comment by aanoaa** [comment]
이 기능은 develop 에 머지 되었지만 아직 배포되어선 안됩니다.
OpenCloset::Schema 에 의존성이 있어서 오류를 불러일으킵니다.

새로운 버전의 OpenCloset::Schema 를 배포하고 설치한 후에 적용되어야 하는데,

https://github.com/opencloset/OpenCloset-Schema/issues/75
https://github.com/opencloset/OpenCloset-Schema/issues/76

이슈들이 닫히기는 했지만
적용해도 될지 모르겠습니다.

확인이 된다면 Schema 를 먼저 배포하고 계속해서 진행하도록 하겠습니다.

cc @yongbin @keedi

**Comment by yongbin** [comment]
https://github.com/opencloset/OpenCloset-Schema/releases/tag/release-0.036

OpenCloset::Schema 0.036이 배포되었습니다. 이 릴리즈에 1365관련 작업도 포함되어있습니다. 이 버전으로 배포하시면 될 것 같습니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
