### ISSUE TITLE
다른 단체를 위한 쿠폰 발행 프로세스 추가

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#858]
기존에 **날개 서비스를 통해 신청받았던 경우 외에 추가적으로 예약을 받는 프로세스를 추가하려고 합니다.

경제적인 상황 때문에 면접의상을 구비하지 못하는 학생들에게 제한적으로 `무료 정장대여 서비스`를 진행하려고 합니다. 

이를 위해 필요한 것은 다음과 같습니다.

1. 예약시 쿠폰을 발행할 수 있는 프로세스 추가 (**날개와 같이 예약과 동시에 쿠폰이 발급되도록 함)
2. 방문시 어떤 루트를 통해 방문했는지 확인 할 수 있도록 시간표 등에 정보를 공유
3. 결제시 쿠폰을 통해 무료로 대여할 수 있도록 함

`무료 정장 대여 서비스`를 운영하려다보니 **날개와 형식은 유사하지만 그 외에 단체 추가 이슈가 있습니다. @aanoaa 조언해주시면 단체별로 쿠폰을 발급하고 관리할 수 있도록 하였으면 합니다.

**Comment by aanoaa** [comment]
쿠폰을 발급하고, https://visit.theopencloset.net/coupon 에 입력하면 되긴 합니다만
다른게 필요하신건가요?

취업날개처럼 서비스하고자 한다면,
사용자마다 식별할 수 있는 고유한 무언가가 필요합니다.

**Comment by aanoaa** [comment]
단체별 쿠폰은 모르겠네요.
단체로 와서 대량 대여를 하는건가요?
현재 시스템상에 단체 대여가 없다보니 이거는 쿠폰이슈라기 보다는 단체 대여에 관해서 먼저 생각해봐야 합니다.

**Comment by aanoaa** [comment]
#545 에서 단체 대여에 관한 논의가 있엇는데,
이것은 사이즈 매칭에 관련된 주제였습니다.

이때에 결론은 단체로 오면 종이에 사이즈 적어서 해결한다 였습니다.

**Comment by yongbin** [comment]
제가보기에는 단체로 와서 대량대여를 한다는게 아니라 **서울시/하나은행** 과 같은 단체를 추가로 지원한다는 말씀인거 같습니다.

**Comment by 10001if** [comment]
@aanoaa @yongbin 네~ 제가 표현이 서툴렀네요. `대량대여`가 아니라 다른 단체를 추가하는 개념에 대해 문의 드린 것입니다. ^^

**Comment by aanoaa** [comment]
기본적으로는 쿠폰을 발행해서 나눠주고 사용하면 됩니다.

시스템을 통해서 쿠폰을 발행할 수 있고요,
어떤 단체를 위한 쿠폰인지 구별할 수 있습니다.

앞서 얘기했듯이, 취업날개와 비슷한 방식의 이벤트를 원하시는 거라면,
사용자를 식별할 수 있어야 합니다.

취업날개에선 조건이 있엇죠.

- 개인당 2회 까지
- 총 4000건

여기에서 개인당을 구별하기 위해서 필요한 것이 사용자를 식별할 수 있는 무언가입니다.
그냥 발행한다고 하면 식별하는 절차는 나눠주는 쪽에서 알아서 처리하게 됩니다.

**Comment by aanoaa** [comment]
쿠폰을 발행해서 사용하면 된다고 생각하고 있는데,
쿠폰을 나눠주는 대신에 다른 방법을 찾고 계신건가요?

**Comment by aanoaa** [comment]
원했던 것은 무료로 정장대여를 해주는 것

-> 기존에 만들어 두었던 쿠폰시스템을 활용해서 쿠폰을 발행해서 사용하면 됩니다.

하지만 싫은 것은 발행된 쿠폰을 종이에 인쇄하는 것

-> 다른 방안을 찾아보신다고 했습니다.

어떤 쿠폰인지 구별이 되어야 한다.

-> 구별이 됩니다.

이슈를 진행하기 위해서 고민해서 코멘트를 달고 있습니다.
노티가 많은 건 알겠지만, 찾아와서 말씀하시기 전에 관련된 내용을 읽어주세요.

**Comment by 10001if** [comment]
@aanoaa 말씀하신대로 https://visit.theopencloset.net/coupon 페이지를 이용하여 예약을 받으면 될 것 같습니다. 관계자와 통화를 나눠보았는데요. 우선 수요조사를 한 뒤 필요한 쿠폰 수를 알려주기로 하였습니다. 인원이 정해지면 인원에 약간의 여유 장 수를 더하여 이메일로 발송할 계획입니다. 

그러면 관계자측에서 개인에게 이메일로 쿠폰 번호를 나눠준다고 하네요. 이렇게 진행하면 무리가 없을 것 같습니다~ 그리고 관련 내용 확인해서 찾아뵙게요~ 항상 감사합니다~ ^^

**Comment by 10001if** [comment]
@aanoaa 추가적으로 본 단체의 이름은 `십시일밥`입니다. 혹시 `취업날개`처럼 십시일밥을 통해 방문한 경우 시간표상에 나타나고 누계정보도 통계화면에서 확인할 수 있는지 궁금합니다~

**Comment by aanoaa** [comment]
누계정보에 대한 작업은 필요합니다.
시간표에서는 구별되어서 표시됩니다.

**Comment by 10001if** [comment]
@aanoaa 네~! 알겠습니다~ 단체측에서 연락이 오면 다시 말씀드리겠습니다~ 참고로 종강 시기인 6월 말에 쿠폰 발송을 계획한다고 합니다.

**Comment by aanoaa** [comment]
@10001if 
6월말인데 별 소식이 없네요.
진행되면 다시 열어주세요.

**Comment by 10001if** [comment]
@aanoaa 연락을 주기로 한 단체는 7월 말 즈음에 진행하는 것이 좋을 것 같다고 연락을 주셨구요. 다른 단체와 MOU를 맺고 진행하는 건이 하나가 더 있습니다. "관악고용"이라는 이름으로 쿠폰 50장을 발급해 주시면 되는데요. 계획으로는 월 20명 제한으로 무상대여를 진행하려고 하고 있습니다. 첫 시작은 2달 분으로 진행해 보려고 합니다.

**Comment by aanoaa** [comment]
이런식의 이벤트가 늘어나게 될 것 같은데,
이벤트가 늘어나면 자동으로 통계가 계산되면 좋겠습니다.

**Comment by aanoaa** [comment]
쿠폰을 발행하기 위해 필요한 정보

- 이게 수트 한벌 대여인지 아니면 금액에 따른 쿠폰인지?
- 언제까지 사용할 수 있는 쿠폰인지 아니면 사용기간 같은거 없는건지?
- 설명(혹은 이벤트 이름?) 어떤 목적의 쿠폰인지 구분이 필요하다면

**Comment by aanoaa** [comment]
- `suit` 타입으로
- 사용기간은 2016/12/31 까지
- 설명은 `관악고용`
- 50장

**Comment by aanoaa** [comment]
시간표에 `관악고용` 이라고 표시가 되어야 합니다.

**Comment by aanoaa** [comment]
https://github.com/opencloset/opencloset/issues/730#issuecomment-195264116 코드를 참고해서 쿠폰을 발행합니다.

**Comment by aanoaa** [comment]
```perl
#!/usr/bin/env perl

use v5.18;
use utf8;
use strict;
use warnings;
use open ':locale';

use Algorithm::CouponCode qw(cc_generate cc_validate);

use OpenCloset::Schema;

my $CONF   = require 'donation.conf';
my $schema = OpenCloset::Schema->connect(
    {
        dsn      => $CONF->{database}{dsn},
        user     => $CONF->{database}{user},
        password => $CONF->{database}{pass},
        %{ $CONF->{database}{opts} },
    }
);

my $type    = 'suit';
my $desc    = 'gwanak';
my $expires = '2016-12-31T23:59:59';

for ( 1 .. 50 ) {
    my $code = cc_generate( parts => 3 );
    my $coupon = $schema->resultset('Coupon')->create(
        {
            code         => $code,
            type         => $type,
            desc         => $desc,
            expires_date => $expires
        }
    );

    print STDERR "Couldn't create a new Coupon" unless $coupon;
}

print "Coupon created\n";
```

**Comment by aanoaa** [comment]
![screenshot-localhost 5001 2016-07-01 16-26-49](https://cloud.githubusercontent.com/assets/170528/16514788/1d0a39ec-3fa9-11e6-8522-41801591c993.png)

**Comment by aanoaa** [comment]
@10001if email 을 통해 50장의 쿠폰을 전달해 드렸습니다.

https://visit.theopencloset.net/coupon 에서 입력해서 사용할 수 있습니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^

**Comment by yongbin** [comment]
배포완료했습니다. 확인해주세요

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
