### ISSUE TITLE
주문서에 이벤트 쿠폰을 사용

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#860]
취업날개 이벤트를 모른채로 예약했다가,
대여장소에서 알게되어서 다시 예약하시는 분이 종종 있다고 합니다.

번거로움을 줄이기 위한 방법이 있으면 좋겠습니다.

-------------------

일단 서울시일자리플러스센터에 가입하는 것은 필수 입니다.
정상정인 루트를 통해서 방문예약 페이지를 통해 쿠폰을 받고 난뒤에,
추가 옵션이 있으면 되지 않을까 싶습니다.

**Comment by aanoaa** [comment]
그냥 예약후에
취업날개를 통해서 다시 예약을 하면
쿠폰이 적용되지 않습니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
