### ISSUE TITLE
주문서 메모가 여러번 입력됨

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#866]
/user/38868

버그인것 같은데,

여러번 입력되어 있습니다.

![screenshot-staff theopencloset net 2016-06-17 12-34-16](https://cloud.githubusercontent.com/assets/170528/16139999/e2ad7498-3487-11e6-8305-8e00f1aae11f.png)

**Comment by keedi** [comment]
6월 17일 서버에서 로그상으로 봤을때는 Text::Haml 모듈이 업데이트 된 것으로 보입니다. 최신 버전으로 업데이트 되면서 템플릿 캐시 관련 문제가 생긴것으로 보이며 해당 주문서의 의류를 포장에서 결제로 넘기는 상황에서 오류가 발생하며 다음 화면으로 넘어가지 못했을 것입니다.

```
development.log.11:[Fri Jun 17 12:16:37 2016] [error] Template error in "order/order.html.haml": Can't call method "user_id" on an undefined value at /.....
```

포장에서 결제로 넘어가는 과정에 사용자 프로필의 메모가 주문서로 복사를 하는데 이때 이미 복사는 했지만 오류가 나서 담당자는 이후 진행을 못해 계속 포장을 시도 했을 것입니다. 실제로 25번의 시도를 했으며 계속 실패한 로그가 있습니다.

따라서 이것은 주문서 메모를 저장하는 과정에 생긴 버그가 아니라 시스템 내의 다른 오류로 인해 주문서 메모를 입력하는 절차가 여러번 수행되어 발생한 이슈입니다.
