### ISSUE TITLE
의류사진의 업로드

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#869]
의류사진을 업로드 할 수 있도록 합니다.
아주 간단했으면 좋겠습니다.

**Comment by aanoaa** [comment]
https://avatar.theopencloset.net 을 이용하도록 합니다.

**Comment by aanoaa** [comment]
https://staff.theopencloset.net/clothes/P028
테스트해보느라고 제 프로필 사진을 대신 올려봤습니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
