### ISSUE TITLE
계절에 맞는 의류가 먼저 검색되도록 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#870]
의류 검색시 현재는 대여 횟수를 기준으로 검색이 이뤄지고 있습니다.
때문에 현재 계절시점에서는 하복이 검색되어야 하나, 
계절적인 이슈와 관계없이 검색이 진행되고 있습니다.

따라서 계절, 색상, 잔차제곱합(?) 순으로 대여 검색이 이뤄지도록 요청드립니다.

**Comment by yongbin** [comment]
테그에 기록된 의류의 종류는 다음 3가지 입니다.
 - 동복
 - 하복 
 - 춘추복 

이중 동복과 하복은 서로 비시즌에 `대여불가` 상태를 지정하기때문에 검색에 반영될 위험이 없습니다. 하지만 춘추복과 동/하복은 검색결과에서 섞여서 나오기때문에 열린옷장입장에서 다음 3가지 경우가 생길 수 있습니다.

 1. 춘추복 선호
 2. 동복 선호 
 3. 하복 선호

@10001if 님과 말씀나눠본 결과 이 열린옷장입장에서 봄,여름,가을,겨울이 변하는 시점에 유동적이기때문에 검색에서 특정시점을 기준으로 어느쪽 선호를 이용할지 관련된 설정을 추가해야합니다.

**Comment by yongbin** [comment]
@10001if 

현재 의류중 계절 관련 태그의 입력 상태를 점검해봤습니다.

```sql
SELECT b.`name`, COUNT(*) AS cnt
FROM `clothes_tag` AS a INNER JOIN `tag` AS b ON a.`tag_id` = b.`id`
GROUP BY b.`id`
HAVING b.`name` IN ('봄', '동복', '가을', '하복')
ORDER BY cnt DESC
```

결과

```
|------+-----|
| tag  | cnt |
|------+-----|
| 하복 | 316 |
| 동복 | 284 |
| 봄   |   6 |
| 가을 |   6 |
|------+-----|
```

남성 자켓 보유의류가 약 2000개인점을 고려할때 태그정보가 너무 적습니다. 또한 봄/가을을 구분할지 여부도 결정해야합니다. 이 이슈진행을 위해서는 의류에 계절태그를 어떻게 할당할지 결정하고, 전체적으로 의류에 계절태그를 할당하는 작업이 필요합니다.

**Comment by 10001if** [comment]
@yongbin 오늘 오전에 회의를 진행하였습니다. 기존의 여름에 하복을, 겨울엔 동복을 우선으로 제공해야 한다는 원칙에는 변함이 없지만, 춘추/여름/겨울 세가지로 나누는 것에 대한 의견들이 조금 엇갈렸습니다. 이 부분에 대한 고민이 조금 더 필요해 보입니다. 문제가 되는 것은 이상의 3가지 범주 밖에 있는 의류들에 대한 고민입니다.

**Comment by yongbin** [comment]
오늘 추가적으로 @10001if 님과 상의해서 내린 결론입니다. 

계절의류는 검색결과 정렬에는 반영하지 않고 대신 검색결과화면에서 아이콘등으로 정보제공하고 옷장지기가 눈으로 보고 판단하는 방식으로 합니다.

**Comment by 10001if** [comment]
어떤 방식으로 문제를 해결할지 고민이 더 필요합니다. 우선 이슈 닫도록 하겠습니다.
