### ISSUE TITLE
바지길이-다리길이<11 되도록 검색을 요청

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#871]
사람의 다리길이와 의류의 바지길이 차이가 11 미만인 경우에만 의류검색이 되도록 요청드립니다.

**Comment by keedi** [comment]
본 이슈가 어떤 이슈인지, 현재 상태는 어떠한지, 어떻게 수정해야하는지 정리 부탁드립니다. 제목만 보았을때는 간단해보이는데 그렇지 않은 이슈라면 관련 내용 정리 바랍니다.

@10001if 
더불어 본 이슈는 여전히 필요한 이슈인지 확인 부탁드립니다.

**Comment by 10001if** [comment]
@keedi 이 이슈가 등록되었던 시점에서 살펴보면, 사람의 다리길이에 비해 너무 긴 바지가 추천될 경우 길이를 많이 수선해야 되기 때문에 수선의 상태가 좋지 못하게 될 가능성이 높습니다. 때문에 11cm 이내로 검색되도록 요청드린 것입니다. 하지만 확인해보니 당장 급하게 해결해야 하는 이슈가 아니고 이 문제보다는 신체 사이즈 측정의 정확도를 높이는 부분이 먼저 해결되어야 하는 과제라고 합니다. 우선 이슈는 닫도록 하겠습니다.
