### ISSUE TITLE
주문서에 사용자의 대여이력횟수를 표시

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#872]
재방문자의 경우 결제할때의 안내를 덜고자 위함

**Comment by aanoaa** [comment]
단순하게 생각하면 주문서의 갯수를 세면 되지만,
미방문 혹은 대여를 하지 않은 주문서라면 대여안내를 받은적이 없으므로
반납된 주문서의 갯수를 헤아려야 하겠습니다.

**Comment by aanoaa** [comment]
![screenshot-localhost 5001 2016-06-24 11-08-41](https://cloud.githubusercontent.com/assets/170528/16326616/377dddde-3a03-11e6-8107-5df14faaf67c.png)

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^

**Comment by aanoaa** [comment]
좀 ㄷㅓ 강렬하게 강조해야합니다.

**Comment by aanoaa** [comment]
![screenshot-localhost 5001 2016-07-04 13-33-02](https://cloud.githubusercontent.com/assets/170528/16551004/8e126ae2-41ed-11e6-83da-47eb10249f14.png)

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
