### ISSUE TITLE
주문확정후에 발송되는 SMS 에 열린옷장 반납주소를 포함

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#876]
> 1. 택배로 발송을 하신 경우: <%= url_for("/order/$order_id/return")->to_abs %> 를 클릭하여 반납택배 발송알리미를 작성해주세요.

    서울시 광진구 아차산로 213(화양동 48-3번지) 웅진빌딩 403호 열린옷장

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
