### ISSUE TITLE
대여일 계산이 잘못되었음

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#879]
![2016-07-02 3 09 31](https://cloud.githubusercontent.com/assets/4696328/16538712/1a1e98e0-4067-11e6-9fc7-732e796e772c.png)
그림과 같이 대여일 계산이 잘못되어진 것으로 보입니다.
수정을 요청드립니다.

**Comment by keedi** [comment]
@yongbin 이거 제가 오타 넣었던 것 때문에 생긴 현상인지 확인 부탁드립니다.

**Comment by yongbin** [comment]
네 맞습니다. 지금 OpenCloset::Schema 0.037 릴리즈해서 배포하도록 하겠습니다.

**Comment by yongbin** [comment]
배포 완료되었습니다.

![screen_shot_2016-07-07_at_8_22_56_pm](https://cloud.githubusercontent.com/assets/52704/16651707/be5d7274-4480-11e6-9971-d041f28476a7.png)

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
