### ISSUE TITLE
재고관리 시스템에 wiki 를 도입

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#880]
다른 staff 들이 github repo 의 wiki 를 직접 사용하기는 어려움이 있어서
재고관리 시스템의 메뉴로써 wiki 를 넣고 활용하고 싶다고 합니다.

**Comment by aanoaa** [comment]
https://github.com/blog/699-making-github-more-open-git-backed-wikis

**Comment by 10001if** [comment]
@aanoaa 기존에는 모든 대화가 한 방안에서 이루어졌기 때문에 따로 기록하는 것이 큰 문제가 되지 않았습니다. 하지만 최근에 일요일 오픈을 하면서 월-금 근무직원과 토-일 근무직원 간의 정보 격차가 점점 커지고 있습니다. 월-금 근무자들이 업무에 관해 기록한 정보를 그대로 메뉴얼로 활영하고 토-일 근무자들이 이를 보고 학습하고 의견을 추가하면서 내용에 대해 숙지하는 것이 매우 중요해 졌습니다. 위키 사용방법은 교육과 훈련을 통해 극복하고자 합니다. 논의 후에 위키 문서를 프로그램에서 누적하고 활용할 수 있도록 추가 요청드립니다. 마일스톤을 맨 앞으로 옮기겠습니다. ^^

**Comment by aanoaa** [comment]
위키서비스를 직접 운영할 필요가 없다고 생각됩니다.
허가된 사용자에게 r/w 가능한 위키 서비스를 재고관리에서 링크를 걸어주는 작업입니다.

그렇게 된다면 사용자들은 해당 서비스에 별도의 회원가입을 해야 할 것입니다.

**Comment by aanoaa** [comment]
맘에드는 위키서비스를 직접 사용하시는게 좋을 것 같습니다.
재고관리에는 접근성을 위한 링크만이 추가될 뿐입니다.

브라우저의 즐겨찾기 기능을 활용해도 대체 가능하다고 여겨집니다.

**Comment by MoDoLEE** [comment]
@aanoaa @10001if 원래는 mediawiki 같은 설치형 위키를 서버에 설치해서 사용하면 어떨까 생각했는데, 검색하다 보니 최근 위키독이라는 서비스가 오픈했다고 합니다. 우리나라 서비스이고 사용법이 어렵지 않아서 이 서비스를 이용하면 어떨까 합니다.
http://ko.opencloset.wikidok.net
계정은 기존 사용하던 것과 동일합니다.

**Comment by 10001if** [comment]
@MoDoLEE 아직 다 살펴보지 못했지만, 본 기능이면 생각하고 있는 이슈를 정리하는데 무리가 없을 것으로 보여집니다. 구체적으로 기능을 살펴본 후 사용여부를 결정하도록 하겠습니다.

**Comment by aanoaa** [comment]
일단은 제 이슈가 아닌 것 같아서 변경하였습니다.

**Comment by 10001if** [comment]
@aanoaa 별도의 사이트에서 사용해 보기로 하였습니다. 사용 후 이슈가 생기면 다시 요청드리도록 하겠습니다. 이슈 닫겠습니다.
