### ISSUE TITLE
사용자의 팔길이별 바지길이의 최소/최대값

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#881]
팬츠의 총장길이 수선을 위해 필요한 데이터 입니다.

**Comment by aanoaa** [comment]
cc @10001if

    mysql> SELECT arm, MIN(pants), MAX(pants) FROM user_info WHERE pants IS NOT NULL AND pants != 0 GROUP BY arm;
    SELECT arm, MIN(pants), MAX(pants) FROM user_info WHERE pants IS NOT NULL AND pants != 0 GROUP BY arm;
    +------+------------+------------+
    | arm  | MIN(pants) | MAX(pants) |
    +------+------------+------------+
    | NULL |         94 |        255 |
    |   48 |         90 |         90 |
    |   49 |         83 |         90 |
    |   50 |         90 |         91 |
    |   51 |         90 |        230 |
    |   52 |         84 |         97 |
    |   53 |         85 |        100 |
    |   54 |         83 |        105 |
    |   55 |         80 |        270 |
    |   56 |         88 |        113 |
    |   57 |         87 |        107 |
    |   58 |         80 |        110 |
    |   59 |         80 |        112 |
    |   60 |         90 |        270 |
    |   61 |         83 |        112 |
    |   62 |         90 |        113 |
    |   63 |         90 |        114 |
    |   64 |         80 |        111 |
    |   65 |         96 |        112 |
    |   66 |         92 |        115 |
    |   67 |         99 |        112 |
    |   68 |         97 |        112 |
    |   69 |        102 |        113 |
    |   70 |        104 |        110 |
    |   99 |        100 |        100 |
    +------+------------+------------+
    25 rows in set (0.01 sec)

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
