### ISSUE TITLE
검색 범위 변경 및 검증

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#884]
허리둘레를 확인해 봤을 때.

기존에는 -1 ~ +2 였는데.

@yongbin -1 ~ +5가 더 합리적이라고 하시네요.

확인 부탁드립니다.

**Comment by yongbin** [comment]
`ocarina` 에서 다음과 같은 방식으로 대여된 의류와 대여자의 치수 차이를 보면 현재 적용되어있는 범위보다 IQR 범위가 더 넓게 나옵니다 

![rplot](https://cloud.githubusercontent.com/assets/52704/16651004/1c7da69e-447c-11e6-99e4-dd0ea85edf98.png)

현재 검색결과 필터로 사용하고 있는 범위값을 경험에 의존하지 말고 기존 대여기록을 통해 조정하는것이 가능할 것 같습니다.

**Comment by 10001if** [comment]
어떤 방식으로 문제를 해결할지 고민이 더 필요합니다. 우선 이슈 닫도록 하겠습니다.
