### ISSUE TITLE
의류 검색시 색상에 따른 정렬

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#886]
의류 검색 후 제공되는 순위에서
1지망으로 원한 의류의 색상이 우선적으로 검색될 수 있도록 수정을 요청드립니다.
1지망으로 원한 의류 색상 뒤에는 오차범위에 따라 재정렬되도록 순위를 변경해주시기 바랍니다.

**Comment by yongbin** [comment]
진행합니다.

사용자의 희망 의류는 `user_info`에 `pre_color` 컬럼에 콤마로 분리된 형태로 저장되어있습니다. 1지망 의류는 이중 첫번색상이며 다음 쿼리로 확인할 수 있습니다.

```sql
SELECT SUBSTRING_INDEX(`pre_color`,',',1)   AS 'fav_color'
        ,COUNT(*)                           AS 'cnt'
FROM `user_info`
WHERE `pre_color` IS NOT NULL
GROUP BY SUBSTRING_INDEX(`pre_color`,',',1)
ORDER BY cnt DESC
```
결과는 다음과 같습니다. 

```
|--------------+-------|
| color        |   cnt |
|--------------+-------|
| black        | 11811 |
| staff        |  6892 |
| navy         |  3189 |
| dark         |  2742 |
| charcoalgray |   524 |
| etc          |   232 |
| gray         |   130 |
| brown        |    60 |
|              |     3 |
|--------------+-------|
```

이 중 `staff`, `etc`, `NULL` 을 제외한 색상을 사용자의 1지망 선호색상으로 인지하고 정렬에 반영해야합니다.

**Comment by yongbin** [comment]
세트의류의 색상은 이론적으로 상하의가 같아야 하지만 직원입력실수 등으로 상하의가 다른경우가 있습니다. 검색의 기준은 상의의 색상을 기준으로 하겠습니다.

**Comment by yongbin** [comment]
기존에는 전체 옷을 다음과 같은 방식으로 오차(rss)로 정렬했습니다.

```perl
@result = sort { $a->{rss} <=> $b->{rss} } @result;
```
하지만 옷의 선호색상이 반영된다면 다음과 같이 먼저 선호색상에 해당하는 목록을 오차로 정렬하고 그 후 비 선호 색상의 목록을 오차로 정렬한 뒤 둘을 합쳐야 합니다.

```perl
    if( $fav_color && any { $fav_color eq $_ } @colors ) {
        my @target_color    = sort { $a->{rss} <=> $b->{rss} } grep { $_->{color} eq $fav_color } @result;
        my @nontarget_color = sort { $a->{rss} <=> $b->{rss} } grep { $_->{color} ne $fav_color } @result;

        $self->log->info( "guess fav color / rss limit  : $fav_color / $rss_limit" );
        @sorted = (
            grep { $_->{rss} < $rss_limit } @target_color,
            grep { $_->{rss} < $rss_limit } @nontarget_color,
        );
    } else {
        @sorted = sort { $a->{rss} <=> $b->{rss} } @result;
    }
```

또한 검색결과가 상당히 많을경우 monitor 에서 노출되는 10개 전부가 선호색상일 수 있는데, 이때 _오차가 일정범위보다 큰옷들도 모두 표시되는것이 맞는지_는 @10001if 님과 논의해야 합니다. 현재 구현에서는 오차의 상한을 15로 지정하고 선호색상과 비선호 색상을 모두다 범위 내 의류만 정렬하도록 구현했습니다.

**Comment by yongbin** [comment]
## 검색 대상 

![screenshot_2016-07-17_11_59_11](https://cloud.githubusercontent.com/assets/52704/16898511/9eb0f18c-4c17-11e6-994a-b33310745a91.png)

## 검색 결과

![screenshot_2016-07-17_12_09_00](https://cloud.githubusercontent.com/assets/52704/16898512/a0e307a6-4c17-11e6-851e-54d6ef4dacf7.png)

**Comment by yongbin** [comment]
확인결과 `어둔운계열`(dark) 같은 경우 선호 의류에는 존재하지만, 의류의 컬러에는 존재하지 않기때문에 빼야할것으로 보입니다.

**Comment by yongbin** [comment]
이 이슈를 해결하는 코드를 #905 PR로 보냈습니다. 세부적인 동작에 대한 피드백을 @10001if 님께 받은후 최종 머지하겠습니다.

**Comment by yongbin** [comment]
@10001if 님과 확인했습니다.

지금 구현과 도일한 방식으로 하고 다만 오차에 의한 제한 부분만 적용하지 않기로
했습니다. 오차 제한은 적용이후 판단하기로 했습니다.

**Comment by yongbin** [comment]
v1.8.12 로 배포되었습니다.

**Comment by 10001if** [comment]
확인하였습니다. 정상적으로 잘 동작하고 있습니다.

**Comment by yongbin** [comment]
> 또한 검색결과가 상당히 많을경우 monitor 에서 노출되는 10개 전부가 선호색상일 수 있는데, 이때 오차가 일정범위보다 큰옷들도 모두 표시되는것이 맞는지는 @10001if 님과 논의해야 합니다. 현재 구현에서는 오차의 상한을 15로 지정하고 선호색상과 비선호 색상을 모두다 범위 내 의류만 정렬하도록 구현했습니다.

최종적으로 오차상한을 적용하지는 않았지만 위에서 언급한 사례가 관찰되어서 기록을 위해서 남겨둡니다.

![screen_shot_2016-07-20_at_11_12_32_am](https://cloud.githubusercontent.com/assets/52704/16973090/7acd1e5c-4e6b-11e6-84b6-8ab334f5dcd5.png)

**Comment by 10001if** [comment]
@yongbin 오늘 아침 회의 때 한번 더 공유하였습니다. 적정 점수 범위를 확인하기로 했는데 다만, 옷이 많은 경우 15점 넘는 의류까지 입혀드리지 못하는 경우가 많아 그 점이 어려울 것으로 예상된다고 하네요. 그래도 최대한 확인해서 피드백 드리겠습니다.
