### ISSUE TITLE
의류검색시 의류의 버튼 수에 따른 정렬방식의 변경

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#887]
의류 검색 후 제공되는 순위에서
목적이 면접 인 경우 수트가 2 버튼인 의류가 우선적으로 검색될 수 있도록 수정을 요청드립니다.
2버튼 위류 뒤에는 오차범위에 따라 재정렬되도록 순위를 변경해주시기 바랍니다.

**Comment by 10001if** [comment]
@yongbin 이 이슈는 제가 조금 더 고민을 해보겠습니다. 어떤 목적에 따라 어떤 버튼을 보여줄지는 조금 더 고민이 필요해 보입니다.

**Comment by 10001if** [comment]
목적이 면접인 경우에만 2버튼 수트를 우선적으로 추천해 주도록 요청드립니다.

**Comment by yongbin** [comment]
#870 과 동일한 결론입니다. 의류 검색결과에서 의류의 버튼수는 검색결과 우선순위에 반영하지않고, 정보만 화면에 표시하는 방향으로 진행하기로 했습니다.

**Comment by 10001if** [comment]
어떤 방식으로 문제를 해결할지 고민이 더 필요합니다. 우선 이슈 닫도록 하겠습니다.
