### ISSUE TITLE
검색에서 세트의류 인식 범위 확장

### ISSUE THREAD

**Issue by yongbin** [opencloset/opencloset#888]
현재 검색구현에서 세트의류는 대여기록을 기반으로 계산하고 있기때문에 `suit` 테이블에 존재하는 의류중 한번도 세트로 대여되지 않은 신규의류가 검색대상에 진입할 기회가 없는 문제가 있습니다. 조금 더 많은 검색결과를 확보하기 위해서 검색에서 세트의류를 인식하는 범위를 확장해야합니다.

**Comment by 10001if** [comment]
![39c5df65b8dbef1de147b4db863e1326](https://cloud.githubusercontent.com/assets/4696328/20474871/15119216-b00c-11e6-803b-52110d661782.png)

화면에서 보듯이 남성 의류 추천 시 세트가 아닌 의류가 추천되며,
P198의 경우 정선일님의 의류가 아니고 최치곤님의 의류인데 마우스 오버한 경우 정선일님의 의류로 나옵니다.
그리고 네번째 추천된 의류에는 또 같은 P198이 있고, 최치곤님 의류로 정상 표시됩니다.

프로그램상에 세트는 정상적으로 잘 맺어져 있는 상태입니다.
P198이 J0LM로 함께 대여된 기록은 딱 한번 있으며,
짝벌로 대여하신것도 아니고, 여러벌 대여하면서 같이 대여하신 경우입니다.
세트 추정 시 프로그램에 등록된 세트를 기준으로 하거나,
현재와 같이 대여 기록으로 세트를 추정할 경우 여러 벌 대여한 경우는 제외해야 될 것 같습니다.

**Comment by 10001if** [comment]
@yongbin 의류 세트를 맺어진 것으로 할지 기존대로 할지는 논의가 좀 더 필요해 보입니다..

**Comment by 10001if** [comment]
@yongbin 현장에서 의류 세트화가 얼마나 되어 있는지는 전수조사가 아니면 확인하기가 힘들 것 같습니다. 따라서 대여가능, 반납 상태의 남성의류의 세트 정보를 살펴보고 세트가 되어 있지 않은 의류를 뽑아서 직접 의류를 찾아 세트화 하는 방법을 고민해 보아야 할 것 같습니다.

**Comment by yongbin** [comment]
현재 검색에서 사용하는 세트인식부는 `suit` 테이블이 만들어지기 이전에 구현되었기 때문에 기본적으로 과거 **함께** 대여된 이력이 있는 의류중 가장 자주 함께 대여된 의류를 세트로 **간주**하는 방식으로 동작하기때문에 말씀하신 문제가 발생한 소지가 있습니다. 관련해서 `suit`테이블이 완벽하다면 기존 구현코드를 전부 버리고 단순하게 `suit`쪽 결과를 사용하려고 했었는데 만약 문제가 있다면 적절한 선에서 아래와 같이 두 결과를 혼합하는 형태로 사용하는게 좋을것 같습니다.

1. 먼저 `suit`을 탐색.
2. 결과가 있다면 `suit`정보를 사용
3. 결과가 없다면 기존 대여기록을 바탕으로 한 세트 추정 사용

**Comment by yongbin** [comment]
https://github.com/opencloset/monitor/issues/138 을 통해서 이제 모든 세트의류는 `suit`에 등록되었다는 연락을 받았습니다. 위에 이야기한 검색범위 확장을 진행해야합니다.

**Comment by 10001if** [comment]
어떤 방식으로 문제를 해결할지 고민이 더 필요합니다. 우선 이슈 닫도록 하겠습니다.
