### ISSUE TITLE
예약 화면에서 사용자 이름 팝업 메뉴 하부의 예약 취소 선택시 주문서가 삭제됨

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#889]
주문이 확정된 후에 궁금해서 예약 취소를 눌러보았습니다.
결과는 주문서가 삭제됨.

```
박ㅅㅎ

J1K0
K0D3
B0Q4
```

한시간마다 백업이 돌고 있기 때문에 운이 좋다면 찾을 수 있지만 그렇지
않다면 적당히 만들어줘야 합니다.

그래야 반납 받을때에 문제가 없습니다.
다만 SMS를 보내지 않아야 합니다.

API 에 주문서의 상태에 따라서 삭제가 되지 않도록 하는 기능도 추가
되어야 하겠습니다.

**Comment by aanoaa** [comment]
관련된 주문서 id 는 `34157` 입니다.
삭제된 후에 staff 에 의해 다시 만들어진게 아닌가 합니다.

@10001if 삭제후에 다시 만든 것이 맞나요?
전달해주신 쪽지와 대여 의류가 다릅니다 어느 것이 정확한 것인가요?

**Comment by aanoaa** [comment]
주문서는 새로 만들어진 것이라고 합니다.

`J1K0` 을 `34157` 주문서에 넣고, `K0D3`, `B0Q4` 를 대여가능으로
변경해야 합니다.

**Comment by aanoaa** [comment]
- `J1K0`
- `K0D3`
- `B0Q4`

의류를 대여가능으로 변경

    UPDATE clothes SET status_id = 1 WHERE code IN ('0J1K0', '0K0D3', '0B0Q4');

`J1K0` 을 `34157` 주문서에 추가
자켓을 등록하지 못해서 치마에 자켓가격이 포함되어 있으므로 금액을 `0`원 으로 처리합니다.

    INSERT INTO order_detail (order_id, clothes_code, status_id, name, price, final_price, stage, create_date) VALUES (34157, '0J1K0', 2, 'J1K0 - 자켓', 10000, 0, 0, NOW());

다시 `J1K0` 을 대여중 상태로 변경

    UPDATE clothes SET status_id = 2 WHERE code = '0J1K0';

**Comment by aanoaa** [comment]
``` sql
UPDATE clothes SET status_id = 1 WHERE code IN ('0J1K0', '0K0D3', '0B0Q4');
INSERT INTO order_detail (order_id, clothes_code, status_id, name, price, final_price, stage, create_date) VALUES (34157, '0J1K0', 2, 'J1K0 - 자켓', 10000, 0, 0, NOW());
UPDATE clothes SET status_id = 2 WHERE code = '0J1K0';
```

**Comment by aanoaa** [comment]
서버에 반영하였습니다.

**Comment by aanoaa** [comment]
데이터는 올바르게 수정하였습니다.

> API 에 주문서의 상태에 따라서 삭제가 되지 않도록 하는 기능도 추가
되어야 하겠습니다.

이 기능이 해결되어야 합니다.

**Comment by aanoaa** [comment]
상태에 따라 삭제가 안되게 하는 것은 좋지만 강제로 삭제할 수도 있도록 해야 합니다.

**Comment by 10001if** [comment]
@aanoaa 호기심으로 하는 일은 없도록 공유하였습니다~

**Comment by 10001if** [comment]
@aanoaa 사건이 있은 후 공유하여 예약을 임의로 취소하지 않도록 하고 있는 뒤로는 문제가 발생하지 않았습니다.

**Comment by keedi** [comment]
시간이 오래되어 주문서 삭제 기능이 어떤식으로 동작하는지 좀 까리까리한데, 확인 후 제가 진행하겠습니다.

**Comment by keedi** [comment]
어떤 상태에서 삭제가 가능하게 할것인지, 또는 어떤 상태일 경우 삭제를 불가능하게 해야할지 명확하게 정리해야 합니다.

**Comment by keedi** [comment]
미팅 이후 내용을 정확하게 확인했습니다.

현재 주문서를 삭제 시키는 방법은 다음과 같습니다.

![screenshot-monster silex kr 10301 2016-11-15 15-32-07](https://cloud.githubusercontent.com/assets/138451/20295523/d341c800-ab48-11e6-85a5-cb2311f5ad79.png)

예약 화면에서 사용자 이름 위에서 팝업 메뉴를 띄운 다음 예약 취소를 클릭하면 주문서를 제거하고 있는 것입니다.

하지만 애초에 현재 시스템은 주문서를 기반으로 동작하고 있으며 특별한 경우를 제외하고는 주문서를 지우는 것은 고려하지 않고 있습니다. 예약이라 함은 주문서와 예약 정보(`booking`)를 연결시켜 주는 것이며, 그에 대응해서 예약 취소라 함은 주문서와 예약 정보의 연결 고리를 끊는 것이 맞을 것입니다. 현재는 주문서를 지우고 있으나, 주문서에서 예약 정보를 제거하는 식으로 수정해야 합니다.

따라서 관련해서 다음 내용은 따로 지금 정의할 필요가 없습니다.

> 어떤 상태에서 삭제가 가능하게 할것인지, 또는 어떤 상태일 경우 삭제를 불가능하게 해야할지 명확하게 정리해야 합니다.

진행합니다.

**Comment by keedi** [comment]
현재 주문자가 직접 온라인 예약 화면에 들어가서 예약 취소를 진행할 경우 이 때는 주문서를 지우고 있습니다. 이는 명백히 사용자가 원한 경우기 때문에 큰 상관은 없어보입니다. 어찌됐든 예약 화면에서는 주문서를 지우지 않고 예약 정보만 제거하는 방향으로 처리할 것입니다.

사용자가 온라인 예약 화면에서 정상적으로 예약을 완료한 경우 해당 주문서는 **방문예약** 상태로 내부 코드인 `order.status_id`는 `14`입니다. 직원들이 사용하는 예약 화면에서 **예약 취소**를 진행할 때는 반드시 해당 주문서가 **방문 예약**, 즉 `order.status_id`가 14인 경우에만 예약 정보를 지울 수 있고, 그외의 경우는 오류를 보여주면서 지울 수 없도록 처리하겠습니다.

**Comment by keedi** [comment]
작업 완료했습니다. 이슈 닫습니다.

**Comment by keedi** [comment]
@aanoaa & @yongbin 번거로우셔도 릴리스 완료되면 배포대기 라벨 한번 확인해서 제거해주시면 좋을 것 같습니다. 실제로 머지됐다고 바로 릴리스 하는 것은 아니라 라벨이 번거롭더라도 좀 필요한 듯 합니다.

**Comment by yongbin** [comment]
넵 확인하겠습니다.
