### ISSUE TITLE
포장 시 대여 희망 항목과 실제 포장 항목이 같을 경우 확인용 팝업 창을 보여주지 않음

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#890]
https://github.com/opencloset/opencloset/issues/762 이슈에서 다음과 같은 작업을 진행해주셨습니다.

1. 대여희망품목과 실제포장항목이 같을 경우 -> 같음을 알리는 팝업 창이 뜨도록 함
2. 대여희망품목과 실제포장항목이 다를 경우 -> 다름을 알리는 팝업 창이 뜨도록 함

2번의 경우에는 확인을 해야 하기 때문에 팝업 창이 떠서 경고내용을 알려주는 것은 매우 필요하나
1번의 경우에는 확인의 필요가 없기 때문에 팝업을 없애달라는 의견이 많이 있네요.

1번과 같이 정상적인 경우에는 팝업을 없애고 바로 결제대기 상태로 넘어갈 수 있도록 수정을 요청드립니다.

**Comment by keedi** [comment]
진행합니다.

**Comment by keedi** [comment]
작업 완료했습니다. 반드시 포장 페이지에서 새로고침을 수행한 후 확인해야지 변경 내역을 확인할 수 있습니다.

**Comment by keedi** [comment]
이슈 닫습니다.

**Comment by keedi** [comment]
v1.8.9 릴리스 및 서버 배포 완료했습니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
