### ISSUE TITLE
검색 결과시 여성의 검색결과의 "엉덩이둘레"는 신체의 사이즈로 검색되도록 함 

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#891]
`허리`이슈와 동일합니다.

여성의 `엉덩이둘레` 검색결과는 신체의 `엉덩이둘레`와 동일하게 검색하는 것이 바람직해 보입니다.

수정을 요청드립니다.

**Comment by yongbin** [comment]
확인결과 현재 엉덩이 사이즈 예측이 정상적으로 이루어지고 있지 않습니다 먼저 그부분 부터 해결하겠습니다.

**Comment by yongbin** [comment]
성별에 따른 예측을 위해 전달해야하는 인자를 처리하는 OpenCloset::Size::Guess::OpenCPU::RandomForest 의 guess 함수가 부적절하게 인자를 생성하고있었기 때문에 전반적으로 여성 사이즈 사이즈 예측에 문제가 있었습니다. 해당 모듈의 버그를 수정한 뒤 staff 쪽 코드도 전체적으로 리펙토링했습니다.

**Comment by yongbin** [comment]
#894 PR을 통해 해결되었습니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
