### ISSUE TITLE
검색결과시 여성의 `허리둘레`는 신체의 `윗배둘레`를 기반으로 나타내도록 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#892]
현재 여성 신체의 `허리둘레`는 골반뼈 윗부분의 둘레입니다.
이는 남성의 `허리둘레`와 동일합니다.
하지만 의류의 `허리둘레`는 여성의 신체 사이즈 중 `윗배둘레`에 착용을 하는 관계로

-> 의류의 `허리둘레`는 신체의 `윗배둘레`와 유사하므로 두 사이즈가 매칭되도록 수정을 요청드립니다.

**Comment by yongbin** [comment]
스커트에서 사용하는 의류의 '허리둘레'는 사람의 허리둘레가 아니라 윗배둘레에 대응됩니다. 현재 ocarina에서 예측하는 윗배둘래는 스커트가 아니라 자켓예측을 위한 값이기때문에 측정 윗배둘레를 의류의 예측 허리둘레로 지정하겠습니다.

**Comment by yongbin** [comment]
서버에 반영완료했습니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
