### ISSUE TITLE
주문서에 대여 횟수 외에도 마지막 대여일로 부터 얼마나 지났는지를 표시함

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#893]
주문서에 "1회대여"라고 써 있는 것 대신에 "최근 대여일" 또는 "~일 전 대여"(~개월 전 대여)로 적어 놓으면 좋을 것 같습니다. 작년에 대여하시고 올해 또 오셨는데, 그 동안 안내해 드려야 될 내용이 바뀐 경우가 많습니다. 그래서 최근에 대여하신 경우에만 안내를 생략하고 6개월 이상? 되셨을 경우에는 다시 한번 안내를 드리는게 좋을 것 같습니다. 

대여횟수외에 최근 대여일도 나타나도록 오른쪽에 표기해 주시길 요청드립니다. ^^

**Comment by keedi** [comment]
@10001if 제가 진행합니다. :)

**Comment by keedi** [comment]
문구는 다음과 같습니다.

"마지막 대여일로 부터 XXX일이 지남"

이때 `XXX일`로 표현할 때 단위는 일 단위로 표시하기로 했습니다. 예를 들면 45일 또는 380일과 같은 방식입니다.

**Comment by keedi** [comment]
상기 문구를 표시할 위치는 다음과 같습니다.

![screenshot-monster silex kr 10301 2016-07-14 18-04-30](https://cloud.githubusercontent.com/assets/138451/16834159/8bb2aac0-49ed-11e6-9042-9e4a2e4eba4b.png)

**Comment by keedi** [comment]
문구가 너무 길어져 다음처럼 수정하기로 했습니다.

"1회 대여 - 328일 지남"

**Comment by keedi** [comment]
구현 완료한 화면은 다음과 같습니다.

![screenshot-monster silex kr 10301 2016-07-15 15-18-37](https://cloud.githubusercontent.com/assets/138451/16865417/907f5e1a-4a9f-11e6-9ae8-4c3220278c63.png)

**Comment by keedi** [comment]
이슈 닫습니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
