### ISSUE TITLE
블라우스 "B0EI"가 2000원으로 결제가 되었음

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#897]
블라우스 "B0EI"가 5000원으로 결제가 되어야 하는데, 2000원으로 결제가 되었습니다. 확인 부탁드립니다.

**Comment by aanoaa** [comment]
DB 에 가격이 `2,000` 원으로 저장되어 있습니다.

**Comment by aanoaa** [comment]
UPDATE clothes SET price = 5000 WHERE code = '0B0EI';

**Comment by aanoaa** [comment]
blouse 이면서 2,000 인 의류가 딱 이거 한건 있었습니다.
왜인지는 모르겠습니다.
