### ISSUE TITLE
통계 - 인기 의류에서 대여 기간 및 검색 수량이 변경되지 않음

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#898]
현재는 대여기간은 한달로, 검색수량은 10개로 지정됩니다. 원하는 기간으로 원하는 수량으로 검색되도록 수정 부탁드립니다.

**Comment by keedi** [comment]
무언가 수정하면서 발생한 버그로 보입니다.

진행합니다.

**Comment by keedi** [comment]
작업 완료했습니다. 이슈 닫습니다. :)

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
