### ISSUE TITLE
측정 사이즈를 "사이즈 코리아"의 표준 방식으로 기준을 조정하도록 함 

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#900]
현재 열린옷장에서 측정하고 있는 사이즈 측정 방법 대신 사이즈 코리아에서 측정하는 기준점을 기준으로 측정명, 정의, 방법 등을 수정하려고 합니다. 여기에는 단위변경도 함께 진행되어야 할 것으로 보입니다. @yongbin 준비가 되시면 논의 후에 기준 조정이 이뤄지도록 하는 것이 좋을 것 같습니다. 사이즈 정리는 매칭해야할 의류 측정 내요을 제외하고는 모두 완료되었습니다.

**Comment by yongbin** [comment]
현재는 어떻게 변경될지 구체적인 내용을 모르기때문에 언제 적용이 가능할지 판단하기도 어렵습니다. 먼저 정리된 내용을 좀 올려주시기 바랍니다.

**Comment by keedi** [comment]
@10001if  본 이슈는 여전히 중요한지요? 아니면 더이상 의미가 없는지요. 일단 확인 부탁드립니다.

**Comment by 10001if** [comment]
@keedi 필요한 이슈라고 보입니다. 하지만 당장 적용하기에 어려움이 있어보입니다. 그래서 우선은 이슈를 닫는 것이 바람직해 보입니다. 다만, 이슈를 닫기 전에 이슈에 대해 키디님과 논의 한 후 닫았으면 좋겠습니다.

**Comment by 10001if** [comment]
우선 이슈 닫은 후 차후에 다시 논의하도록 하겠습니다.
