### ISSUE TITLE
한날에 이름이 같은사람이 두명이상일때 시간표에서 다르게 표시

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#902]
전화번호로 구별할 수 있기 때문에 시간표에 전화번호 뒷자리? 를 표시

**Comment by aanoaa** [comment]
아래 쿼리로 같은 이름을 가진 주문서를 찾을 수 있습니다.

``` sql
SELECT b.date, u.name, COUNT(u.name) FROM `order` o
JOIN booking b ON b.id = o.booking_id
JOIN user u ON u.id = o.user_id
GROUP BY b.date, u.name
HAVING COUNT(u.name) > 1
ORDER BY b.date DESC
LIMIT 5;
```

**Comment by aanoaa** [comment]
해서 찾아보니 2016-07-08 일 10:00 에 같은 사용자의 주문서가 두개 만들어진 것이 확인되었습니다.

한사용자에 대해 두개이상의 주문서는 못만드는데 희한합니다.
직원예약 기능을 통해서 가능한지 여부를 살펴보겠습니다.

**Comment by aanoaa** [comment]
직원예약기능을 통한다고 하더라도 별다를게 없습니다.
단지 인증번호를 받지 않는 것 뿐

**Comment by aanoaa** [comment]
![screenshot-localhost 5001 2016-07-15 15-28-17](https://cloud.githubusercontent.com/assets/170528/16865593/e4a19458-4aa0-11e6-83ff-5fa859b8377a.png)

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
