### ISSUE TITLE
다른 단체를 위한 쿠폰 발행 프로세스 추가

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#906]
https://github.com/opencloset/opencloset/issues/858 에서 진행해 주셨던 내용입니다.

`십시일*` 단체의 쿠폰 발행을 요청드립니다. 방법은 지난 번에 보내주셨던 `관악고*`의 방식과 동일합니다.
- `suit` 타입으로
- 사용기간은 2016/12/31 까지
- 설명은 `십시일밥`
- 15장

요청드립니다.

**Comment by aanoaa** [comment]
```perl
#!/usr/bin/env perl

use v5.18;
use utf8;
use strict;
use warnings;
use open ':locale';

use Algorithm::CouponCode qw(cc_generate cc_validate);

use OpenCloset::Schema;

my $CONF   = require 'app.conf';
my $schema = OpenCloset::Schema->connect(
    {
        dsn      => $CONF->{database}{dsn},
        user     => $CONF->{database}{user},
        password => $CONF->{database}{pass},
        %{ $CONF->{database}{opts} },
    }
);

my $type    = 'suit';
my $desc    = '10bob';
my $expires = '2016-12-31T23:59:59';

for ( 1 .. 15 ) {
    my $code = cc_generate( parts => 3 );
    my $coupon = $schema->resultset('Coupon')->create(
        {
            code         => $code,
            type         => $type,
            desc         => $desc,
            expires_date => $expires
        }
    );

    print STDERR "Couldn't create a new Coupon" unless $coupon;
}

print "Coupon created\n";
```

**Comment by aanoaa** [comment]
![screenshot-localhost 5001 2016-07-21 11-14-27](https://cloud.githubusercontent.com/assets/170528/17009299/5c7fb738-4f34-11e6-8f4d-8d0d4fa08414.png)

**Comment by aanoaa** [comment]
@10001if 이메일로 쿠폰코드를 전달해드렸습니다.
다음 버전에서 시간표에 10bob 쿠폰이 표시될 것 입니다.

**Comment by 10001if** [comment]
@aanoaa 이메일 잘받았습니다. 단체에 전달완료하였습니다. 10bob 귀엽네요 ㅎㅎ

**Comment by aanoaa** [comment]
검색해보니 그쪽 페이스북 그룹 이름이 10bob 이더라고요

**Comment by 10001if** [comment]
아하.. ^^

**Comment by 10001if** [comment]
`해피빈캠페인` 단체의 쿠폰 발행을 요청드립니다. 방법은 지난 번에 보내주셨던 `관악고*`의 방식과 동일합니다.
-`suit` 타입으로
- 사용기간은 2017/12/31 까지
- 설명은 `해피빈캠페인`
- 100장

@aanoaa 연휴 뒤에 쿠폰을 발송할 계획입니다.
바쁘시겠지만 금일 중으로 발행 요청드릴게요. ^^

**Comment by aanoaa** [comment]
이메일로 전달해드렸습니다.
