### ISSUE TITLE
포장 완료 상태인 주문서도 내역을 취소할 수 있게 함

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#907]
현재는 결제대기 상태인 주문서만 취소가 가능합니다.
포장완료 주문서에 대해서도 취소가 가능해야 합니다.

**Comment by 10001if** [comment]
@aanoaa 간단히 해결될 문제라면 괜찮지만, 조금 복잡한 이슈라면 빨리 진행해 주지 않으셔도 됩니다. 
이 부분이 문제가 되는 이유는 결제대기 상태가 되어야 새로주문을 할 수 있는데, 결제대기 버튼을 누르면 모니터에서 결제대로 와달라는 멘트를 보고 결제대로 방문하는 것이 문제가 되기 때문입니다. "착오가 있었다. 조금 더 기다려 주세요"라고 말씀드리면 되는 것이므로 빠르게 중요한 이슈는 아닙니다. 

마일스톤을 뒤로 옮기겠습니다. ^^

**Comment by keedi** [comment]
제가 진행합니다.

**Comment by keedi** [comment]
결제 취소 라는 것이 다음 화면 갈무리의 **새로 주문** 버튼을 클릭하는 것을 의미하는지요?

![screenshot-monster silex kr 10301 2016-11-14 17-09-34](https://cloud.githubusercontent.com/assets/138451/20257491/45c9f756-aa8d-11e6-91dd-4425a9017a7a.png)

**Comment by keedi** [comment]
더불어 결제 취소가 상기의 **새로 주문**이 맞다면, 포장 완료 상태의 주문서를 어느 화면에서 처리할 수 있으면 되는지요?

**Comment by keedi** [comment]
결제 대기의 화면에서 **새로 주문** 버튼을 클릭할 경우 주문서는 **결제대기**에서 **포장**으로 상태가 변경됩니다. 이것을 의미하는 것이라면 **포장완료** 상태에서도 마찬가지로 **포장** 상태로 변경되어야 합니다.

**Comment by keedi** [comment]
일단 피드백을 받지는 못했지만 우선 구현 완료한 화면은 다음과 같습니다.

![screenshot-monster silex kr 10301 2016-11-14 17-40-08](https://cloud.githubusercontent.com/assets/138451/20258152/8c4d2c80-aa91-11e6-9a73-9843bbdd6605.png)

**Comment by keedi** [comment]
피드백을 받은 후 처리한 내역이 맞다면 이슈 닫겠습니다.

**Comment by keedi** [comment]
**새로 주문** 기능은 위험한 기능이기 때문에 주문서 목록에서 보이는 것은 부담스럽다고 합니다. 기존처럼 주문서 안에 들어가서 해당 버튼을 클릭할 수 있으면 충분하다고 합니다.

**Comment by keedi** [comment]
작업 완료했습니다. 이슈 닫습니다. :)

**Comment by keedi** [comment]
릴리스 및 배포 완료했습니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
