### ISSUE TITLE
SMS 발송 대기 확인요청의 결과 로그 조정

### ISSUE THREAD

**Issue by yongbin** [opencloset/opencloset#908]
#741 에서 한번 논의된적 있었던 이슈입니다. 

API에서 일관되게 결과가 없는경우 에러를 돌려주고 있지만 SMS의 경우 발송을 위해서 주기적으로 요청이 발생하고 있기때문에 서버 모니터링에서 필요이상으로 에러가 많이 발생해 모니터링에 어려움이 발생합니다. 실제로 발송대기 SMS가 없는것은 오류가 아니기때문에 정상처리하도록 변경합니다.

**Comment by yongbin** [comment]
@keedi 님과 상의해서 200을 돌려주는 방향으로 결정했습니다.

**Comment by yongbin** [comment]
처리했습니다. 닫겠습니다.

@keedi 감사합니다 제 숙원사업이었습니다!

**Comment by aanoaa** [comment]
이거는 @10001if 님이 확인할게 없습니다.
