### ISSUE TITLE
결제대기 주문서의 예약변경

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#909]
현재는 방문예약 상태인 주문서에 대해서만 사용자가 변경이 가능합니다.
취업날개 이벤트의 영향으로 결제시에 취업날개를 통해서 새로 주문을 하고자 하는 사용자가 많습니다.
주문서를 취소하고 포장된 의류들을 다시 바코드 찍고 하는 일이 번거롭습니다.

결제대기인 주문서를 변경가능하게 하면 쿠폰을 적용할 수 있고 번거로운 절차를 줄일 수 있습니다.

**Comment by aanoaa** [comment]
@10001if 

    결제대기 -> 사용자에게 말씀드려서 취업날개를 통해 주문서를 변경 -> 주문서를 새로고침 -> 결제

처럼 사용하시면 됩니다.

**Comment by 10001if** [comment]
확인은 하지 못했지만, 이해는 하였습니다. 사용해보고 문제가 있을시 다시 말씀드리도록 하겠습니다.

**Comment by 10001if** [comment]
@aanoaa 주문서 번호 48863의 경우 본 프로세스로 재예약을 시도하였으나, 취업날개로 예약이 되지 않았습니다. 확인 부탁드리겠습니다.

**Comment by aanoaa** [comment]
@10001if 48863 주문서는 존재하지 않습니다.
주문서 번호를 확인해주세요.

**Comment by 10001if** [comment]
@aanoaa 51437 였습니다. 확인 부탁드릴게요~

**Comment by aanoaa** [comment]
로그를 뒤져서 해당 주문서는 오늘 다시 방문예약이 된 것을(업데이트) 확인했습니다.
오늘 서울시 이벤트를 통해 지급된 쿠폰을 가지고 지난해 이벤트를 조회해서 대여자를 찾을 수 있었습니다.

`P161029484`

쿠폰은 정상적으로 지급되었지만 아직 예약은 되지 않은 상태였습니다.

지급받은 후에 방문예약을 다시 했을때에(업데이트) 쿠폰이 예약되는지의 여부를 제가 재현해보았습니다.

- 이벤트페이지 접속
- 다시 방문예약
- 쿠폰확인

------------------------

제가 시도했을때에는 쿠폰이 정상적으로 지급되었습니다.
가능성이 있는 것은 두개의 브라우저를 사용했을 경우에 이럴 수 있습니다.

- firefox 에서 취업날개 쿠폰을 발급받는다.
- chrome 에서 방문예약을 한다.

**Comment by aanoaa** [comment]
쿠폰을 지급받았을때,

```
175.223.35.22 - - [08/Feb/2017:11:47:44 +0900] "GET /events/seoul?MberSn=xxxx HTTP/1.1" 200 1331 "http://job.seoul.go.kr/m/add_service/openChothesChest.do?method=selectOpenChothesChest" "Mozilla/5.0 (iPhone; CPU iPhone OS 9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Mobile/13B143 NAVER(inapp; search; 560; 7.7.1; 6S)"
```

(MberSn 은 노출을 피하기 위해 제가변경했습니다.)

예약을 갱신했을때,

```
39.7.51.55 - - [08/Feb/2017:11:49:21 +0900] "POST /visit HTTP/1.1" 200 10131 "https://visit.theopencloset.net/visit" "Mozilla/5.0 (iPhone; CPU iPhone OS 9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Mobile/13B143 NAVER(inapp; search; 560; 7.7.1; 6S)"
```

``` diff
"Mozilla/5.0 (iPhone; CPU iPhone OS 9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Mobile/13B143 NAVER(inapp; search; 560; 7.7.1; 6S)"
"Mozilla/5.0 (iPhone; CPU iPhone OS 9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Mobile/13B143 NAVER(inapp; search; 560; 7.7.1; 6S)"
```

**Comment by aanoaa** [comment]
브라우저가 아닌, 네이버 앱을 사용한 것 같습니다.

- 네이버앱에서 이벤트 페이지 방문
  - 쿠폰 지급
- 창을 닫고 다시 열어서 방문예약

을 한게 아닌가 싶습니다.

앱 내의 webkit 을 사용함으로해서 1회성 세션이 만들어졌지만 닫는 순간에 세션에 기록되어있는 쿠폰이 잃은게 아닌가 싶습니다.

**Comment by aanoaa** [comment]
사용자가 쉽게 사용하게 하기 위해서 세션을 사용했는데 이런 문제가 발생할 줄은 몰랐습니다.

**Comment by aanoaa** [comment]
왜 일반인들은 인터넷을 할때 네이버앱을 쓰는거죠?
네이버 == 인터넷?

@10001if 이분에 대해서 어떻게 처리하셨는지 알려주세요.

**Comment by aanoaa** [comment]
돈받지 않고 메모해서 대여해주었다고 합니다.

**Comment by aanoaa** [comment]
제가 착각했습니다.
네이버앱을 통해서 창을 닫지않고 진행한 것 같습니다.
네이버앱에서 한번 테스트해볼 필요가 있습니다.

**Comment by 10001if** [comment]
@aanoaa 예약방법만 안내해드리고 대여자 본인이 직적 예약을 실시했다고 합니다.

**Comment by aanoaa** [comment]
네이버앱을 통해서 일련의 과정을 진행했을때에 쿠폰을 사용해서 예약이 되는지 확인 할 필요가 있습니다.
문제가 있다면 일반적인 브라우저를 통해서 예약을 하도록 안내해야 합니다.

**Comment by aanoaa** [comment]
네이버앱을 사용했을때에도 쿠폰을 통한 예약이 됩니다.
중간과정에서 한번 탭을 닫은 것이 아닌가 싶습니다.

탭을 한번 닫고 방문예약을 하는 케이스도 테스트 해봐야 합니다.

**Comment by aanoaa** [comment]
네이버앱을 통해서도 쿠폰이 정상적으로 지급되었습니다.

- PC 에서 쿠폰없이 방문예약
- 네이버앱에서 쿠폰 지급받고
- 창을 닫음
- 새로운 창을 띄워서 visit.theopencloset.net
- 예약을 갱신
- 쿠폰으로 예약이 됨

-----------------

왜 이런현상이 나타났는지 재현이 안됩니다.

**Comment by aanoaa** [comment]
@10001if 원인을 모르겠습니다.
다시 발생하면 알려주세요.

**Comment by 10001if** [comment]
네! 알겠습니다.

**Comment by 10001if** [comment]
@aanoaa /orders/77382 주문서에서도 예약변경이 되지 않았다고 합니다. 이 분은 컴퓨터에서 예약을 진행하셨는데 변경이 되지 않았다고 하는데요. 이분은 안양시 쿠폰이라 서울시와는 다르게 쿠폰 입력하는 창을 통해 예약을 진행하였습니다. 혹시 서울시만 예약변경이 되고 다른 쿠폰은 기능 구현이 되지 않았나요? 확인 부탁드립니다~

**Comment by aanoaa** [comment]
발행한 곳과는 상관없습니다.
예로 볼때에 모든 결제대기 주문서에서 쿠폰을 사용하도록 예약변경을 해도 적용이 되지 않는 것 같습니다.
어떤 패치 이후에 동작하지 않는 것 같습니다.
