### ISSUE TITLE
신체치수 혹은 대여가능한 의류를 검색하는 카테고리의 추가 요청입니다.

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#91]
![2014-09-25 10 42 06](https://cloud.githubusercontent.com/assets/4696328/4398399/375c46a6-4455-11e4-9b30-fba0b14ace5d.png)

이 부분은 많은 고민이 필요할 것 같으나 우선 이슈로 등록해 놓습니다.
위 스크린샷은 아래의 겁색기능은 대여 아래 추가 카테고리로 생성이 되면 좋을 것 같아 첨부하였습니다.

현재 온라인 주문이 들어오면 다음과 같은 프로세스로 진행합니다.
1. 주문시 들어온 사이즈를 확인
2. 고객과 통화하여 정보의 신뢰성을 체크
3. 과거에 대여했던 기록을 찾아 키/몸무게 기준으로 가슴과 허리둘레를 확인
4. 얻게된 결과값을 토대로 적합한 의류를 찾음
5. 발송

여기서 주문시 사이즈를 측정한 고객의 신뢰성 여부는 현재 제작중인 동영상 (인도치노)를 통해 어느정도 개선할 수 있겠지만, 근본적으로 고객이 사이즈를 편차가 크게 재는 행위에 대해 제재할 방법은 없습니다. 하지만, 저희가 가지고 있는 데이터를 통해 고객이 사이즈 측정을 잘못했을 것이라 추정하는 것은 가능한데요. 그리고 이 의견을 가지고 고객과 대화를 나누다보면 고객 스스로 사이즈 측정에 대해 잘못 인식하고 의견을 수정하는 경우가 대부분입니다.

그래서 저희가 가지고 있던 데이터 중 신뢰할 수 있는 데이터만 추출한다면 그 안에서 검색을 통해 결과값을 도출하고, 고객의 사이즈와 비교를 해 볼 수 있지 않을까 싶습니다.

제가 필요한 것은 

1. 키/몸무게를 기준으로 다른 사이즈를 알 수 있는 것
예) 180cm / 70kg 를 입력하면 
가슴둘레 / 허리둘레 / 팔길이 / 다리길이 / 허벅지 둘레 / 중동 사이즈를 알 수 있다.
1-1. 1번 외에도 다른 항목 1가지만 입력하여도 나머지 다른 모든사항의 평균값이 검색된다.

예) 가슴둘레 100cm 를 입력하면
 키 / 몸무게 / 허리둘레 / 팔길이 / 다리길이 / 허벅지 둘레 / 중동 사이즈를 알 수 있다.

1과 1-1을 통해 고객의 정확한 사이즈를 알게 되었다면

2. 그에 맞는 옷을 검색한다. (대여목적에 따라 색상을 결정해야 하는 이슈가 있으나 이것은 색상 분류만 하면 될 것 같아 큰 고민은 필요하지 않을 것 같습니다.) 도출된 사이즈를 입력하면 가장 잘 맞는 의류가 검색결과로 나온다.

2-1. 검색 시 기존에 대여를 진행했던 의류의 기록이 있다면 그것을 먼저 따르고, 기록이 없다면 옷의 치수와 평균값을 매칭시켜 검색이 가능하도록 하되, 구체적인 부분은 다시 고민해야 할 듯 합니다. 

** 고민사항 : 실제로 기존에 대여했던 의류(점수가 최상인)보다 다른 의류가 검색결과에 먼저 노출된다면 그 부분에 대해서는 임의로 순위를 조정할 것인가 아니면 옷의 사이즈를 임의로 수정할 것인가 - 이 부분은 개인의 신체치수와 옷의 실제사이즈에 대한 객관성 여부가 완전히 확인되지 않았으므로 좀 더 고민해 보기로 함..

** 바지의 경우 종아리 치수가 새로운 이슈로 부각. 또한 바지의 턱(tuck)의 수에 따라 허벅지 치수의 임의 변경이 필요함. 예) 노턱 허벅지 60과 원턱 허벅지 58, 투턱 허벅지 56이 동일한 사이로 인식해야 하는 변동성 존재. 

** 기존에 입력하여 점수화 한 자료를 어떻게 활용하여 사용할 것인지 고민이 필요함. 실제 치수와 옷의 치수 매칭과는 또다른 분제로 보임. 덧붙여 우리가 평가한 점수와 고객이 직접 입력한 사이즈는 어떻게 조화를 이룰 것인지 고민이 필요함.

**Comment by keedi** [comment]
#317 항목과 중복 항목입니다. 현 시점 기준으로 #317 결과물로 대체할 수 있기 때문에 이슈 닫습니다. 정말로 필요한 기능이 더 정확하게 생길 경우 그때 별도의 이슈를 열어서 처리합니다. :)
