### ISSUE TITLE
최근 주문 내역에 있는 의류 현황에 보이는 의류를 정렬함

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#910]
사용자 정보(~user/) 하단에 최근 주문 내역에 있는 기존의류 내역의 의류 정렬 순서를 변경

![2016-07-18 4 29 50](https://cloud.githubusercontent.com/assets/4696328/16908246/f7aa09ac-4d04-11e6-92b7-92e5257e62e8.png)

- 현재는 의류 정렬이 포장된 순서대로 되어 있음
- 이것을 `자켓`, `바지`, `스커트`, `셔츠`, `블라우스`, `구두`, `타이`, `벨트`, `원피스`, `코트` 순으로 정렬 요청드립니다.
- 의류가 정렬되지 않은 상태로 존재하여서 대여내역을 확인하는데 어려움이 있다고 하네요. :)

**Comment by keedi** [comment]
최근 주문 내역은 사용자 페이지 뿐만 아니라 의류 상세 페이지에도 있습니다. 어쨌든 최근 주문 내역 항목에서 의류를 보여주는 순서를 조정합니다.

**Comment by keedi** [comment]
작업 완료했습니다. 이슈 닫습니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
