### ISSUE TITLE
대여 회전율의 품목 추가

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#914]
현재는 자켓, 바지, 스커트만 확인할 수가 있습니다. 코드를 보고 의류를 바로 찾을 수 있는 품목이 3가지 종류이기 때문입니다. 하지만 회전율 정보가 많은 부분에서 큰 도움이 되고 있습니다. 대여가 잘 되지 않는 품목을 폐기하는데에도 도움이 되고 품목별로 어떤 사이즈가 회전율이 높은지 낮은지도 확인할 수 있습니다. 

자켓, 바지, 스커트 외에 현재 존재하는 모든 품목의 대여 회전율을 확인할 수 있도록 모든 품목의 추가를 요청드립니다.

**Comment by keedi** [comment]
모든 품목입니까?

**Comment by 10001if** [comment]
@keedi 네! 맞습니다~! ^^

**Comment by keedi** [comment]
진행합니다. 모든 항목에 대해 캐시를 생성해야 합니다.

**Comment by keedi** [comment]
#540 완료 후 추가된 연계 이슈 입니다.

**Comment by keedi** [comment]
예전 남성/여성/재킷/바지/치마 처리할때 개수는 약 4000개였으며 개발 장비 기준 캐시 생성에 3분이 걸렸습니다.

> 현 시점 기준 남성/여성/재킷/바지/치마는 약 3800~4000개가 데이터베이스에 저장되어 있으며 이 항목에 대해 캐싱값을 생성하는데는 로컬 개발 장비 기준 약 3분이 걸립니다. 대부분의 시간은 모든 항목에 대해 대여 회전율 관련 값을 뽑아내는데 소요되므로 의류가 증가하더라도 소요시간은 선형적으로 증가할 것으로 예측됩니다. 추후 의류가 10배가량 늘어난다고 하더라도 업무 외 시간에 캐싱하는 것은 별 문제 없어보입니다.

**Comment by keedi** [comment]
현재 남녀 및 항목 구분 없이 모든 의류에 대해 처리할 경우 개수는 약 13000개이며 개발 장비 기준 캐시 생성에 4분이 걸립니다.

**Comment by keedi** [comment]
구현한 결과는 다음과 같습니다.

![2016-07-26-155652_3640x2309_scrot](https://cloud.githubusercontent.com/assets/138451/17128795/38b5918c-534a-11e6-9506-a245055c6333.png)

**Comment by keedi** [comment]
배포 후에 캐시 생성을 새로 해주어야 합니다.

**Comment by keedi** [comment]
작업 완료했으므로 이슈 닫습니다.

**Comment by yongbin** [comment]
배포완료했습니다. 확인해주세요

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
