### ISSUE TITLE
취업날개 이벤트 수치 오류

### ISSUE THREAD

**Issue by yongbin** [opencloset/opencloset#916]
현재 서울시에 제공하는 취업날개 이벤트 통계페이지에 수치 계산에 오류가 있습니다.

![screen shot 2016-07-25 at 5 05 19 pm](https://cloud.githubusercontent.com/assets/52704/17094416/142cdf02-528a-11e6-87b6-f55f8a88fabe.png)

**Comment by yongbin** [comment]
내일 맑은정신으로 하루만 더 확인해보겠습니다.

**Comment by keedi** [comment]
지금까지 확인한 내역 정리해주시고, 계속 진행할지 여부를 알려주시면 후속 작업을 제가 진행하던지 하겠습니다.

**Comment by yongbin** [comment]
넵 제가 계속 진행하겠습니다.

**Comment by keedi** [comment]
하기 두 SQL을 실행했을 때 나오는 결과 값이 약간 다릅니다.

```sql
SELECT COUNT(*) FROM coupon WHERE status="used";
```

```sql
SELECT o.id, c.id, c.status, s.name
    FROM `order` AS o
        LEFT JOIN coupon AS c ON o.coupon_id = c.id
        LEFT JOIN status AS s ON o.status_id = s.id
    WHERE (
        c.status = "used"
        AND o.parent_id IS NULL
        AND s.name <> "방문예약"
        AND s.name <> "대여안함"
        AND s.name <> "방문안함"
    )
    ORDER BY c.id
    ;
```

현재 총 개수로 2개 차이가 나는데 이것은 쿠폰이 서로 다른 사람의 주문서에 중복해서 사용된 정황이 있기 때문입니다.

```sql
SELECT o.id, c.id, c.status, s.name, o.parent_id
    FROM `order` AS o
        LEFT JOIN coupon AS c ON o.coupon_id = c.id
        LEFT JOIN status AS s ON o.status_id = s.id
    WHERE (
        c.status = "used"
        AND o.parent_id IS NULL
        AND s.name <> "방문예약"
        AND s.name <> "대여안함"
        AND s.name <> "방문안함"
        AND (
            c.id = 4041
            OR c.id = 2715
        )
    )
    ORDER BY c.id
    ;
```

통계에서 값이 월별로 틀린 부분 보다는 성별이나, 연령대별 총합 계산할 때 2만큼 차이가 나는 것은 현재 발견한 이슈와 연관이 있는 것 같습니다.

**Comment by keedi** [comment]
8월 17일까지 진전이 없으면 제가 진행하겠습니다.

**Comment by keedi** [comment]
> 8월 17일까지 진전이 없으면 제가 진행하겠습니다.

오늘까지 휴가셨군요. 금주까지 진전이 없으면 제가 진행하겠습니다. 누가 진행하든 확인사항은 갱신 부탁드립니다.

**Comment by aanoaa** [comment]
같은 쿠폰이 다른사람에게 발급되는 버그가 있습니다.
하나의 쿠폰이 각기 다른사람 2명에게 발급된 쿠폰이 2장입니다.

이와 관련해서 프로그램상의 오류를 찾아야 합니다.

**Comment by keedi** [comment]
알아낸 내용이 있다면 갱신해주세요. 제가 진행합니다.

**Comment by yongbin** [comment]
여러가지 이슈로 집중을 잃었네요 약속을 못지켜서 죄송합니다. 내일까지 이 이슈 집중해서 처리하도록 하겠습니다.

**Comment by yongbin** [comment]
@aanoaa 
쿠폰의 갱신일(coupon.`update_date`)이 예약시점(booking.`date`)보다 뒤일수 있나요?

**Comment by aanoaa** [comment]
쿠폰의 상태가 바뀔때 갱신될 것 같습니다.
예약이후에 쿠폰의 상태가 바뀔때는 주문서의 `결제대기 -> 대여중` 입니다.

**Comment by aanoaa** [comment]
이 이슈는 수치상의 오류를 찾는 것보다 프로그램의 오류를 먼저 확인하는게 유리할 것
같습니다.

제가 진행해야 하지만, 별거 없기 때문에 직접 확인하셔도 좋습니다.

> 같은 쿠폰이 다른사람에게 발급되는 버그가 있습니다.
> 하나의 쿠폰이 각기 다른사람 2명에게 발급된 쿠폰이 2장입니다.
> 
> 이와 관련해서 프로그램상의 오류를 찾아야 합니다.

**Comment by yongbin** [comment]
제가 판단하기에 이 이슈는 여러가지 문제가 복합적으로 작용하고 있는것 같습니다. 위에 @keedi 님이 말씀해주신 내용 이외에 제가 확인한 사항을 먼저 공유합니다.

`events_seoul` 의 구현부에서 열린옷장의 예약 인원에 대한 수치계산은 예약시점(`booking`.`date`)을 기준으로 하는데, 취업날개의 수치계산은 쿠폰갱신시점(`coupon`.`update_date`)를 기준으로 하고 있습니다(아래코드)

```perl
    ## 월별 취업날개 예약/방문
    my $monthly_events = $self->DB->storage->dbh_do(
        sub {
            my ( $storage, $dbh, @args ) = @_;
            $dbh->selectall_arrayref(
                qq{SELECT DATE_FORMAT(c.update_date, '%Y-%m'), c.status, COUNT(c.status)
FROM (SELECT DISTINCT(coupon_id)
FROM `order`
WHERE coupon_id IS NOT NULL) o
JOIN coupon c ON o.coupon_id = c.id
WHERE c.desc LIKE 'seoul%' GROUP BY DATE_FORMAT(c.update_date, '%Y-%m'), c.status}
            );
        },
    );

    for my $row (@$monthly_events) {
        my ( $ym, $status, $c ) = @$row;

        $counts{monthly}{$ym}{events}{visited}     = $c if $status eq 'used';
        $counts{monthly}{$ym}{events}{not_visited} = $c if $status eq 'provided';
    }

```
일반적으로 생각할때 쿠폰을 발행한 뒤, 예약을 진행하기때문에 예약시점은 쿠폰의 발행시점보다는 앞설수 없습니다. 하지만 형석님이 말씀하신 **예약이후 쿠폰의 상태가 변경되는 상황** 이 발생할 경우 쿠폰의 갱신시점은 언제가 될 지 알수 없기때문에 이 시점을 쿠폰의 발행시점이라고 생각하는것은 문제가 생길수 있습니다.

실재로 4,5,6월의 자료를 확인해본 결과 

 - 4월 예약에 사용된 쿠폰중 4건이 예약시점보다 쿠폰발행시점이 더 뒤입니다. 그중 한건은 쿠폰사용시점이 5월입니다
 - 5월 예약에 사용된 쿠폰중 17건이 예약시점보다 쿠폰발행시점이 더 뒤입니다. 그중 두건은 쿠폰사용시점이 6월입니다.
 - 6월 예약에 사용된 쿠폰중 9건이 예약시점보다 쿠폰발행시점이 더 뒤입니다. 그중 두건은 쿠폰사용시점이 7월입니다. 

이 이슈도 전체 계산을 안맞게 하는 원인중 하나입니다.

**Comment by yongbin** [comment]
```sql
SELECT y.`status`, x.*
FROM
(
    SELECT * FROM `order` WHERE `coupon_id` IN (
        SELECT      `coupon_id`
        FROM        `order`
        WHERE       `coupon_id` IS NOT NULL
        GROUP BY    `coupon_id`
        HAVING COUNT(*) > 1
    )
) AS x  INNER JOIN `coupon` AS y ON x.coupon_id = y.id
ORDER BY x.`coupon_id` ASC , x.`id` DESC 
```

# 같은 사용자가 두개의 주문서에서 사용하지만 최종 대여되지 않은 쿠폰들(5건)

## 2014
 - 26988
 - 26932

## 2168
 - 34454
 - 31522

## 2708
 - 32746
 - 29496

## 2771
 - 29892
 - 29762

## 2794
 - 30091
 - 29857

# **다른** 사용자가 동일한 쿠폰을 사용한 쿠폰(2건)

## 2715
 - 29522
 - 29521

## 4041
 - 41349
 - 41345

**Comment by aanoaa** [comment]
예전에 발견한 것이 2건이고 고치지 않았는데 늘어나지 않았다는 것은 다행입니다.

**Comment by yongbin** [comment]
쿠폰과 예약은 단순하게 생각하면 아주 간단하지만, 조금만 더 복잡하게 경우의 수를 따저보면 다음과 같은 예외사항들때문에 다양한 경계값 이슈를 발생시킵니다.

 - 하나의 쿠폰은 동일 사용자의 여러 방문예약에 포함될 수 있음 (예약중 하나는 방문인 경우도 있고 모든 예약이 미방문인경우도 존재)
 - 하나의 쿠폰은 다수 사용자의 여러 방문예약에 포함될 수 있음 (모든 예약이 방문인 경우가 있을수 있음 / 버그로 추정)

그리고 기존 통계방식에서 쿠폰의 사용시점은 쿠폰이 등록된 방문예약의 예약시점(booking.date)가 아닌 쿠폰의 상태변경시점(coupon.update_date)에 의존하는 방식이었기때문에 경우의 수에 따라서 더 복잡한 케이스가 발생합니다(기존방식에서는 4월에 발행한 쿠폰을 5월과 6월에 각각 방문예약하고 방문하지 않은 사람은 4월 미방문자로 집계됩니다)

마지막으로 전체 숫자의 합이 맞아야 하는 통계페이지의 특성상, 이런 변수가 많은 상황에서는 각각의 수치를 DB로부터 요약 함수를 통해서 뽑을경우 분석을 어렵게 할 수 있기때문에 원하는 원하는 규칙을 포함한 하나의 자료셋을 생성한뒤 그 자료셋으로 부터 여러가지 요약값을 뽑을경우 설령 원하지않는 대상이 포함될 가능성은 있지만, 최소한 페이지상에서 수치가 맞지않을 가능성은 없기때문에 더 안정적입니다.

따라서 기존 취업날개 이벤트 수치 페이지를 전체적으로 개선해서 다음기준으로 표현하도록 변경하겠습니다.

 - 쿠폰이 연결된 예약시간을 기준으로 합니다.
 - 예약시간이 쿠폰의 갱신시간보다 앞선 주문서는 명백하게 잘못된 주문이므로 계산에서 배재합니다.
 - 그 밖에 나머지 경우는 각각의 모든 경우를 결과에 포함해서 집계합니다.
 - 처리는 DB에서 단일쿼리로 가지고 온 자료를 통해 응용단에서 요약합니다.

즉 기존에 있었던 경계값을 기준으로 예를들면

 1. 동일 사용자가 1회 방문신청하고 미방문 한뒤, 두번째 방문신청 후 대여한 경우 : 미방문건은 카운팅되지 않으며 1회방문 통계에 포함합니다
 2. 동일 사용자가 2회 방문신청하고 모두 미방문한 경우 : 각각을 미방문으로 카운팅하여 통계에 포함합니다.
 3. 다른 사용자가 2회 방문신청하고 모두 방문한 경우(버그) : 각각을 방문으로 카운팅해서 통계에 포함합니다.

이렇게 PR작성해서 보내겠습니다.

**Comment by yongbin** [comment]
참고도 다른사용자가 동일한 쿠폰으로 방문예약이 된 이 이슈에서 다루지 않을 예정입니다. 별도 버그로 열어야 합니다.

**Comment by yongbin** [comment]
오늘 @10001if 님과 상의한 결과 다음 사항이 더 필요한것으로 파악했습니다.

- 열린옷장과 관련된 통계는 필요없으니 삭제
- 기존 숫자가 달라진 경우 기존 일별 방문에서 성별, 연령 통계를 제공하는 형태필요

**Comment by yongbin** [comment]
![screen shot 2016-09-05 at 8 16 27 pm](https://cloud.githubusercontent.com/assets/52704/18246293/bb3dc356-73a5-11e6-9d0d-49d41e2e9613.png)

#937 PR에서 구현된 화면입니다. 위에 언급된 방식으로 구현되었고 추가적으로 다음 사항이 변경되었습니다.

 - 열린옷장 관련 수치 제거
 - 방문/미방문 수치를 명확하게 분리
 - 일별 방문수치를 취업날계 시작시점부터 지정 시점형식으로 변경하고 성별, 연령 통계를 추가
 - 기존 전체 성별 섹선 삭제 
 - 기존 전체 연령 섹선 삭제 

모든 숫자의 합은 맞는 상태이지만, @10001if 님께서 29929, 31590 두개의 주문서 연령은 별도로 수정해주셔야 합니다.

**Comment by yongbin** [comment]
연령에 문제가 있던 2건은 @10001if  님이 수정해주셨습니다. 추가적으로 오늘 유선을 통해 아래와 같은 내용을 요청받았습니다.

- [ ] 월 통계와 일 통계의 제목을 부여
- [ ] 월 통계는 기본 보임, 일 통계는 기본 접힘 상태로 보이도록 수정

위 두가지 내용을 반영한 뒤 추가 피드백 없이 머지하기로 했습니다. #937 PR에 위 사항 추가한뒤 머지하고 이슈 닫겠습니다.

**Comment by yongbin** [comment]
#937 PR에서 해결되었습니다. collapse 구현에 coffeescript 가 사용되었기 때문에 서버 반영시점에 꼭 grunt 를 실행해야 합니다.

**Comment by 10001if** [comment]
확인 하였습니다. 배포 요청드립니다. ^^

**Comment by yongbin** [comment]
#1111 이슈를 통해서 확인한 결과 https://github.com/opencloset/opencloset/issues/1111#issuecomment-269424866 `coupon_status`가 `provided`인 쿠폰은 사용된 쿠폰으로 계산되면 안됩니다. 따라서 최종적으로 이 이슈의 쿼리는 다음과 같이 수정되어야 합니다. 
```sql
    SELECT
                    *
                FROM
                    (
                        SELECT
                            a.`date`                                        AS 'booking_date'
                            ,b.`id`                                         AS 'order_id'
                            ,YEAR(a.`date`)                                 AS 'booking_year'
                            ,MONTH(a.`date`)                                AS 'booking_month'
                            ,DAY(a.`date`)                                  AS 'booking_day'
                            ,IF(b.status_id = 12 OR b.status_id = 14, 0, 1) AS 'is_visit'
                            ,d.gender                                       AS 'gender'
                            ,d.birth                                        AS 'birth'
                            ,YEAR(NOW()) - d.birth                          AS 'age'
                            ,TRUNCATE(YEAR(NOW()) - d.birth, -1)            AS 'age_group'
                            ,IF(b.`coupon_id` IS NOT NULL AND e.status = 'used' AND b.status_id NOT IN ( 14, 12, 40 ), 1, 0)            AS 'is_coupon_use'
                            ,e.`id`                                         AS 'coupon_id'
                            ,e.`update_date`                                AS 'coupon_date'
                            ,e.`status`                                     AS 'coupon_status'
                            ,SUBSTRING_INDEX(e.desc, '|', 1)                AS 'coupon_type'
                            ,IFNULL(a.`date` - e.`update_date`,0)           AS 'booking_coupon_issue_diff'
                            ,s.name
                        FROM
                            `booking` AS a
                            INNER JOIN `order`      AS b ON ( a.id = b.booking_id )
                            INNER JOIN `user`       AS c ON ( b.user_id = c.id )
                            INNER JOIN `user_info`  AS d ON ( c.id = d.user_id )
                            INNER JOIN `status`     AS s ON ( b.status_id = s.id )
                            LEFT  JOIN `coupon`     AS e ON ( b.coupon_id = e.id )
                    ) AS x
                WHERE
                    `booking_coupon_issue_diff` >= 0
                    AND `booking_date` > '2016-04-25'
                    AND `is_coupon_use` = 1
```
추후 통계 페이지 작업을 할때 고려해야합니다.  또한 하나의 쿠폰이 하나이상의 주문서에 배정되지 않도록 설계상에서 고려해야하며 그 고려가 되어있지 않은 경우 쿠폰 사용과 관련한 통계를 DB 쿼리로 생성하는것은 부정확할수 있다는것을 유의해야합니다.
