### ISSUE TITLE
복수 의류 선택 후 일괄 태그 등록 및 삭제

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#922]
여러벌의 의류에 대해 한번에 태그를 등록하는 기능

**Comment by aanoaa** [comment]
의류를 등록하면서 태그를 등록할 수 있게 되었습니다.
특히 재활용 의류에 대해서는 수량과 더불어 태그도 입력할 수 있습니다.

**Comment by aanoaa** [comment]
첫화면에 여러벌의 의류를 입력해놓고 한방에 태그를 입력하는 기능입니다.

재활용의류에 등록되는 태그 기능과는 다릅니다.

**Comment by 10001if** [comment]
@aanoaa 단체 기증을 곧 앞두고 있습니다. 본 기능이 빨리 진행되어야 합니다. 바쁘시겠지만 빠르게 요청 드릴게요. ^^;

**Comment by aanoaa** [comment]
의류등록시에 태그를 지정할 수 있는 기능이 있습니다.

**Comment by aanoaa** [comment]
기증 및 의류관리에 관련된 항목이니까 기증프로그램쪽에 기능을 붙이도록 하겠습니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^

**Comment by 10001if** [comment]
이 기능 덕분에 일이 한결 수월해 질 것 같습니다! 감사드려요~!

**Comment by 10001if** [comment]
넘버링 추가를 요청드립니다. ^^
