### ISSUE TITLE
통계-수량 페이지에서 대여불가 상태를 가용 수량으로 추가

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#924]
현재 가용 수량은 `대여가능`, `대여중`, `세탁`, `수선`, `반납` 상태를 의미합니다.

현재는 `대여불가` 상태가 빠져있습니다. `대여불가` 상태의 의류수량이 약 1000개 가량됩니다.

이 같이 많은 수의 의류가 `대여불가` 상태가 된 이유는, 의류가 대여되지 않아야 할 때 `수선`, `세탁`, `예약` 외에는 다른 상태를 표기할 방법이 없었기 때문입니다. 가령 여름시기에 동복인 의류의 상태, 고도몰에서 사용하는 온라인 의류가 대표적인 예입니다. 그래서 기존에는 `대여불가` 상태를 잘 사용하지 않았지만, 검색을 통해 대여가능 의류가 모니터에서 추천되는 시스템이 도입되고 난 후부터, 추천되면 안되는 의류의 경우에는 `대여불가`로 상태를 변경하고 있었습니다.

`대여가능`, `대여중`, `세탁`, `수선`, `반납` 상태외에 
`대여불가` 상태도 가용 수량에 포함될 수 있도록 상태 추가를 요청드립니다.

**Comment by keedi** [comment]
진행합니다.

**Comment by keedi** [comment]
@10001if 무슨 말인지는 이해했습니다. 수량 통계 페이지는 2개로 나뉩니다. 전체 항목을 보여주는 페이지와 세부 한 항목에 대한 통계 페이지로 나뉘죠. 세부 항목 페이지에도 대여불가를 표시할 것인지요? 애초에 세부 항목 페이지에서 모든 상태를 보여주었다면 확인없이 추가했을텐데 당시 모두 말고 몇몇 상태만 보여주길 원하신 결과가 현재 상태이거든요. 확인 부탁드립니다.

**Comment by 10001if** [comment]
@keedi 네. 세부항목에서도 표시해주시는 것이 필요합니다. 부탁드리겠습니다~

**Comment by keedi** [comment]
구현 완료한 화면은 다음과 같습니다.

모든 카테고리가 보이는 화면입니다. 기존과 비교해서 대여불가 상태 의류가 추가되면서 수치가 전체적으로 변경되었음을 확인할 수 있습니다.
![2016-08-11 17-18-56](https://cloud.githubusercontent.com/assets/138451/17618323/fdd1a59c-60b9-11e6-869b-2f1fe816d6a3.png)

세부 의류 항목 화면입니다. 대여불가 상태 의류 개수를 보여줄 수 있는 열이 추가되었습니다.
![2016-08-12 18-22-01](https://cloud.githubusercontent.com/assets/138451/17618325/ffbd4bc2-60b9-11e6-93d7-b1b301f3efcc.png)

**Comment by keedi** [comment]
작업 완료했으므로 이슈 닫습니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
