### ISSUE TITLE
대여탭에서 사용자 상태를 방문으로 바꾸는 퀵메뉴 추가, 탈의와 수선 상태를 대여로 바꾸는 버튼 추가

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#929]
현재 5층에서 안내/포장/결제가 많이 밀린다고 합니다.

결제가 밀리는 이유는 반납 안내를 물리적으로 설명하는 최소시간이 존재하기 때문이라 본 이슈는 내부적으로 고민이 필요합니다. 하지만 포장과 안내는 시간을 조금 더 줄일 수 있을 것 같습니다. 대표적인 것이 3가지의 화면을 하나로 통합하여 하나의 화면에서 업무를 진행하는 것입니다.

포장 안내를 하는 담당인원은 1. 시간표 화면, 2. preparation 화면 3. 대여탭을 보고 있어야 합니다.

3가지 화면을 이동하며 작업을 하는 것이 숙달된 인원 에게는 별로 어렵지 않지만, 일반적으로 포장/안내는 봉사자가 담당하기 때문에 3가지 화면을 이동하며 작업하는데에 어려움을 많이 겪고 있다고 합니다.

따라서 다음과 같은 화면을 요청드리고자 합니다.

![2016-08-17 6 22 42](https://cloud.githubusercontent.com/assets/4696328/17731385/fcc650fc-64a7-11e6-9382-63f7bbece665.png)

1. 대여탭에서 탈의중인 사람과 수선 중인 사람을 포장으로 넘기는 버튼이 추가되었으면 합니다. 이때 바지길이도 입력할 수 있어야 합니다.

2. 시간표를 보지 않고 방문자의 상태를 `방문예약`에서 `방문`으로 변경 할 수 있도록 퀵메뉴가 생성되어야 합니다.

**Comment by 10001if** [comment]
@aanoaa 갑자기 방문자가 많아지고 있는데, 휴가자가 많아 포장/안내에 병목현상이 매우 심하다고 합니다. 온라인 작업으로 바쁘시겠지만 급하게 작업 요청 드립니다. ^^

**Comment by aanoaa** [comment]
업무분업과 처리방식이 변경되면서 발생한 이슈입니다.

탈의/수선 상태의 사용자 변경은 어려운 것이 아니지만,
실시간으로 상태가 변경되는 사용자를 추적해서 보여주어야 합니다.

**Comment by aanoaa** [comment]
바지길이는 선택이 아닌 직접 입력할 수 있도록 하겠습니다.

**Comment by aanoaa** [comment]
모든 상태를 변경할 필요가 없고,

    방문예약 -> 방문

만이 필요한 것이라면, 오늘 방문자를 검색해서 보여줄 수 있도록 하고
버튼 하나로 `방문예약 -> 방문` 이 될 수 있도록 하겠습니다.

**Comment by 10001if** [comment]
@aanoaa 네. 말씀하신 것처럼 `방문예약 -> 방문`이면 충분합니다. 다만, 전화번호 뒷자리가 같은 사람이 하루에 2인 이상 발생할 수 있으므로 식별이 가능하도록 `이름` `전화번호` `예약시간`이 표시되고 방문으로 바꿀 수 있도록 요청드립니다.  그리고 전화번호는 010-1234-5678 인 경우, 일반적으로는 뒤에 4자리만 묻고 입력할 것 같은데. 이 때 입력창에는 뒤에 4자리만 넣게 하는게 좋을지 모든 숫자를 다 넣을 수 있게 하되 뒤 4자리만 넣으면 검색이 되도록 하는게 좋을지 잘 모르겠습니다~ 의견 부탁드리고 싶어요.

**Comment by aanoaa** [comment]
꼭 뒷자리 4자리가 아니라 이름/이메일/전화번호로 검색이 될 수 있으면 되지 않을까요?
검색결과에 위 세개의 정보를 모두 표시해주면 검색도 편하고 구분하기도 좋을 것 같습니다.

**Comment by 10001if** [comment]
@aanoaa 네! 그러네요. 그러면 훨씬 더 자유롭고 편할 것 같습니다. ^^

**Comment by 10001if** [comment]
그리고 검색결과에 `예약시간`도 표시되도록 요청드립니다. `예약시간`보다 너무 빨리 오거나 늦게 오신 경우에는 정시에 방문한 대여자 분들이 많이 계실 경우 기다릴 수 있다는 안내를 해드려야 하거든요~

**Comment by aanoaa** [comment]
바지길이를 넣을 수 있도록 하면 지저분해지는데..

**Comment by aanoaa** [comment]
이미 지저분하긴 하다능

**Comment by 10001if** [comment]
@aanoaa 네.. 이미 더러워졌습니다 ㅎㅎ

**Comment by 10001if** [comment]
@aanoaa 아침에 회의시간에 테스트를 하다가 알게되었는데요. 대여자의 의류포장을 위해 바코드를 찍고 있는 동안 상단의 탈의실에 있는 대여자를 포장상태로 바꾸거나, 방문자를 찾아 방문을 누르면 화면전체가 새로고침되어 포장으로 의류를 찍고 있던 품목들이 모두 사라집니다. 제가 너무 쉽게 생각해서 이야기를 드렸나봐요. 혹시 문제를 해결할 방법이 없을까 싶어.. 우선 이슈 남깁니다. 확인 부탁드릴게요. 

![2016-08-19 9 58 20](https://cloud.githubusercontent.com/assets/4696328/17795583/a981d7e2-65f4-11e6-807a-f51d60b0ad38.png)

**Comment by aanoaa** [comment]
수정하였습니다.
다음 버전에 적용됩니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^

**Comment by keedi** [comment]
무시무시한 기능이군요. ㅎ :)
