### ISSUE TITLE
2016년 9월 24일(일)부터 일요일 영업을 시작함에 따라 예약 인원을 평일처럼 4인으로 변경하도록 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#930]
기존에는 일요일에는 영업을 하지 않았기 때문에 `활성화` 버튼을 눌러도 0명으로 열렸습니다. 하지만 24일부터 일요일 영업을 실시할 예정이므로 일요일도 평일과 같이 4명으로 지정되어 열릴 수 있도록 수정 요청드립니다.

**Comment by 10001if** [comment]
@aanoaa 2 주 전에는 예약을 활성화 시키기 때문에 9월 초 정도까지 수정해 주시면 될 것 같습니다. ^^

**Comment by aanoaa** [comment]
설정파일을 수정해서 해결하였습니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
