### ISSUE TITLE
일요일 영업을 시작함에 따라 봉사신청 인원을 3인으로 변경

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#931]
9월 24일(일)부터 일요일 영업을 시작함에 따라 봉사신청 인원을 2인으로 변경하도록 함

**Comment by 10001if** [comment]
@aanoaa 봉사자분들이 미리 봉사신청을 할 수 있도록 작업 요청드립니다~ ^^

**Comment by 10001if** [comment]
@aanoaa 출근하시면 확인 부탁드리겠습니다. ^^

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^

**Comment by 10001if** [comment]
@aanoaa 제가 봉사시간 입력이 되는지만 확인을 했었는데, 오늘 직접 봉사 신청을 시도해 보니 마지막에  `400 Error bad request - not allow activity date: sunday 라는 메세지가 뜨면서 봉사 신청이 되지 않습니다. 일요일 봉사 신청이 가능하도록 한번 더 확인 부탁드립니다. ^^

**Comment by aanoaa** [comment]
수정하였습니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
