### ISSUE TITLE
기증자의 기증 품목에 대한 대여 정보를 사용자 정보에서 확인할 수 있도록 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#932]
![2016-08-18 4 06 15](https://cloud.githubusercontent.com/assets/4696328/17764985/0feb9ac8-655e-11e6-9180-76c87e3312da.png)

현재는 기증자가 몇 개의 품목을 기증했는지는 확인할 수 있습니다.
하지만 기증물품이 품목별로 구분되어 카운트되지는 않습니다. 
@aanoaa 도움주신 기증신청 페이지에서는 세부 품목을 확인 할 수 있습니다.

1. 사용자 화면에서도 기증물품이 구분되어 카운트 되었으면 합니다. 예) 총 17개 : 자켓 6개, 바지 6개, 타이 5개

2. 더불어 기증자의 기증물품이 대여된 주문서 횟수을 보고 싶습니다. 예) 10회 

3. 각 품목별로 대여된 횟수의 표기 요청드립니다. 예) 품목별 총 대여된 횟수 30회 : 자켓 10회, 바지 10회, 타이 10회

**Comment by aanoaa** [comment]
>  @aanoaa 도움주신 기증신청 페이지에서는 세부 품목을 확인 할 수 있습니다.

예를 들면 https://donation.theopencloset.net/users/42987/donations 와 같은 화면입니다.

**Comment by keedi** [comment]
내용 전달 받았습니다. 제가 처리하겠습니다.

**Comment by keedi** [comment]
진행합니다.

**Comment by keedi** [comment]
기증 신청 페이지 화면은 다음과 같습니다.

![screenshot-donation theopencloset net 2016-10-05 18-42-05](https://cloud.githubusercontent.com/assets/138451/19108369/92bed2a6-8b2b-11e6-84de-d50099633f83.png)

**Comment by aanoaa** [comment]
https://github.com/opencloset/donation/blob/develop/lib/OpenCloset/Donation/Plugin/Helpers.pm#L297

이걸 참고하시면 도움이 될 것 같습니다.

**Comment by keedi** [comment]
특정 아이디의 기증 물품의 품목별 개수를 확인하는 질의는 다음과 같습니다.

```sql
SELECT
    u.id            AS user_id
    , u.name        AS user_name
    , c.category    AS clothes_category
    , COUNT(*)      AS clothes_category_count
FROM `user` AS u
LEFT JOIN `donation` AS d ON d.user_id     = u.id
LEFT JOIN `clothes`  AS c ON c.donation_id = d.id
WHERE (
    u.id = 1                  -- 사용자 아이디
    AND d.id   IS NOT NULL    -- 기증 내역이 있어야 함
    AND c.code IS NOT NULL    -- 기증 의류 내역이 있어야 함
)
GROUP BY c.category
ORDER BY c.category ASC -- 품목별 정렬
;
```

**Comment by keedi** [comment]
툭정 기증자의 기증 의류를 대여한 모든 내역(주문서) 횟수를 확인하는 질의는 다음과 같습니다.

```sql
SELECT
    u.id                     AS d_user_id
    , u.name                 AS d_user_name
    , COUNT( DISTINCT o.id ) AS order_count
FROM `order_detail` AS od
LEFT JOIN `order`    AS o ON o.id   = od.order_id
LEFT JOIN `clothes`  AS c ON c.code = od.clothes_code
LEFT JOIN `donation` AS d ON d.id   = c.donation_id
LEFT JOIN `user`     AS u ON u.id   = d.user_id
WHERE (
    u.id = 6738              -- 사용자 아이디
)
ORDER BY d.create_date ASC  -- 기증 날짜 순 정렬
;
```

**Comment by keedi** [comment]
특정 기증자의 의류 품목별로 대여된 횟수를 확인하는 질의는 다음과 같습니다.

```sql
SELECT
    u.id                           AS d_user_id
    , u.name                       AS d_user_name
    , c.category                   AS clothes_category
    , COUNT(*)                     AS count_category
FROM `user` AS u
LEFT JOIN `donation`     AS d  ON d.user_id       = u.id
LEFT JOIN `clothes`      AS c  ON c.donation_id   = d.id
LEFT JOIN `order_detail` AS od ON od.clothes_code = c.code
LEFT JOIN `order`        AS o  ON o.id            = od.order_id
WHERE (
    u.id = 6738             -- 사용자 아이디
    AND c.code IS NOT NULL  -- 기증 의류 내역이 있어야 함
    AND o.id   IS NOT NULL  -- 주문 내역이 있어야 함
)
GROUP BY c.category
;
```

**Comment by keedi** [comment]
질의는 확인 완료했습니다. 질의 자체에 문제가 없는지 검증한 다음 이상이 없다면 화면상에 어떻게 구성할지 논의한 다음 마무리 짓겠습니다.

**Comment by keedi** [comment]
관련해서 @10001if 님께서 정리해주시는 자료와 상기 질의를 이용해서 나오는 결과를 비교해서 결과가 정확한지 샘플 테스트를 진행하기로 했습니다. 결과에 문제가 없으면 상기 질의를 바로 적용합니다.

우선 결과가 맞다손 치고 웹 화면에 보여질 수 있도록 작업을 진행합니다.

**Comment by 10001if** [comment]
- 2회 기증 : user/2535
1) 총 14 : 자켓 7, 팬츠 7
2) 22번 대여
3) 총 42 : 자켓 21, 팬츠 21

**Comment by 10001if** [comment]
- 5회 기증 : user/3474 

1) 총 38 : 자켓 19, 팬츠 16, 구두 3
2) 154번 대여
3) 총 246 : 자켓 128, 팬츠 118

**Comment by 10001if** [comment]
- 1회 기증 : user/7224 (대여가 많이 된 기증자)

1) 총 4 : 자켓 2, 팬츠 2
2) 127번 대여
3) 총 254 : 자켓 127, 팬츠 127

**Comment by 10001if** [comment]
- 28회 기증 : user/7635

1) 총 1173 : 블라우스 1, 자켓 52, 팬츠 95, 셔츠 1025 

본 사용자에 대해서 문의드릴 사항이 있습니다. 오시면 다시 여쭤보도록 할게요 ^^

**Comment by keedi** [comment]
> 2회 기증 : user/2535
> 
> 1) 총 14 : 자켓 7, 팬츠 7
> 2) 22번 대여
> 3) 총 42 : 자켓 21, 팬츠 21

제가 확인한 결과로는 1 항목은 동일하나 2, 3 항목 값이 다릅니다. 같이 이야기를 좀 나눠봐야 할 것 같습니다.

**Comment by 10001if** [comment]
@keedi 문제 있는 부분은 수정해서 변경해 놓았습니다.

**Comment by keedi** [comment]
수정한 자료의 현재 시점 기준으로 5회 기증 3474 사용자의 자료중 2, 3 항목 결과가 좀 다릅니다. 다시 확인이 필요합니다.

**Comment by 10001if** [comment]
5회 기증 : user/3474
1) 총 38 : 자켓 19, 팬츠 16, 구두 3
2) 288번 대여
3) 총 436 : 자켓 185, 팬츠 176, 구두 75

@keedi 다시 세본 결과 입니다.

**Comment by keedi** [comment]
3번 항목은 동일하며 2번 항목이 데이터베이스상 결과는 286번으로 나오는데 2개의 차이가 있었습니다. 관련해서 같이 디버깅한 결과 다음과 같이 주문서가 중복되는 경우가 있었습니다.

어떤 기증자가 여러차례에 걸쳐 기증을 했고 대여자가 해당 기증자의 1회 기증 재킷과 2회 기증 바지, 3회 기증 셔츠를 대여할 경우 사실 동일한 기증자의 의류를 빌려간 것이지만 각각의 기증 행위는 동일한 주문서와 연결이 되기 때문에 중복되는 경우가 있었습니다.

상기 현상은 버그가 아니며 의도된 결과이며 2번 항목을 계산할 때 미처 예상치 못해 중복이 되었던 것입니다. 중복을 제거한 후 결과를 확인했을 때는 제가 계산한 내역이나 @10001if 님께서 계산한 내역이 동일함을 확인했습니다.

**Comment by keedi** [comment]
UI 작업 진행중입니다. 금주 중에 마무리 지을 예정입니다.

**Comment by keedi** [comment]
각각의 1, 2, 3 항목의 값을 구하는 질의를 DBIC로 변환하면 다음과 같습니다.

```perl
    my $donated_items = +{};
    {
        my $rs = $user->donations->search(
            {
                "me.id"        => { "!=" => undef },
                "clothes.code" => { "!=" => undef },
            },
            {
                join      => ["clothes"],
                group_by  => ["clothes.category"],
                "columns" => [
                    { category => "clothes.category" },
                    {
                        count => { count => "clothes.category", -as => "clothes_category_count" },
                    },
                ],
            },
        );

        my %result;
        while ( my $row = $rs->next ) {
            my %clothes = $row->get_columns;
            my $category_to_string =
                $OpenCloset::Constants::Category::LABEL_MAP{ $clothes{category} };
            $result{$category_to_string} = $clothes{count};
        }

        $donated_items = \%result;
    }

    my $rented_order_count = 0;
    {
        my $rs = $user->donations->search(
            {
                "clothes.code" => { "!=" => undef },
                "order.id"     => { "!=" => undef },
            },
            {
                join      => [
                    { "clothes" => { "order_details" => "order" } },
                ],
                group_by  => ["order.id"],
            },
        );
        $rented_order_count = $rs->count;
    };

    my $rented_category_count = +{};
    {
        my $rs = $user->donations->search(
            {
                "clothes.code" => { "!=" => undef },
                "order.id"     => { "!=" => undef },
            },
            {
                join => [
                    { "clothes" => { "order_details" => "order" } },
                ],
                group_by  => ["clothes.category"],
                "columns" => [
                    { category => "clothes.category" },
                    { count    => { count => "clothes.category" } },
                ],
            },
        );

        my %result;
        while ( my $row = $rs->next ) {
            my %clothes = $row->get_columns;
            my $category_to_string =
                $OpenCloset::Constants::Category::LABEL_MAP{ $clothes{category} };
            $result{$category_to_string} = $clothes{count};
        }

        $rented_category_count = \%result;
    }
```

**Comment by keedi** [comment]
구현 완료한 화면은 다음과 같습니다.

![screenshot-monster silex kr 10301 2016-10-11 13-59-39](https://cloud.githubusercontent.com/assets/138451/19259392/39dfe004-8fbc-11e6-9945-8e7e0bf988bb.png)

**Comment by keedi** [comment]
@10001if 피드백 부탁드립니다.

**Comment by 10001if** [comment]
@keedi 품목별 대여된 횟수가 아래로 보이고 있는데, 상단에 총 합계도 보여주었으면 합니다. ^^

**Comment by keedi** [comment]
품목별 대여된 횟수 옆에 총 합계만 추가로 넣어주면 될 것 같습니다. 디자인적인 부분이나 위치 등은 확인을 받았습니다. 해당 부분 마무리 짓고 머지한 후 이슈 닫겠습니다. :)

**Comment by keedi** [comment]
작업 완료한 화면은 다음과 같습니다.

![screenshot-monster silex kr 10301 2016-10-14 18-27-34](https://cloud.githubusercontent.com/assets/138451/19382621/01b512a8-923c-11e6-937e-a6b52a35b5a0.png)

**Comment by keedi** [comment]
이슈 닫습니다. :-)
