### ISSUE TITLE
결제대기 상태에서 주문확정이 되지 않음

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#934]
1.8.14 버전에서 주문확정이 되지 않음

결제대기 상태에서 주문확정이 안눌러진다고 합니다.

해서 이전버전으로 되돌리고 서비스 재시작하였습니다.

이제 원인파악을 해봐야 합니다.

**Comment by aanoaa** [comment]
36678 주문서의 주문확정을 눌렀을때에 에러입니다.

    [Fri Aug 19 10:39:25 2016] [error] Can't call method "name" on an undefined value at lib/OpenCloset/Web/Controller/Order.pm line 553.

    sprintf(
        "  order_detail.status: %d [%s] -> [%s]",
        $order_detail->id,
        $order_detail->status->name // 'N/A',
        $status{$value} // 'N/A',
    ),

**Comment by aanoaa** [comment]
36677 은 주문확정이 되었다고 합니다.
36678 만 안되는건지, 36677 만 되었던건지 확인을 해봐야 합니다.

**Comment by aanoaa** [comment]
https://monitor.theopencloset.net/target_date
    교차 출처 요청 차단: 동일 출처 정책으로 인해 https://monitor.theopencloset.net/target_date에 있는 원격 자원을 차단하였습니다. (원인: 'Access-Control-Allow-Origin' CORS 헤더가 없음).

주문서페이지에 들어가면 위와 같은 에러메세지가 나타납니다.

**Comment by aanoaa** [comment]
반납일을 계산에 사용되는건데 언제부터 안된건지 모르겠습니다.

**Comment by aanoaa** [comment]
36678 주문서가 주문확정이 되어있습니다.

**Comment by aanoaa** [comment]
모니터쪽 로그입니다.
제 PC 에서 auth 를 통과하지 못해서 발생하는 문제였던것 같습니다.
열린옷장에서는 정상적으로 동작할 것 같습니다.

    [Fri Aug 19 10:53:29 2016] [debug] GET "/target_date"
    [Fri Aug 19 10:53:29 2016] [debug] Routing to controller "OpenCloset::Monitor::Controller::User" and action "auth"
    [Fri Aug 19 10:53:29 2016] [warn] denied address: xxx.xxx.xx.xx

**Comment by aanoaa** [comment]
36291 안되다가 된다
36480 안됨
36679 안됨

**Comment by aanoaa** [comment]
order_detail 의 status_id 가 NULL 일때 이런 문제가 발생하는 것 같고,

https://github.com/opencloset/opencloset/blob/develop/lib/OpenCloset/Web/Controller/Order.pm#L495

에서 오타가 문제인 것 같습니다.

버전을 되돌려서 진행했던 주문서는 정상적으로 서비스 되는데,
1.8.14 버전으로 진행되었던 주문서 중에 order_detail 의 status_id 가 NULL 인 것들을 찾아서,
제값을 넣어주어야지 주문확정이 될 것으로 보입니다.

**Comment by aanoaa** [comment]
위에 주문서번호들이 많은데
통화하면서 정신없이 적어서 이상한게 많습니다.
아래 3개의 주문서가 문제가 있는 주문서입니다.

- 36681
- 36480
- 36316

**Comment by aanoaa** [comment]
임시로 로그를 찍는 부분을 제거 하고 문제가 있는 주문서에 대해 처리를 마친후에 되돌려서 서비스하는 방법도 있을 수 있습니다.

**Comment by aanoaa** [comment]
위 코멘트대로 처리한다면,
로그는 안남지만, NULL 이었던 status_id 가 2 (대여중) 으로 변경되고 주문확정인 상태가 됩니다.
NULL 인 상태로 남지않아서, 반납등 이후 처리에도 문제가 없을 것 같습니다.

**Comment by aanoaa** [comment]
점심시간을 이용해서 계속 결제대기 상태로 남아있는 2개의 주문서에 대해 처리하도록 하겠습니다.

@10001if 문제가 되는 주문서의 번호를 기록해두셨다면 알려주세요.

**Comment by aanoaa** [comment]
> https://monitor.theopencloset.net/target_date

이 경로에 대해서는 인증없이 서비스하는 것이 더 좋을 것 같습니다.

**Comment by aanoaa** [comment]
https://github.com/opencloset/monitor/commit/eb4f9eee8d6682d37a5f6e7b5287c5befd32d40d

**Comment by aanoaa** [comment]
문제가 되던 두개의 주문서에 대해 주문확정을 하였습니다.
현재 서비스중인 버전은 v1.8.13 입니다.

**Comment by 10001if** [comment]
@aanoaa 남아있는 2개의 주문서 외에는 문제되는 것이 없었습니다. 점심에 처리해 주셔서 감사합니다~!

**Comment by keedi** [comment]
#790 이슈를 해결하면서 제가 작성한 코드에 버그가 있어서 발생한 것으로 보입니다.

**Comment by keedi** [comment]
오류가 있던 실DB는 @aanoaa 님께서 이미 수정해주셨습니다. 코드는 제가 확인 후 수정하겠습니다. :)

**Comment by keedi** [comment]
> 위에 주문서번호들이 많은데
> 통화하면서 정신없이 적어서 이상한게 많습니다.
> 아래 3개의 주문서가 문제가 있는 주문서입니다.
> 
>     ~~36681~~
>     36480
>     36316

ᅟ36681의 경우 부분 반납중이던 주문서입니다. 관련없어 보이긴하네요. 그래서 줄로 그어놓으신거려나요?

**Comment by aanoaa** [comment]
네 맞습니다. 36681 은 관련이 없습니다.

**Comment by keedi** [comment]
테스트 해본 결과 상기 오타 문제를 해결한 뒤에는 주문 확정에 문제 없음을 확인했습니다.
