### ISSUE TITLE
대여 품목이 중복된 주문서

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#936]
주문서 37868 를 보면 대여품목이 두개씩 중복되어 있습니다.
어떻게 해서 이런일이 발생했는지 확인해 볼 필요가 있습니다.

![screenshot-staff theopencloset net 2016-09-05 17-55-50](https://cloud.githubusercontent.com/assets/170528/18242620/1b0883fc-7392-11e6-82cb-b89705600f51.png)

**Comment by aanoaa** [comment]
`선택한 항목을 대여합니다.` 버튼을 두번 누른게 아닐까 합니다.
진행중일때에 버튼을 누를 수 없도록 해야 하는데 그처리가 아니되어 있어서
더블클릭이 되었다거나 했을때 중복된 요청에 의해서요.

**Comment by keedi** [comment]
담당자 변경합니다.

**Comment by 10001if** [comment]
이슈가 발생하면 다시 열도록 하겠습니다.
