### ISSUE TITLE
누적 봉사활동인원

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#938]
@10001if said,

> 그리고 여태까지 봉사하신 봉사자 분들 합계인원을 좀 알려주세요~ 다음주에 전시하는데 정보가 필요해서요~ ^^

**Comment by aanoaa** [comment]
`Tue, 06 Sep 2016 13:54:40 +0900` 기준으로 실제로는 더 많겠지만, 자원봉사 서비스를 활용한
이후부터는 `340`명 입니다. 이중에는 여러번 하신 분들도 많습니다.

    mysql> SELECT COUNT(*) FROM volunteer;
    +----------+
    | COUNT(*) |
    +----------+
    |      340 |
    +----------+

**Comment by 10001if** [comment]
@aanoaa 자원봉사 서비스를 활용한 시점이 언제인지 확인 부탁드릴 수 있을까요?

**Comment by aanoaa** [comment]
Wed Aug 5 17:43:00 2015 +0900

2015 년 8월 5일 입니다.
