### ISSUE TITLE
추석연휴 기간인 2016년 9월 14일부터 9월 18일까지 봉사 신청을 받지 않도록 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#940]

**Comment by aanoaa** [comment]
14, 15, 16일은 공휴일이고, 17일은 토요일 18일은 일요일입니다.
이미 14, 15, 16, 18일은 신청을 할 수 없습니다.

17일도 운영안하시는건가요?

**Comment by 10001if** [comment]
@aanoaa 네! 17일 운영하지 않습니다. ^^

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
