### ISSUE TITLE
의류 사진 등록

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#941]
새로운 사진을 받았습니다. 등록함과 동시에 `사진촬영` 태그를 달아주어야 하고, 기존 태그는
삭제해야 합니다.

**Comment by 10001if** [comment]
@aanoaa 새로운 사진을 메일로 발송하였습니다. `사진촬영` 태그는 제가 제거하였습니다. 추가 이슈가 생기면 다시 요청드리도록 하겠습니다. ^^
