### ISSUE TITLE
다른 사용자가 동일한 쿠폰으로 방문예약이 되는 현상

### ISSUE THREAD

**Issue by yongbin** [opencloset/opencloset#942]
#916 을 통해 발견된 이슈입니다. #916은 이 문제에 영향을 받지 않는 방향으로 해결되었지만 이 현상 자체는 다른 문제를 유발할수 있기 떄문에 별도로 확인해서 처리되어야 합니다. 문제에 대한 자세한 서술은 다음 코멘트를 참고하면 됩니다.
- https://github.com/opencloset/opencloset/issues/916#issuecomment-236838073
- https://github.com/opencloset/opencloset/issues/916#issuecomment-243685721
- https://github.com/opencloset/opencloset/issues/916#issuecomment-243981947

이 현상으로 이 잘못발행된 쿠폰은 현재까지 아래 두건입니다.
- 주문서 번호 29522, 29521 에 사용된 쿠폰 2715
- 주문서 번호 41349, 41345 에 사용된 쿠폰 4041

**Comment by 10001if** [comment]
@yongbin 취업날개 서비스를 2월 중에 다시 시작하게 될 것 같습니다. @aanoaa 설명을 들은 바로는 본 오류 수정이 필요하다고 들었습니다. 수정 요청드리겠습니다.

**Comment by yongbin** [comment]
네 쿠폰 발급 및 사용에 있어서 한번 쿠폰을 발급받은 PC로 재발급 받을경우 발생하는 문제와 쿠폰 발급이후 URL에 직접 접근해서 쿠폰을 중복사용하는 문제등이 있습니다. 쿠폰기능을 전반적으로 형석님이 작업하셨기 형석님이 진행하시는게 맞는것 같습니다. 담당자 할당하겠습니다.

**Comment by aanoaa** [comment]
#1111 에서 확인했을때 중복 지급된 쿠폰은 100건이 넘었습니다.

1. 취업지원센터의 URL이 공유됨
2. 세션공유로 인한 프로그램 버그

두가지 경로를 통해서 쿠폰이 중복 지급됩니다.

두개의 문제 모두 수정해야 합니다.

**Comment by aanoaa** [comment]
지급조건에 대해서 다시 한번 적어보겠습니다.

> 각 사용자는 1년에 2회 서울시 이벤트 쿠폰을 사용할 수 있다.

방문안함을 고려해서 한 사용자에게 같은 쿠폰을 여러번 발급합니다.

- `xxxx` - 방문안함
- `xxxx` - 방문안함
- `xxxx` - 대여
- `yyyy` - 방문안함
- `yyyy` - 대여

이럴 경우에는 5번 방문예약을 해서 2개의 쿠폰을 3번, 2번 지급받은 후에 1번씩 사용한 것입니다.
방문하지 않았을 경우에 폐기하는 절차는 없습니다.

**Comment by aanoaa** [comment]
현재 쿠폰의 상태는 아래와 같습니다.

- 발행: NULL
- 지급: provided
- 사용: used
- 폐기: discarded

방문예약만 하고 방문하지 않았을때에 지급된 쿠폰을 어떻게 처리해야 하는가?
이것이 문제가 됩니다.

쿠폰을 받아서 쿠폰코드를 입력하고 방문예약을 했지만 방문을 하지 않았습니다.
이때에 쿠폰은 사용한 것일까요 아닐까요?

지난해의 경우는 이것은 사용하지 않은 쿠폰으로 여기고 다음번 방문예약때에
다시 사용가능하도록 허용했습니다.

이것이 문제가 되어서 여러 주문서에 동일한 쿠폰이 입력되었습니다.
악용한 사례도 있습니다.

서울시 이벤트 같은 경우에는 직접 쿠폰코드를 입력하는 것이 아닌
발행과 지급이 동시에 이루어지기 때문에 상태를 하나 더 추가하면 해결이 될 것 같습니다.

- 예약됨: reserved

하지만 직접 쿠폰 코드를 받은 사용자들은 어찌해야할지 고민해봐야 합니다.

**Comment by aanoaa** [comment]
직접 쿠폰코드를 입력하고 방문하지 않았다면 `예약됨` 쿠폰이 주문서에 남습니다.
다음번에 방문예약을 할때에 이 주문서에는 어떻게 처리해야 할지 고민해야 합니다.

사용할 수 없도록 하면 예약만 하고 사용되지 못한 쿠폰이 남는 것이고,
다시 사용할 수 있도록 하면 하나의 쿠폰이 여러개의 주문서에 들어가는 꼴이 됩니다.

**Comment by aanoaa** [comment]
찾아서 지우고 다시 넣어주는 방법이 있을 수 있습니다.

- A 와 B 가 쿠폰 X 을 공유함
- A 가 X 로 방문예약
- B 가 X 로 방문예약

    이때에 A 의 쿠폰을 제거

이런식으로 한다면 주문서에 쿠폰이 중복되지 않습니다.
사용가능한 쿠폰을 마지막예약한 사람한테만 유효하도록 하는 방법입니다.

방문하지 않았을때에도 다음번에 사용할 수 있습니다.

- A 가 쿠폰 X 로 방문예약
- 방문안함
- A 가 쿠폰 X 로 다시 방문예약

    이때에도 지난날의 방문예약에서 쿠폰을 삭제

**Comment by aanoaa** [comment]
https://github.com/opencloset/OpenCloset-Share-Web/issues/53 진행을 위해서는 이 이슈가 먼저 해결되어야 합니다.

**Comment by aanoaa** [comment]
코멘트를 작성하다보니 얼추 해결방법이 보입니다.

- 쿠폰 상태에 `reserved: 예약됨` 을 추가
- reserved 쿠폰은 다시 예약될 수 있지만 이때에는 기존 주문서의 쿠폰을 가져와서 하는 것
- 서울시 이벤트의 경우, 방문예약을 할때마다(조건이 된다면) 새로운 쿠폰을 발급하는 방식으로 변경

**Comment by aanoaa** [comment]
작년 4000건을 제외하고 올해 667 건의 갯수를 세어야 해서,
이벤트의 이름을 변경하였습니다.

`seoul` -> `seoul-2017`

통계 페이지에 영향이 있을 수 있습니다.
이벤트 이름을 가지고 제대로된 통계가 보일 수 있도록 수정해야 합니다.

**Comment by aanoaa** [comment]
서울시 이벤트의 경우에 방문을 하지 않았더라도 2회 대여가 될때까지는 몇번이든지 방문예약을 할 수 있습니다.
여기서 문제가 발생할 수 있습니다.

**X** URL 이 공유되었다고 가정하면, n 번의 reserved 쿠폰이 생성됩니다.
used 가 2회를 넘지 않았기 때문에 몇건이든 발급합니다.

총 횟수는 제한 되어 있더라도 **X** 는 2회 이상 대여를 한 셈이 됩니다.

**Comment by aanoaa** [comment]
이런 상황을 막기 위해서는 2회? 이상 reserved 쿠폰을 가지고 있는 사용자는 발급을 중지하고 열린옷장에 문의하라고 안내 할 수 있습니다.

**Comment by aanoaa** [comment]
정상적인 상황에서 연락이 와서 방문예약을 해주어야 하는 상황이 발생했을때 해결해주어야 합니다.

- A 는 쿠폰을 지급 받아서 2회 방문예약을 했지만 방문하지 않았다
- A 가 다시 쿠폰을 사용해서 예약하려고 했을때에 문제가 발생(2회 이상 reserved)

방문하지 않은 주문서를 찾아서 삭제하면 해결 할 수 있지만 그레이스풀 하지 않습니다.

**Comment by aanoaa** [comment]
reserved 상태의 주문서가 존재하고 현재 시간이 예약시간보다 이르다면
쿠폰을 발행하지 않으면 될 것 같습니다.

URL 이 공유되었다면 마지막 주문서의 방문예약 이후에 쿠폰발행이 가능해집니다.

**Comment by aanoaa** [comment]
쿠폰발행과 방문예약 사이에 텀이 있습니다.
쿠폰발행후에 방문예약을 하지 않은 상태에서는 마찬가지로 여러건의 쿠폰발행이 가능합니다.

    이벤트 페이지 들어온다 <--- 요사이 ---> 방문예약 한다

**Comment by aanoaa** [comment]
@10001if 은행은 올해 이벤트의 주최자가 아니므로 빠져야 하지 않나요?
이벤트 페이지의 내용 또한 바뀌어야 합니다.

**Comment by aanoaa** [comment]
쿠폰을 발행해서 지급 -> provided
쿠폰을 사용해서 방문예약을 함 -> reserved

으로 상태를 설정하고 1건 이상 지급되지 않게 하면 될 것 같지만 이것 또한 문제가 있습니다.

- 이벤트 페이지에 들어옴(provided)
- 방문예약하지 않음
- 시간이 지나서 다시 이벤트 페이지에 들어옴
  - 아니됨
  - ??

**Comment by aanoaa** [comment]
1. 이벤트 참여(provided)
2. 방문예약(reserved)
3. 실제로 대여(used)

- 이벤트 참여와 방문예약은 여러번 가능하지만 실제로 대여는 2번만 가능
- 방문예약을 해야지만 사용자 정보가 기록됨
- URL 이 공유되면 여러명에게 쿠폰이 지급될 수 있음
  - 지급된 쿠폰이 예약되지 않았을때에 지급을 중지함
  - 지급만 받고 방문예약 하지 않은 사용자는 2회 대여를 할 수 없게 됨

딱 2회 지급이면 편리한데, 여러번 지급 여러번 예약은 가능하지만 2회 사용이라서 어렵습니다.

**Comment by aanoaa** [comment]
provided 쿠폰을 여러명한테 주지만, 예약할때에 이전 사용자의 쿠폰 기록을 지우면 되지않을까 싶습니다.

시나리오1

- 홍길동이 쿠폰 C 를 받음
- 둘리가 쿠폰 C 를 받음
- 홍길동이 쿠폰 C 로 예약
- 둘리가 쿠폰 C 로 예약
  - 이때 홍길동의 쿠폰은 사라짐
  - 예약시점에 쿠폰이 이미 사용되었다면 쿠폰없이 예약됨

---------------------

시나리오2

- 홍길동이 쿠폰 C 를 받음
- 한달후..
- 홍길동이 쿠폰 C 를 받음
- 홍길동이 쿠폰 C 로 예약
- 홍길동이 쿠폰 C 를 사용해서 대여함

**Comment by yongbin** [comment]
> 통계 페이지에 영향이 있을 수 있습니다.
> 이벤트 이름을 가지고 제대로된 통계가 보일 수 있도록 수정해야 합니다.

확인해보니 기존 이벤트 페이지에서 `coupon_type`을 구분하지 않고 통계를 내고 있었습니다. 이 이슈가 처리되고 나면 수정된 내용에 맞게 통계쪽도 같이 수정하겠습니다.

**Comment by aanoaa** [comment]
저희쪽에서 배포하면 이벤트 테스트 후에 진행이 가능합니다.

@10001if

**Comment by aanoaa** [comment]
이게 작년에 2회 대여 했더라도 오해는 reset 되는게 맞지요?

@10001if

**Comment by aanoaa** [comment]
이벤트의 시작은 2월 8일 입니다.

**Comment by aanoaa** [comment]
> 이게 작년에 2회 대여 했더라도 오해는 reset 되는게 맞지요?

맞습니다.
