### ISSUE TITLE
3회 이상 대여자의 할인시 할인 내역을 주문서에 표시

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#946]
현재 3회 이상 대여자의 할인정책이 반영되어 할인을 실시하고 있습니다.

하지만 실제 할인이 적용되었는지 확인이 조금 어렵다고 합니다.

따라서 다음과 같이 수정을 요청드리고자 합니다.

![2016-09-26 4 42 11](https://cloud.githubusercontent.com/assets/4696328/18826658/852b2424-8409-11e6-96d9-5d7fbd81a25f.png)

**Comment by keedi** [comment]
내용 전달 받았습니다. 제가 처리합니다.

**Comment by keedi** [comment]
최종 대여료 밑에 할인 금액도 표시가 되면 좋을 것 같다고 합니다. 즉 예제 화면의 경우 25,000 - 20,000인 할인 금액 5,000원을 표시하면 좋겠다고 합니다.

**Comment by keedi** [comment]
진행합니다.

**Comment by keedi** [comment]
검토해본 결과 3회 이상 할인의 경우 세트 이외 품목 무료와 30% 할인을 두 가지로만 딱 나눌 수 없다는 것을 확인했습니다. 즉, 세트 이외 품목이라고 무조건 무료가 아니라 2셋트에 한해서이기 때문에 2셋트가 넘는 경우 또는 1셋트지만 셋트 구성이 아닌 다른 물품이 있다거나 등등의 경우에선 셋트 무료와 30% 할인이 같이 적용됩니다. (금액적으로 별 차이도 없는데 굳이 이렇게 어렵게 나눈 것은 유감입니다만...;;; ) 어찌됐든 단순히 상단에서 보여주는 것처럼 할인이 적용된 항목이 무엇인지 보여주는 것은 어려워 보입니다.

**Comment by keedi** [comment]
이런 식으로 하면 어떨런지요?

![screenshot-monster silex kr 10301 2016-10-12 16-02-53](https://cloud.githubusercontent.com/assets/138451/19300505/a0e4c5e2-9095-11e6-8620-83e133a57970.png)

@10001if 피드백 부탁드립니다.

**Comment by 10001if** [comment]
@keedi 네! 이렇게 진행해 주시면 될 것 같습니다.
다만, `6. 3회 이상 대여`의 6열은 빨간색 색으로 박스를 감싸던지, 배경색을 칠하던지 해서 3회 이상 대여임을 더 분명하게 보여주면 좋겠습니다. 현장에서 결제를 하다보면 총액만 보고 금액을 지불받는 경우가 종종 생기기 때문입니다.

**Comment by keedi** [comment]
기술적인 이슈로 원래 요청과는 다르게 주문서의 항목 끝단에 할인 내역을 추가하는 방식으로 제안을 드렸습니다.

기술적인 이슈라 함은 주문서를 생성할때 주문서 세부 항목을 DB에 추가만 하는 식으로 웹 요청이 끝나게 구현되어 있습니다. 즉 해당 주문서의 할인 정보(state?)를 웹 요청 사이에 가지고 다닐 방법이 아직은 없다는 의미입니다. 이렇다 보니 주문서 세부 항목 끝단에 약간의 편법으로 3회 이상 대여라는 항목을 넣고 기타 부분에 내용을 적는 식으로 구현을 한 것입니다.

문득 든 생각인데 상기 방식으로 할 경우 기간을 조정할 때 제대로 **기존 대여료**와 **할인 금액**이 제대로 표시 될지 의문입니다. 4일 기준으로 표시하고 있기 때문인데... 흠... 이 부분은 제가 정확하게 확인하겠습니다.

**Comment by keedi** [comment]
OTR, 주문서를 버그질라나 이슈 트래커의 이슈에 가깝게 모델링 했으면 어떨까 하는 아쉬움이 항상 남네요. 돌이켜 생각하면 이렇게 될 줄은 몰랐지만... 어쨌든 설계 미스... 언젠가 모델링을 새로 할 수 있으면 꼭 바꾸고 싶네요. 정확한 아이디어는 없긴하지만...;;;

**Comment by keedi** [comment]
복잡하게 돌아왔는데 어찌되었든 특정 주문서가 어떤 할인 내역에 적용되었는지를 데이터베이스에 기록할 수 있도록 했습니다. `sale` 테이블에는 할인 종류가 들어가며 `order_sale` 테이블에는 `sale.id`와 `order.id`가 조합해 저장합니다. 이로써 최소 3회 이상 할인에 해당하는 주문서가 어떤 주문서인지 확인하는 류의 작업은 이전 기록을 열람한다던가 하는 등의 계산 없이 구할 수 있을 것 같습니다.

**Comment by keedi** [comment]
기술적인 연유로 3회 이상 대여를 `order_detail` 항목에 추가하는 방식을 사용했는데 스키마를 변경한 만큼 이를 사용하지 않을 수도 있을 것 같습니다. 좀 더 진행하겠습니다.

**Comment by keedi** [comment]
OpenCloset-Schema 0.039 버전이 필요합니다. 실서버에는 미리 적용해두었습니다.

**Comment by yongbin** [comment]
> BTW, 주문서를 버그질라나 이슈 트래커의 이슈에 가깝게 모델링 했으면 어떨까 하는 아쉬움이 항상 남네요. 돌이켜 생각하면 이렇게 될 줄은 몰랐지만... 어쨌든 설계 미스... 언젠가 모델링을 새로 할 수 있으면 꼭 바꾸고 싶네요. 정확한 아이디어는 없긴하지만...;;;

저도 공감합니다.

**Comment by keedi** [comment]
구조상 주문서 금액은 몇박 몇일을 선택하느냐에 따라 변동됩니다. 당연히 할인 금액도 변동되어야 합니다. 상기 접근 방식은 포기하고 어짜피 스키마도 수정한 김에 조금 더 근원적으로 문제를 해결하겠습니다. 결과적으로는 @10001if 님께서 처음에 요청하셨던 형태로 표현될 것 같습니다.

**Comment by keedi** [comment]
현재 **주문서 금액**은 자바스크립트의 `updateOrder()` 함수를 이용해 실시간 갱신하고 있습니다. 해당 함수는 `/api/order/<order_id>.json` 요청을 통해 주문서 금액을 산정합니다. **할인 금액** 역시 마찬가지로 요청할 때 서버측에서 미리 연산하고 그 결과를 같이 전달받아 바로바로 갱신해주면 될 것 같습니다.

**Comment by keedi** [comment]
구현 중인 화면은 다음과 같습니다.

![screenshot-monster silex kr 10301 2016-10-20 17-33-30](https://cloud.githubusercontent.com/assets/138451/19552651/b50ad7bc-96eb-11e6-90f3-c92b7df38348.png)

제대로 동작하는지 다양한 경우에 대해 확인 및 피드백 중입니다. 문제 없다면 오늘 중으로 마무리할 수 있을 것 같습니다.

**Comment by keedi** [comment]
정상 동작하는지 여부 확인 완료했습니다. 기능 관련해서 @10001if 님께 보여드렸는데 일단 현재 상태면 충분하다고 합니다. 머지 완료했으므로 이슈 닫습니다.

**Comment by 10001if** [comment]
@keedi 이용을 하다보니, 하단에 보여지는 정보에 대해 헷갈려하는 사람이 많아, 재요청드리고자 합니다.

현재 총액, 할인금액을
`기존 총액`, `할인금액`, `최종 대여료`으로 표시해주시길 요청드립니다.
`기존 총액 - 할인금액 = 최종대여료` 입니다.

그리고 지불받아야 하는 최종 금액인`최종 대여료`는 강조된 표시로 결제자가 다른 금액과 혼동하지 않도록 배경색 or 글씨색 등으로 다르게 노출될 수 있도록 수정 요청드립니다.

**Comment by keedi** [comment]
이미 릴리스 된 이슈이므로 #989 에서 처리합니다. 이슈 닫습니다.

> @keedi 이용을 하다보니, 하단에 보여지는 정보에 대해 헷갈려하는 사람이 많아, 재요청드리고자 합니다.
> 
> 현재 총액, 할인금액을
> 기존 총액, 할인금액, 최종 대여료으로 표시해주시길 요청드립니다.
> 기존 총액 - 할인금액 = 최종대여료 입니다.
> 
> 그리고 지불받아야 하는 최종 금액인최종 대여료는 강조된 표시로 결제자가 다른 금액과 혼동하지 않도록 배경색 or 글씨색 등으로 다르게 노출될 수 있도록 수정 요청드립니다.
