### ISSUE TITLE
대여 확정 시점에 기증 메세지를 별도의 문자로 발송 할 수 있도록 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#949]
현재는 https://github.com/opencloset/opencloset/issues/614 내용처럼 1, 2번의 문자와
https://github.com/opencloset/opencloset/issues/784 의 3번 문자 이렇게 3가지의 내용이 문자로 발송되고 있습니다.

하지만 3번의 기증 메세지를 대여자가 읽을 수 있도록 설명하는 시간이 오래 걸리고 실제 읽기에도 어려워보입니다. 때문에 3번의 내용을 따로 뽑아 문자메세지로 발송하고자 합니다. 자세한 내용은 아래에서 추가하도록 하겠습니다.

**Comment by 10001if** [comment]
기증 메세지에 관련된 내용인 3번 문자를 단독으로 뽑 문자메세지로 전송하려고 합니다.

현재 3번의 내용은 다음과 같습니다.

3.기증이야기 안내 : https://story.theopencloset.net/letters/o/22852/d 를 클릭하시어 오늘 대여하신 의류의 기증이야기를 만나보세요.

여기의 URL은 대여자에 맞는 내용으로 발송되고 있습니다.
하지만 향후에는 다음과 같이 변경되도록 요청드립니다.

[열린옷장] 안녕하세요. OOO님. OO를 기증하신 OOO님의 기증 메세지를 읽어보세요.
`OOO님의 기증메세지`
OOO님이 대여하신 다른 품목의 기증자 이야기를 모두 읽고 싶다면 URL를 클릭해 주세요.

이때, 자켓의 기증 메세지가 없는 경우 다음과 같은 순서로 보여지도록 합니다.

자켓
바지
스커트
원피스
코트
조끼
셔츠
블라우스
타이
벨트
구두
기타

기증메세지가 모두 없는 경우에는 문자를 발송하지 않도록 합니다.

**Comment by 10001if** [comment]
https://github.com/opencloset/opencloset/issues/784 이슈를 보니 @aanoaa 님께서 이슈에 참여하셨던 것 같아 @keedi 님과 함께 등록하였습니다.

**Comment by keedi** [comment]
제가 진행합니다. 급한 이슈라고 합니다.

**Comment by keedi** [comment]
#958 과 더불어 5층의 결제 단계게서 걸리는 시간을 최소화 하기 위해 꼭 필요한 기능이라고 합니다. 우선순위를 높입니다.

**Comment by keedi** [comment]
#946 작업을 진행한다고 많이 늦어졌습니다. 이제 진행합니다.

**Comment by keedi** [comment]
일단 작업은 완료했습니다만, 문구나 전송 조건 등 세부적으로 한번 더 확인해야 합니다. 금요일에 피드백 받은 뒤 문제없다면 마무리 짓겠습니다.

**Comment by keedi** [comment]
화요일 기준으로 세세한 문구 수정 완료했습니다. 목요일 부터 적용할 수 있도록 오늘 수요일 마감 후 서버에 적용할 예정입니다.

실제 테스트로 문자를 전송했을 때 보이는 화면은 다음과 같습니다.

![screenshot_2016-11-02-14-32-41](https://cloud.githubusercontent.com/assets/138451/19917791/a0c6d3fa-a109-11e6-9bf7-2733efbc5af8.png)

**Comment by keedi** [comment]
작업 완료했으므로 이슈 닫습니다.

**Comment by keedi** [comment]
문구 변경 요청이 있습니다.

변경 전 문구는 다음과 같습니다.

```
안녕하세요. 000님. 자켓 지긍자 000님의 ...
```

변경 후 문구는 다음과 같습니다.

```
안녕하세요. 000님.
자켓 지긍자 000님의 ...
```

**Comment by keedi** [comment]
변경 후 문자 전송 시 실제로 보이는 화면은 다음과 같습니다.

![screenshot_2016-11-02-16-42-18](https://cloud.githubusercontent.com/assets/138451/19920336/7fcccb2a-a11b-11e6-9df3-fbf8087ef86f.png)

**Comment by keedi** [comment]
@10001if 확인 부탁드립니다.

**Comment by 10001if** [comment]
확인완료하였습니다 ^^

나의 iPhone에서 보냄

2016. 11. 2. 오후 4:43 Keedi Kim <notifications@github.com> 작성:

**Comment by keedi** [comment]
이슈 닫습니다.

**Comment by keedi** [comment]
배포 완료 되었습니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
