### ISSUE TITLE
주문서 상의 의류 카테고리 목록을 정렬하고자 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#950]
순서는 다음과 같습니다.
1. 자켓
2. 바지
3. 스커트
4. 원피스
5. 코트
6. 조끼
7. 셔츠
8. 블라우스
9. 타이
10. 벨트
11. 구두
12. 기타

품목이 없는 경우 아래의 의류가 나타나는 방식으로 요청드립니다.

**Comment by aanoaa** [comment]
``` perl
my @details = $order->order_details;
for my $detail (sort foo @details) {
  ...
}
```

DBIx::Class 에서 이런 방식은 동작하지 않습니다.
order_by 구문을 써서 해결해야 할 듯 싶습니다.

**Comment by aanoaa** [comment]
알파벳순도 아니고, 카테고리마다 가중치를 두면 쉽게 해결할 수 있겠지만 그것 때문에 스키마
변경하기가 꺼려집니다.

**Comment by 10001if** [comment]
@aanoaa 이유는 잘 모르겠지만 진행이 어렵다 싶으면 말씀해주세요~

**Comment by aanoaa** [comment]
주문상세 데이터가 보여집니다.
현재는 id 별로 정렬되어 있는데 이는 입력된 순서대로 입니다.

에누리, 연체료, 배송비, 연장료 등 의류코드가 없는 값들도 보여져야 합니다.

의류먼저 요청하신대로 정렬해서 보여주고 이후에 나머지 금액들을 보여줘야 합니다.

**Comment by aanoaa** [comment]
적용 시켰는데 소계가 `0`으로 나온다고 합니다.
어떠한 경우인지 추적해보고 수정하겠습니다.

**Comment by aanoaa** [comment]
제 PC 에서는 제대로 동작합니다.
무슨문제지..

**Comment by aanoaa** [comment]
javascript 가 문제인가 싶어서 5층에 올라서 페이지 새로고침도 해보고 브라우저도 바꿔서 봤는데 아니됩니다.
제 PC 에서는 되고요.

재현을 해야 수정할 수 있는데 난감합니다.

**Comment by aanoaa** [comment]
monitor 와 연동시키니까 0원으로 나옵니다.
재현되었습니다.

**Comment by aanoaa** [comment]
오타가 있었습니다.

`data-id-clothes`

`data-is-clothes` 여야 합니다.

오타때문에 의류가 아닌걸로 판단하고 js 에서 final_price 를 0 원으로 update 한겁니다.

**Comment by keedi** [comment]
정리된 이슈지만 참고삼아 기록합니다.

특정 카테고리 별로 정렬해달라는 경우가 의외로 좀 있어서 번거롭지만 구현한 부분입니다. 스키마를 변경하는 것은 적절하지 않은 것 같고, 실제로도 열린옷장에서 요청이 오는 건들마다 조금씩 가중치가 달라서 모듈에 넣기도 어렵습니다. 그런 관계로 해당 정렬이 필요한 부분에서 가중치를 적용해서 처리하고 있습니다.

https://github.com/opencloset/opencloset/blob/d7ed05725eda4a870f689d1e90f32f1e104af4fb/lib/OpenCloset/Web/Controller/Order.pm#L839

**Comment by 10001if** [comment]
확인 하였습니다. 어려운 문제라고 들었는데 신경써서 처리해주셔서 감사합니다. ^^

**Comment by aanoaa** [comment]
결과를 재정렬 하기에 복잡하니까
애초에 넣을때에 정렬해서 넣는게 더 좋은 해결방법이 아닌가 싶습니다.

`order_detail` 에 의류목록이 들어갈때에 정해진 카테고리 순으로 넣으면 더 그레이스풀한 해결방법이라 생각됩니다.
