### ISSUE TITLE
미납 문자 내용 추가

### ISSUE THREAD

**Issue by MoDoLEE** [opencloset/opencloset#952]
`주문서` - `미납`탭 에서 `미납 문자 전송`을 눌렀을 경우 보내는 메세지를 수정합니다.

현재는

```
[열린옷장] 000님, 0일 연장으로 인한 미납 금액 0,000원 입금바랍니다. 국민은행 205737-04-003013
```

이지만

```
[열린옷장] 000님, x일 연장, y일 연체로 인한 추가 금액 00,000원 3일 내로 입금바랍니다. 미입금 시 추후 열린옷장 이용에 제한이 있을 수 있습니다. 국민은행 205737-04-003013 (예금주 : 사단법인열린옷장)
```

으로 변경되어야 합니다.

**Comment by aanoaa** [comment]
@10001if 내용이 조금 공격적이지 않나요?
의견 말씀해주세요.

**Comment by 10001if** [comment]
@aanoaa 내부 인원들과 논의를 해본 뒤 다시 말씀드릴게요. ^^

**Comment by yongbin** [comment]
개인적으로 저는 괜찮은거 같습니다. 김태양님건에서 본것 처럼 미납/연체건은 지연되버리면 양측다 손해가 막심하기때문에 정확하게 내용을 전달하는게 그 사람에게도 더 이득이라고 생각합니다.

**Comment by aanoaa** [comment]
막 실명 얘기하네(틀렸지만)

**Comment by yongbin** [comment]
-0- 깜빡했네요 수정했습니다.

**Comment by keedi** [comment]
예를 들어 서울시 공공 자전거 따릉이의 경우 대여한지 4시간이 넘으면 바로 도난신고가 경찰서에 접수된다고 합니다.
정리하자면 판단은 각자의 몫.

**Comment by 10001if** [comment]
```[열린옷장] 000님, x일 연장, y일 연체로 추가 금액 00,000원이 발생하였습니다. 금일 중으로 국민은행 205737-04-003013 (예금주 : 사단법인열린옷장)으로 입금해주세요.``` 문구 수정하였습니다. @aanoaa 본 내용으로 수정 요청드립니다.

**Comment by 10001if** [comment]
```
[열린옷장] 000님, x일 연장, y일 연체로 추가 금액 00,000원이 발생하였습니다. 금일 중으로 국민은행 205737-04-003013 (예금주 : 사단법인열린옷장)으로 입금해주세요. 000님 이름으로 입금되어야 확인이 가능합니다.
```

@aanoaa 문구 수정하였습니다. 본 내용으로 수정 요청드립니다.
