### ISSUE TITLE
의류 상태가 폐기일 경우 폐기장소, 폐기이유를 선택할 수 있도록 변경

### ISSUE THREAD

**Issue by MoDoLEE** [opencloset/opencloset#953]
현재는 폐기장소, 폐기이유를 직접 작성하고 있는데, dropdown 버튼으로 선택할 수 있도록 변경해주세요.

폐기장소 : 옷캔, 비백, 영구보관, 재활용 불가
폐기이유 : 손상 수선 불가, 오염 제거 불가, 변색, 사용하지 않는 스타일, 짝 잃음

**Comment by aanoaa** [comment]
#792 와 연관이 있습니다.
정해져 있기 때문에 직접 입력보다 선택해서 입력하는 것이 편리합니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^

**Comment by 10001if** [comment]
@aanoaa 폐기장소에 `영구보관`은 삭제 요청드립니다! 이것도 신속한 작업 요청드립니다. ^^
