### ISSUE TITLE
연장신청 성공 페이지에 문구 수정

### ISSUE THREAD

**Issue by MoDoLEE** [opencloset/opencloset#954]
현재
연장을 통해 발생한 추가금액은 반납 이후, 문자로 연장금액과 계좌번호가 발송됩니다. 문자 정보에 따라 추가금액 입금을 진행해주세요. 감사합니다.

변경
연장을 통해 발생한 추가금액은 의류 반납 시 카드 또는 현금 결제하시면 됩니다. 택배 반납 시, 택배가 열린옷장에 도착하여 의류를 확인한 후 대여자님께 문자로 추가금액과 계좌번호를 안내해 드립니다. 문자 정보에 따라 추가금액 입금을 진행해 주세요. 감사합니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
