### ISSUE TITLE
불납을 완납으로 변경하는 기능

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#956]
나중에 완납할 수도 있습니다.
불납 목록을 추가하고, 완납으로 변경하는 기능이 필요합니다.

**Comment by aanoaa** [comment]
불납을 완납으로 바꾸려면 데이터를 바꾸어 주어야 합니다.

order_detail 의 stage 를 `불납(4)` 에서 `완납(5)` 로 바꾸어주고, `불납` 대신 `완납` 으로
업데이트 해주어야 합니다. price, final_price 를 미납금 총합으로 수정해주어야 합니다.

**Comment by aanoaa** [comment]
![screenshot-localhost 5001 2016-09-28 16-33-21](https://cloud.githubusercontent.com/assets/170528/18904517/5bb047dc-8599-11e6-8ced-3272582771fc.png)

**Comment by 10001if** [comment]
https://github.com/opencloset/opencloset/issues/955 이슈와 마찬가지로 불납자의 `불납`버튼을 누르면 불납 목록의 검색페이지로 이동하는 기능을 추가 요청드립니다. ^^

**Comment by aanoaa** [comment]
주문서 상세에서 `불납` 라벨에 대해 `미납`과 마찬가지로 링크를 달아주어야 합니다.

**Comment by 10001if** [comment]
@aanoaa 링크를 달아주시면 이슈를 닫을 수 있을 것 같습니다~ 요청드릴게요~ ^^

**Comment by 10001if** [comment]
@aanoaa https://github.com/opencloset/opencloset/issues/955 이슈와 마찬가지로 불납자의 불납버튼을 누르면 불납 목록의 검색페이지로 이동하는 기능을 추가 요청드립니다. 본 기능만 추가되면 큰 이슈는 없을 것으로 보입니다.

**Comment by 10001if** [comment]
> @aanoaa #955 이슈와 마찬가지로 불납자의 불납버튼을 누르면 불납 목록의 검색페이지로 이동하는 기능을 추가 요청드립니다. 본 기능만 추가되면 큰 이슈는 없을 것으로 보입니다.

@aanoaa 이것 하나만 처리해 주시면 됩니다. :)

**Comment by aanoaa** [comment]
#1277 에서 해결되었습니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
