### ISSUE TITLE
정장 반납 안내 및 대여 메세지 작성 종이를 프린터로 출력

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#958]
5층에서 결제 종료 후 제공하는 정장반납 안내지에는 다음과 같은 내용이 들어가 있습니다.
1. 정장 반납 안내
   1) 방문 반납
   2) 택배 반납
   3) 기간 연장
2. 배상규정 안내
   1) 대여기간 연장
   2) 대여의류 손상
   3) 대여기간 연쳬
   4) 대여의류 분실
3. 서비스 피드백란
4. 나의 정장 대여 이야기 (대여 메세지란)

현재는 위 내용에 추가로 `대여자 이름`, `대여일`, `반납일`, `주문서번호`, `기증자들의 이름`을 사람이 수기로 작성하고 있습니다. 하지만 수기 작성으로 소요되는 시간을 줄이고 잘못 작성하는 오류를 줄이기 위해 프린터 출력으로 대체하려고 합니다. 

프린터 출력이 가능하도록 요청드립니다. 관련하여 실제 반납안내지는 제공해 드리도록 하겠습니다.

**Comment by keedi** [comment]
진행하려면 사전에 프린터가 필요합니다. 프린터를 구매하게 되면 해당 프린터를 옆에 두고 실제로 출력해가며 테스트해야 할 것으로 보입니다. 우선 프린터 구매를 진행하신 다음 알려주세요~ 가능하면 리눅스를 지원하는 프린터여야 하며, 네트워크 기능이 있으면 좋고(옵션이지만 있는것이 유리할 것으로 사료), 더불어 칼라 양면 인쇄가 필히 들어가야 합니다. 마지막으로 리필이 된다면 운영비 절감에 도움이 되겠지요.

**Comment by 10001if** [comment]
- 제품명 : HP 컬러 레이저젯 프로 복합기 M277dw 
- 상세 스펙 : http://www8.hp.com/kr/ko/products/printers/product-detail.html?oid=6782853#!tab=specs HP 사이트에 사양이 적혀 있습니다.
- 체크사항 : 1. 리눅스를 지원 2. 네트워크 기능 있음 3. 칼라 양면 인쇄 가능 4. 리필이 됨

@keedi 오늘 구매하였습니다. 프린터가 도착하면 다시 말씀드리도록 하겠습니다.

**Comment by keedi** [comment]
프린터가 도착했습니다. 프린터 설치 후 작업 진행합니다.

**Comment by keedi** [comment]
급한 이슈라고 합니다. 우선 순위를 높입니다.

**Comment by keedi** [comment]
진행합니다.

**Comment by keedi** [comment]
화요일 기준으로 세세한 문구 수정 완료했습니다. 목요일 부터 적용할 수 있도록 수요일 마감 후 서버에 적용할 예정입니다.

**Comment by keedi** [comment]
실제 테스트로 문자를 전송했을 때 보이는 화면은 다음과 같습니다.

![screenshot_2016-11-02-14-32-41](https://cloud.githubusercontent.com/assets/138451/19917791/a0c6d3fa-a109-11e6-9bf7-2733efbc5af8.png)

**Comment by keedi** [comment]
작업 완료했으므로 이슈 닫습니다.

**Comment by keedi** [comment]
윽 죄송합니다. 이슈를 잘못 적었습니다.

**Comment by keedi** [comment]
사실 이 이슈의 경우 어떻게 해야 최적의 방법일지 아이디어는 없습니다. 의류 태그 출력과 비슷하게 진행할지 또는 별도의 네이티브 앱을 만들지 또는 최대한 브라우저의 출력을 이용할지 고민입니다. 브라우저의 출력을 그대로 이용할 경우 제일 공수가 적긴하지만 원하는 위치에 원하는 결과물을 출력해야 하는 상황상 브라우저와 운영체제 프린터 드라이버의 영향을 너무 많이 받습니다.

**Comment by keedi** [comment]
의류 태그 출력 방식을 응용할 경우 기존 작업물을 다시 활용할 수 있다는 점은 장점이나 현재 #947 에서 발생하고 있는 이슈를 확인한 후 같이 해결해야 합니다.

**Comment by keedi** [comment]
대신 예전에 이용하던 libreoffice와 템플릿을 이용해 pdf 변환 기능을 구현한 적이 있었는데 그 기법을 사용할 수도 있을 것 같습니다. 이 경우 단점으로는 서버측에서 libreoffice를 구동시킬 수 있는 장비를 설정하고 운영해야 한다는 점입니다.

**Comment by keedi** [comment]
네이티브 앱은 최대한 고려하지 않을 예정입니다.

**Comment by keedi** [comment]
기존 의류 태그 이슈와 동일하게 pdfmake 라이브러리를 이용하고 있습니다.

픽셀 노가다를 통해 최종적으로 출력해낸 결과물은 다음과 같습니다.

앞면 입니다.

![r1018764](https://cloud.githubusercontent.com/assets/138451/19999700/3b2d316a-a2b7-11e6-9fad-13a7cb879fe2.JPG)

뒷면 입니다.

![r1018765](https://cloud.githubusercontent.com/assets/138451/19999709/463c4334-a2b7-11e6-83de-ed017a7f9a30.JPG)

출력 환경은 다음과 같습니다.

- HP Color LaserJet Pro MFP M277dw
- 유선 연결
- Linux bebop-i5 4.8.0-1-amd64 #1 SMP Debian 4.8.5-1 (2016-10-28) x86_64 GNU/Linux
- 문서보기 Evince 3.22.1
- 칼라, A5, 양면 긴 방향 표준, 광택 중량지 111-130g, 용지함 2, 세로

**Comment by keedi** [comment]
샘플 출력까지 성공했으니 소스 코드에 반영하고 실제 열린옷장 환경에서 제대로 출력되는지 테스트를 진행해야 합니다.

**Comment by keedi** [comment]
다음주 금요일까지 끝내서 서버에 적용되었으면 좋겠다고 합니다.

**Comment by keedi** [comment]
피드백을 받았습니다. 출력 형식을 다시 변경한다고 합니다. 내일 새로운 출력 형식을 맡기고 수요일에 인쇄 완료되면 수요일에 나오는 출력본 기준으로 다시 작업 진행합니다. 토요일에 적용을 원하기 때문에 데드라인은 금요일 저녁입니다.

**Comment by keedi** [comment]
변경된 출력 형식으로 진행된 내역은 다음과 같습니다.

앞면입니다.
![imgp7404](https://cloud.githubusercontent.com/assets/138451/20096545/b39a9d02-a5ed-11e6-83f0-ac1bad6e707d.JPG)

뒷면입니다.
![imgp7405](https://cloud.githubusercontent.com/assets/138451/20096548/b74b570c-a5ed-11e6-8e4e-fdf06312e308.JPG)

내일 피드백을 받은 후 수정 여부를 결정하겠습니다. 아마도 기증자를 알려드립니다 섹션이 변경될 것으로 예상됩니다.

**Comment by keedi** [comment]
이유는 알 수 없지만 리눅스 쪽에서 양면 프린팅에 문제가 좀 있습니다. 분명히 양면 인쇄 옵션으로 양면 인쇄를 시도하고 있고 프린터도 양면을 인쇄하는 시늉을 하지만 막상 출력 결과물을 보면 뒷면이 인쇄가 안되고 있는 현상입니다. 관련해서 문제를 해결하고는 싶으나 진행 사항과 직접적인 연관은 없기 때문에 윈도우 가상 머신에서 테스트 중입니다. 다행히 윈도우 가상 머신에서는 정상 동작합니다. 한편으로는 실제 사용할 환경은 윈도우긴 합니다.

**Comment by keedi** [comment]
기증자 이름 목록을 각 줄로 나누어 배치하기로 했으며 글자를 현행 대비 80% 이하로 줄이기로 했으며 관련해서 피드백 적용 완료했습니다.

**Comment by keedi** [comment]
더불어 1면에 날짜를 표시할 때 요일을 추가적으로 표시하도록 했습니다.

**Comment by keedi** [comment]
작업 완료했으므로 이슈 닫습니다.

**Comment by keedi** [comment]
아직 대기자가 있는데 대여자가 모두 나가고 나면 서버에 배포 및 프린터 설치 예정입니다.

**Comment by keedi** [comment]
출력 버튼의 위치는 다음과 같습니다.

![screenshot-monster silex kr 10301 2016-11-09 18-22-37](https://cloud.githubusercontent.com/assets/138451/20133128/94845b26-a6a9-11e6-8b96-ecd756b60e98.png)
