### ISSUE TITLE
대여탭에서의 대여희망품목 수정

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#960]
대여탭에서 대여희망품목을 토글해서 추가/삭제 하고 싶다

**Comment by aanoaa** [comment]
![screenshot-localhost 5001 2016-09-30 17-02-11](https://cloud.githubusercontent.com/assets/170528/18984822/b19a45de-872f-11e6-9aea-72ef55b20cfb.png)

**Comment by aanoaa** [comment]
품목의 합계수량을 표시했으면 합니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
