### ISSUE TITLE
비밀번호와 승인번호를 구분

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#963]
https://github.com/opencloset/OpenCloset-Share-Web/issues/6

온라인 서비스가 개시된다면 사용자는 인증번호가 아닌 비밀번호로 서비스를 이용하게 됩니다.
비밀번호가 있는 사용자들이 인증번호를 받게되면 비밀번호가 변경되므로, 인증번호가 아닌
비밀번호로 로그인 할 수 있도록 변경해야 합니다.

온라인 서비스 개시 이후에 바뀌어야 합니다.

**Comment by aanoaa** [comment]
staff 이 아닌 사용자는 방문예약은 할 수 있지만, 로그인은 할 수 없습니다.
그렇다고 아무나 재고관리를 사용해서는 아니됩니다.

email 과 비밀번호가 일치하면 인증은 통과하도록 하고, 재고관리에서 staff 인지 아닌지를
확인하는 절차를 거치면 되지 않을까 싶습니다.

**Comment by aanoaa** [comment]
donation 역시 staff 만 사용가능하도록 변경해야 합니다.

https://github.com/opencloset/donation/commit/d2398ef8c68ece1257afb3150336bb0e79c74693

**Comment by aanoaa** [comment]
다른 서비스에서 로그인 활용을 위한 작업이었습니다.
비밀번호로 방문예약을 하는 것과는 다르기에 다시 열었습니다.

**Comment by aanoaa** [comment]
제 아이디어는 이렇습니다.

방문예약은 승인번호를 비밀번호로 사용하고 있는데,
비밀번호와 승인번호를 따로 저장해두면 해결되지 않을까 합니다.

> 방문예약을 비밀번호로도 사용가능하도록 변경

제목과는 다른 해결방안 입니다.

승인번호로 본인 확인을 하고 온라인으로 가입했을 경우에만 비밀번호를 설정해두는 겁니다.

그렇게 되면 staff 에 로그인할때에도 비밀번호가 변경되는 번거로움을 막을 수 있습니다.

**Comment by yongbin** [comment]
네 저도 스키마에서 승인번호와 비밀번호를 분리하는게 더 좋을거 같습니다.

**Comment by aanoaa** [comment]
승인번호를 입력하고 방문예약을 할때에 `방문 일자 선택` 을 누르면 

    GET /api/gui/booking-list.json?phone=01031820800&sms=452561&gender=male
    400 Bad request
    {"error":{"data":{"error":"sms is wrong"}}}

에러가 발생하면서 방문일을 선택할 수 없습니다.
