### ISSUE TITLE
방문자 통계에서 남녀 구분 자료 추가

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#971]
![_2016-10-10_ _4_30_18](https://cloud.githubusercontent.com/assets/4696328/19229766/f68c4e98-8f0a-11e6-90c1-bfefc314bc08.jpg)

통계에서 방문자 페이지를 보면 총 인원수는 나타나고 있으나 남/녀 구분이 되어 있지 않습니다.

남녀 비율이 대여 프로세스에서 어떤 영향을 미치고 있는지 검토하는 것이 필요합니다.

위 그림처럼 `월별 방문자`의 남녀 인원 체크의 추가를 요청드립니다.

다만 `일별 방문자`, `주별 방문자`에게도 적용하는 것이 바람직 한지는 논의를 통해 결정하려고 합니다. 

추가적으로 베스트 핏은 큰 의미가 없는 것으로 보여 페이지에서는 보이지 않도록 하려고 합니다.

**Comment by 10001if** [comment]
@yongbin 께서 해결해 주시는 게 좋을 것 같은데.. 바쁘신 것 같아 우선 @keedi 께 말씀드려 놓았습니다.

**Comment by yongbin** [comment]
넵 감사합니다. 필요한 부분있으면 지원하겠습니다.

**Comment by 10001if** [comment]
@yongbin BestFit이 중요하다면 통계에서 삭제하지 않도록 해야할 것 같은데요. 의견 주시면 그대로 따라가겠습니다.

**Comment by yongbin** [comment]
> @yongbin BestFit이 중요하다면 통계에서 삭제하지 않도록 해야할 것 같은데요. 의견 주시면 그대로 따라가겠습니다.

아 통계에서 Bestfit 컬럼을 보이지 않도록 삭제하는건과 재고관리에서 Bestfit 정보를 활용하는건 연관이 없어보입니다. 그냥 화면에서 불필요한 정보이면 삭제하셔도 상관없습니다.

**Comment by 10001if** [comment]
@yongbin 물론 컬럼 삭제와 정보 활용은 별개의 문제입니다. 하지만 베스트핏이 중요한 가치를 가진다면 이 정보를 얼마나 기록하고 있는지 매일 확인할 필요가 있습니다. 베스트핏을 얼마나 입력하는지 알지 못한다면, 베스트핏 입력에 대해 계속적으로 요청하기가 어렵기 때문입니다. 때문에 화면에서 필요하냐, 불필요하냐는 베스트핏의 중요도에 따라 달라집니다. 베스트핏이 가지는 가치에 대해 다시 이야기를 나누어 보았으면 합니다.

**Comment by yongbin** [comment]
아 그렇군요 그럼 제가 잘못 이해한거 같습니다. 베스트핏이 가지는 가치에 대해서는 저도 좀 더 고민해볼 필요가 있다고 생각합니다. 차주에 같이 말씀나눠보면 좋겠습니다.

**Comment by 10001if** [comment]
@yongbin 네~ 그럼 뵙고 말씀나누도록 하시죠~ ^^

**Comment by keedi** [comment]
제가 진행하겠습니다.

@10001if 관련해서 한번 정리해서 다시 이야기 나누시죠.

**Comment by keedi** [comment]
미팅 결과로 정리한 내용은 다음과 같습니다.

- 기존 어울림 정보는 제거하지 않고 그대로 둠
- 예약자, 방문자, 미방문자, BestFit, 대여자 항목 모두 남녀 구분 결과도 보여줌

**Comment by keedi** [comment]
진행합니다.

**Comment by keedi** [comment]
해당 요청은 `GET /stat/visitor/:ymd`이며 대응 컨트롤러는 `OpenCloset::Web::Controller::Statistic::visitor_ymd` 입니다.

**Comment by keedi** [comment]
@10001if 일별, 주별에 남녀 자료를 넣을지 말지 결정 부탁드립니다.

**Comment by keedi** [comment]
일별, 주별도 다 필요하다고 합니다.

**Comment by keedi** [comment]
#443 이슈로 1년 전 구현 이슈입니다. 다행히 당시 굳이 어짜피 값을 구하는 것 남녀 값도 따로 구하지 않을 이유가 없다고 판단했었기 때문에 요청은 없었지만 남녀 통계도 이미 구하는 방식으로 구현했고 캐싱하도록 했었습니다. 캐시에서 얻어온 다음 보여만 주면 됩니다.

**Comment by keedi** [comment]
구현 완료한 화면은 다음과 같습니다.

![screenshot-monster silex kr 10301 2016-11-25 14-45-07](https://cloud.githubusercontent.com/assets/138451/20615563/8f3b107a-b31e-11e6-97d3-fe405f0a9cca.png)

**Comment by keedi** [comment]
작업 완료했으므로 이슈 닫습니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
