### ISSUE TITLE
SMS 전송 업체인 API STORE의 결제 방식이 후불에서 선불로 바뀜

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#976]
후불에서 선불로 변경되었습니다.

관련해서 아래와 같은 안내가 있었습니다.

> ※ API 추가 코드 활용 가이드
> - 해당 에러코드는 발송 및 잔액 정산에 소요되는 시간차를 고려한 잔액관리를 위한 조치 사항이므로 개발 부분에 필히 적용해야 합니다.
> - 에러 코드 업데이트: "result_code :600" | 선불제 충전요금 부족
> - 해당 내용 개발 참고는 첨부하여 드린 ‘대용량SMS서비스 API  사용자 가이드’ 의 각 유형별 API의 호출 반환값을 확인하면 됨.
>   (참고 페이지 6 page~10 page 내 각 result_code)

[대용량SMS서비스_사용자가이드_v2.2(0).pdf](http://trk.bizmailer.co.kr/tracker/mail/openCheck.do?method=click&sn=27&mk=1457943199997VSIJVWJ&lk=1476153020891&dk=D693422B718D204D60C0&ck=1476153182677cuhlB4J&ee=FHyM7ND0cDg9LTeBk7v4SYYcUb4KSdhhOoVhxPi5pHo=&nk=14761530208910000005&url=aHR0cDovL3d3dy5iaXptYWlsZXIuY28ua3IvYml6c21hcnQvbWFuYWdlci9kb3duLmRvP21ldGhvZD1saW5rJmZpbGVLZXk9MTQ3NTgyODYzMzU4Mkh5b2dpOTQ=&sd=1476153020000)

검토후에 서비스에 적용해야 한다면 적용해야 합니다.

**Comment by keedi** [comment]
후불에서 선불로 바뀌었기 때문에 예전 coolsms를 사용하던 시절처럼 충전된 금액 및 잔액을 확인하는 UI가 다시 필요할 것으로 보입니다. 관련해서 제가 처리하겠습니다.

**Comment by keedi** [comment]
상기 pdf 파일은 삭제되어 더이상 다운로드가 되지 않습니다.

**Comment by keedi** [comment]
@10001if 관련해서 행정적인 부분은 처리가 완료되셨는지요? 관련한 내용은 다음 링크에서 확인할 수 있습니다.

http://blog.apistore.co.kr/?p=306

**Comment by keedi** [comment]
![screenshot-blog apistore co kr 2016-11-14 17-49-23](https://cloud.githubusercontent.com/assets/138451/20258427/f4119ab2-aa92-11e6-87cb-904d585f445b.png)

**Comment by keedi** [comment]
미팅 후 확인 결과 정상적으로 계약 변경했다고 합니다.

**Comment by keedi** [comment]
가장 최신 버전 문서는 다음 링크에서 확인할 수 있습니다.

http://www.apistore.co.kr/api/apiProviderGuide.do?service_seq=151

**Comment by keedi** [comment]
( 쓸데없는 짓 하지말고 https나 지원하지... 혼잣말이었습니다...;;; )

**Comment by keedi** [comment]
본 작업을 처리하기 위해 총 3가지 문의를 남겨두었습니다.


----

> 안녕하세요.
> 
> 가장 최신 문서를 확인하고 있습니다.
> 
> 대용량SMS서비스_사용자가이드_v2.3.pdf 504.0 KB
> 
> 오류 코드의 4432와 4433 및 6628, 6629는 단순 오타인지
> 아니라면 그 차이를 명확히 설명 부탁드립니다.
> 
> 감사합니다.

----

> 안녕하세요.
> 
> apistore의 공식 문서를 참고해서 발신번호 등록 api쪽을 보고 있습니다.
> 관련해서 등록과 조회는 있는데 모호한 부분이 있어 문의 드립니다.
> 
> 1. 등록과 조회 api만 있는데 제거나 갱신 방법
> 2. 등록시 하나의 번호만 넣는데, 복수 번호를 넣는 방법
> 3. 이미 등록한 번호의 comment 수정 방법
> 4. 현재 5개 번호를 발신 번호로 등록했는데 api를 사용할 경우 추가가 되는 것인지 아니면 5개가 사라지며 하나의 번호로 수정되는지 여부
> 
> 감사합니다.

----

> 안녕하세요.
> 
> 후불에서 선불로 바뀌어 시스템에서 처리해야 할 부분이 늘어났습니다.
> 대표적으로 잔액 확인과 관련된 부분입니다.
> 대부분의 선불제 시스템은 잔액 확인 방법을 제공하는데
> apistore의 공식 문서를 참고해도 잔액 확인 방법이 보이지 않습니다.
> 
> 시스템적으로 특정 계정의 잔액을 확인할 수 있는 방법이 있다면
> 관련 문서나 링크를 알려주시면 감사하겠습니다.
> 
> 감사합니다.

**Comment by keedi** [comment]
응답을 받는대로 바로 마무리 짓겠습니다.

**Comment by keedi** [comment]
모듈 측 변경 사항은 다음 항목에서 처리합니다.

keedi/SMS-Send-KR-APIStore#2

**Comment by 10001if** [comment]
@keedi 혹시 관련해서 아직 이슈가 남았나요? 혹시 제가 확인해드려야 할 사항은 없는지요~?

**Comment by keedi** [comment]
[SMS::Send::KR::APIStore v0.003](https://metacpan.org/release/KEEDI/SMS-Send-KR-APIStore-0.003)을 방금 CPAN에 릴리스 했습니다. 관련해서 기존 코드 상에 당장 변경해야 될 부분은 없습니다.

**Comment by keedi** [comment]
추가된 API 관련해 APIStore와 나눈 대화를 정리하면 다음과 같습니다.

- 발신 번호 목록 조회가 가능하다.
- 발신 번호 등록이 가능하다.
- 발신 번호는 목록으로 관리한다.
- 단 목록 자체를 갱신할 수는 없고 끝에 계속 추가되는 방식이다.
- 기존 등록한 항목을 수정할 수 없다.
- 기존 등록한 항목 지울 수 없다.
- 지우거나 수정을 원할 경우 직접 메일로 문의해야 한다.
- **선불로 바뀌었지만 잔액을 확인하는 방법은 없다**. (패기보소...)

**Comment by keedi** [comment]
모듈의 새로운 릴리스에서는 `cid()`라는 메소드가 추가되었습니다. 사용법 예시는 다음과 같습니다.

cid를 등록할 경우는 두 개의 인자를 입력합니다.
첫 번째 인자는 전화번호이며, 두 번째 인자는 해당 번호에 대한 설명입니다.

```perl
# set caller id and its description
my $ret = $sender->cid( "0XXXXXXXXX", "Office #201" );
```

cid를 얻어올 때는 인자를 넣지 않습니다.
 
```perl
#
# get caller id list
#
my $ret = $sender->cid;
if ( $ret->{success} ) {
    my $cids = $ret->{number_list};
    my $idx = 0;
    for my $cid (@$cids) {
        say "$idx:";
        say "     client_id: " . $cid->{client_id};
        say "       comment: " . ( $cid->{comment} || q{} );
        say "    sendnumber: " . $cid->{sendnumber};
        ++$idx;
    }
}
else {
    say "failed to get cid info: $ret->{reason}"
}
```

**Comment by keedi** [comment]
> @keedi commented on 14 Nov 2016
> 
> 후불에서 선불로 바뀌었기 때문에 예전 coolsms를 사용하던 시절처럼 충전된 금액 및 잔액을 확인하는 UI가 다시 필요할 것으로 보입니다. 관련해서 제가 처리하겠습니다.

API에 없기 때문에 따로 처리할 방법이 없습니다.

**Comment by keedi** [comment]
서버에 릴리스 모듈 배포 및 서비스 재시작 완료했습니다. 잔액 확인 기능이 추가되지 않았기 때문에 체감할 수 있는 부분은 따로 없습니다. 다만 이후 발신자 번호 추가 요청이 올 경우 해당 `cid` api를 이용해 바로 추가가 가능합니다.

**Comment by keedi** [comment]
이슈 닫습니다.
