### ISSUE TITLE
주문서의 대여 메세지가 잘려서 보임

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#978]
주문서 번호 39958에서 이런 현상이 나타났습니다.

**Comment by keedi** [comment]
실제로 메시지를 길게 입력했지만 재고 관리 시스템에서는 한 줄로만 보이는 현상입니다. 더불어 해당 메시지를 클릭해서 수정하러 들어갔을때 역시 한 줄만 보입니다. 관련해서 원래 그랬는지, 아니면 언제부터 그랬는지 확인이 필요합니다.

**Comment by keedi** [comment]
일단 버그인지 아닌지 확인이 필요하지만 버그에 가깝다고 사료됩니다. 이런 일이 있었다면 지금까지 문제가 많았을텐데 좀 의아한 부분이 있습니다. 특정 입력에 따라 발생하는지 아니면 항상 발생하는지 등 면밀한 확인이 필요합니다.

**Comment by keedi** [comment]
진행합니다.

**Comment by keedi** [comment]
bootstrap editable 라이브러리를 이용해서 메시지를 출력하는데 이때 최초 화면에 보이게 할 때 html 속성 값으로 내용을 넣는데 이 값은 큰 따옴표를 이용해서 둘러 쌉니다. 이 값 안에 큰 따옴표가 있어서 발생하는 현상으로 보입니다. 

![screenshot-monster silex kr 10301 2016-11-11 17-47-47](https://cloud.githubusercontent.com/assets/138451/20209306/0a3d2328-a837-11e6-8001-0860e37261ed.png)

**Comment by keedi** [comment]
관련해서 html 내부에 속성으로 값을 넣어 줄 때는 큰 따옴표를 `&quot;`로 치환해야 할 것 같습니다. 또한 대여 메시지 뿐만 아니라 유사한 부분은 모두 수정해야 합니다.

**Comment by keedi** [comment]
수정 완료했습니다.

문제가 있던 메시지가 제대로 출력되는 화면입니다.

![screenshot-monster silex kr 10301 2016-11-11 18-13-33](https://cloud.githubusercontent.com/assets/138451/20210046/ebed345e-a83a-11e6-8d42-33502b218e9a.png)

**Comment by keedi** [comment]
작업 완료했으므로 이슈 닫습니다. :)

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
