### ISSUE TITLE
시간표에서 대여 안함 주문서를 대여한 것으로 간주함

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#979]
유저번호 32159에서 이런 현상이 나타났습니다. 수정 부탁드립니다.

**Comment by keedi** [comment]
방문 후 대여하지 않고 간 주문서를 대여한 것으로 세는 현상입니다. 이 문제를 수정하지 않으면 3회 이상 할인에 영향을 미칠 수 있으므로 수정해야 합니다.

**Comment by keedi** [comment]
확인했습니다. 일단 3회 이상 방문인지 여부는 현재 주문서를 제외하고 2번 이상 방문했는지 체크를 해서 확인합니다. 2번 이상 방문했다면 이번 방문이 3번째이기 때문입니다. 상기 대여안함 주문서로 인해 방문 횟수가 올라가는 현상을 발견했는데 다행히 할인을 체크하는 부분은 해당 주문서가 반납을 제대로 한 주문서인지 확인을 합니다. 즉 로직은 다음과 같습니다.

```perl
    my $visited = 0;

    {
        my $orders                          = $order->user->orders;
        my $visited_without_coupon_order_rs = $orders->search(
            {
                status_id => $OpenCloset::Constants::Status::RETURNED,
                parent_id => undef,
                -and      => [
                    -or => [
                        {
                            "coupon.id"     => { "!=" => undef },
                            "coupon.status" => { "!=" => "used" },
                        },
                        {
                            "coupon.id" => undef,
                        },
                    ],
                ],
            },
            {
                join => [qw/ coupon /],
            },
        );

        $visited = $visited_without_coupon_order_rs->count;
    }
```

실제로 시간표에서는 대여한 횟수에 포함되는 것을 보면 기존 주문서의 상태를 체크하는 조건 부분이 없어서 발생한 것으로 보입니다. 할인 정보에는 영향을 미치진 않지만 시스템을 사용하는 사람 입장에서는 헷갈려서 실수할 여지가 있습니다. 시간표 쪽을 수정하도록 합니다.

**Comment by keedi** [comment]
실제 주문서의 할인에는 영향을 미치지는 않는 상태지만, 눈으로 보는 것과 실제 값이 달라 계속 헷갈리는 것 같습니다. 우선 처리합니다.

**Comment by keedi** [comment]
#102, #339 이슈와 상관이 있습니다. (2014-10-23 ~ 2015-01-13)

확인해보니 예전에는 대여해간(지금 원하는 방식) 주문서에 한해 횟수를 누적했다면, 당시 이 경우 빌려가지 않았어도 방문한적이 있는 사람도 방문한 것으로 해달라는 요청이 있어 변경했던 것입니다. 관련해서 @10001if 님께 알려드렸고 어찌 진행할지 확인을 구한 상태입니다.

피드백을 확인한 후 처리할지, 아니면 수정하지 않고 이슈를 닫을지 결정하겠습니다.

**Comment by keedi** [comment]
@10001if 상기 내용에 대해서 이야기를 나누었는데 최종 확인이 필요하다고 하셨던 걸로 기억합니다. 어찌 처리할지 최종 피드백 부탁드릴게요.

**Comment by keedi** [comment]
일단 본 이슈는 버그가 아닌 것으로 판명되었습니다. 버그 라벨 제거합니다.

**Comment by 10001if** [comment]
@keedi 시간표에서 대여안함 주문서를 대여한 것으로 간주하는 이유는 저희 요청이 있었기 때문이라는 것을 알았습니다. 그 뒤 확인해보니 대여하지 않아도 신체치수 기록이 남아 있는 등 재방문자의 경우에는 최초 방문자와 같은 프로세스가 적용되지 않도록 하는 것이 필요하다고 합니다. 따라서 기존의 `00회 대여`를 `00회 방문`으로 수정해 주시면 문제는 해결될 것으로 보입니다.

**Comment by keedi** [comment]
말씀 하신대로 다른 부분은 그대로 두고 **회 대여** 문구를 **회 방문** 으로 수정하겠습니다.

**Comment by keedi** [comment]
구현 완료한 화면입니다.

![screenshot-monster silex kr 10301 2016-11-11 20-54-41](https://cloud.githubusercontent.com/assets/138451/20214402/53956750-a851-11e6-9d5b-18f8f72e3d2b.png)

**Comment by keedi** [comment]
작업 완료했으므로 이슈 닫습니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
