### ISSUE TITLE
자켓, 코트, 원피스, 스커트, 타이, 블라우스의 바코드 생성 요청드립니다.

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#980]
자켓 1000개
코트 200개
원피스 200개
스커트 200개
타이 200개
블라우스 200개 입니다.

바코드 생성 요청드립니다.
https://github.com/opencloset/opencloset/issues/855 이슈를 보니 @yongbin 께서 해주시던 작업을 @aanoaa 께서 해주시는 걸로 보이는데 맞나요..? 
확실히 몰라 assignees 를 두분 모두에게 걸어놓도록 하겠습니다.

**Comment by aanoaa** [comment]
$ cat a.sh 
    #!/bin/sh
    ./script/generate_code.pl jacket 1000 --save > jacket.csv
    ./script/generate_code.pl coat 200 --save > coat.csv
    ./script/generate_code.pl onepiece 200 --save > onepiece.csv
    ./script/generate_code.pl skirt 200 --save > skirt.csv
    ./script/generate_code.pl tie 200 --save > tie.csv
    ./script/generate_code.pl blouse 200 --save > blouse.csv
    $ ./a.sh 
    -------------------------------------------------
    '-']/ jacket 의류코드가 갱신되었습니다 => J4S9
    -------------------------------------------------
    '-']/ coat 의류코드가 갱신되었습니다 => C0CK
    -------------------------------------------------
    '-']/ onepiece 의류코드가 갱신되었습니다 => O0DJ
    -------------------------------------------------
    '-']/ skirt 의류코드가 갱신되었습니다 => K1F6
    -------------------------------------------------
    '-']/ tie 의류코드가 갱신되었습니다 => T1PS
    -------------------------------------------------
    '-']/ blouse 의류코드가 갱신되었습니다 => B13B

**Comment by aanoaa** [comment]
[blouse.xlsx](https://github.com/opencloset/opencloset/files/532544/blouse.xlsx)
[coat.xlsx](https://github.com/opencloset/opencloset/files/532546/coat.xlsx)
[jacket.xlsx](https://github.com/opencloset/opencloset/files/532545/jacket.xlsx)
[onepiece.xlsx](https://github.com/opencloset/opencloset/files/532548/onepiece.xlsx)
[skirt.xlsx](https://github.com/opencloset/opencloset/files/532549/skirt.xlsx)
[tie.xlsx](https://github.com/opencloset/opencloset/files/532547/tie.xlsx)

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
