### ISSUE TITLE
의류준비탭에서 사용자 화면 바로가기

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#984]

**Comment by keedi** [comment]
@aanoaa 모니터 이슈인가요? 재고 관리 이슈인가요? 모니터 이슈라면 본 이슈는 닫는 것이 좋을 것 같습니다. 더불어 재고관리의 이슈가 아니라면 마일스톤도 제거하고 invalid 라벨이 필요합니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
