### ISSUE TITLE
의류준비탭에서 추천결과와 신체치수를 수정

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#985]

**Comment by yongbin** [comment]
https://github.com/opencloset/monitor/issues/130

**Comment by keedi** [comment]
@yongbin 모니터 이슈인가요? 재고 관리 이슈인가요? 모니터 이슈라면 본 이슈는 닫는 것이 좋을 것 같습니다. 더불어 재고관리의 이슈가 아니라면 마일스톤도 제거하고 invalid 라벨이 필요합니다.

**Comment by yongbin** [comment]
모니터와 검색이 섞여 있는 이슈입니다. 깃헙이 저장소당 이슈를 제공하다보니까 프로젝트 전체 이슈를 관리하기가 어려워서 이곳(opencloset/opencloset)을 프로젝트 이슈처럼 쓰고 저장소별 이슈를 참조하는 방식을 쓰고있습니다. 관련해서 규칙을 정했으면 좋겠습니다.

**Comment by 10001if** [comment]
추천결과와 신체치수를 수정하고자 하였으나, 현재시점에서 다시 고려해 보았을 때 현실적으로 필요한 이슈가 아니라고 판단됩니다. 이슈 닫도록 하겠습니다.
