### ISSUE TITLE
주문서 할인 정보의 가독성을 높임

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#989]
@keedi 이용을 하다보니, 하단에 보여지는 정보에 대해 헷갈려하는 사람이 많아, 재요청드리고자 합니다.

현재 총액, 할인금액을
`기존 총액`, `할인금액`, `최종 대여료`으로 표시해주시길 요청드립니다.
`기존 총액 - 할인금액 = 최종대여료` 입니다.

그리고 지불받아야 하는 최종 금액인`최종 대여료`는 강조된 표시로 결제자가 다른 금액과 혼동하지 않도록 배경색 or 글씨색 등으로 다르게 노출될 수 있도록 수정 요청드립니다.

**Comment by keedi** [comment]
ᅟ#946 에서 파생된 이슈입니다.

**Comment by keedi** [comment]
간단하므로 오늘 처리합니다.

**Comment by keedi** [comment]
구현 완료한 화면은 다음과 같습니다.

![screenshot-staff theopencloset net local 10301 2016-10-24 18-14-26](https://cloud.githubusercontent.com/assets/138451/19640413/84aac42c-9a17-11e6-8f50-a860c91bbcfe.png)

**Comment by keedi** [comment]
피드백 받았으며 문제 없다고 합니다.
작업 완료했으므로 이슈 닫습니다.

**Comment by keedi** [comment]
배포 완료 되었습니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
