### ISSUE TITLE
예약 화면에서 주문서의 예약시간을 변경

### ISSUE THREAD

**Issue by aanoaa** [opencloset/opencloset#996]
편리하게 바꿀 수 있으면 좋겠다고 합니다.

**Comment by 10001if** [comment]
필요한 기능으로 보여지지만, 어느정도 필요한지, 어떻게 하는게 좋을지 명확하게 정리되지 않았습니다. 확인 후 다시 말씀드리겠습니다.

**Comment by keedi** [comment]
구현 요구 조건은 다음과 같습니다.

- 예약 시간 변경은 당일에 한함
- 현 시점 기준 지나간 시간의 예약 시간은 선택할 수 없음
- 슬롯에 여유가 있는 경우에 한해 변경할 수 있도록 함

**Comment by keedi** [comment]
내용 확인 했습니다. 진행합니다.

**Comment by keedi** [comment]
현재 예약 화면에서 특정 사용자를 마우스 왼 클릭하면 팝업 메뉴가 뜹니다. 이 메뉴는 다음처럼 보입니다.

![booking](https://cloud.githubusercontent.com/assets/138451/22763830/7378ce46-eeaa-11e6-93c4-a68efd4f6645.png)

상기 요구 조건을 고려하면 당일 현재 시점 이후 사용 가능한 예약 시간에 한해 선택하므로 후보로 보이는 예약 시간은 최대 25개이며, 열린옷장의 현재 예약 받는 상태를 고려(실제로 사용중인 예약 시간대)하면 절반인 12개로 보입니다. 12개 정도면 바로 팝업 메뉴에 일괄로 보이게 구현해도 크게 상관없을 것 같습니다.

**Comment by 10001if** [comment]
@keedi 네. 12개 정도라면 팝업 메뉴에 일괄로 보이게 구현해주셔도 무리가 없을 것 같네요. 기능 추가되면 4층에 전화로 예약 변경하는 분들이 많이 좋아하실 것 같습니다. ^^

**Comment by keedi** [comment]
구현한 화면은 다음과 같습니다.

![screenshot-monster silex kr 10301-2017-02-14-21-23-46](https://cloud.githubusercontent.com/assets/138451/22929021/bb0bb4e8-f2fc-11e6-8d5b-0ebc5ad48fc0.png)

**Comment by keedi** [comment]
예약 시간을 성공적으로 변경한 후 동적으로 사용자의 예약 위치를 옮겨주기에는 작업량이 많기 때문에 팝업들 띄워서 성공 여부를 알려준 후 자동으로 페이지를 새로 고치도록 구현되었습니다.

**Comment by keedi** [comment]
갈무리한 화면에도 알 수 있지만 현재 당일은 14일이지만 예약 화면은 15일을 띄웠고 이 때 팝업에서 보여주는 옮길 수 있는 예약 시간대는 모두 선택한 15일에 한정한 것입니다. 즉 본 기능은 예약한 당일 안에서만 시간 변경이 가능합니다.

**Comment by keedi** [comment]
작업 완료했으므로 이슈 닫습니다.

**Comment by keedi** [comment]
@10001if 테스트 서버에 배포했으니 테스트 서버에서  확인 부탁드립니다.

**Comment by 10001if** [comment]
@keedi 확인하였습니다. 기능은 요청드린 바로 잘 적용되었다고 생각합니다. 
다만, 당일 시간을 표시하는 것이므로 14:00 만 보여도 충분할 것 같습니다.
![2017-02-15 8 49 33](https://cloud.githubusercontent.com/assets/4696328/22954862/3dd59aa6-f35c-11e6-9147-c669c4417ec6.png)
혹시 날짜와 초 단위를 넣으신게 특별한 이유가 있는 게 아니라면, 그림에서 보는 것처럼 시간 만 표시되도록 수정 요청드립니다. ^^

**Comment by 10001if** [comment]
@keedi 그리고 예약시간을 변경했을 때 000님의 예약시간이 2017-02-17 15:00에서 16:00로 변경 완료되었습니다. 라는 확인 안내가 되었으면 좋겠습니다.

**Comment by keedi** [comment]
@10001if 실제 사이트에서 확인 하셨는지요? 선택이후 팝업이 뜰텐데 팝업을 못보셨는지요? 팝업이 뜬 이후 자동으로 새로고침을 하는데 이 이유는 자동 새로고침을 하지 않을 경우 동적으로 옮겨진 사용자를 표시하기 어렵기 때문입니다. 원하신다면 자동 새로고침 기능은 끌 수 있습니다만, 확인 안내를 보지 못하신 것 같아 여쭤봅니다.

**Comment by keedi** [comment]
@10001if 현재 보여지는 팝업 화면입니다.

![2017-02-15 18-29-14](https://cloud.githubusercontent.com/assets/138451/22968229/f1a61e98-f3ac-11e6-8d8d-862b55c38fa9.png)

자동 새로 고침 여부는 결정해서 알려주세요. 현재는 자동 새로고침입니다.

**Comment by aanoaa** [comment]
실섭에 배포하였습니다.

**Comment by keedi** [comment]
@10001if 

이슈 닫겠습니다. 릴리스 및 배포 완료되었으므로 관련 이슈 중 초 단위 제거 부분은 별도 이슈로 열어주세요. 더불어 확인 안내 관련은 다시 한번 확인해보시고 요구사항이 있다면 역시 별도 이슈로 열어주세요.

**Comment by 10001if** [comment]
@keedi 어제 테스트 페이지에서 확인할 때에는 별도의 안내창이 뜨지 않았는데, 다시 확인해 보니 안내창이 뜨네요. 확인했습니다. 추가 이슈 발생 시 이슈 다시 열어서 작성하도록 하겠습니다.
